In [1]:
!pip install soundfile librosa

Requirement already satisfied: soundfile in ./.miniconda3/lib/python3.13/site-packages (0.13.1)
Requirement already satisfied: librosa in ./.miniconda3/lib/python3.13/site-packages (0.11.0)
Requirement already satisfied: cffi>=1.0 in ./.miniconda3/lib/python3.13/site-packages (from soundfile) (2.0.0)
Requirement already satisfied: numpy in ./.miniconda3/lib/python3.13/site-packages (from soundfile) (2.4.4)
Requirement already satisfied: audioread>=2.1.9 in ./.miniconda3/lib/python3.13/site-packages (from librosa) (3.1.0)
Requirement already satisfied: numba>=0.51.0 in ./.miniconda3/lib/python3.13/site-packages (from librosa) (0.65.1)
Requirement already satisfied: scipy>=1.6.0 in ./.miniconda3/lib/python3.13/site-packages (from librosa) (1.17.1)
Requirement already satisfied: scikit-learn>=1.1.0 in ./.miniconda3/lib/python3.13/site-packages (from librosa) (1.8.0)
Requirement already satisfied: joblib>=1.0 in ./.miniconda3/lib/python3.13/site-packages (from librosa) (1.5.3)
Requirement already satisfied: decorator>=4.3.0 in ./.miniconda3/lib/python3.13/site-packages (from librosa) (5.2.1)
Requirement already satisfied: pooch>=1.1 in ./.miniconda3/lib/python3.13/site-packages (from librosa) (1.9.0)
Requirement already satisfied: soxr>=0.3.2 in ./.miniconda3/lib/python3.13/site-packages (from librosa) (1.1.0)
Requirement already satisfied: typing_extensions>=4.1.1 in ./.miniconda3/lib/python3.13/site-packages (from librosa) (4.15.0)
Requirement already satisfied: lazy_loader>=0.1 in ./.miniconda3/lib/python3.13/site-packages (from librosa) (0.5)
Requirement already satisfied: msgpack>=1.0 in ./.miniconda3/lib/python3.13/site-packages (from librosa) (1.1.1)
Requirement already satisfied: standard-aifc in ./.miniconda3/lib/python3.13/site-packages (from librosa) (3.13.0)
Requirement already satisfied: standard-sunau in ./.miniconda3/lib/python3.13/site-packages (from librosa) (3.13.0)
Requirement already satisfied: pycparser in ./.miniconda3/lib/python3.13/site-packages (from cffi>=1.0->soundfile) (2.23)
Requirement already satisfied: packaging in ./.miniconda3/lib/python3.13/site-packages (from lazy_loader>=0.1->librosa) (25.0)
Requirement already satisfied: llvmlite<0.48,>=0.47.0dev0 in ./.miniconda3/lib/python3.13/site-packages (from numba>=0.51.0->librosa) (0.47.0)
Requirement already satisfied: platformdirs>=2.5.0 in ./.miniconda3/lib/python3.13/site-packages (from pooch>=1.1->librosa) (4.5.0)
Requirement already satisfied: requests>=2.19.0 in ./.miniconda3/lib/python3.13/site-packages (from pooch>=1.1->librosa) (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in ./.miniconda3/lib/python3.13/site-packages (from requests>=2.19.0->pooch>=1.1->librosa) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in ./.miniconda3/lib/python3.13/site-packages (from requests>=2.19.0->pooch>=1.1->librosa) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./.miniconda3/lib/python3.13/site-packages (from requests>=2.19.0->pooch>=1.1->librosa) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in ./.miniconda3/lib/python3.13/site-packages (from requests>=2.19.0->pooch>=1.1->librosa) (2026.1.4)
Requirement already satisfied: threadpoolctl>=3.2.0 in ./.miniconda3/lib/python3.13/site-packages (from scikit-learn>=1.1.0->librosa) (3.6.0)

Requirement already satisfied: standard-chunk in ./.miniconda3/lib/python3.13/site-packages (from standard-aifc->librosa) (3.13.0)
Requirement already satisfied: audioop-lts in ./.miniconda3/lib/python3.13/site-packages (from standard-aifc->librosa) (0.2.2)

In [2]:
# On nettoie tout ce qui a pu être installé à moitié
!pip uninstall -y torch torchvision torchaudio torchcodec

# On installe la version CUDA 12.4 (parfaitement compatible avec votre machine et Python 3.13)
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124

# On remet torchcodec
!pip install torchcodec

Found existing installation: torch 2.6.0+cu124

Uninstalling torch-2.6.0+cu124:

  Successfully uninstalled torch-2.6.0+cu124

Found existing installation: torchvision 0.21.0+cu124

Uninstalling torchvision-0.21.0+cu124:
  Successfully uninstalled torchvision-0.21.0+cu124

Found existing installation: torchaudio 2.6.0+cu124

Uninstalling torchaudio-2.6.0+cu124:
  Successfully uninstalled torchaudio-2.6.0+cu124

Found existing installation: torchcodec 0.11.1
Uninstalling torchcodec-0.11.1:
  Successfully uninstalled torchcodec-0.11.1

Looking in indexes: https://download.pytorch.org/whl/cu124

Collecting torch
  Using cached torch-2.6.0%2Bcu124-cp313-cp313-linux_x86_64.whl.metadata (28 kB)

Collecting torchvision
  Using cached torchvision-0.21.0%2Bcu124-cp313-cp313-linux_x86_64.whl.metadata (6.1 kB)

Collecting torchaudio
  Using cached torchaudio-2.6.0%2Bcu124-cp313-cp313-linux_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: filelock in ./.miniconda3/lib/python3.13/site-packages (from torch) (3.29.0)
Requirement already satisfied: typing-extensions>=4.10.0 in ./.miniconda3/lib/python3.13/site-packages (from torch) (4.15.0)
Requirement already satisfied: networkx in ./.miniconda3/lib/python3.13/site-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in ./.miniconda3/lib/python3.13/site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec in ./.miniconda3/lib/python3.13/site-packages (from torch) (2026.4.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in ./.miniconda3/lib/python3.13/site-packages (from torch) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in ./.miniconda3/lib/python3.13/site-packages (from torch) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in ./.miniconda3/lib/python3.13/site-packages (from torch) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in ./.miniconda3/lib/python3.13/site-packages (from torch) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in ./.miniconda3/lib/python3.13/site-packages (from torch) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in ./.miniconda3/lib/python3.13/site-packages (from torch) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in ./.miniconda3/lib/python3.13/site-packages (from torch) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in ./.miniconda3/lib/python3.13/site-packages (from torch) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in ./.miniconda3/lib/python3.13/site-packages (from torch) (12.3.1.170)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in ./.miniconda3/lib/python3.13/site-packages (from torch) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in ./.miniconda3/lib/python3.13/site-packages (from torch) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in ./.miniconda3/lib/python3.13/site-packages (from torch) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in ./.miniconda3/lib/python3.13/site-packages (from torch) (12.4.127)
Requirement already satisfied: triton==3.2.0 in ./.miniconda3/lib/python3.13/site-packages (from torch) (3.2.0)
Requirement already satisfied: setuptools in ./.miniconda3/lib/python3.13/site-packages (from torch) (80.10.2)
Requirement already satisfied: sympy==1.13.1 in ./.miniconda3/lib/python3.13/site-packages (from torch) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in ./.miniconda3/lib/python3.13/site-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: numpy in ./.miniconda3/lib/python3.13/site-packages (from torchvision) (2.4.4)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in ./.miniconda3/lib/python3.13/site-packages (from torchvision) (12.2.0)

Requirement already satisfied: MarkupSafe>=2.0 in ./.miniconda3/lib/python3.13/site-packages (from jinja2->torch) (3.0.3)
Using cached torch-2.6.0%2Bcu124-cp313-cp313-linux_x86_64.whl (768.4 MB)

Using cached torchvision-0.21.0%2Bcu124-cp313-cp313-linux_x86_64.whl (7.3 MB)
Using cached torchaudio-2.6.0%2Bcu124-cp313-cp313-linux_x86_64.whl (3.4 MB)

Installing collected packages: torch, torchvision, torchaudio

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/3 [torch]

   ━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/3 [torchvision]

   ━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/3 [torchvision]

   ━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/3 [torchvision]

   ━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/3 [torchvision]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [torchaudio]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [torchaudio]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [torchaudio]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [torchaudio]

Successfully installed torch-2.6.0+cu124 torchaudio-2.6.0+cu124 torchvision-0.21.0+cu124

Collecting torchcodec
  Using cached torchcodec-0.11.1-cp313-cp313-manylinux_2_28_x86_64.whl.metadata (11 kB)
Using cached torchcodec-0.11.1-cp313-cp313-manylinux_2_28_x86_64.whl (2.3 MB)

Installing collected packages: torchcodec

Successfully installed torchcodec-0.11.1

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import soundfile as sf
import torch
import librosa
import librosa.display
from tqdm.auto import tqdm

In [4]:
!nvidia-smi

Sat May  9 23:52:15 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.90.07              Driver Version: 550.90.07      CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|

|   0  Tesla V100S-PCIE-32GB          On  |   00000000:00:07.0 Off |                    0 |
| N/A   35C    P0             26W /  250W |       1MiB /  32768MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [5]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

2.6.0+cu124
True

Tesla V100S-PCIE-32GB

In [9]:
!unzip DiffWave_Project.zip

Archive:  DiffWave_Project.zip

  inflating: DiffWave_Project/data_preprocessed/mels/12733.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12726.npy
  inflating: DiffWave_Project/data_preprocessed/summary.json
  inflating: DiffWave_Project/data_preprocessed/mels/12741.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12734.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12725.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12728.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12736.npy
  inflating: DiffWave_Project/data_preprocessed/test.csv

  inflating: DiffWave_Project/data_preprocessed/mels/12720.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12730.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12723.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12739.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12724.npy
  inflating: DiffWave_Project/data_preprocessed/val.csv
  inflating: DiffWave_Project/data_preprocessed/mels/12737.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12718.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12719.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12729.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12731.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12738.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12742.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12740.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12722.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12727.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12732.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12735.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12721.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12717.npy
  inflating: DiffWave_Project/data_preprocessed/eda_male.png
  inflating: DiffWave_Project/data_preprocessed/sample_mels_per_speaker.png
  inflating: DiffWave_Project/data_preprocessed/train.csv
  inflating: DiffWave_Project/data_preprocessed/mels/12715.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12701.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12710.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12693.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12709.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12708.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12687.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12692.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12697.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12712.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12702.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12703.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12700.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12707.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12699.npy

  inflating: DiffWave_Project/data_preprocessed/mels/12690.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12711.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12714.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12713.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12689.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12698.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12691.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12706.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12694.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12696.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12704.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12695.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12686.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12705.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12688.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12685.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12716.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12675.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12658.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12683.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12677.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12682.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12679.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12684.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12680.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12665.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12674.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12678.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12671.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12656.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12668.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12664.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12667.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12681.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12669.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12660.npy

  inflating: DiffWave_Project/data_preprocessed/mels/12653.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12666.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12662.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12673.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12672.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12661.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12663.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12659.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12676.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12657.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12654.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12655.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12670.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12652.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12651.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12640.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12648.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12642.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12646.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12635.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12644.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12645.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12649.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12638.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12639.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12641.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12643.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12636.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12629.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12637.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12627.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12634.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12647.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12625.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12631.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12628.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12632.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12650.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12630.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12626.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12624.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12623.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12621.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12633.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12622.npy

  inflating: DiffWave_Project/data_preprocessed/mels/12619.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12620.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12608.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12618.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12609.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12610.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12611.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12616.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12605.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12612.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12607.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12600.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12594.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12601.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12613.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12604.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12599.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12596.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12615.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12603.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12595.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12614.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12597.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12602.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12591.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12606.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12598.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12617.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12593.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12590.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12582.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12592.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12589.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12577.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12587.npy

  inflating: DiffWave_Project/data_preprocessed/mels/12573.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12568.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12566.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12586.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12564.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12571.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12574.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12572.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12562.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12583.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12575.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12585.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12569.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12584.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12588.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12567.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12578.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12576.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12563.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12580.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12570.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12565.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12558.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12581.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12579.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12559.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12561.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12556.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12560.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12553.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12554.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12552.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12557.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12546.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12543.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12549.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12548.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12550.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12531.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12545.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12542.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12539.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12533.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12536.npy

  inflating: DiffWave_Project/data_preprocessed/mels/12537.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12555.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12534.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12544.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12541.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12547.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12528.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12529.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12530.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12525.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12535.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12551.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12538.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12532.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12540.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12524.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12527.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12519.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12522.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12515.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12517.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12521.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12520.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12509.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12526.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12518.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12494.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12511.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12508.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12510.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12506.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12516.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12502.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12514.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12507.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12512.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12523.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12499.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12513.npy

  inflating: DiffWave_Project/data_preprocessed/mels/12500.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12496.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12505.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12501.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12503.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12495.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12737.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12498.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12739.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12504.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12742.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12741.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12734.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12736.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12738.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12493.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12730.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12732.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12726.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12722.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12740.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12728.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12733.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12727.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12723.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12714.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12735.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12724.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12731.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12718.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12719.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12717.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12721.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12710.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12713.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/12707.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12700.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12715.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12704.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12729.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12711.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12720.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12716.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12708.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12497.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12725.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12705.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12701.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12702.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12709.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12699.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12706.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12698.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12696.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12703.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12697.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12712.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12695.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12694.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12693.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12691.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12685.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12671.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12686.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/12688.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12687.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12681.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12673.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12679.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12689.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12683.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12664.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12675.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12690.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12672.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12668.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12692.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12678.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12680.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12665.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12666.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12667.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12674.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12682.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12676.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12677.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12669.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/12670.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12684.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12663.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12662.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12658.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12660.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12656.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12657.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12659.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12655.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12644.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12649.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12653.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12651.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12646.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12654.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12643.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12648.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12639.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12647.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12645.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12652.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/12641.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12640.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12638.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12661.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12650.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12635.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12636.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12637.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12642.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12632.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12633.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12631.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12624.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12630.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12622.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12614.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12626.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12619.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12628.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12629.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12623.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/12634.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12620.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12618.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12621.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12617.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12625.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12616.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12613.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12602.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12627.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12612.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12609.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12606.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12615.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12599.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12603.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12605.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12590.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12610.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12608.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12611.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12607.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12598.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12604.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12600.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/12589.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12587.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12593.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12594.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12601.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12595.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12584.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12579.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12596.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12597.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12592.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12583.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12585.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12591.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12581.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12572.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12588.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12580.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12574.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12576.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12569.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12568.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12578.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12577.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/12575.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12571.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12582.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12573.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12565.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12586.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12559.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12566.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12562.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12567.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12563.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12564.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12560.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12556.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12553.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12570.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12558.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12554.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12557.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12555.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12543.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12541.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12545.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12540.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12550.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12549.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/12552.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12544.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12542.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12548.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12561.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12410.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12551.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12539.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12409.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12547.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12546.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12405.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12367.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12407.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12537.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12538.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12403.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12406.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12366.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12408.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12536.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12404.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12402.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12249.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12364.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12327.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12365.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12531.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12247.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12535.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12322.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12362.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12286.npy

  inflating: DiffWave_Project/data_preprocessed/wavs/12322.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12467.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12534.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12248.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12323.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12532.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12325.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12328.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12401.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12324.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12533.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12285.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12466.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12326.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12400.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12530.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12400.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12284.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12246.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12363.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12365.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12399.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12364.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12323.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12283.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12319.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12359.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12401.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12363.npy

  inflating: DiffWave_Project/data_preprocessed/mels/12433.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12321.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12465.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12320.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12321.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12360.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12361.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12464.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12287.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12399.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12286.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12529.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12320.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12463.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12285.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12528.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12284.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12398.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12362.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12244.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12319.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12358.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/12442.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12318.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12245.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12283.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12282.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12318.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12527.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12497.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12462.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12432.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12361.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12397.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12441.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12360.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12431.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12281.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12398.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12282.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12396.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12397.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12357.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12243.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12251.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12317.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12317.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12440.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12250.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12248.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/12247.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12249.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12496.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12439.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12281.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12526.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12492.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12359.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12396.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12495.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12280.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12246.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12491.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12395.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12430.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12245.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12280.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12395.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12394.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12461.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12525.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12438.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12316.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12279.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12460.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12358.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12355.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12524.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12356.wav

  inflating: DiffWave_Project/data_preprocessed/mels/12215.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12213.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12315.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12214.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12208.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12316.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12243.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12279.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12216.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12212.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12211.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12244.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12210.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12315.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12429.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12209.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12459.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12314.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12436.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12494.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12354.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12394.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12437.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12356.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12278.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12490.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12242.npy

  inflating: DiffWave_Project/data_preprocessed/mels/12357.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12207.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12278.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12313.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12493.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12353.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12355.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12523.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12427.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12393.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12522.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12428.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12314.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12177.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12393.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12241.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12277.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12277.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12176.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12175.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12458.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12179.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12172.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12173.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12170.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12171.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12169.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12167.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12178.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12174.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12206.npy

  inflating: DiffWave_Project/data_preprocessed/wavs/12313.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12312.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12492.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12392.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12165.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12166.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12168.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12488.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12435.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12489.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12354.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12311.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12457.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12352.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12392.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12426.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12521.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12391.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12312.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12353.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12276.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12134.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12240.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12205.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12276.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12139.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12425.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12164.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12136.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12138.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12491.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12131.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12133.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12135.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12137.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12275.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12128.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12140.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12487.wav

  inflating: DiffWave_Project/data_preprocessed/mels/12132.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12130.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12456.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12127.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12490.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12239.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12129.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12390.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12352.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12424.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12391.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12204.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12434.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12351.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12390.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12486.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12101.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12092.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12093.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12520.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12275.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12310.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12519.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12100.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12311.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12099.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12274.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12097.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12163.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12098.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12096.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12094.npy

  inflating: DiffWave_Project/data_preprocessed/mels/12090.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12433.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12350.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12091.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12089.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12095.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12238.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12351.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12274.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12203.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12162.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12455.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12126.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12088.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12389.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12389.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12310.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12388.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12349.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12058.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12057.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12060.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12489.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12488.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12454.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12432.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12518.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12161.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12485.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12350.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12087.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12273.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12423.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12309.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12059.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12056.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12062.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12061.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12053.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12050.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12048.npy

  inflating: DiffWave_Project/data_preprocessed/mels/12051.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12309.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12484.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12308.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12046.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12054.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12047.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12055.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12045.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12052.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12202.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12273.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12422.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12463.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12125.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12237.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12272.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12431.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12385.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12387.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12388.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12049.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12024.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12517.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12086.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12483.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12386.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12453.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12023.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12201.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12124.npy

  inflating: DiffWave_Project/data_preprocessed/mels/12018.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12015.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12022.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12421.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12013.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12017.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12010.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12020.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12272.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12085.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12011.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12019.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12021.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12009.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12012.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12349.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12016.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12014.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12236.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12348.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12307.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12308.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12008.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12160.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12271.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12271.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12482.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12307.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12487.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12123.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12044.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12233.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12230.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12159.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12231.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12462.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12234.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/12235.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12223.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12228.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12384.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12225.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12348.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12229.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12236.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12224.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12270.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12232.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12347.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12387.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12226.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12452.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12222.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12347.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12516.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12430.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12227.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12007.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12200.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12306.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12515.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12043.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12201.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12420.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12084.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12486.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12195.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12235.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12270.npy

  inflating: DiffWave_Project/data_preprocessed/wavs/12196.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12189.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12122.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12194.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12451.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12197.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12461.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12200.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12305.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12306.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12199.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12184.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12198.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12190.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12192.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12180.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12193.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12386.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12269.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12187.wav

  inflating: DiffWave_Project/data_preprocessed/mels/12346.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12181.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12188.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12185.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12182.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12191.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12485.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12183.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12160.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12155.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12159.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12429.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12156.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12221.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12157.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12346.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12383.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12186.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12006.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12154.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12083.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12234.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12161.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12042.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12158.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/12153.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12179.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12514.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12198.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12199.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12480.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12041.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12152.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12151.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12481.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12428.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12385.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12121.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12419.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12460.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12158.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12484.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12268.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12382.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12220.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12269.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12131.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12305.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12130.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12450.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12345.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12344.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12129.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12120.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12128.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12115.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12124.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/12125.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12114.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12123.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12116.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12132.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12122.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12121.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12150.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12418.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12483.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12126.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12127.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12119.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12345.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12118.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12005.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12343.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12092.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12304.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12178.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12113.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12117.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12082.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12089.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12083.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12233.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12112.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12157.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12093.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12091.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12094.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12268.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12177.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/12077.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12087.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12304.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12082.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12084.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12090.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12088.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12085.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12086.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12232.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12078.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12195.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12080.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12079.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12479.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12427.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12120.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12111.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12081.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12513.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12040.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12381.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12004.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12303.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12080.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12051.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12081.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12267.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12459.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12219.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12055.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12048.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12076.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/12344.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12197.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12449.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12056.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12043.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12052.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12049.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12384.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12149.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12053.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12050.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12054.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12046.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12042.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12047.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12416.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12458.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12038.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12044.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12039.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/12041.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12383.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12045.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12156.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12417.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12037.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12040.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12512.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12343.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12267.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12266.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12218.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12302.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12016.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12015.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12010.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12019.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12303.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12036.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12342.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12012.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12011.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12448.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12482.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12006.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12008.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12478.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12002.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12018.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12017.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12014.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12013.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12009.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12196.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12003.npy

  inflating: DiffWave_Project/data_preprocessed/wavs/12005.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12007.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12001.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12380.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12003.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12075.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12176.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12074.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12155.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12079.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11999.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12039.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12426.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12119.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11984.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12110.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12000.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12004.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11980.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11979.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11970.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11983.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12148.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11977.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12194.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11982.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11981.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11966.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11962.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11968.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11978.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12266.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12035.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12231.npy

  inflating: DiffWave_Project/data_preprocessed/mels/11969.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11974.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11965.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11975.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11972.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12477.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11967.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11976.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12457.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12447.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11973.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12382.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12078.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12118.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11963.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11971.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12217.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11964.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11945.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11939.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11944.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11937.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11938.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12216.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11946.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12301.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11935.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11942.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11931.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11934.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11940.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11943.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11936.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12341.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12154.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11941.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12073.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11932.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11933.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12108.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/12511.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11929.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12425.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12342.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11930.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12302.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12193.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11910.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11960.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11914.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11909.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11904.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12481.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11913.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12147.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11928.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11907.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11911.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12265.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12379.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12002.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11906.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11900.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11908.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11897.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11901.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11912.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12175.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12109.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11961.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11998.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12230.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11905.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12034.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11894.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11902.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12415.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11899.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12038.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11895.npy

  inflating: DiffWave_Project/data_preprocessed/mels/11903.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11893.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12077.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11898.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12476.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12265.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11876.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11872.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11870.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11896.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11868.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12446.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11873.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11871.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11875.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11874.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11878.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11864.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11866.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11858.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11863.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11877.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11867.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11869.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11859.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12510.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12480.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12072.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11861.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12229.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11862.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12424.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11860.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12174.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12414.npy

  inflating: DiffWave_Project/data_preprocessed/mels/12381.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12001.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12117.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11865.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12192.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12215.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12153.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12340.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12378.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12037.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11838.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11843.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12341.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12033.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11836.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11827.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11839.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12076.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11841.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11834.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11842.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11826.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11837.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11831.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11828.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11821.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11829.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11823.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11824.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11830.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11835.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11825.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11840.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11822.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11833.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11819.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11817.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11832.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11818.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11997.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11892.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11820.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11857.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12300.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11959.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11927.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11801.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11794.npy

  inflating: DiffWave_Project/data_preprocessed/wavs/12301.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12264.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11799.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11816.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12107.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12456.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11798.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11791.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12146.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11797.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11800.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11796.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11785.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11792.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11783.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11780.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11786.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11795.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11784.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11787.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11793.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12445.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11781.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11802.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11788.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11790.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11789.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11782.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12455.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11779.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12036.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11996.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12380.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12299.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12264.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11926.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11760.npy

  inflating: DiffWave_Project/data_preprocessed/mels/11754.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12228.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12070.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11765.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12509.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12173.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11763.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11766.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11764.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11753.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11759.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11752.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11756.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11750.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11757.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11751.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11762.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11758.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12475.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11748.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12479.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12214.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11744.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11746.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11755.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11761.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11958.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11743.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12071.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11747.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11745.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11749.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12339.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12263.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11974.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12075.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11973.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12340.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12377.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12413.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11978.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11975.wav

  inflating: DiffWave_Project/data_preprocessed/mels/12000.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11980.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12423.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12191.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11972.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11976.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11969.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11970.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12116.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11962.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11963.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11964.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11966.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11977.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11967.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11957.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11971.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11955.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11968.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11979.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11960.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12152.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11956.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11961.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11965.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11992.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11935.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12032.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11941.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11954.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11958.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11940.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11778.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11815.npy

  inflating: DiffWave_Project/data_preprocessed/wavs/11937.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11856.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11936.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11938.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11959.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11939.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11925.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12106.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11934.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11933.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11930.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11931.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11953.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11926.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11891.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11929.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11928.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11932.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12145.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11922.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11919.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11918.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12035.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12474.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/11921.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12105.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11923.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11999.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12300.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11905.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12444.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12263.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11920.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11927.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11995.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11957.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11903.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12227.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12069.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11924.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12379.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11901.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11899.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11896.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11900.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12115.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11902.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11893.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11895.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11898.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11889.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11888.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12262.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11890.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11879.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12338.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11885.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/11865.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11891.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11894.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11897.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11881.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11887.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11880.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12213.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12422.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11883.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12172.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11884.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11882.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11892.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11886.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12074.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12478.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12412.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11859.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11862.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11854.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11864.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11904.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/11861.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11856.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11857.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11848.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11858.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11850.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11853.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11860.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11855.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12339.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11849.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11833.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11846.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11847.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11845.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11991.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11863.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12298.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11855.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11852.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12031.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12508.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11814.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12190.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11851.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11827.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11952.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11825.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11828.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11821.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12299.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11831.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11890.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11829.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12376.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11917.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/11832.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11830.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12297.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11844.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11826.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11819.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11777.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11822.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11813.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11810.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11823.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11817.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11816.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12144.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11818.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11824.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11812.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11815.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11811.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11799.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11814.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11878.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11998.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12212.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12507.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11798.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11797.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11793.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11794.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12151.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11820.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11792.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11783.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11795.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11791.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11779.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12454.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/12453.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11925.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11790.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11789.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11781.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11780.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11796.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11787.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11786.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11777.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11775.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11782.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11785.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11788.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12411.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12261.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12443.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12034.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11761.wav

  inflating: DiffWave_Project/data_preprocessed/mels/12378.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11762.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12262.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11763.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11755.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11760.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11749.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11753.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11778.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11764.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11759.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11776.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11784.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11757.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11750.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11754.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11758.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11751.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12298.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11747.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11746.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11889.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11990.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11756.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11743.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11748.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11742.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11813.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11752.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12150.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12073.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12068.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12337.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11730.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11745.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/11728.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12477.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11729.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11727.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11731.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12421.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11997.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11726.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12189.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12226.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12338.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11724.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11719.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11718.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11744.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12114.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12375.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11714.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11716.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11708.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11723.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11711.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11720.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11707.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11717.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11951.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11706.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11877.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11722.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11994.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11709.wav

  inflating: DiffWave_Project/data_preprocessed/mels/11956.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11712.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11690.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11703.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11687.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11721.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12296.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11715.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11705.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11710.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12473.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11691.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11713.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11702.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11686.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11704.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11683.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11809.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11689.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11682.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11681.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11725.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11685.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11680.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11679.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11675.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11669.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/11678.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11688.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11670.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11676.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11668.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11677.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11741.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11684.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11673.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12171.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11924.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11916.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11667.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11656.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11854.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11652.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11843.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11650.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11674.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11666.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11672.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11671.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12030.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11649.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11648.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11651.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11642.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11639.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11776.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11774.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11655.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11640.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11653.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11644.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11638.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11643.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11634.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11633.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/12210.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11654.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11641.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11632.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12113.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11635.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11647.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11645.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11620.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11773.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11646.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11614.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11615.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11613.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12033.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12104.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11637.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12143.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11808.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12377.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11619.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11618.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11636.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11612.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11616.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11605.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11602.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11622.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/11603.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11609.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11604.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11617.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11621.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11601.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11600.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11993.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11599.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11608.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11610.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11596.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11607.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11950.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11598.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11611.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11606.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12472.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11584.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12072.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11597.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12452.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12261.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11583.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11585.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12442.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12211.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11577.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11575.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11574.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11576.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11586.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11579.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/11876.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11578.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11853.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11570.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11569.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11581.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11572.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11580.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11564.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11567.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11573.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11571.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11542.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11561.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11568.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12410.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11566.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11546.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11541.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11582.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11915.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11565.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12029.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11562.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11547.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11996.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12188.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12476.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11548.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11536.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11563.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11535.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11537.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12419.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11531.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11529.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11812.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12112.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12260.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/11549.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12506.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11545.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11534.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11533.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11530.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11532.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11540.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11543.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12225.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11544.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11538.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11519.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11518.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11513.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11517.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11512.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11701.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11503.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11508.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11502.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12337.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12170.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11515.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11539.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11740.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11511.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11509.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11510.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11499.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/11504.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11888.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11496.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12336.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11923.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11501.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11498.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11500.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11505.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11514.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11506.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11507.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11516.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11497.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12297.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12374.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11595.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11955.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12067.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11665.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11727.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12295.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11495.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11726.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11733.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12149.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11775.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12420.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11494.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11842.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11631.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11725.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11734.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11732.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11720.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11724.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11719.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11731.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11730.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11728.npy

  inflating: DiffWave_Project/data_preprocessed/mels/11723.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11721.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11722.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11716.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11729.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11715.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11718.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11560.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11709.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11708.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12103.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11707.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11989.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11717.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11712.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11714.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11710.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11693.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11691.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11690.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11696.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11683.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11687.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11682.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11675.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11711.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11674.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11688.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11692.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11694.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11706.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11689.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11686.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11684.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11713.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11679.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11685.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11528.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11676.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11811.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11695.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11670.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11680.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11681.npy

  inflating: DiffWave_Project/data_preprocessed/mels/11673.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11669.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11671.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11672.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12260.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12373.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11700.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11678.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11914.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11739.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11988.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12142.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11650.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11660.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12376.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11659.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11655.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11645.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11527.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11677.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11658.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11649.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11657.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11656.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11652.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11646.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11643.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11654.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11651.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11639.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11648.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11841.wav

  inflating: DiffWave_Project/data_preprocessed/mels/11640.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11887.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12141.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11493.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11653.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11644.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11647.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11623.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11642.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12259.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11636.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12102.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12441.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11638.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11625.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11664.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11913.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11641.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11626.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11875.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11624.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11637.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11618.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11622.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11620.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11617.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11601.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11606.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11613.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11611.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11621.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11612.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11602.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12471.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11619.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12071.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11614.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12148.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11616.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11609.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11605.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11607.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11604.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12259.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11588.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11610.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12032.npy

  inflating: DiffWave_Project/data_preprocessed/mels/12111.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11615.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11603.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11608.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12475.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11578.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11587.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11600.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11586.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11580.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11581.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11582.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11583.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11570.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11574.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11573.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11568.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12505.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11577.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12418.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11572.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11575.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11584.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11922.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11569.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11585.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11571.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12296.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11566.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11772.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12027.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11555.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11554.npy

  inflating: DiffWave_Project/data_preprocessed/mels/11576.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11852.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11548.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11549.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11567.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11539.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11553.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11544.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11995.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11543.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11556.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11547.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11579.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11552.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12335.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12409.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11537.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11536.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11551.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11954.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11532.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11540.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11545.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11541.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11542.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11550.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12224.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11535.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12294.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11546.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11538.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11534.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12187.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12169.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11774.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11807.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11949.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11533.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12066.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11992.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12209.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11511.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11517.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11509.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11519.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11502.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11500.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11503.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11499.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11506.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11518.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11514.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11516.npy

  inflating: DiffWave_Project/data_preprocessed/mels/11510.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11505.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11515.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11520.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11522.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11512.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11507.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11508.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11513.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11498.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11496.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11521.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11565.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11494.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11501.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11497.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11564.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11634.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11559.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11504.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11470.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11495.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12028.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11479.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11482.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11484.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11476.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11485.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11461.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11460.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11481.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11477.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11472.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11630.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11474.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11471.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11483.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11468.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11478.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11466.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/11480.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11467.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11469.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11465.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11463.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11475.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11458.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11473.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11635.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11462.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11464.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11594.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11705.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11668.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12336.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11440.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11457.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11438.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11598.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12451.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11445.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11434.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11435.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11429.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11447.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11437.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11874.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11444.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11443.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11531.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11459.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11493.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11442.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11446.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11426.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11432.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11436.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11422.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11599.npy

  inflating: DiffWave_Project/data_preprocessed/wavs/11448.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11427.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11441.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11433.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11428.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11431.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11430.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11439.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11425.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11421.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11423.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11424.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11411.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11407.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12408.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11409.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11402.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11406.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11412.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11420.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11410.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11401.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11394.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11400.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11397.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11392.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12294.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11405.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11633.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11403.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11408.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11398.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12258.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11404.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12470.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11395.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11390.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11399.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11396.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/11393.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11912.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12031.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11386.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11389.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11387.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11391.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11388.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11385.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11375.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11921.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12258.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11377.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11376.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11742.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12186.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12474.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11369.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11370.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11773.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12295.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11364.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11373.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11357.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11360.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11365.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11363.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11355.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11359.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11374.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11368.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/11372.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11362.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12168.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11371.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11358.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11366.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11353.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11350.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12450.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11361.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11629.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11351.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11367.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11333.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12440.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11332.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12375.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11356.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11331.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11339.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11337.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11334.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11663.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11354.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11338.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11323.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11352.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12504.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11327.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11326.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11328.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11335.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11322.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11851.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11318.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11330.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11320.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11492.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11317.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11321.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/11329.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11319.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12101.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11324.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11316.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11315.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11325.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11987.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11336.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11704.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11306.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11314.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11886.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11305.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11302.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11287.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11296.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11283.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11290.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11994.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12208.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11299.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11294.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11289.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11295.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11304.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11303.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11298.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11292.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11300.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11806.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12335.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11291.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11269.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11268.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/11297.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11285.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11282.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11284.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11293.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11301.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11271.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11349.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11703.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11288.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11286.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11272.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11281.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11873.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11262.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11259.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11266.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11261.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11270.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11260.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11257.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11267.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11255.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11250.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11810.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12110.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11265.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11254.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11251.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11699.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11419.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12026.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11273.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11256.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11263.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11264.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11246.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/11248.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11253.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11258.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11840.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11252.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11247.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11249.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11480.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11456.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12417.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11485.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11479.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11481.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11475.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11471.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11473.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11484.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11487.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11483.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11463.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11488.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11469.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11667.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11464.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11467.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11466.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11482.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11738.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11476.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11474.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11486.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11470.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11477.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11478.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11558.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12333.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11280.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11948.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12140.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11245.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11472.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11451.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11465.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11468.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11453.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11454.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11445.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11455.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12147.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11449.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11384.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11452.npy

  inflating: DiffWave_Project/data_preprocessed/mels/11441.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11442.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11444.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11438.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11446.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11429.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11450.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11440.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11439.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11448.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11432.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11437.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11427.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11428.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11430.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11434.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11435.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11436.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11417.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11416.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11433.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11443.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11953.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11431.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12070.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11563.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11411.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11447.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11407.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11593.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11415.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11402.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11425.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11426.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11414.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11396.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11410.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12065.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11393.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11405.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11413.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11397.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11409.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11403.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11404.npy

  inflating: DiffWave_Project/data_preprocessed/mels/11399.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11408.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11391.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12372.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11530.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11392.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11400.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11406.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11398.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11526.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11395.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11597.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11401.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11390.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12334.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11313.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11379.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11377.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11462.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11376.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11412.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11382.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11375.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11368.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11373.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11381.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11394.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11378.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11362.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11374.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11380.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11364.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11367.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11363.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11348.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11371.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11372.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11361.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11369.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11370.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11366.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12293.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11358.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11357.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11360.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11885.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11529.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11348.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11771.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11359.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11356.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11337.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11344.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12223.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11355.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11347.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11346.npy

  inflating: DiffWave_Project/data_preprocessed/mels/11365.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11340.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11991.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11325.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12107.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11333.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11342.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11339.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11341.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11332.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11324.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11327.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11326.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12449.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11335.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11343.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11336.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11338.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11320.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11321.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11334.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11312.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11311.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11330.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11309.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11307.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11328.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11319.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11323.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11331.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11345.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12374.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11304.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11322.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11329.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11301.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11298.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11300.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11306.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11305.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11596.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11293.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11299.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11308.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11310.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11291.npy

  inflating: DiffWave_Project/data_preprocessed/mels/12185.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11295.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11290.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11302.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11347.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11289.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11491.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11632.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11297.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11294.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11303.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11666.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11296.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11292.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11288.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12030.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11281.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11279.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11911.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11278.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12473.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12257.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11280.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12292.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11276.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11274.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11260.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11265.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11264.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11277.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11267.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11269.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11272.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11273.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11263.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11279.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11557.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11268.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11270.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11275.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11266.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11262.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12100.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11254.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11255.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11257.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11253.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11256.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11271.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11258.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11261.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11259.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11252.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11346.wav

  inflating: DiffWave_Project/data_preprocessed/mels/11424.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11238.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11237.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11244.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12439.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11241.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11243.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11242.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11230.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11228.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11809.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11345.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11235.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11233.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11231.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11234.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11245.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11232.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11224.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11229.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11221.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11226.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11227.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11240.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11236.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11239.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11225.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11219.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11220.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11218.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11216.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12242.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11207.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11215.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11222.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11200.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11223.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11194.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/11196.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11205.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11199.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11202.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11198.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12257.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11204.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11197.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11201.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11217.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11191.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11190.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11183.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11186.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11189.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11208.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11192.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11206.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11187.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11203.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11185.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11195.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11188.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11181.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11182.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11193.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11184.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12371.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11628.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11162.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11161.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11165.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11157.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11872.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11850.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11171.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11172.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11156.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/11164.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11168.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11153.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11154.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11169.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11163.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11160.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11158.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11173.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12146.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12469.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11166.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11151.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11170.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11167.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11149.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11152.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11150.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11159.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11592.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11148.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11144.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11155.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12293.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11146.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11147.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11388.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11137.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11136.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11133.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11124.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11134.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11920.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11128.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11131.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11125.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11123.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11562.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11127.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11389.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11135.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11662.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11132.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11122.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11145.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11117.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/11120.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12025.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11118.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11119.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11126.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11129.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11111.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11130.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11099.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11986.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11109.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11113.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11114.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12069.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11121.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12416.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11112.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11772.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11097.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11110.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11095.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11528.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11116.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11115.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12332.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12330.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12207.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11094.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11100.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11101.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11090.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/11102.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11089.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11096.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11947.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11098.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11092.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11084.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11078.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11077.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11093.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11076.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11087.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11091.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11086.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11085.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11073.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11074.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11071.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11081.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11058.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11060.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11053.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11088.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11080.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11061.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11055.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11056.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11079.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11057.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11082.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11072.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11083.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11075.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11070.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11059.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11049.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11048.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11051.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11052.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11050.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11702.npy

  inflating: DiffWave_Project/data_preprocessed/wavs/11040.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11042.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11036.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11045.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11043.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11318.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11044.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11054.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11039.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12329.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11180.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11033.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11741.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11047.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12334.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12064.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11108.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11037.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11046.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11041.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11698.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11952.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11038.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11525.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11035.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11022.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11018.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11025.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11034.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11016.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11023.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11024.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/11026.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11009.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11007.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11011.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11020.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11014.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11017.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11010.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11013.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11019.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11021.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11006.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11012.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11001.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11003.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11015.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11008.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10999.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11737.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11005.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11002.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11004.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11143.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11235.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11234.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11241.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11232.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11231.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11237.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11228.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11221.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11223.npy

  inflating: DiffWave_Project/data_preprocessed/mels/11219.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11215.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11216.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11218.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11287.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11069.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11251.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11214.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12222.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11224.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11240.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11236.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11242.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11000.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11238.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11383.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11239.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11220.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11226.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11225.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11222.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11227.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11217.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11229.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11230.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11233.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11770.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11206.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11244.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11203.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11312.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12407.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10998.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11201.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11202.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11200.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11198.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11205.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11993.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11204.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11192.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11191.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11199.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11194.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11197.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11196.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11195.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11187.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11176.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11180.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11185.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11032.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11182.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11177.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11188.npy

  inflating: DiffWave_Project/data_preprocessed/mels/11184.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11183.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11190.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11455.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11193.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11178.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11167.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11214.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11213.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11179.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11461.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11189.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12503.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11163.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11164.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11166.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11181.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11186.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11162.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11165.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11152.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11150.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11155.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11148.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11149.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11175.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11159.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11160.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11144.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11161.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11156.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11153.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11154.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12139.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11169.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11157.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11158.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11168.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11146.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11145.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11142.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11151.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11143.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11141.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11147.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11132.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11354.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11418.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11839.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12167.wav

  inflating: DiffWave_Project/data_preprocessed/mels/11133.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11130.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11127.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11115.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11116.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11128.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11111.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11134.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11123.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11131.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11124.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11126.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11112.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11118.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11107.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11110.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11122.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11108.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12108.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11120.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11119.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11140.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11117.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11129.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11114.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11113.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11125.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11121.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11106.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12109.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11099.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11109.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11095.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11990.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11098.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11094.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11091.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11088.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11105.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11097.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11078.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11096.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11092.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11084.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11087.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11082.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11085.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11079.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11080.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11083.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11089.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11076.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11086.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11073.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11072.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11081.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11093.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11077.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11071.npy

  inflating: DiffWave_Project/data_preprocessed/mels/11075.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11070.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11074.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11805.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11090.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11951.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12333.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12206.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12166.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11061.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11838.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12068.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11059.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11058.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11057.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11849.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11064.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11053.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11062.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11054.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11056.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11052.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12448.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11051.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11771.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11063.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11040.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11055.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11044.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11060.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11045.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11050.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11043.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12502.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11049.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11039.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11046.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11036.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11042.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11047.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11030.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11038.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11032.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11041.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11048.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11035.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11037.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11019.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11024.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11012.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11031.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11033.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11034.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11023.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11020.npy

  inflating: DiffWave_Project/data_preprocessed/mels/11009.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11022.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11017.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11016.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12373.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11008.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11021.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11013.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11004.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11014.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11000.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11011.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11010.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11006.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10998.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11002.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11015.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11003.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10995.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11243.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11179.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11018.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11007.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11005.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10997.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10985.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11068.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10994.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12370.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10986.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10999.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10984.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10993.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11001.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10983.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11919.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10978.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10981.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10979.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10977.wav

  inflating: DiffWave_Project/data_preprocessed/mels/10996.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10982.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10962.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10976.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10987.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10969.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10968.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10971.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10964.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10974.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10959.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10955.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10966.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10967.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10947.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10970.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10972.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10980.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10963.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10957.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10975.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10965.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10958.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10973.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11701.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11382.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10960.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10948.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10945.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10942.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11460.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10949.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10956.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10946.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10961.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10943.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10940.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10934.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10929.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10926.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10923.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10936.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10941.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10937.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10932.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10931.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/10939.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10935.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10938.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10922.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11278.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11311.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10930.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10944.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12099.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12438.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10928.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11069.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11884.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11665.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10933.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10924.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10911.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10913.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10927.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10925.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10904.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10905.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10912.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10910.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10920.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10921.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10903.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10901.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10906.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10894.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11561.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10902.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10899.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10888.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10908.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10897.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10898.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10890.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10900.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10907.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10893.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10892.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10896.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10909.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/10895.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10889.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10884.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10883.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10891.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10887.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10886.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10873.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10877.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12468.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10885.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10872.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10867.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10864.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10868.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10869.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10859.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10875.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10865.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10876.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10863.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10855.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10856.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10862.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10918.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10861.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10858.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10874.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10857.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10866.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10870.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10849.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11769.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10854.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10871.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11527.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10852.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11317.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10851.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10853.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10834.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11212.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10860.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10837.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10840.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10832.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/11946.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10829.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10839.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10836.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10842.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10825.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11344.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11286.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10850.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10833.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10841.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10826.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10830.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10835.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10843.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10828.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11661.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10819.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10831.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10818.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10820.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10815.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10838.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10827.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10817.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12255.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10824.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10803.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10799.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10798.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11627.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10821.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10848.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10805.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10797.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10823.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10804.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10801.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10800.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10812.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10816.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10813.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10811.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10822.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11524.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10814.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10802.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10793.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/10796.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10794.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10790.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10791.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11631.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10792.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10780.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10782.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10788.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10781.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10785.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10789.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10772.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10783.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10882.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12331.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10795.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10787.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10779.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10764.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10765.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10778.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10773.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10762.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10763.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10766.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10784.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10775.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12292.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10761.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10777.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10774.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10753.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10776.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10786.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10759.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12256.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12024.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10758.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10750.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10751.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10746.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10987.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10991.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10752.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10988.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10755.wav

  inflating: DiffWave_Project/data_preprocessed/mels/10986.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10760.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11556.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10756.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10978.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10748.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10757.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10990.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11591.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10749.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10744.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10974.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10979.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10754.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10977.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10747.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10992.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10972.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10973.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10743.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10989.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11104.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10970.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10975.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10971.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10963.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10745.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10976.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10960.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10962.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10997.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10959.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10969.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10967.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10968.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10964.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10966.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12472.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11454.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11142.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10954.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10965.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10945.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10944.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10942.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10953.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10956.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10955.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10940.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10941.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10943.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10951.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10957.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10958.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10938.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12291.npy

  inflating: DiffWave_Project/data_preprocessed/mels/10932.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10961.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10954.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10952.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10933.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10930.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10925.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10922.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10934.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10918.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10919.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10937.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10939.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10931.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10935.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10928.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10917.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10915.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10923.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10927.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10929.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11211.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10908.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10921.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11417.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11989.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10920.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10924.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10926.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11107.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10902.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10916.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10936.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10904.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10906.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10905.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10897.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10900.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10903.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10907.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10901.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10899.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12063.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10894.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10891.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12415.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10886.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12184.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10895.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10884.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10896.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10890.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10888.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10893.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10889.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10887.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10950.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10898.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10885.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12328.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10892.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10875.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10882.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11871.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10866.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10872.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10871.npy

  inflating: DiffWave_Project/data_preprocessed/mels/12145.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10863.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10873.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10874.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10861.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10864.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10850.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10854.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10865.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10868.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10870.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10862.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10859.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10852.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11490.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10855.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10849.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10985.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10869.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10883.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10851.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11736.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10867.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10853.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10839.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10914.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10837.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11740.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10858.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10860.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10842.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10856.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10857.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10829.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10833.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10835.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10848.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10836.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10840.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10838.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10841.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10831.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10834.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10825.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10830.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10827.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10818.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10828.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10823.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10815.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10832.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10819.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11029.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10821.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10826.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11985.wav

  inflating: DiffWave_Project/data_preprocessed/mels/11595.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10824.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10812.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10817.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10820.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10847.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10813.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12029.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10800.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10816.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10822.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10802.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10801.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12406.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10803.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10807.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10814.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10806.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10805.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10804.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10796.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10797.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10793.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10798.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10782.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10795.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10792.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10781.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10780.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10791.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10794.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10799.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10783.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10787.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10789.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10790.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10775.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11910.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10776.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10763.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10778.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10788.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10785.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10768.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10758.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10779.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10766.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10767.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10786.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10777.npy

  inflating: DiffWave_Project/data_preprocessed/mels/10784.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10759.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10761.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10762.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10755.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10752.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10748.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10751.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10745.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10774.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10744.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10992.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10742.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10749.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10764.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10746.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10765.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10756.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10760.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10747.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11250.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12138.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10881.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10754.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11697.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10753.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10757.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10743.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11387.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11353.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10919.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10750.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10735.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10727.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12106.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10734.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11213.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10736.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10733.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10810.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10730.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10729.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10731.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10728.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10720.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10726.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10723.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10724.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10717.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10713.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10716.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10714.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10725.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10722.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10715.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10721.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10712.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10711.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10709.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10708.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10706.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10710.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10719.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10732.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10718.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10696.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/10692.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10707.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10705.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10699.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10697.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10689.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10695.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11067.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10691.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10687.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11139.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10684.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10680.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10678.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10685.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10700.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10677.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10676.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10667.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10683.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10686.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10679.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10693.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10694.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10690.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10672.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10671.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10673.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10682.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10688.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10675.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10698.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10668.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10670.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10669.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10660.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10666.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10649.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11594.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10674.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10681.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10658.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10654.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10655.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10653.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10651.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10647.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10640.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10656.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10652.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10657.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10650.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10646.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/10642.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10644.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10641.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10659.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10645.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10648.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10639.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10637.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11031.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10643.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10635.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10634.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11808.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10665.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10626.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10638.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10636.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11423.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12221.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10771.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10627.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10623.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10617.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10622.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10616.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10606.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10624.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11174.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10773.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10741.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12256.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10612.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10620.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10615.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10611.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10633.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10621.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11804.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12241.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10628.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10613.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10609.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10618.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10614.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10619.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10603.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10625.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10601.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10610.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10602.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10596.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10608.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10605.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10585.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10598.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/10582.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10579.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10607.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10586.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10595.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10597.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10584.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10588.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10604.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10600.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10599.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10576.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10581.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10587.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10574.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10580.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10577.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10578.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10583.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10573.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10568.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10566.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10575.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10569.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10560.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10570.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10572.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10571.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12254.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10564.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11210.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11177.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10562.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10632.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10550.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10548.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10546.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10565.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10563.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12405.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11590.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10567.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10547.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10996.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10561.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10552.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10542.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10541.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10558.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10594.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10544.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10545.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10593.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10559.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/10549.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10539.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10534.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10536.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10551.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10535.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10540.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10538.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10543.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10537.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10530.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10522.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10528.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10521.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10523.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10527.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10518.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10532.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10512.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10526.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10529.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10525.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10533.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10510.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10519.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10524.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10509.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10520.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10503.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10513.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10504.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10508.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10531.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10511.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10507.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10502.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10506.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10498.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10505.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10496.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10500.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10493.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10737.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10736.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11310.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10733.npy

  inflating: DiffWave_Project/data_preprocessed/mels/11560.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10739.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10741.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10494.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10734.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11739.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10499.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10501.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10704.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11453.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10738.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10497.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10727.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10726.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10724.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10728.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10495.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10740.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10742.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10722.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10725.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10723.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10720.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10721.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11950.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10735.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10718.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12371.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10716.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11837.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10719.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12332.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10714.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10717.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10710.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10709.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10711.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10706.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10713.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10715.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10703.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10697.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10707.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10701.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10700.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10705.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10689.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10696.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10681.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10688.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10695.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10704.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10685.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10712.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10686.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10683.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10708.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10699.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10694.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10678.npy

  inflating: DiffWave_Project/data_preprocessed/mels/10687.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10679.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10676.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10684.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10702.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10677.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10673.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10675.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10680.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10698.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10664.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10668.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10663.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10671.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10682.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10656.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10655.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10659.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10674.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10669.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10657.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10665.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10670.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10667.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12372.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10672.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10649.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10648.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10650.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11489.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10644.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10666.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10664.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10658.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10643.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10641.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10660.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12165.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10661.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10645.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10640.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10662.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10642.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10646.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10633.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10634.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10647.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10631.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10639.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10625.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10626.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10623.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10627.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10622.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11422.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10630.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10637.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11459.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10624.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10629.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10632.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10628.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10621.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10613.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10636.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10616.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10610.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11592.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10602.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10604.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10599.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10614.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10638.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10601.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10605.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10635.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12255.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10611.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10606.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10603.npy

  inflating: DiffWave_Project/data_preprocessed/mels/10615.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10612.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10608.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10598.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10591.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10607.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11626.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10609.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10600.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10589.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10588.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10590.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10592.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10594.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10595.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10597.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10577.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10572.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10579.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10596.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10563.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10571.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10576.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10564.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10578.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10560.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10568.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10586.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10573.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10567.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10561.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10575.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10593.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10566.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10557.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10570.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10569.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10562.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10584.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10574.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11343.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10654.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10847.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10592.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10559.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10565.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10587.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10549.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11173.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10544.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10552.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11416.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10545.npy

  inflating: DiffWave_Project/data_preprocessed/mels/10551.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10538.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10585.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10548.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11660.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10558.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10550.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10541.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12501.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10539.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10540.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10536.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10531.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10546.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10547.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10534.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11316.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10535.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10533.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10537.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10527.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10525.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10529.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10524.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10542.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10523.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11138.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10532.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10512.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10522.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10511.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10508.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12105.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12067.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10526.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10509.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10543.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10513.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10528.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10530.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10521.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10501.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10515.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10510.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10506.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10507.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10505.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10514.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10502.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10495.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10494.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10493.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10491.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10490.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10499.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10504.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10492.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10487.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12291.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10484.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10498.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10489.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10503.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10483.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10500.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10472.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10488.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10497.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10481.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10486.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10496.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10474.npy

  inflating: DiffWave_Project/data_preprocessed/mels/11421.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10462.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10469.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10470.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10460.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10467.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10485.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10458.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10455.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10456.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10468.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10453.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10482.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10475.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10464.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10451.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10449.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10463.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10454.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10466.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10465.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10448.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10452.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11065.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10471.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10459.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10457.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11806.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11141.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10440.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10461.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10450.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11664.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11285.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10473.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10439.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10437.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10433.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10434.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10431.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10430.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10424.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10441.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10420.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10425.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10421.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10426.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11883.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10423.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10436.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10427.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10422.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10419.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10438.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10442.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10432.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11103.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10428.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10557.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10416.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10480.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11700.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10435.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10429.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10413.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10415.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10406.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10412.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10404.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10405.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11249.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10403.npy

  inflating: DiffWave_Project/data_preprocessed/wavs/10991.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10418.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10417.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11212.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10398.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10395.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10402.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10394.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10407.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11068.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11738.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10414.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10391.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10396.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10400.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10393.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10388.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10384.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10392.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10390.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10387.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10380.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10376.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10373.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10401.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10399.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10383.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10397.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10382.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10386.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10378.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10364.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10379.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10389.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10372.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10371.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10362.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10357.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11770.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10360.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10366.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10375.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10363.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10377.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10352.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10353.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10358.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10356.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10381.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10385.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10365.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10361.npy

  inflating: DiffWave_Project/data_preprocessed/mels/10359.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10349.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10374.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10354.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10347.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10355.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10344.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10351.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10338.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10339.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10348.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10350.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10346.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10336.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12220.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12471.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10343.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10345.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10341.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10340.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10337.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10342.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11066.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10330.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12467.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11768.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10331.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11918.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10327.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12253.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10740.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10329.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12023.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10318.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10312.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10313.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10316.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10325.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10319.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10315.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10323.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10308.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10305.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10302.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10311.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10320.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10300.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10314.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10310.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10328.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10324.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10317.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10326.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10307.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10322.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10306.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10309.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10301.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10299.npy

  inflating: DiffWave_Project/data_preprocessed/mels/10303.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11526.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10286.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10321.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11593.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11735.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10304.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10291.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10298.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10290.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10289.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10284.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10288.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10292.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10278.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10281.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10282.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10277.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10272.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10283.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10287.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10280.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10276.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10269.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10271.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10270.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10285.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10275.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10274.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10917.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10279.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10265.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10263.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10266.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10261.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11381.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10262.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10273.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11386.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11630.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11554.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10255.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10252.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10264.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10250.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10251.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10254.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10268.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10247.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10249.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10256.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10489.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10491.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/10488.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10246.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10267.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10492.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10732.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10248.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10243.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10245.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10490.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10244.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10485.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10482.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10253.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10478.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10484.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10486.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10480.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10487.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10472.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10481.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10949.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10474.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10473.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10476.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10470.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11555.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10455.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10456.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12414.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10483.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10477.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10471.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10475.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10479.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10811.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10469.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10467.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10462.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11870.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10454.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10452.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10458.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10457.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10450.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10460.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10451.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10445.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/10459.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10446.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10448.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10437.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10461.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10449.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10441.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10434.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10438.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10444.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11984.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10430.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10429.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10439.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10424.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10447.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10423.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10442.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10433.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10443.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10415.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10413.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10453.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10431.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10435.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10440.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10770.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10912.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10432.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10420.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10422.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10421.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10419.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10436.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10418.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10416.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10408.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10412.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10410.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10411.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10417.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10399.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10400.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10414.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10401.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10397.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10335.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10392.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10394.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10403.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/11030.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10391.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10398.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10406.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10386.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10409.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10395.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10405.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10384.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10396.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10383.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10407.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10404.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12144.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10402.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12447.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11553.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10382.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10378.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10393.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10376.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/10374.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10373.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10360.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10379.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10365.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10361.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10364.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10381.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10380.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10358.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10371.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10372.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10366.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10363.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10385.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10368.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10357.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10377.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10359.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10345.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10362.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10352.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10354.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10356.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10353.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10355.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10344.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10341.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10367.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10370.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10369.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10375.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10340.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10333.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10336.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10331.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/10332.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10329.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10342.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10343.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10327.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10339.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10335.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10338.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10337.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10330.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10326.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10324.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10325.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10322.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10328.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10334.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10321.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10319.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10317.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10351.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12028.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10316.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11988.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10307.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10323.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12437.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10953.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10350.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10318.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10304.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10311.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10309.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10320.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10846.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10306.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10913.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10305.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10880.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10303.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10301.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10297.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10295.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10300.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10809.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10299.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/10289.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10296.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10288.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10285.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10298.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10290.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10281.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10308.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10294.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10310.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10293.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10280.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10302.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10291.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10287.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10279.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10268.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10276.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10275.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10265.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10278.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10277.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10292.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10286.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10264.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10263.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10284.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10282.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10267.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10266.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10283.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10262.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10253.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10260.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10258.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10248.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10247.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10245.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10259.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10249.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10254.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10255.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10252.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10244.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/10274.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10246.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10260.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11909.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10256.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10257.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10251.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10261.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10240.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10250.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12062.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10231.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10519.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12137.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10447.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10273.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10370.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10228.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10219.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10243.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10226.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10241.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10230.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10215.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10227.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10223.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10224.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10220.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11452.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10225.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10218.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10242.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10556.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10229.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10222.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10214.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10211.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10216.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10221.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10213.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10232.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10212.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10206.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10205.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10209.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10203.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10208.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10207.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10204.npy

  inflating: DiffWave_Project/data_preprocessed/mels/10189.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10195.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10217.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10193.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10201.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11028.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10188.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10182.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10181.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10186.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10210.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10191.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10190.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10185.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10192.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10183.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10173.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10178.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10202.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10187.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10196.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10180.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10179.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10174.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10194.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10171.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10177.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10176.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10315.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10170.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10167.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11277.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10165.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10168.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10184.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10583.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10296.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10169.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10772.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10411.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10161.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10172.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10175.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11523.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10236.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10166.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10158.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10160.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10157.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10159.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10155.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10156.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10117.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10150.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10114.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10152.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10146.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10148.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10154.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10118.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10145.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10116.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10151.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10153.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10143.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10147.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10149.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10141.npy

  inflating: DiffWave_Project/data_preprocessed/mels/10112.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10139.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10115.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10144.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10109.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10138.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10136.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10134.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10142.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10137.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10108.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10135.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10113.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10106.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10111.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10105.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10087.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10133.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10107.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10104.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10132.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10131.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10086.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10084.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10140.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10110.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10085.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10103.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10101.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10127.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10100.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10082.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10129.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10128.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10083.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10096.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10079.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10098.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10099.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10080.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10130.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10097.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10102.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10076.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10081.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10125.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10069.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10070.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10126.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10078.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10077.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10124.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10095.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10068.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10071.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10066.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12098.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10123.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10061.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10062.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10050.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10054.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10065.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10063.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10056.npy

  inflating: DiffWave_Project/data_preprocessed/mels/10057.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10349.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10046.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10693.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10517.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10466.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10237.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10053.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10051.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10067.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10059.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10064.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10052.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10047.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10060.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10058.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10881.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10520.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10049.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10040.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10041.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10048.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10055.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10038.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11945.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10029.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10033.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10036.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10428.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10031.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10032.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10025.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10039.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10037.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10026.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10023.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10030.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10020.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10024.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10015.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10016.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10027.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10035.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10019.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10022.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10017.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10021.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10028.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10034.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11696.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10272.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10018.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10620.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10009.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10014.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10008.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10094.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10010.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10007.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10000.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10297.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10001.npy

  inflating: DiffWave_Project/data_preprocessed/mels/10004.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10005.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09993.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09999.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10240.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10003.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10002.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09996.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09995.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10239.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10006.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10241.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09998.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10242.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09997.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10234.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10232.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10231.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09994.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12205.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10390.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10235.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10223.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10468.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10226.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11807.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10238.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10236.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10237.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10222.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11352.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10233.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10224.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10219.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10217.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10239.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10225.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10221.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10230.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10213.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10212.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10218.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10214.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10215.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10202.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10204.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10201.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10207.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/10199.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10197.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10211.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10210.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10209.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10194.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10220.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10205.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10203.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10206.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10208.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10200.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10198.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10192.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11106.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12327.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10193.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10216.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10196.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10195.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10180.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10181.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10184.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10182.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10172.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10173.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10185.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10186.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10175.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10169.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10171.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10177.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10183.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10190.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10191.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10174.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10163.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10160.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10165.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10170.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10167.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10157.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/10156.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10158.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10145.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10168.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10176.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10164.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10179.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10154.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10159.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10166.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10984.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10161.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10147.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10162.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10144.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10146.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10178.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12240.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10148.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10142.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10155.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10141.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10138.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10140.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10134.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10137.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10149.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10143.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10132.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10128.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10130.wav

  inflating: DiffWave_Project/data_preprocessed/mels/12183.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10139.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10131.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10124.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10127.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10135.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10125.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10120.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10117.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10136.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10133.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10150.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11178.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10118.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10129.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10119.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11803.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10122.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10104.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10109.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10103.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10105.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10106.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10102.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10121.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10110.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10095.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10123.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10116.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10115.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10108.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10107.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10126.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10045.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10093.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10094.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10091.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10101.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10086.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10096.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10092.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10083.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10097.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10081.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10090.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11492.npy

  inflating: DiffWave_Project/data_preprocessed/wavs/10087.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12369.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10099.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10100.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10098.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10089.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10114.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10200.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10074.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10082.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10085.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10238.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10076.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10073.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10075.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10077.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10122.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10071.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10069.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10075.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10072.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10084.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10088.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10068.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10067.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10066.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10064.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10052.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10065.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10060.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10054.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10055.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10058.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10070.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10057.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10059.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10048.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10879.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10056.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10053.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11848.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10044.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11882.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10040.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10047.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10046.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10049.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10050.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10045.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/10039.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10062.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10063.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10061.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10051.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10038.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12290.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10034.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10033.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10032.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10037.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11027.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10036.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10591.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12290.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10026.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10035.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10023.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10024.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10025.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10018.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10028.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10015.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10030.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10029.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10016.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10011.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10013.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10020.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09997.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09999.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09998.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10022.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10014.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10012.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10019.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10017.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/09996.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10021.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10010.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10031.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09993.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09991.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10027.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09989.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09988.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09985.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09995.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09987.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09994.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09981.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09986.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10008.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09982.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09983.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09979.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09977.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09984.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09992.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09978.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09976.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10009.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09973.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09974.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09975.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09969.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09970.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10004.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10314.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10005.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09990.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10006.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09980.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09965.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09962.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09964.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09961.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09960.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10003.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10982.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09972.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09957.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09959.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09956.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09971.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09955.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09953.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09949.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09952.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10007.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09954.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09951.npy

  inflating: DiffWave_Project/data_preprocessed/mels/09942.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09943.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09944.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09950.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09963.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09946.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09945.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09938.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09937.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09935.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09947.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09958.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09941.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09932.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09934.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09948.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09936.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09939.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10631.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11663.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09925.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09922.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09940.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09924.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11451.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09928.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09927.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11458.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09919.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09921.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09918.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09916.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09926.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10002.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09920.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09914.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09910.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09907.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09917.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09933.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09904.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09908.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09906.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09897.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09903.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09898.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09915.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09905.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09923.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09887.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09913.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09902.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09888.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09886.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09900.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09883.npy

  inflating: DiffWave_Project/data_preprocessed/mels/09884.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09896.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09885.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09889.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09901.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09911.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09912.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09881.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09894.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09882.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09909.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09899.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09895.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09878.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09893.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09877.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09880.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09872.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09875.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09879.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09862.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09865.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09874.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09863.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09859.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09876.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09871.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09857.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11351.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11315.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09860.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09864.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09858.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09850.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09855.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09870.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09866.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09868.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09849.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09861.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09869.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09846.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09867.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09845.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09873.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09848.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11917.npy

  inflating: DiffWave_Project/data_preprocessed/mels/11137.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09841.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09838.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09840.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09837.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09835.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09834.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09836.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09827.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09824.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09844.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09851.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09856.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09839.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09828.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09847.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09829.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09826.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09812.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09842.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09825.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09814.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09809.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09808.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09821.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09830.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09831.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09807.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09811.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09822.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09843.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09833.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09832.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09804.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09813.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09800.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09798.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09792.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09802.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09806.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09823.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09797.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09810.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09805.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09799.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09794.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09803.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09795.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09819.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09801.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09791.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09796.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11211.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09790.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11695.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09820.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09793.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09789.npy

  inflating: DiffWave_Project/data_preprocessed/mels/09778.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09788.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09777.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09781.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10810.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09968.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09775.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10229.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10080.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09771.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09770.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09783.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09773.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09774.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09772.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09782.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09780.npy

  inflating: DiffWave_Project/data_preprocessed/mels/09776.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09769.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09768.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09766.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09763.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09760.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09761.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09764.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09755.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09818.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09787.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09756.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09753.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09779.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09765.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09751.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09757.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09745.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09743.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09992.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09990.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09750.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09752.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09986.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09754.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09758.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09767.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09744.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09988.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09983.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09746.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09987.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09762.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09982.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09759.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09991.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09984.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09976.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/09981.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09979.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09967.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09973.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09969.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09965.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09971.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09977.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09968.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09989.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09978.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09964.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09985.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11836.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10043.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09980.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09975.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11699.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09959.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11625.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09956.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09958.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09951.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09947.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09974.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09970.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09972.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09948.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09963.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09954.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09966.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09949.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09950.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09943.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09945.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09942.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09940.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09936.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09957.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09946.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12436.npy

  inflating: DiffWave_Project/data_preprocessed/wavs/09955.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09952.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09953.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09941.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09939.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09934.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09944.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09937.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09931.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09928.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09933.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09920.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09918.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09930.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09929.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09938.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09912.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09935.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09932.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09916.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09909.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09904.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09901.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09908.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09905.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09907.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09919.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09915.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09911.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09910.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09914.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09917.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09913.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/09900.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09927.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09893.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09895.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09892.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12404.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10663.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09894.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09887.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09926.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09888.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09881.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09897.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09899.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09925.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09906.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09921.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09903.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12136.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10739.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09884.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09902.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09896.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09880.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/09898.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09885.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09877.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09882.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09872.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09869.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09883.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09875.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09871.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09867.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09873.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09874.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09886.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09876.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09879.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09863.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09860.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09865.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09859.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09868.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09866.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09864.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09858.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09870.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09849.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09878.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09862.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11420.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12370.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09851.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09856.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09855.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09931.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11525.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09850.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09848.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09840.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09844.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/09857.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09837.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09833.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09836.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09831.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09846.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09861.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09825.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09834.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09827.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09842.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09828.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09838.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09832.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09826.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09847.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09841.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09839.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09845.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09835.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09824.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09821.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09829.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09843.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09830.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10199.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09820.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09822.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10164.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09812.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09809.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/09808.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09807.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09805.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09804.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09813.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09819.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09806.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09800.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09799.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09796.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09810.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09811.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09815.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09803.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09801.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09797.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09798.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09802.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09794.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09823.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09793.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09790.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09795.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09786.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09791.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09789.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09814.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10948.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09892.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11629.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12470.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09780.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11694.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09779.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09792.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/09777.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09778.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09773.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09772.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09788.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09776.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09771.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09787.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09770.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09766.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09774.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09765.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09762.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09764.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11659.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09761.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09767.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10518.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09775.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09781.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09768.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09760.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09785.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09758.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09752.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09747.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09753.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09769.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09759.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10516.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09756.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09750.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09740.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09749.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09739.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09754.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09746.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09738.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09733.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09745.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10153.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09732.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09734.npy

  inflating: DiffWave_Project/data_preprocessed/mels/09731.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09741.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09729.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09736.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09763.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09755.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09757.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09737.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09748.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09730.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09725.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09751.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09735.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09722.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09718.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09719.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09727.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09709.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09715.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09726.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09711.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09710.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09713.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12164.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10479.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09714.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09728.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09701.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09717.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09704.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09716.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09712.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09721.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09724.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10916.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09723.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09703.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09700.npy

  inflating: DiffWave_Project/data_preprocessed/mels/09720.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09698.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09708.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09697.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09693.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09690.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09688.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09686.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09817.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09685.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09684.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09695.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09694.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09702.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09699.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09691.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09692.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09681.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09687.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09664.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09679.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09682.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09696.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09677.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09676.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09689.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09683.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09673.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09660.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09674.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09678.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09661.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09680.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09672.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09657.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09663.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09675.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09659.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09655.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09650.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09654.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09665.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09658.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09647.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09645.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09652.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09662.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09656.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09646.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09641.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09644.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09642.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09639.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09638.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09643.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09670.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09671.npy

  inflating: DiffWave_Project/data_preprocessed/mels/09640.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09648.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09629.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09630.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09669.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09653.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09651.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09854.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09635.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09631.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09628.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09636.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11769.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09626.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09625.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09620.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09624.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11172.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09623.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09616.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09649.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09622.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09619.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09614.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09637.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10619.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09613.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09615.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09612.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09621.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09607.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09627.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09610.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09608.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09617.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09603.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09611.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09598.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09604.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09618.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09605.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09609.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09602.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09594.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10952.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11491.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09593.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09601.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09592.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09599.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09585.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09582.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09583.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09606.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09749.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09588.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09581.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09584.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10653.npy

  inflating: DiffWave_Project/data_preprocessed/mels/09577.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09575.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09600.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09578.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09591.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10692.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09572.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09573.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09576.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09586.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09569.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09579.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09580.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09571.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09570.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09564.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09567.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09589.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09587.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09590.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09566.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09561.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12022.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09563.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09557.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10445.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10446.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09565.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09555.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09574.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09554.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09552.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09553.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09550.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09547.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10846.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09540.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09568.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11589.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09562.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09543.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09548.npy

  inflating: DiffWave_Project/data_preprocessed/mels/09545.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09541.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09534.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09556.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09544.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09551.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09538.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09546.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09539.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09532.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09549.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09533.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09536.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09535.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09531.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09542.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09528.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09526.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09514.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09510.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09529.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09513.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09503.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09508.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09501.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09500.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09496.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09516.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09537.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09524.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09507.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09511.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09502.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09515.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09525.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09523.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09495.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09527.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09498.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09506.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09512.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09530.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09505.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09517.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09741.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09499.npy

  inflating: DiffWave_Project/data_preprocessed/wavs/09740.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09509.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09738.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09504.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09739.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09737.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09494.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09742.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09726.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09497.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09728.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09731.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09730.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09722.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09733.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09521.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09522.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09721.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09724.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09493.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09720.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09723.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09718.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09732.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09719.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09717.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09729.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09727.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09725.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09712.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09709.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09711.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09715.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09716.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09704.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12500.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09705.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/09714.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11385.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10044.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09708.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11908.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09699.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09698.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09710.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11846.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09693.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09695.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09696.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10334.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09706.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09520.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09697.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11802.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09713.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09694.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09700.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09692.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09707.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09688.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10478.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09682.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09686.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09679.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09677.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09689.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09681.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09680.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09685.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09683.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09672.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09671.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09678.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09690.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/09675.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09687.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09664.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09670.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09684.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09691.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09665.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09667.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09666.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11176.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09668.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09663.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09674.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09650.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09646.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09643.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09673.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09639.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09638.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09644.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09651.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09676.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09641.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09640.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09645.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09669.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09649.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09642.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09658.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09634.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09637.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09662.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09629.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09633.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09661.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09648.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09632.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09660.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/09635.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09631.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09628.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09626.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09647.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09655.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09659.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09656.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09636.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09630.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09657.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09617.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09622.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11881.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09616.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09627.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11869.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09606.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09615.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09611.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09619.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/09608.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09621.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09614.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09613.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09612.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09609.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09610.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09604.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09603.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09607.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09601.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09596.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09591.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09592.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09602.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09620.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09618.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09600.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09598.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09597.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09595.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09588.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09583.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09593.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09594.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09590.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09576.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09580.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09577.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12466.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09605.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12331.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/09589.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09584.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09582.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09572.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09574.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09578.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09579.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09570.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09581.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09567.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09561.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09599.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09566.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09560.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09563.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09562.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09569.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09568.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09571.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09564.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09559.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09553.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09556.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11248.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09573.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09558.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09575.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09555.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09557.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10990.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11987.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11805.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09548.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11209.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11067.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09565.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09547.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09554.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09543.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09546.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/09540.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09538.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09542.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09544.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09532.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09552.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09545.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09535.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09527.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09526.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09525.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09531.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09534.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09530.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09536.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09520.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09517.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09522.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09523.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09524.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09509.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09508.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09504.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09521.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09518.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09541.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09528.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09519.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/09529.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09516.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09537.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09533.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09539.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09515.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09514.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09505.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09501.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09498.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09506.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09503.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09502.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09500.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09496.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09487.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09499.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09495.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09483.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09482.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09493.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09492.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09494.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10013.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09513.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09488.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09489.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09486.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09490.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09485.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09491.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09497.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09507.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09480.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09962.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09479.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09475.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11767.wav

  inflating: DiffWave_Project/data_preprocessed/mels/09481.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09472.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09484.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09854.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09465.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09464.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12446.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11102.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09474.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09460.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09468.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09471.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09456.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09457.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09467.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09462.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09473.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09454.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09469.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09450.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09452.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09461.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09446.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09463.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09459.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09449.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09458.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09451.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09444.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09436.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09455.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09453.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09466.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09448.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09447.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09470.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09435.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09434.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09433.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09432.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09431.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09429.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09423.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09445.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09427.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09414.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09430.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09424.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09422.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09419.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09418.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09412.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09409.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09411.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09420.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09425.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09421.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09426.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09416.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09413.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09443.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09417.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09408.npy

  inflating: DiffWave_Project/data_preprocessed/mels/09440.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09428.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09441.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09410.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09402.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09442.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09407.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09415.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09397.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09399.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09395.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09406.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09393.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09386.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09400.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09385.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09390.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09382.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09381.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09396.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09376.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09392.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09389.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09398.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09401.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09380.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09391.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09387.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09378.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09377.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09383.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09384.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09375.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09374.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09394.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09379.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09367.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09373.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09388.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09368.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10093.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09736.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10348.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09354.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09357.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12219.npy

  inflating: DiffWave_Project/data_preprocessed/mels/09366.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09364.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09363.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09362.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09361.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09365.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11488.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09359.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09356.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09372.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09360.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09347.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09352.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09350.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09349.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09348.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09353.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09346.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09358.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09343.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09336.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10983.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09330.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09328.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09339.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11552.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11944.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09344.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09351.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09338.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11734.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09325.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09337.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09345.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09355.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09321.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09327.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09322.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09341.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09340.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09331.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09342.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09324.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09335.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09326.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09316.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09315.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09784.wav

  inflating: DiffWave_Project/data_preprocessed/mels/09323.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09329.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09312.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09314.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09320.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09317.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09310.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09307.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09305.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09309.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09296.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09289.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09311.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09304.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09313.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09319.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09300.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09308.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09301.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09318.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09292.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09290.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09299.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09303.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09298.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09286.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09288.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09306.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09287.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09279.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09276.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09302.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09273.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09274.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09291.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09278.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09284.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09271.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09280.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09285.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09282.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09281.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09283.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09268.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09272.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09277.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09266.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09258.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09259.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09247.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09249.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09275.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09248.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09256.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09264.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09251.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09267.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09270.npy

  inflating: DiffWave_Project/data_preprocessed/mels/09269.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09491.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09488.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09253.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09250.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09487.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09265.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09254.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09489.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09297.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09245.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09492.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09295.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09246.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09255.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09252.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09490.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09483.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09481.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09480.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09257.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09485.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09243.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09244.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09486.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09484.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09474.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09482.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09472.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11522.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09462.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09469.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09479.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09471.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/09459.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11140.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09475.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09466.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09470.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09473.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09461.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09891.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09464.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09458.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12239.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11737.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09460.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09455.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09467.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09468.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09463.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09456.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09465.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09453.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09451.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09439.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09433.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09437.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09436.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09450.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09452.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09457.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09448.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09454.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09435.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09449.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09428.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09442.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09441.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09431.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09446.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09430.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09425.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09434.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09421.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09418.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09424.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09422.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/09440.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09427.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09432.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09438.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09417.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09423.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09426.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09447.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09416.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09924.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09420.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09419.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09429.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09404.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09407.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09402.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09401.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09405.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09411.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09395.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10389.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09399.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09397.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09408.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09409.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09415.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09394.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09392.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09478.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10259.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09403.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12413.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09386.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09383.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09396.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09398.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09400.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09390.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09410.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09406.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09388.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09393.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09391.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09381.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09382.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09368.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11559.npy

  inflating: DiffWave_Project/data_preprocessed/wavs/09385.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10911.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09363.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09375.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09384.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09379.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09387.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09389.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10845.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09364.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09369.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09360.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09373.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09370.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09367.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09359.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09365.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09354.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09380.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09374.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09371.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09358.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09357.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09356.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09366.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11380.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09372.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09361.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09353.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09348.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09349.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09339.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/09338.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09336.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09335.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09333.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09332.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09329.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09351.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09355.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09362.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09345.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09328.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09337.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09326.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09352.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09350.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09340.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09347.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09707.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09330.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09334.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09322.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09327.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09317.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09323.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09346.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09314.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09325.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09341.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09319.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09320.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09324.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10427.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09331.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10731.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09305.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09313.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09306.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12061.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09321.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09315.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09302.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11591.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09405.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09308.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09297.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09303.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/11105.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09292.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09294.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09300.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09299.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09309.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09289.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09316.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09318.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09307.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11949.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09304.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09290.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09301.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09293.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09291.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09286.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09278.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09271.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09285.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09298.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09288.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09279.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09284.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09277.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09296.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09295.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09262.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09265.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09283.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09280.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09267.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09266.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09272.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09287.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09270.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09282.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/09281.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09259.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09260.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09744.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09258.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09264.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09253.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09254.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09252.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09249.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09246.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09257.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09269.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09273.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09263.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09268.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09251.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09256.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09247.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09255.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09238.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09237.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09240.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12027.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09250.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09261.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10189.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09248.wav

  inflating: DiffWave_Project/data_preprocessed/mels/09233.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09226.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09227.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09245.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09239.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09231.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09234.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09221.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09217.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09229.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09225.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09216.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09223.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09236.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09241.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09232.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10556.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09228.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09235.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09230.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12066.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11415.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09218.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09224.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12326.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09219.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09220.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09214.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09209.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12104.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09206.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09208.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09204.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09222.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09668.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09215.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09196.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09194.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10878.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09201.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09203.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09193.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09205.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09190.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11029.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09199.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09213.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09198.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09195.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09207.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09187.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09191.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09185.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09192.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09200.npy

  inflating: DiffWave_Project/data_preprocessed/mels/09186.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09184.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09188.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09189.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09197.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09414.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09183.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09202.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09178.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09170.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09179.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09181.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09177.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09182.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09180.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09169.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09165.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09162.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09171.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09167.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09155.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09164.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09173.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09172.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09161.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09163.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09141.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09156.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09168.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09148.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09143.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09312.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09445.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09151.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09147.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09166.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09159.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12182.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09154.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09144.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09158.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09149.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09142.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09133.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09153.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09160.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09157.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09150.npy

  inflating: DiffWave_Project/data_preprocessed/mels/09132.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09152.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09128.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09136.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09126.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09145.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09124.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09146.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09134.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09129.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09131.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09123.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09130.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09119.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09140.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09135.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09127.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09120.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09125.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09122.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09116.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09118.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09121.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09117.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09112.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09097.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09109.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09110.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09113.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09114.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09099.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09111.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09106.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09098.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09104.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09105.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09587.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09115.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09095.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09088.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09263.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09085.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09107.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09108.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09093.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09089.npy

  inflating: DiffWave_Project/data_preprocessed/mels/09083.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09077.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09096.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09082.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09100.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09094.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09081.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09087.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09091.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09092.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09072.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09073.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09080.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09090.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09066.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09067.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09064.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09063.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09079.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09071.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09065.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09075.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09084.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09086.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09076.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10582.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09058.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09061.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09059.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09078.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09057.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09060.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09062.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09049.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09074.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09051.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09056.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09044.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09053.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11284.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09054.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09043.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09050.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09052.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09038.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09046.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09055.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09045.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10769.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09042.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09439.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09039.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09030.npy

  inflating: DiffWave_Project/data_preprocessed/mels/09040.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09048.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10295.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09034.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09032.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12289.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09027.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09512.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09026.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09033.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09025.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09018.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09047.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09041.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09371.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09020.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09019.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09022.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09014.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09007.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09012.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09004.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09013.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09010.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09031.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09023.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09028.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09016.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09029.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09024.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09021.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09008.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06997.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06998.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06993.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09005.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09003.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06994.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09011.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09009.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06995.npy

  inflating: DiffWave_Project/data_preprocessed/mels/09017.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06996.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09240.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09015.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09242.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09237.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09236.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09234.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09241.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09006.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09238.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09235.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09228.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09239.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09226.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09229.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09220.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09139.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09232.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09230.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10555.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09244.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09233.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09231.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09227.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09654.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09560.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09223.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09216.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09818.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09224.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09213.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09211.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09002.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09222.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09221.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09625.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09176.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09225.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12254.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/09210.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09207.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09215.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09206.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09197.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09478.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09214.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09202.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09209.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09203.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09193.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09201.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09199.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09198.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09208.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09200.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09192.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09205.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09186.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09175.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09212.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09189.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09174.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09190.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09187.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09176.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09167.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09191.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09204.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09195.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09165.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09164.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09196.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09188.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09194.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09183.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09184.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09163.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09170.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/09185.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09161.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09162.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09154.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09160.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09169.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09156.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09173.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09151.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09153.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09152.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09172.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09157.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09171.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09166.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09147.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09168.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09146.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09150.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09140.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09148.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09159.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09149.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09155.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/09180.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09181.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09134.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09138.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09182.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09128.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09129.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09135.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09158.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09136.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09141.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09137.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09130.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09139.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09133.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09131.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09127.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09132.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09121.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09120.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09116.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09119.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09126.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09118.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10880.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09112.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09125.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09124.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09122.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09001.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09145.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09123.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09115.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09114.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10369.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09102.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09703.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09117.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09103.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09101.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09111.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/09113.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09105.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09099.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09089.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09212.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09100.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09087.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09107.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09094.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09092.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09106.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09096.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09090.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09091.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09086.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09093.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09075.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09079.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09084.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09081.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09098.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09085.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09083.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09104.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09082.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09095.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09097.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09078.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09069.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09071.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09065.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09068.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09088.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/09077.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09070.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09080.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09062.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09064.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09057.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09067.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09052.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09049.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09046.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09048.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09076.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09063.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09055.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09056.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09066.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09053.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09058.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09059.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09043.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09144.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09035.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09054.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09051.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09060.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09047.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09044.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09045.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09022.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09026.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09050.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09039.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09061.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/09074.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09037.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09032.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09021.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09014.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09033.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09024.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09019.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09030.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09034.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09031.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09038.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09025.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09036.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09023.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09016.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09017.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09029.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09344.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09013.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09008.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09015.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09004.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06998.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09027.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09110.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09276.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09028.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09020.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06992.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09005.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09018.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06991.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09001.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09007.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09012.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06999.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09003.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/09002.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09006.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06989.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09000.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06987.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06994.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06981.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09219.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06993.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06988.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06990.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06983.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06985.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06997.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06984.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06982.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06979.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06996.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06995.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09042.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06972.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09011.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06986.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09179.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09103.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06966.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06973.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06980.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06974.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06963.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06964.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06967.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06961.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06959.npy

  inflating: DiffWave_Project/data_preprocessed/mels/11847.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06965.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06978.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06970.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06971.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06975.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06968.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06956.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06947.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06943.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06944.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06955.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06954.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06962.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06951.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06957.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06969.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06950.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06949.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06953.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06960.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06958.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06952.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06946.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06938.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06948.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06935.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06937.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06925.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06929.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06930.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06939.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06924.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06945.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06934.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06932.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06936.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06928.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06921.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06910.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06926.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06920.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06918.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10410.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06915.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06931.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06927.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06923.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06913.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06933.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09378.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06914.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06916.npy

  inflating: DiffWave_Project/data_preprocessed/mels/06922.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06912.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06919.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06906.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06900.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06917.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06895.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06888.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10771.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06891.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06883.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06896.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06881.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06898.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06890.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06904.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06905.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06911.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06903.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06893.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06897.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06901.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06902.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06894.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06887.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06877.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06899.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06884.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06875.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06889.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06892.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06942.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06876.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06874.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06885.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06870.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06866.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06865.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06869.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06860.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06863.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06862.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06880.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06886.npy

  inflating: DiffWave_Project/data_preprocessed/mels/06882.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06855.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06852.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06867.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06859.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06879.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06857.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06878.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06856.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06861.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06868.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06858.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06853.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06873.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09551.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06846.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06844.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06864.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06851.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06845.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06909.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06854.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06849.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06848.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09037.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06838.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06847.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06840.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06835.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06843.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06837.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09786.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06833.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06836.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06839.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06822.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06850.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06829.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06834.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06823.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06830.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06831.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06825.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06821.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06828.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06817.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06819.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06814.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11276.wav

  inflating: DiffWave_Project/data_preprocessed/mels/06820.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06818.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06827.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06832.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06826.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06811.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06812.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06813.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06806.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06816.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06810.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06824.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06797.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06794.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06807.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06800.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09634.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06796.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06798.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06815.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06809.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06795.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06792.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06801.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06799.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06787.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06782.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06808.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06786.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06784.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06802.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06783.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06791.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06785.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06779.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06790.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06777.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06780.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06772.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06775.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06805.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06778.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06793.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06789.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06776.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06788.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06781.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09597.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06771.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06774.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06766.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06765.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12252.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06757.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06760.npy

  inflating: DiffWave_Project/data_preprocessed/mels/06773.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06768.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06755.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06754.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06764.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06758.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06761.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06745.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06762.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06756.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06744.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06753.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06748.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06763.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06752.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06747.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06749.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06767.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06746.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06759.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06992.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06989.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06990.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10113.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09070.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06984.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06750.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06991.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/06985.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06751.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06980.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06975.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06987.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06979.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06973.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10235.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06986.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06966.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06977.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06969.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06971.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06968.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06743.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06988.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06972.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06978.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09334.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06967.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06964.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06981.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06963.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06962.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06957.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06958.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06976.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06965.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06970.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06960.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06953.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06974.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06959.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06951.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06961.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06956.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06952.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12368.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06948.wav

  inflating: DiffWave_Project/data_preprocessed/mels/12143.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06942.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06949.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06940.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06941.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06944.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06937.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06955.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06943.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06934.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06936.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06938.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06930.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06950.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06932.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06954.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10090.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06929.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06935.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06939.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06933.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06923.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06921.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06926.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06928.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06920.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06925.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06919.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06913.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06903.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06900.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06916.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/06924.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06918.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06899.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06907.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06922.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06931.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06915.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06904.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06927.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06895.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06893.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06896.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06901.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06912.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06889.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06917.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06905.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06897.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06894.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06891.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06898.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06890.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06892.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06906.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06888.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/06914.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11342.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06884.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06885.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06902.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06887.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06878.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11064.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06883.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06911.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06882.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06947.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06880.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06881.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06871.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06875.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06868.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06879.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06870.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06910.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06867.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06865.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06869.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06857.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06863.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06886.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06872.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06864.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06873.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06859.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06858.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06862.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06860.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06866.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06855.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/06848.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06851.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06874.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06861.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06853.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06856.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06850.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10074.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06854.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10703.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06838.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06839.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11983.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10121.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06846.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10995.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06834.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06835.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06836.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06841.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06833.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06852.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10271.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06847.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06837.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06845.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06817.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06826.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06823.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06828.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06844.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06824.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/06830.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06832.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06849.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06840.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06821.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06819.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06815.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06827.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06799.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06825.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06829.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06793.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06816.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06831.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06812.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06818.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06802.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06800.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06796.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06795.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06792.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06794.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06822.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06791.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06797.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06801.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06790.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06814.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06786.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06813.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06789.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06798.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06811.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06820.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06784.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06788.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06777.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10465.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/06773.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06809.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06806.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06778.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06810.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06787.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06808.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06780.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06772.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06807.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06782.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06770.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06766.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12097.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06764.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06779.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06771.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06769.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06785.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06781.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06783.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06759.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06757.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06760.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06755.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06768.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06744.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06749.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06758.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06743.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06754.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06761.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06767.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06765.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06756.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06745.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06763.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06746.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12204.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/06750.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06762.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06742.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06737.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06752.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06753.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06741.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06740.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06748.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06735.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06725.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06733.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06727.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06732.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06730.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06729.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06726.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06719.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06714.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06717.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06805.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06747.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06734.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06776.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06736.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06731.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06723.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06751.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06728.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06716.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06713.npy

  inflating: DiffWave_Project/data_preprocessed/mels/06721.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06709.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06724.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06708.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06706.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06722.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06712.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06698.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06701.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06715.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06710.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06720.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06718.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06700.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06689.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06699.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06696.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06687.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06694.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06707.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06711.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06692.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06691.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06681.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06683.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06690.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06693.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06697.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06688.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06677.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06695.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06668.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06674.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06673.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06680.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06686.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06684.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06662.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06666.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06682.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06685.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06678.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06676.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06705.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06661.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06663.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06679.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06675.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06658.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06654.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06660.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06664.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06656.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06655.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06669.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06647.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06652.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06667.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06659.npy

  inflating: DiffWave_Project/data_preprocessed/wavs/09444.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10808.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06653.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09438.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06645.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06643.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06657.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06646.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06636.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06630.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06704.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06665.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06648.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06650.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06639.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06649.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06651.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06946.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06672.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06644.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06634.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06642.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06631.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11309.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06627.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06635.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06621.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06628.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06633.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06632.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06637.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06638.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06629.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06619.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06606.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06625.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06616.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06626.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06622.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06624.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06615.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06610.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06620.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06601.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06614.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06607.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06612.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06623.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06602.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06611.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06618.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06608.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06770.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06617.npy

  inflating: DiffWave_Project/data_preprocessed/mels/06596.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06592.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06600.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06603.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11247.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06599.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06595.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06613.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06609.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06593.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06582.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06583.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06594.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06588.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06591.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06585.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06598.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06586.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06597.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06587.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06579.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06584.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06578.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06577.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06562.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06574.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06589.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06575.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06590.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06581.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06561.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06560.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06567.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06559.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06558.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06556.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06580.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06568.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06576.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06552.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06546.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06573.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06566.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06565.npy

  inflating: DiffWave_Project/data_preprocessed/mels/06555.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06550.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06564.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06563.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06554.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06545.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06548.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06553.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06542.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06547.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06537.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06540.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06533.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06551.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06536.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06842.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06527.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06535.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06513.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06534.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06532.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06549.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06571.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06531.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06572.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06528.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06521.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06557.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06519.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06543.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06541.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06544.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06525.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06524.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06526.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06703.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06530.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06522.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06515.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06512.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06523.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06520.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06518.npy

  inflating: DiffWave_Project/data_preprocessed/mels/06514.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06511.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06508.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06529.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06503.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06517.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06510.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06516.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06498.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10234.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06496.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06495.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06494.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06505.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06501.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06742.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06741.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06509.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06738.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06497.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06504.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06736.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06733.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06500.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06730.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06731.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06727.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06502.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06739.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06732.wav

  inflating: DiffWave_Project/data_preprocessed/mels/06499.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06493.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06740.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06729.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06722.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06717.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06735.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06737.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06734.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06719.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09143.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06641.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06872.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06715.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09586.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06714.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06718.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06726.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06716.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06720.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06705.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06721.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06728.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06713.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06706.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06699.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06701.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06707.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06711.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06708.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06710.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06703.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06712.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06704.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06694.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06696.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06702.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06700.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06695.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11384.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06697.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06693.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/06709.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06685.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06680.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06689.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06683.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06686.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06692.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06698.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06687.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06684.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06682.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06671.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06674.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06688.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06675.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06669.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06667.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06672.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06570.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06676.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09624.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06654.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06663.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06664.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06660.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06681.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06678.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06658.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06659.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06507.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06666.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06679.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06677.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06665.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06673.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06668.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/06670.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06661.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11450.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06655.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06643.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06662.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06653.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06652.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06642.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06651.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06631.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06648.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06650.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06647.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06644.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06636.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06639.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06637.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06646.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06633.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06632.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06638.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06640.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06634.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06649.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06645.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06628.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06641.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06629.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06621.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06635.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06624.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06618.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06626.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09702.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06611.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06619.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06625.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06627.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06602.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/06630.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06610.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06603.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06595.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06615.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06614.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06608.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06617.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06620.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06607.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06600.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06606.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06616.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06598.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06594.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06941.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06671.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06612.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06613.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06592.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06596.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06597.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06591.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06588.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06604.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06586.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06587.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06601.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06599.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06609.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/06605.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06585.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06593.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06572.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06577.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06582.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06576.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06578.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06571.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06584.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06574.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06579.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06573.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11766.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06565.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06570.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06560.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06583.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06581.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06568.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06569.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06564.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06575.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09010.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06580.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06567.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/06561.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06566.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06553.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06547.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06605.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06558.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06563.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06562.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06555.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06559.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06551.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06545.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06548.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06552.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06541.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06531.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06528.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06554.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06543.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06539.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06544.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06546.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06529.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06540.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06520.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06549.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06532.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06527.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06542.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06535.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/06534.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06521.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06526.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06519.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06550.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06537.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06538.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06536.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06518.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06530.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06505.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06502.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06499.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06516.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06515.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06510.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06514.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06507.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06512.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06513.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06506.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/06504.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06508.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06496.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06501.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09178.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06498.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06524.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06517.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06511.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06533.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06509.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06724.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06497.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06500.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10994.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06503.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06525.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06484.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06495.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06478.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06480.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06491.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06482.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06471.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06476.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06469.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06494.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06483.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09036.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06489.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06487.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06473.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06488.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06479.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06475.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06490.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06486.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06481.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06467.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06474.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06485.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06465.npy

  inflating: DiffWave_Project/data_preprocessed/mels/06477.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06464.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06468.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06456.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06463.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06470.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06472.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06462.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06447.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06457.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06446.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06455.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06466.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06435.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06454.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06436.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06452.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06434.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06432.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06438.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06449.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06441.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06444.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06451.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06443.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06453.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06450.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06445.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06433.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06442.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10702.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06439.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06427.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06590.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06437.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06739.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06420.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06419.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06417.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06440.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06431.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06461.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06430.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06448.npy

  inflating: DiffWave_Project/data_preprocessed/mels/06412.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10630.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06423.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06425.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06416.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06415.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06460.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06418.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06424.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06426.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06421.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06411.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06409.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06406.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06405.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06399.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06422.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06414.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06408.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06413.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06403.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06400.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06402.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06398.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06396.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06691.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06404.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06391.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06410.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06390.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06395.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06407.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06389.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06623.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06385.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06397.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06381.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06384.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06379.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06378.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06383.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06401.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06387.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06386.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06392.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06388.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06375.npy

  inflating: DiffWave_Project/data_preprocessed/mels/06382.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06373.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06367.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06369.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06362.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06361.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06356.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06366.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06368.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06365.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06370.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06377.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06376.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06380.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06557.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06657.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06358.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06357.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06363.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06354.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06355.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06374.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06371.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10590.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06344.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06348.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06351.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06341.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06338.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06364.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06347.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06350.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06343.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06349.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06337.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06346.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06339.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06334.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06345.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06342.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06327.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06336.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06353.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06352.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06331.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06333.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06335.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12103.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06332.npy

  inflating: DiffWave_Project/data_preprocessed/wavs/06775.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06323.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06329.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06330.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06340.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06317.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06324.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06311.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06328.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06309.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06304.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06322.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06320.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06319.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06307.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06299.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06297.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06294.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06295.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06305.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06313.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06312.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06301.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06298.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06318.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06308.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06300.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06314.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06321.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06316.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06315.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06306.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06292.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06286.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06287.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06296.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06310.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06283.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06293.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06302.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06282.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06303.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06268.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06279.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06280.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06276.npy

  inflating: DiffWave_Project/data_preprocessed/mels/06273.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06266.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06267.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06284.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06281.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06274.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06285.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06269.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06277.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06288.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06264.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06270.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06271.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06272.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06261.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06262.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06278.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06275.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06259.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06291.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06258.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06260.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06263.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06265.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10228.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06909.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09218.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06459.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06908.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06248.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06244.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06247.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06245.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06490.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06487.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06251.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06486.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06485.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06243.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06488.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06479.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06253.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06489.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06255.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06250.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06246.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06254.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06482.wav

  inflating: DiffWave_Project/data_preprocessed/mels/06252.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06491.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06249.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06477.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06492.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06468.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06466.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06462.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06483.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06484.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06481.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06475.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06480.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06464.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06460.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06478.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06457.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06456.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06459.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06454.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06458.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06467.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06453.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06455.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06465.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06452.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06450.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06476.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06446.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06463.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06447.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/06448.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06442.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06437.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06436.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06472.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06461.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06473.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06474.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09041.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06445.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06449.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06443.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06444.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06439.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10042.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10347.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06451.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11175.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06429.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06433.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06471.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06435.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06432.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09109.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06434.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06427.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06438.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06428.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06417.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06416.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06415.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06413.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06405.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/06422.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06420.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06431.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06426.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06423.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06418.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06425.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06424.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06430.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06421.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06408.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06410.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06398.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06397.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06392.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06394.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06412.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06396.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06414.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06419.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06407.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06387.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/06411.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06406.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06395.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06409.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06393.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06388.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06390.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06384.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06386.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06385.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06383.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06380.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06378.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06381.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06382.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06391.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06399.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06389.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06372.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06371.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06373.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06403.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06402.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06379.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09000.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06372.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09890.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06377.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06376.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/06365.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06364.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06370.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06366.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06359.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06361.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06363.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06375.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06356.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06362.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06358.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06352.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06345.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06350.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06404.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06374.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06357.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06355.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06360.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06367.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06349.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06347.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06353.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06354.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06339.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06340.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06348.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06341.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06330.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06328.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06322.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06327.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06325.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/06343.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06351.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06320.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06318.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06324.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06338.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06344.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06346.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06316.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06317.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06329.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06313.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06311.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06319.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06310.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06323.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06326.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06321.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06342.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06314.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06337.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06331.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06315.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06307.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06336.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06306.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06334.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09748.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06300.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/06298.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06285.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06294.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06335.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06308.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06305.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06312.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06304.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11588.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06309.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06394.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11171.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06297.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06401.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06301.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10043.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06295.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06288.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06296.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06293.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06289.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06281.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06292.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06282.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06290.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06291.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06279.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06280.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06283.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06287.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06284.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06299.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06276.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06259.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06278.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/06274.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06262.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06257.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06277.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06258.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06248.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06249.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06256.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06260.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06261.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06286.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06247.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06245.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06252.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06253.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06251.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06271.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06267.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06275.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06244.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06255.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06269.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06246.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06272.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06241.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06242.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06268.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09073.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/06250.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06273.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06243.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06254.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09069.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06231.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06228.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06270.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06235.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06265.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06266.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06236.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06227.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06232.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06240.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06234.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06843.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11379.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06226.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06220.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06441.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06229.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06218.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06223.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06233.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06225.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06224.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06219.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06205.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06208.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06230.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06214.npy

  inflating: DiffWave_Project/data_preprocessed/mels/06221.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06217.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06215.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06212.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06213.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06222.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06211.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06209.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06207.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06196.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06206.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06197.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06194.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06216.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06204.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06185.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06190.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06189.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06192.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06178.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06183.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06210.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06187.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06198.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06180.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06193.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06182.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06186.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06184.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06181.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06195.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06191.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06188.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06166.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06164.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06173.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06172.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06175.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06177.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06171.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06176.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06179.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06170.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06174.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06165.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06161.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06157.npy

  inflating: DiffWave_Project/data_preprocessed/mels/06162.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06159.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06169.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06202.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06160.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06153.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06154.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06203.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06151.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06201.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06143.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06158.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06152.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06148.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06155.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06145.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06163.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06138.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06136.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06137.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06140.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06132.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06139.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06156.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06146.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06141.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11628.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06135.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06144.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06150.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06149.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06142.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12059.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06130.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06125.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06128.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06290.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06122.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06127.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06131.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06147.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06123.npy

  inflating: DiffWave_Project/data_preprocessed/mels/06121.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06118.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06126.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06129.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06124.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06107.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06114.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06109.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06110.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06120.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06429.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06104.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06112.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06105.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06119.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06111.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06102.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06099.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06113.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06117.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06095.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06116.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06115.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06106.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06101.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06089.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06092.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06080.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06108.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06100.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06090.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06093.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06103.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06084.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06086.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06083.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06081.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06073.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06074.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06091.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06096.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06077.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06094.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06079.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06070.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06078.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06075.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06088.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06076.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06085.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10845.wav

  inflating: DiffWave_Project/data_preprocessed/mels/06072.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06063.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06069.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06082.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06062.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06067.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06061.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11835.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06066.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06068.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06087.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06071.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06056.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06060.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06059.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06058.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12367.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06983.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06055.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06057.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06041.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06040.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06043.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06049.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06051.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06037.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06044.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06052.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06048.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06042.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06039.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06053.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06054.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06045.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06031.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06047.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06032.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06028.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06038.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06050.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06035.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06027.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06024.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06033.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06020.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06046.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06034.npy

  inflating: DiffWave_Project/data_preprocessed/mels/06022.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06036.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06019.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06009.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06013.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06007.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06006.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06005.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06025.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06026.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06014.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06017.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06018.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06016.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06023.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04998.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06002.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06021.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06012.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06011.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06004.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04999.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06015.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06134.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06010.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06008.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06001.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06240.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06239.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06238.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06003.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06539.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06000.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04993.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04996.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06236.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04997.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06232.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06241.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/06229.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06231.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06220.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06230.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06224.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06228.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06234.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06233.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06242.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06235.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06219.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06218.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06237.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06225.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06207.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06226.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06214.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06211.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06200.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06205.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06227.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06222.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06215.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10001.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06223.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06221.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06217.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06202.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06210.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06208.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06203.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/06209.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06206.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10388.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10989.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06201.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06200.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06194.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06195.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06216.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06204.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06198.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06196.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06197.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06188.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06191.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06199.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06176.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06177.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06184.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06186.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06187.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06193.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06190.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06183.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06182.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/06171.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06174.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06167.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06169.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06168.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06180.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06166.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06181.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06165.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06175.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06192.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06185.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06189.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06172.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06173.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06163.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06151.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06164.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06162.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06170.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06155.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06161.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06143.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06141.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06150.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06157.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06158.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06065.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06160.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06159.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06140.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06145.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/06148.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06135.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06153.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06144.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06154.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06156.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06139.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06152.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06137.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06142.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06149.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06136.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06134.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06133.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06129.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06132.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06138.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06128.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06118.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06130.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06126.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06111.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06110.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06131.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06124.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06122.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06109.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06120.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06116.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06102.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06106.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/06121.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06127.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06103.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06117.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06112.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06104.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06125.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06108.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06101.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06092.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06123.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06113.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06105.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06119.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06100.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06099.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06098.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06107.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06097.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06090.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06096.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06369.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06725.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06086.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06095.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06075.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06074.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06072.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06070.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06238.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06076.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06333.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06094.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/06093.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06087.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06179.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06091.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06069.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06081.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12253.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06089.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06080.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06077.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06085.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06079.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06030.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06065.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06073.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06088.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06082.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06071.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06068.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06063.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06078.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06047.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06061.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06040.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06036.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06062.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06053.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06067.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06066.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06046.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06058.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06064.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06056.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/06038.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06059.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06052.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06054.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06060.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06045.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06044.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06055.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06043.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06035.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06039.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06057.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06041.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06037.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06034.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06033.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06027.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06050.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06042.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06023.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06029.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06019.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09816.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11066.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06012.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06007.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06020.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06031.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/06024.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06010.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06025.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06014.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06032.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06021.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06051.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06009.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06018.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06030.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06026.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06013.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06028.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06022.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06011.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06005.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06003.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06015.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06004.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06006.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06000.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06008.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04988.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04977.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04982.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04980.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04986.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04998.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04997.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06002.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06001.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04999.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04996.wav

  inflating: DiffWave_Project/data_preprocessed/mels/04990.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04992.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04993.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04991.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04987.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04985.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10730.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04989.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04976.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04978.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11350.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04995.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04972.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04973.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04994.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04979.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04981.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04974.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04962.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04959.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04975.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04966.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04950.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04953.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04971.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04968.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04967.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04970.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04949.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04963.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04942.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04954.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04961.npy

  inflating: DiffWave_Project/data_preprocessed/mels/04944.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04955.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04969.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04946.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04964.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04960.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04951.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04937.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04958.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04945.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04957.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04943.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04965.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04952.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04956.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04939.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04940.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04941.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04934.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04932.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04927.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04938.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04931.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04926.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04924.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04936.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04907.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04935.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04925.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04933.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04923.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04919.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04910.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04906.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04930.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04929.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04928.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04904.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04903.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04913.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04901.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04911.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04922.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04908.npy

  inflating: DiffWave_Project/data_preprocessed/mels/04920.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04905.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04894.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04892.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04909.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04897.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04921.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04912.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04893.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04899.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04896.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04902.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10879.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04898.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04890.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04895.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06470.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04900.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04880.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06493.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04889.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04917.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10198.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04918.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04995.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04891.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04916.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04883.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04881.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04886.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04879.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04878.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04873.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04885.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04882.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04874.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04884.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06877.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04875.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04866.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04872.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04871.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04867.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04863.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09735.wav

  inflating: DiffWave_Project/data_preprocessed/mels/04877.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04860.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04865.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04876.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04858.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04864.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04849.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04856.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04845.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04868.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04848.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04850.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04870.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04851.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04843.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04847.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04838.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04846.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04869.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04841.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04857.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04836.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04840.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04861.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04859.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04844.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04862.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04835.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04839.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04833.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04837.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04823.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04825.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04834.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04814.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04831.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04832.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04813.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04830.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04855.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04842.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04829.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04812.npy

  inflating: DiffWave_Project/data_preprocessed/mels/04811.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04827.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04822.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04854.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04806.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04803.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04801.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04800.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04797.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04804.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04798.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04808.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04795.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04809.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04828.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04815.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04805.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04818.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04817.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04810.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04816.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04807.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04826.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04789.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04791.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04788.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04799.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10618.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04820.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04794.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04786.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04792.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04793.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04824.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04802.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04796.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04790.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04821.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04787.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04776.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04774.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04781.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04783.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04772.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04773.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04764.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04782.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04779.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04778.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04780.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04777.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04765.npy

  inflating: DiffWave_Project/data_preprocessed/mels/04768.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04770.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04757.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04766.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04755.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04853.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04769.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04762.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04775.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12369.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04767.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04771.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06168.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04760.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04761.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04763.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04758.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04759.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11419.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04748.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04750.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04749.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04752.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04756.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04746.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04747.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11907.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04990.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04751.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04744.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04984.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06098.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04992.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04977.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04979.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/04989.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04981.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04980.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04973.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06213.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04975.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04986.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04991.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04745.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04978.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09706.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04968.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04743.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04982.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04971.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04985.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04976.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04987.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04988.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04967.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04983.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09930.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04972.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04956.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10662.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11208.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04974.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04955.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04959.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04964.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/04957.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04941.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04948.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04945.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04938.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04939.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04937.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04960.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04958.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04950.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04951.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04954.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04949.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04965.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04966.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04961.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04947.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04962.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04952.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04963.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04940.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04953.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04946.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04931.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04942.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/04944.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04930.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04932.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04943.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04929.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04918.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04919.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04916.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04909.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04915.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04924.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04913.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04910.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04935.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04928.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04927.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04926.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04908.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04921.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04923.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04907.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04917.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04936.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04920.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04922.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04925.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04912.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04904.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04903.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04914.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04894.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04896.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/04905.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04911.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04906.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04984.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04892.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04887.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04885.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04899.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11662.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04902.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04888.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09961.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04897.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04882.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04893.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04890.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04891.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04898.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04889.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04878.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04876.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04872.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04874.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04884.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04854.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04873.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04895.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04881.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04879.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04886.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04871.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04864.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/04883.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04880.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04877.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04855.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04863.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04862.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04857.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04847.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04846.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04875.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04860.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04859.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04858.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04856.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04848.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04853.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04850.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04861.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04851.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04849.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04844.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04838.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06257.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06239.npy

  inflating: DiffWave_Project/data_preprocessed/wavs/04852.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04845.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04869.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10981.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04867.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04835.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04841.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04834.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04840.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04868.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04839.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04842.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04843.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04870.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04825.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04823.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04830.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04832.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04829.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04828.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04818.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04824.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04831.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04821.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04814.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04812.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04833.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04816.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04827.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04810.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04811.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04819.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04808.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04826.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04822.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/04809.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04805.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04799.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04807.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04820.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04815.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04817.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04804.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04813.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04800.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04797.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04796.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04780.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04787.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04775.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04791.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04792.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04798.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04806.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04786.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04793.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04781.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04790.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04803.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04788.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04783.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04794.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04785.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04773.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04766.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04795.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/04789.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04774.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04776.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04779.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04784.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04777.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04782.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04771.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04767.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04765.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04778.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04763.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04764.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04748.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04746.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04756.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04743.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04752.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04757.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04758.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04754.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04762.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04760.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04759.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04772.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04751.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/04750.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04761.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04745.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04747.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04755.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04744.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04740.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04741.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04770.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04742.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04749.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04753.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04739.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06360.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04731.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04723.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04728.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04733.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04729.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04727.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04734.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04725.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04724.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04736.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12181.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04730.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04718.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04713.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12058.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04716.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04735.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04732.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04717.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04726.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04710.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04711.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04715.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04721.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04722.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04719.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04709.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04720.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04712.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12403.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10270.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/12330.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04703.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04696.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04687.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04688.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04700.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04901.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04701.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04705.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04714.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04706.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04698.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04704.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12435.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04692.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04697.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04689.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04702.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04691.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04699.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04678.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04694.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04684.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04677.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04665.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04686.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04690.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04679.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04695.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04685.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04676.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04693.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04683.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04668.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04681.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04667.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04682.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04664.npy

  inflating: DiffWave_Project/data_preprocessed/mels/04669.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04657.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04674.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04680.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04670.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04673.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04666.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04653.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04658.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04662.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04663.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04652.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04650.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04649.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04647.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04659.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04656.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04655.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04661.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04651.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04640.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04631.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04633.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04660.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04654.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04644.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04645.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04642.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06303.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04648.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04643.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11624.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04637.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04635.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06326.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04646.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04675.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04641.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04636.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04627.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04626.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04634.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10844.npy

  inflating: DiffWave_Project/data_preprocessed/wavs/12445.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04628.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06017.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04629.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04630.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04625.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04618.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04615.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04611.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04632.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04623.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04621.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04622.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04617.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04612.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04600.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04624.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04620.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04616.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04594.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04609.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04610.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04599.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04614.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04613.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04598.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04595.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04592.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04586.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04593.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04619.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04597.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04587.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04588.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04581.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04585.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04596.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04580.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04590.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04589.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04606.npy

  inflating: DiffWave_Project/data_preprocessed/mels/04571.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04591.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04605.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04579.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04584.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04608.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04576.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04561.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04563.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04568.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04566.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04578.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04575.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04574.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04577.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04583.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04607.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04570.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04560.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04582.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04565.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04604.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04569.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04557.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04562.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04564.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04558.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04553.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04567.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04556.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04559.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04544.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04535.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04547.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04554.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04552.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04546.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04540.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04551.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04603.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04549.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04555.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04536.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04548.npy

  inflating: DiffWave_Project/data_preprocessed/mels/04550.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04545.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04531.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04532.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04528.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04541.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04534.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04527.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04530.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04543.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04533.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04537.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04542.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04518.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04517.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04515.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04522.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04523.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04526.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04524.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04520.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04525.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04516.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04738.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11487.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04499.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04529.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04521.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04511.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04510.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11693.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04514.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04519.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04503.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04508.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04513.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04501.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04504.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04509.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04512.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04500.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04502.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04739.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04496.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04505.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04736.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/04734.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04729.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04741.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04495.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04737.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04498.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04742.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04497.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04735.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04740.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04493.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04727.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04738.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04732.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04728.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04719.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04733.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04494.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04731.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04718.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04721.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04730.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04717.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04702.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04704.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04709.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04714.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/04723.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04726.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04722.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04715.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04708.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04720.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04703.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04706.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04710.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04716.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04711.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04707.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04713.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04507.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04712.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04699.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04705.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04698.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04688.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12142.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04700.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11136.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04701.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04697.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04686.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04696.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04691.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04682.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04690.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04695.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04692.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04684.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04678.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04679.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/04674.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04708.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04677.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04666.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04683.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04673.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04689.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04685.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04687.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04671.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04675.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04681.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04680.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04676.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04664.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04672.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04670.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04694.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04667.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04660.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04669.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04656.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04659.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04665.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04663.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04668.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04658.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04602.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04650.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/12163.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04657.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04655.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04644.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04649.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04651.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04648.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04647.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04638.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04639.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04642.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04643.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04645.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04672.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04652.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04653.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04654.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04635.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04634.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04637.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04641.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04646.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04628.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04633.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09923.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04640.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04636.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04625.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10581.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04620.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/04631.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04622.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04948.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04626.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04632.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09653.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04616.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04617.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04621.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04608.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04604.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04612.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04624.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04615.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04618.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04603.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04619.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04607.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04609.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04623.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04600.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04614.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04606.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04611.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/04601.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04613.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04605.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04599.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04627.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04586.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04602.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04598.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04610.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04593.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04592.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04587.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04580.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04582.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04588.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04589.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04591.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04585.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04570.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04584.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04581.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04590.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04597.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04558.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04568.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04572.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04583.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04574.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04579.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04573.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/04576.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04578.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04571.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04559.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04577.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04596.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04565.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04566.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04575.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04555.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04567.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04553.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04556.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04569.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04561.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04554.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04552.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04541.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04562.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04543.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04548.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04549.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04551.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04547.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04557.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04538.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04550.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04542.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04530.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04537.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04524.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12289.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04545.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/04529.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04540.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04536.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04535.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04544.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04546.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04525.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04534.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04523.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04533.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04519.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04517.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04513.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04507.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04539.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04515.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04522.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04560.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04528.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04527.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04526.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04514.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04521.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04520.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04518.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04511.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/04508.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04516.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04510.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04595.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04498.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04502.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04512.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04491.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04506.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04509.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04539.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04499.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04489.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04495.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04505.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04488.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04494.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04504.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04480.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04484.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04503.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04479.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04630.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04490.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04497.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04481.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04476.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04496.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04493.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04486.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04487.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04477.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/04482.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04483.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04492.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04461.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04485.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04475.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04474.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04463.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04470.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04465.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04460.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04458.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04472.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04444.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04464.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04478.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04473.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04446.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04447.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04462.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04451.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04449.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04453.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04457.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04471.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04452.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04455.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04456.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04450.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04448.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04459.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/04445.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04454.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04441.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04443.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04442.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09559.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10368.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04468.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04431.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04429.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04424.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04469.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04419.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11283.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04970.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04785.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04440.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04423.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04436.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04428.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04433.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04416.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04420.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04435.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04437.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04430.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04417.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/04422.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04434.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04414.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04415.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04412.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04405.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04418.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04432.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04427.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04421.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04401.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04426.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04425.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04413.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04410.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04402.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04409.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04403.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04400.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04393.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04392.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04390.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04408.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04391.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04404.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04411.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04388.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04395.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04389.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04386.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/04398.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04394.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04396.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04387.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04399.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04397.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04378.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04385.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04383.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04372.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04381.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06264.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04374.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04384.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06804.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11026.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04380.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04382.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04379.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04370.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04369.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04362.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04363.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04361.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04360.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/04377.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04373.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11768.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04371.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04357.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04366.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11986.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04365.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04364.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11139.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04355.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04356.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04358.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04353.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04368.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04359.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04367.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04354.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04345.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04339.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04332.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04346.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04349.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04351.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04335.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04336.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04348.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04328.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04347.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04344.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04350.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04352.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04330.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04331.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/04322.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04327.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04334.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04337.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04324.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04333.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04329.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04325.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04338.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04321.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04326.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04323.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04769.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04342.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04317.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04314.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04315.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11804.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10444.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04318.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04320.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04316.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04306.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04319.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04309.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12251.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04307.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11490.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10477.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04303.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12469.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10517.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04313.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04305.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12096.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04312.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04343.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/04301.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04300.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04295.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04302.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10079.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04304.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04290.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04297.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04293.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04291.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04283.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04484.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04273.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04308.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04296.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04492.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04289.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04288.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04287.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04298.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04486.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04292.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04294.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04284.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/04282.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04299.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04286.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04483.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04491.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04285.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04274.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04478.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04481.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04479.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04476.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04475.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04480.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04474.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04487.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04485.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04482.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04473.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04469.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04470.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04266.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04477.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04490.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04276.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04279.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04277.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04472.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04471.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04280.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04467.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04468.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04261.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04259.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04267.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04263.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04260.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04462.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04272.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04271.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04256.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/04281.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04278.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04465.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04258.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04466.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04262.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04264.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04254.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04265.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04255.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04252.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04251.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04250.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04464.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04253.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04257.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04463.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04244.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04460.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04247.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04453.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04243.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04447.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04455.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04441.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04444.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04245.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04461.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04449.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04451.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04248.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/04246.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04443.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04442.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04452.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04249.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04450.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04445.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04438.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04439.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04436.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04434.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04432.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04437.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04446.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04440.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04448.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04454.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04459.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04433.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04418.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04435.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04427.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04429.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04422.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04412.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04270.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04421.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04428.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04410.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04423.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04407.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04430.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04408.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04417.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04415.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04419.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04489.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04414.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04402.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04401.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04416.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04409.npy

  inflating: DiffWave_Project/data_preprocessed/mels/04394.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04404.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04411.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04413.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04403.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04420.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04426.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04397.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04400.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04405.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04406.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04396.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04387.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04385.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04382.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04377.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04372.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04390.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04458.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04384.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04431.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04398.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04395.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04388.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04386.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04378.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04380.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04367.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04370.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04399.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04376.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04379.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04389.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04373.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04364.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04374.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04381.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04368.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04369.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04383.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04375.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04361.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04393.npy

  inflating: DiffWave_Project/data_preprocessed/mels/04366.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04362.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04802.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04353.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04351.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04371.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04358.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12060.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04342.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04365.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04356.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04888.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04457.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04355.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04363.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04357.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04352.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04337.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04348.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04349.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04334.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04341.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04344.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04343.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04339.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04335.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04319.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04345.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04322.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04354.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04333.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04347.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04338.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04340.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04350.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04329.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04346.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04321.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04320.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04314.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04336.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04332.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04331.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04312.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04318.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04313.npy

  inflating: DiffWave_Project/data_preprocessed/mels/04305.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04303.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04301.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04311.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04316.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04317.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04315.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04330.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04309.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04304.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04323.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04302.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04310.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04297.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04306.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09785.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04866.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04298.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04307.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04289.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04300.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04308.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04296.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04295.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04299.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04294.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09891.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04291.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04327.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04280.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04328.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04282.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04326.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04281.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04286.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04288.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04272.npy

  inflating: DiffWave_Project/data_preprocessed/mels/04284.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04271.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04276.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04290.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04267.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04273.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04287.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04285.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04277.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04275.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04283.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04279.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04264.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04269.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04259.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04260.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04278.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04265.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04270.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04274.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04256.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04258.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04360.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04268.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04263.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09817.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04252.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04257.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04255.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04248.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04254.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04266.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04247.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04253.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04244.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04250.npy

  inflating: DiffWave_Project/data_preprocessed/mels/04232.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09743.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04251.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04243.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04240.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04245.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04242.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04246.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04241.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04222.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04237.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04239.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04236.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04235.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04231.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04238.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04225.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04230.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04233.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10554.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04532.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04234.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09853.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04223.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04229.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04214.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04213.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04218.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04207.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04216.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04215.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04204.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12064.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04249.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04201.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04221.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04220.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04226.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04219.npy

  inflating: DiffWave_Project/data_preprocessed/mels/04217.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04224.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04212.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04209.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04208.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04206.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04192.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04199.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04202.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04190.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04200.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04182.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04205.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04203.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04211.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04210.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04197.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04183.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04198.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04191.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04178.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04186.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04180.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04188.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04187.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04184.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04174.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04181.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04179.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04185.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04171.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04168.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04177.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04189.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04170.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04175.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04164.npy

  inflating: DiffWave_Project/data_preprocessed/mels/04196.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04837.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04156.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04176.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04161.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04160.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04166.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04173.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04172.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04152.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04147.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04155.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04165.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04167.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04153.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04151.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04157.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04169.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06049.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04144.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04145.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04149.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04195.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04159.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04439.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04142.npy

  inflating: DiffWave_Project/data_preprocessed/mels/04158.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04148.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04150.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04136.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04154.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04139.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04143.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04146.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04138.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04121.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04140.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04132.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04125.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04133.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04141.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04115.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04123.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04112.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04128.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04135.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04134.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04114.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04102.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04111.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04126.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04113.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04137.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04116.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04127.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04119.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04122.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04103.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04117.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04120.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04107.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04105.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04124.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04104.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04108.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04110.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04131.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04101.npy

  inflating: DiffWave_Project/data_preprocessed/mels/04100.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04093.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04092.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04097.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04262.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04096.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04088.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04084.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04118.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04106.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04109.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04376.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04392.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04094.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04095.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04091.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04573.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04089.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04086.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04078.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04079.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04083.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04082.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04081.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04066.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04072.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04087.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09783.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04073.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04071.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04090.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04067.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04076.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04080.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04074.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04065.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04085.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04075.npy

  inflating: DiffWave_Project/data_preprocessed/mels/10258.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09667.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04077.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12218.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04057.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04068.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04060.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04070.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04062.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04061.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04059.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04050.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04069.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04054.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04053.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10652.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12021.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06523.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04046.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04051.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04042.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04045.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04044.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04048.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04055.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04052.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04043.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04058.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04047.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04040.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04056.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04049.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04039.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04037.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04036.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04035.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04034.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04032.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04041.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04023.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04021.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04019.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04017.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04016.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04018.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04009.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04011.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04010.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04001.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04014.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04038.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04015.npy

  inflating: DiffWave_Project/data_preprocessed/mels/04022.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04006.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04013.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04033.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04003.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04031.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04012.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04004.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04027.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03998.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09967.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04029.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04002.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04020.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04007.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04008.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03999.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04026.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04005.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04000.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10951.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04238.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04242.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03997.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04030.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10910.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04241.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03993.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12288.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04028.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12465.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10807.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10554.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04237.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04239.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04230.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04229.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03996.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04240.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11916.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04235.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/04231.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04236.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04216.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04219.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04220.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04228.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04224.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04222.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04233.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04223.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04232.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04225.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04218.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04215.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04234.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04210.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04217.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04199.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04212.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04214.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04198.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04227.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04195.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04192.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04193.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04200.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04221.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/04211.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04186.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04185.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04183.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04180.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04196.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04213.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04226.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04190.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04184.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04189.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04197.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04182.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04194.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04177.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04175.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04165.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04176.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04188.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04173.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04191.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04209.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04187.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04174.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04162.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04208.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/04149.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04163.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04157.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04151.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04178.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04148.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04164.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04181.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04155.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04154.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04150.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04153.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04156.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04160.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04207.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04158.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04159.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04145.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04205.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04144.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04170.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04161.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04172.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04171.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04152.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04179.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04141.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/04147.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04139.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04146.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04143.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04142.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04169.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04130.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04133.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04131.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04124.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04121.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04132.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04134.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04115.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04119.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04140.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04125.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04206.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04120.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04126.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04204.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04114.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04123.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04127.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04113.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04128.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04129.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04116.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04111.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/04117.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04112.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04118.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04109.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04099.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04108.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04122.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04137.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04107.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04101.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04110.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04105.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04106.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04084.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04087.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04098.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04138.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04095.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04096.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04090.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04088.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04081.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04086.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04078.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04077.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04083.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04097.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04085.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04093.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/04091.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04092.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04168.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04089.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04094.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04075.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04100.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04080.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04067.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04068.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04073.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10915.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04066.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04934.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04079.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04076.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04072.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04082.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04104.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04074.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04203.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04056.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04054.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04063.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04058.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04059.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04061.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04060.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04065.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04055.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04051.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04053.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04025.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04062.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04039.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04043.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/04069.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04325.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04048.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04064.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04041.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04052.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04044.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04035.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04040.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04042.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04030.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04049.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04036.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04021.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04047.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04037.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04050.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04024.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04038.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04019.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04029.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04023.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04028.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04027.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04026.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04022.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04046.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04025.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04057.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04020.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04045.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04016.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04014.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04015.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04007.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04017.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04018.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04009.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04034.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/04008.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10770.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04003.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04004.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04011.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04064.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04012.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11948.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04002.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04006.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03995.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10515.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04013.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04000.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04001.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04564.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04010.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03996.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11867.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10112.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03989.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04033.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03986.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04005.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03990.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03997.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04725.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10012.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03991.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03983.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03993.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03975.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03974.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03971.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03985.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03984.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03973.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03979.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03987.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03977.npy

  inflating: DiffWave_Project/data_preprocessed/mels/03980.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03994.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03982.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03992.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03978.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03954.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03976.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03988.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03969.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03951.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03950.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03981.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03970.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03955.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03972.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03953.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03949.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03968.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03948.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03942.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03943.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03937.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03941.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03936.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03952.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03965.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03946.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03964.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03938.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03966.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03963.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03939.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03947.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03962.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03967.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03940.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03961.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03945.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03944.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03931.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03934.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03933.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03935.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03932.npy

  inflating: DiffWave_Project/data_preprocessed/mels/03929.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03960.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03959.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03923.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03915.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03913.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03920.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03911.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03914.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03905.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03904.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03912.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03930.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03908.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03906.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03909.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03922.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03901.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03924.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03919.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03916.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03921.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03907.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03910.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03896.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03902.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03900.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03918.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03917.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03898.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03899.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03897.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03894.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03903.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03895.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03927.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03883.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03882.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03876.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03889.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03884.npy

  inflating: DiffWave_Project/data_preprocessed/mels/03874.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03870.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03868.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03890.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03879.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03878.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03873.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03875.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03871.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03877.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03881.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03928.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03866.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03887.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03867.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03869.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03888.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03886.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03872.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03885.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03880.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03864.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03863.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04130.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03865.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03857.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03958.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03853.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03848.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03855.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10333.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03861.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06147.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03893.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03849.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12238.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03843.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03862.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03854.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03852.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03860.npy

  inflating: DiffWave_Project/data_preprocessed/mels/03856.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03847.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03844.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03839.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03840.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03851.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03850.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03846.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03838.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03837.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03845.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03831.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03842.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03818.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03841.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03836.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09511.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03825.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03826.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03833.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03824.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03823.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03810.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03814.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03809.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03834.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03817.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03812.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03813.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03815.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03832.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03806.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03819.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03835.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03808.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03827.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03798.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03807.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03829.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03830.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03805.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03816.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03828.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03801.npy

  inflating: DiffWave_Project/data_preprocessed/mels/03811.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03802.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03803.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03787.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03786.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03822.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03791.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03800.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03788.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03790.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03789.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03797.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03781.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03804.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03795.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03799.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03774.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03792.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03780.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03776.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03771.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03778.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03773.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03777.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03794.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03793.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03782.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03796.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03770.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03779.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03766.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03772.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03785.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03775.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03767.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03756.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03765.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03769.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03764.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03757.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03753.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03754.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03758.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03762.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03752.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03751.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03743.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03750.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03759.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03747.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03768.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03992.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03991.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03746.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03763.npy

  inflating: DiffWave_Project/data_preprocessed/mels/03761.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03745.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03744.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03988.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03760.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03986.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03755.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04407.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03987.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03983.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03989.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03990.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03985.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03979.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03972.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03969.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03974.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03980.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03984.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03970.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03971.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03981.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03973.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03859.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03976.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03982.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04099.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03978.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03962.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03958.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03966.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10188.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03960.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/03977.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03965.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03955.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03975.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03821.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03961.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03968.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03959.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03967.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03957.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03943.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03949.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03956.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03936.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03947.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03954.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03953.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03951.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03950.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03948.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03940.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03937.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03941.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03942.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03938.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03926.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03935.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03939.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03946.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03945.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03923.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03952.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03932.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/03921.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03934.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03920.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03922.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03916.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03924.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03925.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03917.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03908.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03914.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03909.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03910.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03905.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03904.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03930.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03902.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03933.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03944.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03931.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03901.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03906.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03919.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03913.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03915.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03918.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03903.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03912.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03900.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/03911.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03891.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03899.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03893.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03907.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03895.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03894.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03886.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03892.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03889.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03890.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03929.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03887.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03881.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03878.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03882.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03872.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03880.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03888.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03884.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03870.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03898.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03879.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03877.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03871.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04228.npy

  inflating: DiffWave_Project/data_preprocessed/wavs/03868.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04032.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03869.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03883.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03876.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03957.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03860.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03885.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03875.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04754.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03853.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03874.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03873.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03863.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03858.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03848.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03854.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03862.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03859.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03845.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03842.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03865.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03864.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03840.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03861.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03855.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03852.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/03846.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03850.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03839.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03856.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03837.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03851.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03831.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03844.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03841.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03857.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03849.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03847.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03838.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03823.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03843.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03829.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03827.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03832.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03822.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03830.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03835.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03836.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04662.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04194.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03828.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03821.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03814.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03819.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/03815.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03826.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03824.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03816.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03825.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03818.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03820.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03809.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03792.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03807.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03810.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03805.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03813.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03817.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03806.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03796.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03804.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03808.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03793.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03811.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03797.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03812.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03789.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03787.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03798.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03795.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03783.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03782.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03790.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03791.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03784.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03794.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03803.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03801.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03777.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03786.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/03780.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03788.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03775.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03774.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03785.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03773.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03778.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12026.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03771.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03772.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03781.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03779.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10409.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03766.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03765.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03763.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03762.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03767.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03764.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11308.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03758.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03897.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03776.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03760.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11658.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03802.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03999.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03759.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03754.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03755.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03768.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03751.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/03749.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03750.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03761.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03756.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03757.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03743.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03753.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03752.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03741.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03727.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03728.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03745.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03737.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03742.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03748.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03738.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03746.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03744.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03747.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03740.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03726.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03733.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03739.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03721.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03731.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03730.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03713.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03712.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03732.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03719.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03729.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03724.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03723.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03716.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03714.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03711.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03718.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03725.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03715.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03706.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03722.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03709.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03708.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03705.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03703.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03720.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03710.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03717.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03707.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03697.npy

  inflating: DiffWave_Project/data_preprocessed/mels/03695.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03696.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03694.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03689.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03685.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03700.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03704.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03699.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03684.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03690.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03698.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03686.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03688.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03682.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04269.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03691.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03736.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03681.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03683.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03674.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03680.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03673.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03672.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03693.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03692.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03676.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03670.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03677.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03675.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03671.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03660.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03656.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03687.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03654.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03678.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04915.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03679.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03661.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03658.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03667.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03664.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03657.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03666.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03659.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03655.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03663.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03647.npy

  inflating: DiffWave_Project/data_preprocessed/mels/03646.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03662.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03665.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03645.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03644.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03651.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03648.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03641.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03650.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03642.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03640.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03653.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03652.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03649.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03635.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03625.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03639.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03627.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03632.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03618.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03624.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03621.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03614.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03636.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03634.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03630.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03629.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09550.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03626.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03628.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03633.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03643.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03631.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03617.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03616.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03619.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03613.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03611.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03620.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04341.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03609.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04167.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03610.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03605.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03622.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03608.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03604.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03606.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03612.npy

  inflating: DiffWave_Project/data_preprocessed/mels/03623.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10555.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03607.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03600.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03596.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03592.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03598.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03615.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10294.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12412.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09519.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06084.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03601.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03589.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03590.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04639.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04163.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03584.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03591.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03588.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03594.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03595.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03585.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03578.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03583.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03593.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03582.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03599.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03586.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03597.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03587.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03575.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03568.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03576.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03562.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03580.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03572.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03559.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03563.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03571.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03581.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03574.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03577.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03557.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03579.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03569.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03560.npy

  inflating: DiffWave_Project/data_preprocessed/mels/03556.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03551.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03552.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03573.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03555.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03543.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03570.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03554.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03558.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03553.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03544.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03550.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03547.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03545.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03536.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03548.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03549.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03542.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03561.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03533.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03534.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03537.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03524.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03535.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03540.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03539.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03546.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09477.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03532.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03567.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03525.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03526.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03522.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03520.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09102.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03519.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03527.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03541.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03566.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03528.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03784.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03521.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03508.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03531.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03538.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03515.npy

  inflating: DiffWave_Project/data_preprocessed/mels/03514.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03509.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03512.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03506.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11314.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03516.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03517.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03511.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03523.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03507.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03513.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03505.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03510.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03518.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03503.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03499.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03498.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03737.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03740.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03504.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03501.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03741.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03500.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03497.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03735.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03736.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03730.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03502.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03728.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03738.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03733.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03719.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03721.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03723.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03725.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03739.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03734.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03722.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03727.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03729.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03732.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/03731.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03718.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03724.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03713.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03712.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03720.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03726.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03711.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03717.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03707.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03715.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03494.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03496.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03714.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03697.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03694.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03698.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03705.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03716.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03704.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03701.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03708.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03696.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03495.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03703.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03693.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03692.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03702.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03690.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03695.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03689.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/03688.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03700.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03706.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03691.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03687.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03686.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03684.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03679.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03699.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03680.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03683.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03668.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03672.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03681.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03682.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03493.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03678.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03749.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03675.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03670.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03667.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03685.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03664.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03661.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03669.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/03658.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03565.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03660.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03674.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03657.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03656.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03654.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03671.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03662.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03649.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03666.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03647.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03665.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04071.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03639.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03659.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03673.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03663.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03646.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03645.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03669.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03653.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03643.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03702.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03648.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03655.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03652.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03635.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03651.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03632.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03627.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03621.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03629.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/03644.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03638.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03650.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03640.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03633.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03630.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03637.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03631.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03634.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03623.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03624.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03625.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03636.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03628.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03622.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03626.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03616.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03608.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03613.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03614.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03620.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03612.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03618.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03619.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03617.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03593.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03596.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03599.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03615.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03609.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/03598.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03610.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03595.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03601.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03597.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03607.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03600.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03591.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03588.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03611.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03594.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03578.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03584.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03586.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03603.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03602.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03580.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03585.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03574.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03573.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03590.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03589.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03583.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03579.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03577.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03592.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03571.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03587.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03581.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03561.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03564.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03582.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03562.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03576.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03559.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03560.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/03563.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03555.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03566.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03557.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03552.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03558.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03575.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03551.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03565.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03550.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03556.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03545.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03547.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03549.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03554.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03553.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03544.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03572.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03541.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03548.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03538.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03543.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03546.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03531.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03539.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03542.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/03532.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03540.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03530.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03529.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03526.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03527.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03525.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03528.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03518.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03517.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03524.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03520.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03514.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03512.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03523.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03536.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03537.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03511.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03569.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03513.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03519.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03521.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03522.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03503.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11982.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03510.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03516.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03606.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03515.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09261.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04136.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03504.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03501.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03502.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/04275.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03508.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03509.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03570.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03535.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03497.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03505.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03496.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04501.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03490.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03483.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03491.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03485.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03480.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03478.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03477.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03495.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03494.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03493.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03500.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03489.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03492.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03482.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03498.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03479.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03499.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03476.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03487.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03474.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03484.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03471.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03481.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03475.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03468.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03488.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03457.npy

  inflating: DiffWave_Project/data_preprocessed/mels/03464.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03462.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03486.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03469.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03467.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03460.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03466.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03470.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03463.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03461.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03448.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03455.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03451.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03459.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03458.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03449.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03453.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03454.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03452.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03456.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03447.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03443.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03465.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03439.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03444.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03450.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03435.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03442.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03434.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03446.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03445.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03433.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03429.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03438.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03426.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03428.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03437.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03425.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03427.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03421.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03416.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03414.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03412.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03419.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03436.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03432.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10092.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03417.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03431.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03422.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03430.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03420.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03415.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03411.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03406.npy

  inflating: DiffWave_Project/data_preprocessed/mels/03424.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03408.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03404.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03413.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03418.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03394.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03393.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03423.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03397.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03400.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03401.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03405.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03386.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03407.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03399.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03398.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03402.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03390.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03384.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03387.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03389.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03395.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03396.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03388.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04425.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03403.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03834.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03382.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09413.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03473.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03368.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11457.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03392.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03385.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03391.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03377.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03383.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12134.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10426.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03677.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03370.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03371.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04293.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03378.npy

  inflating: DiffWave_Project/data_preprocessed/mels/03379.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03530.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03373.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03366.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11736.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03369.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03372.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03367.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03375.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03358.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03360.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03374.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03376.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03356.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03355.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03357.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03362.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03365.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03364.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03361.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03359.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03353.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03350.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03351.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03348.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03363.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03354.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03352.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03342.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03349.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03347.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03335.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03336.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03343.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03332.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03339.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03328.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03330.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03337.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03329.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03331.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03319.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03322.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03340.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03318.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03341.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03324.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03323.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03338.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03326.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03333.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03312.npy

  inflating: DiffWave_Project/data_preprocessed/mels/03317.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03334.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03325.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03321.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03316.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03320.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03315.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03313.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03311.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03327.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03302.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03301.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03299.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03307.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03305.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03290.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03291.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03296.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03284.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03295.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03285.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03279.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03314.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03304.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03300.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03286.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03293.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03287.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03298.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03306.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03288.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03297.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03283.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03303.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03282.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03281.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03292.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03346.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03275.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03264.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03294.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03280.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03289.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03310.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03271.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09477.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03262.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03274.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04311.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03266.npy

  inflating: DiffWave_Project/data_preprocessed/mels/03261.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03267.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03278.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03265.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03269.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03255.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03270.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03256.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03258.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03272.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03268.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03770.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03257.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03273.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03251.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03259.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03252.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03263.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03253.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03260.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03240.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03892.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11551.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03246.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03245.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03247.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03241.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03254.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03238.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03244.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03249.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03232.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03239.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03234.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03226.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03236.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03228.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03227.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03248.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03235.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03233.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09370.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03224.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03229.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03568.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03223.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03210.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03221.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03231.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03230.npy

  inflating: DiffWave_Project/data_preprocessed/mels/03211.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03220.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03237.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03222.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03213.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03225.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03218.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03212.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03217.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03250.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12325.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03216.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09311.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03219.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03215.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03202.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03203.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03209.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03214.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03205.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03200.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03204.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03201.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03195.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03208.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03197.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03199.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03196.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03180.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03182.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03178.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03190.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03194.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03183.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03188.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03198.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03185.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03181.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03189.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03191.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03184.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03193.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03177.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03186.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03176.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03175.npy

  inflating: DiffWave_Project/data_preprocessed/mels/03192.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03173.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03170.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03187.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03169.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03167.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03179.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03168.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03159.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03158.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03147.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03162.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03154.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03161.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03156.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03174.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03140.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03165.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03144.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03146.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03155.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03163.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03164.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03152.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03150.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03141.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03149.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03603.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03139.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03995.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03142.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03151.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03507.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03160.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03145.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03153.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03148.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03166.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03132.npy

  inflating: DiffWave_Project/data_preprocessed/mels/03133.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03157.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03143.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03131.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03127.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03136.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03135.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03119.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03115.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03129.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03118.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03107.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03112.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03124.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03125.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03123.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03126.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03128.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03113.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03117.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03116.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03134.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03122.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03120.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03108.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03114.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03121.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03106.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03130.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03111.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09175.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03101.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03094.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03110.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03100.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03109.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03085.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03735.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03099.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03092.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11341.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03090.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03102.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03096.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03097.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03084.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03086.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03098.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03089.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03082.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03083.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03105.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03093.npy

  inflating: DiffWave_Project/data_preprocessed/mels/03088.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03076.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03078.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03075.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03073.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03079.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03091.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03074.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03095.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03087.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03081.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03069.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03066.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03080.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03077.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03061.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03056.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10152.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03065.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03062.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03072.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03071.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03053.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03063.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03055.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03059.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03060.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03058.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03046.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03070.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03052.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03042.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03047.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03064.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03051.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03043.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03054.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03050.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03049.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03057.npy

  inflating: DiffWave_Project/data_preprocessed/mels/03044.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03045.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03034.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03035.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03041.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03048.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03040.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03039.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03037.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03032.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03022.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03016.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03031.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03027.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03026.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03038.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03019.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03036.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03023.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03018.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03021.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03025.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03017.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03015.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03033.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03005.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03028.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03012.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03020.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03013.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03011.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03007.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03008.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03024.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03014.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03001.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03002.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03006.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02999.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03004.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03010.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02998.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03009.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03638.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03000.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03381.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03486.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03489.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/03964.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03488.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03491.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03003.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03487.wav
  inflating: DiffWave_Project/data_preprocessed/mels/02994.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03478.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03484.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03490.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03479.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03483.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03481.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03482.wav
  inflating: DiffWave_Project/data_preprocessed/mels/02993.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03492.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03469.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03475.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03467.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03472.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03485.wav
  inflating: DiffWave_Project/data_preprocessed/mels/02997.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03477.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03480.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03470.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03243.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03468.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11521.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03471.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03474.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12135.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03466.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10313.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03473.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03463.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/03454.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03458.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03800.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03465.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03476.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03459.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09243.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03464.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03456.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03460.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03457.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03453.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03448.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03451.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03452.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03445.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03455.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03449.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03447.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03440.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03443.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03439.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03450.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03442.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03441.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03436.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03435.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03434.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03446.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03430.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03432.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03433.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03437.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03429.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03422.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/03420.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03444.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03431.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03416.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03438.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03428.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03413.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03415.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03414.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03423.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03412.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03417.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03409.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03404.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03395.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03405.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03419.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03410.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03421.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03418.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03406.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03407.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03402.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03411.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03401.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03400.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03403.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03393.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03385.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04202.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03408.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/03392.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03398.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03388.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03397.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03426.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03381.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03378.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03399.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03394.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03427.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03383.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03380.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03376.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03377.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03375.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03374.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03396.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03382.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03387.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03384.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03386.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03373.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03389.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03370.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03368.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03369.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03371.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03364.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03363.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03362.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03372.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03367.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/03379.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03365.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03359.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03354.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03366.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03360.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03353.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03350.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03352.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03361.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03349.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03348.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03342.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03340.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03345.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03351.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03343.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03336.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03339.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03344.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03335.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03331.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03332.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03334.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03337.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03328.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03327.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03325.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03330.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03346.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03347.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03333.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11845.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03341.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03329.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/03358.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03326.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03357.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03338.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11868.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03534.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04467.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03324.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03319.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03323.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03317.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03316.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03104.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03307.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03306.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10464.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03314.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03309.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03313.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03867.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03310.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03320.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03318.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03303.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03308.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03292.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/03311.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03305.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03312.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03300.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03297.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03298.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03315.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03296.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03302.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03293.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03299.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03294.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03295.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03304.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03277.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03270.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03267.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03287.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03301.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03289.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03282.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03279.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03280.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03291.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03276.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03274.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03271.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03281.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03273.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03278.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/03275.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03288.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03265.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03264.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03262.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03260.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03268.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03257.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03266.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03256.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03272.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03261.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03254.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03269.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03258.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03290.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03251.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/03255.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03263.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03285.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03030.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03246.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03245.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03244.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03247.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03259.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03252.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11210.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03240.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03253.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03241.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03235.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03237.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03248.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03238.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03286.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03234.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03239.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03243.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03230.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03242.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03228.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03233.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03236.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03220.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03229.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03222.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03232.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03221.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03231.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/03214.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03217.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03227.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03216.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03218.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03224.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03215.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03219.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03206.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03208.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03212.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03209.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03213.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03226.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03205.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03223.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03225.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03203.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03194.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03200.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03197.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03204.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03195.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03182.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03322.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03201.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03202.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03192.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03207.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03193.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03189.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03187.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03190.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/03184.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03180.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03185.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03188.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03183.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03179.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03196.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03191.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11558.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03178.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03177.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03186.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03198.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03199.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03181.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03174.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03173.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03170.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09262.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03167.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03169.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03165.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03166.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03163.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/03171.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03156.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03168.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03164.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03160.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03158.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03172.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03149.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03157.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03145.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03151.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03148.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03154.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03161.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03153.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03152.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03142.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03162.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03710.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03144.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03150.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03159.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03139.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03146.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03441.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03155.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03147.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03132.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/03143.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03131.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03134.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03138.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03129.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03136.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03137.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03122.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03127.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03130.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03125.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03135.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03118.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03126.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03119.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03117.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03102.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03114.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03115.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03112.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03113.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03133.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03128.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03120.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03108.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03277.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03124.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03123.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03107.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03121.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/03103.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03116.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03104.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03110.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03111.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03100.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03101.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03109.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03095.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03094.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03092.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03098.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03083.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03087.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03091.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03096.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03084.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03089.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03078.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03077.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03081.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03088.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03097.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03070.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10947.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03076.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11028.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03085.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03080.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03082.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11275.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03090.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03079.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03074.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/03075.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03093.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03086.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03069.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03099.wav
  inflating: DiffWave_Project/data_preprocessed/mels/02996.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03065.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03207.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03071.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03642.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03068.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03058.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03057.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03060.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03056.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03052.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03062.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03063.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03061.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03048.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03051.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03049.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03053.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03047.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03045.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03042.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03066.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/03067.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03054.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03055.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03059.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03064.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03033.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03031.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03044.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03046.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03041.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03043.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03032.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03030.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03050.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03025.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03027.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03026.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03029.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03023.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03020.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03034.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03016.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03014.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03007.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03021.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03019.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03028.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03011.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03010.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03015.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03013.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/03008.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03022.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03009.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03003.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03017.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03024.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03018.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03038.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03006.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02997.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03012.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03005.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03000.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03040.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03039.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02998.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02996.wav
  inflating: DiffWave_Project/data_preprocessed/mels/02991.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02989.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/02999.wav
  inflating: DiffWave_Project/data_preprocessed/mels/02986.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/02995.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02993.wav
  inflating: DiffWave_Project/data_preprocessed/mels/02990.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02987.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02985.npy

  inflating: DiffWave_Project/data_preprocessed/mels/02983.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02963.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02974.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02975.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02962.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02988.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02992.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02984.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02980.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02982.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02981.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/02994.wav
  inflating: DiffWave_Project/data_preprocessed/mels/02978.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02979.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02976.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02967.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03004.wav
  inflating: DiffWave_Project/data_preprocessed/mels/02977.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02966.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02971.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02973.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02961.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02956.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02958.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03036.wav
  inflating: DiffWave_Project/data_preprocessed/mels/02972.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02952.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02957.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03391.wav
  inflating: DiffWave_Project/data_preprocessed/mels/02960.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02964.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02965.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02955.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02970.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02947.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02948.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02942.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03037.wav
  inflating: DiffWave_Project/data_preprocessed/mels/02951.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02949.npy

  inflating: DiffWave_Project/data_preprocessed/mels/02944.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02959.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02945.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02939.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02954.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02946.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02950.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02953.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02937.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02933.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02930.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02936.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02928.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02926.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02934.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02923.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02922.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02940.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02924.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02921.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02941.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02943.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02918.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02935.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02938.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02917.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02920.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02925.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11801.wav
  inflating: DiffWave_Project/data_preprocessed/mels/02915.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11733.wav
  inflating: DiffWave_Project/data_preprocessed/mels/02916.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09211.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02912.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02910.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02919.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02909.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02929.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02911.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02927.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02906.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02914.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02913.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02900.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02908.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02890.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02904.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02879.npy

  inflating: DiffWave_Project/data_preprocessed/mels/02891.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02902.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02907.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02887.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02883.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02888.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02901.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02893.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02878.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02882.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02881.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02894.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02877.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02889.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02903.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02884.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02905.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02875.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02886.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02880.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02876.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02899.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02873.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02892.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02885.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02874.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02869.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02868.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02872.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02858.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02897.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02866.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02898.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02859.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02854.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02853.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02867.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09404.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02861.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02847.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02848.npy

  inflating: DiffWave_Project/data_preprocessed/mels/02849.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02860.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02846.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02845.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02871.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02870.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02857.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02862.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02844.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02850.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02851.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02865.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02843.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02838.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02842.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02856.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02852.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02837.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02855.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02834.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02833.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02835.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02841.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11104.wav
  inflating: DiffWave_Project/data_preprocessed/mels/02840.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02832.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02836.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09275.wav
  inflating: DiffWave_Project/data_preprocessed/mels/02831.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02821.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03356.wav
  inflating: DiffWave_Project/data_preprocessed/mels/02827.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02839.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02829.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09596.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02820.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02819.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02823.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02818.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02822.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02830.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02828.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02815.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02813.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03462.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04103.wav

  inflating: DiffWave_Project/data_preprocessed/mels/02825.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02810.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02817.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02824.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02807.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02802.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02804.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02809.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02800.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02812.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02797.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02784.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02796.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02805.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02793.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02814.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02816.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02794.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02798.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02786.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02806.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02801.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02811.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02781.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02783.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02803.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02785.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02799.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02775.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02778.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02777.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02795.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02780.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02774.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02782.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02773.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02771.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02768.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02776.npy

  inflating: DiffWave_Project/data_preprocessed/mels/02764.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02770.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02765.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02779.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02792.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02767.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02791.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02763.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11590.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02808.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02762.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02772.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02790.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02789.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02759.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02755.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02752.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02769.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02756.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02751.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02761.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02760.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/02989.wav
  inflating: DiffWave_Project/data_preprocessed/mels/02744.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02746.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02743.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02753.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02747.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02750.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02754.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/02987.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02986.wav
  inflating: DiffWave_Project/data_preprocessed/mels/02749.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02748.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/02990.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02992.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02991.wav
  inflating: DiffWave_Project/data_preprocessed/mels/02745.npy

  inflating: DiffWave_Project/data_preprocessed/mels/02766.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/02984.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02988.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02982.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02978.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02980.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02983.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02985.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02977.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03425.wav
  inflating: DiffWave_Project/data_preprocessed/mels/02788.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/02971.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02979.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02972.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02970.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02969.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02975.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02957.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02965.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02966.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02967.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02960.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02981.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02956.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02959.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02968.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02963.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02953.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02954.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02955.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/09377.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02961.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02958.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02950.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02976.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02948.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02944.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02962.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02947.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02945.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02943.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02952.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02964.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09343.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02949.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02951.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02974.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02942.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02938.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02937.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02946.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02932.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02929.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02931.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02926.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/02941.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02933.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02936.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02922.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02919.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02913.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02927.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02930.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02935.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02916.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02924.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02923.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02934.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02921.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02915.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02911.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02920.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02917.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02914.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02909.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02907.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02925.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02918.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02910.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03002.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02900.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02908.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02902.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02904.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02901.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02912.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/02928.wav
  inflating: DiffWave_Project/data_preprocessed/mels/02896.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/02896.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02891.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02892.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02903.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02889.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02887.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02899.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02882.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02886.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02898.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02884.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02883.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02880.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02890.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02885.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02894.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02874.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02877.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02895.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02888.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02879.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02875.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02897.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/02893.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03926.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/02881.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02872.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02878.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02868.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02864.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02869.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02867.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03284.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02863.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10877.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/02858.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02857.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02859.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02856.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02876.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02873.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02861.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09294.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/02851.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02853.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02860.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02852.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02855.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02854.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/02866.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02849.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02862.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02865.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02843.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02842.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02847.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02838.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02848.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02840.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02837.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02844.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02835.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02830.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02850.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02825.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02836.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02845.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02846.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02824.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/02826.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02841.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02839.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02827.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02821.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02823.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02822.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02829.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02818.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02817.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02815.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02831.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02814.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02819.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02828.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02820.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02832.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02812.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02809.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02807.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02816.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02810.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/02808.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02806.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02813.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02805.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02811.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02801.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03250.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02800.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02797.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02793.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02790.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02789.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02791.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02802.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02804.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02794.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02803.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02779.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02785.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02783.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02792.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03410.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/02781.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02777.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02788.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02786.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02796.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02774.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02775.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02795.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02776.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02784.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02771.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/02787.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02772.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02782.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02780.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02773.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02766.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02768.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02778.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02770.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02758.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02751.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02756.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02755.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02754.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02752.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02753.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02769.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02744.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02759.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02767.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02747.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02745.wav
  inflating: DiffWave_Project/data_preprocessed/mels/02739.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/02750.wav
  inflating: DiffWave_Project/data_preprocessed/mels/02742.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/02757.wav

  inflating: DiffWave_Project/data_preprocessed/mels/02738.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/02746.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02749.wav
  inflating: DiffWave_Project/data_preprocessed/mels/02741.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02737.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/02762.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02760.wav
  inflating: DiffWave_Project/data_preprocessed/mels/02740.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/02761.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02765.wav
  inflating: DiffWave_Project/data_preprocessed/mels/02734.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03068.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/02748.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09853.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03211.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06115.wav
  inflating: DiffWave_Project/data_preprocessed/mels/02736.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/02834.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02743.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01998.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01999.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01997.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02735.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/02906.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01993.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01995.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01991.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02731.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01992.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01996.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01984.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01979.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01990.npy

  inflating: DiffWave_Project/data_preprocessed/mels/01983.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03176.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01980.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01982.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01978.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01988.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01987.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01965.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/02764.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01977.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01981.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01986.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01994.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01971.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01970.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01985.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01969.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01989.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01973.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01964.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01976.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01967.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01975.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01968.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01960.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01966.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01974.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01961.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01955.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01958.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01972.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01954.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01959.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01948.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01949.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01956.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01938.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01957.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01935.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01929.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01945.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01941.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01952.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01939.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01953.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01937.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01936.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01932.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01946.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01940.npy

  inflating: DiffWave_Project/data_preprocessed/mels/01943.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01951.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01930.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01947.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01942.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01950.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01928.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01927.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01944.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01934.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01931.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01920.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01921.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01917.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01918.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01933.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01922.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01914.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01915.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01902.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01916.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01913.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01905.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01919.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03138.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01910.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01923.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01911.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01906.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01908.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01912.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01897.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01901.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01909.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01903.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01924.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01904.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01900.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01894.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01888.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01899.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01895.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01896.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01893.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01887.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01907.npy

  inflating: DiffWave_Project/data_preprocessed/mels/01885.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01898.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01889.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01876.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01883.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01884.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01886.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01878.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01877.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01866.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01873.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01871.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01879.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01869.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01880.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01865.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01867.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01881.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01875.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01868.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01859.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01872.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01870.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01864.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01882.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01862.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01892.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01858.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01861.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01874.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01845.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03928.wav
  inflating: DiffWave_Project/data_preprocessed/mels/02932.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01863.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01855.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01854.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01852.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01853.npy

  inflating: DiffWave_Project/data_preprocessed/mels/01846.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01847.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01850.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01848.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/02871.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01849.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01860.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01842.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10768.wav
  inflating: DiffWave_Project/data_preprocessed/mels/02758.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01841.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02864.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01851.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01837.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01836.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01835.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01833.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01843.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01844.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01834.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01840.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01832.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01839.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01838.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01831.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01825.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01824.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01830.npy

  inflating: DiffWave_Project/data_preprocessed/mels/01826.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01828.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01823.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01822.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01829.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01821.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01816.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01818.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01857.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01817.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01813.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01811.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01827.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01810.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01809.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01808.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01812.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01804.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03605.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01807.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03172.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01802.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01798.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01805.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01814.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01800.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01785.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01806.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01815.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01791.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01801.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01787.npy

  inflating: DiffWave_Project/data_preprocessed/mels/01799.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01786.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01789.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01797.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01784.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01792.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01783.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01796.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01790.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01788.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01780.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01803.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01794.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01778.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01779.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01795.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01776.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01793.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01772.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01775.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01768.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01774.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01762.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/02738.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01770.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01769.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01767.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01766.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01777.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/02742.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01771.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01773.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/02739.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01765.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01763.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/02737.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01998.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01764.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/02735.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02741.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02736.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02732.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01999.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01990.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02740.wav

  inflating: DiffWave_Project/data_preprocessed/mels/03345.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01989.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01993.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01997.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02731.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01992.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02733.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01985.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01987.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02734.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01983.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01986.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01991.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01979.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01996.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01981.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01982.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01980.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01988.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01971.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01978.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01967.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01965.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01968.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01964.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01972.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01970.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01973.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01962.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01961.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01963.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01969.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01952.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/01984.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01956.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01976.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01955.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01974.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03073.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01954.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01963.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01951.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01975.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01977.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01966.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01953.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01950.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01949.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01960.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01945.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01957.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03106.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01926.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01947.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01946.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01943.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/01940.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01944.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01941.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01942.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01939.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01936.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01933.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01934.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01929.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01923.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01937.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01930.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01927.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01948.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01931.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01935.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01932.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01917.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01928.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01925.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01926.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01913.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01938.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01914.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01924.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01918.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01912.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01915.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01911.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01904.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01905.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01902.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01903.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01899.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01901.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01910.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01908.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01909.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/01916.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01898.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01906.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01887.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01895.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01893.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01907.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01890.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01894.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01889.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01921.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01897.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03309.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01820.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01884.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01900.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01891.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01896.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01888.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01883.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01878.wav
  inflating: DiffWave_Project/data_preprocessed/mels/02733.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01892.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01877.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01875.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01891.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01876.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01882.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01922.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01880.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01873.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01874.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01870.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01879.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01867.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01866.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/01881.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01869.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01868.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01864.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01863.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01861.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01857.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01862.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01872.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01856.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01858.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01855.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01837.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01871.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01844.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01859.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01860.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01853.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01839.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01854.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01835.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01840.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01845.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01831.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01865.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01846.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/01843.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01829.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01832.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01827.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01838.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01834.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01826.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01822.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01824.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01833.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01841.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01828.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01842.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01820.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01825.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01852.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01836.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01830.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01819.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10691.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01850.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01821.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01782.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01812.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10809.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01823.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01809.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01813.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01818.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01795.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01800.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01808.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01816.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01804.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01811.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01798.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01817.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01799.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/01802.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01849.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01806.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01807.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01801.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01796.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01791.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01803.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01792.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01810.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01851.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01789.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01788.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01783.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01787.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01805.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01786.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01797.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01793.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01794.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01784.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01785.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01790.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01772.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01769.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/01782.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01773.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01774.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01770.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01761.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01768.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01764.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01762.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01780.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01766.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01781.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01775.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01756.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01767.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01771.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01754.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01752.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01763.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01765.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01750.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01753.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01749.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01758.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01759.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01755.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01760.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01757.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01779.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01778.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01745.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01747.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01742.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01746.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01741.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01751.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01920.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01748.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01733.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01730.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01739.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01723.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01732.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01735.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01738.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01728.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01736.npy

  inflating: DiffWave_Project/data_preprocessed/mels/01734.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01727.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01729.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01740.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01722.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01725.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01737.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01714.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01715.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01724.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01716.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01719.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01718.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01731.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01717.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01721.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01720.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01886.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01713.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01726.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01709.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01708.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01697.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01706.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01712.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01777.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01699.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01703.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01704.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/02940.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01705.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01702.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01695.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01694.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01707.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01696.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01701.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01690.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01691.npy

  inflating: DiffWave_Project/data_preprocessed/mels/01693.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01700.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01688.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01687.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01685.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01698.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01692.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01681.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01689.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01679.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01680.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01684.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01682.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01677.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01678.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01686.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01848.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01673.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03141.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01959.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01683.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01815.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01663.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01653.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01995.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02799.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01672.npy

  inflating: DiffWave_Project/data_preprocessed/mels/01671.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01667.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02969.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01669.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01661.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01668.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01664.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01656.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01654.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01674.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01655.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01662.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01651.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01659.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01660.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01666.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01670.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01657.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01650.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01665.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01644.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01647.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01646.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01632.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01652.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01633.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01631.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01630.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01618.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01649.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01624.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01626.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01643.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01625.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01628.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01622.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01648.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01629.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01617.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01627.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01619.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01613.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01645.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01609.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01614.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01658.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01639.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01623.npy

  inflating: DiffWave_Project/data_preprocessed/mels/01611.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01621.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01615.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01641.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01616.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01610.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01620.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01640.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01608.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01637.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01601.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01612.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01599.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01605.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06977.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01607.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01636.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01598.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01595.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01638.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01591.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01587.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01642.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01593.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01597.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01586.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01606.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01592.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01588.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01585.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01594.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01590.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01582.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01600.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01596.npy

  inflating: DiffWave_Project/data_preprocessed/mels/01589.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01580.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01583.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01584.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01558.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01602.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01579.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01576.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01581.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01575.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01565.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01578.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01557.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01561.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01556.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01577.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01559.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01553.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01563.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01555.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01551.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01564.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01554.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01548.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01547.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01550.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01560.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01562.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01574.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01545.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01543.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01566.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01541.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01549.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01542.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01546.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01572.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01568.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01540.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01570.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01552.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01544.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01635.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01569.npy

  inflating: DiffWave_Project/data_preprocessed/mels/01571.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01604.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01536.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01535.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10073.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01531.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01573.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01534.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01527.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01711.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01538.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01539.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01530.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01744.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01529.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01760.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01525.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01533.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01528.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01676.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01522.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01532.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01515.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01516.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01523.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01758.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01524.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01757.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01521.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01520.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01759.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01513.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01526.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01514.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01518.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01519.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01755.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01512.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01742.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01761.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01754.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01756.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01741.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01517.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01736.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01740.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/01737.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01726.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01733.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01739.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01731.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01721.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01753.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01730.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01727.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01729.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01732.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01720.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01738.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01735.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01749.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01747.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01734.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01725.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01718.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01724.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01717.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01722.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/01752.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01751.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01748.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01728.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01716.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01746.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01712.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01710.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01706.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01723.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01750.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01711.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01719.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01700.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01705.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01702.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01703.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01745.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01709.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01704.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01701.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01694.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01690.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01699.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01693.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01707.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01692.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01689.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01687.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/01686.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01685.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01691.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01698.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01697.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01684.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01681.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01683.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01680.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01708.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01688.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01673.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01695.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01674.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01668.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01715.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01682.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01667.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01656.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01659.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01676.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01664.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/01670.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01658.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01696.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01655.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01661.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01654.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01672.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01671.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01652.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01675.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01663.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01666.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01657.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01665.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01662.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01669.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01647.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01646.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01650.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01679.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01638.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01660.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12499.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01642.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01653.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01648.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01651.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01649.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01634.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01640.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01639.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01630.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/01628.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01629.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01744.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01637.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01632.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01636.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01625.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01624.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01633.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01622.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01641.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01631.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01621.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01645.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01618.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01623.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01616.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01614.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01619.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01613.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01611.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01626.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01627.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01603.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01635.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01615.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01610.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01612.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/01617.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01678.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01604.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01597.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01599.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01606.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01620.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01598.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01600.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01605.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01595.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01593.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01586.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01594.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01584.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01714.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01590.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10089.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01591.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01592.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01589.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01587.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/01596.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01607.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01581.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01602.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01578.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01585.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01582.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01583.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01577.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01575.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01574.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09138.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01568.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01573.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01579.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01567.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01601.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01588.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01566.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01561.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01564.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01570.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01580.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01556.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01558.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01559.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01565.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/01555.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01557.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01576.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01562.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01569.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01563.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01552.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01551.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01547.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01545.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01560.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01550.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01549.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01528.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01544.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01541.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01554.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01546.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11943.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/01553.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01548.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01543.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01530.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01536.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01531.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01529.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01540.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01644.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01542.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01521.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01537.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01525.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01522.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01524.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01523.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01539.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01533.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01526.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01538.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01532.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01517.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01513.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01515.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01520.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01505.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01527.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01514.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01512.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01510.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01519.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01509.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01493.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01516.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01506.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01504.npy

  inflating: DiffWave_Project/data_preprocessed/mels/01508.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01511.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01500.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01518.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01491.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01495.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01494.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01492.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01501.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01488.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01496.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01489.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01502.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01507.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01480.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01478.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01483.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01486.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01503.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01479.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01485.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01487.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01474.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01482.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01484.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01481.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01476.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01470.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01471.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01490.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01467.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01477.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01475.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01473.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01469.npy

  inflating: DiffWave_Project/data_preprocessed/mels/01462.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01472.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01499.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01465.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01535.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01453.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01455.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01609.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01445.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01447.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01452.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01457.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01461.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01466.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01458.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01448.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01468.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01459.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01456.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01460.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01572.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01449.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01442.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01441.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01454.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01446.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01440.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01451.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01450.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01443.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01428.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01436.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01438.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01426.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01464.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01423.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01444.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01432.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01498.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01437.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01435.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01427.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06804.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01431.npy

  inflating: DiffWave_Project/data_preprocessed/mels/01425.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01433.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01420.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01422.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01424.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01439.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01417.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01430.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01421.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01419.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01416.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01434.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01418.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01414.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01410.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01412.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01407.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01415.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01413.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01405.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01404.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01409.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01400.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11524.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09633.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01402.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01398.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01411.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01395.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01397.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01401.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11880.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01406.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11101.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10163.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01408.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01399.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09333.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12203.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01396.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01390.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01394.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01388.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01389.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01391.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01392.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01403.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01374.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01366.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01387.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01383.npy

  inflating: DiffWave_Project/data_preprocessed/mels/01380.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01381.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01378.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01372.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01385.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01376.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01373.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01386.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01384.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01375.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01371.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01368.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01365.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01367.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01369.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01379.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01364.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01370.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01357.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01377.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01363.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01362.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01359.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01358.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01344.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01360.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01382.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01342.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01348.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01330.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01336.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01343.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01345.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01341.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01338.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01337.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01340.npy

  inflating: DiffWave_Project/data_preprocessed/mels/01339.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01335.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01349.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01332.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01347.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01361.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01331.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01329.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01333.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01346.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01328.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01320.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01321.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01334.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01327.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01325.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01324.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01315.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01355.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01307.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01323.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01326.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01356.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01314.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01312.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01353.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01322.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01319.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01310.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01318.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01308.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01304.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01313.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01306.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01300.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01354.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01305.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01302.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01301.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01309.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01296.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01295.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01303.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01294.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01299.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01297.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01293.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01292.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01311.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01298.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01290.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01286.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01287.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01289.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10120.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01282.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01278.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01288.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01285.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01283.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01291.npy

  inflating: DiffWave_Project/data_preprocessed/mels/01281.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01280.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01277.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01351.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01279.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01352.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01284.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01273.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01269.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01272.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01274.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01270.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11414.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01268.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01267.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01271.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01256.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01263.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01262.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01255.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01260.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01258.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01261.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01266.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01254.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01257.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01252.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01251.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01250.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01249.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01264.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01253.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01265.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01259.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01239.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01240.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01244.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01317.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01241.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01242.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01245.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11063.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01246.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01243.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01235.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01248.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01238.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01227.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01226.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01228.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01229.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01247.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01224.npy

  inflating: DiffWave_Project/data_preprocessed/mels/01233.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01217.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01219.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01221.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01232.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01222.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01234.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01223.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01220.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01225.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01214.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01212.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01208.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01218.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01230.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01231.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01216.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01213.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01215.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01211.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01206.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01209.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01207.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01204.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01199.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01210.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01201.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01202.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01186.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01195.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01203.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01194.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01196.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01193.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01192.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01191.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01205.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01190.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01188.npy

  inflating: DiffWave_Project/data_preprocessed/mels/01181.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01187.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01200.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01185.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01189.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01184.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01183.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01175.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01180.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01177.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01178.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01176.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01182.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01172.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01170.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01161.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01163.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01173.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01171.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01164.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01166.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01169.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01179.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01174.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01167.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01165.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01168.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01237.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10738.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11698.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01157.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01276.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01155.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01154.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01160.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01156.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01162.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01151.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01153.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01159.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01146.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01140.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01149.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01148.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01150.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01152.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01145.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01137.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01147.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01198.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01134.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01139.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01143.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01132.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01133.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01142.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01129.npy

  inflating: DiffWave_Project/data_preprocessed/mels/01135.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01116.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01130.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01141.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01144.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01131.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01125.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01127.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01136.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01138.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01128.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01126.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01108.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01124.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01115.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01122.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01112.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01123.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01114.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01110.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01113.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01111.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01107.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01121.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01120.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01106.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01109.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01101.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01103.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01105.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01099.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01098.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01100.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01097.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01096.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01085.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01088.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01091.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01093.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12065.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01095.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01092.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01086.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01089.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01104.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01119.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01076.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01077.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01075.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01102.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01082.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01087.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01094.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01084.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01083.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01081.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01090.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01069.npy

  inflating: DiffWave_Project/data_preprocessed/mels/01072.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01073.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01068.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01071.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01061.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01070.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01074.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01067.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01065.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01066.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01064.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01078.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01055.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01045.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01063.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01056.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01058.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01053.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01052.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01051.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01046.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01047.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01048.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01062.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01050.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01060.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01037.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01054.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01057.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01059.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01044.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01042.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01032.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01043.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01033.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01030.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01028.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01031.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01029.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01036.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01027.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01049.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01038.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01024.npy

  inflating: DiffWave_Project/data_preprocessed/mels/01023.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01025.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01012.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01510.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01018.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01026.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01035.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01034.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01015.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01020.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01022.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01021.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01041.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01509.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01017.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01040.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01958.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01019.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01013.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01016.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01508.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01505.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01118.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01890.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/02939.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01501.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01511.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01503.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01506.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01080.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01502.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01500.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01499.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01496.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01493.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01507.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01494.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/01498.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01014.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01491.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01487.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01492.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01477.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01489.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01488.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01490.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01497.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01485.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01481.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01480.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01495.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01475.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01478.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01476.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01479.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01484.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01486.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01474.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01482.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01460.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/01456.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01472.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01447.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01473.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01455.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01454.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01459.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01458.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01449.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01483.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01470.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01450.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01446.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01457.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01452.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01444.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01471.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01443.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01445.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01448.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01451.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01441.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01440.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01453.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01439.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01438.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01442.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01437.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01435.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01434.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01467.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01465.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01433.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/01468.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01431.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01430.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01436.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01432.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01429.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01425.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01422.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01426.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01423.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01419.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01463.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01469.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01464.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01428.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01462.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01421.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01466.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01424.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01416.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03424.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01417.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01418.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01414.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01412.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01415.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01420.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/01410.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01407.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01408.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01409.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01411.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01405.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01406.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01400.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01403.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01401.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01404.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01397.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01398.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01396.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01393.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01413.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01399.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01387.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01394.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01392.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01383.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01389.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01388.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01391.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01395.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01390.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01374.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01402.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01381.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01379.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/01386.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01376.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01382.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01370.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01377.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01365.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01378.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01375.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01380.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01360.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01357.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01358.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01364.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01367.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01363.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01362.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01361.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01352.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01371.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01355.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01356.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01366.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01372.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01351.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01354.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01368.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01348.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01350.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01359.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01345.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/01343.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01335.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01353.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01369.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01342.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01341.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01337.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01344.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01349.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01338.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01323.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01334.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01373.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01333.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01327.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01328.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01325.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01326.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01339.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01331.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01318.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01324.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01314.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01316.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01336.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/01330.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01340.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01315.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01320.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01307.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01321.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01317.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01322.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01329.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01306.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01309.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01304.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01319.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01303.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01301.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01291.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01308.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01299.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01294.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01298.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01292.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01332.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01295.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01289.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01305.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01300.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01287.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01302.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01288.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01296.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/01290.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01285.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01280.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01286.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01276.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01385.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01293.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01297.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01281.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01279.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01313.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01284.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01283.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01347.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01272.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01271.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01275.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01269.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01001.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01273.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01267.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01312.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01264.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01268.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01270.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01266.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01274.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01265.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01011.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01282.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/01262.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01010.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01009.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01003.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01004.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01000.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01261.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01259.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01255.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01005.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01263.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01260.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01007.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01006.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01278.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01257.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01002.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01008.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01497.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01258.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01252.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01251.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01249.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01253.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01246.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01244.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01256.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01311.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01243.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01247.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01250.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02973.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/01248.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01240.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01238.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01237.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01234.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01235.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01232.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01242.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01224.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01221.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01241.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01233.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01230.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01236.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01216.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01225.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01217.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01245.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01226.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01229.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01239.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01223.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01222.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01213.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01220.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01227.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01231.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01228.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/01219.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01218.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01039.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01211.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01919.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01212.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01209.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01208.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01204.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01203.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01210.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01201.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01215.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01202.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01196.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01205.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01187.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01199.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01185.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01184.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01207.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01193.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01200.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01194.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01198.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01190.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01191.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01197.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01206.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01195.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01189.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01183.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01192.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01182.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01180.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01181.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01186.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01174.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01172.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01166.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01173.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01163.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01167.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/01161.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01164.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01169.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01168.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01175.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01160.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01165.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01154.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01157.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01156.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01158.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01162.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01171.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01155.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01153.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01170.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01179.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01149.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01188.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01159.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01150.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01148.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01152.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01146.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01178.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01147.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01151.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01885.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01140.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01129.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01143.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01177.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01571.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01141.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01133.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/01139.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01130.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01134.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01125.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01138.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01135.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01144.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01132.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01126.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01122.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01121.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01131.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01128.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01136.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01119.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01118.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01127.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01346.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01145.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01120.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01123.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01137.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01115.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01113.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01114.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01116.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01111.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01117.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01112.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/01102.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01106.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01104.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01100.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01105.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01098.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01099.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01092.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01097.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01095.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01110.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01096.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01087.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01109.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01108.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01090.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01091.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01856.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01093.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01107.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01101.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01083.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01078.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01086.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01089.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01094.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01072.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01084.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01088.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01080.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01082.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01081.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01079.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01076.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01124.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01066.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01074.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01075.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/01068.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01071.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01085.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01070.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01067.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01069.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01077.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01059.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01058.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01073.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01052.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01056.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01061.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01060.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01046.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01064.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01054.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01048.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01045.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01049.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01050.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01051.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01055.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01047.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01042.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01065.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01057.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01062.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01053.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01036.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01038.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01039.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01044.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/01037.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01040.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01043.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01035.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01024.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01029.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01031.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01032.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01030.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01033.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01013.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01021.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01041.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01019.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01034.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01018.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01017.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01016.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01022.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01023.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01011.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01009.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01015.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01002.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01003.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01675.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06506.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01007.wav

  inflating: DiffWave_Project/data_preprocessed/mels/10769.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01001.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01004.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01020.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01012.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01026.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01027.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01006.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01014.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01008.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01028.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01776.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06048.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01743.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01677.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04031.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01000.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01158.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11486.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11383.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11100.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12329.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11349.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12217.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09782.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11313.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06146.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01005.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10701.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12402.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11207.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10580.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11915.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09518.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11282.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01010.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09889.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06083.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06393.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06332.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11587.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10119.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12252.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/06589.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11418.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09747.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10993.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10111.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11523.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10737.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11065.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11449.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09966.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10387.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10946.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06803.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11985.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09072.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11735.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06723.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12366.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10909.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03390.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11456.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11062.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10516.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11557.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11520.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03137.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09342.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11844.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11732.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03103.npy

  inflating: DiffWave_Project/data_preprocessed/wavs/11274.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11866.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10463.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10806.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03344.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03206.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03440.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10332.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12324.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12025.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12063.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09310.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09412.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03820.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09376.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12180.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09369.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04070.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03998.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11550.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10980.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09332.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03769.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09443.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11209.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10408.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03604.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10257.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04531.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11138.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11103.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09510.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12498.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12287.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12133.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09585.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04098.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10914.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/10346.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09742.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09549.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12411.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10767.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04836.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10091.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11589.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12057.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04768.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11947.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10425.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12020.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10878.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04456.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09652.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10233.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11627.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09705.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12464.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11767.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04359.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10514.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11246.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10312.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10367.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04707.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12368.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09666.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09929.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10553.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10617.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10729.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04466.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12443.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10476.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10651.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11803.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04914.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09922.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10553.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12444.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06114.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11765.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10443.npy

  inflating: DiffWave_Project/data_preprocessed/mels/10690.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11025.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11697.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11170.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11661.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11879.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06029.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09784.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12468.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12434.npy
  inflating: DiffWave_Project/data_preprocessed/mels/11489.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11657.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11413.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11027.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11623.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06522.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11378.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10000.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06841.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10629.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11834.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11906.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11981.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11340.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10589.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12237.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12095.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11174.wav
  inflating: DiffWave_Project/data_preprocessed/mels/11135.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06982.wav

  inflating: DiffWave_Project/data_preprocessed/mels/10843.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12102.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10844.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06999.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09177.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03891.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09210.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06908.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01567.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11307.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10162.npy
  inflating: DiffWave_Project/data_preprocessed/mels/12250.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02968.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09217.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/11692.wav
  inflating: DiffWave_Project/data_preprocessed/mels/12141.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11942.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10808.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10088.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01847.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10072.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03175.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01117.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/02763.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02905.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01103.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06907.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01236.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01461.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10187.wav
  inflating: DiffWave_Project/data_preprocessed/mels/02787.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03748.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01063.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01814.wav
  inflating: DiffWave_Project/data_preprocessed/mels/02895.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01350.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/02870.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09242.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01384.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01176.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01254.wav

  inflating: DiffWave_Project/data_preprocessed/mels/01925.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01781.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06289.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06803.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09101.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10988.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02833.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01994.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09009.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09816.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01504.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09035.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06256.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10041.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06133.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12288.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06976.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06670.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04983.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03029.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09852.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10197.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09890.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03709.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03355.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06622.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09632.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02995.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09274.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03283.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09260.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10876.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03676.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06359.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03567.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09137.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/12162.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03963.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03529.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09403.npy

  inflating: DiffWave_Project/data_preprocessed/wavs/04693.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09437.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03668.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10293.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03799.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03833.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04737.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04375.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06940.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09293.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04324.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03742.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09852.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04310.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09623.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03171.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09595.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04424.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09558.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04538.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09142.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09476.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04661.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04406.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06945.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04994.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04438.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04629.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10950.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04887.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04638.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04933.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10227.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10151.wav

  inflating: DiffWave_Project/data_preprocessed/wavs/04268.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06016.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/09960.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01743.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06440.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/12202.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06167.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06876.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10269.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09476.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04563.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06556.wav
  inflating: DiffWave_Project/data_preprocessed/mels/10042.npy
  inflating: DiffWave_Project/data_preprocessed/mels/09815.npy
  inflating: DiffWave_Project/data_preprocessed/mels/10011.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06538.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06702.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02826.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02863.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01608.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/10078.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03956.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06871.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03783.npy
  inflating: DiffWave_Project/data_preprocessed/mels/02732.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/10661.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06458.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01534.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01214.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01463.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01537.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01316.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06769.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01962.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06656.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01142.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06097.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03072.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04102.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03140.wav

  inflating: DiffWave_Project/data_preprocessed/mels/06325.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06640.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03602.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06199.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09040.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03308.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04947.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03641.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06064.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03506.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/02798.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06604.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03637.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04753.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03409.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/11800.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03564.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03927.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04340.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03533.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04227.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04063.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03925.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04852.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04488.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04784.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01310.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09068.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04506.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04292.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04601.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06368.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04594.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04819.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01079.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01643.wav
  inflating: DiffWave_Project/data_preprocessed/mels/02757.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01710.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06842.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03461.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03858.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09734.wav

  inflating: DiffWave_Project/data_preprocessed/mels/01393.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06492.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09701.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04024.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01277.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06690.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06428.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06237.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01634.npy
  inflating: DiffWave_Project/data_preprocessed/mels/06569.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03321.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03210.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04135.wav
  inflating: DiffWave_Project/data_preprocessed/mels/09174.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03701.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06212.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03734.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03001.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04162.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06302.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04969.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03249.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06178.wav

  inflating: DiffWave_Project/data_preprocessed/mels/04572.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04724.wav
  inflating: DiffWave_Project/data_preprocessed/mels/06738.npy
  inflating: DiffWave_Project/data_preprocessed/mels/04193.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03380.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01429.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01603.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04865.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06469.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03472.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04500.wav
  inflating: DiffWave_Project/data_preprocessed/mels/02931.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01819.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03276.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/09108.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06400.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03242.npy
  inflating: DiffWave_Project/data_preprocessed/mels/03994.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04201.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04900.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/04801.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/06774.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04129.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/06263.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04261.npy
  inflating: DiffWave_Project/data_preprocessed/mels/01275.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/01713.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04391.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/03866.wav
  inflating: DiffWave_Project/data_preprocessed/mels/04671.npy

  inflating: DiffWave_Project/data_preprocessed/wavs/03896.wav
  inflating: DiffWave_Project/data_preprocessed/mels/01197.npy
  inflating: DiffWave_Project/data_preprocessed/wavs/04166.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03105.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/03035.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01025.wav
  inflating: DiffWave_Project/data_preprocessed/wavs/01427.wav
  inflating: DiffWave_Project/data_preprocessed/mels/03067.npy

In [6]:
from pathlib import Path

for path in Path.cwd().rglob("train.csv"):
    print(path)

/workspace/DiffWave_Project/data_preprocessed/train.csv

In [7]:
from pathlib import Path
import pandas as pd
import json
import numpy as np

# ============================================================
# 1. Chemins principaux
# ============================================================

PROJECT_DIR = Path("/workspace/DiffWave_Project")
DATA_DIR = PROJECT_DIR / "data_preprocessed"

# ============================================================
# 2. Fichiers et dossiers
# ============================================================

TRAIN_CSV = DATA_DIR / "train.csv"
VAL_CSV   = DATA_DIR / "val.csv"
TEST_CSV  = DATA_DIR / "test.csv"
SUMMARY_JSON = DATA_DIR / "summary.json"

WAV_DIR = DATA_DIR / "wavs"
MEL_DIR = DATA_DIR / "mels"

CHECKPOINT_DIR = PROJECT_DIR / "checkpoints"
FIGURES_DIR    = PROJECT_DIR / "figures"
RESULTS_DIR    = PROJECT_DIR / "results"
GENERATED_DIR  = PROJECT_DIR / "generated_audios"

for directory in [CHECKPOINT_DIR, FIGURES_DIR, RESULTS_DIR, GENERATED_DIR]:
    directory.mkdir(parents=True, exist_ok=True)

# ============================================================
# 3. Vérification des chemins
# ============================================================

print("\nVérification des chemins")
print("------------------------")
print("PROJECT_DIR existe :", PROJECT_DIR.exists())
print("DATA_DIR existe    :", DATA_DIR.exists())

print("\nFichiers CSV / JSON")
print("-------------------")
print("train.csv existe   :", TRAIN_CSV.exists())
print("val.csv existe     :", VAL_CSV.exists())
print("test.csv existe    :", TEST_CSV.exists())
print("summary.json existe:", SUMMARY_JSON.exists())

print("\nDossiers audio / Mel")
print("--------------------")
print("wavs existe :", WAV_DIR.exists())
print("mels existe :", MEL_DIR.exists())

print("\nNombre de fichiers")
print("------------------")
print("Nombre de wavs :", len(list(WAV_DIR.glob("*.wav"))) if WAV_DIR.exists() else "dossier absent")
print("Nombre de mels :", len(list(MEL_DIR.glob("*.npy"))) if MEL_DIR.exists() else "dossier absent")

# ============================================================
# 4. Chargement des CSV et du summary
# ============================================================

train_df = pd.read_csv(TRAIN_CSV)
val_df   = pd.read_csv(VAL_CSV)
test_df  = pd.read_csv(TEST_CSV)

with open(SUMMARY_JSON, "r", encoding="utf-8") as f:
    summary = json.load(f)

print("\nSplits chargés")
print("--------------")
print("Train :", train_df.shape)
print("Val   :", val_df.shape)
print("Test  :", test_df.shape)

print("\nRésumé du prétraitement")
print("-----------------------")
print(summary)

display(train_df.head())
display(val_df.head())
display(test_df.head())

# ============================================================
# 5. Test rapide d'un Mel spectrogram
# ============================================================

example_mel_path = Path(train_df.iloc[0]["mel_path"])

if not example_mel_path.exists():
    example_id = str(train_df.iloc[0]["id"]).zfill(5)
    example_mel_path = MEL_DIR / f"{example_id}.npy"

mel = np.load(example_mel_path)

print("\nTest Mel spectrogram")
print("--------------------")
print("Mel path  :", example_mel_path)
print("Mel shape :", mel.shape)
print("Mel min/max :", mel.min(), mel.max())

Vérification des chemins
------------------------
PROJECT_DIR existe : True
DATA_DIR existe    : True

Fichiers CSV / JSON
-------------------
train.csv existe   : True
val.csv existe     : True
test.csv existe    : True
summary.json existe: True

Dossiers audio / Mel
--------------------
wavs existe : True
mels existe : True

Nombre de fichiers
------------------
Nombre de wavs : 8012
Nombre de mels : 8012

Splits chargés
--------------
Train : (6489, 7)
Val   : (721, 7)
Test  : (802, 7)

Résumé du prétraitement
-----------------------
{'dataset': 'atlasia/DODa-audio-dataset', 'filtre': 'voix masculines (M1, M2, M3)', 'exemples_traites': 8012, 'duree_totale_h': 6.26, 'locuteurs': ['M1', 'M2', 'M3'], 'sample_rate': 22050, 'n_mels': 80, 'n_fft': 1024, 'hop_length': 256, 'splits': {'train': 6489, 'val': 721, 'test': 802}}

,id,speaker,text_latin,wav_path,mel_path,duration_s,mel_frames
0,9111,M2,ana tsizit,/content/drive/MyDrive/DiffWave_Project/data_p...,/content/drive/MyDrive/DiffWave_Project/data_p...,2.283,197
1,10284,M1,b Tabi3at l7al,/content/drive/MyDrive/DiffWave_Project/data_p...,/content/drive/MyDrive/DiffWave_Project/data_p...,2.539,219
2,9520,M2,chokran 3la lkado,/content/drive/MyDrive/DiffWave_Project/data_p...,/content/drive/MyDrive/DiffWave_Project/data_p...,2.176,188
3,10666,M1,nowanbir,/content/drive/MyDrive/DiffWave_Project/data_p...,/content/drive/MyDrive/DiffWave_Project/data_p...,1.472,127
4,1462,M3,3lach ana?,/content/drive/MyDrive/DiffWave_Project/data_p...,/content/drive/MyDrive/DiffWave_Project/data_p...,1.707,148

,id,speaker,text_latin,wav_path,mel_path,duration_s,mel_frames
0,3167,M2,"ah, drayfa",/content/drive/MyDrive/DiffWave_Project/data_p...,/content/drive/MyDrive/DiffWave_Project/data_p...,1.643,142
1,12027,M2,achnahowa a7ssen new3 dial chti7 3endek ?,/content/drive/MyDrive/DiffWave_Project/data_p...,/content/drive/MyDrive/DiffWave_Project/data_p...,2.709,234
2,3269,M2,ana katib.,/content/drive/MyDrive/DiffWave_Project/data_p...,/content/drive/MyDrive/DiffWave_Project/data_p...,1.771,153
3,12728,M1,ghanchouf wach kayna chi reservatio m3a tmenya...,/content/drive/MyDrive/DiffWave_Project/data_p...,/content/drive/MyDrive/DiffWave_Project/data_p...,3.648,315
4,12316,M2,ana m9tan3a bli 3a2iltna fach kitjm3ou kiweliw...,/content/drive/MyDrive/DiffWave_Project/data_p...,/content/drive/MyDrive/DiffWave_Project/data_p...,5.525,476

,id,speaker,text_latin,wav_path,mel_path,duration_s,mel_frames
0,3757,M2,walakin nta kan 3ndk jtima3 S3ib,/content/drive/MyDrive/DiffWave_Project/data_p...,/content/drive/MyDrive/DiffWave_Project/data_p...,2.987,258
1,10384,M1,redlbal,/content/drive/MyDrive/DiffWave_Project/data_p...,/content/drive/MyDrive/DiffWave_Project/data_p...,2.347,203
2,4938,M1,momkin tabghiha 9bal mosi9a dyal rock,/content/drive/MyDrive/DiffWave_Project/data_p...,/content/drive/MyDrive/DiffWave_Project/data_p...,3.541,306
3,11678,M1,kaystresse mli katchouf nass a5rin ki5niw,/content/drive/MyDrive/DiffWave_Project/data_p...,/content/drive/MyDrive/DiffWave_Project/data_p...,3.861,333
4,3633,M2,nta katbi3 otchri f achmn naw3 dyal nifT?,/content/drive/MyDrive/DiffWave_Project/data_p...,/content/drive/MyDrive/DiffWave_Project/data_p...,2.837,245

Test Mel spectrogram
--------------------
Mel path  : /workspace/DiffWave_Project/data_preprocessed/mels/09111.npy
Mel shape : (80, 197)
Mel min/max : -11.5 4.9098268

In [8]:
train_df = pd.read_csv(TRAIN_CSV)
val_df = pd.read_csv(VAL_CSV)
test_df = pd.read_csv(TEST_CSV)

print("Train :", train_df.shape)
print("Val :", val_df.shape)
print("Test :", test_df.shape)

display(train_df.head())
display(val_df.head())
display(test_df.head())

Train : (6489, 7)
Val : (721, 7)
Test : (802, 7)

,id,speaker,text_latin,wav_path,mel_path,duration_s,mel_frames
0,9111,M2,ana tsizit,/content/drive/MyDrive/DiffWave_Project/data_p...,/content/drive/MyDrive/DiffWave_Project/data_p...,2.283,197
1,10284,M1,b Tabi3at l7al,/content/drive/MyDrive/DiffWave_Project/data_p...,/content/drive/MyDrive/DiffWave_Project/data_p...,2.539,219
2,9520,M2,chokran 3la lkado,/content/drive/MyDrive/DiffWave_Project/data_p...,/content/drive/MyDrive/DiffWave_Project/data_p...,2.176,188
3,10666,M1,nowanbir,/content/drive/MyDrive/DiffWave_Project/data_p...,/content/drive/MyDrive/DiffWave_Project/data_p...,1.472,127
4,1462,M3,3lach ana?,/content/drive/MyDrive/DiffWave_Project/data_p...,/content/drive/MyDrive/DiffWave_Project/data_p...,1.707,148

,id,speaker,text_latin,wav_path,mel_path,duration_s,mel_frames
0,3167,M2,"ah, drayfa",/content/drive/MyDrive/DiffWave_Project/data_p...,/content/drive/MyDrive/DiffWave_Project/data_p...,1.643,142
1,12027,M2,achnahowa a7ssen new3 dial chti7 3endek ?,/content/drive/MyDrive/DiffWave_Project/data_p...,/content/drive/MyDrive/DiffWave_Project/data_p...,2.709,234
2,3269,M2,ana katib.,/content/drive/MyDrive/DiffWave_Project/data_p...,/content/drive/MyDrive/DiffWave_Project/data_p...,1.771,153
3,12728,M1,ghanchouf wach kayna chi reservatio m3a tmenya...,/content/drive/MyDrive/DiffWave_Project/data_p...,/content/drive/MyDrive/DiffWave_Project/data_p...,3.648,315
4,12316,M2,ana m9tan3a bli 3a2iltna fach kitjm3ou kiweliw...,/content/drive/MyDrive/DiffWave_Project/data_p...,/content/drive/MyDrive/DiffWave_Project/data_p...,5.525,476

,id,speaker,text_latin,wav_path,mel_path,duration_s,mel_frames
0,3757,M2,walakin nta kan 3ndk jtima3 S3ib,/content/drive/MyDrive/DiffWave_Project/data_p...,/content/drive/MyDrive/DiffWave_Project/data_p...,2.987,258
1,10384,M1,redlbal,/content/drive/MyDrive/DiffWave_Project/data_p...,/content/drive/MyDrive/DiffWave_Project/data_p...,2.347,203
2,4938,M1,momkin tabghiha 9bal mosi9a dyal rock,/content/drive/MyDrive/DiffWave_Project/data_p...,/content/drive/MyDrive/DiffWave_Project/data_p...,3.541,306
3,11678,M1,kaystresse mli katchouf nass a5rin ki5niw,/content/drive/MyDrive/DiffWave_Project/data_p...,/content/drive/MyDrive/DiffWave_Project/data_p...,3.861,333
4,3633,M2,nta katbi3 otchri f achmn naw3 dyal nifT?,/content/drive/MyDrive/DiffWave_Project/data_p...,/content/drive/MyDrive/DiffWave_Project/data_p...,2.837,245

In [9]:
with open(SUMMARY_JSON, "r", encoding="utf-8") as f:
    summary = json.load(f)

summary

{'dataset': 'atlasia/DODa-audio-dataset',
 'filtre': 'voix masculines (M1, M2, M3)',
 'exemples_traites': 8012,
 'duree_totale_h': 6.26,
 'locuteurs': ['M1', 'M2', 'M3'],
 'sample_rate': 22050,
 'n_mels': 80,
 'n_fft': 1024,
 'hop_length': 256,
 'splits': {'train': 6489, 'val': 721, 'test': 802}}

In [10]:
example_mel_path = Path(train_df.iloc[0]["mel_path"])

# Si le chemin dans le CSV est relatif ou local, on le reconstruit :
if not example_mel_path.exists():
    example_id = str(train_df.iloc[0]["id"]).zfill(5)
    example_mel_path = MEL_DIR / f"{example_id}.npy"

mel = np.load(example_mel_path)

print("Mel path :", example_mel_path)
print("Mel shape :", mel.shape)
print("Mel min/max :", mel.min(), mel.max())

Mel path : /workspace/DiffWave_Project/data_preprocessed/mels/09111.npy
Mel shape : (80, 197)
Mel min/max : -11.5 4.9098268

# Préparation du Dataset PyTorch pour DiffWave

Dans cette partie, on prépare les données pour l'entraînement du modèle DiffWave.

Les fichiers audio prétraités sont au format `.wav`, tandis que les spectrogrammes Mel sont sauvegardés au format `.npy`.

L’objectif est de créer un Dataset PyTorch capable de charger correctement chaque paire :

- audio prétraité ;
- spectrogramme Mel correspondant.

On vérifiera ensuite que les dimensions sont compatibles avec le modèle DiffWave.

In [11]:
!pip install -q git+https://github.com/lmnt-com/diffwave.git

import os
import soundfile as sf
import torch
from torch.utils.data import Dataset, DataLoader

from diffwave.model import DiffWave
from diffwave.params import params

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device utilisé :", device)

Device utilisé : cuda

## Vérification des paramètres DiffWave

On vérifie maintenant les paramètres internes utilisés par l’implémentation DiffWave.

Ils doivent être cohérents avec le prétraitement déjà réalisé, notamment :

- le nombre de bandes Mel ;
- la taille du hop ;
- le nombre de frames Mel utilisées pendant l’entraînement.

In [12]:
print("Paramètres DiffWave chargés :")
print("n_mels :", params.n_mels)
print("n_fft :", params.n_fft)
print("hop_samples :", params.hop_samples)
print("crop_mel_frames :", params.crop_mel_frames)
print("residual_layers :", params.residual_layers)
print("residual_channels :", params.residual_channels)

Paramètres DiffWave chargés :
n_mels : 80
n_fft : 1024
hop_samples : 256
crop_mel_frames : 62
residual_layers : 30
residual_channels : 64

## Création du Dataset PyTorch

Le Dataset lit les chemins indiqués dans les fichiers `train.csv` et `val.csv`.

Pour chaque exemple, il charge :

- l’audio `.wav` avec `soundfile` ;
- le spectrogramme Mel `.npy` avec `numpy`.

Pour stabiliser l’entraînement, chaque exemple est ramené à une taille fixe :

- un nombre fixe de frames Mel ;
- une longueur audio correspondante.

In [13]:
class DiffWaveDODaDataset(Dataset):
    def __init__(self, dataframe, wav_dir, mel_dir, sample_rate=22050, hop_length=256, crop_mel_frames=62):
        self.df = dataframe.reset_index(drop=True)
        self.wav_dir = Path(wav_dir)
        self.mel_dir = Path(mel_dir)

        self.sample_rate = sample_rate
        self.hop_length = hop_length
        self.crop_mel_frames = crop_mel_frames
        self.audio_length = crop_mel_frames * hop_length

    def __len__(self):
        return len(self.df)

    def _resolve_wav_path(self, row):
        wav_path = Path(row["wav_path"])

        if wav_path.exists():
            return wav_path

        file_id = str(row["id"]).zfill(5)
        return self.wav_dir / f"{file_id}.wav"

    def _resolve_mel_path(self, row):
        mel_path = Path(row["mel_path"])

        if mel_path.exists():
            return mel_path

        file_id = str(row["id"]).zfill(5)
        return self.mel_dir / f"{file_id}.npy"

    def _pad_audio(self, audio):
        if len(audio) < self.audio_length:
            pad_len = self.audio_length - len(audio)
            audio = np.pad(audio, (0, pad_len), mode="constant")
        elif len(audio) > self.audio_length:
            audio = audio[:self.audio_length]

        return audio

    def _pad_mel(self, mel):
        if mel.shape[1] < self.crop_mel_frames:
            pad_len = self.crop_mel_frames - mel.shape[1]
            mel = np.pad(mel, ((0, 0), (0, pad_len)), mode="constant")
        elif mel.shape[1] > self.crop_mel_frames:
            mel = mel[:, :self.crop_mel_frames]

        return mel

    def __getitem__(self, idx):
        row = self.df.iloc[idx]

        wav_path = self._resolve_wav_path(row)
        mel_path = self._resolve_mel_path(row)

        audio, sr = sf.read(wav_path)

        if audio.ndim > 1:
            audio = np.mean(audio, axis=1)

        audio = audio.astype(np.float32)
        mel = np.load(mel_path).astype(np.float32)

        # Crop synchronisé entre le Mel et l'audio
        if mel.shape[1] > self.crop_mel_frames:
            max_start = mel.shape[1] - self.crop_mel_frames
            mel_start = np.random.randint(0, max_start + 1)
            mel_end = mel_start + self.crop_mel_frames

            audio_start = mel_start * self.hop_length
            audio_end = audio_start + self.audio_length

            mel = mel[:, mel_start:mel_end]
            audio = audio[audio_start:audio_end]

        audio = self._pad_audio(audio)
        mel = self._pad_mel(mel)

        audio = torch.tensor(audio, dtype=torch.float32)
        mel = torch.tensor(mel, dtype=torch.float32)

        return {
            "audio": audio,
            "mel": mel,
            "id": row["id"],
            "speaker": row["speaker"],
            "text_latin": row.get("text_latin", "")
        }

## Création des DataLoaders

Les DataLoaders permettent d’envoyer les données au modèle par batch.

On crée ici :

- un DataLoader pour l’entraînement ;
- un DataLoader pour la validation.

On commence avec un batch size modéré pour éviter de saturer la mémoire GPU.

In [112]:
BATCH_SIZE = 8

train_dataset = DiffWaveDODaDataset(
    dataframe=train_df,
    wav_dir=WAV_DIR,
    mel_dir=MEL_DIR,
    sample_rate=summary["sample_rate"],
    hop_length=summary["hop_length"],
    crop_mel_frames=params.crop_mel_frames
)

val_dataset = DiffWaveDODaDataset(
    dataframe=val_df,
    wav_dir=WAV_DIR,
    mel_dir=MEL_DIR,
    sample_rate=summary["sample_rate"],
    hop_length=summary["hop_length"],
    crop_mel_frames=params.crop_mel_frames
)

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=4,
    pin_memory=True,
    drop_last=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=4,
    pin_memory=True,
    drop_last=True
)

print("Nombre de batches train :", len(train_loader))
print("Nombre de batches validation :", len(val_loader))

Nombre de batches train : 811
Nombre de batches validation : 90

## Vérification d’un batch

Avant de lancer l’entraînement, on vérifie qu’un batch se charge correctement.

Cette étape est importante pour confirmer que :

- les audios sont bien lus ;
- les Mel spectrograms sont bien chargés ;
- les dimensions sont compatibles avec DiffWave.

In [113]:
batch = next(iter(train_loader))

audio = batch["audio"]
mel = batch["mel"]

print("Audio shape :", audio.shape)
print("Mel shape :", mel.shape)
print("IDs :", batch["id"][:5])
print("Speakers :", batch["speaker"][:5])

Audio shape : torch.Size([8, 15872])
Mel shape : torch.Size([8, 80, 62])
IDs : tensor([ 1430, 10683,  6210,  6980, 11427])
Speakers : ['M3', 'M1', 'M1', 'M1', 'M1']

## Chargement du modèle DiffWave

On instancie maintenant le modèle DiffWave avec les paramètres fournis par l’implémentation officielle.

À ce stade, le modèle n’est pas encore entraîné sur notre dataset.  
Il est simplement créé avec ses poids initiaux.

In [58]:
model = DiffWave(params).to(device)

num_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print("Nombre de paramètres entraînables :", num_params)

Nombre de paramètres entraînables : 2619971

In [114]:
PRETRAINED_PATH = PROJECT_DIR / "diffwave-ljspeech.pt"

model = DiffWave(params).to(device)
num_params = sum(p.numel() for p in model.parameters() if p.requires_grad)

if PRETRAINED_PATH.exists():
    ckpt = torch.load(PRETRAINED_PATH, map_location=device)
    # checkpoint officiel LJSpeech = directement les poids, pas de clé 'model_state_dict'
    if "model_state_dict" in ckpt:
        model.load_state_dict(ckpt["model_state_dict"], strict=False)
    else:
        model.load_state_dict(ckpt, strict=False)
    print("Fine-tuning : checkpoint LJSpeech chargé.")
else:
    print("From scratch : pas de checkpoint pré-entraîné.")

Fine-tuning : checkpoint LJSpeech chargé.

## Test de passage dans le modèle

Avant l’entraînement, on vérifie qu’un batch peut passer dans le modèle.

On simule une étape de diffusion :

1. on prend un audio propre ;
2. on ajoute du bruit selon un pas de diffusion aléatoire ;
3. le modèle reçoit l’audio bruité, le pas de diffusion et le Mel ;
4. il prédit le bruit.

Si cette cellule fonctionne sans erreur, on pourra passer à la boucle d’entraînement.

In [115]:
audio = batch["audio"].to(device)
mel = batch["mel"].to(device)

# Pas de diffusion aléatoire
t = torch.randint(
    low=0,
    high=len(params.noise_schedule),
    size=(audio.shape[0],),
    device=device
)

# Bruit ajouté
noise = torch.randn_like(audio)

# Schedule de bruit
noise_schedule = torch.tensor(params.noise_schedule, dtype=torch.float32, device=device)
alpha = 1.0 - noise_schedule
alpha_cum = torch.cumprod(alpha, dim=0)

sqrt_alpha_cum = torch.sqrt(alpha_cum[t]).unsqueeze(1)
sqrt_one_minus_alpha_cum = torch.sqrt(1.0 - alpha_cum[t]).unsqueeze(1)

# Création de l'audio bruité
noisy_audio = sqrt_alpha_cum * audio + sqrt_one_minus_alpha_cum * noise

# Passage dans le modèle
with torch.no_grad():
    predicted_noise = model(noisy_audio, t, mel)

print("Audio propre :", audio.shape)
print("Audio bruité :", noisy_audio.shape)
print("Bruit réel :", noise.shape)
print("Bruit prédit :", predicted_noise.shape)

Audio propre : torch.Size([8, 15872])
Audio bruité : torch.Size([8, 15872])
Bruit réel : torch.Size([8, 15872])
Bruit prédit : torch.Size([8, 1, 15872])

# Fin de la préparation modèle

À ce stade :

- les données prétraitées sont chargées ;
- le Dataset PyTorch fonctionne ;
- les DataLoaders sont prêts ;
- le modèle DiffWave est instancié ;
- un premier forward pass a été testé.

La prochaine étape sera l’entraînement du modèle et la sauvegarde d’un checkpoint.

# Entraînement de DiffWave sur DODa

Dans cette partie, on entraîne le modèle DiffWave sur les données prétraitées.

Le principe est le suivant :

1. On prend un audio propre.
2. On choisit un pas de diffusion aléatoire.
3. On ajoute du bruit à l’audio.
4. Le modèle reçoit l’audio bruité, le pas de diffusion et le spectrogramme Mel.
5. Le modèle doit prédire le bruit ajouté.
6. On optimise le modèle avec une MSE Loss.

À la fin de l’entraînement, on sauvegarde un checkpoint qui sera utilisé pour la génération audio.

In [116]:
CHECKPOINT_DIR = PROJECT_DIR / "checkpoints"
FIGURES_DIR = PROJECT_DIR / "figures"
RESULTS_DIR = PROJECT_DIR / "results"

CHECKPOINT_DIR.mkdir(parents=True, exist_ok=True)
FIGURES_DIR.mkdir(parents=True, exist_ok=True)
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

EXPERIMENT_NAME = "diffwave_doda_male"
EXPERIMENT_DIR = CHECKPOINT_DIR / EXPERIMENT_NAME
EXPERIMENT_DIR.mkdir(parents=True, exist_ok=True)

print("Dossier de l'expérience :", EXPERIMENT_DIR)

Dossier de l'expérience : /workspace/DiffWave_Project/checkpoints/diffwave_doda_male

In [117]:
# Préparation du noise schedule

noise_schedule = torch.tensor(
    params.noise_schedule,
    dtype=torch.float32,
    device=device
)

alphas = 1.0 - noise_schedule
alpha_cumprod = torch.cumprod(alphas, dim=0)

NUM_DIFFUSION_STEPS = len(params.noise_schedule)

print("Nombre de diffusion steps :", NUM_DIFFUSION_STEPS)
print("Noise schedule min :", noise_schedule.min().item())
print("Noise schedule max :", noise_schedule.max().item())


def add_noise_to_audio(clean_audio, diffusion_steps):
    """
    Ajoute du bruit à un audio propre selon un pas de diffusion.

    clean_audio : Tensor [B, T]
    diffusion_steps : Tensor [B]

    Retourne :
    - noisy_audio : audio bruité
    - noise : bruit réel ajouté
    """

    noise = torch.randn_like(clean_audio)

    sqrt_alpha_cumprod = torch.sqrt(alpha_cumprod[diffusion_steps]).unsqueeze(1)
    sqrt_one_minus_alpha_cumprod = torch.sqrt(
        1.0 - alpha_cumprod[diffusion_steps]
    ).unsqueeze(1)

    noisy_audio = (
        sqrt_alpha_cumprod * clean_audio
        + sqrt_one_minus_alpha_cumprod * noise
    )

    return noisy_audio, noise

Nombre de diffusion steps : 50
Noise schedule min : 9.999999747378752e-05
Noise schedule max : 0.05000000074505806

In [118]:
import torch.nn.functional as F

LEARNING_RATE = 2e-4

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=LEARNING_RATE
)

scaler = torch.amp.GradScaler('cuda')

def stft_loss(x, y, fft_sizes=[512, 1024, 2048], hop_sizes=[128, 256, 512]):
    """Multi-resolution STFT loss pour capturer les détails fréquentiels."""
    loss = 0.0
    for fft_size, hop_size in zip(fft_sizes, hop_sizes):
        window = torch.hann_window(fft_size, device=x.device)
        X = torch.stft(x, fft_size, hop_size, return_complex=True, window=window)
        Y = torch.stft(y, fft_size, hop_size, return_complex=True, window=window)
        loss += F.l1_loss(X.abs().clamp(min=1e-8).log(), Y.abs().clamp(min=1e-8).log())
    return loss / len(fft_sizes)


STFT_WEIGHT = 0.1

print("Optimizer, scaler AMP et loss définis.")
print("Learning rate :", LEARNING_RATE)

Optimizer, scaler AMP et loss définis.
Learning rate : 0.0002

## Paramètres d'entraînement

On commence avec un entraînement court pour vérifier que le pipeline fonctionne.

L’objectif initial n’est pas d’obtenir une voix parfaite, mais de valider que :

- les données passent correctement dans le modèle ;
- la loss se calcule ;
- le modèle apprend ;
- un checkpoint peut être sauvegardé.

Ensuite, on pourra augmenter le nombre de steps.

In [119]:
MAX_TRAIN_STEPS = 10000    # à augmenter si tout fonctionne
LOG_EVERY = 100
VALID_EVERY = 1000
SAVE_EVERY = 1000

GRAD_CLIP = 1.0

train_losses = []
val_losses = []

print("MAX_TRAIN_STEPS :", MAX_TRAIN_STEPS)
print("Validation toutes les", VALID_EVERY, "steps")
print("Sauvegarde toutes les", SAVE_EVERY, "steps")

MAX_TRAIN_STEPS : 10000
Validation toutes les 1000 steps
Sauvegarde toutes les 1000 steps

In [120]:
def validate_model(model, val_loader, max_batches=20):
    """
    Évalue rapidement le modèle sur quelques batches de validation.
    """

    model.eval()
    total_loss = 0.0
    n_batches = 0

    with torch.no_grad():
        for batch in val_loader:
            audio = batch["audio"].to(device)
            mel = batch["mel"].to(device)

            batch_size = audio.shape[0]

            diffusion_steps = torch.randint(
                low=0,
                high=NUM_DIFFUSION_STEPS,
                size=(batch_size,),
                device=device
            )

            noisy_audio, noise = add_noise_to_audio(audio, diffusion_steps)

            predicted_noise = model(noisy_audio, diffusion_steps, mel)
            if predicted_noise.dim() == 3:
                predicted_noise = predicted_noise.squeeze(1)

            mse = F.mse_loss(predicted_noise, noise)
            stft = stft_loss(predicted_noise, noise)
            loss = mse + STFT_WEIGHT * stft

            total_loss += loss.item()
            n_batches += 1

            if n_batches >= max_batches:
                break

    model.train()

    return total_loss / max(1, n_batches)

In [121]:
import time
from tqdm import tqdm

model.train()
global_step = 0
best_val_loss = float("inf")
train_start = time.time()

progress_bar = tqdm(total=MAX_TRAIN_STEPS, initial=global_step, desc="Entraînement", unit="step")

while global_step < MAX_TRAIN_STEPS:
    for batch in train_loader:
        audio = batch["audio"].to(device)
        mel = batch["mel"].to(device)
        batch_size = audio.shape[0]
        diffusion_steps = torch.randint(
            low=0,
            high=NUM_DIFFUSION_STEPS,
            size=(batch_size,),
            device=device
        )
        noisy_audio, noise = add_noise_to_audio(audio, diffusion_steps)
        with torch.amp.autocast('cuda'):
            predicted_noise = model(noisy_audio, diffusion_steps, mel)
            if predicted_noise.dim() == 3:
                predicted_noise = predicted_noise.squeeze(1)
                
            mse = F.mse_loss(predicted_noise, noise)
            stft = stft_loss(predicted_noise.float(), noise.float())
            loss = mse + STFT_WEIGHT * stft
        optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), GRAD_CLIP)
        optimizer.step()
        global_step += 1
        train_losses.append(loss.item())

        progress_bar.update(1)
        progress_bar.set_postfix({
            "loss": f"{loss.item():.6f}",
            "elapsed": f"{(time.time() - train_start)/60:.1f}min"
        })

        if global_step % LOG_EVERY == 0:
            elapsed = time.time() - train_start
            steps_remaining = MAX_TRAIN_STEPS - global_step
            eta = steps_remaining * (elapsed / global_step)
            tqdm.write(
                f"Step {global_step}/{MAX_TRAIN_STEPS} | "
                f"Train loss: {loss.item():.6f} | "
                f"Elapsed: {elapsed/60:.1f}min | "
                f"ETA: {eta/60:.1f}min"
            )

        if global_step % VALID_EVERY == 0:
            val_start = time.time()
            val_loss = validate_model(model, val_loader)
            val_duration = time.time() - val_start
            val_losses.append({
                "step": global_step,
                "val_loss": val_loss
            })
            tqdm.write(
                f"Step {global_step}/{MAX_TRAIN_STEPS} | "
                f"Val loss: {val_loss:.6f} | "
                f"Validation en {val_duration:.1f}s"
            )
            if val_loss < best_val_loss:
                best_val_loss = val_loss
                best_checkpoint_path = EXPERIMENT_DIR / "best_checkpoint.pt"
                torch.save({
                    "step": global_step,
                    "model_state_dict": model.state_dict(),
                    "optimizer_state_dict": optimizer.state_dict(),
                    "train_losses": train_losses,
                    "val_losses": val_losses,
                    "params": params.__dict__ if hasattr(params, "__dict__") else None,
                    "summary": summary
                }, best_checkpoint_path)
                tqdm.write("Meilleur checkpoint sauvegardé : " + str(best_checkpoint_path))

        if global_step % SAVE_EVERY == 0:
            last_checkpoint_path = EXPERIMENT_DIR / "last_checkpoint.pt"
            torch.save({
                "step": global_step,
                "model_state_dict": model.state_dict(),
                "optimizer_state_dict": optimizer.state_dict(),
                "train_losses": train_losses,
                "val_losses": val_losses,
                "params": params.__dict__ if hasattr(params, "__dict__") else None,
                "summary": summary
            }, last_checkpoint_path)
            tqdm.write("Dernier checkpoint sauvegardé : " + str(last_checkpoint_path))

        if global_step >= MAX_TRAIN_STEPS:
            break

progress_bar.close()
total_time = time.time() - train_start
print(f"Entraînement terminé en {total_time/60:.1f}min ({total_time/3600:.2f}h).")

Entraînement:   0%|          | 0/10000 [00:00<?, ?step/s]

Entraînement:   0%|          | 34/10000 [00:45<3:43:11,  1.34s/step, loss=1.330127, elapsed=0.2min]

Entraînement:   0%|          | 1/10000 [00:00<1:09:53,  2.38step/s]

Entraînement:   0%|          | 1/10000 [00:00<1:09:53,  2.38step/s, loss=2.880355, elapsed=0.0min]

Entraînement:   0%|          | 2/10000 [00:00<47:52,  3.48step/s, loss=2.880355, elapsed=0.0min]

Entraînement:   0%|          | 2/10000 [00:00<47:52,  3.48step/s, loss=1.829675, elapsed=0.0min]

Entraînement:   0%|          | 3/10000 [00:00<40:28,  4.12step/s, loss=1.829675, elapsed=0.0min]

Entraînement:   0%|          | 3/10000 [00:00<40:28,  4.12step/s, loss=1.781127, elapsed=0.0min]

Entraînement:   0%|          | 4/10000 [00:00<36:56,  4.51step/s, loss=1.781127, elapsed=0.0min]

Entraînement:   0%|          | 4/10000 [00:00<36:56,  4.51step/s, loss=1.689373, elapsed=0.0min]

Entraînement:   0%|          | 5/10000 [00:01<35:00,  4.76step/s, loss=1.689373, elapsed=0.0min]

Entraînement:   0%|          | 5/10000 [00:01<35:00,  4.76step/s, loss=1.667945, elapsed=0.0min]

Entraînement:   0%|          | 6/10000 [00:01<33:48,  4.93step/s, loss=1.667945, elapsed=0.0min]

Entraînement:   0%|          | 6/10000 [00:01<33:48,  4.93step/s, loss=1.647276, elapsed=0.0min]

Entraînement:   0%|          | 7/10000 [00:01<33:06,  5.03step/s, loss=1.647276, elapsed=0.0min]

Entraînement:   0%|          | 7/10000 [00:01<33:06,  5.03step/s, loss=1.585409, elapsed=0.0min]

Entraînement:   0%|          | 8/10000 [00:01<32:39,  5.10step/s, loss=1.585409, elapsed=0.0min]

Entraînement:   0%|          | 8/10000 [00:01<32:39,  5.10step/s, loss=1.552618, elapsed=0.0min]

Entraînement:   0%|          | 9/10000 [00:01<32:17,  5.16step/s, loss=1.552618, elapsed=0.0min]

Entraînement:   0%|          | 9/10000 [00:01<32:17,  5.16step/s, loss=1.544047, elapsed=0.0min]

Entraînement:   0%|          | 10/10000 [00:02<32:05,  5.19step/s, loss=1.544047, elapsed=0.0min]

Entraînement:   0%|          | 10/10000 [00:02<32:05,  5.19step/s, loss=1.543812, elapsed=0.0min]

Entraînement:   0%|          | 11/10000 [00:02<31:52,  5.22step/s, loss=1.543812, elapsed=0.0min]

Entraînement:   0%|          | 11/10000 [00:02<31:52,  5.22step/s, loss=1.544677, elapsed=0.0min]

Entraînement:   0%|          | 12/10000 [00:02<31:49,  5.23step/s, loss=1.544677, elapsed=0.0min]

Entraînement:   0%|          | 12/10000 [00:02<31:49,  5.23step/s, loss=1.464852, elapsed=0.0min]

Entraînement:   0%|          | 13/10000 [00:02<31:43,  5.25step/s, loss=1.464852, elapsed=0.0min]

Entraînement:   0%|          | 13/10000 [00:02<31:43,  5.25step/s, loss=1.455277, elapsed=0.0min]

Entraînement:   0%|          | 14/10000 [00:02<31:37,  5.26step/s, loss=1.455277, elapsed=0.0min]

Entraînement:   0%|          | 14/10000 [00:02<31:37,  5.26step/s, loss=1.454767, elapsed=0.0min]

Entraînement:   0%|          | 15/10000 [00:03<31:36,  5.27step/s, loss=1.454767, elapsed=0.0min]

Entraînement:   0%|          | 15/10000 [00:03<31:36,  5.27step/s, loss=1.435920, elapsed=0.1min]

Entraînement:   0%|          | 16/10000 [00:03<31:33,  5.27step/s, loss=1.435920, elapsed=0.1min]

Entraînement:   0%|          | 16/10000 [00:03<31:33,  5.27step/s, loss=1.424067, elapsed=0.1min]

Entraînement:   0%|          | 17/10000 [00:03<31:36,  5.26step/s, loss=1.424067, elapsed=0.1min]

Entraînement:   0%|          | 17/10000 [00:03<31:36,  5.26step/s, loss=1.397201, elapsed=0.1min]

Entraînement:   0%|          | 18/10000 [00:03<31:35,  5.27step/s, loss=1.397201, elapsed=0.1min]

Entraînement:   0%|          | 18/10000 [00:03<31:35,  5.27step/s, loss=1.391031, elapsed=0.1min]

Entraînement:   0%|          | 19/10000 [00:03<31:34,  5.27step/s, loss=1.391031, elapsed=0.1min]

Entraînement:   0%|          | 19/10000 [00:03<31:34,  5.27step/s, loss=1.361299, elapsed=0.1min]

Entraînement:   0%|          | 20/10000 [00:04<31:35,  5.27step/s, loss=1.361299, elapsed=0.1min]

Entraînement:   0%|          | 20/10000 [00:04<31:35,  5.27step/s, loss=1.354428, elapsed=0.1min]

Entraînement:   0%|          | 21/10000 [00:04<31:43,  5.24step/s, loss=1.354428, elapsed=0.1min]

Entraînement:   0%|          | 21/10000 [00:04<31:43,  5.24step/s, loss=1.313038, elapsed=0.1min]

Entraînement:   0%|          | 22/10000 [00:04<31:46,  5.23step/s, loss=1.313038, elapsed=0.1min]

Entraînement:   0%|          | 22/10000 [00:04<31:46,  5.23step/s, loss=1.309621, elapsed=0.1min]

Entraînement:   0%|          | 23/10000 [00:04<31:53,  5.21step/s, loss=1.309621, elapsed=0.1min]

Entraînement:   0%|          | 23/10000 [00:04<31:53,  5.21step/s, loss=1.304945, elapsed=0.1min]

Entraînement:   0%|          | 24/10000 [00:04<31:53,  5.21step/s, loss=1.304945, elapsed=0.1min]

Entraînement:   0%|          | 24/10000 [00:04<31:53,  5.21step/s, loss=1.292094, elapsed=0.1min]

Entraînement:   0%|          | 25/10000 [00:04<31:48,  5.23step/s, loss=1.292094, elapsed=0.1min]

Entraînement:   0%|          | 25/10000 [00:04<31:48,  5.23step/s, loss=1.259210, elapsed=0.1min]

Entraînement:   0%|          | 26/10000 [00:05<31:31,  5.27step/s, loss=1.259210, elapsed=0.1min]

Entraînement:   0%|          | 26/10000 [00:05<31:31,  5.27step/s, loss=1.244481, elapsed=0.1min]

Entraînement:   0%|          | 27/10000 [00:05<31:30,  5.28step/s, loss=1.244481, elapsed=0.1min]

Entraînement:   0%|          | 27/10000 [00:05<31:30,  5.28step/s, loss=1.230320, elapsed=0.1min]

Entraînement:   0%|          | 28/10000 [00:05<31:30,  5.27step/s, loss=1.230320, elapsed=0.1min]

Entraînement:   0%|          | 28/10000 [00:05<31:30,  5.27step/s, loss=1.202809, elapsed=0.1min]

Entraînement:   0%|          | 29/10000 [00:05<31:28,  5.28step/s, loss=1.202809, elapsed=0.1min]

Entraînement:   0%|          | 29/10000 [00:05<31:28,  5.28step/s, loss=1.190603, elapsed=0.1min]

Entraînement:   0%|          | 30/10000 [00:05<31:29,  5.28step/s, loss=1.190603, elapsed=0.1min]

Entraînement:   0%|          | 30/10000 [00:05<31:29,  5.28step/s, loss=1.119529, elapsed=0.1min]

Entraînement:   0%|          | 31/10000 [00:06<31:33,  5.26step/s, loss=1.119529, elapsed=0.1min]

Entraînement:   0%|          | 31/10000 [00:06<31:33,  5.26step/s, loss=1.110092, elapsed=0.1min]

Entraînement:   0%|          | 32/10000 [00:06<31:34,  5.26step/s, loss=1.110092, elapsed=0.1min]

Entraînement:   0%|          | 32/10000 [00:06<31:34,  5.26step/s, loss=1.082565, elapsed=0.1min]

Entraînement:   0%|          | 33/10000 [00:06<31:35,  5.26step/s, loss=1.082565, elapsed=0.1min]

Entraînement:   0%|          | 33/10000 [00:06<31:35,  5.26step/s, loss=1.052408, elapsed=0.1min]

Entraînement:   0%|          | 34/10000 [00:06<31:33,  5.26step/s, loss=1.052408, elapsed=0.1min]

Entraînement:   0%|          | 34/10000 [00:06<31:33,  5.26step/s, loss=1.011536, elapsed=0.1min]

Entraînement:   0%|          | 35/10000 [00:06<31:34,  5.26step/s, loss=1.011536, elapsed=0.1min]

Entraînement:   0%|          | 35/10000 [00:06<31:34,  5.26step/s, loss=0.954068, elapsed=0.1min]

Entraînement:   0%|          | 36/10000 [00:07<31:32,  5.27step/s, loss=0.954068, elapsed=0.1min]

Entraînement:   0%|          | 36/10000 [00:07<31:32,  5.27step/s, loss=0.946201, elapsed=0.1min]

Entraînement:   0%|          | 37/10000 [00:07<31:30,  5.27step/s, loss=0.946201, elapsed=0.1min]

Entraînement:   0%|          | 37/10000 [00:07<31:30,  5.27step/s, loss=0.853984, elapsed=0.1min]

Entraînement:   0%|          | 38/10000 [00:07<31:31,  5.27step/s, loss=0.853984, elapsed=0.1min]

Entraînement:   0%|          | 38/10000 [00:07<31:31,  5.27step/s, loss=0.777199, elapsed=0.1min]

Entraînement:   0%|          | 39/10000 [00:07<31:28,  5.28step/s, loss=0.777199, elapsed=0.1min]

Entraînement:   0%|          | 39/10000 [00:07<31:28,  5.28step/s, loss=0.722812, elapsed=0.1min]

Entraînement:   0%|          | 40/10000 [00:07<31:30,  5.27step/s, loss=0.722812, elapsed=0.1min]

Entraînement:   0%|          | 40/10000 [00:07<31:30,  5.27step/s, loss=0.661686, elapsed=0.1min]

Entraînement:   0%|          | 41/10000 [00:08<31:29,  5.27step/s, loss=0.661686, elapsed=0.1min]

Entraînement:   0%|          | 41/10000 [00:08<31:29,  5.27step/s, loss=0.605384, elapsed=0.1min]

Entraînement:   0%|          | 42/10000 [00:08<31:28,  5.27step/s, loss=0.605384, elapsed=0.1min]

Entraînement:   0%|          | 42/10000 [00:08<31:28,  5.27step/s, loss=0.656247, elapsed=0.1min]

Entraînement:   0%|          | 43/10000 [00:08<31:30,  5.27step/s, loss=0.656247, elapsed=0.1min]

Entraînement:   0%|          | 43/10000 [00:08<31:30,  5.27step/s, loss=0.558427, elapsed=0.1min]

Entraînement:   0%|          | 44/10000 [00:08<31:27,  5.28step/s, loss=0.558427, elapsed=0.1min]

Entraînement:   0%|          | 44/10000 [00:08<31:27,  5.28step/s, loss=0.447190, elapsed=0.1min]

Entraînement:   0%|          | 45/10000 [00:08<31:28,  5.27step/s, loss=0.447190, elapsed=0.1min]

Entraînement:   0%|          | 45/10000 [00:08<31:28,  5.27step/s, loss=0.397848, elapsed=0.1min]

Entraînement:   0%|          | 46/10000 [00:08<31:25,  5.28step/s, loss=0.397848, elapsed=0.1min]

Entraînement:   0%|          | 46/10000 [00:08<31:25,  5.28step/s, loss=0.343730, elapsed=0.1min]

Entraînement:   0%|          | 47/10000 [00:09<31:29,  5.27step/s, loss=0.343730, elapsed=0.1min]

Entraînement:   0%|          | 47/10000 [00:09<31:29,  5.27step/s, loss=0.328934, elapsed=0.2min]

Entraînement:   0%|          | 48/10000 [00:09<31:25,  5.28step/s, loss=0.328934, elapsed=0.2min]

Entraînement:   0%|          | 48/10000 [00:09<31:25,  5.28step/s, loss=0.315253, elapsed=0.2min]

Entraînement:   0%|          | 49/10000 [00:09<31:32,  5.26step/s, loss=0.315253, elapsed=0.2min]

Entraînement:   0%|          | 49/10000 [00:09<31:32,  5.26step/s, loss=0.277173, elapsed=0.2min]

Entraînement:   0%|          | 50/10000 [00:09<31:37,  5.24step/s, loss=0.277173, elapsed=0.2min]

Entraînement:   0%|          | 50/10000 [00:09<31:37,  5.24step/s, loss=0.343157, elapsed=0.2min]

Entraînement:   1%|          | 51/10000 [00:09<31:38,  5.24step/s, loss=0.343157, elapsed=0.2min]

Entraînement:   1%|          | 51/10000 [00:09<31:38,  5.24step/s, loss=0.440498, elapsed=0.2min]

Entraînement:   1%|          | 52/10000 [00:10<31:33,  5.25step/s, loss=0.440498, elapsed=0.2min]

Entraînement:   1%|          | 52/10000 [00:10<31:33,  5.25step/s, loss=0.245882, elapsed=0.2min]

Entraînement:   1%|          | 53/10000 [00:10<31:32,  5.26step/s, loss=0.245882, elapsed=0.2min]

Entraînement:   1%|          | 53/10000 [00:10<31:32,  5.26step/s, loss=0.357970, elapsed=0.2min]

Entraînement:   1%|          | 54/10000 [00:10<31:35,  5.25step/s, loss=0.357970, elapsed=0.2min]

Entraînement:   1%|          | 54/10000 [00:10<31:35,  5.25step/s, loss=0.242296, elapsed=0.2min]

Entraînement:   1%|          | 55/10000 [00:10<31:34,  5.25step/s, loss=0.242296, elapsed=0.2min]

Entraînement:   1%|          | 55/10000 [00:10<31:34,  5.25step/s, loss=0.228223, elapsed=0.2min]

Entraînement:   1%|          | 56/10000 [00:10<31:32,  5.26step/s, loss=0.228223, elapsed=0.2min]

Entraînement:   1%|          | 56/10000 [00:10<31:32,  5.26step/s, loss=0.346099, elapsed=0.2min]

Entraînement:   1%|          | 57/10000 [00:11<31:27,  5.27step/s, loss=0.346099, elapsed=0.2min]

Entraînement:   1%|          | 57/10000 [00:11<31:27,  5.27step/s, loss=0.205690, elapsed=0.2min]

Entraînement:   1%|          | 58/10000 [00:11<31:25,  5.27step/s, loss=0.205690, elapsed=0.2min]

Entraînement:   1%|          | 58/10000 [00:11<31:25,  5.27step/s, loss=0.243174, elapsed=0.2min]

Entraînement:   1%|          | 59/10000 [00:11<31:24,  5.27step/s, loss=0.243174, elapsed=0.2min]

Entraînement:   1%|          | 59/10000 [00:11<31:24,  5.27step/s, loss=0.268138, elapsed=0.2min]

Entraînement:   1%|          | 60/10000 [00:11<31:26,  5.27step/s, loss=0.268138, elapsed=0.2min]

Entraînement:   1%|          | 60/10000 [00:11<31:26,  5.27step/s, loss=0.272893, elapsed=0.2min]

Entraînement:   1%|          | 61/10000 [00:11<31:28,  5.26step/s, loss=0.272893, elapsed=0.2min]

Entraînement:   1%|          | 61/10000 [00:11<31:28,  5.26step/s, loss=0.196201, elapsed=0.2min]

Entraînement:   1%|          | 62/10000 [00:12<31:28,  5.26step/s, loss=0.196201, elapsed=0.2min]

Entraînement:   1%|          | 62/10000 [00:12<31:28,  5.26step/s, loss=0.541533, elapsed=0.2min]

Entraînement:   1%|          | 63/10000 [00:12<31:32,  5.25step/s, loss=0.541533, elapsed=0.2min]

Entraînement:   1%|          | 63/10000 [00:12<31:32,  5.25step/s, loss=0.191615, elapsed=0.2min]

Entraînement:   1%|          | 64/10000 [00:12<31:28,  5.26step/s, loss=0.191615, elapsed=0.2min]

Entraînement:   1%|          | 64/10000 [00:12<31:28,  5.26step/s, loss=0.188642, elapsed=0.2min]

Entraînement:   1%|          | 65/10000 [00:12<31:28,  5.26step/s, loss=0.188642, elapsed=0.2min]

Entraînement:   1%|          | 65/10000 [00:12<31:28,  5.26step/s, loss=0.437202, elapsed=0.2min]

Entraînement:   1%|          | 66/10000 [00:12<31:25,  5.27step/s, loss=0.437202, elapsed=0.2min]

Entraînement:   1%|          | 66/10000 [00:12<31:25,  5.27step/s, loss=0.198214, elapsed=0.2min]

Entraînement:   1%|          | 67/10000 [00:12<31:25,  5.27step/s, loss=0.198214, elapsed=0.2min]

Entraînement:   1%|          | 67/10000 [00:12<31:25,  5.27step/s, loss=0.247492, elapsed=0.2min]

Entraînement:   1%|          | 68/10000 [00:13<31:26,  5.27step/s, loss=0.247492, elapsed=0.2min]

Entraînement:   1%|          | 68/10000 [00:13<31:26,  5.27step/s, loss=0.378197, elapsed=0.2min]

Entraînement:   1%|          | 69/10000 [00:13<31:30,  5.25step/s, loss=0.378197, elapsed=0.2min]

Entraînement:   1%|          | 69/10000 [00:13<31:30,  5.25step/s, loss=0.189121, elapsed=0.2min]

Entraînement:   1%|          | 70/10000 [00:13<31:34,  5.24step/s, loss=0.189121, elapsed=0.2min]

Entraînement:   1%|          | 70/10000 [00:13<31:34,  5.24step/s, loss=0.165012, elapsed=0.2min]

Entraînement:   1%|          | 71/10000 [00:13<31:37,  5.23step/s, loss=0.165012, elapsed=0.2min]

Entraînement:   1%|          | 71/10000 [00:13<31:37,  5.23step/s, loss=0.148906, elapsed=0.2min]

Entraînement:   1%|          | 72/10000 [00:13<31:40,  5.22step/s, loss=0.148906, elapsed=0.2min]

Entraînement:   1%|          | 72/10000 [00:13<31:40,  5.22step/s, loss=0.249586, elapsed=0.2min]

Entraînement:   1%|          | 73/10000 [00:14<31:41,  5.22step/s, loss=0.249586, elapsed=0.2min]

Entraînement:   1%|          | 73/10000 [00:14<31:41,  5.22step/s, loss=0.398670, elapsed=0.2min]

Entraînement:   1%|          | 74/10000 [00:14<31:53,  5.19step/s, loss=0.398670, elapsed=0.2min]

Entraînement:   1%|          | 74/10000 [00:14<31:53,  5.19step/s, loss=0.396140, elapsed=0.2min]

Entraînement:   1%|          | 75/10000 [00:14<31:47,  5.20step/s, loss=0.396140, elapsed=0.2min]

Entraînement:   1%|          | 75/10000 [00:14<31:47,  5.20step/s, loss=0.240465, elapsed=0.2min]

Entraînement:   1%|          | 76/10000 [00:14<31:40,  5.22step/s, loss=0.240465, elapsed=0.2min]

Entraînement:   1%|          | 76/10000 [00:14<31:40,  5.22step/s, loss=0.319040, elapsed=0.2min]

Entraînement:   1%|          | 77/10000 [00:14<31:50,  5.19step/s, loss=0.319040, elapsed=0.2min]

Entraînement:   1%|          | 77/10000 [00:14<31:50,  5.19step/s, loss=0.176723, elapsed=0.2min]

Entraînement:   1%|          | 78/10000 [00:15<31:41,  5.22step/s, loss=0.176723, elapsed=0.2min]

Entraînement:   1%|          | 78/10000 [00:15<31:41,  5.22step/s, loss=0.259199, elapsed=0.3min]

Entraînement:   1%|          | 79/10000 [00:15<31:40,  5.22step/s, loss=0.259199, elapsed=0.3min]

Entraînement:   1%|          | 79/10000 [00:15<31:40,  5.22step/s, loss=0.285155, elapsed=0.3min]

Entraînement:   1%|          | 80/10000 [00:15<31:36,  5.23step/s, loss=0.285155, elapsed=0.3min]

Entraînement:   1%|          | 80/10000 [00:15<31:36,  5.23step/s, loss=0.162813, elapsed=0.3min]

Entraînement:   1%|          | 81/10000 [00:15<31:38,  5.22step/s, loss=0.162813, elapsed=0.3min]

Entraînement:   1%|          | 81/10000 [00:15<31:38,  5.22step/s, loss=0.159532, elapsed=0.3min]

Entraînement:   1%|          | 82/10000 [00:15<31:33,  5.24step/s, loss=0.159532, elapsed=0.3min]

Entraînement:   1%|          | 82/10000 [00:15<31:33,  5.24step/s, loss=0.201462, elapsed=0.3min]

Entraînement:   1%|          | 83/10000 [00:16<31:32,  5.24step/s, loss=0.201462, elapsed=0.3min]

Entraînement:   1%|          | 83/10000 [00:16<31:32,  5.24step/s, loss=0.261821, elapsed=0.3min]

Entraînement:   1%|          | 84/10000 [00:16<31:33,  5.24step/s, loss=0.261821, elapsed=0.3min]

Entraînement:   1%|          | 84/10000 [00:16<31:33,  5.24step/s, loss=0.116660, elapsed=0.3min]

Entraînement:   1%|          | 85/10000 [00:16<31:32,  5.24step/s, loss=0.116660, elapsed=0.3min]

Entraînement:   1%|          | 85/10000 [00:16<31:32,  5.24step/s, loss=0.150812, elapsed=0.3min]

Entraînement:   1%|          | 86/10000 [00:16<31:31,  5.24step/s, loss=0.150812, elapsed=0.3min]

Entraînement:   1%|          | 86/10000 [00:16<31:31,  5.24step/s, loss=0.139014, elapsed=0.3min]

Entraînement:   1%|          | 87/10000 [00:16<31:31,  5.24step/s, loss=0.139014, elapsed=0.3min]

Entraînement:   1%|          | 87/10000 [00:16<31:31,  5.24step/s, loss=0.110026, elapsed=0.3min]

Entraînement:   1%|          | 88/10000 [00:16<31:29,  5.25step/s, loss=0.110026, elapsed=0.3min]

Entraînement:   1%|          | 88/10000 [00:16<31:29,  5.25step/s, loss=0.140605, elapsed=0.3min]

Entraînement:   1%|          | 89/10000 [00:17<31:28,  5.25step/s, loss=0.140605, elapsed=0.3min]

Entraînement:   1%|          | 89/10000 [00:17<31:28,  5.25step/s, loss=0.166642, elapsed=0.3min]

Entraînement:   1%|          | 90/10000 [00:17<31:25,  5.26step/s, loss=0.166642, elapsed=0.3min]

Entraînement:   1%|          | 90/10000 [00:17<31:25,  5.26step/s, loss=0.111693, elapsed=0.3min]

Entraînement:   1%|          | 91/10000 [00:17<31:30,  5.24step/s, loss=0.111693, elapsed=0.3min]

Entraînement:   1%|          | 91/10000 [00:17<31:30,  5.24step/s, loss=0.161981, elapsed=0.3min]

Entraînement:   1%|          | 92/10000 [00:17<31:33,  5.23step/s, loss=0.161981, elapsed=0.3min]

Entraînement:   1%|          | 92/10000 [00:17<31:33,  5.23step/s, loss=0.100927, elapsed=0.3min]

Entraînement:   1%|          | 93/10000 [00:17<31:37,  5.22step/s, loss=0.100927, elapsed=0.3min]

Entraînement:   1%|          | 93/10000 [00:17<31:37,  5.22step/s, loss=0.146533, elapsed=0.3min]

Entraînement:   1%|          | 94/10000 [00:18<31:30,  5.24step/s, loss=0.146533, elapsed=0.3min]

Entraînement:   1%|          | 94/10000 [00:18<31:30,  5.24step/s, loss=0.141953, elapsed=0.3min]

Entraînement:   1%|          | 95/10000 [00:18<31:33,  5.23step/s, loss=0.141953, elapsed=0.3min]

Entraînement:   1%|          | 95/10000 [00:18<31:33,  5.23step/s, loss=0.218468, elapsed=0.3min]

Entraînement:   1%|          | 96/10000 [00:18<31:29,  5.24step/s, loss=0.218468, elapsed=0.3min]

Entraînement:   1%|          | 96/10000 [00:18<31:29,  5.24step/s, loss=0.210093, elapsed=0.3min]

Entraînement:   1%|          | 97/10000 [00:18<31:33,  5.23step/s, loss=0.210093, elapsed=0.3min]

Entraînement:   1%|          | 97/10000 [00:18<31:33,  5.23step/s, loss=0.120966, elapsed=0.3min]

Entraînement:   1%|          | 98/10000 [00:18<31:28,  5.24step/s, loss=0.120966, elapsed=0.3min]

Entraînement:   1%|          | 98/10000 [00:18<31:28,  5.24step/s, loss=0.129322, elapsed=0.3min]

Entraînement:   1%|          | 99/10000 [00:19<31:33,  5.23step/s, loss=0.129322, elapsed=0.3min]

Entraînement:   1%|          | 99/10000 [00:19<31:33,  5.23step/s, loss=0.146360, elapsed=0.3min]

Entraînement:   1%|          | 100/10000 [00:19<31:31,  5.24step/s, loss=0.146360, elapsed=0.3min]

Entraînement:   1%|          | 100/10000 [00:19<31:31,  5.24step/s, loss=0.109116, elapsed=0.3min]

Entraînement:   1%|          | 100/10000 [00:19<31:31,  5.24step/s, loss=0.109116, elapsed=0.3min]

Entraînement:   1%|          | 101/10000 [00:19<31:49,  5.18step/s, loss=0.109116, elapsed=0.3min]

Entraînement:   1%|          | 101/10000 [00:19<31:49,  5.18step/s, loss=0.083736, elapsed=0.3min]

Step 100/10000 | Train loss: 0.109116 | Elapsed: 0.3min | ETA: 31.8min

Entraînement:   1%|          | 102/10000 [00:19<31:39,  5.21step/s, loss=0.083736, elapsed=0.3min]

Entraînement:   1%|          | 102/10000 [00:19<31:39,  5.21step/s, loss=0.249410, elapsed=0.3min]

Entraînement:   1%|          | 103/10000 [00:19<31:34,  5.22step/s, loss=0.249410, elapsed=0.3min]

Entraînement:   1%|          | 103/10000 [00:19<31:34,  5.22step/s, loss=0.147559, elapsed=0.3min]

Entraînement:   1%|          | 104/10000 [00:20<31:29,  5.24step/s, loss=0.147559, elapsed=0.3min]

Entraînement:   1%|          | 104/10000 [00:20<31:29,  5.24step/s, loss=0.110912, elapsed=0.3min]

Entraînement:   1%|          | 105/10000 [00:20<31:23,  5.25step/s, loss=0.110912, elapsed=0.3min]

Entraînement:   1%|          | 105/10000 [00:20<31:23,  5.25step/s, loss=0.122400, elapsed=0.3min]

Entraînement:   1%|          | 106/10000 [00:20<31:22,  5.26step/s, loss=0.122400, elapsed=0.3min]

Entraînement:   1%|          | 106/10000 [00:20<31:22,  5.26step/s, loss=0.152566, elapsed=0.3min]

Entraînement:   1%|          | 107/10000 [00:20<31:24,  5.25step/s, loss=0.152566, elapsed=0.3min]

Entraînement:   1%|          | 107/10000 [00:20<31:24,  5.25step/s, loss=0.092347, elapsed=0.3min]

Entraînement:   1%|          | 108/10000 [00:20<31:26,  5.24step/s, loss=0.092347, elapsed=0.3min]

Entraînement:   1%|          | 108/10000 [00:20<31:26,  5.24step/s, loss=0.103735, elapsed=0.3min]

Entraînement:   1%|          | 109/10000 [00:20<31:21,  5.26step/s, loss=0.103735, elapsed=0.3min]

Entraînement:   1%|          | 109/10000 [00:20<31:21,  5.26step/s, loss=0.226307, elapsed=0.3min]

Entraînement:   1%|          | 110/10000 [00:21<31:19,  5.26step/s, loss=0.226307, elapsed=0.3min]

Entraînement:   1%|          | 110/10000 [00:21<31:19,  5.26step/s, loss=0.248703, elapsed=0.4min]

Entraînement:   1%|          | 111/10000 [00:21<31:17,  5.27step/s, loss=0.248703, elapsed=0.4min]

Entraînement:   1%|          | 111/10000 [00:21<31:17,  5.27step/s, loss=0.117133, elapsed=0.4min]

Entraînement:   1%|          | 112/10000 [00:21<31:15,  5.27step/s, loss=0.117133, elapsed=0.4min]

Entraînement:   1%|          | 112/10000 [00:21<31:15,  5.27step/s, loss=0.114062, elapsed=0.4min]

Entraînement:   1%|          | 113/10000 [00:21<31:16,  5.27step/s, loss=0.114062, elapsed=0.4min]

Entraînement:   1%|          | 113/10000 [00:21<31:16,  5.27step/s, loss=0.158683, elapsed=0.4min]

Entraînement:   1%|          | 114/10000 [00:21<31:15,  5.27step/s, loss=0.158683, elapsed=0.4min]

Entraînement:   1%|          | 114/10000 [00:21<31:15,  5.27step/s, loss=0.086746, elapsed=0.4min]

Entraînement:   1%|          | 115/10000 [00:22<31:16,  5.27step/s, loss=0.086746, elapsed=0.4min]

Entraînement:   1%|          | 115/10000 [00:22<31:16,  5.27step/s, loss=0.090636, elapsed=0.4min]

Entraînement:   1%|          | 116/10000 [00:22<31:14,  5.27step/s, loss=0.090636, elapsed=0.4min]

Entraînement:   1%|          | 116/10000 [00:22<31:14,  5.27step/s, loss=0.125262, elapsed=0.4min]

Entraînement:   1%|          | 117/10000 [00:22<31:15,  5.27step/s, loss=0.125262, elapsed=0.4min]

Entraînement:   1%|          | 117/10000 [00:22<31:15,  5.27step/s, loss=0.090863, elapsed=0.4min]

Entraînement:   1%|          | 118/10000 [00:22<31:14,  5.27step/s, loss=0.090863, elapsed=0.4min]

Entraînement:   1%|          | 118/10000 [00:22<31:14,  5.27step/s, loss=0.076679, elapsed=0.4min]

Entraînement:   1%|          | 119/10000 [00:22<31:15,  5.27step/s, loss=0.076679, elapsed=0.4min]

Entraînement:   1%|          | 119/10000 [00:22<31:15,  5.27step/s, loss=0.075451, elapsed=0.4min]

Entraînement:   1%|          | 120/10000 [00:23<31:13,  5.27step/s, loss=0.075451, elapsed=0.4min]

Entraînement:   1%|          | 120/10000 [00:23<31:13,  5.27step/s, loss=0.158243, elapsed=0.4min]

Entraînement:   1%|          | 121/10000 [00:23<31:12,  5.28step/s, loss=0.158243, elapsed=0.4min]

Entraînement:   1%|          | 121/10000 [00:23<31:12,  5.28step/s, loss=0.081247, elapsed=0.4min]

Entraînement:   1%|          | 122/10000 [00:23<31:18,  5.26step/s, loss=0.081247, elapsed=0.4min]

Entraînement:   1%|          | 122/10000 [00:23<31:18,  5.26step/s, loss=0.136998, elapsed=0.4min]

Entraînement:   1%|          | 123/10000 [00:23<31:19,  5.26step/s, loss=0.136998, elapsed=0.4min]

Entraînement:   1%|          | 123/10000 [00:23<31:19,  5.26step/s, loss=0.099544, elapsed=0.4min]

Entraînement:   1%|          | 124/10000 [00:23<31:26,  5.23step/s, loss=0.099544, elapsed=0.4min]

Entraînement:   1%|          | 124/10000 [00:23<31:26,  5.23step/s, loss=0.084973, elapsed=0.4min]

Entraînement:   1%|▏         | 125/10000 [00:24<31:22,  5.24step/s, loss=0.084973, elapsed=0.4min]

Entraînement:   1%|▏         | 125/10000 [00:24<31:22,  5.24step/s, loss=0.086716, elapsed=0.4min]

Entraînement:   1%|▏         | 126/10000 [00:24<31:18,  5.26step/s, loss=0.086716, elapsed=0.4min]

Entraînement:   1%|▏         | 126/10000 [00:24<31:18,  5.26step/s, loss=0.072945, elapsed=0.4min]

Entraînement:   1%|▏         | 127/10000 [00:24<31:14,  5.27step/s, loss=0.072945, elapsed=0.4min]

Entraînement:   1%|▏         | 127/10000 [00:24<31:14,  5.27step/s, loss=0.139401, elapsed=0.4min]

Entraînement:   1%|▏         | 128/10000 [00:24<31:12,  5.27step/s, loss=0.139401, elapsed=0.4min]

Entraînement:   1%|▏         | 128/10000 [00:24<31:12,  5.27step/s, loss=0.079691, elapsed=0.4min]

Entraînement:   1%|▏         | 129/10000 [00:24<31:15,  5.26step/s, loss=0.079691, elapsed=0.4min]

Entraînement:   1%|▏         | 129/10000 [00:24<31:15,  5.26step/s, loss=0.063044, elapsed=0.4min]

Entraînement:   1%|▏         | 130/10000 [00:24<31:15,  5.26step/s, loss=0.063044, elapsed=0.4min]

Entraînement:   1%|▏         | 130/10000 [00:24<31:15,  5.26step/s, loss=0.237298, elapsed=0.4min]

Entraînement:   1%|▏         | 131/10000 [00:25<31:15,  5.26step/s, loss=0.237298, elapsed=0.4min]

Entraînement:   1%|▏         | 131/10000 [00:25<31:15,  5.26step/s, loss=0.066279, elapsed=0.4min]

Entraînement:   1%|▏         | 132/10000 [00:25<31:12,  5.27step/s, loss=0.066279, elapsed=0.4min]

Entraînement:   1%|▏         | 132/10000 [00:25<31:12,  5.27step/s, loss=0.156102, elapsed=0.4min]

Entraînement:   1%|▏         | 133/10000 [00:25<31:14,  5.26step/s, loss=0.156102, elapsed=0.4min]

Entraînement:   1%|▏         | 133/10000 [00:25<31:14,  5.26step/s, loss=0.102715, elapsed=0.4min]

Entraînement:   1%|▏         | 134/10000 [00:25<31:14,  5.26step/s, loss=0.102715, elapsed=0.4min]

Entraînement:   1%|▏         | 134/10000 [00:25<31:14,  5.26step/s, loss=0.204130, elapsed=0.4min]

Entraînement:   1%|▏         | 135/10000 [00:25<31:18,  5.25step/s, loss=0.204130, elapsed=0.4min]

Entraînement:   1%|▏         | 135/10000 [00:25<31:18,  5.25step/s, loss=0.093987, elapsed=0.4min]

Entraînement:   1%|▏         | 136/10000 [00:26<31:17,  5.25step/s, loss=0.093987, elapsed=0.4min]

Entraînement:   1%|▏         | 136/10000 [00:26<31:17,  5.25step/s, loss=0.083681, elapsed=0.4min]

Entraînement:   1%|▏         | 137/10000 [00:26<31:17,  5.25step/s, loss=0.083681, elapsed=0.4min]

Entraînement:   1%|▏         | 137/10000 [00:26<31:17,  5.25step/s, loss=0.122501, elapsed=0.4min]

Entraînement:   1%|▏         | 138/10000 [00:26<31:15,  5.26step/s, loss=0.122501, elapsed=0.4min]

Entraînement:   1%|▏         | 138/10000 [00:26<31:15,  5.26step/s, loss=0.168299, elapsed=0.4min]

Entraînement:   1%|▏         | 139/10000 [00:26<31:09,  5.27step/s, loss=0.168299, elapsed=0.4min]

Entraînement:   1%|▏         | 139/10000 [00:26<31:09,  5.27step/s, loss=0.464212, elapsed=0.4min]

Entraînement:   1%|▏         | 140/10000 [00:26<31:08,  5.28step/s, loss=0.464212, elapsed=0.4min]

Entraînement:   1%|▏         | 140/10000 [00:26<31:08,  5.28step/s, loss=0.176872, elapsed=0.4min]

Entraînement:   1%|▏         | 141/10000 [00:27<31:05,  5.28step/s, loss=0.176872, elapsed=0.4min]

Entraînement:   1%|▏         | 141/10000 [00:27<31:05,  5.28step/s, loss=0.101435, elapsed=0.5min]

Entraînement:   1%|▏         | 142/10000 [00:27<31:02,  5.29step/s, loss=0.101435, elapsed=0.5min]

Entraînement:   1%|▏         | 142/10000 [00:27<31:02,  5.29step/s, loss=0.195171, elapsed=0.5min]

Entraînement:   1%|▏         | 143/10000 [00:27<31:05,  5.28step/s, loss=0.195171, elapsed=0.5min]

Entraînement:   1%|▏         | 143/10000 [00:27<31:05,  5.28step/s, loss=0.100086, elapsed=0.5min]

Entraînement:   1%|▏         | 144/10000 [00:27<31:07,  5.28step/s, loss=0.100086, elapsed=0.5min]

Entraînement:   1%|▏         | 144/10000 [00:27<31:07,  5.28step/s, loss=0.165663, elapsed=0.5min]

Entraînement:   1%|▏         | 145/10000 [00:27<31:10,  5.27step/s, loss=0.165663, elapsed=0.5min]

Entraînement:   1%|▏         | 145/10000 [00:27<31:10,  5.27step/s, loss=0.077342, elapsed=0.5min]

Entraînement:   1%|▏         | 146/10000 [00:28<31:15,  5.26step/s, loss=0.077342, elapsed=0.5min]

Entraînement:   1%|▏         | 146/10000 [00:28<31:15,  5.26step/s, loss=0.178918, elapsed=0.5min]

Entraînement:   1%|▏         | 147/10000 [00:28<31:14,  5.26step/s, loss=0.178918, elapsed=0.5min]

Entraînement:   1%|▏         | 147/10000 [00:28<31:14,  5.26step/s, loss=0.141889, elapsed=0.5min]

Entraînement:   1%|▏         | 148/10000 [00:28<31:18,  5.25step/s, loss=0.141889, elapsed=0.5min]

Entraînement:   1%|▏         | 148/10000 [00:28<31:18,  5.25step/s, loss=0.109427, elapsed=0.5min]

Entraînement:   1%|▏         | 149/10000 [00:28<31:18,  5.24step/s, loss=0.109427, elapsed=0.5min]

Entraînement:   1%|▏         | 149/10000 [00:28<31:18,  5.24step/s, loss=0.115139, elapsed=0.5min]

Entraînement:   2%|▏         | 150/10000 [00:28<31:17,  5.25step/s, loss=0.115139, elapsed=0.5min]

Entraînement:   2%|▏         | 150/10000 [00:28<31:17,  5.25step/s, loss=0.110744, elapsed=0.5min]

Entraînement:   2%|▏         | 151/10000 [00:28<31:14,  5.25step/s, loss=0.110744, elapsed=0.5min]

Entraînement:   2%|▏         | 151/10000 [00:28<31:14,  5.25step/s, loss=0.142252, elapsed=0.5min]

Entraînement:   2%|▏         | 152/10000 [00:29<31:21,  5.23step/s, loss=0.142252, elapsed=0.5min]

Entraînement:   2%|▏         | 152/10000 [00:29<31:21,  5.23step/s, loss=0.076453, elapsed=0.5min]

Entraînement:   2%|▏         | 153/10000 [00:29<31:22,  5.23step/s, loss=0.076453, elapsed=0.5min]

Entraînement:   2%|▏         | 153/10000 [00:29<31:22,  5.23step/s, loss=0.086869, elapsed=0.5min]

Entraînement:   2%|▏         | 154/10000 [00:29<31:21,  5.23step/s, loss=0.086869, elapsed=0.5min]

Entraînement:   2%|▏         | 154/10000 [00:29<31:21,  5.23step/s, loss=0.068711, elapsed=0.5min]

Entraînement:   2%|▏         | 155/10000 [00:29<31:19,  5.24step/s, loss=0.068711, elapsed=0.5min]

Entraînement:   2%|▏         | 155/10000 [00:29<31:19,  5.24step/s, loss=0.098141, elapsed=0.5min]

Entraînement:   2%|▏         | 156/10000 [00:29<31:17,  5.24step/s, loss=0.098141, elapsed=0.5min]

Entraînement:   2%|▏         | 156/10000 [00:29<31:17,  5.24step/s, loss=0.201934, elapsed=0.5min]

Entraînement:   2%|▏         | 157/10000 [00:30<31:12,  5.26step/s, loss=0.201934, elapsed=0.5min]

Entraînement:   2%|▏         | 157/10000 [00:30<31:12,  5.26step/s, loss=0.197012, elapsed=0.5min]

Entraînement:   2%|▏         | 158/10000 [00:30<31:21,  5.23step/s, loss=0.197012, elapsed=0.5min]

Entraînement:   2%|▏         | 158/10000 [00:30<31:21,  5.23step/s, loss=0.103072, elapsed=0.5min]

Entraînement:   2%|▏         | 159/10000 [00:30<31:17,  5.24step/s, loss=0.103072, elapsed=0.5min]

Entraînement:   2%|▏         | 159/10000 [00:30<31:17,  5.24step/s, loss=0.085754, elapsed=0.5min]

Entraînement:   2%|▏         | 160/10000 [00:30<31:14,  5.25step/s, loss=0.085754, elapsed=0.5min]

Entraînement:   2%|▏         | 160/10000 [00:30<31:14,  5.25step/s, loss=0.155538, elapsed=0.5min]

Entraînement:   2%|▏         | 161/10000 [00:30<31:11,  5.26step/s, loss=0.155538, elapsed=0.5min]

Entraînement:   2%|▏         | 161/10000 [00:30<31:11,  5.26step/s, loss=0.108626, elapsed=0.5min]

Entraînement:   2%|▏         | 162/10000 [00:31<31:04,  5.28step/s, loss=0.108626, elapsed=0.5min]

Entraînement:   2%|▏         | 162/10000 [00:31<31:04,  5.28step/s, loss=0.075497, elapsed=0.5min]

Entraînement:   2%|▏         | 163/10000 [00:31<31:09,  5.26step/s, loss=0.075497, elapsed=0.5min]

Entraînement:   2%|▏         | 163/10000 [00:31<31:09,  5.26step/s, loss=0.086715, elapsed=0.5min]

Entraînement:   2%|▏         | 164/10000 [00:31<31:05,  5.27step/s, loss=0.086715, elapsed=0.5min]

Entraînement:   2%|▏         | 164/10000 [00:31<31:05,  5.27step/s, loss=0.096868, elapsed=0.5min]

Entraînement:   2%|▏         | 165/10000 [00:31<31:15,  5.24step/s, loss=0.096868, elapsed=0.5min]

Entraînement:   2%|▏         | 165/10000 [00:31<31:15,  5.24step/s, loss=0.182538, elapsed=0.5min]

Entraînement:   2%|▏         | 166/10000 [00:31<31:16,  5.24step/s, loss=0.182538, elapsed=0.5min]

Entraînement:   2%|▏         | 166/10000 [00:31<31:16,  5.24step/s, loss=0.109980, elapsed=0.5min]

Entraînement:   2%|▏         | 167/10000 [00:32<31:16,  5.24step/s, loss=0.109980, elapsed=0.5min]

Entraînement:   2%|▏         | 167/10000 [00:32<31:16,  5.24step/s, loss=0.101268, elapsed=0.5min]

Entraînement:   2%|▏         | 168/10000 [00:32<31:21,  5.23step/s, loss=0.101268, elapsed=0.5min]

Entraînement:   2%|▏         | 168/10000 [00:32<31:21,  5.23step/s, loss=0.078884, elapsed=0.5min]

Entraînement:   2%|▏         | 169/10000 [00:32<31:13,  5.25step/s, loss=0.078884, elapsed=0.5min]

Entraînement:   2%|▏         | 169/10000 [00:32<31:13,  5.25step/s, loss=0.266105, elapsed=0.5min]

Entraînement:   2%|▏         | 170/10000 [00:32<31:20,  5.23step/s, loss=0.266105, elapsed=0.5min]

Entraînement:   2%|▏         | 170/10000 [00:32<31:20,  5.23step/s, loss=0.104680, elapsed=0.5min]

Entraînement:   2%|▏         | 171/10000 [00:32<31:16,  5.24step/s, loss=0.104680, elapsed=0.5min]

Entraînement:   2%|▏         | 171/10000 [00:32<31:16,  5.24step/s, loss=0.062601, elapsed=0.5min]

Entraînement:   2%|▏         | 172/10000 [00:32<31:14,  5.24step/s, loss=0.062601, elapsed=0.5min]

Entraînement:   2%|▏         | 172/10000 [00:32<31:14,  5.24step/s, loss=0.079410, elapsed=0.5min]

Entraînement:   2%|▏         | 173/10000 [00:33<31:11,  5.25step/s, loss=0.079410, elapsed=0.5min]

Entraînement:   2%|▏         | 173/10000 [00:33<31:11,  5.25step/s, loss=0.104996, elapsed=0.6min]

Entraînement:   2%|▏         | 174/10000 [00:33<31:07,  5.26step/s, loss=0.104996, elapsed=0.6min]

Entraînement:   2%|▏         | 174/10000 [00:33<31:07,  5.26step/s, loss=0.161709, elapsed=0.6min]

Entraînement:   2%|▏         | 175/10000 [00:33<31:10,  5.25step/s, loss=0.161709, elapsed=0.6min]

Entraînement:   2%|▏         | 175/10000 [00:33<31:10,  5.25step/s, loss=0.115320, elapsed=0.6min]

Entraînement:   2%|▏         | 176/10000 [00:33<31:11,  5.25step/s, loss=0.115320, elapsed=0.6min]

Entraînement:   2%|▏         | 176/10000 [00:33<31:11,  5.25step/s, loss=0.118871, elapsed=0.6min]

Entraînement:   2%|▏         | 177/10000 [00:33<31:07,  5.26step/s, loss=0.118871, elapsed=0.6min]

Entraînement:   2%|▏         | 177/10000 [00:33<31:07,  5.26step/s, loss=0.071876, elapsed=0.6min]

Entraînement:   2%|▏         | 178/10000 [00:34<31:15,  5.24step/s, loss=0.071876, elapsed=0.6min]

Entraînement:   2%|▏         | 178/10000 [00:34<31:15,  5.24step/s, loss=0.074122, elapsed=0.6min]

Entraînement:   2%|▏         | 179/10000 [00:34<31:10,  5.25step/s, loss=0.074122, elapsed=0.6min]

Entraînement:   2%|▏         | 179/10000 [00:34<31:10,  5.25step/s, loss=0.097835, elapsed=0.6min]

Entraînement:   2%|▏         | 180/10000 [00:34<31:05,  5.26step/s, loss=0.097835, elapsed=0.6min]

Entraînement:   2%|▏         | 180/10000 [00:34<31:05,  5.26step/s, loss=0.119539, elapsed=0.6min]

Entraînement:   2%|▏         | 181/10000 [00:34<31:04,  5.26step/s, loss=0.119539, elapsed=0.6min]

Entraînement:   2%|▏         | 181/10000 [00:34<31:04,  5.26step/s, loss=0.072175, elapsed=0.6min]

Entraînement:   2%|▏         | 182/10000 [00:34<31:03,  5.27step/s, loss=0.072175, elapsed=0.6min]

Entraînement:   2%|▏         | 182/10000 [00:34<31:03,  5.27step/s, loss=0.122064, elapsed=0.6min]

Entraînement:   2%|▏         | 183/10000 [00:35<31:00,  5.28step/s, loss=0.122064, elapsed=0.6min]

Entraînement:   2%|▏         | 183/10000 [00:35<31:00,  5.28step/s, loss=0.163080, elapsed=0.6min]

Entraînement:   2%|▏         | 184/10000 [00:35<31:10,  5.25step/s, loss=0.163080, elapsed=0.6min]

Entraînement:   2%|▏         | 184/10000 [00:35<31:10,  5.25step/s, loss=0.086118, elapsed=0.6min]

Entraînement:   2%|▏         | 185/10000 [00:35<31:05,  5.26step/s, loss=0.086118, elapsed=0.6min]

Entraînement:   2%|▏         | 185/10000 [00:35<31:05,  5.26step/s, loss=0.085259, elapsed=0.6min]

Entraînement:   2%|▏         | 186/10000 [00:35<30:59,  5.28step/s, loss=0.085259, elapsed=0.6min]

Entraînement:   2%|▏         | 186/10000 [00:35<30:59,  5.28step/s, loss=0.054105, elapsed=0.6min]

Entraînement:   2%|▏         | 187/10000 [00:35<30:57,  5.28step/s, loss=0.054105, elapsed=0.6min]

Entraînement:   2%|▏         | 187/10000 [00:35<30:57,  5.28step/s, loss=0.074453, elapsed=0.6min]

Entraînement:   2%|▏         | 188/10000 [00:36<30:57,  5.28step/s, loss=0.074453, elapsed=0.6min]

Entraînement:   2%|▏         | 188/10000 [00:36<30:57,  5.28step/s, loss=0.097529, elapsed=0.6min]

Entraînement:   2%|▏         | 189/10000 [00:36<30:57,  5.28step/s, loss=0.097529, elapsed=0.6min]

Entraînement:   2%|▏         | 189/10000 [00:36<30:57,  5.28step/s, loss=0.188931, elapsed=0.6min]

Entraînement:   2%|▏         | 190/10000 [00:36<30:54,  5.29step/s, loss=0.188931, elapsed=0.6min]

Entraînement:   2%|▏         | 190/10000 [00:36<30:54,  5.29step/s, loss=0.261334, elapsed=0.6min]

Entraînement:   2%|▏         | 191/10000 [00:36<30:53,  5.29step/s, loss=0.261334, elapsed=0.6min]

Entraînement:   2%|▏         | 191/10000 [00:36<30:53,  5.29step/s, loss=0.125767, elapsed=0.6min]

Entraînement:   2%|▏         | 192/10000 [00:36<30:52,  5.29step/s, loss=0.125767, elapsed=0.6min]

Entraînement:   2%|▏         | 192/10000 [00:36<30:52,  5.29step/s, loss=0.318732, elapsed=0.6min]

Entraînement:   2%|▏         | 193/10000 [00:36<30:56,  5.28step/s, loss=0.318732, elapsed=0.6min]

Entraînement:   2%|▏         | 193/10000 [00:36<30:56,  5.28step/s, loss=0.068080, elapsed=0.6min]

Entraînement:   2%|▏         | 194/10000 [00:37<30:57,  5.28step/s, loss=0.068080, elapsed=0.6min]

Entraînement:   2%|▏         | 194/10000 [00:37<30:57,  5.28step/s, loss=0.137315, elapsed=0.6min]

Entraînement:   2%|▏         | 195/10000 [00:37<30:57,  5.28step/s, loss=0.137315, elapsed=0.6min]

Entraînement:   2%|▏         | 195/10000 [00:37<30:57,  5.28step/s, loss=0.271421, elapsed=0.6min]

Entraînement:   2%|▏         | 196/10000 [00:37<30:57,  5.28step/s, loss=0.271421, elapsed=0.6min]

Entraînement:   2%|▏         | 196/10000 [00:37<30:57,  5.28step/s, loss=0.108242, elapsed=0.6min]

Entraînement:   2%|▏         | 197/10000 [00:37<30:56,  5.28step/s, loss=0.108242, elapsed=0.6min]

Entraînement:   2%|▏         | 197/10000 [00:37<30:56,  5.28step/s, loss=0.091824, elapsed=0.6min]

Entraînement:   2%|▏         | 198/10000 [00:37<30:55,  5.28step/s, loss=0.091824, elapsed=0.6min]

Entraînement:   2%|▏         | 198/10000 [00:37<30:55,  5.28step/s, loss=0.079683, elapsed=0.6min]

Entraînement:   2%|▏         | 199/10000 [00:38<30:55,  5.28step/s, loss=0.079683, elapsed=0.6min]

Entraînement:   2%|▏         | 199/10000 [00:38<30:55,  5.28step/s, loss=0.059055, elapsed=0.6min]

Entraînement:   2%|▏         | 200/10000 [00:38<30:55,  5.28step/s, loss=0.059055, elapsed=0.6min]

Entraînement:   2%|▏         | 200/10000 [00:38<30:55,  5.28step/s, loss=0.070913, elapsed=0.6min]

Entraînement:   2%|▏         | 200/10000 [00:38<30:55,  5.28step/s, loss=0.070913, elapsed=0.6min]

Entraînement:   2%|▏         | 201/10000 [00:38<31:10,  5.24step/s, loss=0.070913, elapsed=0.6min]

Entraînement:   2%|▏         | 201/10000 [00:38<31:10,  5.24step/s, loss=0.118390, elapsed=0.6min]

Step 200/10000 | Train loss: 0.070913 | Elapsed: 0.6min | ETA: 31.3min

Entraînement:   2%|▏         | 202/10000 [00:38<31:06,  5.25step/s, loss=0.118390, elapsed=0.6min]

Entraînement:   2%|▏         | 202/10000 [00:38<31:06,  5.25step/s, loss=0.100735, elapsed=0.6min]

Entraînement:   2%|▏         | 203/10000 [00:38<31:04,  5.26step/s, loss=0.100735, elapsed=0.6min]

Entraînement:   2%|▏         | 203/10000 [00:38<31:04,  5.26step/s, loss=0.165837, elapsed=0.6min]

Entraînement:   2%|▏         | 204/10000 [00:39<31:01,  5.26step/s, loss=0.165837, elapsed=0.6min]

Entraînement:   2%|▏         | 204/10000 [00:39<31:01,  5.26step/s, loss=0.102410, elapsed=0.7min]

Entraînement:   2%|▏         | 205/10000 [00:39<31:01,  5.26step/s, loss=0.102410, elapsed=0.7min]

Entraînement:   2%|▏         | 205/10000 [00:39<31:01,  5.26step/s, loss=0.089774, elapsed=0.7min]

Entraînement:   2%|▏         | 206/10000 [00:39<31:01,  5.26step/s, loss=0.089774, elapsed=0.7min]

Entraînement:   2%|▏         | 206/10000 [00:39<31:01,  5.26step/s, loss=0.209694, elapsed=0.7min]

Entraînement:   2%|▏         | 207/10000 [00:39<30:58,  5.27step/s, loss=0.209694, elapsed=0.7min]

Entraînement:   2%|▏         | 207/10000 [00:39<30:58,  5.27step/s, loss=0.061286, elapsed=0.7min]

Entraînement:   2%|▏         | 208/10000 [00:39<30:55,  5.28step/s, loss=0.061286, elapsed=0.7min]

Entraînement:   2%|▏         | 208/10000 [00:39<30:55,  5.28step/s, loss=0.066987, elapsed=0.7min]

Entraînement:   2%|▏         | 209/10000 [00:39<30:58,  5.27step/s, loss=0.066987, elapsed=0.7min]

Entraînement:   2%|▏         | 209/10000 [00:39<30:58,  5.27step/s, loss=0.068501, elapsed=0.7min]

Entraînement:   2%|▏         | 210/10000 [00:40<31:04,  5.25step/s, loss=0.068501, elapsed=0.7min]

Entraînement:   2%|▏         | 210/10000 [00:40<31:04,  5.25step/s, loss=0.118468, elapsed=0.7min]

Entraînement:   2%|▏         | 211/10000 [00:40<31:03,  5.25step/s, loss=0.118468, elapsed=0.7min]

Entraînement:   2%|▏         | 211/10000 [00:40<31:03,  5.25step/s, loss=0.126269, elapsed=0.7min]

Entraînement:   2%|▏         | 212/10000 [00:40<31:03,  5.25step/s, loss=0.126269, elapsed=0.7min]

Entraînement:   2%|▏         | 212/10000 [00:40<31:03,  5.25step/s, loss=0.107738, elapsed=0.7min]

Entraînement:   2%|▏         | 213/10000 [00:40<31:01,  5.26step/s, loss=0.107738, elapsed=0.7min]

Entraînement:   2%|▏         | 213/10000 [00:40<31:01,  5.26step/s, loss=0.102978, elapsed=0.7min]

Entraînement:   2%|▏         | 214/10000 [00:40<30:58,  5.27step/s, loss=0.102978, elapsed=0.7min]

Entraînement:   2%|▏         | 214/10000 [00:40<30:58,  5.27step/s, loss=0.105463, elapsed=0.7min]

Entraînement:   2%|▏         | 215/10000 [00:41<30:55,  5.27step/s, loss=0.105463, elapsed=0.7min]

Entraînement:   2%|▏         | 215/10000 [00:41<30:55,  5.27step/s, loss=0.101174, elapsed=0.7min]

Entraînement:   2%|▏         | 216/10000 [00:41<30:52,  5.28step/s, loss=0.101174, elapsed=0.7min]

Entraînement:   2%|▏         | 216/10000 [00:41<30:52,  5.28step/s, loss=0.069771, elapsed=0.7min]

Entraînement:   2%|▏         | 217/10000 [00:41<30:51,  5.28step/s, loss=0.069771, elapsed=0.7min]

Entraînement:   2%|▏         | 217/10000 [00:41<30:51,  5.28step/s, loss=0.123549, elapsed=0.7min]

Entraînement:   2%|▏         | 218/10000 [00:41<30:50,  5.29step/s, loss=0.123549, elapsed=0.7min]

Entraînement:   2%|▏         | 218/10000 [00:41<30:50,  5.29step/s, loss=0.145500, elapsed=0.7min]

Entraînement:   2%|▏         | 219/10000 [00:41<30:54,  5.28step/s, loss=0.145500, elapsed=0.7min]

Entraînement:   2%|▏         | 219/10000 [00:41<30:54,  5.28step/s, loss=0.108631, elapsed=0.7min]

Entraînement:   2%|▏         | 220/10000 [00:42<30:56,  5.27step/s, loss=0.108631, elapsed=0.7min]

Entraînement:   2%|▏         | 220/10000 [00:42<30:56,  5.27step/s, loss=0.077629, elapsed=0.7min]

Entraînement:   2%|▏         | 221/10000 [00:42<30:50,  5.28step/s, loss=0.077629, elapsed=0.7min]

Entraînement:   2%|▏         | 221/10000 [00:42<30:50,  5.28step/s, loss=0.190467, elapsed=0.7min]

Entraînement:   2%|▏         | 222/10000 [00:42<30:54,  5.27step/s, loss=0.190467, elapsed=0.7min]

Entraînement:   2%|▏         | 222/10000 [00:42<30:54,  5.27step/s, loss=0.197220, elapsed=0.7min]

Entraînement:   2%|▏         | 223/10000 [00:42<30:52,  5.28step/s, loss=0.197220, elapsed=0.7min]

Entraînement:   2%|▏         | 223/10000 [00:42<30:52,  5.28step/s, loss=0.085346, elapsed=0.7min]

Entraînement:   2%|▏         | 224/10000 [00:42<30:54,  5.27step/s, loss=0.085346, elapsed=0.7min]

Entraînement:   2%|▏         | 224/10000 [00:42<30:54,  5.27step/s, loss=0.108879, elapsed=0.7min]

Entraînement:   2%|▏         | 225/10000 [00:43<30:53,  5.27step/s, loss=0.108879, elapsed=0.7min]

Entraînement:   2%|▏         | 225/10000 [00:43<30:53,  5.27step/s, loss=0.073296, elapsed=0.7min]

Entraînement:   2%|▏         | 226/10000 [00:43<30:57,  5.26step/s, loss=0.073296, elapsed=0.7min]

Entraînement:   2%|▏         | 226/10000 [00:43<30:57,  5.26step/s, loss=0.097343, elapsed=0.7min]

Entraînement:   2%|▏         | 227/10000 [00:43<30:58,  5.26step/s, loss=0.097343, elapsed=0.7min]

Entraînement:   2%|▏         | 227/10000 [00:43<30:58,  5.26step/s, loss=0.162189, elapsed=0.7min]

Entraînement:   2%|▏         | 228/10000 [00:43<30:59,  5.26step/s, loss=0.162189, elapsed=0.7min]

Entraînement:   2%|▏         | 228/10000 [00:43<30:59,  5.26step/s, loss=0.165109, elapsed=0.7min]

Entraînement:   2%|▏         | 229/10000 [00:43<30:57,  5.26step/s, loss=0.165109, elapsed=0.7min]

Entraînement:   2%|▏         | 229/10000 [00:43<30:57,  5.26step/s, loss=0.078527, elapsed=0.7min]

Entraînement:   2%|▏         | 230/10000 [00:43<30:55,  5.26step/s, loss=0.078527, elapsed=0.7min]

Entraînement:   2%|▏         | 230/10000 [00:43<30:55,  5.26step/s, loss=0.065861, elapsed=0.7min]

Entraînement:   2%|▏         | 231/10000 [00:44<30:54,  5.27step/s, loss=0.065861, elapsed=0.7min]

Entraînement:   2%|▏         | 231/10000 [00:44<30:54,  5.27step/s, loss=0.060814, elapsed=0.7min]

Entraînement:   2%|▏         | 232/10000 [00:44<30:52,  5.27step/s, loss=0.060814, elapsed=0.7min]

Entraînement:   2%|▏         | 232/10000 [00:44<30:52,  5.27step/s, loss=0.075203, elapsed=0.7min]

Entraînement:   2%|▏         | 233/10000 [00:44<30:48,  5.28step/s, loss=0.075203, elapsed=0.7min]

Entraînement:   2%|▏         | 233/10000 [00:44<30:48,  5.28step/s, loss=0.069280, elapsed=0.7min]

Entraînement:   2%|▏         | 234/10000 [00:44<30:49,  5.28step/s, loss=0.069280, elapsed=0.7min]

Entraînement:   2%|▏         | 234/10000 [00:44<30:49,  5.28step/s, loss=0.089056, elapsed=0.7min]

Entraînement:   2%|▏         | 235/10000 [00:44<30:51,  5.28step/s, loss=0.089056, elapsed=0.7min]

Entraînement:   2%|▏         | 235/10000 [00:44<30:51,  5.28step/s, loss=0.099741, elapsed=0.7min]

Entraînement:   2%|▏         | 236/10000 [00:45<30:51,  5.27step/s, loss=0.099741, elapsed=0.7min]

Entraînement:   2%|▏         | 236/10000 [00:45<30:51,  5.27step/s, loss=0.093887, elapsed=0.8min]

Entraînement:   2%|▏         | 237/10000 [00:45<30:51,  5.27step/s, loss=0.093887, elapsed=0.8min]

Entraînement:   2%|▏         | 237/10000 [00:45<30:51,  5.27step/s, loss=0.078703, elapsed=0.8min]

Entraînement:   2%|▏         | 238/10000 [00:45<30:47,  5.29step/s, loss=0.078703, elapsed=0.8min]

Entraînement:   2%|▏         | 238/10000 [00:45<30:47,  5.29step/s, loss=0.049850, elapsed=0.8min]

Entraînement:   2%|▏         | 239/10000 [00:45<30:48,  5.28step/s, loss=0.049850, elapsed=0.8min]

Entraînement:   2%|▏         | 239/10000 [00:45<30:48,  5.28step/s, loss=0.105609, elapsed=0.8min]

Entraînement:   2%|▏         | 240/10000 [00:45<30:45,  5.29step/s, loss=0.105609, elapsed=0.8min]

Entraînement:   2%|▏         | 240/10000 [00:45<30:45,  5.29step/s, loss=0.046082, elapsed=0.8min]

Entraînement:   2%|▏         | 241/10000 [00:46<30:42,  5.30step/s, loss=0.046082, elapsed=0.8min]

Entraînement:   2%|▏         | 241/10000 [00:46<30:42,  5.30step/s, loss=0.052645, elapsed=0.8min]

Entraînement:   2%|▏         | 242/10000 [00:46<30:43,  5.29step/s, loss=0.052645, elapsed=0.8min]

Entraînement:   2%|▏         | 242/10000 [00:46<30:43,  5.29step/s, loss=0.055927, elapsed=0.8min]

Entraînement:   2%|▏         | 243/10000 [00:46<30:44,  5.29step/s, loss=0.055927, elapsed=0.8min]

Entraînement:   2%|▏         | 243/10000 [00:46<30:44,  5.29step/s, loss=0.123509, elapsed=0.8min]

Entraînement:   2%|▏         | 244/10000 [00:46<30:46,  5.28step/s, loss=0.123509, elapsed=0.8min]

Entraînement:   2%|▏         | 244/10000 [00:46<30:46,  5.28step/s, loss=0.134441, elapsed=0.8min]

Entraînement:   2%|▏         | 245/10000 [00:46<30:46,  5.28step/s, loss=0.134441, elapsed=0.8min]

Entraînement:   2%|▏         | 245/10000 [00:46<30:46,  5.28step/s, loss=0.062127, elapsed=0.8min]

Entraînement:   2%|▏         | 246/10000 [00:47<30:45,  5.28step/s, loss=0.062127, elapsed=0.8min]

Entraînement:   2%|▏         | 246/10000 [00:47<30:45,  5.28step/s, loss=0.080109, elapsed=0.8min]

Entraînement:   2%|▏         | 247/10000 [00:47<30:44,  5.29step/s, loss=0.080109, elapsed=0.8min]

Entraînement:   2%|▏         | 247/10000 [00:47<30:44,  5.29step/s, loss=0.105897, elapsed=0.8min]

Entraînement:   2%|▏         | 248/10000 [00:47<30:41,  5.30step/s, loss=0.105897, elapsed=0.8min]

Entraînement:   2%|▏         | 248/10000 [00:47<30:41,  5.30step/s, loss=0.145485, elapsed=0.8min]

Entraînement:   2%|▏         | 249/10000 [00:47<30:43,  5.29step/s, loss=0.145485, elapsed=0.8min]

Entraînement:   2%|▏         | 249/10000 [00:47<30:43,  5.29step/s, loss=0.094350, elapsed=0.8min]

Entraînement:   2%|▎         | 250/10000 [00:47<30:43,  5.29step/s, loss=0.094350, elapsed=0.8min]

Entraînement:   2%|▎         | 250/10000 [00:47<30:43,  5.29step/s, loss=0.064591, elapsed=0.8min]

Entraînement:   3%|▎         | 251/10000 [00:47<30:51,  5.27step/s, loss=0.064591, elapsed=0.8min]

Entraînement:   3%|▎         | 251/10000 [00:47<30:51,  5.27step/s, loss=0.077147, elapsed=0.8min]

Entraînement:   3%|▎         | 252/10000 [00:48<30:57,  5.25step/s, loss=0.077147, elapsed=0.8min]

Entraînement:   3%|▎         | 252/10000 [00:48<30:57,  5.25step/s, loss=0.051927, elapsed=0.8min]

Entraînement:   3%|▎         | 253/10000 [00:48<30:58,  5.25step/s, loss=0.051927, elapsed=0.8min]

Entraînement:   3%|▎         | 253/10000 [00:48<30:58,  5.25step/s, loss=0.065739, elapsed=0.8min]

Entraînement:   3%|▎         | 254/10000 [00:48<30:52,  5.26step/s, loss=0.065739, elapsed=0.8min]

Entraînement:   3%|▎         | 254/10000 [00:48<30:52,  5.26step/s, loss=0.071374, elapsed=0.8min]

Entraînement:   3%|▎         | 255/10000 [00:48<30:55,  5.25step/s, loss=0.071374, elapsed=0.8min]

Entraînement:   3%|▎         | 255/10000 [00:48<30:55,  5.25step/s, loss=0.051296, elapsed=0.8min]

Entraînement:   3%|▎         | 256/10000 [00:48<30:51,  5.26step/s, loss=0.051296, elapsed=0.8min]

Entraînement:   3%|▎         | 256/10000 [00:48<30:51,  5.26step/s, loss=0.072987, elapsed=0.8min]

Entraînement:   3%|▎         | 257/10000 [00:49<30:52,  5.26step/s, loss=0.072987, elapsed=0.8min]

Entraînement:   3%|▎         | 257/10000 [00:49<30:52,  5.26step/s, loss=0.043321, elapsed=0.8min]

Entraînement:   3%|▎         | 258/10000 [00:49<30:50,  5.26step/s, loss=0.043321, elapsed=0.8min]

Entraînement:   3%|▎         | 258/10000 [00:49<30:50,  5.26step/s, loss=0.103421, elapsed=0.8min]

Entraînement:   3%|▎         | 259/10000 [00:49<30:46,  5.28step/s, loss=0.103421, elapsed=0.8min]

Entraînement:   3%|▎         | 259/10000 [00:49<30:46,  5.28step/s, loss=0.091294, elapsed=0.8min]

Entraînement:   3%|▎         | 260/10000 [00:49<30:48,  5.27step/s, loss=0.091294, elapsed=0.8min]

Entraînement:   3%|▎         | 260/10000 [00:49<30:48,  5.27step/s, loss=0.059775, elapsed=0.8min]

Entraînement:   3%|▎         | 261/10000 [00:49<30:44,  5.28step/s, loss=0.059775, elapsed=0.8min]

Entraînement:   3%|▎         | 261/10000 [00:49<30:44,  5.28step/s, loss=0.081268, elapsed=0.8min]

Entraînement:   3%|▎         | 262/10000 [00:50<30:41,  5.29step/s, loss=0.081268, elapsed=0.8min]

Entraînement:   3%|▎         | 262/10000 [00:50<30:41,  5.29step/s, loss=0.093671, elapsed=0.8min]

Entraînement:   3%|▎         | 263/10000 [00:50<30:40,  5.29step/s, loss=0.093671, elapsed=0.8min]

Entraînement:   3%|▎         | 263/10000 [00:50<30:40,  5.29step/s, loss=0.053217, elapsed=0.8min]

Entraînement:   3%|▎         | 264/10000 [00:50<30:37,  5.30step/s, loss=0.053217, elapsed=0.8min]

Entraînement:   3%|▎         | 264/10000 [00:50<30:37,  5.30step/s, loss=0.081410, elapsed=0.8min]

Entraînement:   3%|▎         | 265/10000 [00:50<30:41,  5.29step/s, loss=0.081410, elapsed=0.8min]

Entraînement:   3%|▎         | 265/10000 [00:50<30:41,  5.29step/s, loss=0.090575, elapsed=0.8min]

Entraînement:   3%|▎         | 266/10000 [00:50<30:43,  5.28step/s, loss=0.090575, elapsed=0.8min]

Entraînement:   3%|▎         | 266/10000 [00:50<30:43,  5.28step/s, loss=0.073784, elapsed=0.8min]

Entraînement:   3%|▎         | 267/10000 [00:50<30:42,  5.28step/s, loss=0.073784, elapsed=0.8min]

Entraînement:   3%|▎         | 267/10000 [00:50<30:42,  5.28step/s, loss=0.124557, elapsed=0.8min]

Entraînement:   3%|▎         | 268/10000 [00:51<30:42,  5.28step/s, loss=0.124557, elapsed=0.8min]

Entraînement:   3%|▎         | 268/10000 [00:51<30:42,  5.28step/s, loss=0.057906, elapsed=0.9min]

Entraînement:   3%|▎         | 269/10000 [00:51<30:37,  5.30step/s, loss=0.057906, elapsed=0.9min]

Entraînement:   3%|▎         | 269/10000 [00:51<30:37,  5.30step/s, loss=0.114695, elapsed=0.9min]

Entraînement:   3%|▎         | 270/10000 [00:51<30:36,  5.30step/s, loss=0.114695, elapsed=0.9min]

Entraînement:   3%|▎         | 270/10000 [00:51<30:36,  5.30step/s, loss=0.061527, elapsed=0.9min]

Entraînement:   3%|▎         | 271/10000 [00:51<30:34,  5.30step/s, loss=0.061527, elapsed=0.9min]

Entraînement:   3%|▎         | 271/10000 [00:51<30:34,  5.30step/s, loss=0.046458, elapsed=0.9min]

Entraînement:   3%|▎         | 272/10000 [00:51<30:32,  5.31step/s, loss=0.046458, elapsed=0.9min]

Entraînement:   3%|▎         | 272/10000 [00:51<30:32,  5.31step/s, loss=0.089023, elapsed=0.9min]

Entraînement:   3%|▎         | 273/10000 [00:52<30:32,  5.31step/s, loss=0.089023, elapsed=0.9min]

Entraînement:   3%|▎         | 273/10000 [00:52<30:32,  5.31step/s, loss=0.095754, elapsed=0.9min]

Entraînement:   3%|▎         | 274/10000 [00:52<30:33,  5.30step/s, loss=0.095754, elapsed=0.9min]

Entraînement:   3%|▎         | 274/10000 [00:52<30:33,  5.30step/s, loss=0.075188, elapsed=0.9min]

Entraînement:   3%|▎         | 275/10000 [00:52<30:36,  5.30step/s, loss=0.075188, elapsed=0.9min]

Entraînement:   3%|▎         | 275/10000 [00:52<30:36,  5.30step/s, loss=0.117489, elapsed=0.9min]

Entraînement:   3%|▎         | 276/10000 [00:52<30:38,  5.29step/s, loss=0.117489, elapsed=0.9min]

Entraînement:   3%|▎         | 276/10000 [00:52<30:38,  5.29step/s, loss=0.100694, elapsed=0.9min]

Entraînement:   3%|▎         | 277/10000 [00:52<30:43,  5.28step/s, loss=0.100694, elapsed=0.9min]

Entraînement:   3%|▎         | 277/10000 [00:52<30:43,  5.28step/s, loss=0.103607, elapsed=0.9min]

Entraînement:   3%|▎         | 278/10000 [00:53<30:41,  5.28step/s, loss=0.103607, elapsed=0.9min]

Entraînement:   3%|▎         | 278/10000 [00:53<30:41,  5.28step/s, loss=0.037583, elapsed=0.9min]

Entraînement:   3%|▎         | 279/10000 [00:53<30:40,  5.28step/s, loss=0.037583, elapsed=0.9min]

Entraînement:   3%|▎         | 279/10000 [00:53<30:40,  5.28step/s, loss=0.065297, elapsed=0.9min]

Entraînement:   3%|▎         | 280/10000 [00:53<30:43,  5.27step/s, loss=0.065297, elapsed=0.9min]

Entraînement:   3%|▎         | 280/10000 [00:53<30:43,  5.27step/s, loss=0.104700, elapsed=0.9min]

Entraînement:   3%|▎         | 281/10000 [00:53<30:41,  5.28step/s, loss=0.104700, elapsed=0.9min]

Entraînement:   3%|▎         | 281/10000 [00:53<30:41,  5.28step/s, loss=0.074952, elapsed=0.9min]

Entraînement:   3%|▎         | 282/10000 [00:53<30:38,  5.29step/s, loss=0.074952, elapsed=0.9min]

Entraînement:   3%|▎         | 282/10000 [00:53<30:38,  5.29step/s, loss=0.082055, elapsed=0.9min]

Entraînement:   3%|▎         | 283/10000 [00:54<30:44,  5.27step/s, loss=0.082055, elapsed=0.9min]

Entraînement:   3%|▎         | 283/10000 [00:54<30:44,  5.27step/s, loss=0.106707, elapsed=0.9min]

Entraînement:   3%|▎         | 284/10000 [00:54<30:43,  5.27step/s, loss=0.106707, elapsed=0.9min]

Entraînement:   3%|▎         | 284/10000 [00:54<30:43,  5.27step/s, loss=0.080541, elapsed=0.9min]

Entraînement:   3%|▎         | 285/10000 [00:54<30:46,  5.26step/s, loss=0.080541, elapsed=0.9min]

Entraînement:   3%|▎         | 285/10000 [00:54<30:46,  5.26step/s, loss=0.069905, elapsed=0.9min]

Entraînement:   3%|▎         | 286/10000 [00:54<30:43,  5.27step/s, loss=0.069905, elapsed=0.9min]

Entraînement:   3%|▎         | 286/10000 [00:54<30:43,  5.27step/s, loss=0.101952, elapsed=0.9min]

Entraînement:   3%|▎         | 287/10000 [00:54<30:38,  5.28step/s, loss=0.101952, elapsed=0.9min]

Entraînement:   3%|▎         | 287/10000 [00:54<30:38,  5.28step/s, loss=0.178939, elapsed=0.9min]

Entraînement:   3%|▎         | 288/10000 [00:54<30:38,  5.28step/s, loss=0.178939, elapsed=0.9min]

Entraînement:   3%|▎         | 288/10000 [00:54<30:38,  5.28step/s, loss=0.067692, elapsed=0.9min]

Entraînement:   3%|▎         | 289/10000 [00:55<30:35,  5.29step/s, loss=0.067692, elapsed=0.9min]

Entraînement:   3%|▎         | 289/10000 [00:55<30:35,  5.29step/s, loss=0.194958, elapsed=0.9min]

Entraînement:   3%|▎         | 290/10000 [00:55<30:40,  5.28step/s, loss=0.194958, elapsed=0.9min]

Entraînement:   3%|▎         | 290/10000 [00:55<30:40,  5.28step/s, loss=0.082554, elapsed=0.9min]

Entraînement:   3%|▎         | 291/10000 [00:55<30:40,  5.27step/s, loss=0.082554, elapsed=0.9min]

Entraînement:   3%|▎         | 291/10000 [00:55<30:40,  5.27step/s, loss=0.153492, elapsed=0.9min]

Entraînement:   3%|▎         | 292/10000 [00:55<30:43,  5.27step/s, loss=0.153492, elapsed=0.9min]

Entraînement:   3%|▎         | 292/10000 [00:55<30:43,  5.27step/s, loss=0.094141, elapsed=0.9min]

Entraînement:   3%|▎         | 293/10000 [00:55<30:39,  5.28step/s, loss=0.094141, elapsed=0.9min]

Entraînement:   3%|▎         | 293/10000 [00:55<30:39,  5.28step/s, loss=0.084686, elapsed=0.9min]

Entraînement:   3%|▎         | 294/10000 [00:56<30:44,  5.26step/s, loss=0.084686, elapsed=0.9min]

Entraînement:   3%|▎         | 294/10000 [00:56<30:44,  5.26step/s, loss=0.075516, elapsed=0.9min]

Entraînement:   3%|▎         | 295/10000 [00:56<30:39,  5.28step/s, loss=0.075516, elapsed=0.9min]

Entraînement:   3%|▎         | 295/10000 [00:56<30:39,  5.28step/s, loss=0.070014, elapsed=0.9min]

Entraînement:   3%|▎         | 296/10000 [00:56<30:34,  5.29step/s, loss=0.070014, elapsed=0.9min]

Entraînement:   3%|▎         | 296/10000 [00:56<30:34,  5.29step/s, loss=0.063830, elapsed=0.9min]

Entraînement:   3%|▎         | 297/10000 [00:56<30:40,  5.27step/s, loss=0.063830, elapsed=0.9min]

Entraînement:   3%|▎         | 297/10000 [00:56<30:40,  5.27step/s, loss=0.090293, elapsed=0.9min]

Entraînement:   3%|▎         | 298/10000 [00:56<30:40,  5.27step/s, loss=0.090293, elapsed=0.9min]

Entraînement:   3%|▎         | 298/10000 [00:56<30:40,  5.27step/s, loss=0.199456, elapsed=0.9min]

Entraînement:   3%|▎         | 299/10000 [00:57<30:39,  5.27step/s, loss=0.199456, elapsed=0.9min]

Entraînement:   3%|▎         | 299/10000 [00:57<30:39,  5.27step/s, loss=0.054099, elapsed=1.0min]

Entraînement:   3%|▎         | 300/10000 [00:57<30:34,  5.29step/s, loss=0.054099, elapsed=1.0min]

Entraînement:   3%|▎         | 300/10000 [00:57<30:34,  5.29step/s, loss=0.061132, elapsed=1.0min]

Entraînement:   3%|▎         | 300/10000 [00:57<30:34,  5.29step/s, loss=0.061132, elapsed=1.0min]

Entraînement:   3%|▎         | 301/10000 [00:57<30:51,  5.24step/s, loss=0.061132, elapsed=1.0min]

Entraînement:   3%|▎         | 301/10000 [00:57<30:51,  5.24step/s, loss=0.051867, elapsed=1.0min]

Step 300/10000 | Train loss: 0.061132 | Elapsed: 1.0min | ETA: 30.8min

Entraînement:   3%|▎         | 302/10000 [00:57<30:44,  5.26step/s, loss=0.051867, elapsed=1.0min]

Entraînement:   3%|▎         | 302/10000 [00:57<30:44,  5.26step/s, loss=0.086455, elapsed=1.0min]

Entraînement:   3%|▎         | 303/10000 [00:57<30:37,  5.28step/s, loss=0.086455, elapsed=1.0min]

Entraînement:   3%|▎         | 303/10000 [00:57<30:37,  5.28step/s, loss=0.101814, elapsed=1.0min]

Entraînement:   3%|▎         | 304/10000 [00:57<30:38,  5.27step/s, loss=0.101814, elapsed=1.0min]

Entraînement:   3%|▎         | 304/10000 [00:58<30:38,  5.27step/s, loss=0.056259, elapsed=1.0min]

Entraînement:   3%|▎         | 305/10000 [00:58<30:42,  5.26step/s, loss=0.056259, elapsed=1.0min]

Entraînement:   3%|▎         | 305/10000 [00:58<30:42,  5.26step/s, loss=0.071312, elapsed=1.0min]

Entraînement:   3%|▎         | 306/10000 [00:58<30:38,  5.27step/s, loss=0.071312, elapsed=1.0min]

Entraînement:   3%|▎         | 306/10000 [00:58<30:38,  5.27step/s, loss=0.112253, elapsed=1.0min]

Entraînement:   3%|▎         | 307/10000 [00:58<30:37,  5.27step/s, loss=0.112253, elapsed=1.0min]

Entraînement:   3%|▎         | 307/10000 [00:58<30:37,  5.27step/s, loss=0.226830, elapsed=1.0min]

Entraînement:   3%|▎         | 308/10000 [00:58<30:35,  5.28step/s, loss=0.226830, elapsed=1.0min]

Entraînement:   3%|▎         | 308/10000 [00:58<30:35,  5.28step/s, loss=0.068638, elapsed=1.0min]

Entraînement:   3%|▎         | 309/10000 [00:58<30:36,  5.28step/s, loss=0.068638, elapsed=1.0min]

Entraînement:   3%|▎         | 309/10000 [00:58<30:36,  5.28step/s, loss=0.075990, elapsed=1.0min]

Entraînement:   3%|▎         | 310/10000 [00:59<30:37,  5.27step/s, loss=0.075990, elapsed=1.0min]

Entraînement:   3%|▎         | 310/10000 [00:59<30:37,  5.27step/s, loss=0.138181, elapsed=1.0min]

Entraînement:   3%|▎         | 311/10000 [00:59<30:32,  5.29step/s, loss=0.138181, elapsed=1.0min]

Entraînement:   3%|▎         | 311/10000 [00:59<30:32,  5.29step/s, loss=0.135146, elapsed=1.0min]

Entraînement:   3%|▎         | 312/10000 [00:59<30:31,  5.29step/s, loss=0.135146, elapsed=1.0min]

Entraînement:   3%|▎         | 312/10000 [00:59<30:31,  5.29step/s, loss=0.065316, elapsed=1.0min]

Entraînement:   3%|▎         | 313/10000 [00:59<30:29,  5.29step/s, loss=0.065316, elapsed=1.0min]

Entraînement:   3%|▎         | 313/10000 [00:59<30:29,  5.29step/s, loss=0.075634, elapsed=1.0min]

Entraînement:   3%|▎         | 314/10000 [00:59<30:34,  5.28step/s, loss=0.075634, elapsed=1.0min]

Entraînement:   3%|▎         | 314/10000 [00:59<30:34,  5.28step/s, loss=0.054831, elapsed=1.0min]

Entraînement:   3%|▎         | 315/10000 [01:00<30:32,  5.29step/s, loss=0.054831, elapsed=1.0min]

Entraînement:   3%|▎         | 315/10000 [01:00<30:32,  5.29step/s, loss=0.056371, elapsed=1.0min]

Entraînement:   3%|▎         | 316/10000 [01:00<30:31,  5.29step/s, loss=0.056371, elapsed=1.0min]

Entraînement:   3%|▎         | 316/10000 [01:00<30:31,  5.29step/s, loss=0.119965, elapsed=1.0min]

Entraînement:   3%|▎         | 317/10000 [01:00<30:32,  5.29step/s, loss=0.119965, elapsed=1.0min]

Entraînement:   3%|▎         | 317/10000 [01:00<30:32,  5.29step/s, loss=0.193424, elapsed=1.0min]

Entraînement:   3%|▎         | 318/10000 [01:00<30:30,  5.29step/s, loss=0.193424, elapsed=1.0min]

Entraînement:   3%|▎         | 318/10000 [01:00<30:30,  5.29step/s, loss=0.082251, elapsed=1.0min]

Entraînement:   3%|▎         | 319/10000 [01:00<30:31,  5.29step/s, loss=0.082251, elapsed=1.0min]

Entraînement:   3%|▎         | 319/10000 [01:00<30:31,  5.29step/s, loss=0.064554, elapsed=1.0min]

Entraînement:   3%|▎         | 320/10000 [01:01<30:29,  5.29step/s, loss=0.064554, elapsed=1.0min]

Entraînement:   3%|▎         | 320/10000 [01:01<30:29,  5.29step/s, loss=0.118031, elapsed=1.0min]

Entraînement:   3%|▎         | 321/10000 [01:01<30:31,  5.29step/s, loss=0.118031, elapsed=1.0min]

Entraînement:   3%|▎         | 321/10000 [01:01<30:31,  5.29step/s, loss=0.054796, elapsed=1.0min]

Entraînement:   3%|▎         | 322/10000 [01:01<30:31,  5.29step/s, loss=0.054796, elapsed=1.0min]

Entraînement:   3%|▎         | 322/10000 [01:01<30:31,  5.29step/s, loss=0.093333, elapsed=1.0min]

Entraînement:   3%|▎         | 323/10000 [01:01<30:28,  5.29step/s, loss=0.093333, elapsed=1.0min]

Entraînement:   3%|▎         | 323/10000 [01:01<30:28,  5.29step/s, loss=0.155234, elapsed=1.0min]

Entraînement:   3%|▎         | 324/10000 [01:01<30:28,  5.29step/s, loss=0.155234, elapsed=1.0min]

Entraînement:   3%|▎         | 324/10000 [01:01<30:28,  5.29step/s, loss=0.050622, elapsed=1.0min]

Entraînement:   3%|▎         | 325/10000 [01:01<30:27,  5.30step/s, loss=0.050622, elapsed=1.0min]

Entraînement:   3%|▎         | 325/10000 [01:01<30:27,  5.30step/s, loss=0.117597, elapsed=1.0min]

Entraînement:   3%|▎         | 326/10000 [01:02<30:25,  5.30step/s, loss=0.117597, elapsed=1.0min]

Entraînement:   3%|▎         | 326/10000 [01:02<30:25,  5.30step/s, loss=0.073925, elapsed=1.0min]

Entraînement:   3%|▎         | 327/10000 [01:02<30:26,  5.30step/s, loss=0.073925, elapsed=1.0min]

Entraînement:   3%|▎         | 327/10000 [01:02<30:26,  5.30step/s, loss=0.068481, elapsed=1.0min]

Entraînement:   3%|▎         | 328/10000 [01:02<30:24,  5.30step/s, loss=0.068481, elapsed=1.0min]

Entraînement:   3%|▎         | 328/10000 [01:02<30:24,  5.30step/s, loss=0.220613, elapsed=1.0min]

Entraînement:   3%|▎         | 329/10000 [01:02<30:22,  5.31step/s, loss=0.220613, elapsed=1.0min]

Entraînement:   3%|▎         | 329/10000 [01:02<30:22,  5.31step/s, loss=0.057799, elapsed=1.0min]

Entraînement:   3%|▎         | 330/10000 [01:02<30:26,  5.29step/s, loss=0.057799, elapsed=1.0min]

Entraînement:   3%|▎         | 330/10000 [01:02<30:26,  5.29step/s, loss=0.075562, elapsed=1.0min]

Entraînement:   3%|▎         | 331/10000 [01:03<30:25,  5.30step/s, loss=0.075562, elapsed=1.0min]

Entraînement:   3%|▎         | 331/10000 [01:03<30:25,  5.30step/s, loss=0.044781, elapsed=1.1min]

Entraînement:   3%|▎         | 332/10000 [01:03<30:26,  5.29step/s, loss=0.044781, elapsed=1.1min]

Entraînement:   3%|▎         | 332/10000 [01:03<30:26,  5.29step/s, loss=0.145733, elapsed=1.1min]

Entraînement:   3%|▎         | 333/10000 [01:03<30:32,  5.28step/s, loss=0.145733, elapsed=1.1min]

Entraînement:   3%|▎         | 333/10000 [01:03<30:32,  5.28step/s, loss=0.086211, elapsed=1.1min]

Entraînement:   3%|▎         | 334/10000 [01:03<30:28,  5.29step/s, loss=0.086211, elapsed=1.1min]

Entraînement:   3%|▎         | 334/10000 [01:03<30:28,  5.29step/s, loss=0.071339, elapsed=1.1min]

Entraînement:   3%|▎         | 335/10000 [01:03<30:27,  5.29step/s, loss=0.071339, elapsed=1.1min]

Entraînement:   3%|▎         | 335/10000 [01:03<30:27,  5.29step/s, loss=0.058812, elapsed=1.1min]

Entraînement:   3%|▎         | 336/10000 [01:04<30:25,  5.29step/s, loss=0.058812, elapsed=1.1min]

Entraînement:   3%|▎         | 336/10000 [01:04<30:25,  5.29step/s, loss=0.066255, elapsed=1.1min]

Entraînement:   3%|▎         | 337/10000 [01:04<30:23,  5.30step/s, loss=0.066255, elapsed=1.1min]

Entraînement:   3%|▎         | 337/10000 [01:04<30:23,  5.30step/s, loss=0.072294, elapsed=1.1min]

Entraînement:   3%|▎         | 338/10000 [01:04<30:25,  5.29step/s, loss=0.072294, elapsed=1.1min]

Entraînement:   3%|▎         | 338/10000 [01:04<30:25,  5.29step/s, loss=0.091313, elapsed=1.1min]

Entraînement:   3%|▎         | 339/10000 [01:04<30:24,  5.30step/s, loss=0.091313, elapsed=1.1min]

Entraînement:   3%|▎         | 339/10000 [01:04<30:24,  5.30step/s, loss=0.061172, elapsed=1.1min]

Entraînement:   3%|▎         | 340/10000 [01:04<30:26,  5.29step/s, loss=0.061172, elapsed=1.1min]

Entraînement:   3%|▎         | 340/10000 [01:04<30:26,  5.29step/s, loss=0.058951, elapsed=1.1min]

Entraînement:   3%|▎         | 341/10000 [01:04<30:32,  5.27step/s, loss=0.058951, elapsed=1.1min]

Entraînement:   3%|▎         | 341/10000 [01:04<30:32,  5.27step/s, loss=0.107287, elapsed=1.1min]

Entraînement:   3%|▎         | 342/10000 [01:05<30:29,  5.28step/s, loss=0.107287, elapsed=1.1min]

Entraînement:   3%|▎         | 342/10000 [01:05<30:29,  5.28step/s, loss=0.068746, elapsed=1.1min]

Entraînement:   3%|▎         | 343/10000 [01:05<30:27,  5.28step/s, loss=0.068746, elapsed=1.1min]

Entraînement:   3%|▎         | 343/10000 [01:05<30:27,  5.28step/s, loss=0.111848, elapsed=1.1min]

Entraînement:   3%|▎         | 344/10000 [01:05<30:23,  5.30step/s, loss=0.111848, elapsed=1.1min]

Entraînement:   3%|▎         | 344/10000 [01:05<30:23,  5.30step/s, loss=0.080529, elapsed=1.1min]

Entraînement:   3%|▎         | 345/10000 [01:05<30:24,  5.29step/s, loss=0.080529, elapsed=1.1min]

Entraînement:   3%|▎         | 345/10000 [01:05<30:24,  5.29step/s, loss=0.089560, elapsed=1.1min]

Entraînement:   3%|▎         | 346/10000 [01:05<30:26,  5.29step/s, loss=0.089560, elapsed=1.1min]

Entraînement:   3%|▎         | 346/10000 [01:05<30:26,  5.29step/s, loss=0.193808, elapsed=1.1min]

Entraînement:   3%|▎         | 347/10000 [01:06<30:26,  5.29step/s, loss=0.193808, elapsed=1.1min]

Entraînement:   3%|▎         | 347/10000 [01:06<30:26,  5.29step/s, loss=0.043757, elapsed=1.1min]

Entraînement:   3%|▎         | 348/10000 [01:06<30:25,  5.29step/s, loss=0.043757, elapsed=1.1min]

Entraînement:   3%|▎         | 348/10000 [01:06<30:25,  5.29step/s, loss=0.083296, elapsed=1.1min]

Entraînement:   3%|▎         | 349/10000 [01:06<30:23,  5.29step/s, loss=0.083296, elapsed=1.1min]

Entraînement:   3%|▎         | 349/10000 [01:06<30:23,  5.29step/s, loss=0.115896, elapsed=1.1min]

Entraînement:   4%|▎         | 350/10000 [01:06<30:24,  5.29step/s, loss=0.115896, elapsed=1.1min]

Entraînement:   4%|▎         | 350/10000 [01:06<30:24,  5.29step/s, loss=0.070919, elapsed=1.1min]

Entraînement:   4%|▎         | 351/10000 [01:06<30:21,  5.30step/s, loss=0.070919, elapsed=1.1min]

Entraînement:   4%|▎         | 351/10000 [01:06<30:21,  5.30step/s, loss=0.129099, elapsed=1.1min]

Entraînement:   4%|▎         | 352/10000 [01:07<30:18,  5.31step/s, loss=0.129099, elapsed=1.1min]

Entraînement:   4%|▎         | 352/10000 [01:07<30:18,  5.31step/s, loss=0.061177, elapsed=1.1min]

Entraînement:   4%|▎         | 353/10000 [01:07<30:23,  5.29step/s, loss=0.061177, elapsed=1.1min]

Entraînement:   4%|▎         | 353/10000 [01:07<30:23,  5.29step/s, loss=0.110878, elapsed=1.1min]

Entraînement:   4%|▎         | 354/10000 [01:07<30:25,  5.28step/s, loss=0.110878, elapsed=1.1min]

Entraînement:   4%|▎         | 354/10000 [01:07<30:25,  5.28step/s, loss=0.162344, elapsed=1.1min]

Entraînement:   4%|▎         | 355/10000 [01:07<30:24,  5.29step/s, loss=0.162344, elapsed=1.1min]

Entraînement:   4%|▎         | 355/10000 [01:07<30:24,  5.29step/s, loss=0.058164, elapsed=1.1min]

Entraînement:   4%|▎         | 356/10000 [01:07<30:26,  5.28step/s, loss=0.058164, elapsed=1.1min]

Entraînement:   4%|▎         | 356/10000 [01:07<30:26,  5.28step/s, loss=0.249693, elapsed=1.1min]

Entraînement:   4%|▎         | 357/10000 [01:08<30:23,  5.29step/s, loss=0.249693, elapsed=1.1min]

Entraînement:   4%|▎         | 357/10000 [01:08<30:23,  5.29step/s, loss=0.155715, elapsed=1.1min]

Entraînement:   4%|▎         | 358/10000 [01:08<30:25,  5.28step/s, loss=0.155715, elapsed=1.1min]

Entraînement:   4%|▎         | 358/10000 [01:08<30:25,  5.28step/s, loss=0.059436, elapsed=1.1min]

Entraînement:   4%|▎         | 359/10000 [01:08<30:25,  5.28step/s, loss=0.059436, elapsed=1.1min]

Entraînement:   4%|▎         | 359/10000 [01:08<30:25,  5.28step/s, loss=0.049756, elapsed=1.1min]

Entraînement:   4%|▎         | 360/10000 [01:08<30:29,  5.27step/s, loss=0.049756, elapsed=1.1min]

Entraînement:   4%|▎         | 360/10000 [01:08<30:29,  5.27step/s, loss=0.061733, elapsed=1.1min]

Entraînement:   4%|▎         | 361/10000 [01:08<30:33,  5.26step/s, loss=0.061733, elapsed=1.1min]

Entraînement:   4%|▎         | 361/10000 [01:08<30:33,  5.26step/s, loss=0.061072, elapsed=1.1min]

Entraînement:   4%|▎         | 362/10000 [01:08<30:34,  5.25step/s, loss=0.061072, elapsed=1.1min]

Entraînement:   4%|▎         | 362/10000 [01:08<30:34,  5.25step/s, loss=0.130198, elapsed=1.1min]

Entraînement:   4%|▎         | 363/10000 [01:09<30:30,  5.27step/s, loss=0.130198, elapsed=1.1min]

Entraînement:   4%|▎         | 363/10000 [01:09<30:30,  5.27step/s, loss=0.068050, elapsed=1.2min]

Entraînement:   4%|▎         | 364/10000 [01:09<30:31,  5.26step/s, loss=0.068050, elapsed=1.2min]

Entraînement:   4%|▎         | 364/10000 [01:09<30:31,  5.26step/s, loss=0.126340, elapsed=1.2min]

Entraînement:   4%|▎         | 365/10000 [01:09<30:30,  5.26step/s, loss=0.126340, elapsed=1.2min]

Entraînement:   4%|▎         | 365/10000 [01:09<30:30,  5.26step/s, loss=0.066752, elapsed=1.2min]

Entraînement:   4%|▎         | 366/10000 [01:09<30:28,  5.27step/s, loss=0.066752, elapsed=1.2min]

Entraînement:   4%|▎         | 366/10000 [01:09<30:28,  5.27step/s, loss=0.159753, elapsed=1.2min]

Entraînement:   4%|▎         | 367/10000 [01:09<30:28,  5.27step/s, loss=0.159753, elapsed=1.2min]

Entraînement:   4%|▎         | 367/10000 [01:09<30:28,  5.27step/s, loss=0.072919, elapsed=1.2min]

Entraînement:   4%|▎         | 368/10000 [01:10<30:39,  5.24step/s, loss=0.072919, elapsed=1.2min]

Entraînement:   4%|▎         | 368/10000 [01:10<30:39,  5.24step/s, loss=0.061686, elapsed=1.2min]

Entraînement:   4%|▎         | 369/10000 [01:10<30:37,  5.24step/s, loss=0.061686, elapsed=1.2min]

Entraînement:   4%|▎         | 369/10000 [01:10<30:37,  5.24step/s, loss=0.052158, elapsed=1.2min]

Entraînement:   4%|▎         | 370/10000 [01:10<30:36,  5.24step/s, loss=0.052158, elapsed=1.2min]

Entraînement:   4%|▎         | 370/10000 [01:10<30:36,  5.24step/s, loss=0.088744, elapsed=1.2min]

Entraînement:   4%|▎         | 371/10000 [01:10<30:33,  5.25step/s, loss=0.088744, elapsed=1.2min]

Entraînement:   4%|▎         | 371/10000 [01:10<30:33,  5.25step/s, loss=0.199403, elapsed=1.2min]

Entraînement:   4%|▎         | 372/10000 [01:10<30:29,  5.26step/s, loss=0.199403, elapsed=1.2min]

Entraînement:   4%|▎         | 372/10000 [01:10<30:29,  5.26step/s, loss=0.063358, elapsed=1.2min]

Entraînement:   4%|▎         | 373/10000 [01:11<30:28,  5.27step/s, loss=0.063358, elapsed=1.2min]

Entraînement:   4%|▎         | 373/10000 [01:11<30:28,  5.27step/s, loss=0.043858, elapsed=1.2min]

Entraînement:   4%|▎         | 374/10000 [01:11<30:24,  5.28step/s, loss=0.043858, elapsed=1.2min]

Entraînement:   4%|▎         | 374/10000 [01:11<30:24,  5.28step/s, loss=0.068703, elapsed=1.2min]

Entraînement:   4%|▍         | 375/10000 [01:11<30:20,  5.29step/s, loss=0.068703, elapsed=1.2min]

Entraînement:   4%|▍         | 375/10000 [01:11<30:20,  5.29step/s, loss=0.091988, elapsed=1.2min]

Entraînement:   4%|▍         | 376/10000 [01:11<30:19,  5.29step/s, loss=0.091988, elapsed=1.2min]

Entraînement:   4%|▍         | 376/10000 [01:11<30:19,  5.29step/s, loss=0.301506, elapsed=1.2min]

Entraînement:   4%|▍         | 377/10000 [01:11<30:25,  5.27step/s, loss=0.301506, elapsed=1.2min]

Entraînement:   4%|▍         | 377/10000 [01:11<30:25,  5.27step/s, loss=0.140465, elapsed=1.2min]

Entraînement:   4%|▍         | 378/10000 [01:12<30:23,  5.28step/s, loss=0.140465, elapsed=1.2min]

Entraînement:   4%|▍         | 378/10000 [01:12<30:23,  5.28step/s, loss=0.066030, elapsed=1.2min]

Entraînement:   4%|▍         | 379/10000 [01:12<30:21,  5.28step/s, loss=0.066030, elapsed=1.2min]

Entraînement:   4%|▍         | 379/10000 [01:12<30:21,  5.28step/s, loss=0.141885, elapsed=1.2min]

Entraînement:   4%|▍         | 380/10000 [01:12<30:17,  5.29step/s, loss=0.141885, elapsed=1.2min]

Entraînement:   4%|▍         | 380/10000 [01:12<30:17,  5.29step/s, loss=0.106937, elapsed=1.2min]

Entraînement:   4%|▍         | 381/10000 [01:12<30:18,  5.29step/s, loss=0.106937, elapsed=1.2min]

Entraînement:   4%|▍         | 381/10000 [01:12<30:18,  5.29step/s, loss=0.085549, elapsed=1.2min]

Entraînement:   4%|▍         | 382/10000 [01:12<30:17,  5.29step/s, loss=0.085549, elapsed=1.2min]

Entraînement:   4%|▍         | 382/10000 [01:12<30:17,  5.29step/s, loss=0.123570, elapsed=1.2min]

Entraînement:   4%|▍         | 383/10000 [01:12<30:13,  5.30step/s, loss=0.123570, elapsed=1.2min]

Entraînement:   4%|▍         | 383/10000 [01:12<30:13,  5.30step/s, loss=0.095777, elapsed=1.2min]

Entraînement:   4%|▍         | 384/10000 [01:13<30:16,  5.29step/s, loss=0.095777, elapsed=1.2min]

Entraînement:   4%|▍         | 384/10000 [01:13<30:16,  5.29step/s, loss=0.047857, elapsed=1.2min]

Entraînement:   4%|▍         | 385/10000 [01:13<30:19,  5.29step/s, loss=0.047857, elapsed=1.2min]

Entraînement:   4%|▍         | 385/10000 [01:13<30:19,  5.29step/s, loss=0.040190, elapsed=1.2min]

Entraînement:   4%|▍         | 386/10000 [01:13<30:19,  5.28step/s, loss=0.040190, elapsed=1.2min]

Entraînement:   4%|▍         | 386/10000 [01:13<30:19,  5.28step/s, loss=0.062174, elapsed=1.2min]

Entraînement:   4%|▍         | 387/10000 [01:13<30:21,  5.28step/s, loss=0.062174, elapsed=1.2min]

Entraînement:   4%|▍         | 387/10000 [01:13<30:21,  5.28step/s, loss=0.094549, elapsed=1.2min]

Entraînement:   4%|▍         | 388/10000 [01:13<30:10,  5.31step/s, loss=0.094549, elapsed=1.2min]

Entraînement:   4%|▍         | 388/10000 [01:13<30:10,  5.31step/s, loss=0.074012, elapsed=1.2min]

Entraînement:   4%|▍         | 389/10000 [01:14<30:05,  5.32step/s, loss=0.074012, elapsed=1.2min]

Entraînement:   4%|▍         | 389/10000 [01:14<30:05,  5.32step/s, loss=0.111709, elapsed=1.2min]

Entraînement:   4%|▍         | 390/10000 [01:14<30:07,  5.32step/s, loss=0.111709, elapsed=1.2min]

Entraînement:   4%|▍         | 390/10000 [01:14<30:07,  5.32step/s, loss=0.157818, elapsed=1.2min]

Entraînement:   4%|▍         | 391/10000 [01:14<30:08,  5.31step/s, loss=0.157818, elapsed=1.2min]

Entraînement:   4%|▍         | 391/10000 [01:14<30:08,  5.31step/s, loss=0.142996, elapsed=1.2min]

Entraînement:   4%|▍         | 392/10000 [01:14<30:12,  5.30step/s, loss=0.142996, elapsed=1.2min]

Entraînement:   4%|▍         | 392/10000 [01:14<30:12,  5.30step/s, loss=0.160311, elapsed=1.2min]

Entraînement:   4%|▍         | 393/10000 [01:14<30:15,  5.29step/s, loss=0.160311, elapsed=1.2min]

Entraînement:   4%|▍         | 393/10000 [01:14<30:15,  5.29step/s, loss=0.091771, elapsed=1.2min]

Entraînement:   4%|▍         | 394/10000 [01:15<30:16,  5.29step/s, loss=0.091771, elapsed=1.2min]

Entraînement:   4%|▍         | 394/10000 [01:15<30:16,  5.29step/s, loss=0.120171, elapsed=1.3min]

Entraînement:   4%|▍         | 395/10000 [01:15<30:14,  5.29step/s, loss=0.120171, elapsed=1.3min]

Entraînement:   4%|▍         | 395/10000 [01:15<30:14,  5.29step/s, loss=0.089826, elapsed=1.3min]

Entraînement:   4%|▍         | 396/10000 [01:15<30:09,  5.31step/s, loss=0.089826, elapsed=1.3min]

Entraînement:   4%|▍         | 396/10000 [01:15<30:09,  5.31step/s, loss=0.098884, elapsed=1.3min]

Entraînement:   4%|▍         | 397/10000 [01:15<30:09,  5.31step/s, loss=0.098884, elapsed=1.3min]

Entraînement:   4%|▍         | 397/10000 [01:15<30:09,  5.31step/s, loss=0.089946, elapsed=1.3min]

Entraînement:   4%|▍         | 398/10000 [01:15<30:09,  5.31step/s, loss=0.089946, elapsed=1.3min]

Entraînement:   4%|▍         | 398/10000 [01:15<30:09,  5.31step/s, loss=0.089340, elapsed=1.3min]

Entraînement:   4%|▍         | 399/10000 [01:15<30:12,  5.30step/s, loss=0.089340, elapsed=1.3min]

Entraînement:   4%|▍         | 399/10000 [01:15<30:12,  5.30step/s, loss=0.057953, elapsed=1.3min]

Entraînement:   4%|▍         | 400/10000 [01:16<30:13,  5.29step/s, loss=0.057953, elapsed=1.3min]

Entraînement:   4%|▍         | 400/10000 [01:16<30:13,  5.29step/s, loss=0.065554, elapsed=1.3min]

Entraînement:   4%|▍         | 400/10000 [01:16<30:13,  5.29step/s, loss=0.065554, elapsed=1.3min]

Entraînement:   4%|▍         | 401/10000 [01:16<30:32,  5.24step/s, loss=0.065554, elapsed=1.3min]

Entraînement:   4%|▍         | 401/10000 [01:16<30:32,  5.24step/s, loss=0.076375, elapsed=1.3min]

Step 400/10000 | Train loss: 0.065554 | Elapsed: 1.3min | ETA: 30.5min

Entraînement:   4%|▍         | 402/10000 [01:16<30:25,  5.26step/s, loss=0.076375, elapsed=1.3min]

Entraînement:   4%|▍         | 402/10000 [01:16<30:25,  5.26step/s, loss=0.088972, elapsed=1.3min]

Entraînement:   4%|▍         | 403/10000 [01:16<30:20,  5.27step/s, loss=0.088972, elapsed=1.3min]

Entraînement:   4%|▍         | 403/10000 [01:16<30:20,  5.27step/s, loss=0.058832, elapsed=1.3min]

Entraînement:   4%|▍         | 404/10000 [01:16<30:16,  5.28step/s, loss=0.058832, elapsed=1.3min]

Entraînement:   4%|▍         | 404/10000 [01:16<30:16,  5.28step/s, loss=0.089442, elapsed=1.3min]

Entraînement:   4%|▍         | 405/10000 [01:17<30:12,  5.29step/s, loss=0.089442, elapsed=1.3min]

Entraînement:   4%|▍         | 405/10000 [01:17<30:12,  5.29step/s, loss=0.041863, elapsed=1.3min]

Entraînement:   4%|▍         | 406/10000 [01:17<30:11,  5.30step/s, loss=0.041863, elapsed=1.3min]

Entraînement:   4%|▍         | 406/10000 [01:17<30:11,  5.30step/s, loss=0.074917, elapsed=1.3min]

Entraînement:   4%|▍         | 407/10000 [01:17<30:10,  5.30step/s, loss=0.074917, elapsed=1.3min]

Entraînement:   4%|▍         | 407/10000 [01:17<30:10,  5.30step/s, loss=0.081870, elapsed=1.3min]

Entraînement:   4%|▍         | 408/10000 [01:17<30:09,  5.30step/s, loss=0.081870, elapsed=1.3min]

Entraînement:   4%|▍         | 408/10000 [01:17<30:09,  5.30step/s, loss=0.151143, elapsed=1.3min]

Entraînement:   4%|▍         | 409/10000 [01:17<30:10,  5.30step/s, loss=0.151143, elapsed=1.3min]

Entraînement:   4%|▍         | 409/10000 [01:17<30:10,  5.30step/s, loss=0.071386, elapsed=1.3min]

Entraînement:   4%|▍         | 410/10000 [01:18<30:10,  5.30step/s, loss=0.071386, elapsed=1.3min]

Entraînement:   4%|▍         | 410/10000 [01:18<30:10,  5.30step/s, loss=0.071459, elapsed=1.3min]

Entraînement:   4%|▍         | 411/10000 [01:18<30:13,  5.29step/s, loss=0.071459, elapsed=1.3min]

Entraînement:   4%|▍         | 411/10000 [01:18<30:13,  5.29step/s, loss=0.173439, elapsed=1.3min]

Entraînement:   4%|▍         | 412/10000 [01:18<30:11,  5.29step/s, loss=0.173439, elapsed=1.3min]

Entraînement:   4%|▍         | 412/10000 [01:18<30:11,  5.29step/s, loss=0.212645, elapsed=1.3min]

Entraînement:   4%|▍         | 413/10000 [01:18<30:13,  5.29step/s, loss=0.212645, elapsed=1.3min]

Entraînement:   4%|▍         | 413/10000 [01:18<30:13,  5.29step/s, loss=0.101409, elapsed=1.3min]

Entraînement:   4%|▍         | 414/10000 [01:18<30:12,  5.29step/s, loss=0.101409, elapsed=1.3min]

Entraînement:   4%|▍         | 414/10000 [01:18<30:12,  5.29step/s, loss=0.056079, elapsed=1.3min]

Entraînement:   4%|▍         | 415/10000 [01:18<30:11,  5.29step/s, loss=0.056079, elapsed=1.3min]

Entraînement:   4%|▍         | 415/10000 [01:19<30:11,  5.29step/s, loss=0.045945, elapsed=1.3min]

Entraînement:   4%|▍         | 416/10000 [01:19<30:22,  5.26step/s, loss=0.045945, elapsed=1.3min]

Entraînement:   4%|▍         | 416/10000 [01:19<30:22,  5.26step/s, loss=0.057781, elapsed=1.3min]

Entraînement:   4%|▍         | 417/10000 [01:19<30:21,  5.26step/s, loss=0.057781, elapsed=1.3min]

Entraînement:   4%|▍         | 417/10000 [01:19<30:21,  5.26step/s, loss=0.252736, elapsed=1.3min]

Entraînement:   4%|▍         | 418/10000 [01:19<30:21,  5.26step/s, loss=0.252736, elapsed=1.3min]

Entraînement:   4%|▍         | 418/10000 [01:19<30:21,  5.26step/s, loss=0.078723, elapsed=1.3min]

Entraînement:   4%|▍         | 419/10000 [01:19<30:20,  5.26step/s, loss=0.078723, elapsed=1.3min]

Entraînement:   4%|▍         | 419/10000 [01:19<30:20,  5.26step/s, loss=0.047904, elapsed=1.3min]

Entraînement:   4%|▍         | 420/10000 [01:19<30:17,  5.27step/s, loss=0.047904, elapsed=1.3min]

Entraînement:   4%|▍         | 420/10000 [01:19<30:17,  5.27step/s, loss=0.140386, elapsed=1.3min]

Entraînement:   4%|▍         | 421/10000 [01:20<30:16,  5.27step/s, loss=0.140386, elapsed=1.3min]

Entraînement:   4%|▍         | 421/10000 [01:20<30:16,  5.27step/s, loss=0.145055, elapsed=1.3min]

Entraînement:   4%|▍         | 422/10000 [01:20<30:14,  5.28step/s, loss=0.145055, elapsed=1.3min]

Entraînement:   4%|▍         | 422/10000 [01:20<30:14,  5.28step/s, loss=0.084366, elapsed=1.3min]

Entraînement:   4%|▍         | 423/10000 [01:20<30:19,  5.26step/s, loss=0.084366, elapsed=1.3min]

Entraînement:   4%|▍         | 423/10000 [01:20<30:19,  5.26step/s, loss=0.163903, elapsed=1.3min]

Entraînement:   4%|▍         | 424/10000 [01:20<30:20,  5.26step/s, loss=0.163903, elapsed=1.3min]

Entraînement:   4%|▍         | 424/10000 [01:20<30:20,  5.26step/s, loss=0.053192, elapsed=1.3min]

Entraînement:   4%|▍         | 425/10000 [01:20<30:18,  5.27step/s, loss=0.053192, elapsed=1.3min]

Entraînement:   4%|▍         | 425/10000 [01:20<30:18,  5.27step/s, loss=0.066761, elapsed=1.3min]

Entraînement:   4%|▍         | 426/10000 [01:21<30:19,  5.26step/s, loss=0.066761, elapsed=1.3min]

Entraînement:   4%|▍         | 426/10000 [01:21<30:19,  5.26step/s, loss=0.060798, elapsed=1.4min]

Entraînement:   4%|▍         | 427/10000 [01:21<30:15,  5.27step/s, loss=0.060798, elapsed=1.4min]

Entraînement:   4%|▍         | 427/10000 [01:21<30:15,  5.27step/s, loss=0.059935, elapsed=1.4min]

Entraînement:   4%|▍         | 428/10000 [01:21<30:15,  5.27step/s, loss=0.059935, elapsed=1.4min]

Entraînement:   4%|▍         | 428/10000 [01:21<30:15,  5.27step/s, loss=0.076111, elapsed=1.4min]

Entraînement:   4%|▍         | 429/10000 [01:21<30:13,  5.28step/s, loss=0.076111, elapsed=1.4min]

Entraînement:   4%|▍         | 429/10000 [01:21<30:13,  5.28step/s, loss=0.066166, elapsed=1.4min]

Entraînement:   4%|▍         | 430/10000 [01:21<30:16,  5.27step/s, loss=0.066166, elapsed=1.4min]

Entraînement:   4%|▍         | 430/10000 [01:21<30:16,  5.27step/s, loss=0.064265, elapsed=1.4min]

Entraînement:   4%|▍         | 431/10000 [01:22<30:14,  5.27step/s, loss=0.064265, elapsed=1.4min]

Entraînement:   4%|▍         | 431/10000 [01:22<30:14,  5.27step/s, loss=0.066361, elapsed=1.4min]

Entraînement:   4%|▍         | 432/10000 [01:22<30:17,  5.26step/s, loss=0.066361, elapsed=1.4min]

Entraînement:   4%|▍         | 432/10000 [01:22<30:17,  5.26step/s, loss=0.058947, elapsed=1.4min]

Entraînement:   4%|▍         | 433/10000 [01:22<30:15,  5.27step/s, loss=0.058947, elapsed=1.4min]

Entraînement:   4%|▍         | 433/10000 [01:22<30:15,  5.27step/s, loss=0.095352, elapsed=1.4min]

Entraînement:   4%|▍         | 434/10000 [01:22<30:24,  5.24step/s, loss=0.095352, elapsed=1.4min]

Entraînement:   4%|▍         | 434/10000 [01:22<30:24,  5.24step/s, loss=0.174002, elapsed=1.4min]

Entraînement:   4%|▍         | 435/10000 [01:22<30:50,  5.17step/s, loss=0.174002, elapsed=1.4min]

Entraînement:   4%|▍         | 435/10000 [01:22<30:50,  5.17step/s, loss=0.043117, elapsed=1.4min]

Entraînement:   4%|▍         | 436/10000 [01:23<30:45,  5.18step/s, loss=0.043117, elapsed=1.4min]

Entraînement:   4%|▍         | 436/10000 [01:23<30:45,  5.18step/s, loss=0.088019, elapsed=1.4min]

Entraînement:   4%|▍         | 437/10000 [01:23<30:35,  5.21step/s, loss=0.088019, elapsed=1.4min]

Entraînement:   4%|▍         | 437/10000 [01:23<30:35,  5.21step/s, loss=0.097991, elapsed=1.4min]

Entraînement:   4%|▍         | 438/10000 [01:23<30:28,  5.23step/s, loss=0.097991, elapsed=1.4min]

Entraînement:   4%|▍         | 438/10000 [01:23<30:28,  5.23step/s, loss=0.072522, elapsed=1.4min]

Entraînement:   4%|▍         | 439/10000 [01:23<30:24,  5.24step/s, loss=0.072522, elapsed=1.4min]

Entraînement:   4%|▍         | 439/10000 [01:23<30:24,  5.24step/s, loss=0.103940, elapsed=1.4min]

Entraînement:   4%|▍         | 440/10000 [01:23<30:23,  5.24step/s, loss=0.103940, elapsed=1.4min]

Entraînement:   4%|▍         | 440/10000 [01:23<30:23,  5.24step/s, loss=0.044679, elapsed=1.4min]

Entraînement:   4%|▍         | 441/10000 [01:23<30:22,  5.24step/s, loss=0.044679, elapsed=1.4min]

Entraînement:   4%|▍         | 441/10000 [01:23<30:22,  5.24step/s, loss=0.180951, elapsed=1.4min]

Entraînement:   4%|▍         | 442/10000 [01:24<30:19,  5.25step/s, loss=0.180951, elapsed=1.4min]

Entraînement:   4%|▍         | 442/10000 [01:24<30:19,  5.25step/s, loss=0.087720, elapsed=1.4min]

Entraînement:   4%|▍         | 443/10000 [01:24<30:15,  5.26step/s, loss=0.087720, elapsed=1.4min]

Entraînement:   4%|▍         | 443/10000 [01:24<30:15,  5.26step/s, loss=0.072882, elapsed=1.4min]

Entraînement:   4%|▍         | 444/10000 [01:24<30:10,  5.28step/s, loss=0.072882, elapsed=1.4min]

Entraînement:   4%|▍         | 444/10000 [01:24<30:10,  5.28step/s, loss=0.077161, elapsed=1.4min]

Entraînement:   4%|▍         | 445/10000 [01:24<30:12,  5.27step/s, loss=0.077161, elapsed=1.4min]

Entraînement:   4%|▍         | 445/10000 [01:24<30:12,  5.27step/s, loss=0.079866, elapsed=1.4min]

Entraînement:   4%|▍         | 446/10000 [01:24<30:13,  5.27step/s, loss=0.079866, elapsed=1.4min]

Entraînement:   4%|▍         | 446/10000 [01:24<30:13,  5.27step/s, loss=0.140189, elapsed=1.4min]

Entraînement:   4%|▍         | 447/10000 [01:25<30:16,  5.26step/s, loss=0.140189, elapsed=1.4min]

Entraînement:   4%|▍         | 447/10000 [01:25<30:16,  5.26step/s, loss=0.059448, elapsed=1.4min]

Entraînement:   4%|▍         | 448/10000 [01:25<30:13,  5.27step/s, loss=0.059448, elapsed=1.4min]

Entraînement:   4%|▍         | 448/10000 [01:25<30:13,  5.27step/s, loss=0.051604, elapsed=1.4min]

Entraînement:   4%|▍         | 449/10000 [01:25<30:15,  5.26step/s, loss=0.051604, elapsed=1.4min]

Entraînement:   4%|▍         | 449/10000 [01:25<30:15,  5.26step/s, loss=0.070095, elapsed=1.4min]

Entraînement:   4%|▍         | 450/10000 [01:25<30:13,  5.26step/s, loss=0.070095, elapsed=1.4min]

Entraînement:   4%|▍         | 450/10000 [01:25<30:13,  5.26step/s, loss=0.052475, elapsed=1.4min]

Entraînement:   5%|▍         | 451/10000 [01:25<30:11,  5.27step/s, loss=0.052475, elapsed=1.4min]

Entraînement:   5%|▍         | 451/10000 [01:25<30:11,  5.27step/s, loss=0.057549, elapsed=1.4min]

Entraînement:   5%|▍         | 452/10000 [01:26<30:10,  5.27step/s, loss=0.057549, elapsed=1.4min]

Entraînement:   5%|▍         | 452/10000 [01:26<30:10,  5.27step/s, loss=0.072898, elapsed=1.4min]

Entraînement:   5%|▍         | 453/10000 [01:26<30:08,  5.28step/s, loss=0.072898, elapsed=1.4min]

Entraînement:   5%|▍         | 453/10000 [01:26<30:08,  5.28step/s, loss=0.098700, elapsed=1.4min]

Entraînement:   5%|▍         | 454/10000 [01:26<30:10,  5.27step/s, loss=0.098700, elapsed=1.4min]

Entraînement:   5%|▍         | 454/10000 [01:26<30:10,  5.27step/s, loss=0.065030, elapsed=1.4min]

Entraînement:   5%|▍         | 455/10000 [01:26<30:07,  5.28step/s, loss=0.065030, elapsed=1.4min]

Entraînement:   5%|▍         | 455/10000 [01:26<30:07,  5.28step/s, loss=0.066418, elapsed=1.4min]

Entraînement:   5%|▍         | 456/10000 [01:26<30:10,  5.27step/s, loss=0.066418, elapsed=1.4min]

Entraînement:   5%|▍         | 456/10000 [01:26<30:10,  5.27step/s, loss=0.102058, elapsed=1.4min]

Entraînement:   5%|▍         | 457/10000 [01:26<30:08,  5.28step/s, loss=0.102058, elapsed=1.4min]

Entraînement:   5%|▍         | 457/10000 [01:26<30:08,  5.28step/s, loss=0.055556, elapsed=1.4min]

Entraînement:   5%|▍         | 458/10000 [01:27<30:08,  5.28step/s, loss=0.055556, elapsed=1.4min]

Entraînement:   5%|▍         | 458/10000 [01:27<30:08,  5.28step/s, loss=0.055627, elapsed=1.5min]

Entraînement:   5%|▍         | 459/10000 [01:27<30:07,  5.28step/s, loss=0.055627, elapsed=1.5min]

Entraînement:   5%|▍         | 459/10000 [01:27<30:07,  5.28step/s, loss=0.056848, elapsed=1.5min]

Entraînement:   5%|▍         | 460/10000 [01:27<30:07,  5.28step/s, loss=0.056848, elapsed=1.5min]

Entraînement:   5%|▍         | 460/10000 [01:27<30:07,  5.28step/s, loss=0.040770, elapsed=1.5min]

Entraînement:   5%|▍         | 461/10000 [01:27<30:14,  5.26step/s, loss=0.040770, elapsed=1.5min]

Entraînement:   5%|▍         | 461/10000 [01:27<30:14,  5.26step/s, loss=0.097306, elapsed=1.5min]

Entraînement:   5%|▍         | 462/10000 [01:27<30:13,  5.26step/s, loss=0.097306, elapsed=1.5min]

Entraînement:   5%|▍         | 462/10000 [01:27<30:13,  5.26step/s, loss=0.058754, elapsed=1.5min]

Entraînement:   5%|▍         | 463/10000 [01:28<30:16,  5.25step/s, loss=0.058754, elapsed=1.5min]

Entraînement:   5%|▍         | 463/10000 [01:28<30:16,  5.25step/s, loss=0.045059, elapsed=1.5min]

Entraînement:   5%|▍         | 464/10000 [01:28<30:13,  5.26step/s, loss=0.045059, elapsed=1.5min]

Entraînement:   5%|▍         | 464/10000 [01:28<30:13,  5.26step/s, loss=0.069314, elapsed=1.5min]

Entraînement:   5%|▍         | 465/10000 [01:28<30:14,  5.25step/s, loss=0.069314, elapsed=1.5min]

Entraînement:   5%|▍         | 465/10000 [01:28<30:14,  5.25step/s, loss=0.062978, elapsed=1.5min]

Entraînement:   5%|▍         | 466/10000 [01:28<30:22,  5.23step/s, loss=0.062978, elapsed=1.5min]

Entraînement:   5%|▍         | 466/10000 [01:28<30:22,  5.23step/s, loss=0.078928, elapsed=1.5min]

Entraînement:   5%|▍         | 467/10000 [01:28<30:17,  5.25step/s, loss=0.078928, elapsed=1.5min]

Entraînement:   5%|▍         | 467/10000 [01:28<30:17,  5.25step/s, loss=0.181733, elapsed=1.5min]

Entraînement:   5%|▍         | 468/10000 [01:29<30:29,  5.21step/s, loss=0.181733, elapsed=1.5min]

Entraînement:   5%|▍         | 468/10000 [01:29<30:29,  5.21step/s, loss=0.067666, elapsed=1.5min]

Entraînement:   5%|▍         | 469/10000 [01:29<30:27,  5.21step/s, loss=0.067666, elapsed=1.5min]

Entraînement:   5%|▍         | 469/10000 [01:29<30:27,  5.21step/s, loss=0.069061, elapsed=1.5min]

Entraînement:   5%|▍         | 470/10000 [01:29<30:19,  5.24step/s, loss=0.069061, elapsed=1.5min]

Entraînement:   5%|▍         | 470/10000 [01:29<30:19,  5.24step/s, loss=0.080073, elapsed=1.5min]

Entraînement:   5%|▍         | 471/10000 [01:29<30:15,  5.25step/s, loss=0.080073, elapsed=1.5min]

Entraînement:   5%|▍         | 471/10000 [01:29<30:15,  5.25step/s, loss=0.111375, elapsed=1.5min]

Entraînement:   5%|▍         | 472/10000 [01:29<30:15,  5.25step/s, loss=0.111375, elapsed=1.5min]

Entraînement:   5%|▍         | 472/10000 [01:29<30:15,  5.25step/s, loss=0.068044, elapsed=1.5min]

Entraînement:   5%|▍         | 473/10000 [01:30<30:15,  5.25step/s, loss=0.068044, elapsed=1.5min]

Entraînement:   5%|▍         | 473/10000 [01:30<30:15,  5.25step/s, loss=0.108337, elapsed=1.5min]

Entraînement:   5%|▍         | 474/10000 [01:30<30:13,  5.25step/s, loss=0.108337, elapsed=1.5min]

Entraînement:   5%|▍         | 474/10000 [01:30<30:13,  5.25step/s, loss=0.091773, elapsed=1.5min]

Entraînement:   5%|▍         | 475/10000 [01:30<30:09,  5.26step/s, loss=0.091773, elapsed=1.5min]

Entraînement:   5%|▍         | 475/10000 [01:30<30:09,  5.26step/s, loss=0.054876, elapsed=1.5min]

Entraînement:   5%|▍         | 476/10000 [01:30<30:14,  5.25step/s, loss=0.054876, elapsed=1.5min]

Entraînement:   5%|▍         | 476/10000 [01:30<30:14,  5.25step/s, loss=0.075988, elapsed=1.5min]

Entraînement:   5%|▍         | 477/10000 [01:30<30:15,  5.25step/s, loss=0.075988, elapsed=1.5min]

Entraînement:   5%|▍         | 477/10000 [01:30<30:15,  5.25step/s, loss=0.102223, elapsed=1.5min]

Entraînement:   5%|▍         | 478/10000 [01:30<30:15,  5.25step/s, loss=0.102223, elapsed=1.5min]

Entraînement:   5%|▍         | 478/10000 [01:30<30:15,  5.25step/s, loss=0.207127, elapsed=1.5min]

Entraînement:   5%|▍         | 479/10000 [01:31<30:13,  5.25step/s, loss=0.207127, elapsed=1.5min]

Entraînement:   5%|▍         | 479/10000 [01:31<30:13,  5.25step/s, loss=0.065787, elapsed=1.5min]

Entraînement:   5%|▍         | 480/10000 [01:31<30:21,  5.23step/s, loss=0.065787, elapsed=1.5min]

Entraînement:   5%|▍         | 480/10000 [01:31<30:21,  5.23step/s, loss=0.089801, elapsed=1.5min]

Entraînement:   5%|▍         | 481/10000 [01:31<30:19,  5.23step/s, loss=0.089801, elapsed=1.5min]

Entraînement:   5%|▍         | 481/10000 [01:31<30:19,  5.23step/s, loss=0.130984, elapsed=1.5min]

Entraînement:   5%|▍         | 482/10000 [01:31<30:19,  5.23step/s, loss=0.130984, elapsed=1.5min]

Entraînement:   5%|▍         | 482/10000 [01:31<30:19,  5.23step/s, loss=0.107523, elapsed=1.5min]

Entraînement:   5%|▍         | 483/10000 [01:31<30:23,  5.22step/s, loss=0.107523, elapsed=1.5min]

Entraînement:   5%|▍         | 483/10000 [01:31<30:23,  5.22step/s, loss=0.103993, elapsed=1.5min]

Entraînement:   5%|▍         | 484/10000 [01:32<30:23,  5.22step/s, loss=0.103993, elapsed=1.5min]

Entraînement:   5%|▍         | 484/10000 [01:32<30:23,  5.22step/s, loss=0.059965, elapsed=1.5min]

Entraînement:   5%|▍         | 485/10000 [01:32<30:31,  5.20step/s, loss=0.059965, elapsed=1.5min]

Entraînement:   5%|▍         | 485/10000 [01:32<30:31,  5.20step/s, loss=0.072713, elapsed=1.5min]

Entraînement:   5%|▍         | 486/10000 [01:32<30:23,  5.22step/s, loss=0.072713, elapsed=1.5min]

Entraînement:   5%|▍         | 486/10000 [01:32<30:23,  5.22step/s, loss=0.048650, elapsed=1.5min]

Entraînement:   5%|▍         | 487/10000 [01:32<30:23,  5.22step/s, loss=0.048650, elapsed=1.5min]

Entraînement:   5%|▍         | 487/10000 [01:32<30:23,  5.22step/s, loss=0.142724, elapsed=1.5min]

Entraînement:   5%|▍         | 488/10000 [01:32<30:18,  5.23step/s, loss=0.142724, elapsed=1.5min]

Entraînement:   5%|▍         | 488/10000 [01:32<30:18,  5.23step/s, loss=0.074451, elapsed=1.5min]

Entraînement:   5%|▍         | 489/10000 [01:33<30:10,  5.25step/s, loss=0.074451, elapsed=1.5min]

Entraînement:   5%|▍         | 489/10000 [01:33<30:10,  5.25step/s, loss=0.042110, elapsed=1.6min]

Entraînement:   5%|▍         | 490/10000 [01:33<30:08,  5.26step/s, loss=0.042110, elapsed=1.6min]

Entraînement:   5%|▍         | 490/10000 [01:33<30:08,  5.26step/s, loss=0.051861, elapsed=1.6min]

Entraînement:   5%|▍         | 491/10000 [01:33<30:08,  5.26step/s, loss=0.051861, elapsed=1.6min]

Entraînement:   5%|▍         | 491/10000 [01:33<30:08,  5.26step/s, loss=0.061922, elapsed=1.6min]

Entraînement:   5%|▍         | 492/10000 [01:33<30:08,  5.26step/s, loss=0.061922, elapsed=1.6min]

Entraînement:   5%|▍         | 492/10000 [01:33<30:08,  5.26step/s, loss=0.106507, elapsed=1.6min]

Entraînement:   5%|▍         | 493/10000 [01:33<30:06,  5.26step/s, loss=0.106507, elapsed=1.6min]

Entraînement:   5%|▍         | 493/10000 [01:33<30:06,  5.26step/s, loss=0.068645, elapsed=1.6min]

Entraînement:   5%|▍         | 494/10000 [01:34<30:09,  5.25step/s, loss=0.068645, elapsed=1.6min]

Entraînement:   5%|▍         | 494/10000 [01:34<30:09,  5.25step/s, loss=0.086630, elapsed=1.6min]

Entraînement:   5%|▍         | 495/10000 [01:34<30:08,  5.26step/s, loss=0.086630, elapsed=1.6min]

Entraînement:   5%|▍         | 495/10000 [01:34<30:08,  5.26step/s, loss=0.086751, elapsed=1.6min]

Entraînement:   5%|▍         | 496/10000 [01:34<30:06,  5.26step/s, loss=0.086751, elapsed=1.6min]

Entraînement:   5%|▍         | 496/10000 [01:34<30:06,  5.26step/s, loss=0.117197, elapsed=1.6min]

Entraînement:   5%|▍         | 497/10000 [01:34<30:04,  5.27step/s, loss=0.117197, elapsed=1.6min]

Entraînement:   5%|▍         | 497/10000 [01:34<30:04,  5.27step/s, loss=0.064222, elapsed=1.6min]

Entraînement:   5%|▍         | 498/10000 [01:34<30:04,  5.27step/s, loss=0.064222, elapsed=1.6min]

Entraînement:   5%|▍         | 498/10000 [01:34<30:04,  5.27step/s, loss=0.034513, elapsed=1.6min]

Entraînement:   5%|▍         | 499/10000 [01:34<30:09,  5.25step/s, loss=0.034513, elapsed=1.6min]

Entraînement:   5%|▍         | 499/10000 [01:34<30:09,  5.25step/s, loss=0.041020, elapsed=1.6min]

Entraînement:   5%|▌         | 500/10000 [01:35<30:03,  5.27step/s, loss=0.041020, elapsed=1.6min]

Entraînement:   5%|▌         | 500/10000 [01:35<30:03,  5.27step/s, loss=0.179555, elapsed=1.6min]

Entraînement:   5%|▌         | 500/10000 [01:35<30:03,  5.27step/s, loss=0.179555, elapsed=1.6min]

Entraînement:   5%|▌         | 501/10000 [01:35<30:18,  5.22step/s, loss=0.179555, elapsed=1.6min]

Entraînement:   5%|▌         | 501/10000 [01:35<30:18,  5.22step/s, loss=0.044510, elapsed=1.6min]

Step 500/10000 | Train loss: 0.179555 | Elapsed: 1.6min | ETA: 30.1min

Entraînement:   5%|▌         | 502/10000 [01:35<30:12,  5.24step/s, loss=0.044510, elapsed=1.6min]

Entraînement:   5%|▌         | 502/10000 [01:35<30:12,  5.24step/s, loss=0.053434, elapsed=1.6min]

Entraînement:   5%|▌         | 503/10000 [01:35<30:09,  5.25step/s, loss=0.053434, elapsed=1.6min]

Entraînement:   5%|▌         | 503/10000 [01:35<30:09,  5.25step/s, loss=0.055526, elapsed=1.6min]

Entraînement:   5%|▌         | 504/10000 [01:35<30:04,  5.26step/s, loss=0.055526, elapsed=1.6min]

Entraînement:   5%|▌         | 504/10000 [01:35<30:04,  5.26step/s, loss=0.178917, elapsed=1.6min]

Entraînement:   5%|▌         | 505/10000 [01:36<30:03,  5.27step/s, loss=0.178917, elapsed=1.6min]

Entraînement:   5%|▌         | 505/10000 [01:36<30:03,  5.27step/s, loss=0.080308, elapsed=1.6min]

Entraînement:   5%|▌         | 506/10000 [01:36<30:04,  5.26step/s, loss=0.080308, elapsed=1.6min]

Entraînement:   5%|▌         | 506/10000 [01:36<30:04,  5.26step/s, loss=0.051461, elapsed=1.6min]

Entraînement:   5%|▌         | 507/10000 [01:36<30:06,  5.26step/s, loss=0.051461, elapsed=1.6min]

Entraînement:   5%|▌         | 507/10000 [01:36<30:06,  5.26step/s, loss=0.097917, elapsed=1.6min]

Entraînement:   5%|▌         | 508/10000 [01:36<30:04,  5.26step/s, loss=0.097917, elapsed=1.6min]

Entraînement:   5%|▌         | 508/10000 [01:36<30:04,  5.26step/s, loss=0.046639, elapsed=1.6min]

Entraînement:   5%|▌         | 509/10000 [01:36<30:00,  5.27step/s, loss=0.046639, elapsed=1.6min]

Entraînement:   5%|▌         | 509/10000 [01:36<30:00,  5.27step/s, loss=0.072215, elapsed=1.6min]

Entraînement:   5%|▌         | 510/10000 [01:37<29:59,  5.27step/s, loss=0.072215, elapsed=1.6min]

Entraînement:   5%|▌         | 510/10000 [01:37<29:59,  5.27step/s, loss=0.081073, elapsed=1.6min]

Entraînement:   5%|▌         | 511/10000 [01:37<29:59,  5.27step/s, loss=0.081073, elapsed=1.6min]

Entraînement:   5%|▌         | 511/10000 [01:37<29:59,  5.27step/s, loss=0.072426, elapsed=1.6min]

Entraînement:   5%|▌         | 512/10000 [01:37<29:55,  5.28step/s, loss=0.072426, elapsed=1.6min]

Entraînement:   5%|▌         | 512/10000 [01:37<29:55,  5.28step/s, loss=0.062388, elapsed=1.6min]

Entraînement:   5%|▌         | 513/10000 [01:37<29:57,  5.28step/s, loss=0.062388, elapsed=1.6min]

Entraînement:   5%|▌         | 513/10000 [01:37<29:57,  5.28step/s, loss=0.174125, elapsed=1.6min]

Entraînement:   5%|▌         | 514/10000 [01:37<29:57,  5.28step/s, loss=0.174125, elapsed=1.6min]

Entraînement:   5%|▌         | 514/10000 [01:37<29:57,  5.28step/s, loss=0.225579, elapsed=1.6min]

Entraînement:   5%|▌         | 515/10000 [01:38<30:01,  5.26step/s, loss=0.225579, elapsed=1.6min]

Entraînement:   5%|▌         | 515/10000 [01:38<30:01,  5.26step/s, loss=0.060628, elapsed=1.6min]

Entraînement:   5%|▌         | 516/10000 [01:38<30:00,  5.27step/s, loss=0.060628, elapsed=1.6min]

Entraînement:   5%|▌         | 516/10000 [01:38<30:00,  5.27step/s, loss=0.068168, elapsed=1.6min]

Entraînement:   5%|▌         | 517/10000 [01:38<29:59,  5.27step/s, loss=0.068168, elapsed=1.6min]

Entraînement:   5%|▌         | 517/10000 [01:38<29:59,  5.27step/s, loss=0.056314, elapsed=1.6min]

Entraînement:   5%|▌         | 518/10000 [01:38<29:59,  5.27step/s, loss=0.056314, elapsed=1.6min]

Entraînement:   5%|▌         | 518/10000 [01:38<29:59,  5.27step/s, loss=0.084082, elapsed=1.6min]

Entraînement:   5%|▌         | 519/10000 [01:38<29:57,  5.27step/s, loss=0.084082, elapsed=1.6min]

Entraînement:   5%|▌         | 519/10000 [01:38<29:57,  5.27step/s, loss=0.054114, elapsed=1.6min]

Entraînement:   5%|▌         | 520/10000 [01:38<29:56,  5.28step/s, loss=0.054114, elapsed=1.6min]

Entraînement:   5%|▌         | 520/10000 [01:38<29:56,  5.28step/s, loss=0.043059, elapsed=1.6min]

Entraînement:   5%|▌         | 521/10000 [01:39<29:58,  5.27step/s, loss=0.043059, elapsed=1.6min]

Entraînement:   5%|▌         | 521/10000 [01:39<29:58,  5.27step/s, loss=0.129470, elapsed=1.7min]

Entraînement:   5%|▌         | 522/10000 [01:39<30:03,  5.26step/s, loss=0.129470, elapsed=1.7min]

Entraînement:   5%|▌         | 522/10000 [01:39<30:03,  5.26step/s, loss=0.080215, elapsed=1.7min]

Entraînement:   5%|▌         | 523/10000 [01:39<30:00,  5.26step/s, loss=0.080215, elapsed=1.7min]

Entraînement:   5%|▌         | 523/10000 [01:39<30:00,  5.26step/s, loss=0.092877, elapsed=1.7min]

Entraînement:   5%|▌         | 524/10000 [01:39<29:55,  5.28step/s, loss=0.092877, elapsed=1.7min]

Entraînement:   5%|▌         | 524/10000 [01:39<29:55,  5.28step/s, loss=0.105712, elapsed=1.7min]

Entraînement:   5%|▌         | 525/10000 [01:39<29:57,  5.27step/s, loss=0.105712, elapsed=1.7min]

Entraînement:   5%|▌         | 525/10000 [01:39<29:57,  5.27step/s, loss=0.109973, elapsed=1.7min]

Entraînement:   5%|▌         | 526/10000 [01:40<29:55,  5.28step/s, loss=0.109973, elapsed=1.7min]

Entraînement:   5%|▌         | 526/10000 [01:40<29:55,  5.28step/s, loss=0.109795, elapsed=1.7min]

Entraînement:   5%|▌         | 527/10000 [01:40<29:51,  5.29step/s, loss=0.109795, elapsed=1.7min]

Entraînement:   5%|▌         | 527/10000 [01:40<29:51,  5.29step/s, loss=0.044242, elapsed=1.7min]

Entraînement:   5%|▌         | 528/10000 [01:40<29:52,  5.29step/s, loss=0.044242, elapsed=1.7min]

Entraînement:   5%|▌         | 528/10000 [01:40<29:52,  5.29step/s, loss=0.049153, elapsed=1.7min]

Entraînement:   5%|▌         | 529/10000 [01:40<29:51,  5.29step/s, loss=0.049153, elapsed=1.7min]

Entraînement:   5%|▌         | 529/10000 [01:40<29:51,  5.29step/s, loss=0.079855, elapsed=1.7min]

Entraînement:   5%|▌         | 530/10000 [01:40<29:53,  5.28step/s, loss=0.079855, elapsed=1.7min]

Entraînement:   5%|▌         | 530/10000 [01:40<29:53,  5.28step/s, loss=0.039455, elapsed=1.7min]

Entraînement:   5%|▌         | 531/10000 [01:41<29:53,  5.28step/s, loss=0.039455, elapsed=1.7min]

Entraînement:   5%|▌         | 531/10000 [01:41<29:53,  5.28step/s, loss=0.044474, elapsed=1.7min]

Entraînement:   5%|▌         | 532/10000 [01:41<29:55,  5.27step/s, loss=0.044474, elapsed=1.7min]

Entraînement:   5%|▌         | 532/10000 [01:41<29:55,  5.27step/s, loss=0.096426, elapsed=1.7min]

Entraînement:   5%|▌         | 533/10000 [01:41<29:55,  5.27step/s, loss=0.096426, elapsed=1.7min]

Entraînement:   5%|▌         | 533/10000 [01:41<29:55,  5.27step/s, loss=0.096678, elapsed=1.7min]

Entraînement:   5%|▌         | 534/10000 [01:41<29:53,  5.28step/s, loss=0.096678, elapsed=1.7min]

Entraînement:   5%|▌         | 534/10000 [01:41<29:53,  5.28step/s, loss=0.057068, elapsed=1.7min]

Entraînement:   5%|▌         | 535/10000 [01:41<29:51,  5.28step/s, loss=0.057068, elapsed=1.7min]

Entraînement:   5%|▌         | 535/10000 [01:41<29:51,  5.28step/s, loss=0.043119, elapsed=1.7min]

Entraînement:   5%|▌         | 536/10000 [01:42<29:52,  5.28step/s, loss=0.043119, elapsed=1.7min]

Entraînement:   5%|▌         | 536/10000 [01:42<29:52,  5.28step/s, loss=0.138580, elapsed=1.7min]

Entraînement:   5%|▌         | 537/10000 [01:42<29:51,  5.28step/s, loss=0.138580, elapsed=1.7min]

Entraînement:   5%|▌         | 537/10000 [01:42<29:51,  5.28step/s, loss=0.027953, elapsed=1.7min]

Entraînement:   5%|▌         | 538/10000 [01:42<29:51,  5.28step/s, loss=0.027953, elapsed=1.7min]

Entraînement:   5%|▌         | 538/10000 [01:42<29:51,  5.28step/s, loss=0.148284, elapsed=1.7min]

Entraînement:   5%|▌         | 539/10000 [01:42<29:49,  5.29step/s, loss=0.148284, elapsed=1.7min]

Entraînement:   5%|▌         | 539/10000 [01:42<29:49,  5.29step/s, loss=0.212433, elapsed=1.7min]

Entraînement:   5%|▌         | 540/10000 [01:42<29:53,  5.27step/s, loss=0.212433, elapsed=1.7min]

Entraînement:   5%|▌         | 540/10000 [01:42<29:53,  5.27step/s, loss=0.047191, elapsed=1.7min]

Entraînement:   5%|▌         | 541/10000 [01:42<29:55,  5.27step/s, loss=0.047191, elapsed=1.7min]

Entraînement:   5%|▌         | 541/10000 [01:42<29:55,  5.27step/s, loss=0.049858, elapsed=1.7min]

Entraînement:   5%|▌         | 542/10000 [01:43<29:55,  5.27step/s, loss=0.049858, elapsed=1.7min]

Entraînement:   5%|▌         | 542/10000 [01:43<29:55,  5.27step/s, loss=0.043418, elapsed=1.7min]

Entraînement:   5%|▌         | 543/10000 [01:43<29:58,  5.26step/s, loss=0.043418, elapsed=1.7min]

Entraînement:   5%|▌         | 543/10000 [01:43<29:58,  5.26step/s, loss=0.127460, elapsed=1.7min]

Entraînement:   5%|▌         | 544/10000 [01:43<29:52,  5.28step/s, loss=0.127460, elapsed=1.7min]

Entraînement:   5%|▌         | 544/10000 [01:43<29:52,  5.28step/s, loss=0.073601, elapsed=1.7min]

Entraînement:   5%|▌         | 545/10000 [01:43<29:52,  5.27step/s, loss=0.073601, elapsed=1.7min]

Entraînement:   5%|▌         | 545/10000 [01:43<29:52,  5.27step/s, loss=0.038634, elapsed=1.7min]

Entraînement:   5%|▌         | 546/10000 [01:43<29:58,  5.26step/s, loss=0.038634, elapsed=1.7min]

Entraînement:   5%|▌         | 546/10000 [01:43<29:58,  5.26step/s, loss=0.064963, elapsed=1.7min]

Entraînement:   5%|▌         | 547/10000 [01:44<29:57,  5.26step/s, loss=0.064963, elapsed=1.7min]

Entraînement:   5%|▌         | 547/10000 [01:44<29:57,  5.26step/s, loss=0.117322, elapsed=1.7min]

Entraînement:   5%|▌         | 548/10000 [01:44<29:56,  5.26step/s, loss=0.117322, elapsed=1.7min]

Entraînement:   5%|▌         | 548/10000 [01:44<29:56,  5.26step/s, loss=0.051626, elapsed=1.7min]

Entraînement:   5%|▌         | 549/10000 [01:44<29:55,  5.26step/s, loss=0.051626, elapsed=1.7min]

Entraînement:   5%|▌         | 549/10000 [01:44<29:55,  5.26step/s, loss=0.042142, elapsed=1.7min]

Entraînement:   6%|▌         | 550/10000 [01:44<29:57,  5.26step/s, loss=0.042142, elapsed=1.7min]

Entraînement:   6%|▌         | 550/10000 [01:44<29:57,  5.26step/s, loss=0.083349, elapsed=1.7min]

Entraînement:   6%|▌         | 551/10000 [01:44<29:55,  5.26step/s, loss=0.083349, elapsed=1.7min]

Entraînement:   6%|▌         | 551/10000 [01:44<29:55,  5.26step/s, loss=0.061249, elapsed=1.7min]

Entraînement:   6%|▌         | 552/10000 [01:45<29:56,  5.26step/s, loss=0.061249, elapsed=1.7min]

Entraînement:   6%|▌         | 552/10000 [01:45<29:56,  5.26step/s, loss=0.065160, elapsed=1.8min]

Entraînement:   6%|▌         | 553/10000 [01:45<29:54,  5.26step/s, loss=0.065160, elapsed=1.8min]

Entraînement:   6%|▌         | 553/10000 [01:45<29:54,  5.26step/s, loss=0.095841, elapsed=1.8min]

Entraînement:   6%|▌         | 554/10000 [01:45<29:53,  5.27step/s, loss=0.095841, elapsed=1.8min]

Entraînement:   6%|▌         | 554/10000 [01:45<29:53,  5.27step/s, loss=0.050732, elapsed=1.8min]

Entraînement:   6%|▌         | 555/10000 [01:45<29:47,  5.29step/s, loss=0.050732, elapsed=1.8min]

Entraînement:   6%|▌         | 555/10000 [01:45<29:47,  5.29step/s, loss=0.277647, elapsed=1.8min]

Entraînement:   6%|▌         | 556/10000 [01:45<29:45,  5.29step/s, loss=0.277647, elapsed=1.8min]

Entraînement:   6%|▌         | 556/10000 [01:45<29:45,  5.29step/s, loss=0.078101, elapsed=1.8min]

Entraînement:   6%|▌         | 557/10000 [01:45<29:45,  5.29step/s, loss=0.078101, elapsed=1.8min]

Entraînement:   6%|▌         | 557/10000 [01:45<29:45,  5.29step/s, loss=0.093286, elapsed=1.8min]

Entraînement:   6%|▌         | 558/10000 [01:46<29:48,  5.28step/s, loss=0.093286, elapsed=1.8min]

Entraînement:   6%|▌         | 558/10000 [01:46<29:48,  5.28step/s, loss=0.081399, elapsed=1.8min]

Entraînement:   6%|▌         | 559/10000 [01:46<29:50,  5.27step/s, loss=0.081399, elapsed=1.8min]

Entraînement:   6%|▌         | 559/10000 [01:46<29:50,  5.27step/s, loss=0.067284, elapsed=1.8min]

Entraînement:   6%|▌         | 560/10000 [01:46<29:48,  5.28step/s, loss=0.067284, elapsed=1.8min]

Entraînement:   6%|▌         | 560/10000 [01:46<29:48,  5.28step/s, loss=0.064286, elapsed=1.8min]

Entraînement:   6%|▌         | 561/10000 [01:46<29:48,  5.28step/s, loss=0.064286, elapsed=1.8min]

Entraînement:   6%|▌         | 561/10000 [01:46<29:48,  5.28step/s, loss=0.051915, elapsed=1.8min]

Entraînement:   6%|▌         | 562/10000 [01:46<29:49,  5.27step/s, loss=0.051915, elapsed=1.8min]

Entraînement:   6%|▌         | 562/10000 [01:46<29:49,  5.27step/s, loss=0.097318, elapsed=1.8min]

Entraînement:   6%|▌         | 563/10000 [01:47<29:48,  5.28step/s, loss=0.097318, elapsed=1.8min]

Entraînement:   6%|▌         | 563/10000 [01:47<29:48,  5.28step/s, loss=0.162812, elapsed=1.8min]

Entraînement:   6%|▌         | 564/10000 [01:47<29:46,  5.28step/s, loss=0.162812, elapsed=1.8min]

Entraînement:   6%|▌         | 564/10000 [01:47<29:46,  5.28step/s, loss=0.048014, elapsed=1.8min]

Entraînement:   6%|▌         | 565/10000 [01:47<29:45,  5.29step/s, loss=0.048014, elapsed=1.8min]

Entraînement:   6%|▌         | 565/10000 [01:47<29:45,  5.29step/s, loss=0.070475, elapsed=1.8min]

Entraînement:   6%|▌         | 566/10000 [01:47<29:50,  5.27step/s, loss=0.070475, elapsed=1.8min]

Entraînement:   6%|▌         | 566/10000 [01:47<29:50,  5.27step/s, loss=0.137913, elapsed=1.8min]

Entraînement:   6%|▌         | 567/10000 [01:47<29:51,  5.27step/s, loss=0.137913, elapsed=1.8min]

Entraînement:   6%|▌         | 567/10000 [01:47<29:51,  5.27step/s, loss=0.098711, elapsed=1.8min]

Entraînement:   6%|▌         | 568/10000 [01:48<29:52,  5.26step/s, loss=0.098711, elapsed=1.8min]

Entraînement:   6%|▌         | 568/10000 [01:48<29:52,  5.26step/s, loss=0.050875, elapsed=1.8min]

Entraînement:   6%|▌         | 569/10000 [01:48<29:50,  5.27step/s, loss=0.050875, elapsed=1.8min]

Entraînement:   6%|▌         | 569/10000 [01:48<29:50,  5.27step/s, loss=0.094692, elapsed=1.8min]

Entraînement:   6%|▌         | 570/10000 [01:48<29:47,  5.27step/s, loss=0.094692, elapsed=1.8min]

Entraînement:   6%|▌         | 570/10000 [01:48<29:47,  5.27step/s, loss=0.061379, elapsed=1.8min]

Entraînement:   6%|▌         | 571/10000 [01:48<29:56,  5.25step/s, loss=0.061379, elapsed=1.8min]

Entraînement:   6%|▌         | 571/10000 [01:48<29:56,  5.25step/s, loss=0.054707, elapsed=1.8min]

Entraînement:   6%|▌         | 572/10000 [01:48<30:04,  5.23step/s, loss=0.054707, elapsed=1.8min]

Entraînement:   6%|▌         | 572/10000 [01:48<30:04,  5.23step/s, loss=0.079884, elapsed=1.8min]

Entraînement:   6%|▌         | 573/10000 [01:49<30:01,  5.23step/s, loss=0.079884, elapsed=1.8min]

Entraînement:   6%|▌         | 573/10000 [01:49<30:01,  5.23step/s, loss=0.096339, elapsed=1.8min]

Entraînement:   6%|▌         | 574/10000 [01:49<29:58,  5.24step/s, loss=0.096339, elapsed=1.8min]

Entraînement:   6%|▌         | 574/10000 [01:49<29:58,  5.24step/s, loss=0.232855, elapsed=1.8min]

Entraînement:   6%|▌         | 575/10000 [01:49<29:58,  5.24step/s, loss=0.232855, elapsed=1.8min]

Entraînement:   6%|▌         | 575/10000 [01:49<29:58,  5.24step/s, loss=0.086057, elapsed=1.8min]

Entraînement:   6%|▌         | 576/10000 [01:49<29:56,  5.25step/s, loss=0.086057, elapsed=1.8min]

Entraînement:   6%|▌         | 576/10000 [01:49<29:56,  5.25step/s, loss=0.165951, elapsed=1.8min]

Entraînement:   6%|▌         | 577/10000 [01:49<29:54,  5.25step/s, loss=0.165951, elapsed=1.8min]

Entraînement:   6%|▌         | 577/10000 [01:49<29:54,  5.25step/s, loss=0.159175, elapsed=1.8min]

Entraînement:   6%|▌         | 578/10000 [01:49<29:52,  5.26step/s, loss=0.159175, elapsed=1.8min]

Entraînement:   6%|▌         | 578/10000 [01:49<29:52,  5.26step/s, loss=0.058807, elapsed=1.8min]

Entraînement:   6%|▌         | 579/10000 [01:50<29:49,  5.26step/s, loss=0.058807, elapsed=1.8min]

Entraînement:   6%|▌         | 579/10000 [01:50<29:49,  5.26step/s, loss=0.054421, elapsed=1.8min]

Entraînement:   6%|▌         | 580/10000 [01:50<29:49,  5.26step/s, loss=0.054421, elapsed=1.8min]

Entraînement:   6%|▌         | 580/10000 [01:50<29:49,  5.26step/s, loss=0.128480, elapsed=1.8min]

Entraînement:   6%|▌         | 581/10000 [01:50<29:51,  5.26step/s, loss=0.128480, elapsed=1.8min]

Entraînement:   6%|▌         | 581/10000 [01:50<29:51,  5.26step/s, loss=0.057909, elapsed=1.8min]

Entraînement:   6%|▌         | 582/10000 [01:50<29:50,  5.26step/s, loss=0.057909, elapsed=1.8min]

Entraînement:   6%|▌         | 582/10000 [01:50<29:50,  5.26step/s, loss=0.061738, elapsed=1.8min]

Entraînement:   6%|▌         | 583/10000 [01:50<29:50,  5.26step/s, loss=0.061738, elapsed=1.8min]

Entraînement:   6%|▌         | 583/10000 [01:50<29:50,  5.26step/s, loss=0.078270, elapsed=1.8min]

Entraînement:   6%|▌         | 584/10000 [01:51<29:47,  5.27step/s, loss=0.078270, elapsed=1.8min]

Entraînement:   6%|▌         | 584/10000 [01:51<29:47,  5.27step/s, loss=0.067958, elapsed=1.9min]

Entraînement:   6%|▌         | 585/10000 [01:51<29:47,  5.27step/s, loss=0.067958, elapsed=1.9min]

Entraînement:   6%|▌         | 585/10000 [01:51<29:47,  5.27step/s, loss=0.054665, elapsed=1.9min]

Entraînement:   6%|▌         | 586/10000 [01:51<29:43,  5.28step/s, loss=0.054665, elapsed=1.9min]

Entraînement:   6%|▌         | 586/10000 [01:51<29:43,  5.28step/s, loss=0.051439, elapsed=1.9min]

Entraînement:   6%|▌         | 587/10000 [01:51<29:44,  5.27step/s, loss=0.051439, elapsed=1.9min]

Entraînement:   6%|▌         | 587/10000 [01:51<29:44,  5.27step/s, loss=0.110993, elapsed=1.9min]

Entraînement:   6%|▌         | 588/10000 [01:51<29:45,  5.27step/s, loss=0.110993, elapsed=1.9min]

Entraînement:   6%|▌         | 588/10000 [01:51<29:45,  5.27step/s, loss=0.057455, elapsed=1.9min]

Entraînement:   6%|▌         | 589/10000 [01:52<29:49,  5.26step/s, loss=0.057455, elapsed=1.9min]

Entraînement:   6%|▌         | 589/10000 [01:52<29:49,  5.26step/s, loss=0.054135, elapsed=1.9min]

Entraînement:   6%|▌         | 590/10000 [01:52<29:51,  5.25step/s, loss=0.054135, elapsed=1.9min]

Entraînement:   6%|▌         | 590/10000 [01:52<29:51,  5.25step/s, loss=0.067899, elapsed=1.9min]

Entraînement:   6%|▌         | 591/10000 [01:52<29:49,  5.26step/s, loss=0.067899, elapsed=1.9min]

Entraînement:   6%|▌         | 591/10000 [01:52<29:49,  5.26step/s, loss=0.053596, elapsed=1.9min]

Entraînement:   6%|▌         | 592/10000 [01:52<29:50,  5.26step/s, loss=0.053596, elapsed=1.9min]

Entraînement:   6%|▌         | 592/10000 [01:52<29:50,  5.26step/s, loss=0.085992, elapsed=1.9min]

Entraînement:   6%|▌         | 593/10000 [01:52<29:49,  5.26step/s, loss=0.085992, elapsed=1.9min]

Entraînement:   6%|▌         | 593/10000 [01:52<29:49,  5.26step/s, loss=0.083192, elapsed=1.9min]

Entraînement:   6%|▌         | 594/10000 [01:53<29:46,  5.26step/s, loss=0.083192, elapsed=1.9min]

Entraînement:   6%|▌         | 594/10000 [01:53<29:46,  5.26step/s, loss=0.064997, elapsed=1.9min]

Entraînement:   6%|▌         | 595/10000 [01:53<29:42,  5.28step/s, loss=0.064997, elapsed=1.9min]

Entraînement:   6%|▌         | 595/10000 [01:53<29:42,  5.28step/s, loss=0.183628, elapsed=1.9min]

Entraînement:   6%|▌         | 596/10000 [01:53<29:43,  5.27step/s, loss=0.183628, elapsed=1.9min]

Entraînement:   6%|▌         | 596/10000 [01:53<29:43,  5.27step/s, loss=0.067180, elapsed=1.9min]

Entraînement:   6%|▌         | 597/10000 [01:53<29:43,  5.27step/s, loss=0.067180, elapsed=1.9min]

Entraînement:   6%|▌         | 597/10000 [01:53<29:43,  5.27step/s, loss=0.095978, elapsed=1.9min]

Entraînement:   6%|▌         | 598/10000 [01:53<29:46,  5.26step/s, loss=0.095978, elapsed=1.9min]

Entraînement:   6%|▌         | 598/10000 [01:53<29:46,  5.26step/s, loss=0.043003, elapsed=1.9min]

Entraînement:   6%|▌         | 599/10000 [01:53<29:47,  5.26step/s, loss=0.043003, elapsed=1.9min]

Entraînement:   6%|▌         | 599/10000 [01:53<29:47,  5.26step/s, loss=0.087869, elapsed=1.9min]

Entraînement:   6%|▌         | 600/10000 [01:54<29:46,  5.26step/s, loss=0.087869, elapsed=1.9min]

Entraînement:   6%|▌         | 600/10000 [01:54<29:46,  5.26step/s, loss=0.096925, elapsed=1.9min]

Entraînement:   6%|▌         | 600/10000 [01:54<29:46,  5.26step/s, loss=0.096925, elapsed=1.9min]

Entraînement:   6%|▌         | 601/10000 [01:54<30:01,  5.22step/s, loss=0.096925, elapsed=1.9min]

Entraînement:   6%|▌         | 601/10000 [01:54<30:01,  5.22step/s, loss=0.064579, elapsed=1.9min]

Step 600/10000 | Train loss: 0.096925 | Elapsed: 1.9min | ETA: 29.8min

Entraînement:   6%|▌         | 602/10000 [01:54<29:56,  5.23step/s, loss=0.064579, elapsed=1.9min]

Entraînement:   6%|▌         | 602/10000 [01:54<29:56,  5.23step/s, loss=0.039214, elapsed=1.9min]

Entraînement:   6%|▌         | 603/10000 [01:54<29:51,  5.25step/s, loss=0.039214, elapsed=1.9min]

Entraînement:   6%|▌         | 603/10000 [01:54<29:51,  5.25step/s, loss=0.178511, elapsed=1.9min]

Entraînement:   6%|▌         | 604/10000 [01:54<29:49,  5.25step/s, loss=0.178511, elapsed=1.9min]

Entraînement:   6%|▌         | 604/10000 [01:54<29:49,  5.25step/s, loss=0.157044, elapsed=1.9min]

Entraînement:   6%|▌         | 605/10000 [01:55<29:49,  5.25step/s, loss=0.157044, elapsed=1.9min]

Entraînement:   6%|▌         | 605/10000 [01:55<29:49,  5.25step/s, loss=0.120394, elapsed=1.9min]

Entraînement:   6%|▌         | 606/10000 [01:55<29:44,  5.27step/s, loss=0.120394, elapsed=1.9min]

Entraînement:   6%|▌         | 606/10000 [01:55<29:44,  5.27step/s, loss=0.112764, elapsed=1.9min]

Entraînement:   6%|▌         | 607/10000 [01:55<29:47,  5.25step/s, loss=0.112764, elapsed=1.9min]

Entraînement:   6%|▌         | 607/10000 [01:55<29:47,  5.25step/s, loss=0.070623, elapsed=1.9min]

Entraînement:   6%|▌         | 608/10000 [01:55<29:43,  5.27step/s, loss=0.070623, elapsed=1.9min]

Entraînement:   6%|▌         | 608/10000 [01:55<29:43,  5.27step/s, loss=0.092892, elapsed=1.9min]

Entraînement:   6%|▌         | 609/10000 [01:55<29:44,  5.26step/s, loss=0.092892, elapsed=1.9min]

Entraînement:   6%|▌         | 609/10000 [01:55<29:44,  5.26step/s, loss=0.113441, elapsed=1.9min]

Entraînement:   6%|▌         | 610/10000 [01:56<29:41,  5.27step/s, loss=0.113441, elapsed=1.9min]

Entraînement:   6%|▌         | 610/10000 [01:56<29:41,  5.27step/s, loss=0.081125, elapsed=1.9min]

Entraînement:   6%|▌         | 611/10000 [01:56<29:41,  5.27step/s, loss=0.081125, elapsed=1.9min]

Entraînement:   6%|▌         | 611/10000 [01:56<29:41,  5.27step/s, loss=0.051540, elapsed=1.9min]

Entraînement:   6%|▌         | 612/10000 [01:56<29:42,  5.27step/s, loss=0.051540, elapsed=1.9min]

Entraînement:   6%|▌         | 612/10000 [01:56<29:42,  5.27step/s, loss=0.050460, elapsed=1.9min]

Entraînement:   6%|▌         | 613/10000 [01:56<29:44,  5.26step/s, loss=0.050460, elapsed=1.9min]

Entraînement:   6%|▌         | 613/10000 [01:56<29:44,  5.26step/s, loss=0.102654, elapsed=1.9min]

Entraînement:   6%|▌         | 614/10000 [01:56<29:45,  5.26step/s, loss=0.102654, elapsed=1.9min]

Entraînement:   6%|▌         | 614/10000 [01:56<29:45,  5.26step/s, loss=0.091308, elapsed=1.9min]

Entraînement:   6%|▌         | 615/10000 [01:57<29:46,  5.25step/s, loss=0.091308, elapsed=1.9min]

Entraînement:   6%|▌         | 615/10000 [01:57<29:46,  5.25step/s, loss=0.065027, elapsed=2.0min]

Entraînement:   6%|▌         | 616/10000 [01:57<29:43,  5.26step/s, loss=0.065027, elapsed=2.0min]

Entraînement:   6%|▌         | 616/10000 [01:57<29:43,  5.26step/s, loss=0.076721, elapsed=2.0min]

Entraînement:   6%|▌         | 617/10000 [01:57<29:39,  5.27step/s, loss=0.076721, elapsed=2.0min]

Entraînement:   6%|▌         | 617/10000 [01:57<29:39,  5.27step/s, loss=0.060163, elapsed=2.0min]

Entraînement:   6%|▌         | 618/10000 [01:57<29:37,  5.28step/s, loss=0.060163, elapsed=2.0min]

Entraînement:   6%|▌         | 618/10000 [01:57<29:37,  5.28step/s, loss=0.164826, elapsed=2.0min]

Entraînement:   6%|▌         | 619/10000 [01:57<29:36,  5.28step/s, loss=0.164826, elapsed=2.0min]

Entraînement:   6%|▌         | 619/10000 [01:57<29:36,  5.28step/s, loss=0.061095, elapsed=2.0min]

Entraînement:   6%|▌         | 620/10000 [01:57<29:41,  5.27step/s, loss=0.061095, elapsed=2.0min]

Entraînement:   6%|▌         | 620/10000 [01:57<29:41,  5.27step/s, loss=0.058550, elapsed=2.0min]

Entraînement:   6%|▌         | 621/10000 [01:58<29:39,  5.27step/s, loss=0.058550, elapsed=2.0min]

Entraînement:   6%|▌         | 621/10000 [01:58<29:39,  5.27step/s, loss=0.035480, elapsed=2.0min]

Entraînement:   6%|▌         | 622/10000 [01:58<29:45,  5.25step/s, loss=0.035480, elapsed=2.0min]

Entraînement:   6%|▌         | 622/10000 [01:58<29:45,  5.25step/s, loss=0.054514, elapsed=2.0min]

Entraînement:   6%|▌         | 623/10000 [01:58<29:41,  5.26step/s, loss=0.054514, elapsed=2.0min]

Entraînement:   6%|▌         | 623/10000 [01:58<29:41,  5.26step/s, loss=0.080762, elapsed=2.0min]

Entraînement:   6%|▌         | 624/10000 [01:58<29:44,  5.25step/s, loss=0.080762, elapsed=2.0min]

Entraînement:   6%|▌         | 624/10000 [01:58<29:44,  5.25step/s, loss=0.073557, elapsed=2.0min]

Entraînement:   6%|▋         | 625/10000 [01:58<29:40,  5.27step/s, loss=0.073557, elapsed=2.0min]

Entraînement:   6%|▋         | 625/10000 [01:58<29:40,  5.27step/s, loss=0.063822, elapsed=2.0min]

Entraînement:   6%|▋         | 626/10000 [01:59<29:42,  5.26step/s, loss=0.063822, elapsed=2.0min]

Entraînement:   6%|▋         | 626/10000 [01:59<29:42,  5.26step/s, loss=0.058331, elapsed=2.0min]

Entraînement:   6%|▋         | 627/10000 [01:59<29:42,  5.26step/s, loss=0.058331, elapsed=2.0min]

Entraînement:   6%|▋         | 627/10000 [01:59<29:42,  5.26step/s, loss=0.048393, elapsed=2.0min]

Entraînement:   6%|▋         | 628/10000 [01:59<29:39,  5.27step/s, loss=0.048393, elapsed=2.0min]

Entraînement:   6%|▋         | 628/10000 [01:59<29:39,  5.27step/s, loss=0.070202, elapsed=2.0min]

Entraînement:   6%|▋         | 629/10000 [01:59<29:40,  5.26step/s, loss=0.070202, elapsed=2.0min]

Entraînement:   6%|▋         | 629/10000 [01:59<29:40,  5.26step/s, loss=0.047867, elapsed=2.0min]

Entraînement:   6%|▋         | 630/10000 [01:59<29:39,  5.26step/s, loss=0.047867, elapsed=2.0min]

Entraînement:   6%|▋         | 630/10000 [01:59<29:39,  5.26step/s, loss=0.103216, elapsed=2.0min]

Entraînement:   6%|▋         | 631/10000 [02:00<29:39,  5.27step/s, loss=0.103216, elapsed=2.0min]

Entraînement:   6%|▋         | 631/10000 [02:00<29:39,  5.27step/s, loss=0.057547, elapsed=2.0min]

Entraînement:   6%|▋         | 632/10000 [02:00<29:44,  5.25step/s, loss=0.057547, elapsed=2.0min]

Entraînement:   6%|▋         | 632/10000 [02:00<29:44,  5.25step/s, loss=0.079410, elapsed=2.0min]

Entraînement:   6%|▋         | 633/10000 [02:00<29:40,  5.26step/s, loss=0.079410, elapsed=2.0min]

Entraînement:   6%|▋         | 633/10000 [02:00<29:40,  5.26step/s, loss=0.058701, elapsed=2.0min]

Entraînement:   6%|▋         | 634/10000 [02:00<29:39,  5.26step/s, loss=0.058701, elapsed=2.0min]

Entraînement:   6%|▋         | 634/10000 [02:00<29:39,  5.26step/s, loss=0.114280, elapsed=2.0min]

Entraînement:   6%|▋         | 635/10000 [02:00<29:36,  5.27step/s, loss=0.114280, elapsed=2.0min]

Entraînement:   6%|▋         | 635/10000 [02:00<29:36,  5.27step/s, loss=0.045167, elapsed=2.0min]

Entraînement:   6%|▋         | 636/10000 [02:01<29:37,  5.27step/s, loss=0.045167, elapsed=2.0min]

Entraînement:   6%|▋         | 636/10000 [02:01<29:37,  5.27step/s, loss=0.074554, elapsed=2.0min]

Entraînement:   6%|▋         | 637/10000 [02:01<29:33,  5.28step/s, loss=0.074554, elapsed=2.0min]

Entraînement:   6%|▋         | 637/10000 [02:01<29:33,  5.28step/s, loss=0.190471, elapsed=2.0min]

Entraînement:   6%|▋         | 638/10000 [02:01<29:32,  5.28step/s, loss=0.190471, elapsed=2.0min]

Entraînement:   6%|▋         | 638/10000 [02:01<29:32,  5.28step/s, loss=0.099473, elapsed=2.0min]

Entraînement:   6%|▋         | 639/10000 [02:01<29:29,  5.29step/s, loss=0.099473, elapsed=2.0min]

Entraînement:   6%|▋         | 639/10000 [02:01<29:29,  5.29step/s, loss=0.162825, elapsed=2.0min]

Entraînement:   6%|▋         | 640/10000 [02:01<29:27,  5.30step/s, loss=0.162825, elapsed=2.0min]

Entraînement:   6%|▋         | 640/10000 [02:01<29:27,  5.30step/s, loss=0.106114, elapsed=2.0min]

Entraînement:   6%|▋         | 641/10000 [02:01<29:27,  5.30step/s, loss=0.106114, elapsed=2.0min]

Entraînement:   6%|▋         | 641/10000 [02:01<29:27,  5.30step/s, loss=0.064939, elapsed=2.0min]

Entraînement:   6%|▋         | 642/10000 [02:02<29:26,  5.30step/s, loss=0.064939, elapsed=2.0min]

Entraînement:   6%|▋         | 642/10000 [02:02<29:26,  5.30step/s, loss=0.188732, elapsed=2.0min]

Entraînement:   6%|▋         | 643/10000 [02:02<29:31,  5.28step/s, loss=0.188732, elapsed=2.0min]

Entraînement:   6%|▋         | 643/10000 [02:02<29:31,  5.28step/s, loss=0.053050, elapsed=2.0min]

Entraînement:   6%|▋         | 644/10000 [02:02<29:29,  5.29step/s, loss=0.053050, elapsed=2.0min]

Entraînement:   6%|▋         | 644/10000 [02:02<29:29,  5.29step/s, loss=0.093387, elapsed=2.0min]

Entraînement:   6%|▋         | 645/10000 [02:02<29:26,  5.30step/s, loss=0.093387, elapsed=2.0min]

Entraînement:   6%|▋         | 645/10000 [02:02<29:26,  5.30step/s, loss=0.082099, elapsed=2.0min]

Entraînement:   6%|▋         | 646/10000 [02:02<29:29,  5.29step/s, loss=0.082099, elapsed=2.0min]

Entraînement:   6%|▋         | 646/10000 [02:02<29:29,  5.29step/s, loss=0.073711, elapsed=2.0min]

Entraînement:   6%|▋         | 647/10000 [02:03<29:27,  5.29step/s, loss=0.073711, elapsed=2.0min]

Entraînement:   6%|▋         | 647/10000 [02:03<29:27,  5.29step/s, loss=0.028463, elapsed=2.1min]

Entraînement:   6%|▋         | 648/10000 [02:03<29:24,  5.30step/s, loss=0.028463, elapsed=2.1min]

Entraînement:   6%|▋         | 648/10000 [02:03<29:24,  5.30step/s, loss=0.078309, elapsed=2.1min]

Entraînement:   6%|▋         | 649/10000 [02:03<29:24,  5.30step/s, loss=0.078309, elapsed=2.1min]

Entraînement:   6%|▋         | 649/10000 [02:03<29:24,  5.30step/s, loss=0.054567, elapsed=2.1min]

Entraînement:   6%|▋         | 650/10000 [02:03<29:24,  5.30step/s, loss=0.054567, elapsed=2.1min]

Entraînement:   6%|▋         | 650/10000 [02:03<29:24,  5.30step/s, loss=0.068275, elapsed=2.1min]

Entraînement:   7%|▋         | 651/10000 [02:03<29:27,  5.29step/s, loss=0.068275, elapsed=2.1min]

Entraînement:   7%|▋         | 651/10000 [02:03<29:27,  5.29step/s, loss=0.038547, elapsed=2.1min]

Entraînement:   7%|▋         | 652/10000 [02:04<29:26,  5.29step/s, loss=0.038547, elapsed=2.1min]

Entraînement:   7%|▋         | 652/10000 [02:04<29:26,  5.29step/s, loss=0.043797, elapsed=2.1min]

Entraînement:   7%|▋         | 653/10000 [02:04<29:24,  5.30step/s, loss=0.043797, elapsed=2.1min]

Entraînement:   7%|▋         | 653/10000 [02:04<29:24,  5.30step/s, loss=0.129245, elapsed=2.1min]

Entraînement:   7%|▋         | 654/10000 [02:04<29:25,  5.29step/s, loss=0.129245, elapsed=2.1min]

Entraînement:   7%|▋         | 654/10000 [02:04<29:25,  5.29step/s, loss=0.058744, elapsed=2.1min]

Entraînement:   7%|▋         | 655/10000 [02:04<29:23,  5.30step/s, loss=0.058744, elapsed=2.1min]

Entraînement:   7%|▋         | 655/10000 [02:04<29:23,  5.30step/s, loss=0.046577, elapsed=2.1min]

Entraînement:   7%|▋         | 656/10000 [02:04<29:28,  5.28step/s, loss=0.046577, elapsed=2.1min]

Entraînement:   7%|▋         | 656/10000 [02:04<29:28,  5.28step/s, loss=0.086937, elapsed=2.1min]

Entraînement:   7%|▋         | 657/10000 [02:04<29:27,  5.29step/s, loss=0.086937, elapsed=2.1min]

Entraînement:   7%|▋         | 657/10000 [02:04<29:27,  5.29step/s, loss=0.055965, elapsed=2.1min]

Entraînement:   7%|▋         | 658/10000 [02:05<29:25,  5.29step/s, loss=0.055965, elapsed=2.1min]

Entraînement:   7%|▋         | 658/10000 [02:05<29:25,  5.29step/s, loss=0.098779, elapsed=2.1min]

Entraînement:   7%|▋         | 659/10000 [02:05<29:28,  5.28step/s, loss=0.098779, elapsed=2.1min]

Entraînement:   7%|▋         | 659/10000 [02:05<29:28,  5.28step/s, loss=0.042799, elapsed=2.1min]

Entraînement:   7%|▋         | 660/10000 [02:05<29:24,  5.29step/s, loss=0.042799, elapsed=2.1min]

Entraînement:   7%|▋         | 660/10000 [02:05<29:24,  5.29step/s, loss=0.078637, elapsed=2.1min]

Entraînement:   7%|▋         | 661/10000 [02:05<29:26,  5.29step/s, loss=0.078637, elapsed=2.1min]

Entraînement:   7%|▋         | 661/10000 [02:05<29:26,  5.29step/s, loss=0.074329, elapsed=2.1min]

Entraînement:   7%|▋         | 662/10000 [02:05<29:24,  5.29step/s, loss=0.074329, elapsed=2.1min]

Entraînement:   7%|▋         | 662/10000 [02:05<29:24,  5.29step/s, loss=0.069549, elapsed=2.1min]

Entraînement:   7%|▋         | 663/10000 [02:06<29:23,  5.29step/s, loss=0.069549, elapsed=2.1min]

Entraînement:   7%|▋         | 663/10000 [02:06<29:23,  5.29step/s, loss=0.209614, elapsed=2.1min]

Entraînement:   7%|▋         | 664/10000 [02:06<29:22,  5.30step/s, loss=0.209614, elapsed=2.1min]

Entraînement:   7%|▋         | 664/10000 [02:06<29:22,  5.30step/s, loss=0.059637, elapsed=2.1min]

Entraînement:   7%|▋         | 665/10000 [02:06<29:19,  5.31step/s, loss=0.059637, elapsed=2.1min]

Entraînement:   7%|▋         | 665/10000 [02:06<29:19,  5.31step/s, loss=0.142413, elapsed=2.1min]

Entraînement:   7%|▋         | 666/10000 [02:06<29:25,  5.29step/s, loss=0.142413, elapsed=2.1min]

Entraînement:   7%|▋         | 666/10000 [02:06<29:25,  5.29step/s, loss=0.141036, elapsed=2.1min]

Entraînement:   7%|▋         | 667/10000 [02:06<29:29,  5.28step/s, loss=0.141036, elapsed=2.1min]

Entraînement:   7%|▋         | 667/10000 [02:06<29:29,  5.28step/s, loss=0.066243, elapsed=2.1min]

Entraînement:   7%|▋         | 668/10000 [02:07<29:27,  5.28step/s, loss=0.066243, elapsed=2.1min]

Entraînement:   7%|▋         | 668/10000 [02:07<29:27,  5.28step/s, loss=0.048984, elapsed=2.1min]

Entraînement:   7%|▋         | 669/10000 [02:07<29:26,  5.28step/s, loss=0.048984, elapsed=2.1min]

Entraînement:   7%|▋         | 669/10000 [02:07<29:26,  5.28step/s, loss=0.129922, elapsed=2.1min]

Entraînement:   7%|▋         | 670/10000 [02:07<29:25,  5.29step/s, loss=0.129922, elapsed=2.1min]

Entraînement:   7%|▋         | 670/10000 [02:07<29:25,  5.29step/s, loss=0.082736, elapsed=2.1min]

Entraînement:   7%|▋         | 671/10000 [02:07<29:21,  5.30step/s, loss=0.082736, elapsed=2.1min]

Entraînement:   7%|▋         | 671/10000 [02:07<29:21,  5.30step/s, loss=0.070191, elapsed=2.1min]

Entraînement:   7%|▋         | 672/10000 [02:07<29:21,  5.29step/s, loss=0.070191, elapsed=2.1min]

Entraînement:   7%|▋         | 672/10000 [02:07<29:21,  5.29step/s, loss=0.214173, elapsed=2.1min]

Entraînement:   7%|▋         | 673/10000 [02:08<29:20,  5.30step/s, loss=0.214173, elapsed=2.1min]

Entraînement:   7%|▋         | 673/10000 [02:08<29:20,  5.30step/s, loss=0.133870, elapsed=2.1min]

Entraînement:   7%|▋         | 674/10000 [02:08<29:19,  5.30step/s, loss=0.133870, elapsed=2.1min]

Entraînement:   7%|▋         | 674/10000 [02:08<29:19,  5.30step/s, loss=0.059982, elapsed=2.1min]

Entraînement:   7%|▋         | 675/10000 [02:08<29:24,  5.29step/s, loss=0.059982, elapsed=2.1min]

Entraînement:   7%|▋         | 675/10000 [02:08<29:24,  5.29step/s, loss=0.145763, elapsed=2.1min]

Entraînement:   7%|▋         | 676/10000 [02:08<29:21,  5.29step/s, loss=0.145763, elapsed=2.1min]

Entraînement:   7%|▋         | 676/10000 [02:08<29:21,  5.29step/s, loss=0.063510, elapsed=2.1min]

Entraînement:   7%|▋         | 677/10000 [02:08<29:23,  5.29step/s, loss=0.063510, elapsed=2.1min]

Entraînement:   7%|▋         | 677/10000 [02:08<29:23,  5.29step/s, loss=0.114163, elapsed=2.1min]

Entraînement:   7%|▋         | 678/10000 [02:08<29:21,  5.29step/s, loss=0.114163, elapsed=2.1min]

Entraînement:   7%|▋         | 678/10000 [02:08<29:21,  5.29step/s, loss=0.050479, elapsed=2.1min]

Entraînement:   7%|▋         | 679/10000 [02:09<29:25,  5.28step/s, loss=0.050479, elapsed=2.1min]

Entraînement:   7%|▋         | 679/10000 [02:09<29:25,  5.28step/s, loss=0.055285, elapsed=2.2min]

Entraînement:   7%|▋         | 680/10000 [02:09<29:22,  5.29step/s, loss=0.055285, elapsed=2.2min]

Entraînement:   7%|▋         | 680/10000 [02:09<29:22,  5.29step/s, loss=0.059681, elapsed=2.2min]

Entraînement:   7%|▋         | 681/10000 [02:09<29:19,  5.30step/s, loss=0.059681, elapsed=2.2min]

Entraînement:   7%|▋         | 681/10000 [02:09<29:19,  5.30step/s, loss=0.141408, elapsed=2.2min]

Entraînement:   7%|▋         | 682/10000 [02:09<29:18,  5.30step/s, loss=0.141408, elapsed=2.2min]

Entraînement:   7%|▋         | 682/10000 [02:09<29:18,  5.30step/s, loss=0.047122, elapsed=2.2min]

Entraînement:   7%|▋         | 683/10000 [02:09<29:20,  5.29step/s, loss=0.047122, elapsed=2.2min]

Entraînement:   7%|▋         | 683/10000 [02:09<29:20,  5.29step/s, loss=0.065696, elapsed=2.2min]

Entraînement:   7%|▋         | 684/10000 [02:10<29:22,  5.29step/s, loss=0.065696, elapsed=2.2min]

Entraînement:   7%|▋         | 684/10000 [02:10<29:22,  5.29step/s, loss=0.179232, elapsed=2.2min]

Entraînement:   7%|▋         | 685/10000 [02:10<29:21,  5.29step/s, loss=0.179232, elapsed=2.2min]

Entraînement:   7%|▋         | 685/10000 [02:10<29:21,  5.29step/s, loss=0.151901, elapsed=2.2min]

Entraînement:   7%|▋         | 686/10000 [02:10<29:22,  5.29step/s, loss=0.151901, elapsed=2.2min]

Entraînement:   7%|▋         | 686/10000 [02:10<29:22,  5.29step/s, loss=0.047461, elapsed=2.2min]

Entraînement:   7%|▋         | 687/10000 [02:10<29:22,  5.28step/s, loss=0.047461, elapsed=2.2min]

Entraînement:   7%|▋         | 687/10000 [02:10<29:22,  5.28step/s, loss=0.060816, elapsed=2.2min]

Entraînement:   7%|▋         | 688/10000 [02:10<29:19,  5.29step/s, loss=0.060816, elapsed=2.2min]

Entraînement:   7%|▋         | 688/10000 [02:10<29:19,  5.29step/s, loss=0.118910, elapsed=2.2min]

Entraînement:   7%|▋         | 689/10000 [02:11<29:20,  5.29step/s, loss=0.118910, elapsed=2.2min]

Entraînement:   7%|▋         | 689/10000 [02:11<29:20,  5.29step/s, loss=0.045742, elapsed=2.2min]

Entraînement:   7%|▋         | 690/10000 [02:11<29:21,  5.29step/s, loss=0.045742, elapsed=2.2min]

Entraînement:   7%|▋         | 690/10000 [02:11<29:21,  5.29step/s, loss=0.051684, elapsed=2.2min]

Entraînement:   7%|▋         | 691/10000 [02:11<29:21,  5.28step/s, loss=0.051684, elapsed=2.2min]

Entraînement:   7%|▋         | 691/10000 [02:11<29:21,  5.28step/s, loss=0.070224, elapsed=2.2min]

Entraînement:   7%|▋         | 692/10000 [02:11<29:25,  5.27step/s, loss=0.070224, elapsed=2.2min]

Entraînement:   7%|▋         | 692/10000 [02:11<29:25,  5.27step/s, loss=0.079667, elapsed=2.2min]

Entraînement:   7%|▋         | 693/10000 [02:11<29:22,  5.28step/s, loss=0.079667, elapsed=2.2min]

Entraînement:   7%|▋         | 693/10000 [02:11<29:22,  5.28step/s, loss=0.077779, elapsed=2.2min]

Entraînement:   7%|▋         | 694/10000 [02:11<29:15,  5.30step/s, loss=0.077779, elapsed=2.2min]

Entraînement:   7%|▋         | 694/10000 [02:11<29:15,  5.30step/s, loss=0.164701, elapsed=2.2min]

Entraînement:   7%|▋         | 695/10000 [02:12<29:16,  5.30step/s, loss=0.164701, elapsed=2.2min]

Entraînement:   7%|▋         | 695/10000 [02:12<29:16,  5.30step/s, loss=0.104424, elapsed=2.2min]

Entraînement:   7%|▋         | 696/10000 [02:12<29:15,  5.30step/s, loss=0.104424, elapsed=2.2min]

Entraînement:   7%|▋         | 696/10000 [02:12<29:15,  5.30step/s, loss=0.039306, elapsed=2.2min]

Entraînement:   7%|▋         | 697/10000 [02:12<29:13,  5.30step/s, loss=0.039306, elapsed=2.2min]

Entraînement:   7%|▋         | 697/10000 [02:12<29:13,  5.30step/s, loss=0.107608, elapsed=2.2min]

Entraînement:   7%|▋         | 698/10000 [02:12<29:15,  5.30step/s, loss=0.107608, elapsed=2.2min]

Entraînement:   7%|▋         | 698/10000 [02:12<29:15,  5.30step/s, loss=0.043247, elapsed=2.2min]

Entraînement:   7%|▋         | 699/10000 [02:12<29:16,  5.30step/s, loss=0.043247, elapsed=2.2min]

Entraînement:   7%|▋         | 699/10000 [02:12<29:16,  5.30step/s, loss=0.090845, elapsed=2.2min]

Entraînement:   7%|▋         | 700/10000 [02:13<29:19,  5.28step/s, loss=0.090845, elapsed=2.2min]

Entraînement:   7%|▋         | 700/10000 [02:13<29:19,  5.28step/s, loss=0.059295, elapsed=2.2min]

Entraînement:   7%|▋         | 700/10000 [02:13<29:19,  5.28step/s, loss=0.059295, elapsed=2.2min]

Entraînement:   7%|▋         | 701/10000 [02:13<29:42,  5.22step/s, loss=0.059295, elapsed=2.2min]

Entraînement:   7%|▋         | 701/10000 [02:13<29:42,  5.22step/s, loss=0.071900, elapsed=2.2min]

Step 700/10000 | Train loss: 0.059295 | Elapsed: 2.2min | ETA: 29.5min

Entraînement:   7%|▋         | 702/10000 [02:13<29:37,  5.23step/s, loss=0.071900, elapsed=2.2min]

Entraînement:   7%|▋         | 702/10000 [02:13<29:37,  5.23step/s, loss=0.067902, elapsed=2.2min]

Entraînement:   7%|▋         | 703/10000 [02:13<29:33,  5.24step/s, loss=0.067902, elapsed=2.2min]

Entraînement:   7%|▋         | 703/10000 [02:13<29:33,  5.24step/s, loss=0.103879, elapsed=2.2min]

Entraînement:   7%|▋         | 704/10000 [02:13<29:29,  5.25step/s, loss=0.103879, elapsed=2.2min]

Entraînement:   7%|▋         | 704/10000 [02:13<29:29,  5.25step/s, loss=0.057817, elapsed=2.2min]

Entraînement:   7%|▋         | 705/10000 [02:14<29:22,  5.27step/s, loss=0.057817, elapsed=2.2min]

Entraînement:   7%|▋         | 705/10000 [02:14<29:22,  5.27step/s, loss=0.045922, elapsed=2.2min]

Entraînement:   7%|▋         | 706/10000 [02:14<29:29,  5.25step/s, loss=0.045922, elapsed=2.2min]

Entraînement:   7%|▋         | 706/10000 [02:14<29:29,  5.25step/s, loss=0.057848, elapsed=2.2min]

Entraînement:   7%|▋         | 707/10000 [02:14<29:26,  5.26step/s, loss=0.057848, elapsed=2.2min]

Entraînement:   7%|▋         | 707/10000 [02:14<29:26,  5.26step/s, loss=0.091398, elapsed=2.2min]

Entraînement:   7%|▋         | 708/10000 [02:14<29:30,  5.25step/s, loss=0.091398, elapsed=2.2min]

Entraînement:   7%|▋         | 708/10000 [02:14<29:30,  5.25step/s, loss=0.056467, elapsed=2.2min]

Entraînement:   7%|▋         | 709/10000 [02:14<29:26,  5.26step/s, loss=0.056467, elapsed=2.2min]

Entraînement:   7%|▋         | 709/10000 [02:14<29:26,  5.26step/s, loss=0.042285, elapsed=2.2min]

Entraînement:   7%|▋         | 710/10000 [02:15<29:25,  5.26step/s, loss=0.042285, elapsed=2.2min]

Entraînement:   7%|▋         | 710/10000 [02:15<29:25,  5.26step/s, loss=0.110171, elapsed=2.3min]

Entraînement:   7%|▋         | 711/10000 [02:15<29:25,  5.26step/s, loss=0.110171, elapsed=2.3min]

Entraînement:   7%|▋         | 711/10000 [02:15<29:25,  5.26step/s, loss=0.046389, elapsed=2.3min]

Entraînement:   7%|▋         | 712/10000 [02:15<29:19,  5.28step/s, loss=0.046389, elapsed=2.3min]

Entraînement:   7%|▋         | 712/10000 [02:15<29:19,  5.28step/s, loss=0.048784, elapsed=2.3min]

Entraînement:   7%|▋         | 713/10000 [02:15<29:18,  5.28step/s, loss=0.048784, elapsed=2.3min]

Entraînement:   7%|▋         | 713/10000 [02:15<29:18,  5.28step/s, loss=0.046698, elapsed=2.3min]

Entraînement:   7%|▋         | 714/10000 [02:15<29:17,  5.28step/s, loss=0.046698, elapsed=2.3min]

Entraînement:   7%|▋         | 714/10000 [02:15<29:17,  5.28step/s, loss=0.249765, elapsed=2.3min]

Entraînement:   7%|▋         | 715/10000 [02:15<29:20,  5.27step/s, loss=0.249765, elapsed=2.3min]

Entraînement:   7%|▋         | 715/10000 [02:15<29:20,  5.27step/s, loss=0.054423, elapsed=2.3min]

Entraînement:   7%|▋         | 716/10000 [02:16<29:19,  5.28step/s, loss=0.054423, elapsed=2.3min]

Entraînement:   7%|▋         | 716/10000 [02:16<29:19,  5.28step/s, loss=0.039307, elapsed=2.3min]

Entraînement:   7%|▋         | 717/10000 [02:16<29:18,  5.28step/s, loss=0.039307, elapsed=2.3min]

Entraînement:   7%|▋         | 717/10000 [02:16<29:18,  5.28step/s, loss=0.089894, elapsed=2.3min]

Entraînement:   7%|▋         | 718/10000 [02:16<29:19,  5.27step/s, loss=0.089894, elapsed=2.3min]

Entraînement:   7%|▋         | 718/10000 [02:16<29:19,  5.27step/s, loss=0.200352, elapsed=2.3min]

Entraînement:   7%|▋         | 719/10000 [02:16<29:17,  5.28step/s, loss=0.200352, elapsed=2.3min]

Entraînement:   7%|▋         | 719/10000 [02:16<29:17,  5.28step/s, loss=0.050605, elapsed=2.3min]

Entraînement:   7%|▋         | 720/10000 [02:16<29:17,  5.28step/s, loss=0.050605, elapsed=2.3min]

Entraînement:   7%|▋         | 720/10000 [02:16<29:17,  5.28step/s, loss=0.105434, elapsed=2.3min]

Entraînement:   7%|▋         | 721/10000 [02:17<29:17,  5.28step/s, loss=0.105434, elapsed=2.3min]

Entraînement:   7%|▋         | 721/10000 [02:17<29:17,  5.28step/s, loss=0.216619, elapsed=2.3min]

Entraînement:   7%|▋         | 722/10000 [02:17<29:18,  5.28step/s, loss=0.216619, elapsed=2.3min]

Entraînement:   7%|▋         | 722/10000 [02:17<29:18,  5.28step/s, loss=0.042340, elapsed=2.3min]

Entraînement:   7%|▋         | 723/10000 [02:17<29:17,  5.28step/s, loss=0.042340, elapsed=2.3min]

Entraînement:   7%|▋         | 723/10000 [02:17<29:17,  5.28step/s, loss=0.046488, elapsed=2.3min]

Entraînement:   7%|▋         | 724/10000 [02:17<29:13,  5.29step/s, loss=0.046488, elapsed=2.3min]

Entraînement:   7%|▋         | 724/10000 [02:17<29:13,  5.29step/s, loss=0.079778, elapsed=2.3min]

Entraînement:   7%|▋         | 725/10000 [02:17<29:14,  5.29step/s, loss=0.079778, elapsed=2.3min]

Entraînement:   7%|▋         | 725/10000 [02:17<29:14,  5.29step/s, loss=0.062164, elapsed=2.3min]

Entraînement:   7%|▋         | 726/10000 [02:18<29:14,  5.29step/s, loss=0.062164, elapsed=2.3min]

Entraînement:   7%|▋         | 726/10000 [02:18<29:14,  5.29step/s, loss=0.053275, elapsed=2.3min]

Entraînement:   7%|▋         | 727/10000 [02:18<29:14,  5.29step/s, loss=0.053275, elapsed=2.3min]

Entraînement:   7%|▋         | 727/10000 [02:18<29:14,  5.29step/s, loss=0.082169, elapsed=2.3min]

Entraînement:   7%|▋         | 728/10000 [02:18<29:12,  5.29step/s, loss=0.082169, elapsed=2.3min]

Entraînement:   7%|▋         | 728/10000 [02:18<29:12,  5.29step/s, loss=0.064609, elapsed=2.3min]

Entraînement:   7%|▋         | 729/10000 [02:18<29:14,  5.29step/s, loss=0.064609, elapsed=2.3min]

Entraînement:   7%|▋         | 729/10000 [02:18<29:14,  5.29step/s, loss=0.159210, elapsed=2.3min]

Entraînement:   7%|▋         | 730/10000 [02:18<29:17,  5.27step/s, loss=0.159210, elapsed=2.3min]

Entraînement:   7%|▋         | 730/10000 [02:18<29:17,  5.27step/s, loss=0.049151, elapsed=2.3min]

Entraînement:   7%|▋         | 731/10000 [02:18<29:19,  5.27step/s, loss=0.049151, elapsed=2.3min]

Entraînement:   7%|▋         | 731/10000 [02:18<29:19,  5.27step/s, loss=0.045522, elapsed=2.3min]

Entraînement:   7%|▋         | 732/10000 [02:19<29:20,  5.27step/s, loss=0.045522, elapsed=2.3min]

Entraînement:   7%|▋         | 732/10000 [02:19<29:20,  5.27step/s, loss=0.041028, elapsed=2.3min]

Entraînement:   7%|▋         | 733/10000 [02:19<29:14,  5.28step/s, loss=0.041028, elapsed=2.3min]

Entraînement:   7%|▋         | 733/10000 [02:19<29:14,  5.28step/s, loss=0.161166, elapsed=2.3min]

Entraînement:   7%|▋         | 734/10000 [02:19<29:14,  5.28step/s, loss=0.161166, elapsed=2.3min]

Entraînement:   7%|▋         | 734/10000 [02:19<29:14,  5.28step/s, loss=0.066981, elapsed=2.3min]

Entraînement:   7%|▋         | 735/10000 [02:19<29:13,  5.28step/s, loss=0.066981, elapsed=2.3min]

Entraînement:   7%|▋         | 735/10000 [02:19<29:13,  5.28step/s, loss=0.048668, elapsed=2.3min]

Entraînement:   7%|▋         | 736/10000 [02:19<29:11,  5.29step/s, loss=0.048668, elapsed=2.3min]

Entraînement:   7%|▋         | 736/10000 [02:19<29:11,  5.29step/s, loss=0.041476, elapsed=2.3min]

Entraînement:   7%|▋         | 737/10000 [02:20<29:15,  5.28step/s, loss=0.041476, elapsed=2.3min]

Entraînement:   7%|▋         | 737/10000 [02:20<29:15,  5.28step/s, loss=0.095537, elapsed=2.3min]

Entraînement:   7%|▋         | 738/10000 [02:20<29:15,  5.28step/s, loss=0.095537, elapsed=2.3min]

Entraînement:   7%|▋         | 738/10000 [02:20<29:15,  5.28step/s, loss=0.082007, elapsed=2.3min]

Entraînement:   7%|▋         | 739/10000 [02:20<29:20,  5.26step/s, loss=0.082007, elapsed=2.3min]

Entraînement:   7%|▋         | 739/10000 [02:20<29:20,  5.26step/s, loss=0.071896, elapsed=2.3min]

Entraînement:   7%|▋         | 740/10000 [02:20<29:17,  5.27step/s, loss=0.071896, elapsed=2.3min]

Entraînement:   7%|▋         | 740/10000 [02:20<29:17,  5.27step/s, loss=0.052592, elapsed=2.3min]

Entraînement:   7%|▋         | 741/10000 [02:20<29:17,  5.27step/s, loss=0.052592, elapsed=2.3min]

Entraînement:   7%|▋         | 741/10000 [02:20<29:17,  5.27step/s, loss=0.042160, elapsed=2.3min]

Entraînement:   7%|▋         | 742/10000 [02:21<29:13,  5.28step/s, loss=0.042160, elapsed=2.3min]

Entraînement:   7%|▋         | 742/10000 [02:21<29:13,  5.28step/s, loss=0.054332, elapsed=2.4min]

Entraînement:   7%|▋         | 743/10000 [02:21<29:09,  5.29step/s, loss=0.054332, elapsed=2.4min]

Entraînement:   7%|▋         | 743/10000 [02:21<29:09,  5.29step/s, loss=0.059473, elapsed=2.4min]

Entraînement:   7%|▋         | 744/10000 [02:21<29:10,  5.29step/s, loss=0.059473, elapsed=2.4min]

Entraînement:   7%|▋         | 744/10000 [02:21<29:10,  5.29step/s, loss=0.105314, elapsed=2.4min]

Entraînement:   7%|▋         | 745/10000 [02:21<29:11,  5.28step/s, loss=0.105314, elapsed=2.4min]

Entraînement:   7%|▋         | 745/10000 [02:21<29:11,  5.28step/s, loss=0.082467, elapsed=2.4min]

Entraînement:   7%|▋         | 746/10000 [02:21<29:13,  5.28step/s, loss=0.082467, elapsed=2.4min]

Entraînement:   7%|▋         | 746/10000 [02:21<29:13,  5.28step/s, loss=0.080923, elapsed=2.4min]

Entraînement:   7%|▋         | 747/10000 [02:22<29:11,  5.28step/s, loss=0.080923, elapsed=2.4min]

Entraînement:   7%|▋         | 747/10000 [02:22<29:11,  5.28step/s, loss=0.105195, elapsed=2.4min]

Entraînement:   7%|▋         | 748/10000 [02:22<29:11,  5.28step/s, loss=0.105195, elapsed=2.4min]

Entraînement:   7%|▋         | 748/10000 [02:22<29:11,  5.28step/s, loss=0.065593, elapsed=2.4min]

Entraînement:   7%|▋         | 749/10000 [02:22<29:10,  5.28step/s, loss=0.065593, elapsed=2.4min]

Entraînement:   7%|▋         | 749/10000 [02:22<29:10,  5.28step/s, loss=0.056051, elapsed=2.4min]

Entraînement:   8%|▊         | 750/10000 [02:22<29:11,  5.28step/s, loss=0.056051, elapsed=2.4min]

Entraînement:   8%|▊         | 750/10000 [02:22<29:11,  5.28step/s, loss=0.133532, elapsed=2.4min]

Entraînement:   8%|▊         | 751/10000 [02:22<29:44,  5.18step/s, loss=0.133532, elapsed=2.4min]

Entraînement:   8%|▊         | 751/10000 [02:22<29:44,  5.18step/s, loss=0.067996, elapsed=2.4min]

Entraînement:   8%|▊         | 752/10000 [02:22<29:35,  5.21step/s, loss=0.067996, elapsed=2.4min]

Entraînement:   8%|▊         | 752/10000 [02:22<29:35,  5.21step/s, loss=0.054374, elapsed=2.4min]

Entraînement:   8%|▊         | 753/10000 [02:23<29:24,  5.24step/s, loss=0.054374, elapsed=2.4min]

Entraînement:   8%|▊         | 753/10000 [02:23<29:24,  5.24step/s, loss=0.126786, elapsed=2.4min]

Entraînement:   8%|▊         | 754/10000 [02:23<29:22,  5.25step/s, loss=0.126786, elapsed=2.4min]

Entraînement:   8%|▊         | 754/10000 [02:23<29:22,  5.25step/s, loss=0.103369, elapsed=2.4min]

Entraînement:   8%|▊         | 755/10000 [02:23<29:17,  5.26step/s, loss=0.103369, elapsed=2.4min]

Entraînement:   8%|▊         | 755/10000 [02:23<29:17,  5.26step/s, loss=0.046012, elapsed=2.4min]

Entraînement:   8%|▊         | 756/10000 [02:23<29:14,  5.27step/s, loss=0.046012, elapsed=2.4min]

Entraînement:   8%|▊         | 756/10000 [02:23<29:14,  5.27step/s, loss=0.097644, elapsed=2.4min]

Entraînement:   8%|▊         | 757/10000 [02:23<29:12,  5.27step/s, loss=0.097644, elapsed=2.4min]

Entraînement:   8%|▊         | 757/10000 [02:23<29:12,  5.27step/s, loss=0.064305, elapsed=2.4min]

Entraînement:   8%|▊         | 758/10000 [02:24<29:09,  5.28step/s, loss=0.064305, elapsed=2.4min]

Entraînement:   8%|▊         | 758/10000 [02:24<29:09,  5.28step/s, loss=0.090017, elapsed=2.4min]

Entraînement:   8%|▊         | 759/10000 [02:24<29:13,  5.27step/s, loss=0.090017, elapsed=2.4min]

Entraînement:   8%|▊         | 759/10000 [02:24<29:13,  5.27step/s, loss=0.088816, elapsed=2.4min]

Entraînement:   8%|▊         | 760/10000 [02:24<29:18,  5.25step/s, loss=0.088816, elapsed=2.4min]

Entraînement:   8%|▊         | 760/10000 [02:24<29:18,  5.25step/s, loss=0.059074, elapsed=2.4min]

Entraînement:   8%|▊         | 761/10000 [02:24<29:24,  5.24step/s, loss=0.059074, elapsed=2.4min]

Entraînement:   8%|▊         | 761/10000 [02:24<29:24,  5.24step/s, loss=0.099514, elapsed=2.4min]

Entraînement:   8%|▊         | 762/10000 [02:24<29:24,  5.24step/s, loss=0.099514, elapsed=2.4min]

Entraînement:   8%|▊         | 762/10000 [02:24<29:24,  5.24step/s, loss=0.191501, elapsed=2.4min]

Entraînement:   8%|▊         | 763/10000 [02:25<29:10,  5.28step/s, loss=0.191501, elapsed=2.4min]

Entraînement:   8%|▊         | 763/10000 [02:25<29:10,  5.28step/s, loss=0.048282, elapsed=2.4min]

Entraînement:   8%|▊         | 764/10000 [02:25<29:12,  5.27step/s, loss=0.048282, elapsed=2.4min]

Entraînement:   8%|▊         | 764/10000 [02:25<29:12,  5.27step/s, loss=0.063065, elapsed=2.4min]

Entraînement:   8%|▊         | 765/10000 [02:25<29:07,  5.29step/s, loss=0.063065, elapsed=2.4min]

Entraînement:   8%|▊         | 765/10000 [02:25<29:07,  5.29step/s, loss=0.040148, elapsed=2.4min]

Entraînement:   8%|▊         | 766/10000 [02:25<29:05,  5.29step/s, loss=0.040148, elapsed=2.4min]

Entraînement:   8%|▊         | 766/10000 [02:25<29:05,  5.29step/s, loss=0.073077, elapsed=2.4min]

Entraînement:   8%|▊         | 767/10000 [02:25<29:04,  5.29step/s, loss=0.073077, elapsed=2.4min]

Entraînement:   8%|▊         | 767/10000 [02:25<29:04,  5.29step/s, loss=0.072623, elapsed=2.4min]

Entraînement:   8%|▊         | 768/10000 [02:26<29:01,  5.30step/s, loss=0.072623, elapsed=2.4min]

Entraînement:   8%|▊         | 768/10000 [02:26<29:01,  5.30step/s, loss=0.172775, elapsed=2.4min]

Entraînement:   8%|▊         | 769/10000 [02:26<29:02,  5.30step/s, loss=0.172775, elapsed=2.4min]

Entraînement:   8%|▊         | 769/10000 [02:26<29:02,  5.30step/s, loss=0.068208, elapsed=2.4min]

Entraînement:   8%|▊         | 770/10000 [02:26<29:04,  5.29step/s, loss=0.068208, elapsed=2.4min]

Entraînement:   8%|▊         | 770/10000 [02:26<29:04,  5.29step/s, loss=0.102100, elapsed=2.4min]

Entraînement:   8%|▊         | 771/10000 [02:26<29:08,  5.28step/s, loss=0.102100, elapsed=2.4min]

Entraînement:   8%|▊         | 771/10000 [02:26<29:08,  5.28step/s, loss=0.129315, elapsed=2.4min]

Entraînement:   8%|▊         | 772/10000 [02:26<29:05,  5.29step/s, loss=0.129315, elapsed=2.4min]

Entraînement:   8%|▊         | 772/10000 [02:26<29:05,  5.29step/s, loss=0.053314, elapsed=2.4min]

Entraînement:   8%|▊         | 773/10000 [02:26<29:02,  5.30step/s, loss=0.053314, elapsed=2.4min]

Entraînement:   8%|▊         | 773/10000 [02:26<29:02,  5.30step/s, loss=0.056034, elapsed=2.4min]

Entraînement:   8%|▊         | 774/10000 [02:27<29:04,  5.29step/s, loss=0.056034, elapsed=2.4min]

Entraînement:   8%|▊         | 774/10000 [02:27<29:04,  5.29step/s, loss=0.101104, elapsed=2.5min]

Entraînement:   8%|▊         | 775/10000 [02:27<29:03,  5.29step/s, loss=0.101104, elapsed=2.5min]

Entraînement:   8%|▊         | 775/10000 [02:27<29:03,  5.29step/s, loss=0.096716, elapsed=2.5min]

Entraînement:   8%|▊         | 776/10000 [02:27<29:08,  5.27step/s, loss=0.096716, elapsed=2.5min]

Entraînement:   8%|▊         | 776/10000 [02:27<29:08,  5.27step/s, loss=0.128408, elapsed=2.5min]

Entraînement:   8%|▊         | 777/10000 [02:27<29:06,  5.28step/s, loss=0.128408, elapsed=2.5min]

Entraînement:   8%|▊         | 777/10000 [02:27<29:06,  5.28step/s, loss=0.170677, elapsed=2.5min]

Entraînement:   8%|▊         | 778/10000 [02:27<29:10,  5.27step/s, loss=0.170677, elapsed=2.5min]

Entraînement:   8%|▊         | 778/10000 [02:27<29:10,  5.27step/s, loss=0.084476, elapsed=2.5min]

Entraînement:   8%|▊         | 779/10000 [02:28<29:09,  5.27step/s, loss=0.084476, elapsed=2.5min]

Entraînement:   8%|▊         | 779/10000 [02:28<29:09,  5.27step/s, loss=0.113203, elapsed=2.5min]

Entraînement:   8%|▊         | 780/10000 [02:28<29:08,  5.27step/s, loss=0.113203, elapsed=2.5min]

Entraînement:   8%|▊         | 780/10000 [02:28<29:08,  5.27step/s, loss=0.077905, elapsed=2.5min]

Entraînement:   8%|▊         | 781/10000 [02:28<29:09,  5.27step/s, loss=0.077905, elapsed=2.5min]

Entraînement:   8%|▊         | 781/10000 [02:28<29:09,  5.27step/s, loss=0.069276, elapsed=2.5min]

Entraînement:   8%|▊         | 782/10000 [02:28<29:08,  5.27step/s, loss=0.069276, elapsed=2.5min]

Entraînement:   8%|▊         | 782/10000 [02:28<29:08,  5.27step/s, loss=0.060067, elapsed=2.5min]

Entraînement:   8%|▊         | 783/10000 [02:28<29:11,  5.26step/s, loss=0.060067, elapsed=2.5min]

Entraînement:   8%|▊         | 783/10000 [02:28<29:11,  5.26step/s, loss=0.056950, elapsed=2.5min]

Entraînement:   8%|▊         | 784/10000 [02:29<29:12,  5.26step/s, loss=0.056950, elapsed=2.5min]

Entraînement:   8%|▊         | 784/10000 [02:29<29:12,  5.26step/s, loss=0.074994, elapsed=2.5min]

Entraînement:   8%|▊         | 785/10000 [02:29<29:13,  5.25step/s, loss=0.074994, elapsed=2.5min]

Entraînement:   8%|▊         | 785/10000 [02:29<29:13,  5.25step/s, loss=0.068302, elapsed=2.5min]

Entraînement:   8%|▊         | 786/10000 [02:29<29:11,  5.26step/s, loss=0.068302, elapsed=2.5min]

Entraînement:   8%|▊         | 786/10000 [02:29<29:11,  5.26step/s, loss=0.067486, elapsed=2.5min]

Entraînement:   8%|▊         | 787/10000 [02:29<29:11,  5.26step/s, loss=0.067486, elapsed=2.5min]

Entraînement:   8%|▊         | 787/10000 [02:29<29:11,  5.26step/s, loss=0.063295, elapsed=2.5min]

Entraînement:   8%|▊         | 788/10000 [02:29<29:09,  5.27step/s, loss=0.063295, elapsed=2.5min]

Entraînement:   8%|▊         | 788/10000 [02:29<29:09,  5.27step/s, loss=0.071526, elapsed=2.5min]

Entraînement:   8%|▊         | 789/10000 [02:29<29:06,  5.27step/s, loss=0.071526, elapsed=2.5min]

Entraînement:   8%|▊         | 789/10000 [02:29<29:06,  5.27step/s, loss=0.073171, elapsed=2.5min]

Entraînement:   8%|▊         | 790/10000 [02:30<29:07,  5.27step/s, loss=0.073171, elapsed=2.5min]

Entraînement:   8%|▊         | 790/10000 [02:30<29:07,  5.27step/s, loss=0.057984, elapsed=2.5min]

Entraînement:   8%|▊         | 791/10000 [02:30<29:05,  5.28step/s, loss=0.057984, elapsed=2.5min]

Entraînement:   8%|▊         | 791/10000 [02:30<29:05,  5.28step/s, loss=0.062498, elapsed=2.5min]

Entraînement:   8%|▊         | 792/10000 [02:30<29:05,  5.28step/s, loss=0.062498, elapsed=2.5min]

Entraînement:   8%|▊         | 792/10000 [02:30<29:05,  5.28step/s, loss=0.036614, elapsed=2.5min]

Entraînement:   8%|▊         | 793/10000 [02:30<29:03,  5.28step/s, loss=0.036614, elapsed=2.5min]

Entraînement:   8%|▊         | 793/10000 [02:30<29:03,  5.28step/s, loss=0.073863, elapsed=2.5min]

Entraînement:   8%|▊         | 794/10000 [02:30<29:04,  5.28step/s, loss=0.073863, elapsed=2.5min]

Entraînement:   8%|▊         | 794/10000 [02:30<29:04,  5.28step/s, loss=0.061927, elapsed=2.5min]

Entraînement:   8%|▊         | 795/10000 [02:31<29:02,  5.28step/s, loss=0.061927, elapsed=2.5min]

Entraînement:   8%|▊         | 795/10000 [02:31<29:02,  5.28step/s, loss=0.050762, elapsed=2.5min]

Entraînement:   8%|▊         | 796/10000 [02:31<29:11,  5.26step/s, loss=0.050762, elapsed=2.5min]

Entraînement:   8%|▊         | 796/10000 [02:31<29:11,  5.26step/s, loss=0.154434, elapsed=2.5min]

Entraînement:   8%|▊         | 797/10000 [02:31<29:10,  5.26step/s, loss=0.154434, elapsed=2.5min]

Entraînement:   8%|▊         | 797/10000 [02:31<29:10,  5.26step/s, loss=0.058277, elapsed=2.5min]

Entraînement:   8%|▊         | 798/10000 [02:31<29:16,  5.24step/s, loss=0.058277, elapsed=2.5min]

Entraînement:   8%|▊         | 798/10000 [02:31<29:16,  5.24step/s, loss=0.154045, elapsed=2.5min]

Entraînement:   8%|▊         | 799/10000 [02:31<29:17,  5.24step/s, loss=0.154045, elapsed=2.5min]

Entraînement:   8%|▊         | 799/10000 [02:31<29:17,  5.24step/s, loss=0.045640, elapsed=2.5min]

Entraînement:   8%|▊         | 800/10000 [02:32<29:18,  5.23step/s, loss=0.045640, elapsed=2.5min]

Entraînement:   8%|▊         | 800/10000 [02:32<29:18,  5.23step/s, loss=0.125223, elapsed=2.5min]

Entraînement:   8%|▊         | 800/10000 [02:32<29:18,  5.23step/s, loss=0.125223, elapsed=2.5min]

Entraînement:   8%|▊         | 801/10000 [02:32<29:40,  5.17step/s, loss=0.125223, elapsed=2.5min]

Entraînement:   8%|▊         | 801/10000 [02:32<29:40,  5.17step/s, loss=0.043826, elapsed=2.5min]

Step 800/10000 | Train loss: 0.125223 | Elapsed: 2.5min | ETA: 29.2min

Entraînement:   8%|▊         | 802/10000 [02:32<29:37,  5.17step/s, loss=0.043826, elapsed=2.5min]

Entraînement:   8%|▊         | 802/10000 [02:32<29:37,  5.17step/s, loss=0.068695, elapsed=2.5min]

Entraînement:   8%|▊         | 803/10000 [02:32<29:30,  5.19step/s, loss=0.068695, elapsed=2.5min]

Entraînement:   8%|▊         | 803/10000 [02:32<29:30,  5.19step/s, loss=0.052704, elapsed=2.5min]

Entraînement:   8%|▊         | 804/10000 [02:32<29:32,  5.19step/s, loss=0.052704, elapsed=2.5min]

Entraînement:   8%|▊         | 804/10000 [02:32<29:32,  5.19step/s, loss=0.045345, elapsed=2.5min]

Entraînement:   8%|▊         | 805/10000 [02:33<29:32,  5.19step/s, loss=0.045345, elapsed=2.5min]

Entraînement:   8%|▊         | 805/10000 [02:33<29:32,  5.19step/s, loss=0.060286, elapsed=2.6min]

Entraînement:   8%|▊         | 806/10000 [02:33<29:29,  5.20step/s, loss=0.060286, elapsed=2.6min]

Entraînement:   8%|▊         | 806/10000 [02:33<29:29,  5.20step/s, loss=0.053148, elapsed=2.6min]

Entraînement:   8%|▊         | 807/10000 [02:33<29:29,  5.20step/s, loss=0.053148, elapsed=2.6min]

Entraînement:   8%|▊         | 807/10000 [02:33<29:29,  5.20step/s, loss=0.083723, elapsed=2.6min]

Entraînement:   8%|▊         | 808/10000 [02:33<29:24,  5.21step/s, loss=0.083723, elapsed=2.6min]

Entraînement:   8%|▊         | 808/10000 [02:33<29:24,  5.21step/s, loss=0.091741, elapsed=2.6min]

Entraînement:   8%|▊         | 809/10000 [02:33<29:24,  5.21step/s, loss=0.091741, elapsed=2.6min]

Entraînement:   8%|▊         | 809/10000 [02:33<29:24,  5.21step/s, loss=0.116404, elapsed=2.6min]

Entraînement:   8%|▊         | 810/10000 [02:34<29:21,  5.22step/s, loss=0.116404, elapsed=2.6min]

Entraînement:   8%|▊         | 810/10000 [02:34<29:21,  5.22step/s, loss=0.103381, elapsed=2.6min]

Entraînement:   8%|▊         | 811/10000 [02:34<29:21,  5.22step/s, loss=0.103381, elapsed=2.6min]

Entraînement:   8%|▊         | 811/10000 [02:34<29:21,  5.22step/s, loss=0.079941, elapsed=2.6min]

Entraînement:   8%|▊         | 812/10000 [02:34<42:26,  3.61step/s, loss=0.079941, elapsed=2.6min]

Entraînement:   8%|▊         | 812/10000 [02:34<42:26,  3.61step/s, loss=0.071111, elapsed=2.6min]

Entraînement:   8%|▊         | 813/10000 [02:34<38:39,  3.96step/s, loss=0.071111, elapsed=2.6min]

Entraînement:   8%|▊         | 813/10000 [02:34<38:39,  3.96step/s, loss=0.109130, elapsed=2.6min]

Entraînement:   8%|▊         | 814/10000 [02:35<35:55,  4.26step/s, loss=0.109130, elapsed=2.6min]

Entraînement:   8%|▊         | 814/10000 [02:35<35:55,  4.26step/s, loss=0.088398, elapsed=2.6min]

Entraînement:   8%|▊         | 815/10000 [02:35<33:59,  4.50step/s, loss=0.088398, elapsed=2.6min]

Entraînement:   8%|▊         | 815/10000 [02:35<33:59,  4.50step/s, loss=0.069706, elapsed=2.6min]

Entraînement:   8%|▊         | 816/10000 [02:35<32:37,  4.69step/s, loss=0.069706, elapsed=2.6min]

Entraînement:   8%|▊         | 816/10000 [02:35<32:37,  4.69step/s, loss=0.112757, elapsed=2.6min]

Entraînement:   8%|▊         | 817/10000 [02:35<31:39,  4.83step/s, loss=0.112757, elapsed=2.6min]

Entraînement:   8%|▊         | 817/10000 [02:35<31:39,  4.83step/s, loss=0.172076, elapsed=2.6min]

Entraînement:   8%|▊         | 818/10000 [02:35<30:57,  4.94step/s, loss=0.172076, elapsed=2.6min]

Entraînement:   8%|▊         | 818/10000 [02:35<30:57,  4.94step/s, loss=0.112038, elapsed=2.6min]

Entraînement:   8%|▊         | 819/10000 [02:36<30:34,  5.01step/s, loss=0.112038, elapsed=2.6min]

Entraînement:   8%|▊         | 819/10000 [02:36<30:34,  5.01step/s, loss=0.082049, elapsed=2.6min]

Entraînement:   8%|▊         | 820/10000 [02:36<30:11,  5.07step/s, loss=0.082049, elapsed=2.6min]

Entraînement:   8%|▊         | 820/10000 [02:36<30:11,  5.07step/s, loss=0.139181, elapsed=2.6min]

Entraînement:   8%|▊         | 821/10000 [02:36<30:01,  5.10step/s, loss=0.139181, elapsed=2.6min]

Entraînement:   8%|▊         | 821/10000 [02:36<30:01,  5.10step/s, loss=0.055061, elapsed=2.6min]

Entraînement:   8%|▊         | 822/10000 [02:36<29:52,  5.12step/s, loss=0.055061, elapsed=2.6min]

Entraînement:   8%|▊         | 822/10000 [02:36<29:52,  5.12step/s, loss=0.122410, elapsed=2.6min]

Entraînement:   8%|▊         | 823/10000 [02:36<29:43,  5.15step/s, loss=0.122410, elapsed=2.6min]

Entraînement:   8%|▊         | 823/10000 [02:36<29:43,  5.15step/s, loss=0.039466, elapsed=2.6min]

Entraînement:   8%|▊         | 824/10000 [02:36<29:35,  5.17step/s, loss=0.039466, elapsed=2.6min]

Entraînement:   8%|▊         | 824/10000 [02:36<29:35,  5.17step/s, loss=0.113502, elapsed=2.6min]

Entraînement:   8%|▊         | 825/10000 [02:37<29:28,  5.19step/s, loss=0.113502, elapsed=2.6min]

Entraînement:   8%|▊         | 825/10000 [02:37<29:28,  5.19step/s, loss=0.053932, elapsed=2.6min]

Entraînement:   8%|▊         | 826/10000 [02:37<29:20,  5.21step/s, loss=0.053932, elapsed=2.6min]

Entraînement:   8%|▊         | 826/10000 [02:37<29:20,  5.21step/s, loss=0.032096, elapsed=2.6min]

Entraînement:   8%|▊         | 827/10000 [02:37<29:28,  5.19step/s, loss=0.032096, elapsed=2.6min]

Entraînement:   8%|▊         | 827/10000 [02:37<29:28,  5.19step/s, loss=0.037704, elapsed=2.6min]

Entraînement:   8%|▊         | 828/10000 [02:37<29:18,  5.22step/s, loss=0.037704, elapsed=2.6min]

Entraînement:   8%|▊         | 828/10000 [02:37<29:18,  5.22step/s, loss=0.036258, elapsed=2.6min]

Entraînement:   8%|▊         | 829/10000 [02:37<29:14,  5.23step/s, loss=0.036258, elapsed=2.6min]

Entraînement:   8%|▊         | 829/10000 [02:37<29:14,  5.23step/s, loss=0.052024, elapsed=2.6min]

Entraînement:   8%|▊         | 830/10000 [02:38<29:09,  5.24step/s, loss=0.052024, elapsed=2.6min]

Entraînement:   8%|▊         | 830/10000 [02:38<29:09,  5.24step/s, loss=0.036108, elapsed=2.6min]

Entraînement:   8%|▊         | 831/10000 [02:38<29:06,  5.25step/s, loss=0.036108, elapsed=2.6min]

Entraînement:   8%|▊         | 831/10000 [02:38<29:06,  5.25step/s, loss=0.139301, elapsed=2.6min]

Entraînement:   8%|▊         | 832/10000 [02:38<29:05,  5.25step/s, loss=0.139301, elapsed=2.6min]

Entraînement:   8%|▊         | 832/10000 [02:38<29:05,  5.25step/s, loss=0.079762, elapsed=2.6min]

Entraînement:   8%|▊         | 833/10000 [02:38<29:05,  5.25step/s, loss=0.079762, elapsed=2.6min]

Entraînement:   8%|▊         | 833/10000 [02:38<29:05,  5.25step/s, loss=0.040553, elapsed=2.6min]

Entraînement:   8%|▊         | 834/10000 [02:38<29:02,  5.26step/s, loss=0.040553, elapsed=2.6min]

Entraînement:   8%|▊         | 834/10000 [02:38<29:02,  5.26step/s, loss=0.058886, elapsed=2.6min]

Entraînement:   8%|▊         | 835/10000 [02:39<29:04,  5.25step/s, loss=0.058886, elapsed=2.6min]

Entraînement:   8%|▊         | 835/10000 [02:39<29:04,  5.25step/s, loss=0.140491, elapsed=2.7min]

Entraînement:   8%|▊         | 836/10000 [02:39<29:05,  5.25step/s, loss=0.140491, elapsed=2.7min]

Entraînement:   8%|▊         | 836/10000 [02:39<29:05,  5.25step/s, loss=0.041504, elapsed=2.7min]

Entraînement:   8%|▊         | 837/10000 [02:39<29:04,  5.25step/s, loss=0.041504, elapsed=2.7min]

Entraînement:   8%|▊         | 837/10000 [02:39<29:04,  5.25step/s, loss=0.047978, elapsed=2.7min]

Entraînement:   8%|▊         | 838/10000 [02:39<29:03,  5.26step/s, loss=0.047978, elapsed=2.7min]

Entraînement:   8%|▊         | 838/10000 [02:39<29:03,  5.26step/s, loss=0.032766, elapsed=2.7min]

Entraînement:   8%|▊         | 839/10000 [02:39<29:03,  5.26step/s, loss=0.032766, elapsed=2.7min]

Entraînement:   8%|▊         | 839/10000 [02:39<29:03,  5.26step/s, loss=0.044025, elapsed=2.7min]

Entraînement:   8%|▊         | 840/10000 [02:40<29:02,  5.26step/s, loss=0.044025, elapsed=2.7min]

Entraînement:   8%|▊         | 840/10000 [02:40<29:02,  5.26step/s, loss=0.053563, elapsed=2.7min]

Entraînement:   8%|▊         | 841/10000 [02:40<28:59,  5.27step/s, loss=0.053563, elapsed=2.7min]

Entraînement:   8%|▊         | 841/10000 [02:40<28:59,  5.27step/s, loss=0.066284, elapsed=2.7min]

Entraînement:   8%|▊         | 842/10000 [02:40<28:59,  5.26step/s, loss=0.066284, elapsed=2.7min]

Entraînement:   8%|▊         | 842/10000 [02:40<28:59,  5.26step/s, loss=0.045626, elapsed=2.7min]

Entraînement:   8%|▊         | 843/10000 [02:40<28:59,  5.26step/s, loss=0.045626, elapsed=2.7min]

Entraînement:   8%|▊         | 843/10000 [02:40<28:59,  5.26step/s, loss=0.047877, elapsed=2.7min]

Entraînement:   8%|▊         | 844/10000 [02:40<29:01,  5.26step/s, loss=0.047877, elapsed=2.7min]

Entraînement:   8%|▊         | 844/10000 [02:40<29:01,  5.26step/s, loss=0.105100, elapsed=2.7min]

Entraînement:   8%|▊         | 845/10000 [02:40<29:00,  5.26step/s, loss=0.105100, elapsed=2.7min]

Entraînement:   8%|▊         | 845/10000 [02:40<29:00,  5.26step/s, loss=0.046776, elapsed=2.7min]

Entraînement:   8%|▊         | 846/10000 [02:41<29:02,  5.25step/s, loss=0.046776, elapsed=2.7min]

Entraînement:   8%|▊         | 846/10000 [02:41<29:02,  5.25step/s, loss=0.071286, elapsed=2.7min]

Entraînement:   8%|▊         | 847/10000 [02:41<29:01,  5.26step/s, loss=0.071286, elapsed=2.7min]

Entraînement:   8%|▊         | 847/10000 [02:41<29:01,  5.26step/s, loss=0.089560, elapsed=2.7min]

Entraînement:   8%|▊         | 848/10000 [02:41<28:57,  5.27step/s, loss=0.089560, elapsed=2.7min]

Entraînement:   8%|▊         | 848/10000 [02:41<28:57,  5.27step/s, loss=0.028686, elapsed=2.7min]

Entraînement:   8%|▊         | 849/10000 [02:41<28:57,  5.27step/s, loss=0.028686, elapsed=2.7min]

Entraînement:   8%|▊         | 849/10000 [02:41<28:57,  5.27step/s, loss=0.080234, elapsed=2.7min]

Entraînement:   8%|▊         | 850/10000 [02:41<28:57,  5.27step/s, loss=0.080234, elapsed=2.7min]

Entraînement:   8%|▊         | 850/10000 [02:41<28:57,  5.27step/s, loss=0.049465, elapsed=2.7min]

Entraînement:   9%|▊         | 851/10000 [02:42<28:55,  5.27step/s, loss=0.049465, elapsed=2.7min]

Entraînement:   9%|▊         | 851/10000 [02:42<28:55,  5.27step/s, loss=0.053545, elapsed=2.7min]

Entraînement:   9%|▊         | 852/10000 [02:42<28:57,  5.27step/s, loss=0.053545, elapsed=2.7min]

Entraînement:   9%|▊         | 852/10000 [02:42<28:57,  5.27step/s, loss=0.085124, elapsed=2.7min]

Entraînement:   9%|▊         | 853/10000 [02:42<28:55,  5.27step/s, loss=0.085124, elapsed=2.7min]

Entraînement:   9%|▊         | 853/10000 [02:42<28:55,  5.27step/s, loss=0.035746, elapsed=2.7min]

Entraînement:   9%|▊         | 854/10000 [02:42<28:56,  5.27step/s, loss=0.035746, elapsed=2.7min]

Entraînement:   9%|▊         | 854/10000 [02:42<28:56,  5.27step/s, loss=0.028337, elapsed=2.7min]

Entraînement:   9%|▊         | 855/10000 [02:42<28:55,  5.27step/s, loss=0.028337, elapsed=2.7min]

Entraînement:   9%|▊         | 855/10000 [02:42<28:55,  5.27step/s, loss=0.054380, elapsed=2.7min]

Entraînement:   9%|▊         | 856/10000 [02:43<28:51,  5.28step/s, loss=0.054380, elapsed=2.7min]

Entraînement:   9%|▊         | 856/10000 [02:43<28:51,  5.28step/s, loss=0.066700, elapsed=2.7min]

Entraînement:   9%|▊         | 857/10000 [02:43<28:53,  5.27step/s, loss=0.066700, elapsed=2.7min]

Entraînement:   9%|▊         | 857/10000 [02:43<28:53,  5.27step/s, loss=0.066545, elapsed=2.7min]

Entraînement:   9%|▊         | 858/10000 [02:43<28:51,  5.28step/s, loss=0.066545, elapsed=2.7min]

Entraînement:   9%|▊         | 858/10000 [02:43<28:51,  5.28step/s, loss=0.084179, elapsed=2.7min]

Entraînement:   9%|▊         | 859/10000 [02:43<28:51,  5.28step/s, loss=0.084179, elapsed=2.7min]

Entraînement:   9%|▊         | 859/10000 [02:43<28:51,  5.28step/s, loss=0.078288, elapsed=2.7min]

Entraînement:   9%|▊         | 860/10000 [02:43<28:49,  5.29step/s, loss=0.078288, elapsed=2.7min]

Entraînement:   9%|▊         | 860/10000 [02:43<28:49,  5.29step/s, loss=0.153098, elapsed=2.7min]

Entraînement:   9%|▊         | 861/10000 [02:44<28:52,  5.27step/s, loss=0.153098, elapsed=2.7min]

Entraînement:   9%|▊         | 861/10000 [02:44<28:52,  5.27step/s, loss=0.055740, elapsed=2.7min]

Entraînement:   9%|▊         | 862/10000 [02:44<28:51,  5.28step/s, loss=0.055740, elapsed=2.7min]

Entraînement:   9%|▊         | 862/10000 [02:44<28:51,  5.28step/s, loss=0.096856, elapsed=2.7min]

Entraînement:   9%|▊         | 863/10000 [02:44<28:51,  5.28step/s, loss=0.096856, elapsed=2.7min]

Entraînement:   9%|▊         | 863/10000 [02:44<28:51,  5.28step/s, loss=0.039560, elapsed=2.7min]

Entraînement:   9%|▊         | 864/10000 [02:44<28:49,  5.28step/s, loss=0.039560, elapsed=2.7min]

Entraînement:   9%|▊         | 864/10000 [02:44<28:49,  5.28step/s, loss=0.045979, elapsed=2.7min]

Entraînement:   9%|▊         | 865/10000 [02:44<28:45,  5.29step/s, loss=0.045979, elapsed=2.7min]

Entraînement:   9%|▊         | 865/10000 [02:44<28:45,  5.29step/s, loss=0.037936, elapsed=2.7min]

Entraînement:   9%|▊         | 866/10000 [02:44<28:49,  5.28step/s, loss=0.037936, elapsed=2.7min]

Entraînement:   9%|▊         | 866/10000 [02:44<28:49,  5.28step/s, loss=0.092315, elapsed=2.7min]

Entraînement:   9%|▊         | 867/10000 [02:45<28:50,  5.28step/s, loss=0.092315, elapsed=2.7min]

Entraînement:   9%|▊         | 867/10000 [02:45<28:50,  5.28step/s, loss=0.058617, elapsed=2.8min]

Entraînement:   9%|▊         | 868/10000 [02:45<28:46,  5.29step/s, loss=0.058617, elapsed=2.8min]

Entraînement:   9%|▊         | 868/10000 [02:45<28:46,  5.29step/s, loss=0.051769, elapsed=2.8min]

Entraînement:   9%|▊         | 869/10000 [02:45<28:48,  5.28step/s, loss=0.051769, elapsed=2.8min]

Entraînement:   9%|▊         | 869/10000 [02:45<28:48,  5.28step/s, loss=0.087078, elapsed=2.8min]

Entraînement:   9%|▊         | 870/10000 [02:45<28:47,  5.28step/s, loss=0.087078, elapsed=2.8min]

Entraînement:   9%|▊         | 870/10000 [02:45<28:47,  5.28step/s, loss=0.091104, elapsed=2.8min]

Entraînement:   9%|▊         | 871/10000 [02:45<28:46,  5.29step/s, loss=0.091104, elapsed=2.8min]

Entraînement:   9%|▊         | 871/10000 [02:45<28:46,  5.29step/s, loss=0.052082, elapsed=2.8min]

Entraînement:   9%|▊         | 872/10000 [02:46<28:48,  5.28step/s, loss=0.052082, elapsed=2.8min]

Entraînement:   9%|▊         | 872/10000 [02:46<28:48,  5.28step/s, loss=0.079082, elapsed=2.8min]

Entraînement:   9%|▊         | 873/10000 [02:46<28:45,  5.29step/s, loss=0.079082, elapsed=2.8min]

Entraînement:   9%|▊         | 873/10000 [02:46<28:45,  5.29step/s, loss=0.049697, elapsed=2.8min]

Entraînement:   9%|▊         | 874/10000 [02:46<28:45,  5.29step/s, loss=0.049697, elapsed=2.8min]

Entraînement:   9%|▊         | 874/10000 [02:46<28:45,  5.29step/s, loss=0.048631, elapsed=2.8min]

Entraînement:   9%|▉         | 875/10000 [02:46<28:48,  5.28step/s, loss=0.048631, elapsed=2.8min]

Entraînement:   9%|▉         | 875/10000 [02:46<28:48,  5.28step/s, loss=0.073084, elapsed=2.8min]

Entraînement:   9%|▉         | 876/10000 [02:46<28:49,  5.27step/s, loss=0.073084, elapsed=2.8min]

Entraînement:   9%|▉         | 876/10000 [02:46<28:49,  5.27step/s, loss=0.046692, elapsed=2.8min]

Entraînement:   9%|▉         | 877/10000 [02:47<28:45,  5.29step/s, loss=0.046692, elapsed=2.8min]

Entraînement:   9%|▉         | 877/10000 [02:47<28:45,  5.29step/s, loss=0.097241, elapsed=2.8min]

Entraînement:   9%|▉         | 878/10000 [02:47<28:47,  5.28step/s, loss=0.097241, elapsed=2.8min]

Entraînement:   9%|▉         | 878/10000 [02:47<28:47,  5.28step/s, loss=0.164624, elapsed=2.8min]

Entraînement:   9%|▉         | 879/10000 [02:47<28:46,  5.28step/s, loss=0.164624, elapsed=2.8min]

Entraînement:   9%|▉         | 879/10000 [02:47<28:46,  5.28step/s, loss=0.055880, elapsed=2.8min]

Entraînement:   9%|▉         | 880/10000 [02:47<28:43,  5.29step/s, loss=0.055880, elapsed=2.8min]

Entraînement:   9%|▉         | 880/10000 [02:47<28:43,  5.29step/s, loss=0.040632, elapsed=2.8min]

Entraînement:   9%|▉         | 881/10000 [02:47<28:45,  5.28step/s, loss=0.040632, elapsed=2.8min]

Entraînement:   9%|▉         | 881/10000 [02:47<28:45,  5.28step/s, loss=0.066742, elapsed=2.8min]

Entraînement:   9%|▉         | 882/10000 [02:48<28:46,  5.28step/s, loss=0.066742, elapsed=2.8min]

Entraînement:   9%|▉         | 882/10000 [02:48<28:46,  5.28step/s, loss=0.071040, elapsed=2.8min]

Entraînement:   9%|▉         | 883/10000 [02:48<28:43,  5.29step/s, loss=0.071040, elapsed=2.8min]

Entraînement:   9%|▉         | 883/10000 [02:48<28:43,  5.29step/s, loss=0.050922, elapsed=2.8min]

Entraînement:   9%|▉         | 884/10000 [02:48<28:41,  5.30step/s, loss=0.050922, elapsed=2.8min]

Entraînement:   9%|▉         | 884/10000 [02:48<28:41,  5.30step/s, loss=0.109688, elapsed=2.8min]

Entraînement:   9%|▉         | 885/10000 [02:48<28:45,  5.28step/s, loss=0.109688, elapsed=2.8min]

Entraînement:   9%|▉         | 885/10000 [02:48<28:45,  5.28step/s, loss=0.058134, elapsed=2.8min]

Entraînement:   9%|▉         | 886/10000 [02:48<28:46,  5.28step/s, loss=0.058134, elapsed=2.8min]

Entraînement:   9%|▉         | 886/10000 [02:48<28:46,  5.28step/s, loss=0.045947, elapsed=2.8min]

Entraînement:   9%|▉         | 887/10000 [02:48<28:43,  5.29step/s, loss=0.045947, elapsed=2.8min]

Entraînement:   9%|▉         | 887/10000 [02:48<28:43,  5.29step/s, loss=0.088031, elapsed=2.8min]

Entraînement:   9%|▉         | 888/10000 [02:49<28:47,  5.27step/s, loss=0.088031, elapsed=2.8min]

Entraînement:   9%|▉         | 888/10000 [02:49<28:47,  5.27step/s, loss=0.054725, elapsed=2.8min]

Entraînement:   9%|▉         | 889/10000 [02:49<28:46,  5.28step/s, loss=0.054725, elapsed=2.8min]

Entraînement:   9%|▉         | 889/10000 [02:49<28:46,  5.28step/s, loss=0.128696, elapsed=2.8min]

Entraînement:   9%|▉         | 890/10000 [02:49<28:43,  5.29step/s, loss=0.128696, elapsed=2.8min]

Entraînement:   9%|▉         | 890/10000 [02:49<28:43,  5.29step/s, loss=0.128021, elapsed=2.8min]

Entraînement:   9%|▉         | 891/10000 [02:49<28:46,  5.27step/s, loss=0.128021, elapsed=2.8min]

Entraînement:   9%|▉         | 891/10000 [02:49<28:46,  5.27step/s, loss=0.060362, elapsed=2.8min]

Entraînement:   9%|▉         | 892/10000 [02:49<28:52,  5.26step/s, loss=0.060362, elapsed=2.8min]

Entraînement:   9%|▉         | 892/10000 [02:49<28:52,  5.26step/s, loss=0.068748, elapsed=2.8min]

Entraînement:   9%|▉         | 893/10000 [02:50<28:52,  5.26step/s, loss=0.068748, elapsed=2.8min]

Entraînement:   9%|▉         | 893/10000 [02:50<28:52,  5.26step/s, loss=0.069037, elapsed=2.8min]

Entraînement:   9%|▉         | 894/10000 [02:50<28:47,  5.27step/s, loss=0.069037, elapsed=2.8min]

Entraînement:   9%|▉         | 894/10000 [02:50<28:47,  5.27step/s, loss=0.058207, elapsed=2.8min]

Entraînement:   9%|▉         | 895/10000 [02:50<28:48,  5.27step/s, loss=0.058207, elapsed=2.8min]

Entraînement:   9%|▉         | 895/10000 [02:50<28:48,  5.27step/s, loss=0.076294, elapsed=2.8min]

Entraînement:   9%|▉         | 896/10000 [02:50<28:48,  5.27step/s, loss=0.076294, elapsed=2.8min]

Entraînement:   9%|▉         | 896/10000 [02:50<28:48,  5.27step/s, loss=0.090844, elapsed=2.8min]

Entraînement:   9%|▉         | 897/10000 [02:50<28:47,  5.27step/s, loss=0.090844, elapsed=2.8min]

Entraînement:   9%|▉         | 897/10000 [02:50<28:47,  5.27step/s, loss=0.098335, elapsed=2.8min]

Entraînement:   9%|▉         | 898/10000 [02:51<28:48,  5.26step/s, loss=0.098335, elapsed=2.8min]

Entraînement:   9%|▉         | 898/10000 [02:51<28:48,  5.26step/s, loss=0.062592, elapsed=2.9min]

Entraînement:   9%|▉         | 899/10000 [02:51<28:48,  5.27step/s, loss=0.062592, elapsed=2.9min]

Entraînement:   9%|▉         | 899/10000 [02:51<28:48,  5.27step/s, loss=0.082202, elapsed=2.9min]

Entraînement:   9%|▉         | 900/10000 [02:51<28:46,  5.27step/s, loss=0.082202, elapsed=2.9min]

Entraînement:   9%|▉         | 900/10000 [02:51<28:46,  5.27step/s, loss=0.095196, elapsed=2.9min]

Entraînement:   9%|▉         | 900/10000 [02:51<28:46,  5.27step/s, loss=0.095196, elapsed=2.9min]

Entraînement:   9%|▉         | 901/10000 [02:51<29:07,  5.21step/s, loss=0.095196, elapsed=2.9min]

Entraînement:   9%|▉         | 901/10000 [02:51<29:07,  5.21step/s, loss=0.055620, elapsed=2.9min]

Step 900/10000 | Train loss: 0.095196 | Elapsed: 2.9min | ETA: 28.9min

Entraînement:   9%|▉         | 902/10000 [02:51<29:02,  5.22step/s, loss=0.055620, elapsed=2.9min]

Entraînement:   9%|▉         | 902/10000 [02:51<29:02,  5.22step/s, loss=0.091206, elapsed=2.9min]

Entraînement:   9%|▉         | 903/10000 [02:51<28:55,  5.24step/s, loss=0.091206, elapsed=2.9min]

Entraînement:   9%|▉         | 903/10000 [02:51<28:55,  5.24step/s, loss=0.048241, elapsed=2.9min]

Entraînement:   9%|▉         | 904/10000 [02:52<28:56,  5.24step/s, loss=0.048241, elapsed=2.9min]

Entraînement:   9%|▉         | 904/10000 [02:52<28:56,  5.24step/s, loss=0.078521, elapsed=2.9min]

Entraînement:   9%|▉         | 905/10000 [02:52<28:49,  5.26step/s, loss=0.078521, elapsed=2.9min]

Entraînement:   9%|▉         | 905/10000 [02:52<28:49,  5.26step/s, loss=0.056759, elapsed=2.9min]

Entraînement:   9%|▉         | 906/10000 [02:52<28:46,  5.27step/s, loss=0.056759, elapsed=2.9min]

Entraînement:   9%|▉         | 906/10000 [02:52<28:46,  5.27step/s, loss=0.094102, elapsed=2.9min]

Entraînement:   9%|▉         | 907/10000 [02:52<28:48,  5.26step/s, loss=0.094102, elapsed=2.9min]

Entraînement:   9%|▉         | 907/10000 [02:52<28:48,  5.26step/s, loss=0.048596, elapsed=2.9min]

Entraînement:   9%|▉         | 908/10000 [02:52<28:48,  5.26step/s, loss=0.048596, elapsed=2.9min]

Entraînement:   9%|▉         | 908/10000 [02:52<28:48,  5.26step/s, loss=0.080795, elapsed=2.9min]

Entraînement:   9%|▉         | 909/10000 [02:53<28:48,  5.26step/s, loss=0.080795, elapsed=2.9min]

Entraînement:   9%|▉         | 909/10000 [02:53<28:48,  5.26step/s, loss=0.139481, elapsed=2.9min]

Entraînement:   9%|▉         | 910/10000 [02:53<28:51,  5.25step/s, loss=0.139481, elapsed=2.9min]

Entraînement:   9%|▉         | 910/10000 [02:53<28:51,  5.25step/s, loss=0.047397, elapsed=2.9min]

Entraînement:   9%|▉         | 911/10000 [02:53<28:55,  5.24step/s, loss=0.047397, elapsed=2.9min]

Entraînement:   9%|▉         | 911/10000 [02:53<28:55,  5.24step/s, loss=0.035583, elapsed=2.9min]

Entraînement:   9%|▉         | 912/10000 [02:53<28:51,  5.25step/s, loss=0.035583, elapsed=2.9min]

Entraînement:   9%|▉         | 912/10000 [02:53<28:51,  5.25step/s, loss=0.074367, elapsed=2.9min]

Entraînement:   9%|▉         | 913/10000 [02:53<29:03,  5.21step/s, loss=0.074367, elapsed=2.9min]

Entraînement:   9%|▉         | 913/10000 [02:53<29:03,  5.21step/s, loss=0.045169, elapsed=2.9min]

Entraînement:   9%|▉         | 914/10000 [02:54<28:55,  5.24step/s, loss=0.045169, elapsed=2.9min]

Entraînement:   9%|▉         | 914/10000 [02:54<28:55,  5.24step/s, loss=0.047941, elapsed=2.9min]

Entraînement:   9%|▉         | 915/10000 [02:54<28:49,  5.25step/s, loss=0.047941, elapsed=2.9min]

Entraînement:   9%|▉         | 915/10000 [02:54<28:49,  5.25step/s, loss=0.079836, elapsed=2.9min]

Entraînement:   9%|▉         | 916/10000 [02:54<28:43,  5.27step/s, loss=0.079836, elapsed=2.9min]

Entraînement:   9%|▉         | 916/10000 [02:54<28:43,  5.27step/s, loss=0.031867, elapsed=2.9min]

Entraînement:   9%|▉         | 917/10000 [02:54<28:44,  5.27step/s, loss=0.031867, elapsed=2.9min]

Entraînement:   9%|▉         | 917/10000 [02:54<28:44,  5.27step/s, loss=0.100098, elapsed=2.9min]

Entraînement:   9%|▉         | 918/10000 [02:54<28:47,  5.26step/s, loss=0.100098, elapsed=2.9min]

Entraînement:   9%|▉         | 918/10000 [02:54<28:47,  5.26step/s, loss=0.044041, elapsed=2.9min]

Entraînement:   9%|▉         | 919/10000 [02:55<28:47,  5.26step/s, loss=0.044041, elapsed=2.9min]

Entraînement:   9%|▉         | 919/10000 [02:55<28:47,  5.26step/s, loss=0.047583, elapsed=2.9min]

Entraînement:   9%|▉         | 920/10000 [02:55<28:49,  5.25step/s, loss=0.047583, elapsed=2.9min]

Entraînement:   9%|▉         | 920/10000 [02:55<28:49,  5.25step/s, loss=0.063238, elapsed=2.9min]

Entraînement:   9%|▉         | 921/10000 [02:55<28:49,  5.25step/s, loss=0.063238, elapsed=2.9min]

Entraînement:   9%|▉         | 921/10000 [02:55<28:49,  5.25step/s, loss=0.088155, elapsed=2.9min]

Entraînement:   9%|▉         | 922/10000 [02:55<28:50,  5.25step/s, loss=0.088155, elapsed=2.9min]

Entraînement:   9%|▉         | 922/10000 [02:55<28:50,  5.25step/s, loss=0.070847, elapsed=2.9min]

Entraînement:   9%|▉         | 923/10000 [02:55<28:51,  5.24step/s, loss=0.070847, elapsed=2.9min]

Entraînement:   9%|▉         | 923/10000 [02:55<28:51,  5.24step/s, loss=0.052420, elapsed=2.9min]

Entraînement:   9%|▉         | 924/10000 [02:55<28:48,  5.25step/s, loss=0.052420, elapsed=2.9min]

Entraînement:   9%|▉         | 924/10000 [02:55<28:48,  5.25step/s, loss=0.048063, elapsed=2.9min]

Entraînement:   9%|▉         | 925/10000 [02:56<28:42,  5.27step/s, loss=0.048063, elapsed=2.9min]

Entraînement:   9%|▉         | 925/10000 [02:56<28:42,  5.27step/s, loss=0.124575, elapsed=2.9min]

Entraînement:   9%|▉         | 926/10000 [02:56<28:43,  5.26step/s, loss=0.124575, elapsed=2.9min]

Entraînement:   9%|▉         | 926/10000 [02:56<28:43,  5.26step/s, loss=0.069449, elapsed=2.9min]

Entraînement:   9%|▉         | 927/10000 [02:56<28:41,  5.27step/s, loss=0.069449, elapsed=2.9min]

Entraînement:   9%|▉         | 927/10000 [02:56<28:41,  5.27step/s, loss=0.053997, elapsed=2.9min]

Entraînement:   9%|▉         | 928/10000 [02:56<28:42,  5.27step/s, loss=0.053997, elapsed=2.9min]

Entraînement:   9%|▉         | 928/10000 [02:56<28:42,  5.27step/s, loss=0.091989, elapsed=2.9min]

Entraînement:   9%|▉         | 929/10000 [02:56<28:43,  5.26step/s, loss=0.091989, elapsed=2.9min]

Entraînement:   9%|▉         | 929/10000 [02:56<28:43,  5.26step/s, loss=0.061488, elapsed=2.9min]

Entraînement:   9%|▉         | 930/10000 [02:57<28:43,  5.26step/s, loss=0.061488, elapsed=2.9min]

Entraînement:   9%|▉         | 930/10000 [02:57<28:43,  5.26step/s, loss=0.043095, elapsed=3.0min]

Entraînement:   9%|▉         | 931/10000 [02:57<28:40,  5.27step/s, loss=0.043095, elapsed=3.0min]

Entraînement:   9%|▉         | 931/10000 [02:57<28:40,  5.27step/s, loss=0.146261, elapsed=3.0min]

Entraînement:   9%|▉         | 932/10000 [02:57<28:36,  5.28step/s, loss=0.146261, elapsed=3.0min]

Entraînement:   9%|▉         | 932/10000 [02:57<28:36,  5.28step/s, loss=0.047940, elapsed=3.0min]

Entraînement:   9%|▉         | 933/10000 [02:57<28:36,  5.28step/s, loss=0.047940, elapsed=3.0min]

Entraînement:   9%|▉         | 933/10000 [02:57<28:36,  5.28step/s, loss=0.103819, elapsed=3.0min]

Entraînement:   9%|▉         | 934/10000 [02:57<28:35,  5.29step/s, loss=0.103819, elapsed=3.0min]

Entraînement:   9%|▉         | 934/10000 [02:57<28:35,  5.29step/s, loss=0.066532, elapsed=3.0min]

Entraînement:   9%|▉         | 935/10000 [02:58<28:35,  5.28step/s, loss=0.066532, elapsed=3.0min]

Entraînement:   9%|▉         | 935/10000 [02:58<28:35,  5.28step/s, loss=0.055591, elapsed=3.0min]

Entraînement:   9%|▉         | 936/10000 [02:58<28:35,  5.28step/s, loss=0.055591, elapsed=3.0min]

Entraînement:   9%|▉         | 936/10000 [02:58<28:35,  5.28step/s, loss=0.055328, elapsed=3.0min]

Entraînement:   9%|▉         | 937/10000 [02:58<28:34,  5.29step/s, loss=0.055328, elapsed=3.0min]

Entraînement:   9%|▉         | 937/10000 [02:58<28:34,  5.29step/s, loss=0.060791, elapsed=3.0min]

Entraînement:   9%|▉         | 938/10000 [02:58<28:33,  5.29step/s, loss=0.060791, elapsed=3.0min]

Entraînement:   9%|▉         | 938/10000 [02:58<28:33,  5.29step/s, loss=0.040730, elapsed=3.0min]

Entraînement:   9%|▉         | 939/10000 [02:58<28:31,  5.29step/s, loss=0.040730, elapsed=3.0min]

Entraînement:   9%|▉         | 939/10000 [02:58<28:31,  5.29step/s, loss=0.042919, elapsed=3.0min]

Entraînement:   9%|▉         | 940/10000 [02:59<28:31,  5.29step/s, loss=0.042919, elapsed=3.0min]

Entraînement:   9%|▉         | 940/10000 [02:59<28:31,  5.29step/s, loss=0.067622, elapsed=3.0min]

Entraînement:   9%|▉         | 941/10000 [02:59<28:32,  5.29step/s, loss=0.067622, elapsed=3.0min]

Entraînement:   9%|▉         | 941/10000 [02:59<28:32,  5.29step/s, loss=0.037661, elapsed=3.0min]

Entraînement:   9%|▉         | 942/10000 [02:59<28:31,  5.29step/s, loss=0.037661, elapsed=3.0min]

Entraînement:   9%|▉         | 942/10000 [02:59<28:31,  5.29step/s, loss=0.123839, elapsed=3.0min]

Entraînement:   9%|▉         | 943/10000 [02:59<28:33,  5.29step/s, loss=0.123839, elapsed=3.0min]

Entraînement:   9%|▉         | 943/10000 [02:59<28:33,  5.29step/s, loss=0.083079, elapsed=3.0min]

Entraînement:   9%|▉         | 944/10000 [02:59<28:32,  5.29step/s, loss=0.083079, elapsed=3.0min]

Entraînement:   9%|▉         | 944/10000 [02:59<28:32,  5.29step/s, loss=0.071140, elapsed=3.0min]

Entraînement:   9%|▉         | 945/10000 [02:59<28:29,  5.30step/s, loss=0.071140, elapsed=3.0min]

Entraînement:   9%|▉         | 945/10000 [02:59<28:29,  5.30step/s, loss=0.035680, elapsed=3.0min]

Entraînement:   9%|▉         | 946/10000 [03:00<28:32,  5.29step/s, loss=0.035680, elapsed=3.0min]

Entraînement:   9%|▉         | 946/10000 [03:00<28:32,  5.29step/s, loss=0.068441, elapsed=3.0min]

Entraînement:   9%|▉         | 947/10000 [03:00<28:30,  5.29step/s, loss=0.068441, elapsed=3.0min]

Entraînement:   9%|▉         | 947/10000 [03:00<28:30,  5.29step/s, loss=0.096802, elapsed=3.0min]

Entraînement:   9%|▉         | 948/10000 [03:00<28:31,  5.29step/s, loss=0.096802, elapsed=3.0min]

Entraînement:   9%|▉         | 948/10000 [03:00<28:31,  5.29step/s, loss=0.057437, elapsed=3.0min]

Entraînement:   9%|▉         | 949/10000 [03:00<28:30,  5.29step/s, loss=0.057437, elapsed=3.0min]

Entraînement:   9%|▉         | 949/10000 [03:00<28:30,  5.29step/s, loss=0.065402, elapsed=3.0min]

Entraînement:  10%|▉         | 950/10000 [03:00<28:30,  5.29step/s, loss=0.065402, elapsed=3.0min]

Entraînement:  10%|▉         | 950/10000 [03:00<28:30,  5.29step/s, loss=0.064221, elapsed=3.0min]

Entraînement:  10%|▉         | 951/10000 [03:01<28:32,  5.28step/s, loss=0.064221, elapsed=3.0min]

Entraînement:  10%|▉         | 951/10000 [03:01<28:32,  5.28step/s, loss=0.053205, elapsed=3.0min]

Entraînement:  10%|▉         | 952/10000 [03:01<28:29,  5.29step/s, loss=0.053205, elapsed=3.0min]

Entraînement:  10%|▉         | 952/10000 [03:01<28:29,  5.29step/s, loss=0.177559, elapsed=3.0min]

Entraînement:  10%|▉         | 953/10000 [03:01<28:29,  5.29step/s, loss=0.177559, elapsed=3.0min]

Entraînement:  10%|▉         | 953/10000 [03:01<28:29,  5.29step/s, loss=0.166461, elapsed=3.0min]

Entraînement:  10%|▉         | 954/10000 [03:01<28:28,  5.29step/s, loss=0.166461, elapsed=3.0min]

Entraînement:  10%|▉         | 954/10000 [03:01<28:28,  5.29step/s, loss=0.131673, elapsed=3.0min]

Entraînement:  10%|▉         | 955/10000 [03:01<28:25,  5.30step/s, loss=0.131673, elapsed=3.0min]

Entraînement:  10%|▉         | 955/10000 [03:01<28:25,  5.30step/s, loss=0.166751, elapsed=3.0min]

Entraînement:  10%|▉         | 956/10000 [03:02<28:25,  5.30step/s, loss=0.166751, elapsed=3.0min]

Entraînement:  10%|▉         | 956/10000 [03:02<28:25,  5.30step/s, loss=0.076892, elapsed=3.0min]

Entraînement:  10%|▉         | 957/10000 [03:02<28:26,  5.30step/s, loss=0.076892, elapsed=3.0min]

Entraînement:  10%|▉         | 957/10000 [03:02<28:26,  5.30step/s, loss=0.060446, elapsed=3.0min]

Entraînement:  10%|▉         | 958/10000 [03:02<28:31,  5.28step/s, loss=0.060446, elapsed=3.0min]

Entraînement:  10%|▉         | 958/10000 [03:02<28:31,  5.28step/s, loss=0.044131, elapsed=3.0min]

Entraînement:  10%|▉         | 959/10000 [03:02<28:36,  5.27step/s, loss=0.044131, elapsed=3.0min]

Entraînement:  10%|▉         | 959/10000 [03:02<28:36,  5.27step/s, loss=0.051391, elapsed=3.0min]

Entraînement:  10%|▉         | 960/10000 [03:02<28:36,  5.27step/s, loss=0.051391, elapsed=3.0min]

Entraînement:  10%|▉         | 960/10000 [03:02<28:36,  5.27step/s, loss=0.052633, elapsed=3.0min]

Entraînement:  10%|▉         | 961/10000 [03:02<28:36,  5.27step/s, loss=0.052633, elapsed=3.0min]

Entraînement:  10%|▉         | 961/10000 [03:02<28:36,  5.27step/s, loss=0.076462, elapsed=3.0min]

Entraînement:  10%|▉         | 962/10000 [03:03<28:32,  5.28step/s, loss=0.076462, elapsed=3.0min]

Entraînement:  10%|▉         | 962/10000 [03:03<28:32,  5.28step/s, loss=0.107441, elapsed=3.1min]

Entraînement:  10%|▉         | 963/10000 [03:03<28:32,  5.28step/s, loss=0.107441, elapsed=3.1min]

Entraînement:  10%|▉         | 963/10000 [03:03<28:32,  5.28step/s, loss=0.119605, elapsed=3.1min]

Entraînement:  10%|▉         | 964/10000 [03:03<28:28,  5.29step/s, loss=0.119605, elapsed=3.1min]

Entraînement:  10%|▉         | 964/10000 [03:03<28:28,  5.29step/s, loss=0.103059, elapsed=3.1min]

Entraînement:  10%|▉         | 965/10000 [03:03<28:24,  5.30step/s, loss=0.103059, elapsed=3.1min]

Entraînement:  10%|▉         | 965/10000 [03:03<28:24,  5.30step/s, loss=0.063068, elapsed=3.1min]

Entraînement:  10%|▉         | 966/10000 [03:03<28:28,  5.29step/s, loss=0.063068, elapsed=3.1min]

Entraînement:  10%|▉         | 966/10000 [03:03<28:28,  5.29step/s, loss=0.125505, elapsed=3.1min]

Entraînement:  10%|▉         | 967/10000 [03:04<28:30,  5.28step/s, loss=0.125505, elapsed=3.1min]

Entraînement:  10%|▉         | 967/10000 [03:04<28:30,  5.28step/s, loss=0.086486, elapsed=3.1min]

Entraînement:  10%|▉         | 968/10000 [03:04<28:29,  5.28step/s, loss=0.086486, elapsed=3.1min]

Entraînement:  10%|▉         | 968/10000 [03:04<28:29,  5.28step/s, loss=0.067158, elapsed=3.1min]

Entraînement:  10%|▉         | 969/10000 [03:04<28:27,  5.29step/s, loss=0.067158, elapsed=3.1min]

Entraînement:  10%|▉         | 969/10000 [03:04<28:27,  5.29step/s, loss=0.057599, elapsed=3.1min]

Entraînement:  10%|▉         | 970/10000 [03:04<28:22,  5.31step/s, loss=0.057599, elapsed=3.1min]

Entraînement:  10%|▉         | 970/10000 [03:04<28:22,  5.31step/s, loss=0.065644, elapsed=3.1min]

Entraînement:  10%|▉         | 971/10000 [03:04<28:23,  5.30step/s, loss=0.065644, elapsed=3.1min]

Entraînement:  10%|▉         | 971/10000 [03:04<28:23,  5.30step/s, loss=0.032343, elapsed=3.1min]

Entraînement:  10%|▉         | 972/10000 [03:05<28:22,  5.30step/s, loss=0.032343, elapsed=3.1min]

Entraînement:  10%|▉         | 972/10000 [03:05<28:22,  5.30step/s, loss=0.133534, elapsed=3.1min]

Entraînement:  10%|▉         | 973/10000 [03:05<28:21,  5.31step/s, loss=0.133534, elapsed=3.1min]

Entraînement:  10%|▉         | 973/10000 [03:05<28:21,  5.31step/s, loss=0.062923, elapsed=3.1min]

Entraînement:  10%|▉         | 974/10000 [03:05<28:25,  5.29step/s, loss=0.062923, elapsed=3.1min]

Entraînement:  10%|▉         | 974/10000 [03:05<28:25,  5.29step/s, loss=0.073427, elapsed=3.1min]

Entraînement:  10%|▉         | 975/10000 [03:05<28:24,  5.29step/s, loss=0.073427, elapsed=3.1min]

Entraînement:  10%|▉         | 975/10000 [03:05<28:24,  5.29step/s, loss=0.106961, elapsed=3.1min]

Entraînement:  10%|▉         | 976/10000 [03:05<28:27,  5.29step/s, loss=0.106961, elapsed=3.1min]

Entraînement:  10%|▉         | 976/10000 [03:05<28:27,  5.29step/s, loss=0.035573, elapsed=3.1min]

Entraînement:  10%|▉         | 977/10000 [03:06<28:23,  5.30step/s, loss=0.035573, elapsed=3.1min]

Entraînement:  10%|▉         | 977/10000 [03:06<28:23,  5.30step/s, loss=0.054236, elapsed=3.1min]

Entraînement:  10%|▉         | 978/10000 [03:06<28:22,  5.30step/s, loss=0.054236, elapsed=3.1min]

Entraînement:  10%|▉         | 978/10000 [03:06<28:22,  5.30step/s, loss=0.071563, elapsed=3.1min]

Entraînement:  10%|▉         | 979/10000 [03:06<28:21,  5.30step/s, loss=0.071563, elapsed=3.1min]

Entraînement:  10%|▉         | 979/10000 [03:06<28:21,  5.30step/s, loss=0.059116, elapsed=3.1min]

Entraînement:  10%|▉         | 980/10000 [03:06<28:19,  5.31step/s, loss=0.059116, elapsed=3.1min]

Entraînement:  10%|▉         | 980/10000 [03:06<28:19,  5.31step/s, loss=0.033297, elapsed=3.1min]

Entraînement:  10%|▉         | 981/10000 [03:06<28:21,  5.30step/s, loss=0.033297, elapsed=3.1min]

Entraînement:  10%|▉         | 981/10000 [03:06<28:21,  5.30step/s, loss=0.158996, elapsed=3.1min]

Entraînement:  10%|▉         | 982/10000 [03:06<28:21,  5.30step/s, loss=0.158996, elapsed=3.1min]

Entraînement:  10%|▉         | 982/10000 [03:06<28:21,  5.30step/s, loss=0.056702, elapsed=3.1min]

Entraînement:  10%|▉         | 983/10000 [03:07<28:23,  5.29step/s, loss=0.056702, elapsed=3.1min]

Entraînement:  10%|▉         | 983/10000 [03:07<28:23,  5.29step/s, loss=0.059895, elapsed=3.1min]

Entraînement:  10%|▉         | 984/10000 [03:07<28:22,  5.29step/s, loss=0.059895, elapsed=3.1min]

Entraînement:  10%|▉         | 984/10000 [03:07<28:22,  5.29step/s, loss=0.101854, elapsed=3.1min]

Entraînement:  10%|▉         | 985/10000 [03:07<28:19,  5.30step/s, loss=0.101854, elapsed=3.1min]

Entraînement:  10%|▉         | 985/10000 [03:07<28:19,  5.30step/s, loss=0.073581, elapsed=3.1min]

Entraînement:  10%|▉         | 986/10000 [03:07<28:19,  5.30step/s, loss=0.073581, elapsed=3.1min]

Entraînement:  10%|▉         | 986/10000 [03:07<28:19,  5.30step/s, loss=0.039960, elapsed=3.1min]

Entraînement:  10%|▉         | 987/10000 [03:07<28:21,  5.30step/s, loss=0.039960, elapsed=3.1min]

Entraînement:  10%|▉         | 987/10000 [03:07<28:21,  5.30step/s, loss=0.103277, elapsed=3.1min]

Entraînement:  10%|▉         | 988/10000 [03:08<28:18,  5.31step/s, loss=0.103277, elapsed=3.1min]

Entraînement:  10%|▉         | 988/10000 [03:08<28:18,  5.31step/s, loss=0.109671, elapsed=3.1min]

Entraînement:  10%|▉         | 989/10000 [03:08<28:22,  5.29step/s, loss=0.109671, elapsed=3.1min]

Entraînement:  10%|▉         | 989/10000 [03:08<28:22,  5.29step/s, loss=0.030304, elapsed=3.1min]

Entraînement:  10%|▉         | 990/10000 [03:08<28:22,  5.29step/s, loss=0.030304, elapsed=3.1min]

Entraînement:  10%|▉         | 990/10000 [03:08<28:22,  5.29step/s, loss=0.051616, elapsed=3.1min]

Entraînement:  10%|▉         | 991/10000 [03:08<28:22,  5.29step/s, loss=0.051616, elapsed=3.1min]

Entraînement:  10%|▉         | 991/10000 [03:08<28:22,  5.29step/s, loss=0.049780, elapsed=3.1min]

Entraînement:  10%|▉         | 992/10000 [03:08<28:24,  5.29step/s, loss=0.049780, elapsed=3.1min]

Entraînement:  10%|▉         | 992/10000 [03:08<28:24,  5.29step/s, loss=0.034820, elapsed=3.1min]

Entraînement:  10%|▉         | 993/10000 [03:09<28:21,  5.29step/s, loss=0.034820, elapsed=3.1min]

Entraînement:  10%|▉         | 993/10000 [03:09<28:21,  5.29step/s, loss=0.058272, elapsed=3.2min]

Entraînement:  10%|▉         | 994/10000 [03:09<28:21,  5.29step/s, loss=0.058272, elapsed=3.2min]

Entraînement:  10%|▉         | 994/10000 [03:09<28:21,  5.29step/s, loss=0.066369, elapsed=3.2min]

Entraînement:  10%|▉         | 995/10000 [03:09<28:19,  5.30step/s, loss=0.066369, elapsed=3.2min]

Entraînement:  10%|▉         | 995/10000 [03:09<28:19,  5.30step/s, loss=0.040493, elapsed=3.2min]

Entraînement:  10%|▉         | 996/10000 [03:09<28:17,  5.31step/s, loss=0.040493, elapsed=3.2min]

Entraînement:  10%|▉         | 996/10000 [03:09<28:17,  5.31step/s, loss=0.060832, elapsed=3.2min]

Entraînement:  10%|▉         | 997/10000 [03:09<28:19,  5.30step/s, loss=0.060832, elapsed=3.2min]

Entraînement:  10%|▉         | 997/10000 [03:09<28:19,  5.30step/s, loss=0.051742, elapsed=3.2min]

Entraînement:  10%|▉         | 998/10000 [03:09<28:19,  5.30step/s, loss=0.051742, elapsed=3.2min]

Entraînement:  10%|▉         | 998/10000 [03:09<28:19,  5.30step/s, loss=0.047918, elapsed=3.2min]

Entraînement:  10%|▉         | 999/10000 [03:10<28:24,  5.28step/s, loss=0.047918, elapsed=3.2min]

Entraînement:  10%|▉         | 999/10000 [03:10<28:24,  5.28step/s, loss=0.055912, elapsed=3.2min]

Entraînement:  10%|█         | 1000/10000 [03:10<28:34,  5.25step/s, loss=0.055912, elapsed=3.2min]

Entraînement:  10%|█         | 1000/10000 [03:10<28:34,  5.25step/s, loss=0.116945, elapsed=3.2min]

Entraînement:  10%|█         | 1000/10000 [03:10<28:34,  5.25step/s, loss=0.116945, elapsed=3.2min]

Step 1000/10000 | Train loss: 0.116945 | Elapsed: 3.2min | ETA: 28.6min

Entraînement:  10%|█         | 1000/10000 [03:12<28:34,  5.25step/s, loss=0.116945, elapsed=3.2min]

Step 1000/10000 | Val loss: 0.073118 | Validation en 1.7s

Entraînement:  10%|█         | 1000/10000 [03:12<28:34,  5.25step/s, loss=0.116945, elapsed=3.2min]

Entraînement:  10%|█         | 1000/10000 [03:12<28:34,  5.25step/s, loss=0.116945, elapsed=3.2min]

Meilleur checkpoint sauvegardé : /workspace/DiffWave_Project/checkpoints/diffwave_doda_male/best_checkpoint.pt
Dernier checkpoint sauvegardé : /workspace/DiffWave_Project/checkpoints/diffwave_doda_male/last_checkpoint.pt

Entraînement:  10%|█         | 1001/10000 [03:12<2:09:41,  1.16step/s, loss=0.116945, elapsed=3.2min]

Entraînement:  10%|█         | 1001/10000 [03:12<2:09:41,  1.16step/s, loss=0.072647, elapsed=3.2min]

Entraînement:  10%|█         | 1002/10000 [03:12<1:39:16,  1.51step/s, loss=0.072647, elapsed=3.2min]

Entraînement:  10%|█         | 1002/10000 [03:12<1:39:16,  1.51step/s, loss=0.058652, elapsed=3.2min]

Entraînement:  10%|█         | 1003/10000 [03:13<1:18:02,  1.92step/s, loss=0.058652, elapsed=3.2min]

Entraînement:  10%|█         | 1003/10000 [03:13<1:18:02,  1.92step/s, loss=0.055775, elapsed=3.2min]

Entraînement:  10%|█         | 1004/10000 [03:13<1:03:09,  2.37step/s, loss=0.055775, elapsed=3.2min]

Entraînement:  10%|█         | 1004/10000 [03:13<1:03:09,  2.37step/s, loss=0.058664, elapsed=3.2min]

Entraînement:  10%|█         | 1005/10000 [03:13<52:43,  2.84step/s, loss=0.058664, elapsed=3.2min]

Entraînement:  10%|█         | 1005/10000 [03:13<52:43,  2.84step/s, loss=0.062760, elapsed=3.2min]

Entraînement:  10%|█         | 1006/10000 [03:13<45:22,  3.30step/s, loss=0.062760, elapsed=3.2min]

Entraînement:  10%|█         | 1006/10000 [03:13<45:22,  3.30step/s, loss=0.056360, elapsed=3.2min]

Entraînement:  10%|█         | 1007/10000 [03:13<40:18,  3.72step/s, loss=0.056360, elapsed=3.2min]

Entraînement:  10%|█         | 1007/10000 [03:13<40:18,  3.72step/s, loss=0.054545, elapsed=3.2min]

Entraînement:  10%|█         | 1008/10000 [03:14<36:43,  4.08step/s, loss=0.054545, elapsed=3.2min]

Entraînement:  10%|█         | 1008/10000 [03:14<36:43,  4.08step/s, loss=0.131678, elapsed=3.2min]

Entraînement:  10%|█         | 1009/10000 [03:14<34:10,  4.38step/s, loss=0.131678, elapsed=3.2min]

Entraînement:  10%|█         | 1009/10000 [03:14<34:10,  4.38step/s, loss=0.049578, elapsed=3.2min]

Entraînement:  10%|█         | 1010/10000 [03:14<32:25,  4.62step/s, loss=0.049578, elapsed=3.2min]

Entraînement:  10%|█         | 1010/10000 [03:14<32:25,  4.62step/s, loss=0.071167, elapsed=3.2min]

Entraînement:  10%|█         | 1011/10000 [03:14<31:09,  4.81step/s, loss=0.071167, elapsed=3.2min]

Entraînement:  10%|█         | 1011/10000 [03:14<31:09,  4.81step/s, loss=0.075791, elapsed=3.2min]

Entraînement:  10%|█         | 1012/10000 [03:14<30:21,  4.93step/s, loss=0.075791, elapsed=3.2min]

Entraînement:  10%|█         | 1012/10000 [03:14<30:21,  4.93step/s, loss=0.165218, elapsed=3.2min]

Entraînement:  10%|█         | 1013/10000 [03:15<29:43,  5.04step/s, loss=0.165218, elapsed=3.2min]

Entraînement:  10%|█         | 1013/10000 [03:15<29:43,  5.04step/s, loss=0.055265, elapsed=3.3min]

Entraînement:  10%|█         | 1014/10000 [03:15<29:19,  5.11step/s, loss=0.055265, elapsed=3.3min]

Entraînement:  10%|█         | 1014/10000 [03:15<29:19,  5.11step/s, loss=0.114218, elapsed=3.3min]

Entraînement:  10%|█         | 1015/10000 [03:15<29:00,  5.16step/s, loss=0.114218, elapsed=3.3min]

Entraînement:  10%|█         | 1015/10000 [03:15<29:00,  5.16step/s, loss=0.127913, elapsed=3.3min]

Entraînement:  10%|█         | 1016/10000 [03:15<28:45,  5.21step/s, loss=0.127913, elapsed=3.3min]

Entraînement:  10%|█         | 1016/10000 [03:15<28:45,  5.21step/s, loss=0.067732, elapsed=3.3min]

Entraînement:  10%|█         | 1017/10000 [03:15<28:37,  5.23step/s, loss=0.067732, elapsed=3.3min]

Entraînement:  10%|█         | 1017/10000 [03:15<28:37,  5.23step/s, loss=0.066456, elapsed=3.3min]

Entraînement:  10%|█         | 1018/10000 [03:16<28:29,  5.25step/s, loss=0.066456, elapsed=3.3min]

Entraînement:  10%|█         | 1018/10000 [03:16<28:29,  5.25step/s, loss=0.050069, elapsed=3.3min]

Entraînement:  10%|█         | 1019/10000 [03:16<28:26,  5.26step/s, loss=0.050069, elapsed=3.3min]

Entraînement:  10%|█         | 1019/10000 [03:16<28:26,  5.26step/s, loss=0.059302, elapsed=3.3min]

Entraînement:  10%|█         | 1020/10000 [03:16<28:24,  5.27step/s, loss=0.059302, elapsed=3.3min]

Entraînement:  10%|█         | 1020/10000 [03:16<28:24,  5.27step/s, loss=0.063987, elapsed=3.3min]

Entraînement:  10%|█         | 1021/10000 [03:16<28:23,  5.27step/s, loss=0.063987, elapsed=3.3min]

Entraînement:  10%|█         | 1021/10000 [03:16<28:23,  5.27step/s, loss=0.055073, elapsed=3.3min]

Entraînement:  10%|█         | 1022/10000 [03:16<28:18,  5.29step/s, loss=0.055073, elapsed=3.3min]

Entraînement:  10%|█         | 1022/10000 [03:16<28:18,  5.29step/s, loss=0.056279, elapsed=3.3min]

Entraînement:  10%|█         | 1023/10000 [03:16<28:19,  5.28step/s, loss=0.056279, elapsed=3.3min]

Entraînement:  10%|█         | 1023/10000 [03:16<28:19,  5.28step/s, loss=0.085653, elapsed=3.3min]

Entraînement:  10%|█         | 1024/10000 [03:17<28:19,  5.28step/s, loss=0.085653, elapsed=3.3min]

Entraînement:  10%|█         | 1024/10000 [03:17<28:19,  5.28step/s, loss=0.082578, elapsed=3.3min]

Entraînement:  10%|█         | 1025/10000 [03:17<28:19,  5.28step/s, loss=0.082578, elapsed=3.3min]

Entraînement:  10%|█         | 1025/10000 [03:17<28:19,  5.28step/s, loss=0.083623, elapsed=3.3min]

Entraînement:  10%|█         | 1026/10000 [03:17<28:20,  5.28step/s, loss=0.083623, elapsed=3.3min]

Entraînement:  10%|█         | 1026/10000 [03:17<28:20,  5.28step/s, loss=0.068727, elapsed=3.3min]

Entraînement:  10%|█         | 1027/10000 [03:17<28:19,  5.28step/s, loss=0.068727, elapsed=3.3min]

Entraînement:  10%|█         | 1027/10000 [03:17<28:19,  5.28step/s, loss=0.063881, elapsed=3.3min]

Entraînement:  10%|█         | 1028/10000 [03:17<28:20,  5.28step/s, loss=0.063881, elapsed=3.3min]

Entraînement:  10%|█         | 1028/10000 [03:17<28:20,  5.28step/s, loss=0.048311, elapsed=3.3min]

Entraînement:  10%|█         | 1029/10000 [03:18<28:09,  5.31step/s, loss=0.048311, elapsed=3.3min]

Entraînement:  10%|█         | 1029/10000 [03:18<28:09,  5.31step/s, loss=0.110658, elapsed=3.3min]

Entraînement:  10%|█         | 1030/10000 [03:18<28:00,  5.34step/s, loss=0.110658, elapsed=3.3min]

Entraînement:  10%|█         | 1030/10000 [03:18<28:00,  5.34step/s, loss=0.073517, elapsed=3.3min]

Entraînement:  10%|█         | 1031/10000 [03:18<28:11,  5.30step/s, loss=0.073517, elapsed=3.3min]

Entraînement:  10%|█         | 1031/10000 [03:18<28:11,  5.30step/s, loss=0.116913, elapsed=3.3min]

Entraînement:  10%|█         | 1032/10000 [03:18<28:12,  5.30step/s, loss=0.116913, elapsed=3.3min]

Entraînement:  10%|█         | 1032/10000 [03:18<28:12,  5.30step/s, loss=0.069249, elapsed=3.3min]

Entraînement:  10%|█         | 1033/10000 [03:18<28:16,  5.29step/s, loss=0.069249, elapsed=3.3min]

Entraînement:  10%|█         | 1033/10000 [03:18<28:16,  5.29step/s, loss=0.102655, elapsed=3.3min]

Entraînement:  10%|█         | 1034/10000 [03:19<28:17,  5.28step/s, loss=0.102655, elapsed=3.3min]

Entraînement:  10%|█         | 1034/10000 [03:19<28:17,  5.28step/s, loss=0.050397, elapsed=3.3min]

Entraînement:  10%|█         | 1035/10000 [03:19<28:21,  5.27step/s, loss=0.050397, elapsed=3.3min]

Entraînement:  10%|█         | 1035/10000 [03:19<28:21,  5.27step/s, loss=0.069550, elapsed=3.3min]

Entraînement:  10%|█         | 1036/10000 [03:19<28:17,  5.28step/s, loss=0.069550, elapsed=3.3min]

Entraînement:  10%|█         | 1036/10000 [03:19<28:17,  5.28step/s, loss=0.047512, elapsed=3.3min]

Entraînement:  10%|█         | 1037/10000 [03:19<28:21,  5.27step/s, loss=0.047512, elapsed=3.3min]

Entraînement:  10%|█         | 1037/10000 [03:19<28:21,  5.27step/s, loss=0.066440, elapsed=3.3min]

Entraînement:  10%|█         | 1038/10000 [03:19<28:22,  5.27step/s, loss=0.066440, elapsed=3.3min]

Entraînement:  10%|█         | 1038/10000 [03:19<28:22,  5.27step/s, loss=0.181396, elapsed=3.3min]

Entraînement:  10%|█         | 1039/10000 [03:19<28:15,  5.29step/s, loss=0.181396, elapsed=3.3min]

Entraînement:  10%|█         | 1039/10000 [03:19<28:15,  5.29step/s, loss=0.094840, elapsed=3.3min]

Entraînement:  10%|█         | 1040/10000 [03:20<28:14,  5.29step/s, loss=0.094840, elapsed=3.3min]

Entraînement:  10%|█         | 1040/10000 [03:20<28:14,  5.29step/s, loss=0.064594, elapsed=3.3min]

Entraînement:  10%|█         | 1041/10000 [03:20<28:11,  5.30step/s, loss=0.064594, elapsed=3.3min]

Entraînement:  10%|█         | 1041/10000 [03:20<28:11,  5.30step/s, loss=0.103154, elapsed=3.3min]

Entraînement:  10%|█         | 1042/10000 [03:20<28:10,  5.30step/s, loss=0.103154, elapsed=3.3min]

Entraînement:  10%|█         | 1042/10000 [03:20<28:10,  5.30step/s, loss=0.073202, elapsed=3.3min]

Entraînement:  10%|█         | 1043/10000 [03:20<28:40,  5.21step/s, loss=0.073202, elapsed=3.3min]

Entraînement:  10%|█         | 1043/10000 [03:20<28:40,  5.21step/s, loss=0.077869, elapsed=3.3min]

Entraînement:  10%|█         | 1044/10000 [03:20<28:31,  5.23step/s, loss=0.077869, elapsed=3.3min]

Entraînement:  10%|█         | 1044/10000 [03:20<28:31,  5.23step/s, loss=0.038525, elapsed=3.3min]

Entraînement:  10%|█         | 1045/10000 [03:21<28:24,  5.25step/s, loss=0.038525, elapsed=3.3min]

Entraînement:  10%|█         | 1045/10000 [03:21<28:24,  5.25step/s, loss=0.045179, elapsed=3.4min]

Entraînement:  10%|█         | 1046/10000 [03:21<28:17,  5.27step/s, loss=0.045179, elapsed=3.4min]

Entraînement:  10%|█         | 1046/10000 [03:21<28:17,  5.27step/s, loss=0.035936, elapsed=3.4min]

Entraînement:  10%|█         | 1047/10000 [03:21<28:14,  5.28step/s, loss=0.035936, elapsed=3.4min]

Entraînement:  10%|█         | 1047/10000 [03:21<28:14,  5.28step/s, loss=0.135470, elapsed=3.4min]

Entraînement:  10%|█         | 1048/10000 [03:21<28:13,  5.29step/s, loss=0.135470, elapsed=3.4min]

Entraînement:  10%|█         | 1048/10000 [03:21<28:13,  5.29step/s, loss=0.062087, elapsed=3.4min]

Entraînement:  10%|█         | 1049/10000 [03:21<28:10,  5.30step/s, loss=0.062087, elapsed=3.4min]

Entraînement:  10%|█         | 1049/10000 [03:21<28:10,  5.30step/s, loss=0.061768, elapsed=3.4min]

Entraînement:  10%|█         | 1050/10000 [03:22<28:11,  5.29step/s, loss=0.061768, elapsed=3.4min]

Entraînement:  10%|█         | 1050/10000 [03:22<28:11,  5.29step/s, loss=0.152631, elapsed=3.4min]

Entraînement:  11%|█         | 1051/10000 [03:22<28:09,  5.30step/s, loss=0.152631, elapsed=3.4min]

Entraînement:  11%|█         | 1051/10000 [03:22<28:09,  5.30step/s, loss=0.054191, elapsed=3.4min]

Entraînement:  11%|█         | 1052/10000 [03:22<28:10,  5.29step/s, loss=0.054191, elapsed=3.4min]

Entraînement:  11%|█         | 1052/10000 [03:22<28:10,  5.29step/s, loss=0.042935, elapsed=3.4min]

Entraînement:  11%|█         | 1053/10000 [03:22<28:13,  5.28step/s, loss=0.042935, elapsed=3.4min]

Entraînement:  11%|█         | 1053/10000 [03:22<28:13,  5.28step/s, loss=0.063459, elapsed=3.4min]

Entraînement:  11%|█         | 1054/10000 [03:22<28:08,  5.30step/s, loss=0.063459, elapsed=3.4min]

Entraînement:  11%|█         | 1054/10000 [03:22<28:08,  5.30step/s, loss=0.085729, elapsed=3.4min]

Entraînement:  11%|█         | 1055/10000 [03:23<28:11,  5.29step/s, loss=0.085729, elapsed=3.4min]

Entraînement:  11%|█         | 1055/10000 [03:23<28:11,  5.29step/s, loss=0.064782, elapsed=3.4min]

Entraînement:  11%|█         | 1056/10000 [03:23<28:10,  5.29step/s, loss=0.064782, elapsed=3.4min]

Entraînement:  11%|█         | 1056/10000 [03:23<28:10,  5.29step/s, loss=0.136804, elapsed=3.4min]

Entraînement:  11%|█         | 1057/10000 [03:23<28:10,  5.29step/s, loss=0.136804, elapsed=3.4min]

Entraînement:  11%|█         | 1057/10000 [03:23<28:10,  5.29step/s, loss=0.077203, elapsed=3.4min]

Entraînement:  11%|█         | 1058/10000 [03:23<28:10,  5.29step/s, loss=0.077203, elapsed=3.4min]

Entraînement:  11%|█         | 1058/10000 [03:23<28:10,  5.29step/s, loss=0.049812, elapsed=3.4min]

Entraînement:  11%|█         | 1059/10000 [03:23<28:12,  5.28step/s, loss=0.049812, elapsed=3.4min]

Entraînement:  11%|█         | 1059/10000 [03:23<28:12,  5.28step/s, loss=0.048334, elapsed=3.4min]

Entraînement:  11%|█         | 1060/10000 [03:23<28:15,  5.27step/s, loss=0.048334, elapsed=3.4min]

Entraînement:  11%|█         | 1060/10000 [03:23<28:15,  5.27step/s, loss=0.045808, elapsed=3.4min]

Entraînement:  11%|█         | 1061/10000 [03:24<28:15,  5.27step/s, loss=0.045808, elapsed=3.4min]

Entraînement:  11%|█         | 1061/10000 [03:24<28:15,  5.27step/s, loss=0.041312, elapsed=3.4min]

Entraînement:  11%|█         | 1062/10000 [03:24<28:15,  5.27step/s, loss=0.041312, elapsed=3.4min]

Entraînement:  11%|█         | 1062/10000 [03:24<28:15,  5.27step/s, loss=0.141153, elapsed=3.4min]

Entraînement:  11%|█         | 1063/10000 [03:24<28:12,  5.28step/s, loss=0.141153, elapsed=3.4min]

Entraînement:  11%|█         | 1063/10000 [03:24<28:12,  5.28step/s, loss=0.135378, elapsed=3.4min]

Entraînement:  11%|█         | 1064/10000 [03:24<28:11,  5.28step/s, loss=0.135378, elapsed=3.4min]

Entraînement:  11%|█         | 1064/10000 [03:24<28:11,  5.28step/s, loss=0.068966, elapsed=3.4min]

Entraînement:  11%|█         | 1065/10000 [03:24<28:13,  5.28step/s, loss=0.068966, elapsed=3.4min]

Entraînement:  11%|█         | 1065/10000 [03:24<28:13,  5.28step/s, loss=0.061833, elapsed=3.4min]

Entraînement:  11%|█         | 1066/10000 [03:25<28:11,  5.28step/s, loss=0.061833, elapsed=3.4min]

Entraînement:  11%|█         | 1066/10000 [03:25<28:11,  5.28step/s, loss=0.054670, elapsed=3.4min]

Entraînement:  11%|█         | 1067/10000 [03:25<28:13,  5.28step/s, loss=0.054670, elapsed=3.4min]

Entraînement:  11%|█         | 1067/10000 [03:25<28:13,  5.28step/s, loss=0.045682, elapsed=3.4min]

Entraînement:  11%|█         | 1068/10000 [03:25<28:14,  5.27step/s, loss=0.045682, elapsed=3.4min]

Entraînement:  11%|█         | 1068/10000 [03:25<28:14,  5.27step/s, loss=0.103417, elapsed=3.4min]

Entraînement:  11%|█         | 1069/10000 [03:25<28:10,  5.28step/s, loss=0.103417, elapsed=3.4min]

Entraînement:  11%|█         | 1069/10000 [03:25<28:10,  5.28step/s, loss=0.064287, elapsed=3.4min]

Entraînement:  11%|█         | 1070/10000 [03:25<28:11,  5.28step/s, loss=0.064287, elapsed=3.4min]

Entraînement:  11%|█         | 1070/10000 [03:25<28:11,  5.28step/s, loss=0.052116, elapsed=3.4min]

Entraînement:  11%|█         | 1071/10000 [03:26<28:08,  5.29step/s, loss=0.052116, elapsed=3.4min]

Entraînement:  11%|█         | 1071/10000 [03:26<28:08,  5.29step/s, loss=0.066627, elapsed=3.4min]

Entraînement:  11%|█         | 1072/10000 [03:26<28:08,  5.29step/s, loss=0.066627, elapsed=3.4min]

Entraînement:  11%|█         | 1072/10000 [03:26<28:08,  5.29step/s, loss=0.073504, elapsed=3.4min]

Entraînement:  11%|█         | 1073/10000 [03:26<28:14,  5.27step/s, loss=0.073504, elapsed=3.4min]

Entraînement:  11%|█         | 1073/10000 [03:26<28:14,  5.27step/s, loss=0.115855, elapsed=3.4min]

Entraînement:  11%|█         | 1074/10000 [03:26<28:11,  5.28step/s, loss=0.115855, elapsed=3.4min]

Entraînement:  11%|█         | 1074/10000 [03:26<28:11,  5.28step/s, loss=0.063179, elapsed=3.4min]

Entraînement:  11%|█         | 1075/10000 [03:26<28:12,  5.27step/s, loss=0.063179, elapsed=3.4min]

Entraînement:  11%|█         | 1075/10000 [03:26<28:12,  5.27step/s, loss=0.147685, elapsed=3.4min]

Entraînement:  11%|█         | 1076/10000 [03:26<28:09,  5.28step/s, loss=0.147685, elapsed=3.4min]

Entraînement:  11%|█         | 1076/10000 [03:26<28:09,  5.28step/s, loss=0.045404, elapsed=3.5min]

Entraînement:  11%|█         | 1077/10000 [03:27<28:10,  5.28step/s, loss=0.045404, elapsed=3.5min]

Entraînement:  11%|█         | 1077/10000 [03:27<28:10,  5.28step/s, loss=0.051280, elapsed=3.5min]

Entraînement:  11%|█         | 1078/10000 [03:27<28:06,  5.29step/s, loss=0.051280, elapsed=3.5min]

Entraînement:  11%|█         | 1078/10000 [03:27<28:06,  5.29step/s, loss=0.033664, elapsed=3.5min]

Entraînement:  11%|█         | 1079/10000 [03:27<28:04,  5.30step/s, loss=0.033664, elapsed=3.5min]

Entraînement:  11%|█         | 1079/10000 [03:27<28:04,  5.30step/s, loss=0.037150, elapsed=3.5min]

Entraînement:  11%|█         | 1080/10000 [03:27<28:04,  5.30step/s, loss=0.037150, elapsed=3.5min]

Entraînement:  11%|█         | 1080/10000 [03:27<28:04,  5.30step/s, loss=0.135588, elapsed=3.5min]

Entraînement:  11%|█         | 1081/10000 [03:27<28:03,  5.30step/s, loss=0.135588, elapsed=3.5min]

Entraînement:  11%|█         | 1081/10000 [03:27<28:03,  5.30step/s, loss=0.067401, elapsed=3.5min]

Entraînement:  11%|█         | 1082/10000 [03:28<28:07,  5.28step/s, loss=0.067401, elapsed=3.5min]

Entraînement:  11%|█         | 1082/10000 [03:28<28:07,  5.28step/s, loss=0.131647, elapsed=3.5min]

Entraînement:  11%|█         | 1083/10000 [03:28<28:10,  5.27step/s, loss=0.131647, elapsed=3.5min]

Entraînement:  11%|█         | 1083/10000 [03:28<28:10,  5.27step/s, loss=0.077130, elapsed=3.5min]

Entraînement:  11%|█         | 1084/10000 [03:28<28:11,  5.27step/s, loss=0.077130, elapsed=3.5min]

Entraînement:  11%|█         | 1084/10000 [03:28<28:11,  5.27step/s, loss=0.109643, elapsed=3.5min]

Entraînement:  11%|█         | 1085/10000 [03:28<28:10,  5.27step/s, loss=0.109643, elapsed=3.5min]

Entraînement:  11%|█         | 1085/10000 [03:28<28:10,  5.27step/s, loss=0.054856, elapsed=3.5min]

Entraînement:  11%|█         | 1086/10000 [03:28<28:06,  5.29step/s, loss=0.054856, elapsed=3.5min]

Entraînement:  11%|█         | 1086/10000 [03:28<28:06,  5.29step/s, loss=0.072050, elapsed=3.5min]

Entraînement:  11%|█         | 1087/10000 [03:29<28:07,  5.28step/s, loss=0.072050, elapsed=3.5min]

Entraînement:  11%|█         | 1087/10000 [03:29<28:07,  5.28step/s, loss=0.053440, elapsed=3.5min]

Entraînement:  11%|█         | 1088/10000 [03:29<28:07,  5.28step/s, loss=0.053440, elapsed=3.5min]

Entraînement:  11%|█         | 1088/10000 [03:29<28:07,  5.28step/s, loss=0.065993, elapsed=3.5min]

Entraînement:  11%|█         | 1089/10000 [03:29<28:06,  5.28step/s, loss=0.065993, elapsed=3.5min]

Entraînement:  11%|█         | 1089/10000 [03:29<28:06,  5.28step/s, loss=0.064324, elapsed=3.5min]

Entraînement:  11%|█         | 1090/10000 [03:29<28:08,  5.28step/s, loss=0.064324, elapsed=3.5min]

Entraînement:  11%|█         | 1090/10000 [03:29<28:08,  5.28step/s, loss=0.023918, elapsed=3.5min]

Entraînement:  11%|█         | 1091/10000 [03:29<28:09,  5.27step/s, loss=0.023918, elapsed=3.5min]

Entraînement:  11%|█         | 1091/10000 [03:29<28:09,  5.27step/s, loss=0.043726, elapsed=3.5min]

Entraînement:  11%|█         | 1092/10000 [03:30<28:10,  5.27step/s, loss=0.043726, elapsed=3.5min]

Entraînement:  11%|█         | 1092/10000 [03:30<28:10,  5.27step/s, loss=0.067709, elapsed=3.5min]

Entraînement:  11%|█         | 1093/10000 [03:30<28:09,  5.27step/s, loss=0.067709, elapsed=3.5min]

Entraînement:  11%|█         | 1093/10000 [03:30<28:09,  5.27step/s, loss=0.090830, elapsed=3.5min]

Entraînement:  11%|█         | 1094/10000 [03:30<28:09,  5.27step/s, loss=0.090830, elapsed=3.5min]

Entraînement:  11%|█         | 1094/10000 [03:30<28:09,  5.27step/s, loss=0.051005, elapsed=3.5min]

Entraînement:  11%|█         | 1095/10000 [03:30<28:08,  5.27step/s, loss=0.051005, elapsed=3.5min]

Entraînement:  11%|█         | 1095/10000 [03:30<28:08,  5.27step/s, loss=0.040715, elapsed=3.5min]

Entraînement:  11%|█         | 1096/10000 [03:30<28:10,  5.27step/s, loss=0.040715, elapsed=3.5min]

Entraînement:  11%|█         | 1096/10000 [03:30<28:10,  5.27step/s, loss=0.033221, elapsed=3.5min]

Entraînement:  11%|█         | 1097/10000 [03:30<28:07,  5.28step/s, loss=0.033221, elapsed=3.5min]

Entraînement:  11%|█         | 1097/10000 [03:30<28:07,  5.28step/s, loss=0.072758, elapsed=3.5min]

Entraînement:  11%|█         | 1098/10000 [03:31<28:04,  5.29step/s, loss=0.072758, elapsed=3.5min]

Entraînement:  11%|█         | 1098/10000 [03:31<28:04,  5.29step/s, loss=0.034974, elapsed=3.5min]

Entraînement:  11%|█         | 1099/10000 [03:31<28:03,  5.29step/s, loss=0.034974, elapsed=3.5min]

Entraînement:  11%|█         | 1099/10000 [03:31<28:03,  5.29step/s, loss=0.046095, elapsed=3.5min]

Entraînement:  11%|█         | 1100/10000 [03:31<28:01,  5.29step/s, loss=0.046095, elapsed=3.5min]

Entraînement:  11%|█         | 1100/10000 [03:31<28:01,  5.29step/s, loss=0.059801, elapsed=3.5min]

Entraînement:  11%|█         | 1100/10000 [03:31<28:01,  5.29step/s, loss=0.059801, elapsed=3.5min]

Entraînement:  11%|█         | 1101/10000 [03:31<28:25,  5.22step/s, loss=0.059801, elapsed=3.5min]

Entraînement:  11%|█         | 1101/10000 [03:31<28:25,  5.22step/s, loss=0.046156, elapsed=3.5min]

Step 1100/10000 | Train loss: 0.059801 | Elapsed: 3.5min | ETA: 28.5min

Entraînement:  11%|█         | 1102/10000 [03:31<28:22,  5.23step/s, loss=0.046156, elapsed=3.5min]

Entraînement:  11%|█         | 1102/10000 [03:31<28:22,  5.23step/s, loss=0.056497, elapsed=3.5min]

Entraînement:  11%|█         | 1103/10000 [03:32<28:18,  5.24step/s, loss=0.056497, elapsed=3.5min]

Entraînement:  11%|█         | 1103/10000 [03:32<28:18,  5.24step/s, loss=0.047136, elapsed=3.5min]

Entraînement:  11%|█         | 1104/10000 [03:32<28:25,  5.22step/s, loss=0.047136, elapsed=3.5min]

Entraînement:  11%|█         | 1104/10000 [03:32<28:25,  5.22step/s, loss=0.067009, elapsed=3.5min]

Entraînement:  11%|█         | 1105/10000 [03:32<28:21,  5.23step/s, loss=0.067009, elapsed=3.5min]

Entraînement:  11%|█         | 1105/10000 [03:32<28:21,  5.23step/s, loss=0.087755, elapsed=3.5min]

Entraînement:  11%|█         | 1106/10000 [03:32<28:18,  5.24step/s, loss=0.087755, elapsed=3.5min]

Entraînement:  11%|█         | 1106/10000 [03:32<28:18,  5.24step/s, loss=0.055650, elapsed=3.5min]

Entraînement:  11%|█         | 1107/10000 [03:32<28:14,  5.25step/s, loss=0.055650, elapsed=3.5min]

Entraînement:  11%|█         | 1107/10000 [03:32<28:14,  5.25step/s, loss=0.071981, elapsed=3.5min]

Entraînement:  11%|█         | 1108/10000 [03:33<28:08,  5.26step/s, loss=0.071981, elapsed=3.5min]

Entraînement:  11%|█         | 1108/10000 [03:33<28:08,  5.26step/s, loss=0.039467, elapsed=3.6min]

Entraînement:  11%|█         | 1109/10000 [03:33<28:05,  5.27step/s, loss=0.039467, elapsed=3.6min]

Entraînement:  11%|█         | 1109/10000 [03:33<28:05,  5.27step/s, loss=0.106061, elapsed=3.6min]

Entraînement:  11%|█         | 1110/10000 [03:33<28:02,  5.28step/s, loss=0.106061, elapsed=3.6min]

Entraînement:  11%|█         | 1110/10000 [03:33<28:02,  5.28step/s, loss=0.101536, elapsed=3.6min]

Entraînement:  11%|█         | 1111/10000 [03:33<27:59,  5.29step/s, loss=0.101536, elapsed=3.6min]

Entraînement:  11%|█         | 1111/10000 [03:33<27:59,  5.29step/s, loss=0.092962, elapsed=3.6min]

Entraînement:  11%|█         | 1112/10000 [03:33<27:59,  5.29step/s, loss=0.092962, elapsed=3.6min]

Entraînement:  11%|█         | 1112/10000 [03:33<27:59,  5.29step/s, loss=0.120545, elapsed=3.6min]

Entraînement:  11%|█         | 1113/10000 [03:34<28:01,  5.29step/s, loss=0.120545, elapsed=3.6min]

Entraînement:  11%|█         | 1113/10000 [03:34<28:01,  5.29step/s, loss=0.089648, elapsed=3.6min]

Entraînement:  11%|█         | 1114/10000 [03:34<27:59,  5.29step/s, loss=0.089648, elapsed=3.6min]

Entraînement:  11%|█         | 1114/10000 [03:34<27:59,  5.29step/s, loss=0.034920, elapsed=3.6min]

Entraînement:  11%|█         | 1115/10000 [03:34<27:59,  5.29step/s, loss=0.034920, elapsed=3.6min]

Entraînement:  11%|█         | 1115/10000 [03:34<27:59,  5.29step/s, loss=0.117134, elapsed=3.6min]

Entraînement:  11%|█         | 1116/10000 [03:34<27:57,  5.30step/s, loss=0.117134, elapsed=3.6min]

Entraînement:  11%|█         | 1116/10000 [03:34<27:57,  5.30step/s, loss=0.034167, elapsed=3.6min]

Entraînement:  11%|█         | 1117/10000 [03:34<27:57,  5.30step/s, loss=0.034167, elapsed=3.6min]

Entraînement:  11%|█         | 1117/10000 [03:34<27:57,  5.30step/s, loss=0.074366, elapsed=3.6min]

Entraînement:  11%|█         | 1118/10000 [03:34<27:56,  5.30step/s, loss=0.074366, elapsed=3.6min]

Entraînement:  11%|█         | 1118/10000 [03:34<27:56,  5.30step/s, loss=0.033376, elapsed=3.6min]

Entraînement:  11%|█         | 1119/10000 [03:35<27:54,  5.30step/s, loss=0.033376, elapsed=3.6min]

Entraînement:  11%|█         | 1119/10000 [03:35<27:54,  5.30step/s, loss=0.051763, elapsed=3.6min]

Entraînement:  11%|█         | 1120/10000 [03:35<27:55,  5.30step/s, loss=0.051763, elapsed=3.6min]

Entraînement:  11%|█         | 1120/10000 [03:35<27:55,  5.30step/s, loss=0.124399, elapsed=3.6min]

Entraînement:  11%|█         | 1121/10000 [03:35<27:56,  5.30step/s, loss=0.124399, elapsed=3.6min]

Entraînement:  11%|█         | 1121/10000 [03:35<27:56,  5.30step/s, loss=0.094336, elapsed=3.6min]

Entraînement:  11%|█         | 1122/10000 [03:35<27:57,  5.29step/s, loss=0.094336, elapsed=3.6min]

Entraînement:  11%|█         | 1122/10000 [03:35<27:57,  5.29step/s, loss=0.054218, elapsed=3.6min]

Entraînement:  11%|█         | 1123/10000 [03:35<27:58,  5.29step/s, loss=0.054218, elapsed=3.6min]

Entraînement:  11%|█         | 1123/10000 [03:35<27:58,  5.29step/s, loss=0.057274, elapsed=3.6min]

Entraînement:  11%|█         | 1124/10000 [03:36<27:57,  5.29step/s, loss=0.057274, elapsed=3.6min]

Entraînement:  11%|█         | 1124/10000 [03:36<27:57,  5.29step/s, loss=0.026640, elapsed=3.6min]

Entraînement:  11%|█▏        | 1125/10000 [03:36<27:56,  5.29step/s, loss=0.026640, elapsed=3.6min]

Entraînement:  11%|█▏        | 1125/10000 [03:36<27:56,  5.29step/s, loss=0.039708, elapsed=3.6min]

Entraînement:  11%|█▏        | 1126/10000 [03:36<27:54,  5.30step/s, loss=0.039708, elapsed=3.6min]

Entraînement:  11%|█▏        | 1126/10000 [03:36<27:54,  5.30step/s, loss=0.180820, elapsed=3.6min]

Entraînement:  11%|█▏        | 1127/10000 [03:36<27:54,  5.30step/s, loss=0.180820, elapsed=3.6min]

Entraînement:  11%|█▏        | 1127/10000 [03:36<27:54,  5.30step/s, loss=0.059925, elapsed=3.6min]

Entraînement:  11%|█▏        | 1128/10000 [03:36<27:55,  5.29step/s, loss=0.059925, elapsed=3.6min]

Entraînement:  11%|█▏        | 1128/10000 [03:36<27:55,  5.29step/s, loss=0.026503, elapsed=3.6min]

Entraînement:  11%|█▏        | 1129/10000 [03:37<27:59,  5.28step/s, loss=0.026503, elapsed=3.6min]

Entraînement:  11%|█▏        | 1129/10000 [03:37<27:59,  5.28step/s, loss=0.078848, elapsed=3.6min]

Entraînement:  11%|█▏        | 1130/10000 [03:37<27:58,  5.28step/s, loss=0.078848, elapsed=3.6min]

Entraînement:  11%|█▏        | 1130/10000 [03:37<27:58,  5.28step/s, loss=0.058292, elapsed=3.6min]

Entraînement:  11%|█▏        | 1131/10000 [03:37<27:57,  5.29step/s, loss=0.058292, elapsed=3.6min]

Entraînement:  11%|█▏        | 1131/10000 [03:37<27:57,  5.29step/s, loss=0.095773, elapsed=3.6min]

Entraînement:  11%|█▏        | 1132/10000 [03:37<27:59,  5.28step/s, loss=0.095773, elapsed=3.6min]

Entraînement:  11%|█▏        | 1132/10000 [03:37<27:59,  5.28step/s, loss=0.113402, elapsed=3.6min]

Entraînement:  11%|█▏        | 1133/10000 [03:37<27:57,  5.29step/s, loss=0.113402, elapsed=3.6min]

Entraînement:  11%|█▏        | 1133/10000 [03:37<27:57,  5.29step/s, loss=0.079266, elapsed=3.6min]

Entraînement:  11%|█▏        | 1134/10000 [03:37<27:57,  5.29step/s, loss=0.079266, elapsed=3.6min]

Entraînement:  11%|█▏        | 1134/10000 [03:37<27:57,  5.29step/s, loss=0.091896, elapsed=3.6min]

Entraînement:  11%|█▏        | 1135/10000 [03:38<27:58,  5.28step/s, loss=0.091896, elapsed=3.6min]

Entraînement:  11%|█▏        | 1135/10000 [03:38<27:58,  5.28step/s, loss=0.119900, elapsed=3.6min]

Entraînement:  11%|█▏        | 1136/10000 [03:38<27:58,  5.28step/s, loss=0.119900, elapsed=3.6min]

Entraînement:  11%|█▏        | 1136/10000 [03:38<27:58,  5.28step/s, loss=0.074975, elapsed=3.6min]

Entraînement:  11%|█▏        | 1137/10000 [03:38<28:00,  5.27step/s, loss=0.074975, elapsed=3.6min]

Entraînement:  11%|█▏        | 1137/10000 [03:38<28:00,  5.27step/s, loss=0.075797, elapsed=3.6min]

Entraînement:  11%|█▏        | 1138/10000 [03:38<28:02,  5.27step/s, loss=0.075797, elapsed=3.6min]

Entraînement:  11%|█▏        | 1138/10000 [03:38<28:02,  5.27step/s, loss=0.079845, elapsed=3.6min]

Entraînement:  11%|█▏        | 1139/10000 [03:38<27:59,  5.28step/s, loss=0.079845, elapsed=3.6min]

Entraînement:  11%|█▏        | 1139/10000 [03:38<27:59,  5.28step/s, loss=0.095321, elapsed=3.6min]

Entraînement:  11%|█▏        | 1140/10000 [03:39<28:06,  5.25step/s, loss=0.095321, elapsed=3.6min]

Entraînement:  11%|█▏        | 1140/10000 [03:39<28:06,  5.25step/s, loss=0.051048, elapsed=3.7min]

Entraînement:  11%|█▏        | 1141/10000 [03:39<28:04,  5.26step/s, loss=0.051048, elapsed=3.7min]

Entraînement:  11%|█▏        | 1141/10000 [03:39<28:04,  5.26step/s, loss=0.123365, elapsed=3.7min]

Entraînement:  11%|█▏        | 1142/10000 [03:39<28:01,  5.27step/s, loss=0.123365, elapsed=3.7min]

Entraînement:  11%|█▏        | 1142/10000 [03:39<28:01,  5.27step/s, loss=0.080557, elapsed=3.7min]

Entraînement:  11%|█▏        | 1143/10000 [03:39<27:57,  5.28step/s, loss=0.080557, elapsed=3.7min]

Entraînement:  11%|█▏        | 1143/10000 [03:39<27:57,  5.28step/s, loss=0.042730, elapsed=3.7min]

Entraînement:  11%|█▏        | 1144/10000 [03:39<27:54,  5.29step/s, loss=0.042730, elapsed=3.7min]

Entraînement:  11%|█▏        | 1144/10000 [03:39<27:54,  5.29step/s, loss=0.095722, elapsed=3.7min]

Entraînement:  11%|█▏        | 1145/10000 [03:40<28:02,  5.26step/s, loss=0.095722, elapsed=3.7min]

Entraînement:  11%|█▏        | 1145/10000 [03:40<28:02,  5.26step/s, loss=0.079784, elapsed=3.7min]

Entraînement:  11%|█▏        | 1146/10000 [03:40<27:58,  5.27step/s, loss=0.079784, elapsed=3.7min]

Entraînement:  11%|█▏        | 1146/10000 [03:40<27:58,  5.27step/s, loss=0.070975, elapsed=3.7min]

Entraînement:  11%|█▏        | 1147/10000 [03:40<28:00,  5.27step/s, loss=0.070975, elapsed=3.7min]

Entraînement:  11%|█▏        | 1147/10000 [03:40<28:00,  5.27step/s, loss=0.065760, elapsed=3.7min]

Entraînement:  11%|█▏        | 1148/10000 [03:40<27:59,  5.27step/s, loss=0.065760, elapsed=3.7min]

Entraînement:  11%|█▏        | 1148/10000 [03:40<27:59,  5.27step/s, loss=0.052412, elapsed=3.7min]

Entraînement:  11%|█▏        | 1149/10000 [03:40<27:57,  5.28step/s, loss=0.052412, elapsed=3.7min]

Entraînement:  11%|█▏        | 1149/10000 [03:40<27:57,  5.28step/s, loss=0.147590, elapsed=3.7min]

Entraînement:  12%|█▏        | 1150/10000 [03:41<27:55,  5.28step/s, loss=0.147590, elapsed=3.7min]

Entraînement:  12%|█▏        | 1150/10000 [03:41<27:55,  5.28step/s, loss=0.201322, elapsed=3.7min]

Entraînement:  12%|█▏        | 1151/10000 [03:41<27:56,  5.28step/s, loss=0.201322, elapsed=3.7min]

Entraînement:  12%|█▏        | 1151/10000 [03:41<27:56,  5.28step/s, loss=0.119513, elapsed=3.7min]

Entraînement:  12%|█▏        | 1152/10000 [03:41<27:58,  5.27step/s, loss=0.119513, elapsed=3.7min]

Entraînement:  12%|█▏        | 1152/10000 [03:41<27:58,  5.27step/s, loss=0.050737, elapsed=3.7min]

Entraînement:  12%|█▏        | 1153/10000 [03:41<27:57,  5.27step/s, loss=0.050737, elapsed=3.7min]

Entraînement:  12%|█▏        | 1153/10000 [03:41<27:57,  5.27step/s, loss=0.069949, elapsed=3.7min]

Entraînement:  12%|█▏        | 1154/10000 [03:41<27:59,  5.27step/s, loss=0.069949, elapsed=3.7min]

Entraînement:  12%|█▏        | 1154/10000 [03:41<27:59,  5.27step/s, loss=0.052051, elapsed=3.7min]

Entraînement:  12%|█▏        | 1155/10000 [03:41<27:57,  5.27step/s, loss=0.052051, elapsed=3.7min]

Entraînement:  12%|█▏        | 1155/10000 [03:41<27:57,  5.27step/s, loss=0.065543, elapsed=3.7min]

Entraînement:  12%|█▏        | 1156/10000 [03:42<28:04,  5.25step/s, loss=0.065543, elapsed=3.7min]

Entraînement:  12%|█▏        | 1156/10000 [03:42<28:04,  5.25step/s, loss=0.058148, elapsed=3.7min]

Entraînement:  12%|█▏        | 1157/10000 [03:42<28:00,  5.26step/s, loss=0.058148, elapsed=3.7min]

Entraînement:  12%|█▏        | 1157/10000 [03:42<28:00,  5.26step/s, loss=0.061086, elapsed=3.7min]

Entraînement:  12%|█▏        | 1158/10000 [03:42<27:56,  5.27step/s, loss=0.061086, elapsed=3.7min]

Entraînement:  12%|█▏        | 1158/10000 [03:42<27:56,  5.27step/s, loss=0.031870, elapsed=3.7min]

Entraînement:  12%|█▏        | 1159/10000 [03:42<27:55,  5.28step/s, loss=0.031870, elapsed=3.7min]

Entraînement:  12%|█▏        | 1159/10000 [03:42<27:55,  5.28step/s, loss=0.050135, elapsed=3.7min]

Entraînement:  12%|█▏        | 1160/10000 [03:42<27:55,  5.28step/s, loss=0.050135, elapsed=3.7min]

Entraînement:  12%|█▏        | 1160/10000 [03:42<27:55,  5.28step/s, loss=0.031963, elapsed=3.7min]

Entraînement:  12%|█▏        | 1161/10000 [03:43<28:03,  5.25step/s, loss=0.031963, elapsed=3.7min]

Entraînement:  12%|█▏        | 1161/10000 [03:43<28:03,  5.25step/s, loss=0.058245, elapsed=3.7min]

Entraînement:  12%|█▏        | 1162/10000 [03:43<27:57,  5.27step/s, loss=0.058245, elapsed=3.7min]

Entraînement:  12%|█▏        | 1162/10000 [03:43<27:57,  5.27step/s, loss=0.044426, elapsed=3.7min]

Entraînement:  12%|█▏        | 1163/10000 [03:43<27:56,  5.27step/s, loss=0.044426, elapsed=3.7min]

Entraînement:  12%|█▏        | 1163/10000 [03:43<27:56,  5.27step/s, loss=0.033122, elapsed=3.7min]

Entraînement:  12%|█▏        | 1164/10000 [03:43<27:55,  5.27step/s, loss=0.033122, elapsed=3.7min]

Entraînement:  12%|█▏        | 1164/10000 [03:43<27:55,  5.27step/s, loss=0.098391, elapsed=3.7min]

Entraînement:  12%|█▏        | 1165/10000 [03:43<27:57,  5.27step/s, loss=0.098391, elapsed=3.7min]

Entraînement:  12%|█▏        | 1165/10000 [03:43<27:57,  5.27step/s, loss=0.052554, elapsed=3.7min]

Entraînement:  12%|█▏        | 1166/10000 [03:44<27:57,  5.27step/s, loss=0.052554, elapsed=3.7min]

Entraînement:  12%|█▏        | 1166/10000 [03:44<27:57,  5.27step/s, loss=0.059942, elapsed=3.7min]

Entraînement:  12%|█▏        | 1167/10000 [03:44<27:54,  5.27step/s, loss=0.059942, elapsed=3.7min]

Entraînement:  12%|█▏        | 1167/10000 [03:44<27:54,  5.27step/s, loss=0.083716, elapsed=3.7min]

Entraînement:  12%|█▏        | 1168/10000 [03:44<27:59,  5.26step/s, loss=0.083716, elapsed=3.7min]

Entraînement:  12%|█▏        | 1168/10000 [03:44<27:59,  5.26step/s, loss=0.080150, elapsed=3.7min]

Entraînement:  12%|█▏        | 1169/10000 [03:44<27:55,  5.27step/s, loss=0.080150, elapsed=3.7min]

Entraînement:  12%|█▏        | 1169/10000 [03:44<27:55,  5.27step/s, loss=0.094481, elapsed=3.7min]

Entraînement:  12%|█▏        | 1170/10000 [03:44<27:58,  5.26step/s, loss=0.094481, elapsed=3.7min]

Entraînement:  12%|█▏        | 1170/10000 [03:44<27:58,  5.26step/s, loss=0.055656, elapsed=3.7min]

Entraînement:  12%|█▏        | 1171/10000 [03:45<27:56,  5.27step/s, loss=0.055656, elapsed=3.7min]

Entraînement:  12%|█▏        | 1171/10000 [03:45<27:56,  5.27step/s, loss=0.048757, elapsed=3.8min]

Entraînement:  12%|█▏        | 1172/10000 [03:45<27:53,  5.28step/s, loss=0.048757, elapsed=3.8min]

Entraînement:  12%|█▏        | 1172/10000 [03:45<27:53,  5.28step/s, loss=0.138994, elapsed=3.8min]

Entraînement:  12%|█▏        | 1173/10000 [03:45<27:50,  5.28step/s, loss=0.138994, elapsed=3.8min]

Entraînement:  12%|█▏        | 1173/10000 [03:45<27:50,  5.28step/s, loss=0.083216, elapsed=3.8min]

Entraînement:  12%|█▏        | 1174/10000 [03:45<27:47,  5.29step/s, loss=0.083216, elapsed=3.8min]

Entraînement:  12%|█▏        | 1174/10000 [03:45<27:47,  5.29step/s, loss=0.058642, elapsed=3.8min]

Entraînement:  12%|█▏        | 1175/10000 [03:45<27:51,  5.28step/s, loss=0.058642, elapsed=3.8min]

Entraînement:  12%|█▏        | 1175/10000 [03:45<27:51,  5.28step/s, loss=0.048212, elapsed=3.8min]

Entraînement:  12%|█▏        | 1176/10000 [03:45<27:53,  5.27step/s, loss=0.048212, elapsed=3.8min]

Entraînement:  12%|█▏        | 1176/10000 [03:45<27:53,  5.27step/s, loss=0.092907, elapsed=3.8min]

Entraînement:  12%|█▏        | 1177/10000 [03:46<27:50,  5.28step/s, loss=0.092907, elapsed=3.8min]

Entraînement:  12%|█▏        | 1177/10000 [03:46<27:50,  5.28step/s, loss=0.121583, elapsed=3.8min]

Entraînement:  12%|█▏        | 1178/10000 [03:46<27:50,  5.28step/s, loss=0.121583, elapsed=3.8min]

Entraînement:  12%|█▏        | 1178/10000 [03:46<27:50,  5.28step/s, loss=0.047565, elapsed=3.8min]

Entraînement:  12%|█▏        | 1179/10000 [03:46<27:49,  5.28step/s, loss=0.047565, elapsed=3.8min]

Entraînement:  12%|█▏        | 1179/10000 [03:46<27:49,  5.28step/s, loss=0.059770, elapsed=3.8min]

Entraînement:  12%|█▏        | 1180/10000 [03:46<27:51,  5.28step/s, loss=0.059770, elapsed=3.8min]

Entraînement:  12%|█▏        | 1180/10000 [03:46<27:51,  5.28step/s, loss=0.085080, elapsed=3.8min]

Entraînement:  12%|█▏        | 1181/10000 [03:46<28:01,  5.24step/s, loss=0.085080, elapsed=3.8min]

Entraînement:  12%|█▏        | 1181/10000 [03:46<28:01,  5.24step/s, loss=0.056222, elapsed=3.8min]

Entraînement:  12%|█▏        | 1182/10000 [03:47<28:00,  5.25step/s, loss=0.056222, elapsed=3.8min]

Entraînement:  12%|█▏        | 1182/10000 [03:47<28:00,  5.25step/s, loss=0.091159, elapsed=3.8min]

Entraînement:  12%|█▏        | 1183/10000 [03:47<27:59,  5.25step/s, loss=0.091159, elapsed=3.8min]

Entraînement:  12%|█▏        | 1183/10000 [03:47<27:59,  5.25step/s, loss=0.060924, elapsed=3.8min]

Entraînement:  12%|█▏        | 1184/10000 [03:47<27:56,  5.26step/s, loss=0.060924, elapsed=3.8min]

Entraînement:  12%|█▏        | 1184/10000 [03:47<27:56,  5.26step/s, loss=0.065271, elapsed=3.8min]

Entraînement:  12%|█▏        | 1185/10000 [03:47<27:55,  5.26step/s, loss=0.065271, elapsed=3.8min]

Entraînement:  12%|█▏        | 1185/10000 [03:47<27:55,  5.26step/s, loss=0.074289, elapsed=3.8min]

Entraînement:  12%|█▏        | 1186/10000 [03:47<27:52,  5.27step/s, loss=0.074289, elapsed=3.8min]

Entraînement:  12%|█▏        | 1186/10000 [03:47<27:52,  5.27step/s, loss=0.046063, elapsed=3.8min]

Entraînement:  12%|█▏        | 1187/10000 [03:48<27:52,  5.27step/s, loss=0.046063, elapsed=3.8min]

Entraînement:  12%|█▏        | 1187/10000 [03:48<27:52,  5.27step/s, loss=0.075590, elapsed=3.8min]

Entraînement:  12%|█▏        | 1188/10000 [03:48<27:53,  5.27step/s, loss=0.075590, elapsed=3.8min]

Entraînement:  12%|█▏        | 1188/10000 [03:48<27:53,  5.27step/s, loss=0.069742, elapsed=3.8min]

Entraînement:  12%|█▏        | 1189/10000 [03:48<27:53,  5.26step/s, loss=0.069742, elapsed=3.8min]

Entraînement:  12%|█▏        | 1189/10000 [03:48<27:53,  5.26step/s, loss=0.057619, elapsed=3.8min]

Entraînement:  12%|█▏        | 1190/10000 [03:48<27:52,  5.27step/s, loss=0.057619, elapsed=3.8min]

Entraînement:  12%|█▏        | 1190/10000 [03:48<27:52,  5.27step/s, loss=0.071681, elapsed=3.8min]

Entraînement:  12%|█▏        | 1191/10000 [03:48<27:57,  5.25step/s, loss=0.071681, elapsed=3.8min]

Entraînement:  12%|█▏        | 1191/10000 [03:48<27:57,  5.25step/s, loss=0.055449, elapsed=3.8min]

Entraînement:  12%|█▏        | 1192/10000 [03:48<27:54,  5.26step/s, loss=0.055449, elapsed=3.8min]

Entraînement:  12%|█▏        | 1192/10000 [03:48<27:54,  5.26step/s, loss=0.059485, elapsed=3.8min]

Entraînement:  12%|█▏        | 1193/10000 [03:49<27:54,  5.26step/s, loss=0.059485, elapsed=3.8min]

Entraînement:  12%|█▏        | 1193/10000 [03:49<27:54,  5.26step/s, loss=0.119683, elapsed=3.8min]

Entraînement:  12%|█▏        | 1194/10000 [03:49<27:53,  5.26step/s, loss=0.119683, elapsed=3.8min]

Entraînement:  12%|█▏        | 1194/10000 [03:49<27:53,  5.26step/s, loss=0.057913, elapsed=3.8min]

Entraînement:  12%|█▏        | 1195/10000 [03:49<27:49,  5.27step/s, loss=0.057913, elapsed=3.8min]

Entraînement:  12%|█▏        | 1195/10000 [03:49<27:49,  5.27step/s, loss=0.034733, elapsed=3.8min]

Entraînement:  12%|█▏        | 1196/10000 [03:49<27:51,  5.27step/s, loss=0.034733, elapsed=3.8min]

Entraînement:  12%|█▏        | 1196/10000 [03:49<27:51,  5.27step/s, loss=0.045164, elapsed=3.8min]

Entraînement:  12%|█▏        | 1197/10000 [03:49<27:48,  5.27step/s, loss=0.045164, elapsed=3.8min]

Entraînement:  12%|█▏        | 1197/10000 [03:49<27:48,  5.27step/s, loss=0.052870, elapsed=3.8min]

Entraînement:  12%|█▏        | 1198/10000 [03:50<27:53,  5.26step/s, loss=0.052870, elapsed=3.8min]

Entraînement:  12%|█▏        | 1198/10000 [03:50<27:53,  5.26step/s, loss=0.027957, elapsed=3.8min]

Entraînement:  12%|█▏        | 1199/10000 [03:50<27:54,  5.26step/s, loss=0.027957, elapsed=3.8min]

Entraînement:  12%|█▏        | 1199/10000 [03:50<27:54,  5.26step/s, loss=0.068205, elapsed=3.8min]

Entraînement:  12%|█▏        | 1200/10000 [03:50<27:53,  5.26step/s, loss=0.068205, elapsed=3.8min]

Entraînement:  12%|█▏        | 1200/10000 [03:50<27:53,  5.26step/s, loss=0.070468, elapsed=3.8min]

Entraînement:  12%|█▏        | 1200/10000 [03:50<27:53,  5.26step/s, loss=0.070468, elapsed=3.8min]

Entraînement:  12%|█▏        | 1201/10000 [03:50<28:06,  5.22step/s, loss=0.070468, elapsed=3.8min]

Entraînement:  12%|█▏        | 1201/10000 [03:50<28:06,  5.22step/s, loss=0.042607, elapsed=3.8min]

Step 1200/10000 | Train loss: 0.070468 | Elapsed: 3.8min | ETA: 28.2min

Entraînement:  12%|█▏        | 1202/10000 [03:50<28:02,  5.23step/s, loss=0.042607, elapsed=3.8min]

Entraînement:  12%|█▏        | 1202/10000 [03:50<28:02,  5.23step/s, loss=0.053923, elapsed=3.8min]

Entraînement:  12%|█▏        | 1203/10000 [03:51<27:56,  5.25step/s, loss=0.053923, elapsed=3.8min]

Entraînement:  12%|█▏        | 1203/10000 [03:51<27:56,  5.25step/s, loss=0.044920, elapsed=3.9min]

Entraînement:  12%|█▏        | 1204/10000 [03:51<27:51,  5.26step/s, loss=0.044920, elapsed=3.9min]

Entraînement:  12%|█▏        | 1204/10000 [03:51<27:51,  5.26step/s, loss=0.060567, elapsed=3.9min]

Entraînement:  12%|█▏        | 1205/10000 [03:51<27:51,  5.26step/s, loss=0.060567, elapsed=3.9min]

Entraînement:  12%|█▏        | 1205/10000 [03:51<27:51,  5.26step/s, loss=0.058718, elapsed=3.9min]

Entraînement:  12%|█▏        | 1206/10000 [03:51<27:49,  5.27step/s, loss=0.058718, elapsed=3.9min]

Entraînement:  12%|█▏        | 1206/10000 [03:51<27:49,  5.27step/s, loss=0.089662, elapsed=3.9min]

Entraînement:  12%|█▏        | 1207/10000 [03:51<27:50,  5.26step/s, loss=0.089662, elapsed=3.9min]

Entraînement:  12%|█▏        | 1207/10000 [03:51<27:50,  5.26step/s, loss=0.115855, elapsed=3.9min]

Entraînement:  12%|█▏        | 1208/10000 [03:52<27:50,  5.26step/s, loss=0.115855, elapsed=3.9min]

Entraînement:  12%|█▏        | 1208/10000 [03:52<27:50,  5.26step/s, loss=0.049879, elapsed=3.9min]

Entraînement:  12%|█▏        | 1209/10000 [03:52<27:47,  5.27step/s, loss=0.049879, elapsed=3.9min]

Entraînement:  12%|█▏        | 1209/10000 [03:52<27:47,  5.27step/s, loss=0.055252, elapsed=3.9min]

Entraînement:  12%|█▏        | 1210/10000 [03:52<27:53,  5.25step/s, loss=0.055252, elapsed=3.9min]

Entraînement:  12%|█▏        | 1210/10000 [03:52<27:53,  5.25step/s, loss=0.125941, elapsed=3.9min]

Entraînement:  12%|█▏        | 1211/10000 [03:52<27:48,  5.27step/s, loss=0.125941, elapsed=3.9min]

Entraînement:  12%|█▏        | 1211/10000 [03:52<27:48,  5.27step/s, loss=0.086303, elapsed=3.9min]

Entraînement:  12%|█▏        | 1212/10000 [03:52<27:48,  5.27step/s, loss=0.086303, elapsed=3.9min]

Entraînement:  12%|█▏        | 1212/10000 [03:52<27:48,  5.27step/s, loss=0.068846, elapsed=3.9min]

Entraînement:  12%|█▏        | 1213/10000 [03:52<27:47,  5.27step/s, loss=0.068846, elapsed=3.9min]

Entraînement:  12%|█▏        | 1213/10000 [03:52<27:47,  5.27step/s, loss=0.059619, elapsed=3.9min]

Entraînement:  12%|█▏        | 1214/10000 [03:53<27:46,  5.27step/s, loss=0.059619, elapsed=3.9min]

Entraînement:  12%|█▏        | 1214/10000 [03:53<27:46,  5.27step/s, loss=0.093890, elapsed=3.9min]

Entraînement:  12%|█▏        | 1215/10000 [03:53<27:48,  5.27step/s, loss=0.093890, elapsed=3.9min]

Entraînement:  12%|█▏        | 1215/10000 [03:53<27:48,  5.27step/s, loss=0.044704, elapsed=3.9min]

Entraînement:  12%|█▏        | 1216/10000 [03:53<27:43,  5.28step/s, loss=0.044704, elapsed=3.9min]

Entraînement:  12%|█▏        | 1216/10000 [03:53<27:43,  5.28step/s, loss=0.041645, elapsed=3.9min]

Entraînement:  12%|█▏        | 1217/10000 [03:53<27:46,  5.27step/s, loss=0.041645, elapsed=3.9min]

Entraînement:  12%|█▏        | 1217/10000 [03:53<27:46,  5.27step/s, loss=0.078329, elapsed=3.9min]

Entraînement:  12%|█▏        | 1218/10000 [03:53<27:48,  5.26step/s, loss=0.078329, elapsed=3.9min]

Entraînement:  12%|█▏        | 1218/10000 [03:53<27:48,  5.26step/s, loss=0.081819, elapsed=3.9min]

Entraînement:  12%|█▏        | 1219/10000 [03:54<27:50,  5.26step/s, loss=0.081819, elapsed=3.9min]

Entraînement:  12%|█▏        | 1219/10000 [03:54<27:50,  5.26step/s, loss=0.098411, elapsed=3.9min]

Entraînement:  12%|█▏        | 1220/10000 [03:54<27:45,  5.27step/s, loss=0.098411, elapsed=3.9min]

Entraînement:  12%|█▏        | 1220/10000 [03:54<27:45,  5.27step/s, loss=0.096506, elapsed=3.9min]

Entraînement:  12%|█▏        | 1221/10000 [03:54<27:43,  5.28step/s, loss=0.096506, elapsed=3.9min]

Entraînement:  12%|█▏        | 1221/10000 [03:54<27:43,  5.28step/s, loss=0.113595, elapsed=3.9min]

Entraînement:  12%|█▏        | 1222/10000 [03:54<27:46,  5.27step/s, loss=0.113595, elapsed=3.9min]

Entraînement:  12%|█▏        | 1222/10000 [03:54<27:46,  5.27step/s, loss=0.058632, elapsed=3.9min]

Entraînement:  12%|█▏        | 1223/10000 [03:54<27:51,  5.25step/s, loss=0.058632, elapsed=3.9min]

Entraînement:  12%|█▏        | 1223/10000 [03:54<27:51,  5.25step/s, loss=0.085942, elapsed=3.9min]

Entraînement:  12%|█▏        | 1224/10000 [03:55<27:45,  5.27step/s, loss=0.085942, elapsed=3.9min]

Entraînement:  12%|█▏        | 1224/10000 [03:55<27:45,  5.27step/s, loss=0.057400, elapsed=3.9min]

Entraînement:  12%|█▏        | 1225/10000 [03:55<27:45,  5.27step/s, loss=0.057400, elapsed=3.9min]

Entraînement:  12%|█▏        | 1225/10000 [03:55<27:45,  5.27step/s, loss=0.115126, elapsed=3.9min]

Entraînement:  12%|█▏        | 1226/10000 [03:55<27:43,  5.27step/s, loss=0.115126, elapsed=3.9min]

Entraînement:  12%|█▏        | 1226/10000 [03:55<27:43,  5.27step/s, loss=0.055170, elapsed=3.9min]

Entraînement:  12%|█▏        | 1227/10000 [03:55<27:42,  5.28step/s, loss=0.055170, elapsed=3.9min]

Entraînement:  12%|█▏        | 1227/10000 [03:55<27:42,  5.28step/s, loss=0.071727, elapsed=3.9min]

Entraînement:  12%|█▏        | 1228/10000 [03:55<27:39,  5.29step/s, loss=0.071727, elapsed=3.9min]

Entraînement:  12%|█▏        | 1228/10000 [03:55<27:39,  5.29step/s, loss=0.088308, elapsed=3.9min]

Entraînement:  12%|█▏        | 1229/10000 [03:56<27:37,  5.29step/s, loss=0.088308, elapsed=3.9min]

Entraînement:  12%|█▏        | 1229/10000 [03:56<27:37,  5.29step/s, loss=0.083602, elapsed=3.9min]

Entraînement:  12%|█▏        | 1230/10000 [03:56<27:38,  5.29step/s, loss=0.083602, elapsed=3.9min]

Entraînement:  12%|█▏        | 1230/10000 [03:56<27:38,  5.29step/s, loss=0.052349, elapsed=3.9min]

Entraînement:  12%|█▏        | 1231/10000 [03:56<27:42,  5.27step/s, loss=0.052349, elapsed=3.9min]

Entraînement:  12%|█▏        | 1231/10000 [03:56<27:42,  5.27step/s, loss=0.085126, elapsed=3.9min]

Entraînement:  12%|█▏        | 1232/10000 [03:56<27:47,  5.26step/s, loss=0.085126, elapsed=3.9min]

Entraînement:  12%|█▏        | 1232/10000 [03:56<27:47,  5.26step/s, loss=0.033158, elapsed=3.9min]

Entraînement:  12%|█▏        | 1233/10000 [03:56<27:46,  5.26step/s, loss=0.033158, elapsed=3.9min]

Entraînement:  12%|█▏        | 1233/10000 [03:56<27:46,  5.26step/s, loss=0.040859, elapsed=3.9min]

Entraînement:  12%|█▏        | 1234/10000 [03:56<27:43,  5.27step/s, loss=0.040859, elapsed=3.9min]

Entraînement:  12%|█▏        | 1234/10000 [03:56<27:43,  5.27step/s, loss=0.114940, elapsed=3.9min]

Entraînement:  12%|█▏        | 1235/10000 [03:57<27:45,  5.26step/s, loss=0.114940, elapsed=3.9min]

Entraînement:  12%|█▏        | 1235/10000 [03:57<27:45,  5.26step/s, loss=0.041185, elapsed=4.0min]

Entraînement:  12%|█▏        | 1236/10000 [03:57<27:45,  5.26step/s, loss=0.041185, elapsed=4.0min]

Entraînement:  12%|█▏        | 1236/10000 [03:57<27:45,  5.26step/s, loss=0.107913, elapsed=4.0min]

Entraînement:  12%|█▏        | 1237/10000 [03:57<27:44,  5.27step/s, loss=0.107913, elapsed=4.0min]

Entraînement:  12%|█▏        | 1237/10000 [03:57<27:44,  5.27step/s, loss=0.029391, elapsed=4.0min]

Entraînement:  12%|█▏        | 1238/10000 [03:57<27:41,  5.27step/s, loss=0.029391, elapsed=4.0min]

Entraînement:  12%|█▏        | 1238/10000 [03:57<27:41,  5.27step/s, loss=0.057092, elapsed=4.0min]

Entraînement:  12%|█▏        | 1239/10000 [03:57<27:45,  5.26step/s, loss=0.057092, elapsed=4.0min]

Entraînement:  12%|█▏        | 1239/10000 [03:57<27:45,  5.26step/s, loss=0.048461, elapsed=4.0min]

Entraînement:  12%|█▏        | 1240/10000 [03:58<27:44,  5.26step/s, loss=0.048461, elapsed=4.0min]

Entraînement:  12%|█▏        | 1240/10000 [03:58<27:44,  5.26step/s, loss=0.078987, elapsed=4.0min]

Entraînement:  12%|█▏        | 1241/10000 [03:58<27:47,  5.25step/s, loss=0.078987, elapsed=4.0min]

Entraînement:  12%|█▏        | 1241/10000 [03:58<27:47,  5.25step/s, loss=0.122192, elapsed=4.0min]

Entraînement:  12%|█▏        | 1242/10000 [03:58<27:46,  5.26step/s, loss=0.122192, elapsed=4.0min]

Entraînement:  12%|█▏        | 1242/10000 [03:58<27:46,  5.26step/s, loss=0.039798, elapsed=4.0min]

Entraînement:  12%|█▏        | 1243/10000 [03:58<27:44,  5.26step/s, loss=0.039798, elapsed=4.0min]

Entraînement:  12%|█▏        | 1243/10000 [03:58<27:44,  5.26step/s, loss=0.053084, elapsed=4.0min]

Entraînement:  12%|█▏        | 1244/10000 [03:58<27:41,  5.27step/s, loss=0.053084, elapsed=4.0min]

Entraînement:  12%|█▏        | 1244/10000 [03:58<27:41,  5.27step/s, loss=0.040762, elapsed=4.0min]

Entraînement:  12%|█▏        | 1245/10000 [03:59<27:41,  5.27step/s, loss=0.040762, elapsed=4.0min]

Entraînement:  12%|█▏        | 1245/10000 [03:59<27:41,  5.27step/s, loss=0.078645, elapsed=4.0min]

Entraînement:  12%|█▏        | 1246/10000 [03:59<27:41,  5.27step/s, loss=0.078645, elapsed=4.0min]

Entraînement:  12%|█▏        | 1246/10000 [03:59<27:41,  5.27step/s, loss=0.073672, elapsed=4.0min]

Entraînement:  12%|█▏        | 1247/10000 [03:59<27:39,  5.27step/s, loss=0.073672, elapsed=4.0min]

Entraînement:  12%|█▏        | 1247/10000 [03:59<27:39,  5.27step/s, loss=0.051622, elapsed=4.0min]

Entraînement:  12%|█▏        | 1248/10000 [03:59<27:37,  5.28step/s, loss=0.051622, elapsed=4.0min]

Entraînement:  12%|█▏        | 1248/10000 [03:59<27:37,  5.28step/s, loss=0.030194, elapsed=4.0min]

Entraînement:  12%|█▏        | 1249/10000 [03:59<27:30,  5.30step/s, loss=0.030194, elapsed=4.0min]

Entraînement:  12%|█▏        | 1249/10000 [03:59<27:30,  5.30step/s, loss=0.028460, elapsed=4.0min]

Entraînement:  12%|█▎        | 1250/10000 [04:00<27:36,  5.28step/s, loss=0.028460, elapsed=4.0min]

Entraînement:  12%|█▎        | 1250/10000 [04:00<27:36,  5.28step/s, loss=0.068170, elapsed=4.0min]

Entraînement:  13%|█▎        | 1251/10000 [04:00<27:39,  5.27step/s, loss=0.068170, elapsed=4.0min]

Entraînement:  13%|█▎        | 1251/10000 [04:00<27:39,  5.27step/s, loss=0.184127, elapsed=4.0min]

Entraînement:  13%|█▎        | 1252/10000 [04:00<27:37,  5.28step/s, loss=0.184127, elapsed=4.0min]

Entraînement:  13%|█▎        | 1252/10000 [04:00<27:37,  5.28step/s, loss=0.119863, elapsed=4.0min]

Entraînement:  13%|█▎        | 1253/10000 [04:00<27:34,  5.29step/s, loss=0.119863, elapsed=4.0min]

Entraînement:  13%|█▎        | 1253/10000 [04:00<27:34,  5.29step/s, loss=0.043164, elapsed=4.0min]

Entraînement:  13%|█▎        | 1254/10000 [04:00<27:36,  5.28step/s, loss=0.043164, elapsed=4.0min]

Entraînement:  13%|█▎        | 1254/10000 [04:00<27:36,  5.28step/s, loss=0.046986, elapsed=4.0min]

Entraînement:  13%|█▎        | 1255/10000 [04:00<27:34,  5.29step/s, loss=0.046986, elapsed=4.0min]

Entraînement:  13%|█▎        | 1255/10000 [04:00<27:34,  5.29step/s, loss=0.046359, elapsed=4.0min]

Entraînement:  13%|█▎        | 1256/10000 [04:01<27:31,  5.29step/s, loss=0.046359, elapsed=4.0min]

Entraînement:  13%|█▎        | 1256/10000 [04:01<27:31,  5.29step/s, loss=0.118756, elapsed=4.0min]

Entraînement:  13%|█▎        | 1257/10000 [04:01<27:32,  5.29step/s, loss=0.118756, elapsed=4.0min]

Entraînement:  13%|█▎        | 1257/10000 [04:01<27:32,  5.29step/s, loss=0.036653, elapsed=4.0min]

Entraînement:  13%|█▎        | 1258/10000 [04:01<27:38,  5.27step/s, loss=0.036653, elapsed=4.0min]

Entraînement:  13%|█▎        | 1258/10000 [04:01<27:38,  5.27step/s, loss=0.038557, elapsed=4.0min]

Entraînement:  13%|█▎        | 1259/10000 [04:01<27:36,  5.28step/s, loss=0.038557, elapsed=4.0min]

Entraînement:  13%|█▎        | 1259/10000 [04:01<27:36,  5.28step/s, loss=0.078414, elapsed=4.0min]

Entraînement:  13%|█▎        | 1260/10000 [04:01<27:32,  5.29step/s, loss=0.078414, elapsed=4.0min]

Entraînement:  13%|█▎        | 1260/10000 [04:01<27:32,  5.29step/s, loss=0.069024, elapsed=4.0min]

Entraînement:  13%|█▎        | 1261/10000 [04:02<27:33,  5.28step/s, loss=0.069024, elapsed=4.0min]

Entraînement:  13%|█▎        | 1261/10000 [04:02<27:33,  5.28step/s, loss=0.052977, elapsed=4.0min]

Entraînement:  13%|█▎        | 1262/10000 [04:02<27:34,  5.28step/s, loss=0.052977, elapsed=4.0min]

Entraînement:  13%|█▎        | 1262/10000 [04:02<27:34,  5.28step/s, loss=0.059608, elapsed=4.0min]

Entraînement:  13%|█▎        | 1263/10000 [04:02<27:32,  5.29step/s, loss=0.059608, elapsed=4.0min]

Entraînement:  13%|█▎        | 1263/10000 [04:02<27:32,  5.29step/s, loss=0.053328, elapsed=4.0min]

Entraînement:  13%|█▎        | 1264/10000 [04:02<27:33,  5.28step/s, loss=0.053328, elapsed=4.0min]

Entraînement:  13%|█▎        | 1264/10000 [04:02<27:33,  5.28step/s, loss=0.088536, elapsed=4.0min]

Entraînement:  13%|█▎        | 1265/10000 [04:02<27:34,  5.28step/s, loss=0.088536, elapsed=4.0min]

Entraînement:  13%|█▎        | 1265/10000 [04:02<27:34,  5.28step/s, loss=0.065772, elapsed=4.0min]

Entraînement:  13%|█▎        | 1266/10000 [04:03<27:33,  5.28step/s, loss=0.065772, elapsed=4.0min]

Entraînement:  13%|█▎        | 1266/10000 [04:03<27:33,  5.28step/s, loss=0.071343, elapsed=4.1min]

Entraînement:  13%|█▎        | 1267/10000 [04:03<27:30,  5.29step/s, loss=0.071343, elapsed=4.1min]

Entraînement:  13%|█▎        | 1267/10000 [04:03<27:30,  5.29step/s, loss=0.072105, elapsed=4.1min]

Entraînement:  13%|█▎        | 1268/10000 [04:03<27:33,  5.28step/s, loss=0.072105, elapsed=4.1min]

Entraînement:  13%|█▎        | 1268/10000 [04:03<27:33,  5.28step/s, loss=0.064303, elapsed=4.1min]

Entraînement:  13%|█▎        | 1269/10000 [04:03<27:32,  5.28step/s, loss=0.064303, elapsed=4.1min]

Entraînement:  13%|█▎        | 1269/10000 [04:03<27:32,  5.28step/s, loss=0.062678, elapsed=4.1min]

Entraînement:  13%|█▎        | 1270/10000 [04:03<27:31,  5.29step/s, loss=0.062678, elapsed=4.1min]

Entraînement:  13%|█▎        | 1270/10000 [04:03<27:31,  5.29step/s, loss=0.065969, elapsed=4.1min]

Entraînement:  13%|█▎        | 1271/10000 [04:03<27:34,  5.28step/s, loss=0.065969, elapsed=4.1min]

Entraînement:  13%|█▎        | 1271/10000 [04:03<27:34,  5.28step/s, loss=0.062046, elapsed=4.1min]

Entraînement:  13%|█▎        | 1272/10000 [04:04<27:32,  5.28step/s, loss=0.062046, elapsed=4.1min]

Entraînement:  13%|█▎        | 1272/10000 [04:04<27:32,  5.28step/s, loss=0.065072, elapsed=4.1min]

Entraînement:  13%|█▎        | 1273/10000 [04:04<27:29,  5.29step/s, loss=0.065072, elapsed=4.1min]

Entraînement:  13%|█▎        | 1273/10000 [04:04<27:29,  5.29step/s, loss=0.045828, elapsed=4.1min]

Entraînement:  13%|█▎        | 1274/10000 [04:04<27:29,  5.29step/s, loss=0.045828, elapsed=4.1min]

Entraînement:  13%|█▎        | 1274/10000 [04:04<27:29,  5.29step/s, loss=0.099181, elapsed=4.1min]

Entraînement:  13%|█▎        | 1275/10000 [04:04<27:32,  5.28step/s, loss=0.099181, elapsed=4.1min]

Entraînement:  13%|█▎        | 1275/10000 [04:04<27:32,  5.28step/s, loss=0.130458, elapsed=4.1min]

Entraînement:  13%|█▎        | 1276/10000 [04:04<27:33,  5.28step/s, loss=0.130458, elapsed=4.1min]

Entraînement:  13%|█▎        | 1276/10000 [04:04<27:33,  5.28step/s, loss=0.059774, elapsed=4.1min]

Entraînement:  13%|█▎        | 1277/10000 [04:05<27:32,  5.28step/s, loss=0.059774, elapsed=4.1min]

Entraînement:  13%|█▎        | 1277/10000 [04:05<27:32,  5.28step/s, loss=0.060981, elapsed=4.1min]

Entraînement:  13%|█▎        | 1278/10000 [04:05<27:33,  5.27step/s, loss=0.060981, elapsed=4.1min]

Entraînement:  13%|█▎        | 1278/10000 [04:05<27:33,  5.27step/s, loss=0.078794, elapsed=4.1min]

Entraînement:  13%|█▎        | 1279/10000 [04:05<27:32,  5.28step/s, loss=0.078794, elapsed=4.1min]

Entraînement:  13%|█▎        | 1279/10000 [04:05<27:32,  5.28step/s, loss=0.063551, elapsed=4.1min]

Entraînement:  13%|█▎        | 1280/10000 [04:05<27:29,  5.29step/s, loss=0.063551, elapsed=4.1min]

Entraînement:  13%|█▎        | 1280/10000 [04:05<27:29,  5.29step/s, loss=0.074807, elapsed=4.1min]

Entraînement:  13%|█▎        | 1281/10000 [04:05<27:30,  5.28step/s, loss=0.074807, elapsed=4.1min]

Entraînement:  13%|█▎        | 1281/10000 [04:05<27:30,  5.28step/s, loss=0.142091, elapsed=4.1min]

Entraînement:  13%|█▎        | 1282/10000 [04:06<27:29,  5.29step/s, loss=0.142091, elapsed=4.1min]

Entraînement:  13%|█▎        | 1282/10000 [04:06<27:29,  5.29step/s, loss=0.045792, elapsed=4.1min]

Entraînement:  13%|█▎        | 1283/10000 [04:06<27:33,  5.27step/s, loss=0.045792, elapsed=4.1min]

Entraînement:  13%|█▎        | 1283/10000 [04:06<27:33,  5.27step/s, loss=0.043354, elapsed=4.1min]

Entraînement:  13%|█▎        | 1284/10000 [04:06<27:34,  5.27step/s, loss=0.043354, elapsed=4.1min]

Entraînement:  13%|█▎        | 1284/10000 [04:06<27:34,  5.27step/s, loss=0.037125, elapsed=4.1min]

Entraînement:  13%|█▎        | 1285/10000 [04:06<27:39,  5.25step/s, loss=0.037125, elapsed=4.1min]

Entraînement:  13%|█▎        | 1285/10000 [04:06<27:39,  5.25step/s, loss=0.145043, elapsed=4.1min]

Entraînement:  13%|█▎        | 1286/10000 [04:06<27:35,  5.26step/s, loss=0.145043, elapsed=4.1min]

Entraînement:  13%|█▎        | 1286/10000 [04:06<27:35,  5.26step/s, loss=0.045357, elapsed=4.1min]

Entraînement:  13%|█▎        | 1287/10000 [04:07<27:34,  5.27step/s, loss=0.045357, elapsed=4.1min]

Entraînement:  13%|█▎        | 1287/10000 [04:07<27:34,  5.27step/s, loss=0.093253, elapsed=4.1min]

Entraînement:  13%|█▎        | 1288/10000 [04:07<27:32,  5.27step/s, loss=0.093253, elapsed=4.1min]

Entraînement:  13%|█▎        | 1288/10000 [04:07<27:32,  5.27step/s, loss=0.068462, elapsed=4.1min]

Entraînement:  13%|█▎        | 1289/10000 [04:07<27:28,  5.28step/s, loss=0.068462, elapsed=4.1min]

Entraînement:  13%|█▎        | 1289/10000 [04:07<27:28,  5.28step/s, loss=0.047726, elapsed=4.1min]

Entraînement:  13%|█▎        | 1290/10000 [04:07<27:31,  5.27step/s, loss=0.047726, elapsed=4.1min]

Entraînement:  13%|█▎        | 1290/10000 [04:07<27:31,  5.27step/s, loss=0.160958, elapsed=4.1min]

Entraînement:  13%|█▎        | 1291/10000 [04:07<27:31,  5.27step/s, loss=0.160958, elapsed=4.1min]

Entraînement:  13%|█▎        | 1291/10000 [04:07<27:31,  5.27step/s, loss=0.075716, elapsed=4.1min]

Entraînement:  13%|█▎        | 1292/10000 [04:07<27:33,  5.27step/s, loss=0.075716, elapsed=4.1min]

Entraînement:  13%|█▎        | 1292/10000 [04:07<27:33,  5.27step/s, loss=0.052347, elapsed=4.1min]

Entraînement:  13%|█▎        | 1293/10000 [04:08<27:31,  5.27step/s, loss=0.052347, elapsed=4.1min]

Entraînement:  13%|█▎        | 1293/10000 [04:08<27:31,  5.27step/s, loss=0.055987, elapsed=4.1min]

Entraînement:  13%|█▎        | 1294/10000 [04:08<27:28,  5.28step/s, loss=0.055987, elapsed=4.1min]

Entraînement:  13%|█▎        | 1294/10000 [04:08<27:28,  5.28step/s, loss=0.067179, elapsed=4.1min]

Entraînement:  13%|█▎        | 1295/10000 [04:08<27:28,  5.28step/s, loss=0.067179, elapsed=4.1min]

Entraînement:  13%|█▎        | 1295/10000 [04:08<27:28,  5.28step/s, loss=0.045653, elapsed=4.1min]

Entraînement:  13%|█▎        | 1296/10000 [04:08<27:23,  5.30step/s, loss=0.045653, elapsed=4.1min]

Entraînement:  13%|█▎        | 1296/10000 [04:08<27:23,  5.30step/s, loss=0.094278, elapsed=4.1min]

Entraînement:  13%|█▎        | 1297/10000 [04:08<27:26,  5.29step/s, loss=0.094278, elapsed=4.1min]

Entraînement:  13%|█▎        | 1297/10000 [04:08<27:26,  5.29step/s, loss=0.039838, elapsed=4.1min]

Entraînement:  13%|█▎        | 1298/10000 [04:09<27:29,  5.27step/s, loss=0.039838, elapsed=4.1min]

Entraînement:  13%|█▎        | 1298/10000 [04:09<27:29,  5.27step/s, loss=0.045986, elapsed=4.2min]

Entraînement:  13%|█▎        | 1299/10000 [04:09<27:27,  5.28step/s, loss=0.045986, elapsed=4.2min]

Entraînement:  13%|█▎        | 1299/10000 [04:09<27:27,  5.28step/s, loss=0.079253, elapsed=4.2min]

Entraînement:  13%|█▎        | 1300/10000 [04:09<27:28,  5.28step/s, loss=0.079253, elapsed=4.2min]

Entraînement:  13%|█▎        | 1300/10000 [04:09<27:28,  5.28step/s, loss=0.053506, elapsed=4.2min]

Entraînement:  13%|█▎        | 1300/10000 [04:09<27:28,  5.28step/s, loss=0.053506, elapsed=4.2min]

Entraînement:  13%|█▎        | 1301/10000 [04:09<27:42,  5.23step/s, loss=0.053506, elapsed=4.2min]

Entraînement:  13%|█▎        | 1301/10000 [04:09<27:42,  5.23step/s, loss=0.068901, elapsed=4.2min]

Step 1300/10000 | Train loss: 0.053506 | Elapsed: 4.2min | ETA: 27.8min

Entraînement:  13%|█▎        | 1302/10000 [04:09<27:38,  5.24step/s, loss=0.068901, elapsed=4.2min]

Entraînement:  13%|█▎        | 1302/10000 [04:09<27:38,  5.24step/s, loss=0.087210, elapsed=4.2min]

Entraînement:  13%|█▎        | 1303/10000 [04:10<27:32,  5.26step/s, loss=0.087210, elapsed=4.2min]

Entraînement:  13%|█▎        | 1303/10000 [04:10<27:32,  5.26step/s, loss=0.073850, elapsed=4.2min]

Entraînement:  13%|█▎        | 1304/10000 [04:10<27:30,  5.27step/s, loss=0.073850, elapsed=4.2min]

Entraînement:  13%|█▎        | 1304/10000 [04:10<27:30,  5.27step/s, loss=0.052149, elapsed=4.2min]

Entraînement:  13%|█▎        | 1305/10000 [04:10<27:27,  5.28step/s, loss=0.052149, elapsed=4.2min]

Entraînement:  13%|█▎        | 1305/10000 [04:10<27:27,  5.28step/s, loss=0.058898, elapsed=4.2min]

Entraînement:  13%|█▎        | 1306/10000 [04:10<27:30,  5.27step/s, loss=0.058898, elapsed=4.2min]

Entraînement:  13%|█▎        | 1306/10000 [04:10<27:30,  5.27step/s, loss=0.047529, elapsed=4.2min]

Entraînement:  13%|█▎        | 1307/10000 [04:10<27:28,  5.27step/s, loss=0.047529, elapsed=4.2min]

Entraînement:  13%|█▎        | 1307/10000 [04:10<27:28,  5.27step/s, loss=0.089430, elapsed=4.2min]

Entraînement:  13%|█▎        | 1308/10000 [04:10<27:26,  5.28step/s, loss=0.089430, elapsed=4.2min]

Entraînement:  13%|█▎        | 1308/10000 [04:10<27:26,  5.28step/s, loss=0.063986, elapsed=4.2min]

Entraînement:  13%|█▎        | 1309/10000 [04:11<27:25,  5.28step/s, loss=0.063986, elapsed=4.2min]

Entraînement:  13%|█▎        | 1309/10000 [04:11<27:25,  5.28step/s, loss=0.084385, elapsed=4.2min]

Entraînement:  13%|█▎        | 1310/10000 [04:11<27:21,  5.29step/s, loss=0.084385, elapsed=4.2min]

Entraînement:  13%|█▎        | 1310/10000 [04:11<27:21,  5.29step/s, loss=0.048425, elapsed=4.2min]

Entraînement:  13%|█▎        | 1311/10000 [04:11<27:20,  5.30step/s, loss=0.048425, elapsed=4.2min]

Entraînement:  13%|█▎        | 1311/10000 [04:11<27:20,  5.30step/s, loss=0.039560, elapsed=4.2min]

Entraînement:  13%|█▎        | 1312/10000 [04:11<27:17,  5.30step/s, loss=0.039560, elapsed=4.2min]

Entraînement:  13%|█▎        | 1312/10000 [04:11<27:17,  5.30step/s, loss=0.067353, elapsed=4.2min]

Entraînement:  13%|█▎        | 1313/10000 [04:11<27:20,  5.30step/s, loss=0.067353, elapsed=4.2min]

Entraînement:  13%|█▎        | 1313/10000 [04:11<27:20,  5.30step/s, loss=0.044615, elapsed=4.2min]

Entraînement:  13%|█▎        | 1314/10000 [04:12<27:22,  5.29step/s, loss=0.044615, elapsed=4.2min]

Entraînement:  13%|█▎        | 1314/10000 [04:12<27:22,  5.29step/s, loss=0.107675, elapsed=4.2min]

Entraînement:  13%|█▎        | 1315/10000 [04:12<27:19,  5.30step/s, loss=0.107675, elapsed=4.2min]

Entraînement:  13%|█▎        | 1315/10000 [04:12<27:19,  5.30step/s, loss=0.043847, elapsed=4.2min]

Entraînement:  13%|█▎        | 1316/10000 [04:12<27:22,  5.29step/s, loss=0.043847, elapsed=4.2min]

Entraînement:  13%|█▎        | 1316/10000 [04:12<27:22,  5.29step/s, loss=0.052292, elapsed=4.2min]

Entraînement:  13%|█▎        | 1317/10000 [04:12<27:21,  5.29step/s, loss=0.052292, elapsed=4.2min]

Entraînement:  13%|█▎        | 1317/10000 [04:12<27:21,  5.29step/s, loss=0.125327, elapsed=4.2min]

Entraînement:  13%|█▎        | 1318/10000 [04:12<27:21,  5.29step/s, loss=0.125327, elapsed=4.2min]

Entraînement:  13%|█▎        | 1318/10000 [04:12<27:21,  5.29step/s, loss=0.050310, elapsed=4.2min]

Entraînement:  13%|█▎        | 1319/10000 [04:13<27:20,  5.29step/s, loss=0.050310, elapsed=4.2min]

Entraînement:  13%|█▎        | 1319/10000 [04:13<27:20,  5.29step/s, loss=0.051386, elapsed=4.2min]

Entraînement:  13%|█▎        | 1320/10000 [04:13<27:17,  5.30step/s, loss=0.051386, elapsed=4.2min]

Entraînement:  13%|█▎        | 1320/10000 [04:13<27:17,  5.30step/s, loss=0.077221, elapsed=4.2min]

Entraînement:  13%|█▎        | 1321/10000 [04:13<27:21,  5.29step/s, loss=0.077221, elapsed=4.2min]

Entraînement:  13%|█▎        | 1321/10000 [04:13<27:21,  5.29step/s, loss=0.164797, elapsed=4.2min]

Entraînement:  13%|█▎        | 1322/10000 [04:13<27:22,  5.28step/s, loss=0.164797, elapsed=4.2min]

Entraînement:  13%|█▎        | 1322/10000 [04:13<27:22,  5.28step/s, loss=0.098016, elapsed=4.2min]

Entraînement:  13%|█▎        | 1323/10000 [04:13<27:23,  5.28step/s, loss=0.098016, elapsed=4.2min]

Entraînement:  13%|█▎        | 1323/10000 [04:13<27:23,  5.28step/s, loss=0.062800, elapsed=4.2min]

Entraînement:  13%|█▎        | 1324/10000 [04:14<27:22,  5.28step/s, loss=0.062800, elapsed=4.2min]

Entraînement:  13%|█▎        | 1324/10000 [04:14<27:22,  5.28step/s, loss=0.091336, elapsed=4.2min]

Entraînement:  13%|█▎        | 1325/10000 [04:14<27:20,  5.29step/s, loss=0.091336, elapsed=4.2min]

Entraînement:  13%|█▎        | 1325/10000 [04:14<27:20,  5.29step/s, loss=0.096861, elapsed=4.2min]

Entraînement:  13%|█▎        | 1326/10000 [04:14<27:22,  5.28step/s, loss=0.096861, elapsed=4.2min]

Entraînement:  13%|█▎        | 1326/10000 [04:14<27:22,  5.28step/s, loss=0.046379, elapsed=4.2min]

Entraînement:  13%|█▎        | 1327/10000 [04:14<27:21,  5.28step/s, loss=0.046379, elapsed=4.2min]

Entraînement:  13%|█▎        | 1327/10000 [04:14<27:21,  5.28step/s, loss=0.076038, elapsed=4.2min]

Entraînement:  13%|█▎        | 1328/10000 [04:14<27:23,  5.28step/s, loss=0.076038, elapsed=4.2min]

Entraînement:  13%|█▎        | 1328/10000 [04:14<27:23,  5.28step/s, loss=0.046201, elapsed=4.2min]

Entraînement:  13%|█▎        | 1329/10000 [04:14<27:25,  5.27step/s, loss=0.046201, elapsed=4.2min]

Entraînement:  13%|█▎        | 1329/10000 [04:14<27:25,  5.27step/s, loss=0.046102, elapsed=4.2min]

Entraînement:  13%|█▎        | 1330/10000 [04:15<27:27,  5.26step/s, loss=0.046102, elapsed=4.2min]

Entraînement:  13%|█▎        | 1330/10000 [04:15<27:27,  5.26step/s, loss=0.042693, elapsed=4.3min]

Entraînement:  13%|█▎        | 1331/10000 [04:15<27:26,  5.27step/s, loss=0.042693, elapsed=4.3min]

Entraînement:  13%|█▎        | 1331/10000 [04:15<27:26,  5.27step/s, loss=0.064599, elapsed=4.3min]

Entraînement:  13%|█▎        | 1332/10000 [04:15<27:23,  5.27step/s, loss=0.064599, elapsed=4.3min]

Entraînement:  13%|█▎        | 1332/10000 [04:15<27:23,  5.27step/s, loss=0.060258, elapsed=4.3min]

Entraînement:  13%|█▎        | 1333/10000 [04:15<27:24,  5.27step/s, loss=0.060258, elapsed=4.3min]

Entraînement:  13%|█▎        | 1333/10000 [04:15<27:24,  5.27step/s, loss=0.047984, elapsed=4.3min]

Entraînement:  13%|█▎        | 1334/10000 [04:15<27:22,  5.28step/s, loss=0.047984, elapsed=4.3min]

Entraînement:  13%|█▎        | 1334/10000 [04:15<27:22,  5.28step/s, loss=0.041875, elapsed=4.3min]

Entraînement:  13%|█▎        | 1335/10000 [04:16<27:22,  5.28step/s, loss=0.041875, elapsed=4.3min]

Entraînement:  13%|█▎        | 1335/10000 [04:16<27:22,  5.28step/s, loss=0.061966, elapsed=4.3min]

Entraînement:  13%|█▎        | 1336/10000 [04:16<27:21,  5.28step/s, loss=0.061966, elapsed=4.3min]

Entraînement:  13%|█▎        | 1336/10000 [04:16<27:21,  5.28step/s, loss=0.139673, elapsed=4.3min]

Entraînement:  13%|█▎        | 1337/10000 [04:16<27:21,  5.28step/s, loss=0.139673, elapsed=4.3min]

Entraînement:  13%|█▎        | 1337/10000 [04:16<27:21,  5.28step/s, loss=0.044943, elapsed=4.3min]

Entraînement:  13%|█▎        | 1338/10000 [04:16<27:22,  5.27step/s, loss=0.044943, elapsed=4.3min]

Entraînement:  13%|█▎        | 1338/10000 [04:16<27:22,  5.27step/s, loss=0.057652, elapsed=4.3min]

Entraînement:  13%|█▎        | 1339/10000 [04:16<27:23,  5.27step/s, loss=0.057652, elapsed=4.3min]

Entraînement:  13%|█▎        | 1339/10000 [04:16<27:23,  5.27step/s, loss=0.128442, elapsed=4.3min]

Entraînement:  13%|█▎        | 1340/10000 [04:17<27:19,  5.28step/s, loss=0.128442, elapsed=4.3min]

Entraînement:  13%|█▎        | 1340/10000 [04:17<27:19,  5.28step/s, loss=0.264515, elapsed=4.3min]

Entraînement:  13%|█▎        | 1341/10000 [04:17<27:22,  5.27step/s, loss=0.264515, elapsed=4.3min]

Entraînement:  13%|█▎        | 1341/10000 [04:17<27:22,  5.27step/s, loss=0.117827, elapsed=4.3min]

Entraînement:  13%|█▎        | 1342/10000 [04:17<27:21,  5.27step/s, loss=0.117827, elapsed=4.3min]

Entraînement:  13%|█▎        | 1342/10000 [04:17<27:21,  5.27step/s, loss=0.065827, elapsed=4.3min]

Entraînement:  13%|█▎        | 1343/10000 [04:17<27:23,  5.27step/s, loss=0.065827, elapsed=4.3min]

Entraînement:  13%|█▎        | 1343/10000 [04:17<27:23,  5.27step/s, loss=0.043162, elapsed=4.3min]

Entraînement:  13%|█▎        | 1344/10000 [04:17<27:20,  5.28step/s, loss=0.043162, elapsed=4.3min]

Entraînement:  13%|█▎        | 1344/10000 [04:17<27:20,  5.28step/s, loss=0.081065, elapsed=4.3min]

Entraînement:  13%|█▎        | 1345/10000 [04:17<27:17,  5.29step/s, loss=0.081065, elapsed=4.3min]

Entraînement:  13%|█▎        | 1345/10000 [04:18<27:17,  5.29step/s, loss=0.103486, elapsed=4.3min]

Entraînement:  13%|█▎        | 1346/10000 [04:18<27:21,  5.27step/s, loss=0.103486, elapsed=4.3min]

Entraînement:  13%|█▎        | 1346/10000 [04:18<27:21,  5.27step/s, loss=0.046754, elapsed=4.3min]

Entraînement:  13%|█▎        | 1347/10000 [04:18<27:18,  5.28step/s, loss=0.046754, elapsed=4.3min]

Entraînement:  13%|█▎        | 1347/10000 [04:18<27:18,  5.28step/s, loss=0.123771, elapsed=4.3min]

Entraînement:  13%|█▎        | 1348/10000 [04:18<27:18,  5.28step/s, loss=0.123771, elapsed=4.3min]

Entraînement:  13%|█▎        | 1348/10000 [04:18<27:18,  5.28step/s, loss=0.055958, elapsed=4.3min]

Entraînement:  13%|█▎        | 1349/10000 [04:18<27:18,  5.28step/s, loss=0.055958, elapsed=4.3min]

Entraînement:  13%|█▎        | 1349/10000 [04:18<27:18,  5.28step/s, loss=0.027434, elapsed=4.3min]

Entraînement:  14%|█▎        | 1350/10000 [04:18<27:18,  5.28step/s, loss=0.027434, elapsed=4.3min]

Entraînement:  14%|█▎        | 1350/10000 [04:18<27:18,  5.28step/s, loss=0.098329, elapsed=4.3min]

Entraînement:  14%|█▎        | 1351/10000 [04:19<27:18,  5.28step/s, loss=0.098329, elapsed=4.3min]

Entraînement:  14%|█▎        | 1351/10000 [04:19<27:18,  5.28step/s, loss=0.059513, elapsed=4.3min]

Entraînement:  14%|█▎        | 1352/10000 [04:19<27:16,  5.28step/s, loss=0.059513, elapsed=4.3min]

Entraînement:  14%|█▎        | 1352/10000 [04:19<27:16,  5.28step/s, loss=0.057805, elapsed=4.3min]

Entraînement:  14%|█▎        | 1353/10000 [04:19<27:17,  5.28step/s, loss=0.057805, elapsed=4.3min]

Entraînement:  14%|█▎        | 1353/10000 [04:19<27:17,  5.28step/s, loss=0.097777, elapsed=4.3min]

Entraînement:  14%|█▎        | 1354/10000 [04:19<27:12,  5.30step/s, loss=0.097777, elapsed=4.3min]

Entraînement:  14%|█▎        | 1354/10000 [04:19<27:12,  5.30step/s, loss=0.027847, elapsed=4.3min]

Entraînement:  14%|█▎        | 1355/10000 [04:19<27:16,  5.28step/s, loss=0.027847, elapsed=4.3min]

Entraînement:  14%|█▎        | 1355/10000 [04:19<27:16,  5.28step/s, loss=0.035295, elapsed=4.3min]

Entraînement:  14%|█▎        | 1356/10000 [04:20<27:15,  5.28step/s, loss=0.035295, elapsed=4.3min]

Entraînement:  14%|█▎        | 1356/10000 [04:20<27:15,  5.28step/s, loss=0.037922, elapsed=4.3min]

Entraînement:  14%|█▎        | 1357/10000 [04:20<27:12,  5.29step/s, loss=0.037922, elapsed=4.3min]

Entraînement:  14%|█▎        | 1357/10000 [04:20<27:12,  5.29step/s, loss=0.079598, elapsed=4.3min]

Entraînement:  14%|█▎        | 1358/10000 [04:20<27:12,  5.29step/s, loss=0.079598, elapsed=4.3min]

Entraînement:  14%|█▎        | 1358/10000 [04:20<27:12,  5.29step/s, loss=0.120803, elapsed=4.3min]

Entraînement:  14%|█▎        | 1359/10000 [04:20<27:11,  5.30step/s, loss=0.120803, elapsed=4.3min]

Entraînement:  14%|█▎        | 1359/10000 [04:20<27:11,  5.30step/s, loss=0.047806, elapsed=4.3min]

Entraînement:  14%|█▎        | 1360/10000 [04:20<27:08,  5.31step/s, loss=0.047806, elapsed=4.3min]

Entraînement:  14%|█▎        | 1360/10000 [04:20<27:08,  5.31step/s, loss=0.046997, elapsed=4.3min]

Entraînement:  14%|█▎        | 1361/10000 [04:21<27:13,  5.29step/s, loss=0.046997, elapsed=4.3min]

Entraînement:  14%|█▎        | 1361/10000 [04:21<27:13,  5.29step/s, loss=0.099760, elapsed=4.4min]

Entraînement:  14%|█▎        | 1362/10000 [04:21<27:14,  5.28step/s, loss=0.099760, elapsed=4.4min]

Entraînement:  14%|█▎        | 1362/10000 [04:21<27:14,  5.28step/s, loss=0.068294, elapsed=4.4min]

Entraînement:  14%|█▎        | 1363/10000 [04:21<27:12,  5.29step/s, loss=0.068294, elapsed=4.4min]

Entraînement:  14%|█▎        | 1363/10000 [04:21<27:12,  5.29step/s, loss=0.071639, elapsed=4.4min]

Entraînement:  14%|█▎        | 1364/10000 [04:21<27:12,  5.29step/s, loss=0.071639, elapsed=4.4min]

Entraînement:  14%|█▎        | 1364/10000 [04:21<27:12,  5.29step/s, loss=0.047954, elapsed=4.4min]

Entraînement:  14%|█▎        | 1365/10000 [04:21<27:11,  5.29step/s, loss=0.047954, elapsed=4.4min]

Entraînement:  14%|█▎        | 1365/10000 [04:21<27:11,  5.29step/s, loss=0.090867, elapsed=4.4min]

Entraînement:  14%|█▎        | 1366/10000 [04:21<27:12,  5.29step/s, loss=0.090867, elapsed=4.4min]

Entraînement:  14%|█▎        | 1366/10000 [04:21<27:12,  5.29step/s, loss=0.035032, elapsed=4.4min]

Entraînement:  14%|█▎        | 1367/10000 [04:22<27:12,  5.29step/s, loss=0.035032, elapsed=4.4min]

Entraînement:  14%|█▎        | 1367/10000 [04:22<27:12,  5.29step/s, loss=0.057502, elapsed=4.4min]

Entraînement:  14%|█▎        | 1368/10000 [04:22<27:11,  5.29step/s, loss=0.057502, elapsed=4.4min]

Entraînement:  14%|█▎        | 1368/10000 [04:22<27:11,  5.29step/s, loss=0.108086, elapsed=4.4min]

Entraînement:  14%|█▎        | 1369/10000 [04:22<27:14,  5.28step/s, loss=0.108086, elapsed=4.4min]

Entraînement:  14%|█▎        | 1369/10000 [04:22<27:14,  5.28step/s, loss=0.050093, elapsed=4.4min]

Entraînement:  14%|█▎        | 1370/10000 [04:22<27:14,  5.28step/s, loss=0.050093, elapsed=4.4min]

Entraînement:  14%|█▎        | 1370/10000 [04:22<27:14,  5.28step/s, loss=0.047531, elapsed=4.4min]

Entraînement:  14%|█▎        | 1371/10000 [04:22<27:16,  5.27step/s, loss=0.047531, elapsed=4.4min]

Entraînement:  14%|█▎        | 1371/10000 [04:22<27:16,  5.27step/s, loss=0.111863, elapsed=4.4min]

Entraînement:  14%|█▎        | 1372/10000 [04:23<27:14,  5.28step/s, loss=0.111863, elapsed=4.4min]

Entraînement:  14%|█▎        | 1372/10000 [04:23<27:14,  5.28step/s, loss=0.113233, elapsed=4.4min]

Entraînement:  14%|█▎        | 1373/10000 [04:23<27:12,  5.28step/s, loss=0.113233, elapsed=4.4min]

Entraînement:  14%|█▎        | 1373/10000 [04:23<27:12,  5.28step/s, loss=0.086320, elapsed=4.4min]

Entraînement:  14%|█▎        | 1374/10000 [04:23<27:11,  5.29step/s, loss=0.086320, elapsed=4.4min]

Entraînement:  14%|█▎        | 1374/10000 [04:23<27:11,  5.29step/s, loss=0.057705, elapsed=4.4min]

Entraînement:  14%|█▍        | 1375/10000 [04:23<27:08,  5.30step/s, loss=0.057705, elapsed=4.4min]

Entraînement:  14%|█▍        | 1375/10000 [04:23<27:08,  5.30step/s, loss=0.095448, elapsed=4.4min]

Entraînement:  14%|█▍        | 1376/10000 [04:23<27:11,  5.28step/s, loss=0.095448, elapsed=4.4min]

Entraînement:  14%|█▍        | 1376/10000 [04:23<27:11,  5.28step/s, loss=0.079365, elapsed=4.4min]

Entraînement:  14%|█▍        | 1377/10000 [04:24<27:13,  5.28step/s, loss=0.079365, elapsed=4.4min]

Entraînement:  14%|█▍        | 1377/10000 [04:24<27:13,  5.28step/s, loss=0.069266, elapsed=4.4min]

Entraînement:  14%|█▍        | 1378/10000 [04:24<27:13,  5.28step/s, loss=0.069266, elapsed=4.4min]

Entraînement:  14%|█▍        | 1378/10000 [04:24<27:13,  5.28step/s, loss=0.055035, elapsed=4.4min]

Entraînement:  14%|█▍        | 1379/10000 [04:24<27:10,  5.29step/s, loss=0.055035, elapsed=4.4min]

Entraînement:  14%|█▍        | 1379/10000 [04:24<27:10,  5.29step/s, loss=0.109466, elapsed=4.4min]

Entraînement:  14%|█▍        | 1380/10000 [04:24<27:08,  5.29step/s, loss=0.109466, elapsed=4.4min]

Entraînement:  14%|█▍        | 1380/10000 [04:24<27:08,  5.29step/s, loss=0.049344, elapsed=4.4min]

Entraînement:  14%|█▍        | 1381/10000 [04:24<27:09,  5.29step/s, loss=0.049344, elapsed=4.4min]

Entraînement:  14%|█▍        | 1381/10000 [04:24<27:09,  5.29step/s, loss=0.044723, elapsed=4.4min]

Entraînement:  14%|█▍        | 1382/10000 [04:24<27:08,  5.29step/s, loss=0.044723, elapsed=4.4min]

Entraînement:  14%|█▍        | 1382/10000 [04:24<27:08,  5.29step/s, loss=0.027177, elapsed=4.4min]

Entraînement:  14%|█▍        | 1383/10000 [04:25<27:06,  5.30step/s, loss=0.027177, elapsed=4.4min]

Entraînement:  14%|█▍        | 1383/10000 [04:25<27:06,  5.30step/s, loss=0.117159, elapsed=4.4min]

Entraînement:  14%|█▍        | 1384/10000 [04:25<27:07,  5.29step/s, loss=0.117159, elapsed=4.4min]

Entraînement:  14%|█▍        | 1384/10000 [04:25<27:07,  5.29step/s, loss=0.075473, elapsed=4.4min]

Entraînement:  14%|█▍        | 1385/10000 [04:25<27:09,  5.29step/s, loss=0.075473, elapsed=4.4min]

Entraînement:  14%|█▍        | 1385/10000 [04:25<27:09,  5.29step/s, loss=0.038998, elapsed=4.4min]

Entraînement:  14%|█▍        | 1386/10000 [04:25<27:09,  5.29step/s, loss=0.038998, elapsed=4.4min]

Entraînement:  14%|█▍        | 1386/10000 [04:25<27:09,  5.29step/s, loss=0.068158, elapsed=4.4min]

Entraînement:  14%|█▍        | 1387/10000 [04:25<27:08,  5.29step/s, loss=0.068158, elapsed=4.4min]

Entraînement:  14%|█▍        | 1387/10000 [04:25<27:08,  5.29step/s, loss=0.049150, elapsed=4.4min]

Entraînement:  14%|█▍        | 1388/10000 [04:26<27:04,  5.30step/s, loss=0.049150, elapsed=4.4min]

Entraînement:  14%|█▍        | 1388/10000 [04:26<27:04,  5.30step/s, loss=0.045180, elapsed=4.4min]

Entraînement:  14%|█▍        | 1389/10000 [04:26<27:05,  5.30step/s, loss=0.045180, elapsed=4.4min]

Entraînement:  14%|█▍        | 1389/10000 [04:26<27:05,  5.30step/s, loss=0.044734, elapsed=4.4min]

Entraînement:  14%|█▍        | 1390/10000 [04:26<27:02,  5.31step/s, loss=0.044734, elapsed=4.4min]

Entraînement:  14%|█▍        | 1390/10000 [04:26<27:02,  5.31step/s, loss=0.065912, elapsed=4.4min]

Entraînement:  14%|█▍        | 1391/10000 [04:26<27:02,  5.31step/s, loss=0.065912, elapsed=4.4min]

Entraînement:  14%|█▍        | 1391/10000 [04:26<27:02,  5.31step/s, loss=0.070238, elapsed=4.4min]

Entraînement:  14%|█▍        | 1392/10000 [04:26<27:04,  5.30step/s, loss=0.070238, elapsed=4.4min]

Entraînement:  14%|█▍        | 1392/10000 [04:26<27:04,  5.30step/s, loss=0.082663, elapsed=4.4min]

Entraînement:  14%|█▍        | 1393/10000 [04:27<27:05,  5.30step/s, loss=0.082663, elapsed=4.4min]

Entraînement:  14%|█▍        | 1393/10000 [04:27<27:05,  5.30step/s, loss=0.044488, elapsed=4.5min]

Entraînement:  14%|█▍        | 1394/10000 [04:27<27:07,  5.29step/s, loss=0.044488, elapsed=4.5min]

Entraînement:  14%|█▍        | 1394/10000 [04:27<27:07,  5.29step/s, loss=0.071881, elapsed=4.5min]

Entraînement:  14%|█▍        | 1395/10000 [04:27<27:06,  5.29step/s, loss=0.071881, elapsed=4.5min]

Entraînement:  14%|█▍        | 1395/10000 [04:27<27:06,  5.29step/s, loss=0.071586, elapsed=4.5min]

Entraînement:  14%|█▍        | 1396/10000 [04:27<27:07,  5.29step/s, loss=0.071586, elapsed=4.5min]

Entraînement:  14%|█▍        | 1396/10000 [04:27<27:07,  5.29step/s, loss=0.046337, elapsed=4.5min]

Entraînement:  14%|█▍        | 1397/10000 [04:27<27:07,  5.29step/s, loss=0.046337, elapsed=4.5min]

Entraînement:  14%|█▍        | 1397/10000 [04:27<27:07,  5.29step/s, loss=0.083131, elapsed=4.5min]

Entraînement:  14%|█▍        | 1398/10000 [04:28<27:07,  5.28step/s, loss=0.083131, elapsed=4.5min]

Entraînement:  14%|█▍        | 1398/10000 [04:28<27:07,  5.28step/s, loss=0.056448, elapsed=4.5min]

Entraînement:  14%|█▍        | 1399/10000 [04:28<27:07,  5.28step/s, loss=0.056448, elapsed=4.5min]

Entraînement:  14%|█▍        | 1399/10000 [04:28<27:07,  5.28step/s, loss=0.074004, elapsed=4.5min]

Entraînement:  14%|█▍        | 1400/10000 [04:28<27:08,  5.28step/s, loss=0.074004, elapsed=4.5min]

Entraînement:  14%|█▍        | 1400/10000 [04:28<27:08,  5.28step/s, loss=0.035946, elapsed=4.5min]

Entraînement:  14%|█▍        | 1400/10000 [04:28<27:08,  5.28step/s, loss=0.035946, elapsed=4.5min]

Entraînement:  14%|█▍        | 1401/10000 [04:28<27:23,  5.23step/s, loss=0.035946, elapsed=4.5min]

Entraînement:  14%|█▍        | 1401/10000 [04:28<27:23,  5.23step/s, loss=0.045130, elapsed=4.5min]

Step 1400/10000 | Train loss: 0.035946 | Elapsed: 4.5min | ETA: 27.5min

Entraînement:  14%|█▍        | 1402/10000 [04:28<27:23,  5.23step/s, loss=0.045130, elapsed=4.5min]

Entraînement:  14%|█▍        | 1402/10000 [04:28<27:23,  5.23step/s, loss=0.043127, elapsed=4.5min]

Entraînement:  14%|█▍        | 1403/10000 [04:28<27:18,  5.25step/s, loss=0.043127, elapsed=4.5min]

Entraînement:  14%|█▍        | 1403/10000 [04:28<27:18,  5.25step/s, loss=0.060073, elapsed=4.5min]

Entraînement:  14%|█▍        | 1404/10000 [04:29<27:11,  5.27step/s, loss=0.060073, elapsed=4.5min]

Entraînement:  14%|█▍        | 1404/10000 [04:29<27:11,  5.27step/s, loss=0.045205, elapsed=4.5min]

Entraînement:  14%|█▍        | 1405/10000 [04:29<27:09,  5.27step/s, loss=0.045205, elapsed=4.5min]

Entraînement:  14%|█▍        | 1405/10000 [04:29<27:09,  5.27step/s, loss=0.139916, elapsed=4.5min]

Entraînement:  14%|█▍        | 1406/10000 [04:29<27:06,  5.28step/s, loss=0.139916, elapsed=4.5min]

Entraînement:  14%|█▍        | 1406/10000 [04:29<27:06,  5.28step/s, loss=0.068974, elapsed=4.5min]

Entraînement:  14%|█▍        | 1407/10000 [04:29<27:03,  5.29step/s, loss=0.068974, elapsed=4.5min]

Entraînement:  14%|█▍        | 1407/10000 [04:29<27:03,  5.29step/s, loss=0.115142, elapsed=4.5min]

Entraînement:  14%|█▍        | 1408/10000 [04:29<27:07,  5.28step/s, loss=0.115142, elapsed=4.5min]

Entraînement:  14%|█▍        | 1408/10000 [04:29<27:07,  5.28step/s, loss=0.063421, elapsed=4.5min]

Entraînement:  14%|█▍        | 1409/10000 [04:30<27:08,  5.28step/s, loss=0.063421, elapsed=4.5min]

Entraînement:  14%|█▍        | 1409/10000 [04:30<27:08,  5.28step/s, loss=0.078432, elapsed=4.5min]

Entraînement:  14%|█▍        | 1410/10000 [04:30<27:09,  5.27step/s, loss=0.078432, elapsed=4.5min]

Entraînement:  14%|█▍        | 1410/10000 [04:30<27:09,  5.27step/s, loss=0.097780, elapsed=4.5min]

Entraînement:  14%|█▍        | 1411/10000 [04:30<27:08,  5.27step/s, loss=0.097780, elapsed=4.5min]

Entraînement:  14%|█▍        | 1411/10000 [04:30<27:08,  5.27step/s, loss=0.082926, elapsed=4.5min]

Entraînement:  14%|█▍        | 1412/10000 [04:30<27:04,  5.29step/s, loss=0.082926, elapsed=4.5min]

Entraînement:  14%|█▍        | 1412/10000 [04:30<27:04,  5.29step/s, loss=0.069754, elapsed=4.5min]

Entraînement:  14%|█▍        | 1413/10000 [04:30<27:12,  5.26step/s, loss=0.069754, elapsed=4.5min]

Entraînement:  14%|█▍        | 1413/10000 [04:30<27:12,  5.26step/s, loss=0.115877, elapsed=4.5min]

Entraînement:  14%|█▍        | 1414/10000 [04:31<27:07,  5.28step/s, loss=0.115877, elapsed=4.5min]

Entraînement:  14%|█▍        | 1414/10000 [04:31<27:07,  5.28step/s, loss=0.054121, elapsed=4.5min]

Entraînement:  14%|█▍        | 1415/10000 [04:31<27:07,  5.28step/s, loss=0.054121, elapsed=4.5min]

Entraînement:  14%|█▍        | 1415/10000 [04:31<27:07,  5.28step/s, loss=0.064430, elapsed=4.5min]

Entraînement:  14%|█▍        | 1416/10000 [04:31<27:07,  5.28step/s, loss=0.064430, elapsed=4.5min]

Entraînement:  14%|█▍        | 1416/10000 [04:31<27:07,  5.28step/s, loss=0.170710, elapsed=4.5min]

Entraînement:  14%|█▍        | 1417/10000 [04:31<27:09,  5.27step/s, loss=0.170710, elapsed=4.5min]

Entraînement:  14%|█▍        | 1417/10000 [04:31<27:09,  5.27step/s, loss=0.081018, elapsed=4.5min]

Entraînement:  14%|█▍        | 1418/10000 [04:31<27:07,  5.27step/s, loss=0.081018, elapsed=4.5min]

Entraînement:  14%|█▍        | 1418/10000 [04:31<27:07,  5.27step/s, loss=0.076635, elapsed=4.5min]

Entraînement:  14%|█▍        | 1419/10000 [04:32<27:20,  5.23step/s, loss=0.076635, elapsed=4.5min]

Entraînement:  14%|█▍        | 1419/10000 [04:32<27:20,  5.23step/s, loss=0.043637, elapsed=4.5min]

Entraînement:  14%|█▍        | 1420/10000 [04:32<27:13,  5.25step/s, loss=0.043637, elapsed=4.5min]

Entraînement:  14%|█▍        | 1420/10000 [04:32<27:13,  5.25step/s, loss=0.052991, elapsed=4.5min]

Entraînement:  14%|█▍        | 1421/10000 [04:32<27:10,  5.26step/s, loss=0.052991, elapsed=4.5min]

Entraînement:  14%|█▍        | 1421/10000 [04:32<27:10,  5.26step/s, loss=0.051235, elapsed=4.5min]

Entraînement:  14%|█▍        | 1422/10000 [04:32<27:12,  5.25step/s, loss=0.051235, elapsed=4.5min]

Entraînement:  14%|█▍        | 1422/10000 [04:32<27:12,  5.25step/s, loss=0.085248, elapsed=4.5min]

Entraînement:  14%|█▍        | 1423/10000 [04:32<27:12,  5.25step/s, loss=0.085248, elapsed=4.5min]

Entraînement:  14%|█▍        | 1423/10000 [04:32<27:12,  5.25step/s, loss=0.064823, elapsed=4.5min]

Entraînement:  14%|█▍        | 1424/10000 [04:32<27:11,  5.26step/s, loss=0.064823, elapsed=4.5min]

Entraînement:  14%|█▍        | 1424/10000 [04:32<27:11,  5.26step/s, loss=0.037738, elapsed=4.5min]

Entraînement:  14%|█▍        | 1425/10000 [04:33<27:10,  5.26step/s, loss=0.037738, elapsed=4.5min]

Entraînement:  14%|█▍        | 1425/10000 [04:33<27:10,  5.26step/s, loss=0.042960, elapsed=4.6min]

Entraînement:  14%|█▍        | 1426/10000 [04:33<27:06,  5.27step/s, loss=0.042960, elapsed=4.6min]

Entraînement:  14%|█▍        | 1426/10000 [04:33<27:06,  5.27step/s, loss=0.047023, elapsed=4.6min]

Entraînement:  14%|█▍        | 1427/10000 [04:33<27:03,  5.28step/s, loss=0.047023, elapsed=4.6min]

Entraînement:  14%|█▍        | 1427/10000 [04:33<27:03,  5.28step/s, loss=0.050866, elapsed=4.6min]

Entraînement:  14%|█▍        | 1428/10000 [04:33<27:11,  5.26step/s, loss=0.050866, elapsed=4.6min]

Entraînement:  14%|█▍        | 1428/10000 [04:33<27:11,  5.26step/s, loss=0.036838, elapsed=4.6min]

Entraînement:  14%|█▍        | 1429/10000 [04:33<27:07,  5.27step/s, loss=0.036838, elapsed=4.6min]

Entraînement:  14%|█▍        | 1429/10000 [04:33<27:07,  5.27step/s, loss=0.050850, elapsed=4.6min]

Entraînement:  14%|█▍        | 1430/10000 [04:34<27:02,  5.28step/s, loss=0.050850, elapsed=4.6min]

Entraînement:  14%|█▍        | 1430/10000 [04:34<27:02,  5.28step/s, loss=0.052155, elapsed=4.6min]

Entraînement:  14%|█▍        | 1431/10000 [04:34<27:05,  5.27step/s, loss=0.052155, elapsed=4.6min]

Entraînement:  14%|█▍        | 1431/10000 [04:34<27:05,  5.27step/s, loss=0.060380, elapsed=4.6min]

Entraînement:  14%|█▍        | 1432/10000 [04:34<27:04,  5.27step/s, loss=0.060380, elapsed=4.6min]

Entraînement:  14%|█▍        | 1432/10000 [04:34<27:04,  5.27step/s, loss=0.059554, elapsed=4.6min]

Entraînement:  14%|█▍        | 1433/10000 [04:34<27:03,  5.28step/s, loss=0.059554, elapsed=4.6min]

Entraînement:  14%|█▍        | 1433/10000 [04:34<27:03,  5.28step/s, loss=0.038645, elapsed=4.6min]

Entraînement:  14%|█▍        | 1434/10000 [04:34<27:03,  5.27step/s, loss=0.038645, elapsed=4.6min]

Entraînement:  14%|█▍        | 1434/10000 [04:34<27:03,  5.27step/s, loss=0.091282, elapsed=4.6min]

Entraînement:  14%|█▍        | 1435/10000 [04:35<27:00,  5.28step/s, loss=0.091282, elapsed=4.6min]

Entraînement:  14%|█▍        | 1435/10000 [04:35<27:00,  5.28step/s, loss=0.040207, elapsed=4.6min]

Entraînement:  14%|█▍        | 1436/10000 [04:35<26:59,  5.29step/s, loss=0.040207, elapsed=4.6min]

Entraînement:  14%|█▍        | 1436/10000 [04:35<26:59,  5.29step/s, loss=0.038684, elapsed=4.6min]

Entraînement:  14%|█▍        | 1437/10000 [04:35<26:58,  5.29step/s, loss=0.038684, elapsed=4.6min]

Entraînement:  14%|█▍        | 1437/10000 [04:35<26:58,  5.29step/s, loss=0.051079, elapsed=4.6min]

Entraînement:  14%|█▍        | 1438/10000 [04:35<26:58,  5.29step/s, loss=0.051079, elapsed=4.6min]

Entraînement:  14%|█▍        | 1438/10000 [04:35<26:58,  5.29step/s, loss=0.090045, elapsed=4.6min]

Entraînement:  14%|█▍        | 1439/10000 [04:35<27:01,  5.28step/s, loss=0.090045, elapsed=4.6min]

Entraînement:  14%|█▍        | 1439/10000 [04:35<27:01,  5.28step/s, loss=0.077860, elapsed=4.6min]

Entraînement:  14%|█▍        | 1440/10000 [04:35<27:02,  5.28step/s, loss=0.077860, elapsed=4.6min]

Entraînement:  14%|█▍        | 1440/10000 [04:35<27:02,  5.28step/s, loss=0.079411, elapsed=4.6min]

Entraînement:  14%|█▍        | 1441/10000 [04:36<27:00,  5.28step/s, loss=0.079411, elapsed=4.6min]

Entraînement:  14%|█▍        | 1441/10000 [04:36<27:00,  5.28step/s, loss=0.052321, elapsed=4.6min]

Entraînement:  14%|█▍        | 1442/10000 [04:36<26:57,  5.29step/s, loss=0.052321, elapsed=4.6min]

Entraînement:  14%|█▍        | 1442/10000 [04:36<26:57,  5.29step/s, loss=0.058145, elapsed=4.6min]

Entraînement:  14%|█▍        | 1443/10000 [04:36<26:59,  5.29step/s, loss=0.058145, elapsed=4.6min]

Entraînement:  14%|█▍        | 1443/10000 [04:36<26:59,  5.29step/s, loss=0.060931, elapsed=4.6min]

Entraînement:  14%|█▍        | 1444/10000 [04:36<26:57,  5.29step/s, loss=0.060931, elapsed=4.6min]

Entraînement:  14%|█▍        | 1444/10000 [04:36<26:57,  5.29step/s, loss=0.111216, elapsed=4.6min]

Entraînement:  14%|█▍        | 1445/10000 [04:36<26:57,  5.29step/s, loss=0.111216, elapsed=4.6min]

Entraînement:  14%|█▍        | 1445/10000 [04:36<26:57,  5.29step/s, loss=0.149453, elapsed=4.6min]

Entraînement:  14%|█▍        | 1446/10000 [04:37<26:57,  5.29step/s, loss=0.149453, elapsed=4.6min]

Entraînement:  14%|█▍        | 1446/10000 [04:37<26:57,  5.29step/s, loss=0.134576, elapsed=4.6min]

Entraînement:  14%|█▍        | 1447/10000 [04:37<26:56,  5.29step/s, loss=0.134576, elapsed=4.6min]

Entraînement:  14%|█▍        | 1447/10000 [04:37<26:56,  5.29step/s, loss=0.057555, elapsed=4.6min]

Entraînement:  14%|█▍        | 1448/10000 [04:37<27:04,  5.26step/s, loss=0.057555, elapsed=4.6min]

Entraînement:  14%|█▍        | 1448/10000 [04:37<27:04,  5.26step/s, loss=0.035819, elapsed=4.6min]

Entraînement:  14%|█▍        | 1449/10000 [04:37<27:02,  5.27step/s, loss=0.035819, elapsed=4.6min]

Entraînement:  14%|█▍        | 1449/10000 [04:37<27:02,  5.27step/s, loss=0.124529, elapsed=4.6min]

Entraînement:  14%|█▍        | 1450/10000 [04:37<27:03,  5.27step/s, loss=0.124529, elapsed=4.6min]

Entraînement:  14%|█▍        | 1450/10000 [04:37<27:03,  5.27step/s, loss=0.096630, elapsed=4.6min]

Entraînement:  15%|█▍        | 1451/10000 [04:38<27:00,  5.28step/s, loss=0.096630, elapsed=4.6min]

Entraînement:  15%|█▍        | 1451/10000 [04:38<27:00,  5.28step/s, loss=0.033419, elapsed=4.6min]

Entraînement:  15%|█▍        | 1452/10000 [04:38<26:57,  5.28step/s, loss=0.033419, elapsed=4.6min]

Entraînement:  15%|█▍        | 1452/10000 [04:38<26:57,  5.28step/s, loss=0.095499, elapsed=4.6min]

Entraînement:  15%|█▍        | 1453/10000 [04:38<26:58,  5.28step/s, loss=0.095499, elapsed=4.6min]

Entraînement:  15%|█▍        | 1453/10000 [04:38<26:58,  5.28step/s, loss=0.064735, elapsed=4.6min]

Entraînement:  15%|█▍        | 1454/10000 [04:38<26:58,  5.28step/s, loss=0.064735, elapsed=4.6min]

Entraînement:  15%|█▍        | 1454/10000 [04:38<26:58,  5.28step/s, loss=0.037972, elapsed=4.6min]

Entraînement:  15%|█▍        | 1455/10000 [04:38<27:01,  5.27step/s, loss=0.037972, elapsed=4.6min]

Entraînement:  15%|█▍        | 1455/10000 [04:38<27:01,  5.27step/s, loss=0.041772, elapsed=4.6min]

Entraînement:  15%|█▍        | 1456/10000 [04:39<27:01,  5.27step/s, loss=0.041772, elapsed=4.6min]

Entraînement:  15%|█▍        | 1456/10000 [04:39<27:01,  5.27step/s, loss=0.065076, elapsed=4.7min]

Entraînement:  15%|█▍        | 1457/10000 [04:39<27:00,  5.27step/s, loss=0.065076, elapsed=4.7min]

Entraînement:  15%|█▍        | 1457/10000 [04:39<27:00,  5.27step/s, loss=0.222916, elapsed=4.7min]

Entraînement:  15%|█▍        | 1458/10000 [04:39<27:00,  5.27step/s, loss=0.222916, elapsed=4.7min]

Entraînement:  15%|█▍        | 1458/10000 [04:39<27:00,  5.27step/s, loss=0.036436, elapsed=4.7min]

Entraînement:  15%|█▍        | 1459/10000 [04:39<26:58,  5.28step/s, loss=0.036436, elapsed=4.7min]

Entraînement:  15%|█▍        | 1459/10000 [04:39<26:58,  5.28step/s, loss=0.049462, elapsed=4.7min]

Entraînement:  15%|█▍        | 1460/10000 [04:39<26:56,  5.28step/s, loss=0.049462, elapsed=4.7min]

Entraînement:  15%|█▍        | 1460/10000 [04:39<26:56,  5.28step/s, loss=0.052057, elapsed=4.7min]

Entraînement:  15%|█▍        | 1461/10000 [04:39<26:56,  5.28step/s, loss=0.052057, elapsed=4.7min]

Entraînement:  15%|█▍        | 1461/10000 [04:39<26:56,  5.28step/s, loss=0.046289, elapsed=4.7min]

Entraînement:  15%|█▍        | 1462/10000 [04:40<26:56,  5.28step/s, loss=0.046289, elapsed=4.7min]

Entraînement:  15%|█▍        | 1462/10000 [04:40<26:56,  5.28step/s, loss=0.079391, elapsed=4.7min]

Entraînement:  15%|█▍        | 1463/10000 [04:40<26:59,  5.27step/s, loss=0.079391, elapsed=4.7min]

Entraînement:  15%|█▍        | 1463/10000 [04:40<26:59,  5.27step/s, loss=0.068338, elapsed=4.7min]

Entraînement:  15%|█▍        | 1464/10000 [04:40<26:59,  5.27step/s, loss=0.068338, elapsed=4.7min]

Entraînement:  15%|█▍        | 1464/10000 [04:40<26:59,  5.27step/s, loss=0.053312, elapsed=4.7min]

Entraînement:  15%|█▍        | 1465/10000 [04:40<26:58,  5.27step/s, loss=0.053312, elapsed=4.7min]

Entraînement:  15%|█▍        | 1465/10000 [04:40<26:58,  5.27step/s, loss=0.114197, elapsed=4.7min]

Entraînement:  15%|█▍        | 1466/10000 [04:40<26:57,  5.28step/s, loss=0.114197, elapsed=4.7min]

Entraînement:  15%|█▍        | 1466/10000 [04:40<26:57,  5.28step/s, loss=0.047956, elapsed=4.7min]

Entraînement:  15%|█▍        | 1467/10000 [04:41<26:54,  5.29step/s, loss=0.047956, elapsed=4.7min]

Entraînement:  15%|█▍        | 1467/10000 [04:41<26:54,  5.29step/s, loss=0.086500, elapsed=4.7min]

Entraînement:  15%|█▍        | 1468/10000 [04:41<26:54,  5.28step/s, loss=0.086500, elapsed=4.7min]

Entraînement:  15%|█▍        | 1468/10000 [04:41<26:54,  5.28step/s, loss=0.079883, elapsed=4.7min]

Entraînement:  15%|█▍        | 1469/10000 [04:41<26:52,  5.29step/s, loss=0.079883, elapsed=4.7min]

Entraînement:  15%|█▍        | 1469/10000 [04:41<26:52,  5.29step/s, loss=0.134752, elapsed=4.7min]

Entraînement:  15%|█▍        | 1470/10000 [04:41<26:55,  5.28step/s, loss=0.134752, elapsed=4.7min]

Entraînement:  15%|█▍        | 1470/10000 [04:41<26:55,  5.28step/s, loss=0.065715, elapsed=4.7min]

Entraînement:  15%|█▍        | 1471/10000 [04:41<26:57,  5.27step/s, loss=0.065715, elapsed=4.7min]

Entraînement:  15%|█▍        | 1471/10000 [04:41<26:57,  5.27step/s, loss=0.063904, elapsed=4.7min]

Entraînement:  15%|█▍        | 1472/10000 [04:42<26:55,  5.28step/s, loss=0.063904, elapsed=4.7min]

Entraînement:  15%|█▍        | 1472/10000 [04:42<26:55,  5.28step/s, loss=0.082851, elapsed=4.7min]

Entraînement:  15%|█▍        | 1473/10000 [04:42<26:55,  5.28step/s, loss=0.082851, elapsed=4.7min]

Entraînement:  15%|█▍        | 1473/10000 [04:42<26:55,  5.28step/s, loss=0.089869, elapsed=4.7min]

Entraînement:  15%|█▍        | 1474/10000 [04:42<26:53,  5.28step/s, loss=0.089869, elapsed=4.7min]

Entraînement:  15%|█▍        | 1474/10000 [04:42<26:53,  5.28step/s, loss=0.056781, elapsed=4.7min]

Entraînement:  15%|█▍        | 1475/10000 [04:42<26:53,  5.28step/s, loss=0.056781, elapsed=4.7min]

Entraînement:  15%|█▍        | 1475/10000 [04:42<26:53,  5.28step/s, loss=0.065714, elapsed=4.7min]

Entraînement:  15%|█▍        | 1476/10000 [04:42<26:55,  5.28step/s, loss=0.065714, elapsed=4.7min]

Entraînement:  15%|█▍        | 1476/10000 [04:42<26:55,  5.28step/s, loss=0.047674, elapsed=4.7min]

Entraînement:  15%|█▍        | 1477/10000 [04:42<26:51,  5.29step/s, loss=0.047674, elapsed=4.7min]

Entraînement:  15%|█▍        | 1477/10000 [04:43<26:51,  5.29step/s, loss=0.073401, elapsed=4.7min]

Entraînement:  15%|█▍        | 1478/10000 [04:43<26:54,  5.28step/s, loss=0.073401, elapsed=4.7min]

Entraînement:  15%|█▍        | 1478/10000 [04:43<26:54,  5.28step/s, loss=0.045901, elapsed=4.7min]

Entraînement:  15%|█▍        | 1479/10000 [04:43<26:57,  5.27step/s, loss=0.045901, elapsed=4.7min]

Entraînement:  15%|█▍        | 1479/10000 [04:43<26:57,  5.27step/s, loss=0.099386, elapsed=4.7min]

Entraînement:  15%|█▍        | 1480/10000 [04:43<27:01,  5.26step/s, loss=0.099386, elapsed=4.7min]

Entraînement:  15%|█▍        | 1480/10000 [04:43<27:01,  5.26step/s, loss=0.067668, elapsed=4.7min]

Entraînement:  15%|█▍        | 1481/10000 [04:43<26:57,  5.27step/s, loss=0.067668, elapsed=4.7min]

Entraînement:  15%|█▍        | 1481/10000 [04:43<26:57,  5.27step/s, loss=0.047752, elapsed=4.7min]

Entraînement:  15%|█▍        | 1482/10000 [04:43<26:57,  5.27step/s, loss=0.047752, elapsed=4.7min]

Entraînement:  15%|█▍        | 1482/10000 [04:43<26:57,  5.27step/s, loss=0.041191, elapsed=4.7min]

Entraînement:  15%|█▍        | 1483/10000 [04:44<26:54,  5.27step/s, loss=0.041191, elapsed=4.7min]

Entraînement:  15%|█▍        | 1483/10000 [04:44<26:54,  5.27step/s, loss=0.039568, elapsed=4.7min]

Entraînement:  15%|█▍        | 1484/10000 [04:44<26:51,  5.28step/s, loss=0.039568, elapsed=4.7min]

Entraînement:  15%|█▍        | 1484/10000 [04:44<26:51,  5.28step/s, loss=0.061179, elapsed=4.7min]

Entraînement:  15%|█▍        | 1485/10000 [04:44<26:52,  5.28step/s, loss=0.061179, elapsed=4.7min]

Entraînement:  15%|█▍        | 1485/10000 [04:44<26:52,  5.28step/s, loss=0.082521, elapsed=4.7min]

Entraînement:  15%|█▍        | 1486/10000 [04:44<26:50,  5.29step/s, loss=0.082521, elapsed=4.7min]

Entraînement:  15%|█▍        | 1486/10000 [04:44<26:50,  5.29step/s, loss=0.091095, elapsed=4.7min]

Entraînement:  15%|█▍        | 1487/10000 [04:44<26:55,  5.27step/s, loss=0.091095, elapsed=4.7min]

Entraînement:  15%|█▍        | 1487/10000 [04:44<26:55,  5.27step/s, loss=0.115559, elapsed=4.7min]

Entraînement:  15%|█▍        | 1488/10000 [04:45<26:53,  5.28step/s, loss=0.115559, elapsed=4.7min]

Entraînement:  15%|█▍        | 1488/10000 [04:45<26:53,  5.28step/s, loss=0.061459, elapsed=4.8min]

Entraînement:  15%|█▍        | 1489/10000 [04:45<26:53,  5.28step/s, loss=0.061459, elapsed=4.8min]

Entraînement:  15%|█▍        | 1489/10000 [04:45<26:53,  5.28step/s, loss=0.066245, elapsed=4.8min]

Entraînement:  15%|█▍        | 1490/10000 [04:45<26:52,  5.28step/s, loss=0.066245, elapsed=4.8min]

Entraînement:  15%|█▍        | 1490/10000 [04:45<26:52,  5.28step/s, loss=0.096537, elapsed=4.8min]

Entraînement:  15%|█▍        | 1491/10000 [04:45<26:50,  5.28step/s, loss=0.096537, elapsed=4.8min]

Entraînement:  15%|█▍        | 1491/10000 [04:45<26:50,  5.28step/s, loss=0.066552, elapsed=4.8min]

Entraînement:  15%|█▍        | 1492/10000 [04:45<26:50,  5.28step/s, loss=0.066552, elapsed=4.8min]

Entraînement:  15%|█▍        | 1492/10000 [04:45<26:50,  5.28step/s, loss=0.081764, elapsed=4.8min]

Entraînement:  15%|█▍        | 1493/10000 [04:46<26:47,  5.29step/s, loss=0.081764, elapsed=4.8min]

Entraînement:  15%|█▍        | 1493/10000 [04:46<26:47,  5.29step/s, loss=0.050878, elapsed=4.8min]

Entraînement:  15%|█▍        | 1494/10000 [04:46<26:57,  5.26step/s, loss=0.050878, elapsed=4.8min]

Entraînement:  15%|█▍        | 1494/10000 [04:46<26:57,  5.26step/s, loss=0.067904, elapsed=4.8min]

Entraînement:  15%|█▍        | 1495/10000 [04:46<26:56,  5.26step/s, loss=0.067904, elapsed=4.8min]

Entraînement:  15%|█▍        | 1495/10000 [04:46<26:56,  5.26step/s, loss=0.103406, elapsed=4.8min]

Entraînement:  15%|█▍        | 1496/10000 [04:46<26:57,  5.26step/s, loss=0.103406, elapsed=4.8min]

Entraînement:  15%|█▍        | 1496/10000 [04:46<26:57,  5.26step/s, loss=0.050131, elapsed=4.8min]

Entraînement:  15%|█▍        | 1497/10000 [04:46<26:54,  5.27step/s, loss=0.050131, elapsed=4.8min]

Entraînement:  15%|█▍        | 1497/10000 [04:46<26:54,  5.27step/s, loss=0.073946, elapsed=4.8min]

Entraînement:  15%|█▍        | 1498/10000 [04:46<26:51,  5.27step/s, loss=0.073946, elapsed=4.8min]

Entraînement:  15%|█▍        | 1498/10000 [04:46<26:51,  5.27step/s, loss=0.177884, elapsed=4.8min]

Entraînement:  15%|█▍        | 1499/10000 [04:47<26:51,  5.28step/s, loss=0.177884, elapsed=4.8min]

Entraînement:  15%|█▍        | 1499/10000 [04:47<26:51,  5.28step/s, loss=0.130464, elapsed=4.8min]

Entraînement:  15%|█▌        | 1500/10000 [04:47<26:49,  5.28step/s, loss=0.130464, elapsed=4.8min]

Entraînement:  15%|█▌        | 1500/10000 [04:47<26:49,  5.28step/s, loss=0.152514, elapsed=4.8min]

Entraînement:  15%|█▌        | 1500/10000 [04:47<26:49,  5.28step/s, loss=0.152514, elapsed=4.8min]

Entraînement:  15%|█▌        | 1501/10000 [04:47<27:04,  5.23step/s, loss=0.152514, elapsed=4.8min]

Entraînement:  15%|█▌        | 1501/10000 [04:47<27:04,  5.23step/s, loss=0.089900, elapsed=4.8min]

Step 1500/10000 | Train loss: 0.152514 | Elapsed: 4.8min | ETA: 27.1min

Entraînement:  15%|█▌        | 1502/10000 [04:47<27:00,  5.24step/s, loss=0.089900, elapsed=4.8min]

Entraînement:  15%|█▌        | 1502/10000 [04:47<27:00,  5.24step/s, loss=0.127525, elapsed=4.8min]

Entraînement:  15%|█▌        | 1503/10000 [04:47<26:57,  5.25step/s, loss=0.127525, elapsed=4.8min]

Entraînement:  15%|█▌        | 1503/10000 [04:47<26:57,  5.25step/s, loss=0.057195, elapsed=4.8min]

Entraînement:  15%|█▌        | 1504/10000 [04:48<26:55,  5.26step/s, loss=0.057195, elapsed=4.8min]

Entraînement:  15%|█▌        | 1504/10000 [04:48<26:55,  5.26step/s, loss=0.066544, elapsed=4.8min]

Entraînement:  15%|█▌        | 1505/10000 [04:48<26:50,  5.27step/s, loss=0.066544, elapsed=4.8min]

Entraînement:  15%|█▌        | 1505/10000 [04:48<26:50,  5.27step/s, loss=0.088950, elapsed=4.8min]

Entraînement:  15%|█▌        | 1506/10000 [04:48<26:49,  5.28step/s, loss=0.088950, elapsed=4.8min]

Entraînement:  15%|█▌        | 1506/10000 [04:48<26:49,  5.28step/s, loss=0.198271, elapsed=4.8min]

Entraînement:  15%|█▌        | 1507/10000 [04:48<26:48,  5.28step/s, loss=0.198271, elapsed=4.8min]

Entraînement:  15%|█▌        | 1507/10000 [04:48<26:48,  5.28step/s, loss=0.052910, elapsed=4.8min]

Entraînement:  15%|█▌        | 1508/10000 [04:48<26:50,  5.27step/s, loss=0.052910, elapsed=4.8min]

Entraînement:  15%|█▌        | 1508/10000 [04:48<26:50,  5.27step/s, loss=0.058096, elapsed=4.8min]

Entraînement:  15%|█▌        | 1509/10000 [04:49<26:49,  5.28step/s, loss=0.058096, elapsed=4.8min]

Entraînement:  15%|█▌        | 1509/10000 [04:49<26:49,  5.28step/s, loss=0.082106, elapsed=4.8min]

Entraînement:  15%|█▌        | 1510/10000 [04:49<26:46,  5.28step/s, loss=0.082106, elapsed=4.8min]

Entraînement:  15%|█▌        | 1510/10000 [04:49<26:46,  5.28step/s, loss=0.083292, elapsed=4.8min]

Entraînement:  15%|█▌        | 1511/10000 [04:49<26:49,  5.27step/s, loss=0.083292, elapsed=4.8min]

Entraînement:  15%|█▌        | 1511/10000 [04:49<26:49,  5.27step/s, loss=0.055156, elapsed=4.8min]

Entraînement:  15%|█▌        | 1512/10000 [04:49<26:46,  5.28step/s, loss=0.055156, elapsed=4.8min]

Entraînement:  15%|█▌        | 1512/10000 [04:49<26:46,  5.28step/s, loss=0.086275, elapsed=4.8min]

Entraînement:  15%|█▌        | 1513/10000 [04:49<26:48,  5.28step/s, loss=0.086275, elapsed=4.8min]

Entraînement:  15%|█▌        | 1513/10000 [04:49<26:48,  5.28step/s, loss=0.040238, elapsed=4.8min]

Entraînement:  15%|█▌        | 1514/10000 [04:50<26:45,  5.29step/s, loss=0.040238, elapsed=4.8min]

Entraînement:  15%|█▌        | 1514/10000 [04:50<26:45,  5.29step/s, loss=0.146416, elapsed=4.8min]

Entraînement:  15%|█▌        | 1515/10000 [04:50<26:45,  5.28step/s, loss=0.146416, elapsed=4.8min]

Entraînement:  15%|█▌        | 1515/10000 [04:50<26:45,  5.28step/s, loss=0.172272, elapsed=4.8min]

Entraînement:  15%|█▌        | 1516/10000 [04:50<26:47,  5.28step/s, loss=0.172272, elapsed=4.8min]

Entraînement:  15%|█▌        | 1516/10000 [04:50<26:47,  5.28step/s, loss=0.095482, elapsed=4.8min]

Entraînement:  15%|█▌        | 1517/10000 [04:50<26:52,  5.26step/s, loss=0.095482, elapsed=4.8min]

Entraînement:  15%|█▌        | 1517/10000 [04:50<26:52,  5.26step/s, loss=0.087954, elapsed=4.8min]

Entraînement:  15%|█▌        | 1518/10000 [04:50<26:53,  5.26step/s, loss=0.087954, elapsed=4.8min]

Entraînement:  15%|█▌        | 1518/10000 [04:50<26:53,  5.26step/s, loss=0.091630, elapsed=4.8min]

Entraînement:  15%|█▌        | 1519/10000 [04:50<26:50,  5.27step/s, loss=0.091630, elapsed=4.8min]

Entraînement:  15%|█▌        | 1519/10000 [04:50<26:50,  5.27step/s, loss=0.045125, elapsed=4.8min]

Entraînement:  15%|█▌        | 1520/10000 [04:51<26:49,  5.27step/s, loss=0.045125, elapsed=4.8min]

Entraînement:  15%|█▌        | 1520/10000 [04:51<26:49,  5.27step/s, loss=0.074578, elapsed=4.9min]

Entraînement:  15%|█▌        | 1521/10000 [04:51<26:48,  5.27step/s, loss=0.074578, elapsed=4.9min]

Entraînement:  15%|█▌        | 1521/10000 [04:51<26:48,  5.27step/s, loss=0.032720, elapsed=4.9min]

Entraînement:  15%|█▌        | 1522/10000 [04:51<26:44,  5.28step/s, loss=0.032720, elapsed=4.9min]

Entraînement:  15%|█▌        | 1522/10000 [04:51<26:44,  5.28step/s, loss=0.077064, elapsed=4.9min]

Entraînement:  15%|█▌        | 1523/10000 [04:51<26:44,  5.28step/s, loss=0.077064, elapsed=4.9min]

Entraînement:  15%|█▌        | 1523/10000 [04:51<26:44,  5.28step/s, loss=0.068155, elapsed=4.9min]

Entraînement:  15%|█▌        | 1524/10000 [04:51<26:43,  5.28step/s, loss=0.068155, elapsed=4.9min]

Entraînement:  15%|█▌        | 1524/10000 [04:51<26:43,  5.28step/s, loss=0.060604, elapsed=4.9min]

Entraînement:  15%|█▌        | 1525/10000 [04:52<26:42,  5.29step/s, loss=0.060604, elapsed=4.9min]

Entraînement:  15%|█▌        | 1525/10000 [04:52<26:42,  5.29step/s, loss=0.040532, elapsed=4.9min]

Entraînement:  15%|█▌        | 1526/10000 [04:52<26:45,  5.28step/s, loss=0.040532, elapsed=4.9min]

Entraînement:  15%|█▌        | 1526/10000 [04:52<26:45,  5.28step/s, loss=0.092687, elapsed=4.9min]

Entraînement:  15%|█▌        | 1527/10000 [04:52<26:43,  5.28step/s, loss=0.092687, elapsed=4.9min]

Entraînement:  15%|█▌        | 1527/10000 [04:52<26:43,  5.28step/s, loss=0.042089, elapsed=4.9min]

Entraînement:  15%|█▌        | 1528/10000 [04:52<26:47,  5.27step/s, loss=0.042089, elapsed=4.9min]

Entraînement:  15%|█▌        | 1528/10000 [04:52<26:47,  5.27step/s, loss=0.051618, elapsed=4.9min]

Entraînement:  15%|█▌        | 1529/10000 [04:52<26:47,  5.27step/s, loss=0.051618, elapsed=4.9min]

Entraînement:  15%|█▌        | 1529/10000 [04:52<26:47,  5.27step/s, loss=0.046004, elapsed=4.9min]

Entraînement:  15%|█▌        | 1530/10000 [04:53<26:48,  5.26step/s, loss=0.046004, elapsed=4.9min]

Entraînement:  15%|█▌        | 1530/10000 [04:53<26:48,  5.26step/s, loss=0.075535, elapsed=4.9min]

Entraînement:  15%|█▌        | 1531/10000 [04:53<26:46,  5.27step/s, loss=0.075535, elapsed=4.9min]

Entraînement:  15%|█▌        | 1531/10000 [04:53<26:46,  5.27step/s, loss=0.052780, elapsed=4.9min]

Entraînement:  15%|█▌        | 1532/10000 [04:53<26:46,  5.27step/s, loss=0.052780, elapsed=4.9min]

Entraînement:  15%|█▌        | 1532/10000 [04:53<26:46,  5.27step/s, loss=0.086194, elapsed=4.9min]

Entraînement:  15%|█▌        | 1533/10000 [04:53<26:47,  5.27step/s, loss=0.086194, elapsed=4.9min]

Entraînement:  15%|█▌        | 1533/10000 [04:53<26:47,  5.27step/s, loss=0.065831, elapsed=4.9min]

Entraînement:  15%|█▌        | 1534/10000 [04:53<26:45,  5.27step/s, loss=0.065831, elapsed=4.9min]

Entraînement:  15%|█▌        | 1534/10000 [04:53<26:45,  5.27step/s, loss=0.033436, elapsed=4.9min]

Entraînement:  15%|█▌        | 1535/10000 [04:54<26:49,  5.26step/s, loss=0.033436, elapsed=4.9min]

Entraînement:  15%|█▌        | 1535/10000 [04:54<26:49,  5.26step/s, loss=0.058770, elapsed=4.9min]

Entraînement:  15%|█▌        | 1536/10000 [04:54<26:45,  5.27step/s, loss=0.058770, elapsed=4.9min]

Entraînement:  15%|█▌        | 1536/10000 [04:54<26:45,  5.27step/s, loss=0.150110, elapsed=4.9min]

Entraînement:  15%|█▌        | 1537/10000 [04:54<26:47,  5.27step/s, loss=0.150110, elapsed=4.9min]

Entraînement:  15%|█▌        | 1537/10000 [04:54<26:47,  5.27step/s, loss=0.036293, elapsed=4.9min]

Entraînement:  15%|█▌        | 1538/10000 [04:54<26:44,  5.27step/s, loss=0.036293, elapsed=4.9min]

Entraînement:  15%|█▌        | 1538/10000 [04:54<26:44,  5.27step/s, loss=0.108537, elapsed=4.9min]

Entraînement:  15%|█▌        | 1539/10000 [04:54<26:43,  5.28step/s, loss=0.108537, elapsed=4.9min]

Entraînement:  15%|█▌        | 1539/10000 [04:54<26:43,  5.28step/s, loss=0.065939, elapsed=4.9min]

Entraînement:  15%|█▌        | 1540/10000 [04:54<26:42,  5.28step/s, loss=0.065939, elapsed=4.9min]

Entraînement:  15%|█▌        | 1540/10000 [04:54<26:42,  5.28step/s, loss=0.058791, elapsed=4.9min]

Entraînement:  15%|█▌        | 1541/10000 [04:55<26:40,  5.29step/s, loss=0.058791, elapsed=4.9min]

Entraînement:  15%|█▌        | 1541/10000 [04:55<26:40,  5.29step/s, loss=0.089182, elapsed=4.9min]

Entraînement:  15%|█▌        | 1542/10000 [04:55<26:42,  5.28step/s, loss=0.089182, elapsed=4.9min]

Entraînement:  15%|█▌        | 1542/10000 [04:55<26:42,  5.28step/s, loss=0.129487, elapsed=4.9min]

Entraînement:  15%|█▌        | 1543/10000 [04:55<26:41,  5.28step/s, loss=0.129487, elapsed=4.9min]

Entraînement:  15%|█▌        | 1543/10000 [04:55<26:41,  5.28step/s, loss=0.109389, elapsed=4.9min]

Entraînement:  15%|█▌        | 1544/10000 [04:55<26:39,  5.29step/s, loss=0.109389, elapsed=4.9min]

Entraînement:  15%|█▌        | 1544/10000 [04:55<26:39,  5.29step/s, loss=0.067780, elapsed=4.9min]

Entraînement:  15%|█▌        | 1545/10000 [04:55<26:39,  5.29step/s, loss=0.067780, elapsed=4.9min]

Entraînement:  15%|█▌        | 1545/10000 [04:55<26:39,  5.29step/s, loss=0.042249, elapsed=4.9min]

Entraînement:  15%|█▌        | 1546/10000 [04:56<26:38,  5.29step/s, loss=0.042249, elapsed=4.9min]

Entraînement:  15%|█▌        | 1546/10000 [04:56<26:38,  5.29step/s, loss=0.053950, elapsed=4.9min]

Entraînement:  15%|█▌        | 1547/10000 [04:56<26:36,  5.30step/s, loss=0.053950, elapsed=4.9min]

Entraînement:  15%|█▌        | 1547/10000 [04:56<26:36,  5.30step/s, loss=0.058816, elapsed=4.9min]

Entraînement:  15%|█▌        | 1548/10000 [04:56<26:38,  5.29step/s, loss=0.058816, elapsed=4.9min]

Entraînement:  15%|█▌        | 1548/10000 [04:56<26:38,  5.29step/s, loss=0.034246, elapsed=4.9min]

Entraînement:  15%|█▌        | 1549/10000 [04:56<26:38,  5.29step/s, loss=0.034246, elapsed=4.9min]

Entraînement:  15%|█▌        | 1549/10000 [04:56<26:38,  5.29step/s, loss=0.050487, elapsed=4.9min]

Entraînement:  16%|█▌        | 1550/10000 [04:56<26:40,  5.28step/s, loss=0.050487, elapsed=4.9min]

Entraînement:  16%|█▌        | 1550/10000 [04:56<26:40,  5.28step/s, loss=0.094414, elapsed=4.9min]

Entraînement:  16%|█▌        | 1551/10000 [04:57<26:39,  5.28step/s, loss=0.094414, elapsed=4.9min]

Entraînement:  16%|█▌        | 1551/10000 [04:57<26:39,  5.28step/s, loss=0.104537, elapsed=5.0min]

Entraînement:  16%|█▌        | 1552/10000 [04:57<26:39,  5.28step/s, loss=0.104537, elapsed=5.0min]

Entraînement:  16%|█▌        | 1552/10000 [04:57<26:39,  5.28step/s, loss=0.095083, elapsed=5.0min]

Entraînement:  16%|█▌        | 1553/10000 [04:57<26:38,  5.28step/s, loss=0.095083, elapsed=5.0min]

Entraînement:  16%|█▌        | 1553/10000 [04:57<26:38,  5.28step/s, loss=0.055507, elapsed=5.0min]

Entraînement:  16%|█▌        | 1554/10000 [04:57<26:37,  5.29step/s, loss=0.055507, elapsed=5.0min]

Entraînement:  16%|█▌        | 1554/10000 [04:57<26:37,  5.29step/s, loss=0.027072, elapsed=5.0min]

Entraînement:  16%|█▌        | 1555/10000 [04:57<26:39,  5.28step/s, loss=0.027072, elapsed=5.0min]

Entraînement:  16%|█▌        | 1555/10000 [04:57<26:39,  5.28step/s, loss=0.055916, elapsed=5.0min]

Entraînement:  16%|█▌        | 1556/10000 [04:57<26:38,  5.28step/s, loss=0.055916, elapsed=5.0min]

Entraînement:  16%|█▌        | 1556/10000 [04:57<26:38,  5.28step/s, loss=0.096560, elapsed=5.0min]

Entraînement:  16%|█▌        | 1557/10000 [04:58<26:43,  5.27step/s, loss=0.096560, elapsed=5.0min]

Entraînement:  16%|█▌        | 1557/10000 [04:58<26:43,  5.27step/s, loss=0.046363, elapsed=5.0min]

Entraînement:  16%|█▌        | 1558/10000 [04:58<26:44,  5.26step/s, loss=0.046363, elapsed=5.0min]

Entraînement:  16%|█▌        | 1558/10000 [04:58<26:44,  5.26step/s, loss=0.075044, elapsed=5.0min]

Entraînement:  16%|█▌        | 1559/10000 [04:58<26:47,  5.25step/s, loss=0.075044, elapsed=5.0min]

Entraînement:  16%|█▌        | 1559/10000 [04:58<26:47,  5.25step/s, loss=0.039208, elapsed=5.0min]

Entraînement:  16%|█▌        | 1560/10000 [04:58<26:45,  5.26step/s, loss=0.039208, elapsed=5.0min]

Entraînement:  16%|█▌        | 1560/10000 [04:58<26:45,  5.26step/s, loss=0.043887, elapsed=5.0min]

Entraînement:  16%|█▌        | 1561/10000 [04:58<26:43,  5.26step/s, loss=0.043887, elapsed=5.0min]

Entraînement:  16%|█▌        | 1561/10000 [04:58<26:43,  5.26step/s, loss=0.068661, elapsed=5.0min]

Entraînement:  16%|█▌        | 1562/10000 [04:59<26:47,  5.25step/s, loss=0.068661, elapsed=5.0min]

Entraînement:  16%|█▌        | 1562/10000 [04:59<26:47,  5.25step/s, loss=0.042192, elapsed=5.0min]

Entraînement:  16%|█▌        | 1563/10000 [04:59<26:45,  5.26step/s, loss=0.042192, elapsed=5.0min]

Entraînement:  16%|█▌        | 1563/10000 [04:59<26:45,  5.26step/s, loss=0.049698, elapsed=5.0min]

Entraînement:  16%|█▌        | 1564/10000 [04:59<26:44,  5.26step/s, loss=0.049698, elapsed=5.0min]

Entraînement:  16%|█▌        | 1564/10000 [04:59<26:44,  5.26step/s, loss=0.042152, elapsed=5.0min]

Entraînement:  16%|█▌        | 1565/10000 [04:59<26:41,  5.27step/s, loss=0.042152, elapsed=5.0min]

Entraînement:  16%|█▌        | 1565/10000 [04:59<26:41,  5.27step/s, loss=0.064995, elapsed=5.0min]

Entraînement:  16%|█▌        | 1566/10000 [04:59<26:42,  5.26step/s, loss=0.064995, elapsed=5.0min]

Entraînement:  16%|█▌        | 1566/10000 [04:59<26:42,  5.26step/s, loss=0.059880, elapsed=5.0min]

Entraînement:  16%|█▌        | 1567/10000 [05:00<26:39,  5.27step/s, loss=0.059880, elapsed=5.0min]

Entraînement:  16%|█▌        | 1567/10000 [05:00<26:39,  5.27step/s, loss=0.064130, elapsed=5.0min]

Entraînement:  16%|█▌        | 1568/10000 [05:00<26:36,  5.28step/s, loss=0.064130, elapsed=5.0min]

Entraînement:  16%|█▌        | 1568/10000 [05:00<26:36,  5.28step/s, loss=0.114689, elapsed=5.0min]

Entraînement:  16%|█▌        | 1569/10000 [05:00<26:35,  5.28step/s, loss=0.114689, elapsed=5.0min]

Entraînement:  16%|█▌        | 1569/10000 [05:00<26:35,  5.28step/s, loss=0.048361, elapsed=5.0min]

Entraînement:  16%|█▌        | 1570/10000 [05:00<26:34,  5.29step/s, loss=0.048361, elapsed=5.0min]

Entraînement:  16%|█▌        | 1570/10000 [05:00<26:34,  5.29step/s, loss=0.054076, elapsed=5.0min]

Entraînement:  16%|█▌        | 1571/10000 [05:00<26:31,  5.29step/s, loss=0.054076, elapsed=5.0min]

Entraînement:  16%|█▌        | 1571/10000 [05:00<26:31,  5.29step/s, loss=0.055905, elapsed=5.0min]

Entraînement:  16%|█▌        | 1572/10000 [05:01<26:36,  5.28step/s, loss=0.055905, elapsed=5.0min]

Entraînement:  16%|█▌        | 1572/10000 [05:01<26:36,  5.28step/s, loss=0.063882, elapsed=5.0min]

Entraînement:  16%|█▌        | 1573/10000 [05:01<26:38,  5.27step/s, loss=0.063882, elapsed=5.0min]

Entraînement:  16%|█▌        | 1573/10000 [05:01<26:38,  5.27step/s, loss=0.056393, elapsed=5.0min]

Entraînement:  16%|█▌        | 1574/10000 [05:01<26:39,  5.27step/s, loss=0.056393, elapsed=5.0min]

Entraînement:  16%|█▌        | 1574/10000 [05:01<26:39,  5.27step/s, loss=0.040706, elapsed=5.0min]

Entraînement:  16%|█▌        | 1575/10000 [05:01<26:37,  5.27step/s, loss=0.040706, elapsed=5.0min]

Entraînement:  16%|█▌        | 1575/10000 [05:01<26:37,  5.27step/s, loss=0.078979, elapsed=5.0min]

Entraînement:  16%|█▌        | 1576/10000 [05:01<26:33,  5.29step/s, loss=0.078979, elapsed=5.0min]

Entraînement:  16%|█▌        | 1576/10000 [05:01<26:33,  5.29step/s, loss=0.063493, elapsed=5.0min]

Entraînement:  16%|█▌        | 1577/10000 [05:01<26:33,  5.29step/s, loss=0.063493, elapsed=5.0min]

Entraînement:  16%|█▌        | 1577/10000 [05:01<26:33,  5.29step/s, loss=0.037446, elapsed=5.0min]

Entraînement:  16%|█▌        | 1578/10000 [05:02<26:31,  5.29step/s, loss=0.037446, elapsed=5.0min]

Entraînement:  16%|█▌        | 1578/10000 [05:02<26:31,  5.29step/s, loss=0.054088, elapsed=5.0min]

Entraînement:  16%|█▌        | 1579/10000 [05:02<26:28,  5.30step/s, loss=0.054088, elapsed=5.0min]

Entraînement:  16%|█▌        | 1579/10000 [05:02<26:28,  5.30step/s, loss=0.111984, elapsed=5.0min]

Entraînement:  16%|█▌        | 1580/10000 [05:02<26:33,  5.28step/s, loss=0.111984, elapsed=5.0min]

Entraînement:  16%|█▌        | 1580/10000 [05:02<26:33,  5.28step/s, loss=0.061065, elapsed=5.0min]

Entraînement:  16%|█▌        | 1581/10000 [05:02<26:37,  5.27step/s, loss=0.061065, elapsed=5.0min]

Entraînement:  16%|█▌        | 1581/10000 [05:02<26:37,  5.27step/s, loss=0.029436, elapsed=5.0min]

Entraînement:  16%|█▌        | 1582/10000 [05:02<27:01,  5.19step/s, loss=0.029436, elapsed=5.0min]

Entraînement:  16%|█▌        | 1582/10000 [05:02<27:01,  5.19step/s, loss=0.076431, elapsed=5.0min]

Entraînement:  16%|█▌        | 1583/10000 [05:03<26:54,  5.21step/s, loss=0.076431, elapsed=5.0min]

Entraînement:  16%|█▌        | 1583/10000 [05:03<26:54,  5.21step/s, loss=0.046644, elapsed=5.1min]

Entraînement:  16%|█▌        | 1584/10000 [05:03<26:44,  5.24step/s, loss=0.046644, elapsed=5.1min]

Entraînement:  16%|█▌        | 1584/10000 [05:03<26:44,  5.24step/s, loss=0.100893, elapsed=5.1min]

Entraînement:  16%|█▌        | 1585/10000 [05:03<26:41,  5.25step/s, loss=0.100893, elapsed=5.1min]

Entraînement:  16%|█▌        | 1585/10000 [05:03<26:41,  5.25step/s, loss=0.080919, elapsed=5.1min]

Entraînement:  16%|█▌        | 1586/10000 [05:03<26:38,  5.27step/s, loss=0.080919, elapsed=5.1min]

Entraînement:  16%|█▌        | 1586/10000 [05:03<26:38,  5.27step/s, loss=0.091019, elapsed=5.1min]

Entraînement:  16%|█▌        | 1587/10000 [05:03<26:35,  5.27step/s, loss=0.091019, elapsed=5.1min]

Entraînement:  16%|█▌        | 1587/10000 [05:03<26:35,  5.27step/s, loss=0.060809, elapsed=5.1min]

Entraînement:  16%|█▌        | 1588/10000 [05:04<26:33,  5.28step/s, loss=0.060809, elapsed=5.1min]

Entraînement:  16%|█▌        | 1588/10000 [05:04<26:33,  5.28step/s, loss=0.039401, elapsed=5.1min]

Entraînement:  16%|█▌        | 1589/10000 [05:04<26:29,  5.29step/s, loss=0.039401, elapsed=5.1min]

Entraînement:  16%|█▌        | 1589/10000 [05:04<26:29,  5.29step/s, loss=0.046177, elapsed=5.1min]

Entraînement:  16%|█▌        | 1590/10000 [05:04<26:31,  5.28step/s, loss=0.046177, elapsed=5.1min]

Entraînement:  16%|█▌        | 1590/10000 [05:04<26:31,  5.28step/s, loss=0.089541, elapsed=5.1min]

Entraînement:  16%|█▌        | 1591/10000 [05:04<26:32,  5.28step/s, loss=0.089541, elapsed=5.1min]

Entraînement:  16%|█▌        | 1591/10000 [05:04<26:32,  5.28step/s, loss=0.035951, elapsed=5.1min]

Entraînement:  16%|█▌        | 1592/10000 [05:04<26:32,  5.28step/s, loss=0.035951, elapsed=5.1min]

Entraînement:  16%|█▌        | 1592/10000 [05:04<26:32,  5.28step/s, loss=0.058761, elapsed=5.1min]

Entraînement:  16%|█▌        | 1593/10000 [05:04<26:31,  5.28step/s, loss=0.058761, elapsed=5.1min]

Entraînement:  16%|█▌        | 1593/10000 [05:04<26:31,  5.28step/s, loss=0.044920, elapsed=5.1min]

Entraînement:  16%|█▌        | 1594/10000 [05:05<26:30,  5.29step/s, loss=0.044920, elapsed=5.1min]

Entraînement:  16%|█▌        | 1594/10000 [05:05<26:30,  5.29step/s, loss=0.040769, elapsed=5.1min]

Entraînement:  16%|█▌        | 1595/10000 [05:05<26:30,  5.28step/s, loss=0.040769, elapsed=5.1min]

Entraînement:  16%|█▌        | 1595/10000 [05:05<26:30,  5.28step/s, loss=0.146720, elapsed=5.1min]

Entraînement:  16%|█▌        | 1596/10000 [05:05<26:29,  5.29step/s, loss=0.146720, elapsed=5.1min]

Entraînement:  16%|█▌        | 1596/10000 [05:05<26:29,  5.29step/s, loss=0.157651, elapsed=5.1min]

Entraînement:  16%|█▌        | 1597/10000 [05:05<26:27,  5.29step/s, loss=0.157651, elapsed=5.1min]

Entraînement:  16%|█▌        | 1597/10000 [05:05<26:27,  5.29step/s, loss=0.037773, elapsed=5.1min]

Entraînement:  16%|█▌        | 1598/10000 [05:05<26:32,  5.27step/s, loss=0.037773, elapsed=5.1min]

Entraînement:  16%|█▌        | 1598/10000 [05:05<26:32,  5.27step/s, loss=0.074337, elapsed=5.1min]

Entraînement:  16%|█▌        | 1599/10000 [05:06<26:36,  5.26step/s, loss=0.074337, elapsed=5.1min]

Entraînement:  16%|█▌        | 1599/10000 [05:06<26:36,  5.26step/s, loss=0.053518, elapsed=5.1min]

Entraînement:  16%|█▌        | 1600/10000 [05:06<26:32,  5.27step/s, loss=0.053518, elapsed=5.1min]

Entraînement:  16%|█▌        | 1600/10000 [05:06<26:32,  5.27step/s, loss=0.055592, elapsed=5.1min]

Entraînement:  16%|█▌        | 1600/10000 [05:06<26:32,  5.27step/s, loss=0.055592, elapsed=5.1min]

Entraînement:  16%|█▌        | 1601/10000 [05:06<26:51,  5.21step/s, loss=0.055592, elapsed=5.1min]

Entraînement:  16%|█▌        | 1601/10000 [05:06<26:51,  5.21step/s, loss=0.031745, elapsed=5.1min]

Step 1600/10000 | Train loss: 0.055592 | Elapsed: 5.1min | ETA: 26.8min

Entraînement:  16%|█▌        | 1602/10000 [05:06<26:45,  5.23step/s, loss=0.031745, elapsed=5.1min]

Entraînement:  16%|█▌        | 1602/10000 [05:06<26:45,  5.23step/s, loss=0.068057, elapsed=5.1min]

Entraînement:  16%|█▌        | 1603/10000 [05:06<26:39,  5.25step/s, loss=0.068057, elapsed=5.1min]

Entraînement:  16%|█▌        | 1603/10000 [05:06<26:39,  5.25step/s, loss=0.133641, elapsed=5.1min]

Entraînement:  16%|█▌        | 1604/10000 [05:07<26:35,  5.26step/s, loss=0.133641, elapsed=5.1min]

Entraînement:  16%|█▌        | 1604/10000 [05:07<26:35,  5.26step/s, loss=0.040611, elapsed=5.1min]

Entraînement:  16%|█▌        | 1605/10000 [05:07<26:32,  5.27step/s, loss=0.040611, elapsed=5.1min]

Entraînement:  16%|█▌        | 1605/10000 [05:07<26:32,  5.27step/s, loss=0.066218, elapsed=5.1min]

Entraînement:  16%|█▌        | 1606/10000 [05:07<26:31,  5.27step/s, loss=0.066218, elapsed=5.1min]

Entraînement:  16%|█▌        | 1606/10000 [05:07<26:31,  5.27step/s, loss=0.058587, elapsed=5.1min]

Entraînement:  16%|█▌        | 1607/10000 [05:07<26:35,  5.26step/s, loss=0.058587, elapsed=5.1min]

Entraînement:  16%|█▌        | 1607/10000 [05:07<26:35,  5.26step/s, loss=0.122819, elapsed=5.1min]

Entraînement:  16%|█▌        | 1608/10000 [05:07<26:35,  5.26step/s, loss=0.122819, elapsed=5.1min]

Entraînement:  16%|█▌        | 1608/10000 [05:07<26:35,  5.26step/s, loss=0.087610, elapsed=5.1min]

Entraînement:  16%|█▌        | 1609/10000 [05:08<26:33,  5.26step/s, loss=0.087610, elapsed=5.1min]

Entraînement:  16%|█▌        | 1609/10000 [05:08<26:33,  5.26step/s, loss=0.034596, elapsed=5.1min]

Entraînement:  16%|█▌        | 1610/10000 [05:08<26:33,  5.26step/s, loss=0.034596, elapsed=5.1min]

Entraînement:  16%|█▌        | 1610/10000 [05:08<26:33,  5.26step/s, loss=0.209684, elapsed=5.1min]

Entraînement:  16%|█▌        | 1611/10000 [05:08<26:35,  5.26step/s, loss=0.209684, elapsed=5.1min]

Entraînement:  16%|█▌        | 1611/10000 [05:08<26:35,  5.26step/s, loss=0.037698, elapsed=5.1min]

Entraînement:  16%|█▌        | 1612/10000 [05:08<26:33,  5.26step/s, loss=0.037698, elapsed=5.1min]

Entraînement:  16%|█▌        | 1612/10000 [05:08<26:33,  5.26step/s, loss=0.055465, elapsed=5.1min]

Entraînement:  16%|█▌        | 1613/10000 [05:08<26:34,  5.26step/s, loss=0.055465, elapsed=5.1min]

Entraînement:  16%|█▌        | 1613/10000 [05:08<26:34,  5.26step/s, loss=0.075319, elapsed=5.1min]

Entraînement:  16%|█▌        | 1614/10000 [05:08<26:35,  5.26step/s, loss=0.075319, elapsed=5.1min]

Entraînement:  16%|█▌        | 1614/10000 [05:08<26:35,  5.26step/s, loss=0.025506, elapsed=5.1min]

Entraînement:  16%|█▌        | 1615/10000 [05:09<26:35,  5.25step/s, loss=0.025506, elapsed=5.1min]

Entraînement:  16%|█▌        | 1615/10000 [05:09<26:35,  5.25step/s, loss=0.045146, elapsed=5.2min]

Entraînement:  16%|█▌        | 1616/10000 [05:09<26:33,  5.26step/s, loss=0.045146, elapsed=5.2min]

Entraînement:  16%|█▌        | 1616/10000 [05:09<26:33,  5.26step/s, loss=0.062086, elapsed=5.2min]

Entraînement:  16%|█▌        | 1617/10000 [05:09<26:33,  5.26step/s, loss=0.062086, elapsed=5.2min]

Entraînement:  16%|█▌        | 1617/10000 [05:09<26:33,  5.26step/s, loss=0.104125, elapsed=5.2min]

Entraînement:  16%|█▌        | 1618/10000 [05:09<26:31,  5.27step/s, loss=0.104125, elapsed=5.2min]

Entraînement:  16%|█▌        | 1618/10000 [05:09<26:31,  5.27step/s, loss=0.054339, elapsed=5.2min]

Entraînement:  16%|█▌        | 1619/10000 [05:09<26:30,  5.27step/s, loss=0.054339, elapsed=5.2min]

Entraînement:  16%|█▌        | 1619/10000 [05:09<26:30,  5.27step/s, loss=0.063192, elapsed=5.2min]

Entraînement:  16%|█▌        | 1620/10000 [05:10<26:31,  5.27step/s, loss=0.063192, elapsed=5.2min]

Entraînement:  16%|█▌        | 1620/10000 [05:10<26:31,  5.27step/s, loss=0.065822, elapsed=5.2min]

Entraînement:  16%|█▌        | 1621/10000 [05:10<26:29,  5.27step/s, loss=0.065822, elapsed=5.2min]

Entraînement:  16%|█▌        | 1621/10000 [05:10<26:29,  5.27step/s, loss=0.071871, elapsed=5.2min]

Entraînement:  16%|█▌        | 1622/10000 [05:10<26:26,  5.28step/s, loss=0.071871, elapsed=5.2min]

Entraînement:  16%|█▌        | 1622/10000 [05:10<26:26,  5.28step/s, loss=0.065023, elapsed=5.2min]

Entraînement:  16%|█▌        | 1623/10000 [05:11<40:19,  3.46step/s, loss=0.065023, elapsed=5.2min]

Entraînement:  16%|█▌        | 1623/10000 [05:11<40:19,  3.46step/s, loss=0.061654, elapsed=5.2min]

Entraînement:  16%|█▌        | 1624/10000 [05:11<36:21,  3.84step/s, loss=0.061654, elapsed=5.2min]

Entraînement:  16%|█▌        | 1624/10000 [05:11<36:21,  3.84step/s, loss=0.102240, elapsed=5.2min]

Entraînement:  16%|█▋        | 1625/10000 [05:11<33:24,  4.18step/s, loss=0.102240, elapsed=5.2min]

Entraînement:  16%|█▋        | 1625/10000 [05:11<33:24,  4.18step/s, loss=0.045162, elapsed=5.2min]

Entraînement:  16%|█▋        | 1626/10000 [05:11<31:30,  4.43step/s, loss=0.045162, elapsed=5.2min]

Entraînement:  16%|█▋        | 1626/10000 [05:11<31:30,  4.43step/s, loss=0.071267, elapsed=5.2min]

Entraînement:  16%|█▋        | 1627/10000 [05:11<29:52,  4.67step/s, loss=0.071267, elapsed=5.2min]

Entraînement:  16%|█▋        | 1627/10000 [05:11<29:52,  4.67step/s, loss=0.037683, elapsed=5.2min]

Entraînement:  16%|█▋        | 1628/10000 [05:11<28:52,  4.83step/s, loss=0.037683, elapsed=5.2min]

Entraînement:  16%|█▋        | 1628/10000 [05:11<28:52,  4.83step/s, loss=0.131493, elapsed=5.2min]

Entraînement:  16%|█▋        | 1629/10000 [05:12<28:08,  4.96step/s, loss=0.131493, elapsed=5.2min]

Entraînement:  16%|█▋        | 1629/10000 [05:12<28:08,  4.96step/s, loss=0.062161, elapsed=5.2min]

Entraînement:  16%|█▋        | 1630/10000 [05:12<27:39,  5.04step/s, loss=0.062161, elapsed=5.2min]

Entraînement:  16%|█▋        | 1630/10000 [05:12<27:39,  5.04step/s, loss=0.104028, elapsed=5.2min]

Entraînement:  16%|█▋        | 1631/10000 [05:12<27:23,  5.09step/s, loss=0.104028, elapsed=5.2min]

Entraînement:  16%|█▋        | 1631/10000 [05:12<27:23,  5.09step/s, loss=0.048554, elapsed=5.2min]

Entraînement:  16%|█▋        | 1632/10000 [05:12<27:08,  5.14step/s, loss=0.048554, elapsed=5.2min]

Entraînement:  16%|█▋        | 1632/10000 [05:12<27:08,  5.14step/s, loss=0.049955, elapsed=5.2min]

Entraînement:  16%|█▋        | 1633/10000 [05:12<26:58,  5.17step/s, loss=0.049955, elapsed=5.2min]

Entraînement:  16%|█▋        | 1633/10000 [05:12<26:58,  5.17step/s, loss=0.082513, elapsed=5.2min]

Entraînement:  16%|█▋        | 1634/10000 [05:13<26:52,  5.19step/s, loss=0.082513, elapsed=5.2min]

Entraînement:  16%|█▋        | 1634/10000 [05:13<26:52,  5.19step/s, loss=0.045494, elapsed=5.2min]

Entraînement:  16%|█▋        | 1635/10000 [05:13<26:48,  5.20step/s, loss=0.045494, elapsed=5.2min]

Entraînement:  16%|█▋        | 1635/10000 [05:13<26:48,  5.20step/s, loss=0.141962, elapsed=5.2min]

Entraînement:  16%|█▋        | 1636/10000 [05:13<26:41,  5.22step/s, loss=0.141962, elapsed=5.2min]

Entraînement:  16%|█▋        | 1636/10000 [05:13<26:41,  5.22step/s, loss=0.073945, elapsed=5.2min]

Entraînement:  16%|█▋        | 1637/10000 [05:13<26:37,  5.23step/s, loss=0.073945, elapsed=5.2min]

Entraînement:  16%|█▋        | 1637/10000 [05:13<26:37,  5.23step/s, loss=0.076143, elapsed=5.2min]

Entraînement:  16%|█▋        | 1638/10000 [05:13<26:33,  5.25step/s, loss=0.076143, elapsed=5.2min]

Entraînement:  16%|█▋        | 1638/10000 [05:13<26:33,  5.25step/s, loss=0.044848, elapsed=5.2min]

Entraînement:  16%|█▋        | 1639/10000 [05:14<26:33,  5.25step/s, loss=0.044848, elapsed=5.2min]

Entraînement:  16%|█▋        | 1639/10000 [05:14<26:33,  5.25step/s, loss=0.052060, elapsed=5.2min]

Entraînement:  16%|█▋        | 1640/10000 [05:14<26:33,  5.25step/s, loss=0.052060, elapsed=5.2min]

Entraînement:  16%|█▋        | 1640/10000 [05:14<26:33,  5.25step/s, loss=0.037346, elapsed=5.2min]

Entraînement:  16%|█▋        | 1641/10000 [05:14<26:30,  5.26step/s, loss=0.037346, elapsed=5.2min]

Entraînement:  16%|█▋        | 1641/10000 [05:14<26:30,  5.26step/s, loss=0.081686, elapsed=5.2min]

Entraînement:  16%|█▋        | 1642/10000 [05:14<26:29,  5.26step/s, loss=0.081686, elapsed=5.2min]

Entraînement:  16%|█▋        | 1642/10000 [05:14<26:29,  5.26step/s, loss=0.038554, elapsed=5.2min]

Entraînement:  16%|█▋        | 1643/10000 [05:14<26:24,  5.27step/s, loss=0.038554, elapsed=5.2min]

Entraînement:  16%|█▋        | 1643/10000 [05:14<26:24,  5.27step/s, loss=0.049116, elapsed=5.2min]

Entraînement:  16%|█▋        | 1644/10000 [05:15<26:24,  5.27step/s, loss=0.049116, elapsed=5.2min]

Entraînement:  16%|█▋        | 1644/10000 [05:15<26:24,  5.27step/s, loss=0.134019, elapsed=5.3min]

Entraînement:  16%|█▋        | 1645/10000 [05:15<26:22,  5.28step/s, loss=0.134019, elapsed=5.3min]

Entraînement:  16%|█▋        | 1645/10000 [05:15<26:22,  5.28step/s, loss=0.024217, elapsed=5.3min]

Entraînement:  16%|█▋        | 1646/10000 [05:15<26:23,  5.28step/s, loss=0.024217, elapsed=5.3min]

Entraînement:  16%|█▋        | 1646/10000 [05:15<26:23,  5.28step/s, loss=0.070802, elapsed=5.3min]

Entraînement:  16%|█▋        | 1647/10000 [05:15<26:24,  5.27step/s, loss=0.070802, elapsed=5.3min]

Entraînement:  16%|█▋        | 1647/10000 [05:15<26:24,  5.27step/s, loss=0.125408, elapsed=5.3min]

Entraînement:  16%|█▋        | 1648/10000 [05:15<26:24,  5.27step/s, loss=0.125408, elapsed=5.3min]

Entraînement:  16%|█▋        | 1648/10000 [05:15<26:24,  5.27step/s, loss=0.074353, elapsed=5.3min]

Entraînement:  16%|█▋        | 1649/10000 [05:15<26:24,  5.27step/s, loss=0.074353, elapsed=5.3min]

Entraînement:  16%|█▋        | 1649/10000 [05:15<26:24,  5.27step/s, loss=0.042008, elapsed=5.3min]

Entraînement:  16%|█▋        | 1650/10000 [05:16<26:25,  5.27step/s, loss=0.042008, elapsed=5.3min]

Entraînement:  16%|█▋        | 1650/10000 [05:16<26:25,  5.27step/s, loss=0.058486, elapsed=5.3min]

Entraînement:  17%|█▋        | 1651/10000 [05:16<26:23,  5.27step/s, loss=0.058486, elapsed=5.3min]

Entraînement:  17%|█▋        | 1651/10000 [05:16<26:23,  5.27step/s, loss=0.105994, elapsed=5.3min]

Entraînement:  17%|█▋        | 1652/10000 [05:16<26:23,  5.27step/s, loss=0.105994, elapsed=5.3min]

Entraînement:  17%|█▋        | 1652/10000 [05:16<26:23,  5.27step/s, loss=0.049353, elapsed=5.3min]

Entraînement:  17%|█▋        | 1653/10000 [05:16<26:23,  5.27step/s, loss=0.049353, elapsed=5.3min]

Entraînement:  17%|█▋        | 1653/10000 [05:16<26:23,  5.27step/s, loss=0.055887, elapsed=5.3min]

Entraînement:  17%|█▋        | 1654/10000 [05:16<26:22,  5.27step/s, loss=0.055887, elapsed=5.3min]

Entraînement:  17%|█▋        | 1654/10000 [05:16<26:22,  5.27step/s, loss=0.041976, elapsed=5.3min]

Entraînement:  17%|█▋        | 1655/10000 [05:17<26:19,  5.28step/s, loss=0.041976, elapsed=5.3min]

Entraînement:  17%|█▋        | 1655/10000 [05:17<26:19,  5.28step/s, loss=0.056306, elapsed=5.3min]

Entraînement:  17%|█▋        | 1656/10000 [05:17<26:23,  5.27step/s, loss=0.056306, elapsed=5.3min]

Entraînement:  17%|█▋        | 1656/10000 [05:17<26:23,  5.27step/s, loss=0.051965, elapsed=5.3min]

Entraînement:  17%|█▋        | 1657/10000 [05:17<26:22,  5.27step/s, loss=0.051965, elapsed=5.3min]

Entraînement:  17%|█▋        | 1657/10000 [05:17<26:22,  5.27step/s, loss=0.028238, elapsed=5.3min]

Entraînement:  17%|█▋        | 1658/10000 [05:17<26:23,  5.27step/s, loss=0.028238, elapsed=5.3min]

Entraînement:  17%|█▋        | 1658/10000 [05:17<26:23,  5.27step/s, loss=0.057729, elapsed=5.3min]

Entraînement:  17%|█▋        | 1659/10000 [05:17<26:23,  5.27step/s, loss=0.057729, elapsed=5.3min]

Entraînement:  17%|█▋        | 1659/10000 [05:17<26:23,  5.27step/s, loss=0.063964, elapsed=5.3min]

Entraînement:  17%|█▋        | 1660/10000 [05:18<26:24,  5.26step/s, loss=0.063964, elapsed=5.3min]

Entraînement:  17%|█▋        | 1660/10000 [05:18<26:24,  5.26step/s, loss=0.047604, elapsed=5.3min]

Entraînement:  17%|█▋        | 1661/10000 [05:18<26:23,  5.27step/s, loss=0.047604, elapsed=5.3min]

Entraînement:  17%|█▋        | 1661/10000 [05:18<26:23,  5.27step/s, loss=0.049681, elapsed=5.3min]

Entraînement:  17%|█▋        | 1662/10000 [05:18<26:23,  5.27step/s, loss=0.049681, elapsed=5.3min]

Entraînement:  17%|█▋        | 1662/10000 [05:18<26:23,  5.27step/s, loss=0.078776, elapsed=5.3min]

Entraînement:  17%|█▋        | 1663/10000 [05:18<26:26,  5.25step/s, loss=0.078776, elapsed=5.3min]

Entraînement:  17%|█▋        | 1663/10000 [05:18<26:26,  5.25step/s, loss=0.117115, elapsed=5.3min]

Entraînement:  17%|█▋        | 1664/10000 [05:18<26:25,  5.26step/s, loss=0.117115, elapsed=5.3min]

Entraînement:  17%|█▋        | 1664/10000 [05:18<26:25,  5.26step/s, loss=0.046447, elapsed=5.3min]

Entraînement:  17%|█▋        | 1665/10000 [05:19<26:26,  5.25step/s, loss=0.046447, elapsed=5.3min]

Entraînement:  17%|█▋        | 1665/10000 [05:19<26:26,  5.25step/s, loss=0.055734, elapsed=5.3min]

Entraînement:  17%|█▋        | 1666/10000 [05:19<26:25,  5.26step/s, loss=0.055734, elapsed=5.3min]

Entraînement:  17%|█▋        | 1666/10000 [05:19<26:25,  5.26step/s, loss=0.044432, elapsed=5.3min]

Entraînement:  17%|█▋        | 1667/10000 [05:19<26:24,  5.26step/s, loss=0.044432, elapsed=5.3min]

Entraînement:  17%|█▋        | 1667/10000 [05:19<26:24,  5.26step/s, loss=0.109024, elapsed=5.3min]

Entraînement:  17%|█▋        | 1668/10000 [05:19<26:21,  5.27step/s, loss=0.109024, elapsed=5.3min]

Entraînement:  17%|█▋        | 1668/10000 [05:19<26:21,  5.27step/s, loss=0.034746, elapsed=5.3min]

Entraînement:  17%|█▋        | 1669/10000 [05:19<26:21,  5.27step/s, loss=0.034746, elapsed=5.3min]

Entraînement:  17%|█▋        | 1669/10000 [05:19<26:21,  5.27step/s, loss=0.057693, elapsed=5.3min]

Entraînement:  17%|█▋        | 1670/10000 [05:19<26:24,  5.26step/s, loss=0.057693, elapsed=5.3min]

Entraînement:  17%|█▋        | 1670/10000 [05:19<26:24,  5.26step/s, loss=0.038919, elapsed=5.3min]

Entraînement:  17%|█▋        | 1671/10000 [05:20<26:24,  5.26step/s, loss=0.038919, elapsed=5.3min]

Entraînement:  17%|█▋        | 1671/10000 [05:20<26:24,  5.26step/s, loss=0.056434, elapsed=5.3min]

Entraînement:  17%|█▋        | 1672/10000 [05:20<26:23,  5.26step/s, loss=0.056434, elapsed=5.3min]

Entraînement:  17%|█▋        | 1672/10000 [05:20<26:23,  5.26step/s, loss=0.037264, elapsed=5.3min]

Entraînement:  17%|█▋        | 1673/10000 [05:20<26:23,  5.26step/s, loss=0.037264, elapsed=5.3min]

Entraînement:  17%|█▋        | 1673/10000 [05:20<26:23,  5.26step/s, loss=0.024453, elapsed=5.3min]

Entraînement:  17%|█▋        | 1674/10000 [05:20<26:20,  5.27step/s, loss=0.024453, elapsed=5.3min]

Entraînement:  17%|█▋        | 1674/10000 [05:20<26:20,  5.27step/s, loss=0.066695, elapsed=5.3min]

Entraînement:  17%|█▋        | 1675/10000 [05:20<26:17,  5.28step/s, loss=0.066695, elapsed=5.3min]

Entraînement:  17%|█▋        | 1675/10000 [05:20<26:17,  5.28step/s, loss=0.043733, elapsed=5.3min]

Entraînement:  17%|█▋        | 1676/10000 [05:21<26:17,  5.28step/s, loss=0.043733, elapsed=5.3min]

Entraînement:  17%|█▋        | 1676/10000 [05:21<26:17,  5.28step/s, loss=0.036641, elapsed=5.4min]

Entraînement:  17%|█▋        | 1677/10000 [05:21<26:16,  5.28step/s, loss=0.036641, elapsed=5.4min]

Entraînement:  17%|█▋        | 1677/10000 [05:21<26:16,  5.28step/s, loss=0.036393, elapsed=5.4min]

Entraînement:  17%|█▋        | 1678/10000 [05:21<26:16,  5.28step/s, loss=0.036393, elapsed=5.4min]

Entraînement:  17%|█▋        | 1678/10000 [05:21<26:16,  5.28step/s, loss=0.051538, elapsed=5.4min]

Entraînement:  17%|█▋        | 1679/10000 [05:21<26:19,  5.27step/s, loss=0.051538, elapsed=5.4min]

Entraînement:  17%|█▋        | 1679/10000 [05:21<26:19,  5.27step/s, loss=0.097585, elapsed=5.4min]

Entraînement:  17%|█▋        | 1680/10000 [05:21<26:19,  5.27step/s, loss=0.097585, elapsed=5.4min]

Entraînement:  17%|█▋        | 1680/10000 [05:21<26:19,  5.27step/s, loss=0.140197, elapsed=5.4min]

Entraînement:  17%|█▋        | 1681/10000 [05:22<26:19,  5.27step/s, loss=0.140197, elapsed=5.4min]

Entraînement:  17%|█▋        | 1681/10000 [05:22<26:19,  5.27step/s, loss=0.049738, elapsed=5.4min]

Entraînement:  17%|█▋        | 1682/10000 [05:22<26:21,  5.26step/s, loss=0.049738, elapsed=5.4min]

Entraînement:  17%|█▋        | 1682/10000 [05:22<26:21,  5.26step/s, loss=0.045996, elapsed=5.4min]

Entraînement:  17%|█▋        | 1683/10000 [05:22<26:20,  5.26step/s, loss=0.045996, elapsed=5.4min]

Entraînement:  17%|█▋        | 1683/10000 [05:22<26:20,  5.26step/s, loss=0.046148, elapsed=5.4min]

Entraînement:  17%|█▋        | 1684/10000 [05:22<26:21,  5.26step/s, loss=0.046148, elapsed=5.4min]

Entraînement:  17%|█▋        | 1684/10000 [05:22<26:21,  5.26step/s, loss=0.084422, elapsed=5.4min]

Entraînement:  17%|█▋        | 1685/10000 [05:22<26:17,  5.27step/s, loss=0.084422, elapsed=5.4min]

Entraînement:  17%|█▋        | 1685/10000 [05:22<26:17,  5.27step/s, loss=0.040872, elapsed=5.4min]

Entraînement:  17%|█▋        | 1686/10000 [05:22<26:19,  5.26step/s, loss=0.040872, elapsed=5.4min]

Entraînement:  17%|█▋        | 1686/10000 [05:23<26:19,  5.26step/s, loss=0.048949, elapsed=5.4min]

Entraînement:  17%|█▋        | 1687/10000 [05:23<26:14,  5.28step/s, loss=0.048949, elapsed=5.4min]

Entraînement:  17%|█▋        | 1687/10000 [05:23<26:14,  5.28step/s, loss=0.089347, elapsed=5.4min]

Entraînement:  17%|█▋        | 1688/10000 [05:23<26:19,  5.26step/s, loss=0.089347, elapsed=5.4min]

Entraînement:  17%|█▋        | 1688/10000 [05:23<26:19,  5.26step/s, loss=0.070703, elapsed=5.4min]

Entraînement:  17%|█▋        | 1689/10000 [05:23<26:19,  5.26step/s, loss=0.070703, elapsed=5.4min]

Entraînement:  17%|█▋        | 1689/10000 [05:23<26:19,  5.26step/s, loss=0.118181, elapsed=5.4min]

Entraînement:  17%|█▋        | 1690/10000 [05:23<26:17,  5.27step/s, loss=0.118181, elapsed=5.4min]

Entraînement:  17%|█▋        | 1690/10000 [05:23<26:17,  5.27step/s, loss=0.048769, elapsed=5.4min]

Entraînement:  17%|█▋        | 1691/10000 [05:23<26:17,  5.27step/s, loss=0.048769, elapsed=5.4min]

Entraînement:  17%|█▋        | 1691/10000 [05:23<26:17,  5.27step/s, loss=0.135248, elapsed=5.4min]

Entraînement:  17%|█▋        | 1692/10000 [05:24<26:15,  5.27step/s, loss=0.135248, elapsed=5.4min]

Entraînement:  17%|█▋        | 1692/10000 [05:24<26:15,  5.27step/s, loss=0.129572, elapsed=5.4min]

Entraînement:  17%|█▋        | 1693/10000 [05:24<26:16,  5.27step/s, loss=0.129572, elapsed=5.4min]

Entraînement:  17%|█▋        | 1693/10000 [05:24<26:16,  5.27step/s, loss=0.097760, elapsed=5.4min]

Entraînement:  17%|█▋        | 1694/10000 [05:24<26:16,  5.27step/s, loss=0.097760, elapsed=5.4min]

Entraînement:  17%|█▋        | 1694/10000 [05:24<26:16,  5.27step/s, loss=0.053309, elapsed=5.4min]

Entraînement:  17%|█▋        | 1695/10000 [05:24<26:16,  5.27step/s, loss=0.053309, elapsed=5.4min]

Entraînement:  17%|█▋        | 1695/10000 [05:24<26:16,  5.27step/s, loss=0.083436, elapsed=5.4min]

Entraînement:  17%|█▋        | 1696/10000 [05:24<26:16,  5.27step/s, loss=0.083436, elapsed=5.4min]

Entraînement:  17%|█▋        | 1696/10000 [05:24<26:16,  5.27step/s, loss=0.043725, elapsed=5.4min]

Entraînement:  17%|█▋        | 1697/10000 [05:25<26:19,  5.26step/s, loss=0.043725, elapsed=5.4min]

Entraînement:  17%|█▋        | 1697/10000 [05:25<26:19,  5.26step/s, loss=0.059880, elapsed=5.4min]

Entraînement:  17%|█▋        | 1698/10000 [05:25<26:16,  5.27step/s, loss=0.059880, elapsed=5.4min]

Entraînement:  17%|█▋        | 1698/10000 [05:25<26:16,  5.27step/s, loss=0.080380, elapsed=5.4min]

Entraînement:  17%|█▋        | 1699/10000 [05:25<26:15,  5.27step/s, loss=0.080380, elapsed=5.4min]

Entraînement:  17%|█▋        | 1699/10000 [05:25<26:15,  5.27step/s, loss=0.034069, elapsed=5.4min]

Entraînement:  17%|█▋        | 1700/10000 [05:25<26:18,  5.26step/s, loss=0.034069, elapsed=5.4min]

Entraînement:  17%|█▋        | 1700/10000 [05:25<26:18,  5.26step/s, loss=0.109924, elapsed=5.4min]

Entraînement:  17%|█▋        | 1700/10000 [05:25<26:18,  5.26step/s, loss=0.109924, elapsed=5.4min]

Entraînement:  17%|█▋        | 1701/10000 [05:25<26:37,  5.20step/s, loss=0.109924, elapsed=5.4min]

Entraînement:  17%|█▋        | 1701/10000 [05:25<26:37,  5.20step/s, loss=0.047603, elapsed=5.4min]

Step 1700/10000 | Train loss: 0.109924 | Elapsed: 5.4min | ETA: 26.5min

Entraînement:  17%|█▋        | 1702/10000 [05:26<26:30,  5.22step/s, loss=0.047603, elapsed=5.4min]

Entraînement:  17%|█▋        | 1702/10000 [05:26<26:30,  5.22step/s, loss=0.090117, elapsed=5.4min]

Entraînement:  17%|█▋        | 1703/10000 [05:26<26:26,  5.23step/s, loss=0.090117, elapsed=5.4min]

Entraînement:  17%|█▋        | 1703/10000 [05:26<26:26,  5.23step/s, loss=0.081776, elapsed=5.4min]

Entraînement:  17%|█▋        | 1704/10000 [05:26<26:22,  5.24step/s, loss=0.081776, elapsed=5.4min]

Entraînement:  17%|█▋        | 1704/10000 [05:26<26:22,  5.24step/s, loss=0.172999, elapsed=5.4min]

Entraînement:  17%|█▋        | 1705/10000 [05:26<26:20,  5.25step/s, loss=0.172999, elapsed=5.4min]

Entraînement:  17%|█▋        | 1705/10000 [05:26<26:20,  5.25step/s, loss=0.047625, elapsed=5.4min]

Entraînement:  17%|█▋        | 1706/10000 [05:26<26:17,  5.26step/s, loss=0.047625, elapsed=5.4min]

Entraînement:  17%|█▋        | 1706/10000 [05:26<26:17,  5.26step/s, loss=0.041102, elapsed=5.4min]

Entraînement:  17%|█▋        | 1707/10000 [05:26<26:15,  5.26step/s, loss=0.041102, elapsed=5.4min]

Entraînement:  17%|█▋        | 1707/10000 [05:26<26:15,  5.26step/s, loss=0.047562, elapsed=5.5min]

Entraînement:  17%|█▋        | 1708/10000 [05:27<26:16,  5.26step/s, loss=0.047562, elapsed=5.5min]

Entraînement:  17%|█▋        | 1708/10000 [05:27<26:16,  5.26step/s, loss=0.058774, elapsed=5.5min]

Entraînement:  17%|█▋        | 1709/10000 [05:27<26:15,  5.26step/s, loss=0.058774, elapsed=5.5min]

Entraînement:  17%|█▋        | 1709/10000 [05:27<26:15,  5.26step/s, loss=0.054899, elapsed=5.5min]

Entraînement:  17%|█▋        | 1710/10000 [05:27<26:15,  5.26step/s, loss=0.054899, elapsed=5.5min]

Entraînement:  17%|█▋        | 1710/10000 [05:27<26:15,  5.26step/s, loss=0.076764, elapsed=5.5min]

Entraînement:  17%|█▋        | 1711/10000 [05:27<26:13,  5.27step/s, loss=0.076764, elapsed=5.5min]

Entraînement:  17%|█▋        | 1711/10000 [05:27<26:13,  5.27step/s, loss=0.036243, elapsed=5.5min]

Entraînement:  17%|█▋        | 1712/10000 [05:27<26:13,  5.27step/s, loss=0.036243, elapsed=5.5min]

Entraînement:  17%|█▋        | 1712/10000 [05:27<26:13,  5.27step/s, loss=0.103702, elapsed=5.5min]

Entraînement:  17%|█▋        | 1713/10000 [05:28<26:11,  5.27step/s, loss=0.103702, elapsed=5.5min]

Entraînement:  17%|█▋        | 1713/10000 [05:28<26:11,  5.27step/s, loss=0.029032, elapsed=5.5min]

Entraînement:  17%|█▋        | 1714/10000 [05:28<26:14,  5.26step/s, loss=0.029032, elapsed=5.5min]

Entraînement:  17%|█▋        | 1714/10000 [05:28<26:14,  5.26step/s, loss=0.101444, elapsed=5.5min]

Entraînement:  17%|█▋        | 1715/10000 [05:28<26:18,  5.25step/s, loss=0.101444, elapsed=5.5min]

Entraînement:  17%|█▋        | 1715/10000 [05:28<26:18,  5.25step/s, loss=0.032466, elapsed=5.5min]

Entraînement:  17%|█▋        | 1716/10000 [05:28<26:23,  5.23step/s, loss=0.032466, elapsed=5.5min]

Entraînement:  17%|█▋        | 1716/10000 [05:28<26:23,  5.23step/s, loss=0.040658, elapsed=5.5min]

Entraînement:  17%|█▋        | 1717/10000 [05:28<26:19,  5.24step/s, loss=0.040658, elapsed=5.5min]

Entraînement:  17%|█▋        | 1717/10000 [05:28<26:19,  5.24step/s, loss=0.072756, elapsed=5.5min]

Entraînement:  17%|█▋        | 1718/10000 [05:29<26:18,  5.25step/s, loss=0.072756, elapsed=5.5min]

Entraînement:  17%|█▋        | 1718/10000 [05:29<26:18,  5.25step/s, loss=0.038118, elapsed=5.5min]

Entraînement:  17%|█▋        | 1719/10000 [05:29<26:15,  5.26step/s, loss=0.038118, elapsed=5.5min]

Entraînement:  17%|█▋        | 1719/10000 [05:29<26:15,  5.26step/s, loss=0.031493, elapsed=5.5min]

Entraînement:  17%|█▋        | 1720/10000 [05:29<26:11,  5.27step/s, loss=0.031493, elapsed=5.5min]

Entraînement:  17%|█▋        | 1720/10000 [05:29<26:11,  5.27step/s, loss=0.115799, elapsed=5.5min]

Entraînement:  17%|█▋        | 1721/10000 [05:29<26:10,  5.27step/s, loss=0.115799, elapsed=5.5min]

Entraînement:  17%|█▋        | 1721/10000 [05:29<26:10,  5.27step/s, loss=0.067641, elapsed=5.5min]

Entraînement:  17%|█▋        | 1722/10000 [05:29<26:07,  5.28step/s, loss=0.067641, elapsed=5.5min]

Entraînement:  17%|█▋        | 1722/10000 [05:29<26:07,  5.28step/s, loss=0.126566, elapsed=5.5min]

Entraînement:  17%|█▋        | 1723/10000 [05:30<26:09,  5.27step/s, loss=0.126566, elapsed=5.5min]

Entraînement:  17%|█▋        | 1723/10000 [05:30<26:09,  5.27step/s, loss=0.043692, elapsed=5.5min]

Entraînement:  17%|█▋        | 1724/10000 [05:30<26:12,  5.26step/s, loss=0.043692, elapsed=5.5min]

Entraînement:  17%|█▋        | 1724/10000 [05:30<26:12,  5.26step/s, loss=0.073049, elapsed=5.5min]

Entraînement:  17%|█▋        | 1725/10000 [05:30<26:08,  5.28step/s, loss=0.073049, elapsed=5.5min]

Entraînement:  17%|█▋        | 1725/10000 [05:30<26:08,  5.28step/s, loss=0.098749, elapsed=5.5min]

Entraînement:  17%|█▋        | 1726/10000 [05:30<26:11,  5.27step/s, loss=0.098749, elapsed=5.5min]

Entraînement:  17%|█▋        | 1726/10000 [05:30<26:11,  5.27step/s, loss=0.123825, elapsed=5.5min]

Entraînement:  17%|█▋        | 1727/10000 [05:30<26:12,  5.26step/s, loss=0.123825, elapsed=5.5min]

Entraînement:  17%|█▋        | 1727/10000 [05:30<26:12,  5.26step/s, loss=0.043836, elapsed=5.5min]

Entraînement:  17%|█▋        | 1728/10000 [05:30<26:00,  5.30step/s, loss=0.043836, elapsed=5.5min]

Entraînement:  17%|█▋        | 1728/10000 [05:30<26:00,  5.30step/s, loss=0.052748, elapsed=5.5min]

Entraînement:  17%|█▋        | 1729/10000 [05:31<25:55,  5.32step/s, loss=0.052748, elapsed=5.5min]

Entraînement:  17%|█▋        | 1729/10000 [05:31<25:55,  5.32step/s, loss=0.051364, elapsed=5.5min]

Entraînement:  17%|█▋        | 1730/10000 [05:31<25:52,  5.33step/s, loss=0.051364, elapsed=5.5min]

Entraînement:  17%|█▋        | 1730/10000 [05:31<25:52,  5.33step/s, loss=0.065319, elapsed=5.5min]

Entraînement:  17%|█▋        | 1731/10000 [05:31<25:48,  5.34step/s, loss=0.065319, elapsed=5.5min]

Entraînement:  17%|█▋        | 1731/10000 [05:31<25:48,  5.34step/s, loss=0.050763, elapsed=5.5min]

Entraînement:  17%|█▋        | 1732/10000 [05:31<25:48,  5.34step/s, loss=0.050763, elapsed=5.5min]

Entraînement:  17%|█▋        | 1732/10000 [05:31<25:48,  5.34step/s, loss=0.056652, elapsed=5.5min]

Entraînement:  17%|█▋        | 1733/10000 [05:31<25:52,  5.33step/s, loss=0.056652, elapsed=5.5min]

Entraînement:  17%|█▋        | 1733/10000 [05:31<25:52,  5.33step/s, loss=0.033719, elapsed=5.5min]

Entraînement:  17%|█▋        | 1734/10000 [05:32<25:50,  5.33step/s, loss=0.033719, elapsed=5.5min]

Entraînement:  17%|█▋        | 1734/10000 [05:32<25:50,  5.33step/s, loss=0.037249, elapsed=5.5min]

Entraînement:  17%|█▋        | 1735/10000 [05:32<25:48,  5.34step/s, loss=0.037249, elapsed=5.5min]

Entraînement:  17%|█▋        | 1735/10000 [05:32<25:48,  5.34step/s, loss=0.072338, elapsed=5.5min]

Entraînement:  17%|█▋        | 1736/10000 [05:32<25:48,  5.34step/s, loss=0.072338, elapsed=5.5min]

Entraînement:  17%|█▋        | 1736/10000 [05:32<25:48,  5.34step/s, loss=0.091183, elapsed=5.5min]

Entraînement:  17%|█▋        | 1737/10000 [05:32<25:52,  5.32step/s, loss=0.091183, elapsed=5.5min]

Entraînement:  17%|█▋        | 1737/10000 [05:32<25:52,  5.32step/s, loss=0.048975, elapsed=5.5min]

Entraînement:  17%|█▋        | 1738/10000 [05:32<25:58,  5.30step/s, loss=0.048975, elapsed=5.5min]

Entraînement:  17%|█▋        | 1738/10000 [05:32<25:58,  5.30step/s, loss=0.044183, elapsed=5.5min]

Entraînement:  17%|█▋        | 1739/10000 [05:33<25:59,  5.30step/s, loss=0.044183, elapsed=5.5min]

Entraînement:  17%|█▋        | 1739/10000 [05:33<25:59,  5.30step/s, loss=0.055167, elapsed=5.6min]

Entraînement:  17%|█▋        | 1740/10000 [05:33<26:05,  5.28step/s, loss=0.055167, elapsed=5.6min]

Entraînement:  17%|█▋        | 1740/10000 [05:33<26:05,  5.28step/s, loss=0.076634, elapsed=5.6min]

Entraînement:  17%|█▋        | 1741/10000 [05:33<26:07,  5.27step/s, loss=0.076634, elapsed=5.6min]

Entraînement:  17%|█▋        | 1741/10000 [05:33<26:07,  5.27step/s, loss=0.123242, elapsed=5.6min]

Entraînement:  17%|█▋        | 1742/10000 [05:33<26:09,  5.26step/s, loss=0.123242, elapsed=5.6min]

Entraînement:  17%|█▋        | 1742/10000 [05:33<26:09,  5.26step/s, loss=0.061935, elapsed=5.6min]

Entraînement:  17%|█▋        | 1743/10000 [05:33<26:08,  5.27step/s, loss=0.061935, elapsed=5.6min]

Entraînement:  17%|█▋        | 1743/10000 [05:33<26:08,  5.27step/s, loss=0.039363, elapsed=5.6min]

Entraînement:  17%|█▋        | 1744/10000 [05:33<26:09,  5.26step/s, loss=0.039363, elapsed=5.6min]

Entraînement:  17%|█▋        | 1744/10000 [05:34<26:09,  5.26step/s, loss=0.048321, elapsed=5.6min]

Entraînement:  17%|█▋        | 1745/10000 [05:34<26:08,  5.26step/s, loss=0.048321, elapsed=5.6min]

Entraînement:  17%|█▋        | 1745/10000 [05:34<26:08,  5.26step/s, loss=0.071109, elapsed=5.6min]

Entraînement:  17%|█▋        | 1746/10000 [05:34<26:06,  5.27step/s, loss=0.071109, elapsed=5.6min]

Entraînement:  17%|█▋        | 1746/10000 [05:34<26:06,  5.27step/s, loss=0.032197, elapsed=5.6min]

Entraînement:  17%|█▋        | 1747/10000 [05:34<26:09,  5.26step/s, loss=0.032197, elapsed=5.6min]

Entraînement:  17%|█▋        | 1747/10000 [05:34<26:09,  5.26step/s, loss=0.068682, elapsed=5.6min]

Entraînement:  17%|█▋        | 1748/10000 [05:34<26:09,  5.26step/s, loss=0.068682, elapsed=5.6min]

Entraînement:  17%|█▋        | 1748/10000 [05:34<26:09,  5.26step/s, loss=0.059682, elapsed=5.6min]

Entraînement:  17%|█▋        | 1749/10000 [05:34<26:12,  5.25step/s, loss=0.059682, elapsed=5.6min]

Entraînement:  17%|█▋        | 1749/10000 [05:34<26:12,  5.25step/s, loss=0.058320, elapsed=5.6min]

Entraînement:  18%|█▊        | 1750/10000 [05:35<26:11,  5.25step/s, loss=0.058320, elapsed=5.6min]

Entraînement:  18%|█▊        | 1750/10000 [05:35<26:11,  5.25step/s, loss=0.046357, elapsed=5.6min]

Entraînement:  18%|█▊        | 1751/10000 [05:35<26:13,  5.24step/s, loss=0.046357, elapsed=5.6min]

Entraînement:  18%|█▊        | 1751/10000 [05:35<26:13,  5.24step/s, loss=0.115053, elapsed=5.6min]

Entraînement:  18%|█▊        | 1752/10000 [05:35<26:10,  5.25step/s, loss=0.115053, elapsed=5.6min]

Entraînement:  18%|█▊        | 1752/10000 [05:35<26:10,  5.25step/s, loss=0.056270, elapsed=5.6min]

Entraînement:  18%|█▊        | 1753/10000 [05:35<26:06,  5.26step/s, loss=0.056270, elapsed=5.6min]

Entraînement:  18%|█▊        | 1753/10000 [05:35<26:06,  5.26step/s, loss=0.045227, elapsed=5.6min]

Entraînement:  18%|█▊        | 1754/10000 [05:35<26:04,  5.27step/s, loss=0.045227, elapsed=5.6min]

Entraînement:  18%|█▊        | 1754/10000 [05:35<26:04,  5.27step/s, loss=0.038265, elapsed=5.6min]

Entraînement:  18%|█▊        | 1755/10000 [05:36<26:01,  5.28step/s, loss=0.038265, elapsed=5.6min]

Entraînement:  18%|█▊        | 1755/10000 [05:36<26:01,  5.28step/s, loss=0.076333, elapsed=5.6min]

Entraînement:  18%|█▊        | 1756/10000 [05:36<26:03,  5.27step/s, loss=0.076333, elapsed=5.6min]

Entraînement:  18%|█▊        | 1756/10000 [05:36<26:03,  5.27step/s, loss=0.112998, elapsed=5.6min]

Entraînement:  18%|█▊        | 1757/10000 [05:36<26:02,  5.28step/s, loss=0.112998, elapsed=5.6min]

Entraînement:  18%|█▊        | 1757/10000 [05:36<26:02,  5.28step/s, loss=0.124809, elapsed=5.6min]

Entraînement:  18%|█▊        | 1758/10000 [05:36<26:02,  5.28step/s, loss=0.124809, elapsed=5.6min]

Entraînement:  18%|█▊        | 1758/10000 [05:36<26:02,  5.28step/s, loss=0.064830, elapsed=5.6min]

Entraînement:  18%|█▊        | 1759/10000 [05:36<26:00,  5.28step/s, loss=0.064830, elapsed=5.6min]

Entraînement:  18%|█▊        | 1759/10000 [05:36<26:00,  5.28step/s, loss=0.053478, elapsed=5.6min]

Entraînement:  18%|█▊        | 1760/10000 [05:37<26:00,  5.28step/s, loss=0.053478, elapsed=5.6min]

Entraînement:  18%|█▊        | 1760/10000 [05:37<26:00,  5.28step/s, loss=0.062531, elapsed=5.6min]

Entraînement:  18%|█▊        | 1761/10000 [05:37<26:01,  5.28step/s, loss=0.062531, elapsed=5.6min]

Entraînement:  18%|█▊        | 1761/10000 [05:37<26:01,  5.28step/s, loss=0.058524, elapsed=5.6min]

Entraînement:  18%|█▊        | 1762/10000 [05:37<25:59,  5.28step/s, loss=0.058524, elapsed=5.6min]

Entraînement:  18%|█▊        | 1762/10000 [05:37<25:59,  5.28step/s, loss=0.036379, elapsed=5.6min]

Entraînement:  18%|█▊        | 1763/10000 [05:37<26:00,  5.28step/s, loss=0.036379, elapsed=5.6min]

Entraînement:  18%|█▊        | 1763/10000 [05:37<26:00,  5.28step/s, loss=0.047163, elapsed=5.6min]

Entraînement:  18%|█▊        | 1764/10000 [05:37<25:57,  5.29step/s, loss=0.047163, elapsed=5.6min]

Entraînement:  18%|█▊        | 1764/10000 [05:37<25:57,  5.29step/s, loss=0.038494, elapsed=5.6min]

Entraînement:  18%|█▊        | 1765/10000 [05:37<26:07,  5.25step/s, loss=0.038494, elapsed=5.6min]

Entraînement:  18%|█▊        | 1765/10000 [05:37<26:07,  5.25step/s, loss=0.063746, elapsed=5.6min]

Entraînement:  18%|█▊        | 1766/10000 [05:38<26:07,  5.25step/s, loss=0.063746, elapsed=5.6min]

Entraînement:  18%|█▊        | 1766/10000 [05:38<26:07,  5.25step/s, loss=0.135088, elapsed=5.6min]

Entraînement:  18%|█▊        | 1767/10000 [05:38<26:05,  5.26step/s, loss=0.135088, elapsed=5.6min]

Entraînement:  18%|█▊        | 1767/10000 [05:38<26:05,  5.26step/s, loss=0.057982, elapsed=5.6min]

Entraînement:  18%|█▊        | 1768/10000 [05:38<26:01,  5.27step/s, loss=0.057982, elapsed=5.6min]

Entraînement:  18%|█▊        | 1768/10000 [05:38<26:01,  5.27step/s, loss=0.062307, elapsed=5.6min]

Entraînement:  18%|█▊        | 1769/10000 [05:38<26:08,  5.25step/s, loss=0.062307, elapsed=5.6min]

Entraînement:  18%|█▊        | 1769/10000 [05:38<26:08,  5.25step/s, loss=0.061839, elapsed=5.6min]

Entraînement:  18%|█▊        | 1770/10000 [05:38<26:10,  5.24step/s, loss=0.061839, elapsed=5.6min]

Entraînement:  18%|█▊        | 1770/10000 [05:38<26:10,  5.24step/s, loss=0.026039, elapsed=5.6min]

Entraînement:  18%|█▊        | 1771/10000 [05:39<26:16,  5.22step/s, loss=0.026039, elapsed=5.6min]

Entraînement:  18%|█▊        | 1771/10000 [05:39<26:16,  5.22step/s, loss=0.071887, elapsed=5.7min]

Entraînement:  18%|█▊        | 1772/10000 [05:39<26:14,  5.23step/s, loss=0.071887, elapsed=5.7min]

Entraînement:  18%|█▊        | 1772/10000 [05:39<26:14,  5.23step/s, loss=0.097267, elapsed=5.7min]

Entraînement:  18%|█▊        | 1773/10000 [05:39<26:13,  5.23step/s, loss=0.097267, elapsed=5.7min]

Entraînement:  18%|█▊        | 1773/10000 [05:39<26:13,  5.23step/s, loss=0.085304, elapsed=5.7min]

Entraînement:  18%|█▊        | 1774/10000 [05:39<26:10,  5.24step/s, loss=0.085304, elapsed=5.7min]

Entraînement:  18%|█▊        | 1774/10000 [05:39<26:10,  5.24step/s, loss=0.029698, elapsed=5.7min]

Entraînement:  18%|█▊        | 1775/10000 [05:39<26:10,  5.24step/s, loss=0.029698, elapsed=5.7min]

Entraînement:  18%|█▊        | 1775/10000 [05:39<26:10,  5.24step/s, loss=0.117064, elapsed=5.7min]

Entraînement:  18%|█▊        | 1776/10000 [05:40<26:07,  5.25step/s, loss=0.117064, elapsed=5.7min]

Entraînement:  18%|█▊        | 1776/10000 [05:40<26:07,  5.25step/s, loss=0.055453, elapsed=5.7min]

Entraînement:  18%|█▊        | 1777/10000 [05:40<26:08,  5.24step/s, loss=0.055453, elapsed=5.7min]

Entraînement:  18%|█▊        | 1777/10000 [05:40<26:08,  5.24step/s, loss=0.095456, elapsed=5.7min]

Entraînement:  18%|█▊        | 1778/10000 [05:40<26:08,  5.24step/s, loss=0.095456, elapsed=5.7min]

Entraînement:  18%|█▊        | 1778/10000 [05:40<26:08,  5.24step/s, loss=0.050898, elapsed=5.7min]

Entraînement:  18%|█▊        | 1779/10000 [05:40<26:10,  5.23step/s, loss=0.050898, elapsed=5.7min]

Entraînement:  18%|█▊        | 1779/10000 [05:40<26:10,  5.23step/s, loss=0.043570, elapsed=5.7min]

Entraînement:  18%|█▊        | 1780/10000 [05:40<26:07,  5.24step/s, loss=0.043570, elapsed=5.7min]

Entraînement:  18%|█▊        | 1780/10000 [05:40<26:07,  5.24step/s, loss=0.046422, elapsed=5.7min]

Entraînement:  18%|█▊        | 1781/10000 [05:41<26:04,  5.25step/s, loss=0.046422, elapsed=5.7min]

Entraînement:  18%|█▊        | 1781/10000 [05:41<26:04,  5.25step/s, loss=0.166002, elapsed=5.7min]

Entraînement:  18%|█▊        | 1782/10000 [05:41<26:02,  5.26step/s, loss=0.166002, elapsed=5.7min]

Entraînement:  18%|█▊        | 1782/10000 [05:41<26:02,  5.26step/s, loss=0.032166, elapsed=5.7min]

Entraînement:  18%|█▊        | 1783/10000 [05:41<25:58,  5.27step/s, loss=0.032166, elapsed=5.7min]

Entraînement:  18%|█▊        | 1783/10000 [05:41<25:58,  5.27step/s, loss=0.069804, elapsed=5.7min]

Entraînement:  18%|█▊        | 1784/10000 [05:41<25:59,  5.27step/s, loss=0.069804, elapsed=5.7min]

Entraînement:  18%|█▊        | 1784/10000 [05:41<25:59,  5.27step/s, loss=0.065046, elapsed=5.7min]

Entraînement:  18%|█▊        | 1785/10000 [05:41<26:00,  5.27step/s, loss=0.065046, elapsed=5.7min]

Entraînement:  18%|█▊        | 1785/10000 [05:41<26:00,  5.27step/s, loss=0.076805, elapsed=5.7min]

Entraînement:  18%|█▊        | 1786/10000 [05:41<26:01,  5.26step/s, loss=0.076805, elapsed=5.7min]

Entraînement:  18%|█▊        | 1786/10000 [05:41<26:01,  5.26step/s, loss=0.030534, elapsed=5.7min]

Entraînement:  18%|█▊        | 1787/10000 [05:42<26:00,  5.26step/s, loss=0.030534, elapsed=5.7min]

Entraînement:  18%|█▊        | 1787/10000 [05:42<26:00,  5.26step/s, loss=0.031350, elapsed=5.7min]

Entraînement:  18%|█▊        | 1788/10000 [05:42<25:56,  5.27step/s, loss=0.031350, elapsed=5.7min]

Entraînement:  18%|█▊        | 1788/10000 [05:42<25:56,  5.27step/s, loss=0.025640, elapsed=5.7min]

Entraînement:  18%|█▊        | 1789/10000 [05:42<25:56,  5.27step/s, loss=0.025640, elapsed=5.7min]

Entraînement:  18%|█▊        | 1789/10000 [05:42<25:56,  5.27step/s, loss=0.046814, elapsed=5.7min]

Entraînement:  18%|█▊        | 1790/10000 [05:42<25:57,  5.27step/s, loss=0.046814, elapsed=5.7min]

Entraînement:  18%|█▊        | 1790/10000 [05:42<25:57,  5.27step/s, loss=0.126001, elapsed=5.7min]

Entraînement:  18%|█▊        | 1791/10000 [05:42<25:56,  5.28step/s, loss=0.126001, elapsed=5.7min]

Entraînement:  18%|█▊        | 1791/10000 [05:42<25:56,  5.28step/s, loss=0.032728, elapsed=5.7min]

Entraînement:  18%|█▊        | 1792/10000 [05:43<25:55,  5.28step/s, loss=0.032728, elapsed=5.7min]

Entraînement:  18%|█▊        | 1792/10000 [05:43<25:55,  5.28step/s, loss=0.031496, elapsed=5.7min]

Entraînement:  18%|█▊        | 1793/10000 [05:43<25:57,  5.27step/s, loss=0.031496, elapsed=5.7min]

Entraînement:  18%|█▊        | 1793/10000 [05:43<25:57,  5.27step/s, loss=0.053112, elapsed=5.7min]

Entraînement:  18%|█▊        | 1794/10000 [05:43<26:02,  5.25step/s, loss=0.053112, elapsed=5.7min]

Entraînement:  18%|█▊        | 1794/10000 [05:43<26:02,  5.25step/s, loss=0.062950, elapsed=5.7min]

Entraînement:  18%|█▊        | 1795/10000 [05:43<26:02,  5.25step/s, loss=0.062950, elapsed=5.7min]

Entraînement:  18%|█▊        | 1795/10000 [05:43<26:02,  5.25step/s, loss=0.086910, elapsed=5.7min]

Entraînement:  18%|█▊        | 1796/10000 [05:43<25:50,  5.29step/s, loss=0.086910, elapsed=5.7min]

Entraînement:  18%|█▊        | 1796/10000 [05:43<25:50,  5.29step/s, loss=0.130134, elapsed=5.7min]

Entraînement:  18%|█▊        | 1797/10000 [05:44<25:50,  5.29step/s, loss=0.130134, elapsed=5.7min]

Entraînement:  18%|█▊        | 1797/10000 [05:44<25:50,  5.29step/s, loss=0.059449, elapsed=5.7min]

Entraînement:  18%|█▊        | 1798/10000 [05:44<25:49,  5.29step/s, loss=0.059449, elapsed=5.7min]

Entraînement:  18%|█▊        | 1798/10000 [05:44<25:49,  5.29step/s, loss=0.110985, elapsed=5.7min]

Entraînement:  18%|█▊        | 1799/10000 [05:44<25:51,  5.29step/s, loss=0.110985, elapsed=5.7min]

Entraînement:  18%|█▊        | 1799/10000 [05:44<25:51,  5.29step/s, loss=0.067025, elapsed=5.7min]

Entraînement:  18%|█▊        | 1800/10000 [05:44<25:52,  5.28step/s, loss=0.067025, elapsed=5.7min]

Entraînement:  18%|█▊        | 1800/10000 [05:44<25:52,  5.28step/s, loss=0.042384, elapsed=5.7min]

Entraînement:  18%|█▊        | 1800/10000 [05:44<25:52,  5.28step/s, loss=0.042384, elapsed=5.7min]

Entraînement:  18%|█▊        | 1801/10000 [05:44<26:12,  5.21step/s, loss=0.042384, elapsed=5.7min]

Entraînement:  18%|█▊        | 1801/10000 [05:44<26:12,  5.21step/s, loss=0.034903, elapsed=5.7min]

Step 1800/10000 | Train loss: 0.042384 | Elapsed: 5.7min | ETA: 26.2min

Entraînement:  18%|█▊        | 1802/10000 [05:45<26:13,  5.21step/s, loss=0.034903, elapsed=5.7min]

Entraînement:  18%|█▊        | 1802/10000 [05:45<26:13,  5.21step/s, loss=0.033692, elapsed=5.8min]

Entraînement:  18%|█▊        | 1803/10000 [05:45<26:13,  5.21step/s, loss=0.033692, elapsed=5.8min]

Entraînement:  18%|█▊        | 1803/10000 [05:45<26:13,  5.21step/s, loss=0.075572, elapsed=5.8min]

Entraînement:  18%|█▊        | 1804/10000 [05:45<26:15,  5.20step/s, loss=0.075572, elapsed=5.8min]

Entraînement:  18%|█▊        | 1804/10000 [05:45<26:15,  5.20step/s, loss=0.137704, elapsed=5.8min]

Entraînement:  18%|█▊        | 1805/10000 [05:45<26:13,  5.21step/s, loss=0.137704, elapsed=5.8min]

Entraînement:  18%|█▊        | 1805/10000 [05:45<26:13,  5.21step/s, loss=0.064821, elapsed=5.8min]

Entraînement:  18%|█▊        | 1806/10000 [05:45<26:08,  5.22step/s, loss=0.064821, elapsed=5.8min]

Entraînement:  18%|█▊        | 1806/10000 [05:45<26:08,  5.22step/s, loss=0.079190, elapsed=5.8min]

Entraînement:  18%|█▊        | 1807/10000 [05:45<26:09,  5.22step/s, loss=0.079190, elapsed=5.8min]

Entraînement:  18%|█▊        | 1807/10000 [05:45<26:09,  5.22step/s, loss=0.102358, elapsed=5.8min]

Entraînement:  18%|█▊        | 1808/10000 [05:46<26:10,  5.22step/s, loss=0.102358, elapsed=5.8min]

Entraînement:  18%|█▊        | 1808/10000 [05:46<26:10,  5.22step/s, loss=0.081864, elapsed=5.8min]

Entraînement:  18%|█▊        | 1809/10000 [05:46<26:12,  5.21step/s, loss=0.081864, elapsed=5.8min]

Entraînement:  18%|█▊        | 1809/10000 [05:46<26:12,  5.21step/s, loss=0.107392, elapsed=5.8min]

Entraînement:  18%|█▊        | 1810/10000 [05:46<26:12,  5.21step/s, loss=0.107392, elapsed=5.8min]

Entraînement:  18%|█▊        | 1810/10000 [05:46<26:12,  5.21step/s, loss=0.154613, elapsed=5.8min]

Entraînement:  18%|█▊        | 1811/10000 [05:46<26:11,  5.21step/s, loss=0.154613, elapsed=5.8min]

Entraînement:  18%|█▊        | 1811/10000 [05:46<26:11,  5.21step/s, loss=0.052012, elapsed=5.8min]

Entraînement:  18%|█▊        | 1812/10000 [05:46<26:10,  5.21step/s, loss=0.052012, elapsed=5.8min]

Entraînement:  18%|█▊        | 1812/10000 [05:46<26:10,  5.21step/s, loss=0.129736, elapsed=5.8min]

Entraînement:  18%|█▊        | 1813/10000 [05:47<26:08,  5.22step/s, loss=0.129736, elapsed=5.8min]

Entraînement:  18%|█▊        | 1813/10000 [05:47<26:08,  5.22step/s, loss=0.042267, elapsed=5.8min]

Entraînement:  18%|█▊        | 1814/10000 [05:47<26:10,  5.21step/s, loss=0.042267, elapsed=5.8min]

Entraînement:  18%|█▊        | 1814/10000 [05:47<26:10,  5.21step/s, loss=0.067721, elapsed=5.8min]

Entraînement:  18%|█▊        | 1815/10000 [05:47<26:10,  5.21step/s, loss=0.067721, elapsed=5.8min]

Entraînement:  18%|█▊        | 1815/10000 [05:47<26:10,  5.21step/s, loss=0.025367, elapsed=5.8min]

Entraînement:  18%|█▊        | 1816/10000 [05:47<26:12,  5.20step/s, loss=0.025367, elapsed=5.8min]

Entraînement:  18%|█▊        | 1816/10000 [05:47<26:12,  5.20step/s, loss=0.078003, elapsed=5.8min]

Entraînement:  18%|█▊        | 1817/10000 [05:47<26:09,  5.21step/s, loss=0.078003, elapsed=5.8min]

Entraînement:  18%|█▊        | 1817/10000 [05:47<26:09,  5.21step/s, loss=0.030740, elapsed=5.8min]

Entraînement:  18%|█▊        | 1818/10000 [05:48<26:10,  5.21step/s, loss=0.030740, elapsed=5.8min]

Entraînement:  18%|█▊        | 1818/10000 [05:48<26:10,  5.21step/s, loss=0.038027, elapsed=5.8min]

Entraînement:  18%|█▊        | 1819/10000 [05:48<26:08,  5.21step/s, loss=0.038027, elapsed=5.8min]

Entraînement:  18%|█▊        | 1819/10000 [05:48<26:08,  5.21step/s, loss=0.063219, elapsed=5.8min]

Entraînement:  18%|█▊        | 1820/10000 [05:48<26:09,  5.21step/s, loss=0.063219, elapsed=5.8min]

Entraînement:  18%|█▊        | 1820/10000 [05:48<26:09,  5.21step/s, loss=0.052406, elapsed=5.8min]

Entraînement:  18%|█▊        | 1821/10000 [05:48<26:03,  5.23step/s, loss=0.052406, elapsed=5.8min]

Entraînement:  18%|█▊        | 1821/10000 [05:48<26:03,  5.23step/s, loss=0.052794, elapsed=5.8min]

Entraînement:  18%|█▊        | 1822/10000 [05:48<26:02,  5.23step/s, loss=0.052794, elapsed=5.8min]

Entraînement:  18%|█▊        | 1822/10000 [05:48<26:02,  5.23step/s, loss=0.027808, elapsed=5.8min]

Entraînement:  18%|█▊        | 1823/10000 [05:49<26:01,  5.24step/s, loss=0.027808, elapsed=5.8min]

Entraînement:  18%|█▊        | 1823/10000 [05:49<26:01,  5.24step/s, loss=0.038836, elapsed=5.8min]

Entraînement:  18%|█▊        | 1824/10000 [05:49<25:59,  5.24step/s, loss=0.038836, elapsed=5.8min]

Entraînement:  18%|█▊        | 1824/10000 [05:49<25:59,  5.24step/s, loss=0.028195, elapsed=5.8min]

Entraînement:  18%|█▊        | 1825/10000 [05:49<25:56,  5.25step/s, loss=0.028195, elapsed=5.8min]

Entraînement:  18%|█▊        | 1825/10000 [05:49<25:56,  5.25step/s, loss=0.053978, elapsed=5.8min]

Entraînement:  18%|█▊        | 1826/10000 [05:49<25:52,  5.27step/s, loss=0.053978, elapsed=5.8min]

Entraînement:  18%|█▊        | 1826/10000 [05:49<25:52,  5.27step/s, loss=0.051441, elapsed=5.8min]

Entraînement:  18%|█▊        | 1827/10000 [05:49<25:50,  5.27step/s, loss=0.051441, elapsed=5.8min]

Entraînement:  18%|█▊        | 1827/10000 [05:49<25:50,  5.27step/s, loss=0.034667, elapsed=5.8min]

Entraînement:  18%|█▊        | 1828/10000 [05:50<25:48,  5.28step/s, loss=0.034667, elapsed=5.8min]

Entraînement:  18%|█▊        | 1828/10000 [05:50<25:48,  5.28step/s, loss=0.049512, elapsed=5.8min]

Entraînement:  18%|█▊        | 1829/10000 [05:50<25:52,  5.26step/s, loss=0.049512, elapsed=5.8min]

Entraînement:  18%|█▊        | 1829/10000 [05:50<25:52,  5.26step/s, loss=0.040979, elapsed=5.8min]

Entraînement:  18%|█▊        | 1830/10000 [05:50<25:52,  5.26step/s, loss=0.040979, elapsed=5.8min]

Entraînement:  18%|█▊        | 1830/10000 [05:50<25:52,  5.26step/s, loss=0.055350, elapsed=5.8min]

Entraînement:  18%|█▊        | 1831/10000 [05:50<25:54,  5.26step/s, loss=0.055350, elapsed=5.8min]

Entraînement:  18%|█▊        | 1831/10000 [05:50<25:54,  5.26step/s, loss=0.115788, elapsed=5.8min]

Entraînement:  18%|█▊        | 1832/10000 [05:50<25:51,  5.26step/s, loss=0.115788, elapsed=5.8min]

Entraînement:  18%|█▊        | 1832/10000 [05:50<25:51,  5.26step/s, loss=0.071524, elapsed=5.8min]

Entraînement:  18%|█▊        | 1833/10000 [05:50<25:52,  5.26step/s, loss=0.071524, elapsed=5.8min]

Entraînement:  18%|█▊        | 1833/10000 [05:50<25:52,  5.26step/s, loss=0.032912, elapsed=5.8min]

Entraînement:  18%|█▊        | 1834/10000 [05:51<25:50,  5.27step/s, loss=0.032912, elapsed=5.8min]

Entraînement:  18%|█▊        | 1834/10000 [05:51<25:50,  5.27step/s, loss=0.095882, elapsed=5.9min]

Entraînement:  18%|█▊        | 1835/10000 [05:51<25:46,  5.28step/s, loss=0.095882, elapsed=5.9min]

Entraînement:  18%|█▊        | 1835/10000 [05:51<25:46,  5.28step/s, loss=0.035147, elapsed=5.9min]

Entraînement:  18%|█▊        | 1836/10000 [05:51<25:47,  5.28step/s, loss=0.035147, elapsed=5.9min]

Entraînement:  18%|█▊        | 1836/10000 [05:51<25:47,  5.28step/s, loss=0.091145, elapsed=5.9min]

Entraînement:  18%|█▊        | 1837/10000 [05:51<25:48,  5.27step/s, loss=0.091145, elapsed=5.9min]

Entraînement:  18%|█▊        | 1837/10000 [05:51<25:48,  5.27step/s, loss=0.094550, elapsed=5.9min]

Entraînement:  18%|█▊        | 1838/10000 [05:51<25:48,  5.27step/s, loss=0.094550, elapsed=5.9min]

Entraînement:  18%|█▊        | 1838/10000 [05:51<25:48,  5.27step/s, loss=0.071579, elapsed=5.9min]

Entraînement:  18%|█▊        | 1839/10000 [05:52<25:48,  5.27step/s, loss=0.071579, elapsed=5.9min]

Entraînement:  18%|█▊        | 1839/10000 [05:52<25:48,  5.27step/s, loss=0.041635, elapsed=5.9min]

Entraînement:  18%|█▊        | 1840/10000 [05:52<25:45,  5.28step/s, loss=0.041635, elapsed=5.9min]

Entraînement:  18%|█▊        | 1840/10000 [05:52<25:45,  5.28step/s, loss=0.127503, elapsed=5.9min]

Entraînement:  18%|█▊        | 1841/10000 [05:52<25:45,  5.28step/s, loss=0.127503, elapsed=5.9min]

Entraînement:  18%|█▊        | 1841/10000 [05:52<25:45,  5.28step/s, loss=0.142165, elapsed=5.9min]

Entraînement:  18%|█▊        | 1842/10000 [05:52<25:46,  5.27step/s, loss=0.142165, elapsed=5.9min]

Entraînement:  18%|█▊        | 1842/10000 [05:52<25:46,  5.27step/s, loss=0.100355, elapsed=5.9min]

Entraînement:  18%|█▊        | 1843/10000 [05:52<25:45,  5.28step/s, loss=0.100355, elapsed=5.9min]

Entraînement:  18%|█▊        | 1843/10000 [05:52<25:45,  5.28step/s, loss=0.037998, elapsed=5.9min]

Entraînement:  18%|█▊        | 1844/10000 [05:53<25:45,  5.28step/s, loss=0.037998, elapsed=5.9min]

Entraînement:  18%|█▊        | 1844/10000 [05:53<25:45,  5.28step/s, loss=0.119654, elapsed=5.9min]

Entraînement:  18%|█▊        | 1845/10000 [05:53<25:44,  5.28step/s, loss=0.119654, elapsed=5.9min]

Entraînement:  18%|█▊        | 1845/10000 [05:53<25:44,  5.28step/s, loss=0.070009, elapsed=5.9min]

Entraînement:  18%|█▊        | 1846/10000 [05:53<25:47,  5.27step/s, loss=0.070009, elapsed=5.9min]

Entraînement:  18%|█▊        | 1846/10000 [05:53<25:47,  5.27step/s, loss=0.118762, elapsed=5.9min]

Entraînement:  18%|█▊        | 1847/10000 [05:53<25:46,  5.27step/s, loss=0.118762, elapsed=5.9min]

Entraînement:  18%|█▊        | 1847/10000 [05:53<25:46,  5.27step/s, loss=0.053340, elapsed=5.9min]

Entraînement:  18%|█▊        | 1848/10000 [05:53<25:47,  5.27step/s, loss=0.053340, elapsed=5.9min]

Entraînement:  18%|█▊        | 1848/10000 [05:53<25:47,  5.27step/s, loss=0.041395, elapsed=5.9min]

Entraînement:  18%|█▊        | 1849/10000 [05:53<25:47,  5.27step/s, loss=0.041395, elapsed=5.9min]

Entraînement:  18%|█▊        | 1849/10000 [05:53<25:47,  5.27step/s, loss=0.041823, elapsed=5.9min]

Entraînement:  18%|█▊        | 1850/10000 [05:54<25:47,  5.27step/s, loss=0.041823, elapsed=5.9min]

Entraînement:  18%|█▊        | 1850/10000 [05:55<25:47,  5.27step/s, loss=0.059526, elapsed=5.9min]

Entraînement:  19%|█▊        | 1851/10000 [05:55<1:04:51,  2.09step/s, loss=0.059526, elapsed=5.9min]

Entraînement:  19%|█▊        | 1851/10000 [05:55<1:04:51,  2.09step/s, loss=0.075306, elapsed=5.9min]

Entraînement:  19%|█▊        | 1852/10000 [05:55<53:05,  2.56step/s, loss=0.075306, elapsed=5.9min]

Entraînement:  19%|█▊        | 1852/10000 [05:55<53:05,  2.56step/s, loss=0.076864, elapsed=5.9min]

Entraînement:  19%|█▊        | 1853/10000 [05:55<44:51,  3.03step/s, loss=0.076864, elapsed=5.9min]

Entraînement:  19%|█▊        | 1853/10000 [05:55<44:51,  3.03step/s, loss=0.082029, elapsed=5.9min]

Entraînement:  19%|█▊        | 1854/10000 [05:55<39:02,  3.48step/s, loss=0.082029, elapsed=5.9min]

Entraînement:  19%|█▊        | 1854/10000 [05:55<39:02,  3.48step/s, loss=0.065421, elapsed=5.9min]

Entraînement:  19%|█▊        | 1855/10000 [05:56<35:02,  3.87step/s, loss=0.065421, elapsed=5.9min]

Entraînement:  19%|█▊        | 1855/10000 [05:56<35:02,  3.87step/s, loss=0.044933, elapsed=5.9min]

Entraînement:  19%|█▊        | 1856/10000 [05:56<32:14,  4.21step/s, loss=0.044933, elapsed=5.9min]

Entraînement:  19%|█▊        | 1856/10000 [05:56<32:14,  4.21step/s, loss=0.037750, elapsed=5.9min]

Entraînement:  19%|█▊        | 1857/10000 [05:56<30:16,  4.48step/s, loss=0.037750, elapsed=5.9min]

Entraînement:  19%|█▊        | 1857/10000 [05:56<30:16,  4.48step/s, loss=0.056887, elapsed=5.9min]

Entraînement:  19%|█▊        | 1858/10000 [05:56<28:52,  4.70step/s, loss=0.056887, elapsed=5.9min]

Entraînement:  19%|█▊        | 1858/10000 [05:56<28:52,  4.70step/s, loss=0.043452, elapsed=5.9min]

Entraînement:  19%|█▊        | 1859/10000 [05:56<27:54,  4.86step/s, loss=0.043452, elapsed=5.9min]

Entraînement:  19%|█▊        | 1859/10000 [05:56<27:54,  4.86step/s, loss=0.037373, elapsed=5.9min]

Entraînement:  19%|█▊        | 1860/10000 [05:57<27:13,  4.98step/s, loss=0.037373, elapsed=5.9min]

Entraînement:  19%|█▊        | 1860/10000 [05:57<27:13,  4.98step/s, loss=0.080273, elapsed=6.0min]

Entraînement:  19%|█▊        | 1861/10000 [05:57<26:43,  5.08step/s, loss=0.080273, elapsed=6.0min]

Entraînement:  19%|█▊        | 1861/10000 [05:57<26:43,  5.08step/s, loss=0.031143, elapsed=6.0min]

Entraînement:  19%|█▊        | 1862/10000 [05:57<26:24,  5.14step/s, loss=0.031143, elapsed=6.0min]

Entraînement:  19%|█▊        | 1862/10000 [05:57<26:24,  5.14step/s, loss=0.062063, elapsed=6.0min]

Entraînement:  19%|█▊        | 1863/10000 [05:57<26:09,  5.18step/s, loss=0.062063, elapsed=6.0min]

Entraînement:  19%|█▊        | 1863/10000 [05:57<26:09,  5.18step/s, loss=0.050938, elapsed=6.0min]

Entraînement:  19%|█▊        | 1864/10000 [05:57<26:02,  5.21step/s, loss=0.050938, elapsed=6.0min]

Entraînement:  19%|█▊        | 1864/10000 [05:57<26:02,  5.21step/s, loss=0.033394, elapsed=6.0min]

Entraînement:  19%|█▊        | 1865/10000 [05:57<25:55,  5.23step/s, loss=0.033394, elapsed=6.0min]

Entraînement:  19%|█▊        | 1865/10000 [05:57<25:55,  5.23step/s, loss=0.076711, elapsed=6.0min]

Entraînement:  19%|█▊        | 1866/10000 [05:58<25:50,  5.25step/s, loss=0.076711, elapsed=6.0min]

Entraînement:  19%|█▊        | 1866/10000 [05:58<25:50,  5.25step/s, loss=0.050433, elapsed=6.0min]

Entraînement:  19%|█▊        | 1867/10000 [05:58<25:47,  5.26step/s, loss=0.050433, elapsed=6.0min]

Entraînement:  19%|█▊        | 1867/10000 [05:58<25:47,  5.26step/s, loss=0.048421, elapsed=6.0min]

Entraînement:  19%|█▊        | 1868/10000 [05:58<25:42,  5.27step/s, loss=0.048421, elapsed=6.0min]

Entraînement:  19%|█▊        | 1868/10000 [05:58<25:42,  5.27step/s, loss=0.033639, elapsed=6.0min]

Entraînement:  19%|█▊        | 1869/10000 [05:58<25:41,  5.27step/s, loss=0.033639, elapsed=6.0min]

Entraînement:  19%|█▊        | 1869/10000 [05:58<25:41,  5.27step/s, loss=0.047088, elapsed=6.0min]

Entraînement:  19%|█▊        | 1870/10000 [05:58<25:40,  5.28step/s, loss=0.047088, elapsed=6.0min]

Entraînement:  19%|█▊        | 1870/10000 [05:58<25:40,  5.28step/s, loss=0.051058, elapsed=6.0min]

Entraînement:  19%|█▊        | 1871/10000 [05:59<25:43,  5.27step/s, loss=0.051058, elapsed=6.0min]

Entraînement:  19%|█▊        | 1871/10000 [05:59<25:43,  5.27step/s, loss=0.032646, elapsed=6.0min]

Entraînement:  19%|█▊        | 1872/10000 [05:59<25:40,  5.27step/s, loss=0.032646, elapsed=6.0min]

Entraînement:  19%|█▊        | 1872/10000 [05:59<25:40,  5.27step/s, loss=0.098855, elapsed=6.0min]

Entraînement:  19%|█▊        | 1873/10000 [05:59<25:38,  5.28step/s, loss=0.098855, elapsed=6.0min]

Entraînement:  19%|█▊        | 1873/10000 [05:59<25:38,  5.28step/s, loss=0.031096, elapsed=6.0min]

Entraînement:  19%|█▊        | 1874/10000 [05:59<25:43,  5.26step/s, loss=0.031096, elapsed=6.0min]

Entraînement:  19%|█▊        | 1874/10000 [05:59<25:43,  5.26step/s, loss=0.106812, elapsed=6.0min]

Entraînement:  19%|█▉        | 1875/10000 [05:59<25:41,  5.27step/s, loss=0.106812, elapsed=6.0min]

Entraînement:  19%|█▉        | 1875/10000 [05:59<25:41,  5.27step/s, loss=0.103013, elapsed=6.0min]

Entraînement:  19%|█▉        | 1876/10000 [06:00<25:39,  5.28step/s, loss=0.103013, elapsed=6.0min]

Entraînement:  19%|█▉        | 1876/10000 [06:00<25:39,  5.28step/s, loss=0.041035, elapsed=6.0min]

Entraînement:  19%|█▉        | 1877/10000 [06:00<25:37,  5.28step/s, loss=0.041035, elapsed=6.0min]

Entraînement:  19%|█▉        | 1877/10000 [06:00<25:37,  5.28step/s, loss=0.073851, elapsed=6.0min]

Entraînement:  19%|█▉        | 1878/10000 [06:00<25:35,  5.29step/s, loss=0.073851, elapsed=6.0min]

Entraînement:  19%|█▉        | 1878/10000 [06:00<25:35,  5.29step/s, loss=0.048361, elapsed=6.0min]

Entraînement:  19%|█▉        | 1879/10000 [06:00<25:39,  5.27step/s, loss=0.048361, elapsed=6.0min]

Entraînement:  19%|█▉        | 1879/10000 [06:00<25:39,  5.27step/s, loss=0.115226, elapsed=6.0min]

Entraînement:  19%|█▉        | 1880/10000 [06:00<25:38,  5.28step/s, loss=0.115226, elapsed=6.0min]

Entraînement:  19%|█▉        | 1880/10000 [06:00<25:38,  5.28step/s, loss=0.038233, elapsed=6.0min]

Entraînement:  19%|█▉        | 1881/10000 [06:01<25:33,  5.29step/s, loss=0.038233, elapsed=6.0min]

Entraînement:  19%|█▉        | 1881/10000 [06:01<25:33,  5.29step/s, loss=0.095424, elapsed=6.0min]

Entraînement:  19%|█▉        | 1882/10000 [06:01<25:35,  5.29step/s, loss=0.095424, elapsed=6.0min]

Entraînement:  19%|█▉        | 1882/10000 [06:01<25:35,  5.29step/s, loss=0.058177, elapsed=6.0min]

Entraînement:  19%|█▉        | 1883/10000 [06:01<25:32,  5.30step/s, loss=0.058177, elapsed=6.0min]

Entraînement:  19%|█▉        | 1883/10000 [06:01<25:32,  5.30step/s, loss=0.102587, elapsed=6.0min]

Entraînement:  19%|█▉        | 1884/10000 [06:01<25:31,  5.30step/s, loss=0.102587, elapsed=6.0min]

Entraînement:  19%|█▉        | 1884/10000 [06:01<25:31,  5.30step/s, loss=0.233114, elapsed=6.0min]

Entraînement:  19%|█▉        | 1885/10000 [06:01<25:31,  5.30step/s, loss=0.233114, elapsed=6.0min]

Entraînement:  19%|█▉        | 1885/10000 [06:01<25:31,  5.30step/s, loss=0.066205, elapsed=6.0min]

Entraînement:  19%|█▉        | 1886/10000 [06:01<25:29,  5.30step/s, loss=0.066205, elapsed=6.0min]

Entraînement:  19%|█▉        | 1886/10000 [06:01<25:29,  5.30step/s, loss=0.038842, elapsed=6.0min]

Entraînement:  19%|█▉        | 1887/10000 [06:02<25:32,  5.29step/s, loss=0.038842, elapsed=6.0min]

Entraînement:  19%|█▉        | 1887/10000 [06:02<25:32,  5.29step/s, loss=0.073921, elapsed=6.0min]

Entraînement:  19%|█▉        | 1888/10000 [06:02<25:34,  5.29step/s, loss=0.073921, elapsed=6.0min]

Entraînement:  19%|█▉        | 1888/10000 [06:02<25:34,  5.29step/s, loss=0.033028, elapsed=6.0min]

Entraînement:  19%|█▉        | 1889/10000 [06:02<25:33,  5.29step/s, loss=0.033028, elapsed=6.0min]

Entraînement:  19%|█▉        | 1889/10000 [06:02<25:33,  5.29step/s, loss=0.101887, elapsed=6.0min]

Entraînement:  19%|█▉        | 1890/10000 [06:02<25:33,  5.29step/s, loss=0.101887, elapsed=6.0min]

Entraînement:  19%|█▉        | 1890/10000 [06:02<25:33,  5.29step/s, loss=0.086000, elapsed=6.0min]

Entraînement:  19%|█▉        | 1891/10000 [06:02<25:31,  5.30step/s, loss=0.086000, elapsed=6.0min]

Entraînement:  19%|█▉        | 1891/10000 [06:02<25:31,  5.30step/s, loss=0.055105, elapsed=6.0min]

Entraînement:  19%|█▉        | 1892/10000 [06:03<25:32,  5.29step/s, loss=0.055105, elapsed=6.0min]

Entraînement:  19%|█▉        | 1892/10000 [06:03<25:32,  5.29step/s, loss=0.075860, elapsed=6.1min]

Entraînement:  19%|█▉        | 1893/10000 [06:03<25:32,  5.29step/s, loss=0.075860, elapsed=6.1min]

Entraînement:  19%|█▉        | 1893/10000 [06:03<25:32,  5.29step/s, loss=0.091686, elapsed=6.1min]

Entraînement:  19%|█▉        | 1894/10000 [06:03<25:32,  5.29step/s, loss=0.091686, elapsed=6.1min]

Entraînement:  19%|█▉        | 1894/10000 [06:03<25:32,  5.29step/s, loss=0.069897, elapsed=6.1min]

Entraînement:  19%|█▉        | 1895/10000 [06:03<25:38,  5.27step/s, loss=0.069897, elapsed=6.1min]

Entraînement:  19%|█▉        | 1895/10000 [06:03<25:38,  5.27step/s, loss=0.037562, elapsed=6.1min]

Entraînement:  19%|█▉        | 1896/10000 [06:03<25:37,  5.27step/s, loss=0.037562, elapsed=6.1min]

Entraînement:  19%|█▉        | 1896/10000 [06:03<25:37,  5.27step/s, loss=0.038271, elapsed=6.1min]

Entraînement:  19%|█▉        | 1897/10000 [06:04<25:40,  5.26step/s, loss=0.038271, elapsed=6.1min]

Entraînement:  19%|█▉        | 1897/10000 [06:04<25:40,  5.26step/s, loss=0.069436, elapsed=6.1min]

Entraînement:  19%|█▉        | 1898/10000 [06:04<25:35,  5.28step/s, loss=0.069436, elapsed=6.1min]

Entraînement:  19%|█▉        | 1898/10000 [06:04<25:35,  5.28step/s, loss=0.030032, elapsed=6.1min]

Entraînement:  19%|█▉        | 1899/10000 [06:04<25:37,  5.27step/s, loss=0.030032, elapsed=6.1min]

Entraînement:  19%|█▉        | 1899/10000 [06:04<25:37,  5.27step/s, loss=0.039341, elapsed=6.1min]

Entraînement:  19%|█▉        | 1900/10000 [06:04<25:38,  5.27step/s, loss=0.039341, elapsed=6.1min]

Entraînement:  19%|█▉        | 1900/10000 [06:04<25:38,  5.27step/s, loss=0.038763, elapsed=6.1min]

Entraînement:  19%|█▉        | 1900/10000 [06:04<25:38,  5.27step/s, loss=0.038763, elapsed=6.1min]

Entraînement:  19%|█▉        | 1901/10000 [06:04<25:53,  5.21step/s, loss=0.038763, elapsed=6.1min]

Entraînement:  19%|█▉        | 1901/10000 [06:04<25:53,  5.21step/s, loss=0.049465, elapsed=6.1min]

Step 1900/10000 | Train loss: 0.038763 | Elapsed: 6.1min | ETA: 25.9min

Entraînement:  19%|█▉        | 1902/10000 [06:04<25:49,  5.23step/s, loss=0.049465, elapsed=6.1min]

Entraînement:  19%|█▉        | 1902/10000 [06:04<25:49,  5.23step/s, loss=0.088732, elapsed=6.1min]

Entraînement:  19%|█▉        | 1903/10000 [06:05<25:47,  5.23step/s, loss=0.088732, elapsed=6.1min]

Entraînement:  19%|█▉        | 1903/10000 [06:05<25:47,  5.23step/s, loss=0.073696, elapsed=6.1min]

Entraînement:  19%|█▉        | 1904/10000 [06:05<25:49,  5.22step/s, loss=0.073696, elapsed=6.1min]

Entraînement:  19%|█▉        | 1904/10000 [06:05<25:49,  5.22step/s, loss=0.064399, elapsed=6.1min]

Entraînement:  19%|█▉        | 1905/10000 [06:05<25:47,  5.23step/s, loss=0.064399, elapsed=6.1min]

Entraînement:  19%|█▉        | 1905/10000 [06:05<25:47,  5.23step/s, loss=0.052991, elapsed=6.1min]

Entraînement:  19%|█▉        | 1906/10000 [06:05<25:44,  5.24step/s, loss=0.052991, elapsed=6.1min]

Entraînement:  19%|█▉        | 1906/10000 [06:05<25:44,  5.24step/s, loss=0.057223, elapsed=6.1min]

Entraînement:  19%|█▉        | 1907/10000 [06:05<25:41,  5.25step/s, loss=0.057223, elapsed=6.1min]

Entraînement:  19%|█▉        | 1907/10000 [06:05<25:41,  5.25step/s, loss=0.031509, elapsed=6.1min]

Entraînement:  19%|█▉        | 1908/10000 [06:06<25:40,  5.25step/s, loss=0.031509, elapsed=6.1min]

Entraînement:  19%|█▉        | 1908/10000 [06:06<25:40,  5.25step/s, loss=0.085762, elapsed=6.1min]

Entraînement:  19%|█▉        | 1909/10000 [06:06<25:40,  5.25step/s, loss=0.085762, elapsed=6.1min]

Entraînement:  19%|█▉        | 1909/10000 [06:06<25:40,  5.25step/s, loss=0.047420, elapsed=6.1min]

Entraînement:  19%|█▉        | 1910/10000 [06:06<25:41,  5.25step/s, loss=0.047420, elapsed=6.1min]

Entraînement:  19%|█▉        | 1910/10000 [06:06<25:41,  5.25step/s, loss=0.036927, elapsed=6.1min]

Entraînement:  19%|█▉        | 1911/10000 [06:06<25:41,  5.25step/s, loss=0.036927, elapsed=6.1min]

Entraînement:  19%|█▉        | 1911/10000 [06:06<25:41,  5.25step/s, loss=0.111974, elapsed=6.1min]

Entraînement:  19%|█▉        | 1912/10000 [06:06<25:41,  5.25step/s, loss=0.111974, elapsed=6.1min]

Entraînement:  19%|█▉        | 1912/10000 [06:06<25:41,  5.25step/s, loss=0.043984, elapsed=6.1min]

Entraînement:  19%|█▉        | 1913/10000 [06:07<25:41,  5.25step/s, loss=0.043984, elapsed=6.1min]

Entraînement:  19%|█▉        | 1913/10000 [06:07<25:41,  5.25step/s, loss=0.031186, elapsed=6.1min]

Entraînement:  19%|█▉        | 1914/10000 [06:07<25:40,  5.25step/s, loss=0.031186, elapsed=6.1min]

Entraînement:  19%|█▉        | 1914/10000 [06:07<25:40,  5.25step/s, loss=0.051723, elapsed=6.1min]

Entraînement:  19%|█▉        | 1915/10000 [06:07<25:40,  5.25step/s, loss=0.051723, elapsed=6.1min]

Entraînement:  19%|█▉        | 1915/10000 [06:07<25:40,  5.25step/s, loss=0.051068, elapsed=6.1min]

Entraînement:  19%|█▉        | 1916/10000 [06:07<25:38,  5.26step/s, loss=0.051068, elapsed=6.1min]

Entraînement:  19%|█▉        | 1916/10000 [06:07<25:38,  5.26step/s, loss=0.047292, elapsed=6.1min]

Entraînement:  19%|█▉        | 1917/10000 [06:07<25:39,  5.25step/s, loss=0.047292, elapsed=6.1min]

Entraînement:  19%|█▉        | 1917/10000 [06:07<25:39,  5.25step/s, loss=0.045515, elapsed=6.1min]

Entraînement:  19%|█▉        | 1918/10000 [06:08<25:37,  5.26step/s, loss=0.045515, elapsed=6.1min]

Entraînement:  19%|█▉        | 1918/10000 [06:08<25:37,  5.26step/s, loss=0.040590, elapsed=6.1min]

Entraînement:  19%|█▉        | 1919/10000 [06:08<25:38,  5.25step/s, loss=0.040590, elapsed=6.1min]

Entraînement:  19%|█▉        | 1919/10000 [06:08<25:38,  5.25step/s, loss=0.116441, elapsed=6.1min]

Entraînement:  19%|█▉        | 1920/10000 [06:08<25:35,  5.26step/s, loss=0.116441, elapsed=6.1min]

Entraînement:  19%|█▉        | 1920/10000 [06:08<25:35,  5.26step/s, loss=0.033348, elapsed=6.1min]

Entraînement:  19%|█▉        | 1921/10000 [06:08<25:36,  5.26step/s, loss=0.033348, elapsed=6.1min]

Entraînement:  19%|█▉        | 1921/10000 [06:08<25:36,  5.26step/s, loss=0.096876, elapsed=6.1min]

Entraînement:  19%|█▉        | 1922/10000 [06:08<25:38,  5.25step/s, loss=0.096876, elapsed=6.1min]

Entraînement:  19%|█▉        | 1922/10000 [06:08<25:38,  5.25step/s, loss=0.046446, elapsed=6.1min]

Entraînement:  19%|█▉        | 1923/10000 [06:08<25:36,  5.26step/s, loss=0.046446, elapsed=6.1min]

Entraînement:  19%|█▉        | 1923/10000 [06:08<25:36,  5.26step/s, loss=0.096234, elapsed=6.1min]

Entraînement:  19%|█▉        | 1924/10000 [06:09<25:37,  5.25step/s, loss=0.096234, elapsed=6.1min]

Entraînement:  19%|█▉        | 1924/10000 [06:09<25:37,  5.25step/s, loss=0.110386, elapsed=6.2min]

Entraînement:  19%|█▉        | 1925/10000 [06:09<25:36,  5.25step/s, loss=0.110386, elapsed=6.2min]

Entraînement:  19%|█▉        | 1925/10000 [06:09<25:36,  5.25step/s, loss=0.074865, elapsed=6.2min]

Entraînement:  19%|█▉        | 1926/10000 [06:09<25:33,  5.26step/s, loss=0.074865, elapsed=6.2min]

Entraînement:  19%|█▉        | 1926/10000 [06:09<25:33,  5.26step/s, loss=0.060507, elapsed=6.2min]

Entraînement:  19%|█▉        | 1927/10000 [06:09<25:34,  5.26step/s, loss=0.060507, elapsed=6.2min]

Entraînement:  19%|█▉        | 1927/10000 [06:09<25:34,  5.26step/s, loss=0.069531, elapsed=6.2min]

Entraînement:  19%|█▉        | 1928/10000 [06:09<25:36,  5.25step/s, loss=0.069531, elapsed=6.2min]

Entraînement:  19%|█▉        | 1928/10000 [06:09<25:36,  5.25step/s, loss=0.142160, elapsed=6.2min]

Entraînement:  19%|█▉        | 1929/10000 [06:10<25:33,  5.26step/s, loss=0.142160, elapsed=6.2min]

Entraînement:  19%|█▉        | 1929/10000 [06:10<25:33,  5.26step/s, loss=0.089915, elapsed=6.2min]

Entraînement:  19%|█▉        | 1930/10000 [06:10<25:39,  5.24step/s, loss=0.089915, elapsed=6.2min]

Entraînement:  19%|█▉        | 1930/10000 [06:10<25:39,  5.24step/s, loss=0.034792, elapsed=6.2min]

Entraînement:  19%|█▉        | 1931/10000 [06:10<25:40,  5.24step/s, loss=0.034792, elapsed=6.2min]

Entraînement:  19%|█▉        | 1931/10000 [06:10<25:40,  5.24step/s, loss=0.033898, elapsed=6.2min]

Entraînement:  19%|█▉        | 1932/10000 [06:10<25:44,  5.22step/s, loss=0.033898, elapsed=6.2min]

Entraînement:  19%|█▉        | 1932/10000 [06:10<25:44,  5.22step/s, loss=0.035091, elapsed=6.2min]

Entraînement:  19%|█▉        | 1933/10000 [06:10<25:39,  5.24step/s, loss=0.035091, elapsed=6.2min]

Entraînement:  19%|█▉        | 1933/10000 [06:10<25:39,  5.24step/s, loss=0.042813, elapsed=6.2min]

Entraînement:  19%|█▉        | 1934/10000 [06:11<25:35,  5.25step/s, loss=0.042813, elapsed=6.2min]

Entraînement:  19%|█▉        | 1934/10000 [06:11<25:35,  5.25step/s, loss=0.057597, elapsed=6.2min]

Entraînement:  19%|█▉        | 1935/10000 [06:11<25:32,  5.26step/s, loss=0.057597, elapsed=6.2min]

Entraînement:  19%|█▉        | 1935/10000 [06:11<25:32,  5.26step/s, loss=0.048320, elapsed=6.2min]

Entraînement:  19%|█▉        | 1936/10000 [06:11<25:30,  5.27step/s, loss=0.048320, elapsed=6.2min]

Entraînement:  19%|█▉        | 1936/10000 [06:11<25:30,  5.27step/s, loss=0.040115, elapsed=6.2min]

Entraînement:  19%|█▉        | 1937/10000 [06:11<25:28,  5.28step/s, loss=0.040115, elapsed=6.2min]

Entraînement:  19%|█▉        | 1937/10000 [06:11<25:28,  5.28step/s, loss=0.051647, elapsed=6.2min]

Entraînement:  19%|█▉        | 1938/10000 [06:11<25:28,  5.28step/s, loss=0.051647, elapsed=6.2min]

Entraînement:  19%|█▉        | 1938/10000 [06:11<25:28,  5.28step/s, loss=0.040750, elapsed=6.2min]

Entraînement:  19%|█▉        | 1939/10000 [06:12<25:26,  5.28step/s, loss=0.040750, elapsed=6.2min]

Entraînement:  19%|█▉        | 1939/10000 [06:12<25:26,  5.28step/s, loss=0.059122, elapsed=6.2min]

Entraînement:  19%|█▉        | 1940/10000 [06:12<25:26,  5.28step/s, loss=0.059122, elapsed=6.2min]

Entraînement:  19%|█▉        | 1940/10000 [06:12<25:26,  5.28step/s, loss=0.147047, elapsed=6.2min]

Entraînement:  19%|█▉        | 1941/10000 [06:12<25:29,  5.27step/s, loss=0.147047, elapsed=6.2min]

Entraînement:  19%|█▉        | 1941/10000 [06:12<25:29,  5.27step/s, loss=0.041045, elapsed=6.2min]

Entraînement:  19%|█▉        | 1942/10000 [06:12<25:36,  5.24step/s, loss=0.041045, elapsed=6.2min]

Entraînement:  19%|█▉        | 1942/10000 [06:12<25:36,  5.24step/s, loss=0.026813, elapsed=6.2min]

Entraînement:  19%|█▉        | 1943/10000 [06:12<25:39,  5.24step/s, loss=0.026813, elapsed=6.2min]

Entraînement:  19%|█▉        | 1943/10000 [06:12<25:39,  5.24step/s, loss=0.139296, elapsed=6.2min]

Entraînement:  19%|█▉        | 1944/10000 [06:12<25:36,  5.24step/s, loss=0.139296, elapsed=6.2min]

Entraînement:  19%|█▉        | 1944/10000 [06:12<25:36,  5.24step/s, loss=0.099153, elapsed=6.2min]

Entraînement:  19%|█▉        | 1945/10000 [06:13<25:30,  5.26step/s, loss=0.099153, elapsed=6.2min]

Entraînement:  19%|█▉        | 1945/10000 [06:13<25:30,  5.26step/s, loss=0.079703, elapsed=6.2min]

Entraînement:  19%|█▉        | 1946/10000 [06:13<25:30,  5.26step/s, loss=0.079703, elapsed=6.2min]

Entraînement:  19%|█▉        | 1946/10000 [06:13<25:30,  5.26step/s, loss=0.062328, elapsed=6.2min]

Entraînement:  19%|█▉        | 1947/10000 [06:13<25:31,  5.26step/s, loss=0.062328, elapsed=6.2min]

Entraînement:  19%|█▉        | 1947/10000 [06:13<25:31,  5.26step/s, loss=0.076824, elapsed=6.2min]

Entraînement:  19%|█▉        | 1948/10000 [06:13<25:29,  5.26step/s, loss=0.076824, elapsed=6.2min]

Entraînement:  19%|█▉        | 1948/10000 [06:13<25:29,  5.26step/s, loss=0.039334, elapsed=6.2min]

Entraînement:  19%|█▉        | 1949/10000 [06:13<25:27,  5.27step/s, loss=0.039334, elapsed=6.2min]

Entraînement:  19%|█▉        | 1949/10000 [06:13<25:27,  5.27step/s, loss=0.066061, elapsed=6.2min]

Entraînement:  20%|█▉        | 1950/10000 [06:14<25:26,  5.27step/s, loss=0.066061, elapsed=6.2min]

Entraînement:  20%|█▉        | 1950/10000 [06:14<25:26,  5.27step/s, loss=0.040212, elapsed=6.2min]

Entraînement:  20%|█▉        | 1951/10000 [06:14<25:27,  5.27step/s, loss=0.040212, elapsed=6.2min]

Entraînement:  20%|█▉        | 1951/10000 [06:14<25:27,  5.27step/s, loss=0.040822, elapsed=6.2min]

Entraînement:  20%|█▉        | 1952/10000 [06:14<25:28,  5.27step/s, loss=0.040822, elapsed=6.2min]

Entraînement:  20%|█▉        | 1952/10000 [06:14<25:28,  5.27step/s, loss=0.027118, elapsed=6.2min]

Entraînement:  20%|█▉        | 1953/10000 [06:14<25:26,  5.27step/s, loss=0.027118, elapsed=6.2min]

Entraînement:  20%|█▉        | 1953/10000 [06:14<25:26,  5.27step/s, loss=0.068151, elapsed=6.2min]

Entraînement:  20%|█▉        | 1954/10000 [06:14<25:28,  5.26step/s, loss=0.068151, elapsed=6.2min]

Entraînement:  20%|█▉        | 1954/10000 [06:14<25:28,  5.26step/s, loss=0.063877, elapsed=6.2min]

Entraînement:  20%|█▉        | 1955/10000 [06:15<25:26,  5.27step/s, loss=0.063877, elapsed=6.2min]

Entraînement:  20%|█▉        | 1955/10000 [06:15<25:26,  5.27step/s, loss=0.055586, elapsed=6.3min]

Entraînement:  20%|█▉        | 1956/10000 [06:15<25:23,  5.28step/s, loss=0.055586, elapsed=6.3min]

Entraînement:  20%|█▉        | 1956/10000 [06:15<25:23,  5.28step/s, loss=0.149328, elapsed=6.3min]

Entraînement:  20%|█▉        | 1957/10000 [06:15<25:23,  5.28step/s, loss=0.149328, elapsed=6.3min]

Entraînement:  20%|█▉        | 1957/10000 [06:15<25:23,  5.28step/s, loss=0.037235, elapsed=6.3min]

Entraînement:  20%|█▉        | 1958/10000 [06:15<25:21,  5.28step/s, loss=0.037235, elapsed=6.3min]

Entraînement:  20%|█▉        | 1958/10000 [06:15<25:21,  5.28step/s, loss=0.049090, elapsed=6.3min]

Entraînement:  20%|█▉        | 1959/10000 [06:15<25:19,  5.29step/s, loss=0.049090, elapsed=6.3min]

Entraînement:  20%|█▉        | 1959/10000 [06:15<25:19,  5.29step/s, loss=0.073660, elapsed=6.3min]

Entraînement:  20%|█▉        | 1960/10000 [06:16<25:19,  5.29step/s, loss=0.073660, elapsed=6.3min]

Entraînement:  20%|█▉        | 1960/10000 [06:16<25:19,  5.29step/s, loss=0.036946, elapsed=6.3min]

Entraînement:  20%|█▉        | 1961/10000 [06:16<25:22,  5.28step/s, loss=0.036946, elapsed=6.3min]

Entraînement:  20%|█▉        | 1961/10000 [06:16<25:22,  5.28step/s, loss=0.064159, elapsed=6.3min]

Entraînement:  20%|█▉        | 1962/10000 [06:16<25:22,  5.28step/s, loss=0.064159, elapsed=6.3min]

Entraînement:  20%|█▉        | 1962/10000 [06:16<25:22,  5.28step/s, loss=0.029540, elapsed=6.3min]

Entraînement:  20%|█▉        | 1963/10000 [06:16<28:33,  4.69step/s, loss=0.029540, elapsed=6.3min]

Entraînement:  20%|█▉        | 1963/10000 [06:16<28:33,  4.69step/s, loss=0.072566, elapsed=6.3min]

Entraînement:  20%|█▉        | 1964/10000 [06:16<27:26,  4.88step/s, loss=0.072566, elapsed=6.3min]

Entraînement:  20%|█▉        | 1964/10000 [06:16<27:26,  4.88step/s, loss=0.042155, elapsed=6.3min]

Entraînement:  20%|█▉        | 1965/10000 [06:17<26:47,  5.00step/s, loss=0.042155, elapsed=6.3min]

Entraînement:  20%|█▉        | 1965/10000 [06:17<26:47,  5.00step/s, loss=0.124399, elapsed=6.3min]

Entraînement:  20%|█▉        | 1966/10000 [06:17<26:19,  5.09step/s, loss=0.124399, elapsed=6.3min]

Entraînement:  20%|█▉        | 1966/10000 [06:17<26:19,  5.09step/s, loss=0.060190, elapsed=6.3min]

Entraînement:  20%|█▉        | 1967/10000 [06:17<26:04,  5.13step/s, loss=0.060190, elapsed=6.3min]

Entraînement:  20%|█▉        | 1967/10000 [06:17<26:04,  5.13step/s, loss=0.039235, elapsed=6.3min]

Entraînement:  20%|█▉        | 1968/10000 [06:17<25:54,  5.17step/s, loss=0.039235, elapsed=6.3min]

Entraînement:  20%|█▉        | 1968/10000 [06:17<25:54,  5.17step/s, loss=0.039662, elapsed=6.3min]

Entraînement:  20%|█▉        | 1969/10000 [06:17<25:41,  5.21step/s, loss=0.039662, elapsed=6.3min]

Entraînement:  20%|█▉        | 1969/10000 [06:17<25:41,  5.21step/s, loss=0.057225, elapsed=6.3min]

Entraînement:  20%|█▉        | 1970/10000 [06:17<25:37,  5.22step/s, loss=0.057225, elapsed=6.3min]

Entraînement:  20%|█▉        | 1970/10000 [06:17<25:37,  5.22step/s, loss=0.041398, elapsed=6.3min]

Entraînement:  20%|█▉        | 1971/10000 [06:18<25:31,  5.24step/s, loss=0.041398, elapsed=6.3min]

Entraînement:  20%|█▉        | 1971/10000 [06:18<25:31,  5.24step/s, loss=0.053680, elapsed=6.3min]

Entraînement:  20%|█▉        | 1972/10000 [06:18<25:29,  5.25step/s, loss=0.053680, elapsed=6.3min]

Entraînement:  20%|█▉        | 1972/10000 [06:18<25:29,  5.25step/s, loss=0.038903, elapsed=6.3min]

Entraînement:  20%|█▉        | 1973/10000 [06:18<25:29,  5.25step/s, loss=0.038903, elapsed=6.3min]

Entraînement:  20%|█▉        | 1973/10000 [06:18<25:29,  5.25step/s, loss=0.031793, elapsed=6.3min]

Entraînement:  20%|█▉        | 1974/10000 [06:18<25:27,  5.26step/s, loss=0.031793, elapsed=6.3min]

Entraînement:  20%|█▉        | 1974/10000 [06:18<25:27,  5.26step/s, loss=0.046177, elapsed=6.3min]

Entraînement:  20%|█▉        | 1975/10000 [06:18<25:26,  5.26step/s, loss=0.046177, elapsed=6.3min]

Entraînement:  20%|█▉        | 1975/10000 [06:18<25:26,  5.26step/s, loss=0.025851, elapsed=6.3min]

Entraînement:  20%|█▉        | 1976/10000 [06:19<25:23,  5.27step/s, loss=0.025851, elapsed=6.3min]

Entraînement:  20%|█▉        | 1976/10000 [06:19<25:23,  5.27step/s, loss=0.061823, elapsed=6.3min]

Entraînement:  20%|█▉        | 1977/10000 [06:19<25:24,  5.26step/s, loss=0.061823, elapsed=6.3min]

Entraînement:  20%|█▉        | 1977/10000 [06:19<25:24,  5.26step/s, loss=0.034999, elapsed=6.3min]

Entraînement:  20%|█▉        | 1978/10000 [06:19<25:21,  5.27step/s, loss=0.034999, elapsed=6.3min]

Entraînement:  20%|█▉        | 1978/10000 [06:19<25:21,  5.27step/s, loss=0.046806, elapsed=6.3min]

Entraînement:  20%|█▉        | 1979/10000 [06:19<25:20,  5.28step/s, loss=0.046806, elapsed=6.3min]

Entraînement:  20%|█▉        | 1979/10000 [06:19<25:20,  5.28step/s, loss=0.065516, elapsed=6.3min]

Entraînement:  20%|█▉        | 1980/10000 [06:19<25:20,  5.28step/s, loss=0.065516, elapsed=6.3min]

Entraînement:  20%|█▉        | 1980/10000 [06:19<25:20,  5.28step/s, loss=0.077299, elapsed=6.3min]

Entraînement:  20%|█▉        | 1981/10000 [06:20<25:18,  5.28step/s, loss=0.077299, elapsed=6.3min]

Entraînement:  20%|█▉        | 1981/10000 [06:20<25:18,  5.28step/s, loss=0.077430, elapsed=6.3min]

Entraînement:  20%|█▉        | 1982/10000 [06:20<25:22,  5.27step/s, loss=0.077430, elapsed=6.3min]

Entraînement:  20%|█▉        | 1982/10000 [06:20<25:22,  5.27step/s, loss=0.053375, elapsed=6.3min]

Entraînement:  20%|█▉        | 1983/10000 [06:20<25:21,  5.27step/s, loss=0.053375, elapsed=6.3min]

Entraînement:  20%|█▉        | 1983/10000 [06:20<25:21,  5.27step/s, loss=0.040454, elapsed=6.3min]

Entraînement:  20%|█▉        | 1984/10000 [06:20<25:22,  5.27step/s, loss=0.040454, elapsed=6.3min]

Entraînement:  20%|█▉        | 1984/10000 [06:20<25:22,  5.27step/s, loss=0.045684, elapsed=6.3min]

Entraînement:  20%|█▉        | 1985/10000 [06:20<25:18,  5.28step/s, loss=0.045684, elapsed=6.3min]

Entraînement:  20%|█▉        | 1985/10000 [06:20<25:18,  5.28step/s, loss=0.065420, elapsed=6.3min]

Entraînement:  20%|█▉        | 1986/10000 [06:21<25:18,  5.28step/s, loss=0.065420, elapsed=6.3min]

Entraînement:  20%|█▉        | 1986/10000 [06:21<25:18,  5.28step/s, loss=0.064499, elapsed=6.4min]

Entraînement:  20%|█▉        | 1987/10000 [06:21<25:16,  5.28step/s, loss=0.064499, elapsed=6.4min]

Entraînement:  20%|█▉        | 1987/10000 [06:21<25:16,  5.28step/s, loss=0.042720, elapsed=6.4min]

Entraînement:  20%|█▉        | 1988/10000 [06:21<25:15,  5.29step/s, loss=0.042720, elapsed=6.4min]

Entraînement:  20%|█▉        | 1988/10000 [06:21<25:15,  5.29step/s, loss=0.061436, elapsed=6.4min]

Entraînement:  20%|█▉        | 1989/10000 [06:21<25:16,  5.28step/s, loss=0.061436, elapsed=6.4min]

Entraînement:  20%|█▉        | 1989/10000 [06:21<25:16,  5.28step/s, loss=0.117779, elapsed=6.4min]

Entraînement:  20%|█▉        | 1990/10000 [06:21<25:15,  5.29step/s, loss=0.117779, elapsed=6.4min]

Entraînement:  20%|█▉        | 1990/10000 [06:21<25:15,  5.29step/s, loss=0.058393, elapsed=6.4min]

Entraînement:  20%|█▉        | 1991/10000 [06:21<25:16,  5.28step/s, loss=0.058393, elapsed=6.4min]

Entraînement:  20%|█▉        | 1991/10000 [06:21<25:16,  5.28step/s, loss=0.080508, elapsed=6.4min]

Entraînement:  20%|█▉        | 1992/10000 [06:22<25:16,  5.28step/s, loss=0.080508, elapsed=6.4min]

Entraînement:  20%|█▉        | 1992/10000 [06:22<25:16,  5.28step/s, loss=0.047568, elapsed=6.4min]

Entraînement:  20%|█▉        | 1993/10000 [06:22<25:14,  5.29step/s, loss=0.047568, elapsed=6.4min]

Entraînement:  20%|█▉        | 1993/10000 [06:22<25:14,  5.29step/s, loss=0.058526, elapsed=6.4min]

Entraînement:  20%|█▉        | 1994/10000 [06:22<25:15,  5.28step/s, loss=0.058526, elapsed=6.4min]

Entraînement:  20%|█▉        | 1994/10000 [06:22<25:15,  5.28step/s, loss=0.039671, elapsed=6.4min]

Entraînement:  20%|█▉        | 1995/10000 [06:22<25:15,  5.28step/s, loss=0.039671, elapsed=6.4min]

Entraînement:  20%|█▉        | 1995/10000 [06:22<25:15,  5.28step/s, loss=0.040484, elapsed=6.4min]

Entraînement:  20%|█▉        | 1996/10000 [06:22<25:14,  5.29step/s, loss=0.040484, elapsed=6.4min]

Entraînement:  20%|█▉        | 1996/10000 [06:22<25:14,  5.29step/s, loss=0.117639, elapsed=6.4min]

Entraînement:  20%|█▉        | 1997/10000 [06:23<25:16,  5.28step/s, loss=0.117639, elapsed=6.4min]

Entraînement:  20%|█▉        | 1997/10000 [06:23<25:16,  5.28step/s, loss=0.072376, elapsed=6.4min]

Entraînement:  20%|█▉        | 1998/10000 [06:23<25:13,  5.29step/s, loss=0.072376, elapsed=6.4min]

Entraînement:  20%|█▉        | 1998/10000 [06:23<25:13,  5.29step/s, loss=0.046290, elapsed=6.4min]

Entraînement:  20%|█▉        | 1999/10000 [06:23<25:16,  5.28step/s, loss=0.046290, elapsed=6.4min]

Entraînement:  20%|█▉        | 1999/10000 [06:23<25:16,  5.28step/s, loss=0.114538, elapsed=6.4min]

Entraînement:  20%|██        | 2000/10000 [06:23<25:14,  5.28step/s, loss=0.114538, elapsed=6.4min]

Entraînement:  20%|██        | 2000/10000 [06:23<25:14,  5.28step/s, loss=0.056071, elapsed=6.4min]

Entraînement:  20%|██        | 2000/10000 [06:23<25:14,  5.28step/s, loss=0.056071, elapsed=6.4min]

Step 2000/10000 | Train loss: 0.056071 | Elapsed: 6.4min | ETA: 25.6min

Entraînement:  20%|██        | 2000/10000 [06:25<25:14,  5.28step/s, loss=0.056071, elapsed=6.4min]

Entraînement:  20%|██        | 2000/10000 [06:25<25:14,  5.28step/s, loss=0.056071, elapsed=6.4min]

Step 2000/10000 | Val loss: 0.058241 | Validation en 1.7s
Meilleur checkpoint sauvegardé : /workspace/DiffWave_Project/checkpoints/diffwave_doda_male/best_checkpoint.pt

Entraînement:  20%|██        | 2000/10000 [06:25<25:14,  5.28step/s, loss=0.056071, elapsed=6.4min]

Entraînement:  20%|██        | 2001/10000 [06:25<1:45:47,  1.26step/s, loss=0.056071, elapsed=6.4min]

Dernier checkpoint sauvegardé : /workspace/DiffWave_Project/checkpoints/diffwave_doda_male/last_checkpoint.pt

Entraînement:  20%|██        | 2001/10000 [06:25<1:45:47,  1.26step/s, loss=0.065516, elapsed=6.4min]

Entraînement:  20%|██        | 2002/10000 [06:26<1:21:39,  1.63step/s, loss=0.065516, elapsed=6.4min]

Entraînement:  20%|██        | 2002/10000 [06:26<1:21:39,  1.63step/s, loss=0.054257, elapsed=6.4min]

Entraînement:  20%|██        | 2003/10000 [06:26<1:04:43,  2.06step/s, loss=0.054257, elapsed=6.4min]

Entraînement:  20%|██        | 2003/10000 [06:26<1:04:43,  2.06step/s, loss=0.068421, elapsed=6.4min]

Entraînement:  20%|██        | 2004/10000 [06:26<52:50,  2.52step/s, loss=0.068421, elapsed=6.4min]

Entraînement:  20%|██        | 2004/10000 [06:26<52:50,  2.52step/s, loss=0.053466, elapsed=6.4min]

Entraînement:  20%|██        | 2005/10000 [06:26<44:35,  2.99step/s, loss=0.053466, elapsed=6.4min]

Entraînement:  20%|██        | 2005/10000 [06:26<44:35,  2.99step/s, loss=0.035879, elapsed=6.4min]

Entraînement:  20%|██        | 2006/10000 [06:26<38:48,  3.43step/s, loss=0.035879, elapsed=6.4min]

Entraînement:  20%|██        | 2006/10000 [06:26<38:48,  3.43step/s, loss=0.046502, elapsed=6.4min]

Entraînement:  20%|██        | 2007/10000 [06:27<34:44,  3.83step/s, loss=0.046502, elapsed=6.4min]

Entraînement:  20%|██        | 2007/10000 [06:27<34:44,  3.83step/s, loss=0.088379, elapsed=6.5min]

Entraînement:  20%|██        | 2008/10000 [06:27<31:52,  4.18step/s, loss=0.088379, elapsed=6.5min]

Entraînement:  20%|██        | 2008/10000 [06:27<31:52,  4.18step/s, loss=0.056130, elapsed=6.5min]

Entraînement:  20%|██        | 2009/10000 [06:27<29:50,  4.46step/s, loss=0.056130, elapsed=6.5min]

Entraînement:  20%|██        | 2009/10000 [06:27<29:50,  4.46step/s, loss=0.025882, elapsed=6.5min]

Entraînement:  20%|██        | 2010/10000 [06:27<28:28,  4.68step/s, loss=0.025882, elapsed=6.5min]

Entraînement:  20%|██        | 2010/10000 [06:27<28:28,  4.68step/s, loss=0.118002, elapsed=6.5min]

Entraînement:  20%|██        | 2011/10000 [06:27<27:28,  4.85step/s, loss=0.118002, elapsed=6.5min]

Entraînement:  20%|██        | 2011/10000 [06:27<27:28,  4.85step/s, loss=0.028344, elapsed=6.5min]

Entraînement:  20%|██        | 2012/10000 [06:27<26:47,  4.97step/s, loss=0.028344, elapsed=6.5min]

Entraînement:  20%|██        | 2012/10000 [06:27<26:47,  4.97step/s, loss=0.083307, elapsed=6.5min]

Entraînement:  20%|██        | 2013/10000 [06:28<26:18,  5.06step/s, loss=0.083307, elapsed=6.5min]

Entraînement:  20%|██        | 2013/10000 [06:28<26:18,  5.06step/s, loss=0.077904, elapsed=6.5min]

Entraînement:  20%|██        | 2014/10000 [06:28<26:01,  5.11step/s, loss=0.077904, elapsed=6.5min]

Entraînement:  20%|██        | 2014/10000 [06:28<26:01,  5.11step/s, loss=0.054000, elapsed=6.5min]

Entraînement:  20%|██        | 2015/10000 [06:28<25:46,  5.16step/s, loss=0.054000, elapsed=6.5min]

Entraînement:  20%|██        | 2015/10000 [06:28<25:46,  5.16step/s, loss=0.034724, elapsed=6.5min]

Entraînement:  20%|██        | 2016/10000 [06:28<25:37,  5.19step/s, loss=0.034724, elapsed=6.5min]

Entraînement:  20%|██        | 2016/10000 [06:28<25:37,  5.19step/s, loss=0.048008, elapsed=6.5min]

Entraînement:  20%|██        | 2017/10000 [06:28<25:29,  5.22step/s, loss=0.048008, elapsed=6.5min]

Entraînement:  20%|██        | 2017/10000 [06:28<25:29,  5.22step/s, loss=0.073404, elapsed=6.5min]

Entraînement:  20%|██        | 2018/10000 [06:29<25:22,  5.24step/s, loss=0.073404, elapsed=6.5min]

Entraînement:  20%|██        | 2018/10000 [06:29<25:22,  5.24step/s, loss=0.057870, elapsed=6.5min]

Entraînement:  20%|██        | 2019/10000 [06:29<25:18,  5.26step/s, loss=0.057870, elapsed=6.5min]

Entraînement:  20%|██        | 2019/10000 [06:29<25:18,  5.26step/s, loss=0.030163, elapsed=6.5min]

Entraînement:  20%|██        | 2020/10000 [06:29<25:15,  5.27step/s, loss=0.030163, elapsed=6.5min]

Entraînement:  20%|██        | 2020/10000 [06:29<25:15,  5.27step/s, loss=0.048948, elapsed=6.5min]

Entraînement:  20%|██        | 2021/10000 [06:29<25:17,  5.26step/s, loss=0.048948, elapsed=6.5min]

Entraînement:  20%|██        | 2021/10000 [06:29<25:17,  5.26step/s, loss=0.071901, elapsed=6.5min]

Entraînement:  20%|██        | 2022/10000 [06:29<25:19,  5.25step/s, loss=0.071901, elapsed=6.5min]

Entraînement:  20%|██        | 2022/10000 [06:29<25:19,  5.25step/s, loss=0.052980, elapsed=6.5min]

Entraînement:  20%|██        | 2023/10000 [06:30<25:15,  5.26step/s, loss=0.052980, elapsed=6.5min]

Entraînement:  20%|██        | 2023/10000 [06:30<25:15,  5.26step/s, loss=0.047781, elapsed=6.5min]

Entraînement:  20%|██        | 2024/10000 [06:30<25:15,  5.26step/s, loss=0.047781, elapsed=6.5min]

Entraînement:  20%|██        | 2024/10000 [06:30<25:15,  5.26step/s, loss=0.051140, elapsed=6.5min]

Entraînement:  20%|██        | 2025/10000 [06:30<25:12,  5.27step/s, loss=0.051140, elapsed=6.5min]

Entraînement:  20%|██        | 2025/10000 [06:30<25:12,  5.27step/s, loss=0.081580, elapsed=6.5min]

Entraînement:  20%|██        | 2026/10000 [06:30<25:13,  5.27step/s, loss=0.081580, elapsed=6.5min]

Entraînement:  20%|██        | 2026/10000 [06:30<25:13,  5.27step/s, loss=0.060064, elapsed=6.5min]

Entraînement:  20%|██        | 2027/10000 [06:30<25:13,  5.27step/s, loss=0.060064, elapsed=6.5min]

Entraînement:  20%|██        | 2027/10000 [06:30<25:13,  5.27step/s, loss=0.047738, elapsed=6.5min]

Entraînement:  20%|██        | 2028/10000 [06:30<25:11,  5.27step/s, loss=0.047738, elapsed=6.5min]

Entraînement:  20%|██        | 2028/10000 [06:30<25:11,  5.27step/s, loss=0.051557, elapsed=6.5min]

Entraînement:  20%|██        | 2029/10000 [06:31<25:14,  5.26step/s, loss=0.051557, elapsed=6.5min]

Entraînement:  20%|██        | 2029/10000 [06:31<25:14,  5.26step/s, loss=0.177631, elapsed=6.5min]

Entraînement:  20%|██        | 2030/10000 [06:31<25:15,  5.26step/s, loss=0.177631, elapsed=6.5min]

Entraînement:  20%|██        | 2030/10000 [06:31<25:15,  5.26step/s, loss=0.130474, elapsed=6.5min]

Entraînement:  20%|██        | 2031/10000 [06:31<25:15,  5.26step/s, loss=0.130474, elapsed=6.5min]

Entraînement:  20%|██        | 2031/10000 [06:31<25:15,  5.26step/s, loss=0.077554, elapsed=6.5min]

Entraînement:  20%|██        | 2032/10000 [06:31<25:15,  5.26step/s, loss=0.077554, elapsed=6.5min]

Entraînement:  20%|██        | 2032/10000 [06:31<25:15,  5.26step/s, loss=0.039287, elapsed=6.5min]

Entraînement:  20%|██        | 2033/10000 [06:31<25:16,  5.25step/s, loss=0.039287, elapsed=6.5min]

Entraînement:  20%|██        | 2033/10000 [06:31<25:16,  5.25step/s, loss=0.037458, elapsed=6.5min]

Entraînement:  20%|██        | 2034/10000 [06:32<25:15,  5.26step/s, loss=0.037458, elapsed=6.5min]

Entraînement:  20%|██        | 2034/10000 [06:32<25:15,  5.26step/s, loss=0.159888, elapsed=6.5min]

Entraînement:  20%|██        | 2035/10000 [06:32<25:13,  5.26step/s, loss=0.159888, elapsed=6.5min]

Entraînement:  20%|██        | 2035/10000 [06:32<25:13,  5.26step/s, loss=0.089176, elapsed=6.5min]

Entraînement:  20%|██        | 2036/10000 [06:32<25:13,  5.26step/s, loss=0.089176, elapsed=6.5min]

Entraînement:  20%|██        | 2036/10000 [06:32<25:13,  5.26step/s, loss=0.029144, elapsed=6.5min]

Entraînement:  20%|██        | 2037/10000 [06:32<25:12,  5.26step/s, loss=0.029144, elapsed=6.5min]

Entraînement:  20%|██        | 2037/10000 [06:32<25:12,  5.26step/s, loss=0.038396, elapsed=6.5min]

Entraînement:  20%|██        | 2038/10000 [06:32<25:14,  5.26step/s, loss=0.038396, elapsed=6.5min]

Entraînement:  20%|██        | 2038/10000 [06:32<25:14,  5.26step/s, loss=0.065506, elapsed=6.5min]

Entraînement:  20%|██        | 2039/10000 [06:33<25:11,  5.27step/s, loss=0.065506, elapsed=6.5min]

Entraînement:  20%|██        | 2039/10000 [06:33<25:11,  5.27step/s, loss=0.055867, elapsed=6.6min]

Entraînement:  20%|██        | 2040/10000 [06:33<25:13,  5.26step/s, loss=0.055867, elapsed=6.6min]

Entraînement:  20%|██        | 2040/10000 [06:33<25:13,  5.26step/s, loss=0.118044, elapsed=6.6min]

Entraînement:  20%|██        | 2041/10000 [06:33<25:10,  5.27step/s, loss=0.118044, elapsed=6.6min]

Entraînement:  20%|██        | 2041/10000 [06:33<25:10,  5.27step/s, loss=0.070539, elapsed=6.6min]

Entraînement:  20%|██        | 2042/10000 [06:33<25:11,  5.27step/s, loss=0.070539, elapsed=6.6min]

Entraînement:  20%|██        | 2042/10000 [06:33<25:11,  5.27step/s, loss=0.036520, elapsed=6.6min]

Entraînement:  20%|██        | 2043/10000 [06:33<25:10,  5.27step/s, loss=0.036520, elapsed=6.6min]

Entraînement:  20%|██        | 2043/10000 [06:33<25:10,  5.27step/s, loss=0.071396, elapsed=6.6min]

Entraînement:  20%|██        | 2044/10000 [06:34<25:15,  5.25step/s, loss=0.071396, elapsed=6.6min]

Entraînement:  20%|██        | 2044/10000 [06:34<25:15,  5.25step/s, loss=0.080478, elapsed=6.6min]

Entraînement:  20%|██        | 2045/10000 [06:34<25:15,  5.25step/s, loss=0.080478, elapsed=6.6min]

Entraînement:  20%|██        | 2045/10000 [06:34<25:15,  5.25step/s, loss=0.072864, elapsed=6.6min]

Entraînement:  20%|██        | 2046/10000 [06:34<25:14,  5.25step/s, loss=0.072864, elapsed=6.6min]

Entraînement:  20%|██        | 2046/10000 [06:34<25:14,  5.25step/s, loss=0.082138, elapsed=6.6min]

Entraînement:  20%|██        | 2047/10000 [06:34<25:14,  5.25step/s, loss=0.082138, elapsed=6.6min]

Entraînement:  20%|██        | 2047/10000 [06:34<25:14,  5.25step/s, loss=0.074533, elapsed=6.6min]

Entraînement:  20%|██        | 2048/10000 [06:34<25:18,  5.24step/s, loss=0.074533, elapsed=6.6min]

Entraînement:  20%|██        | 2048/10000 [06:34<25:18,  5.24step/s, loss=0.110616, elapsed=6.6min]

Entraînement:  20%|██        | 2049/10000 [06:34<25:17,  5.24step/s, loss=0.110616, elapsed=6.6min]

Entraînement:  20%|██        | 2049/10000 [06:34<25:17,  5.24step/s, loss=0.056781, elapsed=6.6min]

Entraînement:  20%|██        | 2050/10000 [06:35<25:14,  5.25step/s, loss=0.056781, elapsed=6.6min]

Entraînement:  20%|██        | 2050/10000 [06:35<25:14,  5.25step/s, loss=0.057916, elapsed=6.6min]

Entraînement:  21%|██        | 2051/10000 [06:35<25:55,  5.11step/s, loss=0.057916, elapsed=6.6min]

Entraînement:  21%|██        | 2051/10000 [06:35<25:55,  5.11step/s, loss=0.034362, elapsed=6.6min]

Entraînement:  21%|██        | 2052/10000 [06:35<25:42,  5.15step/s, loss=0.034362, elapsed=6.6min]

Entraînement:  21%|██        | 2052/10000 [06:35<25:42,  5.15step/s, loss=0.082640, elapsed=6.6min]

Entraînement:  21%|██        | 2053/10000 [06:35<25:33,  5.18step/s, loss=0.082640, elapsed=6.6min]

Entraînement:  21%|██        | 2053/10000 [06:35<25:33,  5.18step/s, loss=0.033702, elapsed=6.6min]

Entraînement:  21%|██        | 2054/10000 [06:35<25:35,  5.18step/s, loss=0.033702, elapsed=6.6min]

Entraînement:  21%|██        | 2054/10000 [06:35<25:35,  5.18step/s, loss=0.039100, elapsed=6.6min]

Entraînement:  21%|██        | 2055/10000 [06:36<25:27,  5.20step/s, loss=0.039100, elapsed=6.6min]

Entraînement:  21%|██        | 2055/10000 [06:36<25:27,  5.20step/s, loss=0.103487, elapsed=6.6min]

Entraînement:  21%|██        | 2056/10000 [06:36<25:20,  5.23step/s, loss=0.103487, elapsed=6.6min]

Entraînement:  21%|██        | 2056/10000 [06:36<25:20,  5.23step/s, loss=0.155739, elapsed=6.6min]

Entraînement:  21%|██        | 2057/10000 [06:36<25:12,  5.25step/s, loss=0.155739, elapsed=6.6min]

Entraînement:  21%|██        | 2057/10000 [06:36<25:12,  5.25step/s, loss=0.022872, elapsed=6.6min]

Entraînement:  21%|██        | 2058/10000 [06:36<25:10,  5.26step/s, loss=0.022872, elapsed=6.6min]

Entraînement:  21%|██        | 2058/10000 [06:36<25:10,  5.26step/s, loss=0.115489, elapsed=6.6min]

Entraînement:  21%|██        | 2059/10000 [06:36<25:08,  5.27step/s, loss=0.115489, elapsed=6.6min]

Entraînement:  21%|██        | 2059/10000 [06:36<25:08,  5.27step/s, loss=0.035842, elapsed=6.6min]

Entraînement:  21%|██        | 2060/10000 [06:37<25:07,  5.27step/s, loss=0.035842, elapsed=6.6min]

Entraînement:  21%|██        | 2060/10000 [06:37<25:07,  5.27step/s, loss=0.064284, elapsed=6.6min]

Entraînement:  21%|██        | 2061/10000 [06:37<25:05,  5.27step/s, loss=0.064284, elapsed=6.6min]

Entraînement:  21%|██        | 2061/10000 [06:37<25:05,  5.27step/s, loss=0.076454, elapsed=6.6min]

Entraînement:  21%|██        | 2062/10000 [06:37<25:05,  5.27step/s, loss=0.076454, elapsed=6.6min]

Entraînement:  21%|██        | 2062/10000 [06:37<25:05,  5.27step/s, loss=0.047325, elapsed=6.6min]

Entraînement:  21%|██        | 2063/10000 [06:37<25:04,  5.27step/s, loss=0.047325, elapsed=6.6min]

Entraînement:  21%|██        | 2063/10000 [06:37<25:04,  5.27step/s, loss=0.075411, elapsed=6.6min]

Entraînement:  21%|██        | 2064/10000 [06:37<25:03,  5.28step/s, loss=0.075411, elapsed=6.6min]

Entraînement:  21%|██        | 2064/10000 [06:37<25:03,  5.28step/s, loss=0.081279, elapsed=6.6min]

Entraînement:  21%|██        | 2065/10000 [06:38<25:02,  5.28step/s, loss=0.081279, elapsed=6.6min]

Entraînement:  21%|██        | 2065/10000 [06:38<25:02,  5.28step/s, loss=0.043538, elapsed=6.6min]

Entraînement:  21%|██        | 2066/10000 [06:38<25:00,  5.29step/s, loss=0.043538, elapsed=6.6min]

Entraînement:  21%|██        | 2066/10000 [06:38<25:00,  5.29step/s, loss=0.062743, elapsed=6.6min]

Entraînement:  21%|██        | 2067/10000 [06:38<25:02,  5.28step/s, loss=0.062743, elapsed=6.6min]

Entraînement:  21%|██        | 2067/10000 [06:38<25:02,  5.28step/s, loss=0.079226, elapsed=6.6min]

Entraînement:  21%|██        | 2068/10000 [06:38<25:02,  5.28step/s, loss=0.079226, elapsed=6.6min]

Entraînement:  21%|██        | 2068/10000 [06:38<25:02,  5.28step/s, loss=0.085265, elapsed=6.6min]

Entraînement:  21%|██        | 2069/10000 [06:38<25:00,  5.29step/s, loss=0.085265, elapsed=6.6min]

Entraînement:  21%|██        | 2069/10000 [06:38<25:00,  5.29step/s, loss=0.049817, elapsed=6.6min]

Entraînement:  21%|██        | 2070/10000 [06:38<25:01,  5.28step/s, loss=0.049817, elapsed=6.6min]

Entraînement:  21%|██        | 2070/10000 [06:38<25:01,  5.28step/s, loss=0.034258, elapsed=6.6min]

Entraînement:  21%|██        | 2071/10000 [06:39<25:00,  5.28step/s, loss=0.034258, elapsed=6.6min]

Entraînement:  21%|██        | 2071/10000 [06:39<25:00,  5.28step/s, loss=0.156240, elapsed=6.7min]

Entraînement:  21%|██        | 2072/10000 [06:39<25:01,  5.28step/s, loss=0.156240, elapsed=6.7min]

Entraînement:  21%|██        | 2072/10000 [06:39<25:01,  5.28step/s, loss=0.058198, elapsed=6.7min]

Entraînement:  21%|██        | 2073/10000 [06:39<24:59,  5.29step/s, loss=0.058198, elapsed=6.7min]

Entraînement:  21%|██        | 2073/10000 [06:39<24:59,  5.29step/s, loss=0.030631, elapsed=6.7min]

Entraînement:  21%|██        | 2074/10000 [06:39<24:57,  5.29step/s, loss=0.030631, elapsed=6.7min]

Entraînement:  21%|██        | 2074/10000 [06:39<24:57,  5.29step/s, loss=0.055073, elapsed=6.7min]

Entraînement:  21%|██        | 2075/10000 [06:39<25:02,  5.27step/s, loss=0.055073, elapsed=6.7min]

Entraînement:  21%|██        | 2075/10000 [06:39<25:02,  5.27step/s, loss=0.065050, elapsed=6.7min]

Entraînement:  21%|██        | 2076/10000 [06:40<25:01,  5.28step/s, loss=0.065050, elapsed=6.7min]

Entraînement:  21%|██        | 2076/10000 [06:40<25:01,  5.28step/s, loss=0.065255, elapsed=6.7min]

Entraînement:  21%|██        | 2077/10000 [06:40<24:59,  5.28step/s, loss=0.065255, elapsed=6.7min]

Entraînement:  21%|██        | 2077/10000 [06:40<24:59,  5.28step/s, loss=0.044986, elapsed=6.7min]

Entraînement:  21%|██        | 2078/10000 [06:40<24:59,  5.28step/s, loss=0.044986, elapsed=6.7min]

Entraînement:  21%|██        | 2078/10000 [06:40<24:59,  5.28step/s, loss=0.130850, elapsed=6.7min]

Entraînement:  21%|██        | 2079/10000 [06:40<24:58,  5.29step/s, loss=0.130850, elapsed=6.7min]

Entraînement:  21%|██        | 2079/10000 [06:40<24:58,  5.29step/s, loss=0.115375, elapsed=6.7min]

Entraînement:  21%|██        | 2080/10000 [06:40<24:58,  5.29step/s, loss=0.115375, elapsed=6.7min]

Entraînement:  21%|██        | 2080/10000 [06:40<24:58,  5.29step/s, loss=0.052158, elapsed=6.7min]

Entraînement:  21%|██        | 2081/10000 [06:41<24:56,  5.29step/s, loss=0.052158, elapsed=6.7min]

Entraînement:  21%|██        | 2081/10000 [06:41<24:56,  5.29step/s, loss=0.044282, elapsed=6.7min]

Entraînement:  21%|██        | 2082/10000 [06:41<24:55,  5.29step/s, loss=0.044282, elapsed=6.7min]

Entraînement:  21%|██        | 2082/10000 [06:41<24:55,  5.29step/s, loss=0.039555, elapsed=6.7min]

Entraînement:  21%|██        | 2083/10000 [06:41<25:05,  5.26step/s, loss=0.039555, elapsed=6.7min]

Entraînement:  21%|██        | 2083/10000 [06:41<25:05,  5.26step/s, loss=0.031576, elapsed=6.7min]

Entraînement:  21%|██        | 2084/10000 [06:41<25:20,  5.20step/s, loss=0.031576, elapsed=6.7min]

Entraînement:  21%|██        | 2084/10000 [06:41<25:20,  5.20step/s, loss=0.094871, elapsed=6.7min]

Entraînement:  21%|██        | 2085/10000 [06:41<25:12,  5.23step/s, loss=0.094871, elapsed=6.7min]

Entraînement:  21%|██        | 2085/10000 [06:41<25:12,  5.23step/s, loss=0.078604, elapsed=6.7min]

Entraînement:  21%|██        | 2086/10000 [06:42<25:10,  5.24step/s, loss=0.078604, elapsed=6.7min]

Entraînement:  21%|██        | 2086/10000 [06:42<25:10,  5.24step/s, loss=0.054706, elapsed=6.7min]

Entraînement:  21%|██        | 2087/10000 [06:42<25:06,  5.25step/s, loss=0.054706, elapsed=6.7min]

Entraînement:  21%|██        | 2087/10000 [06:42<25:06,  5.25step/s, loss=0.078778, elapsed=6.7min]

Entraînement:  21%|██        | 2088/10000 [06:42<25:03,  5.26step/s, loss=0.078778, elapsed=6.7min]

Entraînement:  21%|██        | 2088/10000 [06:42<25:03,  5.26step/s, loss=0.040824, elapsed=6.7min]

Entraînement:  21%|██        | 2089/10000 [06:42<25:02,  5.27step/s, loss=0.040824, elapsed=6.7min]

Entraînement:  21%|██        | 2089/10000 [06:42<25:02,  5.27step/s, loss=0.064125, elapsed=6.7min]

Entraînement:  21%|██        | 2090/10000 [06:42<25:05,  5.25step/s, loss=0.064125, elapsed=6.7min]

Entraînement:  21%|██        | 2090/10000 [06:42<25:05,  5.25step/s, loss=0.057818, elapsed=6.7min]

Entraînement:  21%|██        | 2091/10000 [06:42<25:02,  5.26step/s, loss=0.057818, elapsed=6.7min]

Entraînement:  21%|██        | 2091/10000 [06:42<25:02,  5.26step/s, loss=0.052026, elapsed=6.7min]

Entraînement:  21%|██        | 2092/10000 [06:43<24:59,  5.27step/s, loss=0.052026, elapsed=6.7min]

Entraînement:  21%|██        | 2092/10000 [06:43<24:59,  5.27step/s, loss=0.045366, elapsed=6.7min]

Entraînement:  21%|██        | 2093/10000 [06:43<25:00,  5.27step/s, loss=0.045366, elapsed=6.7min]

Entraînement:  21%|██        | 2093/10000 [06:43<25:00,  5.27step/s, loss=0.046040, elapsed=6.7min]

Entraînement:  21%|██        | 2094/10000 [06:43<25:04,  5.26step/s, loss=0.046040, elapsed=6.7min]

Entraînement:  21%|██        | 2094/10000 [06:43<25:04,  5.26step/s, loss=0.044986, elapsed=6.7min]

Entraînement:  21%|██        | 2095/10000 [06:43<25:01,  5.27step/s, loss=0.044986, elapsed=6.7min]

Entraînement:  21%|██        | 2095/10000 [06:43<25:01,  5.27step/s, loss=0.078194, elapsed=6.7min]

Entraînement:  21%|██        | 2096/10000 [06:43<25:01,  5.26step/s, loss=0.078194, elapsed=6.7min]

Entraînement:  21%|██        | 2096/10000 [06:43<25:01,  5.26step/s, loss=0.115294, elapsed=6.7min]

Entraînement:  21%|██        | 2097/10000 [06:44<24:57,  5.28step/s, loss=0.115294, elapsed=6.7min]

Entraînement:  21%|██        | 2097/10000 [06:44<24:57,  5.28step/s, loss=0.066613, elapsed=6.7min]

Entraînement:  21%|██        | 2098/10000 [06:44<25:00,  5.27step/s, loss=0.066613, elapsed=6.7min]

Entraînement:  21%|██        | 2098/10000 [06:44<25:00,  5.27step/s, loss=0.064741, elapsed=6.7min]

Entraînement:  21%|██        | 2099/10000 [06:44<24:59,  5.27step/s, loss=0.064741, elapsed=6.7min]

Entraînement:  21%|██        | 2099/10000 [06:44<24:59,  5.27step/s, loss=0.102676, elapsed=6.7min]

Entraînement:  21%|██        | 2100/10000 [06:44<24:56,  5.28step/s, loss=0.102676, elapsed=6.7min]

Entraînement:  21%|██        | 2100/10000 [06:44<24:56,  5.28step/s, loss=0.056788, elapsed=6.7min]

Entraînement:  21%|██        | 2100/10000 [06:44<24:56,  5.28step/s, loss=0.056788, elapsed=6.7min]

Entraînement:  21%|██        | 2101/10000 [06:44<25:12,  5.22step/s, loss=0.056788, elapsed=6.7min]

Entraînement:  21%|██        | 2101/10000 [06:44<25:12,  5.22step/s, loss=0.096009, elapsed=6.7min]

Step 2100/10000 | Train loss: 0.056788 | Elapsed: 6.7min | ETA: 25.4min

Entraînement:  21%|██        | 2102/10000 [06:45<25:08,  5.24step/s, loss=0.096009, elapsed=6.7min]

Entraînement:  21%|██        | 2102/10000 [06:45<25:08,  5.24step/s, loss=0.041940, elapsed=6.8min]

Entraînement:  21%|██        | 2103/10000 [06:45<25:04,  5.25step/s, loss=0.041940, elapsed=6.8min]

Entraînement:  21%|██        | 2103/10000 [06:45<25:04,  5.25step/s, loss=0.080651, elapsed=6.8min]

Entraînement:  21%|██        | 2104/10000 [06:45<24:59,  5.27step/s, loss=0.080651, elapsed=6.8min]

Entraînement:  21%|██        | 2104/10000 [06:45<24:59,  5.27step/s, loss=0.038689, elapsed=6.8min]

Entraînement:  21%|██        | 2105/10000 [06:45<25:01,  5.26step/s, loss=0.038689, elapsed=6.8min]

Entraînement:  21%|██        | 2105/10000 [06:45<25:01,  5.26step/s, loss=0.068687, elapsed=6.8min]

Entraînement:  21%|██        | 2106/10000 [06:45<24:59,  5.26step/s, loss=0.068687, elapsed=6.8min]

Entraînement:  21%|██        | 2106/10000 [06:45<24:59,  5.26step/s, loss=0.053512, elapsed=6.8min]

Entraînement:  21%|██        | 2107/10000 [06:46<25:00,  5.26step/s, loss=0.053512, elapsed=6.8min]

Entraînement:  21%|██        | 2107/10000 [06:46<25:00,  5.26step/s, loss=0.099486, elapsed=6.8min]

Entraînement:  21%|██        | 2108/10000 [06:46<24:56,  5.27step/s, loss=0.099486, elapsed=6.8min]

Entraînement:  21%|██        | 2108/10000 [06:46<24:56,  5.27step/s, loss=0.043592, elapsed=6.8min]

Entraînement:  21%|██        | 2109/10000 [06:46<24:51,  5.29step/s, loss=0.043592, elapsed=6.8min]

Entraînement:  21%|██        | 2109/10000 [06:46<24:51,  5.29step/s, loss=0.036674, elapsed=6.8min]

Entraînement:  21%|██        | 2110/10000 [06:46<24:52,  5.29step/s, loss=0.036674, elapsed=6.8min]

Entraînement:  21%|██        | 2110/10000 [06:46<24:52,  5.29step/s, loss=0.046422, elapsed=6.8min]

Entraînement:  21%|██        | 2111/10000 [06:46<24:51,  5.29step/s, loss=0.046422, elapsed=6.8min]

Entraînement:  21%|██        | 2111/10000 [06:46<24:51,  5.29step/s, loss=0.056636, elapsed=6.8min]

Entraînement:  21%|██        | 2112/10000 [06:46<24:52,  5.29step/s, loss=0.056636, elapsed=6.8min]

Entraînement:  21%|██        | 2112/10000 [06:46<24:52,  5.29step/s, loss=0.041529, elapsed=6.8min]

Entraînement:  21%|██        | 2113/10000 [06:47<24:52,  5.29step/s, loss=0.041529, elapsed=6.8min]

Entraînement:  21%|██        | 2113/10000 [06:47<24:52,  5.29step/s, loss=0.045293, elapsed=6.8min]

Entraînement:  21%|██        | 2114/10000 [06:47<24:52,  5.28step/s, loss=0.045293, elapsed=6.8min]

Entraînement:  21%|██        | 2114/10000 [06:47<24:52,  5.28step/s, loss=0.052373, elapsed=6.8min]

Entraînement:  21%|██        | 2115/10000 [06:47<24:53,  5.28step/s, loss=0.052373, elapsed=6.8min]

Entraînement:  21%|██        | 2115/10000 [06:47<24:53,  5.28step/s, loss=0.042267, elapsed=6.8min]

Entraînement:  21%|██        | 2116/10000 [06:47<24:50,  5.29step/s, loss=0.042267, elapsed=6.8min]

Entraînement:  21%|██        | 2116/10000 [06:47<24:50,  5.29step/s, loss=0.142975, elapsed=6.8min]

Entraînement:  21%|██        | 2117/10000 [06:47<24:51,  5.28step/s, loss=0.142975, elapsed=6.8min]

Entraînement:  21%|██        | 2117/10000 [06:47<24:51,  5.28step/s, loss=0.065923, elapsed=6.8min]

Entraînement:  21%|██        | 2118/10000 [06:48<24:51,  5.28step/s, loss=0.065923, elapsed=6.8min]

Entraînement:  21%|██        | 2118/10000 [06:48<24:51,  5.28step/s, loss=0.079620, elapsed=6.8min]

Entraînement:  21%|██        | 2119/10000 [06:48<24:49,  5.29step/s, loss=0.079620, elapsed=6.8min]

Entraînement:  21%|██        | 2119/10000 [06:48<24:49,  5.29step/s, loss=0.123967, elapsed=6.8min]

Entraînement:  21%|██        | 2120/10000 [06:48<24:50,  5.29step/s, loss=0.123967, elapsed=6.8min]

Entraînement:  21%|██        | 2120/10000 [06:48<24:50,  5.29step/s, loss=0.108828, elapsed=6.8min]

Entraînement:  21%|██        | 2121/10000 [06:48<24:55,  5.27step/s, loss=0.108828, elapsed=6.8min]

Entraînement:  21%|██        | 2121/10000 [06:48<24:55,  5.27step/s, loss=0.034128, elapsed=6.8min]

Entraînement:  21%|██        | 2122/10000 [06:48<24:56,  5.26step/s, loss=0.034128, elapsed=6.8min]

Entraînement:  21%|██        | 2122/10000 [06:48<24:56,  5.26step/s, loss=0.054668, elapsed=6.8min]

Entraînement:  21%|██        | 2123/10000 [06:49<24:54,  5.27step/s, loss=0.054668, elapsed=6.8min]

Entraînement:  21%|██        | 2123/10000 [06:49<24:54,  5.27step/s, loss=0.098982, elapsed=6.8min]

Entraînement:  21%|██        | 2124/10000 [06:49<24:52,  5.28step/s, loss=0.098982, elapsed=6.8min]

Entraînement:  21%|██        | 2124/10000 [06:49<24:52,  5.28step/s, loss=0.045059, elapsed=6.8min]

Entraînement:  21%|██▏       | 2125/10000 [06:49<24:51,  5.28step/s, loss=0.045059, elapsed=6.8min]

Entraînement:  21%|██▏       | 2125/10000 [06:49<24:51,  5.28step/s, loss=0.069530, elapsed=6.8min]

Entraînement:  21%|██▏       | 2126/10000 [06:49<24:49,  5.29step/s, loss=0.069530, elapsed=6.8min]

Entraînement:  21%|██▏       | 2126/10000 [06:49<24:49,  5.29step/s, loss=0.065274, elapsed=6.8min]

Entraînement:  21%|██▏       | 2127/10000 [06:49<24:50,  5.28step/s, loss=0.065274, elapsed=6.8min]

Entraînement:  21%|██▏       | 2127/10000 [06:49<24:50,  5.28step/s, loss=0.038699, elapsed=6.8min]

Entraînement:  21%|██▏       | 2128/10000 [06:49<24:50,  5.28step/s, loss=0.038699, elapsed=6.8min]

Entraînement:  21%|██▏       | 2128/10000 [06:49<24:50,  5.28step/s, loss=0.040923, elapsed=6.8min]

Entraînement:  21%|██▏       | 2129/10000 [06:50<24:54,  5.27step/s, loss=0.040923, elapsed=6.8min]

Entraînement:  21%|██▏       | 2129/10000 [06:50<24:54,  5.27step/s, loss=0.043720, elapsed=6.8min]

Entraînement:  21%|██▏       | 2130/10000 [06:50<24:51,  5.28step/s, loss=0.043720, elapsed=6.8min]

Entraînement:  21%|██▏       | 2130/10000 [06:50<24:51,  5.28step/s, loss=0.047806, elapsed=6.8min]

Entraînement:  21%|██▏       | 2131/10000 [06:50<24:54,  5.26step/s, loss=0.047806, elapsed=6.8min]

Entraînement:  21%|██▏       | 2131/10000 [06:50<24:54,  5.26step/s, loss=0.114246, elapsed=6.8min]

Entraînement:  21%|██▏       | 2132/10000 [06:50<24:52,  5.27step/s, loss=0.114246, elapsed=6.8min]

Entraînement:  21%|██▏       | 2132/10000 [06:50<24:52,  5.27step/s, loss=0.058260, elapsed=6.8min]

Entraînement:  21%|██▏       | 2133/10000 [06:50<24:47,  5.29step/s, loss=0.058260, elapsed=6.8min]

Entraînement:  21%|██▏       | 2133/10000 [06:50<24:47,  5.29step/s, loss=0.078002, elapsed=6.8min]

Entraînement:  21%|██▏       | 2134/10000 [06:51<24:47,  5.29step/s, loss=0.078002, elapsed=6.8min]

Entraînement:  21%|██▏       | 2134/10000 [06:51<24:47,  5.29step/s, loss=0.051091, elapsed=6.9min]

Entraînement:  21%|██▏       | 2135/10000 [06:51<24:46,  5.29step/s, loss=0.051091, elapsed=6.9min]

Entraînement:  21%|██▏       | 2135/10000 [06:51<24:46,  5.29step/s, loss=0.038590, elapsed=6.9min]

Entraînement:  21%|██▏       | 2136/10000 [06:51<24:48,  5.28step/s, loss=0.038590, elapsed=6.9min]

Entraînement:  21%|██▏       | 2136/10000 [06:51<24:48,  5.28step/s, loss=0.115392, elapsed=6.9min]

Entraînement:  21%|██▏       | 2137/10000 [06:51<24:51,  5.27step/s, loss=0.115392, elapsed=6.9min]

Entraînement:  21%|██▏       | 2137/10000 [06:51<24:51,  5.27step/s, loss=0.067931, elapsed=6.9min]

Entraînement:  21%|██▏       | 2138/10000 [06:51<24:48,  5.28step/s, loss=0.067931, elapsed=6.9min]

Entraînement:  21%|██▏       | 2138/10000 [06:51<24:48,  5.28step/s, loss=0.099994, elapsed=6.9min]

Entraînement:  21%|██▏       | 2139/10000 [06:52<24:49,  5.28step/s, loss=0.099994, elapsed=6.9min]

Entraînement:  21%|██▏       | 2139/10000 [06:52<24:49,  5.28step/s, loss=0.094665, elapsed=6.9min]

Entraînement:  21%|██▏       | 2140/10000 [06:52<24:47,  5.28step/s, loss=0.094665, elapsed=6.9min]

Entraînement:  21%|██▏       | 2140/10000 [06:52<24:47,  5.28step/s, loss=0.095649, elapsed=6.9min]

Entraînement:  21%|██▏       | 2141/10000 [06:52<24:45,  5.29step/s, loss=0.095649, elapsed=6.9min]

Entraînement:  21%|██▏       | 2141/10000 [06:52<24:45,  5.29step/s, loss=0.065118, elapsed=6.9min]

Entraînement:  21%|██▏       | 2142/10000 [06:52<24:46,  5.29step/s, loss=0.065118, elapsed=6.9min]

Entraînement:  21%|██▏       | 2142/10000 [06:52<24:46,  5.29step/s, loss=0.034278, elapsed=6.9min]

Entraînement:  21%|██▏       | 2143/10000 [06:52<24:45,  5.29step/s, loss=0.034278, elapsed=6.9min]

Entraînement:  21%|██▏       | 2143/10000 [06:52<24:45,  5.29step/s, loss=0.050203, elapsed=6.9min]

Entraînement:  21%|██▏       | 2144/10000 [06:53<24:46,  5.28step/s, loss=0.050203, elapsed=6.9min]

Entraînement:  21%|██▏       | 2144/10000 [06:53<24:46,  5.28step/s, loss=0.066793, elapsed=6.9min]

Entraînement:  21%|██▏       | 2145/10000 [06:53<24:48,  5.28step/s, loss=0.066793, elapsed=6.9min]

Entraînement:  21%|██▏       | 2145/10000 [06:53<24:48,  5.28step/s, loss=0.070020, elapsed=6.9min]

Entraînement:  21%|██▏       | 2146/10000 [06:53<24:47,  5.28step/s, loss=0.070020, elapsed=6.9min]

Entraînement:  21%|██▏       | 2146/10000 [06:53<24:47,  5.28step/s, loss=0.032197, elapsed=6.9min]

Entraînement:  21%|██▏       | 2147/10000 [06:53<24:47,  5.28step/s, loss=0.032197, elapsed=6.9min]

Entraînement:  21%|██▏       | 2147/10000 [06:53<24:47,  5.28step/s, loss=0.071754, elapsed=6.9min]

Entraînement:  21%|██▏       | 2148/10000 [06:53<24:48,  5.28step/s, loss=0.071754, elapsed=6.9min]

Entraînement:  21%|██▏       | 2148/10000 [06:53<24:48,  5.28step/s, loss=0.114875, elapsed=6.9min]

Entraînement:  21%|██▏       | 2149/10000 [06:53<24:51,  5.26step/s, loss=0.114875, elapsed=6.9min]

Entraînement:  21%|██▏       | 2149/10000 [06:53<24:51,  5.26step/s, loss=0.048826, elapsed=6.9min]

Entraînement:  22%|██▏       | 2150/10000 [06:54<24:52,  5.26step/s, loss=0.048826, elapsed=6.9min]

Entraînement:  22%|██▏       | 2150/10000 [06:54<24:52,  5.26step/s, loss=0.045430, elapsed=6.9min]

Entraînement:  22%|██▏       | 2151/10000 [06:54<24:52,  5.26step/s, loss=0.045430, elapsed=6.9min]

Entraînement:  22%|██▏       | 2151/10000 [06:54<24:52,  5.26step/s, loss=0.047106, elapsed=6.9min]

Entraînement:  22%|██▏       | 2152/10000 [06:54<24:51,  5.26step/s, loss=0.047106, elapsed=6.9min]

Entraînement:  22%|██▏       | 2152/10000 [06:54<24:51,  5.26step/s, loss=0.074018, elapsed=6.9min]

Entraînement:  22%|██▏       | 2153/10000 [06:54<24:53,  5.25step/s, loss=0.074018, elapsed=6.9min]

Entraînement:  22%|██▏       | 2153/10000 [06:54<24:53,  5.25step/s, loss=0.047907, elapsed=6.9min]

Entraînement:  22%|██▏       | 2154/10000 [06:54<24:51,  5.26step/s, loss=0.047907, elapsed=6.9min]

Entraînement:  22%|██▏       | 2154/10000 [06:54<24:51,  5.26step/s, loss=0.100634, elapsed=6.9min]

Entraînement:  22%|██▏       | 2155/10000 [06:55<24:50,  5.26step/s, loss=0.100634, elapsed=6.9min]

Entraînement:  22%|██▏       | 2155/10000 [06:55<24:50,  5.26step/s, loss=0.052711, elapsed=6.9min]

Entraînement:  22%|██▏       | 2156/10000 [06:55<24:49,  5.27step/s, loss=0.052711, elapsed=6.9min]

Entraînement:  22%|██▏       | 2156/10000 [06:55<24:49,  5.27step/s, loss=0.061756, elapsed=6.9min]

Entraînement:  22%|██▏       | 2157/10000 [06:55<24:47,  5.27step/s, loss=0.061756, elapsed=6.9min]

Entraînement:  22%|██▏       | 2157/10000 [06:55<24:47,  5.27step/s, loss=0.054415, elapsed=6.9min]

Entraînement:  22%|██▏       | 2158/10000 [06:55<24:47,  5.27step/s, loss=0.054415, elapsed=6.9min]

Entraînement:  22%|██▏       | 2158/10000 [06:55<24:47,  5.27step/s, loss=0.031602, elapsed=6.9min]

Entraînement:  22%|██▏       | 2159/10000 [06:55<24:44,  5.28step/s, loss=0.031602, elapsed=6.9min]

Entraînement:  22%|██▏       | 2159/10000 [06:55<24:44,  5.28step/s, loss=0.042969, elapsed=6.9min]

Entraînement:  22%|██▏       | 2160/10000 [06:56<24:47,  5.27step/s, loss=0.042969, elapsed=6.9min]

Entraînement:  22%|██▏       | 2160/10000 [06:56<24:47,  5.27step/s, loss=0.050028, elapsed=6.9min]

Entraînement:  22%|██▏       | 2161/10000 [06:56<24:47,  5.27step/s, loss=0.050028, elapsed=6.9min]

Entraînement:  22%|██▏       | 2161/10000 [06:56<24:47,  5.27step/s, loss=0.047826, elapsed=6.9min]

Entraînement:  22%|██▏       | 2162/10000 [06:56<24:45,  5.28step/s, loss=0.047826, elapsed=6.9min]

Entraînement:  22%|██▏       | 2162/10000 [06:56<24:45,  5.28step/s, loss=0.029075, elapsed=6.9min]

Entraînement:  22%|██▏       | 2163/10000 [06:56<24:45,  5.28step/s, loss=0.029075, elapsed=6.9min]

Entraînement:  22%|██▏       | 2163/10000 [06:56<24:45,  5.28step/s, loss=0.059008, elapsed=6.9min]

Entraînement:  22%|██▏       | 2164/10000 [06:56<24:45,  5.28step/s, loss=0.059008, elapsed=6.9min]

Entraînement:  22%|██▏       | 2164/10000 [06:56<24:45,  5.28step/s, loss=0.027953, elapsed=6.9min]

Entraînement:  22%|██▏       | 2165/10000 [06:57<24:44,  5.28step/s, loss=0.027953, elapsed=6.9min]

Entraînement:  22%|██▏       | 2165/10000 [06:57<24:44,  5.28step/s, loss=0.095721, elapsed=7.0min]

Entraînement:  22%|██▏       | 2166/10000 [06:57<24:43,  5.28step/s, loss=0.095721, elapsed=7.0min]

Entraînement:  22%|██▏       | 2166/10000 [06:57<24:43,  5.28step/s, loss=0.103256, elapsed=7.0min]

Entraînement:  22%|██▏       | 2167/10000 [06:57<24:41,  5.29step/s, loss=0.103256, elapsed=7.0min]

Entraînement:  22%|██▏       | 2167/10000 [06:57<24:41,  5.29step/s, loss=0.037436, elapsed=7.0min]

Entraînement:  22%|██▏       | 2168/10000 [06:57<24:45,  5.27step/s, loss=0.037436, elapsed=7.0min]

Entraînement:  22%|██▏       | 2168/10000 [06:57<24:45,  5.27step/s, loss=0.043040, elapsed=7.0min]

Entraînement:  22%|██▏       | 2169/10000 [06:57<24:44,  5.28step/s, loss=0.043040, elapsed=7.0min]

Entraînement:  22%|██▏       | 2169/10000 [06:57<24:44,  5.28step/s, loss=0.082713, elapsed=7.0min]

Entraînement:  22%|██▏       | 2170/10000 [06:57<24:46,  5.27step/s, loss=0.082713, elapsed=7.0min]

Entraînement:  22%|██▏       | 2170/10000 [06:57<24:46,  5.27step/s, loss=0.106684, elapsed=7.0min]

Entraînement:  22%|██▏       | 2171/10000 [06:58<24:45,  5.27step/s, loss=0.106684, elapsed=7.0min]

Entraînement:  22%|██▏       | 2171/10000 [06:58<24:45,  5.27step/s, loss=0.019552, elapsed=7.0min]

Entraînement:  22%|██▏       | 2172/10000 [06:58<24:47,  5.26step/s, loss=0.019552, elapsed=7.0min]

Entraînement:  22%|██▏       | 2172/10000 [06:58<24:47,  5.26step/s, loss=0.041017, elapsed=7.0min]

Entraînement:  22%|██▏       | 2173/10000 [06:58<24:50,  5.25step/s, loss=0.041017, elapsed=7.0min]

Entraînement:  22%|██▏       | 2173/10000 [06:58<24:50,  5.25step/s, loss=0.046171, elapsed=7.0min]

Entraînement:  22%|██▏       | 2174/10000 [06:58<24:51,  5.25step/s, loss=0.046171, elapsed=7.0min]

Entraînement:  22%|██▏       | 2174/10000 [06:58<24:51,  5.25step/s, loss=0.080385, elapsed=7.0min]

Entraînement:  22%|██▏       | 2175/10000 [06:58<24:49,  5.25step/s, loss=0.080385, elapsed=7.0min]

Entraînement:  22%|██▏       | 2175/10000 [06:58<24:49,  5.25step/s, loss=0.118265, elapsed=7.0min]

Entraînement:  22%|██▏       | 2176/10000 [06:59<24:51,  5.25step/s, loss=0.118265, elapsed=7.0min]

Entraînement:  22%|██▏       | 2176/10000 [06:59<24:51,  5.25step/s, loss=0.046173, elapsed=7.0min]

Entraînement:  22%|██▏       | 2177/10000 [06:59<24:42,  5.28step/s, loss=0.046173, elapsed=7.0min]

Entraînement:  22%|██▏       | 2177/10000 [06:59<24:42,  5.28step/s, loss=0.079536, elapsed=7.0min]

Entraînement:  22%|██▏       | 2178/10000 [06:59<24:33,  5.31step/s, loss=0.079536, elapsed=7.0min]

Entraînement:  22%|██▏       | 2178/10000 [06:59<24:33,  5.31step/s, loss=0.038983, elapsed=7.0min]

Entraînement:  22%|██▏       | 2179/10000 [06:59<24:30,  5.32step/s, loss=0.038983, elapsed=7.0min]

Entraînement:  22%|██▏       | 2179/10000 [06:59<24:30,  5.32step/s, loss=0.064114, elapsed=7.0min]

Entraînement:  22%|██▏       | 2180/10000 [06:59<24:28,  5.33step/s, loss=0.064114, elapsed=7.0min]

Entraînement:  22%|██▏       | 2180/10000 [06:59<24:28,  5.33step/s, loss=0.142965, elapsed=7.0min]

Entraînement:  22%|██▏       | 2181/10000 [07:00<24:23,  5.34step/s, loss=0.142965, elapsed=7.0min]

Entraînement:  22%|██▏       | 2181/10000 [07:00<24:23,  5.34step/s, loss=0.061908, elapsed=7.0min]

Entraînement:  22%|██▏       | 2182/10000 [07:00<24:19,  5.36step/s, loss=0.061908, elapsed=7.0min]

Entraînement:  22%|██▏       | 2182/10000 [07:00<24:19,  5.36step/s, loss=0.060118, elapsed=7.0min]

Entraînement:  22%|██▏       | 2183/10000 [07:00<24:26,  5.33step/s, loss=0.060118, elapsed=7.0min]

Entraînement:  22%|██▏       | 2183/10000 [07:00<24:26,  5.33step/s, loss=0.145151, elapsed=7.0min]

Entraînement:  22%|██▏       | 2184/10000 [07:00<24:32,  5.31step/s, loss=0.145151, elapsed=7.0min]

Entraînement:  22%|██▏       | 2184/10000 [07:00<24:32,  5.31step/s, loss=0.036814, elapsed=7.0min]

Entraînement:  22%|██▏       | 2185/10000 [07:00<24:34,  5.30step/s, loss=0.036814, elapsed=7.0min]

Entraînement:  22%|██▏       | 2185/10000 [07:00<24:34,  5.30step/s, loss=0.053851, elapsed=7.0min]

Entraînement:  22%|██▏       | 2186/10000 [07:00<24:41,  5.28step/s, loss=0.053851, elapsed=7.0min]

Entraînement:  22%|██▏       | 2186/10000 [07:00<24:41,  5.28step/s, loss=0.052184, elapsed=7.0min]

Entraînement:  22%|██▏       | 2187/10000 [07:01<24:38,  5.28step/s, loss=0.052184, elapsed=7.0min]

Entraînement:  22%|██▏       | 2187/10000 [07:01<24:38,  5.28step/s, loss=0.039595, elapsed=7.0min]

Entraînement:  22%|██▏       | 2188/10000 [07:01<24:38,  5.28step/s, loss=0.039595, elapsed=7.0min]

Entraînement:  22%|██▏       | 2188/10000 [07:01<24:38,  5.28step/s, loss=0.057188, elapsed=7.0min]

Entraînement:  22%|██▏       | 2189/10000 [07:01<24:37,  5.29step/s, loss=0.057188, elapsed=7.0min]

Entraînement:  22%|██▏       | 2189/10000 [07:01<24:37,  5.29step/s, loss=0.066771, elapsed=7.0min]

Entraînement:  22%|██▏       | 2190/10000 [07:01<24:35,  5.29step/s, loss=0.066771, elapsed=7.0min]

Entraînement:  22%|██▏       | 2190/10000 [07:01<24:35,  5.29step/s, loss=0.127312, elapsed=7.0min]

Entraînement:  22%|██▏       | 2191/10000 [07:01<24:37,  5.29step/s, loss=0.127312, elapsed=7.0min]

Entraînement:  22%|██▏       | 2191/10000 [07:01<24:37,  5.29step/s, loss=0.055839, elapsed=7.0min]

Entraînement:  22%|██▏       | 2192/10000 [07:02<24:39,  5.28step/s, loss=0.055839, elapsed=7.0min]

Entraînement:  22%|██▏       | 2192/10000 [07:02<24:39,  5.28step/s, loss=0.047564, elapsed=7.0min]

Entraînement:  22%|██▏       | 2193/10000 [07:02<24:41,  5.27step/s, loss=0.047564, elapsed=7.0min]

Entraînement:  22%|██▏       | 2193/10000 [07:02<24:41,  5.27step/s, loss=0.065325, elapsed=7.0min]

Entraînement:  22%|██▏       | 2194/10000 [07:02<24:39,  5.28step/s, loss=0.065325, elapsed=7.0min]

Entraînement:  22%|██▏       | 2194/10000 [07:02<24:39,  5.28step/s, loss=0.106802, elapsed=7.0min]

Entraînement:  22%|██▏       | 2195/10000 [07:02<24:41,  5.27step/s, loss=0.106802, elapsed=7.0min]

Entraînement:  22%|██▏       | 2195/10000 [07:02<24:41,  5.27step/s, loss=0.047938, elapsed=7.0min]

Entraînement:  22%|██▏       | 2196/10000 [07:02<24:40,  5.27step/s, loss=0.047938, elapsed=7.0min]

Entraînement:  22%|██▏       | 2196/10000 [07:02<24:40,  5.27step/s, loss=0.081941, elapsed=7.0min]

Entraînement:  22%|██▏       | 2197/10000 [07:03<24:39,  5.27step/s, loss=0.081941, elapsed=7.0min]

Entraînement:  22%|██▏       | 2197/10000 [07:03<24:39,  5.27step/s, loss=0.062662, elapsed=7.1min]

Entraînement:  22%|██▏       | 2198/10000 [07:03<24:38,  5.28step/s, loss=0.062662, elapsed=7.1min]

Entraînement:  22%|██▏       | 2198/10000 [07:03<24:38,  5.28step/s, loss=0.046664, elapsed=7.1min]

Entraînement:  22%|██▏       | 2199/10000 [07:03<24:37,  5.28step/s, loss=0.046664, elapsed=7.1min]

Entraînement:  22%|██▏       | 2199/10000 [07:03<24:37,  5.28step/s, loss=0.032407, elapsed=7.1min]

Entraînement:  22%|██▏       | 2200/10000 [07:03<24:39,  5.27step/s, loss=0.032407, elapsed=7.1min]

Entraînement:  22%|██▏       | 2200/10000 [07:03<24:39,  5.27step/s, loss=0.045250, elapsed=7.1min]

Entraînement:  22%|██▏       | 2200/10000 [07:03<24:39,  5.27step/s, loss=0.045250, elapsed=7.1min]

Entraînement:  22%|██▏       | 2201/10000 [07:03<24:55,  5.21step/s, loss=0.045250, elapsed=7.1min]

Entraînement:  22%|██▏       | 2201/10000 [07:03<24:55,  5.21step/s, loss=0.079201, elapsed=7.1min]

Step 2200/10000 | Train loss: 0.045250 | Elapsed: 7.1min | ETA: 25.0min

Entraînement:  22%|██▏       | 2202/10000 [07:04<24:49,  5.24step/s, loss=0.079201, elapsed=7.1min]

Entraînement:  22%|██▏       | 2202/10000 [07:04<24:49,  5.24step/s, loss=0.106819, elapsed=7.1min]

Entraînement:  22%|██▏       | 2203/10000 [07:04<24:45,  5.25step/s, loss=0.106819, elapsed=7.1min]

Entraînement:  22%|██▏       | 2203/10000 [07:04<24:45,  5.25step/s, loss=0.034156, elapsed=7.1min]

Entraînement:  22%|██▏       | 2204/10000 [07:04<24:37,  5.28step/s, loss=0.034156, elapsed=7.1min]

Entraînement:  22%|██▏       | 2204/10000 [07:04<24:37,  5.28step/s, loss=0.061705, elapsed=7.1min]

Entraînement:  22%|██▏       | 2205/10000 [07:04<24:26,  5.32step/s, loss=0.061705, elapsed=7.1min]

Entraînement:  22%|██▏       | 2205/10000 [07:04<24:26,  5.32step/s, loss=0.030107, elapsed=7.1min]

Entraînement:  22%|██▏       | 2206/10000 [07:04<24:18,  5.34step/s, loss=0.030107, elapsed=7.1min]

Entraînement:  22%|██▏       | 2206/10000 [07:04<24:18,  5.34step/s, loss=0.039830, elapsed=7.1min]

Entraînement:  22%|██▏       | 2207/10000 [07:04<24:15,  5.35step/s, loss=0.039830, elapsed=7.1min]

Entraînement:  22%|██▏       | 2207/10000 [07:04<24:15,  5.35step/s, loss=0.037776, elapsed=7.1min]

Entraînement:  22%|██▏       | 2208/10000 [07:05<24:18,  5.34step/s, loss=0.037776, elapsed=7.1min]

Entraînement:  22%|██▏       | 2208/10000 [07:05<24:18,  5.34step/s, loss=0.038381, elapsed=7.1min]

Entraînement:  22%|██▏       | 2209/10000 [07:05<24:13,  5.36step/s, loss=0.038381, elapsed=7.1min]

Entraînement:  22%|██▏       | 2209/10000 [07:05<24:13,  5.36step/s, loss=0.051511, elapsed=7.1min]

Entraînement:  22%|██▏       | 2210/10000 [07:05<24:09,  5.37step/s, loss=0.051511, elapsed=7.1min]

Entraînement:  22%|██▏       | 2210/10000 [07:05<24:09,  5.37step/s, loss=0.050947, elapsed=7.1min]

Entraînement:  22%|██▏       | 2211/10000 [07:05<24:15,  5.35step/s, loss=0.050947, elapsed=7.1min]

Entraînement:  22%|██▏       | 2211/10000 [07:05<24:15,  5.35step/s, loss=0.040198, elapsed=7.1min]

Entraînement:  22%|██▏       | 2212/10000 [07:05<24:21,  5.33step/s, loss=0.040198, elapsed=7.1min]

Entraînement:  22%|██▏       | 2212/10000 [07:05<24:21,  5.33step/s, loss=0.031946, elapsed=7.1min]

Entraînement:  22%|██▏       | 2213/10000 [07:06<24:24,  5.32step/s, loss=0.031946, elapsed=7.1min]

Entraînement:  22%|██▏       | 2213/10000 [07:06<24:24,  5.32step/s, loss=0.024581, elapsed=7.1min]

Entraînement:  22%|██▏       | 2214/10000 [07:06<24:27,  5.30step/s, loss=0.024581, elapsed=7.1min]

Entraînement:  22%|██▏       | 2214/10000 [07:06<24:27,  5.30step/s, loss=0.037457, elapsed=7.1min]

Entraînement:  22%|██▏       | 2215/10000 [07:06<24:31,  5.29step/s, loss=0.037457, elapsed=7.1min]

Entraînement:  22%|██▏       | 2215/10000 [07:06<24:31,  5.29step/s, loss=0.145304, elapsed=7.1min]

Entraînement:  22%|██▏       | 2216/10000 [07:06<24:37,  5.27step/s, loss=0.145304, elapsed=7.1min]

Entraînement:  22%|██▏       | 2216/10000 [07:06<24:37,  5.27step/s, loss=0.122321, elapsed=7.1min]

Entraînement:  22%|██▏       | 2217/10000 [07:06<24:34,  5.28step/s, loss=0.122321, elapsed=7.1min]

Entraînement:  22%|██▏       | 2217/10000 [07:06<24:34,  5.28step/s, loss=0.055500, elapsed=7.1min]

Entraînement:  22%|██▏       | 2218/10000 [07:07<24:36,  5.27step/s, loss=0.055500, elapsed=7.1min]

Entraînement:  22%|██▏       | 2218/10000 [07:07<24:36,  5.27step/s, loss=0.053834, elapsed=7.1min]

Entraînement:  22%|██▏       | 2219/10000 [07:07<24:34,  5.28step/s, loss=0.053834, elapsed=7.1min]

Entraînement:  22%|██▏       | 2219/10000 [07:07<24:34,  5.28step/s, loss=0.055643, elapsed=7.1min]

Entraînement:  22%|██▏       | 2220/10000 [07:07<24:33,  5.28step/s, loss=0.055643, elapsed=7.1min]

Entraînement:  22%|██▏       | 2220/10000 [07:07<24:33,  5.28step/s, loss=0.038664, elapsed=7.1min]

Entraînement:  22%|██▏       | 2221/10000 [07:07<24:33,  5.28step/s, loss=0.038664, elapsed=7.1min]

Entraînement:  22%|██▏       | 2221/10000 [07:07<24:33,  5.28step/s, loss=0.037961, elapsed=7.1min]

Entraînement:  22%|██▏       | 2222/10000 [07:07<24:31,  5.29step/s, loss=0.037961, elapsed=7.1min]

Entraînement:  22%|██▏       | 2222/10000 [07:07<24:31,  5.29step/s, loss=0.086178, elapsed=7.1min]

Entraînement:  22%|██▏       | 2223/10000 [07:07<24:35,  5.27step/s, loss=0.086178, elapsed=7.1min]

Entraînement:  22%|██▏       | 2223/10000 [07:07<24:35,  5.27step/s, loss=0.054580, elapsed=7.1min]

Entraînement:  22%|██▏       | 2224/10000 [07:08<24:36,  5.27step/s, loss=0.054580, elapsed=7.1min]

Entraînement:  22%|██▏       | 2224/10000 [07:08<24:36,  5.27step/s, loss=0.046519, elapsed=7.1min]

Entraînement:  22%|██▏       | 2225/10000 [07:08<24:37,  5.26step/s, loss=0.046519, elapsed=7.1min]

Entraînement:  22%|██▏       | 2225/10000 [07:08<24:37,  5.26step/s, loss=0.062561, elapsed=7.1min]

Entraînement:  22%|██▏       | 2226/10000 [07:08<24:34,  5.27step/s, loss=0.062561, elapsed=7.1min]

Entraînement:  22%|██▏       | 2226/10000 [07:08<24:34,  5.27step/s, loss=0.038234, elapsed=7.1min]

Entraînement:  22%|██▏       | 2227/10000 [07:08<24:37,  5.26step/s, loss=0.038234, elapsed=7.1min]

Entraînement:  22%|██▏       | 2227/10000 [07:08<24:37,  5.26step/s, loss=0.063337, elapsed=7.1min]

Entraînement:  22%|██▏       | 2228/10000 [07:08<24:35,  5.27step/s, loss=0.063337, elapsed=7.1min]

Entraînement:  22%|██▏       | 2228/10000 [07:08<24:35,  5.27step/s, loss=0.088835, elapsed=7.1min]

Entraînement:  22%|██▏       | 2229/10000 [07:09<24:35,  5.27step/s, loss=0.088835, elapsed=7.1min]

Entraînement:  22%|██▏       | 2229/10000 [07:09<24:35,  5.27step/s, loss=0.029074, elapsed=7.2min]

Entraînement:  22%|██▏       | 2230/10000 [07:09<24:35,  5.26step/s, loss=0.029074, elapsed=7.2min]

Entraînement:  22%|██▏       | 2230/10000 [07:09<24:35,  5.26step/s, loss=0.098487, elapsed=7.2min]

Entraînement:  22%|██▏       | 2231/10000 [07:09<24:38,  5.26step/s, loss=0.098487, elapsed=7.2min]

Entraînement:  22%|██▏       | 2231/10000 [07:09<24:38,  5.26step/s, loss=0.027812, elapsed=7.2min]

Entraînement:  22%|██▏       | 2232/10000 [07:09<24:37,  5.26step/s, loss=0.027812, elapsed=7.2min]

Entraînement:  22%|██▏       | 2232/10000 [07:09<24:37,  5.26step/s, loss=0.121665, elapsed=7.2min]

Entraînement:  22%|██▏       | 2233/10000 [07:09<24:38,  5.25step/s, loss=0.121665, elapsed=7.2min]

Entraînement:  22%|██▏       | 2233/10000 [07:09<24:38,  5.25step/s, loss=0.073739, elapsed=7.2min]

Entraînement:  22%|██▏       | 2234/10000 [07:10<24:32,  5.27step/s, loss=0.073739, elapsed=7.2min]

Entraînement:  22%|██▏       | 2234/10000 [07:10<24:32,  5.27step/s, loss=0.104758, elapsed=7.2min]

Entraînement:  22%|██▏       | 2235/10000 [07:10<24:34,  5.27step/s, loss=0.104758, elapsed=7.2min]

Entraînement:  22%|██▏       | 2235/10000 [07:10<24:34,  5.27step/s, loss=0.128339, elapsed=7.2min]

Entraînement:  22%|██▏       | 2236/10000 [07:10<24:34,  5.27step/s, loss=0.128339, elapsed=7.2min]

Entraînement:  22%|██▏       | 2236/10000 [07:10<24:34,  5.27step/s, loss=0.124457, elapsed=7.2min]

Entraînement:  22%|██▏       | 2237/10000 [07:10<24:34,  5.27step/s, loss=0.124457, elapsed=7.2min]

Entraînement:  22%|██▏       | 2237/10000 [07:10<24:34,  5.27step/s, loss=0.062389, elapsed=7.2min]

Entraînement:  22%|██▏       | 2238/10000 [07:10<24:30,  5.28step/s, loss=0.062389, elapsed=7.2min]

Entraînement:  22%|██▏       | 2238/10000 [07:10<24:30,  5.28step/s, loss=0.047534, elapsed=7.2min]

Entraînement:  22%|██▏       | 2239/10000 [07:11<24:30,  5.28step/s, loss=0.047534, elapsed=7.2min]

Entraînement:  22%|██▏       | 2239/10000 [07:11<24:30,  5.28step/s, loss=0.092813, elapsed=7.2min]

Entraînement:  22%|██▏       | 2240/10000 [07:11<24:31,  5.28step/s, loss=0.092813, elapsed=7.2min]

Entraînement:  22%|██▏       | 2240/10000 [07:11<24:31,  5.28step/s, loss=0.032989, elapsed=7.2min]

Entraînement:  22%|██▏       | 2241/10000 [07:11<24:29,  5.28step/s, loss=0.032989, elapsed=7.2min]

Entraînement:  22%|██▏       | 2241/10000 [07:11<24:29,  5.28step/s, loss=0.073165, elapsed=7.2min]

Entraînement:  22%|██▏       | 2242/10000 [07:11<24:29,  5.28step/s, loss=0.073165, elapsed=7.2min]

Entraînement:  22%|██▏       | 2242/10000 [07:11<24:29,  5.28step/s, loss=0.065573, elapsed=7.2min]

Entraînement:  22%|██▏       | 2243/10000 [07:11<24:30,  5.28step/s, loss=0.065573, elapsed=7.2min]

Entraînement:  22%|██▏       | 2243/10000 [07:11<24:30,  5.28step/s, loss=0.059762, elapsed=7.2min]

Entraînement:  22%|██▏       | 2244/10000 [07:11<24:31,  5.27step/s, loss=0.059762, elapsed=7.2min]

Entraînement:  22%|██▏       | 2244/10000 [07:11<24:31,  5.27step/s, loss=0.073523, elapsed=7.2min]

Entraînement:  22%|██▏       | 2245/10000 [07:12<24:30,  5.27step/s, loss=0.073523, elapsed=7.2min]

Entraînement:  22%|██▏       | 2245/10000 [07:12<24:30,  5.27step/s, loss=0.063665, elapsed=7.2min]

Entraînement:  22%|██▏       | 2246/10000 [07:12<24:27,  5.29step/s, loss=0.063665, elapsed=7.2min]

Entraînement:  22%|██▏       | 2246/10000 [07:12<24:27,  5.29step/s, loss=0.042854, elapsed=7.2min]

Entraînement:  22%|██▏       | 2247/10000 [07:12<24:30,  5.27step/s, loss=0.042854, elapsed=7.2min]

Entraînement:  22%|██▏       | 2247/10000 [07:12<24:30,  5.27step/s, loss=0.068413, elapsed=7.2min]

Entraînement:  22%|██▏       | 2248/10000 [07:12<24:27,  5.28step/s, loss=0.068413, elapsed=7.2min]

Entraînement:  22%|██▏       | 2248/10000 [07:12<24:27,  5.28step/s, loss=0.069459, elapsed=7.2min]

Entraînement:  22%|██▏       | 2249/10000 [07:12<24:28,  5.28step/s, loss=0.069459, elapsed=7.2min]

Entraînement:  22%|██▏       | 2249/10000 [07:12<24:28,  5.28step/s, loss=0.059159, elapsed=7.2min]

Entraînement:  22%|██▎       | 2250/10000 [07:13<24:24,  5.29step/s, loss=0.059159, elapsed=7.2min]

Entraînement:  22%|██▎       | 2250/10000 [07:13<24:24,  5.29step/s, loss=0.202143, elapsed=7.2min]

Entraînement:  23%|██▎       | 2251/10000 [07:13<24:21,  5.30step/s, loss=0.202143, elapsed=7.2min]

Entraînement:  23%|██▎       | 2251/10000 [07:13<24:21,  5.30step/s, loss=0.080882, elapsed=7.2min]

Entraînement:  23%|██▎       | 2252/10000 [07:13<24:21,  5.30step/s, loss=0.080882, elapsed=7.2min]

Entraînement:  23%|██▎       | 2252/10000 [07:13<24:21,  5.30step/s, loss=0.034626, elapsed=7.2min]

Entraînement:  23%|██▎       | 2253/10000 [07:13<24:24,  5.29step/s, loss=0.034626, elapsed=7.2min]

Entraînement:  23%|██▎       | 2253/10000 [07:13<24:24,  5.29step/s, loss=0.081089, elapsed=7.2min]

Entraînement:  23%|██▎       | 2254/10000 [07:13<24:21,  5.30step/s, loss=0.081089, elapsed=7.2min]

Entraînement:  23%|██▎       | 2254/10000 [07:13<24:21,  5.30step/s, loss=0.074213, elapsed=7.2min]

Entraînement:  23%|██▎       | 2255/10000 [07:14<24:25,  5.28step/s, loss=0.074213, elapsed=7.2min]

Entraînement:  23%|██▎       | 2255/10000 [07:14<24:25,  5.28step/s, loss=0.052457, elapsed=7.2min]

Entraînement:  23%|██▎       | 2256/10000 [07:14<24:27,  5.28step/s, loss=0.052457, elapsed=7.2min]

Entraînement:  23%|██▎       | 2256/10000 [07:14<24:27,  5.28step/s, loss=0.060690, elapsed=7.2min]

Entraînement:  23%|██▎       | 2257/10000 [07:14<24:23,  5.29step/s, loss=0.060690, elapsed=7.2min]

Entraînement:  23%|██▎       | 2257/10000 [07:14<24:23,  5.29step/s, loss=0.040346, elapsed=7.2min]

Entraînement:  23%|██▎       | 2258/10000 [07:14<24:25,  5.28step/s, loss=0.040346, elapsed=7.2min]

Entraînement:  23%|██▎       | 2258/10000 [07:14<24:25,  5.28step/s, loss=0.061337, elapsed=7.2min]

Entraînement:  23%|██▎       | 2259/10000 [07:14<24:24,  5.29step/s, loss=0.061337, elapsed=7.2min]

Entraînement:  23%|██▎       | 2259/10000 [07:14<24:24,  5.29step/s, loss=0.068362, elapsed=7.2min]

Entraînement:  23%|██▎       | 2260/10000 [07:14<24:21,  5.30step/s, loss=0.068362, elapsed=7.2min]

Entraînement:  23%|██▎       | 2260/10000 [07:14<24:21,  5.30step/s, loss=0.069976, elapsed=7.2min]

Entraînement:  23%|██▎       | 2261/10000 [07:15<24:20,  5.30step/s, loss=0.069976, elapsed=7.2min]

Entraînement:  23%|██▎       | 2261/10000 [07:15<24:20,  5.30step/s, loss=0.053199, elapsed=7.3min]

Entraînement:  23%|██▎       | 2262/10000 [07:15<24:17,  5.31step/s, loss=0.053199, elapsed=7.3min]

Entraînement:  23%|██▎       | 2262/10000 [07:15<24:17,  5.31step/s, loss=0.108769, elapsed=7.3min]

Entraînement:  23%|██▎       | 2263/10000 [07:15<24:17,  5.31step/s, loss=0.108769, elapsed=7.3min]

Entraînement:  23%|██▎       | 2263/10000 [07:15<24:17,  5.31step/s, loss=0.091522, elapsed=7.3min]

Entraînement:  23%|██▎       | 2264/10000 [07:15<24:21,  5.29step/s, loss=0.091522, elapsed=7.3min]

Entraînement:  23%|██▎       | 2264/10000 [07:15<24:21,  5.29step/s, loss=0.069752, elapsed=7.3min]

Entraînement:  23%|██▎       | 2265/10000 [07:15<24:20,  5.30step/s, loss=0.069752, elapsed=7.3min]

Entraînement:  23%|██▎       | 2265/10000 [07:15<24:20,  5.30step/s, loss=0.065631, elapsed=7.3min]

Entraînement:  23%|██▎       | 2266/10000 [07:16<24:15,  5.31step/s, loss=0.065631, elapsed=7.3min]

Entraînement:  23%|██▎       | 2266/10000 [07:16<24:15,  5.31step/s, loss=0.061148, elapsed=7.3min]

Entraînement:  23%|██▎       | 2267/10000 [07:16<24:17,  5.30step/s, loss=0.061148, elapsed=7.3min]

Entraînement:  23%|██▎       | 2267/10000 [07:16<24:17,  5.30step/s, loss=0.070997, elapsed=7.3min]

Entraînement:  23%|██▎       | 2268/10000 [07:16<24:19,  5.30step/s, loss=0.070997, elapsed=7.3min]

Entraînement:  23%|██▎       | 2268/10000 [07:16<24:19,  5.30step/s, loss=0.070764, elapsed=7.3min]

Entraînement:  23%|██▎       | 2269/10000 [07:16<24:18,  5.30step/s, loss=0.070764, elapsed=7.3min]

Entraînement:  23%|██▎       | 2269/10000 [07:16<24:18,  5.30step/s, loss=0.063927, elapsed=7.3min]

Entraînement:  23%|██▎       | 2270/10000 [07:16<24:15,  5.31step/s, loss=0.063927, elapsed=7.3min]

Entraînement:  23%|██▎       | 2270/10000 [07:16<24:15,  5.31step/s, loss=0.150996, elapsed=7.3min]

Entraînement:  23%|██▎       | 2271/10000 [07:17<24:16,  5.30step/s, loss=0.150996, elapsed=7.3min]

Entraînement:  23%|██▎       | 2271/10000 [07:17<24:16,  5.30step/s, loss=0.054954, elapsed=7.3min]

Entraînement:  23%|██▎       | 2272/10000 [07:17<24:18,  5.30step/s, loss=0.054954, elapsed=7.3min]

Entraînement:  23%|██▎       | 2272/10000 [07:17<24:18,  5.30step/s, loss=0.085711, elapsed=7.3min]

Entraînement:  23%|██▎       | 2273/10000 [07:17<24:19,  5.29step/s, loss=0.085711, elapsed=7.3min]

Entraînement:  23%|██▎       | 2273/10000 [07:17<24:19,  5.29step/s, loss=0.034681, elapsed=7.3min]

Entraînement:  23%|██▎       | 2274/10000 [07:17<24:14,  5.31step/s, loss=0.034681, elapsed=7.3min]

Entraînement:  23%|██▎       | 2274/10000 [07:17<24:14,  5.31step/s, loss=0.083952, elapsed=7.3min]

Entraînement:  23%|██▎       | 2275/10000 [07:17<24:18,  5.30step/s, loss=0.083952, elapsed=7.3min]

Entraînement:  23%|██▎       | 2275/10000 [07:17<24:18,  5.30step/s, loss=0.079891, elapsed=7.3min]

Entraînement:  23%|██▎       | 2276/10000 [07:17<24:20,  5.29step/s, loss=0.079891, elapsed=7.3min]

Entraînement:  23%|██▎       | 2276/10000 [07:17<24:20,  5.29step/s, loss=0.066375, elapsed=7.3min]

Entraînement:  23%|██▎       | 2277/10000 [07:18<24:21,  5.28step/s, loss=0.066375, elapsed=7.3min]

Entraînement:  23%|██▎       | 2277/10000 [07:18<24:21,  5.28step/s, loss=0.057892, elapsed=7.3min]

Entraînement:  23%|██▎       | 2278/10000 [07:18<24:19,  5.29step/s, loss=0.057892, elapsed=7.3min]

Entraînement:  23%|██▎       | 2278/10000 [07:18<24:19,  5.29step/s, loss=0.045109, elapsed=7.3min]

Entraînement:  23%|██▎       | 2279/10000 [07:18<24:20,  5.29step/s, loss=0.045109, elapsed=7.3min]

Entraînement:  23%|██▎       | 2279/10000 [07:18<24:20,  5.29step/s, loss=0.027151, elapsed=7.3min]

Entraînement:  23%|██▎       | 2280/10000 [07:18<24:22,  5.28step/s, loss=0.027151, elapsed=7.3min]

Entraînement:  23%|██▎       | 2280/10000 [07:18<24:22,  5.28step/s, loss=0.025249, elapsed=7.3min]

Entraînement:  23%|██▎       | 2281/10000 [07:18<24:22,  5.28step/s, loss=0.025249, elapsed=7.3min]

Entraînement:  23%|██▎       | 2281/10000 [07:18<24:22,  5.28step/s, loss=0.056270, elapsed=7.3min]

Entraînement:  23%|██▎       | 2282/10000 [07:19<24:23,  5.27step/s, loss=0.056270, elapsed=7.3min]

Entraînement:  23%|██▎       | 2282/10000 [07:19<24:23,  5.27step/s, loss=0.066782, elapsed=7.3min]

Entraînement:  23%|██▎       | 2283/10000 [07:19<24:23,  5.27step/s, loss=0.066782, elapsed=7.3min]

Entraînement:  23%|██▎       | 2283/10000 [07:19<24:23,  5.27step/s, loss=0.059962, elapsed=7.3min]

Entraînement:  23%|██▎       | 2284/10000 [07:19<24:23,  5.27step/s, loss=0.059962, elapsed=7.3min]

Entraînement:  23%|██▎       | 2284/10000 [07:19<24:23,  5.27step/s, loss=0.068341, elapsed=7.3min]

Entraînement:  23%|██▎       | 2285/10000 [07:19<24:22,  5.27step/s, loss=0.068341, elapsed=7.3min]

Entraînement:  23%|██▎       | 2285/10000 [07:19<24:22,  5.27step/s, loss=0.038599, elapsed=7.3min]

Entraînement:  23%|██▎       | 2286/10000 [07:19<24:23,  5.27step/s, loss=0.038599, elapsed=7.3min]

Entraînement:  23%|██▎       | 2286/10000 [07:19<24:23,  5.27step/s, loss=0.076306, elapsed=7.3min]

Entraînement:  23%|██▎       | 2287/10000 [07:20<24:23,  5.27step/s, loss=0.076306, elapsed=7.3min]

Entraînement:  23%|██▎       | 2287/10000 [07:20<24:23,  5.27step/s, loss=0.068029, elapsed=7.3min]

Entraînement:  23%|██▎       | 2288/10000 [07:20<24:23,  5.27step/s, loss=0.068029, elapsed=7.3min]

Entraînement:  23%|██▎       | 2288/10000 [07:20<24:23,  5.27step/s, loss=0.022926, elapsed=7.3min]

Entraînement:  23%|██▎       | 2289/10000 [07:20<24:21,  5.27step/s, loss=0.022926, elapsed=7.3min]

Entraînement:  23%|██▎       | 2289/10000 [07:20<24:21,  5.27step/s, loss=0.061831, elapsed=7.3min]

Entraînement:  23%|██▎       | 2290/10000 [07:20<24:24,  5.26step/s, loss=0.061831, elapsed=7.3min]

Entraînement:  23%|██▎       | 2290/10000 [07:20<24:24,  5.26step/s, loss=0.034245, elapsed=7.3min]

Entraînement:  23%|██▎       | 2291/10000 [07:20<24:26,  5.26step/s, loss=0.034245, elapsed=7.3min]

Entraînement:  23%|██▎       | 2291/10000 [07:20<24:26,  5.26step/s, loss=0.037759, elapsed=7.3min]

Entraînement:  23%|██▎       | 2292/10000 [07:21<24:23,  5.27step/s, loss=0.037759, elapsed=7.3min]

Entraînement:  23%|██▎       | 2292/10000 [07:21<24:23,  5.27step/s, loss=0.086353, elapsed=7.4min]

Entraînement:  23%|██▎       | 2293/10000 [07:21<24:24,  5.26step/s, loss=0.086353, elapsed=7.4min]

Entraînement:  23%|██▎       | 2293/10000 [07:21<24:24,  5.26step/s, loss=0.039932, elapsed=7.4min]

Entraînement:  23%|██▎       | 2294/10000 [07:21<24:21,  5.27step/s, loss=0.039932, elapsed=7.4min]

Entraînement:  23%|██▎       | 2294/10000 [07:21<24:21,  5.27step/s, loss=0.033004, elapsed=7.4min]

Entraînement:  23%|██▎       | 2295/10000 [07:21<24:20,  5.28step/s, loss=0.033004, elapsed=7.4min]

Entraînement:  23%|██▎       | 2295/10000 [07:21<24:20,  5.28step/s, loss=0.063776, elapsed=7.4min]

Entraînement:  23%|██▎       | 2296/10000 [07:21<24:18,  5.28step/s, loss=0.063776, elapsed=7.4min]

Entraînement:  23%|██▎       | 2296/10000 [07:21<24:18,  5.28step/s, loss=0.038192, elapsed=7.4min]

Entraînement:  23%|██▎       | 2297/10000 [07:21<24:20,  5.27step/s, loss=0.038192, elapsed=7.4min]

Entraînement:  23%|██▎       | 2297/10000 [07:21<24:20,  5.27step/s, loss=0.052639, elapsed=7.4min]

Entraînement:  23%|██▎       | 2298/10000 [07:22<24:20,  5.27step/s, loss=0.052639, elapsed=7.4min]

Entraînement:  23%|██▎       | 2298/10000 [07:22<24:20,  5.27step/s, loss=0.094912, elapsed=7.4min]

Entraînement:  23%|██▎       | 2299/10000 [07:22<24:20,  5.27step/s, loss=0.094912, elapsed=7.4min]

Entraînement:  23%|██▎       | 2299/10000 [07:22<24:20,  5.27step/s, loss=0.041755, elapsed=7.4min]

Entraînement:  23%|██▎       | 2300/10000 [07:22<24:19,  5.28step/s, loss=0.041755, elapsed=7.4min]

Entraînement:  23%|██▎       | 2300/10000 [07:22<24:19,  5.28step/s, loss=0.040162, elapsed=7.4min]

Entraînement:  23%|██▎       | 2300/10000 [07:22<24:19,  5.28step/s, loss=0.040162, elapsed=7.4min]

Entraînement:  23%|██▎       | 2301/10000 [07:22<24:33,  5.22step/s, loss=0.040162, elapsed=7.4min]

Entraînement:  23%|██▎       | 2301/10000 [07:22<24:33,  5.22step/s, loss=0.088324, elapsed=7.4min]

Step 2300/10000 | Train loss: 0.040162 | Elapsed: 7.4min | ETA: 24.7min

Entraînement:  23%|██▎       | 2302/10000 [07:22<24:29,  5.24step/s, loss=0.088324, elapsed=7.4min]

Entraînement:  23%|██▎       | 2302/10000 [07:22<24:29,  5.24step/s, loss=0.044721, elapsed=7.4min]

Entraînement:  23%|██▎       | 2303/10000 [07:23<24:24,  5.25step/s, loss=0.044721, elapsed=7.4min]

Entraînement:  23%|██▎       | 2303/10000 [07:23<24:24,  5.25step/s, loss=0.035254, elapsed=7.4min]

Entraînement:  23%|██▎       | 2304/10000 [07:23<24:25,  5.25step/s, loss=0.035254, elapsed=7.4min]

Entraînement:  23%|██▎       | 2304/10000 [07:23<24:25,  5.25step/s, loss=0.049233, elapsed=7.4min]

Entraînement:  23%|██▎       | 2305/10000 [07:23<24:25,  5.25step/s, loss=0.049233, elapsed=7.4min]

Entraînement:  23%|██▎       | 2305/10000 [07:23<24:25,  5.25step/s, loss=0.040344, elapsed=7.4min]

Entraînement:  23%|██▎       | 2306/10000 [07:23<24:23,  5.26step/s, loss=0.040344, elapsed=7.4min]

Entraînement:  23%|██▎       | 2306/10000 [07:23<24:23,  5.26step/s, loss=0.097631, elapsed=7.4min]

Entraînement:  23%|██▎       | 2307/10000 [07:23<24:20,  5.27step/s, loss=0.097631, elapsed=7.4min]

Entraînement:  23%|██▎       | 2307/10000 [07:23<24:20,  5.27step/s, loss=0.085793, elapsed=7.4min]

Entraînement:  23%|██▎       | 2308/10000 [07:24<24:24,  5.25step/s, loss=0.085793, elapsed=7.4min]

Entraînement:  23%|██▎       | 2308/10000 [07:24<24:24,  5.25step/s, loss=0.087497, elapsed=7.4min]

Entraînement:  23%|██▎       | 2309/10000 [07:24<24:25,  5.25step/s, loss=0.087497, elapsed=7.4min]

Entraînement:  23%|██▎       | 2309/10000 [07:24<24:25,  5.25step/s, loss=0.063108, elapsed=7.4min]

Entraînement:  23%|██▎       | 2310/10000 [07:24<24:21,  5.26step/s, loss=0.063108, elapsed=7.4min]

Entraînement:  23%|██▎       | 2310/10000 [07:24<24:21,  5.26step/s, loss=0.099263, elapsed=7.4min]

Entraînement:  23%|██▎       | 2311/10000 [07:24<24:20,  5.27step/s, loss=0.099263, elapsed=7.4min]

Entraînement:  23%|██▎       | 2311/10000 [07:24<24:20,  5.27step/s, loss=0.115230, elapsed=7.4min]

Entraînement:  23%|██▎       | 2312/10000 [07:24<24:21,  5.26step/s, loss=0.115230, elapsed=7.4min]

Entraînement:  23%|██▎       | 2312/10000 [07:24<24:21,  5.26step/s, loss=0.082647, elapsed=7.4min]

Entraînement:  23%|██▎       | 2313/10000 [07:25<24:21,  5.26step/s, loss=0.082647, elapsed=7.4min]

Entraînement:  23%|██▎       | 2313/10000 [07:25<24:21,  5.26step/s, loss=0.056400, elapsed=7.4min]

Entraînement:  23%|██▎       | 2314/10000 [07:25<24:19,  5.26step/s, loss=0.056400, elapsed=7.4min]

Entraînement:  23%|██▎       | 2314/10000 [07:25<24:19,  5.26step/s, loss=0.042017, elapsed=7.4min]

Entraînement:  23%|██▎       | 2315/10000 [07:25<24:18,  5.27step/s, loss=0.042017, elapsed=7.4min]

Entraînement:  23%|██▎       | 2315/10000 [07:25<24:18,  5.27step/s, loss=0.145353, elapsed=7.4min]

Entraînement:  23%|██▎       | 2316/10000 [07:25<24:15,  5.28step/s, loss=0.145353, elapsed=7.4min]

Entraînement:  23%|██▎       | 2316/10000 [07:25<24:15,  5.28step/s, loss=0.042990, elapsed=7.4min]

Entraînement:  23%|██▎       | 2317/10000 [07:25<24:16,  5.28step/s, loss=0.042990, elapsed=7.4min]

Entraînement:  23%|██▎       | 2317/10000 [07:25<24:16,  5.28step/s, loss=0.046719, elapsed=7.4min]

Entraînement:  23%|██▎       | 2318/10000 [07:25<24:12,  5.29step/s, loss=0.046719, elapsed=7.4min]

Entraînement:  23%|██▎       | 2318/10000 [07:25<24:12,  5.29step/s, loss=0.039850, elapsed=7.4min]

Entraînement:  23%|██▎       | 2319/10000 [07:26<24:11,  5.29step/s, loss=0.039850, elapsed=7.4min]

Entraînement:  23%|██▎       | 2319/10000 [07:26<24:11,  5.29step/s, loss=0.130493, elapsed=7.4min]

Entraînement:  23%|██▎       | 2320/10000 [07:26<24:10,  5.29step/s, loss=0.130493, elapsed=7.4min]

Entraînement:  23%|██▎       | 2320/10000 [07:26<24:10,  5.29step/s, loss=0.051087, elapsed=7.4min]

Entraînement:  23%|██▎       | 2321/10000 [07:26<24:10,  5.30step/s, loss=0.051087, elapsed=7.4min]

Entraînement:  23%|██▎       | 2321/10000 [07:26<24:10,  5.30step/s, loss=0.122440, elapsed=7.4min]

Entraînement:  23%|██▎       | 2322/10000 [07:26<24:07,  5.30step/s, loss=0.122440, elapsed=7.4min]

Entraînement:  23%|██▎       | 2322/10000 [07:26<24:07,  5.30step/s, loss=0.045346, elapsed=7.4min]

Entraînement:  23%|██▎       | 2323/10000 [07:26<24:08,  5.30step/s, loss=0.045346, elapsed=7.4min]

Entraînement:  23%|██▎       | 2323/10000 [07:26<24:08,  5.30step/s, loss=0.055544, elapsed=7.4min]

Entraînement:  23%|██▎       | 2324/10000 [07:27<24:07,  5.30step/s, loss=0.055544, elapsed=7.4min]

Entraînement:  23%|██▎       | 2324/10000 [07:27<24:07,  5.30step/s, loss=0.034578, elapsed=7.5min]

Entraînement:  23%|██▎       | 2325/10000 [07:27<24:06,  5.31step/s, loss=0.034578, elapsed=7.5min]

Entraînement:  23%|██▎       | 2325/10000 [07:27<24:06,  5.31step/s, loss=0.036648, elapsed=7.5min]

Entraînement:  23%|██▎       | 2326/10000 [07:27<24:09,  5.29step/s, loss=0.036648, elapsed=7.5min]

Entraînement:  23%|██▎       | 2326/10000 [07:27<24:09,  5.29step/s, loss=0.100814, elapsed=7.5min]

Entraînement:  23%|██▎       | 2327/10000 [07:27<24:08,  5.30step/s, loss=0.100814, elapsed=7.5min]

Entraînement:  23%|██▎       | 2327/10000 [07:27<24:08,  5.30step/s, loss=0.057672, elapsed=7.5min]

Entraînement:  23%|██▎       | 2328/10000 [07:27<24:07,  5.30step/s, loss=0.057672, elapsed=7.5min]

Entraînement:  23%|██▎       | 2328/10000 [07:27<24:07,  5.30step/s, loss=0.034925, elapsed=7.5min]

Entraînement:  23%|██▎       | 2329/10000 [07:28<24:07,  5.30step/s, loss=0.034925, elapsed=7.5min]

Entraînement:  23%|██▎       | 2329/10000 [07:28<24:07,  5.30step/s, loss=0.034502, elapsed=7.5min]

Entraînement:  23%|██▎       | 2330/10000 [07:28<24:05,  5.30step/s, loss=0.034502, elapsed=7.5min]

Entraînement:  23%|██▎       | 2330/10000 [07:28<24:05,  5.30step/s, loss=0.053471, elapsed=7.5min]

Entraînement:  23%|██▎       | 2331/10000 [07:28<24:06,  5.30step/s, loss=0.053471, elapsed=7.5min]

Entraînement:  23%|██▎       | 2331/10000 [07:28<24:06,  5.30step/s, loss=0.073285, elapsed=7.5min]

Entraînement:  23%|██▎       | 2332/10000 [07:28<24:06,  5.30step/s, loss=0.073285, elapsed=7.5min]

Entraînement:  23%|██▎       | 2332/10000 [07:28<24:06,  5.30step/s, loss=0.032084, elapsed=7.5min]

Entraînement:  23%|██▎       | 2333/10000 [07:28<24:05,  5.30step/s, loss=0.032084, elapsed=7.5min]

Entraînement:  23%|██▎       | 2333/10000 [07:28<24:05,  5.30step/s, loss=0.030919, elapsed=7.5min]

Entraînement:  23%|██▎       | 2334/10000 [07:28<24:07,  5.30step/s, loss=0.030919, elapsed=7.5min]

Entraînement:  23%|██▎       | 2334/10000 [07:28<24:07,  5.30step/s, loss=0.082867, elapsed=7.5min]

Entraînement:  23%|██▎       | 2335/10000 [07:29<24:07,  5.29step/s, loss=0.082867, elapsed=7.5min]

Entraînement:  23%|██▎       | 2335/10000 [07:29<24:07,  5.29step/s, loss=0.025588, elapsed=7.5min]

Entraînement:  23%|██▎       | 2336/10000 [07:29<24:07,  5.30step/s, loss=0.025588, elapsed=7.5min]

Entraînement:  23%|██▎       | 2336/10000 [07:29<24:07,  5.30step/s, loss=0.060520, elapsed=7.5min]

Entraînement:  23%|██▎       | 2337/10000 [07:29<24:06,  5.30step/s, loss=0.060520, elapsed=7.5min]

Entraînement:  23%|██▎       | 2337/10000 [07:29<24:06,  5.30step/s, loss=0.056078, elapsed=7.5min]

Entraînement:  23%|██▎       | 2338/10000 [07:29<24:04,  5.30step/s, loss=0.056078, elapsed=7.5min]

Entraînement:  23%|██▎       | 2338/10000 [07:29<24:04,  5.30step/s, loss=0.034797, elapsed=7.5min]

Entraînement:  23%|██▎       | 2339/10000 [07:29<24:07,  5.29step/s, loss=0.034797, elapsed=7.5min]

Entraînement:  23%|██▎       | 2339/10000 [07:29<24:07,  5.29step/s, loss=0.054886, elapsed=7.5min]

Entraînement:  23%|██▎       | 2340/10000 [07:30<24:08,  5.29step/s, loss=0.054886, elapsed=7.5min]

Entraînement:  23%|██▎       | 2340/10000 [07:30<24:08,  5.29step/s, loss=0.072153, elapsed=7.5min]

Entraînement:  23%|██▎       | 2341/10000 [07:30<24:12,  5.27step/s, loss=0.072153, elapsed=7.5min]

Entraînement:  23%|██▎       | 2341/10000 [07:30<24:12,  5.27step/s, loss=0.082134, elapsed=7.5min]

Entraînement:  23%|██▎       | 2342/10000 [07:30<24:13,  5.27step/s, loss=0.082134, elapsed=7.5min]

Entraînement:  23%|██▎       | 2342/10000 [07:30<24:13,  5.27step/s, loss=0.222264, elapsed=7.5min]

Entraînement:  23%|██▎       | 2343/10000 [07:30<24:14,  5.27step/s, loss=0.222264, elapsed=7.5min]

Entraînement:  23%|██▎       | 2343/10000 [07:30<24:14,  5.27step/s, loss=0.037792, elapsed=7.5min]

Entraînement:  23%|██▎       | 2344/10000 [07:30<24:12,  5.27step/s, loss=0.037792, elapsed=7.5min]

Entraînement:  23%|██▎       | 2344/10000 [07:30<24:12,  5.27step/s, loss=0.038057, elapsed=7.5min]

Entraînement:  23%|██▎       | 2345/10000 [07:31<24:09,  5.28step/s, loss=0.038057, elapsed=7.5min]

Entraînement:  23%|██▎       | 2345/10000 [07:31<24:09,  5.28step/s, loss=0.039307, elapsed=7.5min]

Entraînement:  23%|██▎       | 2346/10000 [07:31<24:09,  5.28step/s, loss=0.039307, elapsed=7.5min]

Entraînement:  23%|██▎       | 2346/10000 [07:31<24:09,  5.28step/s, loss=0.092147, elapsed=7.5min]

Entraînement:  23%|██▎       | 2347/10000 [07:31<24:08,  5.28step/s, loss=0.092147, elapsed=7.5min]

Entraînement:  23%|██▎       | 2347/10000 [07:31<24:08,  5.28step/s, loss=0.129944, elapsed=7.5min]

Entraînement:  23%|██▎       | 2348/10000 [07:31<24:09,  5.28step/s, loss=0.129944, elapsed=7.5min]

Entraînement:  23%|██▎       | 2348/10000 [07:31<24:09,  5.28step/s, loss=0.029843, elapsed=7.5min]

Entraînement:  23%|██▎       | 2349/10000 [07:31<24:14,  5.26step/s, loss=0.029843, elapsed=7.5min]

Entraînement:  23%|██▎       | 2349/10000 [07:31<24:14,  5.26step/s, loss=0.118689, elapsed=7.5min]

Entraînement:  24%|██▎       | 2350/10000 [07:32<24:20,  5.24step/s, loss=0.118689, elapsed=7.5min]

Entraînement:  24%|██▎       | 2350/10000 [07:32<24:20,  5.24step/s, loss=0.063560, elapsed=7.5min]

Entraînement:  24%|██▎       | 2351/10000 [07:32<24:18,  5.25step/s, loss=0.063560, elapsed=7.5min]

Entraînement:  24%|██▎       | 2351/10000 [07:32<24:18,  5.25step/s, loss=0.089101, elapsed=7.5min]

Entraînement:  24%|██▎       | 2352/10000 [07:32<24:22,  5.23step/s, loss=0.089101, elapsed=7.5min]

Entraînement:  24%|██▎       | 2352/10000 [07:32<24:22,  5.23step/s, loss=0.033804, elapsed=7.5min]

Entraînement:  24%|██▎       | 2353/10000 [07:32<24:24,  5.22step/s, loss=0.033804, elapsed=7.5min]

Entraînement:  24%|██▎       | 2353/10000 [07:32<24:24,  5.22step/s, loss=0.066439, elapsed=7.5min]

Entraînement:  24%|██▎       | 2354/10000 [07:32<24:23,  5.23step/s, loss=0.066439, elapsed=7.5min]

Entraînement:  24%|██▎       | 2354/10000 [07:32<24:23,  5.23step/s, loss=0.047737, elapsed=7.5min]

Entraînement:  24%|██▎       | 2355/10000 [07:32<24:19,  5.24step/s, loss=0.047737, elapsed=7.5min]

Entraînement:  24%|██▎       | 2355/10000 [07:32<24:19,  5.24step/s, loss=0.124995, elapsed=7.5min]

Entraînement:  24%|██▎       | 2356/10000 [07:33<24:24,  5.22step/s, loss=0.124995, elapsed=7.5min]

Entraînement:  24%|██▎       | 2356/10000 [07:33<24:24,  5.22step/s, loss=0.077691, elapsed=7.6min]

Entraînement:  24%|██▎       | 2357/10000 [07:33<24:22,  5.23step/s, loss=0.077691, elapsed=7.6min]

Entraînement:  24%|██▎       | 2357/10000 [07:33<24:22,  5.23step/s, loss=0.071638, elapsed=7.6min]

Entraînement:  24%|██▎       | 2358/10000 [07:33<24:21,  5.23step/s, loss=0.071638, elapsed=7.6min]

Entraînement:  24%|██▎       | 2358/10000 [07:33<24:21,  5.23step/s, loss=0.089247, elapsed=7.6min]

Entraînement:  24%|██▎       | 2359/10000 [07:33<24:18,  5.24step/s, loss=0.089247, elapsed=7.6min]

Entraînement:  24%|██▎       | 2359/10000 [07:33<24:18,  5.24step/s, loss=0.088100, elapsed=7.6min]

Entraînement:  24%|██▎       | 2360/10000 [07:33<24:17,  5.24step/s, loss=0.088100, elapsed=7.6min]

Entraînement:  24%|██▎       | 2360/10000 [07:33<24:17,  5.24step/s, loss=0.041762, elapsed=7.6min]

Entraînement:  24%|██▎       | 2361/10000 [07:34<24:20,  5.23step/s, loss=0.041762, elapsed=7.6min]

Entraînement:  24%|██▎       | 2361/10000 [07:34<24:20,  5.23step/s, loss=0.063917, elapsed=7.6min]

Entraînement:  24%|██▎       | 2362/10000 [07:34<24:17,  5.24step/s, loss=0.063917, elapsed=7.6min]

Entraînement:  24%|██▎       | 2362/10000 [07:34<24:17,  5.24step/s, loss=0.072835, elapsed=7.6min]

Entraînement:  24%|██▎       | 2363/10000 [07:34<24:14,  5.25step/s, loss=0.072835, elapsed=7.6min]

Entraînement:  24%|██▎       | 2363/10000 [07:34<24:14,  5.25step/s, loss=0.056886, elapsed=7.6min]

Entraînement:  24%|██▎       | 2364/10000 [07:34<24:20,  5.23step/s, loss=0.056886, elapsed=7.6min]

Entraînement:  24%|██▎       | 2364/10000 [07:34<24:20,  5.23step/s, loss=0.045373, elapsed=7.6min]

Entraînement:  24%|██▎       | 2365/10000 [07:34<24:18,  5.23step/s, loss=0.045373, elapsed=7.6min]

Entraînement:  24%|██▎       | 2365/10000 [07:34<24:18,  5.23step/s, loss=0.041040, elapsed=7.6min]

Entraînement:  24%|██▎       | 2366/10000 [07:35<24:18,  5.23step/s, loss=0.041040, elapsed=7.6min]

Entraînement:  24%|██▎       | 2366/10000 [07:35<24:18,  5.23step/s, loss=0.077551, elapsed=7.6min]

Entraînement:  24%|██▎       | 2367/10000 [07:35<24:16,  5.24step/s, loss=0.077551, elapsed=7.6min]

Entraînement:  24%|██▎       | 2367/10000 [07:35<24:16,  5.24step/s, loss=0.035636, elapsed=7.6min]

Entraînement:  24%|██▎       | 2368/10000 [07:35<24:13,  5.25step/s, loss=0.035636, elapsed=7.6min]

Entraînement:  24%|██▎       | 2368/10000 [07:35<24:13,  5.25step/s, loss=0.084256, elapsed=7.6min]

Entraînement:  24%|██▎       | 2369/10000 [07:35<24:12,  5.25step/s, loss=0.084256, elapsed=7.6min]

Entraînement:  24%|██▎       | 2369/10000 [07:35<24:12,  5.25step/s, loss=0.069013, elapsed=7.6min]

Entraînement:  24%|██▎       | 2370/10000 [07:35<24:06,  5.27step/s, loss=0.069013, elapsed=7.6min]

Entraînement:  24%|██▎       | 2370/10000 [07:35<24:06,  5.27step/s, loss=0.036890, elapsed=7.6min]

Entraînement:  24%|██▎       | 2371/10000 [07:36<24:08,  5.27step/s, loss=0.036890, elapsed=7.6min]

Entraînement:  24%|██▎       | 2371/10000 [07:36<24:08,  5.27step/s, loss=0.125076, elapsed=7.6min]

Entraînement:  24%|██▎       | 2372/10000 [07:36<24:10,  5.26step/s, loss=0.125076, elapsed=7.6min]

Entraînement:  24%|██▎       | 2372/10000 [07:36<24:10,  5.26step/s, loss=0.040283, elapsed=7.6min]

Entraînement:  24%|██▎       | 2373/10000 [07:36<24:08,  5.26step/s, loss=0.040283, elapsed=7.6min]

Entraînement:  24%|██▎       | 2373/10000 [07:36<24:08,  5.26step/s, loss=0.051575, elapsed=7.6min]

Entraînement:  24%|██▎       | 2374/10000 [07:36<24:10,  5.26step/s, loss=0.051575, elapsed=7.6min]

Entraînement:  24%|██▎       | 2374/10000 [07:36<24:10,  5.26step/s, loss=0.056723, elapsed=7.6min]

Entraînement:  24%|██▍       | 2375/10000 [07:36<24:10,  5.26step/s, loss=0.056723, elapsed=7.6min]

Entraînement:  24%|██▍       | 2375/10000 [07:36<24:10,  5.26step/s, loss=0.088250, elapsed=7.6min]

Entraînement:  24%|██▍       | 2376/10000 [07:36<24:10,  5.25step/s, loss=0.088250, elapsed=7.6min]

Entraînement:  24%|██▍       | 2376/10000 [07:36<24:10,  5.25step/s, loss=0.138993, elapsed=7.6min]

Entraînement:  24%|██▍       | 2377/10000 [07:37<24:09,  5.26step/s, loss=0.138993, elapsed=7.6min]

Entraînement:  24%|██▍       | 2377/10000 [07:37<24:09,  5.26step/s, loss=0.051920, elapsed=7.6min]

Entraînement:  24%|██▍       | 2378/10000 [07:37<24:08,  5.26step/s, loss=0.051920, elapsed=7.6min]

Entraînement:  24%|██▍       | 2378/10000 [07:37<24:08,  5.26step/s, loss=0.028130, elapsed=7.6min]

Entraînement:  24%|██▍       | 2379/10000 [07:37<24:08,  5.26step/s, loss=0.028130, elapsed=7.6min]

Entraînement:  24%|██▍       | 2379/10000 [07:37<24:08,  5.26step/s, loss=0.031827, elapsed=7.6min]

Entraînement:  24%|██▍       | 2380/10000 [07:37<24:08,  5.26step/s, loss=0.031827, elapsed=7.6min]

Entraînement:  24%|██▍       | 2380/10000 [07:37<24:08,  5.26step/s, loss=0.044328, elapsed=7.6min]

Entraînement:  24%|██▍       | 2381/10000 [07:37<24:08,  5.26step/s, loss=0.044328, elapsed=7.6min]

Entraînement:  24%|██▍       | 2381/10000 [07:37<24:08,  5.26step/s, loss=0.066011, elapsed=7.6min]

Entraînement:  24%|██▍       | 2382/10000 [07:38<24:06,  5.27step/s, loss=0.066011, elapsed=7.6min]

Entraînement:  24%|██▍       | 2382/10000 [07:38<24:06,  5.27step/s, loss=0.098788, elapsed=7.6min]

Entraînement:  24%|██▍       | 2383/10000 [07:38<24:00,  5.29step/s, loss=0.098788, elapsed=7.6min]

Entraînement:  24%|██▍       | 2383/10000 [07:38<24:00,  5.29step/s, loss=0.066145, elapsed=7.6min]

Entraînement:  24%|██▍       | 2384/10000 [07:38<24:01,  5.28step/s, loss=0.066145, elapsed=7.6min]

Entraînement:  24%|██▍       | 2384/10000 [07:38<24:01,  5.28step/s, loss=0.098976, elapsed=7.6min]

Entraînement:  24%|██▍       | 2385/10000 [07:38<24:09,  5.25step/s, loss=0.098976, elapsed=7.6min]

Entraînement:  24%|██▍       | 2385/10000 [07:38<24:09,  5.25step/s, loss=0.114486, elapsed=7.6min]

Entraînement:  24%|██▍       | 2386/10000 [07:38<24:05,  5.27step/s, loss=0.114486, elapsed=7.6min]

Entraînement:  24%|██▍       | 2386/10000 [07:38<24:05,  5.27step/s, loss=0.067328, elapsed=7.6min]

Entraînement:  24%|██▍       | 2387/10000 [07:39<24:07,  5.26step/s, loss=0.067328, elapsed=7.6min]

Entraînement:  24%|██▍       | 2387/10000 [07:39<24:07,  5.26step/s, loss=0.058439, elapsed=7.7min]

Entraînement:  24%|██▍       | 2388/10000 [07:39<24:05,  5.27step/s, loss=0.058439, elapsed=7.7min]

Entraînement:  24%|██▍       | 2388/10000 [07:39<24:05,  5.27step/s, loss=0.058874, elapsed=7.7min]

Entraînement:  24%|██▍       | 2389/10000 [07:39<24:00,  5.28step/s, loss=0.058874, elapsed=7.7min]

Entraînement:  24%|██▍       | 2389/10000 [07:39<24:00,  5.28step/s, loss=0.033412, elapsed=7.7min]

Entraînement:  24%|██▍       | 2390/10000 [07:39<24:00,  5.28step/s, loss=0.033412, elapsed=7.7min]

Entraînement:  24%|██▍       | 2390/10000 [07:39<24:00,  5.28step/s, loss=0.049575, elapsed=7.7min]

Entraînement:  24%|██▍       | 2391/10000 [07:39<24:09,  5.25step/s, loss=0.049575, elapsed=7.7min]

Entraînement:  24%|██▍       | 2391/10000 [07:39<24:09,  5.25step/s, loss=0.039287, elapsed=7.7min]

Entraînement:  24%|██▍       | 2392/10000 [07:40<24:10,  5.25step/s, loss=0.039287, elapsed=7.7min]

Entraînement:  24%|██▍       | 2392/10000 [07:40<24:10,  5.25step/s, loss=0.054635, elapsed=7.7min]

Entraînement:  24%|██▍       | 2393/10000 [07:40<24:08,  5.25step/s, loss=0.054635, elapsed=7.7min]

Entraînement:  24%|██▍       | 2393/10000 [07:40<24:08,  5.25step/s, loss=0.048145, elapsed=7.7min]

Entraînement:  24%|██▍       | 2394/10000 [07:40<24:11,  5.24step/s, loss=0.048145, elapsed=7.7min]

Entraînement:  24%|██▍       | 2394/10000 [07:40<24:11,  5.24step/s, loss=0.034044, elapsed=7.7min]

Entraînement:  24%|██▍       | 2395/10000 [07:40<24:11,  5.24step/s, loss=0.034044, elapsed=7.7min]

Entraînement:  24%|██▍       | 2395/10000 [07:40<24:11,  5.24step/s, loss=0.023286, elapsed=7.7min]

Entraînement:  24%|██▍       | 2396/10000 [07:40<24:06,  5.26step/s, loss=0.023286, elapsed=7.7min]

Entraînement:  24%|██▍       | 2396/10000 [07:40<24:06,  5.26step/s, loss=0.071604, elapsed=7.7min]

Entraînement:  24%|██▍       | 2397/10000 [07:40<24:05,  5.26step/s, loss=0.071604, elapsed=7.7min]

Entraînement:  24%|██▍       | 2397/10000 [07:40<24:05,  5.26step/s, loss=0.055120, elapsed=7.7min]

Entraînement:  24%|██▍       | 2398/10000 [07:41<24:04,  5.26step/s, loss=0.055120, elapsed=7.7min]

Entraînement:  24%|██▍       | 2398/10000 [07:41<24:04,  5.26step/s, loss=0.044313, elapsed=7.7min]

Entraînement:  24%|██▍       | 2399/10000 [07:41<24:05,  5.26step/s, loss=0.044313, elapsed=7.7min]

Entraînement:  24%|██▍       | 2399/10000 [07:41<24:05,  5.26step/s, loss=0.057262, elapsed=7.7min]

Entraînement:  24%|██▍       | 2400/10000 [07:41<24:03,  5.26step/s, loss=0.057262, elapsed=7.7min]

Entraînement:  24%|██▍       | 2400/10000 [07:41<24:03,  5.26step/s, loss=0.066564, elapsed=7.7min]

Entraînement:  24%|██▍       | 2400/10000 [07:41<24:03,  5.26step/s, loss=0.066564, elapsed=7.7min]

Entraînement:  24%|██▍       | 2401/10000 [07:41<24:17,  5.21step/s, loss=0.066564, elapsed=7.7min]

Entraînement:  24%|██▍       | 2401/10000 [07:41<24:17,  5.21step/s, loss=0.088815, elapsed=7.7min]

Step 2400/10000 | Train loss: 0.066564 | Elapsed: 7.7min | ETA: 24.4min

Entraînement:  24%|██▍       | 2402/10000 [07:41<24:13,  5.23step/s, loss=0.088815, elapsed=7.7min]

Entraînement:  24%|██▍       | 2402/10000 [07:41<24:13,  5.23step/s, loss=0.064871, elapsed=7.7min]

Entraînement:  24%|██▍       | 2403/10000 [07:42<24:11,  5.23step/s, loss=0.064871, elapsed=7.7min]

Entraînement:  24%|██▍       | 2403/10000 [07:42<24:11,  5.23step/s, loss=0.037186, elapsed=7.7min]

Entraînement:  24%|██▍       | 2404/10000 [07:42<24:09,  5.24step/s, loss=0.037186, elapsed=7.7min]

Entraînement:  24%|██▍       | 2404/10000 [07:42<24:09,  5.24step/s, loss=0.030911, elapsed=7.7min]

Entraînement:  24%|██▍       | 2405/10000 [07:42<24:07,  5.25step/s, loss=0.030911, elapsed=7.7min]

Entraînement:  24%|██▍       | 2405/10000 [07:42<24:07,  5.25step/s, loss=0.068063, elapsed=7.7min]

Entraînement:  24%|██▍       | 2406/10000 [07:42<24:02,  5.26step/s, loss=0.068063, elapsed=7.7min]

Entraînement:  24%|██▍       | 2406/10000 [07:42<24:02,  5.26step/s, loss=0.123595, elapsed=7.7min]

Entraînement:  24%|██▍       | 2407/10000 [07:42<24:02,  5.27step/s, loss=0.123595, elapsed=7.7min]

Entraînement:  24%|██▍       | 2407/10000 [07:42<24:02,  5.27step/s, loss=0.078201, elapsed=7.7min]

Entraînement:  24%|██▍       | 2408/10000 [07:43<24:00,  5.27step/s, loss=0.078201, elapsed=7.7min]

Entraînement:  24%|██▍       | 2408/10000 [07:43<24:00,  5.27step/s, loss=0.032504, elapsed=7.7min]

Entraînement:  24%|██▍       | 2409/10000 [07:43<24:02,  5.26step/s, loss=0.032504, elapsed=7.7min]

Entraînement:  24%|██▍       | 2409/10000 [07:43<24:02,  5.26step/s, loss=0.045380, elapsed=7.7min]

Entraînement:  24%|██▍       | 2410/10000 [07:43<23:58,  5.28step/s, loss=0.045380, elapsed=7.7min]

Entraînement:  24%|██▍       | 2410/10000 [07:43<23:58,  5.28step/s, loss=0.050950, elapsed=7.7min]

Entraînement:  24%|██▍       | 2411/10000 [07:43<23:57,  5.28step/s, loss=0.050950, elapsed=7.7min]

Entraînement:  24%|██▍       | 2411/10000 [07:43<23:57,  5.28step/s, loss=0.051101, elapsed=7.7min]

Entraînement:  24%|██▍       | 2412/10000 [07:43<23:58,  5.28step/s, loss=0.051101, elapsed=7.7min]

Entraînement:  24%|██▍       | 2412/10000 [07:43<23:58,  5.28step/s, loss=0.061683, elapsed=7.7min]

Entraînement:  24%|██▍       | 2413/10000 [07:44<23:59,  5.27step/s, loss=0.061683, elapsed=7.7min]

Entraînement:  24%|██▍       | 2413/10000 [07:44<23:59,  5.27step/s, loss=0.062472, elapsed=7.7min]

Entraînement:  24%|██▍       | 2414/10000 [07:44<23:55,  5.28step/s, loss=0.062472, elapsed=7.7min]

Entraînement:  24%|██▍       | 2414/10000 [07:44<23:55,  5.28step/s, loss=0.046733, elapsed=7.7min]

Entraînement:  24%|██▍       | 2415/10000 [07:44<23:55,  5.28step/s, loss=0.046733, elapsed=7.7min]

Entraînement:  24%|██▍       | 2415/10000 [07:44<23:55,  5.28step/s, loss=0.041694, elapsed=7.7min]

Entraînement:  24%|██▍       | 2416/10000 [07:44<23:54,  5.29step/s, loss=0.041694, elapsed=7.7min]

Entraînement:  24%|██▍       | 2416/10000 [07:44<23:54,  5.29step/s, loss=0.032071, elapsed=7.7min]

Entraînement:  24%|██▍       | 2417/10000 [07:44<23:58,  5.27step/s, loss=0.032071, elapsed=7.7min]

Entraînement:  24%|██▍       | 2417/10000 [07:44<23:58,  5.27step/s, loss=0.053608, elapsed=7.7min]

Entraînement:  24%|██▍       | 2418/10000 [07:44<24:02,  5.26step/s, loss=0.053608, elapsed=7.7min]

Entraînement:  24%|██▍       | 2418/10000 [07:44<24:02,  5.26step/s, loss=0.028243, elapsed=7.7min]

Entraînement:  24%|██▍       | 2419/10000 [07:45<23:59,  5.27step/s, loss=0.028243, elapsed=7.7min]

Entraînement:  24%|██▍       | 2419/10000 [07:45<23:59,  5.27step/s, loss=0.031602, elapsed=7.8min]

Entraînement:  24%|██▍       | 2420/10000 [07:45<23:58,  5.27step/s, loss=0.031602, elapsed=7.8min]

Entraînement:  24%|██▍       | 2420/10000 [07:45<23:58,  5.27step/s, loss=0.048537, elapsed=7.8min]

Entraînement:  24%|██▍       | 2421/10000 [07:45<23:55,  5.28step/s, loss=0.048537, elapsed=7.8min]

Entraînement:  24%|██▍       | 2421/10000 [07:45<23:55,  5.28step/s, loss=0.048741, elapsed=7.8min]

Entraînement:  24%|██▍       | 2422/10000 [07:45<23:55,  5.28step/s, loss=0.048741, elapsed=7.8min]

Entraînement:  24%|██▍       | 2422/10000 [07:45<23:55,  5.28step/s, loss=0.024565, elapsed=7.8min]

Entraînement:  24%|██▍       | 2423/10000 [07:45<23:54,  5.28step/s, loss=0.024565, elapsed=7.8min]

Entraînement:  24%|██▍       | 2423/10000 [07:45<23:54,  5.28step/s, loss=0.030746, elapsed=7.8min]

Entraînement:  24%|██▍       | 2424/10000 [07:46<23:53,  5.28step/s, loss=0.030746, elapsed=7.8min]

Entraînement:  24%|██▍       | 2424/10000 [07:46<23:53,  5.28step/s, loss=0.051155, elapsed=7.8min]

Entraînement:  24%|██▍       | 2425/10000 [07:46<23:56,  5.27step/s, loss=0.051155, elapsed=7.8min]

Entraînement:  24%|██▍       | 2425/10000 [07:46<23:56,  5.27step/s, loss=0.064276, elapsed=7.8min]

Entraînement:  24%|██▍       | 2426/10000 [07:46<23:56,  5.27step/s, loss=0.064276, elapsed=7.8min]

Entraînement:  24%|██▍       | 2426/10000 [07:46<23:56,  5.27step/s, loss=0.033215, elapsed=7.8min]

Entraînement:  24%|██▍       | 2427/10000 [07:46<23:56,  5.27step/s, loss=0.033215, elapsed=7.8min]

Entraînement:  24%|██▍       | 2427/10000 [07:46<23:56,  5.27step/s, loss=0.110783, elapsed=7.8min]

Entraînement:  24%|██▍       | 2428/10000 [07:46<23:54,  5.28step/s, loss=0.110783, elapsed=7.8min]

Entraînement:  24%|██▍       | 2428/10000 [07:46<23:54,  5.28step/s, loss=0.072977, elapsed=7.8min]

Entraînement:  24%|██▍       | 2429/10000 [07:47<23:54,  5.28step/s, loss=0.072977, elapsed=7.8min]

Entraînement:  24%|██▍       | 2429/10000 [07:47<23:54,  5.28step/s, loss=0.053006, elapsed=7.8min]

Entraînement:  24%|██▍       | 2430/10000 [07:47<23:53,  5.28step/s, loss=0.053006, elapsed=7.8min]

Entraînement:  24%|██▍       | 2430/10000 [07:47<23:53,  5.28step/s, loss=0.043415, elapsed=7.8min]

Entraînement:  24%|██▍       | 2431/10000 [07:47<23:52,  5.28step/s, loss=0.043415, elapsed=7.8min]

Entraînement:  24%|██▍       | 2431/10000 [07:47<23:52,  5.28step/s, loss=0.032349, elapsed=7.8min]

Entraînement:  24%|██▍       | 2432/10000 [07:47<23:52,  5.28step/s, loss=0.032349, elapsed=7.8min]

Entraînement:  24%|██▍       | 2432/10000 [07:47<23:52,  5.28step/s, loss=0.047377, elapsed=7.8min]

Entraînement:  24%|██▍       | 2433/10000 [07:47<23:49,  5.29step/s, loss=0.047377, elapsed=7.8min]

Entraînement:  24%|██▍       | 2433/10000 [07:47<23:49,  5.29step/s, loss=0.044662, elapsed=7.8min]

Entraînement:  24%|██▍       | 2434/10000 [07:48<35:24,  3.56step/s, loss=0.044662, elapsed=7.8min]

Entraînement:  24%|██▍       | 2434/10000 [07:48<35:24,  3.56step/s, loss=0.034714, elapsed=7.8min]

Entraînement:  24%|██▍       | 2435/10000 [07:48<32:06,  3.93step/s, loss=0.034714, elapsed=7.8min]

Entraînement:  24%|██▍       | 2435/10000 [07:48<32:06,  3.93step/s, loss=0.070365, elapsed=7.8min]

Entraînement:  24%|██▍       | 2436/10000 [07:48<29:44,  4.24step/s, loss=0.070365, elapsed=7.8min]

Entraînement:  24%|██▍       | 2436/10000 [07:48<29:44,  4.24step/s, loss=0.035278, elapsed=7.8min]

Entraînement:  24%|██▍       | 2437/10000 [07:48<28:07,  4.48step/s, loss=0.035278, elapsed=7.8min]

Entraînement:  24%|██▍       | 2437/10000 [07:48<28:07,  4.48step/s, loss=0.038449, elapsed=7.8min]

Entraînement:  24%|██▍       | 2438/10000 [07:49<26:56,  4.68step/s, loss=0.038449, elapsed=7.8min]

Entraînement:  24%|██▍       | 2438/10000 [07:49<26:56,  4.68step/s, loss=0.116677, elapsed=7.8min]

Entraînement:  24%|██▍       | 2439/10000 [07:49<26:03,  4.84step/s, loss=0.116677, elapsed=7.8min]

Entraînement:  24%|██▍       | 2439/10000 [07:49<26:03,  4.84step/s, loss=0.058518, elapsed=7.8min]

Entraînement:  24%|██▍       | 2440/10000 [07:49<25:24,  4.96step/s, loss=0.058518, elapsed=7.8min]

Entraînement:  24%|██▍       | 2440/10000 [07:49<25:24,  4.96step/s, loss=0.029751, elapsed=7.8min]

Entraînement:  24%|██▍       | 2441/10000 [07:49<24:55,  5.05step/s, loss=0.029751, elapsed=7.8min]

Entraînement:  24%|██▍       | 2441/10000 [07:49<24:55,  5.05step/s, loss=0.046513, elapsed=7.8min]

Entraînement:  24%|██▍       | 2442/10000 [07:49<24:38,  5.11step/s, loss=0.046513, elapsed=7.8min]

Entraînement:  24%|██▍       | 2442/10000 [07:49<24:38,  5.11step/s, loss=0.067270, elapsed=7.8min]

Entraînement:  24%|██▍       | 2443/10000 [07:50<24:24,  5.16step/s, loss=0.067270, elapsed=7.8min]

Entraînement:  24%|██▍       | 2443/10000 [07:50<24:24,  5.16step/s, loss=0.047060, elapsed=7.8min]

Entraînement:  24%|██▍       | 2444/10000 [07:50<24:16,  5.19step/s, loss=0.047060, elapsed=7.8min]

Entraînement:  24%|██▍       | 2444/10000 [07:50<24:16,  5.19step/s, loss=0.135817, elapsed=7.8min]

Entraînement:  24%|██▍       | 2445/10000 [07:50<24:13,  5.20step/s, loss=0.135817, elapsed=7.8min]

Entraînement:  24%|██▍       | 2445/10000 [07:50<24:13,  5.20step/s, loss=0.046462, elapsed=7.8min]

Entraînement:  24%|██▍       | 2446/10000 [07:50<24:13,  5.20step/s, loss=0.046462, elapsed=7.8min]

Entraînement:  24%|██▍       | 2446/10000 [07:50<24:13,  5.20step/s, loss=0.067529, elapsed=7.8min]

Entraînement:  24%|██▍       | 2447/10000 [07:50<24:12,  5.20step/s, loss=0.067529, elapsed=7.8min]

Entraînement:  24%|██▍       | 2447/10000 [07:50<24:12,  5.20step/s, loss=0.047593, elapsed=7.8min]

Entraînement:  24%|██▍       | 2448/10000 [07:50<24:11,  5.20step/s, loss=0.047593, elapsed=7.8min]

Entraînement:  24%|██▍       | 2448/10000 [07:50<24:11,  5.20step/s, loss=0.039572, elapsed=7.8min]

Entraînement:  24%|██▍       | 2449/10000 [07:51<24:11,  5.20step/s, loss=0.039572, elapsed=7.8min]

Entraînement:  24%|██▍       | 2449/10000 [07:51<24:11,  5.20step/s, loss=0.025119, elapsed=7.9min]

Entraînement:  24%|██▍       | 2450/10000 [07:51<24:10,  5.21step/s, loss=0.025119, elapsed=7.9min]

Entraînement:  24%|██▍       | 2450/10000 [07:51<24:10,  5.21step/s, loss=0.044747, elapsed=7.9min]

Entraînement:  25%|██▍       | 2451/10000 [07:51<24:10,  5.21step/s, loss=0.044747, elapsed=7.9min]

Entraînement:  25%|██▍       | 2451/10000 [07:51<24:10,  5.21step/s, loss=0.050477, elapsed=7.9min]

Entraînement:  25%|██▍       | 2452/10000 [07:51<24:08,  5.21step/s, loss=0.050477, elapsed=7.9min]

Entraînement:  25%|██▍       | 2452/10000 [07:51<24:08,  5.21step/s, loss=0.113753, elapsed=7.9min]

Entraînement:  25%|██▍       | 2453/10000 [07:51<24:07,  5.21step/s, loss=0.113753, elapsed=7.9min]

Entraînement:  25%|██▍       | 2453/10000 [07:51<24:07,  5.21step/s, loss=0.115290, elapsed=7.9min]

Entraînement:  25%|██▍       | 2454/10000 [07:52<24:03,  5.23step/s, loss=0.115290, elapsed=7.9min]

Entraînement:  25%|██▍       | 2454/10000 [07:52<24:03,  5.23step/s, loss=0.076069, elapsed=7.9min]

Entraînement:  25%|██▍       | 2455/10000 [07:52<24:04,  5.22step/s, loss=0.076069, elapsed=7.9min]

Entraînement:  25%|██▍       | 2455/10000 [07:52<24:04,  5.22step/s, loss=0.029606, elapsed=7.9min]

Entraînement:  25%|██▍       | 2456/10000 [07:52<24:03,  5.23step/s, loss=0.029606, elapsed=7.9min]

Entraînement:  25%|██▍       | 2456/10000 [07:52<24:03,  5.23step/s, loss=0.085379, elapsed=7.9min]

Entraînement:  25%|██▍       | 2457/10000 [07:52<24:01,  5.23step/s, loss=0.085379, elapsed=7.9min]

Entraînement:  25%|██▍       | 2457/10000 [07:52<24:01,  5.23step/s, loss=0.058656, elapsed=7.9min]

Entraînement:  25%|██▍       | 2458/10000 [07:52<23:59,  5.24step/s, loss=0.058656, elapsed=7.9min]

Entraînement:  25%|██▍       | 2458/10000 [07:52<23:59,  5.24step/s, loss=0.071257, elapsed=7.9min]

Entraînement:  25%|██▍       | 2459/10000 [07:53<23:55,  5.25step/s, loss=0.071257, elapsed=7.9min]

Entraînement:  25%|██▍       | 2459/10000 [07:53<23:55,  5.25step/s, loss=0.027199, elapsed=7.9min]

Entraînement:  25%|██▍       | 2460/10000 [07:53<23:54,  5.26step/s, loss=0.027199, elapsed=7.9min]

Entraînement:  25%|██▍       | 2460/10000 [07:53<23:54,  5.26step/s, loss=0.044019, elapsed=7.9min]

Entraînement:  25%|██▍       | 2461/10000 [07:53<23:54,  5.26step/s, loss=0.044019, elapsed=7.9min]

Entraînement:  25%|██▍       | 2461/10000 [07:53<23:54,  5.26step/s, loss=0.111500, elapsed=7.9min]

Entraînement:  25%|██▍       | 2462/10000 [07:53<23:54,  5.26step/s, loss=0.111500, elapsed=7.9min]

Entraînement:  25%|██▍       | 2462/10000 [07:53<23:54,  5.26step/s, loss=0.036882, elapsed=7.9min]

Entraînement:  25%|██▍       | 2463/10000 [07:53<23:54,  5.25step/s, loss=0.036882, elapsed=7.9min]

Entraînement:  25%|██▍       | 2463/10000 [07:53<23:54,  5.25step/s, loss=0.047151, elapsed=7.9min]

Entraînement:  25%|██▍       | 2464/10000 [07:54<24:12,  5.19step/s, loss=0.047151, elapsed=7.9min]

Entraînement:  25%|██▍       | 2464/10000 [07:54<24:12,  5.19step/s, loss=0.065002, elapsed=7.9min]

Entraînement:  25%|██▍       | 2465/10000 [07:54<24:09,  5.20step/s, loss=0.065002, elapsed=7.9min]

Entraînement:  25%|██▍       | 2465/10000 [07:54<24:09,  5.20step/s, loss=0.050490, elapsed=7.9min]

Entraînement:  25%|██▍       | 2466/10000 [07:54<24:08,  5.20step/s, loss=0.050490, elapsed=7.9min]

Entraînement:  25%|██▍       | 2466/10000 [07:54<24:08,  5.20step/s, loss=0.057890, elapsed=7.9min]

Entraînement:  25%|██▍       | 2467/10000 [07:54<24:02,  5.22step/s, loss=0.057890, elapsed=7.9min]

Entraînement:  25%|██▍       | 2467/10000 [07:54<24:02,  5.22step/s, loss=0.090126, elapsed=7.9min]

Entraînement:  25%|██▍       | 2468/10000 [07:54<23:59,  5.23step/s, loss=0.090126, elapsed=7.9min]

Entraînement:  25%|██▍       | 2468/10000 [07:54<23:59,  5.23step/s, loss=0.090804, elapsed=7.9min]

Entraînement:  25%|██▍       | 2469/10000 [07:54<23:55,  5.25step/s, loss=0.090804, elapsed=7.9min]

Entraînement:  25%|██▍       | 2469/10000 [07:54<23:55,  5.25step/s, loss=0.037015, elapsed=7.9min]

Entraînement:  25%|██▍       | 2470/10000 [07:55<23:57,  5.24step/s, loss=0.037015, elapsed=7.9min]

Entraînement:  25%|██▍       | 2470/10000 [07:55<23:57,  5.24step/s, loss=0.160759, elapsed=7.9min]

Entraînement:  25%|██▍       | 2471/10000 [07:55<23:54,  5.25step/s, loss=0.160759, elapsed=7.9min]

Entraînement:  25%|██▍       | 2471/10000 [07:55<23:54,  5.25step/s, loss=0.078232, elapsed=7.9min]

Entraînement:  25%|██▍       | 2472/10000 [07:55<23:54,  5.25step/s, loss=0.078232, elapsed=7.9min]

Entraînement:  25%|██▍       | 2472/10000 [07:55<23:54,  5.25step/s, loss=0.028933, elapsed=7.9min]

Entraînement:  25%|██▍       | 2473/10000 [07:55<23:51,  5.26step/s, loss=0.028933, elapsed=7.9min]

Entraînement:  25%|██▍       | 2473/10000 [07:55<23:51,  5.26step/s, loss=0.045134, elapsed=7.9min]

Entraînement:  25%|██▍       | 2474/10000 [07:55<23:52,  5.25step/s, loss=0.045134, elapsed=7.9min]

Entraînement:  25%|██▍       | 2474/10000 [07:55<23:52,  5.25step/s, loss=0.045364, elapsed=7.9min]

Entraînement:  25%|██▍       | 2475/10000 [07:56<23:50,  5.26step/s, loss=0.045364, elapsed=7.9min]

Entraînement:  25%|██▍       | 2475/10000 [07:56<23:50,  5.26step/s, loss=0.052174, elapsed=7.9min]

Entraînement:  25%|██▍       | 2476/10000 [07:56<23:50,  5.26step/s, loss=0.052174, elapsed=7.9min]

Entraînement:  25%|██▍       | 2476/10000 [07:56<23:50,  5.26step/s, loss=0.065142, elapsed=7.9min]

Entraînement:  25%|██▍       | 2477/10000 [07:56<23:49,  5.26step/s, loss=0.065142, elapsed=7.9min]

Entraînement:  25%|██▍       | 2477/10000 [07:56<23:49,  5.26step/s, loss=0.035810, elapsed=7.9min]

Entraînement:  25%|██▍       | 2478/10000 [07:56<23:49,  5.26step/s, loss=0.035810, elapsed=7.9min]

Entraînement:  25%|██▍       | 2478/10000 [07:56<23:49,  5.26step/s, loss=0.034202, elapsed=7.9min]

Entraînement:  25%|██▍       | 2479/10000 [07:56<23:51,  5.25step/s, loss=0.034202, elapsed=7.9min]

Entraînement:  25%|██▍       | 2479/10000 [07:56<23:51,  5.25step/s, loss=0.062774, elapsed=7.9min]

Entraînement:  25%|██▍       | 2480/10000 [07:57<23:49,  5.26step/s, loss=0.062774, elapsed=7.9min]

Entraînement:  25%|██▍       | 2480/10000 [07:57<23:49,  5.26step/s, loss=0.067983, elapsed=8.0min]

Entraînement:  25%|██▍       | 2481/10000 [07:57<23:51,  5.25step/s, loss=0.067983, elapsed=8.0min]

Entraînement:  25%|██▍       | 2481/10000 [07:57<23:51,  5.25step/s, loss=0.033671, elapsed=8.0min]

Entraînement:  25%|██▍       | 2482/10000 [07:57<23:51,  5.25step/s, loss=0.033671, elapsed=8.0min]

Entraînement:  25%|██▍       | 2482/10000 [07:57<23:51,  5.25step/s, loss=0.050198, elapsed=8.0min]

Entraînement:  25%|██▍       | 2483/10000 [07:57<23:53,  5.25step/s, loss=0.050198, elapsed=8.0min]

Entraînement:  25%|██▍       | 2483/10000 [07:57<23:53,  5.25step/s, loss=0.112160, elapsed=8.0min]

Entraînement:  25%|██▍       | 2484/10000 [07:57<23:51,  5.25step/s, loss=0.112160, elapsed=8.0min]

Entraînement:  25%|██▍       | 2484/10000 [07:57<23:51,  5.25step/s, loss=0.058219, elapsed=8.0min]

Entraînement:  25%|██▍       | 2485/10000 [07:58<23:49,  5.26step/s, loss=0.058219, elapsed=8.0min]

Entraînement:  25%|██▍       | 2485/10000 [07:58<23:49,  5.26step/s, loss=0.043309, elapsed=8.0min]

Entraînement:  25%|██▍       | 2486/10000 [07:58<23:50,  5.25step/s, loss=0.043309, elapsed=8.0min]

Entraînement:  25%|██▍       | 2486/10000 [07:58<23:50,  5.25step/s, loss=0.101737, elapsed=8.0min]

Entraînement:  25%|██▍       | 2487/10000 [07:58<23:48,  5.26step/s, loss=0.101737, elapsed=8.0min]

Entraînement:  25%|██▍       | 2487/10000 [07:58<23:48,  5.26step/s, loss=0.032375, elapsed=8.0min]

Entraînement:  25%|██▍       | 2488/10000 [07:58<23:49,  5.25step/s, loss=0.032375, elapsed=8.0min]

Entraînement:  25%|██▍       | 2488/10000 [07:58<23:49,  5.25step/s, loss=0.078289, elapsed=8.0min]

Entraînement:  25%|██▍       | 2489/10000 [07:58<23:47,  5.26step/s, loss=0.078289, elapsed=8.0min]

Entraînement:  25%|██▍       | 2489/10000 [07:58<23:47,  5.26step/s, loss=0.099784, elapsed=8.0min]

Entraînement:  25%|██▍       | 2490/10000 [07:58<23:47,  5.26step/s, loss=0.099784, elapsed=8.0min]

Entraînement:  25%|██▍       | 2490/10000 [07:58<23:47,  5.26step/s, loss=0.078450, elapsed=8.0min]

Entraînement:  25%|██▍       | 2491/10000 [07:59<23:47,  5.26step/s, loss=0.078450, elapsed=8.0min]

Entraînement:  25%|██▍       | 2491/10000 [07:59<23:47,  5.26step/s, loss=0.101733, elapsed=8.0min]

Entraînement:  25%|██▍       | 2492/10000 [07:59<23:45,  5.27step/s, loss=0.101733, elapsed=8.0min]

Entraînement:  25%|██▍       | 2492/10000 [07:59<23:45,  5.27step/s, loss=0.024051, elapsed=8.0min]

Entraînement:  25%|██▍       | 2493/10000 [07:59<23:45,  5.27step/s, loss=0.024051, elapsed=8.0min]

Entraînement:  25%|██▍       | 2493/10000 [07:59<23:45,  5.27step/s, loss=0.025218, elapsed=8.0min]

Entraînement:  25%|██▍       | 2494/10000 [07:59<23:45,  5.27step/s, loss=0.025218, elapsed=8.0min]

Entraînement:  25%|██▍       | 2494/10000 [07:59<23:45,  5.27step/s, loss=0.041747, elapsed=8.0min]

Entraînement:  25%|██▍       | 2495/10000 [07:59<23:46,  5.26step/s, loss=0.041747, elapsed=8.0min]

Entraînement:  25%|██▍       | 2495/10000 [07:59<23:46,  5.26step/s, loss=0.091391, elapsed=8.0min]

Entraînement:  25%|██▍       | 2496/10000 [08:00<23:44,  5.27step/s, loss=0.091391, elapsed=8.0min]

Entraînement:  25%|██▍       | 2496/10000 [08:00<23:44,  5.27step/s, loss=0.060157, elapsed=8.0min]

Entraînement:  25%|██▍       | 2497/10000 [08:00<23:46,  5.26step/s, loss=0.060157, elapsed=8.0min]

Entraînement:  25%|██▍       | 2497/10000 [08:00<23:46,  5.26step/s, loss=0.020723, elapsed=8.0min]

Entraînement:  25%|██▍       | 2498/10000 [08:00<23:44,  5.27step/s, loss=0.020723, elapsed=8.0min]

Entraînement:  25%|██▍       | 2498/10000 [08:00<23:44,  5.27step/s, loss=0.028411, elapsed=8.0min]

Entraînement:  25%|██▍       | 2499/10000 [08:00<23:43,  5.27step/s, loss=0.028411, elapsed=8.0min]

Entraînement:  25%|██▍       | 2499/10000 [08:00<23:43,  5.27step/s, loss=0.049550, elapsed=8.0min]

Entraînement:  25%|██▌       | 2500/10000 [08:00<23:41,  5.28step/s, loss=0.049550, elapsed=8.0min]

Entraînement:  25%|██▌       | 2500/10000 [08:00<23:41,  5.28step/s, loss=0.028133, elapsed=8.0min]

Entraînement:  25%|██▌       | 2500/10000 [08:00<23:41,  5.28step/s, loss=0.028133, elapsed=8.0min]

Entraînement:  25%|██▌       | 2501/10000 [08:01<23:58,  5.21step/s, loss=0.028133, elapsed=8.0min]

Entraînement:  25%|██▌       | 2501/10000 [08:01<23:58,  5.21step/s, loss=0.040363, elapsed=8.0min]

Step 2500/10000 | Train loss: 0.028133 | Elapsed: 8.0min | ETA: 24.0min

Entraînement:  25%|██▌       | 2502/10000 [08:01<23:52,  5.23step/s, loss=0.040363, elapsed=8.0min]

Entraînement:  25%|██▌       | 2502/10000 [08:01<23:52,  5.23step/s, loss=0.036053, elapsed=8.0min]

Entraînement:  25%|██▌       | 2503/10000 [08:01<23:48,  5.25step/s, loss=0.036053, elapsed=8.0min]

Entraînement:  25%|██▌       | 2503/10000 [08:01<23:48,  5.25step/s, loss=0.034776, elapsed=8.0min]

Entraînement:  25%|██▌       | 2504/10000 [08:01<23:44,  5.26step/s, loss=0.034776, elapsed=8.0min]

Entraînement:  25%|██▌       | 2504/10000 [08:01<23:44,  5.26step/s, loss=0.025339, elapsed=8.0min]

Entraînement:  25%|██▌       | 2505/10000 [08:01<23:40,  5.28step/s, loss=0.025339, elapsed=8.0min]

Entraînement:  25%|██▌       | 2505/10000 [08:01<23:40,  5.28step/s, loss=0.029589, elapsed=8.0min]

Entraînement:  25%|██▌       | 2506/10000 [08:02<23:39,  5.28step/s, loss=0.029589, elapsed=8.0min]

Entraînement:  25%|██▌       | 2506/10000 [08:02<23:39,  5.28step/s, loss=0.025853, elapsed=8.0min]

Entraînement:  25%|██▌       | 2507/10000 [08:02<23:38,  5.28step/s, loss=0.025853, elapsed=8.0min]

Entraînement:  25%|██▌       | 2507/10000 [08:02<23:38,  5.28step/s, loss=0.059339, elapsed=8.0min]

Entraînement:  25%|██▌       | 2508/10000 [08:02<23:37,  5.29step/s, loss=0.059339, elapsed=8.0min]

Entraînement:  25%|██▌       | 2508/10000 [08:02<23:37,  5.29step/s, loss=0.040500, elapsed=8.0min]

Entraînement:  25%|██▌       | 2509/10000 [08:02<23:43,  5.26step/s, loss=0.040500, elapsed=8.0min]

Entraînement:  25%|██▌       | 2509/10000 [08:02<23:43,  5.26step/s, loss=0.063028, elapsed=8.0min]

Entraînement:  25%|██▌       | 2510/10000 [08:02<23:43,  5.26step/s, loss=0.063028, elapsed=8.0min]

Entraînement:  25%|██▌       | 2510/10000 [08:02<23:43,  5.26step/s, loss=0.036287, elapsed=8.0min]

Entraînement:  25%|██▌       | 2511/10000 [08:02<23:42,  5.26step/s, loss=0.036287, elapsed=8.0min]

Entraînement:  25%|██▌       | 2511/10000 [08:02<23:42,  5.26step/s, loss=0.039689, elapsed=8.0min]

Entraînement:  25%|██▌       | 2512/10000 [08:03<23:39,  5.28step/s, loss=0.039689, elapsed=8.0min]

Entraînement:  25%|██▌       | 2512/10000 [08:03<23:39,  5.28step/s, loss=0.025130, elapsed=8.1min]

Entraînement:  25%|██▌       | 2513/10000 [08:03<23:38,  5.28step/s, loss=0.025130, elapsed=8.1min]

Entraînement:  25%|██▌       | 2513/10000 [08:03<23:38,  5.28step/s, loss=0.069541, elapsed=8.1min]

Entraînement:  25%|██▌       | 2514/10000 [08:03<23:37,  5.28step/s, loss=0.069541, elapsed=8.1min]

Entraînement:  25%|██▌       | 2514/10000 [08:03<23:37,  5.28step/s, loss=0.046902, elapsed=8.1min]

Entraînement:  25%|██▌       | 2515/10000 [08:03<23:37,  5.28step/s, loss=0.046902, elapsed=8.1min]

Entraînement:  25%|██▌       | 2515/10000 [08:03<23:37,  5.28step/s, loss=0.040306, elapsed=8.1min]

Entraînement:  25%|██▌       | 2516/10000 [08:03<23:39,  5.27step/s, loss=0.040306, elapsed=8.1min]

Entraînement:  25%|██▌       | 2516/10000 [08:03<23:39,  5.27step/s, loss=0.058917, elapsed=8.1min]

Entraînement:  25%|██▌       | 2517/10000 [08:04<23:39,  5.27step/s, loss=0.058917, elapsed=8.1min]

Entraînement:  25%|██▌       | 2517/10000 [08:04<23:39,  5.27step/s, loss=0.023237, elapsed=8.1min]

Entraînement:  25%|██▌       | 2518/10000 [08:04<23:40,  5.27step/s, loss=0.023237, elapsed=8.1min]

Entraînement:  25%|██▌       | 2518/10000 [08:04<23:40,  5.27step/s, loss=0.033728, elapsed=8.1min]

Entraînement:  25%|██▌       | 2519/10000 [08:04<23:34,  5.29step/s, loss=0.033728, elapsed=8.1min]

Entraînement:  25%|██▌       | 2519/10000 [08:04<23:34,  5.29step/s, loss=0.047343, elapsed=8.1min]

Entraînement:  25%|██▌       | 2520/10000 [08:04<23:37,  5.28step/s, loss=0.047343, elapsed=8.1min]

Entraînement:  25%|██▌       | 2520/10000 [08:04<23:37,  5.28step/s, loss=0.049987, elapsed=8.1min]

Entraînement:  25%|██▌       | 2521/10000 [08:04<23:38,  5.27step/s, loss=0.049987, elapsed=8.1min]

Entraînement:  25%|██▌       | 2521/10000 [08:04<23:38,  5.27step/s, loss=0.068647, elapsed=8.1min]

Entraînement:  25%|██▌       | 2522/10000 [08:05<23:40,  5.26step/s, loss=0.068647, elapsed=8.1min]

Entraînement:  25%|██▌       | 2522/10000 [08:05<23:40,  5.26step/s, loss=0.078290, elapsed=8.1min]

Entraînement:  25%|██▌       | 2523/10000 [08:05<23:39,  5.27step/s, loss=0.078290, elapsed=8.1min]

Entraînement:  25%|██▌       | 2523/10000 [08:05<23:39,  5.27step/s, loss=0.109346, elapsed=8.1min]

Entraînement:  25%|██▌       | 2524/10000 [08:05<23:41,  5.26step/s, loss=0.109346, elapsed=8.1min]

Entraînement:  25%|██▌       | 2524/10000 [08:05<23:41,  5.26step/s, loss=0.090097, elapsed=8.1min]

Entraînement:  25%|██▌       | 2525/10000 [08:05<23:40,  5.26step/s, loss=0.090097, elapsed=8.1min]

Entraînement:  25%|██▌       | 2525/10000 [08:05<23:40,  5.26step/s, loss=0.034514, elapsed=8.1min]

Entraînement:  25%|██▌       | 2526/10000 [08:05<23:38,  5.27step/s, loss=0.034514, elapsed=8.1min]

Entraînement:  25%|██▌       | 2526/10000 [08:05<23:38,  5.27step/s, loss=0.102539, elapsed=8.1min]

Entraînement:  25%|██▌       | 2527/10000 [08:06<23:39,  5.26step/s, loss=0.102539, elapsed=8.1min]

Entraînement:  25%|██▌       | 2527/10000 [08:06<23:39,  5.26step/s, loss=0.029300, elapsed=8.1min]

Entraînement:  25%|██▌       | 2528/10000 [08:06<23:38,  5.27step/s, loss=0.029300, elapsed=8.1min]

Entraînement:  25%|██▌       | 2528/10000 [08:06<23:38,  5.27step/s, loss=0.036208, elapsed=8.1min]

Entraînement:  25%|██▌       | 2529/10000 [08:06<23:38,  5.27step/s, loss=0.036208, elapsed=8.1min]

Entraînement:  25%|██▌       | 2529/10000 [08:06<23:38,  5.27step/s, loss=0.059251, elapsed=8.1min]

Entraînement:  25%|██▌       | 2530/10000 [08:06<23:38,  5.27step/s, loss=0.059251, elapsed=8.1min]

Entraînement:  25%|██▌       | 2530/10000 [08:06<23:38,  5.27step/s, loss=0.030701, elapsed=8.1min]

Entraînement:  25%|██▌       | 2531/10000 [08:06<23:36,  5.27step/s, loss=0.030701, elapsed=8.1min]

Entraînement:  25%|██▌       | 2531/10000 [08:06<23:36,  5.27step/s, loss=0.059791, elapsed=8.1min]

Entraînement:  25%|██▌       | 2532/10000 [08:06<23:39,  5.26step/s, loss=0.059791, elapsed=8.1min]

Entraînement:  25%|██▌       | 2532/10000 [08:06<23:39,  5.26step/s, loss=0.022749, elapsed=8.1min]

Entraînement:  25%|██▌       | 2533/10000 [08:07<23:36,  5.27step/s, loss=0.022749, elapsed=8.1min]

Entraînement:  25%|██▌       | 2533/10000 [08:07<23:36,  5.27step/s, loss=0.102767, elapsed=8.1min]

Entraînement:  25%|██▌       | 2534/10000 [08:07<23:38,  5.26step/s, loss=0.102767, elapsed=8.1min]

Entraînement:  25%|██▌       | 2534/10000 [08:07<23:38,  5.26step/s, loss=0.028994, elapsed=8.1min]

Entraînement:  25%|██▌       | 2535/10000 [08:07<23:36,  5.27step/s, loss=0.028994, elapsed=8.1min]

Entraînement:  25%|██▌       | 2535/10000 [08:07<23:36,  5.27step/s, loss=0.047256, elapsed=8.1min]

Entraînement:  25%|██▌       | 2536/10000 [08:07<23:35,  5.27step/s, loss=0.047256, elapsed=8.1min]

Entraînement:  25%|██▌       | 2536/10000 [08:07<23:35,  5.27step/s, loss=0.079611, elapsed=8.1min]

Entraînement:  25%|██▌       | 2537/10000 [08:07<23:36,  5.27step/s, loss=0.079611, elapsed=8.1min]

Entraînement:  25%|██▌       | 2537/10000 [08:07<23:36,  5.27step/s, loss=0.059991, elapsed=8.1min]

Entraînement:  25%|██▌       | 2538/10000 [08:08<23:38,  5.26step/s, loss=0.059991, elapsed=8.1min]

Entraînement:  25%|██▌       | 2538/10000 [08:08<23:38,  5.26step/s, loss=0.061022, elapsed=8.1min]

Entraînement:  25%|██▌       | 2539/10000 [08:08<23:38,  5.26step/s, loss=0.061022, elapsed=8.1min]

Entraînement:  25%|██▌       | 2539/10000 [08:08<23:38,  5.26step/s, loss=0.036278, elapsed=8.1min]

Entraînement:  25%|██▌       | 2540/10000 [08:08<23:39,  5.26step/s, loss=0.036278, elapsed=8.1min]

Entraînement:  25%|██▌       | 2540/10000 [08:08<23:39,  5.26step/s, loss=0.102825, elapsed=8.1min]

Entraînement:  25%|██▌       | 2541/10000 [08:08<23:38,  5.26step/s, loss=0.102825, elapsed=8.1min]

Entraînement:  25%|██▌       | 2541/10000 [08:08<23:38,  5.26step/s, loss=0.059328, elapsed=8.1min]

Entraînement:  25%|██▌       | 2542/10000 [08:08<23:38,  5.26step/s, loss=0.059328, elapsed=8.1min]

Entraînement:  25%|██▌       | 2542/10000 [08:08<23:38,  5.26step/s, loss=0.082382, elapsed=8.1min]

Entraînement:  25%|██▌       | 2543/10000 [08:09<23:38,  5.26step/s, loss=0.082382, elapsed=8.1min]

Entraînement:  25%|██▌       | 2543/10000 [08:09<23:38,  5.26step/s, loss=0.026787, elapsed=8.2min]

Entraînement:  25%|██▌       | 2544/10000 [08:09<23:38,  5.26step/s, loss=0.026787, elapsed=8.2min]

Entraînement:  25%|██▌       | 2544/10000 [08:09<23:38,  5.26step/s, loss=0.112549, elapsed=8.2min]

Entraînement:  25%|██▌       | 2545/10000 [08:09<23:37,  5.26step/s, loss=0.112549, elapsed=8.2min]

Entraînement:  25%|██▌       | 2545/10000 [08:09<23:37,  5.26step/s, loss=0.038636, elapsed=8.2min]

Entraînement:  25%|██▌       | 2546/10000 [08:09<23:38,  5.26step/s, loss=0.038636, elapsed=8.2min]

Entraînement:  25%|██▌       | 2546/10000 [08:09<23:38,  5.26step/s, loss=0.072583, elapsed=8.2min]

Entraînement:  25%|██▌       | 2547/10000 [08:09<23:42,  5.24step/s, loss=0.072583, elapsed=8.2min]

Entraînement:  25%|██▌       | 2547/10000 [08:09<23:42,  5.24step/s, loss=0.053895, elapsed=8.2min]

Entraînement:  25%|██▌       | 2548/10000 [08:10<23:44,  5.23step/s, loss=0.053895, elapsed=8.2min]

Entraînement:  25%|██▌       | 2548/10000 [08:10<23:44,  5.23step/s, loss=0.147430, elapsed=8.2min]

Entraînement:  25%|██▌       | 2549/10000 [08:10<23:40,  5.24step/s, loss=0.147430, elapsed=8.2min]

Entraînement:  25%|██▌       | 2549/10000 [08:10<23:40,  5.24step/s, loss=0.097691, elapsed=8.2min]

Entraînement:  26%|██▌       | 2550/10000 [08:10<23:36,  5.26step/s, loss=0.097691, elapsed=8.2min]

Entraînement:  26%|██▌       | 2550/10000 [08:10<23:36,  5.26step/s, loss=0.084018, elapsed=8.2min]

Entraînement:  26%|██▌       | 2551/10000 [08:10<23:37,  5.25step/s, loss=0.084018, elapsed=8.2min]

Entraînement:  26%|██▌       | 2551/10000 [08:10<23:37,  5.25step/s, loss=0.047991, elapsed=8.2min]

Entraînement:  26%|██▌       | 2552/10000 [08:10<23:37,  5.25step/s, loss=0.047991, elapsed=8.2min]

Entraînement:  26%|██▌       | 2552/10000 [08:10<23:37,  5.25step/s, loss=0.038914, elapsed=8.2min]

Entraînement:  26%|██▌       | 2553/10000 [08:10<23:38,  5.25step/s, loss=0.038914, elapsed=8.2min]

Entraînement:  26%|██▌       | 2553/10000 [08:10<23:38,  5.25step/s, loss=0.028336, elapsed=8.2min]

Entraînement:  26%|██▌       | 2554/10000 [08:11<23:37,  5.25step/s, loss=0.028336, elapsed=8.2min]

Entraînement:  26%|██▌       | 2554/10000 [08:11<23:37,  5.25step/s, loss=0.038795, elapsed=8.2min]

Entraînement:  26%|██▌       | 2555/10000 [08:11<23:37,  5.25step/s, loss=0.038795, elapsed=8.2min]

Entraînement:  26%|██▌       | 2555/10000 [08:11<23:37,  5.25step/s, loss=0.096901, elapsed=8.2min]

Entraînement:  26%|██▌       | 2556/10000 [08:11<23:35,  5.26step/s, loss=0.096901, elapsed=8.2min]

Entraînement:  26%|██▌       | 2556/10000 [08:11<23:35,  5.26step/s, loss=0.037573, elapsed=8.2min]

Entraînement:  26%|██▌       | 2557/10000 [08:11<23:33,  5.27step/s, loss=0.037573, elapsed=8.2min]

Entraînement:  26%|██▌       | 2557/10000 [08:11<23:33,  5.27step/s, loss=0.053348, elapsed=8.2min]

Entraînement:  26%|██▌       | 2558/10000 [08:11<23:33,  5.27step/s, loss=0.053348, elapsed=8.2min]

Entraînement:  26%|██▌       | 2558/10000 [08:11<23:33,  5.27step/s, loss=0.040902, elapsed=8.2min]

Entraînement:  26%|██▌       | 2559/10000 [08:12<23:30,  5.27step/s, loss=0.040902, elapsed=8.2min]

Entraînement:  26%|██▌       | 2559/10000 [08:12<23:30,  5.27step/s, loss=0.040249, elapsed=8.2min]

Entraînement:  26%|██▌       | 2560/10000 [08:12<23:30,  5.27step/s, loss=0.040249, elapsed=8.2min]

Entraînement:  26%|██▌       | 2560/10000 [08:12<23:30,  5.27step/s, loss=0.045756, elapsed=8.2min]

Entraînement:  26%|██▌       | 2561/10000 [08:12<23:30,  5.27step/s, loss=0.045756, elapsed=8.2min]

Entraînement:  26%|██▌       | 2561/10000 [08:12<23:30,  5.27step/s, loss=0.025018, elapsed=8.2min]

Entraînement:  26%|██▌       | 2562/10000 [08:12<23:34,  5.26step/s, loss=0.025018, elapsed=8.2min]

Entraînement:  26%|██▌       | 2562/10000 [08:12<23:34,  5.26step/s, loss=0.086039, elapsed=8.2min]

Entraînement:  26%|██▌       | 2563/10000 [08:12<23:33,  5.26step/s, loss=0.086039, elapsed=8.2min]

Entraînement:  26%|██▌       | 2563/10000 [08:12<23:33,  5.26step/s, loss=0.047539, elapsed=8.2min]

Entraînement:  26%|██▌       | 2564/10000 [08:13<23:35,  5.25step/s, loss=0.047539, elapsed=8.2min]

Entraînement:  26%|██▌       | 2564/10000 [08:13<23:35,  5.25step/s, loss=0.042487, elapsed=8.2min]

Entraînement:  26%|██▌       | 2565/10000 [08:13<23:34,  5.26step/s, loss=0.042487, elapsed=8.2min]

Entraînement:  26%|██▌       | 2565/10000 [08:13<23:34,  5.26step/s, loss=0.069960, elapsed=8.2min]

Entraînement:  26%|██▌       | 2566/10000 [08:13<23:34,  5.26step/s, loss=0.069960, elapsed=8.2min]

Entraînement:  26%|██▌       | 2566/10000 [08:13<23:34,  5.26step/s, loss=0.053033, elapsed=8.2min]

Entraînement:  26%|██▌       | 2567/10000 [08:13<23:36,  5.25step/s, loss=0.053033, elapsed=8.2min]

Entraînement:  26%|██▌       | 2567/10000 [08:13<23:36,  5.25step/s, loss=0.099490, elapsed=8.2min]

Entraînement:  26%|██▌       | 2568/10000 [08:13<23:36,  5.25step/s, loss=0.099490, elapsed=8.2min]

Entraînement:  26%|██▌       | 2568/10000 [08:13<23:36,  5.25step/s, loss=0.127921, elapsed=8.2min]

Entraînement:  26%|██▌       | 2569/10000 [08:13<23:37,  5.24step/s, loss=0.127921, elapsed=8.2min]

Entraînement:  26%|██▌       | 2569/10000 [08:14<23:37,  5.24step/s, loss=0.105120, elapsed=8.2min]

Entraînement:  26%|██▌       | 2570/10000 [08:14<23:40,  5.23step/s, loss=0.105120, elapsed=8.2min]

Entraînement:  26%|██▌       | 2570/10000 [08:14<23:40,  5.23step/s, loss=0.059112, elapsed=8.2min]

Entraînement:  26%|██▌       | 2571/10000 [08:14<23:35,  5.25step/s, loss=0.059112, elapsed=8.2min]

Entraînement:  26%|██▌       | 2571/10000 [08:14<23:35,  5.25step/s, loss=0.094096, elapsed=8.2min]

Entraînement:  26%|██▌       | 2572/10000 [08:14<23:34,  5.25step/s, loss=0.094096, elapsed=8.2min]

Entraînement:  26%|██▌       | 2572/10000 [08:14<23:34,  5.25step/s, loss=0.053167, elapsed=8.2min]

Entraînement:  26%|██▌       | 2573/10000 [08:14<23:35,  5.25step/s, loss=0.053167, elapsed=8.2min]

Entraînement:  26%|██▌       | 2573/10000 [08:14<23:35,  5.25step/s, loss=0.029610, elapsed=8.2min]

Entraînement:  26%|██▌       | 2574/10000 [08:14<23:34,  5.25step/s, loss=0.029610, elapsed=8.2min]

Entraînement:  26%|██▌       | 2574/10000 [08:14<23:34,  5.25step/s, loss=0.056235, elapsed=8.2min]

Entraînement:  26%|██▌       | 2575/10000 [08:15<23:40,  5.23step/s, loss=0.056235, elapsed=8.2min]

Entraînement:  26%|██▌       | 2575/10000 [08:15<23:40,  5.23step/s, loss=0.181439, elapsed=8.3min]

Entraînement:  26%|██▌       | 2576/10000 [08:15<23:35,  5.24step/s, loss=0.181439, elapsed=8.3min]

Entraînement:  26%|██▌       | 2576/10000 [08:15<23:35,  5.24step/s, loss=0.038572, elapsed=8.3min]

Entraînement:  26%|██▌       | 2577/10000 [08:15<23:32,  5.25step/s, loss=0.038572, elapsed=8.3min]

Entraînement:  26%|██▌       | 2577/10000 [08:15<23:32,  5.25step/s, loss=0.063936, elapsed=8.3min]

Entraînement:  26%|██▌       | 2578/10000 [08:15<23:32,  5.25step/s, loss=0.063936, elapsed=8.3min]

Entraînement:  26%|██▌       | 2578/10000 [08:15<23:32,  5.25step/s, loss=0.042762, elapsed=8.3min]

Entraînement:  26%|██▌       | 2579/10000 [08:15<23:31,  5.26step/s, loss=0.042762, elapsed=8.3min]

Entraînement:  26%|██▌       | 2579/10000 [08:15<23:31,  5.26step/s, loss=0.035014, elapsed=8.3min]

Entraînement:  26%|██▌       | 2580/10000 [08:16<23:31,  5.26step/s, loss=0.035014, elapsed=8.3min]

Entraînement:  26%|██▌       | 2580/10000 [08:16<23:31,  5.26step/s, loss=0.077652, elapsed=8.3min]

Entraînement:  26%|██▌       | 2581/10000 [08:16<23:30,  5.26step/s, loss=0.077652, elapsed=8.3min]

Entraînement:  26%|██▌       | 2581/10000 [08:16<23:30,  5.26step/s, loss=0.041282, elapsed=8.3min]

Entraînement:  26%|██▌       | 2582/10000 [08:16<23:27,  5.27step/s, loss=0.041282, elapsed=8.3min]

Entraînement:  26%|██▌       | 2582/10000 [08:16<23:27,  5.27step/s, loss=0.050288, elapsed=8.3min]

Entraînement:  26%|██▌       | 2583/10000 [08:16<23:27,  5.27step/s, loss=0.050288, elapsed=8.3min]

Entraînement:  26%|██▌       | 2583/10000 [08:16<23:27,  5.27step/s, loss=0.079808, elapsed=8.3min]

Entraînement:  26%|██▌       | 2584/10000 [08:16<23:28,  5.27step/s, loss=0.079808, elapsed=8.3min]

Entraînement:  26%|██▌       | 2584/10000 [08:16<23:28,  5.27step/s, loss=0.084735, elapsed=8.3min]

Entraînement:  26%|██▌       | 2585/10000 [08:17<23:28,  5.27step/s, loss=0.084735, elapsed=8.3min]

Entraînement:  26%|██▌       | 2585/10000 [08:17<23:28,  5.27step/s, loss=0.044926, elapsed=8.3min]

Entraînement:  26%|██▌       | 2586/10000 [08:17<23:30,  5.26step/s, loss=0.044926, elapsed=8.3min]

Entraînement:  26%|██▌       | 2586/10000 [08:17<23:30,  5.26step/s, loss=0.047520, elapsed=8.3min]

Entraînement:  26%|██▌       | 2587/10000 [08:17<23:31,  5.25step/s, loss=0.047520, elapsed=8.3min]

Entraînement:  26%|██▌       | 2587/10000 [08:17<23:31,  5.25step/s, loss=0.060235, elapsed=8.3min]

Entraînement:  26%|██▌       | 2588/10000 [08:17<23:33,  5.24step/s, loss=0.060235, elapsed=8.3min]

Entraînement:  26%|██▌       | 2588/10000 [08:17<23:33,  5.24step/s, loss=0.031039, elapsed=8.3min]

Entraînement:  26%|██▌       | 2589/10000 [08:17<23:28,  5.26step/s, loss=0.031039, elapsed=8.3min]

Entraînement:  26%|██▌       | 2589/10000 [08:17<23:28,  5.26step/s, loss=0.064010, elapsed=8.3min]

Entraînement:  26%|██▌       | 2590/10000 [08:17<23:27,  5.27step/s, loss=0.064010, elapsed=8.3min]

Entraînement:  26%|██▌       | 2590/10000 [08:17<23:27,  5.27step/s, loss=0.063346, elapsed=8.3min]

Entraînement:  26%|██▌       | 2591/10000 [08:18<23:25,  5.27step/s, loss=0.063346, elapsed=8.3min]

Entraînement:  26%|██▌       | 2591/10000 [08:18<23:25,  5.27step/s, loss=0.104598, elapsed=8.3min]

Entraînement:  26%|██▌       | 2592/10000 [08:18<23:24,  5.28step/s, loss=0.104598, elapsed=8.3min]

Entraînement:  26%|██▌       | 2592/10000 [08:18<23:24,  5.28step/s, loss=0.105633, elapsed=8.3min]

Entraînement:  26%|██▌       | 2593/10000 [08:18<23:24,  5.27step/s, loss=0.105633, elapsed=8.3min]

Entraînement:  26%|██▌       | 2593/10000 [08:18<23:24,  5.27step/s, loss=0.044444, elapsed=8.3min]

Entraînement:  26%|██▌       | 2594/10000 [08:18<23:23,  5.28step/s, loss=0.044444, elapsed=8.3min]

Entraînement:  26%|██▌       | 2594/10000 [08:18<23:23,  5.28step/s, loss=0.038982, elapsed=8.3min]

Entraînement:  26%|██▌       | 2595/10000 [08:18<23:25,  5.27step/s, loss=0.038982, elapsed=8.3min]

Entraînement:  26%|██▌       | 2595/10000 [08:18<23:25,  5.27step/s, loss=0.141172, elapsed=8.3min]

Entraînement:  26%|██▌       | 2596/10000 [08:19<23:30,  5.25step/s, loss=0.141172, elapsed=8.3min]

Entraînement:  26%|██▌       | 2596/10000 [08:19<23:30,  5.25step/s, loss=0.081417, elapsed=8.3min]

Entraînement:  26%|██▌       | 2597/10000 [08:19<23:36,  5.23step/s, loss=0.081417, elapsed=8.3min]

Entraînement:  26%|██▌       | 2597/10000 [08:19<23:36,  5.23step/s, loss=0.045183, elapsed=8.3min]

Entraînement:  26%|██▌       | 2598/10000 [08:19<23:29,  5.25step/s, loss=0.045183, elapsed=8.3min]

Entraînement:  26%|██▌       | 2598/10000 [08:19<23:29,  5.25step/s, loss=0.022973, elapsed=8.3min]

Entraînement:  26%|██▌       | 2599/10000 [08:19<23:24,  5.27step/s, loss=0.022973, elapsed=8.3min]

Entraînement:  26%|██▌       | 2599/10000 [08:19<23:24,  5.27step/s, loss=0.056808, elapsed=8.3min]

Entraînement:  26%|██▌       | 2600/10000 [08:19<23:25,  5.27step/s, loss=0.056808, elapsed=8.3min]

Entraînement:  26%|██▌       | 2600/10000 [08:19<23:25,  5.27step/s, loss=0.119703, elapsed=8.3min]

Entraînement:  26%|██▌       | 2600/10000 [08:19<23:25,  5.27step/s, loss=0.119703, elapsed=8.3min]

Entraînement:  26%|██▌       | 2601/10000 [08:20<23:38,  5.22step/s, loss=0.119703, elapsed=8.3min]

Entraînement:  26%|██▌       | 2601/10000 [08:20<23:38,  5.22step/s, loss=0.027018, elapsed=8.3min]

Step 2600/10000 | Train loss: 0.119703 | Elapsed: 8.3min | ETA: 23.7min

Entraînement:  26%|██▌       | 2602/10000 [08:20<23:31,  5.24step/s, loss=0.027018, elapsed=8.3min]

Entraînement:  26%|██▌       | 2602/10000 [08:20<23:31,  5.24step/s, loss=0.052921, elapsed=8.3min]

Entraînement:  26%|██▌       | 2603/10000 [08:20<23:24,  5.27step/s, loss=0.052921, elapsed=8.3min]

Entraînement:  26%|██▌       | 2603/10000 [08:20<23:24,  5.27step/s, loss=0.029527, elapsed=8.3min]

Entraînement:  26%|██▌       | 2604/10000 [08:20<23:22,  5.27step/s, loss=0.029527, elapsed=8.3min]

Entraînement:  26%|██▌       | 2604/10000 [08:20<23:22,  5.27step/s, loss=0.035638, elapsed=8.3min]

Entraînement:  26%|██▌       | 2605/10000 [08:20<23:19,  5.28step/s, loss=0.035638, elapsed=8.3min]

Entraînement:  26%|██▌       | 2605/10000 [08:20<23:19,  5.28step/s, loss=0.037399, elapsed=8.3min]

Entraînement:  26%|██▌       | 2606/10000 [08:21<23:19,  5.28step/s, loss=0.037399, elapsed=8.3min]

Entraînement:  26%|██▌       | 2606/10000 [08:21<23:19,  5.28step/s, loss=0.035507, elapsed=8.4min]

Entraînement:  26%|██▌       | 2607/10000 [08:21<23:20,  5.28step/s, loss=0.035507, elapsed=8.4min]

Entraînement:  26%|██▌       | 2607/10000 [08:21<23:20,  5.28step/s, loss=0.051185, elapsed=8.4min]

Entraînement:  26%|██▌       | 2608/10000 [08:21<23:18,  5.29step/s, loss=0.051185, elapsed=8.4min]

Entraînement:  26%|██▌       | 2608/10000 [08:21<23:18,  5.29step/s, loss=0.054914, elapsed=8.4min]

Entraînement:  26%|██▌       | 2609/10000 [08:21<23:17,  5.29step/s, loss=0.054914, elapsed=8.4min]

Entraînement:  26%|██▌       | 2609/10000 [08:21<23:17,  5.29step/s, loss=0.049353, elapsed=8.4min]

Entraînement:  26%|██▌       | 2610/10000 [08:21<23:15,  5.30step/s, loss=0.049353, elapsed=8.4min]

Entraînement:  26%|██▌       | 2610/10000 [08:21<23:15,  5.30step/s, loss=0.049849, elapsed=8.4min]

Entraînement:  26%|██▌       | 2611/10000 [08:21<23:14,  5.30step/s, loss=0.049849, elapsed=8.4min]

Entraînement:  26%|██▌       | 2611/10000 [08:21<23:14,  5.30step/s, loss=0.073500, elapsed=8.4min]

Entraînement:  26%|██▌       | 2612/10000 [08:22<23:15,  5.30step/s, loss=0.073500, elapsed=8.4min]

Entraînement:  26%|██▌       | 2612/10000 [08:22<23:15,  5.30step/s, loss=0.032838, elapsed=8.4min]

Entraînement:  26%|██▌       | 2613/10000 [08:22<23:13,  5.30step/s, loss=0.032838, elapsed=8.4min]

Entraînement:  26%|██▌       | 2613/10000 [08:22<23:13,  5.30step/s, loss=0.036680, elapsed=8.4min]

Entraînement:  26%|██▌       | 2614/10000 [08:22<23:12,  5.31step/s, loss=0.036680, elapsed=8.4min]

Entraînement:  26%|██▌       | 2614/10000 [08:22<23:12,  5.31step/s, loss=0.037212, elapsed=8.4min]

Entraînement:  26%|██▌       | 2615/10000 [08:22<23:15,  5.29step/s, loss=0.037212, elapsed=8.4min]

Entraînement:  26%|██▌       | 2615/10000 [08:22<23:15,  5.29step/s, loss=0.142078, elapsed=8.4min]

Entraînement:  26%|██▌       | 2616/10000 [08:22<23:17,  5.29step/s, loss=0.142078, elapsed=8.4min]

Entraînement:  26%|██▌       | 2616/10000 [08:22<23:17,  5.29step/s, loss=0.048042, elapsed=8.4min]

Entraînement:  26%|██▌       | 2617/10000 [08:23<23:17,  5.28step/s, loss=0.048042, elapsed=8.4min]

Entraînement:  26%|██▌       | 2617/10000 [08:23<23:17,  5.28step/s, loss=0.146004, elapsed=8.4min]

Entraînement:  26%|██▌       | 2618/10000 [08:23<23:17,  5.28step/s, loss=0.146004, elapsed=8.4min]

Entraînement:  26%|██▌       | 2618/10000 [08:23<23:17,  5.28step/s, loss=0.041804, elapsed=8.4min]

Entraînement:  26%|██▌       | 2619/10000 [08:23<23:15,  5.29step/s, loss=0.041804, elapsed=8.4min]

Entraînement:  26%|██▌       | 2619/10000 [08:23<23:15,  5.29step/s, loss=0.085044, elapsed=8.4min]

Entraînement:  26%|██▌       | 2620/10000 [08:23<23:15,  5.29step/s, loss=0.085044, elapsed=8.4min]

Entraînement:  26%|██▌       | 2620/10000 [08:23<23:15,  5.29step/s, loss=0.031695, elapsed=8.4min]

Entraînement:  26%|██▌       | 2621/10000 [08:23<23:15,  5.29step/s, loss=0.031695, elapsed=8.4min]

Entraînement:  26%|██▌       | 2621/10000 [08:23<23:15,  5.29step/s, loss=0.047095, elapsed=8.4min]

Entraînement:  26%|██▌       | 2622/10000 [08:24<23:16,  5.28step/s, loss=0.047095, elapsed=8.4min]

Entraînement:  26%|██▌       | 2622/10000 [08:24<23:16,  5.28step/s, loss=0.076698, elapsed=8.4min]

Entraînement:  26%|██▌       | 2623/10000 [08:24<23:14,  5.29step/s, loss=0.076698, elapsed=8.4min]

Entraînement:  26%|██▌       | 2623/10000 [08:24<23:14,  5.29step/s, loss=0.104802, elapsed=8.4min]

Entraînement:  26%|██▌       | 2624/10000 [08:24<23:13,  5.29step/s, loss=0.104802, elapsed=8.4min]

Entraînement:  26%|██▌       | 2624/10000 [08:24<23:13,  5.29step/s, loss=0.045059, elapsed=8.4min]

Entraînement:  26%|██▋       | 2625/10000 [08:24<23:15,  5.29step/s, loss=0.045059, elapsed=8.4min]

Entraînement:  26%|██▋       | 2625/10000 [08:24<23:15,  5.29step/s, loss=0.156230, elapsed=8.4min]

Entraînement:  26%|██▋       | 2626/10000 [08:24<23:20,  5.27step/s, loss=0.156230, elapsed=8.4min]

Entraînement:  26%|██▋       | 2626/10000 [08:24<23:20,  5.27step/s, loss=0.060017, elapsed=8.4min]

Entraînement:  26%|██▋       | 2627/10000 [08:25<23:19,  5.27step/s, loss=0.060017, elapsed=8.4min]

Entraînement:  26%|██▋       | 2627/10000 [08:25<23:19,  5.27step/s, loss=0.056750, elapsed=8.4min]

Entraînement:  26%|██▋       | 2628/10000 [08:25<23:19,  5.27step/s, loss=0.056750, elapsed=8.4min]

Entraînement:  26%|██▋       | 2628/10000 [08:25<23:19,  5.27step/s, loss=0.069214, elapsed=8.4min]

Entraînement:  26%|██▋       | 2629/10000 [08:25<23:21,  5.26step/s, loss=0.069214, elapsed=8.4min]

Entraînement:  26%|██▋       | 2629/10000 [08:25<23:21,  5.26step/s, loss=0.078263, elapsed=8.4min]

Entraînement:  26%|██▋       | 2630/10000 [08:25<23:20,  5.26step/s, loss=0.078263, elapsed=8.4min]

Entraînement:  26%|██▋       | 2630/10000 [08:25<23:20,  5.26step/s, loss=0.093672, elapsed=8.4min]

Entraînement:  26%|██▋       | 2631/10000 [08:25<23:13,  5.29step/s, loss=0.093672, elapsed=8.4min]

Entraînement:  26%|██▋       | 2631/10000 [08:25<23:13,  5.29step/s, loss=0.035866, elapsed=8.4min]

Entraînement:  26%|██▋       | 2632/10000 [08:25<23:15,  5.28step/s, loss=0.035866, elapsed=8.4min]

Entraînement:  26%|██▋       | 2632/10000 [08:25<23:15,  5.28step/s, loss=0.046980, elapsed=8.4min]

Entraînement:  26%|██▋       | 2633/10000 [08:26<23:19,  5.27step/s, loss=0.046980, elapsed=8.4min]

Entraînement:  26%|██▋       | 2633/10000 [08:26<23:19,  5.27step/s, loss=0.131553, elapsed=8.4min]

Entraînement:  26%|██▋       | 2634/10000 [08:26<23:20,  5.26step/s, loss=0.131553, elapsed=8.4min]

Entraînement:  26%|██▋       | 2634/10000 [08:26<23:20,  5.26step/s, loss=0.051286, elapsed=8.4min]

Entraînement:  26%|██▋       | 2635/10000 [08:26<23:22,  5.25step/s, loss=0.051286, elapsed=8.4min]

Entraînement:  26%|██▋       | 2635/10000 [08:26<23:22,  5.25step/s, loss=0.044154, elapsed=8.4min]

Entraînement:  26%|██▋       | 2636/10000 [08:26<23:23,  5.25step/s, loss=0.044154, elapsed=8.4min]

Entraînement:  26%|██▋       | 2636/10000 [08:26<23:23,  5.25step/s, loss=0.082997, elapsed=8.4min]

Entraînement:  26%|██▋       | 2637/10000 [08:26<23:20,  5.26step/s, loss=0.082997, elapsed=8.4min]

Entraînement:  26%|██▋       | 2637/10000 [08:26<23:20,  5.26step/s, loss=0.066662, elapsed=8.4min]

Entraînement:  26%|██▋       | 2638/10000 [08:27<23:17,  5.27step/s, loss=0.066662, elapsed=8.4min]

Entraînement:  26%|██▋       | 2638/10000 [08:27<23:17,  5.27step/s, loss=0.049669, elapsed=8.5min]

Entraînement:  26%|██▋       | 2639/10000 [08:27<23:13,  5.28step/s, loss=0.049669, elapsed=8.5min]

Entraînement:  26%|██▋       | 2639/10000 [08:27<23:13,  5.28step/s, loss=0.033871, elapsed=8.5min]

Entraînement:  26%|██▋       | 2640/10000 [08:27<23:14,  5.28step/s, loss=0.033871, elapsed=8.5min]

Entraînement:  26%|██▋       | 2640/10000 [08:27<23:14,  5.28step/s, loss=0.041058, elapsed=8.5min]

Entraînement:  26%|██▋       | 2641/10000 [08:27<23:15,  5.27step/s, loss=0.041058, elapsed=8.5min]

Entraînement:  26%|██▋       | 2641/10000 [08:27<23:15,  5.27step/s, loss=0.111481, elapsed=8.5min]

Entraînement:  26%|██▋       | 2642/10000 [08:27<23:15,  5.27step/s, loss=0.111481, elapsed=8.5min]

Entraînement:  26%|██▋       | 2642/10000 [08:27<23:15,  5.27step/s, loss=0.032300, elapsed=8.5min]

Entraînement:  26%|██▋       | 2643/10000 [08:28<23:14,  5.27step/s, loss=0.032300, elapsed=8.5min]

Entraînement:  26%|██▋       | 2643/10000 [08:28<23:14,  5.27step/s, loss=0.030220, elapsed=8.5min]

Entraînement:  26%|██▋       | 2644/10000 [08:28<23:15,  5.27step/s, loss=0.030220, elapsed=8.5min]

Entraînement:  26%|██▋       | 2644/10000 [08:28<23:15,  5.27step/s, loss=0.063458, elapsed=8.5min]

Entraînement:  26%|██▋       | 2645/10000 [08:28<23:16,  5.27step/s, loss=0.063458, elapsed=8.5min]

Entraînement:  26%|██▋       | 2645/10000 [08:28<23:16,  5.27step/s, loss=0.046791, elapsed=8.5min]

Entraînement:  26%|██▋       | 2646/10000 [08:28<23:17,  5.26step/s, loss=0.046791, elapsed=8.5min]

Entraînement:  26%|██▋       | 2646/10000 [08:28<23:17,  5.26step/s, loss=0.097536, elapsed=8.5min]

Entraînement:  26%|██▋       | 2647/10000 [08:28<23:15,  5.27step/s, loss=0.097536, elapsed=8.5min]

Entraînement:  26%|██▋       | 2647/10000 [08:28<23:15,  5.27step/s, loss=0.050965, elapsed=8.5min]

Entraînement:  26%|██▋       | 2648/10000 [08:28<23:15,  5.27step/s, loss=0.050965, elapsed=8.5min]

Entraînement:  26%|██▋       | 2648/10000 [08:28<23:15,  5.27step/s, loss=0.027649, elapsed=8.5min]

Entraînement:  26%|██▋       | 2649/10000 [08:29<23:15,  5.27step/s, loss=0.027649, elapsed=8.5min]

Entraînement:  26%|██▋       | 2649/10000 [08:29<23:15,  5.27step/s, loss=0.050427, elapsed=8.5min]

Entraînement:  26%|██▋       | 2650/10000 [08:29<23:13,  5.27step/s, loss=0.050427, elapsed=8.5min]

Entraînement:  26%|██▋       | 2650/10000 [08:29<23:13,  5.27step/s, loss=0.084175, elapsed=8.5min]

Entraînement:  27%|██▋       | 2651/10000 [08:29<23:13,  5.28step/s, loss=0.084175, elapsed=8.5min]

Entraînement:  27%|██▋       | 2651/10000 [08:29<23:13,  5.28step/s, loss=0.044562, elapsed=8.5min]

Entraînement:  27%|██▋       | 2652/10000 [08:29<23:17,  5.26step/s, loss=0.044562, elapsed=8.5min]

Entraînement:  27%|██▋       | 2652/10000 [08:29<23:17,  5.26step/s, loss=0.039094, elapsed=8.5min]

Entraînement:  27%|██▋       | 2653/10000 [08:29<23:18,  5.26step/s, loss=0.039094, elapsed=8.5min]

Entraînement:  27%|██▋       | 2653/10000 [08:29<23:18,  5.26step/s, loss=0.069139, elapsed=8.5min]

Entraînement:  27%|██▋       | 2654/10000 [08:30<23:14,  5.27step/s, loss=0.069139, elapsed=8.5min]

Entraînement:  27%|██▋       | 2654/10000 [08:30<23:14,  5.27step/s, loss=0.083246, elapsed=8.5min]

Entraînement:  27%|██▋       | 2655/10000 [08:30<23:15,  5.26step/s, loss=0.083246, elapsed=8.5min]

Entraînement:  27%|██▋       | 2655/10000 [08:30<23:15,  5.26step/s, loss=0.032906, elapsed=8.5min]

Entraînement:  27%|██▋       | 2656/10000 [08:30<23:16,  5.26step/s, loss=0.032906, elapsed=8.5min]

Entraînement:  27%|██▋       | 2656/10000 [08:30<23:16,  5.26step/s, loss=0.119228, elapsed=8.5min]

Entraînement:  27%|██▋       | 2657/10000 [08:30<23:16,  5.26step/s, loss=0.119228, elapsed=8.5min]

Entraînement:  27%|██▋       | 2657/10000 [08:30<23:16,  5.26step/s, loss=0.061313, elapsed=8.5min]

Entraînement:  27%|██▋       | 2658/10000 [08:30<23:16,  5.26step/s, loss=0.061313, elapsed=8.5min]

Entraînement:  27%|██▋       | 2658/10000 [08:30<23:16,  5.26step/s, loss=0.085316, elapsed=8.5min]

Entraînement:  27%|██▋       | 2659/10000 [08:31<23:16,  5.26step/s, loss=0.085316, elapsed=8.5min]

Entraînement:  27%|██▋       | 2659/10000 [08:31<23:16,  5.26step/s, loss=0.021122, elapsed=8.5min]

Entraînement:  27%|██▋       | 2660/10000 [08:31<23:26,  5.22step/s, loss=0.021122, elapsed=8.5min]

Entraînement:  27%|██▋       | 2660/10000 [08:31<23:26,  5.22step/s, loss=0.082679, elapsed=8.5min]

Entraînement:  27%|██▋       | 2661/10000 [08:31<23:23,  5.23step/s, loss=0.082679, elapsed=8.5min]

Entraînement:  27%|██▋       | 2661/10000 [08:31<23:23,  5.23step/s, loss=0.082233, elapsed=8.5min]

Entraînement:  27%|██▋       | 2662/10000 [08:31<23:21,  5.24step/s, loss=0.082233, elapsed=8.5min]

Entraînement:  27%|██▋       | 2662/10000 [08:31<23:21,  5.24step/s, loss=0.038631, elapsed=8.5min]

Entraînement:  27%|██▋       | 2663/10000 [08:31<23:23,  5.23step/s, loss=0.038631, elapsed=8.5min]

Entraînement:  27%|██▋       | 2663/10000 [08:31<23:23,  5.23step/s, loss=0.102381, elapsed=8.5min]

Entraînement:  27%|██▋       | 2664/10000 [08:32<23:18,  5.24step/s, loss=0.102381, elapsed=8.5min]

Entraînement:  27%|██▋       | 2664/10000 [08:32<23:18,  5.24step/s, loss=0.038367, elapsed=8.5min]

Entraînement:  27%|██▋       | 2665/10000 [08:32<23:22,  5.23step/s, loss=0.038367, elapsed=8.5min]

Entraînement:  27%|██▋       | 2665/10000 [08:32<23:22,  5.23step/s, loss=0.037725, elapsed=8.5min]

Entraînement:  27%|██▋       | 2666/10000 [08:32<23:18,  5.24step/s, loss=0.037725, elapsed=8.5min]

Entraînement:  27%|██▋       | 2666/10000 [08:32<23:18,  5.24step/s, loss=0.074237, elapsed=8.5min]

Entraînement:  27%|██▋       | 2667/10000 [08:32<23:20,  5.23step/s, loss=0.074237, elapsed=8.5min]

Entraînement:  27%|██▋       | 2667/10000 [08:32<23:20,  5.23step/s, loss=0.049160, elapsed=8.5min]

Entraînement:  27%|██▋       | 2668/10000 [08:32<23:23,  5.22step/s, loss=0.049160, elapsed=8.5min]

Entraînement:  27%|██▋       | 2668/10000 [08:32<23:23,  5.22step/s, loss=0.045024, elapsed=8.5min]

Entraînement:  27%|██▋       | 2669/10000 [08:32<23:19,  5.24step/s, loss=0.045024, elapsed=8.5min]

Entraînement:  27%|██▋       | 2669/10000 [08:33<23:19,  5.24step/s, loss=0.034248, elapsed=8.6min]

Entraînement:  27%|██▋       | 2670/10000 [08:33<23:17,  5.25step/s, loss=0.034248, elapsed=8.6min]

Entraînement:  27%|██▋       | 2670/10000 [08:33<23:17,  5.25step/s, loss=0.027433, elapsed=8.6min]

Entraînement:  27%|██▋       | 2671/10000 [08:33<23:13,  5.26step/s, loss=0.027433, elapsed=8.6min]

Entraînement:  27%|██▋       | 2671/10000 [08:33<23:13,  5.26step/s, loss=0.034724, elapsed=8.6min]

Entraînement:  27%|██▋       | 2672/10000 [08:33<23:13,  5.26step/s, loss=0.034724, elapsed=8.6min]

Entraînement:  27%|██▋       | 2672/10000 [08:33<23:13,  5.26step/s, loss=0.070343, elapsed=8.6min]

Entraînement:  27%|██▋       | 2673/10000 [08:33<23:10,  5.27step/s, loss=0.070343, elapsed=8.6min]

Entraînement:  27%|██▋       | 2673/10000 [08:33<23:10,  5.27step/s, loss=0.032236, elapsed=8.6min]

Entraînement:  27%|██▋       | 2674/10000 [08:33<23:10,  5.27step/s, loss=0.032236, elapsed=8.6min]

Entraînement:  27%|██▋       | 2674/10000 [08:33<23:10,  5.27step/s, loss=0.057121, elapsed=8.6min]

Entraînement:  27%|██▋       | 2675/10000 [08:34<23:11,  5.27step/s, loss=0.057121, elapsed=8.6min]

Entraînement:  27%|██▋       | 2675/10000 [08:34<23:11,  5.27step/s, loss=0.047342, elapsed=8.6min]

Entraînement:  27%|██▋       | 2676/10000 [08:34<23:14,  5.25step/s, loss=0.047342, elapsed=8.6min]

Entraînement:  27%|██▋       | 2676/10000 [08:34<23:14,  5.25step/s, loss=0.025562, elapsed=8.6min]

Entraînement:  27%|██▋       | 2677/10000 [08:34<23:11,  5.26step/s, loss=0.025562, elapsed=8.6min]

Entraînement:  27%|██▋       | 2677/10000 [08:34<23:11,  5.26step/s, loss=0.043453, elapsed=8.6min]

Entraînement:  27%|██▋       | 2678/10000 [08:34<23:12,  5.26step/s, loss=0.043453, elapsed=8.6min]

Entraînement:  27%|██▋       | 2678/10000 [08:34<23:12,  5.26step/s, loss=0.048014, elapsed=8.6min]

Entraînement:  27%|██▋       | 2679/10000 [08:34<23:10,  5.26step/s, loss=0.048014, elapsed=8.6min]

Entraînement:  27%|██▋       | 2679/10000 [08:34<23:10,  5.26step/s, loss=0.031848, elapsed=8.6min]

Entraînement:  27%|██▋       | 2680/10000 [08:35<23:08,  5.27step/s, loss=0.031848, elapsed=8.6min]

Entraînement:  27%|██▋       | 2680/10000 [08:35<23:08,  5.27step/s, loss=0.030544, elapsed=8.6min]

Entraînement:  27%|██▋       | 2681/10000 [08:35<23:08,  5.27step/s, loss=0.030544, elapsed=8.6min]

Entraînement:  27%|██▋       | 2681/10000 [08:35<23:08,  5.27step/s, loss=0.065373, elapsed=8.6min]

Entraînement:  27%|██▋       | 2682/10000 [08:35<23:09,  5.27step/s, loss=0.065373, elapsed=8.6min]

Entraînement:  27%|██▋       | 2682/10000 [08:35<23:09,  5.27step/s, loss=0.042165, elapsed=8.6min]

Entraînement:  27%|██▋       | 2683/10000 [08:35<23:07,  5.27step/s, loss=0.042165, elapsed=8.6min]

Entraînement:  27%|██▋       | 2683/10000 [08:35<23:07,  5.27step/s, loss=0.049677, elapsed=8.6min]

Entraînement:  27%|██▋       | 2684/10000 [08:35<23:09,  5.26step/s, loss=0.049677, elapsed=8.6min]

Entraînement:  27%|██▋       | 2684/10000 [08:35<23:09,  5.26step/s, loss=0.029373, elapsed=8.6min]

Entraînement:  27%|██▋       | 2685/10000 [08:36<23:09,  5.26step/s, loss=0.029373, elapsed=8.6min]

Entraînement:  27%|██▋       | 2685/10000 [08:36<23:09,  5.26step/s, loss=0.038712, elapsed=8.6min]

Entraînement:  27%|██▋       | 2686/10000 [08:36<23:10,  5.26step/s, loss=0.038712, elapsed=8.6min]

Entraînement:  27%|██▋       | 2686/10000 [08:36<23:10,  5.26step/s, loss=0.080070, elapsed=8.6min]

Entraînement:  27%|██▋       | 2687/10000 [08:36<23:09,  5.26step/s, loss=0.080070, elapsed=8.6min]

Entraînement:  27%|██▋       | 2687/10000 [08:36<23:09,  5.26step/s, loss=0.044580, elapsed=8.6min]

Entraînement:  27%|██▋       | 2688/10000 [08:36<23:06,  5.27step/s, loss=0.044580, elapsed=8.6min]

Entraînement:  27%|██▋       | 2688/10000 [08:36<23:06,  5.27step/s, loss=0.039129, elapsed=8.6min]

Entraînement:  27%|██▋       | 2689/10000 [08:36<23:08,  5.27step/s, loss=0.039129, elapsed=8.6min]

Entraînement:  27%|██▋       | 2689/10000 [08:36<23:08,  5.27step/s, loss=0.027638, elapsed=8.6min]

Entraînement:  27%|██▋       | 2690/10000 [08:36<23:05,  5.28step/s, loss=0.027638, elapsed=8.6min]

Entraînement:  27%|██▋       | 2690/10000 [08:36<23:05,  5.28step/s, loss=0.063655, elapsed=8.6min]

Entraînement:  27%|██▋       | 2691/10000 [08:37<23:05,  5.28step/s, loss=0.063655, elapsed=8.6min]

Entraînement:  27%|██▋       | 2691/10000 [08:37<23:05,  5.28step/s, loss=0.066625, elapsed=8.6min]

Entraînement:  27%|██▋       | 2692/10000 [08:37<23:05,  5.27step/s, loss=0.066625, elapsed=8.6min]

Entraînement:  27%|██▋       | 2692/10000 [08:37<23:05,  5.27step/s, loss=0.057451, elapsed=8.6min]

Entraînement:  27%|██▋       | 2693/10000 [08:37<23:08,  5.26step/s, loss=0.057451, elapsed=8.6min]

Entraînement:  27%|██▋       | 2693/10000 [08:37<23:08,  5.26step/s, loss=0.073772, elapsed=8.6min]

Entraînement:  27%|██▋       | 2694/10000 [08:37<23:07,  5.27step/s, loss=0.073772, elapsed=8.6min]

Entraînement:  27%|██▋       | 2694/10000 [08:37<23:07,  5.27step/s, loss=0.021731, elapsed=8.6min]

Entraînement:  27%|██▋       | 2695/10000 [08:37<23:08,  5.26step/s, loss=0.021731, elapsed=8.6min]

Entraînement:  27%|██▋       | 2695/10000 [08:37<23:08,  5.26step/s, loss=0.032480, elapsed=8.6min]

Entraînement:  27%|██▋       | 2696/10000 [08:38<23:06,  5.27step/s, loss=0.032480, elapsed=8.6min]

Entraînement:  27%|██▋       | 2696/10000 [08:38<23:06,  5.27step/s, loss=0.028479, elapsed=8.6min]

Entraînement:  27%|██▋       | 2697/10000 [08:38<23:06,  5.27step/s, loss=0.028479, elapsed=8.6min]

Entraînement:  27%|██▋       | 2697/10000 [08:38<23:06,  5.27step/s, loss=0.036329, elapsed=8.6min]

Entraînement:  27%|██▋       | 2698/10000 [08:38<23:06,  5.27step/s, loss=0.036329, elapsed=8.6min]

Entraînement:  27%|██▋       | 2698/10000 [08:38<23:06,  5.27step/s, loss=0.071086, elapsed=8.6min]

Entraînement:  27%|██▋       | 2699/10000 [08:38<23:09,  5.25step/s, loss=0.071086, elapsed=8.6min]

Entraînement:  27%|██▋       | 2699/10000 [08:38<23:09,  5.25step/s, loss=0.089632, elapsed=8.6min]

Entraînement:  27%|██▋       | 2700/10000 [08:38<23:08,  5.26step/s, loss=0.089632, elapsed=8.6min]

Entraînement:  27%|██▋       | 2700/10000 [08:38<23:08,  5.26step/s, loss=0.027933, elapsed=8.6min]

Entraînement:  27%|██▋       | 2700/10000 [08:38<23:08,  5.26step/s, loss=0.027933, elapsed=8.6min]

Entraînement:  27%|██▋       | 2701/10000 [08:39<23:26,  5.19step/s, loss=0.027933, elapsed=8.6min]

Entraînement:  27%|██▋       | 2701/10000 [08:39<23:26,  5.19step/s, loss=0.061326, elapsed=8.7min]

Step 2700/10000 | Train loss: 0.027933 | Elapsed: 8.6min | ETA: 23.4min

Entraînement:  27%|██▋       | 2702/10000 [08:39<23:18,  5.22step/s, loss=0.061326, elapsed=8.7min]

Entraînement:  27%|██▋       | 2702/10000 [08:39<23:18,  5.22step/s, loss=0.111802, elapsed=8.7min]

Entraînement:  27%|██▋       | 2703/10000 [08:39<23:14,  5.23step/s, loss=0.111802, elapsed=8.7min]

Entraînement:  27%|██▋       | 2703/10000 [08:39<23:14,  5.23step/s, loss=0.061057, elapsed=8.7min]

Entraînement:  27%|██▋       | 2704/10000 [08:39<23:23,  5.20step/s, loss=0.061057, elapsed=8.7min]

Entraînement:  27%|██▋       | 2704/10000 [08:39<23:23,  5.20step/s, loss=0.023154, elapsed=8.7min]

Entraînement:  27%|██▋       | 2705/10000 [08:39<23:23,  5.20step/s, loss=0.023154, elapsed=8.7min]

Entraînement:  27%|██▋       | 2705/10000 [08:39<23:23,  5.20step/s, loss=0.071741, elapsed=8.7min]

Entraînement:  27%|██▋       | 2706/10000 [08:40<23:23,  5.20step/s, loss=0.071741, elapsed=8.7min]

Entraînement:  27%|██▋       | 2706/10000 [08:40<23:23,  5.20step/s, loss=0.060621, elapsed=8.7min]

Entraînement:  27%|██▋       | 2707/10000 [08:40<23:24,  5.19step/s, loss=0.060621, elapsed=8.7min]

Entraînement:  27%|██▋       | 2707/10000 [08:40<23:24,  5.19step/s, loss=0.077670, elapsed=8.7min]

Entraînement:  27%|██▋       | 2708/10000 [08:40<23:23,  5.20step/s, loss=0.077670, elapsed=8.7min]

Entraînement:  27%|██▋       | 2708/10000 [08:40<23:23,  5.20step/s, loss=0.041028, elapsed=8.7min]

Entraînement:  27%|██▋       | 2709/10000 [08:40<23:23,  5.19step/s, loss=0.041028, elapsed=8.7min]

Entraînement:  27%|██▋       | 2709/10000 [08:40<23:23,  5.19step/s, loss=0.036679, elapsed=8.7min]

Entraînement:  27%|██▋       | 2710/10000 [08:40<23:24,  5.19step/s, loss=0.036679, elapsed=8.7min]

Entraînement:  27%|██▋       | 2710/10000 [08:40<23:24,  5.19step/s, loss=0.069151, elapsed=8.7min]

Entraînement:  27%|██▋       | 2711/10000 [08:41<23:23,  5.19step/s, loss=0.069151, elapsed=8.7min]

Entraînement:  27%|██▋       | 2711/10000 [08:41<23:23,  5.19step/s, loss=0.038122, elapsed=8.7min]

Entraînement:  27%|██▋       | 2712/10000 [08:41<23:24,  5.19step/s, loss=0.038122, elapsed=8.7min]

Entraînement:  27%|██▋       | 2712/10000 [08:41<23:24,  5.19step/s, loss=0.113909, elapsed=8.7min]

Entraînement:  27%|██▋       | 2713/10000 [08:41<23:23,  5.19step/s, loss=0.113909, elapsed=8.7min]

Entraînement:  27%|██▋       | 2713/10000 [08:41<23:23,  5.19step/s, loss=0.111010, elapsed=8.7min]

Entraînement:  27%|██▋       | 2714/10000 [08:41<23:24,  5.19step/s, loss=0.111010, elapsed=8.7min]

Entraînement:  27%|██▋       | 2714/10000 [08:41<23:24,  5.19step/s, loss=0.091806, elapsed=8.7min]

Entraînement:  27%|██▋       | 2715/10000 [08:41<23:19,  5.20step/s, loss=0.091806, elapsed=8.7min]

Entraînement:  27%|██▋       | 2715/10000 [08:41<23:19,  5.20step/s, loss=0.086144, elapsed=8.7min]

Entraînement:  27%|██▋       | 2716/10000 [08:41<23:21,  5.20step/s, loss=0.086144, elapsed=8.7min]

Entraînement:  27%|██▋       | 2716/10000 [08:41<23:21,  5.20step/s, loss=0.030469, elapsed=8.7min]

Entraînement:  27%|██▋       | 2717/10000 [08:42<23:21,  5.20step/s, loss=0.030469, elapsed=8.7min]

Entraînement:  27%|██▋       | 2717/10000 [08:42<23:21,  5.20step/s, loss=0.090999, elapsed=8.7min]

Entraînement:  27%|██▋       | 2718/10000 [08:42<23:21,  5.20step/s, loss=0.090999, elapsed=8.7min]

Entraînement:  27%|██▋       | 2718/10000 [08:42<23:21,  5.20step/s, loss=0.042521, elapsed=8.7min]

Entraînement:  27%|██▋       | 2719/10000 [08:42<23:21,  5.19step/s, loss=0.042521, elapsed=8.7min]

Entraînement:  27%|██▋       | 2719/10000 [08:42<23:21,  5.19step/s, loss=0.037691, elapsed=8.7min]

Entraînement:  27%|██▋       | 2720/10000 [08:42<23:22,  5.19step/s, loss=0.037691, elapsed=8.7min]

Entraînement:  27%|██▋       | 2720/10000 [08:42<23:22,  5.19step/s, loss=0.020646, elapsed=8.7min]

Entraînement:  27%|██▋       | 2721/10000 [08:42<23:23,  5.19step/s, loss=0.020646, elapsed=8.7min]

Entraînement:  27%|██▋       | 2721/10000 [08:42<23:23,  5.19step/s, loss=0.021899, elapsed=8.7min]

Entraînement:  27%|██▋       | 2722/10000 [08:43<23:12,  5.23step/s, loss=0.021899, elapsed=8.7min]

Entraînement:  27%|██▋       | 2722/10000 [08:43<23:12,  5.23step/s, loss=0.027856, elapsed=8.7min]

Entraînement:  27%|██▋       | 2723/10000 [08:43<23:15,  5.22step/s, loss=0.027856, elapsed=8.7min]

Entraînement:  27%|██▋       | 2723/10000 [08:43<23:15,  5.22step/s, loss=0.067121, elapsed=8.7min]

Entraînement:  27%|██▋       | 2724/10000 [08:43<23:15,  5.21step/s, loss=0.067121, elapsed=8.7min]

Entraînement:  27%|██▋       | 2724/10000 [08:43<23:15,  5.21step/s, loss=0.072436, elapsed=8.7min]

Entraînement:  27%|██▋       | 2725/10000 [08:43<23:17,  5.21step/s, loss=0.072436, elapsed=8.7min]

Entraînement:  27%|██▋       | 2725/10000 [08:43<23:17,  5.21step/s, loss=0.078078, elapsed=8.7min]

Entraînement:  27%|██▋       | 2726/10000 [08:43<23:31,  5.15step/s, loss=0.078078, elapsed=8.7min]

Entraînement:  27%|██▋       | 2726/10000 [08:43<23:31,  5.15step/s, loss=0.073394, elapsed=8.7min]

Entraînement:  27%|██▋       | 2727/10000 [08:44<23:21,  5.19step/s, loss=0.073394, elapsed=8.7min]

Entraînement:  27%|██▋       | 2727/10000 [08:44<23:21,  5.19step/s, loss=0.032214, elapsed=8.7min]

Entraînement:  27%|██▋       | 2728/10000 [08:44<23:13,  5.22step/s, loss=0.032214, elapsed=8.7min]

Entraînement:  27%|██▋       | 2728/10000 [08:44<23:13,  5.22step/s, loss=0.035291, elapsed=8.7min]

Entraînement:  27%|██▋       | 2729/10000 [08:44<23:08,  5.24step/s, loss=0.035291, elapsed=8.7min]

Entraînement:  27%|██▋       | 2729/10000 [08:44<23:08,  5.24step/s, loss=0.051573, elapsed=8.7min]

Entraînement:  27%|██▋       | 2730/10000 [08:44<23:01,  5.26step/s, loss=0.051573, elapsed=8.7min]

Entraînement:  27%|██▋       | 2730/10000 [08:44<23:01,  5.26step/s, loss=0.055387, elapsed=8.7min]

Entraînement:  27%|██▋       | 2731/10000 [08:44<23:02,  5.26step/s, loss=0.055387, elapsed=8.7min]

Entraînement:  27%|██▋       | 2731/10000 [08:44<23:02,  5.26step/s, loss=0.076893, elapsed=8.7min]

Entraînement:  27%|██▋       | 2732/10000 [08:45<23:00,  5.27step/s, loss=0.076893, elapsed=8.7min]

Entraînement:  27%|██▋       | 2732/10000 [08:45<23:00,  5.27step/s, loss=0.098158, elapsed=8.8min]

Entraînement:  27%|██▋       | 2733/10000 [08:45<22:59,  5.27step/s, loss=0.098158, elapsed=8.8min]

Entraînement:  27%|██▋       | 2733/10000 [08:45<22:59,  5.27step/s, loss=0.070807, elapsed=8.8min]

Entraînement:  27%|██▋       | 2734/10000 [08:45<22:58,  5.27step/s, loss=0.070807, elapsed=8.8min]

Entraînement:  27%|██▋       | 2734/10000 [08:45<22:58,  5.27step/s, loss=0.074179, elapsed=8.8min]

Entraînement:  27%|██▋       | 2735/10000 [08:45<22:58,  5.27step/s, loss=0.074179, elapsed=8.8min]

Entraînement:  27%|██▋       | 2735/10000 [08:45<22:58,  5.27step/s, loss=0.050129, elapsed=8.8min]

Entraînement:  27%|██▋       | 2736/10000 [08:45<22:58,  5.27step/s, loss=0.050129, elapsed=8.8min]

Entraînement:  27%|██▋       | 2736/10000 [08:45<22:58,  5.27step/s, loss=0.075409, elapsed=8.8min]

Entraînement:  27%|██▋       | 2737/10000 [08:45<22:55,  5.28step/s, loss=0.075409, elapsed=8.8min]

Entraînement:  27%|██▋       | 2737/10000 [08:45<22:55,  5.28step/s, loss=0.028360, elapsed=8.8min]

Entraînement:  27%|██▋       | 2738/10000 [08:46<22:56,  5.28step/s, loss=0.028360, elapsed=8.8min]

Entraînement:  27%|██▋       | 2738/10000 [08:46<22:56,  5.28step/s, loss=0.032125, elapsed=8.8min]

Entraînement:  27%|██▋       | 2739/10000 [08:46<22:55,  5.28step/s, loss=0.032125, elapsed=8.8min]

Entraînement:  27%|██▋       | 2739/10000 [08:46<22:55,  5.28step/s, loss=0.049006, elapsed=8.8min]

Entraînement:  27%|██▋       | 2740/10000 [08:46<22:53,  5.29step/s, loss=0.049006, elapsed=8.8min]

Entraînement:  27%|██▋       | 2740/10000 [08:46<22:53,  5.29step/s, loss=0.052540, elapsed=8.8min]

Entraînement:  27%|██▋       | 2741/10000 [08:46<23:02,  5.25step/s, loss=0.052540, elapsed=8.8min]

Entraînement:  27%|██▋       | 2741/10000 [08:46<23:02,  5.25step/s, loss=0.101945, elapsed=8.8min]

Entraînement:  27%|██▋       | 2742/10000 [08:46<22:59,  5.26step/s, loss=0.101945, elapsed=8.8min]

Entraînement:  27%|██▋       | 2742/10000 [08:46<22:59,  5.26step/s, loss=0.087630, elapsed=8.8min]

Entraînement:  27%|██▋       | 2743/10000 [08:47<22:58,  5.27step/s, loss=0.087630, elapsed=8.8min]

Entraînement:  27%|██▋       | 2743/10000 [08:47<22:58,  5.27step/s, loss=0.145843, elapsed=8.8min]

Entraînement:  27%|██▋       | 2744/10000 [08:47<22:54,  5.28step/s, loss=0.145843, elapsed=8.8min]

Entraînement:  27%|██▋       | 2744/10000 [08:47<22:54,  5.28step/s, loss=0.040718, elapsed=8.8min]

Entraînement:  27%|██▋       | 2745/10000 [08:47<22:55,  5.27step/s, loss=0.040718, elapsed=8.8min]

Entraînement:  27%|██▋       | 2745/10000 [08:47<22:55,  5.27step/s, loss=0.072237, elapsed=8.8min]

Entraînement:  27%|██▋       | 2746/10000 [08:47<22:53,  5.28step/s, loss=0.072237, elapsed=8.8min]

Entraînement:  27%|██▋       | 2746/10000 [08:47<22:53,  5.28step/s, loss=0.024026, elapsed=8.8min]

Entraînement:  27%|██▋       | 2747/10000 [08:47<22:52,  5.28step/s, loss=0.024026, elapsed=8.8min]

Entraînement:  27%|██▋       | 2747/10000 [08:47<22:52,  5.28step/s, loss=0.087629, elapsed=8.8min]

Entraînement:  27%|██▋       | 2748/10000 [08:48<22:51,  5.29step/s, loss=0.087629, elapsed=8.8min]

Entraînement:  27%|██▋       | 2748/10000 [08:48<22:51,  5.29step/s, loss=0.028368, elapsed=8.8min]

Entraînement:  27%|██▋       | 2749/10000 [08:48<22:49,  5.29step/s, loss=0.028368, elapsed=8.8min]

Entraînement:  27%|██▋       | 2749/10000 [08:48<22:49,  5.29step/s, loss=0.142333, elapsed=8.8min]

Entraînement:  28%|██▊       | 2750/10000 [08:48<22:53,  5.28step/s, loss=0.142333, elapsed=8.8min]

Entraînement:  28%|██▊       | 2750/10000 [08:48<22:53,  5.28step/s, loss=0.079943, elapsed=8.8min]

Entraînement:  28%|██▊       | 2751/10000 [08:48<22:55,  5.27step/s, loss=0.079943, elapsed=8.8min]

Entraînement:  28%|██▊       | 2751/10000 [08:48<22:55,  5.27step/s, loss=0.092037, elapsed=8.8min]

Entraînement:  28%|██▊       | 2752/10000 [08:48<22:54,  5.27step/s, loss=0.092037, elapsed=8.8min]

Entraînement:  28%|██▊       | 2752/10000 [08:48<22:54,  5.27step/s, loss=0.054562, elapsed=8.8min]

Entraînement:  28%|██▊       | 2753/10000 [08:49<22:54,  5.27step/s, loss=0.054562, elapsed=8.8min]

Entraînement:  28%|██▊       | 2753/10000 [08:49<22:54,  5.27step/s, loss=0.080697, elapsed=8.8min]

Entraînement:  28%|██▊       | 2754/10000 [08:49<22:53,  5.27step/s, loss=0.080697, elapsed=8.8min]

Entraînement:  28%|██▊       | 2754/10000 [08:49<22:53,  5.27step/s, loss=0.024748, elapsed=8.8min]

Entraînement:  28%|██▊       | 2755/10000 [08:49<22:53,  5.27step/s, loss=0.024748, elapsed=8.8min]

Entraînement:  28%|██▊       | 2755/10000 [08:49<22:53,  5.27step/s, loss=0.051416, elapsed=8.8min]

Entraînement:  28%|██▊       | 2756/10000 [08:49<22:51,  5.28step/s, loss=0.051416, elapsed=8.8min]

Entraînement:  28%|██▊       | 2756/10000 [08:49<22:51,  5.28step/s, loss=0.049130, elapsed=8.8min]

Entraînement:  28%|██▊       | 2757/10000 [08:49<22:48,  5.29step/s, loss=0.049130, elapsed=8.8min]

Entraînement:  28%|██▊       | 2757/10000 [08:49<22:48,  5.29step/s, loss=0.077386, elapsed=8.8min]

Entraînement:  28%|██▊       | 2758/10000 [08:49<22:51,  5.28step/s, loss=0.077386, elapsed=8.8min]

Entraînement:  28%|██▊       | 2758/10000 [08:49<22:51,  5.28step/s, loss=0.050148, elapsed=8.8min]

Entraînement:  28%|██▊       | 2759/10000 [08:50<22:52,  5.28step/s, loss=0.050148, elapsed=8.8min]

Entraînement:  28%|██▊       | 2759/10000 [08:50<22:52,  5.28step/s, loss=0.093977, elapsed=8.8min]

Entraînement:  28%|██▊       | 2760/10000 [08:50<22:53,  5.27step/s, loss=0.093977, elapsed=8.8min]

Entraînement:  28%|██▊       | 2760/10000 [08:50<22:53,  5.27step/s, loss=0.068488, elapsed=8.8min]

Entraînement:  28%|██▊       | 2761/10000 [08:50<22:52,  5.27step/s, loss=0.068488, elapsed=8.8min]

Entraînement:  28%|██▊       | 2761/10000 [08:50<22:52,  5.27step/s, loss=0.050595, elapsed=8.8min]

Entraînement:  28%|██▊       | 2762/10000 [08:50<22:50,  5.28step/s, loss=0.050595, elapsed=8.8min]

Entraînement:  28%|██▊       | 2762/10000 [08:50<22:50,  5.28step/s, loss=0.057375, elapsed=8.8min]

Entraînement:  28%|██▊       | 2763/10000 [08:50<22:49,  5.28step/s, loss=0.057375, elapsed=8.8min]

Entraînement:  28%|██▊       | 2763/10000 [08:50<22:49,  5.28step/s, loss=0.092468, elapsed=8.8min]

Entraînement:  28%|██▊       | 2764/10000 [08:51<22:47,  5.29step/s, loss=0.092468, elapsed=8.8min]

Entraînement:  28%|██▊       | 2764/10000 [08:51<22:47,  5.29step/s, loss=0.038336, elapsed=8.9min]

Entraînement:  28%|██▊       | 2765/10000 [08:51<22:47,  5.29step/s, loss=0.038336, elapsed=8.9min]

Entraînement:  28%|██▊       | 2765/10000 [08:51<22:47,  5.29step/s, loss=0.084156, elapsed=8.9min]

Entraînement:  28%|██▊       | 2766/10000 [08:51<22:48,  5.29step/s, loss=0.084156, elapsed=8.9min]

Entraînement:  28%|██▊       | 2766/10000 [08:51<22:48,  5.29step/s, loss=0.027129, elapsed=8.9min]

Entraînement:  28%|██▊       | 2767/10000 [08:51<22:49,  5.28step/s, loss=0.027129, elapsed=8.9min]

Entraînement:  28%|██▊       | 2767/10000 [08:51<22:49,  5.28step/s, loss=0.032392, elapsed=8.9min]

Entraînement:  28%|██▊       | 2768/10000 [08:51<22:49,  5.28step/s, loss=0.032392, elapsed=8.9min]

Entraînement:  28%|██▊       | 2768/10000 [08:51<22:49,  5.28step/s, loss=0.039061, elapsed=8.9min]

Entraînement:  28%|██▊       | 2769/10000 [08:52<22:48,  5.28step/s, loss=0.039061, elapsed=8.9min]

Entraînement:  28%|██▊       | 2769/10000 [08:52<22:48,  5.28step/s, loss=0.043234, elapsed=8.9min]

Entraînement:  28%|██▊       | 2770/10000 [08:52<22:47,  5.29step/s, loss=0.043234, elapsed=8.9min]

Entraînement:  28%|██▊       | 2770/10000 [08:52<22:47,  5.29step/s, loss=0.072941, elapsed=8.9min]

Entraînement:  28%|██▊       | 2771/10000 [08:52<22:45,  5.29step/s, loss=0.072941, elapsed=8.9min]

Entraînement:  28%|██▊       | 2771/10000 [08:52<22:45,  5.29step/s, loss=0.059992, elapsed=8.9min]

Entraînement:  28%|██▊       | 2772/10000 [08:52<22:51,  5.27step/s, loss=0.059992, elapsed=8.9min]

Entraînement:  28%|██▊       | 2772/10000 [08:52<22:51,  5.27step/s, loss=0.069630, elapsed=8.9min]

Entraînement:  28%|██▊       | 2773/10000 [08:52<22:49,  5.28step/s, loss=0.069630, elapsed=8.9min]

Entraînement:  28%|██▊       | 2773/10000 [08:52<22:49,  5.28step/s, loss=0.163945, elapsed=8.9min]

Entraînement:  28%|██▊       | 2774/10000 [08:52<22:48,  5.28step/s, loss=0.163945, elapsed=8.9min]

Entraînement:  28%|██▊       | 2774/10000 [08:52<22:48,  5.28step/s, loss=0.030973, elapsed=8.9min]

Entraînement:  28%|██▊       | 2775/10000 [08:53<22:51,  5.27step/s, loss=0.030973, elapsed=8.9min]

Entraînement:  28%|██▊       | 2775/10000 [08:53<22:51,  5.27step/s, loss=0.062914, elapsed=8.9min]

Entraînement:  28%|██▊       | 2776/10000 [08:53<22:49,  5.28step/s, loss=0.062914, elapsed=8.9min]

Entraînement:  28%|██▊       | 2776/10000 [08:53<22:49,  5.28step/s, loss=0.044047, elapsed=8.9min]

Entraînement:  28%|██▊       | 2777/10000 [08:53<22:51,  5.27step/s, loss=0.044047, elapsed=8.9min]

Entraînement:  28%|██▊       | 2777/10000 [08:53<22:51,  5.27step/s, loss=0.029414, elapsed=8.9min]

Entraînement:  28%|██▊       | 2778/10000 [08:53<22:50,  5.27step/s, loss=0.029414, elapsed=8.9min]

Entraînement:  28%|██▊       | 2778/10000 [08:53<22:50,  5.27step/s, loss=0.108861, elapsed=8.9min]

Entraînement:  28%|██▊       | 2779/10000 [08:53<22:53,  5.26step/s, loss=0.108861, elapsed=8.9min]

Entraînement:  28%|██▊       | 2779/10000 [08:53<22:53,  5.26step/s, loss=0.043282, elapsed=8.9min]

Entraînement:  28%|██▊       | 2780/10000 [08:54<22:52,  5.26step/s, loss=0.043282, elapsed=8.9min]

Entraînement:  28%|██▊       | 2780/10000 [08:54<22:52,  5.26step/s, loss=0.030316, elapsed=8.9min]

Entraînement:  28%|██▊       | 2781/10000 [08:54<22:52,  5.26step/s, loss=0.030316, elapsed=8.9min]

Entraînement:  28%|██▊       | 2781/10000 [08:54<22:52,  5.26step/s, loss=0.089486, elapsed=8.9min]

Entraînement:  28%|██▊       | 2782/10000 [08:54<22:53,  5.25step/s, loss=0.089486, elapsed=8.9min]

Entraînement:  28%|██▊       | 2782/10000 [08:54<22:53,  5.25step/s, loss=0.084638, elapsed=8.9min]

Entraînement:  28%|██▊       | 2783/10000 [08:54<22:49,  5.27step/s, loss=0.084638, elapsed=8.9min]

Entraînement:  28%|██▊       | 2783/10000 [08:54<22:49,  5.27step/s, loss=0.042581, elapsed=8.9min]

Entraînement:  28%|██▊       | 2784/10000 [08:54<22:51,  5.26step/s, loss=0.042581, elapsed=8.9min]

Entraînement:  28%|██▊       | 2784/10000 [08:54<22:51,  5.26step/s, loss=0.048251, elapsed=8.9min]

Entraînement:  28%|██▊       | 2785/10000 [08:55<22:48,  5.27step/s, loss=0.048251, elapsed=8.9min]

Entraînement:  28%|██▊       | 2785/10000 [08:55<22:48,  5.27step/s, loss=0.063942, elapsed=8.9min]

Entraînement:  28%|██▊       | 2786/10000 [08:55<22:48,  5.27step/s, loss=0.063942, elapsed=8.9min]

Entraînement:  28%|██▊       | 2786/10000 [08:55<22:48,  5.27step/s, loss=0.081329, elapsed=8.9min]

Entraînement:  28%|██▊       | 2787/10000 [08:55<22:47,  5.28step/s, loss=0.081329, elapsed=8.9min]

Entraînement:  28%|██▊       | 2787/10000 [08:55<22:47,  5.28step/s, loss=0.060825, elapsed=8.9min]

Entraînement:  28%|██▊       | 2788/10000 [08:55<22:41,  5.30step/s, loss=0.060825, elapsed=8.9min]

Entraînement:  28%|██▊       | 2788/10000 [08:55<22:41,  5.30step/s, loss=0.094109, elapsed=8.9min]

Entraînement:  28%|██▊       | 2789/10000 [08:55<22:44,  5.28step/s, loss=0.094109, elapsed=8.9min]

Entraînement:  28%|██▊       | 2789/10000 [08:55<22:44,  5.28step/s, loss=0.097295, elapsed=8.9min]

Entraînement:  28%|██▊       | 2790/10000 [08:56<22:45,  5.28step/s, loss=0.097295, elapsed=8.9min]

Entraînement:  28%|██▊       | 2790/10000 [08:56<22:45,  5.28step/s, loss=0.045807, elapsed=8.9min]

Entraînement:  28%|██▊       | 2791/10000 [08:56<22:47,  5.27step/s, loss=0.045807, elapsed=8.9min]

Entraînement:  28%|██▊       | 2791/10000 [08:56<22:47,  5.27step/s, loss=0.101973, elapsed=8.9min]

Entraînement:  28%|██▊       | 2792/10000 [08:56<22:44,  5.28step/s, loss=0.101973, elapsed=8.9min]

Entraînement:  28%|██▊       | 2792/10000 [08:56<22:44,  5.28step/s, loss=0.057055, elapsed=8.9min]

Entraînement:  28%|██▊       | 2793/10000 [08:56<22:45,  5.28step/s, loss=0.057055, elapsed=8.9min]

Entraînement:  28%|██▊       | 2793/10000 [08:56<22:45,  5.28step/s, loss=0.097927, elapsed=8.9min]

Entraînement:  28%|██▊       | 2794/10000 [08:56<22:44,  5.28step/s, loss=0.097927, elapsed=8.9min]

Entraînement:  28%|██▊       | 2794/10000 [08:56<22:44,  5.28step/s, loss=0.251782, elapsed=8.9min]

Entraînement:  28%|██▊       | 2795/10000 [08:56<22:45,  5.28step/s, loss=0.251782, elapsed=8.9min]

Entraînement:  28%|██▊       | 2795/10000 [08:56<22:45,  5.28step/s, loss=0.063898, elapsed=8.9min]

Entraînement:  28%|██▊       | 2796/10000 [08:57<22:44,  5.28step/s, loss=0.063898, elapsed=8.9min]

Entraînement:  28%|██▊       | 2796/10000 [08:57<22:44,  5.28step/s, loss=0.049663, elapsed=9.0min]

Entraînement:  28%|██▊       | 2797/10000 [08:57<22:43,  5.28step/s, loss=0.049663, elapsed=9.0min]

Entraînement:  28%|██▊       | 2797/10000 [08:57<22:43,  5.28step/s, loss=0.050091, elapsed=9.0min]

Entraînement:  28%|██▊       | 2798/10000 [08:57<22:43,  5.28step/s, loss=0.050091, elapsed=9.0min]

Entraînement:  28%|██▊       | 2798/10000 [08:57<22:43,  5.28step/s, loss=0.037236, elapsed=9.0min]

Entraînement:  28%|██▊       | 2799/10000 [08:57<22:42,  5.28step/s, loss=0.037236, elapsed=9.0min]

Entraînement:  28%|██▊       | 2799/10000 [08:57<22:42,  5.28step/s, loss=0.042721, elapsed=9.0min]

Entraînement:  28%|██▊       | 2800/10000 [08:57<22:41,  5.29step/s, loss=0.042721, elapsed=9.0min]

Entraînement:  28%|██▊       | 2800/10000 [08:57<22:41,  5.29step/s, loss=0.100218, elapsed=9.0min]

Entraînement:  28%|██▊       | 2800/10000 [08:57<22:41,  5.29step/s, loss=0.100218, elapsed=9.0min]

Entraînement:  28%|██▊       | 2801/10000 [08:58<22:53,  5.24step/s, loss=0.100218, elapsed=9.0min]

Entraînement:  28%|██▊       | 2801/10000 [08:58<22:53,  5.24step/s, loss=0.112382, elapsed=9.0min]

Step 2800/10000 | Train loss: 0.100218 | Elapsed: 9.0min | ETA: 23.1min

Entraînement:  28%|██▊       | 2802/10000 [08:58<22:51,  5.25step/s, loss=0.112382, elapsed=9.0min]

Entraînement:  28%|██▊       | 2802/10000 [08:58<22:51,  5.25step/s, loss=0.069389, elapsed=9.0min]

Entraînement:  28%|██▊       | 2803/10000 [08:58<22:49,  5.26step/s, loss=0.069389, elapsed=9.0min]

Entraînement:  28%|██▊       | 2803/10000 [08:58<22:49,  5.26step/s, loss=0.024328, elapsed=9.0min]

Entraînement:  28%|██▊       | 2804/10000 [08:58<22:55,  5.23step/s, loss=0.024328, elapsed=9.0min]

Entraînement:  28%|██▊       | 2804/10000 [08:58<22:55,  5.23step/s, loss=0.046318, elapsed=9.0min]

Entraînement:  28%|██▊       | 2805/10000 [08:58<22:55,  5.23step/s, loss=0.046318, elapsed=9.0min]

Entraînement:  28%|██▊       | 2805/10000 [08:58<22:55,  5.23step/s, loss=0.031686, elapsed=9.0min]

Entraînement:  28%|██▊       | 2806/10000 [08:59<23:02,  5.20step/s, loss=0.031686, elapsed=9.0min]

Entraînement:  28%|██▊       | 2806/10000 [08:59<23:02,  5.20step/s, loss=0.066121, elapsed=9.0min]

Entraînement:  28%|██▊       | 2807/10000 [08:59<22:50,  5.25step/s, loss=0.066121, elapsed=9.0min]

Entraînement:  28%|██▊       | 2807/10000 [08:59<22:50,  5.25step/s, loss=0.043552, elapsed=9.0min]

Entraînement:  28%|██▊       | 2808/10000 [08:59<22:42,  5.28step/s, loss=0.043552, elapsed=9.0min]

Entraînement:  28%|██▊       | 2808/10000 [08:59<22:42,  5.28step/s, loss=0.083304, elapsed=9.0min]

Entraînement:  28%|██▊       | 2809/10000 [08:59<22:41,  5.28step/s, loss=0.083304, elapsed=9.0min]

Entraînement:  28%|██▊       | 2809/10000 [08:59<22:41,  5.28step/s, loss=0.064932, elapsed=9.0min]

Entraînement:  28%|██▊       | 2810/10000 [08:59<22:40,  5.29step/s, loss=0.064932, elapsed=9.0min]

Entraînement:  28%|██▊       | 2810/10000 [08:59<22:40,  5.29step/s, loss=0.043990, elapsed=9.0min]

Entraînement:  28%|██▊       | 2811/10000 [09:00<22:41,  5.28step/s, loss=0.043990, elapsed=9.0min]

Entraînement:  28%|██▊       | 2811/10000 [09:00<22:41,  5.28step/s, loss=0.113144, elapsed=9.0min]

Entraînement:  28%|██▊       | 2812/10000 [09:00<22:45,  5.26step/s, loss=0.113144, elapsed=9.0min]

Entraînement:  28%|██▊       | 2812/10000 [09:00<22:45,  5.26step/s, loss=0.105867, elapsed=9.0min]

Entraînement:  28%|██▊       | 2813/10000 [09:00<22:46,  5.26step/s, loss=0.105867, elapsed=9.0min]

Entraînement:  28%|██▊       | 2813/10000 [09:00<22:46,  5.26step/s, loss=0.056716, elapsed=9.0min]

Entraînement:  28%|██▊       | 2814/10000 [09:00<22:46,  5.26step/s, loss=0.056716, elapsed=9.0min]

Entraînement:  28%|██▊       | 2814/10000 [09:00<22:46,  5.26step/s, loss=0.078516, elapsed=9.0min]

Entraînement:  28%|██▊       | 2815/10000 [09:00<22:56,  5.22step/s, loss=0.078516, elapsed=9.0min]

Entraînement:  28%|██▊       | 2815/10000 [09:00<22:56,  5.22step/s, loss=0.076883, elapsed=9.0min]

Entraînement:  28%|██▊       | 2816/10000 [09:00<22:49,  5.24step/s, loss=0.076883, elapsed=9.0min]

Entraînement:  28%|██▊       | 2816/10000 [09:00<22:49,  5.24step/s, loss=0.142912, elapsed=9.0min]

Entraînement:  28%|██▊       | 2817/10000 [09:01<22:46,  5.26step/s, loss=0.142912, elapsed=9.0min]

Entraînement:  28%|██▊       | 2817/10000 [09:01<22:46,  5.26step/s, loss=0.074177, elapsed=9.0min]

Entraînement:  28%|██▊       | 2818/10000 [09:01<22:45,  5.26step/s, loss=0.074177, elapsed=9.0min]

Entraînement:  28%|██▊       | 2818/10000 [09:01<22:45,  5.26step/s, loss=0.101428, elapsed=9.0min]

Entraînement:  28%|██▊       | 2819/10000 [09:01<22:42,  5.27step/s, loss=0.101428, elapsed=9.0min]

Entraînement:  28%|██▊       | 2819/10000 [09:01<22:42,  5.27step/s, loss=0.099024, elapsed=9.0min]

Entraînement:  28%|██▊       | 2820/10000 [09:01<22:42,  5.27step/s, loss=0.099024, elapsed=9.0min]

Entraînement:  28%|██▊       | 2820/10000 [09:01<22:42,  5.27step/s, loss=0.029403, elapsed=9.0min]

Entraînement:  28%|██▊       | 2821/10000 [09:01<22:41,  5.27step/s, loss=0.029403, elapsed=9.0min]

Entraînement:  28%|██▊       | 2821/10000 [09:01<22:41,  5.27step/s, loss=0.065900, elapsed=9.0min]

Entraînement:  28%|██▊       | 2822/10000 [09:02<22:52,  5.23step/s, loss=0.065900, elapsed=9.0min]

Entraînement:  28%|██▊       | 2822/10000 [09:02<22:52,  5.23step/s, loss=0.051049, elapsed=9.0min]

Entraînement:  28%|██▊       | 2823/10000 [09:02<22:49,  5.24step/s, loss=0.051049, elapsed=9.0min]

Entraînement:  28%|██▊       | 2823/10000 [09:02<22:49,  5.24step/s, loss=0.065413, elapsed=9.0min]

Entraînement:  28%|██▊       | 2824/10000 [09:02<22:45,  5.26step/s, loss=0.065413, elapsed=9.0min]

Entraînement:  28%|██▊       | 2824/10000 [09:02<22:45,  5.26step/s, loss=0.054684, elapsed=9.0min]

Entraînement:  28%|██▊       | 2825/10000 [09:02<22:45,  5.26step/s, loss=0.054684, elapsed=9.0min]

Entraînement:  28%|██▊       | 2825/10000 [09:02<22:45,  5.26step/s, loss=0.039770, elapsed=9.0min]

Entraînement:  28%|██▊       | 2826/10000 [09:02<22:43,  5.26step/s, loss=0.039770, elapsed=9.0min]

Entraînement:  28%|██▊       | 2826/10000 [09:02<22:43,  5.26step/s, loss=0.080253, elapsed=9.0min]

Entraînement:  28%|██▊       | 2827/10000 [09:03<22:44,  5.26step/s, loss=0.080253, elapsed=9.0min]

Entraînement:  28%|██▊       | 2827/10000 [09:03<22:44,  5.26step/s, loss=0.040241, elapsed=9.1min]

Entraînement:  28%|██▊       | 2828/10000 [09:03<22:43,  5.26step/s, loss=0.040241, elapsed=9.1min]

Entraînement:  28%|██▊       | 2828/10000 [09:03<22:43,  5.26step/s, loss=0.117835, elapsed=9.1min]

Entraînement:  28%|██▊       | 2829/10000 [09:03<22:43,  5.26step/s, loss=0.117835, elapsed=9.1min]

Entraînement:  28%|██▊       | 2829/10000 [09:03<22:43,  5.26step/s, loss=0.082748, elapsed=9.1min]

Entraînement:  28%|██▊       | 2830/10000 [09:03<22:40,  5.27step/s, loss=0.082748, elapsed=9.1min]

Entraînement:  28%|██▊       | 2830/10000 [09:03<22:40,  5.27step/s, loss=0.055843, elapsed=9.1min]

Entraînement:  28%|██▊       | 2831/10000 [09:03<22:39,  5.28step/s, loss=0.055843, elapsed=9.1min]

Entraînement:  28%|██▊       | 2831/10000 [09:03<22:39,  5.28step/s, loss=0.070581, elapsed=9.1min]

Entraînement:  28%|██▊       | 2832/10000 [09:04<22:38,  5.28step/s, loss=0.070581, elapsed=9.1min]

Entraînement:  28%|██▊       | 2832/10000 [09:04<22:38,  5.28step/s, loss=0.034869, elapsed=9.1min]

Entraînement:  28%|██▊       | 2833/10000 [09:04<22:36,  5.28step/s, loss=0.034869, elapsed=9.1min]

Entraînement:  28%|██▊       | 2833/10000 [09:04<22:36,  5.28step/s, loss=0.036404, elapsed=9.1min]

Entraînement:  28%|██▊       | 2834/10000 [09:04<22:38,  5.27step/s, loss=0.036404, elapsed=9.1min]

Entraînement:  28%|██▊       | 2834/10000 [09:04<22:38,  5.27step/s, loss=0.060520, elapsed=9.1min]

Entraînement:  28%|██▊       | 2835/10000 [09:04<22:37,  5.28step/s, loss=0.060520, elapsed=9.1min]

Entraînement:  28%|██▊       | 2835/10000 [09:04<22:37,  5.28step/s, loss=0.131123, elapsed=9.1min]

Entraînement:  28%|██▊       | 2836/10000 [09:04<22:38,  5.28step/s, loss=0.131123, elapsed=9.1min]

Entraînement:  28%|██▊       | 2836/10000 [09:04<22:38,  5.28step/s, loss=0.043057, elapsed=9.1min]

Entraînement:  28%|██▊       | 2837/10000 [09:04<22:37,  5.28step/s, loss=0.043057, elapsed=9.1min]

Entraînement:  28%|██▊       | 2837/10000 [09:04<22:37,  5.28step/s, loss=0.149140, elapsed=9.1min]

Entraînement:  28%|██▊       | 2838/10000 [09:05<22:37,  5.28step/s, loss=0.149140, elapsed=9.1min]

Entraînement:  28%|██▊       | 2838/10000 [09:05<22:37,  5.28step/s, loss=0.076277, elapsed=9.1min]

Entraînement:  28%|██▊       | 2839/10000 [09:05<22:37,  5.28step/s, loss=0.076277, elapsed=9.1min]

Entraînement:  28%|██▊       | 2839/10000 [09:05<22:37,  5.28step/s, loss=0.032047, elapsed=9.1min]

Entraînement:  28%|██▊       | 2840/10000 [09:05<22:37,  5.28step/s, loss=0.032047, elapsed=9.1min]

Entraînement:  28%|██▊       | 2840/10000 [09:05<22:37,  5.28step/s, loss=0.199359, elapsed=9.1min]

Entraînement:  28%|██▊       | 2841/10000 [09:05<22:37,  5.27step/s, loss=0.199359, elapsed=9.1min]

Entraînement:  28%|██▊       | 2841/10000 [09:05<22:37,  5.27step/s, loss=0.058923, elapsed=9.1min]

Entraînement:  28%|██▊       | 2842/10000 [09:05<22:36,  5.28step/s, loss=0.058923, elapsed=9.1min]

Entraînement:  28%|██▊       | 2842/10000 [09:05<22:36,  5.28step/s, loss=0.061889, elapsed=9.1min]

Entraînement:  28%|██▊       | 2843/10000 [09:06<22:38,  5.27step/s, loss=0.061889, elapsed=9.1min]

Entraînement:  28%|██▊       | 2843/10000 [09:06<22:38,  5.27step/s, loss=0.044572, elapsed=9.1min]

Entraînement:  28%|██▊       | 2844/10000 [09:06<22:36,  5.27step/s, loss=0.044572, elapsed=9.1min]

Entraînement:  28%|██▊       | 2844/10000 [09:06<22:36,  5.27step/s, loss=0.063289, elapsed=9.1min]

Entraînement:  28%|██▊       | 2845/10000 [09:06<22:34,  5.28step/s, loss=0.063289, elapsed=9.1min]

Entraînement:  28%|██▊       | 2845/10000 [09:06<22:34,  5.28step/s, loss=0.134930, elapsed=9.1min]

Entraînement:  28%|██▊       | 2846/10000 [09:06<22:35,  5.28step/s, loss=0.134930, elapsed=9.1min]

Entraînement:  28%|██▊       | 2846/10000 [09:06<22:35,  5.28step/s, loss=0.045351, elapsed=9.1min]

Entraînement:  28%|██▊       | 2847/10000 [09:06<22:34,  5.28step/s, loss=0.045351, elapsed=9.1min]

Entraînement:  28%|██▊       | 2847/10000 [09:06<22:34,  5.28step/s, loss=0.074308, elapsed=9.1min]

Entraînement:  28%|██▊       | 2848/10000 [09:07<22:32,  5.29step/s, loss=0.074308, elapsed=9.1min]

Entraînement:  28%|██▊       | 2848/10000 [09:07<22:32,  5.29step/s, loss=0.041951, elapsed=9.1min]

Entraînement:  28%|██▊       | 2849/10000 [09:07<22:33,  5.28step/s, loss=0.041951, elapsed=9.1min]

Entraînement:  28%|██▊       | 2849/10000 [09:07<22:33,  5.28step/s, loss=0.083775, elapsed=9.1min]

Entraînement:  28%|██▊       | 2850/10000 [09:07<22:30,  5.29step/s, loss=0.083775, elapsed=9.1min]

Entraînement:  28%|██▊       | 2850/10000 [09:07<22:30,  5.29step/s, loss=0.049672, elapsed=9.1min]

Entraînement:  29%|██▊       | 2851/10000 [09:07<22:35,  5.27step/s, loss=0.049672, elapsed=9.1min]

Entraînement:  29%|██▊       | 2851/10000 [09:07<22:35,  5.27step/s, loss=0.030960, elapsed=9.1min]

Entraînement:  29%|██▊       | 2852/10000 [09:07<22:34,  5.28step/s, loss=0.030960, elapsed=9.1min]

Entraînement:  29%|██▊       | 2852/10000 [09:07<22:34,  5.28step/s, loss=0.056919, elapsed=9.1min]

Entraînement:  29%|██▊       | 2853/10000 [09:07<22:32,  5.28step/s, loss=0.056919, elapsed=9.1min]

Entraînement:  29%|██▊       | 2853/10000 [09:07<22:32,  5.28step/s, loss=0.041825, elapsed=9.1min]

Entraînement:  29%|██▊       | 2854/10000 [09:08<22:33,  5.28step/s, loss=0.041825, elapsed=9.1min]

Entraînement:  29%|██▊       | 2854/10000 [09:08<22:33,  5.28step/s, loss=0.038498, elapsed=9.1min]

Entraînement:  29%|██▊       | 2855/10000 [09:08<22:33,  5.28step/s, loss=0.038498, elapsed=9.1min]

Entraînement:  29%|██▊       | 2855/10000 [09:08<22:33,  5.28step/s, loss=0.061609, elapsed=9.1min]

Entraînement:  29%|██▊       | 2856/10000 [09:08<22:33,  5.28step/s, loss=0.061609, elapsed=9.1min]

Entraînement:  29%|██▊       | 2856/10000 [09:08<22:33,  5.28step/s, loss=0.065387, elapsed=9.1min]

Entraînement:  29%|██▊       | 2857/10000 [09:08<22:33,  5.28step/s, loss=0.065387, elapsed=9.1min]

Entraînement:  29%|██▊       | 2857/10000 [09:08<22:33,  5.28step/s, loss=0.029291, elapsed=9.1min]

Entraînement:  29%|██▊       | 2858/10000 [09:08<22:36,  5.27step/s, loss=0.029291, elapsed=9.1min]

Entraînement:  29%|██▊       | 2858/10000 [09:08<22:36,  5.27step/s, loss=0.037266, elapsed=9.1min]

Entraînement:  29%|██▊       | 2859/10000 [09:09<22:37,  5.26step/s, loss=0.037266, elapsed=9.1min]

Entraînement:  29%|██▊       | 2859/10000 [09:09<22:37,  5.26step/s, loss=0.027025, elapsed=9.2min]

Entraînement:  29%|██▊       | 2860/10000 [09:09<22:38,  5.26step/s, loss=0.027025, elapsed=9.2min]

Entraînement:  29%|██▊       | 2860/10000 [09:09<22:38,  5.26step/s, loss=0.055532, elapsed=9.2min]

Entraînement:  29%|██▊       | 2861/10000 [09:09<22:34,  5.27step/s, loss=0.055532, elapsed=9.2min]

Entraînement:  29%|██▊       | 2861/10000 [09:09<22:34,  5.27step/s, loss=0.090017, elapsed=9.2min]

Entraînement:  29%|██▊       | 2862/10000 [09:09<22:33,  5.27step/s, loss=0.090017, elapsed=9.2min]

Entraînement:  29%|██▊       | 2862/10000 [09:09<22:33,  5.27step/s, loss=0.040810, elapsed=9.2min]

Entraînement:  29%|██▊       | 2863/10000 [09:09<22:34,  5.27step/s, loss=0.040810, elapsed=9.2min]

Entraînement:  29%|██▊       | 2863/10000 [09:09<22:34,  5.27step/s, loss=0.037611, elapsed=9.2min]

Entraînement:  29%|██▊       | 2864/10000 [09:10<22:34,  5.27step/s, loss=0.037611, elapsed=9.2min]

Entraînement:  29%|██▊       | 2864/10000 [09:10<22:34,  5.27step/s, loss=0.075174, elapsed=9.2min]

Entraînement:  29%|██▊       | 2865/10000 [09:10<22:37,  5.26step/s, loss=0.075174, elapsed=9.2min]

Entraînement:  29%|██▊       | 2865/10000 [09:10<22:37,  5.26step/s, loss=0.039897, elapsed=9.2min]

Entraînement:  29%|██▊       | 2866/10000 [09:10<22:36,  5.26step/s, loss=0.039897, elapsed=9.2min]

Entraînement:  29%|██▊       | 2866/10000 [09:10<22:36,  5.26step/s, loss=0.039408, elapsed=9.2min]

Entraînement:  29%|██▊       | 2867/10000 [09:10<22:37,  5.25step/s, loss=0.039408, elapsed=9.2min]

Entraînement:  29%|██▊       | 2867/10000 [09:10<22:37,  5.25step/s, loss=0.059385, elapsed=9.2min]

Entraînement:  29%|██▊       | 2868/10000 [09:10<22:34,  5.27step/s, loss=0.059385, elapsed=9.2min]

Entraînement:  29%|██▊       | 2868/10000 [09:10<22:34,  5.27step/s, loss=0.050695, elapsed=9.2min]

Entraînement:  29%|██▊       | 2869/10000 [09:11<22:30,  5.28step/s, loss=0.050695, elapsed=9.2min]

Entraînement:  29%|██▊       | 2869/10000 [09:11<22:30,  5.28step/s, loss=0.031517, elapsed=9.2min]

Entraînement:  29%|██▊       | 2870/10000 [09:11<22:28,  5.29step/s, loss=0.031517, elapsed=9.2min]

Entraînement:  29%|██▊       | 2870/10000 [09:11<22:28,  5.29step/s, loss=0.038803, elapsed=9.2min]

Entraînement:  29%|██▊       | 2871/10000 [09:11<22:26,  5.29step/s, loss=0.038803, elapsed=9.2min]

Entraînement:  29%|██▊       | 2871/10000 [09:11<22:26,  5.29step/s, loss=0.045773, elapsed=9.2min]

Entraînement:  29%|██▊       | 2872/10000 [09:11<22:26,  5.29step/s, loss=0.045773, elapsed=9.2min]

Entraînement:  29%|██▊       | 2872/10000 [09:11<22:26,  5.29step/s, loss=0.040235, elapsed=9.2min]

Entraînement:  29%|██▊       | 2873/10000 [09:11<22:27,  5.29step/s, loss=0.040235, elapsed=9.2min]

Entraînement:  29%|██▊       | 2873/10000 [09:11<22:27,  5.29step/s, loss=0.045339, elapsed=9.2min]

Entraînement:  29%|██▊       | 2874/10000 [09:11<22:27,  5.29step/s, loss=0.045339, elapsed=9.2min]

Entraînement:  29%|██▊       | 2874/10000 [09:11<22:27,  5.29step/s, loss=0.030855, elapsed=9.2min]

Entraînement:  29%|██▉       | 2875/10000 [09:12<22:29,  5.28step/s, loss=0.030855, elapsed=9.2min]

Entraînement:  29%|██▉       | 2875/10000 [09:12<22:29,  5.28step/s, loss=0.034814, elapsed=9.2min]

Entraînement:  29%|██▉       | 2876/10000 [09:12<22:26,  5.29step/s, loss=0.034814, elapsed=9.2min]

Entraînement:  29%|██▉       | 2876/10000 [09:12<22:26,  5.29step/s, loss=0.024081, elapsed=9.2min]

Entraînement:  29%|██▉       | 2877/10000 [09:12<22:27,  5.29step/s, loss=0.024081, elapsed=9.2min]

Entraînement:  29%|██▉       | 2877/10000 [09:12<22:27,  5.29step/s, loss=0.052492, elapsed=9.2min]

Entraînement:  29%|██▉       | 2878/10000 [09:12<22:27,  5.29step/s, loss=0.052492, elapsed=9.2min]

Entraînement:  29%|██▉       | 2878/10000 [09:12<22:27,  5.29step/s, loss=0.039794, elapsed=9.2min]

Entraînement:  29%|██▉       | 2879/10000 [09:12<22:29,  5.28step/s, loss=0.039794, elapsed=9.2min]

Entraînement:  29%|██▉       | 2879/10000 [09:12<22:29,  5.28step/s, loss=0.042321, elapsed=9.2min]

Entraînement:  29%|██▉       | 2880/10000 [09:13<22:29,  5.28step/s, loss=0.042321, elapsed=9.2min]

Entraînement:  29%|██▉       | 2880/10000 [09:13<22:29,  5.28step/s, loss=0.053723, elapsed=9.2min]

Entraînement:  29%|██▉       | 2881/10000 [09:13<22:29,  5.27step/s, loss=0.053723, elapsed=9.2min]

Entraînement:  29%|██▉       | 2881/10000 [09:13<22:29,  5.27step/s, loss=0.042316, elapsed=9.2min]

Entraînement:  29%|██▉       | 2882/10000 [09:13<22:33,  5.26step/s, loss=0.042316, elapsed=9.2min]

Entraînement:  29%|██▉       | 2882/10000 [09:13<22:33,  5.26step/s, loss=0.040243, elapsed=9.2min]

Entraînement:  29%|██▉       | 2883/10000 [09:13<22:32,  5.26step/s, loss=0.040243, elapsed=9.2min]

Entraînement:  29%|██▉       | 2883/10000 [09:13<22:32,  5.26step/s, loss=0.061346, elapsed=9.2min]

Entraînement:  29%|██▉       | 2884/10000 [09:13<22:40,  5.23step/s, loss=0.061346, elapsed=9.2min]

Entraînement:  29%|██▉       | 2884/10000 [09:13<22:40,  5.23step/s, loss=0.064576, elapsed=9.2min]

Entraînement:  29%|██▉       | 2885/10000 [09:14<22:31,  5.27step/s, loss=0.064576, elapsed=9.2min]

Entraînement:  29%|██▉       | 2885/10000 [09:14<22:31,  5.27step/s, loss=0.047456, elapsed=9.2min]

Entraînement:  29%|██▉       | 2886/10000 [09:14<22:24,  5.29step/s, loss=0.047456, elapsed=9.2min]

Entraînement:  29%|██▉       | 2886/10000 [09:14<22:24,  5.29step/s, loss=0.047616, elapsed=9.2min]

Entraînement:  29%|██▉       | 2887/10000 [09:14<22:19,  5.31step/s, loss=0.047616, elapsed=9.2min]

Entraînement:  29%|██▉       | 2887/10000 [09:14<22:19,  5.31step/s, loss=0.076344, elapsed=9.2min]

Entraînement:  29%|██▉       | 2888/10000 [09:14<22:15,  5.32step/s, loss=0.076344, elapsed=9.2min]

Entraînement:  29%|██▉       | 2888/10000 [09:14<22:15,  5.32step/s, loss=0.081393, elapsed=9.2min]

Entraînement:  29%|██▉       | 2889/10000 [09:14<22:11,  5.34step/s, loss=0.081393, elapsed=9.2min]

Entraînement:  29%|██▉       | 2889/10000 [09:14<22:11,  5.34step/s, loss=0.079020, elapsed=9.2min]

Entraînement:  29%|██▉       | 2890/10000 [09:14<22:09,  5.35step/s, loss=0.079020, elapsed=9.2min]

Entraînement:  29%|██▉       | 2890/10000 [09:14<22:09,  5.35step/s, loss=0.059603, elapsed=9.2min]

Entraînement:  29%|██▉       | 2891/10000 [09:15<22:10,  5.34step/s, loss=0.059603, elapsed=9.2min]

Entraînement:  29%|██▉       | 2891/10000 [09:15<22:10,  5.34step/s, loss=0.050089, elapsed=9.3min]

Entraînement:  29%|██▉       | 2892/10000 [09:15<22:10,  5.34step/s, loss=0.050089, elapsed=9.3min]

Entraînement:  29%|██▉       | 2892/10000 [09:15<22:10,  5.34step/s, loss=0.028519, elapsed=9.3min]

Entraînement:  29%|██▉       | 2893/10000 [09:15<22:07,  5.35step/s, loss=0.028519, elapsed=9.3min]

Entraînement:  29%|██▉       | 2893/10000 [09:15<22:07,  5.35step/s, loss=0.078420, elapsed=9.3min]

Entraînement:  29%|██▉       | 2894/10000 [09:15<22:06,  5.36step/s, loss=0.078420, elapsed=9.3min]

Entraînement:  29%|██▉       | 2894/10000 [09:15<22:06,  5.36step/s, loss=0.042062, elapsed=9.3min]

Entraînement:  29%|██▉       | 2895/10000 [09:15<22:05,  5.36step/s, loss=0.042062, elapsed=9.3min]

Entraînement:  29%|██▉       | 2895/10000 [09:15<22:05,  5.36step/s, loss=0.089827, elapsed=9.3min]

Entraînement:  29%|██▉       | 2896/10000 [09:16<22:03,  5.37step/s, loss=0.089827, elapsed=9.3min]

Entraînement:  29%|██▉       | 2896/10000 [09:16<22:03,  5.37step/s, loss=0.023225, elapsed=9.3min]

Entraînement:  29%|██▉       | 2897/10000 [09:16<22:00,  5.38step/s, loss=0.023225, elapsed=9.3min]

Entraînement:  29%|██▉       | 2897/10000 [09:16<22:00,  5.38step/s, loss=0.024536, elapsed=9.3min]

Entraînement:  29%|██▉       | 2898/10000 [09:16<21:58,  5.39step/s, loss=0.024536, elapsed=9.3min]

Entraînement:  29%|██▉       | 2898/10000 [09:16<21:58,  5.39step/s, loss=0.044468, elapsed=9.3min]

Entraînement:  29%|██▉       | 2899/10000 [09:16<22:01,  5.37step/s, loss=0.044468, elapsed=9.3min]

Entraînement:  29%|██▉       | 2899/10000 [09:16<22:01,  5.37step/s, loss=0.050663, elapsed=9.3min]

Entraînement:  29%|██▉       | 2900/10000 [09:16<22:03,  5.37step/s, loss=0.050663, elapsed=9.3min]

Entraînement:  29%|██▉       | 2900/10000 [09:16<22:03,  5.37step/s, loss=0.062672, elapsed=9.3min]

Entraînement:  29%|██▉       | 2900/10000 [09:16<22:03,  5.37step/s, loss=0.062672, elapsed=9.3min]

Entraînement:  29%|██▉       | 2901/10000 [09:17<22:05,  5.36step/s, loss=0.062672, elapsed=9.3min]

Entraînement:  29%|██▉       | 2901/10000 [09:17<22:05,  5.36step/s, loss=0.038223, elapsed=9.3min]

Step 2900/10000 | Train loss: 0.062672 | Elapsed: 9.3min | ETA: 22.7min

Entraînement:  29%|██▉       | 2902/10000 [09:17<22:01,  5.37step/s, loss=0.038223, elapsed=9.3min]

Entraînement:  29%|██▉       | 2902/10000 [09:17<22:01,  5.37step/s, loss=0.042725, elapsed=9.3min]

Entraînement:  29%|██▉       | 2903/10000 [09:17<22:01,  5.37step/s, loss=0.042725, elapsed=9.3min]

Entraînement:  29%|██▉       | 2903/10000 [09:17<22:01,  5.37step/s, loss=0.064015, elapsed=9.3min]

Entraînement:  29%|██▉       | 2904/10000 [09:17<22:02,  5.37step/s, loss=0.064015, elapsed=9.3min]

Entraînement:  29%|██▉       | 2904/10000 [09:17<22:02,  5.37step/s, loss=0.057641, elapsed=9.3min]

Entraînement:  29%|██▉       | 2905/10000 [09:17<21:59,  5.38step/s, loss=0.057641, elapsed=9.3min]

Entraînement:  29%|██▉       | 2905/10000 [09:17<21:59,  5.38step/s, loss=0.043822, elapsed=9.3min]

Entraînement:  29%|██▉       | 2906/10000 [09:17<22:10,  5.33step/s, loss=0.043822, elapsed=9.3min]

Entraînement:  29%|██▉       | 2906/10000 [09:17<22:10,  5.33step/s, loss=0.041795, elapsed=9.3min]

Entraînement:  29%|██▉       | 2907/10000 [09:18<22:13,  5.32step/s, loss=0.041795, elapsed=9.3min]

Entraînement:  29%|██▉       | 2907/10000 [09:18<22:13,  5.32step/s, loss=0.051881, elapsed=9.3min]

Entraînement:  29%|██▉       | 2908/10000 [09:18<22:20,  5.29step/s, loss=0.051881, elapsed=9.3min]

Entraînement:  29%|██▉       | 2908/10000 [09:18<22:20,  5.29step/s, loss=0.038540, elapsed=9.3min]

Entraînement:  29%|██▉       | 2909/10000 [09:18<22:27,  5.26step/s, loss=0.038540, elapsed=9.3min]

Entraînement:  29%|██▉       | 2909/10000 [09:18<22:27,  5.26step/s, loss=0.042474, elapsed=9.3min]

Entraînement:  29%|██▉       | 2910/10000 [09:18<22:29,  5.25step/s, loss=0.042474, elapsed=9.3min]

Entraînement:  29%|██▉       | 2910/10000 [09:18<22:29,  5.25step/s, loss=0.034778, elapsed=9.3min]

Entraînement:  29%|██▉       | 2911/10000 [09:18<22:26,  5.26step/s, loss=0.034778, elapsed=9.3min]

Entraînement:  29%|██▉       | 2911/10000 [09:18<22:26,  5.26step/s, loss=0.030822, elapsed=9.3min]

Entraînement:  29%|██▉       | 2912/10000 [09:19<22:31,  5.24step/s, loss=0.030822, elapsed=9.3min]

Entraînement:  29%|██▉       | 2912/10000 [09:19<22:31,  5.24step/s, loss=0.057927, elapsed=9.3min]

Entraînement:  29%|██▉       | 2913/10000 [09:19<22:28,  5.25step/s, loss=0.057927, elapsed=9.3min]

Entraînement:  29%|██▉       | 2913/10000 [09:19<22:28,  5.25step/s, loss=0.028852, elapsed=9.3min]

Entraînement:  29%|██▉       | 2914/10000 [09:19<22:27,  5.26step/s, loss=0.028852, elapsed=9.3min]

Entraînement:  29%|██▉       | 2914/10000 [09:19<22:27,  5.26step/s, loss=0.037239, elapsed=9.3min]

Entraînement:  29%|██▉       | 2915/10000 [09:19<22:28,  5.25step/s, loss=0.037239, elapsed=9.3min]

Entraînement:  29%|██▉       | 2915/10000 [09:19<22:28,  5.25step/s, loss=0.059860, elapsed=9.3min]

Entraînement:  29%|██▉       | 2916/10000 [09:19<22:29,  5.25step/s, loss=0.059860, elapsed=9.3min]

Entraînement:  29%|██▉       | 2916/10000 [09:19<22:29,  5.25step/s, loss=0.042876, elapsed=9.3min]

Entraînement:  29%|██▉       | 2917/10000 [09:20<22:27,  5.26step/s, loss=0.042876, elapsed=9.3min]

Entraînement:  29%|██▉       | 2917/10000 [09:20<22:27,  5.26step/s, loss=0.037239, elapsed=9.3min]

Entraînement:  29%|██▉       | 2918/10000 [09:20<22:23,  5.27step/s, loss=0.037239, elapsed=9.3min]

Entraînement:  29%|██▉       | 2918/10000 [09:20<22:23,  5.27step/s, loss=0.066084, elapsed=9.3min]

Entraînement:  29%|██▉       | 2919/10000 [09:20<22:22,  5.27step/s, loss=0.066084, elapsed=9.3min]

Entraînement:  29%|██▉       | 2919/10000 [09:20<22:22,  5.27step/s, loss=0.076016, elapsed=9.3min]

Entraînement:  29%|██▉       | 2920/10000 [09:20<22:24,  5.27step/s, loss=0.076016, elapsed=9.3min]

Entraînement:  29%|██▉       | 2920/10000 [09:20<22:24,  5.27step/s, loss=0.047964, elapsed=9.3min]

Entraînement:  29%|██▉       | 2921/10000 [09:20<22:23,  5.27step/s, loss=0.047964, elapsed=9.3min]

Entraînement:  29%|██▉       | 2921/10000 [09:20<22:23,  5.27step/s, loss=0.027415, elapsed=9.3min]

Entraînement:  29%|██▉       | 2922/10000 [09:21<22:21,  5.27step/s, loss=0.027415, elapsed=9.3min]

Entraînement:  29%|██▉       | 2922/10000 [09:21<22:21,  5.27step/s, loss=0.027849, elapsed=9.4min]

Entraînement:  29%|██▉       | 2923/10000 [09:21<22:24,  5.27step/s, loss=0.027849, elapsed=9.4min]

Entraînement:  29%|██▉       | 2923/10000 [09:21<22:24,  5.27step/s, loss=0.034871, elapsed=9.4min]

Entraînement:  29%|██▉       | 2924/10000 [09:21<22:23,  5.27step/s, loss=0.034871, elapsed=9.4min]

Entraînement:  29%|██▉       | 2924/10000 [09:21<22:23,  5.27step/s, loss=0.040303, elapsed=9.4min]

Entraînement:  29%|██▉       | 2925/10000 [09:21<22:20,  5.28step/s, loss=0.040303, elapsed=9.4min]

Entraînement:  29%|██▉       | 2925/10000 [09:21<22:20,  5.28step/s, loss=0.061529, elapsed=9.4min]

Entraînement:  29%|██▉       | 2926/10000 [09:21<22:21,  5.27step/s, loss=0.061529, elapsed=9.4min]

Entraînement:  29%|██▉       | 2926/10000 [09:21<22:21,  5.27step/s, loss=0.030542, elapsed=9.4min]

Entraînement:  29%|██▉       | 2927/10000 [09:21<22:19,  5.28step/s, loss=0.030542, elapsed=9.4min]

Entraînement:  29%|██▉       | 2927/10000 [09:21<22:19,  5.28step/s, loss=0.042711, elapsed=9.4min]

Entraînement:  29%|██▉       | 2928/10000 [09:22<22:20,  5.27step/s, loss=0.042711, elapsed=9.4min]

Entraînement:  29%|██▉       | 2928/10000 [09:22<22:20,  5.27step/s, loss=0.106236, elapsed=9.4min]

Entraînement:  29%|██▉       | 2929/10000 [09:22<22:19,  5.28step/s, loss=0.106236, elapsed=9.4min]

Entraînement:  29%|██▉       | 2929/10000 [09:22<22:19,  5.28step/s, loss=0.026971, elapsed=9.4min]

Entraînement:  29%|██▉       | 2930/10000 [09:22<22:23,  5.26step/s, loss=0.026971, elapsed=9.4min]

Entraînement:  29%|██▉       | 2930/10000 [09:22<22:23,  5.26step/s, loss=0.041818, elapsed=9.4min]

Entraînement:  29%|██▉       | 2931/10000 [09:22<22:24,  5.26step/s, loss=0.041818, elapsed=9.4min]

Entraînement:  29%|██▉       | 2931/10000 [09:22<22:24,  5.26step/s, loss=0.041012, elapsed=9.4min]

Entraînement:  29%|██▉       | 2932/10000 [09:22<22:26,  5.25step/s, loss=0.041012, elapsed=9.4min]

Entraînement:  29%|██▉       | 2932/10000 [09:22<22:26,  5.25step/s, loss=0.030659, elapsed=9.4min]

Entraînement:  29%|██▉       | 2933/10000 [09:23<22:24,  5.26step/s, loss=0.030659, elapsed=9.4min]

Entraînement:  29%|██▉       | 2933/10000 [09:23<22:24,  5.26step/s, loss=0.042447, elapsed=9.4min]

Entraînement:  29%|██▉       | 2934/10000 [09:23<22:21,  5.27step/s, loss=0.042447, elapsed=9.4min]

Entraînement:  29%|██▉       | 2934/10000 [09:23<22:21,  5.27step/s, loss=0.054735, elapsed=9.4min]

Entraînement:  29%|██▉       | 2935/10000 [09:23<22:20,  5.27step/s, loss=0.054735, elapsed=9.4min]

Entraînement:  29%|██▉       | 2935/10000 [09:23<22:20,  5.27step/s, loss=0.058087, elapsed=9.4min]

Entraînement:  29%|██▉       | 2936/10000 [09:23<22:18,  5.28step/s, loss=0.058087, elapsed=9.4min]

Entraînement:  29%|██▉       | 2936/10000 [09:23<22:18,  5.28step/s, loss=0.031392, elapsed=9.4min]

Entraînement:  29%|██▉       | 2937/10000 [09:23<22:19,  5.27step/s, loss=0.031392, elapsed=9.4min]

Entraînement:  29%|██▉       | 2937/10000 [09:23<22:19,  5.27step/s, loss=0.059828, elapsed=9.4min]

Entraînement:  29%|██▉       | 2938/10000 [09:24<22:21,  5.26step/s, loss=0.059828, elapsed=9.4min]

Entraînement:  29%|██▉       | 2938/10000 [09:24<22:21,  5.26step/s, loss=0.038086, elapsed=9.4min]

Entraînement:  29%|██▉       | 2939/10000 [09:24<22:20,  5.27step/s, loss=0.038086, elapsed=9.4min]

Entraînement:  29%|██▉       | 2939/10000 [09:24<22:20,  5.27step/s, loss=0.069045, elapsed=9.4min]

Entraînement:  29%|██▉       | 2940/10000 [09:24<22:22,  5.26step/s, loss=0.069045, elapsed=9.4min]

Entraînement:  29%|██▉       | 2940/10000 [09:24<22:22,  5.26step/s, loss=0.149462, elapsed=9.4min]

Entraînement:  29%|██▉       | 2941/10000 [09:24<22:19,  5.27step/s, loss=0.149462, elapsed=9.4min]

Entraînement:  29%|██▉       | 2941/10000 [09:24<22:19,  5.27step/s, loss=0.165334, elapsed=9.4min]

Entraînement:  29%|██▉       | 2942/10000 [09:24<22:23,  5.25step/s, loss=0.165334, elapsed=9.4min]

Entraînement:  29%|██▉       | 2942/10000 [09:24<22:23,  5.25step/s, loss=0.057522, elapsed=9.4min]

Entraînement:  29%|██▉       | 2943/10000 [09:25<22:23,  5.25step/s, loss=0.057522, elapsed=9.4min]

Entraînement:  29%|██▉       | 2943/10000 [09:25<22:23,  5.25step/s, loss=0.071113, elapsed=9.4min]

Entraînement:  29%|██▉       | 2944/10000 [09:25<22:23,  5.25step/s, loss=0.071113, elapsed=9.4min]

Entraînement:  29%|██▉       | 2944/10000 [09:25<22:23,  5.25step/s, loss=0.037719, elapsed=9.4min]

Entraînement:  29%|██▉       | 2945/10000 [09:25<22:20,  5.26step/s, loss=0.037719, elapsed=9.4min]

Entraînement:  29%|██▉       | 2945/10000 [09:25<22:20,  5.26step/s, loss=0.094555, elapsed=9.4min]

Entraînement:  29%|██▉       | 2946/10000 [09:25<22:24,  5.25step/s, loss=0.094555, elapsed=9.4min]

Entraînement:  29%|██▉       | 2946/10000 [09:25<22:24,  5.25step/s, loss=0.036902, elapsed=9.4min]

Entraînement:  29%|██▉       | 2947/10000 [09:25<22:23,  5.25step/s, loss=0.036902, elapsed=9.4min]

Entraînement:  29%|██▉       | 2947/10000 [09:25<22:23,  5.25step/s, loss=0.037163, elapsed=9.4min]

Entraînement:  29%|██▉       | 2948/10000 [09:25<22:24,  5.25step/s, loss=0.037163, elapsed=9.4min]

Entraînement:  29%|██▉       | 2948/10000 [09:25<22:24,  5.25step/s, loss=0.116156, elapsed=9.4min]

Entraînement:  29%|██▉       | 2949/10000 [09:26<22:22,  5.25step/s, loss=0.116156, elapsed=9.4min]

Entraînement:  29%|██▉       | 2949/10000 [09:26<22:22,  5.25step/s, loss=0.067318, elapsed=9.4min]

Entraînement:  30%|██▉       | 2950/10000 [09:26<22:23,  5.25step/s, loss=0.067318, elapsed=9.4min]

Entraînement:  30%|██▉       | 2950/10000 [09:26<22:23,  5.25step/s, loss=0.038032, elapsed=9.4min]

Entraînement:  30%|██▉       | 2951/10000 [09:26<22:22,  5.25step/s, loss=0.038032, elapsed=9.4min]

Entraînement:  30%|██▉       | 2951/10000 [09:26<22:22,  5.25step/s, loss=0.060948, elapsed=9.4min]

Entraînement:  30%|██▉       | 2952/10000 [09:26<22:22,  5.25step/s, loss=0.060948, elapsed=9.4min]

Entraînement:  30%|██▉       | 2952/10000 [09:26<22:22,  5.25step/s, loss=0.032800, elapsed=9.4min]

Entraînement:  30%|██▉       | 2953/10000 [09:26<22:24,  5.24step/s, loss=0.032800, elapsed=9.4min]

Entraînement:  30%|██▉       | 2953/10000 [09:26<22:24,  5.24step/s, loss=0.039503, elapsed=9.4min]

Entraînement:  30%|██▉       | 2954/10000 [09:27<22:24,  5.24step/s, loss=0.039503, elapsed=9.4min]

Entraînement:  30%|██▉       | 2954/10000 [09:27<22:24,  5.24step/s, loss=0.076775, elapsed=9.5min]

Entraînement:  30%|██▉       | 2955/10000 [09:27<22:23,  5.24step/s, loss=0.076775, elapsed=9.5min]

Entraînement:  30%|██▉       | 2955/10000 [09:27<22:23,  5.24step/s, loss=0.036497, elapsed=9.5min]

Entraînement:  30%|██▉       | 2956/10000 [09:27<22:20,  5.26step/s, loss=0.036497, elapsed=9.5min]

Entraînement:  30%|██▉       | 2956/10000 [09:27<22:20,  5.26step/s, loss=0.145736, elapsed=9.5min]

Entraînement:  30%|██▉       | 2957/10000 [09:27<22:19,  5.26step/s, loss=0.145736, elapsed=9.5min]

Entraînement:  30%|██▉       | 2957/10000 [09:27<22:19,  5.26step/s, loss=0.035034, elapsed=9.5min]

Entraînement:  30%|██▉       | 2958/10000 [09:27<22:19,  5.26step/s, loss=0.035034, elapsed=9.5min]

Entraînement:  30%|██▉       | 2958/10000 [09:27<22:19,  5.26step/s, loss=0.064369, elapsed=9.5min]

Entraînement:  30%|██▉       | 2959/10000 [09:28<22:17,  5.27step/s, loss=0.064369, elapsed=9.5min]

Entraînement:  30%|██▉       | 2959/10000 [09:28<22:17,  5.27step/s, loss=0.041314, elapsed=9.5min]

Entraînement:  30%|██▉       | 2960/10000 [09:28<22:17,  5.26step/s, loss=0.041314, elapsed=9.5min]

Entraînement:  30%|██▉       | 2960/10000 [09:28<22:17,  5.26step/s, loss=0.030848, elapsed=9.5min]

Entraînement:  30%|██▉       | 2961/10000 [09:28<22:16,  5.26step/s, loss=0.030848, elapsed=9.5min]

Entraînement:  30%|██▉       | 2961/10000 [09:28<22:16,  5.26step/s, loss=0.053287, elapsed=9.5min]

Entraînement:  30%|██▉       | 2962/10000 [09:28<22:17,  5.26step/s, loss=0.053287, elapsed=9.5min]

Entraînement:  30%|██▉       | 2962/10000 [09:28<22:17,  5.26step/s, loss=0.041959, elapsed=9.5min]

Entraînement:  30%|██▉       | 2963/10000 [09:28<22:17,  5.26step/s, loss=0.041959, elapsed=9.5min]

Entraînement:  30%|██▉       | 2963/10000 [09:28<22:17,  5.26step/s, loss=0.053879, elapsed=9.5min]

Entraînement:  30%|██▉       | 2964/10000 [09:28<22:17,  5.26step/s, loss=0.053879, elapsed=9.5min]

Entraînement:  30%|██▉       | 2964/10000 [09:29<22:17,  5.26step/s, loss=0.076395, elapsed=9.5min]

Entraînement:  30%|██▉       | 2965/10000 [09:29<22:17,  5.26step/s, loss=0.076395, elapsed=9.5min]

Entraînement:  30%|██▉       | 2965/10000 [09:29<22:17,  5.26step/s, loss=0.054886, elapsed=9.5min]

Entraînement:  30%|██▉       | 2966/10000 [09:29<22:16,  5.26step/s, loss=0.054886, elapsed=9.5min]

Entraînement:  30%|██▉       | 2966/10000 [09:29<22:16,  5.26step/s, loss=0.091158, elapsed=9.5min]

Entraînement:  30%|██▉       | 2967/10000 [09:29<22:15,  5.26step/s, loss=0.091158, elapsed=9.5min]

Entraînement:  30%|██▉       | 2967/10000 [09:29<22:15,  5.26step/s, loss=0.167849, elapsed=9.5min]

Entraînement:  30%|██▉       | 2968/10000 [09:29<22:15,  5.27step/s, loss=0.167849, elapsed=9.5min]

Entraînement:  30%|██▉       | 2968/10000 [09:29<22:15,  5.27step/s, loss=0.038107, elapsed=9.5min]

Entraînement:  30%|██▉       | 2969/10000 [09:29<22:17,  5.26step/s, loss=0.038107, elapsed=9.5min]

Entraînement:  30%|██▉       | 2969/10000 [09:29<22:17,  5.26step/s, loss=0.037594, elapsed=9.5min]

Entraînement:  30%|██▉       | 2970/10000 [09:30<22:16,  5.26step/s, loss=0.037594, elapsed=9.5min]

Entraînement:  30%|██▉       | 2970/10000 [09:30<22:16,  5.26step/s, loss=0.047543, elapsed=9.5min]

Entraînement:  30%|██▉       | 2971/10000 [09:30<22:18,  5.25step/s, loss=0.047543, elapsed=9.5min]

Entraînement:  30%|██▉       | 2971/10000 [09:30<22:18,  5.25step/s, loss=0.046041, elapsed=9.5min]

Entraînement:  30%|██▉       | 2972/10000 [09:30<22:17,  5.25step/s, loss=0.046041, elapsed=9.5min]

Entraînement:  30%|██▉       | 2972/10000 [09:30<22:17,  5.25step/s, loss=0.040103, elapsed=9.5min]

Entraînement:  30%|██▉       | 2973/10000 [09:30<22:15,  5.26step/s, loss=0.040103, elapsed=9.5min]

Entraînement:  30%|██▉       | 2973/10000 [09:30<22:15,  5.26step/s, loss=0.134175, elapsed=9.5min]

Entraînement:  30%|██▉       | 2974/10000 [09:30<22:44,  5.15step/s, loss=0.134175, elapsed=9.5min]

Entraînement:  30%|██▉       | 2974/10000 [09:30<22:44,  5.15step/s, loss=0.064039, elapsed=9.5min]

Entraînement:  30%|██▉       | 2975/10000 [09:31<22:36,  5.18step/s, loss=0.064039, elapsed=9.5min]

Entraînement:  30%|██▉       | 2975/10000 [09:31<22:36,  5.18step/s, loss=0.106800, elapsed=9.5min]

Entraînement:  30%|██▉       | 2976/10000 [09:31<22:36,  5.18step/s, loss=0.106800, elapsed=9.5min]

Entraînement:  30%|██▉       | 2976/10000 [09:31<22:36,  5.18step/s, loss=0.029777, elapsed=9.5min]

Entraînement:  30%|██▉       | 2977/10000 [09:31<22:30,  5.20step/s, loss=0.029777, elapsed=9.5min]

Entraînement:  30%|██▉       | 2977/10000 [09:31<22:30,  5.20step/s, loss=0.046064, elapsed=9.5min]

Entraînement:  30%|██▉       | 2978/10000 [09:31<22:29,  5.20step/s, loss=0.046064, elapsed=9.5min]

Entraînement:  30%|██▉       | 2978/10000 [09:31<22:29,  5.20step/s, loss=0.058058, elapsed=9.5min]

Entraînement:  30%|██▉       | 2979/10000 [09:31<22:26,  5.22step/s, loss=0.058058, elapsed=9.5min]

Entraînement:  30%|██▉       | 2979/10000 [09:31<22:26,  5.22step/s, loss=0.042151, elapsed=9.5min]

Entraînement:  30%|██▉       | 2980/10000 [09:32<22:21,  5.23step/s, loss=0.042151, elapsed=9.5min]

Entraînement:  30%|██▉       | 2980/10000 [09:32<22:21,  5.23step/s, loss=0.072899, elapsed=9.5min]

Entraînement:  30%|██▉       | 2981/10000 [09:32<22:19,  5.24step/s, loss=0.072899, elapsed=9.5min]

Entraînement:  30%|██▉       | 2981/10000 [09:32<22:19,  5.24step/s, loss=0.050803, elapsed=9.5min]

Entraînement:  30%|██▉       | 2982/10000 [09:32<22:17,  5.25step/s, loss=0.050803, elapsed=9.5min]

Entraînement:  30%|██▉       | 2982/10000 [09:32<22:17,  5.25step/s, loss=0.090356, elapsed=9.5min]

Entraînement:  30%|██▉       | 2983/10000 [09:32<22:16,  5.25step/s, loss=0.090356, elapsed=9.5min]

Entraînement:  30%|██▉       | 2983/10000 [09:32<22:16,  5.25step/s, loss=0.062747, elapsed=9.5min]

Entraînement:  30%|██▉       | 2984/10000 [09:32<22:13,  5.26step/s, loss=0.062747, elapsed=9.5min]

Entraînement:  30%|██▉       | 2984/10000 [09:32<22:13,  5.26step/s, loss=0.164984, elapsed=9.5min]

Entraînement:  30%|██▉       | 2985/10000 [09:33<22:18,  5.24step/s, loss=0.164984, elapsed=9.5min]

Entraînement:  30%|██▉       | 2985/10000 [09:33<22:18,  5.24step/s, loss=0.051542, elapsed=9.6min]

Entraînement:  30%|██▉       | 2986/10000 [09:33<22:17,  5.24step/s, loss=0.051542, elapsed=9.6min]

Entraînement:  30%|██▉       | 2986/10000 [09:33<22:17,  5.24step/s, loss=0.065974, elapsed=9.6min]

Entraînement:  30%|██▉       | 2987/10000 [09:33<22:16,  5.25step/s, loss=0.065974, elapsed=9.6min]

Entraînement:  30%|██▉       | 2987/10000 [09:33<22:16,  5.25step/s, loss=0.063994, elapsed=9.6min]

Entraînement:  30%|██▉       | 2988/10000 [09:33<22:13,  5.26step/s, loss=0.063994, elapsed=9.6min]

Entraînement:  30%|██▉       | 2988/10000 [09:33<22:13,  5.26step/s, loss=0.058195, elapsed=9.6min]

Entraînement:  30%|██▉       | 2989/10000 [09:33<22:14,  5.25step/s, loss=0.058195, elapsed=9.6min]

Entraînement:  30%|██▉       | 2989/10000 [09:33<22:14,  5.25step/s, loss=0.063636, elapsed=9.6min]

Entraînement:  30%|██▉       | 2990/10000 [09:33<22:14,  5.25step/s, loss=0.063636, elapsed=9.6min]

Entraînement:  30%|██▉       | 2990/10000 [09:33<22:14,  5.25step/s, loss=0.051508, elapsed=9.6min]

Entraînement:  30%|██▉       | 2991/10000 [09:34<22:12,  5.26step/s, loss=0.051508, elapsed=9.6min]

Entraînement:  30%|██▉       | 2991/10000 [09:34<22:12,  5.26step/s, loss=0.043404, elapsed=9.6min]

Entraînement:  30%|██▉       | 2992/10000 [09:34<22:12,  5.26step/s, loss=0.043404, elapsed=9.6min]

Entraînement:  30%|██▉       | 2992/10000 [09:34<22:12,  5.26step/s, loss=0.036703, elapsed=9.6min]

Entraînement:  30%|██▉       | 2993/10000 [09:34<22:12,  5.26step/s, loss=0.036703, elapsed=9.6min]

Entraînement:  30%|██▉       | 2993/10000 [09:34<22:12,  5.26step/s, loss=0.060387, elapsed=9.6min]

Entraînement:  30%|██▉       | 2994/10000 [09:34<22:12,  5.26step/s, loss=0.060387, elapsed=9.6min]

Entraînement:  30%|██▉       | 2994/10000 [09:34<22:12,  5.26step/s, loss=0.049196, elapsed=9.6min]

Entraînement:  30%|██▉       | 2995/10000 [09:34<22:15,  5.25step/s, loss=0.049196, elapsed=9.6min]

Entraînement:  30%|██▉       | 2995/10000 [09:34<22:15,  5.25step/s, loss=0.022766, elapsed=9.6min]

Entraînement:  30%|██▉       | 2996/10000 [09:35<22:13,  5.25step/s, loss=0.022766, elapsed=9.6min]

Entraînement:  30%|██▉       | 2996/10000 [09:35<22:13,  5.25step/s, loss=0.053777, elapsed=9.6min]

Entraînement:  30%|██▉       | 2997/10000 [09:35<22:11,  5.26step/s, loss=0.053777, elapsed=9.6min]

Entraînement:  30%|██▉       | 2997/10000 [09:35<22:11,  5.26step/s, loss=0.079139, elapsed=9.6min]

Entraînement:  30%|██▉       | 2998/10000 [09:35<22:08,  5.27step/s, loss=0.079139, elapsed=9.6min]

Entraînement:  30%|██▉       | 2998/10000 [09:35<22:08,  5.27step/s, loss=0.073507, elapsed=9.6min]

Entraînement:  30%|██▉       | 2999/10000 [09:35<22:08,  5.27step/s, loss=0.073507, elapsed=9.6min]

Entraînement:  30%|██▉       | 2999/10000 [09:35<22:08,  5.27step/s, loss=0.109312, elapsed=9.6min]

Entraînement:  30%|███       | 3000/10000 [09:35<22:07,  5.27step/s, loss=0.109312, elapsed=9.6min]

Entraînement:  30%|███       | 3000/10000 [09:35<22:07,  5.27step/s, loss=0.067688, elapsed=9.6min]

Entraînement:  30%|███       | 3000/10000 [09:35<22:07,  5.27step/s, loss=0.067688, elapsed=9.6min]

Step 3000/10000 | Train loss: 0.067688 | Elapsed: 9.6min | ETA: 22.4min

Entraînement:  30%|███       | 3000/10000 [09:37<22:07,  5.27step/s, loss=0.067688, elapsed=9.6min]

Entraînement:  30%|███       | 3000/10000 [09:37<22:07,  5.27step/s, loss=0.067688, elapsed=9.6min]

Step 3000/10000 | Val loss: 0.066393 | Validation en 1.7s
Dernier checkpoint sauvegardé : /workspace/DiffWave_Project/checkpoints/diffwave_doda_male/last_checkpoint.pt

Entraînement:  30%|███       | 3001/10000 [09:37<1:27:40,  1.33step/s, loss=0.067688, elapsed=9.6min]

Entraînement:  30%|███       | 3001/10000 [09:37<1:27:40,  1.33step/s, loss=0.038216, elapsed=9.6min]

Entraînement:  30%|███       | 3002/10000 [09:38<1:08:07,  1.71step/s, loss=0.038216, elapsed=9.6min]

Entraînement:  30%|███       | 3002/10000 [09:38<1:08:07,  1.71step/s, loss=0.049692, elapsed=9.6min]

Entraînement:  30%|███       | 3003/10000 [09:38<54:20,  2.15step/s, loss=0.049692, elapsed=9.6min]

Entraînement:  30%|███       | 3003/10000 [09:38<54:20,  2.15step/s, loss=0.055610, elapsed=9.6min]

Entraînement:  30%|███       | 3004/10000 [09:38<44:40,  2.61step/s, loss=0.055610, elapsed=9.6min]

Entraînement:  30%|███       | 3004/10000 [09:38<44:40,  2.61step/s, loss=0.065381, elapsed=9.6min]

Entraînement:  30%|███       | 3005/10000 [09:38<37:55,  3.07step/s, loss=0.065381, elapsed=9.6min]

Entraînement:  30%|███       | 3005/10000 [09:38<37:55,  3.07step/s, loss=0.048762, elapsed=9.6min]

Entraînement:  30%|███       | 3006/10000 [09:38<33:10,  3.51step/s, loss=0.048762, elapsed=9.6min]

Entraînement:  30%|███       | 3006/10000 [09:38<33:10,  3.51step/s, loss=0.069202, elapsed=9.6min]

Entraînement:  30%|███       | 3007/10000 [09:39<29:53,  3.90step/s, loss=0.069202, elapsed=9.6min]

Entraînement:  30%|███       | 3007/10000 [09:39<29:53,  3.90step/s, loss=0.033118, elapsed=9.7min]

Entraînement:  30%|███       | 3008/10000 [09:39<27:35,  4.22step/s, loss=0.033118, elapsed=9.7min]

Entraînement:  30%|███       | 3008/10000 [09:39<27:35,  4.22step/s, loss=0.025397, elapsed=9.7min]

Entraînement:  30%|███       | 3009/10000 [09:39<25:54,  4.50step/s, loss=0.025397, elapsed=9.7min]

Entraînement:  30%|███       | 3009/10000 [09:39<25:54,  4.50step/s, loss=0.027807, elapsed=9.7min]

Entraînement:  30%|███       | 3010/10000 [09:39<24:43,  4.71step/s, loss=0.027807, elapsed=9.7min]

Entraînement:  30%|███       | 3010/10000 [09:39<24:43,  4.71step/s, loss=0.044073, elapsed=9.7min]

Entraînement:  30%|███       | 3011/10000 [09:39<23:59,  4.86step/s, loss=0.044073, elapsed=9.7min]

Entraînement:  30%|███       | 3011/10000 [09:39<23:59,  4.86step/s, loss=0.057000, elapsed=9.7min]

Entraînement:  30%|███       | 3012/10000 [09:40<23:27,  4.97step/s, loss=0.057000, elapsed=9.7min]

Entraînement:  30%|███       | 3012/10000 [09:40<23:27,  4.97step/s, loss=0.129367, elapsed=9.7min]

Entraînement:  30%|███       | 3013/10000 [09:40<23:04,  5.05step/s, loss=0.129367, elapsed=9.7min]

Entraînement:  30%|███       | 3013/10000 [09:40<23:04,  5.05step/s, loss=0.102387, elapsed=9.7min]

Entraînement:  30%|███       | 3014/10000 [09:40<22:46,  5.11step/s, loss=0.102387, elapsed=9.7min]

Entraînement:  30%|███       | 3014/10000 [09:40<22:46,  5.11step/s, loss=0.033744, elapsed=9.7min]

Entraînement:  30%|███       | 3015/10000 [09:40<22:33,  5.16step/s, loss=0.033744, elapsed=9.7min]

Entraînement:  30%|███       | 3015/10000 [09:40<22:33,  5.16step/s, loss=0.038709, elapsed=9.7min]

Entraînement:  30%|███       | 3016/10000 [09:40<22:25,  5.19step/s, loss=0.038709, elapsed=9.7min]

Entraînement:  30%|███       | 3016/10000 [09:40<22:25,  5.19step/s, loss=0.053686, elapsed=9.7min]

Entraînement:  30%|███       | 3017/10000 [09:40<22:17,  5.22step/s, loss=0.053686, elapsed=9.7min]

Entraînement:  30%|███       | 3017/10000 [09:40<22:17,  5.22step/s, loss=0.156914, elapsed=9.7min]

Entraînement:  30%|███       | 3018/10000 [09:41<22:12,  5.24step/s, loss=0.156914, elapsed=9.7min]

Entraînement:  30%|███       | 3018/10000 [09:41<22:12,  5.24step/s, loss=0.047678, elapsed=9.7min]

Entraînement:  30%|███       | 3019/10000 [09:41<22:12,  5.24step/s, loss=0.047678, elapsed=9.7min]

Entraînement:  30%|███       | 3019/10000 [09:41<22:12,  5.24step/s, loss=0.095606, elapsed=9.7min]

Entraînement:  30%|███       | 3020/10000 [09:41<22:09,  5.25step/s, loss=0.095606, elapsed=9.7min]

Entraînement:  30%|███       | 3020/10000 [09:41<22:09,  5.25step/s, loss=0.085826, elapsed=9.7min]

Entraînement:  30%|███       | 3021/10000 [09:41<22:09,  5.25step/s, loss=0.085826, elapsed=9.7min]

Entraînement:  30%|███       | 3021/10000 [09:41<22:09,  5.25step/s, loss=0.067876, elapsed=9.7min]

Entraînement:  30%|███       | 3022/10000 [09:41<22:06,  5.26step/s, loss=0.067876, elapsed=9.7min]

Entraînement:  30%|███       | 3022/10000 [09:41<22:06,  5.26step/s, loss=0.078794, elapsed=9.7min]

Entraînement:  30%|███       | 3023/10000 [09:42<22:04,  5.27step/s, loss=0.078794, elapsed=9.7min]

Entraînement:  30%|███       | 3023/10000 [09:42<22:04,  5.27step/s, loss=0.078394, elapsed=9.7min]

Entraînement:  30%|███       | 3024/10000 [09:42<22:03,  5.27step/s, loss=0.078394, elapsed=9.7min]

Entraînement:  30%|███       | 3024/10000 [09:42<22:03,  5.27step/s, loss=0.100804, elapsed=9.7min]

Entraînement:  30%|███       | 3025/10000 [09:42<22:10,  5.24step/s, loss=0.100804, elapsed=9.7min]

Entraînement:  30%|███       | 3025/10000 [09:42<22:10,  5.24step/s, loss=0.042540, elapsed=9.7min]

Entraînement:  30%|███       | 3026/10000 [09:42<22:09,  5.25step/s, loss=0.042540, elapsed=9.7min]

Entraînement:  30%|███       | 3026/10000 [09:42<22:09,  5.25step/s, loss=0.100855, elapsed=9.7min]

Entraînement:  30%|███       | 3027/10000 [09:42<22:08,  5.25step/s, loss=0.100855, elapsed=9.7min]

Entraînement:  30%|███       | 3027/10000 [09:42<22:08,  5.25step/s, loss=0.104618, elapsed=9.7min]

Entraînement:  30%|███       | 3028/10000 [09:43<22:05,  5.26step/s, loss=0.104618, elapsed=9.7min]

Entraînement:  30%|███       | 3028/10000 [09:43<22:05,  5.26step/s, loss=0.056681, elapsed=9.7min]

Entraînement:  30%|███       | 3029/10000 [09:43<22:01,  5.27step/s, loss=0.056681, elapsed=9.7min]

Entraînement:  30%|███       | 3029/10000 [09:43<22:01,  5.27step/s, loss=0.074494, elapsed=9.7min]

Entraînement:  30%|███       | 3030/10000 [09:43<22:01,  5.27step/s, loss=0.074494, elapsed=9.7min]

Entraînement:  30%|███       | 3030/10000 [09:43<22:01,  5.27step/s, loss=0.090888, elapsed=9.7min]

Entraînement:  30%|███       | 3031/10000 [09:43<21:59,  5.28step/s, loss=0.090888, elapsed=9.7min]

Entraînement:  30%|███       | 3031/10000 [09:43<21:59,  5.28step/s, loss=0.040630, elapsed=9.7min]

Entraînement:  30%|███       | 3032/10000 [09:43<21:59,  5.28step/s, loss=0.040630, elapsed=9.7min]

Entraînement:  30%|███       | 3032/10000 [09:43<21:59,  5.28step/s, loss=0.075109, elapsed=9.7min]

Entraînement:  30%|███       | 3033/10000 [09:44<21:56,  5.29step/s, loss=0.075109, elapsed=9.7min]

Entraînement:  30%|███       | 3033/10000 [09:44<21:56,  5.29step/s, loss=0.036239, elapsed=9.7min]

Entraînement:  30%|███       | 3034/10000 [09:44<21:56,  5.29step/s, loss=0.036239, elapsed=9.7min]

Entraînement:  30%|███       | 3034/10000 [09:44<21:56,  5.29step/s, loss=0.077738, elapsed=9.7min]

Entraînement:  30%|███       | 3035/10000 [09:44<21:59,  5.28step/s, loss=0.077738, elapsed=9.7min]

Entraînement:  30%|███       | 3035/10000 [09:44<21:59,  5.28step/s, loss=0.042506, elapsed=9.7min]

Entraînement:  30%|███       | 3036/10000 [09:44<21:58,  5.28step/s, loss=0.042506, elapsed=9.7min]

Entraînement:  30%|███       | 3036/10000 [09:44<21:58,  5.28step/s, loss=0.037401, elapsed=9.7min]

Entraînement:  30%|███       | 3037/10000 [09:44<21:59,  5.28step/s, loss=0.037401, elapsed=9.7min]

Entraînement:  30%|███       | 3037/10000 [09:44<21:59,  5.28step/s, loss=0.031167, elapsed=9.7min]

Entraînement:  30%|███       | 3038/10000 [09:44<21:59,  5.28step/s, loss=0.031167, elapsed=9.7min]

Entraînement:  30%|███       | 3038/10000 [09:44<21:59,  5.28step/s, loss=0.146132, elapsed=9.7min]

Entraînement:  30%|███       | 3039/10000 [09:45<21:56,  5.29step/s, loss=0.146132, elapsed=9.7min]

Entraînement:  30%|███       | 3039/10000 [09:45<21:56,  5.29step/s, loss=0.063343, elapsed=9.8min]

Entraînement:  30%|███       | 3040/10000 [09:45<21:56,  5.29step/s, loss=0.063343, elapsed=9.8min]

Entraînement:  30%|███       | 3040/10000 [09:45<21:56,  5.29step/s, loss=0.038775, elapsed=9.8min]

Entraînement:  30%|███       | 3041/10000 [09:45<21:56,  5.28step/s, loss=0.038775, elapsed=9.8min]

Entraînement:  30%|███       | 3041/10000 [09:45<21:56,  5.28step/s, loss=0.034326, elapsed=9.8min]

Entraînement:  30%|███       | 3042/10000 [09:45<21:58,  5.28step/s, loss=0.034326, elapsed=9.8min]

Entraînement:  30%|███       | 3042/10000 [09:45<21:58,  5.28step/s, loss=0.041188, elapsed=9.8min]

Entraînement:  30%|███       | 3043/10000 [09:45<22:00,  5.27step/s, loss=0.041188, elapsed=9.8min]

Entraînement:  30%|███       | 3043/10000 [09:45<22:00,  5.27step/s, loss=0.032096, elapsed=9.8min]

Entraînement:  30%|███       | 3044/10000 [09:46<21:58,  5.27step/s, loss=0.032096, elapsed=9.8min]

Entraînement:  30%|███       | 3044/10000 [09:46<21:58,  5.27step/s, loss=0.044876, elapsed=9.8min]

Entraînement:  30%|███       | 3045/10000 [09:46<22:00,  5.27step/s, loss=0.044876, elapsed=9.8min]

Entraînement:  30%|███       | 3045/10000 [09:46<22:00,  5.27step/s, loss=0.016274, elapsed=9.8min]

Entraînement:  30%|███       | 3046/10000 [09:46<21:59,  5.27step/s, loss=0.016274, elapsed=9.8min]

Entraînement:  30%|███       | 3046/10000 [09:46<21:59,  5.27step/s, loss=0.041724, elapsed=9.8min]

Entraînement:  30%|███       | 3047/10000 [09:47<55:06,  2.10step/s, loss=0.041724, elapsed=9.8min]

Entraînement:  30%|███       | 3047/10000 [09:47<55:06,  2.10step/s, loss=0.035265, elapsed=9.8min]

Entraînement:  30%|███       | 3048/10000 [09:47<45:07,  2.57step/s, loss=0.035265, elapsed=9.8min]

Entraînement:  30%|███       | 3048/10000 [09:47<45:07,  2.57step/s, loss=0.040944, elapsed=9.8min]

Entraînement:  30%|███       | 3049/10000 [09:47<38:08,  3.04step/s, loss=0.040944, elapsed=9.8min]

Entraînement:  30%|███       | 3049/10000 [09:47<38:08,  3.04step/s, loss=0.075039, elapsed=9.8min]

Entraînement:  30%|███       | 3050/10000 [09:48<33:16,  3.48step/s, loss=0.075039, elapsed=9.8min]

Entraînement:  30%|███       | 3050/10000 [09:48<33:16,  3.48step/s, loss=0.036693, elapsed=9.8min]

Entraînement:  31%|███       | 3051/10000 [09:48<29:54,  3.87step/s, loss=0.036693, elapsed=9.8min]

Entraînement:  31%|███       | 3051/10000 [09:48<29:54,  3.87step/s, loss=0.046066, elapsed=9.8min]

Entraînement:  31%|███       | 3052/10000 [09:48<27:32,  4.21step/s, loss=0.046066, elapsed=9.8min]

Entraînement:  31%|███       | 3052/10000 [09:48<27:32,  4.21step/s, loss=0.026213, elapsed=9.8min]

Entraînement:  31%|███       | 3053/10000 [09:48<25:52,  4.48step/s, loss=0.026213, elapsed=9.8min]

Entraînement:  31%|███       | 3053/10000 [09:48<25:52,  4.48step/s, loss=0.088496, elapsed=9.8min]

Entraînement:  31%|███       | 3054/10000 [09:48<24:45,  4.68step/s, loss=0.088496, elapsed=9.8min]

Entraînement:  31%|███       | 3054/10000 [09:48<24:45,  4.68step/s, loss=0.045210, elapsed=9.8min]

Entraînement:  31%|███       | 3055/10000 [09:49<23:54,  4.84step/s, loss=0.045210, elapsed=9.8min]

Entraînement:  31%|███       | 3055/10000 [09:49<23:54,  4.84step/s, loss=0.053179, elapsed=9.8min]

Entraînement:  31%|███       | 3056/10000 [09:49<23:19,  4.96step/s, loss=0.053179, elapsed=9.8min]

Entraînement:  31%|███       | 3056/10000 [09:49<23:19,  4.96step/s, loss=0.093042, elapsed=9.8min]

Entraînement:  31%|███       | 3057/10000 [09:49<22:54,  5.05step/s, loss=0.093042, elapsed=9.8min]

Entraînement:  31%|███       | 3057/10000 [09:49<22:54,  5.05step/s, loss=0.064200, elapsed=9.8min]

Entraînement:  31%|███       | 3058/10000 [09:49<22:35,  5.12step/s, loss=0.064200, elapsed=9.8min]

Entraînement:  31%|███       | 3058/10000 [09:49<22:35,  5.12step/s, loss=0.070519, elapsed=9.8min]

Entraînement:  31%|███       | 3059/10000 [09:49<22:24,  5.16step/s, loss=0.070519, elapsed=9.8min]

Entraînement:  31%|███       | 3059/10000 [09:49<22:24,  5.16step/s, loss=0.059828, elapsed=9.8min]

Entraînement:  31%|███       | 3060/10000 [09:50<22:15,  5.20step/s, loss=0.059828, elapsed=9.8min]

Entraînement:  31%|███       | 3060/10000 [09:50<22:15,  5.20step/s, loss=0.106928, elapsed=9.8min]

Entraînement:  31%|███       | 3061/10000 [09:50<22:06,  5.23step/s, loss=0.106928, elapsed=9.8min]

Entraînement:  31%|███       | 3061/10000 [09:50<22:06,  5.23step/s, loss=0.059881, elapsed=9.8min]

Entraînement:  31%|███       | 3062/10000 [09:50<22:02,  5.25step/s, loss=0.059881, elapsed=9.8min]

Entraînement:  31%|███       | 3062/10000 [09:50<22:02,  5.25step/s, loss=0.029495, elapsed=9.8min]

Entraînement:  31%|███       | 3063/10000 [09:50<21:58,  5.26step/s, loss=0.029495, elapsed=9.8min]

Entraînement:  31%|███       | 3063/10000 [09:50<21:58,  5.26step/s, loss=0.042512, elapsed=9.8min]

Entraînement:  31%|███       | 3064/10000 [09:50<21:55,  5.27step/s, loss=0.042512, elapsed=9.8min]

Entraînement:  31%|███       | 3064/10000 [09:50<21:55,  5.27step/s, loss=0.077235, elapsed=9.8min]

Entraînement:  31%|███       | 3065/10000 [09:51<21:55,  5.27step/s, loss=0.077235, elapsed=9.8min]

Entraînement:  31%|███       | 3065/10000 [09:51<21:55,  5.27step/s, loss=0.038518, elapsed=9.9min]

Entraînement:  31%|███       | 3066/10000 [09:51<21:45,  5.31step/s, loss=0.038518, elapsed=9.9min]

Entraînement:  31%|███       | 3066/10000 [09:51<21:45,  5.31step/s, loss=0.029130, elapsed=9.9min]

Entraînement:  31%|███       | 3067/10000 [09:51<21:47,  5.30step/s, loss=0.029130, elapsed=9.9min]

Entraînement:  31%|███       | 3067/10000 [09:51<21:47,  5.30step/s, loss=0.061006, elapsed=9.9min]

Entraînement:  31%|███       | 3068/10000 [09:51<21:47,  5.30step/s, loss=0.061006, elapsed=9.9min]

Entraînement:  31%|███       | 3068/10000 [09:51<21:47,  5.30step/s, loss=0.024091, elapsed=9.9min]

Entraînement:  31%|███       | 3069/10000 [09:51<21:46,  5.31step/s, loss=0.024091, elapsed=9.9min]

Entraînement:  31%|███       | 3069/10000 [09:51<21:46,  5.31step/s, loss=0.058545, elapsed=9.9min]

Entraînement:  31%|███       | 3070/10000 [09:51<21:48,  5.29step/s, loss=0.058545, elapsed=9.9min]

Entraînement:  31%|███       | 3070/10000 [09:51<21:48,  5.29step/s, loss=0.112123, elapsed=9.9min]

Entraînement:  31%|███       | 3071/10000 [09:52<21:47,  5.30step/s, loss=0.112123, elapsed=9.9min]

Entraînement:  31%|███       | 3071/10000 [09:52<21:47,  5.30step/s, loss=0.048492, elapsed=9.9min]

Entraînement:  31%|███       | 3072/10000 [09:52<21:49,  5.29step/s, loss=0.048492, elapsed=9.9min]

Entraînement:  31%|███       | 3072/10000 [09:52<21:49,  5.29step/s, loss=0.037139, elapsed=9.9min]

Entraînement:  31%|███       | 3073/10000 [09:52<21:48,  5.29step/s, loss=0.037139, elapsed=9.9min]

Entraînement:  31%|███       | 3073/10000 [09:52<21:48,  5.29step/s, loss=0.035694, elapsed=9.9min]

Entraînement:  31%|███       | 3074/10000 [09:52<21:48,  5.29step/s, loss=0.035694, elapsed=9.9min]

Entraînement:  31%|███       | 3074/10000 [09:52<21:48,  5.29step/s, loss=0.111504, elapsed=9.9min]

Entraînement:  31%|███       | 3075/10000 [09:52<21:49,  5.29step/s, loss=0.111504, elapsed=9.9min]

Entraînement:  31%|███       | 3075/10000 [09:52<21:49,  5.29step/s, loss=0.077617, elapsed=9.9min]

Entraînement:  31%|███       | 3076/10000 [09:53<21:44,  5.31step/s, loss=0.077617, elapsed=9.9min]

Entraînement:  31%|███       | 3076/10000 [09:53<21:44,  5.31step/s, loss=0.089515, elapsed=9.9min]

Entraînement:  31%|███       | 3077/10000 [09:53<21:49,  5.29step/s, loss=0.089515, elapsed=9.9min]

Entraînement:  31%|███       | 3077/10000 [09:53<21:49,  5.29step/s, loss=0.073160, elapsed=9.9min]

Entraînement:  31%|███       | 3078/10000 [09:53<22:14,  5.19step/s, loss=0.073160, elapsed=9.9min]

Entraînement:  31%|███       | 3078/10000 [09:53<22:14,  5.19step/s, loss=0.034315, elapsed=9.9min]

Entraînement:  31%|███       | 3079/10000 [09:53<22:08,  5.21step/s, loss=0.034315, elapsed=9.9min]

Entraînement:  31%|███       | 3079/10000 [09:53<22:08,  5.21step/s, loss=0.038114, elapsed=9.9min]

Entraînement:  31%|███       | 3080/10000 [09:53<22:07,  5.21step/s, loss=0.038114, elapsed=9.9min]

Entraînement:  31%|███       | 3080/10000 [09:53<22:07,  5.21step/s, loss=0.046109, elapsed=9.9min]

Entraînement:  31%|███       | 3081/10000 [09:54<22:02,  5.23step/s, loss=0.046109, elapsed=9.9min]

Entraînement:  31%|███       | 3081/10000 [09:54<22:02,  5.23step/s, loss=0.043039, elapsed=9.9min]

Entraînement:  31%|███       | 3082/10000 [09:54<22:01,  5.23step/s, loss=0.043039, elapsed=9.9min]

Entraînement:  31%|███       | 3082/10000 [09:54<22:01,  5.23step/s, loss=0.108730, elapsed=9.9min]

Entraînement:  31%|███       | 3083/10000 [09:54<21:59,  5.24step/s, loss=0.108730, elapsed=9.9min]

Entraînement:  31%|███       | 3083/10000 [09:54<21:59,  5.24step/s, loss=0.031947, elapsed=9.9min]

Entraînement:  31%|███       | 3084/10000 [09:54<21:56,  5.25step/s, loss=0.031947, elapsed=9.9min]

Entraînement:  31%|███       | 3084/10000 [09:54<21:56,  5.25step/s, loss=0.026186, elapsed=9.9min]

Entraînement:  31%|███       | 3085/10000 [09:54<21:58,  5.24step/s, loss=0.026186, elapsed=9.9min]

Entraînement:  31%|███       | 3085/10000 [09:54<21:58,  5.24step/s, loss=0.037643, elapsed=9.9min]

Entraînement:  31%|███       | 3086/10000 [09:55<21:54,  5.26step/s, loss=0.037643, elapsed=9.9min]

Entraînement:  31%|███       | 3086/10000 [09:55<21:54,  5.26step/s, loss=0.038797, elapsed=9.9min]

Entraînement:  31%|███       | 3087/10000 [09:55<21:55,  5.25step/s, loss=0.038797, elapsed=9.9min]

Entraînement:  31%|███       | 3087/10000 [09:55<21:55,  5.25step/s, loss=0.051758, elapsed=9.9min]

Entraînement:  31%|███       | 3088/10000 [09:55<21:52,  5.26step/s, loss=0.051758, elapsed=9.9min]

Entraînement:  31%|███       | 3088/10000 [09:55<21:52,  5.26step/s, loss=0.058996, elapsed=9.9min]

Entraînement:  31%|███       | 3089/10000 [09:55<21:51,  5.27step/s, loss=0.058996, elapsed=9.9min]

Entraînement:  31%|███       | 3089/10000 [09:55<21:51,  5.27step/s, loss=0.096402, elapsed=9.9min]

Entraînement:  31%|███       | 3090/10000 [09:55<21:50,  5.27step/s, loss=0.096402, elapsed=9.9min]

Entraînement:  31%|███       | 3090/10000 [09:55<21:50,  5.27step/s, loss=0.040625, elapsed=9.9min]

Entraînement:  31%|███       | 3091/10000 [09:55<21:50,  5.27step/s, loss=0.040625, elapsed=9.9min]

Entraînement:  31%|███       | 3091/10000 [09:55<21:50,  5.27step/s, loss=0.045644, elapsed=9.9min]

Entraînement:  31%|███       | 3092/10000 [09:56<21:51,  5.27step/s, loss=0.045644, elapsed=9.9min]

Entraînement:  31%|███       | 3092/10000 [09:56<21:51,  5.27step/s, loss=0.039452, elapsed=9.9min]

Entraînement:  31%|███       | 3093/10000 [09:56<21:50,  5.27step/s, loss=0.039452, elapsed=9.9min]

Entraînement:  31%|███       | 3093/10000 [09:56<21:50,  5.27step/s, loss=0.071362, elapsed=9.9min]

Entraînement:  31%|███       | 3094/10000 [09:56<22:07,  5.20step/s, loss=0.071362, elapsed=9.9min]

Entraînement:  31%|███       | 3094/10000 [09:56<22:07,  5.20step/s, loss=0.166667, elapsed=9.9min]

Entraînement:  31%|███       | 3095/10000 [09:56<22:03,  5.22step/s, loss=0.166667, elapsed=9.9min]

Entraînement:  31%|███       | 3095/10000 [09:56<22:03,  5.22step/s, loss=0.142923, elapsed=9.9min]

Entraînement:  31%|███       | 3096/10000 [09:56<21:57,  5.24step/s, loss=0.142923, elapsed=9.9min]

Entraînement:  31%|███       | 3096/10000 [09:56<21:57,  5.24step/s, loss=0.149177, elapsed=9.9min]

Entraînement:  31%|███       | 3097/10000 [09:57<21:54,  5.25step/s, loss=0.149177, elapsed=9.9min]

Entraînement:  31%|███       | 3097/10000 [09:57<21:54,  5.25step/s, loss=0.132105, elapsed=10.0min]

Entraînement:  31%|███       | 3098/10000 [09:57<21:51,  5.26step/s, loss=0.132105, elapsed=10.0min]

Entraînement:  31%|███       | 3098/10000 [09:57<21:51,  5.26step/s, loss=0.132195, elapsed=10.0min]

Entraînement:  31%|███       | 3099/10000 [09:57<21:50,  5.27step/s, loss=0.132195, elapsed=10.0min]

Entraînement:  31%|███       | 3099/10000 [09:57<21:50,  5.27step/s, loss=0.090005, elapsed=10.0min]

Entraînement:  31%|███       | 3100/10000 [09:57<21:50,  5.26step/s, loss=0.090005, elapsed=10.0min]

Entraînement:  31%|███       | 3100/10000 [09:57<21:50,  5.26step/s, loss=0.134010, elapsed=10.0min]

Entraînement:  31%|███       | 3100/10000 [09:57<21:50,  5.26step/s, loss=0.134010, elapsed=10.0min]

Entraînement:  31%|███       | 3101/10000 [09:57<22:00,  5.23step/s, loss=0.134010, elapsed=10.0min]

Entraînement:  31%|███       | 3101/10000 [09:57<22:00,  5.23step/s, loss=0.121163, elapsed=10.0min]

Step 3100/10000 | Train loss: 0.134010 | Elapsed: 10.0min | ETA: 22.2min

Entraînement:  31%|███       | 3102/10000 [09:58<21:55,  5.24step/s, loss=0.121163, elapsed=10.0min]

Entraînement:  31%|███       | 3102/10000 [09:58<21:55,  5.24step/s, loss=0.056798, elapsed=10.0min]

Entraînement:  31%|███       | 3103/10000 [09:58<21:51,  5.26step/s, loss=0.056798, elapsed=10.0min]

Entraînement:  31%|███       | 3103/10000 [09:58<21:51,  5.26step/s, loss=0.045721, elapsed=10.0min]

Entraînement:  31%|███       | 3104/10000 [09:58<21:49,  5.27step/s, loss=0.045721, elapsed=10.0min]

Entraînement:  31%|███       | 3104/10000 [09:58<21:49,  5.27step/s, loss=0.057168, elapsed=10.0min]

Entraînement:  31%|███       | 3105/10000 [09:58<21:47,  5.27step/s, loss=0.057168, elapsed=10.0min]

Entraînement:  31%|███       | 3105/10000 [09:58<21:47,  5.27step/s, loss=0.075525, elapsed=10.0min]

Entraînement:  31%|███       | 3106/10000 [09:58<21:45,  5.28step/s, loss=0.075525, elapsed=10.0min]

Entraînement:  31%|███       | 3106/10000 [09:58<21:45,  5.28step/s, loss=0.094825, elapsed=10.0min]

Entraînement:  31%|███       | 3107/10000 [09:59<21:46,  5.27step/s, loss=0.094825, elapsed=10.0min]

Entraînement:  31%|███       | 3107/10000 [09:59<21:46,  5.27step/s, loss=0.098741, elapsed=10.0min]

Entraînement:  31%|███       | 3108/10000 [09:59<21:48,  5.27step/s, loss=0.098741, elapsed=10.0min]

Entraînement:  31%|███       | 3108/10000 [09:59<21:48,  5.27step/s, loss=0.085078, elapsed=10.0min]

Entraînement:  31%|███       | 3109/10000 [09:59<21:44,  5.28step/s, loss=0.085078, elapsed=10.0min]

Entraînement:  31%|███       | 3109/10000 [09:59<21:44,  5.28step/s, loss=0.050326, elapsed=10.0min]

Entraînement:  31%|███       | 3110/10000 [09:59<21:43,  5.29step/s, loss=0.050326, elapsed=10.0min]

Entraînement:  31%|███       | 3110/10000 [09:59<21:43,  5.29step/s, loss=0.035409, elapsed=10.0min]

Entraînement:  31%|███       | 3111/10000 [09:59<21:40,  5.30step/s, loss=0.035409, elapsed=10.0min]

Entraînement:  31%|███       | 3111/10000 [09:59<21:40,  5.30step/s, loss=0.052110, elapsed=10.0min]

Entraînement:  31%|███       | 3112/10000 [09:59<21:40,  5.30step/s, loss=0.052110, elapsed=10.0min]

Entraînement:  31%|███       | 3112/10000 [09:59<21:40,  5.30step/s, loss=0.062613, elapsed=10.0min]

Entraînement:  31%|███       | 3113/10000 [10:00<21:38,  5.30step/s, loss=0.062613, elapsed=10.0min]

Entraînement:  31%|███       | 3113/10000 [10:00<21:38,  5.30step/s, loss=0.049820, elapsed=10.0min]

Entraînement:  31%|███       | 3114/10000 [10:00<21:36,  5.31step/s, loss=0.049820, elapsed=10.0min]

Entraînement:  31%|███       | 3114/10000 [10:00<21:36,  5.31step/s, loss=0.038206, elapsed=10.0min]

Entraînement:  31%|███       | 3115/10000 [10:00<21:39,  5.30step/s, loss=0.038206, elapsed=10.0min]

Entraînement:  31%|███       | 3115/10000 [10:00<21:39,  5.30step/s, loss=0.036387, elapsed=10.0min]

Entraînement:  31%|███       | 3116/10000 [10:00<21:41,  5.29step/s, loss=0.036387, elapsed=10.0min]

Entraînement:  31%|███       | 3116/10000 [10:00<21:41,  5.29step/s, loss=0.027176, elapsed=10.0min]

Entraînement:  31%|███       | 3117/10000 [10:00<21:43,  5.28step/s, loss=0.027176, elapsed=10.0min]

Entraînement:  31%|███       | 3117/10000 [10:00<21:43,  5.28step/s, loss=0.035419, elapsed=10.0min]

Entraînement:  31%|███       | 3118/10000 [10:01<21:42,  5.29step/s, loss=0.035419, elapsed=10.0min]

Entraînement:  31%|███       | 3118/10000 [10:01<21:42,  5.29step/s, loss=0.068908, elapsed=10.0min]

Entraînement:  31%|███       | 3119/10000 [10:01<21:41,  5.29step/s, loss=0.068908, elapsed=10.0min]

Entraînement:  31%|███       | 3119/10000 [10:01<21:41,  5.29step/s, loss=0.080665, elapsed=10.0min]

Entraînement:  31%|███       | 3120/10000 [10:01<21:40,  5.29step/s, loss=0.080665, elapsed=10.0min]

Entraînement:  31%|███       | 3120/10000 [10:01<21:40,  5.29step/s, loss=0.037716, elapsed=10.0min]

Entraînement:  31%|███       | 3121/10000 [10:01<21:38,  5.30step/s, loss=0.037716, elapsed=10.0min]

Entraînement:  31%|███       | 3121/10000 [10:01<21:38,  5.30step/s, loss=0.069723, elapsed=10.0min]

Entraînement:  31%|███       | 3122/10000 [10:01<21:39,  5.29step/s, loss=0.069723, elapsed=10.0min]

Entraînement:  31%|███       | 3122/10000 [10:01<21:39,  5.29step/s, loss=0.041796, elapsed=10.0min]

Entraînement:  31%|███       | 3123/10000 [10:02<21:41,  5.28step/s, loss=0.041796, elapsed=10.0min]

Entraînement:  31%|███       | 3123/10000 [10:02<21:41,  5.28step/s, loss=0.056317, elapsed=10.0min]

Entraînement:  31%|███       | 3124/10000 [10:02<21:42,  5.28step/s, loss=0.056317, elapsed=10.0min]

Entraînement:  31%|███       | 3124/10000 [10:02<21:42,  5.28step/s, loss=0.106514, elapsed=10.0min]

Entraînement:  31%|███▏      | 3125/10000 [10:02<21:42,  5.28step/s, loss=0.106514, elapsed=10.0min]

Entraînement:  31%|███▏      | 3125/10000 [10:02<21:42,  5.28step/s, loss=0.089132, elapsed=10.0min]

Entraînement:  31%|███▏      | 3126/10000 [10:02<21:41,  5.28step/s, loss=0.089132, elapsed=10.0min]

Entraînement:  31%|███▏      | 3126/10000 [10:02<21:41,  5.28step/s, loss=0.047222, elapsed=10.0min]

Entraînement:  31%|███▏      | 3127/10000 [10:02<21:42,  5.28step/s, loss=0.047222, elapsed=10.0min]

Entraînement:  31%|███▏      | 3127/10000 [10:02<21:42,  5.28step/s, loss=0.104316, elapsed=10.0min]

Entraînement:  31%|███▏      | 3128/10000 [10:02<21:40,  5.29step/s, loss=0.104316, elapsed=10.0min]

Entraînement:  31%|███▏      | 3128/10000 [10:02<21:40,  5.29step/s, loss=0.058549, elapsed=10.0min]

Entraînement:  31%|███▏      | 3129/10000 [10:03<21:38,  5.29step/s, loss=0.058549, elapsed=10.0min]

Entraînement:  31%|███▏      | 3129/10000 [10:03<21:38,  5.29step/s, loss=0.047496, elapsed=10.1min]

Entraînement:  31%|███▏      | 3130/10000 [10:03<21:38,  5.29step/s, loss=0.047496, elapsed=10.1min]

Entraînement:  31%|███▏      | 3130/10000 [10:03<21:38,  5.29step/s, loss=0.030870, elapsed=10.1min]

Entraînement:  31%|███▏      | 3131/10000 [10:03<21:36,  5.30step/s, loss=0.030870, elapsed=10.1min]

Entraînement:  31%|███▏      | 3131/10000 [10:03<21:36,  5.30step/s, loss=0.037850, elapsed=10.1min]

Entraînement:  31%|███▏      | 3132/10000 [10:03<21:37,  5.29step/s, loss=0.037850, elapsed=10.1min]

Entraînement:  31%|███▏      | 3132/10000 [10:03<21:37,  5.29step/s, loss=0.056253, elapsed=10.1min]

Entraînement:  31%|███▏      | 3133/10000 [10:03<21:36,  5.30step/s, loss=0.056253, elapsed=10.1min]

Entraînement:  31%|███▏      | 3133/10000 [10:03<21:36,  5.30step/s, loss=0.058714, elapsed=10.1min]

Entraînement:  31%|███▏      | 3134/10000 [10:04<21:36,  5.30step/s, loss=0.058714, elapsed=10.1min]

Entraînement:  31%|███▏      | 3134/10000 [10:04<21:36,  5.30step/s, loss=0.019673, elapsed=10.1min]

Entraînement:  31%|███▏      | 3135/10000 [10:04<21:36,  5.29step/s, loss=0.019673, elapsed=10.1min]

Entraînement:  31%|███▏      | 3135/10000 [10:04<21:36,  5.29step/s, loss=0.020088, elapsed=10.1min]

Entraînement:  31%|███▏      | 3136/10000 [10:04<21:36,  5.29step/s, loss=0.020088, elapsed=10.1min]

Entraînement:  31%|███▏      | 3136/10000 [10:04<21:36,  5.29step/s, loss=0.041374, elapsed=10.1min]

Entraînement:  31%|███▏      | 3137/10000 [10:04<21:36,  5.29step/s, loss=0.041374, elapsed=10.1min]

Entraînement:  31%|███▏      | 3137/10000 [10:04<21:36,  5.29step/s, loss=0.060534, elapsed=10.1min]

Entraînement:  31%|███▏      | 3138/10000 [10:04<21:38,  5.29step/s, loss=0.060534, elapsed=10.1min]

Entraînement:  31%|███▏      | 3138/10000 [10:04<21:38,  5.29step/s, loss=0.043190, elapsed=10.1min]

Entraînement:  31%|███▏      | 3139/10000 [10:05<21:41,  5.27step/s, loss=0.043190, elapsed=10.1min]

Entraînement:  31%|███▏      | 3139/10000 [10:05<21:41,  5.27step/s, loss=0.037366, elapsed=10.1min]

Entraînement:  31%|███▏      | 3140/10000 [10:05<21:40,  5.27step/s, loss=0.037366, elapsed=10.1min]

Entraînement:  31%|███▏      | 3140/10000 [10:05<21:40,  5.27step/s, loss=0.026173, elapsed=10.1min]

Entraînement:  31%|███▏      | 3141/10000 [10:05<21:42,  5.27step/s, loss=0.026173, elapsed=10.1min]

Entraînement:  31%|███▏      | 3141/10000 [10:05<21:42,  5.27step/s, loss=0.107899, elapsed=10.1min]

Entraînement:  31%|███▏      | 3142/10000 [10:05<21:40,  5.27step/s, loss=0.107899, elapsed=10.1min]

Entraînement:  31%|███▏      | 3142/10000 [10:05<21:40,  5.27step/s, loss=0.065274, elapsed=10.1min]

Entraînement:  31%|███▏      | 3143/10000 [10:05<21:38,  5.28step/s, loss=0.065274, elapsed=10.1min]

Entraînement:  31%|███▏      | 3143/10000 [10:05<21:38,  5.28step/s, loss=0.059302, elapsed=10.1min]

Entraînement:  31%|███▏      | 3144/10000 [10:05<21:37,  5.28step/s, loss=0.059302, elapsed=10.1min]

Entraînement:  31%|███▏      | 3144/10000 [10:06<21:37,  5.28step/s, loss=0.125610, elapsed=10.1min]

Entraînement:  31%|███▏      | 3145/10000 [10:06<21:36,  5.29step/s, loss=0.125610, elapsed=10.1min]

Entraînement:  31%|███▏      | 3145/10000 [10:06<21:36,  5.29step/s, loss=0.071149, elapsed=10.1min]

Entraînement:  31%|███▏      | 3146/10000 [10:06<21:43,  5.26step/s, loss=0.071149, elapsed=10.1min]

Entraînement:  31%|███▏      | 3146/10000 [10:06<21:43,  5.26step/s, loss=0.113116, elapsed=10.1min]

Entraînement:  31%|███▏      | 3147/10000 [10:06<21:44,  5.25step/s, loss=0.113116, elapsed=10.1min]

Entraînement:  31%|███▏      | 3147/10000 [10:06<21:44,  5.25step/s, loss=0.044174, elapsed=10.1min]

Entraînement:  31%|███▏      | 3148/10000 [10:06<21:44,  5.25step/s, loss=0.044174, elapsed=10.1min]

Entraînement:  31%|███▏      | 3148/10000 [10:06<21:44,  5.25step/s, loss=0.034012, elapsed=10.1min]

Entraînement:  31%|███▏      | 3149/10000 [10:06<21:42,  5.26step/s, loss=0.034012, elapsed=10.1min]

Entraînement:  31%|███▏      | 3149/10000 [10:06<21:42,  5.26step/s, loss=0.027565, elapsed=10.1min]

Entraînement:  32%|███▏      | 3150/10000 [10:07<21:38,  5.28step/s, loss=0.027565, elapsed=10.1min]

Entraînement:  32%|███▏      | 3150/10000 [10:07<21:38,  5.28step/s, loss=0.039961, elapsed=10.1min]

Entraînement:  32%|███▏      | 3151/10000 [10:07<21:38,  5.28step/s, loss=0.039961, elapsed=10.1min]

Entraînement:  32%|███▏      | 3151/10000 [10:07<21:38,  5.28step/s, loss=0.039167, elapsed=10.1min]

Entraînement:  32%|███▏      | 3152/10000 [10:07<21:36,  5.28step/s, loss=0.039167, elapsed=10.1min]

Entraînement:  32%|███▏      | 3152/10000 [10:07<21:36,  5.28step/s, loss=0.088132, elapsed=10.1min]

Entraînement:  32%|███▏      | 3153/10000 [10:07<21:36,  5.28step/s, loss=0.088132, elapsed=10.1min]

Entraînement:  32%|███▏      | 3153/10000 [10:07<21:36,  5.28step/s, loss=0.029677, elapsed=10.1min]

Entraînement:  32%|███▏      | 3154/10000 [10:07<21:37,  5.27step/s, loss=0.029677, elapsed=10.1min]

Entraînement:  32%|███▏      | 3154/10000 [10:07<21:37,  5.27step/s, loss=0.029482, elapsed=10.1min]

Entraînement:  32%|███▏      | 3155/10000 [10:08<21:36,  5.28step/s, loss=0.029482, elapsed=10.1min]

Entraînement:  32%|███▏      | 3155/10000 [10:08<21:36,  5.28step/s, loss=0.017953, elapsed=10.1min]

Entraînement:  32%|███▏      | 3156/10000 [10:08<21:36,  5.28step/s, loss=0.017953, elapsed=10.1min]

Entraînement:  32%|███▏      | 3156/10000 [10:08<21:36,  5.28step/s, loss=0.063274, elapsed=10.1min]

Entraînement:  32%|███▏      | 3157/10000 [10:08<21:34,  5.29step/s, loss=0.063274, elapsed=10.1min]

Entraînement:  32%|███▏      | 3157/10000 [10:08<21:34,  5.29step/s, loss=0.104686, elapsed=10.1min]

Entraînement:  32%|███▏      | 3158/10000 [10:08<21:36,  5.28step/s, loss=0.104686, elapsed=10.1min]

Entraînement:  32%|███▏      | 3158/10000 [10:08<21:36,  5.28step/s, loss=0.046164, elapsed=10.1min]

Entraînement:  32%|███▏      | 3159/10000 [10:08<21:36,  5.28step/s, loss=0.046164, elapsed=10.1min]

Entraînement:  32%|███▏      | 3159/10000 [10:08<21:36,  5.28step/s, loss=0.033342, elapsed=10.1min]

Entraînement:  32%|███▏      | 3160/10000 [10:09<21:36,  5.28step/s, loss=0.033342, elapsed=10.1min]

Entraînement:  32%|███▏      | 3160/10000 [10:09<21:36,  5.28step/s, loss=0.092829, elapsed=10.2min]

Entraînement:  32%|███▏      | 3161/10000 [10:09<21:37,  5.27step/s, loss=0.092829, elapsed=10.2min]

Entraînement:  32%|███▏      | 3161/10000 [10:09<21:37,  5.27step/s, loss=0.068042, elapsed=10.2min]

Entraînement:  32%|███▏      | 3162/10000 [10:09<21:39,  5.26step/s, loss=0.068042, elapsed=10.2min]

Entraînement:  32%|███▏      | 3162/10000 [10:09<21:39,  5.26step/s, loss=0.072245, elapsed=10.2min]

Entraînement:  32%|███▏      | 3163/10000 [10:09<21:37,  5.27step/s, loss=0.072245, elapsed=10.2min]

Entraînement:  32%|███▏      | 3163/10000 [10:09<21:37,  5.27step/s, loss=0.035464, elapsed=10.2min]

Entraînement:  32%|███▏      | 3164/10000 [10:09<21:38,  5.26step/s, loss=0.035464, elapsed=10.2min]

Entraînement:  32%|███▏      | 3164/10000 [10:09<21:38,  5.26step/s, loss=0.044664, elapsed=10.2min]

Entraînement:  32%|███▏      | 3165/10000 [10:09<21:37,  5.27step/s, loss=0.044664, elapsed=10.2min]

Entraînement:  32%|███▏      | 3165/10000 [10:09<21:37,  5.27step/s, loss=0.034665, elapsed=10.2min]

Entraînement:  32%|███▏      | 3166/10000 [10:10<21:37,  5.27step/s, loss=0.034665, elapsed=10.2min]

Entraînement:  32%|███▏      | 3166/10000 [10:10<21:37,  5.27step/s, loss=0.037098, elapsed=10.2min]

Entraînement:  32%|███▏      | 3167/10000 [10:10<21:42,  5.25step/s, loss=0.037098, elapsed=10.2min]

Entraînement:  32%|███▏      | 3167/10000 [10:10<21:42,  5.25step/s, loss=0.114348, elapsed=10.2min]

Entraînement:  32%|███▏      | 3168/10000 [10:10<21:38,  5.26step/s, loss=0.114348, elapsed=10.2min]

Entraînement:  32%|███▏      | 3168/10000 [10:10<21:38,  5.26step/s, loss=0.042407, elapsed=10.2min]

Entraînement:  32%|███▏      | 3169/10000 [10:10<21:39,  5.26step/s, loss=0.042407, elapsed=10.2min]

Entraînement:  32%|███▏      | 3169/10000 [10:10<21:39,  5.26step/s, loss=0.065095, elapsed=10.2min]

Entraînement:  32%|███▏      | 3170/10000 [10:10<21:37,  5.26step/s, loss=0.065095, elapsed=10.2min]

Entraînement:  32%|███▏      | 3170/10000 [10:10<21:37,  5.26step/s, loss=0.033965, elapsed=10.2min]

Entraînement:  32%|███▏      | 3171/10000 [10:11<21:36,  5.27step/s, loss=0.033965, elapsed=10.2min]

Entraînement:  32%|███▏      | 3171/10000 [10:11<21:36,  5.27step/s, loss=0.060293, elapsed=10.2min]

Entraînement:  32%|███▏      | 3172/10000 [10:11<21:34,  5.28step/s, loss=0.060293, elapsed=10.2min]

Entraînement:  32%|███▏      | 3172/10000 [10:11<21:34,  5.28step/s, loss=0.032838, elapsed=10.2min]

Entraînement:  32%|███▏      | 3173/10000 [10:11<21:31,  5.29step/s, loss=0.032838, elapsed=10.2min]

Entraînement:  32%|███▏      | 3173/10000 [10:11<21:31,  5.29step/s, loss=0.084192, elapsed=10.2min]

Entraînement:  32%|███▏      | 3174/10000 [10:11<21:30,  5.29step/s, loss=0.084192, elapsed=10.2min]

Entraînement:  32%|███▏      | 3174/10000 [10:11<21:30,  5.29step/s, loss=0.050192, elapsed=10.2min]

Entraînement:  32%|███▏      | 3175/10000 [10:11<21:30,  5.29step/s, loss=0.050192, elapsed=10.2min]

Entraînement:  32%|███▏      | 3175/10000 [10:11<21:30,  5.29step/s, loss=0.056988, elapsed=10.2min]

Entraînement:  32%|███▏      | 3176/10000 [10:12<21:30,  5.29step/s, loss=0.056988, elapsed=10.2min]

Entraînement:  32%|███▏      | 3176/10000 [10:12<21:30,  5.29step/s, loss=0.033796, elapsed=10.2min]

Entraînement:  32%|███▏      | 3177/10000 [10:12<21:31,  5.28step/s, loss=0.033796, elapsed=10.2min]

Entraînement:  32%|███▏      | 3177/10000 [10:12<21:31,  5.28step/s, loss=0.039505, elapsed=10.2min]

Entraînement:  32%|███▏      | 3178/10000 [10:12<21:31,  5.28step/s, loss=0.039505, elapsed=10.2min]

Entraînement:  32%|███▏      | 3178/10000 [10:12<21:31,  5.28step/s, loss=0.053540, elapsed=10.2min]

Entraînement:  32%|███▏      | 3179/10000 [10:12<21:32,  5.28step/s, loss=0.053540, elapsed=10.2min]

Entraînement:  32%|███▏      | 3179/10000 [10:12<21:32,  5.28step/s, loss=0.039127, elapsed=10.2min]

Entraînement:  32%|███▏      | 3180/10000 [10:12<21:32,  5.28step/s, loss=0.039127, elapsed=10.2min]

Entraînement:  32%|███▏      | 3180/10000 [10:12<21:32,  5.28step/s, loss=0.042466, elapsed=10.2min]

Entraînement:  32%|███▏      | 3181/10000 [10:13<21:32,  5.28step/s, loss=0.042466, elapsed=10.2min]

Entraînement:  32%|███▏      | 3181/10000 [10:13<21:32,  5.28step/s, loss=0.055636, elapsed=10.2min]

Entraînement:  32%|███▏      | 3182/10000 [10:13<21:29,  5.29step/s, loss=0.055636, elapsed=10.2min]

Entraînement:  32%|███▏      | 3182/10000 [10:13<21:29,  5.29step/s, loss=0.038078, elapsed=10.2min]

Entraînement:  32%|███▏      | 3183/10000 [10:13<21:30,  5.28step/s, loss=0.038078, elapsed=10.2min]

Entraînement:  32%|███▏      | 3183/10000 [10:13<21:30,  5.28step/s, loss=0.034132, elapsed=10.2min]

Entraînement:  32%|███▏      | 3184/10000 [10:13<21:30,  5.28step/s, loss=0.034132, elapsed=10.2min]

Entraînement:  32%|███▏      | 3184/10000 [10:13<21:30,  5.28step/s, loss=0.102915, elapsed=10.2min]

Entraînement:  32%|███▏      | 3185/10000 [10:13<21:36,  5.26step/s, loss=0.102915, elapsed=10.2min]

Entraînement:  32%|███▏      | 3185/10000 [10:13<21:36,  5.26step/s, loss=0.175786, elapsed=10.2min]

Entraînement:  32%|███▏      | 3186/10000 [10:13<21:35,  5.26step/s, loss=0.175786, elapsed=10.2min]

Entraînement:  32%|███▏      | 3186/10000 [10:13<21:35,  5.26step/s, loss=0.115554, elapsed=10.2min]

Entraînement:  32%|███▏      | 3187/10000 [10:14<21:37,  5.25step/s, loss=0.115554, elapsed=10.2min]

Entraînement:  32%|███▏      | 3187/10000 [10:14<21:37,  5.25step/s, loss=0.049273, elapsed=10.2min]

Entraînement:  32%|███▏      | 3188/10000 [10:14<21:36,  5.25step/s, loss=0.049273, elapsed=10.2min]

Entraînement:  32%|███▏      | 3188/10000 [10:14<21:36,  5.25step/s, loss=0.037347, elapsed=10.2min]

Entraînement:  32%|███▏      | 3189/10000 [10:14<21:37,  5.25step/s, loss=0.037347, elapsed=10.2min]

Entraînement:  32%|███▏      | 3189/10000 [10:14<21:37,  5.25step/s, loss=0.033716, elapsed=10.2min]

Entraînement:  32%|███▏      | 3190/10000 [10:14<21:38,  5.24step/s, loss=0.033716, elapsed=10.2min]

Entraînement:  32%|███▏      | 3190/10000 [10:14<21:38,  5.24step/s, loss=0.076466, elapsed=10.2min]

Entraînement:  32%|███▏      | 3191/10000 [10:14<21:41,  5.23step/s, loss=0.076466, elapsed=10.2min]

Entraînement:  32%|███▏      | 3191/10000 [10:14<21:41,  5.23step/s, loss=0.031832, elapsed=10.2min]

Entraînement:  32%|███▏      | 3192/10000 [10:15<21:41,  5.23step/s, loss=0.031832, elapsed=10.2min]

Entraînement:  32%|███▏      | 3192/10000 [10:15<21:41,  5.23step/s, loss=0.126108, elapsed=10.3min]

Entraînement:  32%|███▏      | 3193/10000 [10:15<21:44,  5.22step/s, loss=0.126108, elapsed=10.3min]

Entraînement:  32%|███▏      | 3193/10000 [10:15<21:44,  5.22step/s, loss=0.045369, elapsed=10.3min]

Entraînement:  32%|███▏      | 3194/10000 [10:15<21:42,  5.22step/s, loss=0.045369, elapsed=10.3min]

Entraînement:  32%|███▏      | 3194/10000 [10:15<21:42,  5.22step/s, loss=0.053196, elapsed=10.3min]

Entraînement:  32%|███▏      | 3195/10000 [10:15<21:45,  5.21step/s, loss=0.053196, elapsed=10.3min]

Entraînement:  32%|███▏      | 3195/10000 [10:15<21:45,  5.21step/s, loss=0.115806, elapsed=10.3min]

Entraînement:  32%|███▏      | 3196/10000 [10:15<21:43,  5.22step/s, loss=0.115806, elapsed=10.3min]

Entraînement:  32%|███▏      | 3196/10000 [10:15<21:43,  5.22step/s, loss=0.051617, elapsed=10.3min]

Entraînement:  32%|███▏      | 3197/10000 [10:16<21:41,  5.23step/s, loss=0.051617, elapsed=10.3min]

Entraînement:  32%|███▏      | 3197/10000 [10:16<21:41,  5.23step/s, loss=0.020756, elapsed=10.3min]

Entraînement:  32%|███▏      | 3198/10000 [10:16<21:37,  5.24step/s, loss=0.020756, elapsed=10.3min]

Entraînement:  32%|███▏      | 3198/10000 [10:16<21:37,  5.24step/s, loss=0.052566, elapsed=10.3min]

Entraînement:  32%|███▏      | 3199/10000 [10:16<21:37,  5.24step/s, loss=0.052566, elapsed=10.3min]

Entraînement:  32%|███▏      | 3199/10000 [10:16<21:37,  5.24step/s, loss=0.084935, elapsed=10.3min]

Entraînement:  32%|███▏      | 3200/10000 [10:16<21:37,  5.24step/s, loss=0.084935, elapsed=10.3min]

Entraînement:  32%|███▏      | 3200/10000 [10:16<21:37,  5.24step/s, loss=0.127514, elapsed=10.3min]

Entraînement:  32%|███▏      | 3200/10000 [10:16<21:37,  5.24step/s, loss=0.127514, elapsed=10.3min]

Entraînement:  32%|███▏      | 3201/10000 [10:16<21:49,  5.19step/s, loss=0.127514, elapsed=10.3min]

Entraînement:  32%|███▏      | 3201/10000 [10:16<21:49,  5.19step/s, loss=0.133934, elapsed=10.3min]

Step 3200/10000 | Train loss: 0.127514 | Elapsed: 10.3min | ETA: 21.8min

Entraînement:  32%|███▏      | 3202/10000 [10:17<21:42,  5.22step/s, loss=0.133934, elapsed=10.3min]

Entraînement:  32%|███▏      | 3202/10000 [10:17<21:42,  5.22step/s, loss=0.061050, elapsed=10.3min]

Entraînement:  32%|███▏      | 3203/10000 [10:17<21:41,  5.22step/s, loss=0.061050, elapsed=10.3min]

Entraînement:  32%|███▏      | 3203/10000 [10:17<21:41,  5.22step/s, loss=0.087165, elapsed=10.3min]

Entraînement:  32%|███▏      | 3204/10000 [10:17<21:37,  5.24step/s, loss=0.087165, elapsed=10.3min]

Entraînement:  32%|███▏      | 3204/10000 [10:17<21:37,  5.24step/s, loss=0.031631, elapsed=10.3min]

Entraînement:  32%|███▏      | 3205/10000 [10:17<21:37,  5.24step/s, loss=0.031631, elapsed=10.3min]

Entraînement:  32%|███▏      | 3205/10000 [10:17<21:37,  5.24step/s, loss=0.083519, elapsed=10.3min]

Entraînement:  32%|███▏      | 3206/10000 [10:17<21:34,  5.25step/s, loss=0.083519, elapsed=10.3min]

Entraînement:  32%|███▏      | 3206/10000 [10:17<21:34,  5.25step/s, loss=0.026107, elapsed=10.3min]

Entraînement:  32%|███▏      | 3207/10000 [10:17<21:35,  5.24step/s, loss=0.026107, elapsed=10.3min]

Entraînement:  32%|███▏      | 3207/10000 [10:17<21:35,  5.24step/s, loss=0.032671, elapsed=10.3min]

Entraînement:  32%|███▏      | 3208/10000 [10:18<21:32,  5.25step/s, loss=0.032671, elapsed=10.3min]

Entraînement:  32%|███▏      | 3208/10000 [10:18<21:32,  5.25step/s, loss=0.057630, elapsed=10.3min]

Entraînement:  32%|███▏      | 3209/10000 [10:18<21:31,  5.26step/s, loss=0.057630, elapsed=10.3min]

Entraînement:  32%|███▏      | 3209/10000 [10:18<21:31,  5.26step/s, loss=0.045689, elapsed=10.3min]

Entraînement:  32%|███▏      | 3210/10000 [10:18<21:29,  5.26step/s, loss=0.045689, elapsed=10.3min]

Entraînement:  32%|███▏      | 3210/10000 [10:18<21:29,  5.26step/s, loss=0.107172, elapsed=10.3min]

Entraînement:  32%|███▏      | 3211/10000 [10:18<21:29,  5.27step/s, loss=0.107172, elapsed=10.3min]

Entraînement:  32%|███▏      | 3211/10000 [10:18<21:29,  5.27step/s, loss=0.046678, elapsed=10.3min]

Entraînement:  32%|███▏      | 3212/10000 [10:18<21:27,  5.27step/s, loss=0.046678, elapsed=10.3min]

Entraînement:  32%|███▏      | 3212/10000 [10:18<21:27,  5.27step/s, loss=0.028265, elapsed=10.3min]

Entraînement:  32%|███▏      | 3213/10000 [10:19<21:26,  5.27step/s, loss=0.028265, elapsed=10.3min]

Entraînement:  32%|███▏      | 3213/10000 [10:19<21:26,  5.27step/s, loss=0.099641, elapsed=10.3min]

Entraînement:  32%|███▏      | 3214/10000 [10:19<21:29,  5.26step/s, loss=0.099641, elapsed=10.3min]

Entraînement:  32%|███▏      | 3214/10000 [10:19<21:29,  5.26step/s, loss=0.068254, elapsed=10.3min]

Entraînement:  32%|███▏      | 3215/10000 [10:19<21:31,  5.25step/s, loss=0.068254, elapsed=10.3min]

Entraînement:  32%|███▏      | 3215/10000 [10:19<21:31,  5.25step/s, loss=0.098214, elapsed=10.3min]

Entraînement:  32%|███▏      | 3216/10000 [10:19<21:27,  5.27step/s, loss=0.098214, elapsed=10.3min]

Entraînement:  32%|███▏      | 3216/10000 [10:19<21:27,  5.27step/s, loss=0.061530, elapsed=10.3min]

Entraînement:  32%|███▏      | 3217/10000 [10:19<21:28,  5.26step/s, loss=0.061530, elapsed=10.3min]

Entraînement:  32%|███▏      | 3217/10000 [10:19<21:28,  5.26step/s, loss=0.033934, elapsed=10.3min]

Entraînement:  32%|███▏      | 3218/10000 [10:20<21:26,  5.27step/s, loss=0.033934, elapsed=10.3min]

Entraînement:  32%|███▏      | 3218/10000 [10:20<21:26,  5.27step/s, loss=0.084514, elapsed=10.3min]

Entraînement:  32%|███▏      | 3219/10000 [10:20<21:26,  5.27step/s, loss=0.084514, elapsed=10.3min]

Entraînement:  32%|███▏      | 3219/10000 [10:20<21:26,  5.27step/s, loss=0.060827, elapsed=10.3min]

Entraînement:  32%|███▏      | 3220/10000 [10:20<21:25,  5.27step/s, loss=0.060827, elapsed=10.3min]

Entraînement:  32%|███▏      | 3220/10000 [10:20<21:25,  5.27step/s, loss=0.037618, elapsed=10.3min]

Entraînement:  32%|███▏      | 3221/10000 [10:20<21:24,  5.28step/s, loss=0.037618, elapsed=10.3min]

Entraînement:  32%|███▏      | 3221/10000 [10:20<21:24,  5.28step/s, loss=0.049068, elapsed=10.3min]

Entraînement:  32%|███▏      | 3222/10000 [10:20<21:27,  5.26step/s, loss=0.049068, elapsed=10.3min]

Entraînement:  32%|███▏      | 3222/10000 [10:20<21:27,  5.26step/s, loss=0.058514, elapsed=10.3min]

Entraînement:  32%|███▏      | 3223/10000 [10:21<21:28,  5.26step/s, loss=0.058514, elapsed=10.3min]

Entraînement:  32%|███▏      | 3223/10000 [10:21<21:28,  5.26step/s, loss=0.040461, elapsed=10.4min]

Entraînement:  32%|███▏      | 3224/10000 [10:21<21:26,  5.27step/s, loss=0.040461, elapsed=10.4min]

Entraînement:  32%|███▏      | 3224/10000 [10:21<21:26,  5.27step/s, loss=0.047764, elapsed=10.4min]

Entraînement:  32%|███▏      | 3225/10000 [10:21<21:24,  5.27step/s, loss=0.047764, elapsed=10.4min]

Entraînement:  32%|███▏      | 3225/10000 [10:21<21:24,  5.27step/s, loss=0.078941, elapsed=10.4min]

Entraînement:  32%|███▏      | 3226/10000 [10:21<21:23,  5.28step/s, loss=0.078941, elapsed=10.4min]

Entraînement:  32%|███▏      | 3226/10000 [10:21<21:23,  5.28step/s, loss=0.063439, elapsed=10.4min]

Entraînement:  32%|███▏      | 3227/10000 [10:21<21:23,  5.28step/s, loss=0.063439, elapsed=10.4min]

Entraînement:  32%|███▏      | 3227/10000 [10:21<21:23,  5.28step/s, loss=0.037788, elapsed=10.4min]

Entraînement:  32%|███▏      | 3228/10000 [10:21<21:20,  5.29step/s, loss=0.037788, elapsed=10.4min]

Entraînement:  32%|███▏      | 3228/10000 [10:21<21:20,  5.29step/s, loss=0.052196, elapsed=10.4min]

Entraînement:  32%|███▏      | 3229/10000 [10:22<21:21,  5.28step/s, loss=0.052196, elapsed=10.4min]

Entraînement:  32%|███▏      | 3229/10000 [10:22<21:21,  5.28step/s, loss=0.114582, elapsed=10.4min]

Entraînement:  32%|███▏      | 3230/10000 [10:22<21:21,  5.28step/s, loss=0.114582, elapsed=10.4min]

Entraînement:  32%|███▏      | 3230/10000 [10:22<21:21,  5.28step/s, loss=0.032173, elapsed=10.4min]

Entraînement:  32%|███▏      | 3231/10000 [10:22<21:25,  5.27step/s, loss=0.032173, elapsed=10.4min]

Entraînement:  32%|███▏      | 3231/10000 [10:22<21:25,  5.27step/s, loss=0.041063, elapsed=10.4min]

Entraînement:  32%|███▏      | 3232/10000 [10:22<21:23,  5.27step/s, loss=0.041063, elapsed=10.4min]

Entraînement:  32%|███▏      | 3232/10000 [10:22<21:23,  5.27step/s, loss=0.039695, elapsed=10.4min]

Entraînement:  32%|███▏      | 3233/10000 [10:22<21:23,  5.27step/s, loss=0.039695, elapsed=10.4min]

Entraînement:  32%|███▏      | 3233/10000 [10:22<21:23,  5.27step/s, loss=0.038536, elapsed=10.4min]

Entraînement:  32%|███▏      | 3234/10000 [10:23<21:21,  5.28step/s, loss=0.038536, elapsed=10.4min]

Entraînement:  32%|███▏      | 3234/10000 [10:23<21:21,  5.28step/s, loss=0.037519, elapsed=10.4min]

Entraînement:  32%|███▏      | 3235/10000 [10:23<21:22,  5.28step/s, loss=0.037519, elapsed=10.4min]

Entraînement:  32%|███▏      | 3235/10000 [10:23<21:22,  5.28step/s, loss=0.039321, elapsed=10.4min]

Entraînement:  32%|███▏      | 3236/10000 [10:23<21:21,  5.28step/s, loss=0.039321, elapsed=10.4min]

Entraînement:  32%|███▏      | 3236/10000 [10:23<21:21,  5.28step/s, loss=0.055860, elapsed=10.4min]

Entraînement:  32%|███▏      | 3237/10000 [10:23<21:22,  5.28step/s, loss=0.055860, elapsed=10.4min]

Entraînement:  32%|███▏      | 3237/10000 [10:23<21:22,  5.28step/s, loss=0.061503, elapsed=10.4min]

Entraînement:  32%|███▏      | 3238/10000 [10:23<21:21,  5.28step/s, loss=0.061503, elapsed=10.4min]

Entraînement:  32%|███▏      | 3238/10000 [10:23<21:21,  5.28step/s, loss=0.034047, elapsed=10.4min]

Entraînement:  32%|███▏      | 3239/10000 [10:24<21:21,  5.28step/s, loss=0.034047, elapsed=10.4min]

Entraînement:  32%|███▏      | 3239/10000 [10:24<21:21,  5.28step/s, loss=0.023731, elapsed=10.4min]

Entraînement:  32%|███▏      | 3240/10000 [10:24<21:18,  5.29step/s, loss=0.023731, elapsed=10.4min]

Entraînement:  32%|███▏      | 3240/10000 [10:24<21:18,  5.29step/s, loss=0.036782, elapsed=10.4min]

Entraînement:  32%|███▏      | 3241/10000 [10:24<21:16,  5.30step/s, loss=0.036782, elapsed=10.4min]

Entraînement:  32%|███▏      | 3241/10000 [10:24<21:16,  5.30step/s, loss=0.042434, elapsed=10.4min]

Entraînement:  32%|███▏      | 3242/10000 [10:24<21:16,  5.29step/s, loss=0.042434, elapsed=10.4min]

Entraînement:  32%|███▏      | 3242/10000 [10:24<21:16,  5.29step/s, loss=0.109057, elapsed=10.4min]

Entraînement:  32%|███▏      | 3243/10000 [10:24<21:15,  5.30step/s, loss=0.109057, elapsed=10.4min]

Entraînement:  32%|███▏      | 3243/10000 [10:24<21:15,  5.30step/s, loss=0.103579, elapsed=10.4min]

Entraînement:  32%|███▏      | 3244/10000 [10:24<21:16,  5.29step/s, loss=0.103579, elapsed=10.4min]

Entraînement:  32%|███▏      | 3244/10000 [10:24<21:16,  5.29step/s, loss=0.067225, elapsed=10.4min]

Entraînement:  32%|███▏      | 3245/10000 [10:25<31:55,  3.53step/s, loss=0.067225, elapsed=10.4min]

Entraînement:  32%|███▏      | 3245/10000 [10:25<31:55,  3.53step/s, loss=0.036422, elapsed=10.4min]

Entraînement:  32%|███▏      | 3246/10000 [10:25<28:54,  3.90step/s, loss=0.036422, elapsed=10.4min]

Entraînement:  32%|███▏      | 3246/10000 [10:25<28:54,  3.90step/s, loss=0.045268, elapsed=10.4min]

Entraînement:  32%|███▏      | 3247/10000 [10:25<26:39,  4.22step/s, loss=0.045268, elapsed=10.4min]

Entraînement:  32%|███▏      | 3247/10000 [10:25<26:39,  4.22step/s, loss=0.041780, elapsed=10.4min]

Entraînement:  32%|███▏      | 3248/10000 [10:26<25:01,  4.50step/s, loss=0.041780, elapsed=10.4min]

Entraînement:  32%|███▏      | 3248/10000 [10:26<25:01,  4.50step/s, loss=0.051954, elapsed=10.4min]

Entraînement:  32%|███▏      | 3249/10000 [10:26<23:56,  4.70step/s, loss=0.051954, elapsed=10.4min]

Entraînement:  32%|███▏      | 3249/10000 [10:26<23:56,  4.70step/s, loss=0.076913, elapsed=10.4min]

Entraînement:  32%|███▎      | 3250/10000 [10:26<23:07,  4.87step/s, loss=0.076913, elapsed=10.4min]

Entraînement:  32%|███▎      | 3250/10000 [10:26<23:07,  4.87step/s, loss=0.028864, elapsed=10.4min]

Entraînement:  33%|███▎      | 3251/10000 [10:26<22:36,  4.98step/s, loss=0.028864, elapsed=10.4min]

Entraînement:  33%|███▎      | 3251/10000 [10:26<22:36,  4.98step/s, loss=0.056028, elapsed=10.4min]

Entraînement:  33%|███▎      | 3252/10000 [10:26<22:11,  5.07step/s, loss=0.056028, elapsed=10.4min]

Entraînement:  33%|███▎      | 3252/10000 [10:26<22:11,  5.07step/s, loss=0.025923, elapsed=10.4min]

Entraînement:  33%|███▎      | 3253/10000 [10:27<21:54,  5.13step/s, loss=0.025923, elapsed=10.4min]

Entraînement:  33%|███▎      | 3253/10000 [10:27<21:54,  5.13step/s, loss=0.031890, elapsed=10.5min]

Entraînement:  33%|███▎      | 3254/10000 [10:27<21:42,  5.18step/s, loss=0.031890, elapsed=10.5min]

Entraînement:  33%|███▎      | 3254/10000 [10:27<21:42,  5.18step/s, loss=0.035588, elapsed=10.5min]

Entraînement:  33%|███▎      | 3255/10000 [10:27<21:31,  5.22step/s, loss=0.035588, elapsed=10.5min]

Entraînement:  33%|███▎      | 3255/10000 [10:27<21:31,  5.22step/s, loss=0.053163, elapsed=10.5min]

Entraînement:  33%|███▎      | 3256/10000 [10:27<21:27,  5.24step/s, loss=0.053163, elapsed=10.5min]

Entraînement:  33%|███▎      | 3256/10000 [10:27<21:27,  5.24step/s, loss=0.068082, elapsed=10.5min]

Entraînement:  33%|███▎      | 3257/10000 [10:27<21:23,  5.25step/s, loss=0.068082, elapsed=10.5min]

Entraînement:  33%|███▎      | 3257/10000 [10:27<21:23,  5.25step/s, loss=0.036848, elapsed=10.5min]

Entraînement:  33%|███▎      | 3258/10000 [10:27<21:18,  5.27step/s, loss=0.036848, elapsed=10.5min]

Entraînement:  33%|███▎      | 3258/10000 [10:27<21:18,  5.27step/s, loss=0.085934, elapsed=10.5min]

Entraînement:  33%|███▎      | 3259/10000 [10:28<21:18,  5.27step/s, loss=0.085934, elapsed=10.5min]

Entraînement:  33%|███▎      | 3259/10000 [10:28<21:18,  5.27step/s, loss=0.048930, elapsed=10.5min]

Entraînement:  33%|███▎      | 3260/10000 [10:28<21:17,  5.28step/s, loss=0.048930, elapsed=10.5min]

Entraînement:  33%|███▎      | 3260/10000 [10:28<21:17,  5.28step/s, loss=0.037050, elapsed=10.5min]

Entraînement:  33%|███▎      | 3261/10000 [10:28<21:16,  5.28step/s, loss=0.037050, elapsed=10.5min]

Entraînement:  33%|███▎      | 3261/10000 [10:28<21:16,  5.28step/s, loss=0.041298, elapsed=10.5min]

Entraînement:  33%|███▎      | 3262/10000 [10:28<21:20,  5.26step/s, loss=0.041298, elapsed=10.5min]

Entraînement:  33%|███▎      | 3262/10000 [10:28<21:20,  5.26step/s, loss=0.099344, elapsed=10.5min]

Entraînement:  33%|███▎      | 3263/10000 [10:28<21:18,  5.27step/s, loss=0.099344, elapsed=10.5min]

Entraînement:  33%|███▎      | 3263/10000 [10:28<21:18,  5.27step/s, loss=0.086510, elapsed=10.5min]

Entraînement:  33%|███▎      | 3264/10000 [10:29<21:21,  5.26step/s, loss=0.086510, elapsed=10.5min]

Entraînement:  33%|███▎      | 3264/10000 [10:29<21:21,  5.26step/s, loss=0.048321, elapsed=10.5min]

Entraînement:  33%|███▎      | 3265/10000 [10:29<21:20,  5.26step/s, loss=0.048321, elapsed=10.5min]

Entraînement:  33%|███▎      | 3265/10000 [10:29<21:20,  5.26step/s, loss=0.050629, elapsed=10.5min]

Entraînement:  33%|███▎      | 3266/10000 [10:29<21:21,  5.26step/s, loss=0.050629, elapsed=10.5min]

Entraînement:  33%|███▎      | 3266/10000 [10:29<21:21,  5.26step/s, loss=0.040089, elapsed=10.5min]

Entraînement:  33%|███▎      | 3267/10000 [10:29<21:20,  5.26step/s, loss=0.040089, elapsed=10.5min]

Entraînement:  33%|███▎      | 3267/10000 [10:29<21:20,  5.26step/s, loss=0.036062, elapsed=10.5min]

Entraînement:  33%|███▎      | 3268/10000 [10:29<21:22,  5.25step/s, loss=0.036062, elapsed=10.5min]

Entraînement:  33%|███▎      | 3268/10000 [10:29<21:22,  5.25step/s, loss=0.046689, elapsed=10.5min]

Entraînement:  33%|███▎      | 3269/10000 [10:30<21:21,  5.25step/s, loss=0.046689, elapsed=10.5min]

Entraînement:  33%|███▎      | 3269/10000 [10:30<21:21,  5.25step/s, loss=0.041755, elapsed=10.5min]

Entraînement:  33%|███▎      | 3270/10000 [10:30<21:23,  5.24step/s, loss=0.041755, elapsed=10.5min]

Entraînement:  33%|███▎      | 3270/10000 [10:30<21:23,  5.24step/s, loss=0.072883, elapsed=10.5min]

Entraînement:  33%|███▎      | 3271/10000 [10:30<21:20,  5.25step/s, loss=0.072883, elapsed=10.5min]

Entraînement:  33%|███▎      | 3271/10000 [10:30<21:20,  5.25step/s, loss=0.041418, elapsed=10.5min]

Entraînement:  33%|███▎      | 3272/10000 [10:30<21:21,  5.25step/s, loss=0.041418, elapsed=10.5min]

Entraînement:  33%|███▎      | 3272/10000 [10:30<21:21,  5.25step/s, loss=0.026064, elapsed=10.5min]

Entraînement:  33%|███▎      | 3273/10000 [10:30<21:21,  5.25step/s, loss=0.026064, elapsed=10.5min]

Entraînement:  33%|███▎      | 3273/10000 [10:30<21:21,  5.25step/s, loss=0.060620, elapsed=10.5min]

Entraînement:  33%|███▎      | 3274/10000 [10:31<21:21,  5.25step/s, loss=0.060620, elapsed=10.5min]

Entraînement:  33%|███▎      | 3274/10000 [10:31<21:21,  5.25step/s, loss=0.072715, elapsed=10.5min]

Entraînement:  33%|███▎      | 3275/10000 [10:31<21:24,  5.24step/s, loss=0.072715, elapsed=10.5min]

Entraînement:  33%|███▎      | 3275/10000 [10:31<21:24,  5.24step/s, loss=0.048330, elapsed=10.5min]

Entraînement:  33%|███▎      | 3276/10000 [10:31<21:23,  5.24step/s, loss=0.048330, elapsed=10.5min]

Entraînement:  33%|███▎      | 3276/10000 [10:31<21:23,  5.24step/s, loss=0.049786, elapsed=10.5min]

Entraînement:  33%|███▎      | 3277/10000 [10:31<21:23,  5.24step/s, loss=0.049786, elapsed=10.5min]

Entraînement:  33%|███▎      | 3277/10000 [10:31<21:23,  5.24step/s, loss=0.100272, elapsed=10.5min]

Entraînement:  33%|███▎      | 3278/10000 [10:31<21:31,  5.20step/s, loss=0.100272, elapsed=10.5min]

Entraînement:  33%|███▎      | 3278/10000 [10:31<21:31,  5.20step/s, loss=0.045900, elapsed=10.5min]

Entraînement:  33%|███▎      | 3279/10000 [10:31<21:35,  5.19step/s, loss=0.045900, elapsed=10.5min]

Entraînement:  33%|███▎      | 3279/10000 [10:31<21:35,  5.19step/s, loss=0.033993, elapsed=10.5min]

Entraînement:  33%|███▎      | 3280/10000 [10:32<21:30,  5.21step/s, loss=0.033993, elapsed=10.5min]

Entraînement:  33%|███▎      | 3280/10000 [10:32<21:30,  5.21step/s, loss=0.067978, elapsed=10.5min]

Entraînement:  33%|███▎      | 3281/10000 [10:32<21:23,  5.23step/s, loss=0.067978, elapsed=10.5min]

Entraînement:  33%|███▎      | 3281/10000 [10:32<21:23,  5.23step/s, loss=0.098594, elapsed=10.5min]

Entraînement:  33%|███▎      | 3282/10000 [10:32<21:22,  5.24step/s, loss=0.098594, elapsed=10.5min]

Entraînement:  33%|███▎      | 3282/10000 [10:32<21:22,  5.24step/s, loss=0.061446, elapsed=10.5min]

Entraînement:  33%|███▎      | 3283/10000 [10:32<21:20,  5.24step/s, loss=0.061446, elapsed=10.5min]

Entraînement:  33%|███▎      | 3283/10000 [10:32<21:20,  5.24step/s, loss=0.039829, elapsed=10.5min]

Entraînement:  33%|███▎      | 3284/10000 [10:32<21:20,  5.24step/s, loss=0.039829, elapsed=10.5min]

Entraînement:  33%|███▎      | 3284/10000 [10:32<21:20,  5.24step/s, loss=0.152410, elapsed=10.5min]

Entraînement:  33%|███▎      | 3285/10000 [10:33<21:19,  5.25step/s, loss=0.152410, elapsed=10.5min]

Entraînement:  33%|███▎      | 3285/10000 [10:33<21:19,  5.25step/s, loss=0.048913, elapsed=10.6min]

Entraînement:  33%|███▎      | 3286/10000 [10:33<21:15,  5.26step/s, loss=0.048913, elapsed=10.6min]

Entraînement:  33%|███▎      | 3286/10000 [10:33<21:15,  5.26step/s, loss=0.124610, elapsed=10.6min]

Entraînement:  33%|███▎      | 3287/10000 [10:33<21:18,  5.25step/s, loss=0.124610, elapsed=10.6min]

Entraînement:  33%|███▎      | 3287/10000 [10:33<21:18,  5.25step/s, loss=0.067649, elapsed=10.6min]

Entraînement:  33%|███▎      | 3288/10000 [10:33<21:16,  5.26step/s, loss=0.067649, elapsed=10.6min]

Entraînement:  33%|███▎      | 3288/10000 [10:33<21:16,  5.26step/s, loss=0.111517, elapsed=10.6min]

Entraînement:  33%|███▎      | 3289/10000 [10:33<21:15,  5.26step/s, loss=0.111517, elapsed=10.6min]

Entraînement:  33%|███▎      | 3289/10000 [10:33<21:15,  5.26step/s, loss=0.059152, elapsed=10.6min]

Entraînement:  33%|███▎      | 3290/10000 [10:34<21:14,  5.26step/s, loss=0.059152, elapsed=10.6min]

Entraînement:  33%|███▎      | 3290/10000 [10:34<21:14,  5.26step/s, loss=0.030736, elapsed=10.6min]

Entraînement:  33%|███▎      | 3291/10000 [10:34<21:14,  5.26step/s, loss=0.030736, elapsed=10.6min]

Entraînement:  33%|███▎      | 3291/10000 [10:34<21:14,  5.26step/s, loss=0.061622, elapsed=10.6min]

Entraînement:  33%|███▎      | 3292/10000 [10:34<21:16,  5.25step/s, loss=0.061622, elapsed=10.6min]

Entraînement:  33%|███▎      | 3292/10000 [10:34<21:16,  5.25step/s, loss=0.041015, elapsed=10.6min]

Entraînement:  33%|███▎      | 3293/10000 [10:34<21:18,  5.24step/s, loss=0.041015, elapsed=10.6min]

Entraînement:  33%|███▎      | 3293/10000 [10:34<21:18,  5.24step/s, loss=0.046822, elapsed=10.6min]

Entraînement:  33%|███▎      | 3294/10000 [10:34<21:19,  5.24step/s, loss=0.046822, elapsed=10.6min]

Entraînement:  33%|███▎      | 3294/10000 [10:34<21:19,  5.24step/s, loss=0.042098, elapsed=10.6min]

Entraînement:  33%|███▎      | 3295/10000 [10:35<21:19,  5.24step/s, loss=0.042098, elapsed=10.6min]

Entraînement:  33%|███▎      | 3295/10000 [10:35<21:19,  5.24step/s, loss=0.035314, elapsed=10.6min]

Entraînement:  33%|███▎      | 3296/10000 [10:35<21:18,  5.24step/s, loss=0.035314, elapsed=10.6min]

Entraînement:  33%|███▎      | 3296/10000 [10:35<21:18,  5.24step/s, loss=0.037128, elapsed=10.6min]

Entraînement:  33%|███▎      | 3297/10000 [10:35<21:18,  5.24step/s, loss=0.037128, elapsed=10.6min]

Entraînement:  33%|███▎      | 3297/10000 [10:35<21:18,  5.24step/s, loss=0.076676, elapsed=10.6min]

Entraînement:  33%|███▎      | 3298/10000 [10:35<21:18,  5.24step/s, loss=0.076676, elapsed=10.6min]

Entraînement:  33%|███▎      | 3298/10000 [10:35<21:18,  5.24step/s, loss=0.042619, elapsed=10.6min]

Entraînement:  33%|███▎      | 3299/10000 [10:35<21:18,  5.24step/s, loss=0.042619, elapsed=10.6min]

Entraînement:  33%|███▎      | 3299/10000 [10:35<21:18,  5.24step/s, loss=0.029217, elapsed=10.6min]

Entraînement:  33%|███▎      | 3300/10000 [10:35<21:19,  5.24step/s, loss=0.029217, elapsed=10.6min]

Entraînement:  33%|███▎      | 3300/10000 [10:35<21:19,  5.24step/s, loss=0.035663, elapsed=10.6min]

Entraînement:  33%|███▎      | 3300/10000 [10:35<21:19,  5.24step/s, loss=0.035663, elapsed=10.6min]

Entraînement:  33%|███▎      | 3301/10000 [10:36<21:35,  5.17step/s, loss=0.035663, elapsed=10.6min]

Entraînement:  33%|███▎      | 3301/10000 [10:36<21:35,  5.17step/s, loss=0.055244, elapsed=10.6min]

Step 3300/10000 | Train loss: 0.035663 | Elapsed: 10.6min | ETA: 21.5min

Entraînement:  33%|███▎      | 3302/10000 [10:36<21:29,  5.20step/s, loss=0.055244, elapsed=10.6min]

Entraînement:  33%|███▎      | 3302/10000 [10:36<21:29,  5.20step/s, loss=0.098514, elapsed=10.6min]

Entraînement:  33%|███▎      | 3303/10000 [10:36<21:24,  5.21step/s, loss=0.098514, elapsed=10.6min]

Entraînement:  33%|███▎      | 3303/10000 [10:36<21:24,  5.21step/s, loss=0.067422, elapsed=10.6min]

Entraînement:  33%|███▎      | 3304/10000 [10:36<21:22,  5.22step/s, loss=0.067422, elapsed=10.6min]

Entraînement:  33%|███▎      | 3304/10000 [10:36<21:22,  5.22step/s, loss=0.045628, elapsed=10.6min]

Entraînement:  33%|███▎      | 3305/10000 [10:36<21:19,  5.23step/s, loss=0.045628, elapsed=10.6min]

Entraînement:  33%|███▎      | 3305/10000 [10:36<21:19,  5.23step/s, loss=0.034786, elapsed=10.6min]

Entraînement:  33%|███▎      | 3306/10000 [10:37<21:19,  5.23step/s, loss=0.034786, elapsed=10.6min]

Entraînement:  33%|███▎      | 3306/10000 [10:37<21:19,  5.23step/s, loss=0.034309, elapsed=10.6min]

Entraînement:  33%|███▎      | 3307/10000 [10:37<21:24,  5.21step/s, loss=0.034309, elapsed=10.6min]

Entraînement:  33%|███▎      | 3307/10000 [10:37<21:24,  5.21step/s, loss=0.044210, elapsed=10.6min]

Entraînement:  33%|███▎      | 3308/10000 [10:37<21:21,  5.22step/s, loss=0.044210, elapsed=10.6min]

Entraînement:  33%|███▎      | 3308/10000 [10:37<21:21,  5.22step/s, loss=0.058994, elapsed=10.6min]

Entraînement:  33%|███▎      | 3309/10000 [10:37<21:18,  5.24step/s, loss=0.058994, elapsed=10.6min]

Entraînement:  33%|███▎      | 3309/10000 [10:37<21:18,  5.24step/s, loss=0.040354, elapsed=10.6min]

Entraînement:  33%|███▎      | 3310/10000 [10:37<21:14,  5.25step/s, loss=0.040354, elapsed=10.6min]

Entraînement:  33%|███▎      | 3310/10000 [10:37<21:14,  5.25step/s, loss=0.022693, elapsed=10.6min]

Entraînement:  33%|███▎      | 3311/10000 [10:38<21:13,  5.25step/s, loss=0.022693, elapsed=10.6min]

Entraînement:  33%|███▎      | 3311/10000 [10:38<21:13,  5.25step/s, loss=0.047657, elapsed=10.6min]

Entraînement:  33%|███▎      | 3312/10000 [10:38<21:12,  5.26step/s, loss=0.047657, elapsed=10.6min]

Entraînement:  33%|███▎      | 3312/10000 [10:38<21:12,  5.26step/s, loss=0.106101, elapsed=10.6min]

Entraînement:  33%|███▎      | 3313/10000 [10:38<21:14,  5.25step/s, loss=0.106101, elapsed=10.6min]

Entraînement:  33%|███▎      | 3313/10000 [10:38<21:14,  5.25step/s, loss=0.053578, elapsed=10.6min]

Entraînement:  33%|███▎      | 3314/10000 [10:38<21:13,  5.25step/s, loss=0.053578, elapsed=10.6min]

Entraînement:  33%|███▎      | 3314/10000 [10:38<21:13,  5.25step/s, loss=0.039600, elapsed=10.6min]

Entraînement:  33%|███▎      | 3315/10000 [10:38<21:13,  5.25step/s, loss=0.039600, elapsed=10.6min]

Entraînement:  33%|███▎      | 3315/10000 [10:38<21:13,  5.25step/s, loss=0.038183, elapsed=10.6min]

Entraînement:  33%|███▎      | 3316/10000 [10:39<21:11,  5.26step/s, loss=0.038183, elapsed=10.6min]

Entraînement:  33%|███▎      | 3316/10000 [10:39<21:11,  5.26step/s, loss=0.053300, elapsed=10.7min]

Entraînement:  33%|███▎      | 3317/10000 [10:39<21:12,  5.25step/s, loss=0.053300, elapsed=10.7min]

Entraînement:  33%|███▎      | 3317/10000 [10:39<21:12,  5.25step/s, loss=0.031396, elapsed=10.7min]

Entraînement:  33%|███▎      | 3318/10000 [10:39<21:12,  5.25step/s, loss=0.031396, elapsed=10.7min]

Entraînement:  33%|███▎      | 3318/10000 [10:39<21:12,  5.25step/s, loss=0.071934, elapsed=10.7min]

Entraînement:  33%|███▎      | 3319/10000 [10:39<21:10,  5.26step/s, loss=0.071934, elapsed=10.7min]

Entraînement:  33%|███▎      | 3319/10000 [10:39<21:10,  5.26step/s, loss=0.046916, elapsed=10.7min]

Entraînement:  33%|███▎      | 3320/10000 [10:39<21:09,  5.26step/s, loss=0.046916, elapsed=10.7min]

Entraînement:  33%|███▎      | 3320/10000 [10:39<21:09,  5.26step/s, loss=0.046517, elapsed=10.7min]

Entraînement:  33%|███▎      | 3321/10000 [10:39<21:09,  5.26step/s, loss=0.046517, elapsed=10.7min]

Entraînement:  33%|███▎      | 3321/10000 [10:39<21:09,  5.26step/s, loss=0.030838, elapsed=10.7min]

Entraînement:  33%|███▎      | 3322/10000 [10:40<21:09,  5.26step/s, loss=0.030838, elapsed=10.7min]

Entraînement:  33%|███▎      | 3322/10000 [10:40<21:09,  5.26step/s, loss=0.060261, elapsed=10.7min]

Entraînement:  33%|███▎      | 3323/10000 [10:40<21:10,  5.25step/s, loss=0.060261, elapsed=10.7min]

Entraînement:  33%|███▎      | 3323/10000 [10:40<21:10,  5.25step/s, loss=0.052919, elapsed=10.7min]

Entraînement:  33%|███▎      | 3324/10000 [10:40<21:12,  5.25step/s, loss=0.052919, elapsed=10.7min]

Entraînement:  33%|███▎      | 3324/10000 [10:40<21:12,  5.25step/s, loss=0.035190, elapsed=10.7min]

Entraînement:  33%|███▎      | 3325/10000 [10:40<21:12,  5.25step/s, loss=0.035190, elapsed=10.7min]

Entraînement:  33%|███▎      | 3325/10000 [10:40<21:12,  5.25step/s, loss=0.050299, elapsed=10.7min]

Entraînement:  33%|███▎      | 3326/10000 [10:40<21:11,  5.25step/s, loss=0.050299, elapsed=10.7min]

Entraînement:  33%|███▎      | 3326/10000 [10:40<21:11,  5.25step/s, loss=0.089623, elapsed=10.7min]

Entraînement:  33%|███▎      | 3327/10000 [10:41<21:09,  5.26step/s, loss=0.089623, elapsed=10.7min]

Entraînement:  33%|███▎      | 3327/10000 [10:41<21:09,  5.26step/s, loss=0.022700, elapsed=10.7min]

Entraînement:  33%|███▎      | 3328/10000 [10:41<21:05,  5.27step/s, loss=0.022700, elapsed=10.7min]

Entraînement:  33%|███▎      | 3328/10000 [10:41<21:05,  5.27step/s, loss=0.060723, elapsed=10.7min]

Entraînement:  33%|███▎      | 3329/10000 [10:41<21:04,  5.27step/s, loss=0.060723, elapsed=10.7min]

Entraînement:  33%|███▎      | 3329/10000 [10:41<21:04,  5.27step/s, loss=0.142848, elapsed=10.7min]

Entraînement:  33%|███▎      | 3330/10000 [10:41<21:04,  5.27step/s, loss=0.142848, elapsed=10.7min]

Entraînement:  33%|███▎      | 3330/10000 [10:41<21:04,  5.27step/s, loss=0.054895, elapsed=10.7min]

Entraînement:  33%|███▎      | 3331/10000 [10:41<21:03,  5.28step/s, loss=0.054895, elapsed=10.7min]

Entraînement:  33%|███▎      | 3331/10000 [10:41<21:03,  5.28step/s, loss=0.035254, elapsed=10.7min]

Entraînement:  33%|███▎      | 3332/10000 [10:42<20:54,  5.31step/s, loss=0.035254, elapsed=10.7min]

Entraînement:  33%|███▎      | 3332/10000 [10:42<20:54,  5.31step/s, loss=0.042116, elapsed=10.7min]

Entraînement:  33%|███▎      | 3333/10000 [10:42<20:48,  5.34step/s, loss=0.042116, elapsed=10.7min]

Entraînement:  33%|███▎      | 3333/10000 [10:42<20:48,  5.34step/s, loss=0.051780, elapsed=10.7min]

Entraînement:  33%|███▎      | 3334/10000 [10:42<20:43,  5.36step/s, loss=0.051780, elapsed=10.7min]

Entraînement:  33%|███▎      | 3334/10000 [10:42<20:43,  5.36step/s, loss=0.067333, elapsed=10.7min]

Entraînement:  33%|███▎      | 3335/10000 [10:42<27:13,  4.08step/s, loss=0.067333, elapsed=10.7min]

Entraînement:  33%|███▎      | 3335/10000 [10:42<27:13,  4.08step/s, loss=0.038611, elapsed=10.7min]

Entraînement:  33%|███▎      | 3336/10000 [10:42<25:13,  4.40step/s, loss=0.038611, elapsed=10.7min]

Entraînement:  33%|███▎      | 3336/10000 [10:42<25:13,  4.40step/s, loss=0.072266, elapsed=10.7min]

Entraînement:  33%|███▎      | 3337/10000 [10:43<23:49,  4.66step/s, loss=0.072266, elapsed=10.7min]

Entraînement:  33%|███▎      | 3337/10000 [10:43<23:49,  4.66step/s, loss=0.040927, elapsed=10.7min]

Entraînement:  33%|███▎      | 3338/10000 [10:43<22:50,  4.86step/s, loss=0.040927, elapsed=10.7min]

Entraînement:  33%|███▎      | 3338/10000 [10:43<22:50,  4.86step/s, loss=0.040555, elapsed=10.7min]

Entraînement:  33%|███▎      | 3339/10000 [10:43<22:07,  5.02step/s, loss=0.040555, elapsed=10.7min]

Entraînement:  33%|███▎      | 3339/10000 [10:43<22:07,  5.02step/s, loss=0.101452, elapsed=10.7min]

Entraînement:  33%|███▎      | 3340/10000 [10:43<21:39,  5.13step/s, loss=0.101452, elapsed=10.7min]

Entraînement:  33%|███▎      | 3340/10000 [10:43<21:39,  5.13step/s, loss=0.044160, elapsed=10.7min]

Entraînement:  33%|███▎      | 3341/10000 [10:43<21:23,  5.19step/s, loss=0.044160, elapsed=10.7min]

Entraînement:  33%|███▎      | 3341/10000 [10:43<21:23,  5.19step/s, loss=0.039794, elapsed=10.7min]

Entraînement:  33%|███▎      | 3342/10000 [10:44<21:12,  5.23step/s, loss=0.039794, elapsed=10.7min]

Entraînement:  33%|███▎      | 3342/10000 [10:44<21:12,  5.23step/s, loss=0.038881, elapsed=10.7min]

Entraînement:  33%|███▎      | 3343/10000 [10:44<21:00,  5.28step/s, loss=0.038881, elapsed=10.7min]

Entraînement:  33%|███▎      | 3343/10000 [10:44<21:00,  5.28step/s, loss=0.060445, elapsed=10.7min]

Entraînement:  33%|███▎      | 3344/10000 [10:44<20:52,  5.31step/s, loss=0.060445, elapsed=10.7min]

Entraînement:  33%|███▎      | 3344/10000 [10:44<20:52,  5.31step/s, loss=0.045767, elapsed=10.7min]

Entraînement:  33%|███▎      | 3345/10000 [10:44<20:46,  5.34step/s, loss=0.045767, elapsed=10.7min]

Entraînement:  33%|███▎      | 3345/10000 [10:44<20:46,  5.34step/s, loss=0.057154, elapsed=10.7min]

Entraînement:  33%|███▎      | 3346/10000 [10:44<20:42,  5.36step/s, loss=0.057154, elapsed=10.7min]

Entraînement:  33%|███▎      | 3346/10000 [10:44<20:42,  5.36step/s, loss=0.082786, elapsed=10.7min]

Entraînement:  33%|███▎      | 3347/10000 [10:45<20:38,  5.37step/s, loss=0.082786, elapsed=10.7min]

Entraînement:  33%|███▎      | 3347/10000 [10:45<20:38,  5.37step/s, loss=0.061966, elapsed=10.8min]

Entraînement:  33%|███▎      | 3348/10000 [10:45<20:35,  5.39step/s, loss=0.061966, elapsed=10.8min]

Entraînement:  33%|███▎      | 3348/10000 [10:45<20:35,  5.39step/s, loss=0.041228, elapsed=10.8min]

Entraînement:  33%|███▎      | 3349/10000 [10:45<20:34,  5.39step/s, loss=0.041228, elapsed=10.8min]

Entraînement:  33%|███▎      | 3349/10000 [10:45<20:34,  5.39step/s, loss=0.081609, elapsed=10.8min]

Entraînement:  34%|███▎      | 3350/10000 [10:45<20:33,  5.39step/s, loss=0.081609, elapsed=10.8min]

Entraînement:  34%|███▎      | 3350/10000 [10:45<20:33,  5.39step/s, loss=0.047691, elapsed=10.8min]

Entraînement:  34%|███▎      | 3351/10000 [10:45<20:31,  5.40step/s, loss=0.047691, elapsed=10.8min]

Entraînement:  34%|███▎      | 3351/10000 [10:45<20:31,  5.40step/s, loss=0.058887, elapsed=10.8min]

Entraînement:  34%|███▎      | 3352/10000 [10:45<20:36,  5.38step/s, loss=0.058887, elapsed=10.8min]

Entraînement:  34%|███▎      | 3352/10000 [10:45<20:36,  5.38step/s, loss=0.027685, elapsed=10.8min]

Entraînement:  34%|███▎      | 3353/10000 [10:46<20:46,  5.33step/s, loss=0.027685, elapsed=10.8min]

Entraînement:  34%|███▎      | 3353/10000 [10:46<20:46,  5.33step/s, loss=0.048037, elapsed=10.8min]

Entraînement:  34%|███▎      | 3354/10000 [10:46<20:51,  5.31step/s, loss=0.048037, elapsed=10.8min]

Entraînement:  34%|███▎      | 3354/10000 [10:46<20:51,  5.31step/s, loss=0.032299, elapsed=10.8min]

Entraînement:  34%|███▎      | 3355/10000 [10:46<20:51,  5.31step/s, loss=0.032299, elapsed=10.8min]

Entraînement:  34%|███▎      | 3355/10000 [10:46<20:51,  5.31step/s, loss=0.030305, elapsed=10.8min]

Entraînement:  34%|███▎      | 3356/10000 [10:46<20:47,  5.33step/s, loss=0.030305, elapsed=10.8min]

Entraînement:  34%|███▎      | 3356/10000 [10:46<20:47,  5.33step/s, loss=0.029352, elapsed=10.8min]

Entraînement:  34%|███▎      | 3357/10000 [10:46<20:47,  5.33step/s, loss=0.029352, elapsed=10.8min]

Entraînement:  34%|███▎      | 3357/10000 [10:46<20:47,  5.33step/s, loss=0.032375, elapsed=10.8min]

Entraînement:  34%|███▎      | 3358/10000 [10:47<20:45,  5.33step/s, loss=0.032375, elapsed=10.8min]

Entraînement:  34%|███▎      | 3358/10000 [10:47<20:45,  5.33step/s, loss=0.028994, elapsed=10.8min]

Entraînement:  34%|███▎      | 3359/10000 [10:47<20:42,  5.34step/s, loss=0.028994, elapsed=10.8min]

Entraînement:  34%|███▎      | 3359/10000 [10:47<20:42,  5.34step/s, loss=0.077589, elapsed=10.8min]

Entraînement:  34%|███▎      | 3360/10000 [10:47<20:43,  5.34step/s, loss=0.077589, elapsed=10.8min]

Entraînement:  34%|███▎      | 3360/10000 [10:47<20:43,  5.34step/s, loss=0.142829, elapsed=10.8min]

Entraînement:  34%|███▎      | 3361/10000 [10:47<20:46,  5.33step/s, loss=0.142829, elapsed=10.8min]

Entraînement:  34%|███▎      | 3361/10000 [10:47<20:46,  5.33step/s, loss=0.031124, elapsed=10.8min]

Entraînement:  34%|███▎      | 3362/10000 [10:47<20:49,  5.31step/s, loss=0.031124, elapsed=10.8min]

Entraînement:  34%|███▎      | 3362/10000 [10:47<20:49,  5.31step/s, loss=0.040991, elapsed=10.8min]

Entraînement:  34%|███▎      | 3363/10000 [10:48<20:47,  5.32step/s, loss=0.040991, elapsed=10.8min]

Entraînement:  34%|███▎      | 3363/10000 [10:48<20:47,  5.32step/s, loss=0.057545, elapsed=10.8min]

Entraînement:  34%|███▎      | 3364/10000 [10:48<20:48,  5.31step/s, loss=0.057545, elapsed=10.8min]

Entraînement:  34%|███▎      | 3364/10000 [10:48<20:48,  5.31step/s, loss=0.044805, elapsed=10.8min]

Entraînement:  34%|███▎      | 3365/10000 [10:48<20:46,  5.32step/s, loss=0.044805, elapsed=10.8min]

Entraînement:  34%|███▎      | 3365/10000 [10:48<20:46,  5.32step/s, loss=0.063275, elapsed=10.8min]

Entraînement:  34%|███▎      | 3366/10000 [10:48<20:46,  5.32step/s, loss=0.063275, elapsed=10.8min]

Entraînement:  34%|███▎      | 3366/10000 [10:48<20:46,  5.32step/s, loss=0.056777, elapsed=10.8min]

Entraînement:  34%|███▎      | 3367/10000 [10:48<20:47,  5.32step/s, loss=0.056777, elapsed=10.8min]

Entraînement:  34%|███▎      | 3367/10000 [10:48<20:47,  5.32step/s, loss=0.046538, elapsed=10.8min]

Entraînement:  34%|███▎      | 3368/10000 [10:48<20:49,  5.31step/s, loss=0.046538, elapsed=10.8min]

Entraînement:  34%|███▎      | 3368/10000 [10:48<20:49,  5.31step/s, loss=0.043748, elapsed=10.8min]

Entraînement:  34%|███▎      | 3369/10000 [10:49<20:50,  5.30step/s, loss=0.043748, elapsed=10.8min]

Entraînement:  34%|███▎      | 3369/10000 [10:49<20:50,  5.30step/s, loss=0.091676, elapsed=10.8min]

Entraînement:  34%|███▎      | 3370/10000 [10:49<20:50,  5.30step/s, loss=0.091676, elapsed=10.8min]

Entraînement:  34%|███▎      | 3370/10000 [10:49<20:50,  5.30step/s, loss=0.049032, elapsed=10.8min]

Entraînement:  34%|███▎      | 3371/10000 [10:49<20:53,  5.29step/s, loss=0.049032, elapsed=10.8min]

Entraînement:  34%|███▎      | 3371/10000 [10:49<20:53,  5.29step/s, loss=0.060615, elapsed=10.8min]

Entraînement:  34%|███▎      | 3372/10000 [10:49<20:55,  5.28step/s, loss=0.060615, elapsed=10.8min]

Entraînement:  34%|███▎      | 3372/10000 [10:49<20:55,  5.28step/s, loss=0.098840, elapsed=10.8min]

Entraînement:  34%|███▎      | 3373/10000 [10:49<20:56,  5.27step/s, loss=0.098840, elapsed=10.8min]

Entraînement:  34%|███▎      | 3373/10000 [10:49<20:56,  5.27step/s, loss=0.080344, elapsed=10.8min]

Entraînement:  34%|███▎      | 3374/10000 [10:50<20:59,  5.26step/s, loss=0.080344, elapsed=10.8min]

Entraînement:  34%|███▎      | 3374/10000 [10:50<20:59,  5.26step/s, loss=0.061577, elapsed=10.8min]

Entraînement:  34%|███▍      | 3375/10000 [10:50<20:56,  5.27step/s, loss=0.061577, elapsed=10.8min]

Entraînement:  34%|███▍      | 3375/10000 [10:50<20:56,  5.27step/s, loss=0.043904, elapsed=10.8min]

Entraînement:  34%|███▍      | 3376/10000 [10:50<20:56,  5.27step/s, loss=0.043904, elapsed=10.8min]

Entraînement:  34%|███▍      | 3376/10000 [10:50<20:56,  5.27step/s, loss=0.042325, elapsed=10.8min]

Entraînement:  34%|███▍      | 3377/10000 [10:50<20:56,  5.27step/s, loss=0.042325, elapsed=10.8min]

Entraînement:  34%|███▍      | 3377/10000 [10:50<20:56,  5.27step/s, loss=0.065586, elapsed=10.8min]

Entraînement:  34%|███▍      | 3378/10000 [10:50<20:58,  5.26step/s, loss=0.065586, elapsed=10.8min]

Entraînement:  34%|███▍      | 3378/10000 [10:50<20:58,  5.26step/s, loss=0.076996, elapsed=10.8min]

Entraînement:  34%|███▍      | 3379/10000 [10:51<20:56,  5.27step/s, loss=0.076996, elapsed=10.8min]

Entraînement:  34%|███▍      | 3379/10000 [10:51<20:56,  5.27step/s, loss=0.036520, elapsed=10.9min]

Entraînement:  34%|███▍      | 3380/10000 [10:51<20:53,  5.28step/s, loss=0.036520, elapsed=10.9min]

Entraînement:  34%|███▍      | 3380/10000 [10:51<20:53,  5.28step/s, loss=0.105465, elapsed=10.9min]

Entraînement:  34%|███▍      | 3381/10000 [10:51<20:56,  5.27step/s, loss=0.105465, elapsed=10.9min]

Entraînement:  34%|███▍      | 3381/10000 [10:51<20:56,  5.27step/s, loss=0.059367, elapsed=10.9min]

Entraînement:  34%|███▍      | 3382/10000 [10:51<20:53,  5.28step/s, loss=0.059367, elapsed=10.9min]

Entraînement:  34%|███▍      | 3382/10000 [10:51<20:53,  5.28step/s, loss=0.055867, elapsed=10.9min]

Entraînement:  34%|███▍      | 3383/10000 [10:51<20:52,  5.28step/s, loss=0.055867, elapsed=10.9min]

Entraînement:  34%|███▍      | 3383/10000 [10:51<20:52,  5.28step/s, loss=0.107336, elapsed=10.9min]

Entraînement:  34%|███▍      | 3384/10000 [10:52<20:51,  5.29step/s, loss=0.107336, elapsed=10.9min]

Entraînement:  34%|███▍      | 3384/10000 [10:52<20:51,  5.29step/s, loss=0.065607, elapsed=10.9min]

Entraînement:  34%|███▍      | 3385/10000 [10:52<20:53,  5.28step/s, loss=0.065607, elapsed=10.9min]

Entraînement:  34%|███▍      | 3385/10000 [10:52<20:53,  5.28step/s, loss=0.070159, elapsed=10.9min]

Entraînement:  34%|███▍      | 3386/10000 [10:52<20:54,  5.27step/s, loss=0.070159, elapsed=10.9min]

Entraînement:  34%|███▍      | 3386/10000 [10:52<20:54,  5.27step/s, loss=0.098732, elapsed=10.9min]

Entraînement:  34%|███▍      | 3387/10000 [10:52<26:46,  4.12step/s, loss=0.098732, elapsed=10.9min]

Entraînement:  34%|███▍      | 3387/10000 [10:52<26:46,  4.12step/s, loss=0.079363, elapsed=10.9min]

Entraînement:  34%|███▍      | 3388/10000 [10:52<25:03,  4.40step/s, loss=0.079363, elapsed=10.9min]

Entraînement:  34%|███▍      | 3388/10000 [10:52<25:03,  4.40step/s, loss=0.066634, elapsed=10.9min]

Entraînement:  34%|███▍      | 3389/10000 [10:53<23:48,  4.63step/s, loss=0.066634, elapsed=10.9min]

Entraînement:  34%|███▍      | 3389/10000 [10:53<23:48,  4.63step/s, loss=0.060625, elapsed=10.9min]

Entraînement:  34%|███▍      | 3390/10000 [10:53<22:55,  4.80step/s, loss=0.060625, elapsed=10.9min]

Entraînement:  34%|███▍      | 3390/10000 [10:53<22:55,  4.80step/s, loss=0.069128, elapsed=10.9min]

Entraînement:  34%|███▍      | 3391/10000 [10:53<22:18,  4.94step/s, loss=0.069128, elapsed=10.9min]

Entraînement:  34%|███▍      | 3391/10000 [10:53<22:18,  4.94step/s, loss=0.078431, elapsed=10.9min]

Entraînement:  34%|███▍      | 3392/10000 [10:53<21:52,  5.04step/s, loss=0.078431, elapsed=10.9min]

Entraînement:  34%|███▍      | 3392/10000 [10:53<21:52,  5.04step/s, loss=0.072301, elapsed=10.9min]

Entraînement:  34%|███▍      | 3393/10000 [10:53<21:48,  5.05step/s, loss=0.072301, elapsed=10.9min]

Entraînement:  34%|███▍      | 3393/10000 [10:53<21:48,  5.05step/s, loss=0.049972, elapsed=10.9min]

Entraînement:  34%|███▍      | 3394/10000 [10:54<21:30,  5.12step/s, loss=0.049972, elapsed=10.9min]

Entraînement:  34%|███▍      | 3394/10000 [10:54<21:30,  5.12step/s, loss=0.034698, elapsed=10.9min]

Entraînement:  34%|███▍      | 3395/10000 [10:54<21:21,  5.15step/s, loss=0.034698, elapsed=10.9min]

Entraînement:  34%|███▍      | 3395/10000 [10:54<21:21,  5.15step/s, loss=0.102270, elapsed=10.9min]

Entraînement:  34%|███▍      | 3396/10000 [10:54<21:14,  5.18step/s, loss=0.102270, elapsed=10.9min]

Entraînement:  34%|███▍      | 3396/10000 [10:54<21:14,  5.18step/s, loss=0.114001, elapsed=10.9min]

Entraînement:  34%|███▍      | 3397/10000 [10:54<21:09,  5.20step/s, loss=0.114001, elapsed=10.9min]

Entraînement:  34%|███▍      | 3397/10000 [10:54<21:09,  5.20step/s, loss=0.042909, elapsed=10.9min]

Entraînement:  34%|███▍      | 3398/10000 [10:54<21:04,  5.22step/s, loss=0.042909, elapsed=10.9min]

Entraînement:  34%|███▍      | 3398/10000 [10:54<21:04,  5.22step/s, loss=0.040989, elapsed=10.9min]

Entraînement:  34%|███▍      | 3399/10000 [10:55<21:01,  5.23step/s, loss=0.040989, elapsed=10.9min]

Entraînement:  34%|███▍      | 3399/10000 [10:55<21:01,  5.23step/s, loss=0.029218, elapsed=10.9min]

Entraînement:  34%|███▍      | 3400/10000 [10:55<20:57,  5.25step/s, loss=0.029218, elapsed=10.9min]

Entraînement:  34%|███▍      | 3400/10000 [10:55<20:57,  5.25step/s, loss=0.026429, elapsed=10.9min]

Entraînement:  34%|███▍      | 3400/10000 [10:55<20:57,  5.25step/s, loss=0.026429, elapsed=10.9min]

Entraînement:  34%|███▍      | 3401/10000 [10:55<21:09,  5.20step/s, loss=0.026429, elapsed=10.9min]

Entraînement:  34%|███▍      | 3401/10000 [10:55<21:09,  5.20step/s, loss=0.104128, elapsed=10.9min]

Step 3400/10000 | Train loss: 0.026429 | Elapsed: 10.9min | ETA: 21.2min

Entraînement:  34%|███▍      | 3402/10000 [10:55<21:04,  5.22step/s, loss=0.104128, elapsed=10.9min]

Entraînement:  34%|███▍      | 3402/10000 [10:55<21:04,  5.22step/s, loss=0.045661, elapsed=10.9min]

Entraînement:  34%|███▍      | 3403/10000 [10:55<21:03,  5.22step/s, loss=0.045661, elapsed=10.9min]

Entraînement:  34%|███▍      | 3403/10000 [10:55<21:03,  5.22step/s, loss=0.028201, elapsed=10.9min]

Entraînement:  34%|███▍      | 3404/10000 [10:55<20:59,  5.24step/s, loss=0.028201, elapsed=10.9min]

Entraînement:  34%|███▍      | 3404/10000 [10:56<20:59,  5.24step/s, loss=0.055153, elapsed=10.9min]

Entraînement:  34%|███▍      | 3405/10000 [10:56<20:56,  5.25step/s, loss=0.055153, elapsed=10.9min]

Entraînement:  34%|███▍      | 3405/10000 [10:56<20:56,  5.25step/s, loss=0.048586, elapsed=10.9min]

Entraînement:  34%|███▍      | 3406/10000 [10:56<20:55,  5.25step/s, loss=0.048586, elapsed=10.9min]

Entraînement:  34%|███▍      | 3406/10000 [10:56<20:55,  5.25step/s, loss=0.119214, elapsed=10.9min]

Entraînement:  34%|███▍      | 3407/10000 [10:56<20:52,  5.26step/s, loss=0.119214, elapsed=10.9min]

Entraînement:  34%|███▍      | 3407/10000 [10:56<20:52,  5.26step/s, loss=0.059824, elapsed=10.9min]

Entraînement:  34%|███▍      | 3408/10000 [10:56<20:54,  5.26step/s, loss=0.059824, elapsed=10.9min]

Entraînement:  34%|███▍      | 3408/10000 [10:56<20:54,  5.26step/s, loss=0.044631, elapsed=10.9min]

Entraînement:  34%|███▍      | 3409/10000 [10:56<20:52,  5.26step/s, loss=0.044631, elapsed=10.9min]

Entraînement:  34%|███▍      | 3409/10000 [10:56<20:52,  5.26step/s, loss=0.033240, elapsed=10.9min]

Entraînement:  34%|███▍      | 3410/10000 [10:57<20:53,  5.26step/s, loss=0.033240, elapsed=10.9min]

Entraînement:  34%|███▍      | 3410/10000 [10:57<20:53,  5.26step/s, loss=0.060305, elapsed=11.0min]

Entraînement:  34%|███▍      | 3411/10000 [10:57<20:50,  5.27step/s, loss=0.060305, elapsed=11.0min]

Entraînement:  34%|███▍      | 3411/10000 [10:57<20:50,  5.27step/s, loss=0.050379, elapsed=11.0min]

Entraînement:  34%|███▍      | 3412/10000 [10:57<20:49,  5.27step/s, loss=0.050379, elapsed=11.0min]

Entraînement:  34%|███▍      | 3412/10000 [10:57<20:49,  5.27step/s, loss=0.097888, elapsed=11.0min]

Entraînement:  34%|███▍      | 3413/10000 [10:57<20:47,  5.28step/s, loss=0.097888, elapsed=11.0min]

Entraînement:  34%|███▍      | 3413/10000 [10:57<20:47,  5.28step/s, loss=0.049505, elapsed=11.0min]

Entraînement:  34%|███▍      | 3414/10000 [10:57<20:47,  5.28step/s, loss=0.049505, elapsed=11.0min]

Entraînement:  34%|███▍      | 3414/10000 [10:57<20:47,  5.28step/s, loss=0.049118, elapsed=11.0min]

Entraînement:  34%|███▍      | 3415/10000 [10:58<20:50,  5.27step/s, loss=0.049118, elapsed=11.0min]

Entraînement:  34%|███▍      | 3415/10000 [10:58<20:50,  5.27step/s, loss=0.051744, elapsed=11.0min]

Entraînement:  34%|███▍      | 3416/10000 [10:58<20:50,  5.26step/s, loss=0.051744, elapsed=11.0min]

Entraînement:  34%|███▍      | 3416/10000 [10:58<20:50,  5.26step/s, loss=0.033788, elapsed=11.0min]

Entraînement:  34%|███▍      | 3417/10000 [10:58<20:50,  5.26step/s, loss=0.033788, elapsed=11.0min]

Entraînement:  34%|███▍      | 3417/10000 [10:58<20:50,  5.26step/s, loss=0.068167, elapsed=11.0min]

Entraînement:  34%|███▍      | 3418/10000 [10:58<20:49,  5.27step/s, loss=0.068167, elapsed=11.0min]

Entraînement:  34%|███▍      | 3418/10000 [10:58<20:49,  5.27step/s, loss=0.028970, elapsed=11.0min]

Entraînement:  34%|███▍      | 3419/10000 [10:58<20:47,  5.28step/s, loss=0.028970, elapsed=11.0min]

Entraînement:  34%|███▍      | 3419/10000 [10:58<20:47,  5.28step/s, loss=0.033313, elapsed=11.0min]

Entraînement:  34%|███▍      | 3420/10000 [10:59<20:47,  5.27step/s, loss=0.033313, elapsed=11.0min]

Entraînement:  34%|███▍      | 3420/10000 [10:59<20:47,  5.27step/s, loss=0.248455, elapsed=11.0min]

Entraînement:  34%|███▍      | 3421/10000 [10:59<20:51,  5.26step/s, loss=0.248455, elapsed=11.0min]

Entraînement:  34%|███▍      | 3421/10000 [10:59<20:51,  5.26step/s, loss=0.065709, elapsed=11.0min]

Entraînement:  34%|███▍      | 3422/10000 [10:59<20:55,  5.24step/s, loss=0.065709, elapsed=11.0min]

Entraînement:  34%|███▍      | 3422/10000 [10:59<20:55,  5.24step/s, loss=0.070802, elapsed=11.0min]

Entraînement:  34%|███▍      | 3423/10000 [10:59<20:52,  5.25step/s, loss=0.070802, elapsed=11.0min]

Entraînement:  34%|███▍      | 3423/10000 [10:59<20:52,  5.25step/s, loss=0.042858, elapsed=11.0min]

Entraînement:  34%|███▍      | 3424/10000 [10:59<20:51,  5.25step/s, loss=0.042858, elapsed=11.0min]

Entraînement:  34%|███▍      | 3424/10000 [10:59<20:51,  5.25step/s, loss=0.035480, elapsed=11.0min]

Entraînement:  34%|███▍      | 3425/10000 [10:59<20:49,  5.26step/s, loss=0.035480, elapsed=11.0min]

Entraînement:  34%|███▍      | 3425/10000 [10:59<20:49,  5.26step/s, loss=0.041883, elapsed=11.0min]

Entraînement:  34%|███▍      | 3426/10000 [11:00<20:47,  5.27step/s, loss=0.041883, elapsed=11.0min]

Entraînement:  34%|███▍      | 3426/10000 [11:00<20:47,  5.27step/s, loss=0.043995, elapsed=11.0min]

Entraînement:  34%|███▍      | 3427/10000 [11:00<20:45,  5.28step/s, loss=0.043995, elapsed=11.0min]

Entraînement:  34%|███▍      | 3427/10000 [11:00<20:45,  5.28step/s, loss=0.023674, elapsed=11.0min]

Entraînement:  34%|███▍      | 3428/10000 [11:00<20:44,  5.28step/s, loss=0.023674, elapsed=11.0min]

Entraînement:  34%|███▍      | 3428/10000 [11:00<20:44,  5.28step/s, loss=0.048015, elapsed=11.0min]

Entraînement:  34%|███▍      | 3429/10000 [11:00<20:45,  5.28step/s, loss=0.048015, elapsed=11.0min]

Entraînement:  34%|███▍      | 3429/10000 [11:00<20:45,  5.28step/s, loss=0.062033, elapsed=11.0min]

Entraînement:  34%|███▍      | 3430/10000 [11:00<20:44,  5.28step/s, loss=0.062033, elapsed=11.0min]

Entraînement:  34%|███▍      | 3430/10000 [11:00<20:44,  5.28step/s, loss=0.038543, elapsed=11.0min]

Entraînement:  34%|███▍      | 3431/10000 [11:01<20:46,  5.27step/s, loss=0.038543, elapsed=11.0min]

Entraînement:  34%|███▍      | 3431/10000 [11:01<20:46,  5.27step/s, loss=0.100025, elapsed=11.0min]

Entraînement:  34%|███▍      | 3432/10000 [11:01<20:45,  5.27step/s, loss=0.100025, elapsed=11.0min]

Entraînement:  34%|███▍      | 3432/10000 [11:01<20:45,  5.27step/s, loss=0.096276, elapsed=11.0min]

Entraînement:  34%|███▍      | 3433/10000 [11:01<20:48,  5.26step/s, loss=0.096276, elapsed=11.0min]

Entraînement:  34%|███▍      | 3433/10000 [11:01<20:48,  5.26step/s, loss=0.051200, elapsed=11.0min]

Entraînement:  34%|███▍      | 3434/10000 [11:01<20:47,  5.26step/s, loss=0.051200, elapsed=11.0min]

Entraînement:  34%|███▍      | 3434/10000 [11:01<20:47,  5.26step/s, loss=0.028236, elapsed=11.0min]

Entraînement:  34%|███▍      | 3435/10000 [11:01<20:45,  5.27step/s, loss=0.028236, elapsed=11.0min]

Entraînement:  34%|███▍      | 3435/10000 [11:01<20:45,  5.27step/s, loss=0.036040, elapsed=11.0min]

Entraînement:  34%|███▍      | 3436/10000 [11:02<20:43,  5.28step/s, loss=0.036040, elapsed=11.0min]

Entraînement:  34%|███▍      | 3436/10000 [11:02<20:43,  5.28step/s, loss=0.093219, elapsed=11.0min]

Entraînement:  34%|███▍      | 3437/10000 [11:02<20:41,  5.29step/s, loss=0.093219, elapsed=11.0min]

Entraînement:  34%|███▍      | 3437/10000 [11:02<20:41,  5.29step/s, loss=0.037971, elapsed=11.0min]

Entraînement:  34%|███▍      | 3438/10000 [11:02<20:43,  5.28step/s, loss=0.037971, elapsed=11.0min]

Entraînement:  34%|███▍      | 3438/10000 [11:02<20:43,  5.28step/s, loss=0.048104, elapsed=11.0min]

Entraînement:  34%|███▍      | 3439/10000 [11:02<20:47,  5.26step/s, loss=0.048104, elapsed=11.0min]

Entraînement:  34%|███▍      | 3439/10000 [11:02<20:47,  5.26step/s, loss=0.031112, elapsed=11.0min]

Entraînement:  34%|███▍      | 3440/10000 [11:02<20:46,  5.26step/s, loss=0.031112, elapsed=11.0min]

Entraînement:  34%|███▍      | 3440/10000 [11:02<20:46,  5.26step/s, loss=0.103660, elapsed=11.0min]

Entraînement:  34%|███▍      | 3441/10000 [11:03<20:47,  5.26step/s, loss=0.103660, elapsed=11.0min]

Entraînement:  34%|███▍      | 3441/10000 [11:03<20:47,  5.26step/s, loss=0.110842, elapsed=11.1min]

Entraînement:  34%|███▍      | 3442/10000 [11:03<20:48,  5.25step/s, loss=0.110842, elapsed=11.1min]

Entraînement:  34%|███▍      | 3442/10000 [11:03<20:48,  5.25step/s, loss=0.139396, elapsed=11.1min]

Entraînement:  34%|███▍      | 3443/10000 [11:03<20:46,  5.26step/s, loss=0.139396, elapsed=11.1min]

Entraînement:  34%|███▍      | 3443/10000 [11:03<20:46,  5.26step/s, loss=0.084356, elapsed=11.1min]

Entraînement:  34%|███▍      | 3444/10000 [11:03<20:43,  5.27step/s, loss=0.084356, elapsed=11.1min]

Entraînement:  34%|███▍      | 3444/10000 [11:03<20:43,  5.27step/s, loss=0.039171, elapsed=11.1min]

Entraînement:  34%|███▍      | 3445/10000 [11:03<20:42,  5.28step/s, loss=0.039171, elapsed=11.1min]

Entraînement:  34%|███▍      | 3445/10000 [11:03<20:42,  5.28step/s, loss=0.043446, elapsed=11.1min]

Entraînement:  34%|███▍      | 3446/10000 [11:03<20:42,  5.27step/s, loss=0.043446, elapsed=11.1min]

Entraînement:  34%|███▍      | 3446/10000 [11:03<20:42,  5.27step/s, loss=0.033376, elapsed=11.1min]

Entraînement:  34%|███▍      | 3447/10000 [11:04<20:40,  5.28step/s, loss=0.033376, elapsed=11.1min]

Entraînement:  34%|███▍      | 3447/10000 [11:04<20:40,  5.28step/s, loss=0.053008, elapsed=11.1min]

Entraînement:  34%|███▍      | 3448/10000 [11:04<20:41,  5.28step/s, loss=0.053008, elapsed=11.1min]

Entraînement:  34%|███▍      | 3448/10000 [11:04<20:41,  5.28step/s, loss=0.082373, elapsed=11.1min]

Entraînement:  34%|███▍      | 3449/10000 [11:04<20:40,  5.28step/s, loss=0.082373, elapsed=11.1min]

Entraînement:  34%|███▍      | 3449/10000 [11:04<20:40,  5.28step/s, loss=0.034703, elapsed=11.1min]

Entraînement:  34%|███▍      | 3450/10000 [11:04<20:40,  5.28step/s, loss=0.034703, elapsed=11.1min]

Entraînement:  34%|███▍      | 3450/10000 [11:04<20:40,  5.28step/s, loss=0.085526, elapsed=11.1min]

Entraînement:  35%|███▍      | 3451/10000 [11:04<20:44,  5.26step/s, loss=0.085526, elapsed=11.1min]

Entraînement:  35%|███▍      | 3451/10000 [11:04<20:44,  5.26step/s, loss=0.066483, elapsed=11.1min]

Entraînement:  35%|███▍      | 3452/10000 [11:05<20:42,  5.27step/s, loss=0.066483, elapsed=11.1min]

Entraînement:  35%|███▍      | 3452/10000 [11:05<20:42,  5.27step/s, loss=0.072856, elapsed=11.1min]

Entraînement:  35%|███▍      | 3453/10000 [11:05<20:41,  5.27step/s, loss=0.072856, elapsed=11.1min]

Entraînement:  35%|███▍      | 3453/10000 [11:05<20:41,  5.27step/s, loss=0.044490, elapsed=11.1min]

Entraînement:  35%|███▍      | 3454/10000 [11:05<20:43,  5.27step/s, loss=0.044490, elapsed=11.1min]

Entraînement:  35%|███▍      | 3454/10000 [11:05<20:43,  5.27step/s, loss=0.030748, elapsed=11.1min]

Entraînement:  35%|███▍      | 3455/10000 [11:05<20:41,  5.27step/s, loss=0.030748, elapsed=11.1min]

Entraînement:  35%|███▍      | 3455/10000 [11:05<20:41,  5.27step/s, loss=0.046006, elapsed=11.1min]

Entraînement:  35%|███▍      | 3456/10000 [11:05<20:39,  5.28step/s, loss=0.046006, elapsed=11.1min]

Entraînement:  35%|███▍      | 3456/10000 [11:05<20:39,  5.28step/s, loss=0.039421, elapsed=11.1min]

Entraînement:  35%|███▍      | 3457/10000 [11:06<20:39,  5.28step/s, loss=0.039421, elapsed=11.1min]

Entraînement:  35%|███▍      | 3457/10000 [11:06<20:39,  5.28step/s, loss=0.046598, elapsed=11.1min]

Entraînement:  35%|███▍      | 3458/10000 [11:06<20:38,  5.28step/s, loss=0.046598, elapsed=11.1min]

Entraînement:  35%|███▍      | 3458/10000 [11:06<20:38,  5.28step/s, loss=0.044320, elapsed=11.1min]

Entraînement:  35%|███▍      | 3459/10000 [11:06<20:37,  5.29step/s, loss=0.044320, elapsed=11.1min]

Entraînement:  35%|███▍      | 3459/10000 [11:06<20:37,  5.29step/s, loss=0.026825, elapsed=11.1min]

Entraînement:  35%|███▍      | 3460/10000 [11:06<20:37,  5.29step/s, loss=0.026825, elapsed=11.1min]

Entraînement:  35%|███▍      | 3460/10000 [11:06<20:37,  5.29step/s, loss=0.111052, elapsed=11.1min]

Entraînement:  35%|███▍      | 3461/10000 [11:06<20:35,  5.29step/s, loss=0.111052, elapsed=11.1min]

Entraînement:  35%|███▍      | 3461/10000 [11:06<20:35,  5.29step/s, loss=0.050677, elapsed=11.1min]

Entraînement:  35%|███▍      | 3462/10000 [11:07<20:39,  5.28step/s, loss=0.050677, elapsed=11.1min]

Entraînement:  35%|███▍      | 3462/10000 [11:07<20:39,  5.28step/s, loss=0.052673, elapsed=11.1min]

Entraînement:  35%|███▍      | 3463/10000 [11:07<20:40,  5.27step/s, loss=0.052673, elapsed=11.1min]

Entraînement:  35%|███▍      | 3463/10000 [11:07<20:40,  5.27step/s, loss=0.055212, elapsed=11.1min]

Entraînement:  35%|███▍      | 3464/10000 [11:07<20:40,  5.27step/s, loss=0.055212, elapsed=11.1min]

Entraînement:  35%|███▍      | 3464/10000 [11:07<20:40,  5.27step/s, loss=0.196728, elapsed=11.1min]

Entraînement:  35%|███▍      | 3465/10000 [11:07<20:39,  5.27step/s, loss=0.196728, elapsed=11.1min]

Entraînement:  35%|███▍      | 3465/10000 [11:07<20:39,  5.27step/s, loss=0.031262, elapsed=11.1min]

Entraînement:  35%|███▍      | 3466/10000 [11:07<20:37,  5.28step/s, loss=0.031262, elapsed=11.1min]

Entraînement:  35%|███▍      | 3466/10000 [11:07<20:37,  5.28step/s, loss=0.107539, elapsed=11.1min]

Entraînement:  35%|███▍      | 3467/10000 [11:07<20:37,  5.28step/s, loss=0.107539, elapsed=11.1min]

Entraînement:  35%|███▍      | 3467/10000 [11:07<20:37,  5.28step/s, loss=0.047288, elapsed=11.1min]

Entraînement:  35%|███▍      | 3468/10000 [11:08<20:35,  5.29step/s, loss=0.047288, elapsed=11.1min]

Entraînement:  35%|███▍      | 3468/10000 [11:08<20:35,  5.29step/s, loss=0.047308, elapsed=11.1min]

Entraînement:  35%|███▍      | 3469/10000 [11:08<20:34,  5.29step/s, loss=0.047308, elapsed=11.1min]

Entraînement:  35%|███▍      | 3469/10000 [11:08<20:34,  5.29step/s, loss=0.039889, elapsed=11.1min]

Entraînement:  35%|███▍      | 3470/10000 [11:08<20:38,  5.27step/s, loss=0.039889, elapsed=11.1min]

Entraînement:  35%|███▍      | 3470/10000 [11:08<20:38,  5.27step/s, loss=0.080745, elapsed=11.1min]

Entraînement:  35%|███▍      | 3471/10000 [11:08<20:39,  5.27step/s, loss=0.080745, elapsed=11.1min]

Entraînement:  35%|███▍      | 3471/10000 [11:08<20:39,  5.27step/s, loss=0.058125, elapsed=11.1min]

Entraînement:  35%|███▍      | 3472/10000 [11:08<20:38,  5.27step/s, loss=0.058125, elapsed=11.1min]

Entraînement:  35%|███▍      | 3472/10000 [11:08<20:38,  5.27step/s, loss=0.029040, elapsed=11.1min]

Entraînement:  35%|███▍      | 3473/10000 [11:09<20:35,  5.28step/s, loss=0.029040, elapsed=11.1min]

Entraînement:  35%|███▍      | 3473/10000 [11:09<20:35,  5.28step/s, loss=0.043359, elapsed=11.2min]

Entraînement:  35%|███▍      | 3474/10000 [11:09<20:36,  5.28step/s, loss=0.043359, elapsed=11.2min]

Entraînement:  35%|███▍      | 3474/10000 [11:09<20:36,  5.28step/s, loss=0.065869, elapsed=11.2min]

Entraînement:  35%|███▍      | 3475/10000 [11:09<20:34,  5.29step/s, loss=0.065869, elapsed=11.2min]

Entraînement:  35%|███▍      | 3475/10000 [11:09<20:34,  5.29step/s, loss=0.058525, elapsed=11.2min]

Entraînement:  35%|███▍      | 3476/10000 [11:09<20:31,  5.30step/s, loss=0.058525, elapsed=11.2min]

Entraînement:  35%|███▍      | 3476/10000 [11:09<20:31,  5.30step/s, loss=0.097735, elapsed=11.2min]

Entraînement:  35%|███▍      | 3477/10000 [11:09<20:33,  5.29step/s, loss=0.097735, elapsed=11.2min]

Entraînement:  35%|███▍      | 3477/10000 [11:09<20:33,  5.29step/s, loss=0.074345, elapsed=11.2min]

Entraînement:  35%|███▍      | 3478/10000 [11:10<20:35,  5.28step/s, loss=0.074345, elapsed=11.2min]

Entraînement:  35%|███▍      | 3478/10000 [11:10<20:35,  5.28step/s, loss=0.071603, elapsed=11.2min]

Entraînement:  35%|███▍      | 3479/10000 [11:10<20:38,  5.27step/s, loss=0.071603, elapsed=11.2min]

Entraînement:  35%|███▍      | 3479/10000 [11:10<20:38,  5.27step/s, loss=0.077940, elapsed=11.2min]

Entraînement:  35%|███▍      | 3480/10000 [11:10<20:36,  5.27step/s, loss=0.077940, elapsed=11.2min]

Entraînement:  35%|███▍      | 3480/10000 [11:10<20:36,  5.27step/s, loss=0.063767, elapsed=11.2min]

Entraînement:  35%|███▍      | 3481/10000 [11:10<20:39,  5.26step/s, loss=0.063767, elapsed=11.2min]

Entraînement:  35%|███▍      | 3481/10000 [11:10<20:39,  5.26step/s, loss=0.113006, elapsed=11.2min]

Entraînement:  35%|███▍      | 3482/10000 [11:10<20:38,  5.26step/s, loss=0.113006, elapsed=11.2min]

Entraînement:  35%|███▍      | 3482/10000 [11:10<20:38,  5.26step/s, loss=0.060178, elapsed=11.2min]

Entraînement:  35%|███▍      | 3483/10000 [11:10<20:39,  5.26step/s, loss=0.060178, elapsed=11.2min]

Entraînement:  35%|███▍      | 3483/10000 [11:10<20:39,  5.26step/s, loss=0.096454, elapsed=11.2min]

Entraînement:  35%|███▍      | 3484/10000 [11:11<20:38,  5.26step/s, loss=0.096454, elapsed=11.2min]

Entraînement:  35%|███▍      | 3484/10000 [11:11<20:38,  5.26step/s, loss=0.054421, elapsed=11.2min]

Entraînement:  35%|███▍      | 3485/10000 [11:11<20:38,  5.26step/s, loss=0.054421, elapsed=11.2min]

Entraînement:  35%|███▍      | 3485/10000 [11:11<20:38,  5.26step/s, loss=0.098746, elapsed=11.2min]

Entraînement:  35%|███▍      | 3486/10000 [11:11<20:40,  5.25step/s, loss=0.098746, elapsed=11.2min]

Entraînement:  35%|███▍      | 3486/10000 [11:11<20:40,  5.25step/s, loss=0.145589, elapsed=11.2min]

Entraînement:  35%|███▍      | 3487/10000 [11:11<20:38,  5.26step/s, loss=0.145589, elapsed=11.2min]

Entraînement:  35%|███▍      | 3487/10000 [11:11<20:38,  5.26step/s, loss=0.050322, elapsed=11.2min]

Entraînement:  35%|███▍      | 3488/10000 [11:11<20:39,  5.25step/s, loss=0.050322, elapsed=11.2min]

Entraînement:  35%|███▍      | 3488/10000 [11:11<20:39,  5.25step/s, loss=0.038511, elapsed=11.2min]

Entraînement:  35%|███▍      | 3489/10000 [11:12<20:38,  5.26step/s, loss=0.038511, elapsed=11.2min]

Entraînement:  35%|███▍      | 3489/10000 [11:12<20:38,  5.26step/s, loss=0.030952, elapsed=11.2min]

Entraînement:  35%|███▍      | 3490/10000 [11:12<20:37,  5.26step/s, loss=0.030952, elapsed=11.2min]

Entraînement:  35%|███▍      | 3490/10000 [11:12<20:37,  5.26step/s, loss=0.044184, elapsed=11.2min]

Entraînement:  35%|███▍      | 3491/10000 [11:12<20:36,  5.27step/s, loss=0.044184, elapsed=11.2min]

Entraînement:  35%|███▍      | 3491/10000 [11:12<20:36,  5.27step/s, loss=0.087736, elapsed=11.2min]

Entraînement:  35%|███▍      | 3492/10000 [11:12<20:36,  5.26step/s, loss=0.087736, elapsed=11.2min]

Entraînement:  35%|███▍      | 3492/10000 [11:12<20:36,  5.26step/s, loss=0.061326, elapsed=11.2min]

Entraînement:  35%|███▍      | 3493/10000 [11:12<20:39,  5.25step/s, loss=0.061326, elapsed=11.2min]

Entraînement:  35%|███▍      | 3493/10000 [11:12<20:39,  5.25step/s, loss=0.078993, elapsed=11.2min]

Entraînement:  35%|███▍      | 3494/10000 [11:13<20:37,  5.26step/s, loss=0.078993, elapsed=11.2min]

Entraînement:  35%|███▍      | 3494/10000 [11:13<20:37,  5.26step/s, loss=0.086491, elapsed=11.2min]

Entraînement:  35%|███▍      | 3495/10000 [11:13<20:36,  5.26step/s, loss=0.086491, elapsed=11.2min]

Entraînement:  35%|███▍      | 3495/10000 [11:13<20:36,  5.26step/s, loss=0.034854, elapsed=11.2min]

Entraînement:  35%|███▍      | 3496/10000 [11:13<20:34,  5.27step/s, loss=0.034854, elapsed=11.2min]

Entraînement:  35%|███▍      | 3496/10000 [11:13<20:34,  5.27step/s, loss=0.043203, elapsed=11.2min]

Entraînement:  35%|███▍      | 3497/10000 [11:13<20:36,  5.26step/s, loss=0.043203, elapsed=11.2min]

Entraînement:  35%|███▍      | 3497/10000 [11:13<20:36,  5.26step/s, loss=0.087527, elapsed=11.2min]

Entraînement:  35%|███▍      | 3498/10000 [11:13<20:34,  5.27step/s, loss=0.087527, elapsed=11.2min]

Entraînement:  35%|███▍      | 3498/10000 [11:13<20:34,  5.27step/s, loss=0.064245, elapsed=11.2min]

Entraînement:  35%|███▍      | 3499/10000 [11:14<20:35,  5.26step/s, loss=0.064245, elapsed=11.2min]

Entraînement:  35%|███▍      | 3499/10000 [11:14<20:35,  5.26step/s, loss=0.050013, elapsed=11.2min]

Entraînement:  35%|███▌      | 3500/10000 [11:14<20:34,  5.27step/s, loss=0.050013, elapsed=11.2min]

Entraînement:  35%|███▌      | 3500/10000 [11:14<20:34,  5.27step/s, loss=0.048485, elapsed=11.2min]

Entraînement:  35%|███▌      | 3500/10000 [11:14<20:34,  5.27step/s, loss=0.048485, elapsed=11.2min]

Entraînement:  35%|███▌      | 3501/10000 [11:14<20:48,  5.21step/s, loss=0.048485, elapsed=11.2min]

Entraînement:  35%|███▌      | 3501/10000 [11:14<20:48,  5.21step/s, loss=0.058857, elapsed=11.2min]

Step 3500/10000 | Train loss: 0.048485 | Elapsed: 11.2min | ETA: 20.9min

Entraînement:  35%|███▌      | 3502/10000 [11:14<20:41,  5.24step/s, loss=0.058857, elapsed=11.2min]

Entraînement:  35%|███▌      | 3502/10000 [11:14<20:41,  5.24step/s, loss=0.042076, elapsed=11.2min]

Entraînement:  35%|███▌      | 3503/10000 [11:14<20:40,  5.24step/s, loss=0.042076, elapsed=11.2min]

Entraînement:  35%|███▌      | 3503/10000 [11:14<20:40,  5.24step/s, loss=0.029705, elapsed=11.2min]

Entraînement:  35%|███▌      | 3504/10000 [11:14<20:36,  5.25step/s, loss=0.029705, elapsed=11.2min]

Entraînement:  35%|███▌      | 3504/10000 [11:14<20:36,  5.25step/s, loss=0.056010, elapsed=11.2min]

Entraînement:  35%|███▌      | 3505/10000 [11:15<20:34,  5.26step/s, loss=0.056010, elapsed=11.2min]

Entraînement:  35%|███▌      | 3505/10000 [11:15<20:34,  5.26step/s, loss=0.038530, elapsed=11.3min]

Entraînement:  35%|███▌      | 3506/10000 [11:15<20:32,  5.27step/s, loss=0.038530, elapsed=11.3min]

Entraînement:  35%|███▌      | 3506/10000 [11:15<20:32,  5.27step/s, loss=0.032327, elapsed=11.3min]

Entraînement:  35%|███▌      | 3507/10000 [11:15<20:29,  5.28step/s, loss=0.032327, elapsed=11.3min]

Entraînement:  35%|███▌      | 3507/10000 [11:15<20:29,  5.28step/s, loss=0.035773, elapsed=11.3min]

Entraînement:  35%|███▌      | 3508/10000 [11:15<20:32,  5.27step/s, loss=0.035773, elapsed=11.3min]

Entraînement:  35%|███▌      | 3508/10000 [11:15<20:32,  5.27step/s, loss=0.132606, elapsed=11.3min]

Entraînement:  35%|███▌      | 3509/10000 [11:15<20:33,  5.26step/s, loss=0.132606, elapsed=11.3min]

Entraînement:  35%|███▌      | 3509/10000 [11:15<20:33,  5.26step/s, loss=0.050092, elapsed=11.3min]

Entraînement:  35%|███▌      | 3510/10000 [11:16<20:29,  5.28step/s, loss=0.050092, elapsed=11.3min]

Entraînement:  35%|███▌      | 3510/10000 [11:16<20:29,  5.28step/s, loss=0.042010, elapsed=11.3min]

Entraînement:  35%|███▌      | 3511/10000 [11:16<20:31,  5.27step/s, loss=0.042010, elapsed=11.3min]

Entraînement:  35%|███▌      | 3511/10000 [11:16<20:31,  5.27step/s, loss=0.057464, elapsed=11.3min]

Entraînement:  35%|███▌      | 3512/10000 [11:16<20:32,  5.26step/s, loss=0.057464, elapsed=11.3min]

Entraînement:  35%|███▌      | 3512/10000 [11:16<20:32,  5.26step/s, loss=0.046026, elapsed=11.3min]

Entraînement:  35%|███▌      | 3513/10000 [11:16<20:31,  5.27step/s, loss=0.046026, elapsed=11.3min]

Entraînement:  35%|███▌      | 3513/10000 [11:16<20:31,  5.27step/s, loss=0.027866, elapsed=11.3min]

Entraînement:  35%|███▌      | 3514/10000 [11:16<20:29,  5.28step/s, loss=0.027866, elapsed=11.3min]

Entraînement:  35%|███▌      | 3514/10000 [11:16<20:29,  5.28step/s, loss=0.051152, elapsed=11.3min]

Entraînement:  35%|███▌      | 3515/10000 [11:17<20:25,  5.29step/s, loss=0.051152, elapsed=11.3min]

Entraînement:  35%|███▌      | 3515/10000 [11:17<20:25,  5.29step/s, loss=0.053153, elapsed=11.3min]

Entraînement:  35%|███▌      | 3516/10000 [11:17<20:30,  5.27step/s, loss=0.053153, elapsed=11.3min]

Entraînement:  35%|███▌      | 3516/10000 [11:17<20:30,  5.27step/s, loss=0.055831, elapsed=11.3min]

Entraînement:  35%|███▌      | 3517/10000 [11:17<20:29,  5.27step/s, loss=0.055831, elapsed=11.3min]

Entraînement:  35%|███▌      | 3517/10000 [11:17<20:29,  5.27step/s, loss=0.041377, elapsed=11.3min]

Entraînement:  35%|███▌      | 3518/10000 [11:17<20:30,  5.27step/s, loss=0.041377, elapsed=11.3min]

Entraînement:  35%|███▌      | 3518/10000 [11:17<20:30,  5.27step/s, loss=0.054298, elapsed=11.3min]

Entraînement:  35%|███▌      | 3519/10000 [11:17<20:28,  5.28step/s, loss=0.054298, elapsed=11.3min]

Entraînement:  35%|███▌      | 3519/10000 [11:17<20:28,  5.28step/s, loss=0.047043, elapsed=11.3min]

Entraînement:  35%|███▌      | 3520/10000 [11:18<20:31,  5.26step/s, loss=0.047043, elapsed=11.3min]

Entraînement:  35%|███▌      | 3520/10000 [11:18<20:31,  5.26step/s, loss=0.050013, elapsed=11.3min]

Entraînement:  35%|███▌      | 3521/10000 [11:18<20:30,  5.27step/s, loss=0.050013, elapsed=11.3min]

Entraînement:  35%|███▌      | 3521/10000 [11:18<20:30,  5.27step/s, loss=0.073690, elapsed=11.3min]

Entraînement:  35%|███▌      | 3522/10000 [11:18<20:31,  5.26step/s, loss=0.073690, elapsed=11.3min]

Entraînement:  35%|███▌      | 3522/10000 [11:18<20:31,  5.26step/s, loss=0.026120, elapsed=11.3min]

Entraînement:  35%|███▌      | 3523/10000 [11:18<20:31,  5.26step/s, loss=0.026120, elapsed=11.3min]

Entraînement:  35%|███▌      | 3523/10000 [11:18<20:31,  5.26step/s, loss=0.072637, elapsed=11.3min]

Entraînement:  35%|███▌      | 3524/10000 [11:18<20:32,  5.25step/s, loss=0.072637, elapsed=11.3min]

Entraînement:  35%|███▌      | 3524/10000 [11:18<20:32,  5.25step/s, loss=0.064074, elapsed=11.3min]

Entraînement:  35%|███▌      | 3525/10000 [11:18<20:30,  5.26step/s, loss=0.064074, elapsed=11.3min]

Entraînement:  35%|███▌      | 3525/10000 [11:18<20:30,  5.26step/s, loss=0.024539, elapsed=11.3min]

Entraînement:  35%|███▌      | 3526/10000 [11:19<20:32,  5.25step/s, loss=0.024539, elapsed=11.3min]

Entraînement:  35%|███▌      | 3526/10000 [11:19<20:32,  5.25step/s, loss=0.043852, elapsed=11.3min]

Entraînement:  35%|███▌      | 3527/10000 [11:19<20:30,  5.26step/s, loss=0.043852, elapsed=11.3min]

Entraînement:  35%|███▌      | 3527/10000 [11:19<20:30,  5.26step/s, loss=0.029260, elapsed=11.3min]

Entraînement:  35%|███▌      | 3528/10000 [11:19<20:28,  5.27step/s, loss=0.029260, elapsed=11.3min]

Entraînement:  35%|███▌      | 3528/10000 [11:19<20:28,  5.27step/s, loss=0.077308, elapsed=11.3min]

Entraînement:  35%|███▌      | 3529/10000 [11:19<20:27,  5.27step/s, loss=0.077308, elapsed=11.3min]

Entraînement:  35%|███▌      | 3529/10000 [11:19<20:27,  5.27step/s, loss=0.063460, elapsed=11.3min]

Entraînement:  35%|███▌      | 3530/10000 [11:19<20:27,  5.27step/s, loss=0.063460, elapsed=11.3min]

Entraînement:  35%|███▌      | 3530/10000 [11:19<20:27,  5.27step/s, loss=0.102500, elapsed=11.3min]

Entraînement:  35%|███▌      | 3531/10000 [11:20<20:43,  5.20step/s, loss=0.102500, elapsed=11.3min]

Entraînement:  35%|███▌      | 3531/10000 [11:20<20:43,  5.20step/s, loss=0.046354, elapsed=11.3min]

Entraînement:  35%|███▌      | 3532/10000 [11:20<20:38,  5.22step/s, loss=0.046354, elapsed=11.3min]

Entraînement:  35%|███▌      | 3532/10000 [11:20<20:38,  5.22step/s, loss=0.039357, elapsed=11.3min]

Entraînement:  35%|███▌      | 3533/10000 [11:20<20:35,  5.23step/s, loss=0.039357, elapsed=11.3min]

Entraînement:  35%|███▌      | 3533/10000 [11:20<20:35,  5.23step/s, loss=0.113146, elapsed=11.3min]

Entraînement:  35%|███▌      | 3534/10000 [11:20<20:32,  5.25step/s, loss=0.113146, elapsed=11.3min]

Entraînement:  35%|███▌      | 3534/10000 [11:20<20:32,  5.25step/s, loss=0.059888, elapsed=11.3min]

Entraînement:  35%|███▌      | 3535/10000 [11:20<20:28,  5.26step/s, loss=0.059888, elapsed=11.3min]

Entraînement:  35%|███▌      | 3535/10000 [11:20<20:28,  5.26step/s, loss=0.047215, elapsed=11.3min]

Entraînement:  35%|███▌      | 3536/10000 [11:21<20:26,  5.27step/s, loss=0.047215, elapsed=11.3min]

Entraînement:  35%|███▌      | 3536/10000 [11:21<20:26,  5.27step/s, loss=0.030374, elapsed=11.4min]

Entraînement:  35%|███▌      | 3537/10000 [11:21<20:24,  5.28step/s, loss=0.030374, elapsed=11.4min]

Entraînement:  35%|███▌      | 3537/10000 [11:21<20:24,  5.28step/s, loss=0.110760, elapsed=11.4min]

Entraînement:  35%|███▌      | 3538/10000 [11:21<20:25,  5.27step/s, loss=0.110760, elapsed=11.4min]

Entraînement:  35%|███▌      | 3538/10000 [11:21<20:25,  5.27step/s, loss=0.098643, elapsed=11.4min]

Entraînement:  35%|███▌      | 3539/10000 [11:21<20:26,  5.27step/s, loss=0.098643, elapsed=11.4min]

Entraînement:  35%|███▌      | 3539/10000 [11:21<20:26,  5.27step/s, loss=0.089953, elapsed=11.4min]

Entraînement:  35%|███▌      | 3540/10000 [11:21<20:24,  5.28step/s, loss=0.089953, elapsed=11.4min]

Entraînement:  35%|███▌      | 3540/10000 [11:21<20:24,  5.28step/s, loss=0.040166, elapsed=11.4min]

Entraînement:  35%|███▌      | 3541/10000 [11:22<20:24,  5.27step/s, loss=0.040166, elapsed=11.4min]

Entraînement:  35%|███▌      | 3541/10000 [11:22<20:24,  5.27step/s, loss=0.046859, elapsed=11.4min]

Entraînement:  35%|███▌      | 3542/10000 [11:22<20:21,  5.29step/s, loss=0.046859, elapsed=11.4min]

Entraînement:  35%|███▌      | 3542/10000 [11:22<20:21,  5.29step/s, loss=0.055321, elapsed=11.4min]

Entraînement:  35%|███▌      | 3543/10000 [11:22<20:22,  5.28step/s, loss=0.055321, elapsed=11.4min]

Entraînement:  35%|███▌      | 3543/10000 [11:22<20:22,  5.28step/s, loss=0.067140, elapsed=11.4min]

Entraînement:  35%|███▌      | 3544/10000 [11:22<20:28,  5.26step/s, loss=0.067140, elapsed=11.4min]

Entraînement:  35%|███▌      | 3544/10000 [11:22<20:28,  5.26step/s, loss=0.066935, elapsed=11.4min]

Entraînement:  35%|███▌      | 3545/10000 [11:22<20:27,  5.26step/s, loss=0.066935, elapsed=11.4min]

Entraînement:  35%|███▌      | 3545/10000 [11:22<20:27,  5.26step/s, loss=0.035662, elapsed=11.4min]

Entraînement:  35%|███▌      | 3546/10000 [11:22<20:26,  5.26step/s, loss=0.035662, elapsed=11.4min]

Entraînement:  35%|███▌      | 3546/10000 [11:22<20:26,  5.26step/s, loss=0.044241, elapsed=11.4min]

Entraînement:  35%|███▌      | 3547/10000 [11:23<20:26,  5.26step/s, loss=0.044241, elapsed=11.4min]

Entraînement:  35%|███▌      | 3547/10000 [11:23<20:26,  5.26step/s, loss=0.031153, elapsed=11.4min]

Entraînement:  35%|███▌      | 3548/10000 [11:23<20:26,  5.26step/s, loss=0.031153, elapsed=11.4min]

Entraînement:  35%|███▌      | 3548/10000 [11:23<20:26,  5.26step/s, loss=0.031216, elapsed=11.4min]

Entraînement:  35%|███▌      | 3549/10000 [11:23<20:26,  5.26step/s, loss=0.031216, elapsed=11.4min]

Entraînement:  35%|███▌      | 3549/10000 [11:23<20:26,  5.26step/s, loss=0.124837, elapsed=11.4min]

Entraînement:  36%|███▌      | 3550/10000 [11:23<20:23,  5.27step/s, loss=0.124837, elapsed=11.4min]

Entraînement:  36%|███▌      | 3550/10000 [11:23<20:23,  5.27step/s, loss=0.039295, elapsed=11.4min]

Entraînement:  36%|███▌      | 3551/10000 [11:23<20:22,  5.28step/s, loss=0.039295, elapsed=11.4min]

Entraînement:  36%|███▌      | 3551/10000 [11:23<20:22,  5.28step/s, loss=0.072780, elapsed=11.4min]

Entraînement:  36%|███▌      | 3552/10000 [11:24<20:21,  5.28step/s, loss=0.072780, elapsed=11.4min]

Entraînement:  36%|███▌      | 3552/10000 [11:24<20:21,  5.28step/s, loss=0.020692, elapsed=11.4min]

Entraînement:  36%|███▌      | 3553/10000 [11:24<20:19,  5.29step/s, loss=0.020692, elapsed=11.4min]

Entraînement:  36%|███▌      | 3553/10000 [11:24<20:19,  5.29step/s, loss=0.032821, elapsed=11.4min]

Entraînement:  36%|███▌      | 3554/10000 [11:24<20:18,  5.29step/s, loss=0.032821, elapsed=11.4min]

Entraînement:  36%|███▌      | 3554/10000 [11:24<20:18,  5.29step/s, loss=0.050825, elapsed=11.4min]

Entraînement:  36%|███▌      | 3555/10000 [11:24<20:21,  5.28step/s, loss=0.050825, elapsed=11.4min]

Entraînement:  36%|███▌      | 3555/10000 [11:24<20:21,  5.28step/s, loss=0.041979, elapsed=11.4min]

Entraînement:  36%|███▌      | 3556/10000 [11:24<20:21,  5.28step/s, loss=0.041979, elapsed=11.4min]

Entraînement:  36%|███▌      | 3556/10000 [11:24<20:21,  5.28step/s, loss=0.062694, elapsed=11.4min]

Entraînement:  36%|███▌      | 3557/10000 [11:25<20:22,  5.27step/s, loss=0.062694, elapsed=11.4min]

Entraînement:  36%|███▌      | 3557/10000 [11:25<20:22,  5.27step/s, loss=0.024177, elapsed=11.4min]

Entraînement:  36%|███▌      | 3558/10000 [11:25<20:22,  5.27step/s, loss=0.024177, elapsed=11.4min]

Entraînement:  36%|███▌      | 3558/10000 [11:25<20:22,  5.27step/s, loss=0.076472, elapsed=11.4min]

Entraînement:  36%|███▌      | 3559/10000 [11:25<20:23,  5.26step/s, loss=0.076472, elapsed=11.4min]

Entraînement:  36%|███▌      | 3559/10000 [11:25<20:23,  5.26step/s, loss=0.094721, elapsed=11.4min]

Entraînement:  36%|███▌      | 3560/10000 [11:25<20:23,  5.26step/s, loss=0.094721, elapsed=11.4min]

Entraînement:  36%|███▌      | 3560/10000 [11:25<20:23,  5.26step/s, loss=0.061354, elapsed=11.4min]

Entraînement:  36%|███▌      | 3561/10000 [11:25<20:21,  5.27step/s, loss=0.061354, elapsed=11.4min]

Entraînement:  36%|███▌      | 3561/10000 [11:25<20:21,  5.27step/s, loss=0.053731, elapsed=11.4min]

Entraînement:  36%|███▌      | 3562/10000 [11:25<20:24,  5.26step/s, loss=0.053731, elapsed=11.4min]

Entraînement:  36%|███▌      | 3562/10000 [11:25<20:24,  5.26step/s, loss=0.032962, elapsed=11.4min]

Entraînement:  36%|███▌      | 3563/10000 [11:26<20:25,  5.25step/s, loss=0.032962, elapsed=11.4min]

Entraînement:  36%|███▌      | 3563/10000 [11:26<20:25,  5.25step/s, loss=0.075057, elapsed=11.4min]

Entraînement:  36%|███▌      | 3564/10000 [11:26<20:25,  5.25step/s, loss=0.075057, elapsed=11.4min]

Entraînement:  36%|███▌      | 3564/10000 [11:26<20:25,  5.25step/s, loss=0.033491, elapsed=11.4min]

Entraînement:  36%|███▌      | 3565/10000 [11:26<20:23,  5.26step/s, loss=0.033491, elapsed=11.4min]

Entraînement:  36%|███▌      | 3565/10000 [11:26<20:23,  5.26step/s, loss=0.051721, elapsed=11.4min]

Entraînement:  36%|███▌      | 3566/10000 [11:26<20:22,  5.26step/s, loss=0.051721, elapsed=11.4min]

Entraînement:  36%|███▌      | 3566/10000 [11:26<20:22,  5.26step/s, loss=0.121164, elapsed=11.4min]

Entraînement:  36%|███▌      | 3567/10000 [11:26<20:22,  5.26step/s, loss=0.121164, elapsed=11.4min]

Entraînement:  36%|███▌      | 3567/10000 [11:26<20:22,  5.26step/s, loss=0.062779, elapsed=11.4min]

Entraînement:  36%|███▌      | 3568/10000 [11:27<20:22,  5.26step/s, loss=0.062779, elapsed=11.4min]

Entraînement:  36%|███▌      | 3568/10000 [11:27<20:22,  5.26step/s, loss=0.034581, elapsed=11.5min]

Entraînement:  36%|███▌      | 3569/10000 [11:27<20:20,  5.27step/s, loss=0.034581, elapsed=11.5min]

Entraînement:  36%|███▌      | 3569/10000 [11:27<20:20,  5.27step/s, loss=0.038599, elapsed=11.5min]

Entraînement:  36%|███▌      | 3570/10000 [11:27<20:13,  5.30step/s, loss=0.038599, elapsed=11.5min]

Entraînement:  36%|███▌      | 3570/10000 [11:27<20:13,  5.30step/s, loss=0.056739, elapsed=11.5min]

Entraînement:  36%|███▌      | 3571/10000 [11:27<20:21,  5.26step/s, loss=0.056739, elapsed=11.5min]

Entraînement:  36%|███▌      | 3571/10000 [11:27<20:21,  5.26step/s, loss=0.056454, elapsed=11.5min]

Entraînement:  36%|███▌      | 3572/10000 [11:27<20:18,  5.28step/s, loss=0.056454, elapsed=11.5min]

Entraînement:  36%|███▌      | 3572/10000 [11:27<20:18,  5.28step/s, loss=0.055966, elapsed=11.5min]

Entraînement:  36%|███▌      | 3573/10000 [11:28<20:18,  5.27step/s, loss=0.055966, elapsed=11.5min]

Entraînement:  36%|███▌      | 3573/10000 [11:28<20:18,  5.27step/s, loss=0.042280, elapsed=11.5min]

Entraînement:  36%|███▌      | 3574/10000 [11:28<20:16,  5.28step/s, loss=0.042280, elapsed=11.5min]

Entraînement:  36%|███▌      | 3574/10000 [11:28<20:16,  5.28step/s, loss=0.036651, elapsed=11.5min]

Entraînement:  36%|███▌      | 3575/10000 [11:28<20:17,  5.28step/s, loss=0.036651, elapsed=11.5min]

Entraînement:  36%|███▌      | 3575/10000 [11:28<20:17,  5.28step/s, loss=0.051531, elapsed=11.5min]

Entraînement:  36%|███▌      | 3576/10000 [11:28<20:22,  5.26step/s, loss=0.051531, elapsed=11.5min]

Entraînement:  36%|███▌      | 3576/10000 [11:28<20:22,  5.26step/s, loss=0.058645, elapsed=11.5min]

Entraînement:  36%|███▌      | 3577/10000 [11:28<20:22,  5.25step/s, loss=0.058645, elapsed=11.5min]

Entraînement:  36%|███▌      | 3577/10000 [11:28<20:22,  5.25step/s, loss=0.049843, elapsed=11.5min]

Entraînement:  36%|███▌      | 3578/10000 [11:29<20:24,  5.25step/s, loss=0.049843, elapsed=11.5min]

Entraînement:  36%|███▌      | 3578/10000 [11:29<20:24,  5.25step/s, loss=0.069275, elapsed=11.5min]

Entraînement:  36%|███▌      | 3579/10000 [11:29<20:21,  5.26step/s, loss=0.069275, elapsed=11.5min]

Entraînement:  36%|███▌      | 3579/10000 [11:29<20:21,  5.26step/s, loss=0.027855, elapsed=11.5min]

Entraînement:  36%|███▌      | 3580/10000 [11:29<20:25,  5.24step/s, loss=0.027855, elapsed=11.5min]

Entraînement:  36%|███▌      | 3580/10000 [11:29<20:25,  5.24step/s, loss=0.054956, elapsed=11.5min]

Entraînement:  36%|███▌      | 3581/10000 [11:29<20:21,  5.26step/s, loss=0.054956, elapsed=11.5min]

Entraînement:  36%|███▌      | 3581/10000 [11:29<20:21,  5.26step/s, loss=0.048320, elapsed=11.5min]

Entraînement:  36%|███▌      | 3582/10000 [11:29<20:17,  5.27step/s, loss=0.048320, elapsed=11.5min]

Entraînement:  36%|███▌      | 3582/10000 [11:29<20:17,  5.27step/s, loss=0.079889, elapsed=11.5min]

Entraînement:  36%|███▌      | 3583/10000 [11:29<20:18,  5.27step/s, loss=0.079889, elapsed=11.5min]

Entraînement:  36%|███▌      | 3583/10000 [11:29<20:18,  5.27step/s, loss=0.045141, elapsed=11.5min]

Entraînement:  36%|███▌      | 3584/10000 [11:30<20:15,  5.28step/s, loss=0.045141, elapsed=11.5min]

Entraînement:  36%|███▌      | 3584/10000 [11:30<20:15,  5.28step/s, loss=0.035763, elapsed=11.5min]

Entraînement:  36%|███▌      | 3585/10000 [11:30<20:17,  5.27step/s, loss=0.035763, elapsed=11.5min]

Entraînement:  36%|███▌      | 3585/10000 [11:30<20:17,  5.27step/s, loss=0.020455, elapsed=11.5min]

Entraînement:  36%|███▌      | 3586/10000 [11:30<20:17,  5.27step/s, loss=0.020455, elapsed=11.5min]

Entraînement:  36%|███▌      | 3586/10000 [11:30<20:17,  5.27step/s, loss=0.058147, elapsed=11.5min]

Entraînement:  36%|███▌      | 3587/10000 [11:30<20:17,  5.27step/s, loss=0.058147, elapsed=11.5min]

Entraînement:  36%|███▌      | 3587/10000 [11:30<20:17,  5.27step/s, loss=0.028853, elapsed=11.5min]

Entraînement:  36%|███▌      | 3588/10000 [11:30<20:11,  5.29step/s, loss=0.028853, elapsed=11.5min]

Entraînement:  36%|███▌      | 3588/10000 [11:30<20:11,  5.29step/s, loss=0.054965, elapsed=11.5min]

Entraînement:  36%|███▌      | 3589/10000 [11:31<20:06,  5.32step/s, loss=0.054965, elapsed=11.5min]

Entraînement:  36%|███▌      | 3589/10000 [11:31<20:06,  5.32step/s, loss=0.116988, elapsed=11.5min]

Entraînement:  36%|███▌      | 3590/10000 [11:31<20:02,  5.33step/s, loss=0.116988, elapsed=11.5min]

Entraînement:  36%|███▌      | 3590/10000 [11:31<20:02,  5.33step/s, loss=0.030398, elapsed=11.5min]

Entraînement:  36%|███▌      | 3591/10000 [11:31<20:01,  5.34step/s, loss=0.030398, elapsed=11.5min]

Entraînement:  36%|███▌      | 3591/10000 [11:31<20:01,  5.34step/s, loss=0.039291, elapsed=11.5min]

Entraînement:  36%|███▌      | 3592/10000 [11:31<19:58,  5.35step/s, loss=0.039291, elapsed=11.5min]

Entraînement:  36%|███▌      | 3592/10000 [11:31<19:58,  5.35step/s, loss=0.032663, elapsed=11.5min]

Entraînement:  36%|███▌      | 3593/10000 [11:31<19:59,  5.34step/s, loss=0.032663, elapsed=11.5min]

Entraînement:  36%|███▌      | 3593/10000 [11:31<19:59,  5.34step/s, loss=0.070257, elapsed=11.5min]

Entraînement:  36%|███▌      | 3594/10000 [11:32<20:02,  5.33step/s, loss=0.070257, elapsed=11.5min]

Entraînement:  36%|███▌      | 3594/10000 [11:32<20:02,  5.33step/s, loss=0.038245, elapsed=11.5min]

Entraînement:  36%|███▌      | 3595/10000 [11:32<20:00,  5.34step/s, loss=0.038245, elapsed=11.5min]

Entraînement:  36%|███▌      | 3595/10000 [11:32<20:00,  5.34step/s, loss=0.047576, elapsed=11.5min]

Entraînement:  36%|███▌      | 3596/10000 [11:32<20:10,  5.29step/s, loss=0.047576, elapsed=11.5min]

Entraînement:  36%|███▌      | 3596/10000 [11:32<20:10,  5.29step/s, loss=0.053093, elapsed=11.5min]

Entraînement:  36%|███▌      | 3597/10000 [11:32<20:13,  5.28step/s, loss=0.053093, elapsed=11.5min]

Entraînement:  36%|███▌      | 3597/10000 [11:32<20:13,  5.28step/s, loss=0.052515, elapsed=11.5min]

Entraînement:  36%|███▌      | 3598/10000 [11:32<20:14,  5.27step/s, loss=0.052515, elapsed=11.5min]

Entraînement:  36%|███▌      | 3598/10000 [11:32<20:14,  5.27step/s, loss=0.046500, elapsed=11.5min]

Entraînement:  36%|███▌      | 3599/10000 [11:33<20:14,  5.27step/s, loss=0.046500, elapsed=11.5min]

Entraînement:  36%|███▌      | 3599/10000 [11:33<20:14,  5.27step/s, loss=0.031809, elapsed=11.6min]

Entraînement:  36%|███▌      | 3600/10000 [11:33<20:12,  5.28step/s, loss=0.031809, elapsed=11.6min]

Entraînement:  36%|███▌      | 3600/10000 [11:33<20:12,  5.28step/s, loss=0.066839, elapsed=11.6min]

Entraînement:  36%|███▌      | 3600/10000 [11:33<20:12,  5.28step/s, loss=0.066839, elapsed=11.6min]

Entraînement:  36%|███▌      | 3601/10000 [11:33<20:25,  5.22step/s, loss=0.066839, elapsed=11.6min]

Entraînement:  36%|███▌      | 3601/10000 [11:33<20:25,  5.22step/s, loss=0.022514, elapsed=11.6min]

Step 3600/10000 | Train loss: 0.066839 | Elapsed: 11.6min | ETA: 20.5min

Entraînement:  36%|███▌      | 3602/10000 [11:33<20:21,  5.24step/s, loss=0.022514, elapsed=11.6min]

Entraînement:  36%|███▌      | 3602/10000 [11:33<20:21,  5.24step/s, loss=0.033497, elapsed=11.6min]

Entraînement:  36%|███▌      | 3603/10000 [11:33<20:19,  5.25step/s, loss=0.033497, elapsed=11.6min]

Entraînement:  36%|███▌      | 3603/10000 [11:33<20:19,  5.25step/s, loss=0.091801, elapsed=11.6min]

Entraînement:  36%|███▌      | 3604/10000 [11:33<20:17,  5.25step/s, loss=0.091801, elapsed=11.6min]

Entraînement:  36%|███▌      | 3604/10000 [11:33<20:17,  5.25step/s, loss=0.036588, elapsed=11.6min]

Entraînement:  36%|███▌      | 3605/10000 [11:34<20:16,  5.26step/s, loss=0.036588, elapsed=11.6min]

Entraînement:  36%|███▌      | 3605/10000 [11:34<20:16,  5.26step/s, loss=0.082254, elapsed=11.6min]

Entraînement:  36%|███▌      | 3606/10000 [11:34<20:14,  5.26step/s, loss=0.082254, elapsed=11.6min]

Entraînement:  36%|███▌      | 3606/10000 [11:34<20:14,  5.26step/s, loss=0.062127, elapsed=11.6min]

Entraînement:  36%|███▌      | 3607/10000 [11:34<20:08,  5.29step/s, loss=0.062127, elapsed=11.6min]

Entraînement:  36%|███▌      | 3607/10000 [11:34<20:08,  5.29step/s, loss=0.041590, elapsed=11.6min]

Entraînement:  36%|███▌      | 3608/10000 [11:34<20:09,  5.28step/s, loss=0.041590, elapsed=11.6min]

Entraînement:  36%|███▌      | 3608/10000 [11:34<20:09,  5.28step/s, loss=0.051490, elapsed=11.6min]

Entraînement:  36%|███▌      | 3609/10000 [11:34<20:11,  5.27step/s, loss=0.051490, elapsed=11.6min]

Entraînement:  36%|███▌      | 3609/10000 [11:34<20:11,  5.27step/s, loss=0.027666, elapsed=11.6min]

Entraînement:  36%|███▌      | 3610/10000 [11:35<20:12,  5.27step/s, loss=0.027666, elapsed=11.6min]

Entraînement:  36%|███▌      | 3610/10000 [11:35<20:12,  5.27step/s, loss=0.042539, elapsed=11.6min]

Entraînement:  36%|███▌      | 3611/10000 [11:35<20:10,  5.28step/s, loss=0.042539, elapsed=11.6min]

Entraînement:  36%|███▌      | 3611/10000 [11:35<20:10,  5.28step/s, loss=0.060211, elapsed=11.6min]

Entraînement:  36%|███▌      | 3612/10000 [11:35<20:11,  5.27step/s, loss=0.060211, elapsed=11.6min]

Entraînement:  36%|███▌      | 3612/10000 [11:35<20:11,  5.27step/s, loss=0.060965, elapsed=11.6min]

Entraînement:  36%|███▌      | 3613/10000 [11:35<20:10,  5.28step/s, loss=0.060965, elapsed=11.6min]

Entraînement:  36%|███▌      | 3613/10000 [11:35<20:10,  5.28step/s, loss=0.018362, elapsed=11.6min]

Entraînement:  36%|███▌      | 3614/10000 [11:35<20:08,  5.29step/s, loss=0.018362, elapsed=11.6min]

Entraînement:  36%|███▌      | 3614/10000 [11:35<20:08,  5.29step/s, loss=0.038956, elapsed=11.6min]

Entraînement:  36%|███▌      | 3615/10000 [11:36<20:08,  5.28step/s, loss=0.038956, elapsed=11.6min]

Entraînement:  36%|███▌      | 3615/10000 [11:36<20:08,  5.28step/s, loss=0.025984, elapsed=11.6min]

Entraînement:  36%|███▌      | 3616/10000 [11:36<20:07,  5.29step/s, loss=0.025984, elapsed=11.6min]

Entraînement:  36%|███▌      | 3616/10000 [11:36<20:07,  5.29step/s, loss=0.053273, elapsed=11.6min]

Entraînement:  36%|███▌      | 3617/10000 [11:36<20:10,  5.27step/s, loss=0.053273, elapsed=11.6min]

Entraînement:  36%|███▌      | 3617/10000 [11:36<20:10,  5.27step/s, loss=0.086900, elapsed=11.6min]

Entraînement:  36%|███▌      | 3618/10000 [11:36<20:09,  5.28step/s, loss=0.086900, elapsed=11.6min]

Entraînement:  36%|███▌      | 3618/10000 [11:36<20:09,  5.28step/s, loss=0.031589, elapsed=11.6min]

Entraînement:  36%|███▌      | 3619/10000 [11:36<20:07,  5.28step/s, loss=0.031589, elapsed=11.6min]

Entraînement:  36%|███▌      | 3619/10000 [11:36<20:07,  5.28step/s, loss=0.033748, elapsed=11.6min]

Entraînement:  36%|███▌      | 3620/10000 [11:36<20:08,  5.28step/s, loss=0.033748, elapsed=11.6min]

Entraînement:  36%|███▌      | 3620/10000 [11:36<20:08,  5.28step/s, loss=0.050185, elapsed=11.6min]

Entraînement:  36%|███▌      | 3621/10000 [11:37<20:06,  5.29step/s, loss=0.050185, elapsed=11.6min]

Entraînement:  36%|███▌      | 3621/10000 [11:37<20:06,  5.29step/s, loss=0.058622, elapsed=11.6min]

Entraînement:  36%|███▌      | 3622/10000 [11:37<20:08,  5.28step/s, loss=0.058622, elapsed=11.6min]

Entraînement:  36%|███▌      | 3622/10000 [11:37<20:08,  5.28step/s, loss=0.022064, elapsed=11.6min]

Entraînement:  36%|███▌      | 3623/10000 [11:37<20:08,  5.28step/s, loss=0.022064, elapsed=11.6min]

Entraînement:  36%|███▌      | 3623/10000 [11:37<20:08,  5.28step/s, loss=0.036282, elapsed=11.6min]

Entraînement:  36%|███▌      | 3624/10000 [11:37<20:06,  5.28step/s, loss=0.036282, elapsed=11.6min]

Entraînement:  36%|███▌      | 3624/10000 [11:37<20:06,  5.28step/s, loss=0.063479, elapsed=11.6min]

Entraînement:  36%|███▋      | 3625/10000 [11:37<20:09,  5.27step/s, loss=0.063479, elapsed=11.6min]

Entraînement:  36%|███▋      | 3625/10000 [11:37<20:09,  5.27step/s, loss=0.051405, elapsed=11.6min]

Entraînement:  36%|███▋      | 3626/10000 [11:38<20:08,  5.27step/s, loss=0.051405, elapsed=11.6min]

Entraînement:  36%|███▋      | 3626/10000 [11:38<20:08,  5.27step/s, loss=0.095048, elapsed=11.6min]

Entraînement:  36%|███▋      | 3627/10000 [11:38<20:09,  5.27step/s, loss=0.095048, elapsed=11.6min]

Entraînement:  36%|███▋      | 3627/10000 [11:38<20:09,  5.27step/s, loss=0.060366, elapsed=11.6min]

Entraînement:  36%|███▋      | 3628/10000 [11:38<20:07,  5.28step/s, loss=0.060366, elapsed=11.6min]

Entraînement:  36%|███▋      | 3628/10000 [11:38<20:07,  5.28step/s, loss=0.058297, elapsed=11.6min]

Entraînement:  36%|███▋      | 3629/10000 [11:38<20:14,  5.24step/s, loss=0.058297, elapsed=11.6min]

Entraînement:  36%|███▋      | 3629/10000 [11:38<20:14,  5.24step/s, loss=0.033176, elapsed=11.6min]

Entraînement:  36%|███▋      | 3630/10000 [11:38<20:11,  5.26step/s, loss=0.033176, elapsed=11.6min]

Entraînement:  36%|███▋      | 3630/10000 [11:38<20:11,  5.26step/s, loss=0.081277, elapsed=11.6min]

Entraînement:  36%|███▋      | 3631/10000 [11:39<20:11,  5.26step/s, loss=0.081277, elapsed=11.6min]

Entraînement:  36%|███▋      | 3631/10000 [11:39<20:11,  5.26step/s, loss=0.052364, elapsed=11.7min]

Entraînement:  36%|███▋      | 3632/10000 [11:39<20:15,  5.24step/s, loss=0.052364, elapsed=11.7min]

Entraînement:  36%|███▋      | 3632/10000 [11:39<20:15,  5.24step/s, loss=0.059958, elapsed=11.7min]

Entraînement:  36%|███▋      | 3633/10000 [11:39<20:17,  5.23step/s, loss=0.059958, elapsed=11.7min]

Entraînement:  36%|███▋      | 3633/10000 [11:39<20:17,  5.23step/s, loss=0.038854, elapsed=11.7min]

Entraînement:  36%|███▋      | 3634/10000 [11:39<20:17,  5.23step/s, loss=0.038854, elapsed=11.7min]

Entraînement:  36%|███▋      | 3634/10000 [11:39<20:17,  5.23step/s, loss=0.037339, elapsed=11.7min]

Entraînement:  36%|███▋      | 3635/10000 [11:39<20:17,  5.23step/s, loss=0.037339, elapsed=11.7min]

Entraînement:  36%|███▋      | 3635/10000 [11:39<20:17,  5.23step/s, loss=0.070010, elapsed=11.7min]

Entraînement:  36%|███▋      | 3636/10000 [11:40<20:13,  5.24step/s, loss=0.070010, elapsed=11.7min]

Entraînement:  36%|███▋      | 3636/10000 [11:40<20:13,  5.24step/s, loss=0.134215, elapsed=11.7min]

Entraînement:  36%|███▋      | 3637/10000 [11:40<20:15,  5.24step/s, loss=0.134215, elapsed=11.7min]

Entraînement:  36%|███▋      | 3637/10000 [11:40<20:15,  5.24step/s, loss=0.120542, elapsed=11.7min]

Entraînement:  36%|███▋      | 3638/10000 [11:40<20:11,  5.25step/s, loss=0.120542, elapsed=11.7min]

Entraînement:  36%|███▋      | 3638/10000 [11:40<20:11,  5.25step/s, loss=0.051120, elapsed=11.7min]

Entraînement:  36%|███▋      | 3639/10000 [11:40<20:12,  5.25step/s, loss=0.051120, elapsed=11.7min]

Entraînement:  36%|███▋      | 3639/10000 [11:40<20:12,  5.25step/s, loss=0.025542, elapsed=11.7min]

Entraînement:  36%|███▋      | 3640/10000 [11:40<20:10,  5.26step/s, loss=0.025542, elapsed=11.7min]

Entraînement:  36%|███▋      | 3640/10000 [11:40<20:10,  5.26step/s, loss=0.035807, elapsed=11.7min]

Entraînement:  36%|███▋      | 3641/10000 [11:40<20:10,  5.25step/s, loss=0.035807, elapsed=11.7min]

Entraînement:  36%|███▋      | 3641/10000 [11:40<20:10,  5.25step/s, loss=0.038476, elapsed=11.7min]

Entraînement:  36%|███▋      | 3642/10000 [11:41<20:08,  5.26step/s, loss=0.038476, elapsed=11.7min]

Entraînement:  36%|███▋      | 3642/10000 [11:41<20:08,  5.26step/s, loss=0.045275, elapsed=11.7min]

Entraînement:  36%|███▋      | 3643/10000 [11:41<20:04,  5.28step/s, loss=0.045275, elapsed=11.7min]

Entraînement:  36%|███▋      | 3643/10000 [11:41<20:04,  5.28step/s, loss=0.040662, elapsed=11.7min]

Entraînement:  36%|███▋      | 3644/10000 [11:41<20:05,  5.27step/s, loss=0.040662, elapsed=11.7min]

Entraînement:  36%|███▋      | 3644/10000 [11:41<20:05,  5.27step/s, loss=0.028276, elapsed=11.7min]

Entraînement:  36%|███▋      | 3645/10000 [11:41<20:03,  5.28step/s, loss=0.028276, elapsed=11.7min]

Entraînement:  36%|███▋      | 3645/10000 [11:41<20:03,  5.28step/s, loss=0.117287, elapsed=11.7min]

Entraînement:  36%|███▋      | 3646/10000 [11:41<20:02,  5.28step/s, loss=0.117287, elapsed=11.7min]

Entraînement:  36%|███▋      | 3646/10000 [11:41<20:02,  5.28step/s, loss=0.038571, elapsed=11.7min]

Entraînement:  36%|███▋      | 3647/10000 [11:42<20:04,  5.27step/s, loss=0.038571, elapsed=11.7min]

Entraînement:  36%|███▋      | 3647/10000 [11:42<20:04,  5.27step/s, loss=0.153405, elapsed=11.7min]

Entraînement:  36%|███▋      | 3648/10000 [11:42<20:04,  5.28step/s, loss=0.153405, elapsed=11.7min]

Entraînement:  36%|███▋      | 3648/10000 [11:42<20:04,  5.28step/s, loss=0.074593, elapsed=11.7min]

Entraînement:  36%|███▋      | 3649/10000 [11:42<20:06,  5.27step/s, loss=0.074593, elapsed=11.7min]

Entraînement:  36%|███▋      | 3649/10000 [11:42<20:06,  5.27step/s, loss=0.047523, elapsed=11.7min]

Entraînement:  36%|███▋      | 3650/10000 [11:42<20:05,  5.27step/s, loss=0.047523, elapsed=11.7min]

Entraînement:  36%|███▋      | 3650/10000 [11:42<20:05,  5.27step/s, loss=0.039857, elapsed=11.7min]

Entraînement:  37%|███▋      | 3651/10000 [11:42<20:06,  5.26step/s, loss=0.039857, elapsed=11.7min]

Entraînement:  37%|███▋      | 3651/10000 [11:42<20:06,  5.26step/s, loss=0.108008, elapsed=11.7min]

Entraînement:  37%|███▋      | 3652/10000 [11:43<20:04,  5.27step/s, loss=0.108008, elapsed=11.7min]

Entraînement:  37%|███▋      | 3652/10000 [11:43<20:04,  5.27step/s, loss=0.025148, elapsed=11.7min]

Entraînement:  37%|███▋      | 3653/10000 [11:43<20:02,  5.28step/s, loss=0.025148, elapsed=11.7min]

Entraînement:  37%|███▋      | 3653/10000 [11:43<20:02,  5.28step/s, loss=0.047210, elapsed=11.7min]

Entraînement:  37%|███▋      | 3654/10000 [11:43<20:04,  5.27step/s, loss=0.047210, elapsed=11.7min]

Entraînement:  37%|███▋      | 3654/10000 [11:43<20:04,  5.27step/s, loss=0.087046, elapsed=11.7min]

Entraînement:  37%|███▋      | 3655/10000 [11:43<20:03,  5.27step/s, loss=0.087046, elapsed=11.7min]

Entraînement:  37%|███▋      | 3655/10000 [11:43<20:03,  5.27step/s, loss=0.081170, elapsed=11.7min]

Entraînement:  37%|███▋      | 3656/10000 [11:43<20:08,  5.25step/s, loss=0.081170, elapsed=11.7min]

Entraînement:  37%|███▋      | 3656/10000 [11:43<20:08,  5.25step/s, loss=0.102828, elapsed=11.7min]

Entraînement:  37%|███▋      | 3657/10000 [11:44<20:06,  5.26step/s, loss=0.102828, elapsed=11.7min]

Entraînement:  37%|███▋      | 3657/10000 [11:44<20:06,  5.26step/s, loss=0.047782, elapsed=11.7min]

Entraînement:  37%|███▋      | 3658/10000 [11:44<20:05,  5.26step/s, loss=0.047782, elapsed=11.7min]

Entraînement:  37%|███▋      | 3658/10000 [11:44<20:05,  5.26step/s, loss=0.029624, elapsed=11.7min]

Entraînement:  37%|███▋      | 3659/10000 [11:44<20:03,  5.27step/s, loss=0.029624, elapsed=11.7min]

Entraînement:  37%|███▋      | 3659/10000 [11:44<20:03,  5.27step/s, loss=0.026805, elapsed=11.7min]

Entraînement:  37%|███▋      | 3660/10000 [11:44<20:04,  5.27step/s, loss=0.026805, elapsed=11.7min]

Entraînement:  37%|███▋      | 3660/10000 [11:44<20:04,  5.27step/s, loss=0.033470, elapsed=11.7min]

Entraînement:  37%|███▋      | 3661/10000 [11:44<20:03,  5.27step/s, loss=0.033470, elapsed=11.7min]

Entraînement:  37%|███▋      | 3661/10000 [11:44<20:03,  5.27step/s, loss=0.044338, elapsed=11.7min]

Entraînement:  37%|███▋      | 3662/10000 [11:44<20:04,  5.26step/s, loss=0.044338, elapsed=11.7min]

Entraînement:  37%|███▋      | 3662/10000 [11:44<20:04,  5.26step/s, loss=0.035183, elapsed=11.7min]

Entraînement:  37%|███▋      | 3663/10000 [11:45<20:07,  5.25step/s, loss=0.035183, elapsed=11.7min]

Entraînement:  37%|███▋      | 3663/10000 [11:45<20:07,  5.25step/s, loss=0.053655, elapsed=11.8min]

Entraînement:  37%|███▋      | 3664/10000 [11:45<20:03,  5.26step/s, loss=0.053655, elapsed=11.8min]

Entraînement:  37%|███▋      | 3664/10000 [11:45<20:03,  5.26step/s, loss=0.084154, elapsed=11.8min]

Entraînement:  37%|███▋      | 3665/10000 [11:45<20:04,  5.26step/s, loss=0.084154, elapsed=11.8min]

Entraînement:  37%|███▋      | 3665/10000 [11:45<20:04,  5.26step/s, loss=0.047428, elapsed=11.8min]

Entraînement:  37%|███▋      | 3666/10000 [11:45<20:01,  5.27step/s, loss=0.047428, elapsed=11.8min]

Entraînement:  37%|███▋      | 3666/10000 [11:45<20:01,  5.27step/s, loss=0.032214, elapsed=11.8min]

Entraînement:  37%|███▋      | 3667/10000 [11:45<19:58,  5.28step/s, loss=0.032214, elapsed=11.8min]

Entraînement:  37%|███▋      | 3667/10000 [11:45<19:58,  5.28step/s, loss=0.073000, elapsed=11.8min]

Entraînement:  37%|███▋      | 3668/10000 [11:46<20:12,  5.22step/s, loss=0.073000, elapsed=11.8min]

Entraînement:  37%|███▋      | 3668/10000 [11:46<20:12,  5.22step/s, loss=0.034405, elapsed=11.8min]

Entraînement:  37%|███▋      | 3669/10000 [11:46<20:08,  5.24step/s, loss=0.034405, elapsed=11.8min]

Entraînement:  37%|███▋      | 3669/10000 [11:46<20:08,  5.24step/s, loss=0.050453, elapsed=11.8min]

Entraînement:  37%|███▋      | 3670/10000 [11:46<19:58,  5.28step/s, loss=0.050453, elapsed=11.8min]

Entraînement:  37%|███▋      | 3670/10000 [11:46<19:58,  5.28step/s, loss=0.023890, elapsed=11.8min]

Entraînement:  37%|███▋      | 3671/10000 [11:46<19:57,  5.28step/s, loss=0.023890, elapsed=11.8min]

Entraînement:  37%|███▋      | 3671/10000 [11:46<19:57,  5.28step/s, loss=0.072282, elapsed=11.8min]

Entraînement:  37%|███▋      | 3672/10000 [11:46<20:00,  5.27step/s, loss=0.072282, elapsed=11.8min]

Entraînement:  37%|███▋      | 3672/10000 [11:46<20:00,  5.27step/s, loss=0.059883, elapsed=11.8min]

Entraînement:  37%|███▋      | 3673/10000 [11:47<19:59,  5.28step/s, loss=0.059883, elapsed=11.8min]

Entraînement:  37%|███▋      | 3673/10000 [11:47<19:59,  5.28step/s, loss=0.029707, elapsed=11.8min]

Entraînement:  37%|███▋      | 3674/10000 [11:47<19:56,  5.29step/s, loss=0.029707, elapsed=11.8min]

Entraînement:  37%|███▋      | 3674/10000 [11:47<19:56,  5.29step/s, loss=0.114220, elapsed=11.8min]

Entraînement:  37%|███▋      | 3675/10000 [11:47<19:57,  5.28step/s, loss=0.114220, elapsed=11.8min]

Entraînement:  37%|███▋      | 3675/10000 [11:47<19:57,  5.28step/s, loss=0.039575, elapsed=11.8min]

Entraînement:  37%|███▋      | 3676/10000 [11:47<19:57,  5.28step/s, loss=0.039575, elapsed=11.8min]

Entraînement:  37%|███▋      | 3676/10000 [11:47<19:57,  5.28step/s, loss=0.115402, elapsed=11.8min]

Entraînement:  37%|███▋      | 3677/10000 [11:47<19:57,  5.28step/s, loss=0.115402, elapsed=11.8min]

Entraînement:  37%|███▋      | 3677/10000 [11:47<19:57,  5.28step/s, loss=0.064334, elapsed=11.8min]

Entraînement:  37%|███▋      | 3678/10000 [11:48<19:55,  5.29step/s, loss=0.064334, elapsed=11.8min]

Entraînement:  37%|███▋      | 3678/10000 [11:48<19:55,  5.29step/s, loss=0.046433, elapsed=11.8min]

Entraînement:  37%|███▋      | 3679/10000 [11:48<19:55,  5.29step/s, loss=0.046433, elapsed=11.8min]

Entraînement:  37%|███▋      | 3679/10000 [11:48<19:55,  5.29step/s, loss=0.034359, elapsed=11.8min]

Entraînement:  37%|███▋      | 3680/10000 [11:48<19:58,  5.27step/s, loss=0.034359, elapsed=11.8min]

Entraînement:  37%|███▋      | 3680/10000 [11:48<19:58,  5.27step/s, loss=0.048316, elapsed=11.8min]

Entraînement:  37%|███▋      | 3681/10000 [11:48<19:59,  5.27step/s, loss=0.048316, elapsed=11.8min]

Entraînement:  37%|███▋      | 3681/10000 [11:48<19:59,  5.27step/s, loss=0.105059, elapsed=11.8min]

Entraînement:  37%|███▋      | 3682/10000 [11:48<20:02,  5.26step/s, loss=0.105059, elapsed=11.8min]

Entraînement:  37%|███▋      | 3682/10000 [11:48<20:02,  5.26step/s, loss=0.064298, elapsed=11.8min]

Entraînement:  37%|███▋      | 3683/10000 [11:48<20:00,  5.26step/s, loss=0.064298, elapsed=11.8min]

Entraînement:  37%|███▋      | 3683/10000 [11:48<20:00,  5.26step/s, loss=0.036349, elapsed=11.8min]

Entraînement:  37%|███▋      | 3684/10000 [11:49<19:58,  5.27step/s, loss=0.036349, elapsed=11.8min]

Entraînement:  37%|███▋      | 3684/10000 [11:49<19:58,  5.27step/s, loss=0.036579, elapsed=11.8min]

Entraînement:  37%|███▋      | 3685/10000 [11:49<19:58,  5.27step/s, loss=0.036579, elapsed=11.8min]

Entraînement:  37%|███▋      | 3685/10000 [11:49<19:58,  5.27step/s, loss=0.039524, elapsed=11.8min]

Entraînement:  37%|███▋      | 3686/10000 [11:49<19:56,  5.28step/s, loss=0.039524, elapsed=11.8min]

Entraînement:  37%|███▋      | 3686/10000 [11:49<19:56,  5.28step/s, loss=0.047028, elapsed=11.8min]

Entraînement:  37%|███▋      | 3687/10000 [11:49<19:54,  5.29step/s, loss=0.047028, elapsed=11.8min]

Entraînement:  37%|███▋      | 3687/10000 [11:49<19:54,  5.29step/s, loss=0.072395, elapsed=11.8min]

Entraînement:  37%|███▋      | 3688/10000 [11:49<19:54,  5.28step/s, loss=0.072395, elapsed=11.8min]

Entraînement:  37%|███▋      | 3688/10000 [11:49<19:54,  5.28step/s, loss=0.057255, elapsed=11.8min]

Entraînement:  37%|███▋      | 3689/10000 [11:50<19:57,  5.27step/s, loss=0.057255, elapsed=11.8min]

Entraînement:  37%|███▋      | 3689/10000 [11:50<19:57,  5.27step/s, loss=0.188830, elapsed=11.8min]

Entraînement:  37%|███▋      | 3690/10000 [11:50<20:00,  5.25step/s, loss=0.188830, elapsed=11.8min]

Entraînement:  37%|███▋      | 3690/10000 [11:50<20:00,  5.25step/s, loss=0.071343, elapsed=11.8min]

Entraînement:  37%|███▋      | 3691/10000 [11:50<19:59,  5.26step/s, loss=0.071343, elapsed=11.8min]

Entraînement:  37%|███▋      | 3691/10000 [11:50<19:59,  5.26step/s, loss=0.037315, elapsed=11.8min]

Entraînement:  37%|███▋      | 3692/10000 [11:50<20:00,  5.25step/s, loss=0.037315, elapsed=11.8min]

Entraînement:  37%|███▋      | 3692/10000 [11:50<20:00,  5.25step/s, loss=0.027251, elapsed=11.8min]

Entraînement:  37%|███▋      | 3693/10000 [11:50<19:58,  5.26step/s, loss=0.027251, elapsed=11.8min]

Entraînement:  37%|███▋      | 3693/10000 [11:50<19:58,  5.26step/s, loss=0.024170, elapsed=11.8min]

Entraînement:  37%|███▋      | 3694/10000 [11:51<19:56,  5.27step/s, loss=0.024170, elapsed=11.8min]

Entraînement:  37%|███▋      | 3694/10000 [11:51<19:56,  5.27step/s, loss=0.115949, elapsed=11.9min]

Entraînement:  37%|███▋      | 3695/10000 [11:51<19:53,  5.28step/s, loss=0.115949, elapsed=11.9min]

Entraînement:  37%|███▋      | 3695/10000 [11:51<19:53,  5.28step/s, loss=0.032434, elapsed=11.9min]

Entraînement:  37%|███▋      | 3696/10000 [11:51<19:54,  5.28step/s, loss=0.032434, elapsed=11.9min]

Entraînement:  37%|███▋      | 3696/10000 [11:51<19:54,  5.28step/s, loss=0.056848, elapsed=11.9min]

Entraînement:  37%|███▋      | 3697/10000 [11:51<19:55,  5.27step/s, loss=0.056848, elapsed=11.9min]

Entraînement:  37%|███▋      | 3697/10000 [11:51<19:55,  5.27step/s, loss=0.050875, elapsed=11.9min]

Entraînement:  37%|███▋      | 3698/10000 [11:51<19:54,  5.27step/s, loss=0.050875, elapsed=11.9min]

Entraînement:  37%|███▋      | 3698/10000 [11:51<19:54,  5.27step/s, loss=0.052989, elapsed=11.9min]

Entraînement:  37%|███▋      | 3699/10000 [11:51<19:52,  5.28step/s, loss=0.052989, elapsed=11.9min]

Entraînement:  37%|███▋      | 3699/10000 [11:51<19:52,  5.28step/s, loss=0.131895, elapsed=11.9min]

Entraînement:  37%|███▋      | 3700/10000 [11:52<19:52,  5.28step/s, loss=0.131895, elapsed=11.9min]

Entraînement:  37%|███▋      | 3700/10000 [11:52<19:52,  5.28step/s, loss=0.039061, elapsed=11.9min]

Entraînement:  37%|███▋      | 3700/10000 [11:52<19:52,  5.28step/s, loss=0.039061, elapsed=11.9min]

Entraînement:  37%|███▋      | 3701/10000 [11:52<20:06,  5.22step/s, loss=0.039061, elapsed=11.9min]

Entraînement:  37%|███▋      | 3701/10000 [11:52<20:06,  5.22step/s, loss=0.046027, elapsed=11.9min]

Step 3700/10000 | Train loss: 0.039061 | Elapsed: 11.9min | ETA: 20.2min

Entraînement:  37%|███▋      | 3702/10000 [11:52<20:04,  5.23step/s, loss=0.046027, elapsed=11.9min]

Entraînement:  37%|███▋      | 3702/10000 [11:52<20:04,  5.23step/s, loss=0.141326, elapsed=11.9min]

Entraînement:  37%|███▋      | 3703/10000 [11:52<20:00,  5.25step/s, loss=0.141326, elapsed=11.9min]

Entraînement:  37%|███▋      | 3703/10000 [11:52<20:00,  5.25step/s, loss=0.035505, elapsed=11.9min]

Entraînement:  37%|███▋      | 3704/10000 [11:52<19:57,  5.26step/s, loss=0.035505, elapsed=11.9min]

Entraînement:  37%|███▋      | 3704/10000 [11:52<19:57,  5.26step/s, loss=0.029938, elapsed=11.9min]

Entraînement:  37%|███▋      | 3705/10000 [11:53<19:55,  5.27step/s, loss=0.029938, elapsed=11.9min]

Entraînement:  37%|███▋      | 3705/10000 [11:53<19:55,  5.27step/s, loss=0.046059, elapsed=11.9min]

Entraînement:  37%|███▋      | 3706/10000 [11:53<19:56,  5.26step/s, loss=0.046059, elapsed=11.9min]

Entraînement:  37%|███▋      | 3706/10000 [11:53<19:56,  5.26step/s, loss=0.049340, elapsed=11.9min]

Entraînement:  37%|███▋      | 3707/10000 [11:53<19:55,  5.26step/s, loss=0.049340, elapsed=11.9min]

Entraînement:  37%|███▋      | 3707/10000 [11:53<19:55,  5.26step/s, loss=0.045645, elapsed=11.9min]

Entraînement:  37%|███▋      | 3708/10000 [11:53<19:55,  5.26step/s, loss=0.045645, elapsed=11.9min]

Entraînement:  37%|███▋      | 3708/10000 [11:53<19:55,  5.26step/s, loss=0.066715, elapsed=11.9min]

Entraînement:  37%|███▋      | 3709/10000 [11:53<19:55,  5.26step/s, loss=0.066715, elapsed=11.9min]

Entraînement:  37%|███▋      | 3709/10000 [11:53<19:55,  5.26step/s, loss=0.037834, elapsed=11.9min]

Entraînement:  37%|███▋      | 3710/10000 [11:54<19:56,  5.26step/s, loss=0.037834, elapsed=11.9min]

Entraînement:  37%|███▋      | 3710/10000 [11:54<19:56,  5.26step/s, loss=0.055396, elapsed=11.9min]

Entraînement:  37%|███▋      | 3711/10000 [11:54<19:55,  5.26step/s, loss=0.055396, elapsed=11.9min]

Entraînement:  37%|███▋      | 3711/10000 [11:54<19:55,  5.26step/s, loss=0.101157, elapsed=11.9min]

Entraînement:  37%|███▋      | 3712/10000 [11:54<19:54,  5.27step/s, loss=0.101157, elapsed=11.9min]

Entraînement:  37%|███▋      | 3712/10000 [11:54<19:54,  5.27step/s, loss=0.101409, elapsed=11.9min]

Entraînement:  37%|███▋      | 3713/10000 [11:54<19:56,  5.25step/s, loss=0.101409, elapsed=11.9min]

Entraînement:  37%|███▋      | 3713/10000 [11:54<19:56,  5.25step/s, loss=0.090715, elapsed=11.9min]

Entraînement:  37%|███▋      | 3714/10000 [11:54<19:58,  5.24step/s, loss=0.090715, elapsed=11.9min]

Entraînement:  37%|███▋      | 3714/10000 [11:54<19:58,  5.24step/s, loss=0.044478, elapsed=11.9min]

Entraînement:  37%|███▋      | 3715/10000 [11:55<19:56,  5.25step/s, loss=0.044478, elapsed=11.9min]

Entraînement:  37%|███▋      | 3715/10000 [11:55<19:56,  5.25step/s, loss=0.030921, elapsed=11.9min]

Entraînement:  37%|███▋      | 3716/10000 [11:55<19:53,  5.27step/s, loss=0.030921, elapsed=11.9min]

Entraînement:  37%|███▋      | 3716/10000 [11:55<19:53,  5.27step/s, loss=0.038398, elapsed=11.9min]

Entraînement:  37%|███▋      | 3717/10000 [11:55<19:50,  5.28step/s, loss=0.038398, elapsed=11.9min]

Entraînement:  37%|███▋      | 3717/10000 [11:55<19:50,  5.28step/s, loss=0.094956, elapsed=11.9min]

Entraînement:  37%|███▋      | 3718/10000 [11:55<19:51,  5.27step/s, loss=0.094956, elapsed=11.9min]

Entraînement:  37%|███▋      | 3718/10000 [11:55<19:51,  5.27step/s, loss=0.063442, elapsed=11.9min]

Entraînement:  37%|███▋      | 3719/10000 [11:55<19:48,  5.28step/s, loss=0.063442, elapsed=11.9min]

Entraînement:  37%|███▋      | 3719/10000 [11:55<19:48,  5.28step/s, loss=0.045553, elapsed=11.9min]

Entraînement:  37%|███▋      | 3720/10000 [11:55<19:45,  5.30step/s, loss=0.045553, elapsed=11.9min]

Entraînement:  37%|███▋      | 3720/10000 [11:55<19:45,  5.30step/s, loss=0.073640, elapsed=11.9min]

Entraînement:  37%|███▋      | 3721/10000 [11:56<19:45,  5.30step/s, loss=0.073640, elapsed=11.9min]

Entraînement:  37%|███▋      | 3721/10000 [11:56<19:45,  5.30step/s, loss=0.023177, elapsed=11.9min]

Entraînement:  37%|███▋      | 3722/10000 [11:56<19:47,  5.29step/s, loss=0.023177, elapsed=11.9min]

Entraînement:  37%|███▋      | 3722/10000 [11:56<19:47,  5.29step/s, loss=0.068722, elapsed=11.9min]

Entraînement:  37%|███▋      | 3723/10000 [11:56<19:48,  5.28step/s, loss=0.068722, elapsed=11.9min]

Entraînement:  37%|███▋      | 3723/10000 [11:56<19:48,  5.28step/s, loss=0.044275, elapsed=11.9min]

Entraînement:  37%|███▋      | 3724/10000 [11:56<19:47,  5.28step/s, loss=0.044275, elapsed=11.9min]

Entraînement:  37%|███▋      | 3724/10000 [11:56<19:47,  5.28step/s, loss=0.063667, elapsed=11.9min]

Entraînement:  37%|███▋      | 3725/10000 [11:56<19:45,  5.29step/s, loss=0.063667, elapsed=11.9min]

Entraînement:  37%|███▋      | 3725/10000 [11:56<19:45,  5.29step/s, loss=0.035212, elapsed=11.9min]

Entraînement:  37%|███▋      | 3726/10000 [11:57<19:46,  5.29step/s, loss=0.035212, elapsed=11.9min]

Entraînement:  37%|███▋      | 3726/10000 [11:57<19:46,  5.29step/s, loss=0.092685, elapsed=12.0min]

Entraînement:  37%|███▋      | 3727/10000 [11:57<19:45,  5.29step/s, loss=0.092685, elapsed=12.0min]

Entraînement:  37%|███▋      | 3727/10000 [11:57<19:45,  5.29step/s, loss=0.131506, elapsed=12.0min]

Entraînement:  37%|███▋      | 3728/10000 [11:57<19:45,  5.29step/s, loss=0.131506, elapsed=12.0min]

Entraînement:  37%|███▋      | 3728/10000 [11:57<19:45,  5.29step/s, loss=0.055969, elapsed=12.0min]

Entraînement:  37%|███▋      | 3729/10000 [11:57<19:45,  5.29step/s, loss=0.055969, elapsed=12.0min]

Entraînement:  37%|███▋      | 3729/10000 [11:57<19:45,  5.29step/s, loss=0.074502, elapsed=12.0min]

Entraînement:  37%|███▋      | 3730/10000 [11:57<19:50,  5.27step/s, loss=0.074502, elapsed=12.0min]

Entraînement:  37%|███▋      | 3730/10000 [11:57<19:50,  5.27step/s, loss=0.058516, elapsed=12.0min]

Entraînement:  37%|███▋      | 3731/10000 [11:58<19:49,  5.27step/s, loss=0.058516, elapsed=12.0min]

Entraînement:  37%|███▋      | 3731/10000 [11:58<19:49,  5.27step/s, loss=0.045511, elapsed=12.0min]

Entraînement:  37%|███▋      | 3732/10000 [11:58<19:49,  5.27step/s, loss=0.045511, elapsed=12.0min]

Entraînement:  37%|███▋      | 3732/10000 [11:58<19:49,  5.27step/s, loss=0.039260, elapsed=12.0min]

Entraînement:  37%|███▋      | 3733/10000 [11:58<19:49,  5.27step/s, loss=0.039260, elapsed=12.0min]

Entraînement:  37%|███▋      | 3733/10000 [11:58<19:49,  5.27step/s, loss=0.078159, elapsed=12.0min]

Entraînement:  37%|███▋      | 3734/10000 [11:58<19:48,  5.27step/s, loss=0.078159, elapsed=12.0min]

Entraînement:  37%|███▋      | 3734/10000 [11:58<19:48,  5.27step/s, loss=0.044391, elapsed=12.0min]

Entraînement:  37%|███▋      | 3735/10000 [11:58<19:51,  5.26step/s, loss=0.044391, elapsed=12.0min]

Entraînement:  37%|███▋      | 3735/10000 [11:58<19:51,  5.26step/s, loss=0.048977, elapsed=12.0min]

Entraînement:  37%|███▋      | 3736/10000 [11:59<19:50,  5.26step/s, loss=0.048977, elapsed=12.0min]

Entraînement:  37%|███▋      | 3736/10000 [11:59<19:50,  5.26step/s, loss=0.029819, elapsed=12.0min]

Entraînement:  37%|███▋      | 3737/10000 [11:59<19:53,  5.25step/s, loss=0.029819, elapsed=12.0min]

Entraînement:  37%|███▋      | 3737/10000 [11:59<19:53,  5.25step/s, loss=0.042049, elapsed=12.0min]

Entraînement:  37%|███▋      | 3738/10000 [11:59<19:53,  5.25step/s, loss=0.042049, elapsed=12.0min]

Entraînement:  37%|███▋      | 3738/10000 [11:59<19:53,  5.25step/s, loss=0.057526, elapsed=12.0min]

Entraînement:  37%|███▋      | 3739/10000 [11:59<19:47,  5.27step/s, loss=0.057526, elapsed=12.0min]

Entraînement:  37%|███▋      | 3739/10000 [11:59<19:47,  5.27step/s, loss=0.032697, elapsed=12.0min]

Entraînement:  37%|███▋      | 3740/10000 [11:59<19:47,  5.27step/s, loss=0.032697, elapsed=12.0min]

Entraînement:  37%|███▋      | 3740/10000 [11:59<19:47,  5.27step/s, loss=0.048713, elapsed=12.0min]

Entraînement:  37%|███▋      | 3741/10000 [11:59<19:47,  5.27step/s, loss=0.048713, elapsed=12.0min]

Entraînement:  37%|███▋      | 3741/10000 [11:59<19:47,  5.27step/s, loss=0.050261, elapsed=12.0min]

Entraînement:  37%|███▋      | 3742/10000 [12:00<19:49,  5.26step/s, loss=0.050261, elapsed=12.0min]

Entraînement:  37%|███▋      | 3742/10000 [12:00<19:49,  5.26step/s, loss=0.039810, elapsed=12.0min]

Entraînement:  37%|███▋      | 3743/10000 [12:00<19:48,  5.27step/s, loss=0.039810, elapsed=12.0min]

Entraînement:  37%|███▋      | 3743/10000 [12:00<19:48,  5.27step/s, loss=0.052066, elapsed=12.0min]

Entraînement:  37%|███▋      | 3744/10000 [12:00<19:50,  5.25step/s, loss=0.052066, elapsed=12.0min]

Entraînement:  37%|███▋      | 3744/10000 [12:00<19:50,  5.25step/s, loss=0.131244, elapsed=12.0min]

Entraînement:  37%|███▋      | 3745/10000 [12:00<19:51,  5.25step/s, loss=0.131244, elapsed=12.0min]

Entraînement:  37%|███▋      | 3745/10000 [12:00<19:51,  5.25step/s, loss=0.052403, elapsed=12.0min]

Entraînement:  37%|███▋      | 3746/10000 [12:00<19:52,  5.24step/s, loss=0.052403, elapsed=12.0min]

Entraînement:  37%|███▋      | 3746/10000 [12:00<19:52,  5.24step/s, loss=0.029616, elapsed=12.0min]

Entraînement:  37%|███▋      | 3747/10000 [12:01<19:51,  5.25step/s, loss=0.029616, elapsed=12.0min]

Entraînement:  37%|███▋      | 3747/10000 [12:01<19:51,  5.25step/s, loss=0.027580, elapsed=12.0min]

Entraînement:  37%|███▋      | 3748/10000 [12:01<19:53,  5.24step/s, loss=0.027580, elapsed=12.0min]

Entraînement:  37%|███▋      | 3748/10000 [12:01<19:53,  5.24step/s, loss=0.090727, elapsed=12.0min]

Entraînement:  37%|███▋      | 3749/10000 [12:01<19:54,  5.23step/s, loss=0.090727, elapsed=12.0min]

Entraînement:  37%|███▋      | 3749/10000 [12:01<19:54,  5.23step/s, loss=0.028121, elapsed=12.0min]

Entraînement:  38%|███▊      | 3750/10000 [12:01<19:52,  5.24step/s, loss=0.028121, elapsed=12.0min]

Entraînement:  38%|███▊      | 3750/10000 [12:01<19:52,  5.24step/s, loss=0.081305, elapsed=12.0min]

Entraînement:  38%|███▊      | 3751/10000 [12:01<19:50,  5.25step/s, loss=0.081305, elapsed=12.0min]

Entraînement:  38%|███▊      | 3751/10000 [12:01<19:50,  5.25step/s, loss=0.029478, elapsed=12.0min]

Entraînement:  38%|███▊      | 3752/10000 [12:02<19:51,  5.24step/s, loss=0.029478, elapsed=12.0min]

Entraînement:  38%|███▊      | 3752/10000 [12:02<19:51,  5.24step/s, loss=0.037818, elapsed=12.0min]

Entraînement:  38%|███▊      | 3753/10000 [12:02<19:55,  5.23step/s, loss=0.037818, elapsed=12.0min]

Entraînement:  38%|███▊      | 3753/10000 [12:02<19:55,  5.23step/s, loss=0.051545, elapsed=12.0min]

Entraînement:  38%|███▊      | 3754/10000 [12:02<19:54,  5.23step/s, loss=0.051545, elapsed=12.0min]

Entraînement:  38%|███▊      | 3754/10000 [12:02<19:54,  5.23step/s, loss=0.070467, elapsed=12.0min]

Entraînement:  38%|███▊      | 3755/10000 [12:02<19:52,  5.24step/s, loss=0.070467, elapsed=12.0min]

Entraînement:  38%|███▊      | 3755/10000 [12:02<19:52,  5.24step/s, loss=0.041556, elapsed=12.0min]

Entraînement:  38%|███▊      | 3756/10000 [12:02<19:53,  5.23step/s, loss=0.041556, elapsed=12.0min]

Entraînement:  38%|███▊      | 3756/10000 [12:02<19:53,  5.23step/s, loss=0.124032, elapsed=12.0min]

Entraînement:  38%|███▊      | 3757/10000 [12:03<19:51,  5.24step/s, loss=0.124032, elapsed=12.0min]

Entraînement:  38%|███▊      | 3757/10000 [12:03<19:51,  5.24step/s, loss=0.044180, elapsed=12.1min]

Entraînement:  38%|███▊      | 3758/10000 [12:03<19:50,  5.24step/s, loss=0.044180, elapsed=12.1min]

Entraînement:  38%|███▊      | 3758/10000 [12:03<19:50,  5.24step/s, loss=0.053303, elapsed=12.1min]

Entraînement:  38%|███▊      | 3759/10000 [12:03<19:50,  5.24step/s, loss=0.053303, elapsed=12.1min]

Entraînement:  38%|███▊      | 3759/10000 [12:03<19:50,  5.24step/s, loss=0.083288, elapsed=12.1min]

Entraînement:  38%|███▊      | 3760/10000 [12:03<19:49,  5.24step/s, loss=0.083288, elapsed=12.1min]

Entraînement:  38%|███▊      | 3760/10000 [12:03<19:49,  5.24step/s, loss=0.041587, elapsed=12.1min]

Entraînement:  38%|███▊      | 3761/10000 [12:03<19:50,  5.24step/s, loss=0.041587, elapsed=12.1min]

Entraînement:  38%|███▊      | 3761/10000 [12:03<19:50,  5.24step/s, loss=0.058892, elapsed=12.1min]

Entraînement:  38%|███▊      | 3762/10000 [12:03<19:48,  5.25step/s, loss=0.058892, elapsed=12.1min]

Entraînement:  38%|███▊      | 3762/10000 [12:03<19:48,  5.25step/s, loss=0.088292, elapsed=12.1min]

Entraînement:  38%|███▊      | 3763/10000 [12:04<19:48,  5.25step/s, loss=0.088292, elapsed=12.1min]

Entraînement:  38%|███▊      | 3763/10000 [12:04<19:48,  5.25step/s, loss=0.035326, elapsed=12.1min]

Entraînement:  38%|███▊      | 3764/10000 [12:04<19:47,  5.25step/s, loss=0.035326, elapsed=12.1min]

Entraînement:  38%|███▊      | 3764/10000 [12:04<19:47,  5.25step/s, loss=0.098363, elapsed=12.1min]

Entraînement:  38%|███▊      | 3765/10000 [12:04<19:46,  5.25step/s, loss=0.098363, elapsed=12.1min]

Entraînement:  38%|███▊      | 3765/10000 [12:04<19:46,  5.25step/s, loss=0.038242, elapsed=12.1min]

Entraînement:  38%|███▊      | 3766/10000 [12:04<19:46,  5.25step/s, loss=0.038242, elapsed=12.1min]

Entraînement:  38%|███▊      | 3766/10000 [12:04<19:46,  5.25step/s, loss=0.104676, elapsed=12.1min]

Entraînement:  38%|███▊      | 3767/10000 [12:04<19:50,  5.24step/s, loss=0.104676, elapsed=12.1min]

Entraînement:  38%|███▊      | 3767/10000 [12:04<19:50,  5.24step/s, loss=0.088700, elapsed=12.1min]

Entraînement:  38%|███▊      | 3768/10000 [12:05<19:49,  5.24step/s, loss=0.088700, elapsed=12.1min]

Entraînement:  38%|███▊      | 3768/10000 [12:05<19:49,  5.24step/s, loss=0.038265, elapsed=12.1min]

Entraînement:  38%|███▊      | 3769/10000 [12:05<19:49,  5.24step/s, loss=0.038265, elapsed=12.1min]

Entraînement:  38%|███▊      | 3769/10000 [12:05<19:49,  5.24step/s, loss=0.154400, elapsed=12.1min]

Entraînement:  38%|███▊      | 3770/10000 [12:05<19:48,  5.24step/s, loss=0.154400, elapsed=12.1min]

Entraînement:  38%|███▊      | 3770/10000 [12:05<19:48,  5.24step/s, loss=0.038256, elapsed=12.1min]

Entraînement:  38%|███▊      | 3771/10000 [12:05<19:48,  5.24step/s, loss=0.038256, elapsed=12.1min]

Entraînement:  38%|███▊      | 3771/10000 [12:05<19:48,  5.24step/s, loss=0.043565, elapsed=12.1min]

Entraînement:  38%|███▊      | 3772/10000 [12:05<19:45,  5.25step/s, loss=0.043565, elapsed=12.1min]

Entraînement:  38%|███▊      | 3772/10000 [12:05<19:45,  5.25step/s, loss=0.035704, elapsed=12.1min]

Entraînement:  38%|███▊      | 3773/10000 [12:06<19:46,  5.25step/s, loss=0.035704, elapsed=12.1min]

Entraînement:  38%|███▊      | 3773/10000 [12:06<19:46,  5.25step/s, loss=0.055608, elapsed=12.1min]

Entraînement:  38%|███▊      | 3774/10000 [12:06<19:46,  5.25step/s, loss=0.055608, elapsed=12.1min]

Entraînement:  38%|███▊      | 3774/10000 [12:06<19:46,  5.25step/s, loss=0.055473, elapsed=12.1min]

Entraînement:  38%|███▊      | 3775/10000 [12:06<19:48,  5.24step/s, loss=0.055473, elapsed=12.1min]

Entraînement:  38%|███▊      | 3775/10000 [12:06<19:48,  5.24step/s, loss=0.132237, elapsed=12.1min]

Entraînement:  38%|███▊      | 3776/10000 [12:06<19:52,  5.22step/s, loss=0.132237, elapsed=12.1min]

Entraînement:  38%|███▊      | 3776/10000 [12:06<19:52,  5.22step/s, loss=0.112151, elapsed=12.1min]

Entraînement:  38%|███▊      | 3777/10000 [12:06<19:44,  5.25step/s, loss=0.112151, elapsed=12.1min]

Entraînement:  38%|███▊      | 3777/10000 [12:06<19:44,  5.25step/s, loss=0.031626, elapsed=12.1min]

Entraînement:  38%|███▊      | 3778/10000 [12:07<19:37,  5.28step/s, loss=0.031626, elapsed=12.1min]

Entraînement:  38%|███▊      | 3778/10000 [12:07<19:37,  5.28step/s, loss=0.067524, elapsed=12.1min]

Entraînement:  38%|███▊      | 3779/10000 [12:07<19:32,  5.31step/s, loss=0.067524, elapsed=12.1min]

Entraînement:  38%|███▊      | 3779/10000 [12:07<19:32,  5.31step/s, loss=0.038972, elapsed=12.1min]

Entraînement:  38%|███▊      | 3780/10000 [12:07<19:28,  5.32step/s, loss=0.038972, elapsed=12.1min]

Entraînement:  38%|███▊      | 3780/10000 [12:07<19:28,  5.32step/s, loss=0.135993, elapsed=12.1min]

Entraînement:  38%|███▊      | 3781/10000 [12:07<19:26,  5.33step/s, loss=0.135993, elapsed=12.1min]

Entraînement:  38%|███▊      | 3781/10000 [12:07<19:26,  5.33step/s, loss=0.054845, elapsed=12.1min]

Entraînement:  38%|███▊      | 3782/10000 [12:07<19:26,  5.33step/s, loss=0.054845, elapsed=12.1min]

Entraînement:  38%|███▊      | 3782/10000 [12:07<19:26,  5.33step/s, loss=0.039145, elapsed=12.1min]

Entraînement:  38%|███▊      | 3783/10000 [12:07<19:25,  5.33step/s, loss=0.039145, elapsed=12.1min]

Entraînement:  38%|███▊      | 3783/10000 [12:07<19:25,  5.33step/s, loss=0.101543, elapsed=12.1min]

Entraînement:  38%|███▊      | 3784/10000 [12:08<19:25,  5.33step/s, loss=0.101543, elapsed=12.1min]

Entraînement:  38%|███▊      | 3784/10000 [12:08<19:25,  5.33step/s, loss=0.031288, elapsed=12.1min]

Entraînement:  38%|███▊      | 3785/10000 [12:08<19:25,  5.33step/s, loss=0.031288, elapsed=12.1min]

Entraînement:  38%|███▊      | 3785/10000 [12:08<19:25,  5.33step/s, loss=0.024436, elapsed=12.1min]

Entraînement:  38%|███▊      | 3786/10000 [12:08<19:24,  5.34step/s, loss=0.024436, elapsed=12.1min]

Entraînement:  38%|███▊      | 3786/10000 [12:08<19:24,  5.34step/s, loss=0.054197, elapsed=12.1min]

Entraînement:  38%|███▊      | 3787/10000 [12:08<19:26,  5.33step/s, loss=0.054197, elapsed=12.1min]

Entraînement:  38%|███▊      | 3787/10000 [12:08<19:26,  5.33step/s, loss=0.072329, elapsed=12.1min]

Entraînement:  38%|███▊      | 3788/10000 [12:08<19:25,  5.33step/s, loss=0.072329, elapsed=12.1min]

Entraînement:  38%|███▊      | 3788/10000 [12:08<19:25,  5.33step/s, loss=0.030360, elapsed=12.1min]

Entraînement:  38%|███▊      | 3789/10000 [12:09<19:24,  5.34step/s, loss=0.030360, elapsed=12.1min]

Entraînement:  38%|███▊      | 3789/10000 [12:09<19:24,  5.34step/s, loss=0.063360, elapsed=12.2min]

Entraînement:  38%|███▊      | 3790/10000 [12:09<19:28,  5.31step/s, loss=0.063360, elapsed=12.2min]

Entraînement:  38%|███▊      | 3790/10000 [12:09<19:28,  5.31step/s, loss=0.062051, elapsed=12.2min]

Entraînement:  38%|███▊      | 3791/10000 [12:09<19:34,  5.29step/s, loss=0.062051, elapsed=12.2min]

Entraînement:  38%|███▊      | 3791/10000 [12:09<19:34,  5.29step/s, loss=0.044172, elapsed=12.2min]

Entraînement:  38%|███▊      | 3792/10000 [12:09<19:39,  5.26step/s, loss=0.044172, elapsed=12.2min]

Entraînement:  38%|███▊      | 3792/10000 [12:09<19:39,  5.26step/s, loss=0.107127, elapsed=12.2min]

Entraînement:  38%|███▊      | 3793/10000 [12:09<19:38,  5.27step/s, loss=0.107127, elapsed=12.2min]

Entraînement:  38%|███▊      | 3793/10000 [12:09<19:38,  5.27step/s, loss=0.135165, elapsed=12.2min]

Entraînement:  38%|███▊      | 3794/10000 [12:10<19:39,  5.26step/s, loss=0.135165, elapsed=12.2min]

Entraînement:  38%|███▊      | 3794/10000 [12:10<19:39,  5.26step/s, loss=0.060249, elapsed=12.2min]

Entraînement:  38%|███▊      | 3795/10000 [12:10<19:38,  5.27step/s, loss=0.060249, elapsed=12.2min]

Entraînement:  38%|███▊      | 3795/10000 [12:10<19:38,  5.27step/s, loss=0.055855, elapsed=12.2min]

Entraînement:  38%|███▊      | 3796/10000 [12:10<19:39,  5.26step/s, loss=0.055855, elapsed=12.2min]

Entraînement:  38%|███▊      | 3796/10000 [12:10<19:39,  5.26step/s, loss=0.134913, elapsed=12.2min]

Entraînement:  38%|███▊      | 3797/10000 [12:10<19:41,  5.25step/s, loss=0.134913, elapsed=12.2min]

Entraînement:  38%|███▊      | 3797/10000 [12:10<19:41,  5.25step/s, loss=0.031764, elapsed=12.2min]

Entraînement:  38%|███▊      | 3798/10000 [12:10<19:42,  5.24step/s, loss=0.031764, elapsed=12.2min]

Entraînement:  38%|███▊      | 3798/10000 [12:10<19:42,  5.24step/s, loss=0.047260, elapsed=12.2min]

Entraînement:  38%|███▊      | 3799/10000 [12:10<19:42,  5.24step/s, loss=0.047260, elapsed=12.2min]

Entraînement:  38%|███▊      | 3799/10000 [12:10<19:42,  5.24step/s, loss=0.044211, elapsed=12.2min]

Entraînement:  38%|███▊      | 3800/10000 [12:11<19:40,  5.25step/s, loss=0.044211, elapsed=12.2min]

Entraînement:  38%|███▊      | 3800/10000 [12:11<19:40,  5.25step/s, loss=0.045722, elapsed=12.2min]

Entraînement:  38%|███▊      | 3800/10000 [12:11<19:40,  5.25step/s, loss=0.045722, elapsed=12.2min]

Entraînement:  38%|███▊      | 3801/10000 [12:11<19:49,  5.21step/s, loss=0.045722, elapsed=12.2min]

Entraînement:  38%|███▊      | 3801/10000 [12:11<19:49,  5.21step/s, loss=0.025134, elapsed=12.2min]

Step 3800/10000 | Train loss: 0.045722 | Elapsed: 12.2min | ETA: 19.9min

Entraînement:  38%|███▊      | 3802/10000 [12:11<19:46,  5.22step/s, loss=0.025134, elapsed=12.2min]

Entraînement:  38%|███▊      | 3802/10000 [12:11<19:46,  5.22step/s, loss=0.058998, elapsed=12.2min]

Entraînement:  38%|███▊      | 3803/10000 [12:11<19:45,  5.23step/s, loss=0.058998, elapsed=12.2min]

Entraînement:  38%|███▊      | 3803/10000 [12:11<19:45,  5.23step/s, loss=0.057444, elapsed=12.2min]

Entraînement:  38%|███▊      | 3804/10000 [12:11<19:40,  5.25step/s, loss=0.057444, elapsed=12.2min]

Entraînement:  38%|███▊      | 3804/10000 [12:11<19:40,  5.25step/s, loss=0.051475, elapsed=12.2min]

Entraînement:  38%|███▊      | 3805/10000 [12:12<19:37,  5.26step/s, loss=0.051475, elapsed=12.2min]

Entraînement:  38%|███▊      | 3805/10000 [12:12<19:37,  5.26step/s, loss=0.033471, elapsed=12.2min]

Entraînement:  38%|███▊      | 3806/10000 [12:12<19:35,  5.27step/s, loss=0.033471, elapsed=12.2min]

Entraînement:  38%|███▊      | 3806/10000 [12:12<19:35,  5.27step/s, loss=0.052017, elapsed=12.2min]

Entraînement:  38%|███▊      | 3807/10000 [12:12<19:35,  5.27step/s, loss=0.052017, elapsed=12.2min]

Entraînement:  38%|███▊      | 3807/10000 [12:12<19:35,  5.27step/s, loss=0.043454, elapsed=12.2min]

Entraînement:  38%|███▊      | 3808/10000 [12:12<19:35,  5.27step/s, loss=0.043454, elapsed=12.2min]

Entraînement:  38%|███▊      | 3808/10000 [12:12<19:35,  5.27step/s, loss=0.037703, elapsed=12.2min]

Entraînement:  38%|███▊      | 3809/10000 [12:12<19:32,  5.28step/s, loss=0.037703, elapsed=12.2min]

Entraînement:  38%|███▊      | 3809/10000 [12:12<19:32,  5.28step/s, loss=0.096923, elapsed=12.2min]

Entraînement:  38%|███▊      | 3810/10000 [12:13<19:31,  5.28step/s, loss=0.096923, elapsed=12.2min]

Entraînement:  38%|███▊      | 3810/10000 [12:13<19:31,  5.28step/s, loss=0.056577, elapsed=12.2min]

Entraînement:  38%|███▊      | 3811/10000 [12:13<19:30,  5.29step/s, loss=0.056577, elapsed=12.2min]

Entraînement:  38%|███▊      | 3811/10000 [12:13<19:30,  5.29step/s, loss=0.032234, elapsed=12.2min]

Entraînement:  38%|███▊      | 3812/10000 [12:13<19:31,  5.28step/s, loss=0.032234, elapsed=12.2min]

Entraînement:  38%|███▊      | 3812/10000 [12:13<19:31,  5.28step/s, loss=0.060008, elapsed=12.2min]

Entraînement:  38%|███▊      | 3813/10000 [12:13<19:30,  5.29step/s, loss=0.060008, elapsed=12.2min]

Entraînement:  38%|███▊      | 3813/10000 [12:13<19:30,  5.29step/s, loss=0.039863, elapsed=12.2min]

Entraînement:  38%|███▊      | 3814/10000 [12:13<19:31,  5.28step/s, loss=0.039863, elapsed=12.2min]

Entraînement:  38%|███▊      | 3814/10000 [12:13<19:31,  5.28step/s, loss=0.076285, elapsed=12.2min]

Entraînement:  38%|███▊      | 3815/10000 [12:14<19:32,  5.27step/s, loss=0.076285, elapsed=12.2min]

Entraînement:  38%|███▊      | 3815/10000 [12:14<19:32,  5.27step/s, loss=0.093815, elapsed=12.2min]

Entraînement:  38%|███▊      | 3816/10000 [12:14<19:30,  5.28step/s, loss=0.093815, elapsed=12.2min]

Entraînement:  38%|███▊      | 3816/10000 [12:14<19:30,  5.28step/s, loss=0.040932, elapsed=12.2min]

Entraînement:  38%|███▊      | 3817/10000 [12:14<19:32,  5.27step/s, loss=0.040932, elapsed=12.2min]

Entraînement:  38%|███▊      | 3817/10000 [12:14<19:32,  5.27step/s, loss=0.059701, elapsed=12.2min]

Entraînement:  38%|███▊      | 3818/10000 [12:14<19:33,  5.27step/s, loss=0.059701, elapsed=12.2min]

Entraînement:  38%|███▊      | 3818/10000 [12:14<19:33,  5.27step/s, loss=0.088732, elapsed=12.2min]

Entraînement:  38%|███▊      | 3819/10000 [12:14<19:34,  5.26step/s, loss=0.088732, elapsed=12.2min]

Entraînement:  38%|███▊      | 3819/10000 [12:14<19:34,  5.26step/s, loss=0.060023, elapsed=12.2min]

Entraînement:  38%|███▊      | 3820/10000 [12:14<19:33,  5.27step/s, loss=0.060023, elapsed=12.2min]

Entraînement:  38%|███▊      | 3820/10000 [12:14<19:33,  5.27step/s, loss=0.046685, elapsed=12.2min]

Entraînement:  38%|███▊      | 3821/10000 [12:15<19:35,  5.26step/s, loss=0.046685, elapsed=12.2min]

Entraînement:  38%|███▊      | 3821/10000 [12:15<19:35,  5.26step/s, loss=0.037084, elapsed=12.3min]

Entraînement:  38%|███▊      | 3822/10000 [12:15<19:35,  5.26step/s, loss=0.037084, elapsed=12.3min]

Entraînement:  38%|███▊      | 3822/10000 [12:15<19:35,  5.26step/s, loss=0.071469, elapsed=12.3min]

Entraînement:  38%|███▊      | 3823/10000 [12:15<19:36,  5.25step/s, loss=0.071469, elapsed=12.3min]

Entraînement:  38%|███▊      | 3823/10000 [12:15<19:36,  5.25step/s, loss=0.052326, elapsed=12.3min]

Entraînement:  38%|███▊      | 3824/10000 [12:15<19:35,  5.25step/s, loss=0.052326, elapsed=12.3min]

Entraînement:  38%|███▊      | 3824/10000 [12:15<19:35,  5.25step/s, loss=0.050257, elapsed=12.3min]

Entraînement:  38%|███▊      | 3825/10000 [12:15<19:34,  5.26step/s, loss=0.050257, elapsed=12.3min]

Entraînement:  38%|███▊      | 3825/10000 [12:15<19:34,  5.26step/s, loss=0.029614, elapsed=12.3min]

Entraînement:  38%|███▊      | 3826/10000 [12:16<19:34,  5.26step/s, loss=0.029614, elapsed=12.3min]

Entraînement:  38%|███▊      | 3826/10000 [12:16<19:34,  5.26step/s, loss=0.066873, elapsed=12.3min]

Entraînement:  38%|███▊      | 3827/10000 [12:16<19:33,  5.26step/s, loss=0.066873, elapsed=12.3min]

Entraînement:  38%|███▊      | 3827/10000 [12:16<19:33,  5.26step/s, loss=0.032663, elapsed=12.3min]

Entraînement:  38%|███▊      | 3828/10000 [12:16<19:34,  5.26step/s, loss=0.032663, elapsed=12.3min]

Entraînement:  38%|███▊      | 3828/10000 [12:16<19:34,  5.26step/s, loss=0.060566, elapsed=12.3min]

Entraînement:  38%|███▊      | 3829/10000 [12:16<19:34,  5.25step/s, loss=0.060566, elapsed=12.3min]

Entraînement:  38%|███▊      | 3829/10000 [12:16<19:34,  5.25step/s, loss=0.066840, elapsed=12.3min]

Entraînement:  38%|███▊      | 3830/10000 [12:16<19:35,  5.25step/s, loss=0.066840, elapsed=12.3min]

Entraînement:  38%|███▊      | 3830/10000 [12:16<19:35,  5.25step/s, loss=0.032937, elapsed=12.3min]

Entraînement:  38%|███▊      | 3831/10000 [12:17<19:34,  5.25step/s, loss=0.032937, elapsed=12.3min]

Entraînement:  38%|███▊      | 3831/10000 [12:17<19:34,  5.25step/s, loss=0.048429, elapsed=12.3min]

Entraînement:  38%|███▊      | 3832/10000 [12:17<19:34,  5.25step/s, loss=0.048429, elapsed=12.3min]

Entraînement:  38%|███▊      | 3832/10000 [12:17<19:34,  5.25step/s, loss=0.125140, elapsed=12.3min]

Entraînement:  38%|███▊      | 3833/10000 [12:17<19:32,  5.26step/s, loss=0.125140, elapsed=12.3min]

Entraînement:  38%|███▊      | 3833/10000 [12:17<19:32,  5.26step/s, loss=0.055497, elapsed=12.3min]

Entraînement:  38%|███▊      | 3834/10000 [12:17<19:30,  5.27step/s, loss=0.055497, elapsed=12.3min]

Entraînement:  38%|███▊      | 3834/10000 [12:17<19:30,  5.27step/s, loss=0.109616, elapsed=12.3min]

Entraînement:  38%|███▊      | 3835/10000 [12:17<19:34,  5.25step/s, loss=0.109616, elapsed=12.3min]

Entraînement:  38%|███▊      | 3835/10000 [12:17<19:34,  5.25step/s, loss=0.022356, elapsed=12.3min]

Entraînement:  38%|███▊      | 3836/10000 [12:18<19:33,  5.25step/s, loss=0.022356, elapsed=12.3min]

Entraînement:  38%|███▊      | 3836/10000 [12:18<19:33,  5.25step/s, loss=0.026918, elapsed=12.3min]

Entraînement:  38%|███▊      | 3837/10000 [12:18<19:34,  5.25step/s, loss=0.026918, elapsed=12.3min]

Entraînement:  38%|███▊      | 3837/10000 [12:18<19:34,  5.25step/s, loss=0.027808, elapsed=12.3min]

Entraînement:  38%|███▊      | 3838/10000 [12:18<19:30,  5.26step/s, loss=0.027808, elapsed=12.3min]

Entraînement:  38%|███▊      | 3838/10000 [12:18<19:30,  5.26step/s, loss=0.049904, elapsed=12.3min]

Entraînement:  38%|███▊      | 3839/10000 [12:18<19:30,  5.26step/s, loss=0.049904, elapsed=12.3min]

Entraînement:  38%|███▊      | 3839/10000 [12:18<19:30,  5.26step/s, loss=0.048197, elapsed=12.3min]

Entraînement:  38%|███▊      | 3840/10000 [12:18<19:31,  5.26step/s, loss=0.048197, elapsed=12.3min]

Entraînement:  38%|███▊      | 3840/10000 [12:18<19:31,  5.26step/s, loss=0.123582, elapsed=12.3min]

Entraînement:  38%|███▊      | 3841/10000 [12:18<19:31,  5.26step/s, loss=0.123582, elapsed=12.3min]

Entraînement:  38%|███▊      | 3841/10000 [12:18<19:31,  5.26step/s, loss=0.034739, elapsed=12.3min]

Entraînement:  38%|███▊      | 3842/10000 [12:19<19:35,  5.24step/s, loss=0.034739, elapsed=12.3min]

Entraînement:  38%|███▊      | 3842/10000 [12:19<19:35,  5.24step/s, loss=0.063563, elapsed=12.3min]

Entraînement:  38%|███▊      | 3843/10000 [12:19<19:32,  5.25step/s, loss=0.063563, elapsed=12.3min]

Entraînement:  38%|███▊      | 3843/10000 [12:19<19:32,  5.25step/s, loss=0.026675, elapsed=12.3min]

Entraînement:  38%|███▊      | 3844/10000 [12:19<19:32,  5.25step/s, loss=0.026675, elapsed=12.3min]

Entraînement:  38%|███▊      | 3844/10000 [12:19<19:32,  5.25step/s, loss=0.114624, elapsed=12.3min]

Entraînement:  38%|███▊      | 3845/10000 [12:19<19:31,  5.25step/s, loss=0.114624, elapsed=12.3min]

Entraînement:  38%|███▊      | 3845/10000 [12:19<19:31,  5.25step/s, loss=0.040837, elapsed=12.3min]

Entraînement:  38%|███▊      | 3846/10000 [12:19<19:31,  5.25step/s, loss=0.040837, elapsed=12.3min]

Entraînement:  38%|███▊      | 3846/10000 [12:19<19:31,  5.25step/s, loss=0.120011, elapsed=12.3min]

Entraînement:  38%|███▊      | 3847/10000 [12:20<19:27,  5.27step/s, loss=0.120011, elapsed=12.3min]

Entraînement:  38%|███▊      | 3847/10000 [12:20<19:27,  5.27step/s, loss=0.035505, elapsed=12.3min]

Entraînement:  38%|███▊      | 3848/10000 [12:20<19:28,  5.26step/s, loss=0.035505, elapsed=12.3min]

Entraînement:  38%|███▊      | 3848/10000 [12:20<19:28,  5.26step/s, loss=0.043823, elapsed=12.3min]

Entraînement:  38%|███▊      | 3849/10000 [12:20<19:29,  5.26step/s, loss=0.043823, elapsed=12.3min]

Entraînement:  38%|███▊      | 3849/10000 [12:20<19:29,  5.26step/s, loss=0.099691, elapsed=12.3min]

Entraînement:  38%|███▊      | 3850/10000 [12:20<19:30,  5.25step/s, loss=0.099691, elapsed=12.3min]

Entraînement:  38%|███▊      | 3850/10000 [12:20<19:30,  5.25step/s, loss=0.029353, elapsed=12.3min]

Entraînement:  39%|███▊      | 3851/10000 [12:20<19:30,  5.25step/s, loss=0.029353, elapsed=12.3min]

Entraînement:  39%|███▊      | 3851/10000 [12:20<19:30,  5.25step/s, loss=0.111079, elapsed=12.3min]

Entraînement:  39%|███▊      | 3852/10000 [12:21<19:30,  5.25step/s, loss=0.111079, elapsed=12.3min]

Entraînement:  39%|███▊      | 3852/10000 [12:21<19:30,  5.25step/s, loss=0.074769, elapsed=12.4min]

Entraînement:  39%|███▊      | 3853/10000 [12:21<19:31,  5.25step/s, loss=0.074769, elapsed=12.4min]

Entraînement:  39%|███▊      | 3853/10000 [12:21<19:31,  5.25step/s, loss=0.040529, elapsed=12.4min]

Entraînement:  39%|███▊      | 3854/10000 [12:21<19:30,  5.25step/s, loss=0.040529, elapsed=12.4min]

Entraînement:  39%|███▊      | 3854/10000 [12:21<19:30,  5.25step/s, loss=0.056880, elapsed=12.4min]

Entraînement:  39%|███▊      | 3855/10000 [12:21<19:30,  5.25step/s, loss=0.056880, elapsed=12.4min]

Entraînement:  39%|███▊      | 3855/10000 [12:21<19:30,  5.25step/s, loss=0.033501, elapsed=12.4min]

Entraînement:  39%|███▊      | 3856/10000 [12:21<19:28,  5.26step/s, loss=0.033501, elapsed=12.4min]

Entraînement:  39%|███▊      | 3856/10000 [12:21<19:28,  5.26step/s, loss=0.072527, elapsed=12.4min]

Entraînement:  39%|███▊      | 3857/10000 [12:22<19:28,  5.26step/s, loss=0.072527, elapsed=12.4min]

Entraînement:  39%|███▊      | 3857/10000 [12:22<19:28,  5.26step/s, loss=0.040952, elapsed=12.4min]

Entraînement:  39%|███▊      | 3858/10000 [12:22<19:28,  5.26step/s, loss=0.040952, elapsed=12.4min]

Entraînement:  39%|███▊      | 3858/10000 [12:22<19:28,  5.26step/s, loss=0.040998, elapsed=12.4min]

Entraînement:  39%|███▊      | 3859/10000 [12:22<19:30,  5.24step/s, loss=0.040998, elapsed=12.4min]

Entraînement:  39%|███▊      | 3859/10000 [12:22<19:30,  5.24step/s, loss=0.043316, elapsed=12.4min]

Entraînement:  39%|███▊      | 3860/10000 [12:22<19:32,  5.24step/s, loss=0.043316, elapsed=12.4min]

Entraînement:  39%|███▊      | 3860/10000 [12:22<19:32,  5.24step/s, loss=0.034931, elapsed=12.4min]

Entraînement:  39%|███▊      | 3861/10000 [12:22<19:41,  5.20step/s, loss=0.034931, elapsed=12.4min]

Entraînement:  39%|███▊      | 3861/10000 [12:22<19:41,  5.20step/s, loss=0.119704, elapsed=12.4min]

Entraînement:  39%|███▊      | 3862/10000 [12:22<19:35,  5.22step/s, loss=0.119704, elapsed=12.4min]

Entraînement:  39%|███▊      | 3862/10000 [12:22<19:35,  5.22step/s, loss=0.048293, elapsed=12.4min]

Entraînement:  39%|███▊      | 3863/10000 [12:23<19:33,  5.23step/s, loss=0.048293, elapsed=12.4min]

Entraînement:  39%|███▊      | 3863/10000 [12:23<19:33,  5.23step/s, loss=0.070326, elapsed=12.4min]

Entraînement:  39%|███▊      | 3864/10000 [12:23<19:30,  5.24step/s, loss=0.070326, elapsed=12.4min]

Entraînement:  39%|███▊      | 3864/10000 [12:23<19:30,  5.24step/s, loss=0.032629, elapsed=12.4min]

Entraînement:  39%|███▊      | 3865/10000 [12:23<19:29,  5.25step/s, loss=0.032629, elapsed=12.4min]

Entraînement:  39%|███▊      | 3865/10000 [12:23<19:29,  5.25step/s, loss=0.035450, elapsed=12.4min]

Entraînement:  39%|███▊      | 3866/10000 [12:23<19:28,  5.25step/s, loss=0.035450, elapsed=12.4min]

Entraînement:  39%|███▊      | 3866/10000 [12:23<19:28,  5.25step/s, loss=0.061717, elapsed=12.4min]

Entraînement:  39%|███▊      | 3867/10000 [12:23<19:27,  5.25step/s, loss=0.061717, elapsed=12.4min]

Entraînement:  39%|███▊      | 3867/10000 [12:23<19:27,  5.25step/s, loss=0.042997, elapsed=12.4min]

Entraînement:  39%|███▊      | 3868/10000 [12:24<19:26,  5.26step/s, loss=0.042997, elapsed=12.4min]

Entraînement:  39%|███▊      | 3868/10000 [12:24<19:26,  5.26step/s, loss=0.034749, elapsed=12.4min]

Entraînement:  39%|███▊      | 3869/10000 [12:24<19:22,  5.27step/s, loss=0.034749, elapsed=12.4min]

Entraînement:  39%|███▊      | 3869/10000 [12:24<19:22,  5.27step/s, loss=0.037825, elapsed=12.4min]

Entraînement:  39%|███▊      | 3870/10000 [12:24<19:21,  5.28step/s, loss=0.037825, elapsed=12.4min]

Entraînement:  39%|███▊      | 3870/10000 [12:24<19:21,  5.28step/s, loss=0.056105, elapsed=12.4min]

Entraînement:  39%|███▊      | 3871/10000 [12:24<19:21,  5.28step/s, loss=0.056105, elapsed=12.4min]

Entraînement:  39%|███▊      | 3871/10000 [12:24<19:21,  5.28step/s, loss=0.038804, elapsed=12.4min]

Entraînement:  39%|███▊      | 3872/10000 [12:24<19:20,  5.28step/s, loss=0.038804, elapsed=12.4min]

Entraînement:  39%|███▊      | 3872/10000 [12:24<19:20,  5.28step/s, loss=0.074452, elapsed=12.4min]

Entraînement:  39%|███▊      | 3873/10000 [12:25<19:21,  5.28step/s, loss=0.074452, elapsed=12.4min]

Entraînement:  39%|███▊      | 3873/10000 [12:25<19:21,  5.28step/s, loss=0.037270, elapsed=12.4min]

Entraînement:  39%|███▊      | 3874/10000 [12:25<19:21,  5.27step/s, loss=0.037270, elapsed=12.4min]

Entraînement:  39%|███▊      | 3874/10000 [12:25<19:21,  5.27step/s, loss=0.025860, elapsed=12.4min]

Entraînement:  39%|███▉      | 3875/10000 [12:25<19:21,  5.27step/s, loss=0.025860, elapsed=12.4min]

Entraînement:  39%|███▉      | 3875/10000 [12:25<19:21,  5.27step/s, loss=0.052504, elapsed=12.4min]

Entraînement:  39%|███▉      | 3876/10000 [12:25<19:21,  5.27step/s, loss=0.052504, elapsed=12.4min]

Entraînement:  39%|███▉      | 3876/10000 [12:25<19:21,  5.27step/s, loss=0.040869, elapsed=12.4min]

Entraînement:  39%|███▉      | 3877/10000 [12:25<19:20,  5.28step/s, loss=0.040869, elapsed=12.4min]

Entraînement:  39%|███▉      | 3877/10000 [12:25<19:20,  5.28step/s, loss=0.053151, elapsed=12.4min]

Entraînement:  39%|███▉      | 3878/10000 [12:26<19:22,  5.27step/s, loss=0.053151, elapsed=12.4min]

Entraînement:  39%|███▉      | 3878/10000 [12:26<19:22,  5.27step/s, loss=0.084594, elapsed=12.4min]

Entraînement:  39%|███▉      | 3879/10000 [12:26<19:21,  5.27step/s, loss=0.084594, elapsed=12.4min]

Entraînement:  39%|███▉      | 3879/10000 [12:26<19:21,  5.27step/s, loss=0.037054, elapsed=12.4min]

Entraînement:  39%|███▉      | 3880/10000 [12:26<19:21,  5.27step/s, loss=0.037054, elapsed=12.4min]

Entraînement:  39%|███▉      | 3880/10000 [12:26<19:21,  5.27step/s, loss=0.025789, elapsed=12.4min]

Entraînement:  39%|███▉      | 3881/10000 [12:26<19:45,  5.16step/s, loss=0.025789, elapsed=12.4min]

Entraînement:  39%|███▉      | 3881/10000 [12:26<19:45,  5.16step/s, loss=0.053564, elapsed=12.4min]

Entraînement:  39%|███▉      | 3882/10000 [12:26<19:38,  5.19step/s, loss=0.053564, elapsed=12.4min]

Entraînement:  39%|███▉      | 3882/10000 [12:26<19:38,  5.19step/s, loss=0.038785, elapsed=12.4min]

Entraînement:  39%|███▉      | 3883/10000 [12:26<19:34,  5.21step/s, loss=0.038785, elapsed=12.4min]

Entraînement:  39%|███▉      | 3883/10000 [12:26<19:34,  5.21step/s, loss=0.087670, elapsed=12.4min]

Entraînement:  39%|███▉      | 3884/10000 [12:27<19:28,  5.23step/s, loss=0.087670, elapsed=12.4min]

Entraînement:  39%|███▉      | 3884/10000 [12:27<19:28,  5.23step/s, loss=0.048786, elapsed=12.5min]

Entraînement:  39%|███▉      | 3885/10000 [12:27<19:25,  5.25step/s, loss=0.048786, elapsed=12.5min]

Entraînement:  39%|███▉      | 3885/10000 [12:27<19:25,  5.25step/s, loss=0.020647, elapsed=12.5min]

Entraînement:  39%|███▉      | 3886/10000 [12:27<19:22,  5.26step/s, loss=0.020647, elapsed=12.5min]

Entraînement:  39%|███▉      | 3886/10000 [12:27<19:22,  5.26step/s, loss=0.041272, elapsed=12.5min]

Entraînement:  39%|███▉      | 3887/10000 [12:27<19:20,  5.27step/s, loss=0.041272, elapsed=12.5min]

Entraînement:  39%|███▉      | 3887/10000 [12:27<19:20,  5.27step/s, loss=0.030823, elapsed=12.5min]

Entraînement:  39%|███▉      | 3888/10000 [12:27<19:19,  5.27step/s, loss=0.030823, elapsed=12.5min]

Entraînement:  39%|███▉      | 3888/10000 [12:27<19:19,  5.27step/s, loss=0.045676, elapsed=12.5min]

Entraînement:  39%|███▉      | 3889/10000 [12:28<19:17,  5.28step/s, loss=0.045676, elapsed=12.5min]

Entraînement:  39%|███▉      | 3889/10000 [12:28<19:17,  5.28step/s, loss=0.075311, elapsed=12.5min]

Entraînement:  39%|███▉      | 3890/10000 [12:28<19:19,  5.27step/s, loss=0.075311, elapsed=12.5min]

Entraînement:  39%|███▉      | 3890/10000 [12:28<19:19,  5.27step/s, loss=0.023561, elapsed=12.5min]

Entraînement:  39%|███▉      | 3891/10000 [12:28<19:18,  5.27step/s, loss=0.023561, elapsed=12.5min]

Entraînement:  39%|███▉      | 3891/10000 [12:28<19:18,  5.27step/s, loss=0.029004, elapsed=12.5min]

Entraînement:  39%|███▉      | 3892/10000 [12:28<19:22,  5.25step/s, loss=0.029004, elapsed=12.5min]

Entraînement:  39%|███▉      | 3892/10000 [12:28<19:22,  5.25step/s, loss=0.052354, elapsed=12.5min]

Entraînement:  39%|███▉      | 3893/10000 [12:28<19:23,  5.25step/s, loss=0.052354, elapsed=12.5min]

Entraînement:  39%|███▉      | 3893/10000 [12:28<19:23,  5.25step/s, loss=0.126402, elapsed=12.5min]

Entraînement:  39%|███▉      | 3894/10000 [12:29<19:23,  5.25step/s, loss=0.126402, elapsed=12.5min]

Entraînement:  39%|███▉      | 3894/10000 [12:29<19:23,  5.25step/s, loss=0.054442, elapsed=12.5min]

Entraînement:  39%|███▉      | 3895/10000 [12:29<19:24,  5.24step/s, loss=0.054442, elapsed=12.5min]

Entraînement:  39%|███▉      | 3895/10000 [12:29<19:24,  5.24step/s, loss=0.090352, elapsed=12.5min]

Entraînement:  39%|███▉      | 3896/10000 [12:29<19:20,  5.26step/s, loss=0.090352, elapsed=12.5min]

Entraînement:  39%|███▉      | 3896/10000 [12:29<19:20,  5.26step/s, loss=0.122782, elapsed=12.5min]

Entraînement:  39%|███▉      | 3897/10000 [12:29<19:20,  5.26step/s, loss=0.122782, elapsed=12.5min]

Entraînement:  39%|███▉      | 3897/10000 [12:29<19:20,  5.26step/s, loss=0.121922, elapsed=12.5min]

Entraînement:  39%|███▉      | 3898/10000 [12:29<19:20,  5.26step/s, loss=0.121922, elapsed=12.5min]

Entraînement:  39%|███▉      | 3898/10000 [12:29<19:20,  5.26step/s, loss=0.100583, elapsed=12.5min]

Entraînement:  39%|███▉      | 3899/10000 [12:30<19:18,  5.27step/s, loss=0.100583, elapsed=12.5min]

Entraînement:  39%|███▉      | 3899/10000 [12:30<19:18,  5.27step/s, loss=0.058056, elapsed=12.5min]

Entraînement:  39%|███▉      | 3900/10000 [12:30<19:17,  5.27step/s, loss=0.058056, elapsed=12.5min]

Entraînement:  39%|███▉      | 3900/10000 [12:30<19:17,  5.27step/s, loss=0.067032, elapsed=12.5min]

Entraînement:  39%|███▉      | 3900/10000 [12:30<19:17,  5.27step/s, loss=0.067032, elapsed=12.5min]

Entraînement:  39%|███▉      | 3901/10000 [12:30<19:27,  5.22step/s, loss=0.067032, elapsed=12.5min]

Entraînement:  39%|███▉      | 3901/10000 [12:30<19:27,  5.22step/s, loss=0.053154, elapsed=12.5min]

Step 3900/10000 | Train loss: 0.067032 | Elapsed: 12.5min | ETA: 19.6min

Entraînement:  39%|███▉      | 3902/10000 [12:30<19:24,  5.24step/s, loss=0.053154, elapsed=12.5min]

Entraînement:  39%|███▉      | 3902/10000 [12:30<19:24,  5.24step/s, loss=0.092005, elapsed=12.5min]

Entraînement:  39%|███▉      | 3903/10000 [12:30<19:19,  5.26step/s, loss=0.092005, elapsed=12.5min]

Entraînement:  39%|███▉      | 3903/10000 [12:30<19:19,  5.26step/s, loss=0.063656, elapsed=12.5min]

Entraînement:  39%|███▉      | 3904/10000 [12:30<19:18,  5.26step/s, loss=0.063656, elapsed=12.5min]

Entraînement:  39%|███▉      | 3904/10000 [12:30<19:18,  5.26step/s, loss=0.069798, elapsed=12.5min]

Entraînement:  39%|███▉      | 3905/10000 [12:31<19:16,  5.27step/s, loss=0.069798, elapsed=12.5min]

Entraînement:  39%|███▉      | 3905/10000 [12:31<19:16,  5.27step/s, loss=0.048406, elapsed=12.5min]

Entraînement:  39%|███▉      | 3906/10000 [12:31<19:15,  5.28step/s, loss=0.048406, elapsed=12.5min]

Entraînement:  39%|███▉      | 3906/10000 [12:31<19:15,  5.28step/s, loss=0.031712, elapsed=12.5min]

Entraînement:  39%|███▉      | 3907/10000 [12:31<19:13,  5.28step/s, loss=0.031712, elapsed=12.5min]

Entraînement:  39%|███▉      | 3907/10000 [12:31<19:13,  5.28step/s, loss=0.072816, elapsed=12.5min]

Entraînement:  39%|███▉      | 3908/10000 [12:31<19:18,  5.26step/s, loss=0.072816, elapsed=12.5min]

Entraînement:  39%|███▉      | 3908/10000 [12:31<19:18,  5.26step/s, loss=0.069209, elapsed=12.5min]

Entraînement:  39%|███▉      | 3909/10000 [12:31<19:17,  5.26step/s, loss=0.069209, elapsed=12.5min]

Entraînement:  39%|███▉      | 3909/10000 [12:31<19:17,  5.26step/s, loss=0.058429, elapsed=12.5min]

Entraînement:  39%|███▉      | 3910/10000 [12:32<19:18,  5.26step/s, loss=0.058429, elapsed=12.5min]

Entraînement:  39%|███▉      | 3910/10000 [12:32<19:18,  5.26step/s, loss=0.041943, elapsed=12.5min]

Entraînement:  39%|███▉      | 3911/10000 [12:32<19:17,  5.26step/s, loss=0.041943, elapsed=12.5min]

Entraînement:  39%|███▉      | 3911/10000 [12:32<19:17,  5.26step/s, loss=0.071982, elapsed=12.5min]

Entraînement:  39%|███▉      | 3912/10000 [12:32<19:17,  5.26step/s, loss=0.071982, elapsed=12.5min]

Entraînement:  39%|███▉      | 3912/10000 [12:32<19:17,  5.26step/s, loss=0.058576, elapsed=12.5min]

Entraînement:  39%|███▉      | 3913/10000 [12:32<19:17,  5.26step/s, loss=0.058576, elapsed=12.5min]

Entraînement:  39%|███▉      | 3913/10000 [12:32<19:17,  5.26step/s, loss=0.044058, elapsed=12.5min]

Entraînement:  39%|███▉      | 3914/10000 [12:32<19:14,  5.27step/s, loss=0.044058, elapsed=12.5min]

Entraînement:  39%|███▉      | 3914/10000 [12:32<19:14,  5.27step/s, loss=0.030405, elapsed=12.5min]

Entraînement:  39%|███▉      | 3915/10000 [12:33<19:15,  5.27step/s, loss=0.030405, elapsed=12.5min]

Entraînement:  39%|███▉      | 3915/10000 [12:33<19:15,  5.27step/s, loss=0.070687, elapsed=12.6min]

Entraînement:  39%|███▉      | 3916/10000 [12:33<19:14,  5.27step/s, loss=0.070687, elapsed=12.6min]

Entraînement:  39%|███▉      | 3916/10000 [12:33<19:14,  5.27step/s, loss=0.031857, elapsed=12.6min]

Entraînement:  39%|███▉      | 3917/10000 [12:33<19:12,  5.28step/s, loss=0.031857, elapsed=12.6min]

Entraînement:  39%|███▉      | 3917/10000 [12:33<19:12,  5.28step/s, loss=0.106070, elapsed=12.6min]

Entraînement:  39%|███▉      | 3918/10000 [12:33<19:12,  5.28step/s, loss=0.106070, elapsed=12.6min]

Entraînement:  39%|███▉      | 3918/10000 [12:33<19:12,  5.28step/s, loss=0.033858, elapsed=12.6min]

Entraînement:  39%|███▉      | 3919/10000 [12:33<19:19,  5.24step/s, loss=0.033858, elapsed=12.6min]

Entraînement:  39%|███▉      | 3919/10000 [12:33<19:19,  5.24step/s, loss=0.120769, elapsed=12.6min]

Entraînement:  39%|███▉      | 3920/10000 [12:33<19:19,  5.25step/s, loss=0.120769, elapsed=12.6min]

Entraînement:  39%|███▉      | 3920/10000 [12:33<19:19,  5.25step/s, loss=0.036928, elapsed=12.6min]

Entraînement:  39%|███▉      | 3921/10000 [12:34<19:16,  5.26step/s, loss=0.036928, elapsed=12.6min]

Entraînement:  39%|███▉      | 3921/10000 [12:34<19:16,  5.26step/s, loss=0.032916, elapsed=12.6min]

Entraînement:  39%|███▉      | 3922/10000 [12:34<19:17,  5.25step/s, loss=0.032916, elapsed=12.6min]

Entraînement:  39%|███▉      | 3922/10000 [12:34<19:17,  5.25step/s, loss=0.116055, elapsed=12.6min]

Entraînement:  39%|███▉      | 3923/10000 [12:34<19:15,  5.26step/s, loss=0.116055, elapsed=12.6min]

Entraînement:  39%|███▉      | 3923/10000 [12:34<19:15,  5.26step/s, loss=0.038134, elapsed=12.6min]

Entraînement:  39%|███▉      | 3924/10000 [12:34<19:12,  5.27step/s, loss=0.038134, elapsed=12.6min]

Entraînement:  39%|███▉      | 3924/10000 [12:34<19:12,  5.27step/s, loss=0.035717, elapsed=12.6min]

Entraînement:  39%|███▉      | 3925/10000 [12:34<19:12,  5.27step/s, loss=0.035717, elapsed=12.6min]

Entraînement:  39%|███▉      | 3925/10000 [12:34<19:12,  5.27step/s, loss=0.114750, elapsed=12.6min]

Entraînement:  39%|███▉      | 3926/10000 [12:35<19:10,  5.28step/s, loss=0.114750, elapsed=12.6min]

Entraînement:  39%|███▉      | 3926/10000 [12:35<19:10,  5.28step/s, loss=0.064907, elapsed=12.6min]

Entraînement:  39%|███▉      | 3927/10000 [12:35<19:11,  5.28step/s, loss=0.064907, elapsed=12.6min]

Entraînement:  39%|███▉      | 3927/10000 [12:35<19:11,  5.28step/s, loss=0.036578, elapsed=12.6min]

Entraînement:  39%|███▉      | 3928/10000 [12:35<19:11,  5.27step/s, loss=0.036578, elapsed=12.6min]

Entraînement:  39%|███▉      | 3928/10000 [12:35<19:11,  5.27step/s, loss=0.040836, elapsed=12.6min]

Entraînement:  39%|███▉      | 3929/10000 [12:35<19:12,  5.27step/s, loss=0.040836, elapsed=12.6min]

Entraînement:  39%|███▉      | 3929/10000 [12:35<19:12,  5.27step/s, loss=0.086306, elapsed=12.6min]

Entraînement:  39%|███▉      | 3930/10000 [12:35<19:11,  5.27step/s, loss=0.086306, elapsed=12.6min]

Entraînement:  39%|███▉      | 3930/10000 [12:35<19:11,  5.27step/s, loss=0.033964, elapsed=12.6min]

Entraînement:  39%|███▉      | 3931/10000 [12:36<19:11,  5.27step/s, loss=0.033964, elapsed=12.6min]

Entraînement:  39%|███▉      | 3931/10000 [12:36<19:11,  5.27step/s, loss=0.050709, elapsed=12.6min]

Entraînement:  39%|███▉      | 3932/10000 [12:36<19:10,  5.28step/s, loss=0.050709, elapsed=12.6min]

Entraînement:  39%|███▉      | 3932/10000 [12:36<19:10,  5.28step/s, loss=0.026266, elapsed=12.6min]

Entraînement:  39%|███▉      | 3933/10000 [12:36<19:08,  5.28step/s, loss=0.026266, elapsed=12.6min]

Entraînement:  39%|███▉      | 3933/10000 [12:36<19:08,  5.28step/s, loss=0.030967, elapsed=12.6min]

Entraînement:  39%|███▉      | 3934/10000 [12:36<19:08,  5.28step/s, loss=0.030967, elapsed=12.6min]

Entraînement:  39%|███▉      | 3934/10000 [12:36<19:08,  5.28step/s, loss=0.042334, elapsed=12.6min]

Entraînement:  39%|███▉      | 3935/10000 [12:36<19:08,  5.28step/s, loss=0.042334, elapsed=12.6min]

Entraînement:  39%|███▉      | 3935/10000 [12:36<19:08,  5.28step/s, loss=0.044678, elapsed=12.6min]

Entraînement:  39%|███▉      | 3936/10000 [12:37<19:10,  5.27step/s, loss=0.044678, elapsed=12.6min]

Entraînement:  39%|███▉      | 3936/10000 [12:37<19:10,  5.27step/s, loss=0.052966, elapsed=12.6min]

Entraînement:  39%|███▉      | 3937/10000 [12:37<19:10,  5.27step/s, loss=0.052966, elapsed=12.6min]

Entraînement:  39%|███▉      | 3937/10000 [12:37<19:10,  5.27step/s, loss=0.038158, elapsed=12.6min]

Entraînement:  39%|███▉      | 3938/10000 [12:37<19:14,  5.25step/s, loss=0.038158, elapsed=12.6min]

Entraînement:  39%|███▉      | 3938/10000 [12:37<19:14,  5.25step/s, loss=0.049646, elapsed=12.6min]

Entraînement:  39%|███▉      | 3939/10000 [12:37<19:15,  5.25step/s, loss=0.049646, elapsed=12.6min]

Entraînement:  39%|███▉      | 3939/10000 [12:37<19:15,  5.25step/s, loss=0.049322, elapsed=12.6min]

Entraînement:  39%|███▉      | 3940/10000 [12:37<19:16,  5.24step/s, loss=0.049322, elapsed=12.6min]

Entraînement:  39%|███▉      | 3940/10000 [12:37<19:16,  5.24step/s, loss=0.053718, elapsed=12.6min]

Entraînement:  39%|███▉      | 3941/10000 [12:37<19:17,  5.24step/s, loss=0.053718, elapsed=12.6min]

Entraînement:  39%|███▉      | 3941/10000 [12:37<19:17,  5.24step/s, loss=0.037433, elapsed=12.6min]

Entraînement:  39%|███▉      | 3942/10000 [12:38<19:13,  5.25step/s, loss=0.037433, elapsed=12.6min]

Entraînement:  39%|███▉      | 3942/10000 [12:38<19:13,  5.25step/s, loss=0.066407, elapsed=12.6min]

Entraînement:  39%|███▉      | 3943/10000 [12:38<19:15,  5.24step/s, loss=0.066407, elapsed=12.6min]

Entraînement:  39%|███▉      | 3943/10000 [12:38<19:15,  5.24step/s, loss=0.031084, elapsed=12.6min]

Entraînement:  39%|███▉      | 3944/10000 [12:38<19:14,  5.24step/s, loss=0.031084, elapsed=12.6min]

Entraînement:  39%|███▉      | 3944/10000 [12:38<19:14,  5.24step/s, loss=0.041464, elapsed=12.6min]

Entraînement:  39%|███▉      | 3945/10000 [12:38<19:17,  5.23step/s, loss=0.041464, elapsed=12.6min]

Entraînement:  39%|███▉      | 3945/10000 [12:38<19:17,  5.23step/s, loss=0.093469, elapsed=12.6min]

Entraînement:  39%|███▉      | 3946/10000 [12:38<19:16,  5.24step/s, loss=0.093469, elapsed=12.6min]

Entraînement:  39%|███▉      | 3946/10000 [12:38<19:16,  5.24step/s, loss=0.022743, elapsed=12.6min]

Entraînement:  39%|███▉      | 3947/10000 [12:39<19:09,  5.26step/s, loss=0.022743, elapsed=12.6min]

Entraînement:  39%|███▉      | 3947/10000 [12:39<19:09,  5.26step/s, loss=0.088730, elapsed=12.7min]

Entraînement:  39%|███▉      | 3948/10000 [12:39<19:04,  5.29step/s, loss=0.088730, elapsed=12.7min]

Entraînement:  39%|███▉      | 3948/10000 [12:39<19:04,  5.29step/s, loss=0.072985, elapsed=12.7min]

Entraînement:  39%|███▉      | 3949/10000 [12:39<18:59,  5.31step/s, loss=0.072985, elapsed=12.7min]

Entraînement:  39%|███▉      | 3949/10000 [12:39<18:59,  5.31step/s, loss=0.090051, elapsed=12.7min]

Entraînement:  40%|███▉      | 3950/10000 [12:39<18:57,  5.32step/s, loss=0.090051, elapsed=12.7min]

Entraînement:  40%|███▉      | 3950/10000 [12:39<18:57,  5.32step/s, loss=0.066493, elapsed=12.7min]

Entraînement:  40%|███▉      | 3951/10000 [12:39<18:59,  5.31step/s, loss=0.066493, elapsed=12.7min]

Entraînement:  40%|███▉      | 3951/10000 [12:39<18:59,  5.31step/s, loss=0.030803, elapsed=12.7min]

Entraînement:  40%|███▉      | 3952/10000 [12:40<18:58,  5.31step/s, loss=0.030803, elapsed=12.7min]

Entraînement:  40%|███▉      | 3952/10000 [12:40<18:58,  5.31step/s, loss=0.060236, elapsed=12.7min]

Entraînement:  40%|███▉      | 3953/10000 [12:40<18:58,  5.31step/s, loss=0.060236, elapsed=12.7min]

Entraînement:  40%|███▉      | 3953/10000 [12:40<18:58,  5.31step/s, loss=0.076389, elapsed=12.7min]

Entraînement:  40%|███▉      | 3954/10000 [12:40<18:57,  5.32step/s, loss=0.076389, elapsed=12.7min]

Entraînement:  40%|███▉      | 3954/10000 [12:40<18:57,  5.32step/s, loss=0.068320, elapsed=12.7min]

Entraînement:  40%|███▉      | 3955/10000 [12:40<18:56,  5.32step/s, loss=0.068320, elapsed=12.7min]

Entraînement:  40%|███▉      | 3955/10000 [12:40<18:56,  5.32step/s, loss=0.074558, elapsed=12.7min]

Entraînement:  40%|███▉      | 3956/10000 [12:40<18:59,  5.30step/s, loss=0.074558, elapsed=12.7min]

Entraînement:  40%|███▉      | 3956/10000 [12:40<18:59,  5.30step/s, loss=0.096509, elapsed=12.7min]

Entraînement:  40%|███▉      | 3957/10000 [12:41<18:57,  5.31step/s, loss=0.096509, elapsed=12.7min]

Entraînement:  40%|███▉      | 3957/10000 [12:41<18:57,  5.31step/s, loss=0.047542, elapsed=12.7min]

Entraînement:  40%|███▉      | 3958/10000 [12:41<18:56,  5.32step/s, loss=0.047542, elapsed=12.7min]

Entraînement:  40%|███▉      | 3958/10000 [12:41<18:56,  5.32step/s, loss=0.044022, elapsed=12.7min]

Entraînement:  40%|███▉      | 3959/10000 [12:41<18:58,  5.31step/s, loss=0.044022, elapsed=12.7min]

Entraînement:  40%|███▉      | 3959/10000 [12:41<18:58,  5.31step/s, loss=0.038093, elapsed=12.7min]

Entraînement:  40%|███▉      | 3960/10000 [12:41<18:56,  5.31step/s, loss=0.038093, elapsed=12.7min]

Entraînement:  40%|███▉      | 3960/10000 [12:41<18:56,  5.31step/s, loss=0.071923, elapsed=12.7min]

Entraînement:  40%|███▉      | 3961/10000 [12:41<18:55,  5.32step/s, loss=0.071923, elapsed=12.7min]

Entraînement:  40%|███▉      | 3961/10000 [12:41<18:55,  5.32step/s, loss=0.051891, elapsed=12.7min]

Entraînement:  40%|███▉      | 3962/10000 [12:41<18:54,  5.32step/s, loss=0.051891, elapsed=12.7min]

Entraînement:  40%|███▉      | 3962/10000 [12:41<18:54,  5.32step/s, loss=0.054336, elapsed=12.7min]

Entraînement:  40%|███▉      | 3963/10000 [12:42<18:52,  5.33step/s, loss=0.054336, elapsed=12.7min]

Entraînement:  40%|███▉      | 3963/10000 [12:42<18:52,  5.33step/s, loss=0.080898, elapsed=12.7min]

Entraînement:  40%|███▉      | 3964/10000 [12:42<18:52,  5.33step/s, loss=0.080898, elapsed=12.7min]

Entraînement:  40%|███▉      | 3964/10000 [12:42<18:52,  5.33step/s, loss=0.082863, elapsed=12.7min]

Entraînement:  40%|███▉      | 3965/10000 [12:42<18:51,  5.33step/s, loss=0.082863, elapsed=12.7min]

Entraînement:  40%|███▉      | 3965/10000 [12:42<18:51,  5.33step/s, loss=0.101368, elapsed=12.7min]

Entraînement:  40%|███▉      | 3966/10000 [12:42<18:51,  5.33step/s, loss=0.101368, elapsed=12.7min]

Entraînement:  40%|███▉      | 3966/10000 [12:42<18:51,  5.33step/s, loss=0.088024, elapsed=12.7min]

Entraînement:  40%|███▉      | 3967/10000 [12:42<18:49,  5.34step/s, loss=0.088024, elapsed=12.7min]

Entraînement:  40%|███▉      | 3967/10000 [12:42<18:49,  5.34step/s, loss=0.027587, elapsed=12.7min]

Entraînement:  40%|███▉      | 3968/10000 [12:43<18:52,  5.33step/s, loss=0.027587, elapsed=12.7min]

Entraînement:  40%|███▉      | 3968/10000 [12:43<18:52,  5.33step/s, loss=0.041757, elapsed=12.7min]

Entraînement:  40%|███▉      | 3969/10000 [12:43<18:51,  5.33step/s, loss=0.041757, elapsed=12.7min]

Entraînement:  40%|███▉      | 3969/10000 [12:43<18:51,  5.33step/s, loss=0.042600, elapsed=12.7min]

Entraînement:  40%|███▉      | 3970/10000 [12:43<18:49,  5.34step/s, loss=0.042600, elapsed=12.7min]

Entraînement:  40%|███▉      | 3970/10000 [12:43<18:49,  5.34step/s, loss=0.030216, elapsed=12.7min]

Entraînement:  40%|███▉      | 3971/10000 [12:43<18:49,  5.34step/s, loss=0.030216, elapsed=12.7min]

Entraînement:  40%|███▉      | 3971/10000 [12:43<18:49,  5.34step/s, loss=0.048624, elapsed=12.7min]

Entraînement:  40%|███▉      | 3972/10000 [12:43<18:49,  5.34step/s, loss=0.048624, elapsed=12.7min]

Entraînement:  40%|███▉      | 3972/10000 [12:43<18:49,  5.34step/s, loss=0.056656, elapsed=12.7min]

Entraînement:  40%|███▉      | 3973/10000 [12:44<18:52,  5.32step/s, loss=0.056656, elapsed=12.7min]

Entraînement:  40%|███▉      | 3973/10000 [12:44<18:52,  5.32step/s, loss=0.048141, elapsed=12.7min]

Entraînement:  40%|███▉      | 3974/10000 [12:44<18:54,  5.31step/s, loss=0.048141, elapsed=12.7min]

Entraînement:  40%|███▉      | 3974/10000 [12:44<18:54,  5.31step/s, loss=0.040456, elapsed=12.7min]

Entraînement:  40%|███▉      | 3975/10000 [12:44<18:52,  5.32step/s, loss=0.040456, elapsed=12.7min]

Entraînement:  40%|███▉      | 3975/10000 [12:44<18:52,  5.32step/s, loss=0.104124, elapsed=12.7min]

Entraînement:  40%|███▉      | 3976/10000 [12:44<18:51,  5.33step/s, loss=0.104124, elapsed=12.7min]

Entraînement:  40%|███▉      | 3976/10000 [12:44<18:51,  5.33step/s, loss=0.058888, elapsed=12.7min]

Entraînement:  40%|███▉      | 3977/10000 [12:44<18:50,  5.33step/s, loss=0.058888, elapsed=12.7min]

Entraînement:  40%|███▉      | 3977/10000 [12:44<18:50,  5.33step/s, loss=0.048490, elapsed=12.7min]

Entraînement:  40%|███▉      | 3978/10000 [12:44<18:50,  5.33step/s, loss=0.048490, elapsed=12.7min]

Entraînement:  40%|███▉      | 3978/10000 [12:44<18:50,  5.33step/s, loss=0.048120, elapsed=12.7min]

Entraînement:  40%|███▉      | 3979/10000 [12:45<18:47,  5.34step/s, loss=0.048120, elapsed=12.7min]

Entraînement:  40%|███▉      | 3979/10000 [12:45<18:47,  5.34step/s, loss=0.096291, elapsed=12.8min]

Entraînement:  40%|███▉      | 3980/10000 [12:45<18:48,  5.34step/s, loss=0.096291, elapsed=12.8min]

Entraînement:  40%|███▉      | 3980/10000 [12:45<18:48,  5.34step/s, loss=0.053560, elapsed=12.8min]

Entraînement:  40%|███▉      | 3981/10000 [12:45<18:46,  5.34step/s, loss=0.053560, elapsed=12.8min]

Entraînement:  40%|███▉      | 3981/10000 [12:45<18:46,  5.34step/s, loss=0.059786, elapsed=12.8min]

Entraînement:  40%|███▉      | 3982/10000 [12:45<18:43,  5.35step/s, loss=0.059786, elapsed=12.8min]

Entraînement:  40%|███▉      | 3982/10000 [12:45<18:43,  5.35step/s, loss=0.056624, elapsed=12.8min]

Entraînement:  40%|███▉      | 3983/10000 [12:45<18:42,  5.36step/s, loss=0.056624, elapsed=12.8min]

Entraînement:  40%|███▉      | 3983/10000 [12:45<18:42,  5.36step/s, loss=0.039793, elapsed=12.8min]

Entraînement:  40%|███▉      | 3984/10000 [12:46<18:45,  5.35step/s, loss=0.039793, elapsed=12.8min]

Entraînement:  40%|███▉      | 3984/10000 [12:46<18:45,  5.35step/s, loss=0.051101, elapsed=12.8min]

Entraînement:  40%|███▉      | 3985/10000 [12:46<18:46,  5.34step/s, loss=0.051101, elapsed=12.8min]

Entraînement:  40%|███▉      | 3985/10000 [12:46<18:46,  5.34step/s, loss=0.026928, elapsed=12.8min]

Entraînement:  40%|███▉      | 3986/10000 [12:46<18:45,  5.34step/s, loss=0.026928, elapsed=12.8min]

Entraînement:  40%|███▉      | 3986/10000 [12:46<18:45,  5.34step/s, loss=0.028091, elapsed=12.8min]

Entraînement:  40%|███▉      | 3987/10000 [12:46<18:46,  5.34step/s, loss=0.028091, elapsed=12.8min]

Entraînement:  40%|███▉      | 3987/10000 [12:46<18:46,  5.34step/s, loss=0.034856, elapsed=12.8min]

Entraînement:  40%|███▉      | 3988/10000 [12:46<18:49,  5.32step/s, loss=0.034856, elapsed=12.8min]

Entraînement:  40%|███▉      | 3988/10000 [12:46<18:49,  5.32step/s, loss=0.048364, elapsed=12.8min]

Entraînement:  40%|███▉      | 3989/10000 [12:47<18:50,  5.31step/s, loss=0.048364, elapsed=12.8min]

Entraînement:  40%|███▉      | 3989/10000 [12:47<18:50,  5.31step/s, loss=0.042206, elapsed=12.8min]

Entraînement:  40%|███▉      | 3990/10000 [12:47<18:53,  5.30step/s, loss=0.042206, elapsed=12.8min]

Entraînement:  40%|███▉      | 3990/10000 [12:47<18:53,  5.30step/s, loss=0.042657, elapsed=12.8min]

Entraînement:  40%|███▉      | 3991/10000 [12:47<18:54,  5.30step/s, loss=0.042657, elapsed=12.8min]

Entraînement:  40%|███▉      | 3991/10000 [12:47<18:54,  5.30step/s, loss=0.027666, elapsed=12.8min]

Entraînement:  40%|███▉      | 3992/10000 [12:47<18:56,  5.29step/s, loss=0.027666, elapsed=12.8min]

Entraînement:  40%|███▉      | 3992/10000 [12:47<18:56,  5.29step/s, loss=0.047456, elapsed=12.8min]

Entraînement:  40%|███▉      | 3993/10000 [12:47<18:57,  5.28step/s, loss=0.047456, elapsed=12.8min]

Entraînement:  40%|███▉      | 3993/10000 [12:47<18:57,  5.28step/s, loss=0.071673, elapsed=12.8min]

Entraînement:  40%|███▉      | 3994/10000 [12:47<18:59,  5.27step/s, loss=0.071673, elapsed=12.8min]

Entraînement:  40%|███▉      | 3994/10000 [12:47<18:59,  5.27step/s, loss=0.083395, elapsed=12.8min]

Entraînement:  40%|███▉      | 3995/10000 [12:48<18:58,  5.28step/s, loss=0.083395, elapsed=12.8min]

Entraînement:  40%|███▉      | 3995/10000 [12:48<18:58,  5.28step/s, loss=0.032342, elapsed=12.8min]

Entraînement:  40%|███▉      | 3996/10000 [12:48<18:56,  5.28step/s, loss=0.032342, elapsed=12.8min]

Entraînement:  40%|███▉      | 3996/10000 [12:48<18:56,  5.28step/s, loss=0.083139, elapsed=12.8min]

Entraînement:  40%|███▉      | 3997/10000 [12:48<18:56,  5.28step/s, loss=0.083139, elapsed=12.8min]

Entraînement:  40%|███▉      | 3997/10000 [12:48<18:56,  5.28step/s, loss=0.036388, elapsed=12.8min]

Entraînement:  40%|███▉      | 3998/10000 [12:48<18:56,  5.28step/s, loss=0.036388, elapsed=12.8min]

Entraînement:  40%|███▉      | 3998/10000 [12:48<18:56,  5.28step/s, loss=0.026210, elapsed=12.8min]

Entraînement:  40%|███▉      | 3999/10000 [12:48<18:56,  5.28step/s, loss=0.026210, elapsed=12.8min]

Entraînement:  40%|███▉      | 3999/10000 [12:48<18:56,  5.28step/s, loss=0.084828, elapsed=12.8min]

Entraînement:  40%|████      | 4000/10000 [12:49<18:56,  5.28step/s, loss=0.084828, elapsed=12.8min]

Entraînement:  40%|████      | 4000/10000 [12:49<18:56,  5.28step/s, loss=0.039654, elapsed=12.8min]

Entraînement:  40%|████      | 4000/10000 [12:49<18:56,  5.28step/s, loss=0.039654, elapsed=12.8min]

Step 4000/10000 | Train loss: 0.039654 | Elapsed: 12.8min | ETA: 19.2min

Entraînement:  40%|████      | 4000/10000 [12:50<18:56,  5.28step/s, loss=0.039654, elapsed=12.8min]

Entraînement:  40%|████      | 4000/10000 [12:50<18:56,  5.28step/s, loss=0.039654, elapsed=12.8min]

Step 4000/10000 | Val loss: 0.063859 | Validation en 1.7s
Dernier checkpoint sauvegardé : /workspace/DiffWave_Project/checkpoints/diffwave_doda_male/last_checkpoint.pt

Entraînement:  40%|████      | 4001/10000 [12:51<1:15:04,  1.33step/s, loss=0.039654, elapsed=12.8min]

Entraînement:  40%|████      | 4001/10000 [12:51<1:15:04,  1.33step/s, loss=0.048044, elapsed=12.9min]

Entraînement:  40%|████      | 4002/10000 [12:51<58:19,  1.71step/s, loss=0.048044, elapsed=12.9min]

Entraînement:  40%|████      | 4002/10000 [12:51<58:19,  1.71step/s, loss=0.063843, elapsed=12.9min]

Entraînement:  40%|████      | 4003/10000 [12:51<46:34,  2.15step/s, loss=0.063843, elapsed=12.9min]

Entraînement:  40%|████      | 4003/10000 [12:51<46:34,  2.15step/s, loss=0.066142, elapsed=12.9min]

Entraînement:  40%|████      | 4004/10000 [12:51<38:17,  2.61step/s, loss=0.066142, elapsed=12.9min]

Entraînement:  40%|████      | 4004/10000 [12:51<38:17,  2.61step/s, loss=0.027009, elapsed=12.9min]

Entraînement:  40%|████      | 4005/10000 [12:51<32:24,  3.08step/s, loss=0.027009, elapsed=12.9min]

Entraînement:  40%|████      | 4005/10000 [12:51<32:24,  3.08step/s, loss=0.028766, elapsed=12.9min]

Entraînement:  40%|████      | 4006/10000 [12:52<28:22,  3.52step/s, loss=0.028766, elapsed=12.9min]

Entraînement:  40%|████      | 4006/10000 [12:52<28:22,  3.52step/s, loss=0.033289, elapsed=12.9min]

Entraînement:  40%|████      | 4007/10000 [12:52<25:32,  3.91step/s, loss=0.033289, elapsed=12.9min]

Entraînement:  40%|████      | 4007/10000 [12:52<25:32,  3.91step/s, loss=0.018605, elapsed=12.9min]

Entraînement:  40%|████      | 4008/10000 [12:52<23:34,  4.24step/s, loss=0.018605, elapsed=12.9min]

Entraînement:  40%|████      | 4008/10000 [12:52<23:34,  4.24step/s, loss=0.062029, elapsed=12.9min]

Entraînement:  40%|████      | 4009/10000 [12:52<22:13,  4.49step/s, loss=0.062029, elapsed=12.9min]

Entraînement:  40%|████      | 4009/10000 [12:52<22:13,  4.49step/s, loss=0.053569, elapsed=12.9min]

Entraînement:  40%|████      | 4010/10000 [12:52<21:12,  4.71step/s, loss=0.053569, elapsed=12.9min]

Entraînement:  40%|████      | 4010/10000 [12:52<21:12,  4.71step/s, loss=0.061621, elapsed=12.9min]

Entraînement:  40%|████      | 4011/10000 [12:53<20:34,  4.85step/s, loss=0.061621, elapsed=12.9min]

Entraînement:  40%|████      | 4011/10000 [12:53<20:34,  4.85step/s, loss=0.115747, elapsed=12.9min]

Entraînement:  40%|████      | 4012/10000 [12:53<20:05,  4.97step/s, loss=0.115747, elapsed=12.9min]

Entraînement:  40%|████      | 4012/10000 [12:53<20:05,  4.97step/s, loss=0.035447, elapsed=12.9min]

Entraînement:  40%|████      | 4013/10000 [12:53<19:45,  5.05step/s, loss=0.035447, elapsed=12.9min]

Entraînement:  40%|████      | 4013/10000 [12:53<19:45,  5.05step/s, loss=0.049437, elapsed=12.9min]

Entraînement:  40%|████      | 4014/10000 [12:53<19:30,  5.11step/s, loss=0.049437, elapsed=12.9min]

Entraînement:  40%|████      | 4014/10000 [12:53<19:30,  5.11step/s, loss=0.055464, elapsed=12.9min]

Entraînement:  40%|████      | 4015/10000 [12:53<19:22,  5.15step/s, loss=0.055464, elapsed=12.9min]

Entraînement:  40%|████      | 4015/10000 [12:53<19:22,  5.15step/s, loss=0.050422, elapsed=12.9min]

Entraînement:  40%|████      | 4016/10000 [12:54<19:18,  5.17step/s, loss=0.050422, elapsed=12.9min]

Entraînement:  40%|████      | 4016/10000 [12:54<19:18,  5.17step/s, loss=0.045155, elapsed=12.9min]

Entraînement:  40%|████      | 4017/10000 [12:54<19:14,  5.18step/s, loss=0.045155, elapsed=12.9min]

Entraînement:  40%|████      | 4017/10000 [12:54<19:14,  5.18step/s, loss=0.046620, elapsed=12.9min]

Entraînement:  40%|████      | 4018/10000 [12:54<19:10,  5.20step/s, loss=0.046620, elapsed=12.9min]

Entraînement:  40%|████      | 4018/10000 [12:54<19:10,  5.20step/s, loss=0.054057, elapsed=12.9min]

Entraînement:  40%|████      | 4019/10000 [12:54<19:09,  5.20step/s, loss=0.054057, elapsed=12.9min]

Entraînement:  40%|████      | 4019/10000 [12:54<19:09,  5.20step/s, loss=0.048433, elapsed=12.9min]

Entraînement:  40%|████      | 4020/10000 [12:54<19:05,  5.22step/s, loss=0.048433, elapsed=12.9min]

Entraînement:  40%|████      | 4020/10000 [12:54<19:05,  5.22step/s, loss=0.049155, elapsed=12.9min]

Entraînement:  40%|████      | 4021/10000 [12:54<18:59,  5.25step/s, loss=0.049155, elapsed=12.9min]

Entraînement:  40%|████      | 4021/10000 [12:54<18:59,  5.25step/s, loss=0.092241, elapsed=12.9min]

Entraînement:  40%|████      | 4022/10000 [12:55<18:57,  5.26step/s, loss=0.092241, elapsed=12.9min]

Entraînement:  40%|████      | 4022/10000 [12:55<18:57,  5.26step/s, loss=0.051476, elapsed=12.9min]

Entraînement:  40%|████      | 4023/10000 [12:55<18:56,  5.26step/s, loss=0.051476, elapsed=12.9min]

Entraînement:  40%|████      | 4023/10000 [12:55<18:56,  5.26step/s, loss=0.087883, elapsed=12.9min]

Entraînement:  40%|████      | 4024/10000 [12:55<18:56,  5.26step/s, loss=0.087883, elapsed=12.9min]

Entraînement:  40%|████      | 4024/10000 [12:55<18:56,  5.26step/s, loss=0.081541, elapsed=12.9min]

Entraînement:  40%|████      | 4025/10000 [12:55<18:57,  5.25step/s, loss=0.081541, elapsed=12.9min]

Entraînement:  40%|████      | 4025/10000 [12:55<18:57,  5.25step/s, loss=0.072968, elapsed=12.9min]

Entraînement:  40%|████      | 4026/10000 [12:55<18:55,  5.26step/s, loss=0.072968, elapsed=12.9min]

Entraînement:  40%|████      | 4026/10000 [12:55<18:55,  5.26step/s, loss=0.163931, elapsed=12.9min]

Entraînement:  40%|████      | 4027/10000 [12:56<18:57,  5.25step/s, loss=0.163931, elapsed=12.9min]

Entraînement:  40%|████      | 4027/10000 [12:56<18:57,  5.25step/s, loss=0.039389, elapsed=12.9min]

Entraînement:  40%|████      | 4028/10000 [12:56<18:55,  5.26step/s, loss=0.039389, elapsed=12.9min]

Entraînement:  40%|████      | 4028/10000 [12:56<18:55,  5.26step/s, loss=0.163352, elapsed=12.9min]

Entraînement:  40%|████      | 4029/10000 [12:56<18:52,  5.27step/s, loss=0.163352, elapsed=12.9min]

Entraînement:  40%|████      | 4029/10000 [12:56<18:52,  5.27step/s, loss=0.024753, elapsed=12.9min]

Entraînement:  40%|████      | 4030/10000 [12:56<18:54,  5.26step/s, loss=0.024753, elapsed=12.9min]

Entraînement:  40%|████      | 4030/10000 [12:56<18:54,  5.26step/s, loss=0.058976, elapsed=12.9min]

Entraînement:  40%|████      | 4031/10000 [12:56<18:53,  5.27step/s, loss=0.058976, elapsed=12.9min]

Entraînement:  40%|████      | 4031/10000 [12:56<18:53,  5.27step/s, loss=0.057771, elapsed=12.9min]

Entraînement:  40%|████      | 4032/10000 [12:57<18:51,  5.28step/s, loss=0.057771, elapsed=12.9min]

Entraînement:  40%|████      | 4032/10000 [12:57<18:51,  5.28step/s, loss=0.056216, elapsed=13.0min]

Entraînement:  40%|████      | 4033/10000 [12:57<18:49,  5.28step/s, loss=0.056216, elapsed=13.0min]

Entraînement:  40%|████      | 4033/10000 [12:57<18:49,  5.28step/s, loss=0.045563, elapsed=13.0min]

Entraînement:  40%|████      | 4034/10000 [12:57<18:52,  5.27step/s, loss=0.045563, elapsed=13.0min]

Entraînement:  40%|████      | 4034/10000 [12:57<18:52,  5.27step/s, loss=0.052906, elapsed=13.0min]

Entraînement:  40%|████      | 4035/10000 [12:57<18:52,  5.27step/s, loss=0.052906, elapsed=13.0min]

Entraînement:  40%|████      | 4035/10000 [12:57<18:52,  5.27step/s, loss=0.067900, elapsed=13.0min]

Entraînement:  40%|████      | 4036/10000 [12:57<18:50,  5.27step/s, loss=0.067900, elapsed=13.0min]

Entraînement:  40%|████      | 4036/10000 [12:57<18:50,  5.27step/s, loss=0.034771, elapsed=13.0min]

Entraînement:  40%|████      | 4037/10000 [12:57<18:50,  5.27step/s, loss=0.034771, elapsed=13.0min]

Entraînement:  40%|████      | 4037/10000 [12:58<18:50,  5.27step/s, loss=0.039116, elapsed=13.0min]

Entraînement:  40%|████      | 4038/10000 [12:58<18:50,  5.27step/s, loss=0.039116, elapsed=13.0min]

Entraînement:  40%|████      | 4038/10000 [12:58<18:50,  5.27step/s, loss=0.110466, elapsed=13.0min]

Entraînement:  40%|████      | 4039/10000 [12:58<18:49,  5.28step/s, loss=0.110466, elapsed=13.0min]

Entraînement:  40%|████      | 4039/10000 [12:58<18:49,  5.28step/s, loss=0.058874, elapsed=13.0min]

Entraînement:  40%|████      | 4040/10000 [12:58<18:49,  5.28step/s, loss=0.058874, elapsed=13.0min]

Entraînement:  40%|████      | 4040/10000 [12:58<18:49,  5.28step/s, loss=0.018663, elapsed=13.0min]

Entraînement:  40%|████      | 4041/10000 [12:58<18:50,  5.27step/s, loss=0.018663, elapsed=13.0min]

Entraînement:  40%|████      | 4041/10000 [12:58<18:50,  5.27step/s, loss=0.039731, elapsed=13.0min]

Entraînement:  40%|████      | 4042/10000 [12:58<18:51,  5.27step/s, loss=0.039731, elapsed=13.0min]

Entraînement:  40%|████      | 4042/10000 [12:58<18:51,  5.27step/s, loss=0.051083, elapsed=13.0min]

Entraînement:  40%|████      | 4043/10000 [12:59<18:53,  5.25step/s, loss=0.051083, elapsed=13.0min]

Entraînement:  40%|████      | 4043/10000 [12:59<18:53,  5.25step/s, loss=0.057293, elapsed=13.0min]

Entraînement:  40%|████      | 4044/10000 [12:59<18:51,  5.26step/s, loss=0.057293, elapsed=13.0min]

Entraînement:  40%|████      | 4044/10000 [12:59<18:51,  5.26step/s, loss=0.034445, elapsed=13.0min]

Entraînement:  40%|████      | 4045/10000 [12:59<18:49,  5.27step/s, loss=0.034445, elapsed=13.0min]

Entraînement:  40%|████      | 4045/10000 [12:59<18:49,  5.27step/s, loss=0.040919, elapsed=13.0min]

Entraînement:  40%|████      | 4046/10000 [12:59<18:48,  5.28step/s, loss=0.040919, elapsed=13.0min]

Entraînement:  40%|████      | 4046/10000 [12:59<18:48,  5.28step/s, loss=0.037762, elapsed=13.0min]

Entraînement:  40%|████      | 4047/10000 [12:59<18:49,  5.27step/s, loss=0.037762, elapsed=13.0min]

Entraînement:  40%|████      | 4047/10000 [12:59<18:49,  5.27step/s, loss=0.043841, elapsed=13.0min]

Entraînement:  40%|████      | 4048/10000 [13:00<18:49,  5.27step/s, loss=0.043841, elapsed=13.0min]

Entraînement:  40%|████      | 4048/10000 [13:00<18:49,  5.27step/s, loss=0.125505, elapsed=13.0min]

Entraînement:  40%|████      | 4049/10000 [13:00<18:46,  5.28step/s, loss=0.125505, elapsed=13.0min]

Entraînement:  40%|████      | 4049/10000 [13:00<18:46,  5.28step/s, loss=0.092115, elapsed=13.0min]

Entraînement:  40%|████      | 4050/10000 [13:00<18:47,  5.28step/s, loss=0.092115, elapsed=13.0min]

Entraînement:  40%|████      | 4050/10000 [13:00<18:47,  5.28step/s, loss=0.063529, elapsed=13.0min]

Entraînement:  41%|████      | 4051/10000 [13:00<18:48,  5.27step/s, loss=0.063529, elapsed=13.0min]

Entraînement:  41%|████      | 4051/10000 [13:00<18:48,  5.27step/s, loss=0.056601, elapsed=13.0min]

Entraînement:  41%|████      | 4052/10000 [13:00<18:48,  5.27step/s, loss=0.056601, elapsed=13.0min]

Entraînement:  41%|████      | 4052/10000 [13:00<18:48,  5.27step/s, loss=0.049946, elapsed=13.0min]

Entraînement:  41%|████      | 4053/10000 [13:01<18:48,  5.27step/s, loss=0.049946, elapsed=13.0min]

Entraînement:  41%|████      | 4053/10000 [13:01<18:48,  5.27step/s, loss=0.077369, elapsed=13.0min]

Entraînement:  41%|████      | 4054/10000 [13:01<18:47,  5.27step/s, loss=0.077369, elapsed=13.0min]

Entraînement:  41%|████      | 4054/10000 [13:01<18:47,  5.27step/s, loss=0.096460, elapsed=13.0min]

Entraînement:  41%|████      | 4055/10000 [13:01<18:44,  5.29step/s, loss=0.096460, elapsed=13.0min]

Entraînement:  41%|████      | 4055/10000 [13:01<18:44,  5.29step/s, loss=0.064786, elapsed=13.0min]

Entraînement:  41%|████      | 4056/10000 [13:01<27:23,  3.62step/s, loss=0.064786, elapsed=13.0min]

Entraînement:  41%|████      | 4056/10000 [13:01<27:23,  3.62step/s, loss=0.061009, elapsed=13.0min]

Entraînement:  41%|████      | 4057/10000 [13:02<24:53,  3.98step/s, loss=0.061009, elapsed=13.0min]

Entraînement:  41%|████      | 4057/10000 [13:02<24:53,  3.98step/s, loss=0.039690, elapsed=13.0min]

Entraînement:  41%|████      | 4058/10000 [13:02<23:01,  4.30step/s, loss=0.039690, elapsed=13.0min]

Entraînement:  41%|████      | 4058/10000 [13:02<23:01,  4.30step/s, loss=0.043762, elapsed=13.0min]

Entraînement:  41%|████      | 4059/10000 [13:02<21:50,  4.53step/s, loss=0.043762, elapsed=13.0min]

Entraînement:  41%|████      | 4059/10000 [13:02<21:50,  4.53step/s, loss=0.032263, elapsed=13.0min]

Entraînement:  41%|████      | 4060/10000 [13:02<20:57,  4.72step/s, loss=0.032263, elapsed=13.0min]

Entraînement:  41%|████      | 4060/10000 [13:02<20:57,  4.72step/s, loss=0.048732, elapsed=13.0min]

Entraînement:  41%|████      | 4061/10000 [13:02<20:21,  4.86step/s, loss=0.048732, elapsed=13.0min]

Entraînement:  41%|████      | 4061/10000 [13:02<20:21,  4.86step/s, loss=0.052164, elapsed=13.0min]

Entraînement:  41%|████      | 4062/10000 [13:03<19:54,  4.97step/s, loss=0.052164, elapsed=13.0min]

Entraînement:  41%|████      | 4062/10000 [13:03<19:54,  4.97step/s, loss=0.030095, elapsed=13.1min]

Entraînement:  41%|████      | 4063/10000 [13:03<19:33,  5.06step/s, loss=0.030095, elapsed=13.1min]

Entraînement:  41%|████      | 4063/10000 [13:03<19:33,  5.06step/s, loss=0.037005, elapsed=13.1min]

Entraînement:  41%|████      | 4064/10000 [13:03<19:19,  5.12step/s, loss=0.037005, elapsed=13.1min]

Entraînement:  41%|████      | 4064/10000 [13:03<19:19,  5.12step/s, loss=0.023468, elapsed=13.1min]

Entraînement:  41%|████      | 4065/10000 [13:03<19:13,  5.15step/s, loss=0.023468, elapsed=13.1min]

Entraînement:  41%|████      | 4065/10000 [13:03<19:13,  5.15step/s, loss=0.026272, elapsed=13.1min]

Entraînement:  41%|████      | 4066/10000 [13:03<19:05,  5.18step/s, loss=0.026272, elapsed=13.1min]

Entraînement:  41%|████      | 4066/10000 [13:03<19:05,  5.18step/s, loss=0.052905, elapsed=13.1min]

Entraînement:  41%|████      | 4067/10000 [13:03<18:58,  5.21step/s, loss=0.052905, elapsed=13.1min]

Entraînement:  41%|████      | 4067/10000 [13:03<18:58,  5.21step/s, loss=0.074496, elapsed=13.1min]

Entraînement:  41%|████      | 4068/10000 [13:04<18:53,  5.23step/s, loss=0.074496, elapsed=13.1min]

Entraînement:  41%|████      | 4068/10000 [13:04<18:53,  5.23step/s, loss=0.023625, elapsed=13.1min]

Entraînement:  41%|████      | 4069/10000 [13:04<18:50,  5.25step/s, loss=0.023625, elapsed=13.1min]

Entraînement:  41%|████      | 4069/10000 [13:04<18:50,  5.25step/s, loss=0.044111, elapsed=13.1min]

Entraînement:  41%|████      | 4070/10000 [13:04<18:48,  5.25step/s, loss=0.044111, elapsed=13.1min]

Entraînement:  41%|████      | 4070/10000 [13:04<18:48,  5.25step/s, loss=0.041663, elapsed=13.1min]

Entraînement:  41%|████      | 4071/10000 [13:04<18:48,  5.25step/s, loss=0.041663, elapsed=13.1min]

Entraînement:  41%|████      | 4071/10000 [13:04<18:48,  5.25step/s, loss=0.073507, elapsed=13.1min]

Entraînement:  41%|████      | 4072/10000 [13:04<18:45,  5.27step/s, loss=0.073507, elapsed=13.1min]

Entraînement:  41%|████      | 4072/10000 [13:04<18:45,  5.27step/s, loss=0.040287, elapsed=13.1min]

Entraînement:  41%|████      | 4073/10000 [13:05<18:44,  5.27step/s, loss=0.040287, elapsed=13.1min]

Entraînement:  41%|████      | 4073/10000 [13:05<18:44,  5.27step/s, loss=0.024566, elapsed=13.1min]

Entraînement:  41%|████      | 4074/10000 [13:05<18:42,  5.28step/s, loss=0.024566, elapsed=13.1min]

Entraînement:  41%|████      | 4074/10000 [13:05<18:42,  5.28step/s, loss=0.024886, elapsed=13.1min]

Entraînement:  41%|████      | 4075/10000 [13:05<18:42,  5.28step/s, loss=0.024886, elapsed=13.1min]

Entraînement:  41%|████      | 4075/10000 [13:05<18:42,  5.28step/s, loss=0.076931, elapsed=13.1min]

Entraînement:  41%|████      | 4076/10000 [13:05<18:41,  5.28step/s, loss=0.076931, elapsed=13.1min]

Entraînement:  41%|████      | 4076/10000 [13:05<18:41,  5.28step/s, loss=0.036459, elapsed=13.1min]

Entraînement:  41%|████      | 4077/10000 [13:05<18:42,  5.28step/s, loss=0.036459, elapsed=13.1min]

Entraînement:  41%|████      | 4077/10000 [13:05<18:42,  5.28step/s, loss=0.036549, elapsed=13.1min]

Entraînement:  41%|████      | 4078/10000 [13:06<18:42,  5.28step/s, loss=0.036549, elapsed=13.1min]

Entraînement:  41%|████      | 4078/10000 [13:06<18:42,  5.28step/s, loss=0.030656, elapsed=13.1min]

Entraînement:  41%|████      | 4079/10000 [13:06<18:39,  5.29step/s, loss=0.030656, elapsed=13.1min]

Entraînement:  41%|████      | 4079/10000 [13:06<18:39,  5.29step/s, loss=0.070375, elapsed=13.1min]

Entraînement:  41%|████      | 4080/10000 [13:06<18:40,  5.28step/s, loss=0.070375, elapsed=13.1min]

Entraînement:  41%|████      | 4080/10000 [13:06<18:40,  5.28step/s, loss=0.057400, elapsed=13.1min]

Entraînement:  41%|████      | 4081/10000 [13:06<18:39,  5.29step/s, loss=0.057400, elapsed=13.1min]

Entraînement:  41%|████      | 4081/10000 [13:06<18:39,  5.29step/s, loss=0.055085, elapsed=13.1min]

Entraînement:  41%|████      | 4082/10000 [13:06<18:39,  5.29step/s, loss=0.055085, elapsed=13.1min]

Entraînement:  41%|████      | 4082/10000 [13:06<18:39,  5.29step/s, loss=0.066260, elapsed=13.1min]

Entraînement:  41%|████      | 4083/10000 [13:07<18:42,  5.27step/s, loss=0.066260, elapsed=13.1min]

Entraînement:  41%|████      | 4083/10000 [13:07<18:42,  5.27step/s, loss=0.043657, elapsed=13.1min]

Entraînement:  41%|████      | 4084/10000 [13:07<18:38,  5.29step/s, loss=0.043657, elapsed=13.1min]

Entraînement:  41%|████      | 4084/10000 [13:07<18:38,  5.29step/s, loss=0.032897, elapsed=13.1min]

Entraînement:  41%|████      | 4085/10000 [13:07<18:40,  5.28step/s, loss=0.032897, elapsed=13.1min]

Entraînement:  41%|████      | 4085/10000 [13:07<18:40,  5.28step/s, loss=0.034744, elapsed=13.1min]

Entraînement:  41%|████      | 4086/10000 [13:07<18:38,  5.29step/s, loss=0.034744, elapsed=13.1min]

Entraînement:  41%|████      | 4086/10000 [13:07<18:38,  5.29step/s, loss=0.044365, elapsed=13.1min]

Entraînement:  41%|████      | 4087/10000 [13:07<18:39,  5.28step/s, loss=0.044365, elapsed=13.1min]

Entraînement:  41%|████      | 4087/10000 [13:07<18:39,  5.28step/s, loss=0.021775, elapsed=13.1min]

Entraînement:  41%|████      | 4088/10000 [13:07<18:39,  5.28step/s, loss=0.021775, elapsed=13.1min]

Entraînement:  41%|████      | 4088/10000 [13:07<18:39,  5.28step/s, loss=0.081223, elapsed=13.1min]

Entraînement:  41%|████      | 4089/10000 [13:08<18:38,  5.28step/s, loss=0.081223, elapsed=13.1min]

Entraînement:  41%|████      | 4089/10000 [13:08<18:38,  5.28step/s, loss=0.034061, elapsed=13.1min]

Entraînement:  41%|████      | 4090/10000 [13:08<18:38,  5.29step/s, loss=0.034061, elapsed=13.1min]

Entraînement:  41%|████      | 4090/10000 [13:08<18:38,  5.29step/s, loss=0.031544, elapsed=13.1min]

Entraînement:  41%|████      | 4091/10000 [13:08<18:38,  5.28step/s, loss=0.031544, elapsed=13.1min]

Entraînement:  41%|████      | 4091/10000 [13:08<18:38,  5.28step/s, loss=0.038373, elapsed=13.1min]

Entraînement:  41%|████      | 4092/10000 [13:08<18:41,  5.27step/s, loss=0.038373, elapsed=13.1min]

Entraînement:  41%|████      | 4092/10000 [13:08<18:41,  5.27step/s, loss=0.040704, elapsed=13.1min]

Entraînement:  41%|████      | 4093/10000 [13:08<18:43,  5.26step/s, loss=0.040704, elapsed=13.1min]

Entraînement:  41%|████      | 4093/10000 [13:08<18:43,  5.26step/s, loss=0.031433, elapsed=13.1min]

Entraînement:  41%|████      | 4094/10000 [13:09<18:46,  5.24step/s, loss=0.031433, elapsed=13.1min]

Entraînement:  41%|████      | 4094/10000 [13:09<18:46,  5.24step/s, loss=0.050727, elapsed=13.2min]

Entraînement:  41%|████      | 4095/10000 [13:09<18:44,  5.25step/s, loss=0.050727, elapsed=13.2min]

Entraînement:  41%|████      | 4095/10000 [13:09<18:44,  5.25step/s, loss=0.041224, elapsed=13.2min]

Entraînement:  41%|████      | 4096/10000 [13:09<18:42,  5.26step/s, loss=0.041224, elapsed=13.2min]

Entraînement:  41%|████      | 4096/10000 [13:09<18:42,  5.26step/s, loss=0.041642, elapsed=13.2min]

Entraînement:  41%|████      | 4097/10000 [13:09<18:40,  5.27step/s, loss=0.041642, elapsed=13.2min]

Entraînement:  41%|████      | 4097/10000 [13:09<18:40,  5.27step/s, loss=0.088078, elapsed=13.2min]

Entraînement:  41%|████      | 4098/10000 [13:09<18:39,  5.27step/s, loss=0.088078, elapsed=13.2min]

Entraînement:  41%|████      | 4098/10000 [13:09<18:39,  5.27step/s, loss=0.049531, elapsed=13.2min]

Entraînement:  41%|████      | 4099/10000 [13:10<18:40,  5.27step/s, loss=0.049531, elapsed=13.2min]

Entraînement:  41%|████      | 4099/10000 [13:10<18:40,  5.27step/s, loss=0.061095, elapsed=13.2min]

Entraînement:  41%|████      | 4100/10000 [13:10<18:41,  5.26step/s, loss=0.061095, elapsed=13.2min]

Entraînement:  41%|████      | 4100/10000 [13:10<18:41,  5.26step/s, loss=0.112685, elapsed=13.2min]

Entraînement:  41%|████      | 4100/10000 [13:10<18:41,  5.26step/s, loss=0.112685, elapsed=13.2min]

Entraînement:  41%|████      | 4101/10000 [13:10<18:52,  5.21step/s, loss=0.112685, elapsed=13.2min]

Entraînement:  41%|████      | 4101/10000 [13:10<18:52,  5.21step/s, loss=0.038388, elapsed=13.2min]

Step 4100/10000 | Train loss: 0.112685 | Elapsed: 13.2min | ETA: 19.0min

Entraînement:  41%|████      | 4102/10000 [13:10<18:51,  5.21step/s, loss=0.038388, elapsed=13.2min]

Entraînement:  41%|████      | 4102/10000 [13:10<18:51,  5.21step/s, loss=0.058951, elapsed=13.2min]

Entraînement:  41%|████      | 4103/10000 [13:10<18:47,  5.23step/s, loss=0.058951, elapsed=13.2min]

Entraînement:  41%|████      | 4103/10000 [13:10<18:47,  5.23step/s, loss=0.033993, elapsed=13.2min]

Entraînement:  41%|████      | 4104/10000 [13:11<18:44,  5.24step/s, loss=0.033993, elapsed=13.2min]

Entraînement:  41%|████      | 4104/10000 [13:11<18:44,  5.24step/s, loss=0.152759, elapsed=13.2min]

Entraînement:  41%|████      | 4105/10000 [13:11<18:41,  5.26step/s, loss=0.152759, elapsed=13.2min]

Entraînement:  41%|████      | 4105/10000 [13:11<18:41,  5.26step/s, loss=0.022150, elapsed=13.2min]

Entraînement:  41%|████      | 4106/10000 [13:11<18:38,  5.27step/s, loss=0.022150, elapsed=13.2min]

Entraînement:  41%|████      | 4106/10000 [13:11<18:38,  5.27step/s, loss=0.025443, elapsed=13.2min]

Entraînement:  41%|████      | 4107/10000 [13:11<18:41,  5.26step/s, loss=0.025443, elapsed=13.2min]

Entraînement:  41%|████      | 4107/10000 [13:11<18:41,  5.26step/s, loss=0.061523, elapsed=13.2min]

Entraînement:  41%|████      | 4108/10000 [13:11<18:41,  5.26step/s, loss=0.061523, elapsed=13.2min]

Entraînement:  41%|████      | 4108/10000 [13:11<18:41,  5.26step/s, loss=0.109300, elapsed=13.2min]

Entraînement:  41%|████      | 4109/10000 [13:11<18:40,  5.26step/s, loss=0.109300, elapsed=13.2min]

Entraînement:  41%|████      | 4109/10000 [13:11<18:40,  5.26step/s, loss=0.033890, elapsed=13.2min]

Entraînement:  41%|████      | 4110/10000 [13:12<18:39,  5.26step/s, loss=0.033890, elapsed=13.2min]

Entraînement:  41%|████      | 4110/10000 [13:12<18:39,  5.26step/s, loss=0.068299, elapsed=13.2min]

Entraînement:  41%|████      | 4111/10000 [13:12<18:36,  5.27step/s, loss=0.068299, elapsed=13.2min]

Entraînement:  41%|████      | 4111/10000 [13:12<18:36,  5.27step/s, loss=0.080131, elapsed=13.2min]

Entraînement:  41%|████      | 4112/10000 [13:12<24:05,  4.07step/s, loss=0.080131, elapsed=13.2min]

Entraînement:  41%|████      | 4112/10000 [13:12<24:05,  4.07step/s, loss=0.056573, elapsed=13.2min]

Entraînement:  41%|████      | 4113/10000 [13:12<22:21,  4.39step/s, loss=0.056573, elapsed=13.2min]

Entraînement:  41%|████      | 4113/10000 [13:12<22:21,  4.39step/s, loss=0.033132, elapsed=13.2min]

Entraînement:  41%|████      | 4114/10000 [13:13<21:14,  4.62step/s, loss=0.033132, elapsed=13.2min]

Entraînement:  41%|████      | 4114/10000 [13:13<21:14,  4.62step/s, loss=0.073878, elapsed=13.2min]

Entraînement:  41%|████      | 4115/10000 [13:13<20:28,  4.79step/s, loss=0.073878, elapsed=13.2min]

Entraînement:  41%|████      | 4115/10000 [13:13<20:28,  4.79step/s, loss=0.066211, elapsed=13.2min]

Entraînement:  41%|████      | 4116/10000 [13:13<19:55,  4.92step/s, loss=0.066211, elapsed=13.2min]

Entraînement:  41%|████      | 4116/10000 [13:13<19:55,  4.92step/s, loss=0.049243, elapsed=13.2min]

Entraînement:  41%|████      | 4117/10000 [13:13<19:29,  5.03step/s, loss=0.049243, elapsed=13.2min]

Entraînement:  41%|████      | 4117/10000 [13:13<19:29,  5.03step/s, loss=0.042299, elapsed=13.2min]

Entraînement:  41%|████      | 4118/10000 [13:13<19:10,  5.11step/s, loss=0.042299, elapsed=13.2min]

Entraînement:  41%|████      | 4118/10000 [13:13<19:10,  5.11step/s, loss=0.034069, elapsed=13.2min]

Entraînement:  41%|████      | 4119/10000 [13:14<19:16,  5.08step/s, loss=0.034069, elapsed=13.2min]

Entraînement:  41%|████      | 4119/10000 [13:14<19:16,  5.08step/s, loss=0.030160, elapsed=13.2min]

Entraînement:  41%|████      | 4120/10000 [13:14<19:04,  5.14step/s, loss=0.030160, elapsed=13.2min]

Entraînement:  41%|████      | 4120/10000 [13:14<19:04,  5.14step/s, loss=0.096168, elapsed=13.2min]

Entraînement:  41%|████      | 4121/10000 [13:14<18:54,  5.18step/s, loss=0.096168, elapsed=13.2min]

Entraînement:  41%|████      | 4121/10000 [13:14<18:54,  5.18step/s, loss=0.118475, elapsed=13.2min]

Entraînement:  41%|████      | 4122/10000 [13:14<18:51,  5.20step/s, loss=0.118475, elapsed=13.2min]

Entraînement:  41%|████      | 4122/10000 [13:14<18:51,  5.20step/s, loss=0.037255, elapsed=13.2min]

Entraînement:  41%|████      | 4123/10000 [13:14<18:45,  5.22step/s, loss=0.037255, elapsed=13.2min]

Entraînement:  41%|████      | 4123/10000 [13:14<18:45,  5.22step/s, loss=0.032331, elapsed=13.2min]

Entraînement:  41%|████      | 4124/10000 [13:15<18:43,  5.23step/s, loss=0.032331, elapsed=13.2min]

Entraînement:  41%|████      | 4124/10000 [13:15<18:43,  5.23step/s, loss=0.039689, elapsed=13.3min]

Entraînement:  41%|████▏     | 4125/10000 [13:15<18:40,  5.24step/s, loss=0.039689, elapsed=13.3min]

Entraînement:  41%|████▏     | 4125/10000 [13:15<18:40,  5.24step/s, loss=0.038255, elapsed=13.3min]

Entraînement:  41%|████▏     | 4126/10000 [13:15<18:37,  5.26step/s, loss=0.038255, elapsed=13.3min]

Entraînement:  41%|████▏     | 4126/10000 [13:15<18:37,  5.26step/s, loss=0.045410, elapsed=13.3min]

Entraînement:  41%|████▏     | 4127/10000 [13:15<18:36,  5.26step/s, loss=0.045410, elapsed=13.3min]

Entraînement:  41%|████▏     | 4127/10000 [13:15<18:36,  5.26step/s, loss=0.049522, elapsed=13.3min]

Entraînement:  41%|████▏     | 4128/10000 [13:15<18:33,  5.27step/s, loss=0.049522, elapsed=13.3min]

Entraînement:  41%|████▏     | 4128/10000 [13:15<18:33,  5.27step/s, loss=0.058826, elapsed=13.3min]

Entraînement:  41%|████▏     | 4129/10000 [13:15<18:34,  5.27step/s, loss=0.058826, elapsed=13.3min]

Entraînement:  41%|████▏     | 4129/10000 [13:15<18:34,  5.27step/s, loss=0.048895, elapsed=13.3min]

Entraînement:  41%|████▏     | 4130/10000 [13:16<18:33,  5.27step/s, loss=0.048895, elapsed=13.3min]

Entraînement:  41%|████▏     | 4130/10000 [13:16<18:33,  5.27step/s, loss=0.078683, elapsed=13.3min]

Entraînement:  41%|████▏     | 4131/10000 [13:16<18:34,  5.27step/s, loss=0.078683, elapsed=13.3min]

Entraînement:  41%|████▏     | 4131/10000 [13:16<18:34,  5.27step/s, loss=0.080271, elapsed=13.3min]

Entraînement:  41%|████▏     | 4132/10000 [13:16<18:34,  5.27step/s, loss=0.080271, elapsed=13.3min]

Entraînement:  41%|████▏     | 4132/10000 [13:16<18:34,  5.27step/s, loss=0.050590, elapsed=13.3min]

Entraînement:  41%|████▏     | 4133/10000 [13:16<18:32,  5.27step/s, loss=0.050590, elapsed=13.3min]

Entraînement:  41%|████▏     | 4133/10000 [13:16<18:32,  5.27step/s, loss=0.047191, elapsed=13.3min]

Entraînement:  41%|████▏     | 4134/10000 [13:16<18:32,  5.27step/s, loss=0.047191, elapsed=13.3min]

Entraînement:  41%|████▏     | 4134/10000 [13:16<18:32,  5.27step/s, loss=0.045342, elapsed=13.3min]

Entraînement:  41%|████▏     | 4135/10000 [13:17<18:30,  5.28step/s, loss=0.045342, elapsed=13.3min]

Entraînement:  41%|████▏     | 4135/10000 [13:17<18:30,  5.28step/s, loss=0.041070, elapsed=13.3min]

Entraînement:  41%|████▏     | 4136/10000 [13:17<18:31,  5.28step/s, loss=0.041070, elapsed=13.3min]

Entraînement:  41%|████▏     | 4136/10000 [13:17<18:31,  5.28step/s, loss=0.038743, elapsed=13.3min]

Entraînement:  41%|████▏     | 4137/10000 [13:17<18:32,  5.27step/s, loss=0.038743, elapsed=13.3min]

Entraînement:  41%|████▏     | 4137/10000 [13:17<18:32,  5.27step/s, loss=0.035741, elapsed=13.3min]

Entraînement:  41%|████▏     | 4138/10000 [13:17<18:33,  5.26step/s, loss=0.035741, elapsed=13.3min]

Entraînement:  41%|████▏     | 4138/10000 [13:17<18:33,  5.26step/s, loss=0.031909, elapsed=13.3min]

Entraînement:  41%|████▏     | 4139/10000 [13:17<18:33,  5.26step/s, loss=0.031909, elapsed=13.3min]

Entraînement:  41%|████▏     | 4139/10000 [13:17<18:33,  5.26step/s, loss=0.035559, elapsed=13.3min]

Entraînement:  41%|████▏     | 4140/10000 [13:18<18:33,  5.26step/s, loss=0.035559, elapsed=13.3min]

Entraînement:  41%|████▏     | 4140/10000 [13:18<18:33,  5.26step/s, loss=0.038987, elapsed=13.3min]

Entraînement:  41%|████▏     | 4141/10000 [13:18<18:33,  5.26step/s, loss=0.038987, elapsed=13.3min]

Entraînement:  41%|████▏     | 4141/10000 [13:18<18:33,  5.26step/s, loss=0.061699, elapsed=13.3min]

Entraînement:  41%|████▏     | 4142/10000 [13:18<18:31,  5.27step/s, loss=0.061699, elapsed=13.3min]

Entraînement:  41%|████▏     | 4142/10000 [13:18<18:31,  5.27step/s, loss=0.050184, elapsed=13.3min]

Entraînement:  41%|████▏     | 4143/10000 [13:18<18:32,  5.26step/s, loss=0.050184, elapsed=13.3min]

Entraînement:  41%|████▏     | 4143/10000 [13:18<18:32,  5.26step/s, loss=0.087410, elapsed=13.3min]

Entraînement:  41%|████▏     | 4144/10000 [13:18<18:31,  5.27step/s, loss=0.087410, elapsed=13.3min]

Entraînement:  41%|████▏     | 4144/10000 [13:18<18:31,  5.27step/s, loss=0.047154, elapsed=13.3min]

Entraînement:  41%|████▏     | 4145/10000 [13:18<18:34,  5.25step/s, loss=0.047154, elapsed=13.3min]

Entraînement:  41%|████▏     | 4145/10000 [13:18<18:34,  5.25step/s, loss=0.016883, elapsed=13.3min]

Entraînement:  41%|████▏     | 4146/10000 [13:19<18:32,  5.26step/s, loss=0.016883, elapsed=13.3min]

Entraînement:  41%|████▏     | 4146/10000 [13:19<18:32,  5.26step/s, loss=0.093008, elapsed=13.3min]

Entraînement:  41%|████▏     | 4147/10000 [13:19<18:32,  5.26step/s, loss=0.093008, elapsed=13.3min]

Entraînement:  41%|████▏     | 4147/10000 [13:19<18:32,  5.26step/s, loss=0.037855, elapsed=13.3min]

Entraînement:  41%|████▏     | 4148/10000 [13:19<18:30,  5.27step/s, loss=0.037855, elapsed=13.3min]

Entraînement:  41%|████▏     | 4148/10000 [13:19<18:30,  5.27step/s, loss=0.027389, elapsed=13.3min]

Entraînement:  41%|████▏     | 4149/10000 [13:19<18:30,  5.27step/s, loss=0.027389, elapsed=13.3min]

Entraînement:  41%|████▏     | 4149/10000 [13:19<18:30,  5.27step/s, loss=0.036043, elapsed=13.3min]

Entraînement:  42%|████▏     | 4150/10000 [13:19<18:29,  5.27step/s, loss=0.036043, elapsed=13.3min]

Entraînement:  42%|████▏     | 4150/10000 [13:19<18:29,  5.27step/s, loss=0.017365, elapsed=13.3min]

Entraînement:  42%|████▏     | 4151/10000 [13:20<18:30,  5.27step/s, loss=0.017365, elapsed=13.3min]

Entraînement:  42%|████▏     | 4151/10000 [13:20<18:30,  5.27step/s, loss=0.048374, elapsed=13.3min]

Entraînement:  42%|████▏     | 4152/10000 [13:20<18:32,  5.26step/s, loss=0.048374, elapsed=13.3min]

Entraînement:  42%|████▏     | 4152/10000 [13:20<18:32,  5.26step/s, loss=0.043076, elapsed=13.3min]

Entraînement:  42%|████▏     | 4153/10000 [13:20<18:32,  5.26step/s, loss=0.043076, elapsed=13.3min]

Entraînement:  42%|████▏     | 4153/10000 [13:20<18:32,  5.26step/s, loss=0.038673, elapsed=13.3min]

Entraînement:  42%|████▏     | 4154/10000 [13:20<18:32,  5.26step/s, loss=0.038673, elapsed=13.3min]

Entraînement:  42%|████▏     | 4154/10000 [13:20<18:32,  5.26step/s, loss=0.035246, elapsed=13.3min]

Entraînement:  42%|████▏     | 4155/10000 [13:20<18:30,  5.26step/s, loss=0.035246, elapsed=13.3min]

Entraînement:  42%|████▏     | 4155/10000 [13:20<18:30,  5.26step/s, loss=0.066595, elapsed=13.3min]

Entraînement:  42%|████▏     | 4156/10000 [13:21<18:29,  5.27step/s, loss=0.066595, elapsed=13.3min]

Entraînement:  42%|████▏     | 4156/10000 [13:21<18:29,  5.27step/s, loss=0.033865, elapsed=13.4min]

Entraînement:  42%|████▏     | 4157/10000 [13:21<18:28,  5.27step/s, loss=0.033865, elapsed=13.4min]

Entraînement:  42%|████▏     | 4157/10000 [13:21<18:28,  5.27step/s, loss=0.061673, elapsed=13.4min]

Entraînement:  42%|████▏     | 4158/10000 [13:21<18:27,  5.28step/s, loss=0.061673, elapsed=13.4min]

Entraînement:  42%|████▏     | 4158/10000 [13:21<18:27,  5.28step/s, loss=0.056748, elapsed=13.4min]

Entraînement:  42%|████▏     | 4159/10000 [13:21<18:27,  5.28step/s, loss=0.056748, elapsed=13.4min]

Entraînement:  42%|████▏     | 4159/10000 [13:21<18:27,  5.28step/s, loss=0.054634, elapsed=13.4min]

Entraînement:  42%|████▏     | 4160/10000 [13:21<18:27,  5.27step/s, loss=0.054634, elapsed=13.4min]

Entraînement:  42%|████▏     | 4160/10000 [13:21<18:27,  5.27step/s, loss=0.034404, elapsed=13.4min]

Entraînement:  42%|████▏     | 4161/10000 [13:22<18:28,  5.27step/s, loss=0.034404, elapsed=13.4min]

Entraînement:  42%|████▏     | 4161/10000 [13:22<18:28,  5.27step/s, loss=0.058267, elapsed=13.4min]

Entraînement:  42%|████▏     | 4162/10000 [13:22<18:26,  5.27step/s, loss=0.058267, elapsed=13.4min]

Entraînement:  42%|████▏     | 4162/10000 [13:22<18:26,  5.27step/s, loss=0.031617, elapsed=13.4min]

Entraînement:  42%|████▏     | 4163/10000 [13:22<18:27,  5.27step/s, loss=0.031617, elapsed=13.4min]

Entraînement:  42%|████▏     | 4163/10000 [13:22<18:27,  5.27step/s, loss=0.033643, elapsed=13.4min]

Entraînement:  42%|████▏     | 4164/10000 [13:22<18:21,  5.30step/s, loss=0.033643, elapsed=13.4min]

Entraînement:  42%|████▏     | 4164/10000 [13:22<18:21,  5.30step/s, loss=0.067031, elapsed=13.4min]

Entraînement:  42%|████▏     | 4165/10000 [13:22<18:21,  5.30step/s, loss=0.067031, elapsed=13.4min]

Entraînement:  42%|████▏     | 4165/10000 [13:22<18:21,  5.30step/s, loss=0.042631, elapsed=13.4min]

Entraînement:  42%|████▏     | 4166/10000 [13:22<18:21,  5.30step/s, loss=0.042631, elapsed=13.4min]

Entraînement:  42%|████▏     | 4166/10000 [13:22<18:21,  5.30step/s, loss=0.028779, elapsed=13.4min]

Entraînement:  42%|████▏     | 4167/10000 [13:23<18:22,  5.29step/s, loss=0.028779, elapsed=13.4min]

Entraînement:  42%|████▏     | 4167/10000 [13:23<18:22,  5.29step/s, loss=0.079203, elapsed=13.4min]

Entraînement:  42%|████▏     | 4168/10000 [13:23<18:25,  5.28step/s, loss=0.079203, elapsed=13.4min]

Entraînement:  42%|████▏     | 4168/10000 [13:23<18:25,  5.28step/s, loss=0.024887, elapsed=13.4min]

Entraînement:  42%|████▏     | 4169/10000 [13:23<18:24,  5.28step/s, loss=0.024887, elapsed=13.4min]

Entraînement:  42%|████▏     | 4169/10000 [13:23<18:24,  5.28step/s, loss=0.104720, elapsed=13.4min]

Entraînement:  42%|████▏     | 4170/10000 [13:23<18:25,  5.27step/s, loss=0.104720, elapsed=13.4min]

Entraînement:  42%|████▏     | 4170/10000 [13:23<18:25,  5.27step/s, loss=0.063842, elapsed=13.4min]

Entraînement:  42%|████▏     | 4171/10000 [13:23<18:25,  5.27step/s, loss=0.063842, elapsed=13.4min]

Entraînement:  42%|████▏     | 4171/10000 [13:23<18:25,  5.27step/s, loss=0.090092, elapsed=13.4min]

Entraînement:  42%|████▏     | 4172/10000 [13:24<18:23,  5.28step/s, loss=0.090092, elapsed=13.4min]

Entraînement:  42%|████▏     | 4172/10000 [13:24<18:23,  5.28step/s, loss=0.076985, elapsed=13.4min]

Entraînement:  42%|████▏     | 4173/10000 [13:24<18:22,  5.28step/s, loss=0.076985, elapsed=13.4min]

Entraînement:  42%|████▏     | 4173/10000 [13:24<18:22,  5.28step/s, loss=0.136658, elapsed=13.4min]

Entraînement:  42%|████▏     | 4174/10000 [13:24<18:21,  5.29step/s, loss=0.136658, elapsed=13.4min]

Entraînement:  42%|████▏     | 4174/10000 [13:24<18:21,  5.29step/s, loss=0.044125, elapsed=13.4min]

Entraînement:  42%|████▏     | 4175/10000 [13:24<18:23,  5.28step/s, loss=0.044125, elapsed=13.4min]

Entraînement:  42%|████▏     | 4175/10000 [13:24<18:23,  5.28step/s, loss=0.022347, elapsed=13.4min]

Entraînement:  42%|████▏     | 4176/10000 [13:24<18:28,  5.25step/s, loss=0.022347, elapsed=13.4min]

Entraînement:  42%|████▏     | 4176/10000 [13:24<18:28,  5.25step/s, loss=0.043344, elapsed=13.4min]

Entraînement:  42%|████▏     | 4177/10000 [13:25<18:28,  5.25step/s, loss=0.043344, elapsed=13.4min]

Entraînement:  42%|████▏     | 4177/10000 [13:25<18:28,  5.25step/s, loss=0.031772, elapsed=13.4min]

Entraînement:  42%|████▏     | 4178/10000 [13:25<18:26,  5.26step/s, loss=0.031772, elapsed=13.4min]

Entraînement:  42%|████▏     | 4178/10000 [13:25<18:26,  5.26step/s, loss=0.049925, elapsed=13.4min]

Entraînement:  42%|████▏     | 4179/10000 [13:25<18:24,  5.27step/s, loss=0.049925, elapsed=13.4min]

Entraînement:  42%|████▏     | 4179/10000 [13:25<18:24,  5.27step/s, loss=0.021210, elapsed=13.4min]

Entraînement:  42%|████▏     | 4180/10000 [13:25<18:22,  5.28step/s, loss=0.021210, elapsed=13.4min]

Entraînement:  42%|████▏     | 4180/10000 [13:25<18:22,  5.28step/s, loss=0.029251, elapsed=13.4min]

Entraînement:  42%|████▏     | 4181/10000 [13:25<18:21,  5.28step/s, loss=0.029251, elapsed=13.4min]

Entraînement:  42%|████▏     | 4181/10000 [13:25<18:21,  5.28step/s, loss=0.034445, elapsed=13.4min]

Entraînement:  42%|████▏     | 4182/10000 [13:26<18:22,  5.28step/s, loss=0.034445, elapsed=13.4min]

Entraînement:  42%|████▏     | 4182/10000 [13:26<18:22,  5.28step/s, loss=0.091656, elapsed=13.4min]

Entraînement:  42%|████▏     | 4183/10000 [13:26<18:22,  5.27step/s, loss=0.091656, elapsed=13.4min]

Entraînement:  42%|████▏     | 4183/10000 [13:26<18:22,  5.27step/s, loss=0.029418, elapsed=13.4min]

Entraînement:  42%|████▏     | 4184/10000 [13:26<18:21,  5.28step/s, loss=0.029418, elapsed=13.4min]

Entraînement:  42%|████▏     | 4184/10000 [13:26<18:21,  5.28step/s, loss=0.026489, elapsed=13.4min]

Entraînement:  42%|████▏     | 4185/10000 [13:26<18:21,  5.28step/s, loss=0.026489, elapsed=13.4min]

Entraînement:  42%|████▏     | 4185/10000 [13:26<18:21,  5.28step/s, loss=0.058360, elapsed=13.4min]

Entraînement:  42%|████▏     | 4186/10000 [13:26<18:19,  5.29step/s, loss=0.058360, elapsed=13.4min]

Entraînement:  42%|████▏     | 4186/10000 [13:26<18:19,  5.29step/s, loss=0.086331, elapsed=13.4min]

Entraînement:  42%|████▏     | 4187/10000 [13:26<18:20,  5.28step/s, loss=0.086331, elapsed=13.4min]

Entraînement:  42%|████▏     | 4187/10000 [13:26<18:20,  5.28step/s, loss=0.027000, elapsed=13.4min]

Entraînement:  42%|████▏     | 4188/10000 [13:27<18:19,  5.29step/s, loss=0.027000, elapsed=13.4min]

Entraînement:  42%|████▏     | 4188/10000 [13:27<18:19,  5.29step/s, loss=0.082879, elapsed=13.5min]

Entraînement:  42%|████▏     | 4189/10000 [13:27<18:19,  5.28step/s, loss=0.082879, elapsed=13.5min]

Entraînement:  42%|████▏     | 4189/10000 [13:27<18:19,  5.28step/s, loss=0.035184, elapsed=13.5min]

Entraînement:  42%|████▏     | 4190/10000 [13:27<18:19,  5.29step/s, loss=0.035184, elapsed=13.5min]

Entraînement:  42%|████▏     | 4190/10000 [13:27<18:19,  5.29step/s, loss=0.075437, elapsed=13.5min]

Entraînement:  42%|████▏     | 4191/10000 [13:27<18:18,  5.29step/s, loss=0.075437, elapsed=13.5min]

Entraînement:  42%|████▏     | 4191/10000 [13:27<18:18,  5.29step/s, loss=0.060618, elapsed=13.5min]

Entraînement:  42%|████▏     | 4192/10000 [13:27<18:20,  5.28step/s, loss=0.060618, elapsed=13.5min]

Entraînement:  42%|████▏     | 4192/10000 [13:27<18:20,  5.28step/s, loss=0.066087, elapsed=13.5min]

Entraînement:  42%|████▏     | 4193/10000 [13:28<18:20,  5.28step/s, loss=0.066087, elapsed=13.5min]

Entraînement:  42%|████▏     | 4193/10000 [13:28<18:20,  5.28step/s, loss=0.037752, elapsed=13.5min]

Entraînement:  42%|████▏     | 4194/10000 [13:28<18:20,  5.28step/s, loss=0.037752, elapsed=13.5min]

Entraînement:  42%|████▏     | 4194/10000 [13:28<18:20,  5.28step/s, loss=0.041002, elapsed=13.5min]

Entraînement:  42%|████▏     | 4195/10000 [13:28<18:19,  5.28step/s, loss=0.041002, elapsed=13.5min]

Entraînement:  42%|████▏     | 4195/10000 [13:28<18:19,  5.28step/s, loss=0.039049, elapsed=13.5min]

Entraînement:  42%|████▏     | 4196/10000 [13:28<18:22,  5.26step/s, loss=0.039049, elapsed=13.5min]

Entraînement:  42%|████▏     | 4196/10000 [13:28<18:22,  5.26step/s, loss=0.071501, elapsed=13.5min]

Entraînement:  42%|████▏     | 4197/10000 [13:28<18:20,  5.27step/s, loss=0.071501, elapsed=13.5min]

Entraînement:  42%|████▏     | 4197/10000 [13:28<18:20,  5.27step/s, loss=0.019377, elapsed=13.5min]

Entraînement:  42%|████▏     | 4198/10000 [13:29<18:23,  5.26step/s, loss=0.019377, elapsed=13.5min]

Entraînement:  42%|████▏     | 4198/10000 [13:29<18:23,  5.26step/s, loss=0.039126, elapsed=13.5min]

Entraînement:  42%|████▏     | 4199/10000 [13:29<18:24,  5.25step/s, loss=0.039126, elapsed=13.5min]

Entraînement:  42%|████▏     | 4199/10000 [13:29<18:24,  5.25step/s, loss=0.042470, elapsed=13.5min]

Entraînement:  42%|████▏     | 4200/10000 [13:29<18:24,  5.25step/s, loss=0.042470, elapsed=13.5min]

Entraînement:  42%|████▏     | 4200/10000 [13:29<18:24,  5.25step/s, loss=0.054500, elapsed=13.5min]

Entraînement:  42%|████▏     | 4200/10000 [13:29<18:24,  5.25step/s, loss=0.054500, elapsed=13.5min]

Entraînement:  42%|████▏     | 4201/10000 [13:29<18:31,  5.22step/s, loss=0.054500, elapsed=13.5min]

Entraînement:  42%|████▏     | 4201/10000 [13:29<18:31,  5.22step/s, loss=0.051458, elapsed=13.5min]

Step 4200/10000 | Train loss: 0.054500 | Elapsed: 13.5min | ETA: 18.6min

Entraînement:  42%|████▏     | 4202/10000 [13:29<18:28,  5.23step/s, loss=0.051458, elapsed=13.5min]

Entraînement:  42%|████▏     | 4202/10000 [13:29<18:28,  5.23step/s, loss=0.019613, elapsed=13.5min]

Entraînement:  42%|████▏     | 4203/10000 [13:29<18:24,  5.25step/s, loss=0.019613, elapsed=13.5min]

Entraînement:  42%|████▏     | 4203/10000 [13:29<18:24,  5.25step/s, loss=0.099627, elapsed=13.5min]

Entraînement:  42%|████▏     | 4204/10000 [13:30<18:21,  5.26step/s, loss=0.099627, elapsed=13.5min]

Entraînement:  42%|████▏     | 4204/10000 [13:30<18:21,  5.26step/s, loss=0.042463, elapsed=13.5min]

Entraînement:  42%|████▏     | 4205/10000 [13:30<18:21,  5.26step/s, loss=0.042463, elapsed=13.5min]

Entraînement:  42%|████▏     | 4205/10000 [13:30<18:21,  5.26step/s, loss=0.113405, elapsed=13.5min]

Entraînement:  42%|████▏     | 4206/10000 [13:30<18:22,  5.26step/s, loss=0.113405, elapsed=13.5min]

Entraînement:  42%|████▏     | 4206/10000 [13:30<18:22,  5.26step/s, loss=0.053808, elapsed=13.5min]

Entraînement:  42%|████▏     | 4207/10000 [13:30<18:23,  5.25step/s, loss=0.053808, elapsed=13.5min]

Entraînement:  42%|████▏     | 4207/10000 [13:30<18:23,  5.25step/s, loss=0.041670, elapsed=13.5min]

Entraînement:  42%|████▏     | 4208/10000 [13:30<18:20,  5.26step/s, loss=0.041670, elapsed=13.5min]

Entraînement:  42%|████▏     | 4208/10000 [13:30<18:20,  5.26step/s, loss=0.117471, elapsed=13.5min]

Entraînement:  42%|████▏     | 4209/10000 [13:31<18:20,  5.26step/s, loss=0.117471, elapsed=13.5min]

Entraînement:  42%|████▏     | 4209/10000 [13:31<18:20,  5.26step/s, loss=0.052878, elapsed=13.5min]

Entraînement:  42%|████▏     | 4210/10000 [13:31<18:16,  5.28step/s, loss=0.052878, elapsed=13.5min]

Entraînement:  42%|████▏     | 4210/10000 [13:31<18:16,  5.28step/s, loss=0.068961, elapsed=13.5min]

Entraînement:  42%|████▏     | 4211/10000 [13:31<18:22,  5.25step/s, loss=0.068961, elapsed=13.5min]

Entraînement:  42%|████▏     | 4211/10000 [13:31<18:22,  5.25step/s, loss=0.040196, elapsed=13.5min]

Entraînement:  42%|████▏     | 4212/10000 [13:31<18:21,  5.25step/s, loss=0.040196, elapsed=13.5min]

Entraînement:  42%|████▏     | 4212/10000 [13:31<18:21,  5.25step/s, loss=0.043775, elapsed=13.5min]

Entraînement:  42%|████▏     | 4213/10000 [13:31<18:27,  5.23step/s, loss=0.043775, elapsed=13.5min]

Entraînement:  42%|████▏     | 4213/10000 [13:31<18:27,  5.23step/s, loss=0.056766, elapsed=13.5min]

Entraînement:  42%|████▏     | 4214/10000 [13:32<18:29,  5.21step/s, loss=0.056766, elapsed=13.5min]

Entraînement:  42%|████▏     | 4214/10000 [13:32<18:29,  5.21step/s, loss=0.065359, elapsed=13.5min]

Entraînement:  42%|████▏     | 4215/10000 [13:32<18:26,  5.23step/s, loss=0.065359, elapsed=13.5min]

Entraînement:  42%|████▏     | 4215/10000 [13:32<18:26,  5.23step/s, loss=0.034914, elapsed=13.5min]

Entraînement:  42%|████▏     | 4216/10000 [13:32<18:21,  5.25step/s, loss=0.034914, elapsed=13.5min]

Entraînement:  42%|████▏     | 4216/10000 [13:32<18:21,  5.25step/s, loss=0.118906, elapsed=13.5min]

Entraînement:  42%|████▏     | 4217/10000 [13:32<18:19,  5.26step/s, loss=0.118906, elapsed=13.5min]

Entraînement:  42%|████▏     | 4217/10000 [13:32<18:19,  5.26step/s, loss=0.100548, elapsed=13.5min]

Entraînement:  42%|████▏     | 4218/10000 [13:32<18:17,  5.27step/s, loss=0.100548, elapsed=13.5min]

Entraînement:  42%|████▏     | 4218/10000 [13:32<18:17,  5.27step/s, loss=0.028766, elapsed=13.5min]

Entraînement:  42%|████▏     | 4219/10000 [13:33<18:15,  5.28step/s, loss=0.028766, elapsed=13.5min]

Entraînement:  42%|████▏     | 4219/10000 [13:33<18:15,  5.28step/s, loss=0.097450, elapsed=13.6min]

Entraînement:  42%|████▏     | 4220/10000 [13:33<18:13,  5.28step/s, loss=0.097450, elapsed=13.6min]

Entraînement:  42%|████▏     | 4220/10000 [13:33<18:13,  5.28step/s, loss=0.054843, elapsed=13.6min]

Entraînement:  42%|████▏     | 4221/10000 [13:33<18:12,  5.29step/s, loss=0.054843, elapsed=13.6min]

Entraînement:  42%|████▏     | 4221/10000 [13:33<18:12,  5.29step/s, loss=0.050031, elapsed=13.6min]

Entraînement:  42%|████▏     | 4222/10000 [13:33<18:13,  5.28step/s, loss=0.050031, elapsed=13.6min]

Entraînement:  42%|████▏     | 4222/10000 [13:33<18:13,  5.28step/s, loss=0.074948, elapsed=13.6min]

Entraînement:  42%|████▏     | 4223/10000 [13:33<18:12,  5.29step/s, loss=0.074948, elapsed=13.6min]

Entraînement:  42%|████▏     | 4223/10000 [13:33<18:12,  5.29step/s, loss=0.042303, elapsed=13.6min]

Entraînement:  42%|████▏     | 4224/10000 [13:33<18:09,  5.30step/s, loss=0.042303, elapsed=13.6min]

Entraînement:  42%|████▏     | 4224/10000 [13:33<18:09,  5.30step/s, loss=0.052644, elapsed=13.6min]

Entraînement:  42%|████▏     | 4225/10000 [13:34<18:10,  5.30step/s, loss=0.052644, elapsed=13.6min]

Entraînement:  42%|████▏     | 4225/10000 [13:34<18:10,  5.30step/s, loss=0.069744, elapsed=13.6min]

Entraînement:  42%|████▏     | 4226/10000 [13:34<18:09,  5.30step/s, loss=0.069744, elapsed=13.6min]

Entraînement:  42%|████▏     | 4226/10000 [13:34<18:09,  5.30step/s, loss=0.095531, elapsed=13.6min]

Entraînement:  42%|████▏     | 4227/10000 [13:34<18:08,  5.30step/s, loss=0.095531, elapsed=13.6min]

Entraînement:  42%|████▏     | 4227/10000 [13:34<18:08,  5.30step/s, loss=0.112188, elapsed=13.6min]

Entraînement:  42%|████▏     | 4228/10000 [13:34<18:08,  5.30step/s, loss=0.112188, elapsed=13.6min]

Entraînement:  42%|████▏     | 4228/10000 [13:34<18:08,  5.30step/s, loss=0.107490, elapsed=13.6min]

Entraînement:  42%|████▏     | 4229/10000 [13:34<18:11,  5.29step/s, loss=0.107490, elapsed=13.6min]

Entraînement:  42%|████▏     | 4229/10000 [13:34<18:11,  5.29step/s, loss=0.045365, elapsed=13.6min]

Entraînement:  42%|████▏     | 4230/10000 [13:35<18:12,  5.28step/s, loss=0.045365, elapsed=13.6min]

Entraînement:  42%|████▏     | 4230/10000 [13:35<18:12,  5.28step/s, loss=0.037816, elapsed=13.6min]

Entraînement:  42%|████▏     | 4231/10000 [13:35<18:12,  5.28step/s, loss=0.037816, elapsed=13.6min]

Entraînement:  42%|████▏     | 4231/10000 [13:35<18:12,  5.28step/s, loss=0.107670, elapsed=13.6min]

Entraînement:  42%|████▏     | 4232/10000 [13:35<18:14,  5.27step/s, loss=0.107670, elapsed=13.6min]

Entraînement:  42%|████▏     | 4232/10000 [13:35<18:14,  5.27step/s, loss=0.047393, elapsed=13.6min]

Entraînement:  42%|████▏     | 4233/10000 [13:35<18:13,  5.27step/s, loss=0.047393, elapsed=13.6min]

Entraînement:  42%|████▏     | 4233/10000 [13:35<18:13,  5.27step/s, loss=0.089171, elapsed=13.6min]

Entraînement:  42%|████▏     | 4234/10000 [13:35<18:12,  5.28step/s, loss=0.089171, elapsed=13.6min]

Entraînement:  42%|████▏     | 4234/10000 [13:35<18:12,  5.28step/s, loss=0.022050, elapsed=13.6min]

Entraînement:  42%|████▏     | 4235/10000 [13:36<18:14,  5.27step/s, loss=0.022050, elapsed=13.6min]

Entraînement:  42%|████▏     | 4235/10000 [13:36<18:14,  5.27step/s, loss=0.052052, elapsed=13.6min]

Entraînement:  42%|████▏     | 4236/10000 [13:36<18:12,  5.28step/s, loss=0.052052, elapsed=13.6min]

Entraînement:  42%|████▏     | 4236/10000 [13:36<18:12,  5.28step/s, loss=0.038099, elapsed=13.6min]

Entraînement:  42%|████▏     | 4237/10000 [13:36<18:13,  5.27step/s, loss=0.038099, elapsed=13.6min]

Entraînement:  42%|████▏     | 4237/10000 [13:36<18:13,  5.27step/s, loss=0.068675, elapsed=13.6min]

Entraînement:  42%|████▏     | 4238/10000 [13:36<18:11,  5.28step/s, loss=0.068675, elapsed=13.6min]

Entraînement:  42%|████▏     | 4238/10000 [13:36<18:11,  5.28step/s, loss=0.028729, elapsed=13.6min]

Entraînement:  42%|████▏     | 4239/10000 [13:36<18:12,  5.27step/s, loss=0.028729, elapsed=13.6min]

Entraînement:  42%|████▏     | 4239/10000 [13:36<18:12,  5.27step/s, loss=0.034610, elapsed=13.6min]

Entraînement:  42%|████▏     | 4240/10000 [13:37<18:11,  5.28step/s, loss=0.034610, elapsed=13.6min]

Entraînement:  42%|████▏     | 4240/10000 [13:37<18:11,  5.28step/s, loss=0.041372, elapsed=13.6min]

Entraînement:  42%|████▏     | 4241/10000 [13:37<18:11,  5.28step/s, loss=0.041372, elapsed=13.6min]

Entraînement:  42%|████▏     | 4241/10000 [13:37<18:11,  5.28step/s, loss=0.031078, elapsed=13.6min]

Entraînement:  42%|████▏     | 4242/10000 [13:37<18:10,  5.28step/s, loss=0.031078, elapsed=13.6min]

Entraînement:  42%|████▏     | 4242/10000 [13:37<18:10,  5.28step/s, loss=0.039568, elapsed=13.6min]

Entraînement:  42%|████▏     | 4243/10000 [13:37<18:11,  5.27step/s, loss=0.039568, elapsed=13.6min]

Entraînement:  42%|████▏     | 4243/10000 [13:37<18:11,  5.27step/s, loss=0.072181, elapsed=13.6min]

Entraînement:  42%|████▏     | 4244/10000 [13:37<18:13,  5.27step/s, loss=0.072181, elapsed=13.6min]

Entraînement:  42%|████▏     | 4244/10000 [13:37<18:13,  5.27step/s, loss=0.041734, elapsed=13.6min]

Entraînement:  42%|████▏     | 4245/10000 [13:37<18:13,  5.26step/s, loss=0.041734, elapsed=13.6min]

Entraînement:  42%|████▏     | 4245/10000 [13:37<18:13,  5.26step/s, loss=0.029671, elapsed=13.6min]

Entraînement:  42%|████▏     | 4246/10000 [13:38<18:12,  5.27step/s, loss=0.029671, elapsed=13.6min]

Entraînement:  42%|████▏     | 4246/10000 [13:38<18:12,  5.27step/s, loss=0.047887, elapsed=13.6min]

Entraînement:  42%|████▏     | 4247/10000 [13:38<18:11,  5.27step/s, loss=0.047887, elapsed=13.6min]

Entraînement:  42%|████▏     | 4247/10000 [13:38<18:11,  5.27step/s, loss=0.122296, elapsed=13.6min]

Entraînement:  42%|████▏     | 4248/10000 [13:38<18:11,  5.27step/s, loss=0.122296, elapsed=13.6min]

Entraînement:  42%|████▏     | 4248/10000 [13:38<18:11,  5.27step/s, loss=0.085280, elapsed=13.6min]

Entraînement:  42%|████▏     | 4249/10000 [13:38<18:11,  5.27step/s, loss=0.085280, elapsed=13.6min]

Entraînement:  42%|████▏     | 4249/10000 [13:38<18:11,  5.27step/s, loss=0.057724, elapsed=13.6min]

Entraînement:  42%|████▎     | 4250/10000 [13:38<18:10,  5.27step/s, loss=0.057724, elapsed=13.6min]

Entraînement:  42%|████▎     | 4250/10000 [13:38<18:10,  5.27step/s, loss=0.066646, elapsed=13.6min]

Entraînement:  43%|████▎     | 4251/10000 [13:39<18:10,  5.27step/s, loss=0.066646, elapsed=13.6min]

Entraînement:  43%|████▎     | 4251/10000 [13:39<18:10,  5.27step/s, loss=0.042564, elapsed=13.7min]

Entraînement:  43%|████▎     | 4252/10000 [13:39<18:11,  5.27step/s, loss=0.042564, elapsed=13.7min]

Entraînement:  43%|████▎     | 4252/10000 [13:39<18:11,  5.27step/s, loss=0.044137, elapsed=13.7min]

Entraînement:  43%|████▎     | 4253/10000 [13:39<18:10,  5.27step/s, loss=0.044137, elapsed=13.7min]

Entraînement:  43%|████▎     | 4253/10000 [13:39<18:10,  5.27step/s, loss=0.020450, elapsed=13.7min]

Entraînement:  43%|████▎     | 4254/10000 [13:39<18:09,  5.27step/s, loss=0.020450, elapsed=13.7min]

Entraînement:  43%|████▎     | 4254/10000 [13:39<18:09,  5.27step/s, loss=0.068105, elapsed=13.7min]

Entraînement:  43%|████▎     | 4255/10000 [13:39<18:10,  5.27step/s, loss=0.068105, elapsed=13.7min]

Entraînement:  43%|████▎     | 4255/10000 [13:39<18:10,  5.27step/s, loss=0.029212, elapsed=13.7min]

Entraînement:  43%|████▎     | 4256/10000 [13:40<18:09,  5.27step/s, loss=0.029212, elapsed=13.7min]

Entraînement:  43%|████▎     | 4256/10000 [13:40<18:09,  5.27step/s, loss=0.092900, elapsed=13.7min]

Entraînement:  43%|████▎     | 4257/10000 [13:40<18:10,  5.27step/s, loss=0.092900, elapsed=13.7min]

Entraînement:  43%|████▎     | 4257/10000 [13:40<18:10,  5.27step/s, loss=0.043234, elapsed=13.7min]

Entraînement:  43%|████▎     | 4258/10000 [13:40<18:10,  5.27step/s, loss=0.043234, elapsed=13.7min]

Entraînement:  43%|████▎     | 4258/10000 [13:40<18:10,  5.27step/s, loss=0.079395, elapsed=13.7min]

Entraînement:  43%|████▎     | 4259/10000 [13:40<18:10,  5.26step/s, loss=0.079395, elapsed=13.7min]

Entraînement:  43%|████▎     | 4259/10000 [13:40<18:10,  5.26step/s, loss=0.039409, elapsed=13.7min]

Entraînement:  43%|████▎     | 4260/10000 [13:40<18:11,  5.26step/s, loss=0.039409, elapsed=13.7min]

Entraînement:  43%|████▎     | 4260/10000 [13:40<18:11,  5.26step/s, loss=0.023611, elapsed=13.7min]

Entraînement:  43%|████▎     | 4261/10000 [13:40<18:08,  5.27step/s, loss=0.023611, elapsed=13.7min]

Entraînement:  43%|████▎     | 4261/10000 [13:40<18:08,  5.27step/s, loss=0.046125, elapsed=13.7min]

Entraînement:  43%|████▎     | 4262/10000 [13:41<18:08,  5.27step/s, loss=0.046125, elapsed=13.7min]

Entraînement:  43%|████▎     | 4262/10000 [13:41<18:08,  5.27step/s, loss=0.025632, elapsed=13.7min]

Entraînement:  43%|████▎     | 4263/10000 [13:41<18:06,  5.28step/s, loss=0.025632, elapsed=13.7min]

Entraînement:  43%|████▎     | 4263/10000 [13:41<18:06,  5.28step/s, loss=0.089268, elapsed=13.7min]

Entraînement:  43%|████▎     | 4264/10000 [13:41<18:06,  5.28step/s, loss=0.089268, elapsed=13.7min]

Entraînement:  43%|████▎     | 4264/10000 [13:41<18:06,  5.28step/s, loss=0.132494, elapsed=13.7min]

Entraînement:  43%|████▎     | 4265/10000 [13:41<18:04,  5.29step/s, loss=0.132494, elapsed=13.7min]

Entraînement:  43%|████▎     | 4265/10000 [13:41<18:04,  5.29step/s, loss=0.042437, elapsed=13.7min]

Entraînement:  43%|████▎     | 4266/10000 [13:41<18:06,  5.28step/s, loss=0.042437, elapsed=13.7min]

Entraînement:  43%|████▎     | 4266/10000 [13:41<18:06,  5.28step/s, loss=0.049518, elapsed=13.7min]

Entraînement:  43%|████▎     | 4267/10000 [13:42<18:08,  5.27step/s, loss=0.049518, elapsed=13.7min]

Entraînement:  43%|████▎     | 4267/10000 [13:42<18:08,  5.27step/s, loss=0.096642, elapsed=13.7min]

Entraînement:  43%|████▎     | 4268/10000 [13:42<18:08,  5.27step/s, loss=0.096642, elapsed=13.7min]

Entraînement:  43%|████▎     | 4268/10000 [13:42<18:08,  5.27step/s, loss=0.025834, elapsed=13.7min]

Entraînement:  43%|████▎     | 4269/10000 [13:42<18:19,  5.21step/s, loss=0.025834, elapsed=13.7min]

Entraînement:  43%|████▎     | 4269/10000 [13:42<18:19,  5.21step/s, loss=0.056214, elapsed=13.7min]

Entraînement:  43%|████▎     | 4270/10000 [13:42<18:17,  5.22step/s, loss=0.056214, elapsed=13.7min]

Entraînement:  43%|████▎     | 4270/10000 [13:42<18:17,  5.22step/s, loss=0.046283, elapsed=13.7min]

Entraînement:  43%|████▎     | 4271/10000 [13:42<18:14,  5.23step/s, loss=0.046283, elapsed=13.7min]

Entraînement:  43%|████▎     | 4271/10000 [13:42<18:14,  5.23step/s, loss=0.118586, elapsed=13.7min]

Entraînement:  43%|████▎     | 4272/10000 [13:43<18:12,  5.24step/s, loss=0.118586, elapsed=13.7min]

Entraînement:  43%|████▎     | 4272/10000 [13:43<18:12,  5.24step/s, loss=0.052881, elapsed=13.7min]

Entraînement:  43%|████▎     | 4273/10000 [13:43<18:10,  5.25step/s, loss=0.052881, elapsed=13.7min]

Entraînement:  43%|████▎     | 4273/10000 [13:43<18:10,  5.25step/s, loss=0.075977, elapsed=13.7min]

Entraînement:  43%|████▎     | 4274/10000 [13:43<18:08,  5.26step/s, loss=0.075977, elapsed=13.7min]

Entraînement:  43%|████▎     | 4274/10000 [13:43<18:08,  5.26step/s, loss=0.047301, elapsed=13.7min]

Entraînement:  43%|████▎     | 4275/10000 [13:43<18:09,  5.25step/s, loss=0.047301, elapsed=13.7min]

Entraînement:  43%|████▎     | 4275/10000 [13:43<18:09,  5.25step/s, loss=0.053768, elapsed=13.7min]

Entraînement:  43%|████▎     | 4276/10000 [13:43<18:08,  5.26step/s, loss=0.053768, elapsed=13.7min]

Entraînement:  43%|████▎     | 4276/10000 [13:43<18:08,  5.26step/s, loss=0.088306, elapsed=13.7min]

Entraînement:  43%|████▎     | 4277/10000 [13:44<18:10,  5.25step/s, loss=0.088306, elapsed=13.7min]

Entraînement:  43%|████▎     | 4277/10000 [13:44<18:10,  5.25step/s, loss=0.115995, elapsed=13.7min]

Entraînement:  43%|████▎     | 4278/10000 [13:44<18:09,  5.25step/s, loss=0.115995, elapsed=13.7min]

Entraînement:  43%|████▎     | 4278/10000 [13:44<18:09,  5.25step/s, loss=0.031880, elapsed=13.7min]

Entraînement:  43%|████▎     | 4279/10000 [13:44<18:08,  5.25step/s, loss=0.031880, elapsed=13.7min]

Entraînement:  43%|████▎     | 4279/10000 [13:44<18:08,  5.25step/s, loss=0.038720, elapsed=13.7min]

Entraînement:  43%|████▎     | 4280/10000 [13:44<18:07,  5.26step/s, loss=0.038720, elapsed=13.7min]

Entraînement:  43%|████▎     | 4280/10000 [13:44<18:07,  5.26step/s, loss=0.069556, elapsed=13.7min]

Entraînement:  43%|████▎     | 4281/10000 [13:44<18:07,  5.26step/s, loss=0.069556, elapsed=13.7min]

Entraînement:  43%|████▎     | 4281/10000 [13:44<18:07,  5.26step/s, loss=0.102776, elapsed=13.7min]

Entraînement:  43%|████▎     | 4282/10000 [13:44<18:08,  5.25step/s, loss=0.102776, elapsed=13.7min]

Entraînement:  43%|████▎     | 4282/10000 [13:44<18:08,  5.25step/s, loss=0.079362, elapsed=13.7min]

Entraînement:  43%|████▎     | 4283/10000 [13:45<18:08,  5.25step/s, loss=0.079362, elapsed=13.7min]

Entraînement:  43%|████▎     | 4283/10000 [13:45<18:08,  5.25step/s, loss=0.042609, elapsed=13.8min]

Entraînement:  43%|████▎     | 4284/10000 [13:45<18:07,  5.26step/s, loss=0.042609, elapsed=13.8min]

Entraînement:  43%|████▎     | 4284/10000 [13:45<18:07,  5.26step/s, loss=0.032990, elapsed=13.8min]

Entraînement:  43%|████▎     | 4285/10000 [13:45<18:05,  5.26step/s, loss=0.032990, elapsed=13.8min]

Entraînement:  43%|████▎     | 4285/10000 [13:45<18:05,  5.26step/s, loss=0.039998, elapsed=13.8min]

Entraînement:  43%|████▎     | 4286/10000 [13:45<18:04,  5.27step/s, loss=0.039998, elapsed=13.8min]

Entraînement:  43%|████▎     | 4286/10000 [13:45<18:04,  5.27step/s, loss=0.037627, elapsed=13.8min]

Entraînement:  43%|████▎     | 4287/10000 [13:45<18:02,  5.28step/s, loss=0.037627, elapsed=13.8min]

Entraînement:  43%|████▎     | 4287/10000 [13:45<18:02,  5.28step/s, loss=0.032682, elapsed=13.8min]

Entraînement:  43%|████▎     | 4288/10000 [13:46<18:02,  5.28step/s, loss=0.032682, elapsed=13.8min]

Entraînement:  43%|████▎     | 4288/10000 [13:46<18:02,  5.28step/s, loss=0.080938, elapsed=13.8min]

Entraînement:  43%|████▎     | 4289/10000 [13:46<18:01,  5.28step/s, loss=0.080938, elapsed=13.8min]

Entraînement:  43%|████▎     | 4289/10000 [13:46<18:01,  5.28step/s, loss=0.030325, elapsed=13.8min]

Entraînement:  43%|████▎     | 4290/10000 [13:46<18:02,  5.28step/s, loss=0.030325, elapsed=13.8min]

Entraînement:  43%|████▎     | 4290/10000 [13:46<18:02,  5.28step/s, loss=0.124586, elapsed=13.8min]

Entraînement:  43%|████▎     | 4291/10000 [13:46<18:03,  5.27step/s, loss=0.124586, elapsed=13.8min]

Entraînement:  43%|████▎     | 4291/10000 [13:46<18:03,  5.27step/s, loss=0.036964, elapsed=13.8min]

Entraînement:  43%|████▎     | 4292/10000 [13:46<18:01,  5.28step/s, loss=0.036964, elapsed=13.8min]

Entraînement:  43%|████▎     | 4292/10000 [13:46<18:01,  5.28step/s, loss=0.067183, elapsed=13.8min]

Entraînement:  43%|████▎     | 4293/10000 [13:47<18:02,  5.27step/s, loss=0.067183, elapsed=13.8min]

Entraînement:  43%|████▎     | 4293/10000 [13:47<18:02,  5.27step/s, loss=0.030334, elapsed=13.8min]

Entraînement:  43%|████▎     | 4294/10000 [13:47<18:02,  5.27step/s, loss=0.030334, elapsed=13.8min]

Entraînement:  43%|████▎     | 4294/10000 [13:47<18:02,  5.27step/s, loss=0.032708, elapsed=13.8min]

Entraînement:  43%|████▎     | 4295/10000 [13:47<18:01,  5.28step/s, loss=0.032708, elapsed=13.8min]

Entraînement:  43%|████▎     | 4295/10000 [13:47<18:01,  5.28step/s, loss=0.039454, elapsed=13.8min]

Entraînement:  43%|████▎     | 4296/10000 [13:47<18:01,  5.28step/s, loss=0.039454, elapsed=13.8min]

Entraînement:  43%|████▎     | 4296/10000 [13:47<18:01,  5.28step/s, loss=0.089562, elapsed=13.8min]

Entraînement:  43%|████▎     | 4297/10000 [13:47<18:00,  5.28step/s, loss=0.089562, elapsed=13.8min]

Entraînement:  43%|████▎     | 4297/10000 [13:47<18:00,  5.28step/s, loss=0.078750, elapsed=13.8min]

Entraînement:  43%|████▎     | 4298/10000 [13:48<18:02,  5.27step/s, loss=0.078750, elapsed=13.8min]

Entraînement:  43%|████▎     | 4298/10000 [13:48<18:02,  5.27step/s, loss=0.023403, elapsed=13.8min]

Entraînement:  43%|████▎     | 4299/10000 [13:48<18:01,  5.27step/s, loss=0.023403, elapsed=13.8min]

Entraînement:  43%|████▎     | 4299/10000 [13:48<18:01,  5.27step/s, loss=0.051789, elapsed=13.8min]

Entraînement:  43%|████▎     | 4300/10000 [13:48<18:02,  5.26step/s, loss=0.051789, elapsed=13.8min]

Entraînement:  43%|████▎     | 4300/10000 [13:48<18:02,  5.26step/s, loss=0.032435, elapsed=13.8min]

Entraînement:  43%|████▎     | 4300/10000 [13:48<18:02,  5.26step/s, loss=0.032435, elapsed=13.8min]

Entraînement:  43%|████▎     | 4301/10000 [13:48<18:11,  5.22step/s, loss=0.032435, elapsed=13.8min]

Entraînement:  43%|████▎     | 4301/10000 [13:48<18:11,  5.22step/s, loss=0.051741, elapsed=13.8min]

Step 4300/10000 | Train loss: 0.032435 | Elapsed: 13.8min | ETA: 18.3min

Entraînement:  43%|████▎     | 4302/10000 [13:48<18:08,  5.23step/s, loss=0.051741, elapsed=13.8min]

Entraînement:  43%|████▎     | 4302/10000 [13:48<18:08,  5.23step/s, loss=0.040845, elapsed=13.8min]

Entraînement:  43%|████▎     | 4303/10000 [13:48<18:04,  5.25step/s, loss=0.040845, elapsed=13.8min]

Entraînement:  43%|████▎     | 4303/10000 [13:48<18:04,  5.25step/s, loss=0.035225, elapsed=13.8min]

Entraînement:  43%|████▎     | 4304/10000 [13:49<18:03,  5.26step/s, loss=0.035225, elapsed=13.8min]

Entraînement:  43%|████▎     | 4304/10000 [13:49<18:03,  5.26step/s, loss=0.105105, elapsed=13.8min]

Entraînement:  43%|████▎     | 4305/10000 [13:49<18:03,  5.26step/s, loss=0.105105, elapsed=13.8min]

Entraînement:  43%|████▎     | 4305/10000 [13:49<18:03,  5.26step/s, loss=0.055382, elapsed=13.8min]

Entraînement:  43%|████▎     | 4306/10000 [13:49<17:59,  5.27step/s, loss=0.055382, elapsed=13.8min]

Entraînement:  43%|████▎     | 4306/10000 [13:49<17:59,  5.27step/s, loss=0.027466, elapsed=13.8min]

Entraînement:  43%|████▎     | 4307/10000 [13:49<17:59,  5.27step/s, loss=0.027466, elapsed=13.8min]

Entraînement:  43%|████▎     | 4307/10000 [13:49<17:59,  5.27step/s, loss=0.022687, elapsed=13.8min]

Entraînement:  43%|████▎     | 4308/10000 [13:49<17:57,  5.28step/s, loss=0.022687, elapsed=13.8min]

Entraînement:  43%|████▎     | 4308/10000 [13:49<17:57,  5.28step/s, loss=0.054129, elapsed=13.8min]

Entraînement:  43%|████▎     | 4309/10000 [13:50<17:57,  5.28step/s, loss=0.054129, elapsed=13.8min]

Entraînement:  43%|████▎     | 4309/10000 [13:50<17:57,  5.28step/s, loss=0.031896, elapsed=13.8min]

Entraînement:  43%|████▎     | 4310/10000 [13:50<17:56,  5.29step/s, loss=0.031896, elapsed=13.8min]

Entraînement:  43%|████▎     | 4310/10000 [13:50<17:56,  5.29step/s, loss=0.030256, elapsed=13.8min]

Entraînement:  43%|████▎     | 4311/10000 [13:50<17:55,  5.29step/s, loss=0.030256, elapsed=13.8min]

Entraînement:  43%|████▎     | 4311/10000 [13:50<17:55,  5.29step/s, loss=0.036900, elapsed=13.8min]

Entraînement:  43%|████▎     | 4312/10000 [13:50<17:52,  5.30step/s, loss=0.036900, elapsed=13.8min]

Entraînement:  43%|████▎     | 4312/10000 [13:50<17:52,  5.30step/s, loss=0.029695, elapsed=13.8min]

Entraînement:  43%|████▎     | 4313/10000 [13:50<17:52,  5.30step/s, loss=0.029695, elapsed=13.8min]

Entraînement:  43%|████▎     | 4313/10000 [13:50<17:52,  5.30step/s, loss=0.033219, elapsed=13.8min]

Entraînement:  43%|████▎     | 4314/10000 [13:51<17:54,  5.29step/s, loss=0.033219, elapsed=13.8min]

Entraînement:  43%|████▎     | 4314/10000 [13:51<17:54,  5.29step/s, loss=0.079718, elapsed=13.9min]

Entraînement:  43%|████▎     | 4315/10000 [13:51<17:54,  5.29step/s, loss=0.079718, elapsed=13.9min]

Entraînement:  43%|████▎     | 4315/10000 [13:51<17:54,  5.29step/s, loss=0.157140, elapsed=13.9min]

Entraînement:  43%|████▎     | 4316/10000 [13:51<17:53,  5.30step/s, loss=0.157140, elapsed=13.9min]

Entraînement:  43%|████▎     | 4316/10000 [13:51<17:53,  5.30step/s, loss=0.046038, elapsed=13.9min]

Entraînement:  43%|████▎     | 4317/10000 [13:51<17:54,  5.29step/s, loss=0.046038, elapsed=13.9min]

Entraînement:  43%|████▎     | 4317/10000 [13:51<17:54,  5.29step/s, loss=0.032154, elapsed=13.9min]

Entraînement:  43%|████▎     | 4318/10000 [13:51<17:53,  5.29step/s, loss=0.032154, elapsed=13.9min]

Entraînement:  43%|████▎     | 4318/10000 [13:51<17:53,  5.29step/s, loss=0.064269, elapsed=13.9min]

Entraînement:  43%|████▎     | 4319/10000 [13:52<17:52,  5.30step/s, loss=0.064269, elapsed=13.9min]

Entraînement:  43%|████▎     | 4319/10000 [13:52<17:52,  5.30step/s, loss=0.104209, elapsed=13.9min]

Entraînement:  43%|████▎     | 4320/10000 [13:52<17:53,  5.29step/s, loss=0.104209, elapsed=13.9min]

Entraînement:  43%|████▎     | 4320/10000 [13:52<17:53,  5.29step/s, loss=0.059446, elapsed=13.9min]

Entraînement:  43%|████▎     | 4321/10000 [13:52<17:53,  5.29step/s, loss=0.059446, elapsed=13.9min]

Entraînement:  43%|████▎     | 4321/10000 [13:52<17:53,  5.29step/s, loss=0.047104, elapsed=13.9min]

Entraînement:  43%|████▎     | 4322/10000 [13:52<17:55,  5.28step/s, loss=0.047104, elapsed=13.9min]

Entraînement:  43%|████▎     | 4322/10000 [13:52<17:55,  5.28step/s, loss=0.052512, elapsed=13.9min]

Entraînement:  43%|████▎     | 4323/10000 [13:52<17:54,  5.28step/s, loss=0.052512, elapsed=13.9min]

Entraînement:  43%|████▎     | 4323/10000 [13:52<17:54,  5.28step/s, loss=0.060798, elapsed=13.9min]

Entraînement:  43%|████▎     | 4324/10000 [13:52<17:54,  5.28step/s, loss=0.060798, elapsed=13.9min]

Entraînement:  43%|████▎     | 4324/10000 [13:52<17:54,  5.28step/s, loss=0.048040, elapsed=13.9min]

Entraînement:  43%|████▎     | 4325/10000 [13:53<18:01,  5.25step/s, loss=0.048040, elapsed=13.9min]

Entraînement:  43%|████▎     | 4325/10000 [13:53<18:01,  5.25step/s, loss=0.077495, elapsed=13.9min]

Entraînement:  43%|████▎     | 4326/10000 [13:53<18:02,  5.24step/s, loss=0.077495, elapsed=13.9min]

Entraînement:  43%|████▎     | 4326/10000 [13:53<18:02,  5.24step/s, loss=0.057434, elapsed=13.9min]

Entraînement:  43%|████▎     | 4327/10000 [13:53<18:00,  5.25step/s, loss=0.057434, elapsed=13.9min]

Entraînement:  43%|████▎     | 4327/10000 [13:53<18:00,  5.25step/s, loss=0.101229, elapsed=13.9min]

Entraînement:  43%|████▎     | 4328/10000 [13:53<18:00,  5.25step/s, loss=0.101229, elapsed=13.9min]

Entraînement:  43%|████▎     | 4328/10000 [13:53<18:00,  5.25step/s, loss=0.082767, elapsed=13.9min]

Entraînement:  43%|████▎     | 4329/10000 [13:53<18:10,  5.20step/s, loss=0.082767, elapsed=13.9min]

Entraînement:  43%|████▎     | 4329/10000 [13:53<18:10,  5.20step/s, loss=0.073779, elapsed=13.9min]

Entraînement:  43%|████▎     | 4330/10000 [13:54<18:08,  5.21step/s, loss=0.073779, elapsed=13.9min]

Entraînement:  43%|████▎     | 4330/10000 [13:54<18:08,  5.21step/s, loss=0.025413, elapsed=13.9min]

Entraînement:  43%|████▎     | 4331/10000 [13:54<18:03,  5.23step/s, loss=0.025413, elapsed=13.9min]

Entraînement:  43%|████▎     | 4331/10000 [13:54<18:03,  5.23step/s, loss=0.053965, elapsed=13.9min]

Entraînement:  43%|████▎     | 4332/10000 [13:54<18:00,  5.25step/s, loss=0.053965, elapsed=13.9min]

Entraînement:  43%|████▎     | 4332/10000 [13:54<18:00,  5.25step/s, loss=0.101479, elapsed=13.9min]

Entraînement:  43%|████▎     | 4333/10000 [13:54<17:57,  5.26step/s, loss=0.101479, elapsed=13.9min]

Entraînement:  43%|████▎     | 4333/10000 [13:54<17:57,  5.26step/s, loss=0.045447, elapsed=13.9min]

Entraînement:  43%|████▎     | 4334/10000 [13:54<17:57,  5.26step/s, loss=0.045447, elapsed=13.9min]

Entraînement:  43%|████▎     | 4334/10000 [13:54<17:57,  5.26step/s, loss=0.031757, elapsed=13.9min]

Entraînement:  43%|████▎     | 4335/10000 [13:55<17:55,  5.27step/s, loss=0.031757, elapsed=13.9min]

Entraînement:  43%|████▎     | 4335/10000 [13:55<17:55,  5.27step/s, loss=0.075802, elapsed=13.9min]

Entraînement:  43%|████▎     | 4336/10000 [13:55<17:53,  5.28step/s, loss=0.075802, elapsed=13.9min]

Entraînement:  43%|████▎     | 4336/10000 [13:55<17:53,  5.28step/s, loss=0.036687, elapsed=13.9min]

Entraînement:  43%|████▎     | 4337/10000 [13:55<17:54,  5.27step/s, loss=0.036687, elapsed=13.9min]

Entraînement:  43%|████▎     | 4337/10000 [13:55<17:54,  5.27step/s, loss=0.051233, elapsed=13.9min]

Entraînement:  43%|████▎     | 4338/10000 [13:55<17:55,  5.26step/s, loss=0.051233, elapsed=13.9min]

Entraînement:  43%|████▎     | 4338/10000 [13:55<17:55,  5.26step/s, loss=0.048039, elapsed=13.9min]

Entraînement:  43%|████▎     | 4339/10000 [13:55<17:53,  5.27step/s, loss=0.048039, elapsed=13.9min]

Entraînement:  43%|████▎     | 4339/10000 [13:55<17:53,  5.27step/s, loss=0.031331, elapsed=13.9min]

Entraînement:  43%|████▎     | 4340/10000 [13:55<17:53,  5.27step/s, loss=0.031331, elapsed=13.9min]

Entraînement:  43%|████▎     | 4340/10000 [13:56<17:53,  5.27step/s, loss=0.043570, elapsed=13.9min]

Entraînement:  43%|████▎     | 4341/10000 [13:56<17:52,  5.28step/s, loss=0.043570, elapsed=13.9min]

Entraînement:  43%|████▎     | 4341/10000 [13:56<17:52,  5.28step/s, loss=0.067611, elapsed=13.9min]

Entraînement:  43%|████▎     | 4342/10000 [13:56<17:52,  5.28step/s, loss=0.067611, elapsed=13.9min]

Entraînement:  43%|████▎     | 4342/10000 [13:56<17:52,  5.28step/s, loss=0.044983, elapsed=13.9min]

Entraînement:  43%|████▎     | 4343/10000 [13:56<17:51,  5.28step/s, loss=0.044983, elapsed=13.9min]

Entraînement:  43%|████▎     | 4343/10000 [13:56<17:51,  5.28step/s, loss=0.033779, elapsed=13.9min]

Entraînement:  43%|████▎     | 4344/10000 [13:56<17:50,  5.28step/s, loss=0.033779, elapsed=13.9min]

Entraînement:  43%|████▎     | 4344/10000 [13:56<17:50,  5.28step/s, loss=0.052198, elapsed=13.9min]

Entraînement:  43%|████▎     | 4345/10000 [13:56<17:51,  5.28step/s, loss=0.052198, elapsed=13.9min]

Entraînement:  43%|████▎     | 4345/10000 [13:56<17:51,  5.28step/s, loss=0.031260, elapsed=13.9min]

Entraînement:  43%|████▎     | 4346/10000 [13:57<17:51,  5.28step/s, loss=0.031260, elapsed=13.9min]

Entraînement:  43%|████▎     | 4346/10000 [13:57<17:51,  5.28step/s, loss=0.043564, elapsed=14.0min]

Entraînement:  43%|████▎     | 4347/10000 [13:57<17:51,  5.27step/s, loss=0.043564, elapsed=14.0min]

Entraînement:  43%|████▎     | 4347/10000 [13:57<17:51,  5.27step/s, loss=0.018426, elapsed=14.0min]

Entraînement:  43%|████▎     | 4348/10000 [13:57<17:51,  5.27step/s, loss=0.018426, elapsed=14.0min]

Entraînement:  43%|████▎     | 4348/10000 [13:57<17:51,  5.27step/s, loss=0.068397, elapsed=14.0min]

Entraînement:  43%|████▎     | 4349/10000 [13:57<17:48,  5.29step/s, loss=0.068397, elapsed=14.0min]

Entraînement:  43%|████▎     | 4349/10000 [13:57<17:48,  5.29step/s, loss=0.031110, elapsed=14.0min]

Entraînement:  44%|████▎     | 4350/10000 [13:57<17:49,  5.28step/s, loss=0.031110, elapsed=14.0min]

Entraînement:  44%|████▎     | 4350/10000 [13:57<17:49,  5.28step/s, loss=0.068099, elapsed=14.0min]

Entraînement:  44%|████▎     | 4351/10000 [13:58<17:48,  5.29step/s, loss=0.068099, elapsed=14.0min]

Entraînement:  44%|████▎     | 4351/10000 [13:58<17:48,  5.29step/s, loss=0.023006, elapsed=14.0min]

Entraînement:  44%|████▎     | 4352/10000 [13:58<17:49,  5.28step/s, loss=0.023006, elapsed=14.0min]

Entraînement:  44%|████▎     | 4352/10000 [13:58<17:49,  5.28step/s, loss=0.034457, elapsed=14.0min]

Entraînement:  44%|████▎     | 4353/10000 [13:58<17:49,  5.28step/s, loss=0.034457, elapsed=14.0min]

Entraînement:  44%|████▎     | 4353/10000 [13:58<17:49,  5.28step/s, loss=0.048596, elapsed=14.0min]

Entraînement:  44%|████▎     | 4354/10000 [13:58<17:50,  5.28step/s, loss=0.048596, elapsed=14.0min]

Entraînement:  44%|████▎     | 4354/10000 [13:58<17:50,  5.28step/s, loss=0.030973, elapsed=14.0min]

Entraînement:  44%|████▎     | 4355/10000 [13:58<17:50,  5.27step/s, loss=0.030973, elapsed=14.0min]

Entraînement:  44%|████▎     | 4355/10000 [13:58<17:50,  5.27step/s, loss=0.069894, elapsed=14.0min]

Entraînement:  44%|████▎     | 4356/10000 [13:59<18:05,  5.20step/s, loss=0.069894, elapsed=14.0min]

Entraînement:  44%|████▎     | 4356/10000 [13:59<18:05,  5.20step/s, loss=0.032314, elapsed=14.0min]

Entraînement:  44%|████▎     | 4357/10000 [13:59<18:01,  5.22step/s, loss=0.032314, elapsed=14.0min]

Entraînement:  44%|████▎     | 4357/10000 [13:59<18:01,  5.22step/s, loss=0.047627, elapsed=14.0min]

Entraînement:  44%|████▎     | 4358/10000 [13:59<17:56,  5.24step/s, loss=0.047627, elapsed=14.0min]

Entraînement:  44%|████▎     | 4358/10000 [13:59<17:56,  5.24step/s, loss=0.130652, elapsed=14.0min]

Entraînement:  44%|████▎     | 4359/10000 [13:59<17:52,  5.26step/s, loss=0.130652, elapsed=14.0min]

Entraînement:  44%|████▎     | 4359/10000 [13:59<17:52,  5.26step/s, loss=0.044186, elapsed=14.0min]

Entraînement:  44%|████▎     | 4360/10000 [13:59<17:53,  5.25step/s, loss=0.044186, elapsed=14.0min]

Entraînement:  44%|████▎     | 4360/10000 [13:59<17:53,  5.25step/s, loss=0.074026, elapsed=14.0min]

Entraînement:  44%|████▎     | 4361/10000 [13:59<17:49,  5.27step/s, loss=0.074026, elapsed=14.0min]

Entraînement:  44%|████▎     | 4361/10000 [13:59<17:49,  5.27step/s, loss=0.027097, elapsed=14.0min]

Entraînement:  44%|████▎     | 4362/10000 [14:00<17:47,  5.28step/s, loss=0.027097, elapsed=14.0min]

Entraînement:  44%|████▎     | 4362/10000 [14:00<17:47,  5.28step/s, loss=0.036675, elapsed=14.0min]

Entraînement:  44%|████▎     | 4363/10000 [14:00<17:47,  5.28step/s, loss=0.036675, elapsed=14.0min]

Entraînement:  44%|████▎     | 4363/10000 [14:00<17:47,  5.28step/s, loss=0.056340, elapsed=14.0min]

Entraînement:  44%|████▎     | 4364/10000 [14:00<17:47,  5.28step/s, loss=0.056340, elapsed=14.0min]

Entraînement:  44%|████▎     | 4364/10000 [14:00<17:47,  5.28step/s, loss=0.082595, elapsed=14.0min]

Entraînement:  44%|████▎     | 4365/10000 [14:00<17:44,  5.29step/s, loss=0.082595, elapsed=14.0min]

Entraînement:  44%|████▎     | 4365/10000 [14:00<17:44,  5.29step/s, loss=0.036336, elapsed=14.0min]

Entraînement:  44%|████▎     | 4366/10000 [14:00<17:46,  5.29step/s, loss=0.036336, elapsed=14.0min]

Entraînement:  44%|████▎     | 4366/10000 [14:00<17:46,  5.29step/s, loss=0.048968, elapsed=14.0min]

Entraînement:  44%|████▎     | 4367/10000 [14:01<17:44,  5.29step/s, loss=0.048968, elapsed=14.0min]

Entraînement:  44%|████▎     | 4367/10000 [14:01<17:44,  5.29step/s, loss=0.037499, elapsed=14.0min]

Entraînement:  44%|████▎     | 4368/10000 [14:01<17:44,  5.29step/s, loss=0.037499, elapsed=14.0min]

Entraînement:  44%|████▎     | 4368/10000 [14:01<17:44,  5.29step/s, loss=0.049574, elapsed=14.0min]

Entraînement:  44%|████▎     | 4369/10000 [14:01<17:42,  5.30step/s, loss=0.049574, elapsed=14.0min]

Entraînement:  44%|████▎     | 4369/10000 [14:01<17:42,  5.30step/s, loss=0.042384, elapsed=14.0min]

Entraînement:  44%|████▎     | 4370/10000 [14:01<17:43,  5.30step/s, loss=0.042384, elapsed=14.0min]

Entraînement:  44%|████▎     | 4370/10000 [14:01<17:43,  5.30step/s, loss=0.058282, elapsed=14.0min]

Entraînement:  44%|████▎     | 4371/10000 [14:01<17:44,  5.29step/s, loss=0.058282, elapsed=14.0min]

Entraînement:  44%|████▎     | 4371/10000 [14:01<17:44,  5.29step/s, loss=0.100201, elapsed=14.0min]

Entraînement:  44%|████▎     | 4372/10000 [14:02<17:43,  5.29step/s, loss=0.100201, elapsed=14.0min]

Entraînement:  44%|████▎     | 4372/10000 [14:02<17:43,  5.29step/s, loss=0.056554, elapsed=14.0min]

Entraînement:  44%|████▎     | 4373/10000 [14:02<17:41,  5.30step/s, loss=0.056554, elapsed=14.0min]

Entraînement:  44%|████▎     | 4373/10000 [14:02<17:41,  5.30step/s, loss=0.043110, elapsed=14.0min]

Entraînement:  44%|████▎     | 4374/10000 [14:02<17:41,  5.30step/s, loss=0.043110, elapsed=14.0min]

Entraînement:  44%|████▎     | 4374/10000 [14:02<17:41,  5.30step/s, loss=0.041051, elapsed=14.0min]

Entraînement:  44%|████▍     | 4375/10000 [14:02<17:41,  5.30step/s, loss=0.041051, elapsed=14.0min]

Entraînement:  44%|████▍     | 4375/10000 [14:02<17:41,  5.30step/s, loss=0.062901, elapsed=14.0min]

Entraînement:  44%|████▍     | 4376/10000 [14:02<17:42,  5.29step/s, loss=0.062901, elapsed=14.0min]

Entraînement:  44%|████▍     | 4376/10000 [14:02<17:42,  5.29step/s, loss=0.042738, elapsed=14.0min]

Entraînement:  44%|████▍     | 4377/10000 [14:03<17:41,  5.30step/s, loss=0.042738, elapsed=14.0min]

Entraînement:  44%|████▍     | 4377/10000 [14:03<17:41,  5.30step/s, loss=0.050532, elapsed=14.1min]

Entraînement:  44%|████▍     | 4378/10000 [14:03<17:45,  5.28step/s, loss=0.050532, elapsed=14.1min]

Entraînement:  44%|████▍     | 4378/10000 [14:03<17:45,  5.28step/s, loss=0.021065, elapsed=14.1min]

Entraînement:  44%|████▍     | 4379/10000 [14:03<17:44,  5.28step/s, loss=0.021065, elapsed=14.1min]

Entraînement:  44%|████▍     | 4379/10000 [14:03<17:44,  5.28step/s, loss=0.023720, elapsed=14.1min]

Entraînement:  44%|████▍     | 4380/10000 [14:03<17:43,  5.28step/s, loss=0.023720, elapsed=14.1min]

Entraînement:  44%|████▍     | 4380/10000 [14:03<17:43,  5.28step/s, loss=0.087515, elapsed=14.1min]

Entraînement:  44%|████▍     | 4381/10000 [14:03<17:41,  5.29step/s, loss=0.087515, elapsed=14.1min]

Entraînement:  44%|████▍     | 4381/10000 [14:03<17:41,  5.29step/s, loss=0.083136, elapsed=14.1min]

Entraînement:  44%|████▍     | 4382/10000 [14:03<17:42,  5.29step/s, loss=0.083136, elapsed=14.1min]

Entraînement:  44%|████▍     | 4382/10000 [14:03<17:42,  5.29step/s, loss=0.042023, elapsed=14.1min]

Entraînement:  44%|████▍     | 4383/10000 [14:04<17:43,  5.28step/s, loss=0.042023, elapsed=14.1min]

Entraînement:  44%|████▍     | 4383/10000 [14:04<17:43,  5.28step/s, loss=0.039056, elapsed=14.1min]

Entraînement:  44%|████▍     | 4384/10000 [14:04<17:44,  5.28step/s, loss=0.039056, elapsed=14.1min]

Entraînement:  44%|████▍     | 4384/10000 [14:04<17:44,  5.28step/s, loss=0.129985, elapsed=14.1min]

Entraînement:  44%|████▍     | 4385/10000 [14:04<17:43,  5.28step/s, loss=0.129985, elapsed=14.1min]

Entraînement:  44%|████▍     | 4385/10000 [14:04<17:43,  5.28step/s, loss=0.054874, elapsed=14.1min]

Entraînement:  44%|████▍     | 4386/10000 [14:04<17:42,  5.29step/s, loss=0.054874, elapsed=14.1min]

Entraînement:  44%|████▍     | 4386/10000 [14:04<17:42,  5.29step/s, loss=0.025277, elapsed=14.1min]

Entraînement:  44%|████▍     | 4387/10000 [14:04<17:44,  5.27step/s, loss=0.025277, elapsed=14.1min]

Entraînement:  44%|████▍     | 4387/10000 [14:04<17:44,  5.27step/s, loss=0.072259, elapsed=14.1min]

Entraînement:  44%|████▍     | 4388/10000 [14:05<17:45,  5.27step/s, loss=0.072259, elapsed=14.1min]

Entraînement:  44%|████▍     | 4388/10000 [14:05<17:45,  5.27step/s, loss=0.093510, elapsed=14.1min]

Entraînement:  44%|████▍     | 4389/10000 [14:05<17:43,  5.28step/s, loss=0.093510, elapsed=14.1min]

Entraînement:  44%|████▍     | 4389/10000 [14:05<17:43,  5.28step/s, loss=0.033943, elapsed=14.1min]

Entraînement:  44%|████▍     | 4390/10000 [14:05<17:39,  5.29step/s, loss=0.033943, elapsed=14.1min]

Entraînement:  44%|████▍     | 4390/10000 [14:05<17:39,  5.29step/s, loss=0.083637, elapsed=14.1min]

Entraînement:  44%|████▍     | 4391/10000 [14:05<17:38,  5.30step/s, loss=0.083637, elapsed=14.1min]

Entraînement:  44%|████▍     | 4391/10000 [14:05<17:38,  5.30step/s, loss=0.061079, elapsed=14.1min]

Entraînement:  44%|████▍     | 4392/10000 [14:05<17:39,  5.29step/s, loss=0.061079, elapsed=14.1min]

Entraînement:  44%|████▍     | 4392/10000 [14:05<17:39,  5.29step/s, loss=0.083384, elapsed=14.1min]

Entraînement:  44%|████▍     | 4393/10000 [14:06<17:37,  5.30step/s, loss=0.083384, elapsed=14.1min]

Entraînement:  44%|████▍     | 4393/10000 [14:06<17:37,  5.30step/s, loss=0.052857, elapsed=14.1min]

Entraînement:  44%|████▍     | 4394/10000 [14:06<17:36,  5.31step/s, loss=0.052857, elapsed=14.1min]

Entraînement:  44%|████▍     | 4394/10000 [14:06<17:36,  5.31step/s, loss=0.067350, elapsed=14.1min]

Entraînement:  44%|████▍     | 4395/10000 [14:06<17:36,  5.30step/s, loss=0.067350, elapsed=14.1min]

Entraînement:  44%|████▍     | 4395/10000 [14:06<17:36,  5.30step/s, loss=0.023234, elapsed=14.1min]

Entraînement:  44%|████▍     | 4396/10000 [14:06<17:39,  5.29step/s, loss=0.023234, elapsed=14.1min]

Entraînement:  44%|████▍     | 4396/10000 [14:06<17:39,  5.29step/s, loss=0.106921, elapsed=14.1min]

Entraînement:  44%|████▍     | 4397/10000 [14:06<17:40,  5.28step/s, loss=0.106921, elapsed=14.1min]

Entraînement:  44%|████▍     | 4397/10000 [14:06<17:40,  5.28step/s, loss=0.078348, elapsed=14.1min]

Entraînement:  44%|████▍     | 4398/10000 [14:06<17:38,  5.29step/s, loss=0.078348, elapsed=14.1min]

Entraînement:  44%|████▍     | 4398/10000 [14:06<17:38,  5.29step/s, loss=0.039798, elapsed=14.1min]

Entraînement:  44%|████▍     | 4399/10000 [14:07<17:38,  5.29step/s, loss=0.039798, elapsed=14.1min]

Entraînement:  44%|████▍     | 4399/10000 [14:07<17:38,  5.29step/s, loss=0.048889, elapsed=14.1min]

Entraînement:  44%|████▍     | 4400/10000 [14:07<17:37,  5.29step/s, loss=0.048889, elapsed=14.1min]

Entraînement:  44%|████▍     | 4400/10000 [14:07<17:37,  5.29step/s, loss=0.027512, elapsed=14.1min]

Entraînement:  44%|████▍     | 4400/10000 [14:07<17:37,  5.29step/s, loss=0.027512, elapsed=14.1min]

Entraînement:  44%|████▍     | 4401/10000 [14:07<17:48,  5.24step/s, loss=0.027512, elapsed=14.1min]

Entraînement:  44%|████▍     | 4401/10000 [14:07<17:48,  5.24step/s, loss=0.053300, elapsed=14.1min]

Step 4400/10000 | Train loss: 0.027512 | Elapsed: 14.1min | ETA: 18.0min

Entraînement:  44%|████▍     | 4402/10000 [14:07<17:44,  5.26step/s, loss=0.053300, elapsed=14.1min]

Entraînement:  44%|████▍     | 4402/10000 [14:07<17:44,  5.26step/s, loss=0.024253, elapsed=14.1min]

Entraînement:  44%|████▍     | 4403/10000 [14:07<17:41,  5.27step/s, loss=0.024253, elapsed=14.1min]

Entraînement:  44%|████▍     | 4403/10000 [14:07<17:41,  5.27step/s, loss=0.111709, elapsed=14.1min]

Entraînement:  44%|████▍     | 4404/10000 [14:08<17:38,  5.28step/s, loss=0.111709, elapsed=14.1min]

Entraînement:  44%|████▍     | 4404/10000 [14:08<17:38,  5.28step/s, loss=0.038437, elapsed=14.1min]

Entraînement:  44%|████▍     | 4405/10000 [14:08<17:40,  5.28step/s, loss=0.038437, elapsed=14.1min]

Entraînement:  44%|████▍     | 4405/10000 [14:08<17:40,  5.28step/s, loss=0.021978, elapsed=14.1min]

Entraînement:  44%|████▍     | 4406/10000 [14:08<17:42,  5.26step/s, loss=0.021978, elapsed=14.1min]

Entraînement:  44%|████▍     | 4406/10000 [14:08<17:42,  5.26step/s, loss=0.020260, elapsed=14.1min]

Entraînement:  44%|████▍     | 4407/10000 [14:08<17:41,  5.27step/s, loss=0.020260, elapsed=14.1min]

Entraînement:  44%|████▍     | 4407/10000 [14:08<17:41,  5.27step/s, loss=0.021832, elapsed=14.1min]

Entraînement:  44%|████▍     | 4408/10000 [14:08<17:41,  5.27step/s, loss=0.021832, elapsed=14.1min]

Entraînement:  44%|████▍     | 4408/10000 [14:08<17:41,  5.27step/s, loss=0.034834, elapsed=14.1min]

Entraînement:  44%|████▍     | 4409/10000 [14:09<17:54,  5.20step/s, loss=0.034834, elapsed=14.1min]

Entraînement:  44%|████▍     | 4409/10000 [14:09<17:54,  5.20step/s, loss=0.078551, elapsed=14.2min]

Entraînement:  44%|████▍     | 4410/10000 [14:09<17:50,  5.22step/s, loss=0.078551, elapsed=14.2min]

Entraînement:  44%|████▍     | 4410/10000 [14:09<17:50,  5.22step/s, loss=0.039884, elapsed=14.2min]

Entraînement:  44%|████▍     | 4411/10000 [14:09<17:45,  5.25step/s, loss=0.039884, elapsed=14.2min]

Entraînement:  44%|████▍     | 4411/10000 [14:09<17:45,  5.25step/s, loss=0.050683, elapsed=14.2min]

Entraînement:  44%|████▍     | 4412/10000 [14:09<17:41,  5.27step/s, loss=0.050683, elapsed=14.2min]

Entraînement:  44%|████▍     | 4412/10000 [14:09<17:41,  5.27step/s, loss=0.038366, elapsed=14.2min]

Entraînement:  44%|████▍     | 4413/10000 [14:09<17:42,  5.26step/s, loss=0.038366, elapsed=14.2min]

Entraînement:  44%|████▍     | 4413/10000 [14:09<17:42,  5.26step/s, loss=0.046854, elapsed=14.2min]

Entraînement:  44%|████▍     | 4414/10000 [14:10<17:40,  5.27step/s, loss=0.046854, elapsed=14.2min]

Entraînement:  44%|████▍     | 4414/10000 [14:10<17:40,  5.27step/s, loss=0.033260, elapsed=14.2min]

Entraînement:  44%|████▍     | 4415/10000 [14:10<17:47,  5.23step/s, loss=0.033260, elapsed=14.2min]

Entraînement:  44%|████▍     | 4415/10000 [14:10<17:47,  5.23step/s, loss=0.028050, elapsed=14.2min]

Entraînement:  44%|████▍     | 4416/10000 [14:10<17:42,  5.25step/s, loss=0.028050, elapsed=14.2min]

Entraînement:  44%|████▍     | 4416/10000 [14:10<17:42,  5.25step/s, loss=0.075420, elapsed=14.2min]

Entraînement:  44%|████▍     | 4417/10000 [14:10<17:41,  5.26step/s, loss=0.075420, elapsed=14.2min]

Entraînement:  44%|████▍     | 4417/10000 [14:10<17:41,  5.26step/s, loss=0.070545, elapsed=14.2min]

Entraînement:  44%|████▍     | 4418/10000 [14:10<17:38,  5.27step/s, loss=0.070545, elapsed=14.2min]

Entraînement:  44%|████▍     | 4418/10000 [14:10<17:38,  5.27step/s, loss=0.031037, elapsed=14.2min]

Entraînement:  44%|████▍     | 4419/10000 [14:10<17:38,  5.27step/s, loss=0.031037, elapsed=14.2min]

Entraînement:  44%|████▍     | 4419/10000 [14:10<17:38,  5.27step/s, loss=0.065081, elapsed=14.2min]

Entraînement:  44%|████▍     | 4420/10000 [14:11<17:36,  5.28step/s, loss=0.065081, elapsed=14.2min]

Entraînement:  44%|████▍     | 4420/10000 [14:11<17:36,  5.28step/s, loss=0.028315, elapsed=14.2min]

Entraînement:  44%|████▍     | 4421/10000 [14:11<17:35,  5.29step/s, loss=0.028315, elapsed=14.2min]

Entraînement:  44%|████▍     | 4421/10000 [14:11<17:35,  5.29step/s, loss=0.022236, elapsed=14.2min]

Entraînement:  44%|████▍     | 4422/10000 [14:11<17:35,  5.28step/s, loss=0.022236, elapsed=14.2min]

Entraînement:  44%|████▍     | 4422/10000 [14:11<17:35,  5.28step/s, loss=0.040825, elapsed=14.2min]

Entraînement:  44%|████▍     | 4423/10000 [14:11<17:33,  5.29step/s, loss=0.040825, elapsed=14.2min]

Entraînement:  44%|████▍     | 4423/10000 [14:11<17:33,  5.29step/s, loss=0.055647, elapsed=14.2min]

Entraînement:  44%|████▍     | 4424/10000 [14:11<17:34,  5.29step/s, loss=0.055647, elapsed=14.2min]

Entraînement:  44%|████▍     | 4424/10000 [14:11<17:34,  5.29step/s, loss=0.026331, elapsed=14.2min]

Entraînement:  44%|████▍     | 4425/10000 [14:12<17:32,  5.30step/s, loss=0.026331, elapsed=14.2min]

Entraînement:  44%|████▍     | 4425/10000 [14:12<17:32,  5.30step/s, loss=0.069568, elapsed=14.2min]

Entraînement:  44%|████▍     | 4426/10000 [14:12<17:32,  5.29step/s, loss=0.069568, elapsed=14.2min]

Entraînement:  44%|████▍     | 4426/10000 [14:12<17:32,  5.29step/s, loss=0.120826, elapsed=14.2min]

Entraînement:  44%|████▍     | 4427/10000 [14:12<17:32,  5.29step/s, loss=0.120826, elapsed=14.2min]

Entraînement:  44%|████▍     | 4427/10000 [14:12<17:32,  5.29step/s, loss=0.098121, elapsed=14.2min]

Entraînement:  44%|████▍     | 4428/10000 [14:12<17:32,  5.29step/s, loss=0.098121, elapsed=14.2min]

Entraînement:  44%|████▍     | 4428/10000 [14:12<17:32,  5.29step/s, loss=0.058897, elapsed=14.2min]

Entraînement:  44%|████▍     | 4429/10000 [14:12<17:31,  5.30step/s, loss=0.058897, elapsed=14.2min]

Entraînement:  44%|████▍     | 4429/10000 [14:12<17:31,  5.30step/s, loss=0.059026, elapsed=14.2min]

Entraînement:  44%|████▍     | 4430/10000 [14:13<17:33,  5.29step/s, loss=0.059026, elapsed=14.2min]

Entraînement:  44%|████▍     | 4430/10000 [14:13<17:33,  5.29step/s, loss=0.038906, elapsed=14.2min]

Entraînement:  44%|████▍     | 4431/10000 [14:13<17:33,  5.29step/s, loss=0.038906, elapsed=14.2min]

Entraînement:  44%|████▍     | 4431/10000 [14:13<17:33,  5.29step/s, loss=0.028959, elapsed=14.2min]

Entraînement:  44%|████▍     | 4432/10000 [14:13<17:32,  5.29step/s, loss=0.028959, elapsed=14.2min]

Entraînement:  44%|████▍     | 4432/10000 [14:13<17:32,  5.29step/s, loss=0.041100, elapsed=14.2min]

Entraînement:  44%|████▍     | 4433/10000 [14:13<17:33,  5.28step/s, loss=0.041100, elapsed=14.2min]

Entraînement:  44%|████▍     | 4433/10000 [14:13<17:33,  5.28step/s, loss=0.031069, elapsed=14.2min]

Entraînement:  44%|████▍     | 4434/10000 [14:13<17:33,  5.28step/s, loss=0.031069, elapsed=14.2min]

Entraînement:  44%|████▍     | 4434/10000 [14:13<17:33,  5.28step/s, loss=0.026429, elapsed=14.2min]

Entraînement:  44%|████▍     | 4435/10000 [14:13<17:33,  5.28step/s, loss=0.026429, elapsed=14.2min]

Entraînement:  44%|████▍     | 4435/10000 [14:13<17:33,  5.28step/s, loss=0.020482, elapsed=14.2min]

Entraînement:  44%|████▍     | 4436/10000 [14:14<17:32,  5.28step/s, loss=0.020482, elapsed=14.2min]

Entraînement:  44%|████▍     | 4436/10000 [14:14<17:32,  5.28step/s, loss=0.102617, elapsed=14.2min]

Entraînement:  44%|████▍     | 4437/10000 [14:14<17:34,  5.27step/s, loss=0.102617, elapsed=14.2min]

Entraînement:  44%|████▍     | 4437/10000 [14:14<17:34,  5.27step/s, loss=0.042293, elapsed=14.2min]

Entraînement:  44%|████▍     | 4438/10000 [14:14<17:34,  5.28step/s, loss=0.042293, elapsed=14.2min]

Entraînement:  44%|████▍     | 4438/10000 [14:14<17:34,  5.28step/s, loss=0.046157, elapsed=14.2min]

Entraînement:  44%|████▍     | 4439/10000 [14:14<17:33,  5.28step/s, loss=0.046157, elapsed=14.2min]

Entraînement:  44%|████▍     | 4439/10000 [14:14<17:33,  5.28step/s, loss=0.071097, elapsed=14.2min]

Entraînement:  44%|████▍     | 4440/10000 [14:14<17:34,  5.27step/s, loss=0.071097, elapsed=14.2min]

Entraînement:  44%|████▍     | 4440/10000 [14:14<17:34,  5.27step/s, loss=0.078058, elapsed=14.2min]

Entraînement:  44%|████▍     | 4441/10000 [14:15<17:33,  5.28step/s, loss=0.078058, elapsed=14.2min]

Entraînement:  44%|████▍     | 4441/10000 [14:15<17:33,  5.28step/s, loss=0.061870, elapsed=14.3min]

Entraînement:  44%|████▍     | 4442/10000 [14:15<17:33,  5.28step/s, loss=0.061870, elapsed=14.3min]

Entraînement:  44%|████▍     | 4442/10000 [14:15<17:33,  5.28step/s, loss=0.022193, elapsed=14.3min]

Entraînement:  44%|████▍     | 4443/10000 [14:15<17:31,  5.28step/s, loss=0.022193, elapsed=14.3min]

Entraînement:  44%|████▍     | 4443/10000 [14:15<17:31,  5.28step/s, loss=0.045427, elapsed=14.3min]

Entraînement:  44%|████▍     | 4444/10000 [14:15<17:33,  5.27step/s, loss=0.045427, elapsed=14.3min]

Entraînement:  44%|████▍     | 4444/10000 [14:15<17:33,  5.27step/s, loss=0.051342, elapsed=14.3min]

Entraînement:  44%|████▍     | 4445/10000 [14:15<17:34,  5.27step/s, loss=0.051342, elapsed=14.3min]

Entraînement:  44%|████▍     | 4445/10000 [14:15<17:34,  5.27step/s, loss=0.040839, elapsed=14.3min]

Entraînement:  44%|████▍     | 4446/10000 [14:16<17:35,  5.26step/s, loss=0.040839, elapsed=14.3min]

Entraînement:  44%|████▍     | 4446/10000 [14:16<17:35,  5.26step/s, loss=0.089608, elapsed=14.3min]

Entraînement:  44%|████▍     | 4447/10000 [14:16<17:35,  5.26step/s, loss=0.089608, elapsed=14.3min]

Entraînement:  44%|████▍     | 4447/10000 [14:16<17:35,  5.26step/s, loss=0.057556, elapsed=14.3min]

Entraînement:  44%|████▍     | 4448/10000 [14:16<17:34,  5.26step/s, loss=0.057556, elapsed=14.3min]

Entraînement:  44%|████▍     | 4448/10000 [14:16<17:34,  5.26step/s, loss=0.036647, elapsed=14.3min]

Entraînement:  44%|████▍     | 4449/10000 [14:16<17:33,  5.27step/s, loss=0.036647, elapsed=14.3min]

Entraînement:  44%|████▍     | 4449/10000 [14:16<17:33,  5.27step/s, loss=0.061201, elapsed=14.3min]

Entraînement:  44%|████▍     | 4450/10000 [14:16<17:31,  5.28step/s, loss=0.061201, elapsed=14.3min]

Entraînement:  44%|████▍     | 4450/10000 [14:16<17:31,  5.28step/s, loss=0.156887, elapsed=14.3min]

Entraînement:  45%|████▍     | 4451/10000 [14:17<17:32,  5.27step/s, loss=0.156887, elapsed=14.3min]

Entraînement:  45%|████▍     | 4451/10000 [14:17<17:32,  5.27step/s, loss=0.107141, elapsed=14.3min]

Entraînement:  45%|████▍     | 4452/10000 [14:17<17:33,  5.27step/s, loss=0.107141, elapsed=14.3min]

Entraînement:  45%|████▍     | 4452/10000 [14:17<17:33,  5.27step/s, loss=0.123265, elapsed=14.3min]

Entraînement:  45%|████▍     | 4453/10000 [14:17<17:34,  5.26step/s, loss=0.123265, elapsed=14.3min]

Entraînement:  45%|████▍     | 4453/10000 [14:17<17:34,  5.26step/s, loss=0.036755, elapsed=14.3min]

Entraînement:  45%|████▍     | 4454/10000 [14:17<17:33,  5.26step/s, loss=0.036755, elapsed=14.3min]

Entraînement:  45%|████▍     | 4454/10000 [14:17<17:33,  5.26step/s, loss=0.052932, elapsed=14.3min]

Entraînement:  45%|████▍     | 4455/10000 [14:17<17:31,  5.28step/s, loss=0.052932, elapsed=14.3min]

Entraînement:  45%|████▍     | 4455/10000 [14:17<17:31,  5.28step/s, loss=0.040850, elapsed=14.3min]

Entraînement:  45%|████▍     | 4456/10000 [14:17<17:31,  5.27step/s, loss=0.040850, elapsed=14.3min]

Entraînement:  45%|████▍     | 4456/10000 [14:17<17:31,  5.27step/s, loss=0.073433, elapsed=14.3min]

Entraînement:  45%|████▍     | 4457/10000 [14:18<17:29,  5.28step/s, loss=0.073433, elapsed=14.3min]

Entraînement:  45%|████▍     | 4457/10000 [14:18<17:29,  5.28step/s, loss=0.035805, elapsed=14.3min]

Entraînement:  45%|████▍     | 4458/10000 [14:18<17:29,  5.28step/s, loss=0.035805, elapsed=14.3min]

Entraînement:  45%|████▍     | 4458/10000 [14:18<17:29,  5.28step/s, loss=0.042292, elapsed=14.3min]

Entraînement:  45%|████▍     | 4459/10000 [14:18<17:29,  5.28step/s, loss=0.042292, elapsed=14.3min]

Entraînement:  45%|████▍     | 4459/10000 [14:18<17:29,  5.28step/s, loss=0.050789, elapsed=14.3min]

Entraînement:  45%|████▍     | 4460/10000 [14:18<17:29,  5.28step/s, loss=0.050789, elapsed=14.3min]

Entraînement:  45%|████▍     | 4460/10000 [14:18<17:29,  5.28step/s, loss=0.030371, elapsed=14.3min]

Entraînement:  45%|████▍     | 4461/10000 [14:18<17:30,  5.27step/s, loss=0.030371, elapsed=14.3min]

Entraînement:  45%|████▍     | 4461/10000 [14:18<17:30,  5.27step/s, loss=0.056873, elapsed=14.3min]

Entraînement:  45%|████▍     | 4462/10000 [14:19<17:29,  5.28step/s, loss=0.056873, elapsed=14.3min]

Entraînement:  45%|████▍     | 4462/10000 [14:19<17:29,  5.28step/s, loss=0.064042, elapsed=14.3min]

Entraînement:  45%|████▍     | 4463/10000 [14:19<17:30,  5.27step/s, loss=0.064042, elapsed=14.3min]

Entraînement:  45%|████▍     | 4463/10000 [14:19<17:30,  5.27step/s, loss=0.048287, elapsed=14.3min]

Entraînement:  45%|████▍     | 4464/10000 [14:19<17:28,  5.28step/s, loss=0.048287, elapsed=14.3min]

Entraînement:  45%|████▍     | 4464/10000 [14:19<17:28,  5.28step/s, loss=0.041136, elapsed=14.3min]

Entraînement:  45%|████▍     | 4465/10000 [14:19<17:28,  5.28step/s, loss=0.041136, elapsed=14.3min]

Entraînement:  45%|████▍     | 4465/10000 [14:19<17:28,  5.28step/s, loss=0.112664, elapsed=14.3min]

Entraînement:  45%|████▍     | 4466/10000 [14:19<17:27,  5.28step/s, loss=0.112664, elapsed=14.3min]

Entraînement:  45%|████▍     | 4466/10000 [14:19<17:27,  5.28step/s, loss=0.050040, elapsed=14.3min]

Entraînement:  45%|████▍     | 4467/10000 [14:20<17:29,  5.27step/s, loss=0.050040, elapsed=14.3min]

Entraînement:  45%|████▍     | 4467/10000 [14:20<17:29,  5.27step/s, loss=0.099435, elapsed=14.3min]

Entraînement:  45%|████▍     | 4468/10000 [14:20<17:31,  5.26step/s, loss=0.099435, elapsed=14.3min]

Entraînement:  45%|████▍     | 4468/10000 [14:20<17:31,  5.26step/s, loss=0.041451, elapsed=14.3min]

Entraînement:  45%|████▍     | 4469/10000 [14:20<17:31,  5.26step/s, loss=0.041451, elapsed=14.3min]

Entraînement:  45%|████▍     | 4469/10000 [14:20<17:31,  5.26step/s, loss=0.036445, elapsed=14.3min]

Entraînement:  45%|████▍     | 4470/10000 [14:20<17:30,  5.27step/s, loss=0.036445, elapsed=14.3min]

Entraînement:  45%|████▍     | 4470/10000 [14:20<17:30,  5.27step/s, loss=0.049611, elapsed=14.3min]

Entraînement:  45%|████▍     | 4471/10000 [14:20<17:27,  5.28step/s, loss=0.049611, elapsed=14.3min]

Entraînement:  45%|████▍     | 4471/10000 [14:20<17:27,  5.28step/s, loss=0.024938, elapsed=14.3min]

Entraînement:  45%|████▍     | 4472/10000 [14:21<17:26,  5.28step/s, loss=0.024938, elapsed=14.3min]

Entraînement:  45%|████▍     | 4472/10000 [14:21<17:26,  5.28step/s, loss=0.047091, elapsed=14.4min]

Entraînement:  45%|████▍     | 4473/10000 [14:21<17:24,  5.29step/s, loss=0.047091, elapsed=14.4min]

Entraînement:  45%|████▍     | 4473/10000 [14:21<17:24,  5.29step/s, loss=0.050964, elapsed=14.4min]

Entraînement:  45%|████▍     | 4474/10000 [14:21<17:22,  5.30step/s, loss=0.050964, elapsed=14.4min]

Entraînement:  45%|████▍     | 4474/10000 [14:21<17:22,  5.30step/s, loss=0.047881, elapsed=14.4min]

Entraînement:  45%|████▍     | 4475/10000 [14:21<17:24,  5.29step/s, loss=0.047881, elapsed=14.4min]

Entraînement:  45%|████▍     | 4475/10000 [14:21<17:24,  5.29step/s, loss=0.039147, elapsed=14.4min]

Entraînement:  45%|████▍     | 4476/10000 [14:21<17:25,  5.29step/s, loss=0.039147, elapsed=14.4min]

Entraînement:  45%|████▍     | 4476/10000 [14:21<17:25,  5.29step/s, loss=0.035118, elapsed=14.4min]

Entraînement:  45%|████▍     | 4477/10000 [14:21<17:26,  5.28step/s, loss=0.035118, elapsed=14.4min]

Entraînement:  45%|████▍     | 4477/10000 [14:21<17:26,  5.28step/s, loss=0.063957, elapsed=14.4min]

Entraînement:  45%|████▍     | 4478/10000 [14:22<17:25,  5.28step/s, loss=0.063957, elapsed=14.4min]

Entraînement:  45%|████▍     | 4478/10000 [14:22<17:25,  5.28step/s, loss=0.036835, elapsed=14.4min]

Entraînement:  45%|████▍     | 4479/10000 [14:22<17:23,  5.29step/s, loss=0.036835, elapsed=14.4min]

Entraînement:  45%|████▍     | 4479/10000 [14:22<17:23,  5.29step/s, loss=0.027864, elapsed=14.4min]

Entraînement:  45%|████▍     | 4480/10000 [14:22<17:24,  5.29step/s, loss=0.027864, elapsed=14.4min]

Entraînement:  45%|████▍     | 4480/10000 [14:22<17:24,  5.29step/s, loss=0.039086, elapsed=14.4min]

Entraînement:  45%|████▍     | 4481/10000 [14:22<17:22,  5.29step/s, loss=0.039086, elapsed=14.4min]

Entraînement:  45%|████▍     | 4481/10000 [14:22<17:22,  5.29step/s, loss=0.054481, elapsed=14.4min]

Entraînement:  45%|████▍     | 4482/10000 [14:22<17:23,  5.29step/s, loss=0.054481, elapsed=14.4min]

Entraînement:  45%|████▍     | 4482/10000 [14:22<17:23,  5.29step/s, loss=0.035895, elapsed=14.4min]

Entraînement:  45%|████▍     | 4483/10000 [14:23<17:25,  5.28step/s, loss=0.035895, elapsed=14.4min]

Entraînement:  45%|████▍     | 4483/10000 [14:23<17:25,  5.28step/s, loss=0.124353, elapsed=14.4min]

Entraînement:  45%|████▍     | 4484/10000 [14:23<17:27,  5.27step/s, loss=0.124353, elapsed=14.4min]

Entraînement:  45%|████▍     | 4484/10000 [14:23<17:27,  5.27step/s, loss=0.110813, elapsed=14.4min]

Entraînement:  45%|████▍     | 4485/10000 [14:23<17:26,  5.27step/s, loss=0.110813, elapsed=14.4min]

Entraînement:  45%|████▍     | 4485/10000 [14:23<17:26,  5.27step/s, loss=0.028954, elapsed=14.4min]

Entraînement:  45%|████▍     | 4486/10000 [14:23<17:25,  5.28step/s, loss=0.028954, elapsed=14.4min]

Entraînement:  45%|████▍     | 4486/10000 [14:23<17:25,  5.28step/s, loss=0.088342, elapsed=14.4min]

Entraînement:  45%|████▍     | 4487/10000 [14:23<17:28,  5.26step/s, loss=0.088342, elapsed=14.4min]

Entraînement:  45%|████▍     | 4487/10000 [14:23<17:28,  5.26step/s, loss=0.037110, elapsed=14.4min]

Entraînement:  45%|████▍     | 4488/10000 [14:24<17:27,  5.26step/s, loss=0.037110, elapsed=14.4min]

Entraînement:  45%|████▍     | 4488/10000 [14:24<17:27,  5.26step/s, loss=0.030817, elapsed=14.4min]

Entraînement:  45%|████▍     | 4489/10000 [14:24<17:26,  5.27step/s, loss=0.030817, elapsed=14.4min]

Entraînement:  45%|████▍     | 4489/10000 [14:24<17:26,  5.27step/s, loss=0.071144, elapsed=14.4min]

Entraînement:  45%|████▍     | 4490/10000 [14:24<17:25,  5.27step/s, loss=0.071144, elapsed=14.4min]

Entraînement:  45%|████▍     | 4490/10000 [14:24<17:25,  5.27step/s, loss=0.027319, elapsed=14.4min]

Entraînement:  45%|████▍     | 4491/10000 [14:24<17:27,  5.26step/s, loss=0.027319, elapsed=14.4min]

Entraînement:  45%|████▍     | 4491/10000 [14:24<17:27,  5.26step/s, loss=0.035749, elapsed=14.4min]

Entraînement:  45%|████▍     | 4492/10000 [14:24<17:25,  5.27step/s, loss=0.035749, elapsed=14.4min]

Entraînement:  45%|████▍     | 4492/10000 [14:24<17:25,  5.27step/s, loss=0.055222, elapsed=14.4min]

Entraînement:  45%|████▍     | 4493/10000 [14:24<17:26,  5.26step/s, loss=0.055222, elapsed=14.4min]

Entraînement:  45%|████▍     | 4493/10000 [14:24<17:26,  5.26step/s, loss=0.039641, elapsed=14.4min]

Entraînement:  45%|████▍     | 4494/10000 [14:25<17:28,  5.25step/s, loss=0.039641, elapsed=14.4min]

Entraînement:  45%|████▍     | 4494/10000 [14:25<17:28,  5.25step/s, loss=0.050379, elapsed=14.4min]

Entraînement:  45%|████▍     | 4495/10000 [14:25<17:27,  5.25step/s, loss=0.050379, elapsed=14.4min]

Entraînement:  45%|████▍     | 4495/10000 [14:25<17:27,  5.25step/s, loss=0.033848, elapsed=14.4min]

Entraînement:  45%|████▍     | 4496/10000 [14:25<17:25,  5.26step/s, loss=0.033848, elapsed=14.4min]

Entraînement:  45%|████▍     | 4496/10000 [14:25<17:25,  5.26step/s, loss=0.046725, elapsed=14.4min]

Entraînement:  45%|████▍     | 4497/10000 [14:25<17:24,  5.27step/s, loss=0.046725, elapsed=14.4min]

Entraînement:  45%|████▍     | 4497/10000 [14:25<17:24,  5.27step/s, loss=0.063045, elapsed=14.4min]

Entraînement:  45%|████▍     | 4498/10000 [14:25<17:26,  5.26step/s, loss=0.063045, elapsed=14.4min]

Entraînement:  45%|████▍     | 4498/10000 [14:25<17:26,  5.26step/s, loss=0.091459, elapsed=14.4min]

Entraînement:  45%|████▍     | 4499/10000 [14:26<17:24,  5.27step/s, loss=0.091459, elapsed=14.4min]

Entraînement:  45%|████▍     | 4499/10000 [14:26<17:24,  5.27step/s, loss=0.039400, elapsed=14.4min]

Entraînement:  45%|████▌     | 4500/10000 [14:26<17:23,  5.27step/s, loss=0.039400, elapsed=14.4min]

Entraînement:  45%|████▌     | 4500/10000 [14:26<17:23,  5.27step/s, loss=0.048547, elapsed=14.4min]

Entraînement:  45%|████▌     | 4500/10000 [14:26<17:23,  5.27step/s, loss=0.048547, elapsed=14.4min]

Entraînement:  45%|████▌     | 4501/10000 [14:26<17:30,  5.23step/s, loss=0.048547, elapsed=14.4min]

Entraînement:  45%|████▌     | 4501/10000 [14:26<17:30,  5.23step/s, loss=0.038795, elapsed=14.4min]

Step 4500/10000 | Train loss: 0.048547 | Elapsed: 14.4min | ETA: 17.6min

Entraînement:  45%|████▌     | 4502/10000 [14:26<17:27,  5.25step/s, loss=0.038795, elapsed=14.4min]

Entraînement:  45%|████▌     | 4502/10000 [14:26<17:27,  5.25step/s, loss=0.101743, elapsed=14.4min]

Entraînement:  45%|████▌     | 4503/10000 [14:26<17:25,  5.26step/s, loss=0.101743, elapsed=14.4min]

Entraînement:  45%|████▌     | 4503/10000 [14:26<17:25,  5.26step/s, loss=0.036991, elapsed=14.4min]

Entraînement:  45%|████▌     | 4504/10000 [14:27<17:23,  5.27step/s, loss=0.036991, elapsed=14.4min]

Entraînement:  45%|████▌     | 4504/10000 [14:27<17:23,  5.27step/s, loss=0.048643, elapsed=14.5min]

Entraînement:  45%|████▌     | 4505/10000 [14:27<17:21,  5.28step/s, loss=0.048643, elapsed=14.5min]

Entraînement:  45%|████▌     | 4505/10000 [14:27<17:21,  5.28step/s, loss=0.031125, elapsed=14.5min]

Entraînement:  45%|████▌     | 4506/10000 [14:27<17:20,  5.28step/s, loss=0.031125, elapsed=14.5min]

Entraînement:  45%|████▌     | 4506/10000 [14:27<17:20,  5.28step/s, loss=0.029690, elapsed=14.5min]

Entraînement:  45%|████▌     | 4507/10000 [14:27<17:20,  5.28step/s, loss=0.029690, elapsed=14.5min]

Entraînement:  45%|████▌     | 4507/10000 [14:27<17:20,  5.28step/s, loss=0.026119, elapsed=14.5min]

Entraînement:  45%|████▌     | 4508/10000 [14:27<17:19,  5.29step/s, loss=0.026119, elapsed=14.5min]

Entraînement:  45%|████▌     | 4508/10000 [14:27<17:19,  5.29step/s, loss=0.019090, elapsed=14.5min]

Entraînement:  45%|████▌     | 4509/10000 [14:28<17:19,  5.28step/s, loss=0.019090, elapsed=14.5min]

Entraînement:  45%|████▌     | 4509/10000 [14:28<17:19,  5.28step/s, loss=0.035134, elapsed=14.5min]

Entraînement:  45%|████▌     | 4510/10000 [14:28<17:18,  5.29step/s, loss=0.035134, elapsed=14.5min]

Entraînement:  45%|████▌     | 4510/10000 [14:28<17:18,  5.29step/s, loss=0.035218, elapsed=14.5min]

Entraînement:  45%|████▌     | 4511/10000 [14:28<17:18,  5.29step/s, loss=0.035218, elapsed=14.5min]

Entraînement:  45%|████▌     | 4511/10000 [14:28<17:18,  5.29step/s, loss=0.073728, elapsed=14.5min]

Entraînement:  45%|████▌     | 4512/10000 [14:28<17:17,  5.29step/s, loss=0.073728, elapsed=14.5min]

Entraînement:  45%|████▌     | 4512/10000 [14:28<17:17,  5.29step/s, loss=0.028094, elapsed=14.5min]

Entraînement:  45%|████▌     | 4513/10000 [14:28<17:15,  5.30step/s, loss=0.028094, elapsed=14.5min]

Entraînement:  45%|████▌     | 4513/10000 [14:28<17:15,  5.30step/s, loss=0.031863, elapsed=14.5min]

Entraînement:  45%|████▌     | 4514/10000 [14:28<17:18,  5.28step/s, loss=0.031863, elapsed=14.5min]

Entraînement:  45%|████▌     | 4514/10000 [14:28<17:18,  5.28step/s, loss=0.031405, elapsed=14.5min]

Entraînement:  45%|████▌     | 4515/10000 [14:29<17:16,  5.29step/s, loss=0.031405, elapsed=14.5min]

Entraînement:  45%|████▌     | 4515/10000 [14:29<17:16,  5.29step/s, loss=0.051824, elapsed=14.5min]

Entraînement:  45%|████▌     | 4516/10000 [14:29<17:18,  5.28step/s, loss=0.051824, elapsed=14.5min]

Entraînement:  45%|████▌     | 4516/10000 [14:29<17:18,  5.28step/s, loss=0.052529, elapsed=14.5min]

Entraînement:  45%|████▌     | 4517/10000 [14:29<17:16,  5.29step/s, loss=0.052529, elapsed=14.5min]

Entraînement:  45%|████▌     | 4517/10000 [14:29<17:16,  5.29step/s, loss=0.037312, elapsed=14.5min]

Entraînement:  45%|████▌     | 4518/10000 [14:29<17:16,  5.29step/s, loss=0.037312, elapsed=14.5min]

Entraînement:  45%|████▌     | 4518/10000 [14:29<17:16,  5.29step/s, loss=0.052813, elapsed=14.5min]

Entraînement:  45%|████▌     | 4519/10000 [14:29<17:17,  5.28step/s, loss=0.052813, elapsed=14.5min]

Entraînement:  45%|████▌     | 4519/10000 [14:29<17:17,  5.28step/s, loss=0.027108, elapsed=14.5min]

Entraînement:  45%|████▌     | 4520/10000 [14:30<17:17,  5.28step/s, loss=0.027108, elapsed=14.5min]

Entraînement:  45%|████▌     | 4520/10000 [14:30<17:17,  5.28step/s, loss=0.146611, elapsed=14.5min]

Entraînement:  45%|████▌     | 4521/10000 [14:30<17:18,  5.27step/s, loss=0.146611, elapsed=14.5min]

Entraînement:  45%|████▌     | 4521/10000 [14:30<17:18,  5.27step/s, loss=0.038482, elapsed=14.5min]

Entraînement:  45%|████▌     | 4522/10000 [14:30<17:19,  5.27step/s, loss=0.038482, elapsed=14.5min]

Entraînement:  45%|████▌     | 4522/10000 [14:30<17:19,  5.27step/s, loss=0.081211, elapsed=14.5min]

Entraînement:  45%|████▌     | 4523/10000 [14:30<17:21,  5.26step/s, loss=0.081211, elapsed=14.5min]

Entraînement:  45%|████▌     | 4523/10000 [14:30<17:21,  5.26step/s, loss=0.051098, elapsed=14.5min]

Entraînement:  45%|████▌     | 4524/10000 [14:30<17:21,  5.26step/s, loss=0.051098, elapsed=14.5min]

Entraînement:  45%|████▌     | 4524/10000 [14:30<17:21,  5.26step/s, loss=0.049592, elapsed=14.5min]

Entraînement:  45%|████▌     | 4525/10000 [14:31<17:20,  5.26step/s, loss=0.049592, elapsed=14.5min]

Entraînement:  45%|████▌     | 4525/10000 [14:31<17:20,  5.26step/s, loss=0.103692, elapsed=14.5min]

Entraînement:  45%|████▌     | 4526/10000 [14:31<17:19,  5.26step/s, loss=0.103692, elapsed=14.5min]

Entraînement:  45%|████▌     | 4526/10000 [14:31<17:19,  5.26step/s, loss=0.079798, elapsed=14.5min]

Entraînement:  45%|████▌     | 4527/10000 [14:31<17:18,  5.27step/s, loss=0.079798, elapsed=14.5min]

Entraînement:  45%|████▌     | 4527/10000 [14:31<17:18,  5.27step/s, loss=0.101136, elapsed=14.5min]

Entraînement:  45%|████▌     | 4528/10000 [14:31<17:20,  5.26step/s, loss=0.101136, elapsed=14.5min]

Entraînement:  45%|████▌     | 4528/10000 [14:31<17:20,  5.26step/s, loss=0.051036, elapsed=14.5min]

Entraînement:  45%|████▌     | 4529/10000 [14:31<17:25,  5.23step/s, loss=0.051036, elapsed=14.5min]

Entraînement:  45%|████▌     | 4529/10000 [14:31<17:25,  5.23step/s, loss=0.110607, elapsed=14.5min]

Entraînement:  45%|████▌     | 4530/10000 [14:32<17:24,  5.24step/s, loss=0.110607, elapsed=14.5min]

Entraînement:  45%|████▌     | 4530/10000 [14:32<17:24,  5.24step/s, loss=0.074549, elapsed=14.5min]

Entraînement:  45%|████▌     | 4531/10000 [14:32<17:21,  5.25step/s, loss=0.074549, elapsed=14.5min]

Entraînement:  45%|████▌     | 4531/10000 [14:32<17:21,  5.25step/s, loss=0.043342, elapsed=14.5min]

Entraînement:  45%|████▌     | 4532/10000 [14:32<17:21,  5.25step/s, loss=0.043342, elapsed=14.5min]

Entraînement:  45%|████▌     | 4532/10000 [14:32<17:21,  5.25step/s, loss=0.067464, elapsed=14.5min]

Entraînement:  45%|████▌     | 4533/10000 [14:32<17:31,  5.20step/s, loss=0.067464, elapsed=14.5min]

Entraînement:  45%|████▌     | 4533/10000 [14:32<17:31,  5.20step/s, loss=0.028893, elapsed=14.5min]

Entraînement:  45%|████▌     | 4534/10000 [14:32<17:27,  5.22step/s, loss=0.028893, elapsed=14.5min]

Entraînement:  45%|████▌     | 4534/10000 [14:32<17:27,  5.22step/s, loss=0.103382, elapsed=14.5min]

Entraînement:  45%|████▌     | 4535/10000 [14:32<17:25,  5.23step/s, loss=0.103382, elapsed=14.5min]

Entraînement:  45%|████▌     | 4535/10000 [14:32<17:25,  5.23step/s, loss=0.041520, elapsed=14.5min]

Entraînement:  45%|████▌     | 4536/10000 [14:33<17:23,  5.24step/s, loss=0.041520, elapsed=14.5min]

Entraînement:  45%|████▌     | 4536/10000 [14:33<17:23,  5.24step/s, loss=0.104196, elapsed=14.6min]

Entraînement:  45%|████▌     | 4537/10000 [14:33<17:23,  5.24step/s, loss=0.104196, elapsed=14.6min]

Entraînement:  45%|████▌     | 4537/10000 [14:33<17:23,  5.24step/s, loss=0.034190, elapsed=14.6min]

Entraînement:  45%|████▌     | 4538/10000 [14:33<17:20,  5.25step/s, loss=0.034190, elapsed=14.6min]

Entraînement:  45%|████▌     | 4538/10000 [14:33<17:20,  5.25step/s, loss=0.038150, elapsed=14.6min]

Entraînement:  45%|████▌     | 4539/10000 [14:33<17:27,  5.21step/s, loss=0.038150, elapsed=14.6min]

Entraînement:  45%|████▌     | 4539/10000 [14:33<17:27,  5.21step/s, loss=0.093515, elapsed=14.6min]

Entraînement:  45%|████▌     | 4540/10000 [14:33<17:33,  5.18step/s, loss=0.093515, elapsed=14.6min]

Entraînement:  45%|████▌     | 4540/10000 [14:33<17:33,  5.18step/s, loss=0.050333, elapsed=14.6min]

Entraînement:  45%|████▌     | 4541/10000 [14:34<17:34,  5.17step/s, loss=0.050333, elapsed=14.6min]

Entraînement:  45%|████▌     | 4541/10000 [14:34<17:34,  5.17step/s, loss=0.069577, elapsed=14.6min]

Entraînement:  45%|████▌     | 4542/10000 [14:34<17:33,  5.18step/s, loss=0.069577, elapsed=14.6min]

Entraînement:  45%|████▌     | 4542/10000 [14:34<17:33,  5.18step/s, loss=0.043977, elapsed=14.6min]

Entraînement:  45%|████▌     | 4543/10000 [14:34<17:35,  5.17step/s, loss=0.043977, elapsed=14.6min]

Entraînement:  45%|████▌     | 4543/10000 [14:34<17:35,  5.17step/s, loss=0.033928, elapsed=14.6min]

Entraînement:  45%|████▌     | 4544/10000 [14:34<17:33,  5.18step/s, loss=0.033928, elapsed=14.6min]

Entraînement:  45%|████▌     | 4544/10000 [14:34<17:33,  5.18step/s, loss=0.071384, elapsed=14.6min]

Entraînement:  45%|████▌     | 4545/10000 [14:34<17:31,  5.19step/s, loss=0.071384, elapsed=14.6min]

Entraînement:  45%|████▌     | 4545/10000 [14:34<17:31,  5.19step/s, loss=0.092612, elapsed=14.6min]

Entraînement:  45%|████▌     | 4546/10000 [14:35<17:25,  5.22step/s, loss=0.092612, elapsed=14.6min]

Entraînement:  45%|████▌     | 4546/10000 [14:35<17:25,  5.22step/s, loss=0.086459, elapsed=14.6min]

Entraînement:  45%|████▌     | 4547/10000 [14:35<17:22,  5.23step/s, loss=0.086459, elapsed=14.6min]

Entraînement:  45%|████▌     | 4547/10000 [14:35<17:22,  5.23step/s, loss=0.018319, elapsed=14.6min]

Entraînement:  45%|████▌     | 4548/10000 [14:35<17:18,  5.25step/s, loss=0.018319, elapsed=14.6min]

Entraînement:  45%|████▌     | 4548/10000 [14:35<17:18,  5.25step/s, loss=0.025306, elapsed=14.6min]

Entraînement:  45%|████▌     | 4549/10000 [14:35<17:17,  5.25step/s, loss=0.025306, elapsed=14.6min]

Entraînement:  45%|████▌     | 4549/10000 [14:35<17:17,  5.25step/s, loss=0.061582, elapsed=14.6min]

Entraînement:  46%|████▌     | 4550/10000 [14:35<17:16,  5.26step/s, loss=0.061582, elapsed=14.6min]

Entraînement:  46%|████▌     | 4550/10000 [14:35<17:16,  5.26step/s, loss=0.044369, elapsed=14.6min]

Entraînement:  46%|████▌     | 4551/10000 [14:36<17:13,  5.27step/s, loss=0.044369, elapsed=14.6min]

Entraînement:  46%|████▌     | 4551/10000 [14:36<17:13,  5.27step/s, loss=0.142467, elapsed=14.6min]

Entraînement:  46%|████▌     | 4552/10000 [14:36<17:13,  5.27step/s, loss=0.142467, elapsed=14.6min]

Entraînement:  46%|████▌     | 4552/10000 [14:36<17:13,  5.27step/s, loss=0.061222, elapsed=14.6min]

Entraînement:  46%|████▌     | 4553/10000 [14:36<17:11,  5.28step/s, loss=0.061222, elapsed=14.6min]

Entraînement:  46%|████▌     | 4553/10000 [14:36<17:11,  5.28step/s, loss=0.053450, elapsed=14.6min]

Entraînement:  46%|████▌     | 4554/10000 [14:36<17:12,  5.28step/s, loss=0.053450, elapsed=14.6min]

Entraînement:  46%|████▌     | 4554/10000 [14:36<17:12,  5.28step/s, loss=0.055946, elapsed=14.6min]

Entraînement:  46%|████▌     | 4555/10000 [14:36<17:11,  5.28step/s, loss=0.055946, elapsed=14.6min]

Entraînement:  46%|████▌     | 4555/10000 [14:36<17:11,  5.28step/s, loss=0.030321, elapsed=14.6min]

Entraînement:  46%|████▌     | 4556/10000 [14:36<17:11,  5.28step/s, loss=0.030321, elapsed=14.6min]

Entraînement:  46%|████▌     | 4556/10000 [14:36<17:11,  5.28step/s, loss=0.031804, elapsed=14.6min]

Entraînement:  46%|████▌     | 4557/10000 [14:37<17:11,  5.28step/s, loss=0.031804, elapsed=14.6min]

Entraînement:  46%|████▌     | 4557/10000 [14:37<17:11,  5.28step/s, loss=0.046463, elapsed=14.6min]

Entraînement:  46%|████▌     | 4558/10000 [14:37<17:13,  5.27step/s, loss=0.046463, elapsed=14.6min]

Entraînement:  46%|████▌     | 4558/10000 [14:37<17:13,  5.27step/s, loss=0.036314, elapsed=14.6min]

Entraînement:  46%|████▌     | 4559/10000 [14:37<17:12,  5.27step/s, loss=0.036314, elapsed=14.6min]

Entraînement:  46%|████▌     | 4559/10000 [14:37<17:12,  5.27step/s, loss=0.072026, elapsed=14.6min]

Entraînement:  46%|████▌     | 4560/10000 [14:37<17:11,  5.27step/s, loss=0.072026, elapsed=14.6min]

Entraînement:  46%|████▌     | 4560/10000 [14:37<17:11,  5.27step/s, loss=0.079495, elapsed=14.6min]

Entraînement:  46%|████▌     | 4561/10000 [14:37<17:12,  5.27step/s, loss=0.079495, elapsed=14.6min]

Entraînement:  46%|████▌     | 4561/10000 [14:37<17:12,  5.27step/s, loss=0.033701, elapsed=14.6min]

Entraînement:  46%|████▌     | 4562/10000 [14:38<17:13,  5.26step/s, loss=0.033701, elapsed=14.6min]

Entraînement:  46%|████▌     | 4562/10000 [14:38<17:13,  5.26step/s, loss=0.057587, elapsed=14.6min]

Entraînement:  46%|████▌     | 4563/10000 [14:38<17:13,  5.26step/s, loss=0.057587, elapsed=14.6min]

Entraînement:  46%|████▌     | 4563/10000 [14:38<17:13,  5.26step/s, loss=0.041721, elapsed=14.6min]

Entraînement:  46%|████▌     | 4564/10000 [14:38<17:11,  5.27step/s, loss=0.041721, elapsed=14.6min]

Entraînement:  46%|████▌     | 4564/10000 [14:38<17:11,  5.27step/s, loss=0.064399, elapsed=14.6min]

Entraînement:  46%|████▌     | 4565/10000 [14:38<17:12,  5.26step/s, loss=0.064399, elapsed=14.6min]

Entraînement:  46%|████▌     | 4565/10000 [14:38<17:12,  5.26step/s, loss=0.052123, elapsed=14.6min]

Entraînement:  46%|████▌     | 4566/10000 [14:38<17:20,  5.22step/s, loss=0.052123, elapsed=14.6min]

Entraînement:  46%|████▌     | 4566/10000 [14:38<17:20,  5.22step/s, loss=0.030908, elapsed=14.6min]

Entraînement:  46%|████▌     | 4567/10000 [14:39<17:18,  5.23step/s, loss=0.030908, elapsed=14.6min]

Entraînement:  46%|████▌     | 4567/10000 [14:39<17:18,  5.23step/s, loss=0.078208, elapsed=14.7min]

Entraînement:  46%|████▌     | 4568/10000 [14:39<17:17,  5.24step/s, loss=0.078208, elapsed=14.7min]

Entraînement:  46%|████▌     | 4568/10000 [14:39<17:17,  5.24step/s, loss=0.037481, elapsed=14.7min]

Entraînement:  46%|████▌     | 4569/10000 [14:39<17:12,  5.26step/s, loss=0.037481, elapsed=14.7min]

Entraînement:  46%|████▌     | 4569/10000 [14:39<17:12,  5.26step/s, loss=0.035492, elapsed=14.7min]

Entraînement:  46%|████▌     | 4570/10000 [14:39<17:12,  5.26step/s, loss=0.035492, elapsed=14.7min]

Entraînement:  46%|████▌     | 4570/10000 [14:39<17:12,  5.26step/s, loss=0.051539, elapsed=14.7min]

Entraînement:  46%|████▌     | 4571/10000 [14:39<17:10,  5.27step/s, loss=0.051539, elapsed=14.7min]

Entraînement:  46%|████▌     | 4571/10000 [14:39<17:10,  5.27step/s, loss=0.030989, elapsed=14.7min]

Entraînement:  46%|████▌     | 4572/10000 [14:40<17:09,  5.27step/s, loss=0.030989, elapsed=14.7min]

Entraînement:  46%|████▌     | 4572/10000 [14:40<17:09,  5.27step/s, loss=0.047679, elapsed=14.7min]

Entraînement:  46%|████▌     | 4573/10000 [14:40<17:09,  5.27step/s, loss=0.047679, elapsed=14.7min]

Entraînement:  46%|████▌     | 4573/10000 [14:40<17:09,  5.27step/s, loss=0.050202, elapsed=14.7min]

Entraînement:  46%|████▌     | 4574/10000 [14:40<17:09,  5.27step/s, loss=0.050202, elapsed=14.7min]

Entraînement:  46%|████▌     | 4574/10000 [14:40<17:09,  5.27step/s, loss=0.058160, elapsed=14.7min]

Entraînement:  46%|████▌     | 4575/10000 [14:40<17:10,  5.27step/s, loss=0.058160, elapsed=14.7min]

Entraînement:  46%|████▌     | 4575/10000 [14:40<17:10,  5.27step/s, loss=0.029840, elapsed=14.7min]

Entraînement:  46%|████▌     | 4576/10000 [14:40<17:08,  5.27step/s, loss=0.029840, elapsed=14.7min]

Entraînement:  46%|████▌     | 4576/10000 [14:40<17:08,  5.27step/s, loss=0.030038, elapsed=14.7min]

Entraînement:  46%|████▌     | 4577/10000 [14:40<17:09,  5.27step/s, loss=0.030038, elapsed=14.7min]

Entraînement:  46%|████▌     | 4577/10000 [14:40<17:09,  5.27step/s, loss=0.076691, elapsed=14.7min]

Entraînement:  46%|████▌     | 4578/10000 [14:41<17:02,  5.30step/s, loss=0.076691, elapsed=14.7min]

Entraînement:  46%|████▌     | 4578/10000 [14:41<17:02,  5.30step/s, loss=0.055578, elapsed=14.7min]

Entraînement:  46%|████▌     | 4579/10000 [14:41<17:04,  5.29step/s, loss=0.055578, elapsed=14.7min]

Entraînement:  46%|████▌     | 4579/10000 [14:41<17:04,  5.29step/s, loss=0.025380, elapsed=14.7min]

Entraînement:  46%|████▌     | 4580/10000 [14:41<17:05,  5.28step/s, loss=0.025380, elapsed=14.7min]

Entraînement:  46%|████▌     | 4580/10000 [14:41<17:05,  5.28step/s, loss=0.037437, elapsed=14.7min]

Entraînement:  46%|████▌     | 4581/10000 [14:41<17:05,  5.28step/s, loss=0.037437, elapsed=14.7min]

Entraînement:  46%|████▌     | 4581/10000 [14:41<17:05,  5.28step/s, loss=0.052215, elapsed=14.7min]

Entraînement:  46%|████▌     | 4582/10000 [14:41<17:06,  5.28step/s, loss=0.052215, elapsed=14.7min]

Entraînement:  46%|████▌     | 4582/10000 [14:41<17:06,  5.28step/s, loss=0.032990, elapsed=14.7min]

Entraînement:  46%|████▌     | 4583/10000 [14:42<17:10,  5.26step/s, loss=0.032990, elapsed=14.7min]

Entraînement:  46%|████▌     | 4583/10000 [14:42<17:10,  5.26step/s, loss=0.041616, elapsed=14.7min]

Entraînement:  46%|████▌     | 4584/10000 [14:42<17:07,  5.27step/s, loss=0.041616, elapsed=14.7min]

Entraînement:  46%|████▌     | 4584/10000 [14:42<17:07,  5.27step/s, loss=0.029035, elapsed=14.7min]

Entraînement:  46%|████▌     | 4585/10000 [14:42<17:06,  5.28step/s, loss=0.029035, elapsed=14.7min]

Entraînement:  46%|████▌     | 4585/10000 [14:42<17:06,  5.28step/s, loss=0.065779, elapsed=14.7min]

Entraînement:  46%|████▌     | 4586/10000 [14:42<17:05,  5.28step/s, loss=0.065779, elapsed=14.7min]

Entraînement:  46%|████▌     | 4586/10000 [14:42<17:05,  5.28step/s, loss=0.093641, elapsed=14.7min]

Entraînement:  46%|████▌     | 4587/10000 [14:42<17:05,  5.28step/s, loss=0.093641, elapsed=14.7min]

Entraînement:  46%|████▌     | 4587/10000 [14:42<17:05,  5.28step/s, loss=0.083247, elapsed=14.7min]

Entraînement:  46%|████▌     | 4588/10000 [14:43<17:04,  5.28step/s, loss=0.083247, elapsed=14.7min]

Entraînement:  46%|████▌     | 4588/10000 [14:43<17:04,  5.28step/s, loss=0.040776, elapsed=14.7min]

Entraînement:  46%|████▌     | 4589/10000 [14:43<17:05,  5.28step/s, loss=0.040776, elapsed=14.7min]

Entraînement:  46%|████▌     | 4589/10000 [14:43<17:05,  5.28step/s, loss=0.045756, elapsed=14.7min]

Entraînement:  46%|████▌     | 4590/10000 [14:43<17:06,  5.27step/s, loss=0.045756, elapsed=14.7min]

Entraînement:  46%|████▌     | 4590/10000 [14:43<17:06,  5.27step/s, loss=0.020073, elapsed=14.7min]

Entraînement:  46%|████▌     | 4591/10000 [14:43<17:04,  5.28step/s, loss=0.020073, elapsed=14.7min]

Entraînement:  46%|████▌     | 4591/10000 [14:43<17:04,  5.28step/s, loss=0.028515, elapsed=14.7min]

Entraînement:  46%|████▌     | 4592/10000 [14:43<17:04,  5.28step/s, loss=0.028515, elapsed=14.7min]

Entraînement:  46%|████▌     | 4592/10000 [14:43<17:04,  5.28step/s, loss=0.022590, elapsed=14.7min]

Entraînement:  46%|████▌     | 4593/10000 [14:44<17:03,  5.28step/s, loss=0.022590, elapsed=14.7min]

Entraînement:  46%|████▌     | 4593/10000 [14:44<17:03,  5.28step/s, loss=0.028553, elapsed=14.7min]

Entraînement:  46%|████▌     | 4594/10000 [14:44<17:01,  5.29step/s, loss=0.028553, elapsed=14.7min]

Entraînement:  46%|████▌     | 4594/10000 [14:44<17:01,  5.29step/s, loss=0.081475, elapsed=14.7min]

Entraînement:  46%|████▌     | 4595/10000 [14:44<17:01,  5.29step/s, loss=0.081475, elapsed=14.7min]

Entraînement:  46%|████▌     | 4595/10000 [14:44<17:01,  5.29step/s, loss=0.019787, elapsed=14.7min]

Entraînement:  46%|████▌     | 4596/10000 [14:44<17:00,  5.30step/s, loss=0.019787, elapsed=14.7min]

Entraînement:  46%|████▌     | 4596/10000 [14:44<17:00,  5.30step/s, loss=0.041377, elapsed=14.7min]

Entraînement:  46%|████▌     | 4597/10000 [14:44<17:02,  5.28step/s, loss=0.041377, elapsed=14.7min]

Entraînement:  46%|████▌     | 4597/10000 [14:44<17:02,  5.28step/s, loss=0.033236, elapsed=14.7min]

Entraînement:  46%|████▌     | 4598/10000 [14:44<17:03,  5.28step/s, loss=0.033236, elapsed=14.7min]

Entraînement:  46%|████▌     | 4598/10000 [14:44<17:03,  5.28step/s, loss=0.042503, elapsed=14.7min]

Entraînement:  46%|████▌     | 4599/10000 [14:45<16:57,  5.31step/s, loss=0.042503, elapsed=14.7min]

Entraînement:  46%|████▌     | 4599/10000 [14:45<16:57,  5.31step/s, loss=0.022108, elapsed=14.8min]

Entraînement:  46%|████▌     | 4600/10000 [14:45<16:55,  5.32step/s, loss=0.022108, elapsed=14.8min]

Entraînement:  46%|████▌     | 4600/10000 [14:45<16:55,  5.32step/s, loss=0.034085, elapsed=14.8min]

Entraînement:  46%|████▌     | 4600/10000 [14:45<16:55,  5.32step/s, loss=0.034085, elapsed=14.8min]

Entraînement:  46%|████▌     | 4601/10000 [14:45<16:57,  5.30step/s, loss=0.034085, elapsed=14.8min]

Entraînement:  46%|████▌     | 4601/10000 [14:45<16:57,  5.30step/s, loss=0.065914, elapsed=14.8min]

Step 4600/10000 | Train loss: 0.034085 | Elapsed: 14.8min | ETA: 17.3min

Entraînement:  46%|████▌     | 4602/10000 [14:45<16:52,  5.33step/s, loss=0.065914, elapsed=14.8min]

Entraînement:  46%|████▌     | 4602/10000 [14:45<16:52,  5.33step/s, loss=0.077684, elapsed=14.8min]

Entraînement:  46%|████▌     | 4603/10000 [14:45<16:50,  5.34step/s, loss=0.077684, elapsed=14.8min]

Entraînement:  46%|████▌     | 4603/10000 [14:45<16:50,  5.34step/s, loss=0.048014, elapsed=14.8min]

Entraînement:  46%|████▌     | 4604/10000 [14:46<16:49,  5.35step/s, loss=0.048014, elapsed=14.8min]

Entraînement:  46%|████▌     | 4604/10000 [14:46<16:49,  5.35step/s, loss=0.035497, elapsed=14.8min]

Entraînement:  46%|████▌     | 4605/10000 [14:46<16:48,  5.35step/s, loss=0.035497, elapsed=14.8min]

Entraînement:  46%|████▌     | 4605/10000 [14:46<16:48,  5.35step/s, loss=0.036514, elapsed=14.8min]

Entraînement:  46%|████▌     | 4606/10000 [14:46<16:50,  5.34step/s, loss=0.036514, elapsed=14.8min]

Entraînement:  46%|████▌     | 4606/10000 [14:46<16:50,  5.34step/s, loss=0.029863, elapsed=14.8min]

Entraînement:  46%|████▌     | 4607/10000 [14:46<16:49,  5.34step/s, loss=0.029863, elapsed=14.8min]

Entraînement:  46%|████▌     | 4607/10000 [14:46<16:49,  5.34step/s, loss=0.072456, elapsed=14.8min]

Entraînement:  46%|████▌     | 4608/10000 [14:46<16:49,  5.34step/s, loss=0.072456, elapsed=14.8min]

Entraînement:  46%|████▌     | 4608/10000 [14:46<16:49,  5.34step/s, loss=0.047664, elapsed=14.8min]

Entraînement:  46%|████▌     | 4609/10000 [14:47<16:47,  5.35step/s, loss=0.047664, elapsed=14.8min]

Entraînement:  46%|████▌     | 4609/10000 [14:47<16:47,  5.35step/s, loss=0.044527, elapsed=14.8min]

Entraînement:  46%|████▌     | 4610/10000 [14:47<16:48,  5.35step/s, loss=0.044527, elapsed=14.8min]

Entraînement:  46%|████▌     | 4610/10000 [14:47<16:48,  5.35step/s, loss=0.030444, elapsed=14.8min]

Entraînement:  46%|████▌     | 4611/10000 [14:47<16:47,  5.35step/s, loss=0.030444, elapsed=14.8min]

Entraînement:  46%|████▌     | 4611/10000 [14:47<16:47,  5.35step/s, loss=0.035413, elapsed=14.8min]

Entraînement:  46%|████▌     | 4612/10000 [14:47<16:47,  5.35step/s, loss=0.035413, elapsed=14.8min]

Entraînement:  46%|████▌     | 4612/10000 [14:47<16:47,  5.35step/s, loss=0.173580, elapsed=14.8min]

Entraînement:  46%|████▌     | 4613/10000 [14:47<16:45,  5.36step/s, loss=0.173580, elapsed=14.8min]

Entraînement:  46%|████▌     | 4613/10000 [14:47<16:45,  5.36step/s, loss=0.061305, elapsed=14.8min]

Entraînement:  46%|████▌     | 4614/10000 [14:47<16:45,  5.36step/s, loss=0.061305, elapsed=14.8min]

Entraînement:  46%|████▌     | 4614/10000 [14:47<16:45,  5.36step/s, loss=0.046469, elapsed=14.8min]

Entraînement:  46%|████▌     | 4615/10000 [14:48<16:48,  5.34step/s, loss=0.046469, elapsed=14.8min]

Entraînement:  46%|████▌     | 4615/10000 [14:48<16:48,  5.34step/s, loss=0.021524, elapsed=14.8min]

Entraînement:  46%|████▌     | 4616/10000 [14:48<16:48,  5.34step/s, loss=0.021524, elapsed=14.8min]

Entraînement:  46%|████▌     | 4616/10000 [14:48<16:48,  5.34step/s, loss=0.030898, elapsed=14.8min]

Entraînement:  46%|████▌     | 4617/10000 [14:48<16:47,  5.34step/s, loss=0.030898, elapsed=14.8min]

Entraînement:  46%|████▌     | 4617/10000 [14:48<16:47,  5.34step/s, loss=0.030317, elapsed=14.8min]

Entraînement:  46%|████▌     | 4618/10000 [14:48<16:48,  5.33step/s, loss=0.030317, elapsed=14.8min]

Entraînement:  46%|████▌     | 4618/10000 [14:48<16:48,  5.33step/s, loss=0.023227, elapsed=14.8min]

Entraînement:  46%|████▌     | 4619/10000 [14:48<16:47,  5.34step/s, loss=0.023227, elapsed=14.8min]

Entraînement:  46%|████▌     | 4619/10000 [14:48<16:47,  5.34step/s, loss=0.035650, elapsed=14.8min]

Entraînement:  46%|████▌     | 4620/10000 [14:49<16:47,  5.34step/s, loss=0.035650, elapsed=14.8min]

Entraînement:  46%|████▌     | 4620/10000 [14:49<16:47,  5.34step/s, loss=0.035996, elapsed=14.8min]

Entraînement:  46%|████▌     | 4621/10000 [14:49<16:51,  5.32step/s, loss=0.035996, elapsed=14.8min]

Entraînement:  46%|████▌     | 4621/10000 [14:49<16:51,  5.32step/s, loss=0.039102, elapsed=14.8min]

Entraînement:  46%|████▌     | 4622/10000 [14:49<16:53,  5.31step/s, loss=0.039102, elapsed=14.8min]

Entraînement:  46%|████▌     | 4622/10000 [14:49<16:53,  5.31step/s, loss=0.033051, elapsed=14.8min]

Entraînement:  46%|████▌     | 4623/10000 [14:49<16:56,  5.29step/s, loss=0.033051, elapsed=14.8min]

Entraînement:  46%|████▌     | 4623/10000 [14:49<16:56,  5.29step/s, loss=0.040291, elapsed=14.8min]

Entraînement:  46%|████▌     | 4624/10000 [14:49<16:58,  5.28step/s, loss=0.040291, elapsed=14.8min]

Entraînement:  46%|████▌     | 4624/10000 [14:49<16:58,  5.28step/s, loss=0.031142, elapsed=14.8min]

Entraînement:  46%|████▋     | 4625/10000 [14:50<17:00,  5.27step/s, loss=0.031142, elapsed=14.8min]

Entraînement:  46%|████▋     | 4625/10000 [14:50<17:00,  5.27step/s, loss=0.075021, elapsed=14.8min]

Entraînement:  46%|████▋     | 4626/10000 [14:50<16:59,  5.27step/s, loss=0.075021, elapsed=14.8min]

Entraînement:  46%|████▋     | 4626/10000 [14:50<16:59,  5.27step/s, loss=0.071256, elapsed=14.8min]

Entraînement:  46%|████▋     | 4627/10000 [14:50<16:59,  5.27step/s, loss=0.071256, elapsed=14.8min]

Entraînement:  46%|████▋     | 4627/10000 [14:50<16:59,  5.27step/s, loss=0.028566, elapsed=14.8min]

Entraînement:  46%|████▋     | 4628/10000 [14:50<16:59,  5.27step/s, loss=0.028566, elapsed=14.8min]

Entraînement:  46%|████▋     | 4628/10000 [14:50<16:59,  5.27step/s, loss=0.034547, elapsed=14.8min]

Entraînement:  46%|████▋     | 4629/10000 [14:50<16:57,  5.28step/s, loss=0.034547, elapsed=14.8min]

Entraînement:  46%|████▋     | 4629/10000 [14:50<16:57,  5.28step/s, loss=0.084573, elapsed=14.8min]

Entraînement:  46%|████▋     | 4630/10000 [14:50<16:57,  5.28step/s, loss=0.084573, elapsed=14.8min]

Entraînement:  46%|████▋     | 4630/10000 [14:50<16:57,  5.28step/s, loss=0.041968, elapsed=14.8min]

Entraînement:  46%|████▋     | 4631/10000 [14:51<16:56,  5.28step/s, loss=0.041968, elapsed=14.8min]

Entraînement:  46%|████▋     | 4631/10000 [14:51<16:56,  5.28step/s, loss=0.075080, elapsed=14.9min]

Entraînement:  46%|████▋     | 4632/10000 [14:51<16:56,  5.28step/s, loss=0.075080, elapsed=14.9min]

Entraînement:  46%|████▋     | 4632/10000 [14:51<16:56,  5.28step/s, loss=0.039720, elapsed=14.9min]

Entraînement:  46%|████▋     | 4633/10000 [14:51<16:55,  5.28step/s, loss=0.039720, elapsed=14.9min]

Entraînement:  46%|████▋     | 4633/10000 [14:51<16:55,  5.28step/s, loss=0.080835, elapsed=14.9min]

Entraînement:  46%|████▋     | 4634/10000 [14:51<16:54,  5.29step/s, loss=0.080835, elapsed=14.9min]

Entraînement:  46%|████▋     | 4634/10000 [14:51<16:54,  5.29step/s, loss=0.072524, elapsed=14.9min]

Entraînement:  46%|████▋     | 4635/10000 [14:51<16:54,  5.29step/s, loss=0.072524, elapsed=14.9min]

Entraînement:  46%|████▋     | 4635/10000 [14:51<16:54,  5.29step/s, loss=0.025895, elapsed=14.9min]

Entraînement:  46%|████▋     | 4636/10000 [14:52<16:54,  5.29step/s, loss=0.025895, elapsed=14.9min]

Entraînement:  46%|████▋     | 4636/10000 [14:52<16:54,  5.29step/s, loss=0.076728, elapsed=14.9min]

Entraînement:  46%|████▋     | 4637/10000 [14:52<16:52,  5.30step/s, loss=0.076728, elapsed=14.9min]

Entraînement:  46%|████▋     | 4637/10000 [14:52<16:52,  5.30step/s, loss=0.032198, elapsed=14.9min]

Entraînement:  46%|████▋     | 4638/10000 [14:52<16:53,  5.29step/s, loss=0.032198, elapsed=14.9min]

Entraînement:  46%|████▋     | 4638/10000 [14:52<16:53,  5.29step/s, loss=0.017216, elapsed=14.9min]

Entraînement:  46%|████▋     | 4639/10000 [14:52<16:53,  5.29step/s, loss=0.017216, elapsed=14.9min]

Entraînement:  46%|████▋     | 4639/10000 [14:52<16:53,  5.29step/s, loss=0.068871, elapsed=14.9min]

Entraînement:  46%|████▋     | 4640/10000 [14:52<16:55,  5.28step/s, loss=0.068871, elapsed=14.9min]

Entraînement:  46%|████▋     | 4640/10000 [14:52<16:55,  5.28step/s, loss=0.039431, elapsed=14.9min]

Entraînement:  46%|████▋     | 4641/10000 [14:53<16:54,  5.28step/s, loss=0.039431, elapsed=14.9min]

Entraînement:  46%|████▋     | 4641/10000 [14:53<16:54,  5.28step/s, loss=0.047742, elapsed=14.9min]

Entraînement:  46%|████▋     | 4642/10000 [14:53<16:54,  5.28step/s, loss=0.047742, elapsed=14.9min]

Entraînement:  46%|████▋     | 4642/10000 [14:53<16:54,  5.28step/s, loss=0.041896, elapsed=14.9min]

Entraînement:  46%|████▋     | 4643/10000 [14:53<16:53,  5.28step/s, loss=0.041896, elapsed=14.9min]

Entraînement:  46%|████▋     | 4643/10000 [14:53<16:53,  5.28step/s, loss=0.031600, elapsed=14.9min]

Entraînement:  46%|████▋     | 4644/10000 [14:53<16:52,  5.29step/s, loss=0.031600, elapsed=14.9min]

Entraînement:  46%|████▋     | 4644/10000 [14:53<16:52,  5.29step/s, loss=0.053677, elapsed=14.9min]

Entraînement:  46%|████▋     | 4645/10000 [14:53<16:54,  5.28step/s, loss=0.053677, elapsed=14.9min]

Entraînement:  46%|████▋     | 4645/10000 [14:53<16:54,  5.28step/s, loss=0.094573, elapsed=14.9min]

Entraînement:  46%|████▋     | 4646/10000 [14:53<16:54,  5.28step/s, loss=0.094573, elapsed=14.9min]

Entraînement:  46%|████▋     | 4646/10000 [14:53<16:54,  5.28step/s, loss=0.035005, elapsed=14.9min]

Entraînement:  46%|████▋     | 4647/10000 [14:54<16:57,  5.26step/s, loss=0.035005, elapsed=14.9min]

Entraînement:  46%|████▋     | 4647/10000 [14:54<16:57,  5.26step/s, loss=0.078534, elapsed=14.9min]

Entraînement:  46%|████▋     | 4648/10000 [14:54<16:55,  5.27step/s, loss=0.078534, elapsed=14.9min]

Entraînement:  46%|████▋     | 4648/10000 [14:54<16:55,  5.27step/s, loss=0.037682, elapsed=14.9min]

Entraînement:  46%|████▋     | 4649/10000 [14:54<16:56,  5.27step/s, loss=0.037682, elapsed=14.9min]

Entraînement:  46%|████▋     | 4649/10000 [14:54<16:56,  5.27step/s, loss=0.044306, elapsed=14.9min]

Entraînement:  46%|████▋     | 4650/10000 [14:54<16:54,  5.27step/s, loss=0.044306, elapsed=14.9min]

Entraînement:  46%|████▋     | 4650/10000 [14:54<16:54,  5.27step/s, loss=0.018128, elapsed=14.9min]

Entraînement:  47%|████▋     | 4651/10000 [14:54<16:55,  5.27step/s, loss=0.018128, elapsed=14.9min]

Entraînement:  47%|████▋     | 4651/10000 [14:54<16:55,  5.27step/s, loss=0.037246, elapsed=14.9min]

Entraînement:  47%|████▋     | 4652/10000 [14:55<16:54,  5.27step/s, loss=0.037246, elapsed=14.9min]

Entraînement:  47%|████▋     | 4652/10000 [14:55<16:54,  5.27step/s, loss=0.052247, elapsed=14.9min]

Entraînement:  47%|████▋     | 4653/10000 [14:55<16:53,  5.28step/s, loss=0.052247, elapsed=14.9min]

Entraînement:  47%|████▋     | 4653/10000 [14:55<16:53,  5.28step/s, loss=0.050993, elapsed=14.9min]

Entraînement:  47%|████▋     | 4654/10000 [14:55<16:54,  5.27step/s, loss=0.050993, elapsed=14.9min]

Entraînement:  47%|████▋     | 4654/10000 [14:55<16:54,  5.27step/s, loss=0.063913, elapsed=14.9min]

Entraînement:  47%|████▋     | 4655/10000 [14:55<16:53,  5.27step/s, loss=0.063913, elapsed=14.9min]

Entraînement:  47%|████▋     | 4655/10000 [14:55<16:53,  5.27step/s, loss=0.030945, elapsed=14.9min]

Entraînement:  47%|████▋     | 4656/10000 [14:55<16:53,  5.27step/s, loss=0.030945, elapsed=14.9min]

Entraînement:  47%|████▋     | 4656/10000 [14:55<16:53,  5.27step/s, loss=0.044543, elapsed=14.9min]

Entraînement:  47%|████▋     | 4657/10000 [14:56<16:51,  5.28step/s, loss=0.044543, elapsed=14.9min]

Entraînement:  47%|████▋     | 4657/10000 [14:56<16:51,  5.28step/s, loss=0.038590, elapsed=14.9min]

Entraînement:  47%|████▋     | 4658/10000 [14:56<16:50,  5.29step/s, loss=0.038590, elapsed=14.9min]

Entraînement:  47%|████▋     | 4658/10000 [14:56<16:50,  5.29step/s, loss=0.059513, elapsed=14.9min]

Entraînement:  47%|████▋     | 4659/10000 [14:56<16:49,  5.29step/s, loss=0.059513, elapsed=14.9min]

Entraînement:  47%|████▋     | 4659/10000 [14:56<16:49,  5.29step/s, loss=0.113179, elapsed=14.9min]

Entraînement:  47%|████▋     | 4660/10000 [14:56<16:49,  5.29step/s, loss=0.113179, elapsed=14.9min]

Entraînement:  47%|████▋     | 4660/10000 [14:56<16:49,  5.29step/s, loss=0.063389, elapsed=14.9min]

Entraînement:  47%|████▋     | 4661/10000 [14:56<16:49,  5.29step/s, loss=0.063389, elapsed=14.9min]

Entraînement:  47%|████▋     | 4661/10000 [14:56<16:49,  5.29step/s, loss=0.031867, elapsed=14.9min]

Entraînement:  47%|████▋     | 4662/10000 [14:57<16:50,  5.28step/s, loss=0.031867, elapsed=14.9min]

Entraînement:  47%|████▋     | 4662/10000 [14:57<16:50,  5.28step/s, loss=0.024545, elapsed=15.0min]

Entraînement:  47%|████▋     | 4663/10000 [14:57<16:49,  5.28step/s, loss=0.024545, elapsed=15.0min]

Entraînement:  47%|████▋     | 4663/10000 [14:57<16:49,  5.28step/s, loss=0.031918, elapsed=15.0min]

Entraînement:  47%|████▋     | 4664/10000 [14:57<16:48,  5.29step/s, loss=0.031918, elapsed=15.0min]

Entraînement:  47%|████▋     | 4664/10000 [14:57<16:48,  5.29step/s, loss=0.046088, elapsed=15.0min]

Entraînement:  47%|████▋     | 4665/10000 [14:57<16:46,  5.30step/s, loss=0.046088, elapsed=15.0min]

Entraînement:  47%|████▋     | 4665/10000 [14:57<16:46,  5.30step/s, loss=0.063426, elapsed=15.0min]

Entraînement:  47%|████▋     | 4666/10000 [14:57<16:47,  5.30step/s, loss=0.063426, elapsed=15.0min]

Entraînement:  47%|████▋     | 4666/10000 [14:57<16:47,  5.30step/s, loss=0.042963, elapsed=15.0min]

Entraînement:  47%|████▋     | 4667/10000 [14:57<16:46,  5.30step/s, loss=0.042963, elapsed=15.0min]

Entraînement:  47%|████▋     | 4667/10000 [14:57<16:46,  5.30step/s, loss=0.030024, elapsed=15.0min]

Entraînement:  47%|████▋     | 4668/10000 [14:58<16:46,  5.30step/s, loss=0.030024, elapsed=15.0min]

Entraînement:  47%|████▋     | 4668/10000 [14:58<16:46,  5.30step/s, loss=0.042623, elapsed=15.0min]

Entraînement:  47%|████▋     | 4669/10000 [14:58<16:46,  5.30step/s, loss=0.042623, elapsed=15.0min]

Entraînement:  47%|████▋     | 4669/10000 [14:58<16:46,  5.30step/s, loss=0.045293, elapsed=15.0min]

Entraînement:  47%|████▋     | 4670/10000 [14:58<16:45,  5.30step/s, loss=0.045293, elapsed=15.0min]

Entraînement:  47%|████▋     | 4670/10000 [14:58<16:45,  5.30step/s, loss=0.014262, elapsed=15.0min]

Entraînement:  47%|████▋     | 4671/10000 [14:58<16:53,  5.26step/s, loss=0.014262, elapsed=15.0min]

Entraînement:  47%|████▋     | 4671/10000 [14:58<16:53,  5.26step/s, loss=0.042693, elapsed=15.0min]

Entraînement:  47%|████▋     | 4672/10000 [14:58<16:52,  5.26step/s, loss=0.042693, elapsed=15.0min]

Entraînement:  47%|████▋     | 4672/10000 [14:58<16:52,  5.26step/s, loss=0.047269, elapsed=15.0min]

Entraînement:  47%|████▋     | 4673/10000 [14:59<16:55,  5.25step/s, loss=0.047269, elapsed=15.0min]

Entraînement:  47%|████▋     | 4673/10000 [14:59<16:55,  5.25step/s, loss=0.123489, elapsed=15.0min]

Entraînement:  47%|████▋     | 4674/10000 [14:59<16:55,  5.25step/s, loss=0.123489, elapsed=15.0min]

Entraînement:  47%|████▋     | 4674/10000 [14:59<16:55,  5.25step/s, loss=0.080434, elapsed=15.0min]

Entraînement:  47%|████▋     | 4675/10000 [14:59<16:53,  5.26step/s, loss=0.080434, elapsed=15.0min]

Entraînement:  47%|████▋     | 4675/10000 [14:59<16:53,  5.26step/s, loss=0.045127, elapsed=15.0min]

Entraînement:  47%|████▋     | 4676/10000 [14:59<16:50,  5.27step/s, loss=0.045127, elapsed=15.0min]

Entraînement:  47%|████▋     | 4676/10000 [14:59<16:50,  5.27step/s, loss=0.049343, elapsed=15.0min]

Entraînement:  47%|████▋     | 4677/10000 [14:59<16:52,  5.26step/s, loss=0.049343, elapsed=15.0min]

Entraînement:  47%|████▋     | 4677/10000 [14:59<16:52,  5.26step/s, loss=0.032358, elapsed=15.0min]

Entraînement:  47%|████▋     | 4678/10000 [15:00<16:51,  5.26step/s, loss=0.032358, elapsed=15.0min]

Entraînement:  47%|████▋     | 4678/10000 [15:00<16:51,  5.26step/s, loss=0.046279, elapsed=15.0min]

Entraînement:  47%|████▋     | 4679/10000 [15:00<16:52,  5.26step/s, loss=0.046279, elapsed=15.0min]

Entraînement:  47%|████▋     | 4679/10000 [15:00<16:52,  5.26step/s, loss=0.047472, elapsed=15.0min]

Entraînement:  47%|████▋     | 4680/10000 [15:00<16:51,  5.26step/s, loss=0.047472, elapsed=15.0min]

Entraînement:  47%|████▋     | 4680/10000 [15:00<16:51,  5.26step/s, loss=0.061901, elapsed=15.0min]

Entraînement:  47%|████▋     | 4681/10000 [15:00<16:51,  5.26step/s, loss=0.061901, elapsed=15.0min]

Entraînement:  47%|████▋     | 4681/10000 [15:00<16:51,  5.26step/s, loss=0.046843, elapsed=15.0min]

Entraînement:  47%|████▋     | 4682/10000 [15:00<16:50,  5.26step/s, loss=0.046843, elapsed=15.0min]

Entraînement:  47%|████▋     | 4682/10000 [15:00<16:50,  5.26step/s, loss=0.041969, elapsed=15.0min]

Entraînement:  47%|████▋     | 4683/10000 [15:01<16:48,  5.27step/s, loss=0.041969, elapsed=15.0min]

Entraînement:  47%|████▋     | 4683/10000 [15:01<16:48,  5.27step/s, loss=0.036786, elapsed=15.0min]

Entraînement:  47%|████▋     | 4684/10000 [15:01<16:48,  5.27step/s, loss=0.036786, elapsed=15.0min]

Entraînement:  47%|████▋     | 4684/10000 [15:01<16:48,  5.27step/s, loss=0.029016, elapsed=15.0min]

Entraînement:  47%|████▋     | 4685/10000 [15:01<16:47,  5.28step/s, loss=0.029016, elapsed=15.0min]

Entraînement:  47%|████▋     | 4685/10000 [15:01<16:47,  5.28step/s, loss=0.036320, elapsed=15.0min]

Entraînement:  47%|████▋     | 4686/10000 [15:01<16:48,  5.27step/s, loss=0.036320, elapsed=15.0min]

Entraînement:  47%|████▋     | 4686/10000 [15:01<16:48,  5.27step/s, loss=0.070040, elapsed=15.0min]

Entraînement:  47%|████▋     | 4687/10000 [15:01<16:47,  5.27step/s, loss=0.070040, elapsed=15.0min]

Entraînement:  47%|████▋     | 4687/10000 [15:01<16:47,  5.27step/s, loss=0.054636, elapsed=15.0min]

Entraînement:  47%|████▋     | 4688/10000 [15:01<16:48,  5.27step/s, loss=0.054636, elapsed=15.0min]

Entraînement:  47%|████▋     | 4688/10000 [15:01<16:48,  5.27step/s, loss=0.026714, elapsed=15.0min]

Entraînement:  47%|████▋     | 4689/10000 [15:02<16:47,  5.27step/s, loss=0.026714, elapsed=15.0min]

Entraînement:  47%|████▋     | 4689/10000 [15:02<16:47,  5.27step/s, loss=0.044967, elapsed=15.0min]

Entraînement:  47%|████▋     | 4690/10000 [15:02<16:47,  5.27step/s, loss=0.044967, elapsed=15.0min]

Entraînement:  47%|████▋     | 4690/10000 [15:02<16:47,  5.27step/s, loss=0.046120, elapsed=15.0min]

Entraînement:  47%|████▋     | 4691/10000 [15:02<16:46,  5.28step/s, loss=0.046120, elapsed=15.0min]

Entraînement:  47%|████▋     | 4691/10000 [15:02<16:46,  5.28step/s, loss=0.032846, elapsed=15.0min]

Entraînement:  47%|████▋     | 4692/10000 [15:02<16:44,  5.28step/s, loss=0.032846, elapsed=15.0min]

Entraînement:  47%|████▋     | 4692/10000 [15:02<16:44,  5.28step/s, loss=0.027506, elapsed=15.0min]

Entraînement:  47%|████▋     | 4693/10000 [15:02<16:46,  5.28step/s, loss=0.027506, elapsed=15.0min]

Entraînement:  47%|████▋     | 4693/10000 [15:02<16:46,  5.28step/s, loss=0.040398, elapsed=15.0min]

Entraînement:  47%|████▋     | 4694/10000 [15:03<16:43,  5.29step/s, loss=0.040398, elapsed=15.0min]

Entraînement:  47%|████▋     | 4694/10000 [15:03<16:43,  5.29step/s, loss=0.045553, elapsed=15.1min]

Entraînement:  47%|████▋     | 4695/10000 [15:03<16:44,  5.28step/s, loss=0.045553, elapsed=15.1min]

Entraînement:  47%|████▋     | 4695/10000 [15:03<16:44,  5.28step/s, loss=0.049306, elapsed=15.1min]

Entraînement:  47%|████▋     | 4696/10000 [15:03<16:42,  5.29step/s, loss=0.049306, elapsed=15.1min]

Entraînement:  47%|████▋     | 4696/10000 [15:03<16:42,  5.29step/s, loss=0.019330, elapsed=15.1min]

Entraînement:  47%|████▋     | 4697/10000 [15:03<16:40,  5.30step/s, loss=0.019330, elapsed=15.1min]

Entraînement:  47%|████▋     | 4697/10000 [15:03<16:40,  5.30step/s, loss=0.094025, elapsed=15.1min]

Entraînement:  47%|████▋     | 4698/10000 [15:03<16:40,  5.30step/s, loss=0.094025, elapsed=15.1min]

Entraînement:  47%|████▋     | 4698/10000 [15:03<16:40,  5.30step/s, loss=0.022232, elapsed=15.1min]

Entraînement:  47%|████▋     | 4699/10000 [15:04<16:39,  5.30step/s, loss=0.022232, elapsed=15.1min]

Entraînement:  47%|████▋     | 4699/10000 [15:04<16:39,  5.30step/s, loss=0.044209, elapsed=15.1min]

Entraînement:  47%|████▋     | 4700/10000 [15:04<16:42,  5.29step/s, loss=0.044209, elapsed=15.1min]

Entraînement:  47%|████▋     | 4700/10000 [15:04<16:42,  5.29step/s, loss=0.027841, elapsed=15.1min]

Entraînement:  47%|████▋     | 4700/10000 [15:04<16:42,  5.29step/s, loss=0.027841, elapsed=15.1min]

Entraînement:  47%|████▋     | 4701/10000 [15:04<16:50,  5.24step/s, loss=0.027841, elapsed=15.1min]

Entraînement:  47%|████▋     | 4701/10000 [15:04<16:50,  5.24step/s, loss=0.039796, elapsed=15.1min]

Step 4700/10000 | Train loss: 0.027841 | Elapsed: 15.1min | ETA: 17.0min

Entraînement:  47%|████▋     | 4702/10000 [15:04<16:50,  5.24step/s, loss=0.039796, elapsed=15.1min]

Entraînement:  47%|████▋     | 4702/10000 [15:04<16:50,  5.24step/s, loss=0.043004, elapsed=15.1min]

Entraînement:  47%|████▋     | 4703/10000 [15:04<16:47,  5.26step/s, loss=0.043004, elapsed=15.1min]

Entraînement:  47%|████▋     | 4703/10000 [15:04<16:47,  5.26step/s, loss=0.035720, elapsed=15.1min]

Entraînement:  47%|████▋     | 4704/10000 [15:04<16:45,  5.27step/s, loss=0.035720, elapsed=15.1min]

Entraînement:  47%|████▋     | 4704/10000 [15:04<16:45,  5.27step/s, loss=0.057155, elapsed=15.1min]

Entraînement:  47%|████▋     | 4705/10000 [15:05<16:44,  5.27step/s, loss=0.057155, elapsed=15.1min]

Entraînement:  47%|████▋     | 4705/10000 [15:05<16:44,  5.27step/s, loss=0.048613, elapsed=15.1min]

Entraînement:  47%|████▋     | 4706/10000 [15:05<16:42,  5.28step/s, loss=0.048613, elapsed=15.1min]

Entraînement:  47%|████▋     | 4706/10000 [15:05<16:42,  5.28step/s, loss=0.065560, elapsed=15.1min]

Entraînement:  47%|████▋     | 4707/10000 [15:05<16:42,  5.28step/s, loss=0.065560, elapsed=15.1min]

Entraînement:  47%|████▋     | 4707/10000 [15:05<16:42,  5.28step/s, loss=0.027351, elapsed=15.1min]

Entraînement:  47%|████▋     | 4708/10000 [15:05<16:44,  5.27step/s, loss=0.027351, elapsed=15.1min]

Entraînement:  47%|████▋     | 4708/10000 [15:05<16:44,  5.27step/s, loss=0.019296, elapsed=15.1min]

Entraînement:  47%|████▋     | 4709/10000 [15:05<16:43,  5.27step/s, loss=0.019296, elapsed=15.1min]

Entraînement:  47%|████▋     | 4709/10000 [15:05<16:43,  5.27step/s, loss=0.068880, elapsed=15.1min]

Entraînement:  47%|████▋     | 4710/10000 [15:06<16:40,  5.29step/s, loss=0.068880, elapsed=15.1min]

Entraînement:  47%|████▋     | 4710/10000 [15:06<16:40,  5.29step/s, loss=0.034179, elapsed=15.1min]

Entraînement:  47%|████▋     | 4711/10000 [15:06<16:35,  5.31step/s, loss=0.034179, elapsed=15.1min]

Entraînement:  47%|████▋     | 4711/10000 [15:06<16:35,  5.31step/s, loss=0.022519, elapsed=15.1min]

Entraînement:  47%|████▋     | 4712/10000 [15:06<16:34,  5.32step/s, loss=0.022519, elapsed=15.1min]

Entraînement:  47%|████▋     | 4712/10000 [15:06<16:34,  5.32step/s, loss=0.026772, elapsed=15.1min]

Entraînement:  47%|████▋     | 4713/10000 [15:06<16:36,  5.31step/s, loss=0.026772, elapsed=15.1min]

Entraînement:  47%|████▋     | 4713/10000 [15:06<16:36,  5.31step/s, loss=0.043239, elapsed=15.1min]

Entraînement:  47%|████▋     | 4714/10000 [15:06<16:37,  5.30step/s, loss=0.043239, elapsed=15.1min]

Entraînement:  47%|████▋     | 4714/10000 [15:06<16:37,  5.30step/s, loss=0.103078, elapsed=15.1min]

Entraînement:  47%|████▋     | 4715/10000 [15:07<16:36,  5.30step/s, loss=0.103078, elapsed=15.1min]

Entraînement:  47%|████▋     | 4715/10000 [15:07<16:36,  5.30step/s, loss=0.066239, elapsed=15.1min]

Entraînement:  47%|████▋     | 4716/10000 [15:07<16:39,  5.29step/s, loss=0.066239, elapsed=15.1min]

Entraînement:  47%|████▋     | 4716/10000 [15:07<16:39,  5.29step/s, loss=0.059369, elapsed=15.1min]

Entraînement:  47%|████▋     | 4717/10000 [15:07<16:42,  5.27step/s, loss=0.059369, elapsed=15.1min]

Entraînement:  47%|████▋     | 4717/10000 [15:07<16:42,  5.27step/s, loss=0.036060, elapsed=15.1min]

Entraînement:  47%|████▋     | 4718/10000 [15:07<16:41,  5.28step/s, loss=0.036060, elapsed=15.1min]

Entraînement:  47%|████▋     | 4718/10000 [15:07<16:41,  5.28step/s, loss=0.063751, elapsed=15.1min]

Entraînement:  47%|████▋     | 4719/10000 [15:07<16:42,  5.27step/s, loss=0.063751, elapsed=15.1min]

Entraînement:  47%|████▋     | 4719/10000 [15:07<16:42,  5.27step/s, loss=0.061032, elapsed=15.1min]

Entraînement:  47%|████▋     | 4720/10000 [15:08<16:40,  5.28step/s, loss=0.061032, elapsed=15.1min]

Entraînement:  47%|████▋     | 4720/10000 [15:08<16:40,  5.28step/s, loss=0.097717, elapsed=15.1min]

Entraînement:  47%|████▋     | 4721/10000 [15:08<16:38,  5.29step/s, loss=0.097717, elapsed=15.1min]

Entraînement:  47%|████▋     | 4721/10000 [15:08<16:38,  5.29step/s, loss=0.032739, elapsed=15.1min]

Entraînement:  47%|████▋     | 4722/10000 [15:08<16:38,  5.29step/s, loss=0.032739, elapsed=15.1min]

Entraînement:  47%|████▋     | 4722/10000 [15:08<16:38,  5.29step/s, loss=0.140871, elapsed=15.1min]

Entraînement:  47%|████▋     | 4723/10000 [15:08<16:39,  5.28step/s, loss=0.140871, elapsed=15.1min]

Entraînement:  47%|████▋     | 4723/10000 [15:08<16:39,  5.28step/s, loss=0.106042, elapsed=15.1min]

Entraînement:  47%|████▋     | 4724/10000 [15:08<16:40,  5.27step/s, loss=0.106042, elapsed=15.1min]

Entraînement:  47%|████▋     | 4724/10000 [15:08<16:40,  5.27step/s, loss=0.058533, elapsed=15.1min]

Entraînement:  47%|████▋     | 4725/10000 [15:08<16:39,  5.28step/s, loss=0.058533, elapsed=15.1min]

Entraînement:  47%|████▋     | 4725/10000 [15:08<16:39,  5.28step/s, loss=0.073768, elapsed=15.1min]

Entraînement:  47%|████▋     | 4726/10000 [15:09<16:39,  5.27step/s, loss=0.073768, elapsed=15.1min]

Entraînement:  47%|████▋     | 4726/10000 [15:09<16:39,  5.27step/s, loss=0.039390, elapsed=15.2min]

Entraînement:  47%|████▋     | 4727/10000 [15:09<16:41,  5.27step/s, loss=0.039390, elapsed=15.2min]

Entraînement:  47%|████▋     | 4727/10000 [15:09<16:41,  5.27step/s, loss=0.047655, elapsed=15.2min]

Entraînement:  47%|████▋     | 4728/10000 [15:09<16:40,  5.27step/s, loss=0.047655, elapsed=15.2min]

Entraînement:  47%|████▋     | 4728/10000 [15:09<16:40,  5.27step/s, loss=0.169157, elapsed=15.2min]

Entraînement:  47%|████▋     | 4729/10000 [15:09<16:41,  5.27step/s, loss=0.169157, elapsed=15.2min]

Entraînement:  47%|████▋     | 4729/10000 [15:09<16:41,  5.27step/s, loss=0.102399, elapsed=15.2min]

Entraînement:  47%|████▋     | 4730/10000 [15:09<16:40,  5.27step/s, loss=0.102399, elapsed=15.2min]

Entraînement:  47%|████▋     | 4730/10000 [15:09<16:40,  5.27step/s, loss=0.037569, elapsed=15.2min]

Entraînement:  47%|████▋     | 4731/10000 [15:10<16:40,  5.27step/s, loss=0.037569, elapsed=15.2min]

Entraînement:  47%|████▋     | 4731/10000 [15:10<16:40,  5.27step/s, loss=0.042547, elapsed=15.2min]

Entraînement:  47%|████▋     | 4732/10000 [15:10<16:39,  5.27step/s, loss=0.042547, elapsed=15.2min]

Entraînement:  47%|████▋     | 4732/10000 [15:10<16:39,  5.27step/s, loss=0.130796, elapsed=15.2min]

Entraînement:  47%|████▋     | 4733/10000 [15:10<16:39,  5.27step/s, loss=0.130796, elapsed=15.2min]

Entraînement:  47%|████▋     | 4733/10000 [15:10<16:39,  5.27step/s, loss=0.044473, elapsed=15.2min]

Entraînement:  47%|████▋     | 4734/10000 [15:10<16:45,  5.24step/s, loss=0.044473, elapsed=15.2min]

Entraînement:  47%|████▋     | 4734/10000 [15:10<16:45,  5.24step/s, loss=0.044153, elapsed=15.2min]

Entraînement:  47%|████▋     | 4735/10000 [15:10<16:44,  5.24step/s, loss=0.044153, elapsed=15.2min]

Entraînement:  47%|████▋     | 4735/10000 [15:10<16:44,  5.24step/s, loss=0.045921, elapsed=15.2min]

Entraînement:  47%|████▋     | 4736/10000 [15:11<16:44,  5.24step/s, loss=0.045921, elapsed=15.2min]

Entraînement:  47%|████▋     | 4736/10000 [15:11<16:44,  5.24step/s, loss=0.050491, elapsed=15.2min]

Entraînement:  47%|████▋     | 4737/10000 [15:11<16:42,  5.25step/s, loss=0.050491, elapsed=15.2min]

Entraînement:  47%|████▋     | 4737/10000 [15:11<16:42,  5.25step/s, loss=0.034201, elapsed=15.2min]

Entraînement:  47%|████▋     | 4738/10000 [15:11<16:39,  5.26step/s, loss=0.034201, elapsed=15.2min]

Entraînement:  47%|████▋     | 4738/10000 [15:11<16:39,  5.26step/s, loss=0.045832, elapsed=15.2min]

Entraînement:  47%|████▋     | 4739/10000 [15:11<16:42,  5.25step/s, loss=0.045832, elapsed=15.2min]

Entraînement:  47%|████▋     | 4739/10000 [15:11<16:42,  5.25step/s, loss=0.072476, elapsed=15.2min]

Entraînement:  47%|████▋     | 4740/10000 [15:11<16:42,  5.25step/s, loss=0.072476, elapsed=15.2min]

Entraînement:  47%|████▋     | 4740/10000 [15:11<16:42,  5.25step/s, loss=0.084069, elapsed=15.2min]

Entraînement:  47%|████▋     | 4741/10000 [15:12<16:39,  5.26step/s, loss=0.084069, elapsed=15.2min]

Entraînement:  47%|████▋     | 4741/10000 [15:12<16:39,  5.26step/s, loss=0.040175, elapsed=15.2min]

Entraînement:  47%|████▋     | 4742/10000 [15:12<16:36,  5.27step/s, loss=0.040175, elapsed=15.2min]

Entraînement:  47%|████▋     | 4742/10000 [15:12<16:36,  5.27step/s, loss=0.032709, elapsed=15.2min]

Entraînement:  47%|████▋     | 4743/10000 [15:12<16:39,  5.26step/s, loss=0.032709, elapsed=15.2min]

Entraînement:  47%|████▋     | 4743/10000 [15:12<16:39,  5.26step/s, loss=0.021743, elapsed=15.2min]

Entraînement:  47%|████▋     | 4744/10000 [15:12<16:41,  5.25step/s, loss=0.021743, elapsed=15.2min]

Entraînement:  47%|████▋     | 4744/10000 [15:12<16:41,  5.25step/s, loss=0.050120, elapsed=15.2min]

Entraînement:  47%|████▋     | 4745/10000 [15:12<16:39,  5.26step/s, loss=0.050120, elapsed=15.2min]

Entraînement:  47%|████▋     | 4745/10000 [15:12<16:39,  5.26step/s, loss=0.035717, elapsed=15.2min]

Entraînement:  47%|████▋     | 4746/10000 [15:12<16:37,  5.27step/s, loss=0.035717, elapsed=15.2min]

Entraînement:  47%|████▋     | 4746/10000 [15:12<16:37,  5.27step/s, loss=0.041483, elapsed=15.2min]

Entraînement:  47%|████▋     | 4747/10000 [15:13<16:37,  5.26step/s, loss=0.041483, elapsed=15.2min]

Entraînement:  47%|████▋     | 4747/10000 [15:13<16:37,  5.26step/s, loss=0.142813, elapsed=15.2min]

Entraînement:  47%|████▋     | 4748/10000 [15:13<16:36,  5.27step/s, loss=0.142813, elapsed=15.2min]

Entraînement:  47%|████▋     | 4748/10000 [15:13<16:36,  5.27step/s, loss=0.138428, elapsed=15.2min]

Entraînement:  47%|████▋     | 4749/10000 [15:13<16:35,  5.28step/s, loss=0.138428, elapsed=15.2min]

Entraînement:  47%|████▋     | 4749/10000 [15:13<16:35,  5.28step/s, loss=0.033433, elapsed=15.2min]

Entraînement:  48%|████▊     | 4750/10000 [15:13<16:34,  5.28step/s, loss=0.033433, elapsed=15.2min]

Entraînement:  48%|████▊     | 4750/10000 [15:13<16:34,  5.28step/s, loss=0.059521, elapsed=15.2min]

Entraînement:  48%|████▊     | 4751/10000 [15:13<16:36,  5.27step/s, loss=0.059521, elapsed=15.2min]

Entraînement:  48%|████▊     | 4751/10000 [15:13<16:36,  5.27step/s, loss=0.091308, elapsed=15.2min]

Entraînement:  48%|████▊     | 4752/10000 [15:14<16:38,  5.26step/s, loss=0.091308, elapsed=15.2min]

Entraînement:  48%|████▊     | 4752/10000 [15:14<16:38,  5.26step/s, loss=0.163527, elapsed=15.2min]

Entraînement:  48%|████▊     | 4753/10000 [15:14<16:36,  5.26step/s, loss=0.163527, elapsed=15.2min]

Entraînement:  48%|████▊     | 4753/10000 [15:14<16:36,  5.26step/s, loss=0.031117, elapsed=15.2min]

Entraînement:  48%|████▊     | 4754/10000 [15:14<16:37,  5.26step/s, loss=0.031117, elapsed=15.2min]

Entraînement:  48%|████▊     | 4754/10000 [15:14<16:37,  5.26step/s, loss=0.074793, elapsed=15.2min]

Entraînement:  48%|████▊     | 4755/10000 [15:14<16:37,  5.26step/s, loss=0.074793, elapsed=15.2min]

Entraînement:  48%|████▊     | 4755/10000 [15:14<16:37,  5.26step/s, loss=0.036834, elapsed=15.2min]

Entraînement:  48%|████▊     | 4756/10000 [15:14<16:36,  5.26step/s, loss=0.036834, elapsed=15.2min]

Entraînement:  48%|████▊     | 4756/10000 [15:14<16:36,  5.26step/s, loss=0.059577, elapsed=15.2min]

Entraînement:  48%|████▊     | 4757/10000 [15:15<16:34,  5.27step/s, loss=0.059577, elapsed=15.2min]

Entraînement:  48%|████▊     | 4757/10000 [15:15<16:34,  5.27step/s, loss=0.093618, elapsed=15.3min]

Entraînement:  48%|████▊     | 4758/10000 [15:15<16:32,  5.28step/s, loss=0.093618, elapsed=15.3min]

Entraînement:  48%|████▊     | 4758/10000 [15:15<16:32,  5.28step/s, loss=0.041232, elapsed=15.3min]

Entraînement:  48%|████▊     | 4759/10000 [15:15<16:32,  5.28step/s, loss=0.041232, elapsed=15.3min]

Entraînement:  48%|████▊     | 4759/10000 [15:15<16:32,  5.28step/s, loss=0.071925, elapsed=15.3min]

Entraînement:  48%|████▊     | 4760/10000 [15:15<16:32,  5.28step/s, loss=0.071925, elapsed=15.3min]

Entraînement:  48%|████▊     | 4760/10000 [15:15<16:32,  5.28step/s, loss=0.055002, elapsed=15.3min]

Entraînement:  48%|████▊     | 4761/10000 [15:15<16:31,  5.28step/s, loss=0.055002, elapsed=15.3min]

Entraînement:  48%|████▊     | 4761/10000 [15:15<16:31,  5.28step/s, loss=0.032473, elapsed=15.3min]

Entraînement:  48%|████▊     | 4762/10000 [15:15<16:33,  5.27step/s, loss=0.032473, elapsed=15.3min]

Entraînement:  48%|████▊     | 4762/10000 [15:15<16:33,  5.27step/s, loss=0.034881, elapsed=15.3min]

Entraînement:  48%|████▊     | 4763/10000 [15:16<16:32,  5.28step/s, loss=0.034881, elapsed=15.3min]

Entraînement:  48%|████▊     | 4763/10000 [15:16<16:32,  5.28step/s, loss=0.024423, elapsed=15.3min]

Entraînement:  48%|████▊     | 4764/10000 [15:16<16:32,  5.27step/s, loss=0.024423, elapsed=15.3min]

Entraînement:  48%|████▊     | 4764/10000 [15:16<16:32,  5.27step/s, loss=0.163631, elapsed=15.3min]

Entraînement:  48%|████▊     | 4765/10000 [15:16<16:32,  5.27step/s, loss=0.163631, elapsed=15.3min]

Entraînement:  48%|████▊     | 4765/10000 [15:16<16:32,  5.27step/s, loss=0.051265, elapsed=15.3min]

Entraînement:  48%|████▊     | 4766/10000 [15:16<16:32,  5.27step/s, loss=0.051265, elapsed=15.3min]

Entraînement:  48%|████▊     | 4766/10000 [15:16<16:32,  5.27step/s, loss=0.080049, elapsed=15.3min]

Entraînement:  48%|████▊     | 4767/10000 [15:16<16:32,  5.27step/s, loss=0.080049, elapsed=15.3min]

Entraînement:  48%|████▊     | 4767/10000 [15:16<16:32,  5.27step/s, loss=0.063005, elapsed=15.3min]

Entraînement:  48%|████▊     | 4768/10000 [15:17<16:31,  5.28step/s, loss=0.063005, elapsed=15.3min]

Entraînement:  48%|████▊     | 4768/10000 [15:17<16:31,  5.28step/s, loss=0.018451, elapsed=15.3min]

Entraînement:  48%|████▊     | 4769/10000 [15:17<16:32,  5.27step/s, loss=0.018451, elapsed=15.3min]

Entraînement:  48%|████▊     | 4769/10000 [15:17<16:32,  5.27step/s, loss=0.201126, elapsed=15.3min]

Entraînement:  48%|████▊     | 4770/10000 [15:17<16:33,  5.26step/s, loss=0.201126, elapsed=15.3min]

Entraînement:  48%|████▊     | 4770/10000 [15:17<16:33,  5.26step/s, loss=0.096482, elapsed=15.3min]

Entraînement:  48%|████▊     | 4771/10000 [15:17<16:32,  5.27step/s, loss=0.096482, elapsed=15.3min]

Entraînement:  48%|████▊     | 4771/10000 [15:17<16:32,  5.27step/s, loss=0.073142, elapsed=15.3min]

Entraînement:  48%|████▊     | 4772/10000 [15:17<16:37,  5.24step/s, loss=0.073142, elapsed=15.3min]

Entraînement:  48%|████▊     | 4772/10000 [15:17<16:37,  5.24step/s, loss=0.057882, elapsed=15.3min]

Entraînement:  48%|████▊     | 4773/10000 [15:18<16:34,  5.25step/s, loss=0.057882, elapsed=15.3min]

Entraînement:  48%|████▊     | 4773/10000 [15:18<16:34,  5.25step/s, loss=0.075367, elapsed=15.3min]

Entraînement:  48%|████▊     | 4774/10000 [15:18<16:34,  5.26step/s, loss=0.075367, elapsed=15.3min]

Entraînement:  48%|████▊     | 4774/10000 [15:18<16:34,  5.26step/s, loss=0.027400, elapsed=15.3min]

Entraînement:  48%|████▊     | 4775/10000 [15:18<16:32,  5.26step/s, loss=0.027400, elapsed=15.3min]

Entraînement:  48%|████▊     | 4775/10000 [15:18<16:32,  5.26step/s, loss=0.025407, elapsed=15.3min]

Entraînement:  48%|████▊     | 4776/10000 [15:18<16:35,  5.25step/s, loss=0.025407, elapsed=15.3min]

Entraînement:  48%|████▊     | 4776/10000 [15:18<16:35,  5.25step/s, loss=0.040820, elapsed=15.3min]

Entraînement:  48%|████▊     | 4777/10000 [15:18<16:36,  5.24step/s, loss=0.040820, elapsed=15.3min]

Entraînement:  48%|████▊     | 4777/10000 [15:18<16:36,  5.24step/s, loss=0.044296, elapsed=15.3min]

Entraînement:  48%|████▊     | 4778/10000 [15:19<16:37,  5.24step/s, loss=0.044296, elapsed=15.3min]

Entraînement:  48%|████▊     | 4778/10000 [15:19<16:37,  5.24step/s, loss=0.035481, elapsed=15.3min]

Entraînement:  48%|████▊     | 4779/10000 [15:19<16:34,  5.25step/s, loss=0.035481, elapsed=15.3min]

Entraînement:  48%|████▊     | 4779/10000 [15:19<16:34,  5.25step/s, loss=0.044920, elapsed=15.3min]

Entraînement:  48%|████▊     | 4780/10000 [15:19<16:33,  5.25step/s, loss=0.044920, elapsed=15.3min]

Entraînement:  48%|████▊     | 4780/10000 [15:19<16:33,  5.25step/s, loss=0.036872, elapsed=15.3min]

Entraînement:  48%|████▊     | 4781/10000 [15:19<16:31,  5.26step/s, loss=0.036872, elapsed=15.3min]

Entraînement:  48%|████▊     | 4781/10000 [15:19<16:31,  5.26step/s, loss=0.033598, elapsed=15.3min]

Entraînement:  48%|████▊     | 4782/10000 [15:19<16:32,  5.26step/s, loss=0.033598, elapsed=15.3min]

Entraînement:  48%|████▊     | 4782/10000 [15:19<16:32,  5.26step/s, loss=0.046576, elapsed=15.3min]

Entraînement:  48%|████▊     | 4783/10000 [15:19<16:31,  5.26step/s, loss=0.046576, elapsed=15.3min]

Entraînement:  48%|████▊     | 4783/10000 [15:19<16:31,  5.26step/s, loss=0.093206, elapsed=15.3min]

Entraînement:  48%|████▊     | 4784/10000 [15:20<16:30,  5.26step/s, loss=0.093206, elapsed=15.3min]

Entraînement:  48%|████▊     | 4784/10000 [15:20<16:30,  5.26step/s, loss=0.022323, elapsed=15.3min]

Entraînement:  48%|████▊     | 4785/10000 [15:20<16:28,  5.27step/s, loss=0.022323, elapsed=15.3min]

Entraînement:  48%|████▊     | 4785/10000 [15:20<16:28,  5.27step/s, loss=0.016442, elapsed=15.3min]

Entraînement:  48%|████▊     | 4786/10000 [15:20<16:30,  5.27step/s, loss=0.016442, elapsed=15.3min]

Entraînement:  48%|████▊     | 4786/10000 [15:20<16:30,  5.27step/s, loss=0.035093, elapsed=15.3min]

Entraînement:  48%|████▊     | 4787/10000 [15:20<16:29,  5.27step/s, loss=0.035093, elapsed=15.3min]

Entraînement:  48%|████▊     | 4787/10000 [15:20<16:29,  5.27step/s, loss=0.089667, elapsed=15.3min]

Entraînement:  48%|████▊     | 4788/10000 [15:20<16:28,  5.27step/s, loss=0.089667, elapsed=15.3min]

Entraînement:  48%|████▊     | 4788/10000 [15:20<16:28,  5.27step/s, loss=0.043937, elapsed=15.3min]

Entraînement:  48%|████▊     | 4789/10000 [15:21<16:28,  5.27step/s, loss=0.043937, elapsed=15.3min]

Entraînement:  48%|████▊     | 4789/10000 [15:21<16:28,  5.27step/s, loss=0.040436, elapsed=15.4min]

Entraînement:  48%|████▊     | 4790/10000 [15:21<16:26,  5.28step/s, loss=0.040436, elapsed=15.4min]

Entraînement:  48%|████▊     | 4790/10000 [15:21<16:26,  5.28step/s, loss=0.018071, elapsed=15.4min]

Entraînement:  48%|████▊     | 4791/10000 [15:21<16:24,  5.29step/s, loss=0.018071, elapsed=15.4min]

Entraînement:  48%|████▊     | 4791/10000 [15:21<16:24,  5.29step/s, loss=0.022433, elapsed=15.4min]

Entraînement:  48%|████▊     | 4792/10000 [15:21<16:26,  5.28step/s, loss=0.022433, elapsed=15.4min]

Entraînement:  48%|████▊     | 4792/10000 [15:21<16:26,  5.28step/s, loss=0.050728, elapsed=15.4min]

Entraînement:  48%|████▊     | 4793/10000 [15:21<16:27,  5.27step/s, loss=0.050728, elapsed=15.4min]

Entraînement:  48%|████▊     | 4793/10000 [15:21<16:27,  5.27step/s, loss=0.029126, elapsed=15.4min]

Entraînement:  48%|████▊     | 4794/10000 [15:22<16:26,  5.27step/s, loss=0.029126, elapsed=15.4min]

Entraînement:  48%|████▊     | 4794/10000 [15:22<16:26,  5.27step/s, loss=0.026535, elapsed=15.4min]

Entraînement:  48%|████▊     | 4795/10000 [15:22<16:26,  5.28step/s, loss=0.026535, elapsed=15.4min]

Entraînement:  48%|████▊     | 4795/10000 [15:22<16:26,  5.28step/s, loss=0.049300, elapsed=15.4min]

Entraînement:  48%|████▊     | 4796/10000 [15:22<16:25,  5.28step/s, loss=0.049300, elapsed=15.4min]

Entraînement:  48%|████▊     | 4796/10000 [15:22<16:25,  5.28step/s, loss=0.117658, elapsed=15.4min]

Entraînement:  48%|████▊     | 4797/10000 [15:22<16:25,  5.28step/s, loss=0.117658, elapsed=15.4min]

Entraînement:  48%|████▊     | 4797/10000 [15:22<16:25,  5.28step/s, loss=0.068262, elapsed=15.4min]

Entraînement:  48%|████▊     | 4798/10000 [15:22<16:24,  5.29step/s, loss=0.068262, elapsed=15.4min]

Entraînement:  48%|████▊     | 4798/10000 [15:22<16:24,  5.29step/s, loss=0.027531, elapsed=15.4min]

Entraînement:  48%|████▊     | 4799/10000 [15:23<16:22,  5.29step/s, loss=0.027531, elapsed=15.4min]

Entraînement:  48%|████▊     | 4799/10000 [15:23<16:22,  5.29step/s, loss=0.029416, elapsed=15.4min]

Entraînement:  48%|████▊     | 4800/10000 [15:23<16:25,  5.28step/s, loss=0.029416, elapsed=15.4min]

Entraînement:  48%|████▊     | 4800/10000 [15:23<16:25,  5.28step/s, loss=0.054002, elapsed=15.4min]

Entraînement:  48%|████▊     | 4800/10000 [15:23<16:25,  5.28step/s, loss=0.054002, elapsed=15.4min]

Entraînement:  48%|████▊     | 4801/10000 [15:23<16:33,  5.23step/s, loss=0.054002, elapsed=15.4min]

Entraînement:  48%|████▊     | 4801/10000 [15:23<16:33,  5.23step/s, loss=0.042514, elapsed=15.4min]

Step 4800/10000 | Train loss: 0.054002 | Elapsed: 15.4min | ETA: 16.7min

Entraînement:  48%|████▊     | 4802/10000 [15:23<16:30,  5.25step/s, loss=0.042514, elapsed=15.4min]

Entraînement:  48%|████▊     | 4802/10000 [15:23<16:30,  5.25step/s, loss=0.055069, elapsed=15.4min]

Entraînement:  48%|████▊     | 4803/10000 [15:23<16:26,  5.27step/s, loss=0.055069, elapsed=15.4min]

Entraînement:  48%|████▊     | 4803/10000 [15:23<16:26,  5.27step/s, loss=0.028683, elapsed=15.4min]

Entraînement:  48%|████▊     | 4804/10000 [15:23<16:26,  5.27step/s, loss=0.028683, elapsed=15.4min]

Entraînement:  48%|████▊     | 4804/10000 [15:23<16:26,  5.27step/s, loss=0.031450, elapsed=15.4min]

Entraînement:  48%|████▊     | 4805/10000 [15:24<16:24,  5.28step/s, loss=0.031450, elapsed=15.4min]

Entraînement:  48%|████▊     | 4805/10000 [15:24<16:24,  5.28step/s, loss=0.032996, elapsed=15.4min]

Entraînement:  48%|████▊     | 4806/10000 [15:24<16:24,  5.28step/s, loss=0.032996, elapsed=15.4min]

Entraînement:  48%|████▊     | 4806/10000 [15:24<16:24,  5.28step/s, loss=0.078889, elapsed=15.4min]

Entraînement:  48%|████▊     | 4807/10000 [15:24<16:23,  5.28step/s, loss=0.078889, elapsed=15.4min]

Entraînement:  48%|████▊     | 4807/10000 [15:24<16:23,  5.28step/s, loss=0.041724, elapsed=15.4min]

Entraînement:  48%|████▊     | 4808/10000 [15:24<16:22,  5.28step/s, loss=0.041724, elapsed=15.4min]

Entraînement:  48%|████▊     | 4808/10000 [15:24<16:22,  5.28step/s, loss=0.044866, elapsed=15.4min]

Entraînement:  48%|████▊     | 4809/10000 [15:24<16:23,  5.28step/s, loss=0.044866, elapsed=15.4min]

Entraînement:  48%|████▊     | 4809/10000 [15:24<16:23,  5.28step/s, loss=0.072090, elapsed=15.4min]

Entraînement:  48%|████▊     | 4810/10000 [15:25<16:22,  5.28step/s, loss=0.072090, elapsed=15.4min]

Entraînement:  48%|████▊     | 4810/10000 [15:25<16:22,  5.28step/s, loss=0.070173, elapsed=15.4min]

Entraînement:  48%|████▊     | 4811/10000 [15:25<16:21,  5.28step/s, loss=0.070173, elapsed=15.4min]

Entraînement:  48%|████▊     | 4811/10000 [15:25<16:21,  5.28step/s, loss=0.050836, elapsed=15.4min]

Entraînement:  48%|████▊     | 4812/10000 [15:25<16:21,  5.29step/s, loss=0.050836, elapsed=15.4min]

Entraînement:  48%|████▊     | 4812/10000 [15:25<16:21,  5.29step/s, loss=0.229395, elapsed=15.4min]

Entraînement:  48%|████▊     | 4813/10000 [15:25<16:20,  5.29step/s, loss=0.229395, elapsed=15.4min]

Entraînement:  48%|████▊     | 4813/10000 [15:25<16:20,  5.29step/s, loss=0.047105, elapsed=15.4min]

Entraînement:  48%|████▊     | 4814/10000 [15:25<16:20,  5.29step/s, loss=0.047105, elapsed=15.4min]

Entraînement:  48%|████▊     | 4814/10000 [15:25<16:20,  5.29step/s, loss=0.103997, elapsed=15.4min]

Entraînement:  48%|████▊     | 4815/10000 [15:26<16:20,  5.29step/s, loss=0.103997, elapsed=15.4min]

Entraînement:  48%|████▊     | 4815/10000 [15:26<16:20,  5.29step/s, loss=0.050461, elapsed=15.4min]

Entraînement:  48%|████▊     | 4816/10000 [15:26<16:22,  5.28step/s, loss=0.050461, elapsed=15.4min]

Entraînement:  48%|████▊     | 4816/10000 [15:26<16:22,  5.28step/s, loss=0.047348, elapsed=15.4min]

Entraînement:  48%|████▊     | 4817/10000 [15:26<16:21,  5.28step/s, loss=0.047348, elapsed=15.4min]

Entraînement:  48%|████▊     | 4817/10000 [15:26<16:21,  5.28step/s, loss=0.035070, elapsed=15.4min]

Entraînement:  48%|████▊     | 4818/10000 [15:26<16:23,  5.27step/s, loss=0.035070, elapsed=15.4min]

Entraînement:  48%|████▊     | 4818/10000 [15:26<16:23,  5.27step/s, loss=0.045934, elapsed=15.4min]

Entraînement:  48%|████▊     | 4819/10000 [15:26<16:21,  5.28step/s, loss=0.045934, elapsed=15.4min]

Entraînement:  48%|████▊     | 4819/10000 [15:26<16:21,  5.28step/s, loss=0.060026, elapsed=15.4min]

Entraînement:  48%|████▊     | 4820/10000 [15:26<16:19,  5.29step/s, loss=0.060026, elapsed=15.4min]

Entraînement:  48%|████▊     | 4820/10000 [15:26<16:19,  5.29step/s, loss=0.065785, elapsed=15.4min]

Entraînement:  48%|████▊     | 4821/10000 [15:27<16:19,  5.29step/s, loss=0.065785, elapsed=15.4min]

Entraînement:  48%|████▊     | 4821/10000 [15:27<16:19,  5.29step/s, loss=0.052792, elapsed=15.5min]

Entraînement:  48%|████▊     | 4822/10000 [15:27<16:18,  5.29step/s, loss=0.052792, elapsed=15.5min]

Entraînement:  48%|████▊     | 4822/10000 [15:27<16:18,  5.29step/s, loss=0.047583, elapsed=15.5min]

Entraînement:  48%|████▊     | 4823/10000 [15:27<16:17,  5.30step/s, loss=0.047583, elapsed=15.5min]

Entraînement:  48%|████▊     | 4823/10000 [15:27<16:17,  5.30step/s, loss=0.045663, elapsed=15.5min]

Entraînement:  48%|████▊     | 4824/10000 [15:27<16:19,  5.28step/s, loss=0.045663, elapsed=15.5min]

Entraînement:  48%|████▊     | 4824/10000 [15:27<16:19,  5.28step/s, loss=0.109735, elapsed=15.5min]

Entraînement:  48%|████▊     | 4825/10000 [15:27<16:18,  5.29step/s, loss=0.109735, elapsed=15.5min]

Entraînement:  48%|████▊     | 4825/10000 [15:27<16:18,  5.29step/s, loss=0.035818, elapsed=15.5min]

Entraînement:  48%|████▊     | 4826/10000 [15:28<16:19,  5.28step/s, loss=0.035818, elapsed=15.5min]

Entraînement:  48%|████▊     | 4826/10000 [15:28<16:19,  5.28step/s, loss=0.032376, elapsed=15.5min]

Entraînement:  48%|████▊     | 4827/10000 [15:28<16:19,  5.28step/s, loss=0.032376, elapsed=15.5min]

Entraînement:  48%|████▊     | 4827/10000 [15:28<16:19,  5.28step/s, loss=0.080791, elapsed=15.5min]

Entraînement:  48%|████▊     | 4828/10000 [15:28<16:19,  5.28step/s, loss=0.080791, elapsed=15.5min]

Entraînement:  48%|████▊     | 4828/10000 [15:28<16:19,  5.28step/s, loss=0.056557, elapsed=15.5min]

Entraînement:  48%|████▊     | 4829/10000 [15:28<16:22,  5.26step/s, loss=0.056557, elapsed=15.5min]

Entraînement:  48%|████▊     | 4829/10000 [15:28<16:22,  5.26step/s, loss=0.058608, elapsed=15.5min]

Entraînement:  48%|████▊     | 4830/10000 [15:28<16:20,  5.27step/s, loss=0.058608, elapsed=15.5min]

Entraînement:  48%|████▊     | 4830/10000 [15:28<16:20,  5.27step/s, loss=0.045963, elapsed=15.5min]

Entraînement:  48%|████▊     | 4831/10000 [15:29<16:28,  5.23step/s, loss=0.045963, elapsed=15.5min]

Entraînement:  48%|████▊     | 4831/10000 [15:29<16:28,  5.23step/s, loss=0.032888, elapsed=15.5min]

Entraînement:  48%|████▊     | 4832/10000 [15:29<16:27,  5.23step/s, loss=0.032888, elapsed=15.5min]

Entraînement:  48%|████▊     | 4832/10000 [15:29<16:27,  5.23step/s, loss=0.043091, elapsed=15.5min]

Entraînement:  48%|████▊     | 4833/10000 [15:29<16:25,  5.24step/s, loss=0.043091, elapsed=15.5min]

Entraînement:  48%|████▊     | 4833/10000 [15:29<16:25,  5.24step/s, loss=0.142465, elapsed=15.5min]

Entraînement:  48%|████▊     | 4834/10000 [15:29<16:23,  5.25step/s, loss=0.142465, elapsed=15.5min]

Entraînement:  48%|████▊     | 4834/10000 [15:29<16:23,  5.25step/s, loss=0.035887, elapsed=15.5min]

Entraînement:  48%|████▊     | 4835/10000 [15:29<16:21,  5.26step/s, loss=0.035887, elapsed=15.5min]

Entraînement:  48%|████▊     | 4835/10000 [15:29<16:21,  5.26step/s, loss=0.075936, elapsed=15.5min]

Entraînement:  48%|████▊     | 4836/10000 [15:30<16:20,  5.27step/s, loss=0.075936, elapsed=15.5min]

Entraînement:  48%|████▊     | 4836/10000 [15:30<16:20,  5.27step/s, loss=0.028330, elapsed=15.5min]

Entraînement:  48%|████▊     | 4837/10000 [15:30<16:22,  5.25step/s, loss=0.028330, elapsed=15.5min]

Entraînement:  48%|████▊     | 4837/10000 [15:30<16:22,  5.25step/s, loss=0.113912, elapsed=15.5min]

Entraînement:  48%|████▊     | 4838/10000 [15:30<16:20,  5.27step/s, loss=0.113912, elapsed=15.5min]

Entraînement:  48%|████▊     | 4838/10000 [15:30<16:20,  5.27step/s, loss=0.039179, elapsed=15.5min]

Entraînement:  48%|████▊     | 4839/10000 [15:30<16:22,  5.25step/s, loss=0.039179, elapsed=15.5min]

Entraînement:  48%|████▊     | 4839/10000 [15:30<16:22,  5.25step/s, loss=0.058385, elapsed=15.5min]

Entraînement:  48%|████▊     | 4840/10000 [15:30<16:21,  5.25step/s, loss=0.058385, elapsed=15.5min]

Entraînement:  48%|████▊     | 4840/10000 [15:30<16:21,  5.25step/s, loss=0.016019, elapsed=15.5min]

Entraînement:  48%|████▊     | 4841/10000 [15:30<16:20,  5.26step/s, loss=0.016019, elapsed=15.5min]

Entraînement:  48%|████▊     | 4841/10000 [15:30<16:20,  5.26step/s, loss=0.039863, elapsed=15.5min]

Entraînement:  48%|████▊     | 4842/10000 [15:31<16:20,  5.26step/s, loss=0.039863, elapsed=15.5min]

Entraînement:  48%|████▊     | 4842/10000 [15:31<16:20,  5.26step/s, loss=0.079684, elapsed=15.5min]

Entraînement:  48%|████▊     | 4843/10000 [15:31<16:18,  5.27step/s, loss=0.079684, elapsed=15.5min]

Entraînement:  48%|████▊     | 4843/10000 [15:31<16:18,  5.27step/s, loss=0.064298, elapsed=15.5min]

Entraînement:  48%|████▊     | 4844/10000 [15:31<16:19,  5.27step/s, loss=0.064298, elapsed=15.5min]

Entraînement:  48%|████▊     | 4844/10000 [15:31<16:19,  5.27step/s, loss=0.062715, elapsed=15.5min]

Entraînement:  48%|████▊     | 4845/10000 [15:31<16:19,  5.26step/s, loss=0.062715, elapsed=15.5min]

Entraînement:  48%|████▊     | 4845/10000 [15:31<16:19,  5.26step/s, loss=0.038912, elapsed=15.5min]

Entraînement:  48%|████▊     | 4846/10000 [15:31<16:26,  5.22step/s, loss=0.038912, elapsed=15.5min]

Entraînement:  48%|████▊     | 4846/10000 [15:31<16:26,  5.22step/s, loss=0.103763, elapsed=15.5min]

Entraînement:  48%|████▊     | 4847/10000 [15:32<16:29,  5.21step/s, loss=0.103763, elapsed=15.5min]

Entraînement:  48%|████▊     | 4847/10000 [15:32<16:29,  5.21step/s, loss=0.026303, elapsed=15.5min]

Entraînement:  48%|████▊     | 4848/10000 [15:32<16:26,  5.22step/s, loss=0.026303, elapsed=15.5min]

Entraînement:  48%|████▊     | 4848/10000 [15:32<16:26,  5.22step/s, loss=0.034150, elapsed=15.5min]

Entraînement:  48%|████▊     | 4849/10000 [15:32<16:21,  5.25step/s, loss=0.034150, elapsed=15.5min]

Entraînement:  48%|████▊     | 4849/10000 [15:32<16:21,  5.25step/s, loss=0.084982, elapsed=15.5min]

Entraînement:  48%|████▊     | 4850/10000 [15:32<16:20,  5.25step/s, loss=0.084982, elapsed=15.5min]

Entraînement:  48%|████▊     | 4850/10000 [15:32<16:20,  5.25step/s, loss=0.048371, elapsed=15.5min]

Entraînement:  49%|████▊     | 4851/10000 [15:32<16:19,  5.26step/s, loss=0.048371, elapsed=15.5min]

Entraînement:  49%|████▊     | 4851/10000 [15:32<16:19,  5.26step/s, loss=0.027352, elapsed=15.5min]

Entraînement:  49%|████▊     | 4852/10000 [15:33<16:18,  5.26step/s, loss=0.027352, elapsed=15.5min]

Entraînement:  49%|████▊     | 4852/10000 [15:33<16:18,  5.26step/s, loss=0.049919, elapsed=15.6min]

Entraînement:  49%|████▊     | 4853/10000 [15:33<16:16,  5.27step/s, loss=0.049919, elapsed=15.6min]

Entraînement:  49%|████▊     | 4853/10000 [15:33<16:16,  5.27step/s, loss=0.051499, elapsed=15.6min]

Entraînement:  49%|████▊     | 4854/10000 [15:33<16:13,  5.28step/s, loss=0.051499, elapsed=15.6min]

Entraînement:  49%|████▊     | 4854/10000 [15:33<16:13,  5.28step/s, loss=0.046650, elapsed=15.6min]

Entraînement:  49%|████▊     | 4855/10000 [15:33<16:13,  5.28step/s, loss=0.046650, elapsed=15.6min]

Entraînement:  49%|████▊     | 4855/10000 [15:33<16:13,  5.28step/s, loss=0.043202, elapsed=15.6min]

Entraînement:  49%|████▊     | 4856/10000 [15:33<16:12,  5.29step/s, loss=0.043202, elapsed=15.6min]

Entraînement:  49%|████▊     | 4856/10000 [15:33<16:12,  5.29step/s, loss=0.042228, elapsed=15.6min]

Entraînement:  49%|████▊     | 4857/10000 [15:34<16:13,  5.28step/s, loss=0.042228, elapsed=15.6min]

Entraînement:  49%|████▊     | 4857/10000 [15:34<16:13,  5.28step/s, loss=0.046972, elapsed=15.6min]

Entraînement:  49%|████▊     | 4858/10000 [15:34<16:12,  5.29step/s, loss=0.046972, elapsed=15.6min]

Entraînement:  49%|████▊     | 4858/10000 [15:34<16:12,  5.29step/s, loss=0.048212, elapsed=15.6min]

Entraînement:  49%|████▊     | 4859/10000 [15:34<16:14,  5.28step/s, loss=0.048212, elapsed=15.6min]

Entraînement:  49%|████▊     | 4859/10000 [15:34<16:14,  5.28step/s, loss=0.044782, elapsed=15.6min]

Entraînement:  49%|████▊     | 4860/10000 [15:34<16:13,  5.28step/s, loss=0.044782, elapsed=15.6min]

Entraînement:  49%|████▊     | 4860/10000 [15:34<16:13,  5.28step/s, loss=0.040896, elapsed=15.6min]

Entraînement:  49%|████▊     | 4861/10000 [15:34<16:12,  5.29step/s, loss=0.040896, elapsed=15.6min]

Entraînement:  49%|████▊     | 4861/10000 [15:34<16:12,  5.29step/s, loss=0.036696, elapsed=15.6min]

Entraînement:  49%|████▊     | 4862/10000 [15:34<16:12,  5.28step/s, loss=0.036696, elapsed=15.6min]

Entraînement:  49%|████▊     | 4862/10000 [15:34<16:12,  5.28step/s, loss=0.038566, elapsed=15.6min]

Entraînement:  49%|████▊     | 4863/10000 [15:35<16:12,  5.28step/s, loss=0.038566, elapsed=15.6min]

Entraînement:  49%|████▊     | 4863/10000 [15:35<16:12,  5.28step/s, loss=0.038527, elapsed=15.6min]

Entraînement:  49%|████▊     | 4864/10000 [15:35<16:09,  5.29step/s, loss=0.038527, elapsed=15.6min]

Entraînement:  49%|████▊     | 4864/10000 [15:35<16:09,  5.29step/s, loss=0.029382, elapsed=15.6min]

Entraînement:  49%|████▊     | 4865/10000 [15:35<16:10,  5.29step/s, loss=0.029382, elapsed=15.6min]

Entraînement:  49%|████▊     | 4865/10000 [15:35<16:10,  5.29step/s, loss=0.039019, elapsed=15.6min]

Entraînement:  49%|████▊     | 4866/10000 [15:35<16:10,  5.29step/s, loss=0.039019, elapsed=15.6min]

Entraînement:  49%|████▊     | 4866/10000 [15:35<16:10,  5.29step/s, loss=0.050687, elapsed=15.6min]

Entraînement:  49%|████▊     | 4867/10000 [15:36<24:11,  3.54step/s, loss=0.050687, elapsed=15.6min]

Entraînement:  49%|████▊     | 4867/10000 [15:36<24:11,  3.54step/s, loss=0.033482, elapsed=15.6min]

Entraînement:  49%|████▊     | 4868/10000 [15:36<21:49,  3.92step/s, loss=0.033482, elapsed=15.6min]

Entraînement:  49%|████▊     | 4868/10000 [15:36<21:49,  3.92step/s, loss=0.095289, elapsed=15.6min]

Entraînement:  49%|████▊     | 4869/10000 [15:36<20:08,  4.25step/s, loss=0.095289, elapsed=15.6min]

Entraînement:  49%|████▊     | 4869/10000 [15:36<20:08,  4.25step/s, loss=0.042362, elapsed=15.6min]

Entraînement:  49%|████▊     | 4870/10000 [15:36<18:57,  4.51step/s, loss=0.042362, elapsed=15.6min]

Entraînement:  49%|████▊     | 4870/10000 [15:36<18:57,  4.51step/s, loss=0.096358, elapsed=15.6min]

Entraînement:  49%|████▊     | 4871/10000 [15:36<18:08,  4.71step/s, loss=0.096358, elapsed=15.6min]

Entraînement:  49%|████▊     | 4871/10000 [15:36<18:08,  4.71step/s, loss=0.026536, elapsed=15.6min]

Entraînement:  49%|████▊     | 4872/10000 [15:37<17:32,  4.87step/s, loss=0.026536, elapsed=15.6min]

Entraînement:  49%|████▊     | 4872/10000 [15:37<17:32,  4.87step/s, loss=0.064483, elapsed=15.6min]

Entraînement:  49%|████▊     | 4873/10000 [15:37<17:06,  4.99step/s, loss=0.064483, elapsed=15.6min]

Entraînement:  49%|████▊     | 4873/10000 [15:37<17:06,  4.99step/s, loss=0.071039, elapsed=15.6min]

Entraînement:  49%|████▊     | 4874/10000 [15:37<16:50,  5.07step/s, loss=0.071039, elapsed=15.6min]

Entraînement:  49%|████▊     | 4874/10000 [15:37<16:50,  5.07step/s, loss=0.106237, elapsed=15.6min]

Entraînement:  49%|████▉     | 4875/10000 [15:37<16:37,  5.14step/s, loss=0.106237, elapsed=15.6min]

Entraînement:  49%|████▉     | 4875/10000 [15:37<16:37,  5.14step/s, loss=0.091471, elapsed=15.6min]

Entraînement:  49%|████▉     | 4876/10000 [15:37<16:29,  5.18step/s, loss=0.091471, elapsed=15.6min]

Entraînement:  49%|████▉     | 4876/10000 [15:37<16:29,  5.18step/s, loss=0.050683, elapsed=15.6min]

Entraînement:  49%|████▉     | 4877/10000 [15:38<16:22,  5.21step/s, loss=0.050683, elapsed=15.6min]

Entraînement:  49%|████▉     | 4877/10000 [15:38<16:22,  5.21step/s, loss=0.036007, elapsed=15.6min]

Entraînement:  49%|████▉     | 4878/10000 [15:38<16:18,  5.23step/s, loss=0.036007, elapsed=15.6min]

Entraînement:  49%|████▉     | 4878/10000 [15:38<16:18,  5.23step/s, loss=0.033491, elapsed=15.6min]

Entraînement:  49%|████▉     | 4879/10000 [15:38<16:17,  5.24step/s, loss=0.033491, elapsed=15.6min]

Entraînement:  49%|████▉     | 4879/10000 [15:38<16:17,  5.24step/s, loss=0.037499, elapsed=15.6min]

Entraînement:  49%|████▉     | 4880/10000 [15:38<16:13,  5.26step/s, loss=0.037499, elapsed=15.6min]

Entraînement:  49%|████▉     | 4880/10000 [15:38<16:13,  5.26step/s, loss=0.053440, elapsed=15.6min]

Entraînement:  49%|████▉     | 4881/10000 [15:38<16:15,  5.25step/s, loss=0.053440, elapsed=15.6min]

Entraînement:  49%|████▉     | 4881/10000 [15:38<16:15,  5.25step/s, loss=0.105923, elapsed=15.6min]

Entraînement:  49%|████▉     | 4882/10000 [15:39<16:09,  5.28step/s, loss=0.105923, elapsed=15.6min]

Entraînement:  49%|████▉     | 4882/10000 [15:39<16:09,  5.28step/s, loss=0.075942, elapsed=15.7min]

Entraînement:  49%|████▉     | 4883/10000 [15:39<16:05,  5.30step/s, loss=0.075942, elapsed=15.7min]

Entraînement:  49%|████▉     | 4883/10000 [15:39<16:05,  5.30step/s, loss=0.056714, elapsed=15.7min]

Entraînement:  49%|████▉     | 4884/10000 [15:39<16:01,  5.32step/s, loss=0.056714, elapsed=15.7min]

Entraînement:  49%|████▉     | 4884/10000 [15:39<16:01,  5.32step/s, loss=0.057247, elapsed=15.7min]

Entraînement:  49%|████▉     | 4885/10000 [15:39<15:59,  5.33step/s, loss=0.057247, elapsed=15.7min]

Entraînement:  49%|████▉     | 4885/10000 [15:39<15:59,  5.33step/s, loss=0.056019, elapsed=15.7min]

Entraînement:  49%|████▉     | 4886/10000 [15:39<15:57,  5.34step/s, loss=0.056019, elapsed=15.7min]

Entraînement:  49%|████▉     | 4886/10000 [15:39<15:57,  5.34step/s, loss=0.045618, elapsed=15.7min]

Entraînement:  49%|████▉     | 4887/10000 [15:39<15:56,  5.34step/s, loss=0.045618, elapsed=15.7min]

Entraînement:  49%|████▉     | 4887/10000 [15:40<15:56,  5.34step/s, loss=0.041082, elapsed=15.7min]

Entraînement:  49%|████▉     | 4888/10000 [15:40<15:59,  5.33step/s, loss=0.041082, elapsed=15.7min]

Entraînement:  49%|████▉     | 4888/10000 [15:40<15:59,  5.33step/s, loss=0.052119, elapsed=15.7min]

Entraînement:  49%|████▉     | 4889/10000 [15:40<15:57,  5.34step/s, loss=0.052119, elapsed=15.7min]

Entraînement:  49%|████▉     | 4889/10000 [15:40<15:57,  5.34step/s, loss=0.035859, elapsed=15.7min]

Entraînement:  49%|████▉     | 4890/10000 [15:40<15:55,  5.35step/s, loss=0.035859, elapsed=15.7min]

Entraînement:  49%|████▉     | 4890/10000 [15:40<15:55,  5.35step/s, loss=0.035431, elapsed=15.7min]

Entraînement:  49%|████▉     | 4891/10000 [15:40<15:54,  5.35step/s, loss=0.035431, elapsed=15.7min]

Entraînement:  49%|████▉     | 4891/10000 [15:40<15:54,  5.35step/s, loss=0.048247, elapsed=15.7min]

Entraînement:  49%|████▉     | 4892/10000 [15:40<15:53,  5.36step/s, loss=0.048247, elapsed=15.7min]

Entraînement:  49%|████▉     | 4892/10000 [15:40<15:53,  5.36step/s, loss=0.042111, elapsed=15.7min]

Entraînement:  49%|████▉     | 4893/10000 [15:41<15:51,  5.36step/s, loss=0.042111, elapsed=15.7min]

Entraînement:  49%|████▉     | 4893/10000 [15:41<15:51,  5.36step/s, loss=0.114422, elapsed=15.7min]

Entraînement:  49%|████▉     | 4894/10000 [15:41<15:50,  5.37step/s, loss=0.114422, elapsed=15.7min]

Entraînement:  49%|████▉     | 4894/10000 [15:41<15:50,  5.37step/s, loss=0.027151, elapsed=15.7min]

Entraînement:  49%|████▉     | 4895/10000 [15:41<15:50,  5.37step/s, loss=0.027151, elapsed=15.7min]

Entraînement:  49%|████▉     | 4895/10000 [15:41<15:50,  5.37step/s, loss=0.097089, elapsed=15.7min]

Entraînement:  49%|████▉     | 4896/10000 [15:41<15:52,  5.36step/s, loss=0.097089, elapsed=15.7min]

Entraînement:  49%|████▉     | 4896/10000 [15:41<15:52,  5.36step/s, loss=0.048092, elapsed=15.7min]

Entraînement:  49%|████▉     | 4897/10000 [15:41<15:51,  5.36step/s, loss=0.048092, elapsed=15.7min]

Entraînement:  49%|████▉     | 4897/10000 [15:41<15:51,  5.36step/s, loss=0.064188, elapsed=15.7min]

Entraînement:  49%|████▉     | 4898/10000 [15:42<15:52,  5.36step/s, loss=0.064188, elapsed=15.7min]

Entraînement:  49%|████▉     | 4898/10000 [15:42<15:52,  5.36step/s, loss=0.043571, elapsed=15.7min]

Entraînement:  49%|████▉     | 4899/10000 [15:42<15:51,  5.36step/s, loss=0.043571, elapsed=15.7min]

Entraînement:  49%|████▉     | 4899/10000 [15:42<15:51,  5.36step/s, loss=0.048744, elapsed=15.7min]

Entraînement:  49%|████▉     | 4900/10000 [15:42<15:51,  5.36step/s, loss=0.048744, elapsed=15.7min]

Entraînement:  49%|████▉     | 4900/10000 [15:42<15:51,  5.36step/s, loss=0.024448, elapsed=15.7min]

Entraînement:  49%|████▉     | 4900/10000 [15:42<15:51,  5.36step/s, loss=0.024448, elapsed=15.7min]

Entraînement:  49%|████▉     | 4901/10000 [15:42<15:57,  5.33step/s, loss=0.024448, elapsed=15.7min]

Entraînement:  49%|████▉     | 4901/10000 [15:42<15:57,  5.33step/s, loss=0.050054, elapsed=15.7min]

Step 4900/10000 | Train loss: 0.024448 | Elapsed: 15.7min | ETA: 16.3min

Entraînement:  49%|████▉     | 4902/10000 [15:42<15:55,  5.33step/s, loss=0.050054, elapsed=15.7min]

Entraînement:  49%|████▉     | 4902/10000 [15:42<15:55,  5.33step/s, loss=0.087905, elapsed=15.7min]

Entraînement:  49%|████▉     | 4903/10000 [15:42<15:52,  5.35step/s, loss=0.087905, elapsed=15.7min]

Entraînement:  49%|████▉     | 4903/10000 [15:42<15:52,  5.35step/s, loss=0.062526, elapsed=15.7min]

Entraînement:  49%|████▉     | 4904/10000 [15:43<15:52,  5.35step/s, loss=0.062526, elapsed=15.7min]

Entraînement:  49%|████▉     | 4904/10000 [15:43<15:52,  5.35step/s, loss=0.135978, elapsed=15.7min]

Entraînement:  49%|████▉     | 4905/10000 [15:43<15:54,  5.34step/s, loss=0.135978, elapsed=15.7min]

Entraînement:  49%|████▉     | 4905/10000 [15:43<15:54,  5.34step/s, loss=0.046607, elapsed=15.7min]

Entraînement:  49%|████▉     | 4906/10000 [15:43<15:51,  5.35step/s, loss=0.046607, elapsed=15.7min]

Entraînement:  49%|████▉     | 4906/10000 [15:43<15:51,  5.35step/s, loss=0.034741, elapsed=15.7min]

Entraînement:  49%|████▉     | 4907/10000 [15:43<15:50,  5.36step/s, loss=0.034741, elapsed=15.7min]

Entraînement:  49%|████▉     | 4907/10000 [15:43<15:50,  5.36step/s, loss=0.029355, elapsed=15.7min]

Entraînement:  49%|████▉     | 4908/10000 [15:43<15:52,  5.35step/s, loss=0.029355, elapsed=15.7min]

Entraînement:  49%|████▉     | 4908/10000 [15:43<15:52,  5.35step/s, loss=0.061878, elapsed=15.7min]

Entraînement:  49%|████▉     | 4909/10000 [15:44<15:51,  5.35step/s, loss=0.061878, elapsed=15.7min]

Entraînement:  49%|████▉     | 4909/10000 [15:44<15:51,  5.35step/s, loss=0.100026, elapsed=15.7min]

Entraînement:  49%|████▉     | 4910/10000 [15:44<15:50,  5.35step/s, loss=0.100026, elapsed=15.7min]

Entraînement:  49%|████▉     | 4910/10000 [15:44<15:50,  5.35step/s, loss=0.055611, elapsed=15.7min]

Entraînement:  49%|████▉     | 4911/10000 [15:44<15:50,  5.35step/s, loss=0.055611, elapsed=15.7min]

Entraînement:  49%|████▉     | 4911/10000 [15:44<15:50,  5.35step/s, loss=0.031897, elapsed=15.7min]

Entraînement:  49%|████▉     | 4912/10000 [15:44<15:49,  5.36step/s, loss=0.031897, elapsed=15.7min]

Entraînement:  49%|████▉     | 4912/10000 [15:44<15:49,  5.36step/s, loss=0.024929, elapsed=15.7min]

Entraînement:  49%|████▉     | 4913/10000 [15:44<15:49,  5.36step/s, loss=0.024929, elapsed=15.7min]

Entraînement:  49%|████▉     | 4913/10000 [15:44<15:49,  5.36step/s, loss=0.035791, elapsed=15.7min]

Entraînement:  49%|████▉     | 4914/10000 [15:45<15:49,  5.36step/s, loss=0.035791, elapsed=15.7min]

Entraînement:  49%|████▉     | 4914/10000 [15:45<15:49,  5.36step/s, loss=0.054726, elapsed=15.8min]

Entraînement:  49%|████▉     | 4915/10000 [15:45<15:49,  5.35step/s, loss=0.054726, elapsed=15.8min]

Entraînement:  49%|████▉     | 4915/10000 [15:45<15:49,  5.35step/s, loss=0.039418, elapsed=15.8min]

Entraînement:  49%|████▉     | 4916/10000 [15:45<15:48,  5.36step/s, loss=0.039418, elapsed=15.8min]

Entraînement:  49%|████▉     | 4916/10000 [15:45<15:48,  5.36step/s, loss=0.035887, elapsed=15.8min]

Entraînement:  49%|████▉     | 4917/10000 [15:45<15:47,  5.37step/s, loss=0.035887, elapsed=15.8min]

Entraînement:  49%|████▉     | 4917/10000 [15:45<15:47,  5.37step/s, loss=0.061203, elapsed=15.8min]

Entraînement:  49%|████▉     | 4918/10000 [15:45<15:47,  5.37step/s, loss=0.061203, elapsed=15.8min]

Entraînement:  49%|████▉     | 4918/10000 [15:45<15:47,  5.37step/s, loss=0.103874, elapsed=15.8min]

Entraînement:  49%|████▉     | 4919/10000 [15:45<15:46,  5.37step/s, loss=0.103874, elapsed=15.8min]

Entraînement:  49%|████▉     | 4919/10000 [15:45<15:46,  5.37step/s, loss=0.048345, elapsed=15.8min]

Entraînement:  49%|████▉     | 4920/10000 [15:46<15:45,  5.37step/s, loss=0.048345, elapsed=15.8min]

Entraînement:  49%|████▉     | 4920/10000 [15:46<15:45,  5.37step/s, loss=0.083324, elapsed=15.8min]

Entraînement:  49%|████▉     | 4921/10000 [15:46<15:45,  5.37step/s, loss=0.083324, elapsed=15.8min]

Entraînement:  49%|████▉     | 4921/10000 [15:46<15:45,  5.37step/s, loss=0.028371, elapsed=15.8min]

Entraînement:  49%|████▉     | 4922/10000 [15:46<15:48,  5.35step/s, loss=0.028371, elapsed=15.8min]

Entraînement:  49%|████▉     | 4922/10000 [15:46<15:48,  5.35step/s, loss=0.053728, elapsed=15.8min]

Entraînement:  49%|████▉     | 4923/10000 [15:46<15:49,  5.35step/s, loss=0.053728, elapsed=15.8min]

Entraînement:  49%|████▉     | 4923/10000 [15:46<15:49,  5.35step/s, loss=0.043502, elapsed=15.8min]

Entraînement:  49%|████▉     | 4924/10000 [15:46<15:47,  5.36step/s, loss=0.043502, elapsed=15.8min]

Entraînement:  49%|████▉     | 4924/10000 [15:46<15:47,  5.36step/s, loss=0.058002, elapsed=15.8min]

Entraînement:  49%|████▉     | 4925/10000 [15:47<15:47,  5.36step/s, loss=0.058002, elapsed=15.8min]

Entraînement:  49%|████▉     | 4925/10000 [15:47<15:47,  5.36step/s, loss=0.026673, elapsed=15.8min]

Entraînement:  49%|████▉     | 4926/10000 [15:47<15:47,  5.36step/s, loss=0.026673, elapsed=15.8min]

Entraînement:  49%|████▉     | 4926/10000 [15:47<15:47,  5.36step/s, loss=0.090481, elapsed=15.8min]

Entraînement:  49%|████▉     | 4927/10000 [15:47<15:45,  5.36step/s, loss=0.090481, elapsed=15.8min]

Entraînement:  49%|████▉     | 4927/10000 [15:47<15:45,  5.36step/s, loss=0.029056, elapsed=15.8min]

Entraînement:  49%|████▉     | 4928/10000 [15:47<15:45,  5.36step/s, loss=0.029056, elapsed=15.8min]

Entraînement:  49%|████▉     | 4928/10000 [15:47<15:45,  5.36step/s, loss=0.080590, elapsed=15.8min]

Entraînement:  49%|████▉     | 4929/10000 [15:47<15:46,  5.36step/s, loss=0.080590, elapsed=15.8min]

Entraînement:  49%|████▉     | 4929/10000 [15:47<15:46,  5.36step/s, loss=0.033321, elapsed=15.8min]

Entraînement:  49%|████▉     | 4930/10000 [15:48<15:51,  5.33step/s, loss=0.033321, elapsed=15.8min]

Entraînement:  49%|████▉     | 4930/10000 [15:48<15:51,  5.33step/s, loss=0.040234, elapsed=15.8min]

Entraînement:  49%|████▉     | 4931/10000 [15:48<15:52,  5.32step/s, loss=0.040234, elapsed=15.8min]

Entraînement:  49%|████▉     | 4931/10000 [15:48<15:52,  5.32step/s, loss=0.028475, elapsed=15.8min]

Entraînement:  49%|████▉     | 4932/10000 [15:48<15:56,  5.30step/s, loss=0.028475, elapsed=15.8min]

Entraînement:  49%|████▉     | 4932/10000 [15:48<15:56,  5.30step/s, loss=0.029098, elapsed=15.8min]

Entraînement:  49%|████▉     | 4933/10000 [15:48<15:57,  5.29step/s, loss=0.029098, elapsed=15.8min]

Entraînement:  49%|████▉     | 4933/10000 [15:48<15:57,  5.29step/s, loss=0.037529, elapsed=15.8min]

Entraînement:  49%|████▉     | 4934/10000 [15:48<15:58,  5.28step/s, loss=0.037529, elapsed=15.8min]

Entraînement:  49%|████▉     | 4934/10000 [15:48<15:58,  5.28step/s, loss=0.033232, elapsed=15.8min]

Entraînement:  49%|████▉     | 4935/10000 [15:48<15:58,  5.28step/s, loss=0.033232, elapsed=15.8min]

Entraînement:  49%|████▉     | 4935/10000 [15:48<15:58,  5.28step/s, loss=0.028261, elapsed=15.8min]

Entraînement:  49%|████▉     | 4936/10000 [15:49<15:55,  5.30step/s, loss=0.028261, elapsed=15.8min]

Entraînement:  49%|████▉     | 4936/10000 [15:49<15:55,  5.30step/s, loss=0.094286, elapsed=15.8min]

Entraînement:  49%|████▉     | 4937/10000 [15:49<15:56,  5.29step/s, loss=0.094286, elapsed=15.8min]

Entraînement:  49%|████▉     | 4937/10000 [15:49<15:56,  5.29step/s, loss=0.037563, elapsed=15.8min]

Entraînement:  49%|████▉     | 4938/10000 [15:49<15:56,  5.29step/s, loss=0.037563, elapsed=15.8min]

Entraînement:  49%|████▉     | 4938/10000 [15:49<15:56,  5.29step/s, loss=0.048914, elapsed=15.8min]

Entraînement:  49%|████▉     | 4939/10000 [15:49<15:57,  5.29step/s, loss=0.048914, elapsed=15.8min]

Entraînement:  49%|████▉     | 4939/10000 [15:49<15:57,  5.29step/s, loss=0.026735, elapsed=15.8min]

Entraînement:  49%|████▉     | 4940/10000 [15:49<15:58,  5.28step/s, loss=0.026735, elapsed=15.8min]

Entraînement:  49%|████▉     | 4940/10000 [15:49<15:58,  5.28step/s, loss=0.041931, elapsed=15.8min]

Entraînement:  49%|████▉     | 4941/10000 [15:50<15:57,  5.28step/s, loss=0.041931, elapsed=15.8min]

Entraînement:  49%|████▉     | 4941/10000 [15:50<15:57,  5.28step/s, loss=0.064469, elapsed=15.8min]

Entraînement:  49%|████▉     | 4942/10000 [15:50<15:59,  5.27step/s, loss=0.064469, elapsed=15.8min]

Entraînement:  49%|████▉     | 4942/10000 [15:50<15:59,  5.27step/s, loss=0.053618, elapsed=15.8min]

Entraînement:  49%|████▉     | 4943/10000 [15:50<15:58,  5.28step/s, loss=0.053618, elapsed=15.8min]

Entraînement:  49%|████▉     | 4943/10000 [15:50<15:58,  5.28step/s, loss=0.048869, elapsed=15.8min]

Entraînement:  49%|████▉     | 4944/10000 [15:50<15:58,  5.27step/s, loss=0.048869, elapsed=15.8min]

Entraînement:  49%|████▉     | 4944/10000 [15:50<15:58,  5.27step/s, loss=0.139746, elapsed=15.8min]

Entraînement:  49%|████▉     | 4945/10000 [15:50<15:57,  5.28step/s, loss=0.139746, elapsed=15.8min]

Entraînement:  49%|████▉     | 4945/10000 [15:50<15:57,  5.28step/s, loss=0.039490, elapsed=15.8min]

Entraînement:  49%|████▉     | 4946/10000 [15:51<15:59,  5.27step/s, loss=0.039490, elapsed=15.8min]

Entraînement:  49%|████▉     | 4946/10000 [15:51<15:59,  5.27step/s, loss=0.029376, elapsed=15.9min]

Entraînement:  49%|████▉     | 4947/10000 [15:51<15:59,  5.27step/s, loss=0.029376, elapsed=15.9min]

Entraînement:  49%|████▉     | 4947/10000 [15:51<15:59,  5.27step/s, loss=0.023298, elapsed=15.9min]

Entraînement:  49%|████▉     | 4948/10000 [15:51<15:56,  5.28step/s, loss=0.023298, elapsed=15.9min]

Entraînement:  49%|████▉     | 4948/10000 [15:51<15:56,  5.28step/s, loss=0.068488, elapsed=15.9min]

Entraînement:  49%|████▉     | 4949/10000 [15:51<15:57,  5.28step/s, loss=0.068488, elapsed=15.9min]

Entraînement:  49%|████▉     | 4949/10000 [15:51<15:57,  5.28step/s, loss=0.056666, elapsed=15.9min]

Entraînement:  50%|████▉     | 4950/10000 [15:51<15:55,  5.28step/s, loss=0.056666, elapsed=15.9min]

Entraînement:  50%|████▉     | 4950/10000 [15:51<15:55,  5.28step/s, loss=0.045805, elapsed=15.9min]

Entraînement:  50%|████▉     | 4951/10000 [15:52<15:54,  5.29step/s, loss=0.045805, elapsed=15.9min]

Entraînement:  50%|████▉     | 4951/10000 [15:52<15:54,  5.29step/s, loss=0.099495, elapsed=15.9min]

Entraînement:  50%|████▉     | 4952/10000 [15:52<15:54,  5.29step/s, loss=0.099495, elapsed=15.9min]

Entraînement:  50%|████▉     | 4952/10000 [15:52<15:54,  5.29step/s, loss=0.052840, elapsed=15.9min]

Entraînement:  50%|████▉     | 4953/10000 [15:52<15:53,  5.29step/s, loss=0.052840, elapsed=15.9min]

Entraînement:  50%|████▉     | 4953/10000 [15:52<15:53,  5.29step/s, loss=0.060020, elapsed=15.9min]

Entraînement:  50%|████▉     | 4954/10000 [15:52<15:55,  5.28step/s, loss=0.060020, elapsed=15.9min]

Entraînement:  50%|████▉     | 4954/10000 [15:52<15:55,  5.28step/s, loss=0.113150, elapsed=15.9min]

Entraînement:  50%|████▉     | 4955/10000 [15:52<15:56,  5.27step/s, loss=0.113150, elapsed=15.9min]

Entraînement:  50%|████▉     | 4955/10000 [15:52<15:56,  5.27step/s, loss=0.096516, elapsed=15.9min]

Entraînement:  50%|████▉     | 4956/10000 [15:52<15:54,  5.28step/s, loss=0.096516, elapsed=15.9min]

Entraînement:  50%|████▉     | 4956/10000 [15:52<15:54,  5.28step/s, loss=0.053581, elapsed=15.9min]

Entraînement:  50%|████▉     | 4957/10000 [15:53<15:55,  5.28step/s, loss=0.053581, elapsed=15.9min]

Entraînement:  50%|████▉     | 4957/10000 [15:53<15:55,  5.28step/s, loss=0.063962, elapsed=15.9min]

Entraînement:  50%|████▉     | 4958/10000 [15:53<15:53,  5.29step/s, loss=0.063962, elapsed=15.9min]

Entraînement:  50%|████▉     | 4958/10000 [15:53<15:53,  5.29step/s, loss=0.035065, elapsed=15.9min]

Entraînement:  50%|████▉     | 4959/10000 [15:53<15:53,  5.29step/s, loss=0.035065, elapsed=15.9min]

Entraînement:  50%|████▉     | 4959/10000 [15:53<15:53,  5.29step/s, loss=0.059487, elapsed=15.9min]

Entraînement:  50%|████▉     | 4960/10000 [15:53<15:54,  5.28step/s, loss=0.059487, elapsed=15.9min]

Entraînement:  50%|████▉     | 4960/10000 [15:53<15:54,  5.28step/s, loss=0.047840, elapsed=15.9min]

Entraînement:  50%|████▉     | 4961/10000 [15:53<15:54,  5.28step/s, loss=0.047840, elapsed=15.9min]

Entraînement:  50%|████▉     | 4961/10000 [15:53<15:54,  5.28step/s, loss=0.194167, elapsed=15.9min]

Entraînement:  50%|████▉     | 4962/10000 [15:54<15:54,  5.28step/s, loss=0.194167, elapsed=15.9min]

Entraînement:  50%|████▉     | 4962/10000 [15:54<15:54,  5.28step/s, loss=0.092564, elapsed=15.9min]

Entraînement:  50%|████▉     | 4963/10000 [15:54<15:54,  5.28step/s, loss=0.092564, elapsed=15.9min]

Entraînement:  50%|████▉     | 4963/10000 [15:54<15:54,  5.28step/s, loss=0.067441, elapsed=15.9min]

Entraînement:  50%|████▉     | 4964/10000 [15:54<15:59,  5.25step/s, loss=0.067441, elapsed=15.9min]

Entraînement:  50%|████▉     | 4964/10000 [15:54<15:59,  5.25step/s, loss=0.030638, elapsed=15.9min]

Entraînement:  50%|████▉     | 4965/10000 [15:54<16:02,  5.23step/s, loss=0.030638, elapsed=15.9min]

Entraînement:  50%|████▉     | 4965/10000 [15:54<16:02,  5.23step/s, loss=0.053336, elapsed=15.9min]

Entraînement:  50%|████▉     | 4966/10000 [15:54<16:04,  5.22step/s, loss=0.053336, elapsed=15.9min]

Entraînement:  50%|████▉     | 4966/10000 [15:54<16:04,  5.22step/s, loss=0.062653, elapsed=15.9min]

Entraînement:  50%|████▉     | 4967/10000 [15:55<16:04,  5.22step/s, loss=0.062653, elapsed=15.9min]

Entraînement:  50%|████▉     | 4967/10000 [15:55<16:04,  5.22step/s, loss=0.051372, elapsed=15.9min]

Entraînement:  50%|████▉     | 4968/10000 [15:55<16:02,  5.23step/s, loss=0.051372, elapsed=15.9min]

Entraînement:  50%|████▉     | 4968/10000 [15:55<16:02,  5.23step/s, loss=0.056973, elapsed=15.9min]

Entraînement:  50%|████▉     | 4969/10000 [15:55<16:03,  5.22step/s, loss=0.056973, elapsed=15.9min]

Entraînement:  50%|████▉     | 4969/10000 [15:55<16:03,  5.22step/s, loss=0.051528, elapsed=15.9min]

Entraînement:  50%|████▉     | 4970/10000 [15:55<16:02,  5.22step/s, loss=0.051528, elapsed=15.9min]

Entraînement:  50%|████▉     | 4970/10000 [15:55<16:02,  5.22step/s, loss=0.101312, elapsed=15.9min]

Entraînement:  50%|████▉     | 4971/10000 [15:55<16:03,  5.22step/s, loss=0.101312, elapsed=15.9min]

Entraînement:  50%|████▉     | 4971/10000 [15:55<16:03,  5.22step/s, loss=0.055821, elapsed=15.9min]

Entraînement:  50%|████▉     | 4972/10000 [15:56<16:00,  5.24step/s, loss=0.055821, elapsed=15.9min]

Entraînement:  50%|████▉     | 4972/10000 [15:56<16:00,  5.24step/s, loss=0.091773, elapsed=15.9min]

Entraînement:  50%|████▉     | 4973/10000 [15:56<16:00,  5.24step/s, loss=0.091773, elapsed=15.9min]

Entraînement:  50%|████▉     | 4973/10000 [15:56<16:00,  5.24step/s, loss=0.074706, elapsed=15.9min]

Entraînement:  50%|████▉     | 4974/10000 [15:56<15:57,  5.25step/s, loss=0.074706, elapsed=15.9min]

Entraînement:  50%|████▉     | 4974/10000 [15:56<15:57,  5.25step/s, loss=0.045082, elapsed=15.9min]

Entraînement:  50%|████▉     | 4975/10000 [15:56<15:54,  5.26step/s, loss=0.045082, elapsed=15.9min]

Entraînement:  50%|████▉     | 4975/10000 [15:56<15:54,  5.26step/s, loss=0.060920, elapsed=15.9min]

Entraînement:  50%|████▉     | 4976/10000 [15:56<15:55,  5.26step/s, loss=0.060920, elapsed=15.9min]

Entraînement:  50%|████▉     | 4976/10000 [15:56<15:55,  5.26step/s, loss=0.041030, elapsed=15.9min]

Entraînement:  50%|████▉     | 4977/10000 [15:56<15:55,  5.26step/s, loss=0.041030, elapsed=15.9min]

Entraînement:  50%|████▉     | 4977/10000 [15:56<15:55,  5.26step/s, loss=0.019097, elapsed=15.9min]

Entraînement:  50%|████▉     | 4978/10000 [15:57<15:56,  5.25step/s, loss=0.019097, elapsed=15.9min]

Entraînement:  50%|████▉     | 4978/10000 [15:57<15:56,  5.25step/s, loss=0.027053, elapsed=16.0min]

Entraînement:  50%|████▉     | 4979/10000 [15:57<15:55,  5.25step/s, loss=0.027053, elapsed=16.0min]

Entraînement:  50%|████▉     | 4979/10000 [15:57<15:55,  5.25step/s, loss=0.051875, elapsed=16.0min]

Entraînement:  50%|████▉     | 4980/10000 [15:57<15:53,  5.26step/s, loss=0.051875, elapsed=16.0min]

Entraînement:  50%|████▉     | 4980/10000 [15:57<15:53,  5.26step/s, loss=0.053512, elapsed=16.0min]

Entraînement:  50%|████▉     | 4981/10000 [15:57<15:53,  5.26step/s, loss=0.053512, elapsed=16.0min]

Entraînement:  50%|████▉     | 4981/10000 [15:57<15:53,  5.26step/s, loss=0.022179, elapsed=16.0min]

Entraînement:  50%|████▉     | 4982/10000 [15:57<15:52,  5.27step/s, loss=0.022179, elapsed=16.0min]

Entraînement:  50%|████▉     | 4982/10000 [15:57<15:52,  5.27step/s, loss=0.113945, elapsed=16.0min]

Entraînement:  50%|████▉     | 4983/10000 [15:58<15:51,  5.27step/s, loss=0.113945, elapsed=16.0min]

Entraînement:  50%|████▉     | 4983/10000 [15:58<15:51,  5.27step/s, loss=0.026087, elapsed=16.0min]

Entraînement:  50%|████▉     | 4984/10000 [15:58<15:51,  5.27step/s, loss=0.026087, elapsed=16.0min]

Entraînement:  50%|████▉     | 4984/10000 [15:58<15:51,  5.27step/s, loss=0.046408, elapsed=16.0min]

Entraînement:  50%|████▉     | 4985/10000 [15:58<15:54,  5.25step/s, loss=0.046408, elapsed=16.0min]

Entraînement:  50%|████▉     | 4985/10000 [15:58<15:54,  5.25step/s, loss=0.046955, elapsed=16.0min]

Entraînement:  50%|████▉     | 4986/10000 [15:58<15:53,  5.26step/s, loss=0.046955, elapsed=16.0min]

Entraînement:  50%|████▉     | 4986/10000 [15:58<15:53,  5.26step/s, loss=0.034918, elapsed=16.0min]

Entraînement:  50%|████▉     | 4987/10000 [15:58<15:53,  5.26step/s, loss=0.034918, elapsed=16.0min]

Entraînement:  50%|████▉     | 4987/10000 [15:58<15:53,  5.26step/s, loss=0.024194, elapsed=16.0min]

Entraînement:  50%|████▉     | 4988/10000 [15:59<15:59,  5.23step/s, loss=0.024194, elapsed=16.0min]

Entraînement:  50%|████▉     | 4988/10000 [15:59<15:59,  5.23step/s, loss=0.044984, elapsed=16.0min]

Entraînement:  50%|████▉     | 4989/10000 [15:59<16:02,  5.21step/s, loss=0.044984, elapsed=16.0min]

Entraînement:  50%|████▉     | 4989/10000 [15:59<16:02,  5.21step/s, loss=0.025523, elapsed=16.0min]

Entraînement:  50%|████▉     | 4990/10000 [15:59<16:02,  5.21step/s, loss=0.025523, elapsed=16.0min]

Entraînement:  50%|████▉     | 4990/10000 [15:59<16:02,  5.21step/s, loss=0.031688, elapsed=16.0min]

Entraînement:  50%|████▉     | 4991/10000 [15:59<15:58,  5.23step/s, loss=0.031688, elapsed=16.0min]

Entraînement:  50%|████▉     | 4991/10000 [15:59<15:58,  5.23step/s, loss=0.099898, elapsed=16.0min]

Entraînement:  50%|████▉     | 4992/10000 [15:59<15:59,  5.22step/s, loss=0.099898, elapsed=16.0min]

Entraînement:  50%|████▉     | 4992/10000 [15:59<15:59,  5.22step/s, loss=0.038238, elapsed=16.0min]

Entraînement:  50%|████▉     | 4993/10000 [16:00<15:56,  5.23step/s, loss=0.038238, elapsed=16.0min]

Entraînement:  50%|████▉     | 4993/10000 [16:00<15:56,  5.23step/s, loss=0.040654, elapsed=16.0min]

Entraînement:  50%|████▉     | 4994/10000 [16:00<15:52,  5.25step/s, loss=0.040654, elapsed=16.0min]

Entraînement:  50%|████▉     | 4994/10000 [16:00<15:52,  5.25step/s, loss=0.048077, elapsed=16.0min]

Entraînement:  50%|████▉     | 4995/10000 [16:00<15:52,  5.25step/s, loss=0.048077, elapsed=16.0min]

Entraînement:  50%|████▉     | 4995/10000 [16:00<15:52,  5.25step/s, loss=0.083322, elapsed=16.0min]

Entraînement:  50%|████▉     | 4996/10000 [16:00<15:49,  5.27step/s, loss=0.083322, elapsed=16.0min]

Entraînement:  50%|████▉     | 4996/10000 [16:00<15:49,  5.27step/s, loss=0.050306, elapsed=16.0min]

Entraînement:  50%|████▉     | 4997/10000 [16:00<15:47,  5.28step/s, loss=0.050306, elapsed=16.0min]

Entraînement:  50%|████▉     | 4997/10000 [16:00<15:47,  5.28step/s, loss=0.034606, elapsed=16.0min]

Entraînement:  50%|████▉     | 4998/10000 [16:00<15:48,  5.27step/s, loss=0.034606, elapsed=16.0min]

Entraînement:  50%|████▉     | 4998/10000 [16:00<15:48,  5.27step/s, loss=0.095887, elapsed=16.0min]

Entraînement:  50%|████▉     | 4999/10000 [16:01<15:47,  5.28step/s, loss=0.095887, elapsed=16.0min]

Entraînement:  50%|████▉     | 4999/10000 [16:01<15:47,  5.28step/s, loss=0.044611, elapsed=16.0min]

Entraînement:  50%|█████     | 5000/10000 [16:01<15:48,  5.27step/s, loss=0.044611, elapsed=16.0min]

Entraînement:  50%|█████     | 5000/10000 [16:01<15:48,  5.27step/s, loss=0.092367, elapsed=16.0min]

Entraînement:  50%|█████     | 5000/10000 [16:01<15:48,  5.27step/s, loss=0.092367, elapsed=16.0min]

Step 5000/10000 | Train loss: 0.092367 | Elapsed: 16.0min | ETA: 16.0min

Entraînement:  50%|█████     | 5000/10000 [16:03<15:48,  5.27step/s, loss=0.092367, elapsed=16.0min]

Entraînement:  50%|█████     | 5000/10000 [16:03<15:48,  5.27step/s, loss=0.092367, elapsed=16.0min]

Step 5000/10000 | Val loss: 0.041205 | Validation en 1.7s
Meilleur checkpoint sauvegardé : /workspace/DiffWave_Project/checkpoints/diffwave_doda_male/best_checkpoint.pt

Entraînement:  50%|█████     | 5000/10000 [16:03<15:48,  5.27step/s, loss=0.092367, elapsed=16.0min]

Entraînement:  50%|█████     | 5001/10000 [16:03<1:05:48,  1.27step/s, loss=0.092367, elapsed=16.0min]

Entraînement:  50%|█████     | 5001/10000 [16:03<1:05:48,  1.27step/s, loss=0.036444, elapsed=16.1min]

Dernier checkpoint sauvegardé : /workspace/DiffWave_Project/checkpoints/diffwave_doda_male/last_checkpoint.pt

Entraînement:  50%|█████     | 5002/10000 [16:03<50:50,  1.64step/s, loss=0.036444, elapsed=16.1min]

Entraînement:  50%|█████     | 5002/10000 [16:03<50:50,  1.64step/s, loss=0.038981, elapsed=16.1min]

Entraînement:  50%|█████     | 5003/10000 [16:03<40:30,  2.06step/s, loss=0.038981, elapsed=16.1min]

Entraînement:  50%|█████     | 5003/10000 [16:03<40:30,  2.06step/s, loss=0.037765, elapsed=16.1min]

Entraînement:  50%|█████     | 5004/10000 [16:04<33:04,  2.52step/s, loss=0.037765, elapsed=16.1min]

Entraînement:  50%|█████     | 5004/10000 [16:04<33:04,  2.52step/s, loss=0.045965, elapsed=16.1min]

Entraînement:  50%|█████     | 5005/10000 [16:04<27:52,  2.99step/s, loss=0.045965, elapsed=16.1min]

Entraînement:  50%|█████     | 5005/10000 [16:04<27:52,  2.99step/s, loss=0.057494, elapsed=16.1min]

Entraînement:  50%|█████     | 5006/10000 [16:04<24:13,  3.44step/s, loss=0.057494, elapsed=16.1min]

Entraînement:  50%|█████     | 5006/10000 [16:04<24:13,  3.44step/s, loss=0.042064, elapsed=16.1min]

Entraînement:  50%|█████     | 5007/10000 [16:04<21:40,  3.84step/s, loss=0.042064, elapsed=16.1min]

Entraînement:  50%|█████     | 5007/10000 [16:04<21:40,  3.84step/s, loss=0.027980, elapsed=16.1min]

Entraînement:  50%|█████     | 5008/10000 [16:04<19:54,  4.18step/s, loss=0.027980, elapsed=16.1min]

Entraînement:  50%|█████     | 5008/10000 [16:04<19:54,  4.18step/s, loss=0.035789, elapsed=16.1min]

Entraînement:  50%|█████     | 5009/10000 [16:05<18:40,  4.45step/s, loss=0.035789, elapsed=16.1min]

Entraînement:  50%|█████     | 5009/10000 [16:05<18:40,  4.45step/s, loss=0.033056, elapsed=16.1min]

Entraînement:  50%|█████     | 5010/10000 [16:05<17:49,  4.67step/s, loss=0.033056, elapsed=16.1min]

Entraînement:  50%|█████     | 5010/10000 [16:05<17:49,  4.67step/s, loss=0.035361, elapsed=16.1min]

Entraînement:  50%|█████     | 5011/10000 [16:05<17:11,  4.83step/s, loss=0.035361, elapsed=16.1min]

Entraînement:  50%|█████     | 5011/10000 [16:05<17:11,  4.83step/s, loss=0.024821, elapsed=16.1min]

Entraînement:  50%|█████     | 5012/10000 [16:05<16:45,  4.96step/s, loss=0.024821, elapsed=16.1min]

Entraînement:  50%|█████     | 5012/10000 [16:05<16:45,  4.96step/s, loss=0.070054, elapsed=16.1min]

Entraînement:  50%|█████     | 5013/10000 [16:05<16:27,  5.05step/s, loss=0.070054, elapsed=16.1min]

Entraînement:  50%|█████     | 5013/10000 [16:05<16:27,  5.05step/s, loss=0.098281, elapsed=16.1min]

Entraînement:  50%|█████     | 5014/10000 [16:05<16:12,  5.13step/s, loss=0.098281, elapsed=16.1min]

Entraînement:  50%|█████     | 5014/10000 [16:05<16:12,  5.13step/s, loss=0.022914, elapsed=16.1min]

Entraînement:  50%|█████     | 5015/10000 [16:06<16:04,  5.17step/s, loss=0.022914, elapsed=16.1min]

Entraînement:  50%|█████     | 5015/10000 [16:06<16:04,  5.17step/s, loss=0.055721, elapsed=16.1min]

Entraînement:  50%|█████     | 5016/10000 [16:06<15:58,  5.20step/s, loss=0.055721, elapsed=16.1min]

Entraînement:  50%|█████     | 5016/10000 [16:06<15:58,  5.20step/s, loss=0.085548, elapsed=16.1min]

Entraînement:  50%|█████     | 5017/10000 [16:06<15:49,  5.25step/s, loss=0.085548, elapsed=16.1min]

Entraînement:  50%|█████     | 5017/10000 [16:06<15:49,  5.25step/s, loss=0.070865, elapsed=16.1min]

Entraînement:  50%|█████     | 5018/10000 [16:06<15:45,  5.27step/s, loss=0.070865, elapsed=16.1min]

Entraînement:  50%|█████     | 5018/10000 [16:06<15:45,  5.27step/s, loss=0.084304, elapsed=16.1min]

Entraînement:  50%|█████     | 5019/10000 [16:06<15:40,  5.29step/s, loss=0.084304, elapsed=16.1min]

Entraînement:  50%|█████     | 5019/10000 [16:06<15:40,  5.29step/s, loss=0.020672, elapsed=16.1min]

Entraînement:  50%|█████     | 5020/10000 [16:07<15:36,  5.32step/s, loss=0.020672, elapsed=16.1min]

Entraînement:  50%|█████     | 5020/10000 [16:07<15:36,  5.32step/s, loss=0.027056, elapsed=16.1min]

Entraînement:  50%|█████     | 5021/10000 [16:07<15:34,  5.33step/s, loss=0.027056, elapsed=16.1min]

Entraînement:  50%|█████     | 5021/10000 [16:07<15:34,  5.33step/s, loss=0.074714, elapsed=16.1min]

Entraînement:  50%|█████     | 5022/10000 [16:07<15:37,  5.31step/s, loss=0.074714, elapsed=16.1min]

Entraînement:  50%|█████     | 5022/10000 [16:07<15:37,  5.31step/s, loss=0.028035, elapsed=16.1min]

Entraînement:  50%|█████     | 5023/10000 [16:07<15:37,  5.31step/s, loss=0.028035, elapsed=16.1min]

Entraînement:  50%|█████     | 5023/10000 [16:07<15:37,  5.31step/s, loss=0.033433, elapsed=16.1min]

Entraînement:  50%|█████     | 5024/10000 [16:07<15:38,  5.30step/s, loss=0.033433, elapsed=16.1min]

Entraînement:  50%|█████     | 5024/10000 [16:07<15:38,  5.30step/s, loss=0.037728, elapsed=16.1min]

Entraînement:  50%|█████     | 5025/10000 [16:08<15:39,  5.30step/s, loss=0.037728, elapsed=16.1min]

Entraînement:  50%|█████     | 5025/10000 [16:08<15:39,  5.30step/s, loss=0.060839, elapsed=16.1min]

Entraînement:  50%|█████     | 5026/10000 [16:08<15:40,  5.29step/s, loss=0.060839, elapsed=16.1min]

Entraînement:  50%|█████     | 5026/10000 [16:08<15:40,  5.29step/s, loss=0.031188, elapsed=16.1min]

Entraînement:  50%|█████     | 5027/10000 [16:08<15:40,  5.29step/s, loss=0.031188, elapsed=16.1min]

Entraînement:  50%|█████     | 5027/10000 [16:08<15:40,  5.29step/s, loss=0.021068, elapsed=16.1min]

Entraînement:  50%|█████     | 5028/10000 [16:08<15:41,  5.28step/s, loss=0.021068, elapsed=16.1min]

Entraînement:  50%|█████     | 5028/10000 [16:08<15:41,  5.28step/s, loss=0.026542, elapsed=16.1min]

Entraînement:  50%|█████     | 5029/10000 [16:08<15:41,  5.28step/s, loss=0.026542, elapsed=16.1min]

Entraînement:  50%|█████     | 5029/10000 [16:08<15:41,  5.28step/s, loss=0.036365, elapsed=16.1min]

Entraînement:  50%|█████     | 5030/10000 [16:09<15:41,  5.28step/s, loss=0.036365, elapsed=16.1min]

Entraînement:  50%|█████     | 5030/10000 [16:09<15:41,  5.28step/s, loss=0.034194, elapsed=16.2min]

Entraînement:  50%|█████     | 5031/10000 [16:09<15:43,  5.27step/s, loss=0.034194, elapsed=16.2min]

Entraînement:  50%|█████     | 5031/10000 [16:09<15:43,  5.27step/s, loss=0.088325, elapsed=16.2min]

Entraînement:  50%|█████     | 5032/10000 [16:09<15:45,  5.25step/s, loss=0.088325, elapsed=16.2min]

Entraînement:  50%|█████     | 5032/10000 [16:09<15:45,  5.25step/s, loss=0.057201, elapsed=16.2min]

Entraînement:  50%|█████     | 5033/10000 [16:09<15:43,  5.26step/s, loss=0.057201, elapsed=16.2min]

Entraînement:  50%|█████     | 5033/10000 [16:09<15:43,  5.26step/s, loss=0.030280, elapsed=16.2min]

Entraînement:  50%|█████     | 5034/10000 [16:09<15:42,  5.27step/s, loss=0.030280, elapsed=16.2min]

Entraînement:  50%|█████     | 5034/10000 [16:09<15:42,  5.27step/s, loss=0.030290, elapsed=16.2min]

Entraînement:  50%|█████     | 5035/10000 [16:09<15:41,  5.27step/s, loss=0.030290, elapsed=16.2min]

Entraînement:  50%|█████     | 5035/10000 [16:09<15:41,  5.27step/s, loss=0.068823, elapsed=16.2min]

Entraînement:  50%|█████     | 5036/10000 [16:10<15:41,  5.27step/s, loss=0.068823, elapsed=16.2min]

Entraînement:  50%|█████     | 5036/10000 [16:10<15:41,  5.27step/s, loss=0.028215, elapsed=16.2min]

Entraînement:  50%|█████     | 5037/10000 [16:10<15:41,  5.27step/s, loss=0.028215, elapsed=16.2min]

Entraînement:  50%|█████     | 5037/10000 [16:10<15:41,  5.27step/s, loss=0.034976, elapsed=16.2min]

Entraînement:  50%|█████     | 5038/10000 [16:10<15:48,  5.23step/s, loss=0.034976, elapsed=16.2min]

Entraînement:  50%|█████     | 5038/10000 [16:10<15:48,  5.23step/s, loss=0.064186, elapsed=16.2min]

Entraînement:  50%|█████     | 5039/10000 [16:10<15:45,  5.25step/s, loss=0.064186, elapsed=16.2min]

Entraînement:  50%|█████     | 5039/10000 [16:10<15:45,  5.25step/s, loss=0.021417, elapsed=16.2min]

Entraînement:  50%|█████     | 5040/10000 [16:10<15:46,  5.24step/s, loss=0.021417, elapsed=16.2min]

Entraînement:  50%|█████     | 5040/10000 [16:10<15:46,  5.24step/s, loss=0.071531, elapsed=16.2min]

Entraînement:  50%|█████     | 5041/10000 [16:11<15:46,  5.24step/s, loss=0.071531, elapsed=16.2min]

Entraînement:  50%|█████     | 5041/10000 [16:11<15:46,  5.24step/s, loss=0.055704, elapsed=16.2min]

Entraînement:  50%|█████     | 5042/10000 [16:11<15:45,  5.24step/s, loss=0.055704, elapsed=16.2min]

Entraînement:  50%|█████     | 5042/10000 [16:11<15:45,  5.24step/s, loss=0.125906, elapsed=16.2min]

Entraînement:  50%|█████     | 5043/10000 [16:11<15:42,  5.26step/s, loss=0.125906, elapsed=16.2min]

Entraînement:  50%|█████     | 5043/10000 [16:11<15:42,  5.26step/s, loss=0.112404, elapsed=16.2min]

Entraînement:  50%|█████     | 5044/10000 [16:11<15:39,  5.28step/s, loss=0.112404, elapsed=16.2min]

Entraînement:  50%|█████     | 5044/10000 [16:11<15:39,  5.28step/s, loss=0.059116, elapsed=16.2min]

Entraînement:  50%|█████     | 5045/10000 [16:11<15:38,  5.28step/s, loss=0.059116, elapsed=16.2min]

Entraînement:  50%|█████     | 5045/10000 [16:11<15:38,  5.28step/s, loss=0.122235, elapsed=16.2min]

Entraînement:  50%|█████     | 5046/10000 [16:12<15:36,  5.29step/s, loss=0.122235, elapsed=16.2min]

Entraînement:  50%|█████     | 5046/10000 [16:12<15:36,  5.29step/s, loss=0.038059, elapsed=16.2min]

Entraînement:  50%|█████     | 5047/10000 [16:12<15:36,  5.29step/s, loss=0.038059, elapsed=16.2min]

Entraînement:  50%|█████     | 5047/10000 [16:12<15:36,  5.29step/s, loss=0.051653, elapsed=16.2min]

Entraînement:  50%|█████     | 5048/10000 [16:12<15:37,  5.28step/s, loss=0.051653, elapsed=16.2min]

Entraînement:  50%|█████     | 5048/10000 [16:12<15:37,  5.28step/s, loss=0.124006, elapsed=16.2min]

Entraînement:  50%|█████     | 5049/10000 [16:12<15:39,  5.27step/s, loss=0.124006, elapsed=16.2min]

Entraînement:  50%|█████     | 5049/10000 [16:12<15:39,  5.27step/s, loss=0.036232, elapsed=16.2min]

Entraînement:  50%|█████     | 5050/10000 [16:12<15:41,  5.26step/s, loss=0.036232, elapsed=16.2min]

Entraînement:  50%|█████     | 5050/10000 [16:12<15:41,  5.26step/s, loss=0.026216, elapsed=16.2min]

Entraînement:  51%|█████     | 5051/10000 [16:13<15:39,  5.27step/s, loss=0.026216, elapsed=16.2min]

Entraînement:  51%|█████     | 5051/10000 [16:13<15:39,  5.27step/s, loss=0.061842, elapsed=16.2min]

Entraînement:  51%|█████     | 5052/10000 [16:13<15:39,  5.27step/s, loss=0.061842, elapsed=16.2min]

Entraînement:  51%|█████     | 5052/10000 [16:13<15:39,  5.27step/s, loss=0.088197, elapsed=16.2min]

Entraînement:  51%|█████     | 5053/10000 [16:13<15:39,  5.27step/s, loss=0.088197, elapsed=16.2min]

Entraînement:  51%|█████     | 5053/10000 [16:13<15:39,  5.27step/s, loss=0.071182, elapsed=16.2min]

Entraînement:  51%|█████     | 5054/10000 [16:13<15:37,  5.27step/s, loss=0.071182, elapsed=16.2min]

Entraînement:  51%|█████     | 5054/10000 [16:13<15:37,  5.27step/s, loss=0.048799, elapsed=16.2min]

Entraînement:  51%|█████     | 5055/10000 [16:13<15:39,  5.26step/s, loss=0.048799, elapsed=16.2min]

Entraînement:  51%|█████     | 5055/10000 [16:13<15:39,  5.26step/s, loss=0.040530, elapsed=16.2min]

Entraînement:  51%|█████     | 5056/10000 [16:13<15:41,  5.25step/s, loss=0.040530, elapsed=16.2min]

Entraînement:  51%|█████     | 5056/10000 [16:13<15:41,  5.25step/s, loss=0.043118, elapsed=16.2min]

Entraînement:  51%|█████     | 5057/10000 [16:14<15:41,  5.25step/s, loss=0.043118, elapsed=16.2min]

Entraînement:  51%|█████     | 5057/10000 [16:14<15:41,  5.25step/s, loss=0.072799, elapsed=16.2min]

Entraînement:  51%|█████     | 5058/10000 [16:14<15:43,  5.24step/s, loss=0.072799, elapsed=16.2min]

Entraînement:  51%|█████     | 5058/10000 [16:14<15:43,  5.24step/s, loss=0.066766, elapsed=16.2min]

Entraînement:  51%|█████     | 5059/10000 [16:14<15:42,  5.24step/s, loss=0.066766, elapsed=16.2min]

Entraînement:  51%|█████     | 5059/10000 [16:14<15:42,  5.24step/s, loss=0.075295, elapsed=16.2min]

Entraînement:  51%|█████     | 5060/10000 [16:14<15:41,  5.24step/s, loss=0.075295, elapsed=16.2min]

Entraînement:  51%|█████     | 5060/10000 [16:14<15:41,  5.24step/s, loss=0.058667, elapsed=16.2min]

Entraînement:  51%|█████     | 5061/10000 [16:14<15:41,  5.25step/s, loss=0.058667, elapsed=16.2min]

Entraînement:  51%|█████     | 5061/10000 [16:14<15:41,  5.25step/s, loss=0.038561, elapsed=16.2min]

Entraînement:  51%|█████     | 5062/10000 [16:15<15:43,  5.23step/s, loss=0.038561, elapsed=16.2min]

Entraînement:  51%|█████     | 5062/10000 [16:15<15:43,  5.23step/s, loss=0.044524, elapsed=16.3min]

Entraînement:  51%|█████     | 5063/10000 [16:15<15:42,  5.24step/s, loss=0.044524, elapsed=16.3min]

Entraînement:  51%|█████     | 5063/10000 [16:15<15:42,  5.24step/s, loss=0.058488, elapsed=16.3min]

Entraînement:  51%|█████     | 5064/10000 [16:15<15:40,  5.25step/s, loss=0.058488, elapsed=16.3min]

Entraînement:  51%|█████     | 5064/10000 [16:15<15:40,  5.25step/s, loss=0.022320, elapsed=16.3min]

Entraînement:  51%|█████     | 5065/10000 [16:15<15:38,  5.26step/s, loss=0.022320, elapsed=16.3min]

Entraînement:  51%|█████     | 5065/10000 [16:15<15:38,  5.26step/s, loss=0.033043, elapsed=16.3min]

Entraînement:  51%|█████     | 5066/10000 [16:15<15:40,  5.24step/s, loss=0.033043, elapsed=16.3min]

Entraînement:  51%|█████     | 5066/10000 [16:15<15:40,  5.24step/s, loss=0.063050, elapsed=16.3min]

Entraînement:  51%|█████     | 5067/10000 [16:16<15:39,  5.25step/s, loss=0.063050, elapsed=16.3min]

Entraînement:  51%|█████     | 5067/10000 [16:16<15:39,  5.25step/s, loss=0.083675, elapsed=16.3min]

Entraînement:  51%|█████     | 5068/10000 [16:16<15:38,  5.26step/s, loss=0.083675, elapsed=16.3min]

Entraînement:  51%|█████     | 5068/10000 [16:16<15:38,  5.26step/s, loss=0.022419, elapsed=16.3min]

Entraînement:  51%|█████     | 5069/10000 [16:16<15:38,  5.25step/s, loss=0.022419, elapsed=16.3min]

Entraînement:  51%|█████     | 5069/10000 [16:16<15:38,  5.25step/s, loss=0.054539, elapsed=16.3min]

Entraînement:  51%|█████     | 5070/10000 [16:16<15:37,  5.26step/s, loss=0.054539, elapsed=16.3min]

Entraînement:  51%|█████     | 5070/10000 [16:16<15:37,  5.26step/s, loss=0.054844, elapsed=16.3min]

Entraînement:  51%|█████     | 5071/10000 [16:16<15:36,  5.26step/s, loss=0.054844, elapsed=16.3min]

Entraînement:  51%|█████     | 5071/10000 [16:16<15:36,  5.26step/s, loss=0.026082, elapsed=16.3min]

Entraînement:  51%|█████     | 5072/10000 [16:17<15:38,  5.25step/s, loss=0.026082, elapsed=16.3min]

Entraînement:  51%|█████     | 5072/10000 [16:17<15:38,  5.25step/s, loss=0.043285, elapsed=16.3min]

Entraînement:  51%|█████     | 5073/10000 [16:17<15:39,  5.25step/s, loss=0.043285, elapsed=16.3min]

Entraînement:  51%|█████     | 5073/10000 [16:17<15:39,  5.25step/s, loss=0.091638, elapsed=16.3min]

Entraînement:  51%|█████     | 5074/10000 [16:17<15:38,  5.25step/s, loss=0.091638, elapsed=16.3min]

Entraînement:  51%|█████     | 5074/10000 [16:17<15:38,  5.25step/s, loss=0.043317, elapsed=16.3min]

Entraînement:  51%|█████     | 5075/10000 [16:17<15:39,  5.24step/s, loss=0.043317, elapsed=16.3min]

Entraînement:  51%|█████     | 5075/10000 [16:17<15:39,  5.24step/s, loss=0.189203, elapsed=16.3min]

Entraînement:  51%|█████     | 5076/10000 [16:17<15:39,  5.24step/s, loss=0.189203, elapsed=16.3min]

Entraînement:  51%|█████     | 5076/10000 [16:17<15:39,  5.24step/s, loss=0.023863, elapsed=16.3min]

Entraînement:  51%|█████     | 5077/10000 [16:17<15:42,  5.22step/s, loss=0.023863, elapsed=16.3min]

Entraînement:  51%|█████     | 5077/10000 [16:17<15:42,  5.22step/s, loss=0.095582, elapsed=16.3min]

Entraînement:  51%|█████     | 5078/10000 [16:18<15:40,  5.23step/s, loss=0.095582, elapsed=16.3min]

Entraînement:  51%|█████     | 5078/10000 [16:18<15:40,  5.23step/s, loss=0.050486, elapsed=16.3min]

Entraînement:  51%|█████     | 5079/10000 [16:18<15:38,  5.24step/s, loss=0.050486, elapsed=16.3min]

Entraînement:  51%|█████     | 5079/10000 [16:18<15:38,  5.24step/s, loss=0.042833, elapsed=16.3min]

Entraînement:  51%|█████     | 5080/10000 [16:18<15:36,  5.26step/s, loss=0.042833, elapsed=16.3min]

Entraînement:  51%|█████     | 5080/10000 [16:18<15:36,  5.26step/s, loss=0.043018, elapsed=16.3min]

Entraînement:  51%|█████     | 5081/10000 [16:18<15:35,  5.26step/s, loss=0.043018, elapsed=16.3min]

Entraînement:  51%|█████     | 5081/10000 [16:18<15:35,  5.26step/s, loss=0.033795, elapsed=16.3min]

Entraînement:  51%|█████     | 5082/10000 [16:18<15:35,  5.26step/s, loss=0.033795, elapsed=16.3min]

Entraînement:  51%|█████     | 5082/10000 [16:18<15:35,  5.26step/s, loss=0.048620, elapsed=16.3min]

Entraînement:  51%|█████     | 5083/10000 [16:19<15:37,  5.24step/s, loss=0.048620, elapsed=16.3min]

Entraînement:  51%|█████     | 5083/10000 [16:19<15:37,  5.24step/s, loss=0.038173, elapsed=16.3min]

Entraînement:  51%|█████     | 5084/10000 [16:19<15:37,  5.25step/s, loss=0.038173, elapsed=16.3min]

Entraînement:  51%|█████     | 5084/10000 [16:19<15:37,  5.25step/s, loss=0.126480, elapsed=16.3min]

Entraînement:  51%|█████     | 5085/10000 [16:19<15:35,  5.26step/s, loss=0.126480, elapsed=16.3min]

Entraînement:  51%|█████     | 5085/10000 [16:19<15:35,  5.26step/s, loss=0.053598, elapsed=16.3min]

Entraînement:  51%|█████     | 5086/10000 [16:19<15:32,  5.27step/s, loss=0.053598, elapsed=16.3min]

Entraînement:  51%|█████     | 5086/10000 [16:19<15:32,  5.27step/s, loss=0.071445, elapsed=16.3min]

Entraînement:  51%|█████     | 5087/10000 [16:19<15:31,  5.27step/s, loss=0.071445, elapsed=16.3min]

Entraînement:  51%|█████     | 5087/10000 [16:19<15:31,  5.27step/s, loss=0.035397, elapsed=16.3min]

Entraînement:  51%|█████     | 5088/10000 [16:20<15:30,  5.28step/s, loss=0.035397, elapsed=16.3min]

Entraînement:  51%|█████     | 5088/10000 [16:20<15:30,  5.28step/s, loss=0.131816, elapsed=16.3min]

Entraînement:  51%|█████     | 5089/10000 [16:20<15:30,  5.28step/s, loss=0.131816, elapsed=16.3min]

Entraînement:  51%|█████     | 5089/10000 [16:20<15:30,  5.28step/s, loss=0.106572, elapsed=16.3min]

Entraînement:  51%|█████     | 5090/10000 [16:20<15:30,  5.28step/s, loss=0.106572, elapsed=16.3min]

Entraînement:  51%|█████     | 5090/10000 [16:20<15:30,  5.28step/s, loss=0.053006, elapsed=16.3min]

Entraînement:  51%|█████     | 5091/10000 [16:20<15:29,  5.28step/s, loss=0.053006, elapsed=16.3min]

Entraînement:  51%|█████     | 5091/10000 [16:20<15:29,  5.28step/s, loss=0.038434, elapsed=16.3min]

Entraînement:  51%|█████     | 5092/10000 [16:20<15:31,  5.27step/s, loss=0.038434, elapsed=16.3min]

Entraînement:  51%|█████     | 5092/10000 [16:20<15:31,  5.27step/s, loss=0.049781, elapsed=16.3min]

Entraînement:  51%|█████     | 5093/10000 [16:20<15:31,  5.27step/s, loss=0.049781, elapsed=16.3min]

Entraînement:  51%|█████     | 5093/10000 [16:21<15:31,  5.27step/s, loss=0.074743, elapsed=16.4min]

Entraînement:  51%|█████     | 5094/10000 [16:21<15:30,  5.27step/s, loss=0.074743, elapsed=16.4min]

Entraînement:  51%|█████     | 5094/10000 [16:21<15:30,  5.27step/s, loss=0.025695, elapsed=16.4min]

Entraînement:  51%|█████     | 5095/10000 [16:21<15:28,  5.28step/s, loss=0.025695, elapsed=16.4min]

Entraînement:  51%|█████     | 5095/10000 [16:21<15:28,  5.28step/s, loss=0.018664, elapsed=16.4min]

Entraînement:  51%|█████     | 5096/10000 [16:21<15:28,  5.28step/s, loss=0.018664, elapsed=16.4min]

Entraînement:  51%|█████     | 5096/10000 [16:21<15:28,  5.28step/s, loss=0.044211, elapsed=16.4min]

Entraînement:  51%|█████     | 5097/10000 [16:21<15:28,  5.28step/s, loss=0.044211, elapsed=16.4min]

Entraînement:  51%|█████     | 5097/10000 [16:21<15:28,  5.28step/s, loss=0.028366, elapsed=16.4min]

Entraînement:  51%|█████     | 5098/10000 [16:21<15:27,  5.29step/s, loss=0.028366, elapsed=16.4min]

Entraînement:  51%|█████     | 5098/10000 [16:21<15:27,  5.29step/s, loss=0.066600, elapsed=16.4min]

Entraînement:  51%|█████     | 5099/10000 [16:22<15:26,  5.29step/s, loss=0.066600, elapsed=16.4min]

Entraînement:  51%|█████     | 5099/10000 [16:22<15:26,  5.29step/s, loss=0.027295, elapsed=16.4min]

Entraînement:  51%|█████     | 5100/10000 [16:22<15:26,  5.29step/s, loss=0.027295, elapsed=16.4min]

Entraînement:  51%|█████     | 5100/10000 [16:22<15:26,  5.29step/s, loss=0.059385, elapsed=16.4min]

Entraînement:  51%|█████     | 5100/10000 [16:22<15:26,  5.29step/s, loss=0.059385, elapsed=16.4min]

Entraînement:  51%|█████     | 5101/10000 [16:22<15:41,  5.20step/s, loss=0.059385, elapsed=16.4min]

Entraînement:  51%|█████     | 5101/10000 [16:22<15:41,  5.20step/s, loss=0.076660, elapsed=16.4min]

Step 5100/10000 | Train loss: 0.059385 | Elapsed: 16.4min | ETA: 15.7min

Entraînement:  51%|█████     | 5102/10000 [16:22<15:36,  5.23step/s, loss=0.076660, elapsed=16.4min]

Entraînement:  51%|█████     | 5102/10000 [16:22<15:36,  5.23step/s, loss=0.061355, elapsed=16.4min]

Entraînement:  51%|█████     | 5103/10000 [16:22<15:35,  5.24step/s, loss=0.061355, elapsed=16.4min]

Entraînement:  51%|█████     | 5103/10000 [16:22<15:35,  5.24step/s, loss=0.079498, elapsed=16.4min]

Entraînement:  51%|█████     | 5104/10000 [16:23<15:32,  5.25step/s, loss=0.079498, elapsed=16.4min]

Entraînement:  51%|█████     | 5104/10000 [16:23<15:32,  5.25step/s, loss=0.032823, elapsed=16.4min]

Entraînement:  51%|█████     | 5105/10000 [16:23<15:29,  5.27step/s, loss=0.032823, elapsed=16.4min]

Entraînement:  51%|█████     | 5105/10000 [16:23<15:29,  5.27step/s, loss=0.103106, elapsed=16.4min]

Entraînement:  51%|█████     | 5106/10000 [16:23<15:28,  5.27step/s, loss=0.103106, elapsed=16.4min]

Entraînement:  51%|█████     | 5106/10000 [16:23<15:28,  5.27step/s, loss=0.035102, elapsed=16.4min]

Entraînement:  51%|█████     | 5107/10000 [16:23<15:28,  5.27step/s, loss=0.035102, elapsed=16.4min]

Entraînement:  51%|█████     | 5107/10000 [16:23<15:28,  5.27step/s, loss=0.032112, elapsed=16.4min]

Entraînement:  51%|█████     | 5108/10000 [16:23<15:29,  5.26step/s, loss=0.032112, elapsed=16.4min]

Entraînement:  51%|█████     | 5108/10000 [16:23<15:29,  5.26step/s, loss=0.067520, elapsed=16.4min]

Entraînement:  51%|█████     | 5109/10000 [16:24<15:28,  5.27step/s, loss=0.067520, elapsed=16.4min]

Entraînement:  51%|█████     | 5109/10000 [16:24<15:28,  5.27step/s, loss=0.027777, elapsed=16.4min]

Entraînement:  51%|█████     | 5110/10000 [16:24<15:29,  5.26step/s, loss=0.027777, elapsed=16.4min]

Entraînement:  51%|█████     | 5110/10000 [16:24<15:29,  5.26step/s, loss=0.064024, elapsed=16.4min]

Entraînement:  51%|█████     | 5111/10000 [16:24<15:28,  5.27step/s, loss=0.064024, elapsed=16.4min]

Entraînement:  51%|█████     | 5111/10000 [16:24<15:28,  5.27step/s, loss=0.107222, elapsed=16.4min]

Entraînement:  51%|█████     | 5112/10000 [16:24<15:26,  5.27step/s, loss=0.107222, elapsed=16.4min]

Entraînement:  51%|█████     | 5112/10000 [16:24<15:26,  5.27step/s, loss=0.091998, elapsed=16.4min]

Entraînement:  51%|█████     | 5113/10000 [16:24<15:26,  5.28step/s, loss=0.091998, elapsed=16.4min]

Entraînement:  51%|█████     | 5113/10000 [16:24<15:26,  5.28step/s, loss=0.044797, elapsed=16.4min]

Entraînement:  51%|█████     | 5114/10000 [16:24<15:24,  5.28step/s, loss=0.044797, elapsed=16.4min]

Entraînement:  51%|█████     | 5114/10000 [16:24<15:24,  5.28step/s, loss=0.024468, elapsed=16.4min]

Entraînement:  51%|█████     | 5115/10000 [16:25<15:26,  5.27step/s, loss=0.024468, elapsed=16.4min]

Entraînement:  51%|█████     | 5115/10000 [16:25<15:26,  5.27step/s, loss=0.064158, elapsed=16.4min]

Entraînement:  51%|█████     | 5116/10000 [16:25<15:27,  5.27step/s, loss=0.064158, elapsed=16.4min]

Entraînement:  51%|█████     | 5116/10000 [16:25<15:27,  5.27step/s, loss=0.074844, elapsed=16.4min]

Entraînement:  51%|█████     | 5117/10000 [16:25<15:28,  5.26step/s, loss=0.074844, elapsed=16.4min]

Entraînement:  51%|█████     | 5117/10000 [16:25<15:28,  5.26step/s, loss=0.076439, elapsed=16.4min]

Entraînement:  51%|█████     | 5118/10000 [16:25<15:26,  5.27step/s, loss=0.076439, elapsed=16.4min]

Entraînement:  51%|█████     | 5118/10000 [16:25<15:26,  5.27step/s, loss=0.034886, elapsed=16.4min]

Entraînement:  51%|█████     | 5119/10000 [16:25<15:27,  5.26step/s, loss=0.034886, elapsed=16.4min]

Entraînement:  51%|█████     | 5119/10000 [16:25<15:27,  5.26step/s, loss=0.060079, elapsed=16.4min]

Entraînement:  51%|█████     | 5120/10000 [16:26<15:25,  5.27step/s, loss=0.060079, elapsed=16.4min]

Entraînement:  51%|█████     | 5120/10000 [16:26<15:25,  5.27step/s, loss=0.043923, elapsed=16.4min]

Entraînement:  51%|█████     | 5121/10000 [16:26<15:25,  5.27step/s, loss=0.043923, elapsed=16.4min]

Entraînement:  51%|█████     | 5121/10000 [16:26<15:25,  5.27step/s, loss=0.056697, elapsed=16.4min]

Entraînement:  51%|█████     | 5122/10000 [16:26<15:25,  5.27step/s, loss=0.056697, elapsed=16.4min]

Entraînement:  51%|█████     | 5122/10000 [16:26<15:25,  5.27step/s, loss=0.029161, elapsed=16.4min]

Entraînement:  51%|█████     | 5123/10000 [16:26<15:26,  5.26step/s, loss=0.029161, elapsed=16.4min]

Entraînement:  51%|█████     | 5123/10000 [16:26<15:26,  5.26step/s, loss=0.099998, elapsed=16.4min]

Entraînement:  51%|█████     | 5124/10000 [16:26<15:27,  5.26step/s, loss=0.099998, elapsed=16.4min]

Entraînement:  51%|█████     | 5124/10000 [16:26<15:27,  5.26step/s, loss=0.027867, elapsed=16.4min]

Entraînement:  51%|█████▏    | 5125/10000 [16:27<15:27,  5.26step/s, loss=0.027867, elapsed=16.4min]

Entraînement:  51%|█████▏    | 5125/10000 [16:27<15:27,  5.26step/s, loss=0.052590, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5126/10000 [16:27<15:24,  5.27step/s, loss=0.052590, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5126/10000 [16:27<15:24,  5.27step/s, loss=0.019947, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5127/10000 [16:27<15:24,  5.27step/s, loss=0.019947, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5127/10000 [16:27<15:24,  5.27step/s, loss=0.040903, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5128/10000 [16:27<15:23,  5.27step/s, loss=0.040903, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5128/10000 [16:27<15:23,  5.27step/s, loss=0.034450, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5129/10000 [16:27<15:23,  5.28step/s, loss=0.034450, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5129/10000 [16:27<15:23,  5.28step/s, loss=0.024762, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5130/10000 [16:28<15:23,  5.27step/s, loss=0.024762, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5130/10000 [16:28<15:23,  5.27step/s, loss=0.053893, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5131/10000 [16:28<15:22,  5.28step/s, loss=0.053893, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5131/10000 [16:28<15:22,  5.28step/s, loss=0.111740, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5132/10000 [16:28<15:24,  5.27step/s, loss=0.111740, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5132/10000 [16:28<15:24,  5.27step/s, loss=0.115607, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5133/10000 [16:28<15:22,  5.28step/s, loss=0.115607, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5133/10000 [16:28<15:22,  5.28step/s, loss=0.095772, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5134/10000 [16:28<15:23,  5.27step/s, loss=0.095772, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5134/10000 [16:28<15:23,  5.27step/s, loss=0.070782, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5135/10000 [16:28<15:22,  5.27step/s, loss=0.070782, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5135/10000 [16:28<15:22,  5.27step/s, loss=0.033335, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5136/10000 [16:29<15:25,  5.26step/s, loss=0.033335, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5136/10000 [16:29<15:25,  5.26step/s, loss=0.039714, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5137/10000 [16:29<15:24,  5.26step/s, loss=0.039714, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5137/10000 [16:29<15:24,  5.26step/s, loss=0.083505, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5138/10000 [16:29<15:25,  5.25step/s, loss=0.083505, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5138/10000 [16:29<15:25,  5.25step/s, loss=0.039381, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5139/10000 [16:29<15:25,  5.25step/s, loss=0.039381, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5139/10000 [16:29<15:25,  5.25step/s, loss=0.053390, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5140/10000 [16:29<15:26,  5.25step/s, loss=0.053390, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5140/10000 [16:29<15:26,  5.25step/s, loss=0.029771, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5141/10000 [16:30<15:24,  5.26step/s, loss=0.029771, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5141/10000 [16:30<15:24,  5.26step/s, loss=0.039508, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5142/10000 [16:30<15:23,  5.26step/s, loss=0.039508, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5142/10000 [16:30<15:23,  5.26step/s, loss=0.027305, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5143/10000 [16:30<15:23,  5.26step/s, loss=0.027305, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5143/10000 [16:30<15:23,  5.26step/s, loss=0.039055, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5144/10000 [16:30<15:23,  5.26step/s, loss=0.039055, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5144/10000 [16:30<15:23,  5.26step/s, loss=0.058963, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5145/10000 [16:30<15:23,  5.26step/s, loss=0.058963, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5145/10000 [16:30<15:23,  5.26step/s, loss=0.034253, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5146/10000 [16:31<15:23,  5.26step/s, loss=0.034253, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5146/10000 [16:31<15:23,  5.26step/s, loss=0.045607, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5147/10000 [16:31<15:23,  5.26step/s, loss=0.045607, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5147/10000 [16:31<15:23,  5.26step/s, loss=0.046306, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5148/10000 [16:31<15:23,  5.25step/s, loss=0.046306, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5148/10000 [16:31<15:23,  5.25step/s, loss=0.035728, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5149/10000 [16:31<15:21,  5.27step/s, loss=0.035728, elapsed=16.5min]

Entraînement:  51%|█████▏    | 5149/10000 [16:31<15:21,  5.27step/s, loss=0.036777, elapsed=16.5min]

Entraînement:  52%|█████▏    | 5150/10000 [16:31<15:21,  5.26step/s, loss=0.036777, elapsed=16.5min]

Entraînement:  52%|█████▏    | 5150/10000 [16:31<15:21,  5.26step/s, loss=0.098958, elapsed=16.5min]

Entraînement:  52%|█████▏    | 5151/10000 [16:32<15:24,  5.25step/s, loss=0.098958, elapsed=16.5min]

Entraînement:  52%|█████▏    | 5151/10000 [16:32<15:24,  5.25step/s, loss=0.030582, elapsed=16.5min]

Entraînement:  52%|█████▏    | 5152/10000 [16:32<15:28,  5.22step/s, loss=0.030582, elapsed=16.5min]

Entraînement:  52%|█████▏    | 5152/10000 [16:32<15:28,  5.22step/s, loss=0.036565, elapsed=16.5min]

Entraînement:  52%|█████▏    | 5153/10000 [16:32<15:29,  5.21step/s, loss=0.036565, elapsed=16.5min]

Entraînement:  52%|█████▏    | 5153/10000 [16:32<15:29,  5.21step/s, loss=0.030262, elapsed=16.5min]

Entraînement:  52%|█████▏    | 5154/10000 [16:32<15:29,  5.21step/s, loss=0.030262, elapsed=16.5min]

Entraînement:  52%|█████▏    | 5154/10000 [16:32<15:29,  5.21step/s, loss=0.089043, elapsed=16.5min]

Entraînement:  52%|█████▏    | 5155/10000 [16:32<15:27,  5.22step/s, loss=0.089043, elapsed=16.5min]

Entraînement:  52%|█████▏    | 5155/10000 [16:32<15:27,  5.22step/s, loss=0.070100, elapsed=16.5min]

Entraînement:  52%|█████▏    | 5156/10000 [16:32<15:25,  5.24step/s, loss=0.070100, elapsed=16.5min]

Entraînement:  52%|█████▏    | 5156/10000 [16:32<15:25,  5.24step/s, loss=0.041632, elapsed=16.5min]

Entraînement:  52%|█████▏    | 5157/10000 [16:33<15:21,  5.26step/s, loss=0.041632, elapsed=16.5min]

Entraînement:  52%|█████▏    | 5157/10000 [16:33<15:21,  5.26step/s, loss=0.030961, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5158/10000 [16:33<15:19,  5.26step/s, loss=0.030961, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5158/10000 [16:33<15:19,  5.26step/s, loss=0.038780, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5159/10000 [16:33<15:17,  5.28step/s, loss=0.038780, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5159/10000 [16:33<15:17,  5.28step/s, loss=0.041157, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5160/10000 [16:33<15:17,  5.28step/s, loss=0.041157, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5160/10000 [16:33<15:17,  5.28step/s, loss=0.042785, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5161/10000 [16:33<15:18,  5.27step/s, loss=0.042785, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5161/10000 [16:33<15:18,  5.27step/s, loss=0.039988, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5162/10000 [16:34<15:18,  5.27step/s, loss=0.039988, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5162/10000 [16:34<15:18,  5.27step/s, loss=0.026511, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5163/10000 [16:34<15:17,  5.27step/s, loss=0.026511, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5163/10000 [16:34<15:17,  5.27step/s, loss=0.030442, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5164/10000 [16:34<15:16,  5.28step/s, loss=0.030442, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5164/10000 [16:34<15:16,  5.28step/s, loss=0.027931, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5165/10000 [16:34<15:16,  5.28step/s, loss=0.027931, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5165/10000 [16:34<15:16,  5.28step/s, loss=0.030548, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5166/10000 [16:34<15:15,  5.28step/s, loss=0.030548, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5166/10000 [16:34<15:15,  5.28step/s, loss=0.093146, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5167/10000 [16:35<15:15,  5.28step/s, loss=0.093146, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5167/10000 [16:35<15:15,  5.28step/s, loss=0.027189, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5168/10000 [16:35<15:15,  5.28step/s, loss=0.027189, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5168/10000 [16:35<15:15,  5.28step/s, loss=0.103479, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5169/10000 [16:35<15:15,  5.28step/s, loss=0.103479, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5169/10000 [16:35<15:15,  5.28step/s, loss=0.028160, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5170/10000 [16:35<15:17,  5.27step/s, loss=0.028160, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5170/10000 [16:35<15:17,  5.27step/s, loss=0.074096, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5171/10000 [16:35<15:16,  5.27step/s, loss=0.074096, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5171/10000 [16:35<15:16,  5.27step/s, loss=0.021781, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5172/10000 [16:36<15:16,  5.27step/s, loss=0.021781, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5172/10000 [16:36<15:16,  5.27step/s, loss=0.032904, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5173/10000 [16:36<15:15,  5.27step/s, loss=0.032904, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5173/10000 [16:36<15:15,  5.27step/s, loss=0.130767, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5174/10000 [16:36<15:13,  5.28step/s, loss=0.130767, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5174/10000 [16:36<15:13,  5.28step/s, loss=0.073071, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5175/10000 [16:36<15:13,  5.28step/s, loss=0.073071, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5175/10000 [16:36<15:13,  5.28step/s, loss=0.037813, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5176/10000 [16:36<15:13,  5.28step/s, loss=0.037813, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5176/10000 [16:36<15:13,  5.28step/s, loss=0.026826, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5177/10000 [16:36<15:15,  5.27step/s, loss=0.026826, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5177/10000 [16:36<15:15,  5.27step/s, loss=0.023987, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5178/10000 [16:37<15:13,  5.28step/s, loss=0.023987, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5178/10000 [16:37<15:13,  5.28step/s, loss=0.049468, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5179/10000 [16:37<15:14,  5.27step/s, loss=0.049468, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5179/10000 [16:37<15:14,  5.27step/s, loss=0.048214, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5180/10000 [16:37<15:13,  5.27step/s, loss=0.048214, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5180/10000 [16:37<15:13,  5.27step/s, loss=0.134500, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5181/10000 [16:37<15:24,  5.21step/s, loss=0.134500, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5181/10000 [16:37<15:24,  5.21step/s, loss=0.046343, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5182/10000 [16:37<15:21,  5.23step/s, loss=0.046343, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5182/10000 [16:37<15:21,  5.23step/s, loss=0.022884, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5183/10000 [16:38<15:22,  5.22step/s, loss=0.022884, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5183/10000 [16:38<15:22,  5.22step/s, loss=0.028528, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5184/10000 [16:38<15:18,  5.24step/s, loss=0.028528, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5184/10000 [16:38<15:18,  5.24step/s, loss=0.030303, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5185/10000 [16:38<15:17,  5.25step/s, loss=0.030303, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5185/10000 [16:38<15:17,  5.25step/s, loss=0.036772, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5186/10000 [16:38<15:19,  5.24step/s, loss=0.036772, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5186/10000 [16:38<15:19,  5.24step/s, loss=0.046441, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5187/10000 [16:38<15:18,  5.24step/s, loss=0.046441, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5187/10000 [16:38<15:18,  5.24step/s, loss=0.025599, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5188/10000 [16:39<15:14,  5.26step/s, loss=0.025599, elapsed=16.6min]

Entraînement:  52%|█████▏    | 5188/10000 [16:39<15:14,  5.26step/s, loss=0.023992, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5189/10000 [16:39<15:12,  5.27step/s, loss=0.023992, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5189/10000 [16:39<15:12,  5.27step/s, loss=0.040798, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5190/10000 [16:39<15:14,  5.26step/s, loss=0.040798, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5190/10000 [16:39<15:14,  5.26step/s, loss=0.077496, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5191/10000 [16:39<15:12,  5.27step/s, loss=0.077496, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5191/10000 [16:39<15:12,  5.27step/s, loss=0.035817, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5192/10000 [16:39<15:14,  5.26step/s, loss=0.035817, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5192/10000 [16:39<15:14,  5.26step/s, loss=0.059913, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5193/10000 [16:40<15:13,  5.26step/s, loss=0.059913, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5193/10000 [16:40<15:13,  5.26step/s, loss=0.023227, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5194/10000 [16:40<15:12,  5.26step/s, loss=0.023227, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5194/10000 [16:40<15:12,  5.26step/s, loss=0.041942, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5195/10000 [16:40<15:13,  5.26step/s, loss=0.041942, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5195/10000 [16:40<15:13,  5.26step/s, loss=0.042211, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5196/10000 [16:40<15:13,  5.26step/s, loss=0.042211, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5196/10000 [16:40<15:13,  5.26step/s, loss=0.053783, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5197/10000 [16:40<15:11,  5.27step/s, loss=0.053783, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5197/10000 [16:40<15:11,  5.27step/s, loss=0.055197, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5198/10000 [16:40<15:11,  5.27step/s, loss=0.055197, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5198/10000 [16:40<15:11,  5.27step/s, loss=0.023989, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5199/10000 [16:41<15:12,  5.26step/s, loss=0.023989, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5199/10000 [16:41<15:12,  5.26step/s, loss=0.035244, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5200/10000 [16:41<15:12,  5.26step/s, loss=0.035244, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5200/10000 [16:41<15:12,  5.26step/s, loss=0.039430, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5200/10000 [16:41<15:12,  5.26step/s, loss=0.039430, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5201/10000 [16:41<15:20,  5.21step/s, loss=0.039430, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5201/10000 [16:41<15:20,  5.21step/s, loss=0.030784, elapsed=16.7min]

Step 5200/10000 | Train loss: 0.039430 | Elapsed: 16.7min | ETA: 15.4min

Entraînement:  52%|█████▏    | 5202/10000 [16:41<15:14,  5.25step/s, loss=0.030784, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5202/10000 [16:41<15:14,  5.25step/s, loss=0.085757, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5203/10000 [16:41<15:12,  5.26step/s, loss=0.085757, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5203/10000 [16:41<15:12,  5.26step/s, loss=0.056930, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5204/10000 [16:42<15:10,  5.27step/s, loss=0.056930, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5204/10000 [16:42<15:10,  5.27step/s, loss=0.026072, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5205/10000 [16:42<15:09,  5.27step/s, loss=0.026072, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5205/10000 [16:42<15:09,  5.27step/s, loss=0.029625, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5206/10000 [16:42<15:09,  5.27step/s, loss=0.029625, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5206/10000 [16:42<15:09,  5.27step/s, loss=0.121990, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5207/10000 [16:42<15:11,  5.26step/s, loss=0.121990, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5207/10000 [16:42<15:11,  5.26step/s, loss=0.023998, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5208/10000 [16:42<15:10,  5.26step/s, loss=0.023998, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5208/10000 [16:42<15:10,  5.26step/s, loss=0.047488, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5209/10000 [16:43<15:09,  5.27step/s, loss=0.047488, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5209/10000 [16:43<15:09,  5.27step/s, loss=0.030165, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5210/10000 [16:43<15:04,  5.29step/s, loss=0.030165, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5210/10000 [16:43<15:04,  5.29step/s, loss=0.023803, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5211/10000 [16:43<15:00,  5.32step/s, loss=0.023803, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5211/10000 [16:43<15:00,  5.32step/s, loss=0.032332, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5212/10000 [16:43<14:58,  5.33step/s, loss=0.032332, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5212/10000 [16:43<14:58,  5.33step/s, loss=0.022050, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5213/10000 [16:43<14:58,  5.33step/s, loss=0.022050, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5213/10000 [16:43<14:58,  5.33step/s, loss=0.035536, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5214/10000 [16:43<15:01,  5.31step/s, loss=0.035536, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5214/10000 [16:43<15:01,  5.31step/s, loss=0.030718, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5215/10000 [16:44<15:03,  5.29step/s, loss=0.030718, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5215/10000 [16:44<15:03,  5.29step/s, loss=0.083955, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5216/10000 [16:44<15:07,  5.27step/s, loss=0.083955, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5216/10000 [16:44<15:07,  5.27step/s, loss=0.041585, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5217/10000 [16:44<15:06,  5.28step/s, loss=0.041585, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5217/10000 [16:44<15:06,  5.28step/s, loss=0.030898, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5218/10000 [16:44<15:03,  5.29step/s, loss=0.030898, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5218/10000 [16:44<15:03,  5.29step/s, loss=0.048934, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5219/10000 [16:44<15:04,  5.29step/s, loss=0.048934, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5219/10000 [16:44<15:04,  5.29step/s, loss=0.027308, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5220/10000 [16:45<15:04,  5.29step/s, loss=0.027308, elapsed=16.7min]

Entraînement:  52%|█████▏    | 5220/10000 [16:45<15:04,  5.29step/s, loss=0.073924, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5221/10000 [16:45<15:03,  5.29step/s, loss=0.073924, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5221/10000 [16:45<15:03,  5.29step/s, loss=0.095452, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5222/10000 [16:45<15:03,  5.29step/s, loss=0.095452, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5222/10000 [16:45<15:03,  5.29step/s, loss=0.044058, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5223/10000 [16:45<15:02,  5.30step/s, loss=0.044058, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5223/10000 [16:45<15:02,  5.30step/s, loss=0.056270, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5224/10000 [16:45<15:04,  5.28step/s, loss=0.056270, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5224/10000 [16:45<15:04,  5.28step/s, loss=0.046512, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5225/10000 [16:46<15:02,  5.29step/s, loss=0.046512, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5225/10000 [16:46<15:02,  5.29step/s, loss=0.045719, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5226/10000 [16:46<15:03,  5.28step/s, loss=0.045719, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5226/10000 [16:46<15:03,  5.28step/s, loss=0.042357, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5227/10000 [16:46<15:02,  5.29step/s, loss=0.042357, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5227/10000 [16:46<15:02,  5.29step/s, loss=0.036536, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5228/10000 [16:46<15:02,  5.29step/s, loss=0.036536, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5228/10000 [16:46<15:02,  5.29step/s, loss=0.032185, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5229/10000 [16:46<15:02,  5.29step/s, loss=0.032185, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5229/10000 [16:46<15:02,  5.29step/s, loss=0.046705, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5230/10000 [16:47<15:01,  5.29step/s, loss=0.046705, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5230/10000 [16:47<15:01,  5.29step/s, loss=0.036819, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5231/10000 [16:47<15:02,  5.28step/s, loss=0.036819, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5231/10000 [16:47<15:02,  5.28step/s, loss=0.070959, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5232/10000 [16:47<15:02,  5.29step/s, loss=0.070959, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5232/10000 [16:47<15:02,  5.29step/s, loss=0.075688, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5233/10000 [16:47<15:03,  5.28step/s, loss=0.075688, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5233/10000 [16:47<15:03,  5.28step/s, loss=0.039431, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5234/10000 [16:47<15:01,  5.28step/s, loss=0.039431, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5234/10000 [16:47<15:01,  5.28step/s, loss=0.052417, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5235/10000 [16:47<15:00,  5.29step/s, loss=0.052417, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5235/10000 [16:47<15:00,  5.29step/s, loss=0.033987, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5236/10000 [16:48<15:01,  5.29step/s, loss=0.033987, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5236/10000 [16:48<15:01,  5.29step/s, loss=0.057091, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5237/10000 [16:48<15:00,  5.29step/s, loss=0.057091, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5237/10000 [16:48<15:00,  5.29step/s, loss=0.057338, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5238/10000 [16:48<14:59,  5.30step/s, loss=0.057338, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5238/10000 [16:48<14:59,  5.30step/s, loss=0.041659, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5239/10000 [16:48<15:02,  5.28step/s, loss=0.041659, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5239/10000 [16:48<15:02,  5.28step/s, loss=0.066937, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5240/10000 [16:48<15:03,  5.27step/s, loss=0.066937, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5240/10000 [16:48<15:03,  5.27step/s, loss=0.041147, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5241/10000 [16:49<15:04,  5.26step/s, loss=0.041147, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5241/10000 [16:49<15:04,  5.26step/s, loss=0.066814, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5242/10000 [16:49<15:02,  5.27step/s, loss=0.066814, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5242/10000 [16:49<15:02,  5.27step/s, loss=0.045027, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5243/10000 [16:49<14:59,  5.29step/s, loss=0.045027, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5243/10000 [16:49<14:59,  5.29step/s, loss=0.085817, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5244/10000 [16:49<15:00,  5.28step/s, loss=0.085817, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5244/10000 [16:49<15:00,  5.28step/s, loss=0.110556, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5245/10000 [16:49<14:59,  5.29step/s, loss=0.110556, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5245/10000 [16:49<14:59,  5.29step/s, loss=0.040301, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5246/10000 [16:50<14:59,  5.28step/s, loss=0.040301, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5246/10000 [16:50<14:59,  5.28step/s, loss=0.053533, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5247/10000 [16:50<15:01,  5.27step/s, loss=0.053533, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5247/10000 [16:50<15:01,  5.27step/s, loss=0.054838, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5248/10000 [16:50<15:03,  5.26step/s, loss=0.054838, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5248/10000 [16:50<15:03,  5.26step/s, loss=0.045812, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5249/10000 [16:50<15:03,  5.26step/s, loss=0.045812, elapsed=16.8min]

Entraînement:  52%|█████▏    | 5249/10000 [16:50<15:03,  5.26step/s, loss=0.061285, elapsed=16.8min]

Entraînement:  52%|█████▎    | 5250/10000 [16:50<15:02,  5.27step/s, loss=0.061285, elapsed=16.8min]

Entraînement:  52%|█████▎    | 5250/10000 [16:50<15:02,  5.27step/s, loss=0.156118, elapsed=16.8min]

Entraînement:  53%|█████▎    | 5251/10000 [16:50<15:01,  5.27step/s, loss=0.156118, elapsed=16.8min]

Entraînement:  53%|█████▎    | 5251/10000 [16:50<15:01,  5.27step/s, loss=0.079930, elapsed=16.8min]

Entraînement:  53%|█████▎    | 5252/10000 [16:51<14:59,  5.28step/s, loss=0.079930, elapsed=16.8min]

Entraînement:  53%|█████▎    | 5252/10000 [16:51<14:59,  5.28step/s, loss=0.065605, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5253/10000 [16:51<14:58,  5.28step/s, loss=0.065605, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5253/10000 [16:51<14:58,  5.28step/s, loss=0.118006, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5254/10000 [16:51<14:57,  5.29step/s, loss=0.118006, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5254/10000 [16:51<14:57,  5.29step/s, loss=0.045836, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5255/10000 [16:51<14:56,  5.29step/s, loss=0.045836, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5255/10000 [16:51<14:56,  5.29step/s, loss=0.045787, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5256/10000 [16:51<14:56,  5.29step/s, loss=0.045787, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5256/10000 [16:51<14:56,  5.29step/s, loss=0.048074, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5257/10000 [16:52<14:54,  5.30step/s, loss=0.048074, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5257/10000 [16:52<14:54,  5.30step/s, loss=0.031533, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5258/10000 [16:52<14:53,  5.31step/s, loss=0.031533, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5258/10000 [16:52<14:53,  5.31step/s, loss=0.078306, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5259/10000 [16:52<14:54,  5.30step/s, loss=0.078306, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5259/10000 [16:52<14:54,  5.30step/s, loss=0.061935, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5260/10000 [16:52<14:54,  5.30step/s, loss=0.061935, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5260/10000 [16:52<14:54,  5.30step/s, loss=0.055651, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5261/10000 [16:52<14:53,  5.30step/s, loss=0.055651, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5261/10000 [16:52<14:53,  5.30step/s, loss=0.026552, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5262/10000 [16:53<14:57,  5.28step/s, loss=0.026552, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5262/10000 [16:53<14:57,  5.28step/s, loss=0.028349, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5263/10000 [16:53<14:56,  5.29step/s, loss=0.028349, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5263/10000 [16:53<14:56,  5.29step/s, loss=0.060298, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5264/10000 [16:53<14:58,  5.27step/s, loss=0.060298, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5264/10000 [16:53<14:58,  5.27step/s, loss=0.056861, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5265/10000 [16:53<14:58,  5.27step/s, loss=0.056861, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5265/10000 [16:53<14:58,  5.27step/s, loss=0.063497, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5266/10000 [16:53<15:03,  5.24step/s, loss=0.063497, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5266/10000 [16:53<15:03,  5.24step/s, loss=0.026383, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5267/10000 [16:54<15:01,  5.25step/s, loss=0.026383, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5267/10000 [16:54<15:01,  5.25step/s, loss=0.038611, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5268/10000 [16:54<15:01,  5.25step/s, loss=0.038611, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5268/10000 [16:54<15:01,  5.25step/s, loss=0.070307, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5269/10000 [16:54<15:00,  5.26step/s, loss=0.070307, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5269/10000 [16:54<15:00,  5.26step/s, loss=0.035354, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5270/10000 [16:54<15:00,  5.25step/s, loss=0.035354, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5270/10000 [16:54<15:00,  5.25step/s, loss=0.066073, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5271/10000 [16:54<15:00,  5.25step/s, loss=0.066073, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5271/10000 [16:54<15:00,  5.25step/s, loss=0.053655, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5272/10000 [16:54<15:01,  5.25step/s, loss=0.053655, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5272/10000 [16:54<15:01,  5.25step/s, loss=0.028870, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5273/10000 [16:55<14:58,  5.26step/s, loss=0.028870, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5273/10000 [16:55<14:58,  5.26step/s, loss=0.045376, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5274/10000 [16:55<14:58,  5.26step/s, loss=0.045376, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5274/10000 [16:55<14:58,  5.26step/s, loss=0.043020, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5275/10000 [16:55<14:56,  5.27step/s, loss=0.043020, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5275/10000 [16:55<14:56,  5.27step/s, loss=0.044548, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5276/10000 [16:55<14:54,  5.28step/s, loss=0.044548, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5276/10000 [16:55<14:54,  5.28step/s, loss=0.106248, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5277/10000 [16:55<14:54,  5.28step/s, loss=0.106248, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5277/10000 [16:55<14:54,  5.28step/s, loss=0.085606, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5278/10000 [16:56<14:54,  5.28step/s, loss=0.085606, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5278/10000 [16:56<14:54,  5.28step/s, loss=0.110419, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5279/10000 [16:56<14:55,  5.27step/s, loss=0.110419, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5279/10000 [16:56<14:55,  5.27step/s, loss=0.033988, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5280/10000 [16:56<14:54,  5.27step/s, loss=0.033988, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5280/10000 [16:56<14:54,  5.27step/s, loss=0.029514, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5281/10000 [16:56<14:53,  5.28step/s, loss=0.029514, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5281/10000 [16:56<14:53,  5.28step/s, loss=0.053318, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5282/10000 [16:56<14:54,  5.27step/s, loss=0.053318, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5282/10000 [16:56<14:54,  5.27step/s, loss=0.078585, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5283/10000 [16:57<14:53,  5.28step/s, loss=0.078585, elapsed=16.9min]

Entraînement:  53%|█████▎    | 5283/10000 [16:57<14:53,  5.28step/s, loss=0.030871, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5284/10000 [16:57<14:52,  5.29step/s, loss=0.030871, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5284/10000 [16:57<14:52,  5.29step/s, loss=0.054361, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5285/10000 [16:57<14:52,  5.28step/s, loss=0.054361, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5285/10000 [16:57<14:52,  5.28step/s, loss=0.034048, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5286/10000 [16:57<14:53,  5.28step/s, loss=0.034048, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5286/10000 [16:57<14:53,  5.28step/s, loss=0.152521, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5287/10000 [16:57<14:53,  5.28step/s, loss=0.152521, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5287/10000 [16:57<14:53,  5.28step/s, loss=0.022755, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5288/10000 [16:57<14:52,  5.28step/s, loss=0.022755, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5288/10000 [16:58<14:52,  5.28step/s, loss=0.052766, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5289/10000 [16:58<14:52,  5.28step/s, loss=0.052766, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5289/10000 [16:58<14:52,  5.28step/s, loss=0.066706, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5290/10000 [16:58<14:53,  5.27step/s, loss=0.066706, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5290/10000 [16:58<14:53,  5.27step/s, loss=0.030377, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5291/10000 [16:58<14:51,  5.28step/s, loss=0.030377, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5291/10000 [16:58<14:51,  5.28step/s, loss=0.024849, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5292/10000 [16:58<14:52,  5.28step/s, loss=0.024849, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5292/10000 [16:58<14:52,  5.28step/s, loss=0.030888, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5293/10000 [16:58<14:51,  5.28step/s, loss=0.030888, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5293/10000 [16:58<14:51,  5.28step/s, loss=0.042552, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5294/10000 [16:59<14:52,  5.27step/s, loss=0.042552, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5294/10000 [16:59<14:52,  5.27step/s, loss=0.047176, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5295/10000 [16:59<14:52,  5.27step/s, loss=0.047176, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5295/10000 [16:59<14:52,  5.27step/s, loss=0.057263, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5296/10000 [16:59<14:52,  5.27step/s, loss=0.057263, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5296/10000 [16:59<14:52,  5.27step/s, loss=0.044959, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5297/10000 [16:59<14:51,  5.28step/s, loss=0.044959, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5297/10000 [16:59<14:51,  5.28step/s, loss=0.031687, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5298/10000 [16:59<14:51,  5.27step/s, loss=0.031687, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5298/10000 [16:59<14:51,  5.27step/s, loss=0.066352, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5299/10000 [17:00<14:51,  5.27step/s, loss=0.066352, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5299/10000 [17:00<14:51,  5.27step/s, loss=0.019739, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5300/10000 [17:00<14:49,  5.28step/s, loss=0.019739, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5300/10000 [17:00<14:49,  5.28step/s, loss=0.069913, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5300/10000 [17:00<14:49,  5.28step/s, loss=0.069913, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5301/10000 [17:00<14:59,  5.23step/s, loss=0.069913, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5301/10000 [17:00<14:59,  5.23step/s, loss=0.038463, elapsed=17.0min]

Step 5300/10000 | Train loss: 0.069913 | Elapsed: 17.0min | ETA: 15.1min

Entraînement:  53%|█████▎    | 5302/10000 [17:00<14:58,  5.23step/s, loss=0.038463, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5302/10000 [17:00<14:58,  5.23step/s, loss=0.075646, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5303/10000 [17:00<14:53,  5.25step/s, loss=0.075646, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5303/10000 [17:00<14:53,  5.25step/s, loss=0.053104, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5304/10000 [17:01<14:51,  5.27step/s, loss=0.053104, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5304/10000 [17:01<14:51,  5.27step/s, loss=0.037632, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5305/10000 [17:01<14:50,  5.27step/s, loss=0.037632, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5305/10000 [17:01<14:50,  5.27step/s, loss=0.023315, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5306/10000 [17:01<14:48,  5.28step/s, loss=0.023315, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5306/10000 [17:01<14:48,  5.28step/s, loss=0.034013, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5307/10000 [17:01<14:47,  5.29step/s, loss=0.034013, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5307/10000 [17:01<14:47,  5.29step/s, loss=0.058332, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5308/10000 [17:01<14:47,  5.29step/s, loss=0.058332, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5308/10000 [17:01<14:47,  5.29step/s, loss=0.045164, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5309/10000 [17:01<14:48,  5.28step/s, loss=0.045164, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5309/10000 [17:01<14:48,  5.28step/s, loss=0.102765, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5310/10000 [17:02<14:48,  5.28step/s, loss=0.102765, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5310/10000 [17:02<14:48,  5.28step/s, loss=0.045609, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5311/10000 [17:02<14:47,  5.28step/s, loss=0.045609, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5311/10000 [17:02<14:47,  5.28step/s, loss=0.031194, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5312/10000 [17:02<14:46,  5.29step/s, loss=0.031194, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5312/10000 [17:02<14:46,  5.29step/s, loss=0.073677, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5313/10000 [17:02<14:46,  5.29step/s, loss=0.073677, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5313/10000 [17:02<14:46,  5.29step/s, loss=0.054169, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5314/10000 [17:02<14:45,  5.29step/s, loss=0.054169, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5314/10000 [17:02<14:45,  5.29step/s, loss=0.114320, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5315/10000 [17:03<14:45,  5.29step/s, loss=0.114320, elapsed=17.0min]

Entraînement:  53%|█████▎    | 5315/10000 [17:03<14:45,  5.29step/s, loss=0.082061, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5316/10000 [17:03<14:45,  5.29step/s, loss=0.082061, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5316/10000 [17:03<14:45,  5.29step/s, loss=0.044816, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5317/10000 [17:03<14:46,  5.29step/s, loss=0.044816, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5317/10000 [17:03<14:46,  5.29step/s, loss=0.089058, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5318/10000 [17:03<14:45,  5.28step/s, loss=0.089058, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5318/10000 [17:03<14:45,  5.28step/s, loss=0.088819, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5319/10000 [17:03<14:44,  5.29step/s, loss=0.088819, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5319/10000 [17:03<14:44,  5.29step/s, loss=0.075546, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5320/10000 [17:04<14:44,  5.29step/s, loss=0.075546, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5320/10000 [17:04<14:44,  5.29step/s, loss=0.046366, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5321/10000 [17:04<14:43,  5.30step/s, loss=0.046366, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5321/10000 [17:04<14:43,  5.30step/s, loss=0.053137, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5322/10000 [17:04<14:43,  5.30step/s, loss=0.053137, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5322/10000 [17:04<14:43,  5.30step/s, loss=0.165151, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5323/10000 [17:04<14:43,  5.30step/s, loss=0.165151, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5323/10000 [17:04<14:43,  5.30step/s, loss=0.030132, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5324/10000 [17:04<14:41,  5.30step/s, loss=0.030132, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5324/10000 [17:04<14:41,  5.30step/s, loss=0.054435, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5325/10000 [17:05<14:43,  5.29step/s, loss=0.054435, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5325/10000 [17:05<14:43,  5.29step/s, loss=0.041968, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5326/10000 [17:05<14:42,  5.30step/s, loss=0.041968, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5326/10000 [17:05<14:42,  5.30step/s, loss=0.027179, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5327/10000 [17:05<14:41,  5.30step/s, loss=0.027179, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5327/10000 [17:05<14:41,  5.30step/s, loss=0.025699, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5328/10000 [17:05<14:37,  5.32step/s, loss=0.025699, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5328/10000 [17:05<14:37,  5.32step/s, loss=0.137814, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5329/10000 [17:05<14:38,  5.32step/s, loss=0.137814, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5329/10000 [17:05<14:38,  5.32step/s, loss=0.033656, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5330/10000 [17:05<14:38,  5.31step/s, loss=0.033656, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5330/10000 [17:05<14:38,  5.31step/s, loss=0.040666, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5331/10000 [17:06<14:38,  5.32step/s, loss=0.040666, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5331/10000 [17:06<14:38,  5.32step/s, loss=0.021070, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5332/10000 [17:06<14:39,  5.31step/s, loss=0.021070, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5332/10000 [17:06<14:39,  5.31step/s, loss=0.094469, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5333/10000 [17:06<14:40,  5.30step/s, loss=0.094469, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5333/10000 [17:06<14:40,  5.30step/s, loss=0.026073, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5334/10000 [17:06<14:42,  5.29step/s, loss=0.026073, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5334/10000 [17:06<14:42,  5.29step/s, loss=0.083510, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5335/10000 [17:06<14:41,  5.29step/s, loss=0.083510, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5335/10000 [17:06<14:41,  5.29step/s, loss=0.039040, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5336/10000 [17:07<14:39,  5.30step/s, loss=0.039040, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5336/10000 [17:07<14:39,  5.30step/s, loss=0.034002, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5337/10000 [17:07<14:39,  5.30step/s, loss=0.034002, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5337/10000 [17:07<14:39,  5.30step/s, loss=0.061768, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5338/10000 [17:07<14:38,  5.31step/s, loss=0.061768, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5338/10000 [17:07<14:38,  5.31step/s, loss=0.028110, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5339/10000 [17:07<14:39,  5.30step/s, loss=0.028110, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5339/10000 [17:07<14:39,  5.30step/s, loss=0.064850, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5340/10000 [17:07<14:39,  5.30step/s, loss=0.064850, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5340/10000 [17:07<14:39,  5.30step/s, loss=0.039648, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5341/10000 [17:08<14:38,  5.30step/s, loss=0.039648, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5341/10000 [17:08<14:38,  5.30step/s, loss=0.116032, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5342/10000 [17:08<14:39,  5.30step/s, loss=0.116032, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5342/10000 [17:08<14:39,  5.30step/s, loss=0.020505, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5343/10000 [17:08<14:38,  5.30step/s, loss=0.020505, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5343/10000 [17:08<14:38,  5.30step/s, loss=0.039405, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5344/10000 [17:08<14:39,  5.29step/s, loss=0.039405, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5344/10000 [17:08<14:39,  5.29step/s, loss=0.040803, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5345/10000 [17:08<14:39,  5.29step/s, loss=0.040803, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5345/10000 [17:08<14:39,  5.29step/s, loss=0.089968, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5346/10000 [17:08<14:38,  5.30step/s, loss=0.089968, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5346/10000 [17:08<14:38,  5.30step/s, loss=0.033076, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5347/10000 [17:09<14:38,  5.30step/s, loss=0.033076, elapsed=17.1min]

Entraînement:  53%|█████▎    | 5347/10000 [17:09<14:38,  5.30step/s, loss=0.019616, elapsed=17.2min]

Entraînement:  53%|█████▎    | 5348/10000 [17:09<14:38,  5.30step/s, loss=0.019616, elapsed=17.2min]

Entraînement:  53%|█████▎    | 5348/10000 [17:09<14:38,  5.30step/s, loss=0.032423, elapsed=17.2min]

Entraînement:  53%|█████▎    | 5349/10000 [17:09<14:37,  5.30step/s, loss=0.032423, elapsed=17.2min]

Entraînement:  53%|█████▎    | 5349/10000 [17:09<14:37,  5.30step/s, loss=0.094339, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5350/10000 [17:09<14:39,  5.29step/s, loss=0.094339, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5350/10000 [17:09<14:39,  5.29step/s, loss=0.035791, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5351/10000 [17:09<14:38,  5.29step/s, loss=0.035791, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5351/10000 [17:09<14:38,  5.29step/s, loss=0.048438, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5352/10000 [17:10<14:39,  5.29step/s, loss=0.048438, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5352/10000 [17:10<14:39,  5.29step/s, loss=0.055501, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5353/10000 [17:10<14:39,  5.28step/s, loss=0.055501, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5353/10000 [17:10<14:39,  5.28step/s, loss=0.038707, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5354/10000 [17:10<14:37,  5.29step/s, loss=0.038707, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5354/10000 [17:10<14:37,  5.29step/s, loss=0.044367, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5355/10000 [17:10<14:37,  5.29step/s, loss=0.044367, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5355/10000 [17:10<14:37,  5.29step/s, loss=0.047525, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5356/10000 [17:10<14:37,  5.29step/s, loss=0.047525, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5356/10000 [17:10<14:37,  5.29step/s, loss=0.078753, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5357/10000 [17:11<14:36,  5.30step/s, loss=0.078753, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5357/10000 [17:11<14:36,  5.30step/s, loss=0.126847, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5358/10000 [17:11<14:38,  5.29step/s, loss=0.126847, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5358/10000 [17:11<14:38,  5.29step/s, loss=0.031876, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5359/10000 [17:11<14:37,  5.29step/s, loss=0.031876, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5359/10000 [17:11<14:37,  5.29step/s, loss=0.077679, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5360/10000 [17:11<14:37,  5.29step/s, loss=0.077679, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5360/10000 [17:11<14:37,  5.29step/s, loss=0.088514, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5361/10000 [17:11<14:37,  5.29step/s, loss=0.088514, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5361/10000 [17:11<14:37,  5.29step/s, loss=0.046859, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5362/10000 [17:11<14:35,  5.30step/s, loss=0.046859, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5362/10000 [17:11<14:35,  5.30step/s, loss=0.059360, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5363/10000 [17:12<14:35,  5.30step/s, loss=0.059360, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5363/10000 [17:12<14:35,  5.30step/s, loss=0.019265, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5364/10000 [17:12<14:34,  5.30step/s, loss=0.019265, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5364/10000 [17:12<14:34,  5.30step/s, loss=0.027219, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5365/10000 [17:12<14:35,  5.29step/s, loss=0.027219, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5365/10000 [17:12<14:35,  5.29step/s, loss=0.052386, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5366/10000 [17:12<14:38,  5.27step/s, loss=0.052386, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5366/10000 [17:12<14:38,  5.27step/s, loss=0.044187, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5367/10000 [17:12<14:40,  5.26step/s, loss=0.044187, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5367/10000 [17:12<14:40,  5.26step/s, loss=0.038279, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5368/10000 [17:13<14:38,  5.27step/s, loss=0.038279, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5368/10000 [17:13<14:38,  5.27step/s, loss=0.024228, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5369/10000 [17:13<14:37,  5.28step/s, loss=0.024228, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5369/10000 [17:13<14:37,  5.28step/s, loss=0.033692, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5370/10000 [17:13<14:37,  5.28step/s, loss=0.033692, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5370/10000 [17:13<14:37,  5.28step/s, loss=0.086029, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5371/10000 [17:13<14:36,  5.28step/s, loss=0.086029, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5371/10000 [17:13<14:36,  5.28step/s, loss=0.021907, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5372/10000 [17:13<14:37,  5.27step/s, loss=0.021907, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5372/10000 [17:13<14:37,  5.27step/s, loss=0.050896, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5373/10000 [17:14<14:43,  5.24step/s, loss=0.050896, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5373/10000 [17:14<14:43,  5.24step/s, loss=0.033028, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5374/10000 [17:14<14:43,  5.24step/s, loss=0.033028, elapsed=17.2min]

Entraînement:  54%|█████▎    | 5374/10000 [17:14<14:43,  5.24step/s, loss=0.100616, elapsed=17.2min]

Entraînement:  54%|█████▍    | 5375/10000 [17:14<14:41,  5.25step/s, loss=0.100616, elapsed=17.2min]

Entraînement:  54%|█████▍    | 5375/10000 [17:14<14:41,  5.25step/s, loss=0.036692, elapsed=17.2min]

Entraînement:  54%|█████▍    | 5376/10000 [17:14<14:39,  5.26step/s, loss=0.036692, elapsed=17.2min]

Entraînement:  54%|█████▍    | 5376/10000 [17:14<14:39,  5.26step/s, loss=0.050158, elapsed=17.2min]

Entraînement:  54%|█████▍    | 5377/10000 [17:14<14:39,  5.26step/s, loss=0.050158, elapsed=17.2min]

Entraînement:  54%|█████▍    | 5377/10000 [17:14<14:39,  5.26step/s, loss=0.040333, elapsed=17.2min]

Entraînement:  54%|█████▍    | 5378/10000 [17:15<14:37,  5.26step/s, loss=0.040333, elapsed=17.2min]

Entraînement:  54%|█████▍    | 5378/10000 [17:15<14:37,  5.26step/s, loss=0.035026, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5379/10000 [17:15<14:37,  5.27step/s, loss=0.035026, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5379/10000 [17:15<14:37,  5.27step/s, loss=0.045427, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5380/10000 [17:15<14:36,  5.27step/s, loss=0.045427, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5380/10000 [17:15<14:36,  5.27step/s, loss=0.063550, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5381/10000 [17:15<14:37,  5.26step/s, loss=0.063550, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5381/10000 [17:15<14:37,  5.26step/s, loss=0.058229, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5382/10000 [17:15<14:37,  5.27step/s, loss=0.058229, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5382/10000 [17:15<14:37,  5.27step/s, loss=0.035742, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5383/10000 [17:15<14:34,  5.28step/s, loss=0.035742, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5383/10000 [17:15<14:34,  5.28step/s, loss=0.044471, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5384/10000 [17:16<14:35,  5.27step/s, loss=0.044471, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5384/10000 [17:16<14:35,  5.27step/s, loss=0.092630, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5385/10000 [17:16<14:34,  5.27step/s, loss=0.092630, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5385/10000 [17:16<14:34,  5.27step/s, loss=0.042115, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5386/10000 [17:16<14:35,  5.27step/s, loss=0.042115, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5386/10000 [17:16<14:35,  5.27step/s, loss=0.065301, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5387/10000 [17:16<14:34,  5.27step/s, loss=0.065301, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5387/10000 [17:16<14:34,  5.27step/s, loss=0.056273, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5388/10000 [17:16<14:36,  5.26step/s, loss=0.056273, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5388/10000 [17:16<14:36,  5.26step/s, loss=0.045449, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5389/10000 [17:17<14:38,  5.25step/s, loss=0.045449, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5389/10000 [17:17<14:38,  5.25step/s, loss=0.027636, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5390/10000 [17:17<14:38,  5.25step/s, loss=0.027636, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5390/10000 [17:17<14:38,  5.25step/s, loss=0.115740, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5391/10000 [17:17<14:35,  5.26step/s, loss=0.115740, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5391/10000 [17:17<14:35,  5.26step/s, loss=0.055229, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5392/10000 [17:17<14:33,  5.27step/s, loss=0.055229, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5392/10000 [17:17<14:33,  5.27step/s, loss=0.032610, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5393/10000 [17:17<14:35,  5.26step/s, loss=0.032610, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5393/10000 [17:17<14:35,  5.26step/s, loss=0.063294, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5394/10000 [17:18<14:34,  5.27step/s, loss=0.063294, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5394/10000 [17:18<14:34,  5.27step/s, loss=0.053166, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5395/10000 [17:18<14:34,  5.27step/s, loss=0.053166, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5395/10000 [17:18<14:34,  5.27step/s, loss=0.030837, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5396/10000 [17:18<14:35,  5.26step/s, loss=0.030837, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5396/10000 [17:18<14:35,  5.26step/s, loss=0.084379, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5397/10000 [17:18<14:35,  5.26step/s, loss=0.084379, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5397/10000 [17:18<14:35,  5.26step/s, loss=0.028188, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5398/10000 [17:18<14:35,  5.26step/s, loss=0.028188, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5398/10000 [17:18<14:35,  5.26step/s, loss=0.050967, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5399/10000 [17:19<14:34,  5.26step/s, loss=0.050967, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5399/10000 [17:19<14:34,  5.26step/s, loss=0.091124, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5400/10000 [17:19<14:34,  5.26step/s, loss=0.091124, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5400/10000 [17:19<14:34,  5.26step/s, loss=0.059859, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5400/10000 [17:19<14:34,  5.26step/s, loss=0.059859, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5401/10000 [17:19<14:41,  5.21step/s, loss=0.059859, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5401/10000 [17:19<14:41,  5.21step/s, loss=0.051608, elapsed=17.3min]

Step 5400/10000 | Train loss: 0.059859 | Elapsed: 17.3min | ETA: 14.8min

Entraînement:  54%|█████▍    | 5402/10000 [17:19<14:38,  5.23step/s, loss=0.051608, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5402/10000 [17:19<14:38,  5.23step/s, loss=0.043288, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5403/10000 [17:19<14:35,  5.25step/s, loss=0.043288, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5403/10000 [17:19<14:35,  5.25step/s, loss=0.081253, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5404/10000 [17:19<14:35,  5.25step/s, loss=0.081253, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5404/10000 [17:19<14:35,  5.25step/s, loss=0.038666, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5405/10000 [17:20<14:33,  5.26step/s, loss=0.038666, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5405/10000 [17:20<14:33,  5.26step/s, loss=0.027993, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5406/10000 [17:20<14:35,  5.25step/s, loss=0.027993, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5406/10000 [17:20<14:35,  5.25step/s, loss=0.025617, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5407/10000 [17:20<14:34,  5.25step/s, loss=0.025617, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5407/10000 [17:20<14:34,  5.25step/s, loss=0.058112, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5408/10000 [17:20<14:31,  5.27step/s, loss=0.058112, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5408/10000 [17:20<14:31,  5.27step/s, loss=0.037306, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5409/10000 [17:20<14:30,  5.27step/s, loss=0.037306, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5409/10000 [17:20<14:30,  5.27step/s, loss=0.041647, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5410/10000 [17:21<14:29,  5.28step/s, loss=0.041647, elapsed=17.3min]

Entraînement:  54%|█████▍    | 5410/10000 [17:21<14:29,  5.28step/s, loss=0.151882, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5411/10000 [17:21<14:35,  5.24step/s, loss=0.151882, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5411/10000 [17:21<14:35,  5.24step/s, loss=0.050552, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5412/10000 [17:21<14:34,  5.25step/s, loss=0.050552, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5412/10000 [17:21<14:34,  5.25step/s, loss=0.020251, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5413/10000 [17:21<14:30,  5.27step/s, loss=0.020251, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5413/10000 [17:21<14:30,  5.27step/s, loss=0.027368, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5414/10000 [17:21<14:31,  5.26step/s, loss=0.027368, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5414/10000 [17:21<14:31,  5.26step/s, loss=0.100811, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5415/10000 [17:22<14:30,  5.27step/s, loss=0.100811, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5415/10000 [17:22<14:30,  5.27step/s, loss=0.031488, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5416/10000 [17:22<14:28,  5.28step/s, loss=0.031488, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5416/10000 [17:22<14:28,  5.28step/s, loss=0.054923, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5417/10000 [17:22<14:27,  5.29step/s, loss=0.054923, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5417/10000 [17:22<14:27,  5.29step/s, loss=0.094442, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5418/10000 [17:22<14:26,  5.29step/s, loss=0.094442, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5418/10000 [17:22<14:26,  5.29step/s, loss=0.042225, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5419/10000 [17:22<14:28,  5.28step/s, loss=0.042225, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5419/10000 [17:22<14:28,  5.28step/s, loss=0.099793, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5420/10000 [17:23<14:29,  5.27step/s, loss=0.099793, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5420/10000 [17:23<14:29,  5.27step/s, loss=0.036490, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5421/10000 [17:23<14:31,  5.25step/s, loss=0.036490, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5421/10000 [17:23<14:31,  5.25step/s, loss=0.022999, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5422/10000 [17:23<14:25,  5.29step/s, loss=0.022999, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5422/10000 [17:23<14:25,  5.29step/s, loss=0.052201, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5423/10000 [17:23<14:22,  5.31step/s, loss=0.052201, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5423/10000 [17:23<14:22,  5.31step/s, loss=0.095157, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5424/10000 [17:23<14:20,  5.32step/s, loss=0.095157, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5424/10000 [17:23<14:20,  5.32step/s, loss=0.029962, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5425/10000 [17:23<14:24,  5.29step/s, loss=0.029962, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5425/10000 [17:23<14:24,  5.29step/s, loss=0.057396, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5426/10000 [17:24<14:24,  5.29step/s, loss=0.057396, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5426/10000 [17:24<14:24,  5.29step/s, loss=0.025192, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5427/10000 [17:24<14:24,  5.29step/s, loss=0.025192, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5427/10000 [17:24<14:24,  5.29step/s, loss=0.033114, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5428/10000 [17:24<14:24,  5.29step/s, loss=0.033114, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5428/10000 [17:24<14:24,  5.29step/s, loss=0.036300, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5429/10000 [17:24<14:24,  5.28step/s, loss=0.036300, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5429/10000 [17:24<14:24,  5.28step/s, loss=0.021421, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5430/10000 [17:24<14:25,  5.28step/s, loss=0.021421, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5430/10000 [17:24<14:25,  5.28step/s, loss=0.027692, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5431/10000 [17:25<14:26,  5.27step/s, loss=0.027692, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5431/10000 [17:25<14:26,  5.27step/s, loss=0.047869, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5432/10000 [17:25<14:26,  5.27step/s, loss=0.047869, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5432/10000 [17:25<14:26,  5.27step/s, loss=0.094767, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5433/10000 [17:25<14:25,  5.28step/s, loss=0.094767, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5433/10000 [17:25<14:25,  5.28step/s, loss=0.046864, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5434/10000 [17:25<14:23,  5.29step/s, loss=0.046864, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5434/10000 [17:25<14:23,  5.29step/s, loss=0.082020, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5435/10000 [17:25<14:24,  5.28step/s, loss=0.082020, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5435/10000 [17:25<14:24,  5.28step/s, loss=0.016800, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5436/10000 [17:26<14:23,  5.28step/s, loss=0.016800, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5436/10000 [17:26<14:23,  5.28step/s, loss=0.062108, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5437/10000 [17:26<14:23,  5.28step/s, loss=0.062108, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5437/10000 [17:26<14:23,  5.28step/s, loss=0.054846, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5438/10000 [17:26<14:22,  5.29step/s, loss=0.054846, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5438/10000 [17:26<14:22,  5.29step/s, loss=0.048401, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5439/10000 [17:26<14:23,  5.28step/s, loss=0.048401, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5439/10000 [17:26<14:23,  5.28step/s, loss=0.028599, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5440/10000 [17:26<14:25,  5.27step/s, loss=0.028599, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5440/10000 [17:26<14:25,  5.27step/s, loss=0.045373, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5441/10000 [17:26<14:24,  5.27step/s, loss=0.045373, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5441/10000 [17:26<14:24,  5.27step/s, loss=0.037466, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5442/10000 [17:27<14:23,  5.28step/s, loss=0.037466, elapsed=17.4min]

Entraînement:  54%|█████▍    | 5442/10000 [17:27<14:23,  5.28step/s, loss=0.042560, elapsed=17.5min]

Entraînement:  54%|█████▍    | 5443/10000 [17:27<14:22,  5.29step/s, loss=0.042560, elapsed=17.5min]

Entraînement:  54%|█████▍    | 5443/10000 [17:27<14:22,  5.29step/s, loss=0.042448, elapsed=17.5min]

Entraînement:  54%|█████▍    | 5444/10000 [17:27<14:23,  5.27step/s, loss=0.042448, elapsed=17.5min]

Entraînement:  54%|█████▍    | 5444/10000 [17:27<14:23,  5.27step/s, loss=0.051207, elapsed=17.5min]

Entraînement:  54%|█████▍    | 5445/10000 [17:27<14:23,  5.28step/s, loss=0.051207, elapsed=17.5min]

Entraînement:  54%|█████▍    | 5445/10000 [17:27<14:23,  5.28step/s, loss=0.105856, elapsed=17.5min]

Entraînement:  54%|█████▍    | 5446/10000 [17:27<14:22,  5.28step/s, loss=0.105856, elapsed=17.5min]

Entraînement:  54%|█████▍    | 5446/10000 [17:27<14:22,  5.28step/s, loss=0.050067, elapsed=17.5min]

Entraînement:  54%|█████▍    | 5447/10000 [17:28<14:22,  5.28step/s, loss=0.050067, elapsed=17.5min]

Entraînement:  54%|█████▍    | 5447/10000 [17:28<14:22,  5.28step/s, loss=0.042871, elapsed=17.5min]

Entraînement:  54%|█████▍    | 5448/10000 [17:28<14:24,  5.27step/s, loss=0.042871, elapsed=17.5min]

Entraînement:  54%|█████▍    | 5448/10000 [17:28<14:24,  5.27step/s, loss=0.047398, elapsed=17.5min]

Entraînement:  54%|█████▍    | 5449/10000 [17:28<14:25,  5.26step/s, loss=0.047398, elapsed=17.5min]

Entraînement:  54%|█████▍    | 5449/10000 [17:28<14:25,  5.26step/s, loss=0.034931, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5450/10000 [17:28<14:32,  5.22step/s, loss=0.034931, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5450/10000 [17:28<14:32,  5.22step/s, loss=0.064617, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5451/10000 [17:28<14:29,  5.23step/s, loss=0.064617, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5451/10000 [17:28<14:29,  5.23step/s, loss=0.022904, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5452/10000 [17:29<14:31,  5.22step/s, loss=0.022904, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5452/10000 [17:29<14:31,  5.22step/s, loss=0.044402, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5453/10000 [17:29<14:29,  5.23step/s, loss=0.044402, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5453/10000 [17:29<14:29,  5.23step/s, loss=0.060964, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5454/10000 [17:29<14:27,  5.24step/s, loss=0.060964, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5454/10000 [17:29<14:27,  5.24step/s, loss=0.028026, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5455/10000 [17:29<14:25,  5.25step/s, loss=0.028026, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5455/10000 [17:29<14:25,  5.25step/s, loss=0.044646, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5456/10000 [17:29<14:23,  5.26step/s, loss=0.044646, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5456/10000 [17:29<14:23,  5.26step/s, loss=0.023340, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5457/10000 [17:30<14:25,  5.25step/s, loss=0.023340, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5457/10000 [17:30<14:25,  5.25step/s, loss=0.048957, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5458/10000 [17:30<14:22,  5.27step/s, loss=0.048957, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5458/10000 [17:30<14:22,  5.27step/s, loss=0.117333, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5459/10000 [17:30<14:22,  5.27step/s, loss=0.117333, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5459/10000 [17:30<14:22,  5.27step/s, loss=0.040662, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5460/10000 [17:30<14:23,  5.26step/s, loss=0.040662, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5460/10000 [17:30<14:23,  5.26step/s, loss=0.029442, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5461/10000 [17:30<14:22,  5.26step/s, loss=0.029442, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5461/10000 [17:30<14:22,  5.26step/s, loss=0.042118, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5462/10000 [17:30<14:22,  5.26step/s, loss=0.042118, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5462/10000 [17:30<14:22,  5.26step/s, loss=0.035388, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5463/10000 [17:31<14:20,  5.27step/s, loss=0.035388, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5463/10000 [17:31<14:20,  5.27step/s, loss=0.040884, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5464/10000 [17:31<14:25,  5.24step/s, loss=0.040884, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5464/10000 [17:31<14:25,  5.24step/s, loss=0.035088, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5465/10000 [17:31<14:28,  5.22step/s, loss=0.035088, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5465/10000 [17:31<14:28,  5.22step/s, loss=0.031889, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5466/10000 [17:31<14:27,  5.22step/s, loss=0.031889, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5466/10000 [17:31<14:27,  5.22step/s, loss=0.031463, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5467/10000 [17:31<14:25,  5.24step/s, loss=0.031463, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5467/10000 [17:31<14:25,  5.24step/s, loss=0.041104, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5468/10000 [17:32<14:28,  5.22step/s, loss=0.041104, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5468/10000 [17:32<14:28,  5.22step/s, loss=0.032454, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5469/10000 [17:32<14:25,  5.23step/s, loss=0.032454, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5469/10000 [17:32<14:25,  5.23step/s, loss=0.041600, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5470/10000 [17:32<14:21,  5.26step/s, loss=0.041600, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5470/10000 [17:32<14:21,  5.26step/s, loss=0.039096, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5471/10000 [17:32<14:20,  5.26step/s, loss=0.039096, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5471/10000 [17:32<14:20,  5.26step/s, loss=0.048207, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5472/10000 [17:32<14:19,  5.27step/s, loss=0.048207, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5472/10000 [17:32<14:19,  5.27step/s, loss=0.025081, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5473/10000 [17:33<14:18,  5.27step/s, loss=0.025081, elapsed=17.5min]

Entraînement:  55%|█████▍    | 5473/10000 [17:33<14:18,  5.27step/s, loss=0.024403, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5474/10000 [17:33<14:16,  5.28step/s, loss=0.024403, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5474/10000 [17:33<14:16,  5.28step/s, loss=0.034192, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5475/10000 [17:33<14:15,  5.29step/s, loss=0.034192, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5475/10000 [17:33<14:15,  5.29step/s, loss=0.093110, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5476/10000 [17:33<14:15,  5.29step/s, loss=0.093110, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5476/10000 [17:33<14:15,  5.29step/s, loss=0.041819, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5477/10000 [17:33<14:13,  5.30step/s, loss=0.041819, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5477/10000 [17:33<14:13,  5.30step/s, loss=0.027098, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5478/10000 [17:34<14:14,  5.29step/s, loss=0.027098, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5478/10000 [17:34<14:14,  5.29step/s, loss=0.038813, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5479/10000 [17:34<14:13,  5.29step/s, loss=0.038813, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5479/10000 [17:34<14:13,  5.29step/s, loss=0.040739, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5480/10000 [17:34<14:17,  5.27step/s, loss=0.040739, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5480/10000 [17:34<14:17,  5.27step/s, loss=0.039969, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5481/10000 [17:34<14:16,  5.28step/s, loss=0.039969, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5481/10000 [17:34<14:16,  5.28step/s, loss=0.015961, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5482/10000 [17:34<14:16,  5.27step/s, loss=0.015961, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5482/10000 [17:34<14:16,  5.27step/s, loss=0.081145, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5483/10000 [17:34<14:16,  5.28step/s, loss=0.081145, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5483/10000 [17:34<14:16,  5.28step/s, loss=0.114585, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5484/10000 [17:35<14:14,  5.29step/s, loss=0.114585, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5484/10000 [17:35<14:14,  5.29step/s, loss=0.022893, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5485/10000 [17:35<14:14,  5.28step/s, loss=0.022893, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5485/10000 [17:35<14:14,  5.28step/s, loss=0.031488, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5486/10000 [17:35<14:13,  5.29step/s, loss=0.031488, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5486/10000 [17:35<14:13,  5.29step/s, loss=0.025870, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5487/10000 [17:35<14:12,  5.29step/s, loss=0.025870, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5487/10000 [17:35<14:12,  5.29step/s, loss=0.051485, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5488/10000 [17:35<14:14,  5.28step/s, loss=0.051485, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5488/10000 [17:35<14:14,  5.28step/s, loss=0.049218, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5489/10000 [17:36<14:15,  5.28step/s, loss=0.049218, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5489/10000 [17:36<14:15,  5.28step/s, loss=0.104218, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5490/10000 [17:36<14:15,  5.27step/s, loss=0.104218, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5490/10000 [17:36<14:15,  5.27step/s, loss=0.035691, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5491/10000 [17:36<14:15,  5.27step/s, loss=0.035691, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5491/10000 [17:36<14:15,  5.27step/s, loss=0.028238, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5492/10000 [17:36<14:15,  5.27step/s, loss=0.028238, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5492/10000 [17:36<14:15,  5.27step/s, loss=0.027771, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5493/10000 [17:36<14:15,  5.27step/s, loss=0.027771, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5493/10000 [17:36<14:15,  5.27step/s, loss=0.124856, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5494/10000 [17:37<14:14,  5.27step/s, loss=0.124856, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5494/10000 [17:37<14:14,  5.27step/s, loss=0.049095, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5495/10000 [17:37<14:14,  5.27step/s, loss=0.049095, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5495/10000 [17:37<14:14,  5.27step/s, loss=0.025172, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5496/10000 [17:37<14:16,  5.26step/s, loss=0.025172, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5496/10000 [17:37<14:16,  5.26step/s, loss=0.019513, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5497/10000 [17:37<14:15,  5.26step/s, loss=0.019513, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5497/10000 [17:37<14:15,  5.26step/s, loss=0.060091, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5498/10000 [17:37<14:14,  5.27step/s, loss=0.060091, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5498/10000 [17:37<14:14,  5.27step/s, loss=0.029697, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5499/10000 [17:38<14:12,  5.28step/s, loss=0.029697, elapsed=17.6min]

Entraînement:  55%|█████▍    | 5499/10000 [17:38<14:12,  5.28step/s, loss=0.054667, elapsed=17.6min]

Entraînement:  55%|█████▌    | 5500/10000 [17:38<14:12,  5.28step/s, loss=0.054667, elapsed=17.6min]

Entraînement:  55%|█████▌    | 5500/10000 [17:38<14:12,  5.28step/s, loss=0.039021, elapsed=17.6min]

Entraînement:  55%|█████▌    | 5500/10000 [17:38<14:12,  5.28step/s, loss=0.039021, elapsed=17.6min]

Entraînement:  55%|█████▌    | 5501/10000 [17:38<14:19,  5.23step/s, loss=0.039021, elapsed=17.6min]

Entraînement:  55%|█████▌    | 5501/10000 [17:38<14:19,  5.23step/s, loss=0.026480, elapsed=17.6min]

Step 5500/10000 | Train loss: 0.039021 | Elapsed: 17.6min | ETA: 14.4min

Entraînement:  55%|█████▌    | 5502/10000 [17:38<14:17,  5.25step/s, loss=0.026480, elapsed=17.6min]

Entraînement:  55%|█████▌    | 5502/10000 [17:38<14:17,  5.25step/s, loss=0.031812, elapsed=17.6min]

Entraînement:  55%|█████▌    | 5503/10000 [17:38<14:13,  5.27step/s, loss=0.031812, elapsed=17.6min]

Entraînement:  55%|█████▌    | 5503/10000 [17:38<14:13,  5.27step/s, loss=0.056209, elapsed=17.6min]

Entraînement:  55%|█████▌    | 5504/10000 [17:38<14:13,  5.27step/s, loss=0.056209, elapsed=17.6min]

Entraînement:  55%|█████▌    | 5504/10000 [17:38<14:13,  5.27step/s, loss=0.057075, elapsed=17.6min]

Entraînement:  55%|█████▌    | 5505/10000 [17:39<14:15,  5.26step/s, loss=0.057075, elapsed=17.6min]

Entraînement:  55%|█████▌    | 5505/10000 [17:39<14:15,  5.26step/s, loss=0.045639, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5506/10000 [17:39<14:14,  5.26step/s, loss=0.045639, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5506/10000 [17:39<14:14,  5.26step/s, loss=0.035376, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5507/10000 [17:39<14:11,  5.27step/s, loss=0.035376, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5507/10000 [17:39<14:11,  5.27step/s, loss=0.068245, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5508/10000 [17:39<14:11,  5.27step/s, loss=0.068245, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5508/10000 [17:39<14:11,  5.27step/s, loss=0.027328, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5509/10000 [17:39<14:12,  5.27step/s, loss=0.027328, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5509/10000 [17:39<14:12,  5.27step/s, loss=0.030650, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5510/10000 [17:40<14:11,  5.27step/s, loss=0.030650, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5510/10000 [17:40<14:11,  5.27step/s, loss=0.036004, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5511/10000 [17:40<14:13,  5.26step/s, loss=0.036004, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5511/10000 [17:40<14:13,  5.26step/s, loss=0.053403, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5512/10000 [17:40<14:22,  5.20step/s, loss=0.053403, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5512/10000 [17:40<14:22,  5.20step/s, loss=0.020519, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5513/10000 [17:40<14:20,  5.21step/s, loss=0.020519, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5513/10000 [17:40<14:20,  5.21step/s, loss=0.041497, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5514/10000 [17:40<14:17,  5.23step/s, loss=0.041497, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5514/10000 [17:40<14:17,  5.23step/s, loss=0.051854, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5515/10000 [17:41<14:15,  5.24step/s, loss=0.051854, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5515/10000 [17:41<14:15,  5.24step/s, loss=0.047900, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5516/10000 [17:41<14:13,  5.25step/s, loss=0.047900, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5516/10000 [17:41<14:13,  5.25step/s, loss=0.050580, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5517/10000 [17:41<14:12,  5.26step/s, loss=0.050580, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5517/10000 [17:41<14:12,  5.26step/s, loss=0.084854, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5518/10000 [17:41<14:12,  5.26step/s, loss=0.084854, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5518/10000 [17:41<14:12,  5.26step/s, loss=0.069990, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5519/10000 [17:41<14:11,  5.27step/s, loss=0.069990, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5519/10000 [17:41<14:11,  5.27step/s, loss=0.035644, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5520/10000 [17:41<14:12,  5.26step/s, loss=0.035644, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5520/10000 [17:42<14:12,  5.26step/s, loss=0.090288, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5521/10000 [17:42<14:07,  5.28step/s, loss=0.090288, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5521/10000 [17:42<14:07,  5.28step/s, loss=0.023668, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5522/10000 [17:42<14:08,  5.28step/s, loss=0.023668, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5522/10000 [17:42<14:08,  5.28step/s, loss=0.036590, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5523/10000 [17:42<14:07,  5.28step/s, loss=0.036590, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5523/10000 [17:42<14:07,  5.28step/s, loss=0.031056, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5524/10000 [17:42<14:07,  5.28step/s, loss=0.031056, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5524/10000 [17:42<14:07,  5.28step/s, loss=0.040890, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5525/10000 [17:42<14:07,  5.28step/s, loss=0.040890, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5525/10000 [17:42<14:07,  5.28step/s, loss=0.027985, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5526/10000 [17:43<14:09,  5.27step/s, loss=0.027985, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5526/10000 [17:43<14:09,  5.27step/s, loss=0.030188, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5527/10000 [17:43<14:08,  5.27step/s, loss=0.030188, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5527/10000 [17:43<14:08,  5.27step/s, loss=0.047388, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5528/10000 [17:43<14:07,  5.28step/s, loss=0.047388, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5528/10000 [17:43<14:07,  5.28step/s, loss=0.047467, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5529/10000 [17:43<14:07,  5.28step/s, loss=0.047467, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5529/10000 [17:43<14:07,  5.28step/s, loss=0.071911, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5530/10000 [17:43<14:07,  5.28step/s, loss=0.071911, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5530/10000 [17:43<14:07,  5.28step/s, loss=0.102399, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5531/10000 [17:44<14:06,  5.28step/s, loss=0.102399, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5531/10000 [17:44<14:06,  5.28step/s, loss=0.045750, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5532/10000 [17:44<14:06,  5.28step/s, loss=0.045750, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5532/10000 [17:44<14:06,  5.28step/s, loss=0.066340, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5533/10000 [17:44<14:07,  5.27step/s, loss=0.066340, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5533/10000 [17:44<14:07,  5.27step/s, loss=0.030491, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5534/10000 [17:44<14:09,  5.26step/s, loss=0.030491, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5534/10000 [17:44<14:09,  5.26step/s, loss=0.080959, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5535/10000 [17:44<14:09,  5.26step/s, loss=0.080959, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5535/10000 [17:44<14:09,  5.26step/s, loss=0.050382, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5536/10000 [17:45<14:13,  5.23step/s, loss=0.050382, elapsed=17.7min]

Entraînement:  55%|█████▌    | 5536/10000 [17:45<14:13,  5.23step/s, loss=0.069399, elapsed=17.8min]

Entraînement:  55%|█████▌    | 5537/10000 [17:45<14:11,  5.24step/s, loss=0.069399, elapsed=17.8min]

Entraînement:  55%|█████▌    | 5537/10000 [17:45<14:11,  5.24step/s, loss=0.056823, elapsed=17.8min]

Entraînement:  55%|█████▌    | 5538/10000 [17:45<14:09,  5.25step/s, loss=0.056823, elapsed=17.8min]

Entraînement:  55%|█████▌    | 5538/10000 [17:45<14:09,  5.25step/s, loss=0.054964, elapsed=17.8min]

Entraînement:  55%|█████▌    | 5539/10000 [17:45<14:08,  5.25step/s, loss=0.054964, elapsed=17.8min]

Entraînement:  55%|█████▌    | 5539/10000 [17:45<14:08,  5.25step/s, loss=0.027492, elapsed=17.8min]

Entraînement:  55%|█████▌    | 5540/10000 [17:45<14:07,  5.26step/s, loss=0.027492, elapsed=17.8min]

Entraînement:  55%|█████▌    | 5540/10000 [17:45<14:07,  5.26step/s, loss=0.053213, elapsed=17.8min]

Entraînement:  55%|█████▌    | 5541/10000 [17:45<14:07,  5.26step/s, loss=0.053213, elapsed=17.8min]

Entraînement:  55%|█████▌    | 5541/10000 [17:45<14:07,  5.26step/s, loss=0.033765, elapsed=17.8min]

Entraînement:  55%|█████▌    | 5542/10000 [17:46<14:06,  5.27step/s, loss=0.033765, elapsed=17.8min]

Entraînement:  55%|█████▌    | 5542/10000 [17:46<14:06,  5.27step/s, loss=0.048428, elapsed=17.8min]

Entraînement:  55%|█████▌    | 5543/10000 [17:46<14:14,  5.21step/s, loss=0.048428, elapsed=17.8min]

Entraînement:  55%|█████▌    | 5543/10000 [17:46<14:14,  5.21step/s, loss=0.041658, elapsed=17.8min]

Entraînement:  55%|█████▌    | 5544/10000 [17:46<14:13,  5.22step/s, loss=0.041658, elapsed=17.8min]

Entraînement:  55%|█████▌    | 5544/10000 [17:46<14:13,  5.22step/s, loss=0.083351, elapsed=17.8min]

Entraînement:  55%|█████▌    | 5545/10000 [17:46<14:10,  5.24step/s, loss=0.083351, elapsed=17.8min]

Entraînement:  55%|█████▌    | 5545/10000 [17:46<14:10,  5.24step/s, loss=0.044626, elapsed=17.8min]

Entraînement:  55%|█████▌    | 5546/10000 [17:46<14:09,  5.24step/s, loss=0.044626, elapsed=17.8min]

Entraînement:  55%|█████▌    | 5546/10000 [17:46<14:09,  5.24step/s, loss=0.054944, elapsed=17.8min]

Entraînement:  55%|█████▌    | 5547/10000 [17:47<14:08,  5.25step/s, loss=0.054944, elapsed=17.8min]

Entraînement:  55%|█████▌    | 5547/10000 [17:47<14:08,  5.25step/s, loss=0.046395, elapsed=17.8min]

Entraînement:  55%|█████▌    | 5548/10000 [17:47<14:08,  5.25step/s, loss=0.046395, elapsed=17.8min]

Entraînement:  55%|█████▌    | 5548/10000 [17:47<14:08,  5.25step/s, loss=0.041511, elapsed=17.8min]

Entraînement:  55%|█████▌    | 5549/10000 [17:47<14:09,  5.24step/s, loss=0.041511, elapsed=17.8min]

Entraînement:  55%|█████▌    | 5549/10000 [17:47<14:09,  5.24step/s, loss=0.045253, elapsed=17.8min]

Entraînement:  56%|█████▌    | 5550/10000 [17:47<14:08,  5.24step/s, loss=0.045253, elapsed=17.8min]

Entraînement:  56%|█████▌    | 5550/10000 [17:47<14:08,  5.24step/s, loss=0.050139, elapsed=17.8min]

Entraînement:  56%|█████▌    | 5551/10000 [17:47<14:07,  5.25step/s, loss=0.050139, elapsed=17.8min]

Entraînement:  56%|█████▌    | 5551/10000 [17:47<14:07,  5.25step/s, loss=0.108927, elapsed=17.8min]

Entraînement:  56%|█████▌    | 5552/10000 [17:48<14:05,  5.26step/s, loss=0.108927, elapsed=17.8min]

Entraînement:  56%|█████▌    | 5552/10000 [17:48<14:05,  5.26step/s, loss=0.037846, elapsed=17.8min]

Entraînement:  56%|█████▌    | 5553/10000 [17:48<14:05,  5.26step/s, loss=0.037846, elapsed=17.8min]

Entraînement:  56%|█████▌    | 5553/10000 [17:48<14:05,  5.26step/s, loss=0.059951, elapsed=17.8min]

Entraînement:  56%|█████▌    | 5554/10000 [17:48<14:04,  5.27step/s, loss=0.059951, elapsed=17.8min]

Entraînement:  56%|█████▌    | 5554/10000 [17:48<14:04,  5.27step/s, loss=0.033888, elapsed=17.8min]

Entraînement:  56%|█████▌    | 5555/10000 [17:48<14:06,  5.25step/s, loss=0.033888, elapsed=17.8min]

Entraînement:  56%|█████▌    | 5555/10000 [17:48<14:06,  5.25step/s, loss=0.043958, elapsed=17.8min]

Entraînement:  56%|█████▌    | 5556/10000 [17:48<14:07,  5.25step/s, loss=0.043958, elapsed=17.8min]

Entraînement:  56%|█████▌    | 5556/10000 [17:48<14:07,  5.25step/s, loss=0.046000, elapsed=17.8min]

Entraînement:  56%|█████▌    | 5557/10000 [17:49<14:15,  5.19step/s, loss=0.046000, elapsed=17.8min]

Entraînement:  56%|█████▌    | 5557/10000 [17:49<14:15,  5.19step/s, loss=0.042488, elapsed=17.8min]

Entraînement:  56%|█████▌    | 5558/10000 [17:49<14:10,  5.22step/s, loss=0.042488, elapsed=17.8min]

Entraînement:  56%|█████▌    | 5558/10000 [17:49<14:10,  5.22step/s, loss=0.019779, elapsed=17.8min]

Entraînement:  56%|█████▌    | 5559/10000 [17:49<14:05,  5.25step/s, loss=0.019779, elapsed=17.8min]

Entraînement:  56%|█████▌    | 5559/10000 [17:49<14:05,  5.25step/s, loss=0.040853, elapsed=17.8min]

Entraînement:  56%|█████▌    | 5560/10000 [17:49<14:03,  5.26step/s, loss=0.040853, elapsed=17.8min]

Entraînement:  56%|█████▌    | 5560/10000 [17:49<14:03,  5.26step/s, loss=0.023974, elapsed=17.8min]

Entraînement:  56%|█████▌    | 5561/10000 [17:49<14:01,  5.28step/s, loss=0.023974, elapsed=17.8min]

Entraînement:  56%|█████▌    | 5561/10000 [17:49<14:01,  5.28step/s, loss=0.024166, elapsed=17.8min]

Entraînement:  56%|█████▌    | 5562/10000 [17:49<13:58,  5.29step/s, loss=0.024166, elapsed=17.8min]

Entraînement:  56%|█████▌    | 5562/10000 [17:49<13:58,  5.29step/s, loss=0.066475, elapsed=17.8min]

Entraînement:  56%|█████▌    | 5563/10000 [17:50<13:58,  5.29step/s, loss=0.066475, elapsed=17.8min]

Entraînement:  56%|█████▌    | 5563/10000 [17:50<13:58,  5.29step/s, loss=0.041798, elapsed=17.8min]

Entraînement:  56%|█████▌    | 5564/10000 [17:50<13:58,  5.29step/s, loss=0.041798, elapsed=17.8min]

Entraînement:  56%|█████▌    | 5564/10000 [17:50<13:58,  5.29step/s, loss=0.076904, elapsed=17.8min]

Entraînement:  56%|█████▌    | 5565/10000 [17:50<13:59,  5.28step/s, loss=0.076904, elapsed=17.8min]

Entraînement:  56%|█████▌    | 5565/10000 [17:50<13:59,  5.28step/s, loss=0.027298, elapsed=17.8min]

Entraînement:  56%|█████▌    | 5566/10000 [17:50<13:59,  5.28step/s, loss=0.027298, elapsed=17.8min]

Entraînement:  56%|█████▌    | 5566/10000 [17:50<13:59,  5.28step/s, loss=0.044070, elapsed=17.8min]

Entraînement:  56%|█████▌    | 5567/10000 [17:50<14:01,  5.27step/s, loss=0.044070, elapsed=17.8min]

Entraînement:  56%|█████▌    | 5567/10000 [17:50<14:01,  5.27step/s, loss=0.078309, elapsed=17.8min]

Entraînement:  56%|█████▌    | 5568/10000 [17:51<14:01,  5.27step/s, loss=0.078309, elapsed=17.8min]

Entraînement:  56%|█████▌    | 5568/10000 [17:51<14:01,  5.27step/s, loss=0.091242, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5569/10000 [17:51<14:00,  5.27step/s, loss=0.091242, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5569/10000 [17:51<14:00,  5.27step/s, loss=0.119568, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5570/10000 [17:51<14:00,  5.27step/s, loss=0.119568, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5570/10000 [17:51<14:00,  5.27step/s, loss=0.042499, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5571/10000 [17:51<13:59,  5.28step/s, loss=0.042499, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5571/10000 [17:51<13:59,  5.28step/s, loss=0.069452, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5572/10000 [17:51<14:01,  5.26step/s, loss=0.069452, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5572/10000 [17:51<14:01,  5.26step/s, loss=0.085219, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5573/10000 [17:52<13:59,  5.27step/s, loss=0.085219, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5573/10000 [17:52<13:59,  5.27step/s, loss=0.091860, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5574/10000 [17:52<14:00,  5.27step/s, loss=0.091860, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5574/10000 [17:52<14:00,  5.27step/s, loss=0.096696, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5575/10000 [17:52<13:58,  5.28step/s, loss=0.096696, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5575/10000 [17:52<13:58,  5.28step/s, loss=0.107274, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5576/10000 [17:52<13:57,  5.28step/s, loss=0.107274, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5576/10000 [17:52<13:57,  5.28step/s, loss=0.063139, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5577/10000 [17:52<13:58,  5.27step/s, loss=0.063139, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5577/10000 [17:52<13:58,  5.27step/s, loss=0.052285, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5578/10000 [17:53<13:57,  5.28step/s, loss=0.052285, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5578/10000 [17:53<13:57,  5.28step/s, loss=0.064216, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5579/10000 [17:53<13:59,  5.27step/s, loss=0.064216, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5579/10000 [17:53<13:59,  5.27step/s, loss=0.081616, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5580/10000 [17:53<14:01,  5.25step/s, loss=0.081616, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5580/10000 [17:53<14:01,  5.25step/s, loss=0.048295, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5581/10000 [17:53<14:03,  5.24step/s, loss=0.048295, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5581/10000 [17:53<14:03,  5.24step/s, loss=0.081170, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5582/10000 [17:53<14:02,  5.24step/s, loss=0.081170, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5582/10000 [17:53<14:02,  5.24step/s, loss=0.074356, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5583/10000 [17:53<13:58,  5.27step/s, loss=0.074356, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5583/10000 [17:53<13:58,  5.27step/s, loss=0.047444, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5584/10000 [17:54<13:59,  5.26step/s, loss=0.047444, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5584/10000 [17:54<13:59,  5.26step/s, loss=0.025653, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5585/10000 [17:54<13:58,  5.26step/s, loss=0.025653, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5585/10000 [17:54<13:58,  5.26step/s, loss=0.062949, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5586/10000 [17:54<13:59,  5.26step/s, loss=0.062949, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5586/10000 [17:54<13:59,  5.26step/s, loss=0.027874, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5587/10000 [17:54<13:59,  5.26step/s, loss=0.027874, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5587/10000 [17:54<13:59,  5.26step/s, loss=0.049413, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5588/10000 [17:54<14:00,  5.25step/s, loss=0.049413, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5588/10000 [17:54<14:00,  5.25step/s, loss=0.093257, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5589/10000 [17:55<13:54,  5.29step/s, loss=0.093257, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5589/10000 [17:55<13:54,  5.29step/s, loss=0.025132, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5590/10000 [17:55<13:57,  5.27step/s, loss=0.025132, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5590/10000 [17:55<13:57,  5.27step/s, loss=0.062380, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5591/10000 [17:55<13:57,  5.26step/s, loss=0.062380, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5591/10000 [17:55<13:57,  5.26step/s, loss=0.092854, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5592/10000 [17:55<13:57,  5.26step/s, loss=0.092854, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5592/10000 [17:55<13:57,  5.26step/s, loss=0.032828, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5593/10000 [17:55<13:57,  5.26step/s, loss=0.032828, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5593/10000 [17:55<13:57,  5.26step/s, loss=0.062495, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5594/10000 [17:56<14:00,  5.25step/s, loss=0.062495, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5594/10000 [17:56<14:00,  5.25step/s, loss=0.027130, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5595/10000 [17:56<14:03,  5.22step/s, loss=0.027130, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5595/10000 [17:56<14:03,  5.22step/s, loss=0.028668, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5596/10000 [17:56<14:02,  5.23step/s, loss=0.028668, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5596/10000 [17:56<14:02,  5.23step/s, loss=0.019248, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5597/10000 [17:56<13:58,  5.25step/s, loss=0.019248, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5597/10000 [17:56<13:58,  5.25step/s, loss=0.028589, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5598/10000 [17:56<13:56,  5.26step/s, loss=0.028589, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5598/10000 [17:56<13:56,  5.26step/s, loss=0.104474, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5599/10000 [17:57<13:58,  5.25step/s, loss=0.104474, elapsed=17.9min]

Entraînement:  56%|█████▌    | 5599/10000 [17:57<13:58,  5.25step/s, loss=0.031836, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5600/10000 [17:57<13:55,  5.26step/s, loss=0.031836, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5600/10000 [17:57<13:55,  5.26step/s, loss=0.037900, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5600/10000 [17:57<13:55,  5.26step/s, loss=0.037900, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5601/10000 [17:57<14:03,  5.22step/s, loss=0.037900, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5601/10000 [17:57<14:03,  5.22step/s, loss=0.044907, elapsed=18.0min]

Step 5600/10000 | Train loss: 0.037900 | Elapsed: 18.0min | ETA: 14.1min

Entraînement:  56%|█████▌    | 5602/10000 [17:57<13:58,  5.25step/s, loss=0.044907, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5602/10000 [17:57<13:58,  5.25step/s, loss=0.048626, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5603/10000 [17:57<13:57,  5.25step/s, loss=0.048626, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5603/10000 [17:57<13:57,  5.25step/s, loss=0.028968, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5604/10000 [17:57<13:55,  5.26step/s, loss=0.028968, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5604/10000 [17:57<13:55,  5.26step/s, loss=0.036532, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5605/10000 [17:58<13:52,  5.28step/s, loss=0.036532, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5605/10000 [17:58<13:52,  5.28step/s, loss=0.064665, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5606/10000 [17:58<13:53,  5.27step/s, loss=0.064665, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5606/10000 [17:58<13:53,  5.27step/s, loss=0.023609, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5607/10000 [17:58<13:51,  5.28step/s, loss=0.023609, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5607/10000 [17:58<13:51,  5.28step/s, loss=0.028193, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5608/10000 [17:58<13:51,  5.28step/s, loss=0.028193, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5608/10000 [17:58<13:51,  5.28step/s, loss=0.021414, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5609/10000 [17:58<13:51,  5.28step/s, loss=0.021414, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5609/10000 [17:58<13:51,  5.28step/s, loss=0.057811, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5610/10000 [17:59<13:51,  5.28step/s, loss=0.057811, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5610/10000 [17:59<13:51,  5.28step/s, loss=0.057886, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5611/10000 [17:59<13:52,  5.27step/s, loss=0.057886, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5611/10000 [17:59<13:52,  5.27step/s, loss=0.027734, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5612/10000 [17:59<13:51,  5.28step/s, loss=0.027734, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5612/10000 [17:59<13:51,  5.28step/s, loss=0.028787, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5613/10000 [17:59<13:51,  5.28step/s, loss=0.028787, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5613/10000 [17:59<13:51,  5.28step/s, loss=0.075012, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5614/10000 [17:59<13:51,  5.28step/s, loss=0.075012, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5614/10000 [17:59<13:51,  5.28step/s, loss=0.017418, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5615/10000 [18:00<13:50,  5.28step/s, loss=0.017418, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5615/10000 [18:00<13:50,  5.28step/s, loss=0.087360, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5616/10000 [18:00<13:49,  5.28step/s, loss=0.087360, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5616/10000 [18:00<13:49,  5.28step/s, loss=0.047179, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5617/10000 [18:00<13:48,  5.29step/s, loss=0.047179, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5617/10000 [18:00<13:48,  5.29step/s, loss=0.066086, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5618/10000 [18:00<13:50,  5.28step/s, loss=0.066086, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5618/10000 [18:00<13:50,  5.28step/s, loss=0.026480, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5619/10000 [18:00<13:48,  5.29step/s, loss=0.026480, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5619/10000 [18:00<13:48,  5.29step/s, loss=0.044024, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5620/10000 [18:00<13:49,  5.28step/s, loss=0.044024, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5620/10000 [18:01<13:49,  5.28step/s, loss=0.040773, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5621/10000 [18:01<13:48,  5.28step/s, loss=0.040773, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5621/10000 [18:01<13:48,  5.28step/s, loss=0.040753, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5622/10000 [18:01<13:47,  5.29step/s, loss=0.040753, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5622/10000 [18:01<13:47,  5.29step/s, loss=0.041352, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5623/10000 [18:01<13:47,  5.29step/s, loss=0.041352, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5623/10000 [18:01<13:47,  5.29step/s, loss=0.063604, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5624/10000 [18:01<13:47,  5.29step/s, loss=0.063604, elapsed=18.0min]

Entraînement:  56%|█████▌    | 5624/10000 [18:01<13:47,  5.29step/s, loss=0.051482, elapsed=18.0min]

Entraînement:  56%|█████▋    | 5625/10000 [18:01<13:46,  5.30step/s, loss=0.051482, elapsed=18.0min]

Entraînement:  56%|█████▋    | 5625/10000 [18:01<13:46,  5.30step/s, loss=0.030964, elapsed=18.0min]

Entraînement:  56%|█████▋    | 5626/10000 [18:02<13:48,  5.28step/s, loss=0.030964, elapsed=18.0min]

Entraînement:  56%|█████▋    | 5626/10000 [18:02<13:48,  5.28step/s, loss=0.065144, elapsed=18.0min]

Entraînement:  56%|█████▋    | 5627/10000 [18:02<13:48,  5.28step/s, loss=0.065144, elapsed=18.0min]

Entraînement:  56%|█████▋    | 5627/10000 [18:02<13:48,  5.28step/s, loss=0.039081, elapsed=18.0min]

Entraînement:  56%|█████▋    | 5628/10000 [18:02<13:48,  5.28step/s, loss=0.039081, elapsed=18.0min]

Entraînement:  56%|█████▋    | 5628/10000 [18:02<13:48,  5.28step/s, loss=0.119573, elapsed=18.0min]

Entraînement:  56%|█████▋    | 5629/10000 [18:02<13:44,  5.30step/s, loss=0.119573, elapsed=18.0min]

Entraînement:  56%|█████▋    | 5629/10000 [18:02<13:44,  5.30step/s, loss=0.036110, elapsed=18.0min]

Entraînement:  56%|█████▋    | 5630/10000 [18:02<13:44,  5.30step/s, loss=0.036110, elapsed=18.0min]

Entraînement:  56%|█████▋    | 5630/10000 [18:02<13:44,  5.30step/s, loss=0.045486, elapsed=18.0min]

Entraînement:  56%|█████▋    | 5631/10000 [18:03<13:47,  5.28step/s, loss=0.045486, elapsed=18.0min]

Entraînement:  56%|█████▋    | 5631/10000 [18:03<13:47,  5.28step/s, loss=0.074711, elapsed=18.1min]

Entraînement:  56%|█████▋    | 5632/10000 [18:03<13:47,  5.28step/s, loss=0.074711, elapsed=18.1min]

Entraînement:  56%|█████▋    | 5632/10000 [18:03<13:47,  5.28step/s, loss=0.042368, elapsed=18.1min]

Entraînement:  56%|█████▋    | 5633/10000 [18:03<13:47,  5.28step/s, loss=0.042368, elapsed=18.1min]

Entraînement:  56%|█████▋    | 5633/10000 [18:03<13:47,  5.28step/s, loss=0.042342, elapsed=18.1min]

Entraînement:  56%|█████▋    | 5634/10000 [18:03<13:48,  5.27step/s, loss=0.042342, elapsed=18.1min]

Entraînement:  56%|█████▋    | 5634/10000 [18:03<13:48,  5.27step/s, loss=0.030317, elapsed=18.1min]

Entraînement:  56%|█████▋    | 5635/10000 [18:03<13:48,  5.27step/s, loss=0.030317, elapsed=18.1min]

Entraînement:  56%|█████▋    | 5635/10000 [18:03<13:48,  5.27step/s, loss=0.060379, elapsed=18.1min]

Entraînement:  56%|█████▋    | 5636/10000 [18:04<13:49,  5.26step/s, loss=0.060379, elapsed=18.1min]

Entraînement:  56%|█████▋    | 5636/10000 [18:04<13:49,  5.26step/s, loss=0.035766, elapsed=18.1min]

Entraînement:  56%|█████▋    | 5637/10000 [18:04<13:47,  5.28step/s, loss=0.035766, elapsed=18.1min]

Entraînement:  56%|█████▋    | 5637/10000 [18:04<13:47,  5.28step/s, loss=0.060412, elapsed=18.1min]

Entraînement:  56%|█████▋    | 5638/10000 [18:04<13:47,  5.27step/s, loss=0.060412, elapsed=18.1min]

Entraînement:  56%|█████▋    | 5638/10000 [18:04<13:47,  5.27step/s, loss=0.022696, elapsed=18.1min]

Entraînement:  56%|█████▋    | 5639/10000 [18:04<13:46,  5.28step/s, loss=0.022696, elapsed=18.1min]

Entraînement:  56%|█████▋    | 5639/10000 [18:04<13:46,  5.28step/s, loss=0.029672, elapsed=18.1min]

Entraînement:  56%|█████▋    | 5640/10000 [18:04<13:47,  5.27step/s, loss=0.029672, elapsed=18.1min]

Entraînement:  56%|█████▋    | 5640/10000 [18:04<13:47,  5.27step/s, loss=0.049414, elapsed=18.1min]

Entraînement:  56%|█████▋    | 5641/10000 [18:04<13:46,  5.27step/s, loss=0.049414, elapsed=18.1min]

Entraînement:  56%|█████▋    | 5641/10000 [18:04<13:46,  5.27step/s, loss=0.050475, elapsed=18.1min]

Entraînement:  56%|█████▋    | 5642/10000 [18:05<13:48,  5.26step/s, loss=0.050475, elapsed=18.1min]

Entraînement:  56%|█████▋    | 5642/10000 [18:05<13:48,  5.26step/s, loss=0.026923, elapsed=18.1min]

Entraînement:  56%|█████▋    | 5643/10000 [18:05<13:47,  5.27step/s, loss=0.026923, elapsed=18.1min]

Entraînement:  56%|█████▋    | 5643/10000 [18:05<13:47,  5.27step/s, loss=0.064541, elapsed=18.1min]

Entraînement:  56%|█████▋    | 5644/10000 [18:05<13:47,  5.26step/s, loss=0.064541, elapsed=18.1min]

Entraînement:  56%|█████▋    | 5644/10000 [18:05<13:47,  5.26step/s, loss=0.056998, elapsed=18.1min]

Entraînement:  56%|█████▋    | 5645/10000 [18:05<13:47,  5.26step/s, loss=0.056998, elapsed=18.1min]

Entraînement:  56%|█████▋    | 5645/10000 [18:05<13:47,  5.26step/s, loss=0.058697, elapsed=18.1min]

Entraînement:  56%|█████▋    | 5646/10000 [18:05<13:45,  5.27step/s, loss=0.058697, elapsed=18.1min]

Entraînement:  56%|█████▋    | 5646/10000 [18:05<13:45,  5.27step/s, loss=0.077374, elapsed=18.1min]

Entraînement:  56%|█████▋    | 5647/10000 [18:06<13:41,  5.30step/s, loss=0.077374, elapsed=18.1min]

Entraînement:  56%|█████▋    | 5647/10000 [18:06<13:41,  5.30step/s, loss=0.041046, elapsed=18.1min]

Entraînement:  56%|█████▋    | 5648/10000 [18:06<13:42,  5.29step/s, loss=0.041046, elapsed=18.1min]

Entraînement:  56%|█████▋    | 5648/10000 [18:06<13:42,  5.29step/s, loss=0.032056, elapsed=18.1min]

Entraînement:  56%|█████▋    | 5649/10000 [18:06<13:42,  5.29step/s, loss=0.032056, elapsed=18.1min]

Entraînement:  56%|█████▋    | 5649/10000 [18:06<13:42,  5.29step/s, loss=0.078700, elapsed=18.1min]

Entraînement:  56%|█████▋    | 5650/10000 [18:06<13:44,  5.28step/s, loss=0.078700, elapsed=18.1min]

Entraînement:  56%|█████▋    | 5650/10000 [18:06<13:44,  5.28step/s, loss=0.031228, elapsed=18.1min]

Entraînement:  57%|█████▋    | 5651/10000 [18:06<13:44,  5.28step/s, loss=0.031228, elapsed=18.1min]

Entraînement:  57%|█████▋    | 5651/10000 [18:06<13:44,  5.28step/s, loss=0.115288, elapsed=18.1min]

Entraînement:  57%|█████▋    | 5652/10000 [18:07<13:42,  5.29step/s, loss=0.115288, elapsed=18.1min]

Entraînement:  57%|█████▋    | 5652/10000 [18:07<13:42,  5.29step/s, loss=0.042385, elapsed=18.1min]

Entraînement:  57%|█████▋    | 5653/10000 [18:07<13:42,  5.28step/s, loss=0.042385, elapsed=18.1min]

Entraînement:  57%|█████▋    | 5653/10000 [18:07<13:42,  5.28step/s, loss=0.045087, elapsed=18.1min]

Entraînement:  57%|█████▋    | 5654/10000 [18:07<13:42,  5.28step/s, loss=0.045087, elapsed=18.1min]

Entraînement:  57%|█████▋    | 5654/10000 [18:07<13:42,  5.28step/s, loss=0.025573, elapsed=18.1min]

Entraînement:  57%|█████▋    | 5655/10000 [18:07<13:42,  5.28step/s, loss=0.025573, elapsed=18.1min]

Entraînement:  57%|█████▋    | 5655/10000 [18:07<13:42,  5.28step/s, loss=0.039823, elapsed=18.1min]

Entraînement:  57%|█████▋    | 5656/10000 [18:07<13:42,  5.28step/s, loss=0.039823, elapsed=18.1min]

Entraînement:  57%|█████▋    | 5656/10000 [18:07<13:42,  5.28step/s, loss=0.066313, elapsed=18.1min]

Entraînement:  57%|█████▋    | 5657/10000 [18:08<13:42,  5.28step/s, loss=0.066313, elapsed=18.1min]

Entraînement:  57%|█████▋    | 5657/10000 [18:08<13:42,  5.28step/s, loss=0.056532, elapsed=18.1min]

Entraînement:  57%|█████▋    | 5658/10000 [18:08<13:43,  5.27step/s, loss=0.056532, elapsed=18.1min]

Entraînement:  57%|█████▋    | 5658/10000 [18:08<13:43,  5.27step/s, loss=0.022427, elapsed=18.1min]

Entraînement:  57%|█████▋    | 5659/10000 [18:08<13:42,  5.28step/s, loss=0.022427, elapsed=18.1min]

Entraînement:  57%|█████▋    | 5659/10000 [18:08<13:42,  5.28step/s, loss=0.071437, elapsed=18.1min]

Entraînement:  57%|█████▋    | 5660/10000 [18:08<13:43,  5.27step/s, loss=0.071437, elapsed=18.1min]

Entraînement:  57%|█████▋    | 5660/10000 [18:08<13:43,  5.27step/s, loss=0.035665, elapsed=18.1min]

Entraînement:  57%|█████▋    | 5661/10000 [18:08<13:42,  5.27step/s, loss=0.035665, elapsed=18.1min]

Entraînement:  57%|█████▋    | 5661/10000 [18:08<13:42,  5.27step/s, loss=0.026957, elapsed=18.1min]

Entraînement:  57%|█████▋    | 5662/10000 [18:08<13:42,  5.27step/s, loss=0.026957, elapsed=18.1min]

Entraînement:  57%|█████▋    | 5662/10000 [18:08<13:42,  5.27step/s, loss=0.037852, elapsed=18.1min]

Entraînement:  57%|█████▋    | 5663/10000 [18:09<13:43,  5.27step/s, loss=0.037852, elapsed=18.1min]

Entraînement:  57%|█████▋    | 5663/10000 [18:09<13:43,  5.27step/s, loss=0.046386, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5664/10000 [18:09<13:43,  5.27step/s, loss=0.046386, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5664/10000 [18:09<13:43,  5.27step/s, loss=0.026354, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5665/10000 [18:09<13:43,  5.27step/s, loss=0.026354, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5665/10000 [18:09<13:43,  5.27step/s, loss=0.026968, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5666/10000 [18:09<13:43,  5.26step/s, loss=0.026968, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5666/10000 [18:09<13:43,  5.26step/s, loss=0.025335, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5667/10000 [18:09<13:43,  5.26step/s, loss=0.025335, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5667/10000 [18:09<13:43,  5.26step/s, loss=0.037670, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5668/10000 [18:10<13:42,  5.27step/s, loss=0.037670, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5668/10000 [18:10<13:42,  5.27step/s, loss=0.022429, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5669/10000 [18:10<13:42,  5.26step/s, loss=0.022429, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5669/10000 [18:10<13:42,  5.26step/s, loss=0.083212, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5670/10000 [18:10<13:40,  5.28step/s, loss=0.083212, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5670/10000 [18:10<13:40,  5.28step/s, loss=0.051401, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5671/10000 [18:10<13:39,  5.28step/s, loss=0.051401, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5671/10000 [18:10<13:39,  5.28step/s, loss=0.126491, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5672/10000 [18:10<13:39,  5.28step/s, loss=0.126491, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5672/10000 [18:10<13:39,  5.28step/s, loss=0.032416, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5673/10000 [18:11<13:39,  5.28step/s, loss=0.032416, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5673/10000 [18:11<13:39,  5.28step/s, loss=0.031065, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5674/10000 [18:11<13:39,  5.28step/s, loss=0.031065, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5674/10000 [18:11<13:39,  5.28step/s, loss=0.050382, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5675/10000 [18:11<13:38,  5.28step/s, loss=0.050382, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5675/10000 [18:11<13:38,  5.28step/s, loss=0.105848, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5676/10000 [18:11<13:38,  5.28step/s, loss=0.105848, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5676/10000 [18:11<13:38,  5.28step/s, loss=0.058418, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5677/10000 [18:11<13:38,  5.28step/s, loss=0.058418, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5677/10000 [18:11<13:38,  5.28step/s, loss=0.030313, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5678/10000 [18:12<20:35,  3.50step/s, loss=0.030313, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5678/10000 [18:12<20:35,  3.50step/s, loss=0.044863, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5679/10000 [18:12<18:34,  3.88step/s, loss=0.044863, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5679/10000 [18:12<18:34,  3.88step/s, loss=0.038450, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5680/10000 [18:12<17:06,  4.21step/s, loss=0.038450, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5680/10000 [18:12<17:06,  4.21step/s, loss=0.055112, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5681/10000 [18:12<16:05,  4.47step/s, loss=0.055112, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5681/10000 [18:12<16:05,  4.47step/s, loss=0.045981, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5682/10000 [18:13<15:22,  4.68step/s, loss=0.045981, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5682/10000 [18:13<15:22,  4.68step/s, loss=0.062756, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5683/10000 [18:13<14:51,  4.84step/s, loss=0.062756, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5683/10000 [18:13<14:51,  4.84step/s, loss=0.045879, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5684/10000 [18:13<14:29,  4.97step/s, loss=0.045879, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5684/10000 [18:13<14:29,  4.97step/s, loss=0.044177, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5685/10000 [18:13<14:14,  5.05step/s, loss=0.044177, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5685/10000 [18:13<14:14,  5.05step/s, loss=0.043068, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5686/10000 [18:13<14:03,  5.11step/s, loss=0.043068, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5686/10000 [18:13<14:03,  5.11step/s, loss=0.046269, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5687/10000 [18:14<13:54,  5.17step/s, loss=0.046269, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5687/10000 [18:14<13:54,  5.17step/s, loss=0.054422, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5688/10000 [18:14<13:49,  5.20step/s, loss=0.054422, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5688/10000 [18:14<13:49,  5.20step/s, loss=0.037215, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5689/10000 [18:14<13:48,  5.20step/s, loss=0.037215, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5689/10000 [18:14<13:48,  5.20step/s, loss=0.050071, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5690/10000 [18:14<13:47,  5.21step/s, loss=0.050071, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5690/10000 [18:14<13:47,  5.21step/s, loss=0.026868, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5691/10000 [18:14<13:44,  5.23step/s, loss=0.026868, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5691/10000 [18:14<13:44,  5.23step/s, loss=0.040496, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5692/10000 [18:14<13:42,  5.24step/s, loss=0.040496, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5692/10000 [18:14<13:42,  5.24step/s, loss=0.035435, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5693/10000 [18:15<13:40,  5.25step/s, loss=0.035435, elapsed=18.2min]

Entraînement:  57%|█████▋    | 5693/10000 [18:15<13:40,  5.25step/s, loss=0.050107, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5694/10000 [18:15<13:38,  5.26step/s, loss=0.050107, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5694/10000 [18:15<13:38,  5.26step/s, loss=0.106789, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5695/10000 [18:15<13:41,  5.24step/s, loss=0.106789, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5695/10000 [18:15<13:41,  5.24step/s, loss=0.052992, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5696/10000 [18:15<13:38,  5.26step/s, loss=0.052992, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5696/10000 [18:15<13:38,  5.26step/s, loss=0.062904, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5697/10000 [18:15<13:38,  5.26step/s, loss=0.062904, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5697/10000 [18:15<13:38,  5.26step/s, loss=0.064840, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5698/10000 [18:16<13:37,  5.26step/s, loss=0.064840, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5698/10000 [18:16<13:37,  5.26step/s, loss=0.035142, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5699/10000 [18:16<13:37,  5.26step/s, loss=0.035142, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5699/10000 [18:16<13:37,  5.26step/s, loss=0.034095, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5700/10000 [18:16<13:37,  5.26step/s, loss=0.034095, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5700/10000 [18:16<13:37,  5.26step/s, loss=0.021532, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5700/10000 [18:16<13:37,  5.26step/s, loss=0.021532, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5701/10000 [18:16<13:45,  5.21step/s, loss=0.021532, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5701/10000 [18:16<13:45,  5.21step/s, loss=0.022155, elapsed=18.3min]

Step 5700/10000 | Train loss: 0.021532 | Elapsed: 18.3min | ETA: 13.8min

Entraînement:  57%|█████▋    | 5702/10000 [18:16<13:41,  5.23step/s, loss=0.022155, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5702/10000 [18:16<13:41,  5.23step/s, loss=0.090505, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5703/10000 [18:17<13:40,  5.24step/s, loss=0.090505, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5703/10000 [18:17<13:40,  5.24step/s, loss=0.029326, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5704/10000 [18:17<13:39,  5.24step/s, loss=0.029326, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5704/10000 [18:17<13:39,  5.24step/s, loss=0.073407, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5705/10000 [18:17<13:38,  5.25step/s, loss=0.073407, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5705/10000 [18:17<13:38,  5.25step/s, loss=0.044294, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5706/10000 [18:17<13:36,  5.26step/s, loss=0.044294, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5706/10000 [18:17<13:36,  5.26step/s, loss=0.038386, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5707/10000 [18:17<13:35,  5.27step/s, loss=0.038386, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5707/10000 [18:17<13:35,  5.27step/s, loss=0.082242, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5708/10000 [18:18<13:34,  5.27step/s, loss=0.082242, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5708/10000 [18:18<13:34,  5.27step/s, loss=0.038784, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5709/10000 [18:18<13:31,  5.29step/s, loss=0.038784, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5709/10000 [18:18<13:31,  5.29step/s, loss=0.054071, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5710/10000 [18:18<13:28,  5.31step/s, loss=0.054071, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5710/10000 [18:18<13:28,  5.31step/s, loss=0.025271, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5711/10000 [18:18<13:28,  5.31step/s, loss=0.025271, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5711/10000 [18:18<13:28,  5.31step/s, loss=0.120654, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5712/10000 [18:18<13:28,  5.31step/s, loss=0.120654, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5712/10000 [18:18<13:28,  5.31step/s, loss=0.043769, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5713/10000 [18:18<13:29,  5.30step/s, loss=0.043769, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5713/10000 [18:18<13:29,  5.30step/s, loss=0.026592, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5714/10000 [18:19<13:30,  5.29step/s, loss=0.026592, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5714/10000 [18:19<13:30,  5.29step/s, loss=0.040857, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5715/10000 [18:19<13:29,  5.30step/s, loss=0.040857, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5715/10000 [18:19<13:29,  5.30step/s, loss=0.039072, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5716/10000 [18:19<13:30,  5.29step/s, loss=0.039072, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5716/10000 [18:19<13:30,  5.29step/s, loss=0.064151, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5717/10000 [18:19<13:29,  5.29step/s, loss=0.064151, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5717/10000 [18:19<13:29,  5.29step/s, loss=0.063857, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5718/10000 [18:19<13:29,  5.29step/s, loss=0.063857, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5718/10000 [18:19<13:29,  5.29step/s, loss=0.046633, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5719/10000 [18:20<13:29,  5.29step/s, loss=0.046633, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5719/10000 [18:20<13:29,  5.29step/s, loss=0.073019, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5720/10000 [18:20<13:30,  5.28step/s, loss=0.073019, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5720/10000 [18:20<13:30,  5.28step/s, loss=0.050480, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5721/10000 [18:20<13:30,  5.28step/s, loss=0.050480, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5721/10000 [18:20<13:30,  5.28step/s, loss=0.054122, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5722/10000 [18:20<13:29,  5.28step/s, loss=0.054122, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5722/10000 [18:20<13:29,  5.28step/s, loss=0.080303, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5723/10000 [18:20<13:29,  5.28step/s, loss=0.080303, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5723/10000 [18:20<13:29,  5.28step/s, loss=0.044076, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5724/10000 [18:21<13:28,  5.29step/s, loss=0.044076, elapsed=18.3min]

Entraînement:  57%|█████▋    | 5724/10000 [18:21<13:28,  5.29step/s, loss=0.019132, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5725/10000 [18:21<13:27,  5.30step/s, loss=0.019132, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5725/10000 [18:21<13:27,  5.30step/s, loss=0.033709, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5726/10000 [18:21<13:27,  5.29step/s, loss=0.033709, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5726/10000 [18:21<13:27,  5.29step/s, loss=0.052078, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5727/10000 [18:21<13:26,  5.30step/s, loss=0.052078, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5727/10000 [18:21<13:26,  5.30step/s, loss=0.026380, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5728/10000 [18:21<13:28,  5.29step/s, loss=0.026380, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5728/10000 [18:21<13:28,  5.29step/s, loss=0.040595, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5729/10000 [18:21<13:27,  5.29step/s, loss=0.040595, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5729/10000 [18:21<13:27,  5.29step/s, loss=0.031234, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5730/10000 [18:22<13:27,  5.29step/s, loss=0.031234, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5730/10000 [18:22<13:27,  5.29step/s, loss=0.026115, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5731/10000 [18:22<13:27,  5.29step/s, loss=0.026115, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5731/10000 [18:22<13:27,  5.29step/s, loss=0.034465, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5732/10000 [18:22<13:26,  5.29step/s, loss=0.034465, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5732/10000 [18:22<13:26,  5.29step/s, loss=0.051562, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5733/10000 [18:22<13:27,  5.29step/s, loss=0.051562, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5733/10000 [18:22<13:27,  5.29step/s, loss=0.034648, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5734/10000 [18:22<13:27,  5.28step/s, loss=0.034648, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5734/10000 [18:22<13:27,  5.28step/s, loss=0.092255, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5735/10000 [18:23<13:27,  5.28step/s, loss=0.092255, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5735/10000 [18:23<13:27,  5.28step/s, loss=0.037633, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5736/10000 [18:23<13:30,  5.26step/s, loss=0.037633, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5736/10000 [18:23<13:30,  5.26step/s, loss=0.051636, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5737/10000 [18:23<13:29,  5.26step/s, loss=0.051636, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5737/10000 [18:23<13:29,  5.26step/s, loss=0.066399, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5738/10000 [18:23<13:29,  5.26step/s, loss=0.066399, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5738/10000 [18:23<13:29,  5.26step/s, loss=0.104931, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5739/10000 [18:23<13:32,  5.24step/s, loss=0.104931, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5739/10000 [18:23<13:32,  5.24step/s, loss=0.039537, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5740/10000 [18:24<13:31,  5.25step/s, loss=0.039537, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5740/10000 [18:24<13:31,  5.25step/s, loss=0.046669, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5741/10000 [18:24<13:28,  5.27step/s, loss=0.046669, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5741/10000 [18:24<13:28,  5.27step/s, loss=0.058986, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5742/10000 [18:24<13:25,  5.29step/s, loss=0.058986, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5742/10000 [18:24<13:25,  5.29step/s, loss=0.113808, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5743/10000 [18:24<13:26,  5.28step/s, loss=0.113808, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5743/10000 [18:24<13:26,  5.28step/s, loss=0.035524, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5744/10000 [18:24<13:27,  5.27step/s, loss=0.035524, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5744/10000 [18:24<13:27,  5.27step/s, loss=0.038396, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5745/10000 [18:25<13:26,  5.27step/s, loss=0.038396, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5745/10000 [18:25<13:26,  5.27step/s, loss=0.061379, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5746/10000 [18:25<13:26,  5.28step/s, loss=0.061379, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5746/10000 [18:25<13:26,  5.28step/s, loss=0.048051, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5747/10000 [18:25<13:26,  5.27step/s, loss=0.048051, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5747/10000 [18:25<13:26,  5.27step/s, loss=0.053924, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5748/10000 [18:25<13:26,  5.27step/s, loss=0.053924, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5748/10000 [18:25<13:26,  5.27step/s, loss=0.047444, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5749/10000 [18:25<13:26,  5.27step/s, loss=0.047444, elapsed=18.4min]

Entraînement:  57%|█████▋    | 5749/10000 [18:25<13:26,  5.27step/s, loss=0.103719, elapsed=18.4min]

Entraînement:  57%|█████▊    | 5750/10000 [18:25<13:26,  5.27step/s, loss=0.103719, elapsed=18.4min]

Entraînement:  57%|█████▊    | 5750/10000 [18:25<13:26,  5.27step/s, loss=0.040047, elapsed=18.4min]

Entraînement:  58%|█████▊    | 5751/10000 [18:26<13:27,  5.26step/s, loss=0.040047, elapsed=18.4min]

Entraînement:  58%|█████▊    | 5751/10000 [18:26<13:27,  5.26step/s, loss=0.075778, elapsed=18.4min]

Entraînement:  58%|█████▊    | 5752/10000 [18:26<13:27,  5.26step/s, loss=0.075778, elapsed=18.4min]

Entraînement:  58%|█████▊    | 5752/10000 [18:26<13:27,  5.26step/s, loss=0.069360, elapsed=18.4min]

Entraînement:  58%|█████▊    | 5753/10000 [18:26<13:27,  5.26step/s, loss=0.069360, elapsed=18.4min]

Entraînement:  58%|█████▊    | 5753/10000 [18:26<13:27,  5.26step/s, loss=0.072202, elapsed=18.4min]

Entraînement:  58%|█████▊    | 5754/10000 [18:26<13:26,  5.26step/s, loss=0.072202, elapsed=18.4min]

Entraînement:  58%|█████▊    | 5754/10000 [18:26<13:26,  5.26step/s, loss=0.048661, elapsed=18.4min]

Entraînement:  58%|█████▊    | 5755/10000 [18:26<13:26,  5.26step/s, loss=0.048661, elapsed=18.4min]

Entraînement:  58%|█████▊    | 5755/10000 [18:26<13:26,  5.26step/s, loss=0.107692, elapsed=18.4min]

Entraînement:  58%|█████▊    | 5756/10000 [18:27<13:24,  5.27step/s, loss=0.107692, elapsed=18.4min]

Entraînement:  58%|█████▊    | 5756/10000 [18:27<13:24,  5.27step/s, loss=0.052941, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5757/10000 [18:27<13:26,  5.26step/s, loss=0.052941, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5757/10000 [18:27<13:26,  5.26step/s, loss=0.127886, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5758/10000 [18:27<13:24,  5.27step/s, loss=0.127886, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5758/10000 [18:27<13:24,  5.27step/s, loss=0.044004, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5759/10000 [18:27<13:25,  5.27step/s, loss=0.044004, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5759/10000 [18:27<13:25,  5.27step/s, loss=0.023127, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5760/10000 [18:27<13:24,  5.27step/s, loss=0.023127, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5760/10000 [18:27<13:24,  5.27step/s, loss=0.103798, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5761/10000 [18:28<13:23,  5.27step/s, loss=0.103798, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5761/10000 [18:28<13:23,  5.27step/s, loss=0.033708, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5762/10000 [18:28<13:23,  5.27step/s, loss=0.033708, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5762/10000 [18:28<13:23,  5.27step/s, loss=0.119102, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5763/10000 [18:28<13:23,  5.27step/s, loss=0.119102, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5763/10000 [18:28<13:23,  5.27step/s, loss=0.038617, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5764/10000 [18:28<13:21,  5.28step/s, loss=0.038617, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5764/10000 [18:28<13:21,  5.28step/s, loss=0.083151, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5765/10000 [18:28<13:22,  5.27step/s, loss=0.083151, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5765/10000 [18:28<13:22,  5.27step/s, loss=0.094240, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5766/10000 [18:29<13:22,  5.28step/s, loss=0.094240, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5766/10000 [18:29<13:22,  5.28step/s, loss=0.074718, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5767/10000 [18:29<13:22,  5.27step/s, loss=0.074718, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5767/10000 [18:29<13:22,  5.27step/s, loss=0.104108, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5768/10000 [18:29<13:24,  5.26step/s, loss=0.104108, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5768/10000 [18:29<13:24,  5.26step/s, loss=0.061229, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5769/10000 [18:29<13:23,  5.27step/s, loss=0.061229, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5769/10000 [18:29<13:23,  5.27step/s, loss=0.042766, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5770/10000 [18:29<13:23,  5.26step/s, loss=0.042766, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5770/10000 [18:29<13:23,  5.26step/s, loss=0.066227, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5771/10000 [18:29<13:23,  5.26step/s, loss=0.066227, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5771/10000 [18:29<13:23,  5.26step/s, loss=0.071791, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5772/10000 [18:30<13:21,  5.27step/s, loss=0.071791, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5772/10000 [18:30<13:21,  5.27step/s, loss=0.031362, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5773/10000 [18:30<13:19,  5.29step/s, loss=0.031362, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5773/10000 [18:30<13:19,  5.29step/s, loss=0.069921, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5774/10000 [18:30<13:21,  5.27step/s, loss=0.069921, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5774/10000 [18:30<13:21,  5.27step/s, loss=0.100831, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5775/10000 [18:30<13:21,  5.27step/s, loss=0.100831, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5775/10000 [18:30<13:21,  5.27step/s, loss=0.082553, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5776/10000 [18:30<13:20,  5.28step/s, loss=0.082553, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5776/10000 [18:30<13:20,  5.28step/s, loss=0.074729, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5777/10000 [18:31<13:20,  5.27step/s, loss=0.074729, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5777/10000 [18:31<13:20,  5.27step/s, loss=0.033978, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5778/10000 [18:31<13:20,  5.27step/s, loss=0.033978, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5778/10000 [18:31<13:20,  5.27step/s, loss=0.035450, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5779/10000 [18:31<13:20,  5.28step/s, loss=0.035450, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5779/10000 [18:31<13:20,  5.28step/s, loss=0.090389, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5780/10000 [18:31<13:19,  5.28step/s, loss=0.090389, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5780/10000 [18:31<13:19,  5.28step/s, loss=0.095084, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5781/10000 [18:31<13:17,  5.29step/s, loss=0.095084, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5781/10000 [18:31<13:17,  5.29step/s, loss=0.089746, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5782/10000 [18:32<13:20,  5.27step/s, loss=0.089746, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5782/10000 [18:32<13:20,  5.27step/s, loss=0.034753, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5783/10000 [18:32<13:20,  5.27step/s, loss=0.034753, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5783/10000 [18:32<13:20,  5.27step/s, loss=0.056144, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5784/10000 [18:32<13:19,  5.27step/s, loss=0.056144, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5784/10000 [18:32<13:19,  5.27step/s, loss=0.035519, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5785/10000 [18:32<13:25,  5.23step/s, loss=0.035519, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5785/10000 [18:32<13:25,  5.23step/s, loss=0.076167, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5786/10000 [18:32<13:25,  5.23step/s, loss=0.076167, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5786/10000 [18:32<13:25,  5.23step/s, loss=0.082952, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5787/10000 [18:33<13:28,  5.21step/s, loss=0.082952, elapsed=18.5min]

Entraînement:  58%|█████▊    | 5787/10000 [18:33<13:28,  5.21step/s, loss=0.044838, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5788/10000 [18:33<13:27,  5.22step/s, loss=0.044838, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5788/10000 [18:33<13:27,  5.22step/s, loss=0.058754, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5789/10000 [18:33<13:25,  5.23step/s, loss=0.058754, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5789/10000 [18:33<13:25,  5.23step/s, loss=0.039653, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5790/10000 [18:33<13:23,  5.24step/s, loss=0.039653, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5790/10000 [18:33<13:23,  5.24step/s, loss=0.043015, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5791/10000 [18:33<13:22,  5.25step/s, loss=0.043015, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5791/10000 [18:33<13:22,  5.25step/s, loss=0.031751, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5792/10000 [18:33<13:33,  5.18step/s, loss=0.031751, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5792/10000 [18:33<13:33,  5.18step/s, loss=0.046609, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5793/10000 [18:34<13:31,  5.18step/s, loss=0.046609, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5793/10000 [18:34<13:31,  5.18step/s, loss=0.025019, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5794/10000 [18:34<13:28,  5.20step/s, loss=0.025019, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5794/10000 [18:34<13:28,  5.20step/s, loss=0.075509, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5795/10000 [18:34<13:25,  5.22step/s, loss=0.075509, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5795/10000 [18:34<13:25,  5.22step/s, loss=0.075902, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5796/10000 [18:34<13:24,  5.22step/s, loss=0.075902, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5796/10000 [18:34<13:24,  5.22step/s, loss=0.088183, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5797/10000 [18:34<13:23,  5.23step/s, loss=0.088183, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5797/10000 [18:34<13:23,  5.23step/s, loss=0.068477, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5798/10000 [18:35<13:20,  5.25step/s, loss=0.068477, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5798/10000 [18:35<13:20,  5.25step/s, loss=0.024133, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5799/10000 [18:35<13:19,  5.25step/s, loss=0.024133, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5799/10000 [18:35<13:19,  5.25step/s, loss=0.025284, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5800/10000 [18:35<13:21,  5.24step/s, loss=0.025284, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5800/10000 [18:35<13:21,  5.24step/s, loss=0.062516, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5800/10000 [18:35<13:21,  5.24step/s, loss=0.062516, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5801/10000 [18:35<13:32,  5.17step/s, loss=0.062516, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5801/10000 [18:35<13:32,  5.17step/s, loss=0.022718, elapsed=18.6min]

Step 5800/10000 | Train loss: 0.062516 | Elapsed: 18.6min | ETA: 13.5min

Entraînement:  58%|█████▊    | 5802/10000 [18:35<13:28,  5.19step/s, loss=0.022718, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5802/10000 [18:35<13:28,  5.19step/s, loss=0.057490, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5803/10000 [18:36<13:24,  5.22step/s, loss=0.057490, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5803/10000 [18:36<13:24,  5.22step/s, loss=0.094149, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5804/10000 [18:36<13:23,  5.22step/s, loss=0.094149, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5804/10000 [18:36<13:23,  5.22step/s, loss=0.056886, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5805/10000 [18:36<13:21,  5.23step/s, loss=0.056886, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5805/10000 [18:36<13:21,  5.23step/s, loss=0.034735, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5806/10000 [18:36<13:20,  5.24step/s, loss=0.034735, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5806/10000 [18:36<13:20,  5.24step/s, loss=0.079166, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5807/10000 [18:36<13:17,  5.26step/s, loss=0.079166, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5807/10000 [18:36<13:17,  5.26step/s, loss=0.025095, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5808/10000 [18:37<13:15,  5.27step/s, loss=0.025095, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5808/10000 [18:37<13:15,  5.27step/s, loss=0.027546, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5809/10000 [18:37<13:15,  5.27step/s, loss=0.027546, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5809/10000 [18:37<13:15,  5.27step/s, loss=0.038585, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5810/10000 [18:37<13:15,  5.26step/s, loss=0.038585, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5810/10000 [18:37<13:15,  5.26step/s, loss=0.067859, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5811/10000 [18:37<13:15,  5.27step/s, loss=0.067859, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5811/10000 [18:37<13:15,  5.27step/s, loss=0.046046, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5812/10000 [18:37<13:14,  5.27step/s, loss=0.046046, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5812/10000 [18:37<13:14,  5.27step/s, loss=0.023707, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5813/10000 [18:37<13:13,  5.28step/s, loss=0.023707, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5813/10000 [18:37<13:13,  5.28step/s, loss=0.034045, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5814/10000 [18:38<13:13,  5.28step/s, loss=0.034045, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5814/10000 [18:38<13:13,  5.28step/s, loss=0.048225, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5815/10000 [18:38<13:12,  5.28step/s, loss=0.048225, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5815/10000 [18:38<13:12,  5.28step/s, loss=0.059805, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5816/10000 [18:38<13:13,  5.27step/s, loss=0.059805, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5816/10000 [18:38<13:13,  5.27step/s, loss=0.107978, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5817/10000 [18:38<13:20,  5.23step/s, loss=0.107978, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5817/10000 [18:38<13:20,  5.23step/s, loss=0.036082, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5818/10000 [18:38<13:18,  5.23step/s, loss=0.036082, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5818/10000 [18:38<13:18,  5.23step/s, loss=0.060552, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5819/10000 [18:39<13:18,  5.23step/s, loss=0.060552, elapsed=18.6min]

Entraînement:  58%|█████▊    | 5819/10000 [18:39<13:18,  5.23step/s, loss=0.038700, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5820/10000 [18:39<13:18,  5.23step/s, loss=0.038700, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5820/10000 [18:39<13:18,  5.23step/s, loss=0.058155, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5821/10000 [18:39<13:16,  5.25step/s, loss=0.058155, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5821/10000 [18:39<13:16,  5.25step/s, loss=0.058782, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5822/10000 [18:39<13:14,  5.26step/s, loss=0.058782, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5822/10000 [18:39<13:14,  5.26step/s, loss=0.090266, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5823/10000 [18:39<13:14,  5.26step/s, loss=0.090266, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5823/10000 [18:39<13:14,  5.26step/s, loss=0.034382, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5824/10000 [18:40<13:13,  5.26step/s, loss=0.034382, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5824/10000 [18:40<13:13,  5.26step/s, loss=0.023252, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5825/10000 [18:40<13:12,  5.27step/s, loss=0.023252, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5825/10000 [18:40<13:12,  5.27step/s, loss=0.045779, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5826/10000 [18:40<13:11,  5.27step/s, loss=0.045779, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5826/10000 [18:40<13:11,  5.27step/s, loss=0.029031, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5827/10000 [18:40<13:12,  5.27step/s, loss=0.029031, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5827/10000 [18:40<13:12,  5.27step/s, loss=0.042595, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5828/10000 [18:40<13:10,  5.28step/s, loss=0.042595, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5828/10000 [18:40<13:10,  5.28step/s, loss=0.064778, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5829/10000 [18:41<13:10,  5.28step/s, loss=0.064778, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5829/10000 [18:41<13:10,  5.28step/s, loss=0.024941, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5830/10000 [18:41<13:08,  5.29step/s, loss=0.024941, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5830/10000 [18:41<13:08,  5.29step/s, loss=0.025012, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5831/10000 [18:41<13:07,  5.29step/s, loss=0.025012, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5831/10000 [18:41<13:07,  5.29step/s, loss=0.034116, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5832/10000 [18:41<13:07,  5.29step/s, loss=0.034116, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5832/10000 [18:41<13:07,  5.29step/s, loss=0.048472, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5833/10000 [18:41<13:08,  5.29step/s, loss=0.048472, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5833/10000 [18:41<13:08,  5.29step/s, loss=0.081020, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5834/10000 [18:41<13:08,  5.28step/s, loss=0.081020, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5834/10000 [18:41<13:08,  5.28step/s, loss=0.063454, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5835/10000 [18:42<13:08,  5.28step/s, loss=0.063454, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5835/10000 [18:42<13:08,  5.28step/s, loss=0.038385, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5836/10000 [18:42<13:06,  5.30step/s, loss=0.038385, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5836/10000 [18:42<13:06,  5.30step/s, loss=0.026793, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5837/10000 [18:42<13:06,  5.29step/s, loss=0.026793, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5837/10000 [18:42<13:06,  5.29step/s, loss=0.102127, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5838/10000 [18:42<13:06,  5.29step/s, loss=0.102127, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5838/10000 [18:42<13:06,  5.29step/s, loss=0.064854, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5839/10000 [18:42<13:06,  5.29step/s, loss=0.064854, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5839/10000 [18:42<13:06,  5.29step/s, loss=0.048826, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5840/10000 [18:43<13:06,  5.29step/s, loss=0.048826, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5840/10000 [18:43<13:06,  5.29step/s, loss=0.040705, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5841/10000 [18:43<13:05,  5.30step/s, loss=0.040705, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5841/10000 [18:43<13:05,  5.30step/s, loss=0.020806, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5842/10000 [18:43<13:06,  5.29step/s, loss=0.020806, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5842/10000 [18:43<13:06,  5.29step/s, loss=0.079162, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5843/10000 [18:43<13:05,  5.29step/s, loss=0.079162, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5843/10000 [18:43<13:05,  5.29step/s, loss=0.053398, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5844/10000 [18:43<13:04,  5.30step/s, loss=0.053398, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5844/10000 [18:43<13:04,  5.30step/s, loss=0.126735, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5845/10000 [18:44<13:04,  5.29step/s, loss=0.126735, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5845/10000 [18:44<13:04,  5.29step/s, loss=0.055456, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5846/10000 [18:44<13:04,  5.30step/s, loss=0.055456, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5846/10000 [18:44<13:04,  5.30step/s, loss=0.039916, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5847/10000 [18:44<13:05,  5.29step/s, loss=0.039916, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5847/10000 [18:44<13:05,  5.29step/s, loss=0.051111, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5848/10000 [18:44<13:06,  5.28step/s, loss=0.051111, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5848/10000 [18:44<13:06,  5.28step/s, loss=0.040880, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5849/10000 [18:44<13:02,  5.31step/s, loss=0.040880, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5849/10000 [18:44<13:02,  5.31step/s, loss=0.065520, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5850/10000 [18:44<13:01,  5.31step/s, loss=0.065520, elapsed=18.7min]

Entraînement:  58%|█████▊    | 5850/10000 [18:44<13:01,  5.31step/s, loss=0.029938, elapsed=18.7min]

Entraînement:  59%|█████▊    | 5851/10000 [18:45<13:03,  5.30step/s, loss=0.029938, elapsed=18.7min]

Entraînement:  59%|█████▊    | 5851/10000 [18:45<13:03,  5.30step/s, loss=0.027861, elapsed=18.8min]

Entraînement:  59%|█████▊    | 5852/10000 [18:45<13:03,  5.29step/s, loss=0.027861, elapsed=18.8min]

Entraînement:  59%|█████▊    | 5852/10000 [18:45<13:03,  5.29step/s, loss=0.053759, elapsed=18.8min]

Entraînement:  59%|█████▊    | 5853/10000 [18:45<13:05,  5.28step/s, loss=0.053759, elapsed=18.8min]

Entraînement:  59%|█████▊    | 5853/10000 [18:45<13:05,  5.28step/s, loss=0.074966, elapsed=18.8min]

Entraînement:  59%|█████▊    | 5854/10000 [18:45<13:05,  5.28step/s, loss=0.074966, elapsed=18.8min]

Entraînement:  59%|█████▊    | 5854/10000 [18:45<13:05,  5.28step/s, loss=0.030963, elapsed=18.8min]

Entraînement:  59%|█████▊    | 5855/10000 [18:45<13:04,  5.29step/s, loss=0.030963, elapsed=18.8min]

Entraînement:  59%|█████▊    | 5855/10000 [18:45<13:04,  5.29step/s, loss=0.060698, elapsed=18.8min]

Entraînement:  59%|█████▊    | 5856/10000 [18:46<13:04,  5.28step/s, loss=0.060698, elapsed=18.8min]

Entraînement:  59%|█████▊    | 5856/10000 [18:46<13:04,  5.28step/s, loss=0.048692, elapsed=18.8min]

Entraînement:  59%|█████▊    | 5857/10000 [18:46<13:04,  5.28step/s, loss=0.048692, elapsed=18.8min]

Entraînement:  59%|█████▊    | 5857/10000 [18:46<13:04,  5.28step/s, loss=0.027718, elapsed=18.8min]

Entraînement:  59%|█████▊    | 5858/10000 [18:46<13:05,  5.27step/s, loss=0.027718, elapsed=18.8min]

Entraînement:  59%|█████▊    | 5858/10000 [18:46<13:05,  5.27step/s, loss=0.049467, elapsed=18.8min]

Entraînement:  59%|█████▊    | 5859/10000 [18:46<13:05,  5.27step/s, loss=0.049467, elapsed=18.8min]

Entraînement:  59%|█████▊    | 5859/10000 [18:46<13:05,  5.27step/s, loss=0.102049, elapsed=18.8min]

Entraînement:  59%|█████▊    | 5860/10000 [18:46<13:04,  5.28step/s, loss=0.102049, elapsed=18.8min]

Entraînement:  59%|█████▊    | 5860/10000 [18:46<13:04,  5.28step/s, loss=0.034987, elapsed=18.8min]

Entraînement:  59%|█████▊    | 5861/10000 [18:47<13:03,  5.28step/s, loss=0.034987, elapsed=18.8min]

Entraînement:  59%|█████▊    | 5861/10000 [18:47<13:03,  5.28step/s, loss=0.042077, elapsed=18.8min]

Entraînement:  59%|█████▊    | 5862/10000 [18:47<13:02,  5.29step/s, loss=0.042077, elapsed=18.8min]

Entraînement:  59%|█████▊    | 5862/10000 [18:47<13:02,  5.29step/s, loss=0.082323, elapsed=18.8min]

Entraînement:  59%|█████▊    | 5863/10000 [18:47<13:02,  5.29step/s, loss=0.082323, elapsed=18.8min]

Entraînement:  59%|█████▊    | 5863/10000 [18:47<13:02,  5.29step/s, loss=0.045284, elapsed=18.8min]

Entraînement:  59%|█████▊    | 5864/10000 [18:47<13:02,  5.28step/s, loss=0.045284, elapsed=18.8min]

Entraînement:  59%|█████▊    | 5864/10000 [18:47<13:02,  5.28step/s, loss=0.013750, elapsed=18.8min]

Entraînement:  59%|█████▊    | 5865/10000 [18:47<13:03,  5.28step/s, loss=0.013750, elapsed=18.8min]

Entraînement:  59%|█████▊    | 5865/10000 [18:47<13:03,  5.28step/s, loss=0.135432, elapsed=18.8min]

Entraînement:  59%|█████▊    | 5866/10000 [18:48<13:03,  5.28step/s, loss=0.135432, elapsed=18.8min]

Entraînement:  59%|█████▊    | 5866/10000 [18:48<13:03,  5.28step/s, loss=0.056299, elapsed=18.8min]

Entraînement:  59%|█████▊    | 5867/10000 [18:48<13:03,  5.28step/s, loss=0.056299, elapsed=18.8min]

Entraînement:  59%|█████▊    | 5867/10000 [18:48<13:03,  5.28step/s, loss=0.051858, elapsed=18.8min]

Entraînement:  59%|█████▊    | 5868/10000 [18:48<13:03,  5.28step/s, loss=0.051858, elapsed=18.8min]

Entraînement:  59%|█████▊    | 5868/10000 [18:48<13:03,  5.28step/s, loss=0.047703, elapsed=18.8min]

Entraînement:  59%|█████▊    | 5869/10000 [18:48<13:01,  5.28step/s, loss=0.047703, elapsed=18.8min]

Entraînement:  59%|█████▊    | 5869/10000 [18:48<13:01,  5.28step/s, loss=0.037901, elapsed=18.8min]

Entraînement:  59%|█████▊    | 5870/10000 [18:48<13:02,  5.28step/s, loss=0.037901, elapsed=18.8min]

Entraînement:  59%|█████▊    | 5870/10000 [18:48<13:02,  5.28step/s, loss=0.068057, elapsed=18.8min]

Entraînement:  59%|█████▊    | 5871/10000 [18:48<13:01,  5.29step/s, loss=0.068057, elapsed=18.8min]

Entraînement:  59%|█████▊    | 5871/10000 [18:48<13:01,  5.29step/s, loss=0.035912, elapsed=18.8min]

Entraînement:  59%|█████▊    | 5872/10000 [18:49<13:08,  5.24step/s, loss=0.035912, elapsed=18.8min]

Entraînement:  59%|█████▊    | 5872/10000 [18:49<13:08,  5.24step/s, loss=0.019973, elapsed=18.8min]

Entraînement:  59%|█████▊    | 5873/10000 [18:49<13:07,  5.24step/s, loss=0.019973, elapsed=18.8min]

Entraînement:  59%|█████▊    | 5873/10000 [18:49<13:07,  5.24step/s, loss=0.055921, elapsed=18.8min]

Entraînement:  59%|█████▊    | 5874/10000 [18:49<13:08,  5.24step/s, loss=0.055921, elapsed=18.8min]

Entraînement:  59%|█████▊    | 5874/10000 [18:49<13:08,  5.24step/s, loss=0.077368, elapsed=18.8min]

Entraînement:  59%|█████▉    | 5875/10000 [18:49<13:06,  5.25step/s, loss=0.077368, elapsed=18.8min]

Entraînement:  59%|█████▉    | 5875/10000 [18:49<13:06,  5.25step/s, loss=0.063916, elapsed=18.8min]

Entraînement:  59%|█████▉    | 5876/10000 [18:49<13:05,  5.25step/s, loss=0.063916, elapsed=18.8min]

Entraînement:  59%|█████▉    | 5876/10000 [18:49<13:05,  5.25step/s, loss=0.045496, elapsed=18.8min]

Entraînement:  59%|█████▉    | 5877/10000 [18:50<13:04,  5.26step/s, loss=0.045496, elapsed=18.8min]

Entraînement:  59%|█████▉    | 5877/10000 [18:50<13:04,  5.26step/s, loss=0.056801, elapsed=18.8min]

Entraînement:  59%|█████▉    | 5878/10000 [18:50<13:02,  5.27step/s, loss=0.056801, elapsed=18.8min]

Entraînement:  59%|█████▉    | 5878/10000 [18:50<13:02,  5.27step/s, loss=0.021661, elapsed=18.8min]

Entraînement:  59%|█████▉    | 5879/10000 [18:50<13:04,  5.25step/s, loss=0.021661, elapsed=18.8min]

Entraînement:  59%|█████▉    | 5879/10000 [18:50<13:04,  5.25step/s, loss=0.032951, elapsed=18.8min]

Entraînement:  59%|█████▉    | 5880/10000 [18:50<13:03,  5.26step/s, loss=0.032951, elapsed=18.8min]

Entraînement:  59%|█████▉    | 5880/10000 [18:50<13:03,  5.26step/s, loss=0.023002, elapsed=18.8min]

Entraînement:  59%|█████▉    | 5881/10000 [18:50<13:04,  5.25step/s, loss=0.023002, elapsed=18.8min]

Entraînement:  59%|█████▉    | 5881/10000 [18:50<13:04,  5.25step/s, loss=0.050630, elapsed=18.8min]

Entraînement:  59%|█████▉    | 5882/10000 [18:51<13:03,  5.26step/s, loss=0.050630, elapsed=18.8min]

Entraînement:  59%|█████▉    | 5882/10000 [18:51<13:03,  5.26step/s, loss=0.146436, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5883/10000 [18:51<13:02,  5.26step/s, loss=0.146436, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5883/10000 [18:51<13:02,  5.26step/s, loss=0.082296, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5884/10000 [18:51<13:03,  5.26step/s, loss=0.082296, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5884/10000 [18:51<13:03,  5.26step/s, loss=0.024639, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5885/10000 [18:51<13:02,  5.26step/s, loss=0.024639, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5885/10000 [18:51<13:02,  5.26step/s, loss=0.045327, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5886/10000 [18:51<13:00,  5.27step/s, loss=0.045327, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5886/10000 [18:51<13:00,  5.27step/s, loss=0.024953, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5887/10000 [18:51<12:59,  5.27step/s, loss=0.024953, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5887/10000 [18:51<12:59,  5.27step/s, loss=0.019885, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5888/10000 [18:52<13:00,  5.27step/s, loss=0.019885, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5888/10000 [18:52<13:00,  5.27step/s, loss=0.065773, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5889/10000 [18:52<13:00,  5.27step/s, loss=0.065773, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5889/10000 [18:52<13:00,  5.27step/s, loss=0.038467, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5890/10000 [18:52<13:01,  5.26step/s, loss=0.038467, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5890/10000 [18:52<13:01,  5.26step/s, loss=0.020955, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5891/10000 [18:52<13:00,  5.27step/s, loss=0.020955, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5891/10000 [18:52<13:00,  5.27step/s, loss=0.048311, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5892/10000 [18:52<12:59,  5.27step/s, loss=0.048311, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5892/10000 [18:52<12:59,  5.27step/s, loss=0.121367, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5893/10000 [18:53<12:58,  5.27step/s, loss=0.121367, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5893/10000 [18:53<12:58,  5.27step/s, loss=0.051597, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5894/10000 [18:53<13:02,  5.25step/s, loss=0.051597, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5894/10000 [18:53<13:02,  5.25step/s, loss=0.037225, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5895/10000 [18:53<13:02,  5.25step/s, loss=0.037225, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5895/10000 [18:53<13:02,  5.25step/s, loss=0.025719, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5896/10000 [18:53<13:02,  5.25step/s, loss=0.025719, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5896/10000 [18:53<13:02,  5.25step/s, loss=0.075067, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5897/10000 [18:53<13:02,  5.25step/s, loss=0.075067, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5897/10000 [18:53<13:02,  5.25step/s, loss=0.058521, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5898/10000 [18:54<13:00,  5.25step/s, loss=0.058521, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5898/10000 [18:54<13:00,  5.25step/s, loss=0.026208, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5899/10000 [18:54<13:00,  5.26step/s, loss=0.026208, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5899/10000 [18:54<13:00,  5.26step/s, loss=0.021953, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5900/10000 [18:54<13:01,  5.25step/s, loss=0.021953, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5900/10000 [18:54<13:01,  5.25step/s, loss=0.036395, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5900/10000 [18:54<13:01,  5.25step/s, loss=0.036395, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5901/10000 [18:54<13:07,  5.21step/s, loss=0.036395, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5901/10000 [18:54<13:07,  5.21step/s, loss=0.033198, elapsed=18.9min]

Step 5900/10000 | Train loss: 0.036395 | Elapsed: 18.9min | ETA: 13.1min

Entraînement:  59%|█████▉    | 5902/10000 [18:54<13:05,  5.22step/s, loss=0.033198, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5902/10000 [18:54<13:05,  5.22step/s, loss=0.032794, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5903/10000 [18:55<13:04,  5.23step/s, loss=0.032794, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5903/10000 [18:55<13:04,  5.23step/s, loss=0.038570, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5904/10000 [18:55<13:01,  5.24step/s, loss=0.038570, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5904/10000 [18:55<13:01,  5.24step/s, loss=0.026675, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5905/10000 [18:55<12:59,  5.25step/s, loss=0.026675, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5905/10000 [18:55<12:59,  5.25step/s, loss=0.050552, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5906/10000 [18:55<12:57,  5.26step/s, loss=0.050552, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5906/10000 [18:55<12:57,  5.26step/s, loss=0.054073, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5907/10000 [18:55<12:55,  5.28step/s, loss=0.054073, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5907/10000 [18:55<12:55,  5.28step/s, loss=0.054637, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5908/10000 [18:55<12:55,  5.28step/s, loss=0.054637, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5908/10000 [18:55<12:55,  5.28step/s, loss=0.082845, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5909/10000 [18:56<12:53,  5.29step/s, loss=0.082845, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5909/10000 [18:56<12:53,  5.29step/s, loss=0.038521, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5910/10000 [18:56<12:54,  5.28step/s, loss=0.038521, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5910/10000 [18:56<12:54,  5.28step/s, loss=0.098336, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5911/10000 [18:56<12:55,  5.27step/s, loss=0.098336, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5911/10000 [18:56<12:55,  5.27step/s, loss=0.177697, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5912/10000 [18:56<12:55,  5.27step/s, loss=0.177697, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5912/10000 [18:56<12:55,  5.27step/s, loss=0.021765, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5913/10000 [18:56<12:54,  5.28step/s, loss=0.021765, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5913/10000 [18:56<12:54,  5.28step/s, loss=0.074578, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5914/10000 [18:57<12:51,  5.29step/s, loss=0.074578, elapsed=18.9min]

Entraînement:  59%|█████▉    | 5914/10000 [18:57<12:51,  5.29step/s, loss=0.040849, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5915/10000 [18:57<12:52,  5.29step/s, loss=0.040849, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5915/10000 [18:57<12:52,  5.29step/s, loss=0.069558, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5916/10000 [18:57<12:51,  5.29step/s, loss=0.069558, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5916/10000 [18:57<12:51,  5.29step/s, loss=0.047401, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5917/10000 [18:57<12:49,  5.30step/s, loss=0.047401, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5917/10000 [18:57<12:49,  5.30step/s, loss=0.046456, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5918/10000 [18:57<12:51,  5.29step/s, loss=0.046456, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5918/10000 [18:57<12:51,  5.29step/s, loss=0.061541, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5919/10000 [18:58<12:52,  5.28step/s, loss=0.061541, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5919/10000 [18:58<12:52,  5.28step/s, loss=0.066657, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5920/10000 [18:58<12:50,  5.29step/s, loss=0.066657, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5920/10000 [18:58<12:50,  5.29step/s, loss=0.087423, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5921/10000 [18:58<12:51,  5.29step/s, loss=0.087423, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5921/10000 [18:58<12:51,  5.29step/s, loss=0.040325, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5922/10000 [18:58<12:51,  5.29step/s, loss=0.040325, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5922/10000 [18:58<12:51,  5.29step/s, loss=0.118727, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5923/10000 [18:58<12:51,  5.28step/s, loss=0.118727, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5923/10000 [18:58<12:51,  5.28step/s, loss=0.024160, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5924/10000 [18:59<12:50,  5.29step/s, loss=0.024160, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5924/10000 [18:59<12:50,  5.29step/s, loss=0.049182, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5925/10000 [18:59<12:51,  5.28step/s, loss=0.049182, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5925/10000 [18:59<12:51,  5.28step/s, loss=0.069903, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5926/10000 [18:59<12:52,  5.28step/s, loss=0.069903, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5926/10000 [18:59<12:52,  5.28step/s, loss=0.095059, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5927/10000 [18:59<12:52,  5.27step/s, loss=0.095059, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5927/10000 [18:59<12:52,  5.27step/s, loss=0.083661, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5928/10000 [18:59<12:52,  5.27step/s, loss=0.083661, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5928/10000 [18:59<12:52,  5.27step/s, loss=0.048224, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5929/10000 [18:59<12:52,  5.27step/s, loss=0.048224, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5929/10000 [18:59<12:52,  5.27step/s, loss=0.040049, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5930/10000 [19:00<12:52,  5.27step/s, loss=0.040049, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5930/10000 [19:00<12:52,  5.27step/s, loss=0.042139, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5931/10000 [19:00<12:51,  5.27step/s, loss=0.042139, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5931/10000 [19:00<12:51,  5.27step/s, loss=0.030457, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5932/10000 [19:00<12:51,  5.28step/s, loss=0.030457, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5932/10000 [19:00<12:51,  5.28step/s, loss=0.033967, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5933/10000 [19:00<12:50,  5.28step/s, loss=0.033967, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5933/10000 [19:00<12:50,  5.28step/s, loss=0.082541, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5934/10000 [19:00<12:50,  5.28step/s, loss=0.082541, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5934/10000 [19:00<12:50,  5.28step/s, loss=0.046434, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5935/10000 [19:01<12:51,  5.27step/s, loss=0.046434, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5935/10000 [19:01<12:51,  5.27step/s, loss=0.018910, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5936/10000 [19:01<12:50,  5.27step/s, loss=0.018910, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5936/10000 [19:01<12:50,  5.27step/s, loss=0.133921, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5937/10000 [19:01<12:51,  5.27step/s, loss=0.133921, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5937/10000 [19:01<12:51,  5.27step/s, loss=0.091835, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5938/10000 [19:01<12:50,  5.27step/s, loss=0.091835, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5938/10000 [19:01<12:50,  5.27step/s, loss=0.035691, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5939/10000 [19:01<12:48,  5.28step/s, loss=0.035691, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5939/10000 [19:01<12:48,  5.28step/s, loss=0.096598, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5940/10000 [19:02<12:48,  5.28step/s, loss=0.096598, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5940/10000 [19:02<12:48,  5.28step/s, loss=0.022891, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5941/10000 [19:02<12:49,  5.28step/s, loss=0.022891, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5941/10000 [19:02<12:49,  5.28step/s, loss=0.023082, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5942/10000 [19:02<12:49,  5.27step/s, loss=0.023082, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5942/10000 [19:02<12:49,  5.27step/s, loss=0.048418, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5943/10000 [19:02<12:50,  5.27step/s, loss=0.048418, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5943/10000 [19:02<12:50,  5.27step/s, loss=0.030969, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5944/10000 [19:02<12:49,  5.27step/s, loss=0.030969, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5944/10000 [19:02<12:49,  5.27step/s, loss=0.059230, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5945/10000 [19:03<12:49,  5.27step/s, loss=0.059230, elapsed=19.0min]

Entraînement:  59%|█████▉    | 5945/10000 [19:03<12:49,  5.27step/s, loss=0.077560, elapsed=19.1min]

Entraînement:  59%|█████▉    | 5946/10000 [19:03<12:48,  5.27step/s, loss=0.077560, elapsed=19.1min]

Entraînement:  59%|█████▉    | 5946/10000 [19:03<12:48,  5.27step/s, loss=0.065901, elapsed=19.1min]

Entraînement:  59%|█████▉    | 5947/10000 [19:03<12:47,  5.28step/s, loss=0.065901, elapsed=19.1min]

Entraînement:  59%|█████▉    | 5947/10000 [19:03<12:47,  5.28step/s, loss=0.048237, elapsed=19.1min]

Entraînement:  59%|█████▉    | 5948/10000 [19:03<12:48,  5.28step/s, loss=0.048237, elapsed=19.1min]

Entraînement:  59%|█████▉    | 5948/10000 [19:03<12:48,  5.28step/s, loss=0.043153, elapsed=19.1min]

Entraînement:  59%|█████▉    | 5949/10000 [19:03<12:46,  5.28step/s, loss=0.043153, elapsed=19.1min]

Entraînement:  59%|█████▉    | 5949/10000 [19:03<12:46,  5.28step/s, loss=0.030991, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5950/10000 [19:03<12:48,  5.27step/s, loss=0.030991, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5950/10000 [19:03<12:48,  5.27step/s, loss=0.027589, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5951/10000 [19:04<12:49,  5.26step/s, loss=0.027589, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5951/10000 [19:04<12:49,  5.26step/s, loss=0.065670, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5952/10000 [19:04<12:49,  5.26step/s, loss=0.065670, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5952/10000 [19:04<12:49,  5.26step/s, loss=0.046884, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5953/10000 [19:04<12:47,  5.27step/s, loss=0.046884, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5953/10000 [19:04<12:47,  5.27step/s, loss=0.045711, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5954/10000 [19:04<12:47,  5.27step/s, loss=0.045711, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5954/10000 [19:04<12:47,  5.27step/s, loss=0.042779, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5955/10000 [19:04<12:47,  5.27step/s, loss=0.042779, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5955/10000 [19:04<12:47,  5.27step/s, loss=0.035528, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5956/10000 [19:05<12:45,  5.28step/s, loss=0.035528, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5956/10000 [19:05<12:45,  5.28step/s, loss=0.038369, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5957/10000 [19:05<12:45,  5.28step/s, loss=0.038369, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5957/10000 [19:05<12:45,  5.28step/s, loss=0.018928, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5958/10000 [19:05<12:44,  5.28step/s, loss=0.018928, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5958/10000 [19:05<12:44,  5.28step/s, loss=0.046539, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5959/10000 [19:05<12:45,  5.28step/s, loss=0.046539, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5959/10000 [19:05<12:45,  5.28step/s, loss=0.046509, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5960/10000 [19:05<12:45,  5.28step/s, loss=0.046509, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5960/10000 [19:05<12:45,  5.28step/s, loss=0.038122, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5961/10000 [19:06<12:44,  5.29step/s, loss=0.038122, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5961/10000 [19:06<12:44,  5.29step/s, loss=0.042237, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5962/10000 [19:06<12:44,  5.28step/s, loss=0.042237, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5962/10000 [19:06<12:44,  5.28step/s, loss=0.044487, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5963/10000 [19:06<12:43,  5.29step/s, loss=0.044487, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5963/10000 [19:06<12:43,  5.29step/s, loss=0.030581, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5964/10000 [19:06<12:43,  5.28step/s, loss=0.030581, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5964/10000 [19:06<12:43,  5.28step/s, loss=0.048697, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5965/10000 [19:06<12:43,  5.28step/s, loss=0.048697, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5965/10000 [19:06<12:43,  5.28step/s, loss=0.029326, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5966/10000 [19:06<12:43,  5.28step/s, loss=0.029326, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5966/10000 [19:06<12:43,  5.28step/s, loss=0.060623, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5967/10000 [19:07<12:43,  5.28step/s, loss=0.060623, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5967/10000 [19:07<12:43,  5.28step/s, loss=0.092258, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5968/10000 [19:07<12:43,  5.28step/s, loss=0.092258, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5968/10000 [19:07<12:43,  5.28step/s, loss=0.039646, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5969/10000 [19:07<12:44,  5.28step/s, loss=0.039646, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5969/10000 [19:07<12:44,  5.28step/s, loss=0.028191, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5970/10000 [19:07<12:45,  5.27step/s, loss=0.028191, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5970/10000 [19:07<12:45,  5.27step/s, loss=0.095788, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5971/10000 [19:07<12:43,  5.28step/s, loss=0.095788, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5971/10000 [19:07<12:43,  5.28step/s, loss=0.036322, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5972/10000 [19:08<12:43,  5.28step/s, loss=0.036322, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5972/10000 [19:08<12:43,  5.28step/s, loss=0.050696, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5973/10000 [19:08<12:43,  5.28step/s, loss=0.050696, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5973/10000 [19:08<12:43,  5.28step/s, loss=0.021073, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5974/10000 [19:08<12:45,  5.26step/s, loss=0.021073, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5974/10000 [19:08<12:45,  5.26step/s, loss=0.032033, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5975/10000 [19:08<12:44,  5.27step/s, loss=0.032033, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5975/10000 [19:08<12:44,  5.27step/s, loss=0.030535, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5976/10000 [19:08<12:41,  5.29step/s, loss=0.030535, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5976/10000 [19:08<12:41,  5.29step/s, loss=0.037385, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5977/10000 [19:09<12:40,  5.29step/s, loss=0.037385, elapsed=19.1min]

Entraînement:  60%|█████▉    | 5977/10000 [19:09<12:40,  5.29step/s, loss=0.045203, elapsed=19.2min]

Entraînement:  60%|█████▉    | 5978/10000 [19:09<12:40,  5.29step/s, loss=0.045203, elapsed=19.2min]

Entraînement:  60%|█████▉    | 5978/10000 [19:09<12:40,  5.29step/s, loss=0.106965, elapsed=19.2min]

Entraînement:  60%|█████▉    | 5979/10000 [19:09<12:40,  5.29step/s, loss=0.106965, elapsed=19.2min]

Entraînement:  60%|█████▉    | 5979/10000 [19:09<12:40,  5.29step/s, loss=0.058124, elapsed=19.2min]

Entraînement:  60%|█████▉    | 5980/10000 [19:09<12:40,  5.29step/s, loss=0.058124, elapsed=19.2min]

Entraînement:  60%|█████▉    | 5980/10000 [19:09<12:40,  5.29step/s, loss=0.020805, elapsed=19.2min]

Entraînement:  60%|█████▉    | 5981/10000 [19:09<12:41,  5.28step/s, loss=0.020805, elapsed=19.2min]

Entraînement:  60%|█████▉    | 5981/10000 [19:09<12:41,  5.28step/s, loss=0.032832, elapsed=19.2min]

Entraînement:  60%|█████▉    | 5982/10000 [19:10<12:41,  5.28step/s, loss=0.032832, elapsed=19.2min]

Entraînement:  60%|█████▉    | 5982/10000 [19:10<12:41,  5.28step/s, loss=0.024631, elapsed=19.2min]

Entraînement:  60%|█████▉    | 5983/10000 [19:10<12:41,  5.27step/s, loss=0.024631, elapsed=19.2min]

Entraînement:  60%|█████▉    | 5983/10000 [19:10<12:41,  5.27step/s, loss=0.050831, elapsed=19.2min]

Entraînement:  60%|█████▉    | 5984/10000 [19:10<12:41,  5.27step/s, loss=0.050831, elapsed=19.2min]

Entraînement:  60%|█████▉    | 5984/10000 [19:10<12:41,  5.27step/s, loss=0.077001, elapsed=19.2min]

Entraînement:  60%|█████▉    | 5985/10000 [19:10<12:41,  5.27step/s, loss=0.077001, elapsed=19.2min]

Entraînement:  60%|█████▉    | 5985/10000 [19:10<12:41,  5.27step/s, loss=0.035727, elapsed=19.2min]

Entraînement:  60%|█████▉    | 5986/10000 [19:10<12:40,  5.28step/s, loss=0.035727, elapsed=19.2min]

Entraînement:  60%|█████▉    | 5986/10000 [19:10<12:40,  5.28step/s, loss=0.019599, elapsed=19.2min]

Entraînement:  60%|█████▉    | 5987/10000 [19:10<12:39,  5.29step/s, loss=0.019599, elapsed=19.2min]

Entraînement:  60%|█████▉    | 5987/10000 [19:10<12:39,  5.29step/s, loss=0.032794, elapsed=19.2min]

Entraînement:  60%|█████▉    | 5988/10000 [19:11<12:37,  5.30step/s, loss=0.032794, elapsed=19.2min]

Entraînement:  60%|█████▉    | 5988/10000 [19:11<12:37,  5.30step/s, loss=0.040277, elapsed=19.2min]

Entraînement:  60%|█████▉    | 5989/10000 [19:11<12:38,  5.28step/s, loss=0.040277, elapsed=19.2min]

Entraînement:  60%|█████▉    | 5989/10000 [19:11<12:38,  5.28step/s, loss=0.039155, elapsed=19.2min]

Entraînement:  60%|█████▉    | 5990/10000 [19:11<12:38,  5.28step/s, loss=0.039155, elapsed=19.2min]

Entraînement:  60%|█████▉    | 5990/10000 [19:11<12:38,  5.28step/s, loss=0.121750, elapsed=19.2min]

Entraînement:  60%|█████▉    | 5991/10000 [19:11<12:39,  5.28step/s, loss=0.121750, elapsed=19.2min]

Entraînement:  60%|█████▉    | 5991/10000 [19:11<12:39,  5.28step/s, loss=0.040470, elapsed=19.2min]

Entraînement:  60%|█████▉    | 5992/10000 [19:11<12:38,  5.28step/s, loss=0.040470, elapsed=19.2min]

Entraînement:  60%|█████▉    | 5992/10000 [19:11<12:38,  5.28step/s, loss=0.040095, elapsed=19.2min]

Entraînement:  60%|█████▉    | 5993/10000 [19:12<12:37,  5.29step/s, loss=0.040095, elapsed=19.2min]

Entraînement:  60%|█████▉    | 5993/10000 [19:12<12:37,  5.29step/s, loss=0.073838, elapsed=19.2min]

Entraînement:  60%|█████▉    | 5994/10000 [19:12<12:37,  5.29step/s, loss=0.073838, elapsed=19.2min]

Entraînement:  60%|█████▉    | 5994/10000 [19:12<12:37,  5.29step/s, loss=0.037890, elapsed=19.2min]

Entraînement:  60%|█████▉    | 5995/10000 [19:12<12:37,  5.29step/s, loss=0.037890, elapsed=19.2min]

Entraînement:  60%|█████▉    | 5995/10000 [19:12<12:37,  5.29step/s, loss=0.031729, elapsed=19.2min]

Entraînement:  60%|█████▉    | 5996/10000 [19:12<12:35,  5.30step/s, loss=0.031729, elapsed=19.2min]

Entraînement:  60%|█████▉    | 5996/10000 [19:12<12:35,  5.30step/s, loss=0.038351, elapsed=19.2min]

Entraînement:  60%|█████▉    | 5997/10000 [19:12<12:36,  5.29step/s, loss=0.038351, elapsed=19.2min]

Entraînement:  60%|█████▉    | 5997/10000 [19:12<12:36,  5.29step/s, loss=0.027949, elapsed=19.2min]

Entraînement:  60%|█████▉    | 5998/10000 [19:13<12:35,  5.29step/s, loss=0.027949, elapsed=19.2min]

Entraînement:  60%|█████▉    | 5998/10000 [19:13<12:35,  5.29step/s, loss=0.041367, elapsed=19.2min]

Entraînement:  60%|█████▉    | 5999/10000 [19:13<12:36,  5.29step/s, loss=0.041367, elapsed=19.2min]

Entraînement:  60%|█████▉    | 5999/10000 [19:13<12:36,  5.29step/s, loss=0.021512, elapsed=19.2min]

Entraînement:  60%|██████    | 6000/10000 [19:13<12:35,  5.29step/s, loss=0.021512, elapsed=19.2min]

Entraînement:  60%|██████    | 6000/10000 [19:13<12:35,  5.29step/s, loss=0.082431, elapsed=19.2min]

Entraînement:  60%|██████    | 6000/10000 [19:13<12:35,  5.29step/s, loss=0.082431, elapsed=19.2min]

Step 6000/10000 | Train loss: 0.082431 | Elapsed: 19.2min | ETA: 12.8min

Entraînement:  60%|██████    | 6000/10000 [19:15<12:35,  5.29step/s, loss=0.082431, elapsed=19.2min]

Entraînement:  60%|██████    | 6000/10000 [19:15<12:35,  5.29step/s, loss=0.082431, elapsed=19.2min]

Step 6000/10000 | Val loss: 0.046535 | Validation en 1.7s
Dernier checkpoint sauvegardé : /workspace/DiffWave_Project/checkpoints/diffwave_doda_male/last_checkpoint.pt

Entraînement:  60%|██████    | 6001/10000 [19:15<50:10,  1.33step/s, loss=0.082431, elapsed=19.2min]

Entraînement:  60%|██████    | 6001/10000 [19:15<50:10,  1.33step/s, loss=0.056278, elapsed=19.3min]

Entraînement:  60%|██████    | 6002/10000 [19:15<38:54,  1.71step/s, loss=0.056278, elapsed=19.3min]

Entraînement:  60%|██████    | 6002/10000 [19:15<38:54,  1.71step/s, loss=0.046176, elapsed=19.3min]

Entraînement:  60%|██████    | 6003/10000 [19:15<31:00,  2.15step/s, loss=0.046176, elapsed=19.3min]

Entraînement:  60%|██████    | 6003/10000 [19:15<31:00,  2.15step/s, loss=0.104389, elapsed=19.3min]

Entraînement:  60%|██████    | 6004/10000 [19:16<25:31,  2.61step/s, loss=0.104389, elapsed=19.3min]

Entraînement:  60%|██████    | 6004/10000 [19:16<25:31,  2.61step/s, loss=0.085569, elapsed=19.3min]

Entraînement:  60%|██████    | 6005/10000 [19:16<21:39,  3.07step/s, loss=0.085569, elapsed=19.3min]

Entraînement:  60%|██████    | 6005/10000 [19:16<21:39,  3.07step/s, loss=0.022808, elapsed=19.3min]

Entraînement:  60%|██████    | 6006/10000 [19:16<19:07,  3.48step/s, loss=0.022808, elapsed=19.3min]

Entraînement:  60%|██████    | 6006/10000 [19:16<19:07,  3.48step/s, loss=0.088452, elapsed=19.3min]

Entraînement:  60%|██████    | 6007/10000 [19:16<17:11,  3.87step/s, loss=0.088452, elapsed=19.3min]

Entraînement:  60%|██████    | 6007/10000 [19:16<17:11,  3.87step/s, loss=0.054948, elapsed=19.3min]

Entraînement:  60%|██████    | 6008/10000 [19:16<15:48,  4.21step/s, loss=0.054948, elapsed=19.3min]

Entraînement:  60%|██████    | 6008/10000 [19:16<15:48,  4.21step/s, loss=0.027142, elapsed=19.3min]

Entraînement:  60%|██████    | 6009/10000 [19:17<14:49,  4.49step/s, loss=0.027142, elapsed=19.3min]

Entraînement:  60%|██████    | 6009/10000 [19:17<14:49,  4.49step/s, loss=0.060034, elapsed=19.3min]

Entraînement:  60%|██████    | 6010/10000 [19:17<14:09,  4.70step/s, loss=0.060034, elapsed=19.3min]

Entraînement:  60%|██████    | 6010/10000 [19:17<14:09,  4.70step/s, loss=0.054459, elapsed=19.3min]

Entraînement:  60%|██████    | 6011/10000 [19:17<13:41,  4.86step/s, loss=0.054459, elapsed=19.3min]

Entraînement:  60%|██████    | 6011/10000 [19:17<13:41,  4.86step/s, loss=0.032359, elapsed=19.3min]

Entraînement:  60%|██████    | 6012/10000 [19:17<13:25,  4.95step/s, loss=0.032359, elapsed=19.3min]

Entraînement:  60%|██████    | 6012/10000 [19:17<13:25,  4.95step/s, loss=0.019702, elapsed=19.3min]

Entraînement:  60%|██████    | 6013/10000 [19:17<13:12,  5.03step/s, loss=0.019702, elapsed=19.3min]

Entraînement:  60%|██████    | 6013/10000 [19:17<13:12,  5.03step/s, loss=0.079650, elapsed=19.3min]

Entraînement:  60%|██████    | 6014/10000 [19:17<13:04,  5.08step/s, loss=0.079650, elapsed=19.3min]

Entraînement:  60%|██████    | 6014/10000 [19:17<13:04,  5.08step/s, loss=0.040669, elapsed=19.3min]

Entraînement:  60%|██████    | 6015/10000 [19:18<12:55,  5.14step/s, loss=0.040669, elapsed=19.3min]

Entraînement:  60%|██████    | 6015/10000 [19:18<12:55,  5.14step/s, loss=0.054206, elapsed=19.3min]

Entraînement:  60%|██████    | 6016/10000 [19:18<12:49,  5.18step/s, loss=0.054206, elapsed=19.3min]

Entraînement:  60%|██████    | 6016/10000 [19:18<12:49,  5.18step/s, loss=0.081671, elapsed=19.3min]

Entraînement:  60%|██████    | 6017/10000 [19:18<12:46,  5.20step/s, loss=0.081671, elapsed=19.3min]

Entraînement:  60%|██████    | 6017/10000 [19:18<12:46,  5.20step/s, loss=0.022731, elapsed=19.3min]

Entraînement:  60%|██████    | 6018/10000 [19:18<12:45,  5.20step/s, loss=0.022731, elapsed=19.3min]

Entraînement:  60%|██████    | 6018/10000 [19:18<12:45,  5.20step/s, loss=0.032811, elapsed=19.3min]

Entraînement:  60%|██████    | 6019/10000 [19:18<12:42,  5.22step/s, loss=0.032811, elapsed=19.3min]

Entraînement:  60%|██████    | 6019/10000 [19:18<12:42,  5.22step/s, loss=0.025233, elapsed=19.3min]

Entraînement:  60%|██████    | 6020/10000 [19:19<12:43,  5.21step/s, loss=0.025233, elapsed=19.3min]

Entraînement:  60%|██████    | 6020/10000 [19:19<12:43,  5.21step/s, loss=0.032938, elapsed=19.3min]

Entraînement:  60%|██████    | 6021/10000 [19:19<12:40,  5.23step/s, loss=0.032938, elapsed=19.3min]

Entraînement:  60%|██████    | 6021/10000 [19:19<12:40,  5.23step/s, loss=0.035743, elapsed=19.3min]

Entraînement:  60%|██████    | 6022/10000 [19:19<12:36,  5.26step/s, loss=0.035743, elapsed=19.3min]

Entraînement:  60%|██████    | 6022/10000 [19:19<12:36,  5.26step/s, loss=0.060720, elapsed=19.3min]

Entraînement:  60%|██████    | 6023/10000 [19:19<12:35,  5.26step/s, loss=0.060720, elapsed=19.3min]

Entraînement:  60%|██████    | 6023/10000 [19:19<12:35,  5.26step/s, loss=0.094388, elapsed=19.3min]

Entraînement:  60%|██████    | 6024/10000 [19:19<12:34,  5.27step/s, loss=0.094388, elapsed=19.3min]

Entraînement:  60%|██████    | 6024/10000 [19:19<12:34,  5.27step/s, loss=0.032269, elapsed=19.3min]

Entraînement:  60%|██████    | 6025/10000 [19:20<12:33,  5.28step/s, loss=0.032269, elapsed=19.3min]

Entraînement:  60%|██████    | 6025/10000 [19:20<12:33,  5.28step/s, loss=0.073874, elapsed=19.3min]

Entraînement:  60%|██████    | 6026/10000 [19:20<12:33,  5.28step/s, loss=0.073874, elapsed=19.3min]

Entraînement:  60%|██████    | 6026/10000 [19:20<12:33,  5.28step/s, loss=0.045229, elapsed=19.3min]

Entraînement:  60%|██████    | 6027/10000 [19:20<12:32,  5.28step/s, loss=0.045229, elapsed=19.3min]

Entraînement:  60%|██████    | 6027/10000 [19:20<12:32,  5.28step/s, loss=0.024941, elapsed=19.3min]

Entraînement:  60%|██████    | 6028/10000 [19:20<12:34,  5.26step/s, loss=0.024941, elapsed=19.3min]

Entraînement:  60%|██████    | 6028/10000 [19:20<12:34,  5.26step/s, loss=0.055074, elapsed=19.3min]

Entraînement:  60%|██████    | 6029/10000 [19:20<12:32,  5.28step/s, loss=0.055074, elapsed=19.3min]

Entraînement:  60%|██████    | 6029/10000 [19:20<12:32,  5.28step/s, loss=0.070342, elapsed=19.3min]

Entraînement:  60%|██████    | 6030/10000 [19:21<12:31,  5.29step/s, loss=0.070342, elapsed=19.3min]

Entraînement:  60%|██████    | 6030/10000 [19:21<12:31,  5.29step/s, loss=0.039751, elapsed=19.4min]

Entraînement:  60%|██████    | 6031/10000 [19:21<12:30,  5.29step/s, loss=0.039751, elapsed=19.4min]

Entraînement:  60%|██████    | 6031/10000 [19:21<12:30,  5.29step/s, loss=0.045120, elapsed=19.4min]

Entraînement:  60%|██████    | 6032/10000 [19:21<12:28,  5.30step/s, loss=0.045120, elapsed=19.4min]

Entraînement:  60%|██████    | 6032/10000 [19:21<12:28,  5.30step/s, loss=0.043413, elapsed=19.4min]

Entraînement:  60%|██████    | 6033/10000 [19:21<12:29,  5.29step/s, loss=0.043413, elapsed=19.4min]

Entraînement:  60%|██████    | 6033/10000 [19:21<12:29,  5.29step/s, loss=0.025347, elapsed=19.4min]

Entraînement:  60%|██████    | 6034/10000 [19:21<12:29,  5.29step/s, loss=0.025347, elapsed=19.4min]

Entraînement:  60%|██████    | 6034/10000 [19:21<12:29,  5.29step/s, loss=0.025894, elapsed=19.4min]

Entraînement:  60%|██████    | 6035/10000 [19:21<12:28,  5.30step/s, loss=0.025894, elapsed=19.4min]

Entraînement:  60%|██████    | 6035/10000 [19:21<12:28,  5.30step/s, loss=0.030498, elapsed=19.4min]

Entraînement:  60%|██████    | 6036/10000 [19:22<12:28,  5.29step/s, loss=0.030498, elapsed=19.4min]

Entraînement:  60%|██████    | 6036/10000 [19:22<12:28,  5.29step/s, loss=0.057739, elapsed=19.4min]

Entraînement:  60%|██████    | 6037/10000 [19:22<12:27,  5.30step/s, loss=0.057739, elapsed=19.4min]

Entraînement:  60%|██████    | 6037/10000 [19:22<12:27,  5.30step/s, loss=0.057979, elapsed=19.4min]

Entraînement:  60%|██████    | 6038/10000 [19:22<12:28,  5.30step/s, loss=0.057979, elapsed=19.4min]

Entraînement:  60%|██████    | 6038/10000 [19:22<12:28,  5.30step/s, loss=0.024874, elapsed=19.4min]

Entraînement:  60%|██████    | 6039/10000 [19:22<12:28,  5.29step/s, loss=0.024874, elapsed=19.4min]

Entraînement:  60%|██████    | 6039/10000 [19:22<12:28,  5.29step/s, loss=0.053645, elapsed=19.4min]

Entraînement:  60%|██████    | 6040/10000 [19:22<12:29,  5.29step/s, loss=0.053645, elapsed=19.4min]

Entraînement:  60%|██████    | 6040/10000 [19:22<12:29,  5.29step/s, loss=0.058548, elapsed=19.4min]

Entraînement:  60%|██████    | 6041/10000 [19:23<12:28,  5.29step/s, loss=0.058548, elapsed=19.4min]

Entraînement:  60%|██████    | 6041/10000 [19:23<12:28,  5.29step/s, loss=0.071685, elapsed=19.4min]

Entraînement:  60%|██████    | 6042/10000 [19:23<12:27,  5.29step/s, loss=0.071685, elapsed=19.4min]

Entraînement:  60%|██████    | 6042/10000 [19:23<12:27,  5.29step/s, loss=0.024484, elapsed=19.4min]

Entraînement:  60%|██████    | 6043/10000 [19:23<12:29,  5.28step/s, loss=0.024484, elapsed=19.4min]

Entraînement:  60%|██████    | 6043/10000 [19:23<12:29,  5.28step/s, loss=0.087947, elapsed=19.4min]

Entraînement:  60%|██████    | 6044/10000 [19:23<12:30,  5.27step/s, loss=0.087947, elapsed=19.4min]

Entraînement:  60%|██████    | 6044/10000 [19:23<12:30,  5.27step/s, loss=0.020455, elapsed=19.4min]

Entraînement:  60%|██████    | 6045/10000 [19:23<12:29,  5.27step/s, loss=0.020455, elapsed=19.4min]

Entraînement:  60%|██████    | 6045/10000 [19:23<12:29,  5.27step/s, loss=0.051355, elapsed=19.4min]

Entraînement:  60%|██████    | 6046/10000 [19:24<12:30,  5.27step/s, loss=0.051355, elapsed=19.4min]

Entraînement:  60%|██████    | 6046/10000 [19:24<12:30,  5.27step/s, loss=0.033870, elapsed=19.4min]

Entraînement:  60%|██████    | 6047/10000 [19:24<12:30,  5.27step/s, loss=0.033870, elapsed=19.4min]

Entraînement:  60%|██████    | 6047/10000 [19:24<12:30,  5.27step/s, loss=0.025404, elapsed=19.4min]

Entraînement:  60%|██████    | 6048/10000 [19:24<12:28,  5.28step/s, loss=0.025404, elapsed=19.4min]

Entraînement:  60%|██████    | 6048/10000 [19:24<12:28,  5.28step/s, loss=0.034787, elapsed=19.4min]

Entraînement:  60%|██████    | 6049/10000 [19:24<12:28,  5.28step/s, loss=0.034787, elapsed=19.4min]

Entraînement:  60%|██████    | 6049/10000 [19:24<12:28,  5.28step/s, loss=0.023747, elapsed=19.4min]

Entraînement:  60%|██████    | 6050/10000 [19:24<12:28,  5.28step/s, loss=0.023747, elapsed=19.4min]

Entraînement:  60%|██████    | 6050/10000 [19:24<12:28,  5.28step/s, loss=0.056023, elapsed=19.4min]

Entraînement:  61%|██████    | 6051/10000 [19:24<12:30,  5.26step/s, loss=0.056023, elapsed=19.4min]

Entraînement:  61%|██████    | 6051/10000 [19:24<12:30,  5.26step/s, loss=0.034282, elapsed=19.4min]

Entraînement:  61%|██████    | 6052/10000 [19:25<12:29,  5.27step/s, loss=0.034282, elapsed=19.4min]

Entraînement:  61%|██████    | 6052/10000 [19:25<12:29,  5.27step/s, loss=0.031921, elapsed=19.4min]

Entraînement:  61%|██████    | 6053/10000 [19:25<12:27,  5.28step/s, loss=0.031921, elapsed=19.4min]

Entraînement:  61%|██████    | 6053/10000 [19:25<12:27,  5.28step/s, loss=0.031498, elapsed=19.4min]

Entraînement:  61%|██████    | 6054/10000 [19:25<12:28,  5.27step/s, loss=0.031498, elapsed=19.4min]

Entraînement:  61%|██████    | 6054/10000 [19:25<12:28,  5.27step/s, loss=0.041706, elapsed=19.4min]

Entraînement:  61%|██████    | 6055/10000 [19:25<12:27,  5.27step/s, loss=0.041706, elapsed=19.4min]

Entraînement:  61%|██████    | 6055/10000 [19:25<12:27,  5.27step/s, loss=0.023295, elapsed=19.4min]

Entraînement:  61%|██████    | 6056/10000 [19:25<12:28,  5.27step/s, loss=0.023295, elapsed=19.4min]

Entraînement:  61%|██████    | 6056/10000 [19:25<12:28,  5.27step/s, loss=0.072956, elapsed=19.4min]

Entraînement:  61%|██████    | 6057/10000 [19:26<12:28,  5.27step/s, loss=0.072956, elapsed=19.4min]

Entraînement:  61%|██████    | 6057/10000 [19:26<12:28,  5.27step/s, loss=0.089175, elapsed=19.4min]

Entraînement:  61%|██████    | 6058/10000 [19:26<12:29,  5.26step/s, loss=0.089175, elapsed=19.4min]

Entraînement:  61%|██████    | 6058/10000 [19:26<12:29,  5.26step/s, loss=0.041330, elapsed=19.4min]

Entraînement:  61%|██████    | 6059/10000 [19:26<12:30,  5.25step/s, loss=0.041330, elapsed=19.4min]

Entraînement:  61%|██████    | 6059/10000 [19:26<12:30,  5.25step/s, loss=0.051628, elapsed=19.4min]

Entraînement:  61%|██████    | 6060/10000 [19:26<12:31,  5.24step/s, loss=0.051628, elapsed=19.4min]

Entraînement:  61%|██████    | 6060/10000 [19:26<12:31,  5.24step/s, loss=0.086358, elapsed=19.4min]

Entraînement:  61%|██████    | 6061/10000 [19:26<12:29,  5.26step/s, loss=0.086358, elapsed=19.4min]

Entraînement:  61%|██████    | 6061/10000 [19:26<12:29,  5.26step/s, loss=0.028978, elapsed=19.4min]

Entraînement:  61%|██████    | 6062/10000 [19:27<12:28,  5.26step/s, loss=0.028978, elapsed=19.4min]

Entraînement:  61%|██████    | 6062/10000 [19:27<12:28,  5.26step/s, loss=0.032924, elapsed=19.5min]

Entraînement:  61%|██████    | 6063/10000 [19:27<12:27,  5.27step/s, loss=0.032924, elapsed=19.5min]

Entraînement:  61%|██████    | 6063/10000 [19:27<12:27,  5.27step/s, loss=0.021297, elapsed=19.5min]

Entraînement:  61%|██████    | 6064/10000 [19:27<12:25,  5.28step/s, loss=0.021297, elapsed=19.5min]

Entraînement:  61%|██████    | 6064/10000 [19:27<12:25,  5.28step/s, loss=0.085575, elapsed=19.5min]

Entraînement:  61%|██████    | 6065/10000 [19:27<12:25,  5.28step/s, loss=0.085575, elapsed=19.5min]

Entraînement:  61%|██████    | 6065/10000 [19:27<12:25,  5.28step/s, loss=0.033481, elapsed=19.5min]

Entraînement:  61%|██████    | 6066/10000 [19:27<12:26,  5.27step/s, loss=0.033481, elapsed=19.5min]

Entraînement:  61%|██████    | 6066/10000 [19:27<12:26,  5.27step/s, loss=0.041905, elapsed=19.5min]

Entraînement:  61%|██████    | 6067/10000 [19:28<12:26,  5.27step/s, loss=0.041905, elapsed=19.5min]

Entraînement:  61%|██████    | 6067/10000 [19:28<12:26,  5.27step/s, loss=0.084842, elapsed=19.5min]

Entraînement:  61%|██████    | 6068/10000 [19:28<12:25,  5.27step/s, loss=0.084842, elapsed=19.5min]

Entraînement:  61%|██████    | 6068/10000 [19:28<12:25,  5.27step/s, loss=0.021624, elapsed=19.5min]

Entraînement:  61%|██████    | 6069/10000 [19:28<12:25,  5.28step/s, loss=0.021624, elapsed=19.5min]

Entraînement:  61%|██████    | 6069/10000 [19:28<12:25,  5.28step/s, loss=0.070059, elapsed=19.5min]

Entraînement:  61%|██████    | 6070/10000 [19:28<12:24,  5.28step/s, loss=0.070059, elapsed=19.5min]

Entraînement:  61%|██████    | 6070/10000 [19:28<12:24,  5.28step/s, loss=0.113129, elapsed=19.5min]

Entraînement:  61%|██████    | 6071/10000 [19:28<12:23,  5.29step/s, loss=0.113129, elapsed=19.5min]

Entraînement:  61%|██████    | 6071/10000 [19:28<12:23,  5.29step/s, loss=0.036098, elapsed=19.5min]

Entraînement:  61%|██████    | 6072/10000 [19:28<12:22,  5.29step/s, loss=0.036098, elapsed=19.5min]

Entraînement:  61%|██████    | 6072/10000 [19:28<12:22,  5.29step/s, loss=0.033030, elapsed=19.5min]

Entraînement:  61%|██████    | 6073/10000 [19:29<12:23,  5.28step/s, loss=0.033030, elapsed=19.5min]

Entraînement:  61%|██████    | 6073/10000 [19:29<12:23,  5.28step/s, loss=0.107818, elapsed=19.5min]

Entraînement:  61%|██████    | 6074/10000 [19:29<12:22,  5.29step/s, loss=0.107818, elapsed=19.5min]

Entraînement:  61%|██████    | 6074/10000 [19:29<12:22,  5.29step/s, loss=0.063869, elapsed=19.5min]

Entraînement:  61%|██████    | 6075/10000 [19:29<12:23,  5.28step/s, loss=0.063869, elapsed=19.5min]

Entraînement:  61%|██████    | 6075/10000 [19:29<12:23,  5.28step/s, loss=0.028689, elapsed=19.5min]

Entraînement:  61%|██████    | 6076/10000 [19:29<12:23,  5.28step/s, loss=0.028689, elapsed=19.5min]

Entraînement:  61%|██████    | 6076/10000 [19:29<12:23,  5.28step/s, loss=0.024632, elapsed=19.5min]

Entraînement:  61%|██████    | 6077/10000 [19:29<12:23,  5.27step/s, loss=0.024632, elapsed=19.5min]

Entraînement:  61%|██████    | 6077/10000 [19:29<12:23,  5.27step/s, loss=0.064149, elapsed=19.5min]

Entraînement:  61%|██████    | 6078/10000 [19:30<12:23,  5.28step/s, loss=0.064149, elapsed=19.5min]

Entraînement:  61%|██████    | 6078/10000 [19:30<12:23,  5.28step/s, loss=0.043186, elapsed=19.5min]

Entraînement:  61%|██████    | 6079/10000 [19:30<12:23,  5.27step/s, loss=0.043186, elapsed=19.5min]

Entraînement:  61%|██████    | 6079/10000 [19:30<12:23,  5.27step/s, loss=0.011904, elapsed=19.5min]

Entraînement:  61%|██████    | 6080/10000 [19:30<12:23,  5.27step/s, loss=0.011904, elapsed=19.5min]

Entraînement:  61%|██████    | 6080/10000 [19:30<12:23,  5.27step/s, loss=0.028356, elapsed=19.5min]

Entraînement:  61%|██████    | 6081/10000 [19:30<12:23,  5.27step/s, loss=0.028356, elapsed=19.5min]

Entraînement:  61%|██████    | 6081/10000 [19:30<12:23,  5.27step/s, loss=0.023046, elapsed=19.5min]

Entraînement:  61%|██████    | 6082/10000 [19:30<12:26,  5.25step/s, loss=0.023046, elapsed=19.5min]

Entraînement:  61%|██████    | 6082/10000 [19:30<12:26,  5.25step/s, loss=0.071891, elapsed=19.5min]

Entraînement:  61%|██████    | 6083/10000 [19:31<12:27,  5.24step/s, loss=0.071891, elapsed=19.5min]

Entraînement:  61%|██████    | 6083/10000 [19:31<12:27,  5.24step/s, loss=0.025186, elapsed=19.5min]

Entraînement:  61%|██████    | 6084/10000 [19:31<12:25,  5.25step/s, loss=0.025186, elapsed=19.5min]

Entraînement:  61%|██████    | 6084/10000 [19:31<12:25,  5.25step/s, loss=0.032571, elapsed=19.5min]

Entraînement:  61%|██████    | 6085/10000 [19:31<12:24,  5.26step/s, loss=0.032571, elapsed=19.5min]

Entraînement:  61%|██████    | 6085/10000 [19:31<12:24,  5.26step/s, loss=0.032419, elapsed=19.5min]

Entraînement:  61%|██████    | 6086/10000 [19:31<12:24,  5.26step/s, loss=0.032419, elapsed=19.5min]

Entraînement:  61%|██████    | 6086/10000 [19:31<12:24,  5.26step/s, loss=0.067501, elapsed=19.5min]

Entraînement:  61%|██████    | 6087/10000 [19:31<12:22,  5.27step/s, loss=0.067501, elapsed=19.5min]

Entraînement:  61%|██████    | 6087/10000 [19:31<12:22,  5.27step/s, loss=0.098548, elapsed=19.5min]

Entraînement:  61%|██████    | 6088/10000 [19:32<12:26,  5.24step/s, loss=0.098548, elapsed=19.5min]

Entraînement:  61%|██████    | 6088/10000 [19:32<12:26,  5.24step/s, loss=0.034548, elapsed=19.5min]

Entraînement:  61%|██████    | 6089/10000 [19:32<12:25,  5.25step/s, loss=0.034548, elapsed=19.5min]

Entraînement:  61%|██████    | 6089/10000 [19:32<12:25,  5.25step/s, loss=0.043352, elapsed=19.5min]

Entraînement:  61%|██████    | 6090/10000 [19:32<12:25,  5.24step/s, loss=0.043352, elapsed=19.5min]

Entraînement:  61%|██████    | 6090/10000 [19:32<12:25,  5.24step/s, loss=0.037284, elapsed=19.5min]

Entraînement:  61%|██████    | 6091/10000 [19:32<12:25,  5.24step/s, loss=0.037284, elapsed=19.5min]

Entraînement:  61%|██████    | 6091/10000 [19:32<12:25,  5.24step/s, loss=0.033418, elapsed=19.5min]

Entraînement:  61%|██████    | 6092/10000 [19:32<12:31,  5.20step/s, loss=0.033418, elapsed=19.5min]

Entraînement:  61%|██████    | 6092/10000 [19:32<12:31,  5.20step/s, loss=0.076830, elapsed=19.5min]

Entraînement:  61%|██████    | 6093/10000 [19:32<12:30,  5.20step/s, loss=0.076830, elapsed=19.5min]

Entraînement:  61%|██████    | 6093/10000 [19:32<12:30,  5.20step/s, loss=0.055202, elapsed=19.5min]

Entraînement:  61%|██████    | 6094/10000 [19:33<12:31,  5.20step/s, loss=0.055202, elapsed=19.5min]

Entraînement:  61%|██████    | 6094/10000 [19:33<12:31,  5.20step/s, loss=0.033643, elapsed=19.6min]

Entraînement:  61%|██████    | 6095/10000 [19:33<12:27,  5.23step/s, loss=0.033643, elapsed=19.6min]

Entraînement:  61%|██████    | 6095/10000 [19:33<12:27,  5.23step/s, loss=0.053242, elapsed=19.6min]

Entraînement:  61%|██████    | 6096/10000 [19:33<12:26,  5.23step/s, loss=0.053242, elapsed=19.6min]

Entraînement:  61%|██████    | 6096/10000 [19:33<12:26,  5.23step/s, loss=0.021475, elapsed=19.6min]

Entraînement:  61%|██████    | 6097/10000 [19:33<12:25,  5.24step/s, loss=0.021475, elapsed=19.6min]

Entraînement:  61%|██████    | 6097/10000 [19:33<12:25,  5.24step/s, loss=0.027498, elapsed=19.6min]

Entraînement:  61%|██████    | 6098/10000 [19:33<12:25,  5.24step/s, loss=0.027498, elapsed=19.6min]

Entraînement:  61%|██████    | 6098/10000 [19:33<12:25,  5.24step/s, loss=0.061941, elapsed=19.6min]

Entraînement:  61%|██████    | 6099/10000 [19:34<12:23,  5.25step/s, loss=0.061941, elapsed=19.6min]

Entraînement:  61%|██████    | 6099/10000 [19:34<12:23,  5.25step/s, loss=0.056916, elapsed=19.6min]

Entraînement:  61%|██████    | 6100/10000 [19:34<12:20,  5.26step/s, loss=0.056916, elapsed=19.6min]

Entraînement:  61%|██████    | 6100/10000 [19:34<12:20,  5.26step/s, loss=0.033578, elapsed=19.6min]

Entraînement:  61%|██████    | 6100/10000 [19:34<12:20,  5.26step/s, loss=0.033578, elapsed=19.6min]

Entraînement:  61%|██████    | 6101/10000 [19:34<12:26,  5.22step/s, loss=0.033578, elapsed=19.6min]

Entraînement:  61%|██████    | 6101/10000 [19:34<12:26,  5.22step/s, loss=0.050116, elapsed=19.6min]

Step 6100/10000 | Train loss: 0.033578 | Elapsed: 19.6min | ETA: 12.5min

Entraînement:  61%|██████    | 6102/10000 [19:34<12:27,  5.21step/s, loss=0.050116, elapsed=19.6min]

Entraînement:  61%|██████    | 6102/10000 [19:34<12:27,  5.21step/s, loss=0.048532, elapsed=19.6min]

Entraînement:  61%|██████    | 6103/10000 [19:34<12:25,  5.23step/s, loss=0.048532, elapsed=19.6min]

Entraînement:  61%|██████    | 6103/10000 [19:34<12:25,  5.23step/s, loss=0.038098, elapsed=19.6min]

Entraînement:  61%|██████    | 6104/10000 [19:35<12:22,  5.25step/s, loss=0.038098, elapsed=19.6min]

Entraînement:  61%|██████    | 6104/10000 [19:35<12:22,  5.25step/s, loss=0.040605, elapsed=19.6min]

Entraînement:  61%|██████    | 6105/10000 [19:35<12:23,  5.24step/s, loss=0.040605, elapsed=19.6min]

Entraînement:  61%|██████    | 6105/10000 [19:35<12:23,  5.24step/s, loss=0.022983, elapsed=19.6min]

Entraînement:  61%|██████    | 6106/10000 [19:35<12:20,  5.26step/s, loss=0.022983, elapsed=19.6min]

Entraînement:  61%|██████    | 6106/10000 [19:35<12:20,  5.26step/s, loss=0.028437, elapsed=19.6min]

Entraînement:  61%|██████    | 6107/10000 [19:35<12:19,  5.26step/s, loss=0.028437, elapsed=19.6min]

Entraînement:  61%|██████    | 6107/10000 [19:35<12:19,  5.26step/s, loss=0.026892, elapsed=19.6min]

Entraînement:  61%|██████    | 6108/10000 [19:35<12:18,  5.27step/s, loss=0.026892, elapsed=19.6min]

Entraînement:  61%|██████    | 6108/10000 [19:35<12:18,  5.27step/s, loss=0.039819, elapsed=19.6min]

Entraînement:  61%|██████    | 6109/10000 [19:36<12:16,  5.28step/s, loss=0.039819, elapsed=19.6min]

Entraînement:  61%|██████    | 6109/10000 [19:36<12:16,  5.28step/s, loss=0.040290, elapsed=19.6min]

Entraînement:  61%|██████    | 6110/10000 [19:36<12:16,  5.28step/s, loss=0.040290, elapsed=19.6min]

Entraînement:  61%|██████    | 6110/10000 [19:36<12:16,  5.28step/s, loss=0.044181, elapsed=19.6min]

Entraînement:  61%|██████    | 6111/10000 [19:36<12:16,  5.28step/s, loss=0.044181, elapsed=19.6min]

Entraînement:  61%|██████    | 6111/10000 [19:36<12:16,  5.28step/s, loss=0.068989, elapsed=19.6min]

Entraînement:  61%|██████    | 6112/10000 [19:36<12:16,  5.28step/s, loss=0.068989, elapsed=19.6min]

Entraînement:  61%|██████    | 6112/10000 [19:36<12:16,  5.28step/s, loss=0.068569, elapsed=19.6min]

Entraînement:  61%|██████    | 6113/10000 [19:36<12:17,  5.27step/s, loss=0.068569, elapsed=19.6min]

Entraînement:  61%|██████    | 6113/10000 [19:36<12:17,  5.27step/s, loss=0.044405, elapsed=19.6min]

Entraînement:  61%|██████    | 6114/10000 [19:36<12:17,  5.27step/s, loss=0.044405, elapsed=19.6min]

Entraînement:  61%|██████    | 6114/10000 [19:36<12:17,  5.27step/s, loss=0.037869, elapsed=19.6min]

Entraînement:  61%|██████    | 6115/10000 [19:37<12:16,  5.28step/s, loss=0.037869, elapsed=19.6min]

Entraînement:  61%|██████    | 6115/10000 [19:37<12:16,  5.28step/s, loss=0.038517, elapsed=19.6min]

Entraînement:  61%|██████    | 6116/10000 [19:37<12:16,  5.28step/s, loss=0.038517, elapsed=19.6min]

Entraînement:  61%|██████    | 6116/10000 [19:37<12:16,  5.28step/s, loss=0.136548, elapsed=19.6min]

Entraînement:  61%|██████    | 6117/10000 [19:37<12:16,  5.27step/s, loss=0.136548, elapsed=19.6min]

Entraînement:  61%|██████    | 6117/10000 [19:37<12:16,  5.27step/s, loss=0.036759, elapsed=19.6min]

Entraînement:  61%|██████    | 6118/10000 [19:37<12:15,  5.27step/s, loss=0.036759, elapsed=19.6min]

Entraînement:  61%|██████    | 6118/10000 [19:37<12:15,  5.27step/s, loss=0.050470, elapsed=19.6min]

Entraînement:  61%|██████    | 6119/10000 [19:37<12:14,  5.28step/s, loss=0.050470, elapsed=19.6min]

Entraînement:  61%|██████    | 6119/10000 [19:37<12:14,  5.28step/s, loss=0.041694, elapsed=19.6min]

Entraînement:  61%|██████    | 6120/10000 [19:38<12:16,  5.27step/s, loss=0.041694, elapsed=19.6min]

Entraînement:  61%|██████    | 6120/10000 [19:38<12:16,  5.27step/s, loss=0.037691, elapsed=19.6min]

Entraînement:  61%|██████    | 6121/10000 [19:38<12:17,  5.26step/s, loss=0.037691, elapsed=19.6min]

Entraînement:  61%|██████    | 6121/10000 [19:38<12:17,  5.26step/s, loss=0.035860, elapsed=19.6min]

Entraînement:  61%|██████    | 6122/10000 [19:38<12:16,  5.27step/s, loss=0.035860, elapsed=19.6min]

Entraînement:  61%|██████    | 6122/10000 [19:38<12:16,  5.27step/s, loss=0.044608, elapsed=19.6min]

Entraînement:  61%|██████    | 6123/10000 [19:38<12:17,  5.26step/s, loss=0.044608, elapsed=19.6min]

Entraînement:  61%|██████    | 6123/10000 [19:38<12:17,  5.26step/s, loss=0.076278, elapsed=19.6min]

Entraînement:  61%|██████    | 6124/10000 [19:38<12:16,  5.26step/s, loss=0.076278, elapsed=19.6min]

Entraînement:  61%|██████    | 6124/10000 [19:38<12:16,  5.26step/s, loss=0.033810, elapsed=19.6min]

Entraînement:  61%|██████▏   | 6125/10000 [19:39<12:14,  5.27step/s, loss=0.033810, elapsed=19.6min]

Entraînement:  61%|██████▏   | 6125/10000 [19:39<12:14,  5.27step/s, loss=0.029905, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6126/10000 [19:39<12:15,  5.27step/s, loss=0.029905, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6126/10000 [19:39<12:15,  5.27step/s, loss=0.022757, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6127/10000 [19:39<12:14,  5.27step/s, loss=0.022757, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6127/10000 [19:39<12:14,  5.27step/s, loss=0.060037, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6128/10000 [19:39<12:15,  5.26step/s, loss=0.060037, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6128/10000 [19:39<12:15,  5.26step/s, loss=0.039788, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6129/10000 [19:39<12:15,  5.26step/s, loss=0.039788, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6129/10000 [19:39<12:15,  5.26step/s, loss=0.088583, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6130/10000 [19:39<12:17,  5.25step/s, loss=0.088583, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6130/10000 [19:39<12:17,  5.25step/s, loss=0.023486, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6131/10000 [19:40<12:15,  5.26step/s, loss=0.023486, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6131/10000 [19:40<12:15,  5.26step/s, loss=0.035568, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6132/10000 [19:40<12:14,  5.26step/s, loss=0.035568, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6132/10000 [19:40<12:14,  5.26step/s, loss=0.032312, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6133/10000 [19:40<12:15,  5.26step/s, loss=0.032312, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6133/10000 [19:40<12:15,  5.26step/s, loss=0.034640, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6134/10000 [19:40<12:15,  5.25step/s, loss=0.034640, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6134/10000 [19:40<12:15,  5.25step/s, loss=0.051493, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6135/10000 [19:40<12:14,  5.26step/s, loss=0.051493, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6135/10000 [19:40<12:14,  5.26step/s, loss=0.052754, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6136/10000 [19:41<12:14,  5.26step/s, loss=0.052754, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6136/10000 [19:41<12:14,  5.26step/s, loss=0.032154, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6137/10000 [19:41<12:12,  5.27step/s, loss=0.032154, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6137/10000 [19:41<12:12,  5.27step/s, loss=0.048127, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6138/10000 [19:41<12:13,  5.26step/s, loss=0.048127, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6138/10000 [19:41<12:13,  5.26step/s, loss=0.040341, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6139/10000 [19:41<12:14,  5.26step/s, loss=0.040341, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6139/10000 [19:41<12:14,  5.26step/s, loss=0.056377, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6140/10000 [19:41<12:13,  5.26step/s, loss=0.056377, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6140/10000 [19:41<12:13,  5.26step/s, loss=0.025652, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6141/10000 [19:42<12:13,  5.26step/s, loss=0.025652, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6141/10000 [19:42<12:13,  5.26step/s, loss=0.058698, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6142/10000 [19:42<12:12,  5.26step/s, loss=0.058698, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6142/10000 [19:42<12:12,  5.26step/s, loss=0.052289, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6143/10000 [19:42<12:11,  5.27step/s, loss=0.052289, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6143/10000 [19:42<12:11,  5.27step/s, loss=0.095688, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6144/10000 [19:42<12:14,  5.25step/s, loss=0.095688, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6144/10000 [19:42<12:14,  5.25step/s, loss=0.031997, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6145/10000 [19:42<12:14,  5.25step/s, loss=0.031997, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6145/10000 [19:42<12:14,  5.25step/s, loss=0.060015, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6146/10000 [19:43<12:13,  5.26step/s, loss=0.060015, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6146/10000 [19:43<12:13,  5.26step/s, loss=0.049759, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6147/10000 [19:43<12:12,  5.26step/s, loss=0.049759, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6147/10000 [19:43<12:12,  5.26step/s, loss=0.045693, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6148/10000 [19:43<12:12,  5.26step/s, loss=0.045693, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6148/10000 [19:43<12:12,  5.26step/s, loss=0.021500, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6149/10000 [19:43<12:11,  5.26step/s, loss=0.021500, elapsed=19.7min]

Entraînement:  61%|██████▏   | 6149/10000 [19:43<12:11,  5.26step/s, loss=0.025614, elapsed=19.7min]

Entraînement:  62%|██████▏   | 6150/10000 [19:43<12:11,  5.27step/s, loss=0.025614, elapsed=19.7min]

Entraînement:  62%|██████▏   | 6150/10000 [19:43<12:11,  5.27step/s, loss=0.077505, elapsed=19.7min]

Entraînement:  62%|██████▏   | 6151/10000 [19:43<12:11,  5.26step/s, loss=0.077505, elapsed=19.7min]

Entraînement:  62%|██████▏   | 6151/10000 [19:43<12:11,  5.26step/s, loss=0.097883, elapsed=19.7min]

Entraînement:  62%|██████▏   | 6152/10000 [19:44<12:11,  5.26step/s, loss=0.097883, elapsed=19.7min]

Entraînement:  62%|██████▏   | 6152/10000 [19:44<12:11,  5.26step/s, loss=0.112307, elapsed=19.7min]

Entraînement:  62%|██████▏   | 6153/10000 [19:44<12:11,  5.26step/s, loss=0.112307, elapsed=19.7min]

Entraînement:  62%|██████▏   | 6153/10000 [19:44<12:11,  5.26step/s, loss=0.057401, elapsed=19.7min]

Entraînement:  62%|██████▏   | 6154/10000 [19:44<12:11,  5.26step/s, loss=0.057401, elapsed=19.7min]

Entraînement:  62%|██████▏   | 6154/10000 [19:44<12:11,  5.26step/s, loss=0.017114, elapsed=19.7min]

Entraînement:  62%|██████▏   | 6155/10000 [19:44<12:11,  5.26step/s, loss=0.017114, elapsed=19.7min]

Entraînement:  62%|██████▏   | 6155/10000 [19:44<12:11,  5.26step/s, loss=0.030178, elapsed=19.7min]

Entraînement:  62%|██████▏   | 6156/10000 [19:44<12:12,  5.25step/s, loss=0.030178, elapsed=19.7min]

Entraînement:  62%|██████▏   | 6156/10000 [19:44<12:12,  5.25step/s, loss=0.029421, elapsed=19.7min]

Entraînement:  62%|██████▏   | 6157/10000 [19:45<12:11,  5.25step/s, loss=0.029421, elapsed=19.7min]

Entraînement:  62%|██████▏   | 6157/10000 [19:45<12:11,  5.25step/s, loss=0.059961, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6158/10000 [19:45<12:10,  5.26step/s, loss=0.059961, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6158/10000 [19:45<12:10,  5.26step/s, loss=0.035324, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6159/10000 [19:45<12:08,  5.27step/s, loss=0.035324, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6159/10000 [19:45<12:08,  5.27step/s, loss=0.067254, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6160/10000 [19:45<12:08,  5.27step/s, loss=0.067254, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6160/10000 [19:45<12:08,  5.27step/s, loss=0.084968, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6161/10000 [19:45<12:08,  5.27step/s, loss=0.084968, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6161/10000 [19:45<12:08,  5.27step/s, loss=0.105680, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6162/10000 [19:46<12:07,  5.28step/s, loss=0.105680, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6162/10000 [19:46<12:07,  5.28step/s, loss=0.032330, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6163/10000 [19:46<12:06,  5.28step/s, loss=0.032330, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6163/10000 [19:46<12:06,  5.28step/s, loss=0.043828, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6164/10000 [19:46<12:07,  5.28step/s, loss=0.043828, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6164/10000 [19:46<12:07,  5.28step/s, loss=0.046921, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6165/10000 [19:46<12:08,  5.26step/s, loss=0.046921, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6165/10000 [19:46<12:08,  5.26step/s, loss=0.028651, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6166/10000 [19:46<12:07,  5.27step/s, loss=0.028651, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6166/10000 [19:46<12:07,  5.27step/s, loss=0.024670, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6167/10000 [19:47<12:06,  5.28step/s, loss=0.024670, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6167/10000 [19:47<12:06,  5.28step/s, loss=0.065420, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6168/10000 [19:47<12:06,  5.28step/s, loss=0.065420, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6168/10000 [19:47<12:06,  5.28step/s, loss=0.089072, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6169/10000 [19:47<12:05,  5.28step/s, loss=0.089072, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6169/10000 [19:47<12:05,  5.28step/s, loss=0.027456, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6170/10000 [19:47<12:04,  5.29step/s, loss=0.027456, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6170/10000 [19:47<12:04,  5.29step/s, loss=0.043950, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6171/10000 [19:47<12:01,  5.31step/s, loss=0.043950, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6171/10000 [19:47<12:01,  5.31step/s, loss=0.023227, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6172/10000 [19:47<12:04,  5.29step/s, loss=0.023227, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6172/10000 [19:47<12:04,  5.29step/s, loss=0.038991, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6173/10000 [19:48<12:04,  5.28step/s, loss=0.038991, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6173/10000 [19:48<12:04,  5.28step/s, loss=0.053785, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6174/10000 [19:48<12:03,  5.29step/s, loss=0.053785, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6174/10000 [19:48<12:03,  5.29step/s, loss=0.026452, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6175/10000 [19:48<12:03,  5.28step/s, loss=0.026452, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6175/10000 [19:48<12:03,  5.28step/s, loss=0.160034, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6176/10000 [19:48<12:05,  5.27step/s, loss=0.160034, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6176/10000 [19:48<12:05,  5.27step/s, loss=0.066009, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6177/10000 [19:48<12:05,  5.27step/s, loss=0.066009, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6177/10000 [19:48<12:05,  5.27step/s, loss=0.026136, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6178/10000 [19:49<12:04,  5.28step/s, loss=0.026136, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6178/10000 [19:49<12:04,  5.28step/s, loss=0.022065, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6179/10000 [19:49<12:05,  5.27step/s, loss=0.022065, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6179/10000 [19:49<12:05,  5.27step/s, loss=0.049942, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6180/10000 [19:49<12:05,  5.26step/s, loss=0.049942, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6180/10000 [19:49<12:05,  5.26step/s, loss=0.027967, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6181/10000 [19:49<12:06,  5.26step/s, loss=0.027967, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6181/10000 [19:49<12:06,  5.26step/s, loss=0.097671, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6182/10000 [19:49<12:05,  5.26step/s, loss=0.097671, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6182/10000 [19:49<12:05,  5.26step/s, loss=0.029565, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6183/10000 [19:50<12:03,  5.27step/s, loss=0.029565, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6183/10000 [19:50<12:03,  5.27step/s, loss=0.076957, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6184/10000 [19:50<12:04,  5.27step/s, loss=0.076957, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6184/10000 [19:50<12:04,  5.27step/s, loss=0.059564, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6185/10000 [19:50<12:03,  5.27step/s, loss=0.059564, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6185/10000 [19:50<12:03,  5.27step/s, loss=0.042914, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6186/10000 [19:50<12:04,  5.26step/s, loss=0.042914, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6186/10000 [19:50<12:04,  5.26step/s, loss=0.028581, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6187/10000 [19:50<12:05,  5.26step/s, loss=0.028581, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6187/10000 [19:50<12:05,  5.26step/s, loss=0.022375, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6188/10000 [19:51<12:05,  5.25step/s, loss=0.022375, elapsed=19.8min]

Entraînement:  62%|██████▏   | 6188/10000 [19:51<12:05,  5.25step/s, loss=0.049044, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6189/10000 [19:51<12:05,  5.26step/s, loss=0.049044, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6189/10000 [19:51<12:05,  5.26step/s, loss=0.094374, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6190/10000 [19:51<12:03,  5.27step/s, loss=0.094374, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6190/10000 [19:51<12:03,  5.27step/s, loss=0.026051, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6191/10000 [19:51<12:03,  5.26step/s, loss=0.026051, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6191/10000 [19:51<12:03,  5.26step/s, loss=0.096143, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6192/10000 [19:51<12:02,  5.27step/s, loss=0.096143, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6192/10000 [19:51<12:02,  5.27step/s, loss=0.032964, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6193/10000 [19:51<12:01,  5.27step/s, loss=0.032964, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6193/10000 [19:51<12:01,  5.27step/s, loss=0.028378, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6194/10000 [19:52<12:01,  5.28step/s, loss=0.028378, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6194/10000 [19:52<12:01,  5.28step/s, loss=0.089452, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6195/10000 [19:52<12:03,  5.26step/s, loss=0.089452, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6195/10000 [19:52<12:03,  5.26step/s, loss=0.049601, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6196/10000 [19:52<12:02,  5.27step/s, loss=0.049601, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6196/10000 [19:52<12:02,  5.27step/s, loss=0.021291, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6197/10000 [19:52<12:02,  5.26step/s, loss=0.021291, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6197/10000 [19:52<12:02,  5.26step/s, loss=0.060282, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6198/10000 [19:52<12:03,  5.26step/s, loss=0.060282, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6198/10000 [19:52<12:03,  5.26step/s, loss=0.018234, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6199/10000 [19:53<12:03,  5.25step/s, loss=0.018234, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6199/10000 [19:53<12:03,  5.25step/s, loss=0.032481, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6200/10000 [19:53<12:02,  5.26step/s, loss=0.032481, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6200/10000 [19:53<12:02,  5.26step/s, loss=0.030699, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6200/10000 [19:53<12:02,  5.26step/s, loss=0.030699, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6201/10000 [19:53<12:10,  5.20step/s, loss=0.030699, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6201/10000 [19:53<12:10,  5.20step/s, loss=0.032353, elapsed=19.9min]

Step 6200/10000 | Train loss: 0.030699 | Elapsed: 19.9min | ETA: 12.2min

Entraînement:  62%|██████▏   | 6202/10000 [19:53<12:07,  5.22step/s, loss=0.032353, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6202/10000 [19:53<12:07,  5.22step/s, loss=0.032302, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6203/10000 [19:53<12:05,  5.23step/s, loss=0.032302, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6203/10000 [19:53<12:05,  5.23step/s, loss=0.036534, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6204/10000 [19:54<12:04,  5.24step/s, loss=0.036534, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6204/10000 [19:54<12:04,  5.24step/s, loss=0.063520, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6205/10000 [19:54<12:04,  5.24step/s, loss=0.063520, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6205/10000 [19:54<12:04,  5.24step/s, loss=0.069314, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6206/10000 [19:54<12:07,  5.22step/s, loss=0.069314, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6206/10000 [19:54<12:07,  5.22step/s, loss=0.054898, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6207/10000 [19:54<12:05,  5.22step/s, loss=0.054898, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6207/10000 [19:54<12:05,  5.22step/s, loss=0.031276, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6208/10000 [19:54<12:05,  5.23step/s, loss=0.031276, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6208/10000 [19:54<12:05,  5.23step/s, loss=0.084704, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6209/10000 [19:55<12:06,  5.22step/s, loss=0.084704, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6209/10000 [19:55<12:06,  5.22step/s, loss=0.025967, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6210/10000 [19:55<12:07,  5.21step/s, loss=0.025967, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6210/10000 [19:55<12:07,  5.21step/s, loss=0.050212, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6211/10000 [19:55<12:06,  5.21step/s, loss=0.050212, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6211/10000 [19:55<12:06,  5.21step/s, loss=0.027838, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6212/10000 [19:55<12:03,  5.23step/s, loss=0.027838, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6212/10000 [19:55<12:03,  5.23step/s, loss=0.035010, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6213/10000 [19:55<12:02,  5.24step/s, loss=0.035010, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6213/10000 [19:55<12:02,  5.24step/s, loss=0.030395, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6214/10000 [19:55<12:01,  5.25step/s, loss=0.030395, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6214/10000 [19:55<12:01,  5.25step/s, loss=0.024088, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6215/10000 [19:56<11:59,  5.26step/s, loss=0.024088, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6215/10000 [19:56<11:59,  5.26step/s, loss=0.036677, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6216/10000 [19:56<11:59,  5.26step/s, loss=0.036677, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6216/10000 [19:56<11:59,  5.26step/s, loss=0.047199, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6217/10000 [19:56<11:58,  5.27step/s, loss=0.047199, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6217/10000 [19:56<11:58,  5.27step/s, loss=0.037058, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6218/10000 [19:56<11:59,  5.26step/s, loss=0.037058, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6218/10000 [19:56<11:59,  5.26step/s, loss=0.070540, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6219/10000 [19:56<11:57,  5.27step/s, loss=0.070540, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6219/10000 [19:56<11:57,  5.27step/s, loss=0.029779, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6220/10000 [19:57<11:57,  5.27step/s, loss=0.029779, elapsed=19.9min]

Entraînement:  62%|██████▏   | 6220/10000 [19:57<11:57,  5.27step/s, loss=0.040880, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6221/10000 [19:57<11:56,  5.27step/s, loss=0.040880, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6221/10000 [19:57<11:56,  5.27step/s, loss=0.112321, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6222/10000 [19:57<11:56,  5.27step/s, loss=0.112321, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6222/10000 [19:57<11:56,  5.27step/s, loss=0.028449, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6223/10000 [19:57<11:56,  5.27step/s, loss=0.028449, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6223/10000 [19:57<11:56,  5.27step/s, loss=0.032793, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6224/10000 [19:57<11:58,  5.25step/s, loss=0.032793, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6224/10000 [19:57<11:58,  5.25step/s, loss=0.034275, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6225/10000 [19:58<11:59,  5.25step/s, loss=0.034275, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6225/10000 [19:58<11:59,  5.25step/s, loss=0.074185, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6226/10000 [19:58<11:57,  5.26step/s, loss=0.074185, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6226/10000 [19:58<11:57,  5.26step/s, loss=0.074632, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6227/10000 [19:58<11:57,  5.26step/s, loss=0.074632, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6227/10000 [19:58<11:57,  5.26step/s, loss=0.075383, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6228/10000 [19:58<11:56,  5.26step/s, loss=0.075383, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6228/10000 [19:58<11:56,  5.26step/s, loss=0.030352, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6229/10000 [19:58<11:57,  5.25step/s, loss=0.030352, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6229/10000 [19:58<11:57,  5.25step/s, loss=0.033426, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6230/10000 [19:59<11:56,  5.26step/s, loss=0.033426, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6230/10000 [19:59<11:56,  5.26step/s, loss=0.025102, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6231/10000 [19:59<11:55,  5.27step/s, loss=0.025102, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6231/10000 [19:59<11:55,  5.27step/s, loss=0.142887, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6232/10000 [19:59<11:56,  5.26step/s, loss=0.142887, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6232/10000 [19:59<11:56,  5.26step/s, loss=0.070684, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6233/10000 [19:59<11:56,  5.26step/s, loss=0.070684, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6233/10000 [19:59<11:56,  5.26step/s, loss=0.049519, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6234/10000 [19:59<11:56,  5.25step/s, loss=0.049519, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6234/10000 [19:59<11:56,  5.25step/s, loss=0.045805, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6235/10000 [19:59<11:55,  5.26step/s, loss=0.045805, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6235/10000 [19:59<11:55,  5.26step/s, loss=0.043823, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6236/10000 [20:00<11:55,  5.26step/s, loss=0.043823, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6236/10000 [20:00<11:55,  5.26step/s, loss=0.063806, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6237/10000 [20:00<11:55,  5.26step/s, loss=0.063806, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6237/10000 [20:00<11:55,  5.26step/s, loss=0.035584, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6238/10000 [20:00<11:55,  5.25step/s, loss=0.035584, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6238/10000 [20:00<11:55,  5.25step/s, loss=0.027766, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6239/10000 [20:00<11:55,  5.26step/s, loss=0.027766, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6239/10000 [20:00<11:55,  5.26step/s, loss=0.098276, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6240/10000 [20:00<11:56,  5.24step/s, loss=0.098276, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6240/10000 [20:00<11:56,  5.24step/s, loss=0.117434, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6241/10000 [20:01<11:55,  5.25step/s, loss=0.117434, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6241/10000 [20:01<11:55,  5.25step/s, loss=0.044319, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6242/10000 [20:01<11:55,  5.25step/s, loss=0.044319, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6242/10000 [20:01<11:55,  5.25step/s, loss=0.027763, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6243/10000 [20:01<11:54,  5.26step/s, loss=0.027763, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6243/10000 [20:01<11:54,  5.26step/s, loss=0.021002, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6244/10000 [20:01<11:53,  5.26step/s, loss=0.021002, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6244/10000 [20:01<11:53,  5.26step/s, loss=0.088007, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6245/10000 [20:01<11:53,  5.27step/s, loss=0.088007, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6245/10000 [20:01<11:53,  5.27step/s, loss=0.089314, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6246/10000 [20:02<11:52,  5.27step/s, loss=0.089314, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6246/10000 [20:02<11:52,  5.27step/s, loss=0.084351, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6247/10000 [20:02<11:53,  5.26step/s, loss=0.084351, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6247/10000 [20:02<11:53,  5.26step/s, loss=0.102123, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6248/10000 [20:02<11:53,  5.26step/s, loss=0.102123, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6248/10000 [20:02<11:53,  5.26step/s, loss=0.066076, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6249/10000 [20:02<11:54,  5.25step/s, loss=0.066076, elapsed=20.0min]

Entraînement:  62%|██████▏   | 6249/10000 [20:02<11:54,  5.25step/s, loss=0.044825, elapsed=20.0min]

Entraînement:  62%|██████▎   | 6250/10000 [20:02<11:56,  5.23step/s, loss=0.044825, elapsed=20.0min]

Entraînement:  62%|██████▎   | 6250/10000 [20:02<11:56,  5.23step/s, loss=0.104278, elapsed=20.0min]

Entraînement:  63%|██████▎   | 6251/10000 [20:03<11:57,  5.23step/s, loss=0.104278, elapsed=20.0min]

Entraînement:  63%|██████▎   | 6251/10000 [20:03<11:57,  5.23step/s, loss=0.040827, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6252/10000 [20:03<11:54,  5.24step/s, loss=0.040827, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6252/10000 [20:03<11:54,  5.24step/s, loss=0.062699, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6253/10000 [20:03<11:51,  5.26step/s, loss=0.062699, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6253/10000 [20:03<11:51,  5.26step/s, loss=0.027247, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6254/10000 [20:03<11:51,  5.27step/s, loss=0.027247, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6254/10000 [20:03<11:51,  5.27step/s, loss=0.042968, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6255/10000 [20:03<11:49,  5.28step/s, loss=0.042968, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6255/10000 [20:03<11:49,  5.28step/s, loss=0.061155, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6256/10000 [20:03<11:52,  5.25step/s, loss=0.061155, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6256/10000 [20:03<11:52,  5.25step/s, loss=0.094467, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6257/10000 [20:04<11:52,  5.25step/s, loss=0.094467, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6257/10000 [20:04<11:52,  5.25step/s, loss=0.039527, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6258/10000 [20:04<11:53,  5.24step/s, loss=0.039527, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6258/10000 [20:04<11:53,  5.24step/s, loss=0.028392, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6259/10000 [20:04<11:53,  5.24step/s, loss=0.028392, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6259/10000 [20:04<11:53,  5.24step/s, loss=0.025969, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6260/10000 [20:04<11:52,  5.25step/s, loss=0.025969, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6260/10000 [20:04<11:52,  5.25step/s, loss=0.040369, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6261/10000 [20:04<11:58,  5.20step/s, loss=0.040369, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6261/10000 [20:04<11:58,  5.20step/s, loss=0.048531, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6262/10000 [20:05<11:55,  5.22step/s, loss=0.048531, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6262/10000 [20:05<11:55,  5.22step/s, loss=0.042723, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6263/10000 [20:05<11:53,  5.23step/s, loss=0.042723, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6263/10000 [20:05<11:53,  5.23step/s, loss=0.030470, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6264/10000 [20:05<11:48,  5.27step/s, loss=0.030470, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6264/10000 [20:05<11:48,  5.27step/s, loss=0.034999, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6265/10000 [20:05<11:44,  5.30step/s, loss=0.034999, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6265/10000 [20:05<11:44,  5.30step/s, loss=0.096999, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6266/10000 [20:05<11:42,  5.31step/s, loss=0.096999, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6266/10000 [20:05<11:42,  5.31step/s, loss=0.126760, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6267/10000 [20:06<11:43,  5.31step/s, loss=0.126760, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6267/10000 [20:06<11:43,  5.31step/s, loss=0.020974, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6268/10000 [20:06<11:43,  5.30step/s, loss=0.020974, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6268/10000 [20:06<11:43,  5.30step/s, loss=0.037007, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6269/10000 [20:06<11:43,  5.31step/s, loss=0.037007, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6269/10000 [20:06<11:43,  5.31step/s, loss=0.053798, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6270/10000 [20:06<11:44,  5.29step/s, loss=0.053798, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6270/10000 [20:06<11:44,  5.29step/s, loss=0.036596, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6271/10000 [20:06<11:45,  5.29step/s, loss=0.036596, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6271/10000 [20:06<11:45,  5.29step/s, loss=0.038501, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6272/10000 [20:06<11:46,  5.28step/s, loss=0.038501, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6272/10000 [20:06<11:46,  5.28step/s, loss=0.038265, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6273/10000 [20:07<11:45,  5.29step/s, loss=0.038265, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6273/10000 [20:07<11:45,  5.29step/s, loss=0.036461, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6274/10000 [20:07<11:44,  5.29step/s, loss=0.036461, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6274/10000 [20:07<11:44,  5.29step/s, loss=0.074999, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6275/10000 [20:07<11:44,  5.29step/s, loss=0.074999, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6275/10000 [20:07<11:44,  5.29step/s, loss=0.078022, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6276/10000 [20:07<11:44,  5.29step/s, loss=0.078022, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6276/10000 [20:07<11:44,  5.29step/s, loss=0.104845, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6277/10000 [20:07<11:42,  5.30step/s, loss=0.104845, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6277/10000 [20:07<11:42,  5.30step/s, loss=0.043821, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6278/10000 [20:08<11:44,  5.29step/s, loss=0.043821, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6278/10000 [20:08<11:44,  5.29step/s, loss=0.022789, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6279/10000 [20:08<11:44,  5.28step/s, loss=0.022789, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6279/10000 [20:08<11:44,  5.28step/s, loss=0.023908, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6280/10000 [20:08<11:45,  5.27step/s, loss=0.023908, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6280/10000 [20:08<11:45,  5.27step/s, loss=0.048321, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6281/10000 [20:08<11:47,  5.26step/s, loss=0.048321, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6281/10000 [20:08<11:47,  5.26step/s, loss=0.033934, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6282/10000 [20:08<11:48,  5.25step/s, loss=0.033934, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6282/10000 [20:08<11:48,  5.25step/s, loss=0.040263, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6283/10000 [20:09<11:49,  5.24step/s, loss=0.040263, elapsed=20.1min]

Entraînement:  63%|██████▎   | 6283/10000 [20:09<11:49,  5.24step/s, loss=0.047466, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6284/10000 [20:09<11:48,  5.25step/s, loss=0.047466, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6284/10000 [20:09<11:48,  5.25step/s, loss=0.022418, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6285/10000 [20:09<11:46,  5.26step/s, loss=0.022418, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6285/10000 [20:09<11:46,  5.26step/s, loss=0.038340, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6286/10000 [20:09<11:47,  5.25step/s, loss=0.038340, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6286/10000 [20:09<11:47,  5.25step/s, loss=0.052192, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6287/10000 [20:09<11:46,  5.26step/s, loss=0.052192, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6287/10000 [20:09<11:46,  5.26step/s, loss=0.042535, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6288/10000 [20:10<11:45,  5.26step/s, loss=0.042535, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6288/10000 [20:10<11:45,  5.26step/s, loss=0.050242, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6289/10000 [20:10<11:44,  5.27step/s, loss=0.050242, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6289/10000 [20:10<11:44,  5.27step/s, loss=0.036519, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6290/10000 [20:10<11:44,  5.26step/s, loss=0.036519, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6290/10000 [20:10<11:44,  5.26step/s, loss=0.052284, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6291/10000 [20:10<11:44,  5.27step/s, loss=0.052284, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6291/10000 [20:10<11:44,  5.27step/s, loss=0.077604, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6292/10000 [20:10<11:45,  5.25step/s, loss=0.077604, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6292/10000 [20:10<11:45,  5.25step/s, loss=0.067852, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6293/10000 [20:10<11:45,  5.25step/s, loss=0.067852, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6293/10000 [20:10<11:45,  5.25step/s, loss=0.032924, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6294/10000 [20:11<11:45,  5.25step/s, loss=0.032924, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6294/10000 [20:11<11:45,  5.25step/s, loss=0.030118, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6295/10000 [20:11<11:42,  5.27step/s, loss=0.030118, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6295/10000 [20:11<11:42,  5.27step/s, loss=0.036215, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6296/10000 [20:11<11:43,  5.27step/s, loss=0.036215, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6296/10000 [20:11<11:43,  5.27step/s, loss=0.042925, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6297/10000 [20:11<11:42,  5.27step/s, loss=0.042925, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6297/10000 [20:11<11:42,  5.27step/s, loss=0.097042, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6298/10000 [20:11<11:40,  5.28step/s, loss=0.097042, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6298/10000 [20:11<11:40,  5.28step/s, loss=0.021695, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6299/10000 [20:12<11:40,  5.28step/s, loss=0.021695, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6299/10000 [20:12<11:40,  5.28step/s, loss=0.035694, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6300/10000 [20:12<11:40,  5.28step/s, loss=0.035694, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6300/10000 [20:12<11:40,  5.28step/s, loss=0.020040, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6300/10000 [20:12<11:40,  5.28step/s, loss=0.020040, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6301/10000 [20:12<11:47,  5.23step/s, loss=0.020040, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6301/10000 [20:12<11:47,  5.23step/s, loss=0.066580, elapsed=20.2min]

Step 6300/10000 | Train loss: 0.020040 | Elapsed: 20.2min | ETA: 11.9min

Entraînement:  63%|██████▎   | 6302/10000 [20:12<11:42,  5.26step/s, loss=0.066580, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6302/10000 [20:12<11:42,  5.26step/s, loss=0.047410, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6303/10000 [20:12<11:39,  5.28step/s, loss=0.047410, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6303/10000 [20:12<11:39,  5.28step/s, loss=0.041632, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6304/10000 [20:13<11:36,  5.31step/s, loss=0.041632, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6304/10000 [20:13<11:36,  5.31step/s, loss=0.033539, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6305/10000 [20:13<11:34,  5.32step/s, loss=0.033539, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6305/10000 [20:13<11:34,  5.32step/s, loss=0.041090, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6306/10000 [20:13<11:32,  5.34step/s, loss=0.041090, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6306/10000 [20:13<11:32,  5.34step/s, loss=0.028165, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6307/10000 [20:13<11:31,  5.34step/s, loss=0.028165, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6307/10000 [20:13<11:31,  5.34step/s, loss=0.028473, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6308/10000 [20:13<11:30,  5.35step/s, loss=0.028473, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6308/10000 [20:13<11:30,  5.35step/s, loss=0.033920, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6309/10000 [20:13<11:36,  5.30step/s, loss=0.033920, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6309/10000 [20:14<11:36,  5.30step/s, loss=0.069042, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6310/10000 [20:14<11:39,  5.28step/s, loss=0.069042, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6310/10000 [20:14<11:39,  5.28step/s, loss=0.023044, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6311/10000 [20:14<11:41,  5.26step/s, loss=0.023044, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6311/10000 [20:14<11:41,  5.26step/s, loss=0.018751, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6312/10000 [20:14<11:42,  5.25step/s, loss=0.018751, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6312/10000 [20:14<11:42,  5.25step/s, loss=0.018514, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6313/10000 [20:14<11:43,  5.24step/s, loss=0.018514, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6313/10000 [20:14<11:43,  5.24step/s, loss=0.072535, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6314/10000 [20:14<11:42,  5.25step/s, loss=0.072535, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6314/10000 [20:14<11:42,  5.25step/s, loss=0.038486, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6315/10000 [20:15<11:42,  5.24step/s, loss=0.038486, elapsed=20.2min]

Entraînement:  63%|██████▎   | 6315/10000 [20:15<11:42,  5.24step/s, loss=0.047016, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6316/10000 [20:15<11:42,  5.25step/s, loss=0.047016, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6316/10000 [20:15<11:42,  5.25step/s, loss=0.030284, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6317/10000 [20:15<11:41,  5.25step/s, loss=0.030284, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6317/10000 [20:15<11:41,  5.25step/s, loss=0.038724, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6318/10000 [20:15<11:42,  5.24step/s, loss=0.038724, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6318/10000 [20:15<11:42,  5.24step/s, loss=0.065766, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6319/10000 [20:15<11:41,  5.25step/s, loss=0.065766, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6319/10000 [20:15<11:41,  5.25step/s, loss=0.063457, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6320/10000 [20:16<11:41,  5.24step/s, loss=0.063457, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6320/10000 [20:16<11:41,  5.24step/s, loss=0.023519, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6321/10000 [20:16<11:41,  5.25step/s, loss=0.023519, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6321/10000 [20:16<11:41,  5.25step/s, loss=0.058294, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6322/10000 [20:16<11:41,  5.24step/s, loss=0.058294, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6322/10000 [20:16<11:41,  5.24step/s, loss=0.034727, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6323/10000 [20:16<11:41,  5.24step/s, loss=0.034727, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6323/10000 [20:16<11:41,  5.24step/s, loss=0.024256, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6324/10000 [20:16<11:44,  5.22step/s, loss=0.024256, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6324/10000 [20:16<11:44,  5.22step/s, loss=0.029496, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6325/10000 [20:17<11:43,  5.23step/s, loss=0.029496, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6325/10000 [20:17<11:43,  5.23step/s, loss=0.029627, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6326/10000 [20:17<11:42,  5.23step/s, loss=0.029627, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6326/10000 [20:17<11:42,  5.23step/s, loss=0.041385, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6327/10000 [20:17<11:41,  5.24step/s, loss=0.041385, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6327/10000 [20:17<11:41,  5.24step/s, loss=0.024275, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6328/10000 [20:17<11:41,  5.24step/s, loss=0.024275, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6328/10000 [20:17<11:41,  5.24step/s, loss=0.110300, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6329/10000 [20:17<11:39,  5.25step/s, loss=0.110300, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6329/10000 [20:17<11:39,  5.25step/s, loss=0.029892, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6330/10000 [20:18<11:39,  5.25step/s, loss=0.029892, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6330/10000 [20:18<11:39,  5.25step/s, loss=0.035713, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6331/10000 [20:18<11:38,  5.25step/s, loss=0.035713, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6331/10000 [20:18<11:38,  5.25step/s, loss=0.026647, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6332/10000 [20:18<11:41,  5.23step/s, loss=0.026647, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6332/10000 [20:18<11:41,  5.23step/s, loss=0.150124, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6333/10000 [20:18<11:39,  5.24step/s, loss=0.150124, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6333/10000 [20:18<11:39,  5.24step/s, loss=0.024130, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6334/10000 [20:18<11:39,  5.24step/s, loss=0.024130, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6334/10000 [20:18<11:39,  5.24step/s, loss=0.041786, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6335/10000 [20:18<11:38,  5.25step/s, loss=0.041786, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6335/10000 [20:18<11:38,  5.25step/s, loss=0.021427, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6336/10000 [20:19<11:37,  5.25step/s, loss=0.021427, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6336/10000 [20:19<11:37,  5.25step/s, loss=0.023235, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6337/10000 [20:19<11:36,  5.26step/s, loss=0.023235, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6337/10000 [20:19<11:36,  5.26step/s, loss=0.027176, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6338/10000 [20:19<11:34,  5.27step/s, loss=0.027176, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6338/10000 [20:19<11:34,  5.27step/s, loss=0.033212, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6339/10000 [20:19<11:36,  5.26step/s, loss=0.033212, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6339/10000 [20:19<11:36,  5.26step/s, loss=0.089715, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6340/10000 [20:19<11:36,  5.25step/s, loss=0.089715, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6340/10000 [20:19<11:36,  5.25step/s, loss=0.055120, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6341/10000 [20:20<11:36,  5.25step/s, loss=0.055120, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6341/10000 [20:20<11:36,  5.25step/s, loss=0.085602, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6342/10000 [20:20<11:35,  5.26step/s, loss=0.085602, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6342/10000 [20:20<11:35,  5.26step/s, loss=0.042507, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6343/10000 [20:20<11:40,  5.22step/s, loss=0.042507, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6343/10000 [20:20<11:40,  5.22step/s, loss=0.033105, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6344/10000 [20:20<11:35,  5.26step/s, loss=0.033105, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6344/10000 [20:20<11:35,  5.26step/s, loss=0.064111, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6345/10000 [20:20<11:30,  5.29step/s, loss=0.064111, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6345/10000 [20:20<11:30,  5.29step/s, loss=0.075567, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6346/10000 [20:21<11:27,  5.31step/s, loss=0.075567, elapsed=20.3min]

Entraînement:  63%|██████▎   | 6346/10000 [20:21<11:27,  5.31step/s, loss=0.043561, elapsed=20.4min]

Entraînement:  63%|██████▎   | 6347/10000 [20:21<11:29,  5.30step/s, loss=0.043561, elapsed=20.4min]

Entraînement:  63%|██████▎   | 6347/10000 [20:21<11:29,  5.30step/s, loss=0.090743, elapsed=20.4min]

Entraînement:  63%|██████▎   | 6348/10000 [20:21<11:29,  5.29step/s, loss=0.090743, elapsed=20.4min]

Entraînement:  63%|██████▎   | 6348/10000 [20:21<11:29,  5.29step/s, loss=0.037204, elapsed=20.4min]

Entraînement:  63%|██████▎   | 6349/10000 [20:21<11:30,  5.29step/s, loss=0.037204, elapsed=20.4min]

Entraînement:  63%|██████▎   | 6349/10000 [20:21<11:30,  5.29step/s, loss=0.042056, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6350/10000 [20:21<11:29,  5.29step/s, loss=0.042056, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6350/10000 [20:21<11:29,  5.29step/s, loss=0.054645, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6351/10000 [20:21<11:29,  5.29step/s, loss=0.054645, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6351/10000 [20:21<11:29,  5.29step/s, loss=0.037201, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6352/10000 [20:22<11:29,  5.29step/s, loss=0.037201, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6352/10000 [20:22<11:29,  5.29step/s, loss=0.048997, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6353/10000 [20:22<11:28,  5.30step/s, loss=0.048997, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6353/10000 [20:22<11:28,  5.30step/s, loss=0.061336, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6354/10000 [20:22<11:28,  5.30step/s, loss=0.061336, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6354/10000 [20:22<11:28,  5.30step/s, loss=0.058190, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6355/10000 [20:22<11:29,  5.28step/s, loss=0.058190, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6355/10000 [20:22<11:29,  5.28step/s, loss=0.026920, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6356/10000 [20:22<11:30,  5.28step/s, loss=0.026920, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6356/10000 [20:22<11:30,  5.28step/s, loss=0.075386, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6357/10000 [20:23<11:30,  5.28step/s, loss=0.075386, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6357/10000 [20:23<11:30,  5.28step/s, loss=0.027484, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6358/10000 [20:23<11:30,  5.27step/s, loss=0.027484, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6358/10000 [20:23<11:30,  5.27step/s, loss=0.063867, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6359/10000 [20:23<11:29,  5.28step/s, loss=0.063867, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6359/10000 [20:23<11:29,  5.28step/s, loss=0.048123, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6360/10000 [20:23<11:29,  5.28step/s, loss=0.048123, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6360/10000 [20:23<11:29,  5.28step/s, loss=0.032624, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6361/10000 [20:23<11:32,  5.25step/s, loss=0.032624, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6361/10000 [20:23<11:32,  5.25step/s, loss=0.036052, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6362/10000 [20:24<11:31,  5.26step/s, loss=0.036052, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6362/10000 [20:24<11:31,  5.26step/s, loss=0.051304, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6363/10000 [20:24<11:31,  5.26step/s, loss=0.051304, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6363/10000 [20:24<11:31,  5.26step/s, loss=0.024249, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6364/10000 [20:24<11:30,  5.26step/s, loss=0.024249, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6364/10000 [20:24<11:30,  5.26step/s, loss=0.023672, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6365/10000 [20:24<11:28,  5.28step/s, loss=0.023672, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6365/10000 [20:24<11:28,  5.28step/s, loss=0.095437, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6366/10000 [20:24<11:29,  5.27step/s, loss=0.095437, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6366/10000 [20:24<11:29,  5.27step/s, loss=0.028876, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6367/10000 [20:25<11:28,  5.28step/s, loss=0.028876, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6367/10000 [20:25<11:28,  5.28step/s, loss=0.046356, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6368/10000 [20:25<11:28,  5.27step/s, loss=0.046356, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6368/10000 [20:25<11:28,  5.27step/s, loss=0.037660, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6369/10000 [20:25<11:28,  5.28step/s, loss=0.037660, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6369/10000 [20:25<11:28,  5.28step/s, loss=0.185690, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6370/10000 [20:25<11:26,  5.28step/s, loss=0.185690, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6370/10000 [20:25<11:26,  5.28step/s, loss=0.057330, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6371/10000 [20:25<11:27,  5.28step/s, loss=0.057330, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6371/10000 [20:25<11:27,  5.28step/s, loss=0.061030, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6372/10000 [20:25<11:26,  5.28step/s, loss=0.061030, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6372/10000 [20:25<11:26,  5.28step/s, loss=0.058618, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6373/10000 [20:26<11:27,  5.28step/s, loss=0.058618, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6373/10000 [20:26<11:27,  5.28step/s, loss=0.057471, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6374/10000 [20:26<11:27,  5.28step/s, loss=0.057471, elapsed=20.4min]

Entraînement:  64%|██████▎   | 6374/10000 [20:26<11:27,  5.28step/s, loss=0.022255, elapsed=20.4min]

Entraînement:  64%|██████▍   | 6375/10000 [20:26<11:27,  5.27step/s, loss=0.022255, elapsed=20.4min]

Entraînement:  64%|██████▍   | 6375/10000 [20:26<11:27,  5.27step/s, loss=0.131241, elapsed=20.4min]

Entraînement:  64%|██████▍   | 6376/10000 [20:26<11:27,  5.27step/s, loss=0.131241, elapsed=20.4min]

Entraînement:  64%|██████▍   | 6376/10000 [20:26<11:27,  5.27step/s, loss=0.107803, elapsed=20.4min]

Entraînement:  64%|██████▍   | 6377/10000 [20:26<11:28,  5.26step/s, loss=0.107803, elapsed=20.4min]

Entraînement:  64%|██████▍   | 6377/10000 [20:26<11:28,  5.26step/s, loss=0.034471, elapsed=20.4min]

Entraînement:  64%|██████▍   | 6378/10000 [20:27<11:28,  5.26step/s, loss=0.034471, elapsed=20.4min]

Entraînement:  64%|██████▍   | 6378/10000 [20:27<11:28,  5.26step/s, loss=0.130362, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6379/10000 [20:27<11:28,  5.26step/s, loss=0.130362, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6379/10000 [20:27<11:28,  5.26step/s, loss=0.094235, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6380/10000 [20:27<11:27,  5.27step/s, loss=0.094235, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6380/10000 [20:27<11:27,  5.27step/s, loss=0.025050, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6381/10000 [20:27<11:25,  5.28step/s, loss=0.025050, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6381/10000 [20:27<11:25,  5.28step/s, loss=0.083797, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6382/10000 [20:27<11:25,  5.28step/s, loss=0.083797, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6382/10000 [20:27<11:25,  5.28step/s, loss=0.031976, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6383/10000 [20:28<11:25,  5.28step/s, loss=0.031976, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6383/10000 [20:28<11:25,  5.28step/s, loss=0.041692, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6384/10000 [20:28<11:25,  5.27step/s, loss=0.041692, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6384/10000 [20:28<11:25,  5.27step/s, loss=0.066585, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6385/10000 [20:28<11:25,  5.27step/s, loss=0.066585, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6385/10000 [20:28<11:25,  5.27step/s, loss=0.083319, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6386/10000 [20:28<11:24,  5.28step/s, loss=0.083319, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6386/10000 [20:28<11:24,  5.28step/s, loss=0.069100, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6387/10000 [20:28<11:25,  5.27step/s, loss=0.069100, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6387/10000 [20:28<11:25,  5.27step/s, loss=0.067461, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6388/10000 [20:29<11:25,  5.27step/s, loss=0.067461, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6388/10000 [20:29<11:25,  5.27step/s, loss=0.049613, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6389/10000 [20:29<11:22,  5.29step/s, loss=0.049613, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6389/10000 [20:29<11:22,  5.29step/s, loss=0.020956, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6390/10000 [20:29<11:22,  5.29step/s, loss=0.020956, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6390/10000 [20:29<11:22,  5.29step/s, loss=0.060009, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6391/10000 [20:29<11:22,  5.29step/s, loss=0.060009, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6391/10000 [20:29<11:22,  5.29step/s, loss=0.044498, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6392/10000 [20:29<11:21,  5.29step/s, loss=0.044498, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6392/10000 [20:29<11:21,  5.29step/s, loss=0.046027, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6393/10000 [20:29<11:22,  5.28step/s, loss=0.046027, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6393/10000 [20:29<11:22,  5.28step/s, loss=0.022768, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6394/10000 [20:30<11:21,  5.29step/s, loss=0.022768, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6394/10000 [20:30<11:21,  5.29step/s, loss=0.026053, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6395/10000 [20:30<11:22,  5.28step/s, loss=0.026053, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6395/10000 [20:30<11:22,  5.28step/s, loss=0.090445, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6396/10000 [20:30<11:21,  5.29step/s, loss=0.090445, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6396/10000 [20:30<11:21,  5.29step/s, loss=0.040344, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6397/10000 [20:30<11:22,  5.28step/s, loss=0.040344, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6397/10000 [20:30<11:22,  5.28step/s, loss=0.078357, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6398/10000 [20:30<11:23,  5.27step/s, loss=0.078357, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6398/10000 [20:30<11:23,  5.27step/s, loss=0.075637, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6399/10000 [20:31<11:22,  5.27step/s, loss=0.075637, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6399/10000 [20:31<11:22,  5.27step/s, loss=0.029896, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6400/10000 [20:31<11:22,  5.28step/s, loss=0.029896, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6400/10000 [20:31<11:22,  5.28step/s, loss=0.024909, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6400/10000 [20:31<11:22,  5.28step/s, loss=0.024909, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6401/10000 [20:31<11:30,  5.22step/s, loss=0.024909, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6401/10000 [20:31<11:30,  5.22step/s, loss=0.051715, elapsed=20.5min]

Step 6400/10000 | Train loss: 0.024909 | Elapsed: 20.5min | ETA: 11.5min

Entraînement:  64%|██████▍   | 6402/10000 [20:31<11:28,  5.22step/s, loss=0.051715, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6402/10000 [20:31<11:28,  5.22step/s, loss=0.041857, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6403/10000 [20:31<11:27,  5.23step/s, loss=0.041857, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6403/10000 [20:31<11:27,  5.23step/s, loss=0.051816, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6404/10000 [20:32<11:26,  5.24step/s, loss=0.051816, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6404/10000 [20:32<11:26,  5.24step/s, loss=0.021927, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6405/10000 [20:32<11:26,  5.24step/s, loss=0.021927, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6405/10000 [20:32<11:26,  5.24step/s, loss=0.040823, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6406/10000 [20:32<11:24,  5.25step/s, loss=0.040823, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6406/10000 [20:32<11:24,  5.25step/s, loss=0.031760, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6407/10000 [20:32<11:23,  5.26step/s, loss=0.031760, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6407/10000 [20:32<11:23,  5.26step/s, loss=0.040033, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6408/10000 [20:32<11:22,  5.26step/s, loss=0.040033, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6408/10000 [20:32<11:22,  5.26step/s, loss=0.016370, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6409/10000 [20:32<11:22,  5.26step/s, loss=0.016370, elapsed=20.5min]

Entraînement:  64%|██████▍   | 6409/10000 [20:32<11:22,  5.26step/s, loss=0.040225, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6410/10000 [20:33<11:22,  5.26step/s, loss=0.040225, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6410/10000 [20:33<11:22,  5.26step/s, loss=0.047483, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6411/10000 [20:33<11:20,  5.27step/s, loss=0.047483, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6411/10000 [20:33<11:20,  5.27step/s, loss=0.041081, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6412/10000 [20:33<11:19,  5.28step/s, loss=0.041081, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6412/10000 [20:33<11:19,  5.28step/s, loss=0.028420, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6413/10000 [20:33<11:18,  5.28step/s, loss=0.028420, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6413/10000 [20:33<11:18,  5.28step/s, loss=0.035528, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6414/10000 [20:33<11:18,  5.29step/s, loss=0.035528, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6414/10000 [20:33<11:18,  5.29step/s, loss=0.027763, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6415/10000 [20:34<11:17,  5.29step/s, loss=0.027763, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6415/10000 [20:34<11:17,  5.29step/s, loss=0.042491, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6416/10000 [20:34<11:20,  5.26step/s, loss=0.042491, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6416/10000 [20:34<11:20,  5.26step/s, loss=0.024772, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6417/10000 [20:34<11:20,  5.27step/s, loss=0.024772, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6417/10000 [20:34<11:20,  5.27step/s, loss=0.066756, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6418/10000 [20:34<11:18,  5.28step/s, loss=0.066756, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6418/10000 [20:34<11:18,  5.28step/s, loss=0.024711, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6419/10000 [20:34<11:17,  5.29step/s, loss=0.024711, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6419/10000 [20:34<11:17,  5.29step/s, loss=0.033576, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6420/10000 [20:35<11:17,  5.28step/s, loss=0.033576, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6420/10000 [20:35<11:17,  5.28step/s, loss=0.019455, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6421/10000 [20:35<11:16,  5.29step/s, loss=0.019455, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6421/10000 [20:35<11:16,  5.29step/s, loss=0.033071, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6422/10000 [20:35<11:16,  5.29step/s, loss=0.033071, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6422/10000 [20:35<11:16,  5.29step/s, loss=0.016438, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6423/10000 [20:35<11:15,  5.29step/s, loss=0.016438, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6423/10000 [20:35<11:15,  5.29step/s, loss=0.116703, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6424/10000 [20:35<11:15,  5.30step/s, loss=0.116703, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6424/10000 [20:35<11:15,  5.30step/s, loss=0.057688, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6425/10000 [20:36<11:16,  5.29step/s, loss=0.057688, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6425/10000 [20:36<11:16,  5.29step/s, loss=0.028247, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6426/10000 [20:36<11:15,  5.29step/s, loss=0.028247, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6426/10000 [20:36<11:15,  5.29step/s, loss=0.035594, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6427/10000 [20:36<11:15,  5.29step/s, loss=0.035594, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6427/10000 [20:36<11:15,  5.29step/s, loss=0.068185, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6428/10000 [20:36<11:14,  5.29step/s, loss=0.068185, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6428/10000 [20:36<11:14,  5.29step/s, loss=0.030025, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6429/10000 [20:36<11:13,  5.30step/s, loss=0.030025, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6429/10000 [20:36<11:13,  5.30step/s, loss=0.032950, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6430/10000 [20:36<11:13,  5.30step/s, loss=0.032950, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6430/10000 [20:36<11:13,  5.30step/s, loss=0.022363, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6431/10000 [20:37<11:13,  5.30step/s, loss=0.022363, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6431/10000 [20:37<11:13,  5.30step/s, loss=0.024813, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6432/10000 [20:37<11:12,  5.30step/s, loss=0.024813, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6432/10000 [20:37<11:12,  5.30step/s, loss=0.058171, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6433/10000 [20:37<11:12,  5.31step/s, loss=0.058171, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6433/10000 [20:37<11:12,  5.31step/s, loss=0.025503, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6434/10000 [20:37<11:13,  5.30step/s, loss=0.025503, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6434/10000 [20:37<11:13,  5.30step/s, loss=0.097551, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6435/10000 [20:37<11:13,  5.30step/s, loss=0.097551, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6435/10000 [20:37<11:13,  5.30step/s, loss=0.028684, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6436/10000 [20:38<11:14,  5.28step/s, loss=0.028684, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6436/10000 [20:38<11:14,  5.28step/s, loss=0.028705, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6437/10000 [20:38<11:14,  5.28step/s, loss=0.028705, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6437/10000 [20:38<11:14,  5.28step/s, loss=0.130858, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6438/10000 [20:38<11:13,  5.29step/s, loss=0.130858, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6438/10000 [20:38<11:13,  5.29step/s, loss=0.058933, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6439/10000 [20:38<11:13,  5.29step/s, loss=0.058933, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6439/10000 [20:38<11:13,  5.29step/s, loss=0.062615, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6440/10000 [20:38<11:12,  5.29step/s, loss=0.062615, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6440/10000 [20:38<11:12,  5.29step/s, loss=0.045578, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6441/10000 [20:39<11:12,  5.29step/s, loss=0.045578, elapsed=20.6min]

Entraînement:  64%|██████▍   | 6441/10000 [20:39<11:12,  5.29step/s, loss=0.030373, elapsed=20.7min]

Entraînement:  64%|██████▍   | 6442/10000 [20:39<11:12,  5.29step/s, loss=0.030373, elapsed=20.7min]

Entraînement:  64%|██████▍   | 6442/10000 [20:39<11:12,  5.29step/s, loss=0.026202, elapsed=20.7min]

Entraînement:  64%|██████▍   | 6443/10000 [20:39<11:11,  5.30step/s, loss=0.026202, elapsed=20.7min]

Entraînement:  64%|██████▍   | 6443/10000 [20:39<11:11,  5.30step/s, loss=0.050265, elapsed=20.7min]

Entraînement:  64%|██████▍   | 6444/10000 [20:39<11:12,  5.29step/s, loss=0.050265, elapsed=20.7min]

Entraînement:  64%|██████▍   | 6444/10000 [20:39<11:12,  5.29step/s, loss=0.097810, elapsed=20.7min]

Entraînement:  64%|██████▍   | 6445/10000 [20:39<11:12,  5.29step/s, loss=0.097810, elapsed=20.7min]

Entraînement:  64%|██████▍   | 6445/10000 [20:39<11:12,  5.29step/s, loss=0.079843, elapsed=20.7min]

Entraînement:  64%|██████▍   | 6446/10000 [20:39<11:12,  5.29step/s, loss=0.079843, elapsed=20.7min]

Entraînement:  64%|██████▍   | 6446/10000 [20:39<11:12,  5.29step/s, loss=0.088298, elapsed=20.7min]

Entraînement:  64%|██████▍   | 6447/10000 [20:40<11:11,  5.29step/s, loss=0.088298, elapsed=20.7min]

Entraînement:  64%|██████▍   | 6447/10000 [20:40<11:11,  5.29step/s, loss=0.030856, elapsed=20.7min]

Entraînement:  64%|██████▍   | 6448/10000 [20:40<11:10,  5.30step/s, loss=0.030856, elapsed=20.7min]

Entraînement:  64%|██████▍   | 6448/10000 [20:40<11:10,  5.30step/s, loss=0.081115, elapsed=20.7min]

Entraînement:  64%|██████▍   | 6449/10000 [20:40<11:13,  5.28step/s, loss=0.081115, elapsed=20.7min]

Entraînement:  64%|██████▍   | 6449/10000 [20:40<11:13,  5.28step/s, loss=0.021499, elapsed=20.7min]

Entraînement:  64%|██████▍   | 6450/10000 [20:40<11:12,  5.28step/s, loss=0.021499, elapsed=20.7min]

Entraînement:  64%|██████▍   | 6450/10000 [20:40<11:12,  5.28step/s, loss=0.024349, elapsed=20.7min]

Entraînement:  65%|██████▍   | 6451/10000 [20:40<11:11,  5.28step/s, loss=0.024349, elapsed=20.7min]

Entraînement:  65%|██████▍   | 6451/10000 [20:40<11:11,  5.28step/s, loss=0.038799, elapsed=20.7min]

Entraînement:  65%|██████▍   | 6452/10000 [20:41<11:11,  5.29step/s, loss=0.038799, elapsed=20.7min]

Entraînement:  65%|██████▍   | 6452/10000 [20:41<11:11,  5.29step/s, loss=0.027693, elapsed=20.7min]

Entraînement:  65%|██████▍   | 6453/10000 [20:41<11:11,  5.28step/s, loss=0.027693, elapsed=20.7min]

Entraînement:  65%|██████▍   | 6453/10000 [20:41<11:11,  5.28step/s, loss=0.084665, elapsed=20.7min]

Entraînement:  65%|██████▍   | 6454/10000 [20:41<11:10,  5.29step/s, loss=0.084665, elapsed=20.7min]

Entraînement:  65%|██████▍   | 6454/10000 [20:41<11:10,  5.29step/s, loss=0.029766, elapsed=20.7min]

Entraînement:  65%|██████▍   | 6455/10000 [20:41<11:10,  5.29step/s, loss=0.029766, elapsed=20.7min]

Entraînement:  65%|██████▍   | 6455/10000 [20:41<11:10,  5.29step/s, loss=0.037213, elapsed=20.7min]

Entraînement:  65%|██████▍   | 6456/10000 [20:41<11:10,  5.29step/s, loss=0.037213, elapsed=20.7min]

Entraînement:  65%|██████▍   | 6456/10000 [20:41<11:10,  5.29step/s, loss=0.022845, elapsed=20.7min]

Entraînement:  65%|██████▍   | 6457/10000 [20:42<11:08,  5.30step/s, loss=0.022845, elapsed=20.7min]

Entraînement:  65%|██████▍   | 6457/10000 [20:42<11:08,  5.30step/s, loss=0.035398, elapsed=20.7min]

Entraînement:  65%|██████▍   | 6458/10000 [20:42<11:09,  5.29step/s, loss=0.035398, elapsed=20.7min]

Entraînement:  65%|██████▍   | 6458/10000 [20:42<11:09,  5.29step/s, loss=0.029583, elapsed=20.7min]

Entraînement:  65%|██████▍   | 6459/10000 [20:42<11:09,  5.29step/s, loss=0.029583, elapsed=20.7min]

Entraînement:  65%|██████▍   | 6459/10000 [20:42<11:09,  5.29step/s, loss=0.029758, elapsed=20.7min]

Entraînement:  65%|██████▍   | 6460/10000 [20:42<11:09,  5.29step/s, loss=0.029758, elapsed=20.7min]

Entraînement:  65%|██████▍   | 6460/10000 [20:42<11:09,  5.29step/s, loss=0.049464, elapsed=20.7min]

Entraînement:  65%|██████▍   | 6461/10000 [20:42<11:10,  5.28step/s, loss=0.049464, elapsed=20.7min]

Entraînement:  65%|██████▍   | 6461/10000 [20:42<11:10,  5.28step/s, loss=0.022736, elapsed=20.7min]

Entraînement:  65%|██████▍   | 6462/10000 [20:43<11:09,  5.29step/s, loss=0.022736, elapsed=20.7min]

Entraînement:  65%|██████▍   | 6462/10000 [20:43<11:09,  5.29step/s, loss=0.095852, elapsed=20.7min]

Entraînement:  65%|██████▍   | 6463/10000 [20:43<11:08,  5.29step/s, loss=0.095852, elapsed=20.7min]

Entraînement:  65%|██████▍   | 6463/10000 [20:43<11:08,  5.29step/s, loss=0.110422, elapsed=20.7min]

Entraînement:  65%|██████▍   | 6464/10000 [20:43<11:08,  5.29step/s, loss=0.110422, elapsed=20.7min]

Entraînement:  65%|██████▍   | 6464/10000 [20:43<11:08,  5.29step/s, loss=0.028280, elapsed=20.7min]

Entraînement:  65%|██████▍   | 6465/10000 [20:43<11:08,  5.29step/s, loss=0.028280, elapsed=20.7min]

Entraînement:  65%|██████▍   | 6465/10000 [20:43<11:08,  5.29step/s, loss=0.077238, elapsed=20.7min]

Entraînement:  65%|██████▍   | 6466/10000 [20:43<11:09,  5.28step/s, loss=0.077238, elapsed=20.7min]

Entraînement:  65%|██████▍   | 6466/10000 [20:43<11:09,  5.28step/s, loss=0.062180, elapsed=20.7min]

Entraînement:  65%|██████▍   | 6467/10000 [20:43<11:10,  5.27step/s, loss=0.062180, elapsed=20.7min]

Entraînement:  65%|██████▍   | 6467/10000 [20:43<11:10,  5.27step/s, loss=0.069437, elapsed=20.7min]

Entraînement:  65%|██████▍   | 6468/10000 [20:44<11:09,  5.28step/s, loss=0.069437, elapsed=20.7min]

Entraînement:  65%|██████▍   | 6468/10000 [20:44<11:09,  5.28step/s, loss=0.032502, elapsed=20.7min]

Entraînement:  65%|██████▍   | 6469/10000 [20:44<11:10,  5.27step/s, loss=0.032502, elapsed=20.7min]

Entraînement:  65%|██████▍   | 6469/10000 [20:44<11:10,  5.27step/s, loss=0.078871, elapsed=20.7min]

Entraînement:  65%|██████▍   | 6470/10000 [20:44<11:09,  5.27step/s, loss=0.078871, elapsed=20.7min]

Entraînement:  65%|██████▍   | 6470/10000 [20:44<11:09,  5.27step/s, loss=0.043322, elapsed=20.7min]

Entraînement:  65%|██████▍   | 6471/10000 [20:44<11:09,  5.27step/s, loss=0.043322, elapsed=20.7min]

Entraînement:  65%|██████▍   | 6471/10000 [20:44<11:09,  5.27step/s, loss=0.040813, elapsed=20.7min]

Entraînement:  65%|██████▍   | 6472/10000 [20:44<11:10,  5.26step/s, loss=0.040813, elapsed=20.7min]

Entraînement:  65%|██████▍   | 6472/10000 [20:44<11:10,  5.26step/s, loss=0.095515, elapsed=20.7min]

Entraînement:  65%|██████▍   | 6473/10000 [20:45<11:11,  5.26step/s, loss=0.095515, elapsed=20.7min]

Entraînement:  65%|██████▍   | 6473/10000 [20:45<11:11,  5.26step/s, loss=0.070229, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6474/10000 [20:45<11:10,  5.26step/s, loss=0.070229, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6474/10000 [20:45<11:10,  5.26step/s, loss=0.047382, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6475/10000 [20:45<11:10,  5.26step/s, loss=0.047382, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6475/10000 [20:45<11:10,  5.26step/s, loss=0.066370, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6476/10000 [20:45<11:10,  5.25step/s, loss=0.066370, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6476/10000 [20:45<11:10,  5.25step/s, loss=0.053631, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6477/10000 [20:45<11:11,  5.25step/s, loss=0.053631, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6477/10000 [20:45<11:11,  5.25step/s, loss=0.048443, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6478/10000 [20:46<11:09,  5.26step/s, loss=0.048443, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6478/10000 [20:46<11:09,  5.26step/s, loss=0.040984, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6479/10000 [20:46<11:11,  5.25step/s, loss=0.040984, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6479/10000 [20:46<11:11,  5.25step/s, loss=0.065828, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6480/10000 [20:46<11:08,  5.26step/s, loss=0.065828, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6480/10000 [20:46<11:08,  5.26step/s, loss=0.027907, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6481/10000 [20:46<11:07,  5.27step/s, loss=0.027907, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6481/10000 [20:46<11:07,  5.27step/s, loss=0.029377, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6482/10000 [20:46<11:05,  5.29step/s, loss=0.029377, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6482/10000 [20:46<11:05,  5.29step/s, loss=0.016901, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6483/10000 [20:47<11:04,  5.30step/s, loss=0.016901, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6483/10000 [20:47<11:04,  5.30step/s, loss=0.079717, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6484/10000 [20:47<11:04,  5.29step/s, loss=0.079717, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6484/10000 [20:47<11:04,  5.29step/s, loss=0.033058, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6485/10000 [20:47<11:03,  5.30step/s, loss=0.033058, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6485/10000 [20:47<11:03,  5.30step/s, loss=0.033545, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6486/10000 [20:47<11:02,  5.31step/s, loss=0.033545, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6486/10000 [20:47<11:02,  5.31step/s, loss=0.042731, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6487/10000 [20:47<11:01,  5.31step/s, loss=0.042731, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6487/10000 [20:47<11:01,  5.31step/s, loss=0.019707, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6488/10000 [20:47<11:00,  5.31step/s, loss=0.019707, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6488/10000 [20:47<11:00,  5.31step/s, loss=0.033830, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6489/10000 [20:48<16:49,  3.48step/s, loss=0.033830, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6489/10000 [20:48<16:49,  3.48step/s, loss=0.045171, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6490/10000 [20:48<15:11,  3.85step/s, loss=0.045171, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6490/10000 [20:48<15:11,  3.85step/s, loss=0.036735, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6491/10000 [20:48<13:58,  4.19step/s, loss=0.036735, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6491/10000 [20:48<13:58,  4.19step/s, loss=0.036068, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6492/10000 [20:49<13:06,  4.46step/s, loss=0.036068, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6492/10000 [20:49<13:06,  4.46step/s, loss=0.055816, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6493/10000 [20:49<12:30,  4.67step/s, loss=0.055816, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6493/10000 [20:49<12:30,  4.67step/s, loss=0.058021, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6494/10000 [20:49<12:04,  4.84step/s, loss=0.058021, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6494/10000 [20:49<12:04,  4.84step/s, loss=0.057959, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6495/10000 [20:49<11:46,  4.96step/s, loss=0.057959, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6495/10000 [20:49<11:46,  4.96step/s, loss=0.038158, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6496/10000 [20:49<11:33,  5.05step/s, loss=0.038158, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6496/10000 [20:49<11:33,  5.05step/s, loss=0.084308, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6497/10000 [20:49<11:24,  5.12step/s, loss=0.084308, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6497/10000 [20:49<11:24,  5.12step/s, loss=0.039317, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6498/10000 [20:50<11:17,  5.17step/s, loss=0.039317, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6498/10000 [20:50<11:17,  5.17step/s, loss=0.046690, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6499/10000 [20:50<11:12,  5.21step/s, loss=0.046690, elapsed=20.8min]

Entraînement:  65%|██████▍   | 6499/10000 [20:50<11:12,  5.21step/s, loss=0.059372, elapsed=20.8min]

Entraînement:  65%|██████▌   | 6500/10000 [20:50<11:10,  5.22step/s, loss=0.059372, elapsed=20.8min]

Entraînement:  65%|██████▌   | 6500/10000 [20:50<11:10,  5.22step/s, loss=0.054994, elapsed=20.8min]

Entraînement:  65%|██████▌   | 6500/10000 [20:50<11:10,  5.22step/s, loss=0.054994, elapsed=20.8min]

Entraînement:  65%|██████▌   | 6501/10000 [20:50<11:14,  5.19step/s, loss=0.054994, elapsed=20.8min]

Entraînement:  65%|██████▌   | 6501/10000 [20:50<11:14,  5.19step/s, loss=0.044032, elapsed=20.8min]

Step 6500/10000 | Train loss: 0.054994 | Elapsed: 20.8min | ETA: 11.2min

Entraînement:  65%|██████▌   | 6502/10000 [20:50<11:12,  5.20step/s, loss=0.044032, elapsed=20.8min]

Entraînement:  65%|██████▌   | 6502/10000 [20:50<11:12,  5.20step/s, loss=0.071185, elapsed=20.8min]

Entraînement:  65%|██████▌   | 6503/10000 [20:51<11:09,  5.22step/s, loss=0.071185, elapsed=20.8min]

Entraînement:  65%|██████▌   | 6503/10000 [20:51<11:09,  5.22step/s, loss=0.028486, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6504/10000 [20:51<11:07,  5.24step/s, loss=0.028486, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6504/10000 [20:51<11:07,  5.24step/s, loss=0.063042, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6505/10000 [20:51<11:05,  5.25step/s, loss=0.063042, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6505/10000 [20:51<11:05,  5.25step/s, loss=0.048660, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6506/10000 [20:51<11:04,  5.26step/s, loss=0.048660, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6506/10000 [20:51<11:04,  5.26step/s, loss=0.043647, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6507/10000 [20:51<11:05,  5.25step/s, loss=0.043647, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6507/10000 [20:51<11:05,  5.25step/s, loss=0.074811, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6508/10000 [20:52<11:05,  5.25step/s, loss=0.074811, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6508/10000 [20:52<11:05,  5.25step/s, loss=0.035148, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6509/10000 [20:52<11:06,  5.24step/s, loss=0.035148, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6509/10000 [20:52<11:06,  5.24step/s, loss=0.041083, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6510/10000 [20:52<11:04,  5.25step/s, loss=0.041083, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6510/10000 [20:52<11:04,  5.25step/s, loss=0.068032, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6511/10000 [20:52<11:05,  5.25step/s, loss=0.068032, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6511/10000 [20:52<11:05,  5.25step/s, loss=0.026318, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6512/10000 [20:52<11:03,  5.26step/s, loss=0.026318, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6512/10000 [20:52<11:03,  5.26step/s, loss=0.041370, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6513/10000 [20:53<11:03,  5.25step/s, loss=0.041370, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6513/10000 [20:53<11:03,  5.25step/s, loss=0.052139, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6514/10000 [20:53<11:02,  5.26step/s, loss=0.052139, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6514/10000 [20:53<11:02,  5.26step/s, loss=0.024233, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6515/10000 [20:53<11:02,  5.26step/s, loss=0.024233, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6515/10000 [20:53<11:02,  5.26step/s, loss=0.020168, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6516/10000 [20:53<11:03,  5.25step/s, loss=0.020168, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6516/10000 [20:53<11:03,  5.25step/s, loss=0.040360, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6517/10000 [20:53<11:03,  5.25step/s, loss=0.040360, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6517/10000 [20:53<11:03,  5.25step/s, loss=0.097146, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6518/10000 [20:53<11:03,  5.25step/s, loss=0.097146, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6518/10000 [20:53<11:03,  5.25step/s, loss=0.087957, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6519/10000 [20:54<11:04,  5.24step/s, loss=0.087957, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6519/10000 [20:54<11:04,  5.24step/s, loss=0.047773, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6520/10000 [20:54<11:05,  5.23step/s, loss=0.047773, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6520/10000 [20:54<11:05,  5.23step/s, loss=0.023086, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6521/10000 [20:54<11:03,  5.24step/s, loss=0.023086, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6521/10000 [20:54<11:03,  5.24step/s, loss=0.035746, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6522/10000 [20:54<11:03,  5.24step/s, loss=0.035746, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6522/10000 [20:54<11:03,  5.24step/s, loss=0.077347, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6523/10000 [20:54<11:02,  5.25step/s, loss=0.077347, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6523/10000 [20:54<11:02,  5.25step/s, loss=0.023753, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6524/10000 [20:55<11:02,  5.25step/s, loss=0.023753, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6524/10000 [20:55<11:02,  5.25step/s, loss=0.037241, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6525/10000 [20:55<11:01,  5.26step/s, loss=0.037241, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6525/10000 [20:55<11:01,  5.26step/s, loss=0.031910, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6526/10000 [20:55<11:01,  5.25step/s, loss=0.031910, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6526/10000 [20:55<11:01,  5.25step/s, loss=0.042785, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6527/10000 [20:55<11:00,  5.25step/s, loss=0.042785, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6527/10000 [20:55<11:00,  5.25step/s, loss=0.048922, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6528/10000 [20:55<11:00,  5.26step/s, loss=0.048922, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6528/10000 [20:55<11:00,  5.26step/s, loss=0.110569, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6529/10000 [20:56<11:00,  5.26step/s, loss=0.110569, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6529/10000 [20:56<11:00,  5.26step/s, loss=0.056661, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6530/10000 [20:56<10:59,  5.26step/s, loss=0.056661, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6530/10000 [20:56<10:59,  5.26step/s, loss=0.054198, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6531/10000 [20:56<10:59,  5.26step/s, loss=0.054198, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6531/10000 [20:56<10:59,  5.26step/s, loss=0.067235, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6532/10000 [20:56<10:57,  5.27step/s, loss=0.067235, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6532/10000 [20:56<10:57,  5.27step/s, loss=0.020102, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6533/10000 [20:56<10:58,  5.27step/s, loss=0.020102, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6533/10000 [20:56<10:58,  5.27step/s, loss=0.096718, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6534/10000 [20:57<10:58,  5.26step/s, loss=0.096718, elapsed=20.9min]

Entraînement:  65%|██████▌   | 6534/10000 [20:57<10:58,  5.26step/s, loss=0.040133, elapsed=21.0min]

Entraînement:  65%|██████▌   | 6535/10000 [20:57<10:59,  5.26step/s, loss=0.040133, elapsed=21.0min]

Entraînement:  65%|██████▌   | 6535/10000 [20:57<10:59,  5.26step/s, loss=0.055889, elapsed=21.0min]

Entraînement:  65%|██████▌   | 6536/10000 [20:57<10:58,  5.26step/s, loss=0.055889, elapsed=21.0min]

Entraînement:  65%|██████▌   | 6536/10000 [20:57<10:58,  5.26step/s, loss=0.037219, elapsed=21.0min]

Entraînement:  65%|██████▌   | 6537/10000 [20:57<10:58,  5.26step/s, loss=0.037219, elapsed=21.0min]

Entraînement:  65%|██████▌   | 6537/10000 [20:57<10:58,  5.26step/s, loss=0.056072, elapsed=21.0min]

Entraînement:  65%|██████▌   | 6538/10000 [20:57<10:57,  5.26step/s, loss=0.056072, elapsed=21.0min]

Entraînement:  65%|██████▌   | 6538/10000 [20:57<10:57,  5.26step/s, loss=0.029167, elapsed=21.0min]

Entraînement:  65%|██████▌   | 6539/10000 [20:57<10:56,  5.27step/s, loss=0.029167, elapsed=21.0min]

Entraînement:  65%|██████▌   | 6539/10000 [20:57<10:56,  5.27step/s, loss=0.099920, elapsed=21.0min]

Entraînement:  65%|██████▌   | 6540/10000 [20:58<10:56,  5.27step/s, loss=0.099920, elapsed=21.0min]

Entraînement:  65%|██████▌   | 6540/10000 [20:58<10:56,  5.27step/s, loss=0.042398, elapsed=21.0min]

Entraînement:  65%|██████▌   | 6541/10000 [20:58<10:56,  5.27step/s, loss=0.042398, elapsed=21.0min]

Entraînement:  65%|██████▌   | 6541/10000 [20:58<10:56,  5.27step/s, loss=0.054032, elapsed=21.0min]

Entraînement:  65%|██████▌   | 6542/10000 [20:58<10:57,  5.26step/s, loss=0.054032, elapsed=21.0min]

Entraînement:  65%|██████▌   | 6542/10000 [20:58<10:57,  5.26step/s, loss=0.025487, elapsed=21.0min]

Entraînement:  65%|██████▌   | 6543/10000 [20:58<10:56,  5.26step/s, loss=0.025487, elapsed=21.0min]

Entraînement:  65%|██████▌   | 6543/10000 [20:58<10:56,  5.26step/s, loss=0.046160, elapsed=21.0min]

Entraînement:  65%|██████▌   | 6544/10000 [20:58<10:56,  5.26step/s, loss=0.046160, elapsed=21.0min]

Entraînement:  65%|██████▌   | 6544/10000 [20:58<10:56,  5.26step/s, loss=0.036747, elapsed=21.0min]

Entraînement:  65%|██████▌   | 6545/10000 [20:59<11:02,  5.22step/s, loss=0.036747, elapsed=21.0min]

Entraînement:  65%|██████▌   | 6545/10000 [20:59<11:02,  5.22step/s, loss=0.042410, elapsed=21.0min]

Entraînement:  65%|██████▌   | 6546/10000 [20:59<10:59,  5.23step/s, loss=0.042410, elapsed=21.0min]

Entraînement:  65%|██████▌   | 6546/10000 [20:59<10:59,  5.23step/s, loss=0.061031, elapsed=21.0min]

Entraînement:  65%|██████▌   | 6547/10000 [20:59<10:57,  5.25step/s, loss=0.061031, elapsed=21.0min]

Entraînement:  65%|██████▌   | 6547/10000 [20:59<10:57,  5.25step/s, loss=0.027394, elapsed=21.0min]

Entraînement:  65%|██████▌   | 6548/10000 [20:59<10:57,  5.25step/s, loss=0.027394, elapsed=21.0min]

Entraînement:  65%|██████▌   | 6548/10000 [20:59<10:57,  5.25step/s, loss=0.030259, elapsed=21.0min]

Entraînement:  65%|██████▌   | 6549/10000 [20:59<10:57,  5.25step/s, loss=0.030259, elapsed=21.0min]

Entraînement:  65%|██████▌   | 6549/10000 [20:59<10:57,  5.25step/s, loss=0.072820, elapsed=21.0min]

Entraînement:  66%|██████▌   | 6550/10000 [21:00<10:54,  5.27step/s, loss=0.072820, elapsed=21.0min]

Entraînement:  66%|██████▌   | 6550/10000 [21:00<10:54,  5.27step/s, loss=0.038501, elapsed=21.0min]

Entraînement:  66%|██████▌   | 6551/10000 [21:00<10:54,  5.27step/s, loss=0.038501, elapsed=21.0min]

Entraînement:  66%|██████▌   | 6551/10000 [21:00<10:54,  5.27step/s, loss=0.030232, elapsed=21.0min]

Entraînement:  66%|██████▌   | 6552/10000 [21:00<10:53,  5.27step/s, loss=0.030232, elapsed=21.0min]

Entraînement:  66%|██████▌   | 6552/10000 [21:00<10:53,  5.27step/s, loss=0.023362, elapsed=21.0min]

Entraînement:  66%|██████▌   | 6553/10000 [21:00<10:53,  5.28step/s, loss=0.023362, elapsed=21.0min]

Entraînement:  66%|██████▌   | 6553/10000 [21:00<10:53,  5.28step/s, loss=0.032928, elapsed=21.0min]

Entraînement:  66%|██████▌   | 6554/10000 [21:00<10:52,  5.28step/s, loss=0.032928, elapsed=21.0min]

Entraînement:  66%|██████▌   | 6554/10000 [21:00<10:52,  5.28step/s, loss=0.019417, elapsed=21.0min]

Entraînement:  66%|██████▌   | 6555/10000 [21:01<10:51,  5.28step/s, loss=0.019417, elapsed=21.0min]

Entraînement:  66%|██████▌   | 6555/10000 [21:01<10:51,  5.28step/s, loss=0.029191, elapsed=21.0min]

Entraînement:  66%|██████▌   | 6556/10000 [21:01<10:52,  5.28step/s, loss=0.029191, elapsed=21.0min]

Entraînement:  66%|██████▌   | 6556/10000 [21:01<10:52,  5.28step/s, loss=0.022721, elapsed=21.0min]

Entraînement:  66%|██████▌   | 6557/10000 [21:01<10:52,  5.28step/s, loss=0.022721, elapsed=21.0min]

Entraînement:  66%|██████▌   | 6557/10000 [21:01<10:52,  5.28step/s, loss=0.061499, elapsed=21.0min]

Entraînement:  66%|██████▌   | 6558/10000 [21:01<10:52,  5.28step/s, loss=0.061499, elapsed=21.0min]

Entraînement:  66%|██████▌   | 6558/10000 [21:01<10:52,  5.28step/s, loss=0.041750, elapsed=21.0min]

Entraînement:  66%|██████▌   | 6559/10000 [21:01<10:51,  5.28step/s, loss=0.041750, elapsed=21.0min]

Entraînement:  66%|██████▌   | 6559/10000 [21:01<10:51,  5.28step/s, loss=0.036418, elapsed=21.0min]

Entraînement:  66%|██████▌   | 6560/10000 [21:01<10:51,  5.28step/s, loss=0.036418, elapsed=21.0min]

Entraînement:  66%|██████▌   | 6560/10000 [21:01<10:51,  5.28step/s, loss=0.035558, elapsed=21.0min]

Entraînement:  66%|██████▌   | 6561/10000 [21:02<10:50,  5.29step/s, loss=0.035558, elapsed=21.0min]

Entraînement:  66%|██████▌   | 6561/10000 [21:02<10:50,  5.29step/s, loss=0.119773, elapsed=21.0min]

Entraînement:  66%|██████▌   | 6562/10000 [21:02<10:49,  5.30step/s, loss=0.119773, elapsed=21.0min]

Entraînement:  66%|██████▌   | 6562/10000 [21:02<10:49,  5.30step/s, loss=0.053971, elapsed=21.0min]

Entraînement:  66%|██████▌   | 6563/10000 [21:02<10:48,  5.30step/s, loss=0.053971, elapsed=21.0min]

Entraînement:  66%|██████▌   | 6563/10000 [21:02<10:48,  5.30step/s, loss=0.030633, elapsed=21.0min]

Entraînement:  66%|██████▌   | 6564/10000 [21:02<10:48,  5.30step/s, loss=0.030633, elapsed=21.0min]

Entraînement:  66%|██████▌   | 6564/10000 [21:02<10:48,  5.30step/s, loss=0.036098, elapsed=21.0min]

Entraînement:  66%|██████▌   | 6565/10000 [21:02<10:49,  5.29step/s, loss=0.036098, elapsed=21.0min]

Entraînement:  66%|██████▌   | 6565/10000 [21:02<10:49,  5.29step/s, loss=0.017874, elapsed=21.0min]

Entraînement:  66%|██████▌   | 6566/10000 [21:03<10:49,  5.29step/s, loss=0.017874, elapsed=21.0min]

Entraînement:  66%|██████▌   | 6566/10000 [21:03<10:49,  5.29step/s, loss=0.087186, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6567/10000 [21:03<10:47,  5.30step/s, loss=0.087186, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6567/10000 [21:03<10:47,  5.30step/s, loss=0.029115, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6568/10000 [21:03<10:47,  5.30step/s, loss=0.029115, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6568/10000 [21:03<10:47,  5.30step/s, loss=0.018818, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6569/10000 [21:03<10:47,  5.30step/s, loss=0.018818, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6569/10000 [21:03<10:47,  5.30step/s, loss=0.026982, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6570/10000 [21:03<10:46,  5.31step/s, loss=0.026982, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6570/10000 [21:03<10:46,  5.31step/s, loss=0.046312, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6571/10000 [21:04<10:47,  5.30step/s, loss=0.046312, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6571/10000 [21:04<10:47,  5.30step/s, loss=0.025872, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6572/10000 [21:04<12:08,  4.70step/s, loss=0.025872, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6572/10000 [21:04<12:08,  4.70step/s, loss=0.030285, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6573/10000 [21:04<11:40,  4.89step/s, loss=0.030285, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6573/10000 [21:04<11:40,  4.89step/s, loss=0.038648, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6574/10000 [21:04<11:24,  5.00step/s, loss=0.038648, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6574/10000 [21:04<11:24,  5.00step/s, loss=0.035915, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6575/10000 [21:04<11:12,  5.09step/s, loss=0.035915, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6575/10000 [21:04<11:12,  5.09step/s, loss=0.029494, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6576/10000 [21:05<11:05,  5.15step/s, loss=0.029494, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6576/10000 [21:05<11:05,  5.15step/s, loss=0.026983, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6577/10000 [21:05<11:00,  5.18step/s, loss=0.026983, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6577/10000 [21:05<11:00,  5.18step/s, loss=0.029157, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6578/10000 [21:05<10:55,  5.22step/s, loss=0.029157, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6578/10000 [21:05<10:55,  5.22step/s, loss=0.112372, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6579/10000 [21:05<10:52,  5.25step/s, loss=0.112372, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6579/10000 [21:05<10:52,  5.25step/s, loss=0.050016, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6580/10000 [21:05<10:50,  5.26step/s, loss=0.050016, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6580/10000 [21:05<10:50,  5.26step/s, loss=0.029511, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6581/10000 [21:06<10:48,  5.27step/s, loss=0.029511, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6581/10000 [21:06<10:48,  5.27step/s, loss=0.032563, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6582/10000 [21:06<10:47,  5.28step/s, loss=0.032563, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6582/10000 [21:06<10:47,  5.28step/s, loss=0.057786, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6583/10000 [21:06<10:45,  5.29step/s, loss=0.057786, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6583/10000 [21:06<10:45,  5.29step/s, loss=0.051464, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6584/10000 [21:06<10:48,  5.26step/s, loss=0.051464, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6584/10000 [21:06<10:48,  5.26step/s, loss=0.070785, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6585/10000 [21:06<10:47,  5.27step/s, loss=0.070785, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6585/10000 [21:06<10:47,  5.27step/s, loss=0.094761, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6586/10000 [21:06<10:47,  5.28step/s, loss=0.094761, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6586/10000 [21:06<10:47,  5.28step/s, loss=0.051892, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6587/10000 [21:07<10:44,  5.29step/s, loss=0.051892, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6587/10000 [21:07<10:44,  5.29step/s, loss=0.027225, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6588/10000 [21:07<10:44,  5.30step/s, loss=0.027225, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6588/10000 [21:07<10:44,  5.30step/s, loss=0.046600, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6589/10000 [21:07<10:43,  5.30step/s, loss=0.046600, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6589/10000 [21:07<10:43,  5.30step/s, loss=0.031925, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6590/10000 [21:07<10:43,  5.30step/s, loss=0.031925, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6590/10000 [21:07<10:43,  5.30step/s, loss=0.047532, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6591/10000 [21:07<10:41,  5.31step/s, loss=0.047532, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6591/10000 [21:07<10:41,  5.31step/s, loss=0.093547, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6592/10000 [21:08<10:41,  5.31step/s, loss=0.093547, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6592/10000 [21:08<10:41,  5.31step/s, loss=0.027679, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6593/10000 [21:08<10:42,  5.30step/s, loss=0.027679, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6593/10000 [21:08<10:42,  5.30step/s, loss=0.040236, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6594/10000 [21:08<10:41,  5.31step/s, loss=0.040236, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6594/10000 [21:08<10:41,  5.31step/s, loss=0.121849, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6595/10000 [21:08<10:43,  5.29step/s, loss=0.121849, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6595/10000 [21:08<10:43,  5.29step/s, loss=0.026623, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6596/10000 [21:08<10:44,  5.28step/s, loss=0.026623, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6596/10000 [21:08<10:44,  5.28step/s, loss=0.062705, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6597/10000 [21:09<10:48,  5.25step/s, loss=0.062705, elapsed=21.1min]

Entraînement:  66%|██████▌   | 6597/10000 [21:09<10:48,  5.25step/s, loss=0.050324, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6598/10000 [21:09<10:46,  5.26step/s, loss=0.050324, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6598/10000 [21:09<10:46,  5.26step/s, loss=0.044035, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6599/10000 [21:09<10:49,  5.24step/s, loss=0.044035, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6599/10000 [21:09<10:49,  5.24step/s, loss=0.042938, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6600/10000 [21:09<10:47,  5.25step/s, loss=0.042938, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6600/10000 [21:09<10:47,  5.25step/s, loss=0.075783, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6600/10000 [21:09<10:47,  5.25step/s, loss=0.075783, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6601/10000 [21:09<10:51,  5.21step/s, loss=0.075783, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6601/10000 [21:09<10:51,  5.21step/s, loss=0.067744, elapsed=21.2min]

Step 6600/10000 | Train loss: 0.075783 | Elapsed: 21.2min | ETA: 10.9min

Entraînement:  66%|██████▌   | 6602/10000 [21:09<10:49,  5.23step/s, loss=0.067744, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6602/10000 [21:09<10:49,  5.23step/s, loss=0.016580, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6603/10000 [21:10<10:48,  5.24step/s, loss=0.016580, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6603/10000 [21:10<10:48,  5.24step/s, loss=0.077597, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6604/10000 [21:10<10:46,  5.25step/s, loss=0.077597, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6604/10000 [21:10<10:46,  5.25step/s, loss=0.067320, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6605/10000 [21:10<10:46,  5.25step/s, loss=0.067320, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6605/10000 [21:10<10:46,  5.25step/s, loss=0.064350, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6606/10000 [21:10<10:44,  5.27step/s, loss=0.064350, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6606/10000 [21:10<10:44,  5.27step/s, loss=0.033556, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6607/10000 [21:10<10:44,  5.27step/s, loss=0.033556, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6607/10000 [21:10<10:44,  5.27step/s, loss=0.016107, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6608/10000 [21:11<10:44,  5.26step/s, loss=0.016107, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6608/10000 [21:11<10:44,  5.26step/s, loss=0.022974, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6609/10000 [21:11<10:44,  5.26step/s, loss=0.022974, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6609/10000 [21:11<10:44,  5.26step/s, loss=0.018762, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6610/10000 [21:11<10:44,  5.26step/s, loss=0.018762, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6610/10000 [21:11<10:44,  5.26step/s, loss=0.030767, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6611/10000 [21:11<10:42,  5.28step/s, loss=0.030767, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6611/10000 [21:11<10:42,  5.28step/s, loss=0.022891, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6612/10000 [21:11<10:42,  5.27step/s, loss=0.022891, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6612/10000 [21:11<10:42,  5.27step/s, loss=0.033559, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6613/10000 [21:12<10:41,  5.28step/s, loss=0.033559, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6613/10000 [21:12<10:41,  5.28step/s, loss=0.063206, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6614/10000 [21:12<10:40,  5.29step/s, loss=0.063206, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6614/10000 [21:12<10:40,  5.29step/s, loss=0.026549, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6615/10000 [21:12<10:41,  5.28step/s, loss=0.026549, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6615/10000 [21:12<10:41,  5.28step/s, loss=0.055487, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6616/10000 [21:12<10:40,  5.28step/s, loss=0.055487, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6616/10000 [21:12<10:40,  5.28step/s, loss=0.085335, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6617/10000 [21:12<10:41,  5.27step/s, loss=0.085335, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6617/10000 [21:12<10:41,  5.27step/s, loss=0.028221, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6618/10000 [21:13<10:40,  5.28step/s, loss=0.028221, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6618/10000 [21:13<10:40,  5.28step/s, loss=0.055850, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6619/10000 [21:13<10:40,  5.28step/s, loss=0.055850, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6619/10000 [21:13<10:40,  5.28step/s, loss=0.029824, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6620/10000 [21:13<10:39,  5.28step/s, loss=0.029824, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6620/10000 [21:13<10:39,  5.28step/s, loss=0.035856, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6621/10000 [21:13<10:38,  5.29step/s, loss=0.035856, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6621/10000 [21:13<10:38,  5.29step/s, loss=0.032704, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6622/10000 [21:13<10:39,  5.28step/s, loss=0.032704, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6622/10000 [21:13<10:39,  5.28step/s, loss=0.040318, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6623/10000 [21:13<10:39,  5.28step/s, loss=0.040318, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6623/10000 [21:13<10:39,  5.28step/s, loss=0.031259, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6624/10000 [21:14<10:40,  5.27step/s, loss=0.031259, elapsed=21.2min]

Entraînement:  66%|██████▌   | 6624/10000 [21:14<10:40,  5.27step/s, loss=0.048452, elapsed=21.2min]

Entraînement:  66%|██████▋   | 6625/10000 [21:14<10:39,  5.28step/s, loss=0.048452, elapsed=21.2min]

Entraînement:  66%|██████▋   | 6625/10000 [21:14<10:39,  5.28step/s, loss=0.031962, elapsed=21.2min]

Entraînement:  66%|██████▋   | 6626/10000 [21:14<10:40,  5.27step/s, loss=0.031962, elapsed=21.2min]

Entraînement:  66%|██████▋   | 6626/10000 [21:14<10:40,  5.27step/s, loss=0.020657, elapsed=21.2min]

Entraînement:  66%|██████▋   | 6627/10000 [21:14<10:39,  5.27step/s, loss=0.020657, elapsed=21.2min]

Entraînement:  66%|██████▋   | 6627/10000 [21:14<10:39,  5.27step/s, loss=0.025797, elapsed=21.2min]

Entraînement:  66%|██████▋   | 6628/10000 [21:14<10:40,  5.27step/s, loss=0.025797, elapsed=21.2min]

Entraînement:  66%|██████▋   | 6628/10000 [21:14<10:40,  5.27step/s, loss=0.076559, elapsed=21.2min]

Entraînement:  66%|██████▋   | 6629/10000 [21:15<10:38,  5.28step/s, loss=0.076559, elapsed=21.2min]

Entraînement:  66%|██████▋   | 6629/10000 [21:15<10:38,  5.28step/s, loss=0.016473, elapsed=21.3min]

Entraînement:  66%|██████▋   | 6630/10000 [21:15<10:38,  5.28step/s, loss=0.016473, elapsed=21.3min]

Entraînement:  66%|██████▋   | 6630/10000 [21:15<10:38,  5.28step/s, loss=0.080348, elapsed=21.3min]

Entraînement:  66%|██████▋   | 6631/10000 [21:15<10:39,  5.27step/s, loss=0.080348, elapsed=21.3min]

Entraînement:  66%|██████▋   | 6631/10000 [21:15<10:39,  5.27step/s, loss=0.135598, elapsed=21.3min]

Entraînement:  66%|██████▋   | 6632/10000 [21:15<10:37,  5.28step/s, loss=0.135598, elapsed=21.3min]

Entraînement:  66%|██████▋   | 6632/10000 [21:15<10:37,  5.28step/s, loss=0.034680, elapsed=21.3min]

Entraînement:  66%|██████▋   | 6633/10000 [21:15<10:37,  5.28step/s, loss=0.034680, elapsed=21.3min]

Entraînement:  66%|██████▋   | 6633/10000 [21:15<10:37,  5.28step/s, loss=0.032016, elapsed=21.3min]

Entraînement:  66%|██████▋   | 6634/10000 [21:16<10:37,  5.28step/s, loss=0.032016, elapsed=21.3min]

Entraînement:  66%|██████▋   | 6634/10000 [21:16<10:37,  5.28step/s, loss=0.072508, elapsed=21.3min]

Entraînement:  66%|██████▋   | 6635/10000 [21:16<10:36,  5.28step/s, loss=0.072508, elapsed=21.3min]

Entraînement:  66%|██████▋   | 6635/10000 [21:16<10:36,  5.28step/s, loss=0.042519, elapsed=21.3min]

Entraînement:  66%|██████▋   | 6636/10000 [21:16<10:36,  5.29step/s, loss=0.042519, elapsed=21.3min]

Entraînement:  66%|██████▋   | 6636/10000 [21:16<10:36,  5.29step/s, loss=0.043972, elapsed=21.3min]

Entraînement:  66%|██████▋   | 6637/10000 [21:16<10:35,  5.29step/s, loss=0.043972, elapsed=21.3min]

Entraînement:  66%|██████▋   | 6637/10000 [21:16<10:35,  5.29step/s, loss=0.057110, elapsed=21.3min]

Entraînement:  66%|██████▋   | 6638/10000 [21:16<10:36,  5.28step/s, loss=0.057110, elapsed=21.3min]

Entraînement:  66%|██████▋   | 6638/10000 [21:16<10:36,  5.28step/s, loss=0.077611, elapsed=21.3min]

Entraînement:  66%|██████▋   | 6639/10000 [21:17<10:37,  5.27step/s, loss=0.077611, elapsed=21.3min]

Entraînement:  66%|██████▋   | 6639/10000 [21:17<10:37,  5.27step/s, loss=0.030474, elapsed=21.3min]

Entraînement:  66%|██████▋   | 6640/10000 [21:17<10:37,  5.27step/s, loss=0.030474, elapsed=21.3min]

Entraînement:  66%|██████▋   | 6640/10000 [21:17<10:37,  5.27step/s, loss=0.032293, elapsed=21.3min]

Entraînement:  66%|██████▋   | 6641/10000 [21:17<10:36,  5.27step/s, loss=0.032293, elapsed=21.3min]

Entraînement:  66%|██████▋   | 6641/10000 [21:17<10:36,  5.27step/s, loss=0.042814, elapsed=21.3min]

Entraînement:  66%|██████▋   | 6642/10000 [21:17<10:35,  5.29step/s, loss=0.042814, elapsed=21.3min]

Entraînement:  66%|██████▋   | 6642/10000 [21:17<10:35,  5.29step/s, loss=0.033732, elapsed=21.3min]

Entraînement:  66%|██████▋   | 6643/10000 [21:17<10:35,  5.28step/s, loss=0.033732, elapsed=21.3min]

Entraînement:  66%|██████▋   | 6643/10000 [21:17<10:35,  5.28step/s, loss=0.023526, elapsed=21.3min]

Entraînement:  66%|██████▋   | 6644/10000 [21:17<10:36,  5.27step/s, loss=0.023526, elapsed=21.3min]

Entraînement:  66%|██████▋   | 6644/10000 [21:17<10:36,  5.27step/s, loss=0.030186, elapsed=21.3min]

Entraînement:  66%|██████▋   | 6645/10000 [21:18<10:36,  5.27step/s, loss=0.030186, elapsed=21.3min]

Entraînement:  66%|██████▋   | 6645/10000 [21:18<10:36,  5.27step/s, loss=0.041901, elapsed=21.3min]

Entraînement:  66%|██████▋   | 6646/10000 [21:18<10:36,  5.27step/s, loss=0.041901, elapsed=21.3min]

Entraînement:  66%|██████▋   | 6646/10000 [21:18<10:36,  5.27step/s, loss=0.021215, elapsed=21.3min]

Entraînement:  66%|██████▋   | 6647/10000 [21:18<10:36,  5.27step/s, loss=0.021215, elapsed=21.3min]

Entraînement:  66%|██████▋   | 6647/10000 [21:18<10:36,  5.27step/s, loss=0.075999, elapsed=21.3min]

Entraînement:  66%|██████▋   | 6648/10000 [21:18<10:36,  5.27step/s, loss=0.075999, elapsed=21.3min]

Entraînement:  66%|██████▋   | 6648/10000 [21:18<10:36,  5.27step/s, loss=0.053202, elapsed=21.3min]

Entraînement:  66%|██████▋   | 6649/10000 [21:18<10:35,  5.27step/s, loss=0.053202, elapsed=21.3min]

Entraînement:  66%|██████▋   | 6649/10000 [21:18<10:35,  5.27step/s, loss=0.054341, elapsed=21.3min]

Entraînement:  66%|██████▋   | 6650/10000 [21:19<10:36,  5.27step/s, loss=0.054341, elapsed=21.3min]

Entraînement:  66%|██████▋   | 6650/10000 [21:19<10:36,  5.27step/s, loss=0.072970, elapsed=21.3min]

Entraînement:  67%|██████▋   | 6651/10000 [21:19<10:35,  5.27step/s, loss=0.072970, elapsed=21.3min]

Entraînement:  67%|██████▋   | 6651/10000 [21:19<10:35,  5.27step/s, loss=0.051418, elapsed=21.3min]

Entraînement:  67%|██████▋   | 6652/10000 [21:19<10:34,  5.28step/s, loss=0.051418, elapsed=21.3min]

Entraînement:  67%|██████▋   | 6652/10000 [21:19<10:34,  5.28step/s, loss=0.023644, elapsed=21.3min]

Entraînement:  67%|██████▋   | 6653/10000 [21:19<10:33,  5.28step/s, loss=0.023644, elapsed=21.3min]

Entraînement:  67%|██████▋   | 6653/10000 [21:19<10:33,  5.28step/s, loss=0.034996, elapsed=21.3min]

Entraînement:  67%|██████▋   | 6654/10000 [21:19<10:35,  5.27step/s, loss=0.034996, elapsed=21.3min]

Entraînement:  67%|██████▋   | 6654/10000 [21:19<10:35,  5.27step/s, loss=0.060745, elapsed=21.3min]

Entraînement:  67%|██████▋   | 6655/10000 [21:20<10:34,  5.27step/s, loss=0.060745, elapsed=21.3min]

Entraînement:  67%|██████▋   | 6655/10000 [21:20<10:34,  5.27step/s, loss=0.043536, elapsed=21.3min]

Entraînement:  67%|██████▋   | 6656/10000 [21:20<10:34,  5.27step/s, loss=0.043536, elapsed=21.3min]

Entraînement:  67%|██████▋   | 6656/10000 [21:20<10:34,  5.27step/s, loss=0.025359, elapsed=21.3min]

Entraînement:  67%|██████▋   | 6657/10000 [21:20<10:33,  5.28step/s, loss=0.025359, elapsed=21.3min]

Entraînement:  67%|██████▋   | 6657/10000 [21:20<10:33,  5.28step/s, loss=0.080759, elapsed=21.3min]

Entraînement:  67%|██████▋   | 6658/10000 [21:20<10:34,  5.27step/s, loss=0.080759, elapsed=21.3min]

Entraînement:  67%|██████▋   | 6658/10000 [21:20<10:34,  5.27step/s, loss=0.043329, elapsed=21.3min]

Entraînement:  67%|██████▋   | 6659/10000 [21:20<10:33,  5.27step/s, loss=0.043329, elapsed=21.3min]

Entraînement:  67%|██████▋   | 6659/10000 [21:20<10:33,  5.27step/s, loss=0.086560, elapsed=21.3min]

Entraînement:  67%|██████▋   | 6660/10000 [21:20<10:30,  5.30step/s, loss=0.086560, elapsed=21.3min]

Entraînement:  67%|██████▋   | 6660/10000 [21:20<10:30,  5.30step/s, loss=0.067564, elapsed=21.3min]

Entraînement:  67%|██████▋   | 6661/10000 [21:21<10:28,  5.31step/s, loss=0.067564, elapsed=21.3min]

Entraînement:  67%|██████▋   | 6661/10000 [21:21<10:28,  5.31step/s, loss=0.027358, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6662/10000 [21:21<10:28,  5.31step/s, loss=0.027358, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6662/10000 [21:21<10:28,  5.31step/s, loss=0.101401, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6663/10000 [21:21<10:26,  5.33step/s, loss=0.101401, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6663/10000 [21:21<10:26,  5.33step/s, loss=0.098870, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6664/10000 [21:21<10:24,  5.34step/s, loss=0.098870, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6664/10000 [21:21<10:24,  5.34step/s, loss=0.050084, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6665/10000 [21:21<10:24,  5.34step/s, loss=0.050084, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6665/10000 [21:21<10:24,  5.34step/s, loss=0.028862, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6666/10000 [21:22<10:24,  5.34step/s, loss=0.028862, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6666/10000 [21:22<10:24,  5.34step/s, loss=0.037444, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6667/10000 [21:22<10:22,  5.35step/s, loss=0.037444, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6667/10000 [21:22<10:22,  5.35step/s, loss=0.036202, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6668/10000 [21:22<10:22,  5.35step/s, loss=0.036202, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6668/10000 [21:22<10:22,  5.35step/s, loss=0.068528, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6669/10000 [21:22<10:25,  5.32step/s, loss=0.068528, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6669/10000 [21:22<10:25,  5.32step/s, loss=0.099396, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6670/10000 [21:22<10:28,  5.30step/s, loss=0.099396, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6670/10000 [21:22<10:28,  5.30step/s, loss=0.045880, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6671/10000 [21:23<10:29,  5.29step/s, loss=0.045880, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6671/10000 [21:23<10:29,  5.29step/s, loss=0.038571, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6672/10000 [21:23<10:30,  5.28step/s, loss=0.038571, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6672/10000 [21:23<10:30,  5.28step/s, loss=0.111426, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6673/10000 [21:23<10:33,  5.25step/s, loss=0.111426, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6673/10000 [21:23<10:33,  5.25step/s, loss=0.019146, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6674/10000 [21:23<10:32,  5.26step/s, loss=0.019146, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6674/10000 [21:23<10:32,  5.26step/s, loss=0.062921, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6675/10000 [21:23<10:30,  5.27step/s, loss=0.062921, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6675/10000 [21:23<10:30,  5.27step/s, loss=0.099085, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6676/10000 [21:23<10:28,  5.29step/s, loss=0.099085, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6676/10000 [21:24<10:28,  5.29step/s, loss=0.039289, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6677/10000 [21:24<10:29,  5.28step/s, loss=0.039289, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6677/10000 [21:24<10:29,  5.28step/s, loss=0.063435, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6678/10000 [21:24<10:29,  5.28step/s, loss=0.063435, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6678/10000 [21:24<10:29,  5.28step/s, loss=0.049454, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6679/10000 [21:24<10:27,  5.29step/s, loss=0.049454, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6679/10000 [21:24<10:27,  5.29step/s, loss=0.035763, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6680/10000 [21:24<10:27,  5.29step/s, loss=0.035763, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6680/10000 [21:24<10:27,  5.29step/s, loss=0.059121, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6681/10000 [21:24<10:26,  5.29step/s, loss=0.059121, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6681/10000 [21:24<10:26,  5.29step/s, loss=0.071758, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6682/10000 [21:25<10:26,  5.29step/s, loss=0.071758, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6682/10000 [21:25<10:26,  5.29step/s, loss=0.030141, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6683/10000 [21:25<10:25,  5.30step/s, loss=0.030141, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6683/10000 [21:25<10:25,  5.30step/s, loss=0.022190, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6684/10000 [21:25<10:25,  5.30step/s, loss=0.022190, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6684/10000 [21:25<10:25,  5.30step/s, loss=0.019274, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6685/10000 [21:25<10:24,  5.30step/s, loss=0.019274, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6685/10000 [21:25<10:24,  5.30step/s, loss=0.028463, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6686/10000 [21:25<10:26,  5.29step/s, loss=0.028463, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6686/10000 [21:25<10:26,  5.29step/s, loss=0.056056, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6687/10000 [21:26<10:25,  5.30step/s, loss=0.056056, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6687/10000 [21:26<10:25,  5.30step/s, loss=0.021776, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6688/10000 [21:26<10:26,  5.29step/s, loss=0.021776, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6688/10000 [21:26<10:26,  5.29step/s, loss=0.048138, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6689/10000 [21:26<10:25,  5.29step/s, loss=0.048138, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6689/10000 [21:26<10:25,  5.29step/s, loss=0.141622, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6690/10000 [21:26<10:25,  5.29step/s, loss=0.141622, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6690/10000 [21:26<10:25,  5.29step/s, loss=0.028609, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6691/10000 [21:26<10:25,  5.29step/s, loss=0.028609, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6691/10000 [21:26<10:25,  5.29step/s, loss=0.051861, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6692/10000 [21:27<10:23,  5.31step/s, loss=0.051861, elapsed=21.4min]

Entraînement:  67%|██████▋   | 6692/10000 [21:27<10:23,  5.31step/s, loss=0.024220, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6693/10000 [21:27<10:23,  5.30step/s, loss=0.024220, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6693/10000 [21:27<10:23,  5.30step/s, loss=0.021658, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6694/10000 [21:27<10:27,  5.27step/s, loss=0.021658, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6694/10000 [21:27<10:27,  5.27step/s, loss=0.052757, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6695/10000 [21:27<10:27,  5.27step/s, loss=0.052757, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6695/10000 [21:27<10:27,  5.27step/s, loss=0.094771, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6696/10000 [21:27<10:26,  5.28step/s, loss=0.094771, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6696/10000 [21:27<10:26,  5.28step/s, loss=0.110045, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6697/10000 [21:27<10:25,  5.28step/s, loss=0.110045, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6697/10000 [21:27<10:25,  5.28step/s, loss=0.022220, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6698/10000 [21:28<10:25,  5.28step/s, loss=0.022220, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6698/10000 [21:28<10:25,  5.28step/s, loss=0.042406, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6699/10000 [21:28<10:25,  5.28step/s, loss=0.042406, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6699/10000 [21:28<10:25,  5.28step/s, loss=0.037560, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6700/10000 [21:28<10:25,  5.28step/s, loss=0.037560, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6700/10000 [21:28<10:25,  5.28step/s, loss=0.060441, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6700/10000 [21:28<10:25,  5.28step/s, loss=0.060441, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6701/10000 [21:28<10:33,  5.21step/s, loss=0.060441, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6701/10000 [21:28<10:33,  5.21step/s, loss=0.030286, elapsed=21.5min]

Step 6700/10000 | Train loss: 0.060441 | Elapsed: 21.5min | ETA: 10.6min

Entraînement:  67%|██████▋   | 6702/10000 [21:28<10:29,  5.24step/s, loss=0.030286, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6702/10000 [21:28<10:29,  5.24step/s, loss=0.067080, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6703/10000 [21:29<10:30,  5.23step/s, loss=0.067080, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6703/10000 [21:29<10:30,  5.23step/s, loss=0.080362, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6704/10000 [21:29<10:28,  5.24step/s, loss=0.080362, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6704/10000 [21:29<10:28,  5.24step/s, loss=0.049269, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6705/10000 [21:29<10:26,  5.26step/s, loss=0.049269, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6705/10000 [21:29<10:26,  5.26step/s, loss=0.050331, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6706/10000 [21:29<10:27,  5.25step/s, loss=0.050331, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6706/10000 [21:29<10:27,  5.25step/s, loss=0.027810, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6707/10000 [21:29<10:25,  5.26step/s, loss=0.027810, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6707/10000 [21:29<10:25,  5.26step/s, loss=0.054179, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6708/10000 [21:30<10:25,  5.26step/s, loss=0.054179, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6708/10000 [21:30<10:25,  5.26step/s, loss=0.027804, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6709/10000 [21:30<10:26,  5.25step/s, loss=0.027804, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6709/10000 [21:30<10:26,  5.25step/s, loss=0.107791, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6710/10000 [21:30<10:26,  5.25step/s, loss=0.107791, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6710/10000 [21:30<10:26,  5.25step/s, loss=0.025972, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6711/10000 [21:30<10:26,  5.25step/s, loss=0.025972, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6711/10000 [21:30<10:26,  5.25step/s, loss=0.030522, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6712/10000 [21:30<10:26,  5.25step/s, loss=0.030522, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6712/10000 [21:30<10:26,  5.25step/s, loss=0.047751, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6713/10000 [21:31<10:25,  5.25step/s, loss=0.047751, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6713/10000 [21:31<10:25,  5.25step/s, loss=0.032599, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6714/10000 [21:31<10:25,  5.26step/s, loss=0.032599, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6714/10000 [21:31<10:25,  5.26step/s, loss=0.038900, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6715/10000 [21:31<10:25,  5.26step/s, loss=0.038900, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6715/10000 [21:31<10:25,  5.26step/s, loss=0.042194, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6716/10000 [21:31<10:26,  5.24step/s, loss=0.042194, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6716/10000 [21:31<10:26,  5.24step/s, loss=0.097433, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6717/10000 [21:31<10:25,  5.25step/s, loss=0.097433, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6717/10000 [21:31<10:25,  5.25step/s, loss=0.042619, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6718/10000 [21:31<10:27,  5.23step/s, loss=0.042619, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6718/10000 [21:31<10:27,  5.23step/s, loss=0.029242, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6719/10000 [21:32<10:27,  5.23step/s, loss=0.029242, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6719/10000 [21:32<10:27,  5.23step/s, loss=0.045941, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6720/10000 [21:32<10:26,  5.23step/s, loss=0.045941, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6720/10000 [21:32<10:26,  5.23step/s, loss=0.053135, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6721/10000 [21:32<10:24,  5.25step/s, loss=0.053135, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6721/10000 [21:32<10:24,  5.25step/s, loss=0.017793, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6722/10000 [21:32<10:26,  5.23step/s, loss=0.017793, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6722/10000 [21:32<10:26,  5.23step/s, loss=0.027397, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6723/10000 [21:32<10:25,  5.24step/s, loss=0.027397, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6723/10000 [21:32<10:25,  5.24step/s, loss=0.011791, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6724/10000 [21:33<10:24,  5.25step/s, loss=0.011791, elapsed=21.5min]

Entraînement:  67%|██████▋   | 6724/10000 [21:33<10:24,  5.25step/s, loss=0.043153, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6725/10000 [21:33<10:23,  5.25step/s, loss=0.043153, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6725/10000 [21:33<10:23,  5.25step/s, loss=0.066582, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6726/10000 [21:33<10:22,  5.26step/s, loss=0.066582, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6726/10000 [21:33<10:22,  5.26step/s, loss=0.023913, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6727/10000 [21:33<10:21,  5.26step/s, loss=0.023913, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6727/10000 [21:33<10:21,  5.26step/s, loss=0.021093, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6728/10000 [21:33<10:20,  5.27step/s, loss=0.021093, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6728/10000 [21:33<10:20,  5.27step/s, loss=0.067097, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6729/10000 [21:34<10:20,  5.27step/s, loss=0.067097, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6729/10000 [21:34<10:20,  5.27step/s, loss=0.021076, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6730/10000 [21:34<10:20,  5.27step/s, loss=0.021076, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6730/10000 [21:34<10:20,  5.27step/s, loss=0.029904, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6731/10000 [21:34<10:19,  5.28step/s, loss=0.029904, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6731/10000 [21:34<10:19,  5.28step/s, loss=0.033023, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6732/10000 [21:34<10:19,  5.28step/s, loss=0.033023, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6732/10000 [21:34<10:19,  5.28step/s, loss=0.037855, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6733/10000 [21:34<10:19,  5.28step/s, loss=0.037855, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6733/10000 [21:34<10:19,  5.28step/s, loss=0.049896, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6734/10000 [21:35<10:18,  5.28step/s, loss=0.049896, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6734/10000 [21:35<10:18,  5.28step/s, loss=0.074266, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6735/10000 [21:35<10:17,  5.28step/s, loss=0.074266, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6735/10000 [21:35<10:17,  5.28step/s, loss=0.027714, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6736/10000 [21:35<10:16,  5.29step/s, loss=0.027714, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6736/10000 [21:35<10:16,  5.29step/s, loss=0.023503, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6737/10000 [21:35<10:16,  5.29step/s, loss=0.023503, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6737/10000 [21:35<10:16,  5.29step/s, loss=0.017691, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6738/10000 [21:35<10:16,  5.29step/s, loss=0.017691, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6738/10000 [21:35<10:16,  5.29step/s, loss=0.016935, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6739/10000 [21:35<10:16,  5.29step/s, loss=0.016935, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6739/10000 [21:35<10:16,  5.29step/s, loss=0.101968, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6740/10000 [21:36<10:16,  5.29step/s, loss=0.101968, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6740/10000 [21:36<10:16,  5.29step/s, loss=0.056954, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6741/10000 [21:36<10:15,  5.30step/s, loss=0.056954, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6741/10000 [21:36<10:15,  5.30step/s, loss=0.033139, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6742/10000 [21:36<10:15,  5.30step/s, loss=0.033139, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6742/10000 [21:36<10:15,  5.30step/s, loss=0.039340, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6743/10000 [21:36<10:14,  5.30step/s, loss=0.039340, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6743/10000 [21:36<10:14,  5.30step/s, loss=0.019923, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6744/10000 [21:36<10:14,  5.30step/s, loss=0.019923, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6744/10000 [21:36<10:14,  5.30step/s, loss=0.080835, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6745/10000 [21:37<10:14,  5.29step/s, loss=0.080835, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6745/10000 [21:37<10:14,  5.29step/s, loss=0.021191, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6746/10000 [21:37<10:14,  5.30step/s, loss=0.021191, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6746/10000 [21:37<10:14,  5.30step/s, loss=0.041058, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6747/10000 [21:37<10:15,  5.28step/s, loss=0.041058, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6747/10000 [21:37<10:15,  5.28step/s, loss=0.032447, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6748/10000 [21:37<10:16,  5.27step/s, loss=0.032447, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6748/10000 [21:37<10:16,  5.27step/s, loss=0.026442, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6749/10000 [21:37<10:15,  5.28step/s, loss=0.026442, elapsed=21.6min]

Entraînement:  67%|██████▋   | 6749/10000 [21:37<10:15,  5.28step/s, loss=0.050093, elapsed=21.6min]

Entraînement:  68%|██████▊   | 6750/10000 [21:38<10:16,  5.27step/s, loss=0.050093, elapsed=21.6min]

Entraînement:  68%|██████▊   | 6750/10000 [21:38<10:16,  5.27step/s, loss=0.058372, elapsed=21.6min]

Entraînement:  68%|██████▊   | 6751/10000 [21:38<10:15,  5.28step/s, loss=0.058372, elapsed=21.6min]

Entraînement:  68%|██████▊   | 6751/10000 [21:38<10:15,  5.28step/s, loss=0.101389, elapsed=21.6min]

Entraînement:  68%|██████▊   | 6752/10000 [21:38<10:14,  5.28step/s, loss=0.101389, elapsed=21.6min]

Entraînement:  68%|██████▊   | 6752/10000 [21:38<10:14,  5.28step/s, loss=0.080622, elapsed=21.6min]

Entraînement:  68%|██████▊   | 6753/10000 [21:38<10:14,  5.28step/s, loss=0.080622, elapsed=21.6min]

Entraînement:  68%|██████▊   | 6753/10000 [21:38<10:14,  5.28step/s, loss=0.031850, elapsed=21.6min]

Entraînement:  68%|██████▊   | 6754/10000 [21:38<10:14,  5.29step/s, loss=0.031850, elapsed=21.6min]

Entraînement:  68%|██████▊   | 6754/10000 [21:38<10:14,  5.29step/s, loss=0.031267, elapsed=21.6min]

Entraînement:  68%|██████▊   | 6755/10000 [21:38<10:15,  5.27step/s, loss=0.031267, elapsed=21.6min]

Entraînement:  68%|██████▊   | 6755/10000 [21:38<10:15,  5.27step/s, loss=0.070411, elapsed=21.6min]

Entraînement:  68%|██████▊   | 6756/10000 [21:39<10:15,  5.27step/s, loss=0.070411, elapsed=21.6min]

Entraînement:  68%|██████▊   | 6756/10000 [21:39<10:15,  5.27step/s, loss=0.031368, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6757/10000 [21:39<10:15,  5.27step/s, loss=0.031368, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6757/10000 [21:39<10:15,  5.27step/s, loss=0.022367, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6758/10000 [21:39<10:14,  5.28step/s, loss=0.022367, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6758/10000 [21:39<10:14,  5.28step/s, loss=0.027464, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6759/10000 [21:39<10:13,  5.28step/s, loss=0.027464, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6759/10000 [21:39<10:13,  5.28step/s, loss=0.122806, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6760/10000 [21:39<10:13,  5.28step/s, loss=0.122806, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6760/10000 [21:39<10:13,  5.28step/s, loss=0.024972, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6761/10000 [21:40<10:12,  5.29step/s, loss=0.024972, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6761/10000 [21:40<10:12,  5.29step/s, loss=0.057319, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6762/10000 [21:40<10:12,  5.29step/s, loss=0.057319, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6762/10000 [21:40<10:12,  5.29step/s, loss=0.087994, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6763/10000 [21:40<10:12,  5.28step/s, loss=0.087994, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6763/10000 [21:40<10:12,  5.28step/s, loss=0.017362, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6764/10000 [21:40<10:13,  5.28step/s, loss=0.017362, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6764/10000 [21:40<10:13,  5.28step/s, loss=0.033664, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6765/10000 [21:40<10:11,  5.29step/s, loss=0.033664, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6765/10000 [21:40<10:11,  5.29step/s, loss=0.030755, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6766/10000 [21:41<10:10,  5.30step/s, loss=0.030755, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6766/10000 [21:41<10:10,  5.30step/s, loss=0.057602, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6767/10000 [21:41<10:10,  5.30step/s, loss=0.057602, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6767/10000 [21:41<10:10,  5.30step/s, loss=0.052986, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6768/10000 [21:41<10:09,  5.30step/s, loss=0.052986, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6768/10000 [21:41<10:09,  5.30step/s, loss=0.033666, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6769/10000 [21:41<10:08,  5.31step/s, loss=0.033666, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6769/10000 [21:41<10:08,  5.31step/s, loss=0.128019, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6770/10000 [21:41<10:09,  5.30step/s, loss=0.128019, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6770/10000 [21:41<10:09,  5.30step/s, loss=0.020392, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6771/10000 [21:42<10:10,  5.29step/s, loss=0.020392, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6771/10000 [21:42<10:10,  5.29step/s, loss=0.016677, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6772/10000 [21:42<10:10,  5.28step/s, loss=0.016677, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6772/10000 [21:42<10:10,  5.28step/s, loss=0.023474, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6773/10000 [21:42<10:10,  5.29step/s, loss=0.023474, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6773/10000 [21:42<10:10,  5.29step/s, loss=0.050905, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6774/10000 [21:42<10:08,  5.30step/s, loss=0.050905, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6774/10000 [21:42<10:08,  5.30step/s, loss=0.020747, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6775/10000 [21:42<10:11,  5.27step/s, loss=0.020747, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6775/10000 [21:42<10:11,  5.27step/s, loss=0.032663, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6776/10000 [21:42<10:10,  5.28step/s, loss=0.032663, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6776/10000 [21:42<10:10,  5.28step/s, loss=0.024381, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6777/10000 [21:43<10:10,  5.28step/s, loss=0.024381, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6777/10000 [21:43<10:10,  5.28step/s, loss=0.028769, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6778/10000 [21:43<10:09,  5.29step/s, loss=0.028769, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6778/10000 [21:43<10:09,  5.29step/s, loss=0.036690, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6779/10000 [21:43<10:08,  5.29step/s, loss=0.036690, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6779/10000 [21:43<10:08,  5.29step/s, loss=0.031292, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6780/10000 [21:43<10:09,  5.29step/s, loss=0.031292, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6780/10000 [21:43<10:09,  5.29step/s, loss=0.024293, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6781/10000 [21:43<10:11,  5.26step/s, loss=0.024293, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6781/10000 [21:43<10:11,  5.26step/s, loss=0.064937, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6782/10000 [21:44<10:10,  5.27step/s, loss=0.064937, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6782/10000 [21:44<10:10,  5.27step/s, loss=0.088643, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6783/10000 [21:44<10:09,  5.28step/s, loss=0.088643, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6783/10000 [21:44<10:09,  5.28step/s, loss=0.026900, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6784/10000 [21:44<10:09,  5.28step/s, loss=0.026900, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6784/10000 [21:44<10:09,  5.28step/s, loss=0.020985, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6785/10000 [21:44<10:09,  5.28step/s, loss=0.020985, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6785/10000 [21:44<10:09,  5.28step/s, loss=0.051640, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6786/10000 [21:44<10:11,  5.26step/s, loss=0.051640, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6786/10000 [21:44<10:11,  5.26step/s, loss=0.052778, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6787/10000 [21:45<10:11,  5.26step/s, loss=0.052778, elapsed=21.7min]

Entraînement:  68%|██████▊   | 6787/10000 [21:45<10:11,  5.26step/s, loss=0.055752, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6788/10000 [21:45<10:11,  5.25step/s, loss=0.055752, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6788/10000 [21:45<10:11,  5.25step/s, loss=0.047531, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6789/10000 [21:45<10:13,  5.24step/s, loss=0.047531, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6789/10000 [21:45<10:13,  5.24step/s, loss=0.030159, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6790/10000 [21:45<10:11,  5.25step/s, loss=0.030159, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6790/10000 [21:45<10:11,  5.25step/s, loss=0.045858, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6791/10000 [21:45<10:10,  5.26step/s, loss=0.045858, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6791/10000 [21:45<10:10,  5.26step/s, loss=0.022235, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6792/10000 [21:45<10:09,  5.27step/s, loss=0.022235, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6792/10000 [21:45<10:09,  5.27step/s, loss=0.033214, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6793/10000 [21:46<10:09,  5.27step/s, loss=0.033214, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6793/10000 [21:46<10:09,  5.27step/s, loss=0.053884, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6794/10000 [21:46<10:09,  5.26step/s, loss=0.053884, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6794/10000 [21:46<10:09,  5.26step/s, loss=0.075345, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6795/10000 [21:46<10:10,  5.25step/s, loss=0.075345, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6795/10000 [21:46<10:10,  5.25step/s, loss=0.034377, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6796/10000 [21:46<10:09,  5.26step/s, loss=0.034377, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6796/10000 [21:46<10:09,  5.26step/s, loss=0.018904, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6797/10000 [21:46<10:09,  5.25step/s, loss=0.018904, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6797/10000 [21:46<10:09,  5.25step/s, loss=0.028562, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6798/10000 [21:47<10:08,  5.26step/s, loss=0.028562, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6798/10000 [21:47<10:08,  5.26step/s, loss=0.065547, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6799/10000 [21:47<10:09,  5.25step/s, loss=0.065547, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6799/10000 [21:47<10:09,  5.25step/s, loss=0.094614, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6800/10000 [21:47<10:08,  5.26step/s, loss=0.094614, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6800/10000 [21:47<10:08,  5.26step/s, loss=0.069951, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6800/10000 [21:47<10:08,  5.26step/s, loss=0.069951, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6801/10000 [21:47<10:15,  5.20step/s, loss=0.069951, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6801/10000 [21:47<10:15,  5.20step/s, loss=0.044644, elapsed=21.8min]

Step 6800/10000 | Train loss: 0.069951 | Elapsed: 21.8min | ETA: 10.3min

Entraînement:  68%|██████▊   | 6802/10000 [21:47<10:13,  5.21step/s, loss=0.044644, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6802/10000 [21:47<10:13,  5.21step/s, loss=0.099051, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6803/10000 [21:48<10:13,  5.21step/s, loss=0.099051, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6803/10000 [21:48<10:13,  5.21step/s, loss=0.032145, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6804/10000 [21:48<10:11,  5.23step/s, loss=0.032145, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6804/10000 [21:48<10:11,  5.23step/s, loss=0.078202, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6805/10000 [21:48<10:09,  5.24step/s, loss=0.078202, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6805/10000 [21:48<10:09,  5.24step/s, loss=0.049025, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6806/10000 [21:48<10:08,  5.25step/s, loss=0.049025, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6806/10000 [21:48<10:08,  5.25step/s, loss=0.023955, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6807/10000 [21:48<10:07,  5.25step/s, loss=0.023955, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6807/10000 [21:48<10:07,  5.25step/s, loss=0.011911, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6808/10000 [21:49<10:07,  5.26step/s, loss=0.011911, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6808/10000 [21:49<10:07,  5.26step/s, loss=0.034408, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6809/10000 [21:49<10:08,  5.24step/s, loss=0.034408, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6809/10000 [21:49<10:08,  5.24step/s, loss=0.032971, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6810/10000 [21:49<10:07,  5.25step/s, loss=0.032971, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6810/10000 [21:49<10:07,  5.25step/s, loss=0.111171, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6811/10000 [21:49<10:07,  5.25step/s, loss=0.111171, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6811/10000 [21:49<10:07,  5.25step/s, loss=0.056783, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6812/10000 [21:49<10:06,  5.25step/s, loss=0.056783, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6812/10000 [21:49<10:06,  5.25step/s, loss=0.025747, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6813/10000 [21:49<10:05,  5.26step/s, loss=0.025747, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6813/10000 [21:50<10:05,  5.26step/s, loss=0.027670, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6814/10000 [21:50<10:05,  5.26step/s, loss=0.027670, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6814/10000 [21:50<10:05,  5.26step/s, loss=0.024266, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6815/10000 [21:50<10:05,  5.26step/s, loss=0.024266, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6815/10000 [21:50<10:05,  5.26step/s, loss=0.106539, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6816/10000 [21:50<10:05,  5.26step/s, loss=0.106539, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6816/10000 [21:50<10:05,  5.26step/s, loss=0.043329, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6817/10000 [21:50<10:07,  5.24step/s, loss=0.043329, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6817/10000 [21:50<10:07,  5.24step/s, loss=0.032723, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6818/10000 [21:50<10:05,  5.25step/s, loss=0.032723, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6818/10000 [21:50<10:05,  5.25step/s, loss=0.018542, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6819/10000 [21:51<10:05,  5.25step/s, loss=0.018542, elapsed=21.8min]

Entraînement:  68%|██████▊   | 6819/10000 [21:51<10:05,  5.25step/s, loss=0.018782, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6820/10000 [21:51<10:05,  5.25step/s, loss=0.018782, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6820/10000 [21:51<10:05,  5.25step/s, loss=0.029390, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6821/10000 [21:51<10:04,  5.26step/s, loss=0.029390, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6821/10000 [21:51<10:04,  5.26step/s, loss=0.031063, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6822/10000 [21:51<10:04,  5.26step/s, loss=0.031063, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6822/10000 [21:51<10:04,  5.26step/s, loss=0.080099, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6823/10000 [21:51<10:04,  5.26step/s, loss=0.080099, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6823/10000 [21:51<10:04,  5.26step/s, loss=0.028053, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6824/10000 [21:52<10:03,  5.26step/s, loss=0.028053, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6824/10000 [21:52<10:03,  5.26step/s, loss=0.063465, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6825/10000 [21:52<10:04,  5.25step/s, loss=0.063465, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6825/10000 [21:52<10:04,  5.25step/s, loss=0.045619, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6826/10000 [21:52<10:04,  5.25step/s, loss=0.045619, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6826/10000 [21:52<10:04,  5.25step/s, loss=0.085052, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6827/10000 [21:52<10:03,  5.25step/s, loss=0.085052, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6827/10000 [21:52<10:03,  5.25step/s, loss=0.111100, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6828/10000 [21:52<10:03,  5.26step/s, loss=0.111100, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6828/10000 [21:52<10:03,  5.26step/s, loss=0.036619, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6829/10000 [21:53<10:02,  5.26step/s, loss=0.036619, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6829/10000 [21:53<10:02,  5.26step/s, loss=0.027048, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6830/10000 [21:53<10:01,  5.27step/s, loss=0.027048, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6830/10000 [21:53<10:01,  5.27step/s, loss=0.041366, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6831/10000 [21:53<10:00,  5.28step/s, loss=0.041366, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6831/10000 [21:53<10:00,  5.28step/s, loss=0.031326, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6832/10000 [21:53<10:01,  5.27step/s, loss=0.031326, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6832/10000 [21:53<10:01,  5.27step/s, loss=0.037666, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6833/10000 [21:53<10:01,  5.26step/s, loss=0.037666, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6833/10000 [21:53<10:01,  5.26step/s, loss=0.064433, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6834/10000 [21:53<10:02,  5.26step/s, loss=0.064433, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6834/10000 [21:53<10:02,  5.26step/s, loss=0.049840, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6835/10000 [21:54<10:03,  5.25step/s, loss=0.049840, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6835/10000 [21:54<10:03,  5.25step/s, loss=0.058662, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6836/10000 [21:54<10:03,  5.24step/s, loss=0.058662, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6836/10000 [21:54<10:03,  5.24step/s, loss=0.089722, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6837/10000 [21:54<10:03,  5.24step/s, loss=0.089722, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6837/10000 [21:54<10:03,  5.24step/s, loss=0.024659, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6838/10000 [21:54<10:03,  5.24step/s, loss=0.024659, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6838/10000 [21:54<10:03,  5.24step/s, loss=0.029211, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6839/10000 [21:54<10:02,  5.24step/s, loss=0.029211, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6839/10000 [21:54<10:02,  5.24step/s, loss=0.039871, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6840/10000 [21:55<10:01,  5.25step/s, loss=0.039871, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6840/10000 [21:55<10:01,  5.25step/s, loss=0.095317, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6841/10000 [21:55<10:01,  5.25step/s, loss=0.095317, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6841/10000 [21:55<10:01,  5.25step/s, loss=0.102389, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6842/10000 [21:55<10:01,  5.25step/s, loss=0.102389, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6842/10000 [21:55<10:01,  5.25step/s, loss=0.022360, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6843/10000 [21:55<10:00,  5.25step/s, loss=0.022360, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6843/10000 [21:55<10:00,  5.25step/s, loss=0.030884, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6844/10000 [21:55<10:01,  5.25step/s, loss=0.030884, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6844/10000 [21:55<10:01,  5.25step/s, loss=0.038018, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6845/10000 [21:56<10:00,  5.25step/s, loss=0.038018, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6845/10000 [21:56<10:00,  5.25step/s, loss=0.041998, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6846/10000 [21:56<10:00,  5.26step/s, loss=0.041998, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6846/10000 [21:56<10:00,  5.26step/s, loss=0.094837, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6847/10000 [21:56<09:58,  5.27step/s, loss=0.094837, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6847/10000 [21:56<09:58,  5.27step/s, loss=0.019729, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6848/10000 [21:56<09:58,  5.27step/s, loss=0.019729, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6848/10000 [21:56<09:58,  5.27step/s, loss=0.044641, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6849/10000 [21:56<09:57,  5.27step/s, loss=0.044641, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6849/10000 [21:56<09:57,  5.27step/s, loss=0.083764, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6850/10000 [21:57<09:57,  5.27step/s, loss=0.083764, elapsed=21.9min]

Entraînement:  68%|██████▊   | 6850/10000 [21:57<09:57,  5.27step/s, loss=0.034845, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6851/10000 [21:57<09:58,  5.26step/s, loss=0.034845, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6851/10000 [21:57<09:58,  5.26step/s, loss=0.019015, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6852/10000 [21:57<09:58,  5.26step/s, loss=0.019015, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6852/10000 [21:57<09:58,  5.26step/s, loss=0.035770, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6853/10000 [21:57<09:57,  5.27step/s, loss=0.035770, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6853/10000 [21:57<09:57,  5.27step/s, loss=0.125932, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6854/10000 [21:57<09:57,  5.27step/s, loss=0.125932, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6854/10000 [21:57<09:57,  5.27step/s, loss=0.035843, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6855/10000 [21:57<09:56,  5.27step/s, loss=0.035843, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6855/10000 [21:57<09:56,  5.27step/s, loss=0.038477, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6856/10000 [21:58<09:55,  5.28step/s, loss=0.038477, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6856/10000 [21:58<09:55,  5.28step/s, loss=0.037999, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6857/10000 [21:58<09:55,  5.28step/s, loss=0.037999, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6857/10000 [21:58<09:55,  5.28step/s, loss=0.029468, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6858/10000 [21:58<09:55,  5.28step/s, loss=0.029468, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6858/10000 [21:58<09:55,  5.28step/s, loss=0.055345, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6859/10000 [21:58<09:56,  5.26step/s, loss=0.055345, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6859/10000 [21:58<09:56,  5.26step/s, loss=0.029429, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6860/10000 [21:58<09:56,  5.26step/s, loss=0.029429, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6860/10000 [21:58<09:56,  5.26step/s, loss=0.039432, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6861/10000 [21:59<09:55,  5.27step/s, loss=0.039432, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6861/10000 [21:59<09:55,  5.27step/s, loss=0.084504, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6862/10000 [21:59<09:55,  5.27step/s, loss=0.084504, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6862/10000 [21:59<09:55,  5.27step/s, loss=0.057450, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6863/10000 [21:59<09:54,  5.28step/s, loss=0.057450, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6863/10000 [21:59<09:54,  5.28step/s, loss=0.074479, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6864/10000 [21:59<09:53,  5.28step/s, loss=0.074479, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6864/10000 [21:59<09:53,  5.28step/s, loss=0.032178, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6865/10000 [21:59<09:54,  5.27step/s, loss=0.032178, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6865/10000 [21:59<09:54,  5.27step/s, loss=0.061458, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6866/10000 [22:00<09:53,  5.28step/s, loss=0.061458, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6866/10000 [22:00<09:53,  5.28step/s, loss=0.031478, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6867/10000 [22:00<09:53,  5.28step/s, loss=0.031478, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6867/10000 [22:00<09:53,  5.28step/s, loss=0.027829, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6868/10000 [22:00<09:54,  5.27step/s, loss=0.027829, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6868/10000 [22:00<09:54,  5.27step/s, loss=0.020211, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6869/10000 [22:00<09:54,  5.27step/s, loss=0.020211, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6869/10000 [22:00<09:54,  5.27step/s, loss=0.043524, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6870/10000 [22:00<09:54,  5.27step/s, loss=0.043524, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6870/10000 [22:00<09:54,  5.27step/s, loss=0.057405, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6871/10000 [22:01<09:53,  5.28step/s, loss=0.057405, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6871/10000 [22:01<09:53,  5.28step/s, loss=0.027378, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6872/10000 [22:01<09:53,  5.27step/s, loss=0.027378, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6872/10000 [22:01<09:53,  5.27step/s, loss=0.031323, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6873/10000 [22:01<09:52,  5.28step/s, loss=0.031323, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6873/10000 [22:01<09:52,  5.28step/s, loss=0.132735, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6874/10000 [22:01<09:53,  5.27step/s, loss=0.132735, elapsed=22.0min]

Entraînement:  69%|██████▊   | 6874/10000 [22:01<09:53,  5.27step/s, loss=0.054259, elapsed=22.0min]

Entraînement:  69%|██████▉   | 6875/10000 [22:01<09:52,  5.27step/s, loss=0.054259, elapsed=22.0min]

Entraînement:  69%|██████▉   | 6875/10000 [22:01<09:52,  5.27step/s, loss=0.033023, elapsed=22.0min]

Entraînement:  69%|██████▉   | 6876/10000 [22:01<09:52,  5.27step/s, loss=0.033023, elapsed=22.0min]

Entraînement:  69%|██████▉   | 6876/10000 [22:01<09:52,  5.27step/s, loss=0.058646, elapsed=22.0min]

Entraînement:  69%|██████▉   | 6877/10000 [22:02<09:53,  5.26step/s, loss=0.058646, elapsed=22.0min]

Entraînement:  69%|██████▉   | 6877/10000 [22:02<09:53,  5.26step/s, loss=0.044602, elapsed=22.0min]

Entraînement:  69%|██████▉   | 6878/10000 [22:02<09:53,  5.26step/s, loss=0.044602, elapsed=22.0min]

Entraînement:  69%|██████▉   | 6878/10000 [22:02<09:53,  5.26step/s, loss=0.029616, elapsed=22.0min]

Entraînement:  69%|██████▉   | 6879/10000 [22:02<09:51,  5.27step/s, loss=0.029616, elapsed=22.0min]

Entraînement:  69%|██████▉   | 6879/10000 [22:02<09:51,  5.27step/s, loss=0.022927, elapsed=22.0min]

Entraînement:  69%|██████▉   | 6880/10000 [22:02<09:50,  5.28step/s, loss=0.022927, elapsed=22.0min]

Entraînement:  69%|██████▉   | 6880/10000 [22:02<09:50,  5.28step/s, loss=0.043911, elapsed=22.0min]

Entraînement:  69%|██████▉   | 6881/10000 [22:02<09:50,  5.28step/s, loss=0.043911, elapsed=22.0min]

Entraînement:  69%|██████▉   | 6881/10000 [22:02<09:50,  5.28step/s, loss=0.023844, elapsed=22.0min]

Entraînement:  69%|██████▉   | 6882/10000 [22:03<09:49,  5.29step/s, loss=0.023844, elapsed=22.0min]

Entraînement:  69%|██████▉   | 6882/10000 [22:03<09:49,  5.29step/s, loss=0.027570, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6883/10000 [22:03<09:48,  5.30step/s, loss=0.027570, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6883/10000 [22:03<09:48,  5.30step/s, loss=0.024692, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6884/10000 [22:03<09:48,  5.29step/s, loss=0.024692, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6884/10000 [22:03<09:48,  5.29step/s, loss=0.065509, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6885/10000 [22:03<09:48,  5.29step/s, loss=0.065509, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6885/10000 [22:03<09:48,  5.29step/s, loss=0.034262, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6886/10000 [22:03<09:49,  5.29step/s, loss=0.034262, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6886/10000 [22:03<09:49,  5.29step/s, loss=0.045867, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6887/10000 [22:04<09:49,  5.28step/s, loss=0.045867, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6887/10000 [22:04<09:49,  5.28step/s, loss=0.068216, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6888/10000 [22:04<09:48,  5.29step/s, loss=0.068216, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6888/10000 [22:04<09:48,  5.29step/s, loss=0.096721, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6889/10000 [22:04<09:47,  5.29step/s, loss=0.096721, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6889/10000 [22:04<09:47,  5.29step/s, loss=0.032832, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6890/10000 [22:04<09:46,  5.30step/s, loss=0.032832, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6890/10000 [22:04<09:46,  5.30step/s, loss=0.017299, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6891/10000 [22:04<09:47,  5.29step/s, loss=0.017299, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6891/10000 [22:04<09:47,  5.29step/s, loss=0.038465, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6892/10000 [22:04<09:47,  5.29step/s, loss=0.038465, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6892/10000 [22:04<09:47,  5.29step/s, loss=0.051607, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6893/10000 [22:05<09:46,  5.29step/s, loss=0.051607, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6893/10000 [22:05<09:46,  5.29step/s, loss=0.067397, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6894/10000 [22:05<09:47,  5.28step/s, loss=0.067397, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6894/10000 [22:05<09:47,  5.28step/s, loss=0.054458, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6895/10000 [22:05<09:46,  5.29step/s, loss=0.054458, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6895/10000 [22:05<09:46,  5.29step/s, loss=0.088511, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6896/10000 [22:05<09:46,  5.29step/s, loss=0.088511, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6896/10000 [22:05<09:46,  5.29step/s, loss=0.027233, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6897/10000 [22:05<09:45,  5.30step/s, loss=0.027233, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6897/10000 [22:05<09:45,  5.30step/s, loss=0.038590, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6898/10000 [22:06<09:44,  5.31step/s, loss=0.038590, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6898/10000 [22:06<09:44,  5.31step/s, loss=0.082877, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6899/10000 [22:06<09:46,  5.29step/s, loss=0.082877, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6899/10000 [22:06<09:46,  5.29step/s, loss=0.037990, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6900/10000 [22:06<09:44,  5.30step/s, loss=0.037990, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6900/10000 [22:06<09:44,  5.30step/s, loss=0.067578, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6900/10000 [22:06<09:44,  5.30step/s, loss=0.067578, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6901/10000 [22:06<09:50,  5.24step/s, loss=0.067578, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6901/10000 [22:06<09:50,  5.24step/s, loss=0.129231, elapsed=22.1min]

Step 6900/10000 | Train loss: 0.067578 | Elapsed: 22.1min | ETA: 9.9min

Entraînement:  69%|██████▉   | 6902/10000 [22:06<09:48,  5.26step/s, loss=0.129231, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6902/10000 [22:06<09:48,  5.26step/s, loss=0.134589, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6903/10000 [22:07<09:47,  5.28step/s, loss=0.134589, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6903/10000 [22:07<09:47,  5.28step/s, loss=0.043067, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6904/10000 [22:07<09:45,  5.28step/s, loss=0.043067, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6904/10000 [22:07<09:45,  5.28step/s, loss=0.039317, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6905/10000 [22:07<09:45,  5.29step/s, loss=0.039317, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6905/10000 [22:07<09:45,  5.29step/s, loss=0.056345, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6906/10000 [22:07<09:45,  5.28step/s, loss=0.056345, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6906/10000 [22:07<09:45,  5.28step/s, loss=0.115442, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6907/10000 [22:07<09:45,  5.28step/s, loss=0.115442, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6907/10000 [22:07<09:45,  5.28step/s, loss=0.041285, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6908/10000 [22:08<09:45,  5.28step/s, loss=0.041285, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6908/10000 [22:08<09:45,  5.28step/s, loss=0.071622, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6909/10000 [22:08<09:45,  5.28step/s, loss=0.071622, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6909/10000 [22:08<09:45,  5.28step/s, loss=0.123138, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6910/10000 [22:08<09:44,  5.29step/s, loss=0.123138, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6910/10000 [22:08<09:44,  5.29step/s, loss=0.059768, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6911/10000 [22:08<09:43,  5.29step/s, loss=0.059768, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6911/10000 [22:08<09:43,  5.29step/s, loss=0.040602, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6912/10000 [22:08<09:43,  5.29step/s, loss=0.040602, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6912/10000 [22:08<09:43,  5.29step/s, loss=0.096117, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6913/10000 [22:08<09:43,  5.29step/s, loss=0.096117, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6913/10000 [22:08<09:43,  5.29step/s, loss=0.058498, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6914/10000 [22:09<09:43,  5.29step/s, loss=0.058498, elapsed=22.1min]

Entraînement:  69%|██████▉   | 6914/10000 [22:09<09:43,  5.29step/s, loss=0.142988, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6915/10000 [22:09<09:43,  5.29step/s, loss=0.142988, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6915/10000 [22:09<09:43,  5.29step/s, loss=0.029048, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6916/10000 [22:09<09:43,  5.28step/s, loss=0.029048, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6916/10000 [22:09<09:43,  5.28step/s, loss=0.034426, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6917/10000 [22:09<09:42,  5.29step/s, loss=0.034426, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6917/10000 [22:09<09:42,  5.29step/s, loss=0.030821, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6918/10000 [22:09<09:42,  5.29step/s, loss=0.030821, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6918/10000 [22:09<09:42,  5.29step/s, loss=0.017115, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6919/10000 [22:10<09:44,  5.27step/s, loss=0.017115, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6919/10000 [22:10<09:44,  5.27step/s, loss=0.038515, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6920/10000 [22:10<09:42,  5.28step/s, loss=0.038515, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6920/10000 [22:10<09:42,  5.28step/s, loss=0.031214, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6921/10000 [22:10<09:39,  5.31step/s, loss=0.031214, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6921/10000 [22:10<09:39,  5.31step/s, loss=0.044685, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6922/10000 [22:10<09:40,  5.30step/s, loss=0.044685, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6922/10000 [22:10<09:40,  5.30step/s, loss=0.043721, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6923/10000 [22:10<09:41,  5.30step/s, loss=0.043721, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6923/10000 [22:10<09:41,  5.30step/s, loss=0.045197, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6924/10000 [22:11<09:40,  5.30step/s, loss=0.045197, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6924/10000 [22:11<09:40,  5.30step/s, loss=0.094188, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6925/10000 [22:11<09:39,  5.30step/s, loss=0.094188, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6925/10000 [22:11<09:39,  5.30step/s, loss=0.022678, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6926/10000 [22:11<09:40,  5.30step/s, loss=0.022678, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6926/10000 [22:11<09:40,  5.30step/s, loss=0.041643, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6927/10000 [22:11<09:40,  5.29step/s, loss=0.041643, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6927/10000 [22:11<09:40,  5.29step/s, loss=0.026921, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6928/10000 [22:11<09:40,  5.29step/s, loss=0.026921, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6928/10000 [22:11<09:40,  5.29step/s, loss=0.024400, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6929/10000 [22:11<09:40,  5.29step/s, loss=0.024400, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6929/10000 [22:11<09:40,  5.29step/s, loss=0.044193, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6930/10000 [22:12<09:39,  5.30step/s, loss=0.044193, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6930/10000 [22:12<09:39,  5.30step/s, loss=0.055673, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6931/10000 [22:12<09:40,  5.28step/s, loss=0.055673, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6931/10000 [22:12<09:40,  5.28step/s, loss=0.022466, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6932/10000 [22:12<09:40,  5.29step/s, loss=0.022466, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6932/10000 [22:12<09:40,  5.29step/s, loss=0.096050, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6933/10000 [22:12<09:40,  5.28step/s, loss=0.096050, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6933/10000 [22:12<09:40,  5.28step/s, loss=0.026984, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6934/10000 [22:12<09:41,  5.27step/s, loss=0.026984, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6934/10000 [22:12<09:41,  5.27step/s, loss=0.055008, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6935/10000 [22:13<09:41,  5.27step/s, loss=0.055008, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6935/10000 [22:13<09:41,  5.27step/s, loss=0.032614, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6936/10000 [22:13<09:41,  5.27step/s, loss=0.032614, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6936/10000 [22:13<09:41,  5.27step/s, loss=0.064528, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6937/10000 [22:13<09:41,  5.27step/s, loss=0.064528, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6937/10000 [22:13<09:41,  5.27step/s, loss=0.105305, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6938/10000 [22:13<09:41,  5.27step/s, loss=0.105305, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6938/10000 [22:13<09:41,  5.27step/s, loss=0.031911, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6939/10000 [22:13<09:42,  5.26step/s, loss=0.031911, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6939/10000 [22:13<09:42,  5.26step/s, loss=0.048662, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6940/10000 [22:14<09:42,  5.25step/s, loss=0.048662, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6940/10000 [22:14<09:42,  5.25step/s, loss=0.047738, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6941/10000 [22:14<09:42,  5.25step/s, loss=0.047738, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6941/10000 [22:14<09:42,  5.25step/s, loss=0.031191, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6942/10000 [22:14<09:42,  5.25step/s, loss=0.031191, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6942/10000 [22:14<09:42,  5.25step/s, loss=0.067982, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6943/10000 [22:14<09:42,  5.25step/s, loss=0.067982, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6943/10000 [22:14<09:42,  5.25step/s, loss=0.086929, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6944/10000 [22:14<09:42,  5.25step/s, loss=0.086929, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6944/10000 [22:14<09:42,  5.25step/s, loss=0.032155, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6945/10000 [22:15<09:50,  5.18step/s, loss=0.032155, elapsed=22.2min]

Entraînement:  69%|██████▉   | 6945/10000 [22:15<09:50,  5.18step/s, loss=0.030512, elapsed=22.3min]

Entraînement:  69%|██████▉   | 6946/10000 [22:15<09:47,  5.19step/s, loss=0.030512, elapsed=22.3min]

Entraînement:  69%|██████▉   | 6946/10000 [22:15<09:47,  5.19step/s, loss=0.020378, elapsed=22.3min]

Entraînement:  69%|██████▉   | 6947/10000 [22:15<09:46,  5.20step/s, loss=0.020378, elapsed=22.3min]

Entraînement:  69%|██████▉   | 6947/10000 [22:15<09:46,  5.20step/s, loss=0.046767, elapsed=22.3min]

Entraînement:  69%|██████▉   | 6948/10000 [22:15<09:45,  5.22step/s, loss=0.046767, elapsed=22.3min]

Entraînement:  69%|██████▉   | 6948/10000 [22:15<09:45,  5.22step/s, loss=0.010828, elapsed=22.3min]

Entraînement:  69%|██████▉   | 6949/10000 [22:15<09:44,  5.22step/s, loss=0.010828, elapsed=22.3min]

Entraînement:  69%|██████▉   | 6949/10000 [22:15<09:44,  5.22step/s, loss=0.030380, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6950/10000 [22:15<09:43,  5.23step/s, loss=0.030380, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6950/10000 [22:15<09:43,  5.23step/s, loss=0.024805, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6951/10000 [22:16<09:42,  5.24step/s, loss=0.024805, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6951/10000 [22:16<09:42,  5.24step/s, loss=0.145052, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6952/10000 [22:16<09:41,  5.24step/s, loss=0.145052, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6952/10000 [22:16<09:41,  5.24step/s, loss=0.062424, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6953/10000 [22:16<09:41,  5.24step/s, loss=0.062424, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6953/10000 [22:16<09:41,  5.24step/s, loss=0.039007, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6954/10000 [22:16<09:42,  5.23step/s, loss=0.039007, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6954/10000 [22:16<09:42,  5.23step/s, loss=0.038832, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6955/10000 [22:16<09:41,  5.24step/s, loss=0.038832, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6955/10000 [22:16<09:41,  5.24step/s, loss=0.026404, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6956/10000 [22:17<09:41,  5.24step/s, loss=0.026404, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6956/10000 [22:17<09:41,  5.24step/s, loss=0.022306, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6957/10000 [22:17<09:41,  5.24step/s, loss=0.022306, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6957/10000 [22:17<09:41,  5.24step/s, loss=0.029727, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6958/10000 [22:17<09:40,  5.24step/s, loss=0.029727, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6958/10000 [22:17<09:40,  5.24step/s, loss=0.031902, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6959/10000 [22:17<09:39,  5.25step/s, loss=0.031902, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6959/10000 [22:17<09:39,  5.25step/s, loss=0.029171, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6960/10000 [22:17<09:40,  5.24step/s, loss=0.029171, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6960/10000 [22:17<09:40,  5.24step/s, loss=0.059729, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6961/10000 [22:18<09:39,  5.25step/s, loss=0.059729, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6961/10000 [22:18<09:39,  5.25step/s, loss=0.031078, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6962/10000 [22:18<09:37,  5.26step/s, loss=0.031078, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6962/10000 [22:18<09:37,  5.26step/s, loss=0.021855, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6963/10000 [22:18<09:36,  5.26step/s, loss=0.021855, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6963/10000 [22:18<09:36,  5.26step/s, loss=0.032434, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6964/10000 [22:18<09:37,  5.26step/s, loss=0.032434, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6964/10000 [22:18<09:37,  5.26step/s, loss=0.046831, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6965/10000 [22:18<09:36,  5.26step/s, loss=0.046831, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6965/10000 [22:18<09:36,  5.26step/s, loss=0.044874, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6966/10000 [22:19<09:35,  5.27step/s, loss=0.044874, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6966/10000 [22:19<09:35,  5.27step/s, loss=0.054771, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6967/10000 [22:19<09:35,  5.27step/s, loss=0.054771, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6967/10000 [22:19<09:35,  5.27step/s, loss=0.053745, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6968/10000 [22:19<09:35,  5.27step/s, loss=0.053745, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6968/10000 [22:19<09:35,  5.27step/s, loss=0.055140, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6969/10000 [22:19<09:34,  5.28step/s, loss=0.055140, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6969/10000 [22:19<09:34,  5.28step/s, loss=0.035899, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6970/10000 [22:19<09:34,  5.28step/s, loss=0.035899, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6970/10000 [22:19<09:34,  5.28step/s, loss=0.056806, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6971/10000 [22:19<09:32,  5.29step/s, loss=0.056806, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6971/10000 [22:19<09:32,  5.29step/s, loss=0.064483, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6972/10000 [22:20<09:32,  5.28step/s, loss=0.064483, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6972/10000 [22:20<09:32,  5.28step/s, loss=0.030819, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6973/10000 [22:20<09:32,  5.29step/s, loss=0.030819, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6973/10000 [22:20<09:32,  5.29step/s, loss=0.025349, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6974/10000 [22:20<09:32,  5.29step/s, loss=0.025349, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6974/10000 [22:20<09:32,  5.29step/s, loss=0.031348, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6975/10000 [22:20<09:32,  5.28step/s, loss=0.031348, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6975/10000 [22:20<09:32,  5.28step/s, loss=0.040647, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6976/10000 [22:20<09:32,  5.28step/s, loss=0.040647, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6976/10000 [22:20<09:32,  5.28step/s, loss=0.040295, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6977/10000 [22:21<09:32,  5.28step/s, loss=0.040295, elapsed=22.3min]

Entraînement:  70%|██████▉   | 6977/10000 [22:21<09:32,  5.28step/s, loss=0.030898, elapsed=22.4min]

Entraînement:  70%|██████▉   | 6978/10000 [22:21<09:32,  5.28step/s, loss=0.030898, elapsed=22.4min]

Entraînement:  70%|██████▉   | 6978/10000 [22:21<09:32,  5.28step/s, loss=0.028624, elapsed=22.4min]

Entraînement:  70%|██████▉   | 6979/10000 [22:21<09:31,  5.29step/s, loss=0.028624, elapsed=22.4min]

Entraînement:  70%|██████▉   | 6979/10000 [22:21<09:31,  5.29step/s, loss=0.043513, elapsed=22.4min]

Entraînement:  70%|██████▉   | 6980/10000 [22:21<09:31,  5.28step/s, loss=0.043513, elapsed=22.4min]

Entraînement:  70%|██████▉   | 6980/10000 [22:21<09:31,  5.28step/s, loss=0.031861, elapsed=22.4min]

Entraînement:  70%|██████▉   | 6981/10000 [22:21<09:30,  5.29step/s, loss=0.031861, elapsed=22.4min]

Entraînement:  70%|██████▉   | 6981/10000 [22:21<09:30,  5.29step/s, loss=0.035306, elapsed=22.4min]

Entraînement:  70%|██████▉   | 6982/10000 [22:22<09:30,  5.29step/s, loss=0.035306, elapsed=22.4min]

Entraînement:  70%|██████▉   | 6982/10000 [22:22<09:30,  5.29step/s, loss=0.018438, elapsed=22.4min]

Entraînement:  70%|██████▉   | 6983/10000 [22:22<09:30,  5.29step/s, loss=0.018438, elapsed=22.4min]

Entraînement:  70%|██████▉   | 6983/10000 [22:22<09:30,  5.29step/s, loss=0.075987, elapsed=22.4min]

Entraînement:  70%|██████▉   | 6984/10000 [22:22<09:30,  5.29step/s, loss=0.075987, elapsed=22.4min]

Entraînement:  70%|██████▉   | 6984/10000 [22:22<09:30,  5.29step/s, loss=0.038183, elapsed=22.4min]

Entraînement:  70%|██████▉   | 6985/10000 [22:22<09:31,  5.28step/s, loss=0.038183, elapsed=22.4min]

Entraînement:  70%|██████▉   | 6985/10000 [22:22<09:31,  5.28step/s, loss=0.058723, elapsed=22.4min]

Entraînement:  70%|██████▉   | 6986/10000 [22:22<09:30,  5.28step/s, loss=0.058723, elapsed=22.4min]

Entraînement:  70%|██████▉   | 6986/10000 [22:22<09:30,  5.28step/s, loss=0.070500, elapsed=22.4min]

Entraînement:  70%|██████▉   | 6987/10000 [22:23<09:30,  5.28step/s, loss=0.070500, elapsed=22.4min]

Entraînement:  70%|██████▉   | 6987/10000 [22:23<09:30,  5.28step/s, loss=0.042742, elapsed=22.4min]

Entraînement:  70%|██████▉   | 6988/10000 [22:23<09:31,  5.27step/s, loss=0.042742, elapsed=22.4min]

Entraînement:  70%|██████▉   | 6988/10000 [22:23<09:31,  5.27step/s, loss=0.035679, elapsed=22.4min]

Entraînement:  70%|██████▉   | 6989/10000 [22:23<09:31,  5.27step/s, loss=0.035679, elapsed=22.4min]

Entraînement:  70%|██████▉   | 6989/10000 [22:23<09:31,  5.27step/s, loss=0.114672, elapsed=22.4min]

Entraînement:  70%|██████▉   | 6990/10000 [22:23<09:30,  5.27step/s, loss=0.114672, elapsed=22.4min]

Entraînement:  70%|██████▉   | 6990/10000 [22:23<09:30,  5.27step/s, loss=0.035850, elapsed=22.4min]

Entraînement:  70%|██████▉   | 6991/10000 [22:23<09:30,  5.27step/s, loss=0.035850, elapsed=22.4min]

Entraînement:  70%|██████▉   | 6991/10000 [22:23<09:30,  5.27step/s, loss=0.063008, elapsed=22.4min]

Entraînement:  70%|██████▉   | 6992/10000 [22:23<09:31,  5.26step/s, loss=0.063008, elapsed=22.4min]

Entraînement:  70%|██████▉   | 6992/10000 [22:23<09:31,  5.26step/s, loss=0.037352, elapsed=22.4min]

Entraînement:  70%|██████▉   | 6993/10000 [22:24<09:30,  5.27step/s, loss=0.037352, elapsed=22.4min]

Entraînement:  70%|██████▉   | 6993/10000 [22:24<09:30,  5.27step/s, loss=0.048323, elapsed=22.4min]

Entraînement:  70%|██████▉   | 6994/10000 [22:24<09:30,  5.27step/s, loss=0.048323, elapsed=22.4min]

Entraînement:  70%|██████▉   | 6994/10000 [22:24<09:30,  5.27step/s, loss=0.058699, elapsed=22.4min]

Entraînement:  70%|██████▉   | 6995/10000 [22:24<09:30,  5.27step/s, loss=0.058699, elapsed=22.4min]

Entraînement:  70%|██████▉   | 6995/10000 [22:24<09:30,  5.27step/s, loss=0.043989, elapsed=22.4min]

Entraînement:  70%|██████▉   | 6996/10000 [22:24<09:30,  5.27step/s, loss=0.043989, elapsed=22.4min]

Entraînement:  70%|██████▉   | 6996/10000 [22:24<09:30,  5.27step/s, loss=0.048036, elapsed=22.4min]

Entraînement:  70%|██████▉   | 6997/10000 [22:24<09:30,  5.27step/s, loss=0.048036, elapsed=22.4min]

Entraînement:  70%|██████▉   | 6997/10000 [22:24<09:30,  5.27step/s, loss=0.033766, elapsed=22.4min]

Entraînement:  70%|██████▉   | 6998/10000 [22:25<09:29,  5.28step/s, loss=0.033766, elapsed=22.4min]

Entraînement:  70%|██████▉   | 6998/10000 [22:25<09:29,  5.28step/s, loss=0.025961, elapsed=22.4min]

Entraînement:  70%|██████▉   | 6999/10000 [22:25<09:29,  5.27step/s, loss=0.025961, elapsed=22.4min]

Entraînement:  70%|██████▉   | 6999/10000 [22:25<09:29,  5.27step/s, loss=0.044462, elapsed=22.4min]

Entraînement:  70%|███████   | 7000/10000 [22:25<09:28,  5.27step/s, loss=0.044462, elapsed=22.4min]

Entraînement:  70%|███████   | 7000/10000 [22:25<09:28,  5.27step/s, loss=0.024004, elapsed=22.4min]

Entraînement:  70%|███████   | 7000/10000 [22:25<09:28,  5.27step/s, loss=0.024004, elapsed=22.4min]

Step 7000/10000 | Train loss: 0.024004 | Elapsed: 22.4min | ETA: 9.6min

Entraînement:  70%|███████   | 7000/10000 [22:27<09:28,  5.27step/s, loss=0.024004, elapsed=22.4min]

Entraînement:  70%|███████   | 7000/10000 [22:27<09:28,  5.27step/s, loss=0.024004, elapsed=22.4min]

Step 7000/10000 | Val loss: 0.042011 | Validation en 1.7s
Dernier checkpoint sauvegardé : /workspace/DiffWave_Project/checkpoints/diffwave_doda_male/last_checkpoint.pt

Entraînement:  70%|███████   | 7001/10000 [22:27<38:04,  1.31step/s, loss=0.024004, elapsed=22.4min]

Entraînement:  70%|███████   | 7001/10000 [22:27<38:04,  1.31step/s, loss=0.034403, elapsed=22.5min]

Entraînement:  70%|███████   | 7002/10000 [22:27<29:30,  1.69step/s, loss=0.034403, elapsed=22.5min]

Entraînement:  70%|███████   | 7002/10000 [22:27<29:30,  1.69step/s, loss=0.033890, elapsed=22.5min]

Entraînement:  70%|███████   | 7003/10000 [22:27<23:28,  2.13step/s, loss=0.033890, elapsed=22.5min]

Entraînement:  70%|███████   | 7003/10000 [22:27<23:28,  2.13step/s, loss=0.095778, elapsed=22.5min]

Entraînement:  70%|███████   | 7004/10000 [22:28<19:17,  2.59step/s, loss=0.095778, elapsed=22.5min]

Entraînement:  70%|███████   | 7004/10000 [22:28<19:17,  2.59step/s, loss=0.021621, elapsed=22.5min]

Entraînement:  70%|███████   | 7005/10000 [22:28<16:20,  3.05step/s, loss=0.021621, elapsed=22.5min]

Entraînement:  70%|███████   | 7005/10000 [22:28<16:20,  3.05step/s, loss=0.031323, elapsed=22.5min]

Entraînement:  70%|███████   | 7006/10000 [22:28<14:16,  3.49step/s, loss=0.031323, elapsed=22.5min]

Entraînement:  70%|███████   | 7006/10000 [22:28<14:16,  3.49step/s, loss=0.083287, elapsed=22.5min]

Entraînement:  70%|███████   | 7007/10000 [22:28<12:51,  3.88step/s, loss=0.083287, elapsed=22.5min]

Entraînement:  70%|███████   | 7007/10000 [22:28<12:51,  3.88step/s, loss=0.040912, elapsed=22.5min]

Entraînement:  70%|███████   | 7008/10000 [22:28<11:48,  4.22step/s, loss=0.040912, elapsed=22.5min]

Entraînement:  70%|███████   | 7008/10000 [22:28<11:48,  4.22step/s, loss=0.036064, elapsed=22.5min]

Entraînement:  70%|███████   | 7009/10000 [22:29<11:06,  4.49step/s, loss=0.036064, elapsed=22.5min]

Entraînement:  70%|███████   | 7009/10000 [22:29<11:06,  4.49step/s, loss=0.035450, elapsed=22.5min]

Entraînement:  70%|███████   | 7010/10000 [22:29<10:35,  4.71step/s, loss=0.035450, elapsed=22.5min]

Entraînement:  70%|███████   | 7010/10000 [22:29<10:35,  4.71step/s, loss=0.077846, elapsed=22.5min]

Entraînement:  70%|███████   | 7011/10000 [22:29<10:13,  4.88step/s, loss=0.077846, elapsed=22.5min]

Entraînement:  70%|███████   | 7011/10000 [22:29<10:13,  4.88step/s, loss=0.021626, elapsed=22.5min]

Entraînement:  70%|███████   | 7012/10000 [22:29<09:59,  4.99step/s, loss=0.021626, elapsed=22.5min]

Entraînement:  70%|███████   | 7012/10000 [22:29<09:59,  4.99step/s, loss=0.030752, elapsed=22.5min]

Entraînement:  70%|███████   | 7013/10000 [22:29<09:50,  5.06step/s, loss=0.030752, elapsed=22.5min]

Entraînement:  70%|███████   | 7013/10000 [22:29<09:50,  5.06step/s, loss=0.046781, elapsed=22.5min]

Entraînement:  70%|███████   | 7014/10000 [22:30<09:44,  5.11step/s, loss=0.046781, elapsed=22.5min]

Entraînement:  70%|███████   | 7014/10000 [22:30<09:44,  5.11step/s, loss=0.038091, elapsed=22.5min]

Entraînement:  70%|███████   | 7015/10000 [22:30<09:38,  5.16step/s, loss=0.038091, elapsed=22.5min]

Entraînement:  70%|███████   | 7015/10000 [22:30<09:38,  5.16step/s, loss=0.034893, elapsed=22.5min]

Entraînement:  70%|███████   | 7016/10000 [22:30<09:34,  5.20step/s, loss=0.034893, elapsed=22.5min]

Entraînement:  70%|███████   | 7016/10000 [22:30<09:34,  5.20step/s, loss=0.058108, elapsed=22.5min]

Entraînement:  70%|███████   | 7017/10000 [22:30<09:31,  5.22step/s, loss=0.058108, elapsed=22.5min]

Entraînement:  70%|███████   | 7017/10000 [22:30<09:31,  5.22step/s, loss=0.069729, elapsed=22.5min]

Entraînement:  70%|███████   | 7018/10000 [22:30<09:28,  5.24step/s, loss=0.069729, elapsed=22.5min]

Entraînement:  70%|███████   | 7018/10000 [22:30<09:28,  5.24step/s, loss=0.035276, elapsed=22.5min]

Entraînement:  70%|███████   | 7019/10000 [22:30<09:27,  5.25step/s, loss=0.035276, elapsed=22.5min]

Entraînement:  70%|███████   | 7019/10000 [22:30<09:27,  5.25step/s, loss=0.052190, elapsed=22.5min]

Entraînement:  70%|███████   | 7020/10000 [22:31<09:27,  5.26step/s, loss=0.052190, elapsed=22.5min]

Entraînement:  70%|███████   | 7020/10000 [22:31<09:27,  5.26step/s, loss=0.067134, elapsed=22.5min]

Entraînement:  70%|███████   | 7021/10000 [22:31<09:26,  5.26step/s, loss=0.067134, elapsed=22.5min]

Entraînement:  70%|███████   | 7021/10000 [22:31<09:26,  5.26step/s, loss=0.068520, elapsed=22.5min]

Entraînement:  70%|███████   | 7022/10000 [22:31<09:25,  5.27step/s, loss=0.068520, elapsed=22.5min]

Entraînement:  70%|███████   | 7022/10000 [22:31<09:25,  5.27step/s, loss=0.035785, elapsed=22.5min]

Entraînement:  70%|███████   | 7023/10000 [22:31<09:25,  5.26step/s, loss=0.035785, elapsed=22.5min]

Entraînement:  70%|███████   | 7023/10000 [22:31<09:25,  5.26step/s, loss=0.055795, elapsed=22.5min]

Entraînement:  70%|███████   | 7024/10000 [22:31<09:25,  5.26step/s, loss=0.055795, elapsed=22.5min]

Entraînement:  70%|███████   | 7024/10000 [22:31<09:25,  5.26step/s, loss=0.056147, elapsed=22.5min]

Entraînement:  70%|███████   | 7025/10000 [22:32<09:25,  5.26step/s, loss=0.056147, elapsed=22.5min]

Entraînement:  70%|███████   | 7025/10000 [22:32<09:25,  5.26step/s, loss=0.066809, elapsed=22.5min]

Entraînement:  70%|███████   | 7026/10000 [22:32<09:25,  5.26step/s, loss=0.066809, elapsed=22.5min]

Entraînement:  70%|███████   | 7026/10000 [22:32<09:25,  5.26step/s, loss=0.073597, elapsed=22.5min]

Entraînement:  70%|███████   | 7027/10000 [22:32<09:25,  5.26step/s, loss=0.073597, elapsed=22.5min]

Entraînement:  70%|███████   | 7027/10000 [22:32<09:25,  5.26step/s, loss=0.056741, elapsed=22.5min]

Entraînement:  70%|███████   | 7028/10000 [22:32<09:26,  5.25step/s, loss=0.056741, elapsed=22.5min]

Entraînement:  70%|███████   | 7028/10000 [22:32<09:26,  5.25step/s, loss=0.042417, elapsed=22.5min]

Entraînement:  70%|███████   | 7029/10000 [22:32<09:26,  5.24step/s, loss=0.042417, elapsed=22.5min]

Entraînement:  70%|███████   | 7029/10000 [22:32<09:26,  5.24step/s, loss=0.052625, elapsed=22.5min]

Entraînement:  70%|███████   | 7030/10000 [22:33<09:25,  5.25step/s, loss=0.052625, elapsed=22.5min]

Entraînement:  70%|███████   | 7030/10000 [22:33<09:25,  5.25step/s, loss=0.058868, elapsed=22.6min]

Entraînement:  70%|███████   | 7031/10000 [22:33<09:23,  5.27step/s, loss=0.058868, elapsed=22.6min]

Entraînement:  70%|███████   | 7031/10000 [22:33<09:23,  5.27step/s, loss=0.026497, elapsed=22.6min]

Entraînement:  70%|███████   | 7032/10000 [22:33<09:23,  5.27step/s, loss=0.026497, elapsed=22.6min]

Entraînement:  70%|███████   | 7032/10000 [22:33<09:23,  5.27step/s, loss=0.061091, elapsed=22.6min]

Entraînement:  70%|███████   | 7033/10000 [22:33<09:21,  5.28step/s, loss=0.061091, elapsed=22.6min]

Entraînement:  70%|███████   | 7033/10000 [22:33<09:21,  5.28step/s, loss=0.044928, elapsed=22.6min]

Entraînement:  70%|███████   | 7034/10000 [22:33<09:22,  5.27step/s, loss=0.044928, elapsed=22.6min]

Entraînement:  70%|███████   | 7034/10000 [22:33<09:22,  5.27step/s, loss=0.047057, elapsed=22.6min]

Entraînement:  70%|███████   | 7035/10000 [22:34<09:23,  5.27step/s, loss=0.047057, elapsed=22.6min]

Entraînement:  70%|███████   | 7035/10000 [22:34<09:23,  5.27step/s, loss=0.072397, elapsed=22.6min]

Entraînement:  70%|███████   | 7036/10000 [22:34<09:22,  5.27step/s, loss=0.072397, elapsed=22.6min]

Entraînement:  70%|███████   | 7036/10000 [22:34<09:22,  5.27step/s, loss=0.035323, elapsed=22.6min]

Entraînement:  70%|███████   | 7037/10000 [22:34<09:22,  5.27step/s, loss=0.035323, elapsed=22.6min]

Entraînement:  70%|███████   | 7037/10000 [22:34<09:22,  5.27step/s, loss=0.041989, elapsed=22.6min]

Entraînement:  70%|███████   | 7038/10000 [22:34<09:23,  5.25step/s, loss=0.041989, elapsed=22.6min]

Entraînement:  70%|███████   | 7038/10000 [22:34<09:23,  5.25step/s, loss=0.048567, elapsed=22.6min]

Entraînement:  70%|███████   | 7039/10000 [22:34<09:23,  5.26step/s, loss=0.048567, elapsed=22.6min]

Entraînement:  70%|███████   | 7039/10000 [22:34<09:23,  5.26step/s, loss=0.031942, elapsed=22.6min]

Entraînement:  70%|███████   | 7040/10000 [22:34<09:21,  5.27step/s, loss=0.031942, elapsed=22.6min]

Entraînement:  70%|███████   | 7040/10000 [22:34<09:21,  5.27step/s, loss=0.040781, elapsed=22.6min]

Entraînement:  70%|███████   | 7041/10000 [22:35<09:20,  5.28step/s, loss=0.040781, elapsed=22.6min]

Entraînement:  70%|███████   | 7041/10000 [22:35<09:20,  5.28step/s, loss=0.124224, elapsed=22.6min]

Entraînement:  70%|███████   | 7042/10000 [22:35<09:20,  5.28step/s, loss=0.124224, elapsed=22.6min]

Entraînement:  70%|███████   | 7042/10000 [22:35<09:20,  5.28step/s, loss=0.042731, elapsed=22.6min]

Entraînement:  70%|███████   | 7043/10000 [22:35<09:19,  5.28step/s, loss=0.042731, elapsed=22.6min]

Entraînement:  70%|███████   | 7043/10000 [22:35<09:19,  5.28step/s, loss=0.066309, elapsed=22.6min]

Entraînement:  70%|███████   | 7044/10000 [22:35<09:19,  5.28step/s, loss=0.066309, elapsed=22.6min]

Entraînement:  70%|███████   | 7044/10000 [22:35<09:19,  5.28step/s, loss=0.026554, elapsed=22.6min]

Entraînement:  70%|███████   | 7045/10000 [22:35<09:18,  5.29step/s, loss=0.026554, elapsed=22.6min]

Entraînement:  70%|███████   | 7045/10000 [22:35<09:18,  5.29step/s, loss=0.024037, elapsed=22.6min]

Entraînement:  70%|███████   | 7046/10000 [22:36<09:18,  5.29step/s, loss=0.024037, elapsed=22.6min]

Entraînement:  70%|███████   | 7046/10000 [22:36<09:18,  5.29step/s, loss=0.029243, elapsed=22.6min]

Entraînement:  70%|███████   | 7047/10000 [22:36<09:19,  5.27step/s, loss=0.029243, elapsed=22.6min]

Entraînement:  70%|███████   | 7047/10000 [22:36<09:19,  5.27step/s, loss=0.022557, elapsed=22.6min]

Entraînement:  70%|███████   | 7048/10000 [22:36<09:19,  5.28step/s, loss=0.022557, elapsed=22.6min]

Entraînement:  70%|███████   | 7048/10000 [22:36<09:19,  5.28step/s, loss=0.061009, elapsed=22.6min]

Entraînement:  70%|███████   | 7049/10000 [22:36<09:18,  5.28step/s, loss=0.061009, elapsed=22.6min]

Entraînement:  70%|███████   | 7049/10000 [22:36<09:18,  5.28step/s, loss=0.154392, elapsed=22.6min]

Entraînement:  70%|███████   | 7050/10000 [22:36<09:19,  5.28step/s, loss=0.154392, elapsed=22.6min]

Entraînement:  70%|███████   | 7050/10000 [22:36<09:19,  5.28step/s, loss=0.031670, elapsed=22.6min]

Entraînement:  71%|███████   | 7051/10000 [22:37<09:20,  5.26step/s, loss=0.031670, elapsed=22.6min]

Entraînement:  71%|███████   | 7051/10000 [22:37<09:20,  5.26step/s, loss=0.017739, elapsed=22.6min]

Entraînement:  71%|███████   | 7052/10000 [22:37<09:20,  5.26step/s, loss=0.017739, elapsed=22.6min]

Entraînement:  71%|███████   | 7052/10000 [22:37<09:20,  5.26step/s, loss=0.036821, elapsed=22.6min]

Entraînement:  71%|███████   | 7053/10000 [22:37<09:19,  5.26step/s, loss=0.036821, elapsed=22.6min]

Entraînement:  71%|███████   | 7053/10000 [22:37<09:19,  5.26step/s, loss=0.023123, elapsed=22.6min]

Entraînement:  71%|███████   | 7054/10000 [22:37<09:18,  5.27step/s, loss=0.023123, elapsed=22.6min]

Entraînement:  71%|███████   | 7054/10000 [22:37<09:18,  5.27step/s, loss=0.043145, elapsed=22.6min]

Entraînement:  71%|███████   | 7055/10000 [22:37<09:18,  5.27step/s, loss=0.043145, elapsed=22.6min]

Entraînement:  71%|███████   | 7055/10000 [22:37<09:18,  5.27step/s, loss=0.040271, elapsed=22.6min]

Entraînement:  71%|███████   | 7056/10000 [22:38<09:17,  5.28step/s, loss=0.040271, elapsed=22.6min]

Entraînement:  71%|███████   | 7056/10000 [22:38<09:17,  5.28step/s, loss=0.045644, elapsed=22.6min]

Entraînement:  71%|███████   | 7057/10000 [22:38<09:16,  5.29step/s, loss=0.045644, elapsed=22.6min]

Entraînement:  71%|███████   | 7057/10000 [22:38<09:16,  5.29step/s, loss=0.025787, elapsed=22.6min]

Entraînement:  71%|███████   | 7058/10000 [22:38<09:17,  5.28step/s, loss=0.025787, elapsed=22.6min]

Entraînement:  71%|███████   | 7058/10000 [22:38<09:17,  5.28step/s, loss=0.044828, elapsed=22.6min]

Entraînement:  71%|███████   | 7059/10000 [22:38<09:17,  5.27step/s, loss=0.044828, elapsed=22.6min]

Entraînement:  71%|███████   | 7059/10000 [22:38<09:17,  5.27step/s, loss=0.064935, elapsed=22.6min]

Entraînement:  71%|███████   | 7060/10000 [22:38<09:19,  5.25step/s, loss=0.064935, elapsed=22.6min]

Entraînement:  71%|███████   | 7060/10000 [22:38<09:19,  5.25step/s, loss=0.048379, elapsed=22.6min]

Entraînement:  71%|███████   | 7061/10000 [22:38<09:18,  5.26step/s, loss=0.048379, elapsed=22.6min]

Entraînement:  71%|███████   | 7061/10000 [22:38<09:18,  5.26step/s, loss=0.036582, elapsed=22.6min]

Entraînement:  71%|███████   | 7062/10000 [22:39<09:19,  5.25step/s, loss=0.036582, elapsed=22.6min]

Entraînement:  71%|███████   | 7062/10000 [22:39<09:19,  5.25step/s, loss=0.061073, elapsed=22.7min]

Entraînement:  71%|███████   | 7063/10000 [22:39<09:18,  5.25step/s, loss=0.061073, elapsed=22.7min]

Entraînement:  71%|███████   | 7063/10000 [22:39<09:18,  5.25step/s, loss=0.157492, elapsed=22.7min]

Entraînement:  71%|███████   | 7064/10000 [22:39<09:18,  5.26step/s, loss=0.157492, elapsed=22.7min]

Entraînement:  71%|███████   | 7064/10000 [22:39<09:18,  5.26step/s, loss=0.021771, elapsed=22.7min]

Entraînement:  71%|███████   | 7065/10000 [22:39<09:18,  5.26step/s, loss=0.021771, elapsed=22.7min]

Entraînement:  71%|███████   | 7065/10000 [22:39<09:18,  5.26step/s, loss=0.043017, elapsed=22.7min]

Entraînement:  71%|███████   | 7066/10000 [22:39<09:18,  5.25step/s, loss=0.043017, elapsed=22.7min]

Entraînement:  71%|███████   | 7066/10000 [22:39<09:18,  5.25step/s, loss=0.075894, elapsed=22.7min]

Entraînement:  71%|███████   | 7067/10000 [22:40<09:18,  5.25step/s, loss=0.075894, elapsed=22.7min]

Entraînement:  71%|███████   | 7067/10000 [22:40<09:18,  5.25step/s, loss=0.087000, elapsed=22.7min]

Entraînement:  71%|███████   | 7068/10000 [22:40<09:17,  5.26step/s, loss=0.087000, elapsed=22.7min]

Entraînement:  71%|███████   | 7068/10000 [22:40<09:17,  5.26step/s, loss=0.110338, elapsed=22.7min]

Entraînement:  71%|███████   | 7069/10000 [22:40<09:17,  5.25step/s, loss=0.110338, elapsed=22.7min]

Entraînement:  71%|███████   | 7069/10000 [22:40<09:17,  5.25step/s, loss=0.077412, elapsed=22.7min]

Entraînement:  71%|███████   | 7070/10000 [22:40<09:16,  5.26step/s, loss=0.077412, elapsed=22.7min]

Entraînement:  71%|███████   | 7070/10000 [22:40<09:16,  5.26step/s, loss=0.058816, elapsed=22.7min]

Entraînement:  71%|███████   | 7071/10000 [22:40<09:16,  5.26step/s, loss=0.058816, elapsed=22.7min]

Entraînement:  71%|███████   | 7071/10000 [22:40<09:16,  5.26step/s, loss=0.064739, elapsed=22.7min]

Entraînement:  71%|███████   | 7072/10000 [22:41<09:16,  5.27step/s, loss=0.064739, elapsed=22.7min]

Entraînement:  71%|███████   | 7072/10000 [22:41<09:16,  5.27step/s, loss=0.048368, elapsed=22.7min]

Entraînement:  71%|███████   | 7073/10000 [22:41<09:17,  5.25step/s, loss=0.048368, elapsed=22.7min]

Entraînement:  71%|███████   | 7073/10000 [22:41<09:17,  5.25step/s, loss=0.018476, elapsed=22.7min]

Entraînement:  71%|███████   | 7074/10000 [22:41<09:17,  5.25step/s, loss=0.018476, elapsed=22.7min]

Entraînement:  71%|███████   | 7074/10000 [22:41<09:17,  5.25step/s, loss=0.068181, elapsed=22.7min]

Entraînement:  71%|███████   | 7075/10000 [22:41<09:17,  5.25step/s, loss=0.068181, elapsed=22.7min]

Entraînement:  71%|███████   | 7075/10000 [22:41<09:17,  5.25step/s, loss=0.045467, elapsed=22.7min]

Entraînement:  71%|███████   | 7076/10000 [22:41<09:16,  5.25step/s, loss=0.045467, elapsed=22.7min]

Entraînement:  71%|███████   | 7076/10000 [22:41<09:16,  5.25step/s, loss=0.049634, elapsed=22.7min]

Entraînement:  71%|███████   | 7077/10000 [22:42<09:15,  5.26step/s, loss=0.049634, elapsed=22.7min]

Entraînement:  71%|███████   | 7077/10000 [22:42<09:15,  5.26step/s, loss=0.052870, elapsed=22.7min]

Entraînement:  71%|███████   | 7078/10000 [22:42<09:15,  5.26step/s, loss=0.052870, elapsed=22.7min]

Entraînement:  71%|███████   | 7078/10000 [22:42<09:15,  5.26step/s, loss=0.057343, elapsed=22.7min]

Entraînement:  71%|███████   | 7079/10000 [22:42<09:15,  5.26step/s, loss=0.057343, elapsed=22.7min]

Entraînement:  71%|███████   | 7079/10000 [22:42<09:15,  5.26step/s, loss=0.054903, elapsed=22.7min]

Entraînement:  71%|███████   | 7080/10000 [22:42<09:18,  5.23step/s, loss=0.054903, elapsed=22.7min]

Entraînement:  71%|███████   | 7080/10000 [22:42<09:18,  5.23step/s, loss=0.039926, elapsed=22.7min]

Entraînement:  71%|███████   | 7081/10000 [22:42<09:17,  5.23step/s, loss=0.039926, elapsed=22.7min]

Entraînement:  71%|███████   | 7081/10000 [22:42<09:17,  5.23step/s, loss=0.065042, elapsed=22.7min]

Entraînement:  71%|███████   | 7082/10000 [22:42<09:17,  5.24step/s, loss=0.065042, elapsed=22.7min]

Entraînement:  71%|███████   | 7082/10000 [22:42<09:17,  5.24step/s, loss=0.065418, elapsed=22.7min]

Entraînement:  71%|███████   | 7083/10000 [22:43<09:15,  5.25step/s, loss=0.065418, elapsed=22.7min]

Entraînement:  71%|███████   | 7083/10000 [22:43<09:15,  5.25step/s, loss=0.035808, elapsed=22.7min]

Entraînement:  71%|███████   | 7084/10000 [22:43<09:14,  5.26step/s, loss=0.035808, elapsed=22.7min]

Entraînement:  71%|███████   | 7084/10000 [22:43<09:14,  5.26step/s, loss=0.131036, elapsed=22.7min]

Entraînement:  71%|███████   | 7085/10000 [22:43<09:13,  5.27step/s, loss=0.131036, elapsed=22.7min]

Entraînement:  71%|███████   | 7085/10000 [22:43<09:13,  5.27step/s, loss=0.037993, elapsed=22.7min]

Entraînement:  71%|███████   | 7086/10000 [22:43<09:12,  5.28step/s, loss=0.037993, elapsed=22.7min]

Entraînement:  71%|███████   | 7086/10000 [22:43<09:12,  5.28step/s, loss=0.047233, elapsed=22.7min]

Entraînement:  71%|███████   | 7087/10000 [22:43<09:13,  5.27step/s, loss=0.047233, elapsed=22.7min]

Entraînement:  71%|███████   | 7087/10000 [22:43<09:13,  5.27step/s, loss=0.029757, elapsed=22.7min]

Entraînement:  71%|███████   | 7088/10000 [22:44<09:12,  5.27step/s, loss=0.029757, elapsed=22.7min]

Entraînement:  71%|███████   | 7088/10000 [22:44<09:12,  5.27step/s, loss=0.027479, elapsed=22.7min]

Entraînement:  71%|███████   | 7089/10000 [22:44<09:12,  5.26step/s, loss=0.027479, elapsed=22.7min]

Entraînement:  71%|███████   | 7089/10000 [22:44<09:12,  5.26step/s, loss=0.020028, elapsed=22.7min]

Entraînement:  71%|███████   | 7090/10000 [22:44<09:12,  5.27step/s, loss=0.020028, elapsed=22.7min]

Entraînement:  71%|███████   | 7090/10000 [22:44<09:12,  5.27step/s, loss=0.025441, elapsed=22.7min]

Entraînement:  71%|███████   | 7091/10000 [22:44<09:12,  5.27step/s, loss=0.025441, elapsed=22.7min]

Entraînement:  71%|███████   | 7091/10000 [22:44<09:12,  5.27step/s, loss=0.042456, elapsed=22.7min]

Entraînement:  71%|███████   | 7092/10000 [22:44<09:12,  5.26step/s, loss=0.042456, elapsed=22.7min]

Entraînement:  71%|███████   | 7092/10000 [22:44<09:12,  5.26step/s, loss=0.069098, elapsed=22.7min]

Entraînement:  71%|███████   | 7093/10000 [22:45<09:11,  5.28step/s, loss=0.069098, elapsed=22.7min]

Entraînement:  71%|███████   | 7093/10000 [22:45<09:11,  5.28step/s, loss=0.063583, elapsed=22.8min]

Entraînement:  71%|███████   | 7094/10000 [22:45<09:10,  5.28step/s, loss=0.063583, elapsed=22.8min]

Entraînement:  71%|███████   | 7094/10000 [22:45<09:10,  5.28step/s, loss=0.045514, elapsed=22.8min]

Entraînement:  71%|███████   | 7095/10000 [22:45<09:09,  5.29step/s, loss=0.045514, elapsed=22.8min]

Entraînement:  71%|███████   | 7095/10000 [22:45<09:09,  5.29step/s, loss=0.090379, elapsed=22.8min]

Entraînement:  71%|███████   | 7096/10000 [22:45<09:10,  5.28step/s, loss=0.090379, elapsed=22.8min]

Entraînement:  71%|███████   | 7096/10000 [22:45<09:10,  5.28step/s, loss=0.076234, elapsed=22.8min]

Entraînement:  71%|███████   | 7097/10000 [22:45<09:10,  5.27step/s, loss=0.076234, elapsed=22.8min]

Entraînement:  71%|███████   | 7097/10000 [22:45<09:10,  5.27step/s, loss=0.098736, elapsed=22.8min]

Entraînement:  71%|███████   | 7098/10000 [22:46<09:11,  5.27step/s, loss=0.098736, elapsed=22.8min]

Entraînement:  71%|███████   | 7098/10000 [22:46<09:11,  5.27step/s, loss=0.045687, elapsed=22.8min]

Entraînement:  71%|███████   | 7099/10000 [22:46<09:10,  5.27step/s, loss=0.045687, elapsed=22.8min]

Entraînement:  71%|███████   | 7099/10000 [22:46<09:10,  5.27step/s, loss=0.040263, elapsed=22.8min]

Entraînement:  71%|███████   | 7100/10000 [22:46<09:09,  5.28step/s, loss=0.040263, elapsed=22.8min]

Entraînement:  71%|███████   | 7100/10000 [22:46<09:09,  5.28step/s, loss=0.034997, elapsed=22.8min]

Entraînement:  71%|███████   | 7100/10000 [22:46<09:09,  5.28step/s, loss=0.034997, elapsed=22.8min]

Entraînement:  71%|███████   | 7101/10000 [22:46<09:13,  5.24step/s, loss=0.034997, elapsed=22.8min]

Entraînement:  71%|███████   | 7101/10000 [22:46<09:13,  5.24step/s, loss=0.060375, elapsed=22.8min]

Step 7100/10000 | Train loss: 0.034997 | Elapsed: 22.8min | ETA: 9.3min

Entraînement:  71%|███████   | 7102/10000 [22:46<09:11,  5.25step/s, loss=0.060375, elapsed=22.8min]

Entraînement:  71%|███████   | 7102/10000 [22:46<09:11,  5.25step/s, loss=0.084748, elapsed=22.8min]

Entraînement:  71%|███████   | 7103/10000 [22:46<09:10,  5.26step/s, loss=0.084748, elapsed=22.8min]

Entraînement:  71%|███████   | 7103/10000 [22:46<09:10,  5.26step/s, loss=0.015982, elapsed=22.8min]

Entraînement:  71%|███████   | 7104/10000 [22:47<09:10,  5.26step/s, loss=0.015982, elapsed=22.8min]

Entraînement:  71%|███████   | 7104/10000 [22:47<09:10,  5.26step/s, loss=0.025449, elapsed=22.8min]

Entraînement:  71%|███████   | 7105/10000 [22:47<09:09,  5.27step/s, loss=0.025449, elapsed=22.8min]

Entraînement:  71%|███████   | 7105/10000 [22:47<09:09,  5.27step/s, loss=0.031336, elapsed=22.8min]

Entraînement:  71%|███████   | 7106/10000 [22:47<09:09,  5.27step/s, loss=0.031336, elapsed=22.8min]

Entraînement:  71%|███████   | 7106/10000 [22:47<09:09,  5.27step/s, loss=0.056400, elapsed=22.8min]

Entraînement:  71%|███████   | 7107/10000 [22:47<09:07,  5.28step/s, loss=0.056400, elapsed=22.8min]

Entraînement:  71%|███████   | 7107/10000 [22:47<09:07,  5.28step/s, loss=0.082950, elapsed=22.8min]

Entraînement:  71%|███████   | 7108/10000 [22:47<09:07,  5.28step/s, loss=0.082950, elapsed=22.8min]

Entraînement:  71%|███████   | 7108/10000 [22:47<09:07,  5.28step/s, loss=0.075430, elapsed=22.8min]

Entraînement:  71%|███████   | 7109/10000 [22:48<09:06,  5.29step/s, loss=0.075430, elapsed=22.8min]

Entraînement:  71%|███████   | 7109/10000 [22:48<09:06,  5.29step/s, loss=0.030422, elapsed=22.8min]

Entraînement:  71%|███████   | 7110/10000 [22:48<09:05,  5.30step/s, loss=0.030422, elapsed=22.8min]

Entraînement:  71%|███████   | 7110/10000 [22:48<09:05,  5.30step/s, loss=0.047865, elapsed=22.8min]

Entraînement:  71%|███████   | 7111/10000 [22:48<09:05,  5.30step/s, loss=0.047865, elapsed=22.8min]

Entraînement:  71%|███████   | 7111/10000 [22:48<09:05,  5.30step/s, loss=0.020060, elapsed=22.8min]

Entraînement:  71%|███████   | 7112/10000 [22:48<09:05,  5.29step/s, loss=0.020060, elapsed=22.8min]

Entraînement:  71%|███████   | 7112/10000 [22:48<09:05,  5.29step/s, loss=0.044645, elapsed=22.8min]

Entraînement:  71%|███████   | 7113/10000 [22:48<09:06,  5.29step/s, loss=0.044645, elapsed=22.8min]

Entraînement:  71%|███████   | 7113/10000 [22:48<09:06,  5.29step/s, loss=0.063050, elapsed=22.8min]

Entraînement:  71%|███████   | 7114/10000 [22:49<09:05,  5.29step/s, loss=0.063050, elapsed=22.8min]

Entraînement:  71%|███████   | 7114/10000 [22:49<09:05,  5.29step/s, loss=0.031800, elapsed=22.8min]

Entraînement:  71%|███████   | 7115/10000 [22:49<09:06,  5.27step/s, loss=0.031800, elapsed=22.8min]

Entraînement:  71%|███████   | 7115/10000 [22:49<09:06,  5.27step/s, loss=0.089905, elapsed=22.8min]

Entraînement:  71%|███████   | 7116/10000 [22:49<09:06,  5.28step/s, loss=0.089905, elapsed=22.8min]

Entraînement:  71%|███████   | 7116/10000 [22:49<09:06,  5.28step/s, loss=0.019034, elapsed=22.8min]

Entraînement:  71%|███████   | 7117/10000 [22:49<09:06,  5.28step/s, loss=0.019034, elapsed=22.8min]

Entraînement:  71%|███████   | 7117/10000 [22:49<09:06,  5.28step/s, loss=0.021500, elapsed=22.8min]

Entraînement:  71%|███████   | 7118/10000 [22:49<09:04,  5.30step/s, loss=0.021500, elapsed=22.8min]

Entraînement:  71%|███████   | 7118/10000 [22:49<09:04,  5.30step/s, loss=0.039804, elapsed=22.8min]

Entraînement:  71%|███████   | 7119/10000 [22:49<09:03,  5.30step/s, loss=0.039804, elapsed=22.8min]

Entraînement:  71%|███████   | 7119/10000 [22:49<09:03,  5.30step/s, loss=0.059118, elapsed=22.8min]

Entraînement:  71%|███████   | 7120/10000 [22:50<09:05,  5.28step/s, loss=0.059118, elapsed=22.8min]

Entraînement:  71%|███████   | 7120/10000 [22:50<09:05,  5.28step/s, loss=0.053832, elapsed=22.8min]

Entraînement:  71%|███████   | 7121/10000 [22:50<09:04,  5.29step/s, loss=0.053832, elapsed=22.8min]

Entraînement:  71%|███████   | 7121/10000 [22:50<09:04,  5.29step/s, loss=0.036182, elapsed=22.8min]

Entraînement:  71%|███████   | 7122/10000 [22:50<09:03,  5.29step/s, loss=0.036182, elapsed=22.8min]

Entraînement:  71%|███████   | 7122/10000 [22:50<09:03,  5.29step/s, loss=0.052779, elapsed=22.8min]

Entraînement:  71%|███████   | 7123/10000 [22:50<09:04,  5.28step/s, loss=0.052779, elapsed=22.8min]

Entraînement:  71%|███████   | 7123/10000 [22:50<09:04,  5.28step/s, loss=0.051338, elapsed=22.8min]

Entraînement:  71%|███████   | 7124/10000 [22:50<09:03,  5.29step/s, loss=0.051338, elapsed=22.8min]

Entraînement:  71%|███████   | 7124/10000 [22:50<09:03,  5.29step/s, loss=0.023104, elapsed=22.8min]

Entraînement:  71%|███████▏  | 7125/10000 [22:51<09:02,  5.30step/s, loss=0.023104, elapsed=22.8min]

Entraînement:  71%|███████▏  | 7125/10000 [22:51<09:02,  5.30step/s, loss=0.114516, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7126/10000 [22:51<09:02,  5.29step/s, loss=0.114516, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7126/10000 [22:51<09:02,  5.29step/s, loss=0.028539, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7127/10000 [22:51<09:03,  5.28step/s, loss=0.028539, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7127/10000 [22:51<09:03,  5.28step/s, loss=0.052163, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7128/10000 [22:51<09:04,  5.27step/s, loss=0.052163, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7128/10000 [22:51<09:04,  5.27step/s, loss=0.042920, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7129/10000 [22:51<09:04,  5.27step/s, loss=0.042920, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7129/10000 [22:51<09:04,  5.27step/s, loss=0.051812, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7130/10000 [22:52<09:03,  5.28step/s, loss=0.051812, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7130/10000 [22:52<09:03,  5.28step/s, loss=0.052837, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7131/10000 [22:52<09:04,  5.27step/s, loss=0.052837, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7131/10000 [22:52<09:04,  5.27step/s, loss=0.098604, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7132/10000 [22:52<09:03,  5.28step/s, loss=0.098604, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7132/10000 [22:52<09:03,  5.28step/s, loss=0.036029, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7133/10000 [22:52<09:00,  5.30step/s, loss=0.036029, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7133/10000 [22:52<09:00,  5.30step/s, loss=0.042754, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7134/10000 [22:52<09:01,  5.29step/s, loss=0.042754, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7134/10000 [22:52<09:01,  5.29step/s, loss=0.050513, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7135/10000 [22:53<09:01,  5.29step/s, loss=0.050513, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7135/10000 [22:53<09:01,  5.29step/s, loss=0.022696, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7136/10000 [22:53<09:03,  5.27step/s, loss=0.022696, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7136/10000 [22:53<09:03,  5.27step/s, loss=0.045622, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7137/10000 [22:53<09:05,  5.25step/s, loss=0.045622, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7137/10000 [22:53<09:05,  5.25step/s, loss=0.027131, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7138/10000 [22:53<09:05,  5.25step/s, loss=0.027131, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7138/10000 [22:53<09:05,  5.25step/s, loss=0.032222, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7139/10000 [22:53<09:03,  5.26step/s, loss=0.032222, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7139/10000 [22:53<09:03,  5.26step/s, loss=0.040530, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7140/10000 [22:53<09:04,  5.25step/s, loss=0.040530, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7140/10000 [22:53<09:04,  5.25step/s, loss=0.064104, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7141/10000 [22:54<09:03,  5.26step/s, loss=0.064104, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7141/10000 [22:54<09:03,  5.26step/s, loss=0.041145, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7142/10000 [22:54<09:03,  5.26step/s, loss=0.041145, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7142/10000 [22:54<09:03,  5.26step/s, loss=0.047925, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7143/10000 [22:54<09:03,  5.25step/s, loss=0.047925, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7143/10000 [22:54<09:03,  5.25step/s, loss=0.036440, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7144/10000 [22:54<09:04,  5.25step/s, loss=0.036440, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7144/10000 [22:54<09:04,  5.25step/s, loss=0.058607, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7145/10000 [22:54<09:04,  5.25step/s, loss=0.058607, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7145/10000 [22:54<09:04,  5.25step/s, loss=0.022709, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7146/10000 [22:55<09:02,  5.26step/s, loss=0.022709, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7146/10000 [22:55<09:02,  5.26step/s, loss=0.027796, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7147/10000 [22:55<09:05,  5.23step/s, loss=0.027796, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7147/10000 [22:55<09:05,  5.23step/s, loss=0.035328, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7148/10000 [22:55<09:03,  5.25step/s, loss=0.035328, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7148/10000 [22:55<09:03,  5.25step/s, loss=0.023446, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7149/10000 [22:55<09:03,  5.25step/s, loss=0.023446, elapsed=22.9min]

Entraînement:  71%|███████▏  | 7149/10000 [22:55<09:03,  5.25step/s, loss=0.037609, elapsed=22.9min]

Entraînement:  72%|███████▏  | 7150/10000 [22:55<09:06,  5.22step/s, loss=0.037609, elapsed=22.9min]

Entraînement:  72%|███████▏  | 7150/10000 [22:55<09:06,  5.22step/s, loss=0.051792, elapsed=22.9min]

Entraînement:  72%|███████▏  | 7151/10000 [22:56<09:05,  5.22step/s, loss=0.051792, elapsed=22.9min]

Entraînement:  72%|███████▏  | 7151/10000 [22:56<09:05,  5.22step/s, loss=0.041341, elapsed=22.9min]

Entraînement:  72%|███████▏  | 7152/10000 [22:56<09:04,  5.23step/s, loss=0.041341, elapsed=22.9min]

Entraînement:  72%|███████▏  | 7152/10000 [22:56<09:04,  5.23step/s, loss=0.026970, elapsed=22.9min]

Entraînement:  72%|███████▏  | 7153/10000 [22:56<09:03,  5.24step/s, loss=0.026970, elapsed=22.9min]

Entraînement:  72%|███████▏  | 7153/10000 [22:56<09:03,  5.24step/s, loss=0.057445, elapsed=22.9min]

Entraînement:  72%|███████▏  | 7154/10000 [22:56<09:02,  5.25step/s, loss=0.057445, elapsed=22.9min]

Entraînement:  72%|███████▏  | 7154/10000 [22:56<09:02,  5.25step/s, loss=0.021350, elapsed=22.9min]

Entraînement:  72%|███████▏  | 7155/10000 [22:56<09:01,  5.25step/s, loss=0.021350, elapsed=22.9min]

Entraînement:  72%|███████▏  | 7155/10000 [22:56<09:01,  5.25step/s, loss=0.068706, elapsed=22.9min]

Entraînement:  72%|███████▏  | 7156/10000 [22:57<09:02,  5.24step/s, loss=0.068706, elapsed=22.9min]

Entraînement:  72%|███████▏  | 7156/10000 [22:57<09:02,  5.24step/s, loss=0.058353, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7157/10000 [22:57<09:02,  5.24step/s, loss=0.058353, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7157/10000 [22:57<09:02,  5.24step/s, loss=0.128295, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7158/10000 [22:57<09:02,  5.24step/s, loss=0.128295, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7158/10000 [22:57<09:02,  5.24step/s, loss=0.151822, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7159/10000 [22:57<09:02,  5.23step/s, loss=0.151822, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7159/10000 [22:57<09:02,  5.23step/s, loss=0.018236, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7160/10000 [22:57<09:02,  5.23step/s, loss=0.018236, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7160/10000 [22:57<09:02,  5.23step/s, loss=0.075885, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7161/10000 [22:57<09:02,  5.23step/s, loss=0.075885, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7161/10000 [22:57<09:02,  5.23step/s, loss=0.043879, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7162/10000 [22:58<09:04,  5.21step/s, loss=0.043879, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7162/10000 [22:58<09:04,  5.21step/s, loss=0.038499, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7163/10000 [22:58<09:03,  5.22step/s, loss=0.038499, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7163/10000 [22:58<09:03,  5.22step/s, loss=0.027520, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7164/10000 [22:58<09:01,  5.24step/s, loss=0.027520, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7164/10000 [22:58<09:01,  5.24step/s, loss=0.037765, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7165/10000 [22:58<09:01,  5.24step/s, loss=0.037765, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7165/10000 [22:58<09:01,  5.24step/s, loss=0.039734, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7166/10000 [22:58<08:59,  5.25step/s, loss=0.039734, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7166/10000 [22:58<08:59,  5.25step/s, loss=0.035267, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7167/10000 [22:59<09:00,  5.24step/s, loss=0.035267, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7167/10000 [22:59<09:00,  5.24step/s, loss=0.071147, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7168/10000 [22:59<09:01,  5.23step/s, loss=0.071147, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7168/10000 [22:59<09:01,  5.23step/s, loss=0.079306, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7169/10000 [22:59<09:03,  5.21step/s, loss=0.079306, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7169/10000 [22:59<09:03,  5.21step/s, loss=0.113465, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7170/10000 [22:59<09:02,  5.22step/s, loss=0.113465, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7170/10000 [22:59<09:02,  5.22step/s, loss=0.037696, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7171/10000 [22:59<09:01,  5.22step/s, loss=0.037696, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7171/10000 [22:59<09:01,  5.22step/s, loss=0.070056, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7172/10000 [23:00<08:59,  5.24step/s, loss=0.070056, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7172/10000 [23:00<08:59,  5.24step/s, loss=0.057756, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7173/10000 [23:00<08:58,  5.25step/s, loss=0.057756, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7173/10000 [23:00<08:58,  5.25step/s, loss=0.029353, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7174/10000 [23:00<08:58,  5.25step/s, loss=0.029353, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7174/10000 [23:00<08:58,  5.25step/s, loss=0.058173, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7175/10000 [23:00<08:59,  5.24step/s, loss=0.058173, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7175/10000 [23:00<08:59,  5.24step/s, loss=0.031883, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7176/10000 [23:00<08:58,  5.25step/s, loss=0.031883, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7176/10000 [23:00<08:58,  5.25step/s, loss=0.014305, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7177/10000 [23:01<08:57,  5.25step/s, loss=0.014305, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7177/10000 [23:01<08:57,  5.25step/s, loss=0.064513, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7178/10000 [23:01<08:57,  5.25step/s, loss=0.064513, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7178/10000 [23:01<08:57,  5.25step/s, loss=0.083892, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7179/10000 [23:01<08:56,  5.26step/s, loss=0.083892, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7179/10000 [23:01<08:56,  5.26step/s, loss=0.078579, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7180/10000 [23:01<08:55,  5.27step/s, loss=0.078579, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7180/10000 [23:01<08:55,  5.27step/s, loss=0.151632, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7181/10000 [23:01<08:55,  5.26step/s, loss=0.151632, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7181/10000 [23:01<08:55,  5.26step/s, loss=0.092140, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7182/10000 [23:01<08:55,  5.26step/s, loss=0.092140, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7182/10000 [23:01<08:55,  5.26step/s, loss=0.042373, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7183/10000 [23:02<08:55,  5.26step/s, loss=0.042373, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7183/10000 [23:02<08:55,  5.26step/s, loss=0.027846, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7184/10000 [23:02<08:56,  5.25step/s, loss=0.027846, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7184/10000 [23:02<08:56,  5.25step/s, loss=0.040609, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7185/10000 [23:02<08:55,  5.25step/s, loss=0.040609, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7185/10000 [23:02<08:55,  5.25step/s, loss=0.024465, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7186/10000 [23:02<08:54,  5.26step/s, loss=0.024465, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7186/10000 [23:02<08:54,  5.26step/s, loss=0.077916, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7187/10000 [23:02<08:54,  5.26step/s, loss=0.077916, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7187/10000 [23:02<08:54,  5.26step/s, loss=0.019728, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7188/10000 [23:03<08:54,  5.27step/s, loss=0.019728, elapsed=23.0min]

Entraînement:  72%|███████▏  | 7188/10000 [23:03<08:54,  5.27step/s, loss=0.062434, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7189/10000 [23:03<08:53,  5.27step/s, loss=0.062434, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7189/10000 [23:03<08:53,  5.27step/s, loss=0.074250, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7190/10000 [23:03<08:53,  5.27step/s, loss=0.074250, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7190/10000 [23:03<08:53,  5.27step/s, loss=0.042131, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7191/10000 [23:03<08:53,  5.27step/s, loss=0.042131, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7191/10000 [23:03<08:53,  5.27step/s, loss=0.060618, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7192/10000 [23:03<08:53,  5.26step/s, loss=0.060618, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7192/10000 [23:03<08:53,  5.26step/s, loss=0.046348, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7193/10000 [23:04<08:53,  5.26step/s, loss=0.046348, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7193/10000 [23:04<08:53,  5.26step/s, loss=0.038872, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7194/10000 [23:04<08:52,  5.27step/s, loss=0.038872, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7194/10000 [23:04<08:52,  5.27step/s, loss=0.027299, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7195/10000 [23:04<08:52,  5.27step/s, loss=0.027299, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7195/10000 [23:04<08:52,  5.27step/s, loss=0.120956, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7196/10000 [23:04<08:51,  5.27step/s, loss=0.120956, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7196/10000 [23:04<08:51,  5.27step/s, loss=0.033526, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7197/10000 [23:04<08:50,  5.28step/s, loss=0.033526, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7197/10000 [23:04<08:50,  5.28step/s, loss=0.028807, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7198/10000 [23:05<08:50,  5.28step/s, loss=0.028807, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7198/10000 [23:05<08:50,  5.28step/s, loss=0.043169, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7199/10000 [23:05<08:50,  5.28step/s, loss=0.043169, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7199/10000 [23:05<08:50,  5.28step/s, loss=0.045600, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7200/10000 [23:05<08:50,  5.28step/s, loss=0.045600, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7200/10000 [23:05<08:50,  5.28step/s, loss=0.022057, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7200/10000 [23:05<08:50,  5.28step/s, loss=0.022057, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7201/10000 [23:05<08:55,  5.23step/s, loss=0.022057, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7201/10000 [23:05<08:55,  5.23step/s, loss=0.067393, elapsed=23.1min]

Step 7200/10000 | Train loss: 0.022057 | Elapsed: 23.1min | ETA: 9.0min

Entraînement:  72%|███████▏  | 7202/10000 [23:05<08:55,  5.23step/s, loss=0.067393, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7202/10000 [23:05<08:55,  5.23step/s, loss=0.065440, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7203/10000 [23:05<08:52,  5.25step/s, loss=0.065440, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7203/10000 [23:05<08:52,  5.25step/s, loss=0.112160, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7204/10000 [23:06<08:52,  5.25step/s, loss=0.112160, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7204/10000 [23:06<08:52,  5.25step/s, loss=0.044681, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7205/10000 [23:06<08:51,  5.26step/s, loss=0.044681, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7205/10000 [23:06<08:51,  5.26step/s, loss=0.023998, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7206/10000 [23:06<08:49,  5.27step/s, loss=0.023998, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7206/10000 [23:06<08:49,  5.27step/s, loss=0.037597, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7207/10000 [23:06<08:49,  5.28step/s, loss=0.037597, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7207/10000 [23:06<08:49,  5.28step/s, loss=0.018949, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7208/10000 [23:06<08:48,  5.28step/s, loss=0.018949, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7208/10000 [23:06<08:48,  5.28step/s, loss=0.060624, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7209/10000 [23:07<08:47,  5.29step/s, loss=0.060624, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7209/10000 [23:07<08:47,  5.29step/s, loss=0.020865, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7210/10000 [23:07<08:48,  5.28step/s, loss=0.020865, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7210/10000 [23:07<08:48,  5.28step/s, loss=0.018208, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7211/10000 [23:07<08:47,  5.29step/s, loss=0.018208, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7211/10000 [23:07<08:47,  5.29step/s, loss=0.039922, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7212/10000 [23:07<08:46,  5.30step/s, loss=0.039922, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7212/10000 [23:07<08:46,  5.30step/s, loss=0.024953, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7213/10000 [23:07<08:46,  5.29step/s, loss=0.024953, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7213/10000 [23:07<08:46,  5.29step/s, loss=0.017258, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7214/10000 [23:08<08:46,  5.29step/s, loss=0.017258, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7214/10000 [23:08<08:46,  5.29step/s, loss=0.061206, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7215/10000 [23:08<08:45,  5.30step/s, loss=0.061206, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7215/10000 [23:08<08:45,  5.30step/s, loss=0.018406, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7216/10000 [23:08<08:45,  5.30step/s, loss=0.018406, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7216/10000 [23:08<08:45,  5.30step/s, loss=0.032675, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7217/10000 [23:08<08:46,  5.29step/s, loss=0.032675, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7217/10000 [23:08<08:46,  5.29step/s, loss=0.040888, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7218/10000 [23:08<08:43,  5.31step/s, loss=0.040888, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7218/10000 [23:08<08:43,  5.31step/s, loss=0.034764, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7219/10000 [23:08<08:42,  5.32step/s, loss=0.034764, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7219/10000 [23:08<08:42,  5.32step/s, loss=0.040520, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7220/10000 [23:09<08:42,  5.33step/s, loss=0.040520, elapsed=23.1min]

Entraînement:  72%|███████▏  | 7220/10000 [23:09<08:42,  5.33step/s, loss=0.087275, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7221/10000 [23:09<08:40,  5.34step/s, loss=0.087275, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7221/10000 [23:09<08:40,  5.34step/s, loss=0.027433, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7222/10000 [23:09<08:39,  5.35step/s, loss=0.027433, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7222/10000 [23:09<08:39,  5.35step/s, loss=0.084031, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7223/10000 [23:09<08:38,  5.35step/s, loss=0.084031, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7223/10000 [23:09<08:38,  5.35step/s, loss=0.025933, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7224/10000 [23:09<08:38,  5.35step/s, loss=0.025933, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7224/10000 [23:09<08:38,  5.35step/s, loss=0.073575, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7225/10000 [23:10<08:39,  5.35step/s, loss=0.073575, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7225/10000 [23:10<08:39,  5.35step/s, loss=0.044305, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7226/10000 [23:10<08:41,  5.32step/s, loss=0.044305, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7226/10000 [23:10<08:41,  5.32step/s, loss=0.044991, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7227/10000 [23:10<08:43,  5.30step/s, loss=0.044991, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7227/10000 [23:10<08:43,  5.30step/s, loss=0.108791, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7228/10000 [23:10<08:44,  5.28step/s, loss=0.108791, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7228/10000 [23:10<08:44,  5.28step/s, loss=0.078045, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7229/10000 [23:10<08:44,  5.28step/s, loss=0.078045, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7229/10000 [23:10<08:44,  5.28step/s, loss=0.053131, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7230/10000 [23:11<08:45,  5.27step/s, loss=0.053131, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7230/10000 [23:11<08:45,  5.27step/s, loss=0.043661, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7231/10000 [23:11<08:44,  5.28step/s, loss=0.043661, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7231/10000 [23:11<08:44,  5.28step/s, loss=0.050685, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7232/10000 [23:11<08:44,  5.28step/s, loss=0.050685, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7232/10000 [23:11<08:44,  5.28step/s, loss=0.092321, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7233/10000 [23:11<08:43,  5.28step/s, loss=0.092321, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7233/10000 [23:11<08:43,  5.28step/s, loss=0.134394, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7234/10000 [23:11<08:43,  5.28step/s, loss=0.134394, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7234/10000 [23:11<08:43,  5.28step/s, loss=0.034646, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7235/10000 [23:12<08:43,  5.29step/s, loss=0.034646, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7235/10000 [23:12<08:43,  5.29step/s, loss=0.046105, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7236/10000 [23:12<08:43,  5.28step/s, loss=0.046105, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7236/10000 [23:12<08:43,  5.28step/s, loss=0.033295, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7237/10000 [23:12<08:42,  5.29step/s, loss=0.033295, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7237/10000 [23:12<08:42,  5.29step/s, loss=0.040028, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7238/10000 [23:12<08:42,  5.29step/s, loss=0.040028, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7238/10000 [23:12<08:42,  5.29step/s, loss=0.031849, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7239/10000 [23:12<08:42,  5.28step/s, loss=0.031849, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7239/10000 [23:12<08:42,  5.28step/s, loss=0.029622, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7240/10000 [23:12<08:41,  5.29step/s, loss=0.029622, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7240/10000 [23:12<08:41,  5.29step/s, loss=0.022221, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7241/10000 [23:13<08:41,  5.29step/s, loss=0.022221, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7241/10000 [23:13<08:41,  5.29step/s, loss=0.014657, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7242/10000 [23:13<08:41,  5.29step/s, loss=0.014657, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7242/10000 [23:13<08:41,  5.29step/s, loss=0.022847, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7243/10000 [23:13<08:40,  5.30step/s, loss=0.022847, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7243/10000 [23:13<08:40,  5.30step/s, loss=0.031161, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7244/10000 [23:13<08:41,  5.29step/s, loss=0.031161, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7244/10000 [23:13<08:41,  5.29step/s, loss=0.023540, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7245/10000 [23:13<08:40,  5.29step/s, loss=0.023540, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7245/10000 [23:13<08:40,  5.29step/s, loss=0.044845, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7246/10000 [23:14<08:40,  5.29step/s, loss=0.044845, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7246/10000 [23:14<08:40,  5.29step/s, loss=0.035196, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7247/10000 [23:14<08:40,  5.29step/s, loss=0.035196, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7247/10000 [23:14<08:40,  5.29step/s, loss=0.014434, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7248/10000 [23:14<08:38,  5.30step/s, loss=0.014434, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7248/10000 [23:14<08:38,  5.30step/s, loss=0.088004, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7249/10000 [23:14<08:39,  5.30step/s, loss=0.088004, elapsed=23.2min]

Entraînement:  72%|███████▏  | 7249/10000 [23:14<08:39,  5.30step/s, loss=0.085911, elapsed=23.2min]

Entraînement:  72%|███████▎  | 7250/10000 [23:14<08:40,  5.29step/s, loss=0.085911, elapsed=23.2min]

Entraînement:  72%|███████▎  | 7250/10000 [23:14<08:40,  5.29step/s, loss=0.025528, elapsed=23.2min]

Entraînement:  73%|███████▎  | 7251/10000 [23:15<08:42,  5.27step/s, loss=0.025528, elapsed=23.2min]

Entraînement:  73%|███████▎  | 7251/10000 [23:15<08:42,  5.27step/s, loss=0.098946, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7252/10000 [23:15<08:41,  5.27step/s, loss=0.098946, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7252/10000 [23:15<08:41,  5.27step/s, loss=0.019472, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7253/10000 [23:15<08:41,  5.27step/s, loss=0.019472, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7253/10000 [23:15<08:41,  5.27step/s, loss=0.016571, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7254/10000 [23:15<08:40,  5.27step/s, loss=0.016571, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7254/10000 [23:15<08:40,  5.27step/s, loss=0.048495, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7255/10000 [23:15<08:39,  5.28step/s, loss=0.048495, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7255/10000 [23:15<08:39,  5.28step/s, loss=0.047091, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7256/10000 [23:15<08:39,  5.28step/s, loss=0.047091, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7256/10000 [23:15<08:39,  5.28step/s, loss=0.035417, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7257/10000 [23:16<08:38,  5.29step/s, loss=0.035417, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7257/10000 [23:16<08:38,  5.29step/s, loss=0.063629, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7258/10000 [23:16<08:40,  5.27step/s, loss=0.063629, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7258/10000 [23:16<08:40,  5.27step/s, loss=0.045150, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7259/10000 [23:16<08:40,  5.26step/s, loss=0.045150, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7259/10000 [23:16<08:40,  5.26step/s, loss=0.028016, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7260/10000 [23:16<08:40,  5.26step/s, loss=0.028016, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7260/10000 [23:16<08:40,  5.26step/s, loss=0.034441, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7261/10000 [23:16<08:39,  5.27step/s, loss=0.034441, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7261/10000 [23:16<08:39,  5.27step/s, loss=0.019881, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7262/10000 [23:17<08:38,  5.28step/s, loss=0.019881, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7262/10000 [23:17<08:38,  5.28step/s, loss=0.046100, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7263/10000 [23:17<08:38,  5.28step/s, loss=0.046100, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7263/10000 [23:17<08:38,  5.28step/s, loss=0.058076, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7264/10000 [23:17<08:37,  5.28step/s, loss=0.058076, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7264/10000 [23:17<08:37,  5.28step/s, loss=0.027498, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7265/10000 [23:17<08:36,  5.29step/s, loss=0.027498, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7265/10000 [23:17<08:36,  5.29step/s, loss=0.029484, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7266/10000 [23:17<08:37,  5.28step/s, loss=0.029484, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7266/10000 [23:17<08:37,  5.28step/s, loss=0.045393, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7267/10000 [23:18<08:37,  5.28step/s, loss=0.045393, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7267/10000 [23:18<08:37,  5.28step/s, loss=0.037106, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7268/10000 [23:18<08:38,  5.27step/s, loss=0.037106, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7268/10000 [23:18<08:38,  5.27step/s, loss=0.035787, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7269/10000 [23:18<08:38,  5.27step/s, loss=0.035787, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7269/10000 [23:18<08:38,  5.27step/s, loss=0.024416, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7270/10000 [23:18<08:37,  5.27step/s, loss=0.024416, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7270/10000 [23:18<08:37,  5.27step/s, loss=0.032005, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7271/10000 [23:18<08:37,  5.27step/s, loss=0.032005, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7271/10000 [23:18<08:37,  5.27step/s, loss=0.033770, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7272/10000 [23:19<08:37,  5.28step/s, loss=0.033770, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7272/10000 [23:19<08:37,  5.28step/s, loss=0.033548, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7273/10000 [23:19<08:37,  5.27step/s, loss=0.033548, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7273/10000 [23:19<08:37,  5.27step/s, loss=0.018517, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7274/10000 [23:19<08:38,  5.25step/s, loss=0.018517, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7274/10000 [23:19<08:38,  5.25step/s, loss=0.034113, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7275/10000 [23:19<08:38,  5.25step/s, loss=0.034113, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7275/10000 [23:19<08:38,  5.25step/s, loss=0.018575, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7276/10000 [23:19<08:37,  5.26step/s, loss=0.018575, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7276/10000 [23:19<08:37,  5.26step/s, loss=0.023493, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7277/10000 [23:19<08:37,  5.26step/s, loss=0.023493, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7277/10000 [23:19<08:37,  5.26step/s, loss=0.092188, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7278/10000 [23:20<08:36,  5.27step/s, loss=0.092188, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7278/10000 [23:20<08:36,  5.27step/s, loss=0.062224, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7279/10000 [23:20<08:35,  5.28step/s, loss=0.062224, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7279/10000 [23:20<08:35,  5.28step/s, loss=0.026387, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7280/10000 [23:20<08:35,  5.28step/s, loss=0.026387, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7280/10000 [23:20<08:35,  5.28step/s, loss=0.080922, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7281/10000 [23:20<08:36,  5.27step/s, loss=0.080922, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7281/10000 [23:20<08:36,  5.27step/s, loss=0.067076, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7282/10000 [23:20<08:36,  5.26step/s, loss=0.067076, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7282/10000 [23:20<08:36,  5.26step/s, loss=0.032841, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7283/10000 [23:21<08:36,  5.26step/s, loss=0.032841, elapsed=23.3min]

Entraînement:  73%|███████▎  | 7283/10000 [23:21<08:36,  5.26step/s, loss=0.032674, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7284/10000 [23:21<08:36,  5.26step/s, loss=0.032674, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7284/10000 [23:21<08:36,  5.26step/s, loss=0.064679, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7285/10000 [23:21<08:34,  5.28step/s, loss=0.064679, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7285/10000 [23:21<08:34,  5.28step/s, loss=0.051519, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7286/10000 [23:21<08:34,  5.28step/s, loss=0.051519, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7286/10000 [23:21<08:34,  5.28step/s, loss=0.077121, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7287/10000 [23:21<08:33,  5.28step/s, loss=0.077121, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7287/10000 [23:21<08:33,  5.28step/s, loss=0.073249, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7288/10000 [23:22<08:33,  5.28step/s, loss=0.073249, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7288/10000 [23:22<08:33,  5.28step/s, loss=0.031032, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7289/10000 [23:22<08:34,  5.27step/s, loss=0.031032, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7289/10000 [23:22<08:34,  5.27step/s, loss=0.068836, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7290/10000 [23:22<08:33,  5.28step/s, loss=0.068836, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7290/10000 [23:22<08:33,  5.28step/s, loss=0.033208, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7291/10000 [23:22<08:34,  5.27step/s, loss=0.033208, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7291/10000 [23:22<08:34,  5.27step/s, loss=0.058971, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7292/10000 [23:22<08:34,  5.27step/s, loss=0.058971, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7292/10000 [23:22<08:34,  5.27step/s, loss=0.030197, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7293/10000 [23:22<08:33,  5.27step/s, loss=0.030197, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7293/10000 [23:22<08:33,  5.27step/s, loss=0.035226, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7294/10000 [23:23<08:32,  5.28step/s, loss=0.035226, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7294/10000 [23:23<08:32,  5.28step/s, loss=0.172738, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7295/10000 [23:23<08:31,  5.28step/s, loss=0.172738, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7295/10000 [23:23<08:31,  5.28step/s, loss=0.071794, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7296/10000 [23:23<08:31,  5.28step/s, loss=0.071794, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7296/10000 [23:23<08:31,  5.28step/s, loss=0.052919, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7297/10000 [23:23<08:31,  5.28step/s, loss=0.052919, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7297/10000 [23:23<08:31,  5.28step/s, loss=0.040137, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7298/10000 [23:23<08:32,  5.27step/s, loss=0.040137, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7298/10000 [23:23<08:32,  5.27step/s, loss=0.040275, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7299/10000 [23:24<08:31,  5.28step/s, loss=0.040275, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7299/10000 [23:24<08:31,  5.28step/s, loss=0.021607, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7300/10000 [23:24<12:25,  3.62step/s, loss=0.021607, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7300/10000 [23:24<12:25,  3.62step/s, loss=0.023472, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7300/10000 [23:24<12:25,  3.62step/s, loss=0.023472, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7301/10000 [23:24<11:22,  3.95step/s, loss=0.023472, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7301/10000 [23:24<11:22,  3.95step/s, loss=0.032282, elapsed=23.4min]

Step 7300/10000 | Train loss: 0.023472 | Elapsed: 23.4min | ETA: 8.7min

Entraînement:  73%|███████▎  | 7302/10000 [23:24<10:31,  4.28step/s, loss=0.032282, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7302/10000 [23:24<10:31,  4.28step/s, loss=0.083130, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7303/10000 [23:25<09:54,  4.54step/s, loss=0.083130, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7303/10000 [23:25<09:54,  4.54step/s, loss=0.032923, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7304/10000 [23:25<09:29,  4.73step/s, loss=0.032923, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7304/10000 [23:25<09:29,  4.73step/s, loss=0.047845, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7305/10000 [23:25<09:12,  4.88step/s, loss=0.047845, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7305/10000 [23:25<09:12,  4.88step/s, loss=0.083096, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7306/10000 [23:25<09:00,  4.98step/s, loss=0.083096, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7306/10000 [23:25<09:00,  4.98step/s, loss=0.020347, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7307/10000 [23:25<08:52,  5.06step/s, loss=0.020347, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7307/10000 [23:25<08:52,  5.06step/s, loss=0.119717, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7308/10000 [23:26<08:46,  5.12step/s, loss=0.119717, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7308/10000 [23:26<08:46,  5.12step/s, loss=0.037544, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7309/10000 [23:26<08:41,  5.16step/s, loss=0.037544, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7309/10000 [23:26<08:41,  5.16step/s, loss=0.069518, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7310/10000 [23:26<08:38,  5.19step/s, loss=0.069518, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7310/10000 [23:26<08:38,  5.19step/s, loss=0.059313, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7311/10000 [23:26<08:35,  5.21step/s, loss=0.059313, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7311/10000 [23:26<08:35,  5.21step/s, loss=0.031957, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7312/10000 [23:26<08:33,  5.23step/s, loss=0.031957, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7312/10000 [23:26<08:33,  5.23step/s, loss=0.020351, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7313/10000 [23:27<08:33,  5.24step/s, loss=0.020351, elapsed=23.4min]

Entraînement:  73%|███████▎  | 7313/10000 [23:27<08:33,  5.24step/s, loss=0.088267, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7314/10000 [23:27<08:31,  5.25step/s, loss=0.088267, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7314/10000 [23:27<08:31,  5.25step/s, loss=0.017004, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7315/10000 [23:27<08:31,  5.25step/s, loss=0.017004, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7315/10000 [23:27<08:31,  5.25step/s, loss=0.038796, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7316/10000 [23:27<08:30,  5.26step/s, loss=0.038796, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7316/10000 [23:27<08:30,  5.26step/s, loss=0.087390, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7317/10000 [23:27<08:30,  5.26step/s, loss=0.087390, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7317/10000 [23:27<08:30,  5.26step/s, loss=0.027725, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7318/10000 [23:28<08:29,  5.26step/s, loss=0.027725, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7318/10000 [23:28<08:29,  5.26step/s, loss=0.048803, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7319/10000 [23:28<08:29,  5.26step/s, loss=0.048803, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7319/10000 [23:28<08:29,  5.26step/s, loss=0.059251, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7320/10000 [23:28<08:29,  5.26step/s, loss=0.059251, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7320/10000 [23:28<08:29,  5.26step/s, loss=0.029486, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7321/10000 [23:28<08:30,  5.25step/s, loss=0.029486, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7321/10000 [23:28<08:30,  5.25step/s, loss=0.031470, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7322/10000 [23:28<08:30,  5.25step/s, loss=0.031470, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7322/10000 [23:28<08:30,  5.25step/s, loss=0.045740, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7323/10000 [23:28<08:30,  5.24step/s, loss=0.045740, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7323/10000 [23:28<08:30,  5.24step/s, loss=0.085826, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7324/10000 [23:29<08:29,  5.25step/s, loss=0.085826, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7324/10000 [23:29<08:29,  5.25step/s, loss=0.030847, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7325/10000 [23:29<08:29,  5.25step/s, loss=0.030847, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7325/10000 [23:29<08:29,  5.25step/s, loss=0.039509, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7326/10000 [23:29<08:28,  5.26step/s, loss=0.039509, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7326/10000 [23:29<08:28,  5.26step/s, loss=0.045471, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7327/10000 [23:29<08:27,  5.27step/s, loss=0.045471, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7327/10000 [23:29<08:27,  5.27step/s, loss=0.049772, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7328/10000 [23:29<08:28,  5.26step/s, loss=0.049772, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7328/10000 [23:29<08:28,  5.26step/s, loss=0.033325, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7329/10000 [23:30<08:28,  5.25step/s, loss=0.033325, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7329/10000 [23:30<08:28,  5.25step/s, loss=0.024165, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7330/10000 [23:30<08:29,  5.24step/s, loss=0.024165, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7330/10000 [23:30<08:29,  5.24step/s, loss=0.048545, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7331/10000 [23:30<08:28,  5.25step/s, loss=0.048545, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7331/10000 [23:30<08:28,  5.25step/s, loss=0.035409, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7332/10000 [23:30<08:27,  5.25step/s, loss=0.035409, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7332/10000 [23:30<08:27,  5.25step/s, loss=0.014521, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7333/10000 [23:30<08:27,  5.25step/s, loss=0.014521, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7333/10000 [23:30<08:27,  5.25step/s, loss=0.087420, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7334/10000 [23:31<08:26,  5.26step/s, loss=0.087420, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7334/10000 [23:31<08:26,  5.26step/s, loss=0.042080, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7335/10000 [23:31<08:26,  5.27step/s, loss=0.042080, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7335/10000 [23:31<08:26,  5.27step/s, loss=0.062752, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7336/10000 [23:31<08:26,  5.26step/s, loss=0.062752, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7336/10000 [23:31<08:26,  5.26step/s, loss=0.032515, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7337/10000 [23:31<08:28,  5.24step/s, loss=0.032515, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7337/10000 [23:31<08:28,  5.24step/s, loss=0.040768, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7338/10000 [23:31<08:28,  5.24step/s, loss=0.040768, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7338/10000 [23:31<08:28,  5.24step/s, loss=0.023319, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7339/10000 [23:32<08:29,  5.22step/s, loss=0.023319, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7339/10000 [23:32<08:29,  5.22step/s, loss=0.037836, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7340/10000 [23:32<08:31,  5.20step/s, loss=0.037836, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7340/10000 [23:32<08:31,  5.20step/s, loss=0.063535, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7341/10000 [23:32<08:29,  5.22step/s, loss=0.063535, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7341/10000 [23:32<08:29,  5.22step/s, loss=0.042444, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7342/10000 [23:32<08:27,  5.24step/s, loss=0.042444, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7342/10000 [23:32<08:27,  5.24step/s, loss=0.030622, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7343/10000 [23:32<08:24,  5.26step/s, loss=0.030622, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7343/10000 [23:32<08:24,  5.26step/s, loss=0.038423, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7344/10000 [23:32<08:24,  5.27step/s, loss=0.038423, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7344/10000 [23:32<08:24,  5.27step/s, loss=0.049415, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7345/10000 [23:33<08:25,  5.26step/s, loss=0.049415, elapsed=23.5min]

Entraînement:  73%|███████▎  | 7345/10000 [23:33<08:25,  5.26step/s, loss=0.019187, elapsed=23.6min]

Entraînement:  73%|███████▎  | 7346/10000 [23:33<08:24,  5.26step/s, loss=0.019187, elapsed=23.6min]

Entraînement:  73%|███████▎  | 7346/10000 [23:33<08:24,  5.26step/s, loss=0.027600, elapsed=23.6min]

Entraînement:  73%|███████▎  | 7347/10000 [23:33<08:24,  5.26step/s, loss=0.027600, elapsed=23.6min]

Entraînement:  73%|███████▎  | 7347/10000 [23:33<08:24,  5.26step/s, loss=0.087583, elapsed=23.6min]

Entraînement:  73%|███████▎  | 7348/10000 [23:33<08:23,  5.27step/s, loss=0.087583, elapsed=23.6min]

Entraînement:  73%|███████▎  | 7348/10000 [23:33<08:23,  5.27step/s, loss=0.029396, elapsed=23.6min]

Entraînement:  73%|███████▎  | 7349/10000 [23:33<08:22,  5.28step/s, loss=0.029396, elapsed=23.6min]

Entraînement:  73%|███████▎  | 7349/10000 [23:33<08:22,  5.28step/s, loss=0.028765, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7350/10000 [23:34<08:22,  5.28step/s, loss=0.028765, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7350/10000 [23:34<08:22,  5.28step/s, loss=0.028142, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7351/10000 [23:34<08:21,  5.28step/s, loss=0.028142, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7351/10000 [23:34<08:21,  5.28step/s, loss=0.039086, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7352/10000 [23:34<08:25,  5.24step/s, loss=0.039086, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7352/10000 [23:34<08:25,  5.24step/s, loss=0.020667, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7353/10000 [23:34<08:25,  5.24step/s, loss=0.020667, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7353/10000 [23:34<08:25,  5.24step/s, loss=0.026298, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7354/10000 [23:34<08:23,  5.26step/s, loss=0.026298, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7354/10000 [23:34<08:23,  5.26step/s, loss=0.063866, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7355/10000 [23:35<08:22,  5.26step/s, loss=0.063866, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7355/10000 [23:35<08:22,  5.26step/s, loss=0.022808, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7356/10000 [23:35<08:21,  5.27step/s, loss=0.022808, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7356/10000 [23:35<08:21,  5.27step/s, loss=0.059330, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7357/10000 [23:35<08:21,  5.27step/s, loss=0.059330, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7357/10000 [23:35<08:21,  5.27step/s, loss=0.027724, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7358/10000 [23:35<08:20,  5.27step/s, loss=0.027724, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7358/10000 [23:35<08:20,  5.27step/s, loss=0.046484, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7359/10000 [23:35<08:21,  5.27step/s, loss=0.046484, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7359/10000 [23:35<08:21,  5.27step/s, loss=0.089524, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7360/10000 [23:36<08:21,  5.26step/s, loss=0.089524, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7360/10000 [23:36<08:21,  5.26step/s, loss=0.016727, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7361/10000 [23:36<08:21,  5.26step/s, loss=0.016727, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7361/10000 [23:36<08:21,  5.26step/s, loss=0.034900, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7362/10000 [23:36<08:20,  5.27step/s, loss=0.034900, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7362/10000 [23:36<08:20,  5.27step/s, loss=0.032198, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7363/10000 [23:36<08:19,  5.28step/s, loss=0.032198, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7363/10000 [23:36<08:19,  5.28step/s, loss=0.021155, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7364/10000 [23:36<08:19,  5.28step/s, loss=0.021155, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7364/10000 [23:36<08:19,  5.28step/s, loss=0.043368, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7365/10000 [23:36<08:18,  5.29step/s, loss=0.043368, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7365/10000 [23:36<08:18,  5.29step/s, loss=0.105368, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7366/10000 [23:37<08:18,  5.28step/s, loss=0.105368, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7366/10000 [23:37<08:18,  5.28step/s, loss=0.075380, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7367/10000 [23:37<08:19,  5.28step/s, loss=0.075380, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7367/10000 [23:37<08:19,  5.28step/s, loss=0.028090, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7368/10000 [23:37<08:19,  5.27step/s, loss=0.028090, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7368/10000 [23:37<08:19,  5.27step/s, loss=0.024573, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7369/10000 [23:37<08:18,  5.28step/s, loss=0.024573, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7369/10000 [23:37<08:18,  5.28step/s, loss=0.023548, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7370/10000 [23:37<08:18,  5.28step/s, loss=0.023548, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7370/10000 [23:37<08:18,  5.28step/s, loss=0.056249, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7371/10000 [23:38<08:18,  5.27step/s, loss=0.056249, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7371/10000 [23:38<08:18,  5.27step/s, loss=0.048575, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7372/10000 [23:38<08:18,  5.28step/s, loss=0.048575, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7372/10000 [23:38<08:18,  5.28step/s, loss=0.051131, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7373/10000 [23:38<08:17,  5.28step/s, loss=0.051131, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7373/10000 [23:38<08:17,  5.28step/s, loss=0.053499, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7374/10000 [23:38<08:18,  5.27step/s, loss=0.053499, elapsed=23.6min]

Entraînement:  74%|███████▎  | 7374/10000 [23:38<08:18,  5.27step/s, loss=0.031785, elapsed=23.6min]

Entraînement:  74%|███████▍  | 7375/10000 [23:38<08:18,  5.27step/s, loss=0.031785, elapsed=23.6min]

Entraînement:  74%|███████▍  | 7375/10000 [23:38<08:18,  5.27step/s, loss=0.069040, elapsed=23.6min]

Entraînement:  74%|███████▍  | 7376/10000 [23:39<08:21,  5.23step/s, loss=0.069040, elapsed=23.6min]

Entraînement:  74%|███████▍  | 7376/10000 [23:39<08:21,  5.23step/s, loss=0.028526, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7377/10000 [23:39<08:19,  5.25step/s, loss=0.028526, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7377/10000 [23:39<08:19,  5.25step/s, loss=0.027437, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7378/10000 [23:39<08:18,  5.26step/s, loss=0.027437, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7378/10000 [23:39<08:18,  5.26step/s, loss=0.079425, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7379/10000 [23:39<08:17,  5.27step/s, loss=0.079425, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7379/10000 [23:39<08:17,  5.27step/s, loss=0.099342, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7380/10000 [23:39<08:16,  5.28step/s, loss=0.099342, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7380/10000 [23:39<08:16,  5.28step/s, loss=0.064082, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7381/10000 [23:40<08:15,  5.29step/s, loss=0.064082, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7381/10000 [23:40<08:15,  5.29step/s, loss=0.017409, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7382/10000 [23:40<08:15,  5.29step/s, loss=0.017409, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7382/10000 [23:40<08:15,  5.29step/s, loss=0.025011, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7383/10000 [23:40<08:16,  5.27step/s, loss=0.025011, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7383/10000 [23:40<08:16,  5.27step/s, loss=0.014028, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7384/10000 [23:40<08:16,  5.27step/s, loss=0.014028, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7384/10000 [23:40<08:16,  5.27step/s, loss=0.028477, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7385/10000 [23:40<08:16,  5.27step/s, loss=0.028477, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7385/10000 [23:40<08:16,  5.27step/s, loss=0.062406, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7386/10000 [23:40<08:16,  5.27step/s, loss=0.062406, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7386/10000 [23:40<08:16,  5.27step/s, loss=0.036505, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7387/10000 [23:41<08:18,  5.25step/s, loss=0.036505, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7387/10000 [23:41<08:18,  5.25step/s, loss=0.029142, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7388/10000 [23:41<08:16,  5.26step/s, loss=0.029142, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7388/10000 [23:41<08:16,  5.26step/s, loss=0.031659, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7389/10000 [23:41<08:15,  5.27step/s, loss=0.031659, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7389/10000 [23:41<08:15,  5.27step/s, loss=0.023751, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7390/10000 [23:41<08:16,  5.26step/s, loss=0.023751, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7390/10000 [23:41<08:16,  5.26step/s, loss=0.045938, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7391/10000 [23:41<08:15,  5.26step/s, loss=0.045938, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7391/10000 [23:41<08:15,  5.26step/s, loss=0.066023, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7392/10000 [23:42<08:15,  5.26step/s, loss=0.066023, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7392/10000 [23:42<08:15,  5.26step/s, loss=0.058773, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7393/10000 [23:42<08:14,  5.27step/s, loss=0.058773, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7393/10000 [23:42<08:14,  5.27step/s, loss=0.108046, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7394/10000 [23:42<08:14,  5.27step/s, loss=0.108046, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7394/10000 [23:42<08:14,  5.27step/s, loss=0.091708, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7395/10000 [23:42<08:14,  5.27step/s, loss=0.091708, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7395/10000 [23:42<08:14,  5.27step/s, loss=0.046057, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7396/10000 [23:42<08:13,  5.28step/s, loss=0.046057, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7396/10000 [23:42<08:13,  5.28step/s, loss=0.104594, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7397/10000 [23:43<08:12,  5.28step/s, loss=0.104594, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7397/10000 [23:43<08:12,  5.28step/s, loss=0.024461, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7398/10000 [23:43<08:14,  5.26step/s, loss=0.024461, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7398/10000 [23:43<08:14,  5.26step/s, loss=0.070666, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7399/10000 [23:43<08:13,  5.27step/s, loss=0.070666, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7399/10000 [23:43<08:13,  5.27step/s, loss=0.111525, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7400/10000 [23:43<08:13,  5.27step/s, loss=0.111525, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7400/10000 [23:43<08:13,  5.27step/s, loss=0.028669, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7400/10000 [23:43<08:13,  5.27step/s, loss=0.028669, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7401/10000 [23:43<08:19,  5.20step/s, loss=0.028669, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7401/10000 [23:43<08:19,  5.20step/s, loss=0.023760, elapsed=23.7min]

Step 7400/10000 | Train loss: 0.028669 | Elapsed: 23.7min | ETA: 8.3min

Entraînement:  74%|███████▍  | 7402/10000 [23:44<08:17,  5.23step/s, loss=0.023760, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7402/10000 [23:44<08:17,  5.23step/s, loss=0.065393, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7403/10000 [23:44<08:14,  5.25step/s, loss=0.065393, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7403/10000 [23:44<08:14,  5.25step/s, loss=0.074519, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7404/10000 [23:44<08:12,  5.27step/s, loss=0.074519, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7404/10000 [23:44<08:12,  5.27step/s, loss=0.022583, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7405/10000 [23:44<08:11,  5.28step/s, loss=0.022583, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7405/10000 [23:44<08:11,  5.28step/s, loss=0.117324, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7406/10000 [23:44<08:12,  5.26step/s, loss=0.117324, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7406/10000 [23:44<08:12,  5.26step/s, loss=0.044579, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7407/10000 [23:44<08:12,  5.27step/s, loss=0.044579, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7407/10000 [23:44<08:12,  5.27step/s, loss=0.037088, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7408/10000 [23:45<08:10,  5.28step/s, loss=0.037088, elapsed=23.7min]

Entraînement:  74%|███████▍  | 7408/10000 [23:45<08:10,  5.28step/s, loss=0.032808, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7409/10000 [23:45<08:11,  5.28step/s, loss=0.032808, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7409/10000 [23:45<08:11,  5.28step/s, loss=0.022719, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7410/10000 [23:45<08:10,  5.28step/s, loss=0.022719, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7410/10000 [23:45<08:10,  5.28step/s, loss=0.034275, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7411/10000 [23:45<08:10,  5.28step/s, loss=0.034275, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7411/10000 [23:45<08:10,  5.28step/s, loss=0.036381, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7412/10000 [23:45<08:09,  5.28step/s, loss=0.036381, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7412/10000 [23:45<08:09,  5.28step/s, loss=0.037103, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7413/10000 [23:46<08:10,  5.27step/s, loss=0.037103, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7413/10000 [23:46<08:10,  5.27step/s, loss=0.020186, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7414/10000 [23:46<08:11,  5.26step/s, loss=0.020186, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7414/10000 [23:46<08:11,  5.26step/s, loss=0.022072, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7415/10000 [23:46<08:11,  5.26step/s, loss=0.022072, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7415/10000 [23:46<08:11,  5.26step/s, loss=0.024945, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7416/10000 [23:46<08:10,  5.27step/s, loss=0.024945, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7416/10000 [23:46<08:10,  5.27step/s, loss=0.044633, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7417/10000 [23:46<08:10,  5.27step/s, loss=0.044633, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7417/10000 [23:46<08:10,  5.27step/s, loss=0.030795, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7418/10000 [23:47<08:10,  5.27step/s, loss=0.030795, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7418/10000 [23:47<08:10,  5.27step/s, loss=0.065566, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7419/10000 [23:47<08:09,  5.28step/s, loss=0.065566, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7419/10000 [23:47<08:09,  5.28step/s, loss=0.032976, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7420/10000 [23:47<08:09,  5.27step/s, loss=0.032976, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7420/10000 [23:47<08:09,  5.27step/s, loss=0.026971, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7421/10000 [23:47<08:09,  5.26step/s, loss=0.026971, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7421/10000 [23:47<08:09,  5.26step/s, loss=0.027248, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7422/10000 [23:47<08:09,  5.27step/s, loss=0.027248, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7422/10000 [23:47<08:09,  5.27step/s, loss=0.054983, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7423/10000 [23:47<08:09,  5.26step/s, loss=0.054983, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7423/10000 [23:47<08:09,  5.26step/s, loss=0.032389, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7424/10000 [23:48<08:08,  5.27step/s, loss=0.032389, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7424/10000 [23:48<08:08,  5.27step/s, loss=0.060897, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7425/10000 [23:48<08:08,  5.27step/s, loss=0.060897, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7425/10000 [23:48<08:08,  5.27step/s, loss=0.176154, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7426/10000 [23:48<08:08,  5.27step/s, loss=0.176154, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7426/10000 [23:48<08:08,  5.27step/s, loss=0.052949, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7427/10000 [23:48<08:07,  5.27step/s, loss=0.052949, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7427/10000 [23:48<08:07,  5.27step/s, loss=0.030014, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7428/10000 [23:48<08:07,  5.28step/s, loss=0.030014, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7428/10000 [23:48<08:07,  5.28step/s, loss=0.039844, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7429/10000 [23:49<08:07,  5.28step/s, loss=0.039844, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7429/10000 [23:49<08:07,  5.28step/s, loss=0.023315, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7430/10000 [23:49<08:07,  5.27step/s, loss=0.023315, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7430/10000 [23:49<08:07,  5.27step/s, loss=0.029725, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7431/10000 [23:49<08:06,  5.28step/s, loss=0.029725, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7431/10000 [23:49<08:06,  5.28step/s, loss=0.033528, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7432/10000 [23:49<08:06,  5.28step/s, loss=0.033528, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7432/10000 [23:49<08:06,  5.28step/s, loss=0.044863, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7433/10000 [23:49<08:06,  5.28step/s, loss=0.044863, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7433/10000 [23:49<08:06,  5.28step/s, loss=0.044508, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7434/10000 [23:50<08:05,  5.29step/s, loss=0.044508, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7434/10000 [23:50<08:05,  5.29step/s, loss=0.071021, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7435/10000 [23:50<08:04,  5.29step/s, loss=0.071021, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7435/10000 [23:50<08:04,  5.29step/s, loss=0.027654, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7436/10000 [23:50<08:04,  5.29step/s, loss=0.027654, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7436/10000 [23:50<08:04,  5.29step/s, loss=0.092954, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7437/10000 [23:50<08:05,  5.28step/s, loss=0.092954, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7437/10000 [23:50<08:05,  5.28step/s, loss=0.029565, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7438/10000 [23:50<08:05,  5.28step/s, loss=0.029565, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7438/10000 [23:50<08:05,  5.28step/s, loss=0.033002, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7439/10000 [23:51<08:04,  5.29step/s, loss=0.033002, elapsed=23.8min]

Entraînement:  74%|███████▍  | 7439/10000 [23:51<08:04,  5.29step/s, loss=0.032674, elapsed=23.9min]

Entraînement:  74%|███████▍  | 7440/10000 [23:51<08:04,  5.29step/s, loss=0.032674, elapsed=23.9min]

Entraînement:  74%|███████▍  | 7440/10000 [23:51<08:04,  5.29step/s, loss=0.057166, elapsed=23.9min]

Entraînement:  74%|███████▍  | 7441/10000 [23:51<08:03,  5.29step/s, loss=0.057166, elapsed=23.9min]

Entraînement:  74%|███████▍  | 7441/10000 [23:51<08:03,  5.29step/s, loss=0.025386, elapsed=23.9min]

Entraînement:  74%|███████▍  | 7442/10000 [23:51<08:03,  5.29step/s, loss=0.025386, elapsed=23.9min]

Entraînement:  74%|███████▍  | 7442/10000 [23:51<08:03,  5.29step/s, loss=0.034322, elapsed=23.9min]

Entraînement:  74%|███████▍  | 7443/10000 [23:51<08:03,  5.29step/s, loss=0.034322, elapsed=23.9min]

Entraînement:  74%|███████▍  | 7443/10000 [23:51<08:03,  5.29step/s, loss=0.053045, elapsed=23.9min]

Entraînement:  74%|███████▍  | 7444/10000 [23:51<08:03,  5.29step/s, loss=0.053045, elapsed=23.9min]

Entraînement:  74%|███████▍  | 7444/10000 [23:51<08:03,  5.29step/s, loss=0.058913, elapsed=23.9min]

Entraînement:  74%|███████▍  | 7445/10000 [23:52<08:03,  5.29step/s, loss=0.058913, elapsed=23.9min]

Entraînement:  74%|███████▍  | 7445/10000 [23:52<08:03,  5.29step/s, loss=0.021865, elapsed=23.9min]

Entraînement:  74%|███████▍  | 7446/10000 [23:52<08:03,  5.28step/s, loss=0.021865, elapsed=23.9min]

Entraînement:  74%|███████▍  | 7446/10000 [23:52<08:03,  5.28step/s, loss=0.035875, elapsed=23.9min]

Entraînement:  74%|███████▍  | 7447/10000 [23:52<08:02,  5.29step/s, loss=0.035875, elapsed=23.9min]

Entraînement:  74%|███████▍  | 7447/10000 [23:52<08:02,  5.29step/s, loss=0.024155, elapsed=23.9min]

Entraînement:  74%|███████▍  | 7448/10000 [23:52<08:03,  5.28step/s, loss=0.024155, elapsed=23.9min]

Entraînement:  74%|███████▍  | 7448/10000 [23:52<08:03,  5.28step/s, loss=0.044488, elapsed=23.9min]

Entraînement:  74%|███████▍  | 7449/10000 [23:52<08:03,  5.28step/s, loss=0.044488, elapsed=23.9min]

Entraînement:  74%|███████▍  | 7449/10000 [23:52<08:03,  5.28step/s, loss=0.035376, elapsed=23.9min]

Entraînement:  74%|███████▍  | 7450/10000 [23:53<08:02,  5.29step/s, loss=0.035376, elapsed=23.9min]

Entraînement:  74%|███████▍  | 7450/10000 [23:53<08:02,  5.29step/s, loss=0.035042, elapsed=23.9min]

Entraînement:  75%|███████▍  | 7451/10000 [23:53<08:01,  5.29step/s, loss=0.035042, elapsed=23.9min]

Entraînement:  75%|███████▍  | 7451/10000 [23:53<08:01,  5.29step/s, loss=0.055269, elapsed=23.9min]

Entraînement:  75%|███████▍  | 7452/10000 [23:53<08:02,  5.29step/s, loss=0.055269, elapsed=23.9min]

Entraînement:  75%|███████▍  | 7452/10000 [23:53<08:02,  5.29step/s, loss=0.026687, elapsed=23.9min]

Entraînement:  75%|███████▍  | 7453/10000 [23:53<08:02,  5.27step/s, loss=0.026687, elapsed=23.9min]

Entraînement:  75%|███████▍  | 7453/10000 [23:53<08:02,  5.27step/s, loss=0.036186, elapsed=23.9min]

Entraînement:  75%|███████▍  | 7454/10000 [23:53<08:02,  5.27step/s, loss=0.036186, elapsed=23.9min]

Entraînement:  75%|███████▍  | 7454/10000 [23:53<08:02,  5.27step/s, loss=0.041109, elapsed=23.9min]

Entraînement:  75%|███████▍  | 7455/10000 [23:54<08:02,  5.27step/s, loss=0.041109, elapsed=23.9min]

Entraînement:  75%|███████▍  | 7455/10000 [23:54<08:02,  5.27step/s, loss=0.030111, elapsed=23.9min]

Entraînement:  75%|███████▍  | 7456/10000 [23:54<08:02,  5.27step/s, loss=0.030111, elapsed=23.9min]

Entraînement:  75%|███████▍  | 7456/10000 [23:54<08:02,  5.27step/s, loss=0.057611, elapsed=23.9min]

Entraînement:  75%|███████▍  | 7457/10000 [23:54<08:02,  5.27step/s, loss=0.057611, elapsed=23.9min]

Entraînement:  75%|███████▍  | 7457/10000 [23:54<08:02,  5.27step/s, loss=0.067024, elapsed=23.9min]

Entraînement:  75%|███████▍  | 7458/10000 [23:54<08:01,  5.28step/s, loss=0.067024, elapsed=23.9min]

Entraînement:  75%|███████▍  | 7458/10000 [23:54<08:01,  5.28step/s, loss=0.087641, elapsed=23.9min]

Entraînement:  75%|███████▍  | 7459/10000 [23:54<08:00,  5.29step/s, loss=0.087641, elapsed=23.9min]

Entraînement:  75%|███████▍  | 7459/10000 [23:54<08:00,  5.29step/s, loss=0.022734, elapsed=23.9min]

Entraînement:  75%|███████▍  | 7460/10000 [23:54<08:00,  5.29step/s, loss=0.022734, elapsed=23.9min]

Entraînement:  75%|███████▍  | 7460/10000 [23:54<08:00,  5.29step/s, loss=0.034811, elapsed=23.9min]

Entraînement:  75%|███████▍  | 7461/10000 [23:55<08:00,  5.29step/s, loss=0.034811, elapsed=23.9min]

Entraînement:  75%|███████▍  | 7461/10000 [23:55<08:00,  5.29step/s, loss=0.064015, elapsed=23.9min]

Entraînement:  75%|███████▍  | 7462/10000 [23:55<08:00,  5.29step/s, loss=0.064015, elapsed=23.9min]

Entraînement:  75%|███████▍  | 7462/10000 [23:55<08:00,  5.29step/s, loss=0.025969, elapsed=23.9min]

Entraînement:  75%|███████▍  | 7463/10000 [23:55<07:59,  5.29step/s, loss=0.025969, elapsed=23.9min]

Entraînement:  75%|███████▍  | 7463/10000 [23:55<07:59,  5.29step/s, loss=0.024755, elapsed=23.9min]

Entraînement:  75%|███████▍  | 7464/10000 [23:55<07:58,  5.30step/s, loss=0.024755, elapsed=23.9min]

Entraînement:  75%|███████▍  | 7464/10000 [23:55<07:58,  5.30step/s, loss=0.025865, elapsed=23.9min]

Entraînement:  75%|███████▍  | 7465/10000 [23:55<07:59,  5.29step/s, loss=0.025865, elapsed=23.9min]

Entraînement:  75%|███████▍  | 7465/10000 [23:55<07:59,  5.29step/s, loss=0.044517, elapsed=23.9min]

Entraînement:  75%|███████▍  | 7466/10000 [23:56<07:58,  5.30step/s, loss=0.044517, elapsed=23.9min]

Entraînement:  75%|███████▍  | 7466/10000 [23:56<07:58,  5.30step/s, loss=0.027285, elapsed=23.9min]

Entraînement:  75%|███████▍  | 7467/10000 [23:56<07:57,  5.31step/s, loss=0.027285, elapsed=23.9min]

Entraînement:  75%|███████▍  | 7467/10000 [23:56<07:57,  5.31step/s, loss=0.047143, elapsed=23.9min]

Entraînement:  75%|███████▍  | 7468/10000 [23:56<07:57,  5.30step/s, loss=0.047143, elapsed=23.9min]

Entraînement:  75%|███████▍  | 7468/10000 [23:56<07:57,  5.30step/s, loss=0.032981, elapsed=23.9min]

Entraînement:  75%|███████▍  | 7469/10000 [23:56<07:58,  5.29step/s, loss=0.032981, elapsed=23.9min]

Entraînement:  75%|███████▍  | 7469/10000 [23:56<07:58,  5.29step/s, loss=0.054595, elapsed=23.9min]

Entraînement:  75%|███████▍  | 7470/10000 [23:56<07:58,  5.29step/s, loss=0.054595, elapsed=23.9min]

Entraînement:  75%|███████▍  | 7470/10000 [23:56<07:58,  5.29step/s, loss=0.024003, elapsed=23.9min]

Entraînement:  75%|███████▍  | 7471/10000 [23:57<07:57,  5.29step/s, loss=0.024003, elapsed=23.9min]

Entraînement:  75%|███████▍  | 7471/10000 [23:57<07:57,  5.29step/s, loss=0.028898, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7472/10000 [23:57<07:56,  5.30step/s, loss=0.028898, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7472/10000 [23:57<07:56,  5.30step/s, loss=0.073552, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7473/10000 [23:57<07:56,  5.30step/s, loss=0.073552, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7473/10000 [23:57<07:56,  5.30step/s, loss=0.060867, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7474/10000 [23:57<07:56,  5.30step/s, loss=0.060867, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7474/10000 [23:57<07:56,  5.30step/s, loss=0.037060, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7475/10000 [23:57<07:56,  5.30step/s, loss=0.037060, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7475/10000 [23:57<07:56,  5.30step/s, loss=0.105814, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7476/10000 [23:58<07:56,  5.30step/s, loss=0.105814, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7476/10000 [23:58<07:56,  5.30step/s, loss=0.023300, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7477/10000 [23:58<07:55,  5.30step/s, loss=0.023300, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7477/10000 [23:58<07:55,  5.30step/s, loss=0.015411, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7478/10000 [23:58<07:56,  5.30step/s, loss=0.015411, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7478/10000 [23:58<07:56,  5.30step/s, loss=0.076911, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7479/10000 [23:58<07:55,  5.30step/s, loss=0.076911, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7479/10000 [23:58<07:55,  5.30step/s, loss=0.030234, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7480/10000 [23:58<07:56,  5.29step/s, loss=0.030234, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7480/10000 [23:58<07:56,  5.29step/s, loss=0.070194, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7481/10000 [23:58<07:56,  5.29step/s, loss=0.070194, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7481/10000 [23:58<07:56,  5.29step/s, loss=0.057217, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7482/10000 [23:59<07:56,  5.29step/s, loss=0.057217, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7482/10000 [23:59<07:56,  5.29step/s, loss=0.076341, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7483/10000 [23:59<07:55,  5.29step/s, loss=0.076341, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7483/10000 [23:59<07:55,  5.29step/s, loss=0.057996, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7484/10000 [23:59<07:55,  5.29step/s, loss=0.057996, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7484/10000 [23:59<07:55,  5.29step/s, loss=0.039705, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7485/10000 [23:59<07:55,  5.28step/s, loss=0.039705, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7485/10000 [23:59<07:55,  5.28step/s, loss=0.027534, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7486/10000 [23:59<07:56,  5.28step/s, loss=0.027534, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7486/10000 [23:59<07:56,  5.28step/s, loss=0.027907, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7487/10000 [24:00<07:55,  5.29step/s, loss=0.027907, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7487/10000 [24:00<07:55,  5.29step/s, loss=0.043965, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7488/10000 [24:00<07:55,  5.28step/s, loss=0.043965, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7488/10000 [24:00<07:55,  5.28step/s, loss=0.034658, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7489/10000 [24:00<07:55,  5.29step/s, loss=0.034658, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7489/10000 [24:00<07:55,  5.29step/s, loss=0.039198, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7490/10000 [24:00<07:54,  5.29step/s, loss=0.039198, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7490/10000 [24:00<07:54,  5.29step/s, loss=0.036677, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7491/10000 [24:00<07:54,  5.29step/s, loss=0.036677, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7491/10000 [24:00<07:54,  5.29step/s, loss=0.031506, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7492/10000 [24:01<07:54,  5.28step/s, loss=0.031506, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7492/10000 [24:01<07:54,  5.28step/s, loss=0.054167, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7493/10000 [24:01<07:53,  5.29step/s, loss=0.054167, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7493/10000 [24:01<07:53,  5.29step/s, loss=0.024257, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7494/10000 [24:01<07:54,  5.29step/s, loss=0.024257, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7494/10000 [24:01<07:54,  5.29step/s, loss=0.132201, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7495/10000 [24:01<07:53,  5.29step/s, loss=0.132201, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7495/10000 [24:01<07:53,  5.29step/s, loss=0.019798, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7496/10000 [24:01<07:53,  5.29step/s, loss=0.019798, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7496/10000 [24:01<07:53,  5.29step/s, loss=0.036526, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7497/10000 [24:01<07:53,  5.29step/s, loss=0.036526, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7497/10000 [24:01<07:53,  5.29step/s, loss=0.035891, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7498/10000 [24:02<07:52,  5.30step/s, loss=0.035891, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7498/10000 [24:02<07:52,  5.30step/s, loss=0.037095, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7499/10000 [24:02<07:51,  5.30step/s, loss=0.037095, elapsed=24.0min]

Entraînement:  75%|███████▍  | 7499/10000 [24:02<07:51,  5.30step/s, loss=0.053957, elapsed=24.0min]

Entraînement:  75%|███████▌  | 7500/10000 [24:02<07:52,  5.29step/s, loss=0.053957, elapsed=24.0min]

Entraînement:  75%|███████▌  | 7500/10000 [24:02<07:52,  5.29step/s, loss=0.052982, elapsed=24.0min]

Entraînement:  75%|███████▌  | 7500/10000 [24:02<07:52,  5.29step/s, loss=0.052982, elapsed=24.0min]

Entraînement:  75%|███████▌  | 7501/10000 [24:02<07:57,  5.23step/s, loss=0.052982, elapsed=24.0min]

Entraînement:  75%|███████▌  | 7501/10000 [24:02<07:57,  5.23step/s, loss=0.074504, elapsed=24.0min]

Step 7500/10000 | Train loss: 0.052982 | Elapsed: 24.0min | ETA: 8.0min

Entraînement:  75%|███████▌  | 7502/10000 [24:02<07:55,  5.25step/s, loss=0.074504, elapsed=24.0min]

Entraînement:  75%|███████▌  | 7502/10000 [24:02<07:55,  5.25step/s, loss=0.034705, elapsed=24.0min]

Entraînement:  75%|███████▌  | 7503/10000 [24:03<07:54,  5.26step/s, loss=0.034705, elapsed=24.0min]

Entraînement:  75%|███████▌  | 7503/10000 [24:03<07:54,  5.26step/s, loss=0.064530, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7504/10000 [24:03<07:53,  5.27step/s, loss=0.064530, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7504/10000 [24:03<07:53,  5.27step/s, loss=0.115040, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7505/10000 [24:03<07:52,  5.28step/s, loss=0.115040, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7505/10000 [24:03<07:52,  5.28step/s, loss=0.031526, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7506/10000 [24:03<07:51,  5.29step/s, loss=0.031526, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7506/10000 [24:03<07:51,  5.29step/s, loss=0.018675, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7507/10000 [24:03<07:56,  5.23step/s, loss=0.018675, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7507/10000 [24:03<07:56,  5.23step/s, loss=0.055238, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7508/10000 [24:04<07:57,  5.22step/s, loss=0.055238, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7508/10000 [24:04<07:57,  5.22step/s, loss=0.054311, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7509/10000 [24:04<07:55,  5.24step/s, loss=0.054311, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7509/10000 [24:04<07:55,  5.24step/s, loss=0.016572, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7510/10000 [24:04<07:54,  5.25step/s, loss=0.016572, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7510/10000 [24:04<07:54,  5.25step/s, loss=0.039692, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7511/10000 [24:04<07:52,  5.27step/s, loss=0.039692, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7511/10000 [24:04<07:52,  5.27step/s, loss=0.028398, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7512/10000 [24:04<07:51,  5.28step/s, loss=0.028398, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7512/10000 [24:04<07:51,  5.28step/s, loss=0.075333, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7513/10000 [24:05<07:48,  5.31step/s, loss=0.075333, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7513/10000 [24:05<07:48,  5.31step/s, loss=0.025853, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7514/10000 [24:05<07:46,  5.33step/s, loss=0.025853, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7514/10000 [24:05<07:46,  5.33step/s, loss=0.070701, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7515/10000 [24:05<07:47,  5.32step/s, loss=0.070701, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7515/10000 [24:05<07:47,  5.32step/s, loss=0.027394, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7516/10000 [24:05<07:47,  5.31step/s, loss=0.027394, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7516/10000 [24:05<07:47,  5.31step/s, loss=0.060899, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7517/10000 [24:05<07:47,  5.31step/s, loss=0.060899, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7517/10000 [24:05<07:47,  5.31step/s, loss=0.142002, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7518/10000 [24:05<07:48,  5.30step/s, loss=0.142002, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7518/10000 [24:05<07:48,  5.30step/s, loss=0.029876, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7519/10000 [24:06<07:48,  5.30step/s, loss=0.029876, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7519/10000 [24:06<07:48,  5.30step/s, loss=0.034981, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7520/10000 [24:06<07:47,  5.30step/s, loss=0.034981, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7520/10000 [24:06<07:47,  5.30step/s, loss=0.032326, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7521/10000 [24:06<07:47,  5.31step/s, loss=0.032326, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7521/10000 [24:06<07:47,  5.31step/s, loss=0.021045, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7522/10000 [24:06<07:47,  5.30step/s, loss=0.021045, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7522/10000 [24:06<07:47,  5.30step/s, loss=0.073936, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7523/10000 [24:06<07:47,  5.30step/s, loss=0.073936, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7523/10000 [24:06<07:47,  5.30step/s, loss=0.047164, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7524/10000 [24:07<07:46,  5.31step/s, loss=0.047164, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7524/10000 [24:07<07:46,  5.31step/s, loss=0.023785, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7525/10000 [24:07<07:45,  5.31step/s, loss=0.023785, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7525/10000 [24:07<07:45,  5.31step/s, loss=0.058129, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7526/10000 [24:07<07:46,  5.30step/s, loss=0.058129, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7526/10000 [24:07<07:46,  5.30step/s, loss=0.021120, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7527/10000 [24:07<07:47,  5.29step/s, loss=0.021120, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7527/10000 [24:07<07:47,  5.29step/s, loss=0.086164, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7528/10000 [24:07<07:45,  5.30step/s, loss=0.086164, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7528/10000 [24:07<07:45,  5.30step/s, loss=0.038260, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7529/10000 [24:08<07:47,  5.29step/s, loss=0.038260, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7529/10000 [24:08<07:47,  5.29step/s, loss=0.065385, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7530/10000 [24:08<07:46,  5.29step/s, loss=0.065385, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7530/10000 [24:08<07:46,  5.29step/s, loss=0.024403, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7531/10000 [24:08<07:46,  5.29step/s, loss=0.024403, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7531/10000 [24:08<07:46,  5.29step/s, loss=0.034569, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7532/10000 [24:08<07:45,  5.30step/s, loss=0.034569, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7532/10000 [24:08<07:45,  5.30step/s, loss=0.022331, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7533/10000 [24:08<07:46,  5.28step/s, loss=0.022331, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7533/10000 [24:08<07:46,  5.28step/s, loss=0.036263, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7534/10000 [24:08<07:46,  5.28step/s, loss=0.036263, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7534/10000 [24:08<07:46,  5.28step/s, loss=0.094197, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7535/10000 [24:09<07:46,  5.28step/s, loss=0.094197, elapsed=24.1min]

Entraînement:  75%|███████▌  | 7535/10000 [24:09<07:46,  5.28step/s, loss=0.022325, elapsed=24.2min]

Entraînement:  75%|███████▌  | 7536/10000 [24:09<07:47,  5.28step/s, loss=0.022325, elapsed=24.2min]

Entraînement:  75%|███████▌  | 7536/10000 [24:09<07:47,  5.28step/s, loss=0.029599, elapsed=24.2min]

Entraînement:  75%|███████▌  | 7537/10000 [24:09<07:44,  5.30step/s, loss=0.029599, elapsed=24.2min]

Entraînement:  75%|███████▌  | 7537/10000 [24:09<07:44,  5.30step/s, loss=0.076512, elapsed=24.2min]

Entraînement:  75%|███████▌  | 7538/10000 [24:09<07:46,  5.28step/s, loss=0.076512, elapsed=24.2min]

Entraînement:  75%|███████▌  | 7538/10000 [24:09<07:46,  5.28step/s, loss=0.045343, elapsed=24.2min]

Entraînement:  75%|███████▌  | 7539/10000 [24:09<07:46,  5.28step/s, loss=0.045343, elapsed=24.2min]

Entraînement:  75%|███████▌  | 7539/10000 [24:09<07:46,  5.28step/s, loss=0.025090, elapsed=24.2min]

Entraînement:  75%|███████▌  | 7540/10000 [24:10<07:45,  5.29step/s, loss=0.025090, elapsed=24.2min]

Entraînement:  75%|███████▌  | 7540/10000 [24:10<07:45,  5.29step/s, loss=0.052663, elapsed=24.2min]

Entraînement:  75%|███████▌  | 7541/10000 [24:10<07:45,  5.28step/s, loss=0.052663, elapsed=24.2min]

Entraînement:  75%|███████▌  | 7541/10000 [24:10<07:45,  5.28step/s, loss=0.023294, elapsed=24.2min]

Entraînement:  75%|███████▌  | 7542/10000 [24:10<07:45,  5.28step/s, loss=0.023294, elapsed=24.2min]

Entraînement:  75%|███████▌  | 7542/10000 [24:10<07:45,  5.28step/s, loss=0.055992, elapsed=24.2min]

Entraînement:  75%|███████▌  | 7543/10000 [24:10<07:45,  5.28step/s, loss=0.055992, elapsed=24.2min]

Entraînement:  75%|███████▌  | 7543/10000 [24:10<07:45,  5.28step/s, loss=0.029986, elapsed=24.2min]

Entraînement:  75%|███████▌  | 7544/10000 [24:10<07:44,  5.29step/s, loss=0.029986, elapsed=24.2min]

Entraînement:  75%|███████▌  | 7544/10000 [24:10<07:44,  5.29step/s, loss=0.082487, elapsed=24.2min]

Entraînement:  75%|███████▌  | 7545/10000 [24:11<07:45,  5.28step/s, loss=0.082487, elapsed=24.2min]

Entraînement:  75%|███████▌  | 7545/10000 [24:11<07:45,  5.28step/s, loss=0.044522, elapsed=24.2min]

Entraînement:  75%|███████▌  | 7546/10000 [24:11<07:44,  5.28step/s, loss=0.044522, elapsed=24.2min]

Entraînement:  75%|███████▌  | 7546/10000 [24:11<07:44,  5.28step/s, loss=0.060180, elapsed=24.2min]

Entraînement:  75%|███████▌  | 7547/10000 [24:11<07:44,  5.29step/s, loss=0.060180, elapsed=24.2min]

Entraînement:  75%|███████▌  | 7547/10000 [24:11<07:44,  5.29step/s, loss=0.064228, elapsed=24.2min]

Entraînement:  75%|███████▌  | 7548/10000 [24:11<07:43,  5.29step/s, loss=0.064228, elapsed=24.2min]

Entraînement:  75%|███████▌  | 7548/10000 [24:11<07:43,  5.29step/s, loss=0.028576, elapsed=24.2min]

Entraînement:  75%|███████▌  | 7549/10000 [24:11<07:42,  5.30step/s, loss=0.028576, elapsed=24.2min]

Entraînement:  75%|███████▌  | 7549/10000 [24:11<07:42,  5.30step/s, loss=0.027097, elapsed=24.2min]

Entraînement:  76%|███████▌  | 7550/10000 [24:12<07:43,  5.29step/s, loss=0.027097, elapsed=24.2min]

Entraînement:  76%|███████▌  | 7550/10000 [24:12<07:43,  5.29step/s, loss=0.026364, elapsed=24.2min]

Entraînement:  76%|███████▌  | 7551/10000 [24:12<07:43,  5.29step/s, loss=0.026364, elapsed=24.2min]

Entraînement:  76%|███████▌  | 7551/10000 [24:12<07:43,  5.29step/s, loss=0.061656, elapsed=24.2min]

Entraînement:  76%|███████▌  | 7552/10000 [24:12<07:42,  5.29step/s, loss=0.061656, elapsed=24.2min]

Entraînement:  76%|███████▌  | 7552/10000 [24:12<07:42,  5.29step/s, loss=0.030837, elapsed=24.2min]

Entraînement:  76%|███████▌  | 7553/10000 [24:12<07:42,  5.29step/s, loss=0.030837, elapsed=24.2min]

Entraînement:  76%|███████▌  | 7553/10000 [24:12<07:42,  5.29step/s, loss=0.025945, elapsed=24.2min]

Entraînement:  76%|███████▌  | 7554/10000 [24:12<07:43,  5.27step/s, loss=0.025945, elapsed=24.2min]

Entraînement:  76%|███████▌  | 7554/10000 [24:12<07:43,  5.27step/s, loss=0.033515, elapsed=24.2min]

Entraînement:  76%|███████▌  | 7555/10000 [24:12<07:44,  5.26step/s, loss=0.033515, elapsed=24.2min]

Entraînement:  76%|███████▌  | 7555/10000 [24:12<07:44,  5.26step/s, loss=0.068707, elapsed=24.2min]

Entraînement:  76%|███████▌  | 7556/10000 [24:13<07:43,  5.27step/s, loss=0.068707, elapsed=24.2min]

Entraînement:  76%|███████▌  | 7556/10000 [24:13<07:43,  5.27step/s, loss=0.029340, elapsed=24.2min]

Entraînement:  76%|███████▌  | 7557/10000 [24:13<07:41,  5.29step/s, loss=0.029340, elapsed=24.2min]

Entraînement:  76%|███████▌  | 7557/10000 [24:13<07:41,  5.29step/s, loss=0.033431, elapsed=24.2min]

Entraînement:  76%|███████▌  | 7558/10000 [24:13<07:42,  5.28step/s, loss=0.033431, elapsed=24.2min]

Entraînement:  76%|███████▌  | 7558/10000 [24:13<07:42,  5.28step/s, loss=0.093854, elapsed=24.2min]

Entraînement:  76%|███████▌  | 7559/10000 [24:13<07:42,  5.28step/s, loss=0.093854, elapsed=24.2min]

Entraînement:  76%|███████▌  | 7559/10000 [24:13<07:42,  5.28step/s, loss=0.032354, elapsed=24.2min]

Entraînement:  76%|███████▌  | 7560/10000 [24:13<07:41,  5.28step/s, loss=0.032354, elapsed=24.2min]

Entraînement:  76%|███████▌  | 7560/10000 [24:13<07:41,  5.28step/s, loss=0.158681, elapsed=24.2min]

Entraînement:  76%|███████▌  | 7561/10000 [24:14<07:45,  5.24step/s, loss=0.158681, elapsed=24.2min]

Entraînement:  76%|███████▌  | 7561/10000 [24:14<07:45,  5.24step/s, loss=0.033507, elapsed=24.2min]

Entraînement:  76%|███████▌  | 7562/10000 [24:14<07:44,  5.24step/s, loss=0.033507, elapsed=24.2min]

Entraînement:  76%|███████▌  | 7562/10000 [24:14<07:44,  5.24step/s, loss=0.023366, elapsed=24.2min]

Entraînement:  76%|███████▌  | 7563/10000 [24:14<07:47,  5.22step/s, loss=0.023366, elapsed=24.2min]

Entraînement:  76%|███████▌  | 7563/10000 [24:14<07:47,  5.22step/s, loss=0.054520, elapsed=24.2min]

Entraînement:  76%|███████▌  | 7564/10000 [24:14<07:44,  5.24step/s, loss=0.054520, elapsed=24.2min]

Entraînement:  76%|███████▌  | 7564/10000 [24:14<07:44,  5.24step/s, loss=0.028476, elapsed=24.2min]

Entraînement:  76%|███████▌  | 7565/10000 [24:14<07:45,  5.24step/s, loss=0.028476, elapsed=24.2min]

Entraînement:  76%|███████▌  | 7565/10000 [24:14<07:45,  5.24step/s, loss=0.018137, elapsed=24.2min]

Entraînement:  76%|███████▌  | 7566/10000 [24:15<07:44,  5.25step/s, loss=0.018137, elapsed=24.2min]

Entraînement:  76%|███████▌  | 7566/10000 [24:15<07:44,  5.25step/s, loss=0.097906, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7567/10000 [24:15<07:43,  5.25step/s, loss=0.097906, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7567/10000 [24:15<07:43,  5.25step/s, loss=0.020769, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7568/10000 [24:15<07:39,  5.29step/s, loss=0.020769, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7568/10000 [24:15<07:39,  5.29step/s, loss=0.153941, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7569/10000 [24:15<07:36,  5.32step/s, loss=0.153941, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7569/10000 [24:15<07:36,  5.32step/s, loss=0.029582, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7570/10000 [24:15<07:39,  5.29step/s, loss=0.029582, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7570/10000 [24:15<07:39,  5.29step/s, loss=0.042096, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7571/10000 [24:15<07:39,  5.28step/s, loss=0.042096, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7571/10000 [24:15<07:39,  5.28step/s, loss=0.043095, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7572/10000 [24:16<07:42,  5.25step/s, loss=0.043095, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7572/10000 [24:16<07:42,  5.25step/s, loss=0.026828, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7573/10000 [24:16<07:40,  5.27step/s, loss=0.026828, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7573/10000 [24:16<07:40,  5.27step/s, loss=0.032636, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7574/10000 [24:16<07:40,  5.26step/s, loss=0.032636, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7574/10000 [24:16<07:40,  5.26step/s, loss=0.071387, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7575/10000 [24:16<07:40,  5.27step/s, loss=0.071387, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7575/10000 [24:16<07:40,  5.27step/s, loss=0.020789, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7576/10000 [24:16<07:39,  5.28step/s, loss=0.020789, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7576/10000 [24:16<07:39,  5.28step/s, loss=0.038454, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7577/10000 [24:17<07:38,  5.28step/s, loss=0.038454, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7577/10000 [24:17<07:38,  5.28step/s, loss=0.068298, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7578/10000 [24:17<07:38,  5.28step/s, loss=0.068298, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7578/10000 [24:17<07:38,  5.28step/s, loss=0.053564, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7579/10000 [24:17<07:38,  5.28step/s, loss=0.053564, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7579/10000 [24:17<07:38,  5.28step/s, loss=0.020829, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7580/10000 [24:17<07:39,  5.27step/s, loss=0.020829, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7580/10000 [24:17<07:39,  5.27step/s, loss=0.034851, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7581/10000 [24:17<07:43,  5.22step/s, loss=0.034851, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7581/10000 [24:17<07:43,  5.22step/s, loss=0.044675, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7582/10000 [24:18<07:42,  5.23step/s, loss=0.044675, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7582/10000 [24:18<07:42,  5.23step/s, loss=0.027888, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7583/10000 [24:18<07:39,  5.25step/s, loss=0.027888, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7583/10000 [24:18<07:39,  5.25step/s, loss=0.060853, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7584/10000 [24:18<07:38,  5.27step/s, loss=0.060853, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7584/10000 [24:18<07:38,  5.27step/s, loss=0.028173, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7585/10000 [24:18<07:37,  5.27step/s, loss=0.028173, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7585/10000 [24:18<07:37,  5.27step/s, loss=0.092966, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7586/10000 [24:18<07:37,  5.27step/s, loss=0.092966, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7586/10000 [24:18<07:37,  5.27step/s, loss=0.060244, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7587/10000 [24:19<07:44,  5.20step/s, loss=0.060244, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7587/10000 [24:19<07:44,  5.20step/s, loss=0.038919, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7588/10000 [24:19<07:42,  5.21step/s, loss=0.038919, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7588/10000 [24:19<07:42,  5.21step/s, loss=0.033764, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7589/10000 [24:19<07:40,  5.23step/s, loss=0.033764, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7589/10000 [24:19<07:40,  5.23step/s, loss=0.080791, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7590/10000 [24:19<07:39,  5.25step/s, loss=0.080791, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7590/10000 [24:19<07:39,  5.25step/s, loss=0.064016, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7591/10000 [24:19<07:37,  5.26step/s, loss=0.064016, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7591/10000 [24:19<07:37,  5.26step/s, loss=0.034426, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7592/10000 [24:19<07:36,  5.27step/s, loss=0.034426, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7592/10000 [24:19<07:36,  5.27step/s, loss=0.020172, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7593/10000 [24:20<07:37,  5.26step/s, loss=0.020172, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7593/10000 [24:20<07:37,  5.26step/s, loss=0.030177, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7594/10000 [24:20<07:37,  5.26step/s, loss=0.030177, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7594/10000 [24:20<07:37,  5.26step/s, loss=0.023082, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7595/10000 [24:20<07:37,  5.25step/s, loss=0.023082, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7595/10000 [24:20<07:37,  5.25step/s, loss=0.017419, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7596/10000 [24:20<07:36,  5.27step/s, loss=0.017419, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7596/10000 [24:20<07:36,  5.27step/s, loss=0.096305, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7597/10000 [24:20<07:36,  5.27step/s, loss=0.096305, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7597/10000 [24:20<07:36,  5.27step/s, loss=0.020333, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7598/10000 [24:21<07:35,  5.27step/s, loss=0.020333, elapsed=24.3min]

Entraînement:  76%|███████▌  | 7598/10000 [24:21<07:35,  5.27step/s, loss=0.075172, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7599/10000 [24:21<07:35,  5.28step/s, loss=0.075172, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7599/10000 [24:21<07:35,  5.28step/s, loss=0.039792, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7600/10000 [24:21<07:35,  5.27step/s, loss=0.039792, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7600/10000 [24:21<07:35,  5.27step/s, loss=0.031619, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7600/10000 [24:21<07:35,  5.27step/s, loss=0.031619, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7601/10000 [24:21<07:38,  5.23step/s, loss=0.031619, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7601/10000 [24:21<07:38,  5.23step/s, loss=0.028852, elapsed=24.4min]

Step 7600/10000 | Train loss: 0.031619 | Elapsed: 24.4min | ETA: 7.7min

Entraînement:  76%|███████▌  | 7602/10000 [24:21<07:37,  5.24step/s, loss=0.028852, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7602/10000 [24:21<07:37,  5.24step/s, loss=0.037079, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7603/10000 [24:22<07:36,  5.26step/s, loss=0.037079, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7603/10000 [24:22<07:36,  5.26step/s, loss=0.069409, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7604/10000 [24:22<07:35,  5.26step/s, loss=0.069409, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7604/10000 [24:22<07:35,  5.26step/s, loss=0.048654, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7605/10000 [24:22<07:34,  5.27step/s, loss=0.048654, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7605/10000 [24:22<07:34,  5.27step/s, loss=0.094757, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7606/10000 [24:22<07:33,  5.27step/s, loss=0.094757, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7606/10000 [24:22<07:33,  5.27step/s, loss=0.038947, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7607/10000 [24:22<07:33,  5.28step/s, loss=0.038947, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7607/10000 [24:22<07:33,  5.28step/s, loss=0.028476, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7608/10000 [24:23<07:33,  5.27step/s, loss=0.028476, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7608/10000 [24:23<07:33,  5.27step/s, loss=0.065313, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7609/10000 [24:23<07:34,  5.26step/s, loss=0.065313, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7609/10000 [24:23<07:34,  5.26step/s, loss=0.061632, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7610/10000 [24:23<07:33,  5.27step/s, loss=0.061632, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7610/10000 [24:23<07:33,  5.27step/s, loss=0.015837, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7611/10000 [24:23<07:32,  5.28step/s, loss=0.015837, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7611/10000 [24:23<07:32,  5.28step/s, loss=0.039277, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7612/10000 [24:23<07:32,  5.27step/s, loss=0.039277, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7612/10000 [24:23<07:32,  5.27step/s, loss=0.034284, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7613/10000 [24:23<07:33,  5.26step/s, loss=0.034284, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7613/10000 [24:23<07:33,  5.26step/s, loss=0.037152, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7614/10000 [24:24<07:32,  5.27step/s, loss=0.037152, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7614/10000 [24:24<07:32,  5.27step/s, loss=0.034502, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7615/10000 [24:24<07:31,  5.28step/s, loss=0.034502, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7615/10000 [24:24<07:31,  5.28step/s, loss=0.039136, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7616/10000 [24:24<07:32,  5.27step/s, loss=0.039136, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7616/10000 [24:24<07:32,  5.27step/s, loss=0.036122, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7617/10000 [24:24<07:32,  5.26step/s, loss=0.036122, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7617/10000 [24:24<07:32,  5.26step/s, loss=0.022522, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7618/10000 [24:24<07:33,  5.26step/s, loss=0.022522, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7618/10000 [24:24<07:33,  5.26step/s, loss=0.038547, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7619/10000 [24:25<07:32,  5.26step/s, loss=0.038547, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7619/10000 [24:25<07:32,  5.26step/s, loss=0.027903, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7620/10000 [24:25<07:31,  5.27step/s, loss=0.027903, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7620/10000 [24:25<07:31,  5.27step/s, loss=0.044294, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7621/10000 [24:25<07:31,  5.27step/s, loss=0.044294, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7621/10000 [24:25<07:31,  5.27step/s, loss=0.021911, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7622/10000 [24:25<07:29,  5.29step/s, loss=0.021911, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7622/10000 [24:25<07:29,  5.29step/s, loss=0.034219, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7623/10000 [24:25<07:29,  5.28step/s, loss=0.034219, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7623/10000 [24:25<07:29,  5.28step/s, loss=0.038438, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7624/10000 [24:26<07:30,  5.27step/s, loss=0.038438, elapsed=24.4min]

Entraînement:  76%|███████▌  | 7624/10000 [24:26<07:30,  5.27step/s, loss=0.075500, elapsed=24.4min]

Entraînement:  76%|███████▋  | 7625/10000 [24:26<07:29,  5.28step/s, loss=0.075500, elapsed=24.4min]

Entraînement:  76%|███████▋  | 7625/10000 [24:26<07:29,  5.28step/s, loss=0.033688, elapsed=24.4min]

Entraînement:  76%|███████▋  | 7626/10000 [24:26<07:30,  5.27step/s, loss=0.033688, elapsed=24.4min]

Entraînement:  76%|███████▋  | 7626/10000 [24:26<07:30,  5.27step/s, loss=0.048098, elapsed=24.4min]

Entraînement:  76%|███████▋  | 7627/10000 [24:26<07:29,  5.28step/s, loss=0.048098, elapsed=24.4min]

Entraînement:  76%|███████▋  | 7627/10000 [24:26<07:29,  5.28step/s, loss=0.025972, elapsed=24.4min]

Entraînement:  76%|███████▋  | 7628/10000 [24:26<07:29,  5.28step/s, loss=0.025972, elapsed=24.4min]

Entraînement:  76%|███████▋  | 7628/10000 [24:26<07:29,  5.28step/s, loss=0.038473, elapsed=24.4min]

Entraînement:  76%|███████▋  | 7629/10000 [24:27<07:28,  5.28step/s, loss=0.038473, elapsed=24.4min]

Entraînement:  76%|███████▋  | 7629/10000 [24:27<07:28,  5.28step/s, loss=0.016393, elapsed=24.5min]

Entraînement:  76%|███████▋  | 7630/10000 [24:27<07:28,  5.29step/s, loss=0.016393, elapsed=24.5min]

Entraînement:  76%|███████▋  | 7630/10000 [24:27<07:28,  5.29step/s, loss=0.021681, elapsed=24.5min]

Entraînement:  76%|███████▋  | 7631/10000 [24:27<07:28,  5.28step/s, loss=0.021681, elapsed=24.5min]

Entraînement:  76%|███████▋  | 7631/10000 [24:27<07:28,  5.28step/s, loss=0.066852, elapsed=24.5min]

Entraînement:  76%|███████▋  | 7632/10000 [24:27<07:28,  5.28step/s, loss=0.066852, elapsed=24.5min]

Entraînement:  76%|███████▋  | 7632/10000 [24:27<07:28,  5.28step/s, loss=0.061748, elapsed=24.5min]

Entraînement:  76%|███████▋  | 7633/10000 [24:27<07:28,  5.27step/s, loss=0.061748, elapsed=24.5min]

Entraînement:  76%|███████▋  | 7633/10000 [24:27<07:28,  5.27step/s, loss=0.034447, elapsed=24.5min]

Entraînement:  76%|███████▋  | 7634/10000 [24:27<07:28,  5.28step/s, loss=0.034447, elapsed=24.5min]

Entraînement:  76%|███████▋  | 7634/10000 [24:27<07:28,  5.28step/s, loss=0.054921, elapsed=24.5min]

Entraînement:  76%|███████▋  | 7635/10000 [24:28<07:31,  5.24step/s, loss=0.054921, elapsed=24.5min]

Entraînement:  76%|███████▋  | 7635/10000 [24:28<07:31,  5.24step/s, loss=0.096808, elapsed=24.5min]

Entraînement:  76%|███████▋  | 7636/10000 [24:28<07:29,  5.26step/s, loss=0.096808, elapsed=24.5min]

Entraînement:  76%|███████▋  | 7636/10000 [24:28<07:29,  5.26step/s, loss=0.040522, elapsed=24.5min]

Entraînement:  76%|███████▋  | 7637/10000 [24:28<07:29,  5.26step/s, loss=0.040522, elapsed=24.5min]

Entraînement:  76%|███████▋  | 7637/10000 [24:28<07:29,  5.26step/s, loss=0.063822, elapsed=24.5min]

Entraînement:  76%|███████▋  | 7638/10000 [24:28<07:28,  5.26step/s, loss=0.063822, elapsed=24.5min]

Entraînement:  76%|███████▋  | 7638/10000 [24:28<07:28,  5.26step/s, loss=0.039116, elapsed=24.5min]

Entraînement:  76%|███████▋  | 7639/10000 [24:28<07:28,  5.26step/s, loss=0.039116, elapsed=24.5min]

Entraînement:  76%|███████▋  | 7639/10000 [24:28<07:28,  5.26step/s, loss=0.035241, elapsed=24.5min]

Entraînement:  76%|███████▋  | 7640/10000 [24:29<07:32,  5.22step/s, loss=0.035241, elapsed=24.5min]

Entraînement:  76%|███████▋  | 7640/10000 [24:29<07:32,  5.22step/s, loss=0.043150, elapsed=24.5min]

Entraînement:  76%|███████▋  | 7641/10000 [24:29<07:31,  5.23step/s, loss=0.043150, elapsed=24.5min]

Entraînement:  76%|███████▋  | 7641/10000 [24:29<07:31,  5.23step/s, loss=0.112198, elapsed=24.5min]

Entraînement:  76%|███████▋  | 7642/10000 [24:29<07:29,  5.25step/s, loss=0.112198, elapsed=24.5min]

Entraînement:  76%|███████▋  | 7642/10000 [24:29<07:29,  5.25step/s, loss=0.017586, elapsed=24.5min]

Entraînement:  76%|███████▋  | 7643/10000 [24:29<07:28,  5.25step/s, loss=0.017586, elapsed=24.5min]

Entraînement:  76%|███████▋  | 7643/10000 [24:29<07:28,  5.25step/s, loss=0.080174, elapsed=24.5min]

Entraînement:  76%|███████▋  | 7644/10000 [24:29<07:28,  5.25step/s, loss=0.080174, elapsed=24.5min]

Entraînement:  76%|███████▋  | 7644/10000 [24:29<07:28,  5.25step/s, loss=0.042038, elapsed=24.5min]

Entraînement:  76%|███████▋  | 7645/10000 [24:30<07:28,  5.25step/s, loss=0.042038, elapsed=24.5min]

Entraînement:  76%|███████▋  | 7645/10000 [24:30<07:28,  5.25step/s, loss=0.032320, elapsed=24.5min]

Entraînement:  76%|███████▋  | 7646/10000 [24:30<07:28,  5.25step/s, loss=0.032320, elapsed=24.5min]

Entraînement:  76%|███████▋  | 7646/10000 [24:30<07:28,  5.25step/s, loss=0.027509, elapsed=24.5min]

Entraînement:  76%|███████▋  | 7647/10000 [24:30<07:27,  5.26step/s, loss=0.027509, elapsed=24.5min]

Entraînement:  76%|███████▋  | 7647/10000 [24:30<07:27,  5.26step/s, loss=0.037535, elapsed=24.5min]

Entraînement:  76%|███████▋  | 7648/10000 [24:30<07:27,  5.25step/s, loss=0.037535, elapsed=24.5min]

Entraînement:  76%|███████▋  | 7648/10000 [24:30<07:27,  5.25step/s, loss=0.057922, elapsed=24.5min]

Entraînement:  76%|███████▋  | 7649/10000 [24:30<07:27,  5.26step/s, loss=0.057922, elapsed=24.5min]

Entraînement:  76%|███████▋  | 7649/10000 [24:30<07:27,  5.26step/s, loss=0.053338, elapsed=24.5min]

Entraînement:  76%|███████▋  | 7650/10000 [24:31<07:27,  5.26step/s, loss=0.053338, elapsed=24.5min]

Entraînement:  76%|███████▋  | 7650/10000 [24:31<07:27,  5.26step/s, loss=0.029342, elapsed=24.5min]

Entraînement:  77%|███████▋  | 7651/10000 [24:31<07:26,  5.26step/s, loss=0.029342, elapsed=24.5min]

Entraînement:  77%|███████▋  | 7651/10000 [24:31<07:26,  5.26step/s, loss=0.025386, elapsed=24.5min]

Entraînement:  77%|███████▋  | 7652/10000 [24:31<07:26,  5.26step/s, loss=0.025386, elapsed=24.5min]

Entraînement:  77%|███████▋  | 7652/10000 [24:31<07:26,  5.26step/s, loss=0.048568, elapsed=24.5min]

Entraînement:  77%|███████▋  | 7653/10000 [24:31<07:26,  5.26step/s, loss=0.048568, elapsed=24.5min]

Entraînement:  77%|███████▋  | 7653/10000 [24:31<07:26,  5.26step/s, loss=0.057207, elapsed=24.5min]

Entraînement:  77%|███████▋  | 7654/10000 [24:31<07:27,  5.25step/s, loss=0.057207, elapsed=24.5min]

Entraînement:  77%|███████▋  | 7654/10000 [24:31<07:27,  5.25step/s, loss=0.064769, elapsed=24.5min]

Entraînement:  77%|███████▋  | 7655/10000 [24:31<07:27,  5.24step/s, loss=0.064769, elapsed=24.5min]

Entraînement:  77%|███████▋  | 7655/10000 [24:31<07:27,  5.24step/s, loss=0.038703, elapsed=24.5min]

Entraînement:  77%|███████▋  | 7656/10000 [24:32<07:32,  5.18step/s, loss=0.038703, elapsed=24.5min]

Entraînement:  77%|███████▋  | 7656/10000 [24:32<07:32,  5.18step/s, loss=0.044492, elapsed=24.5min]

Entraînement:  77%|███████▋  | 7657/10000 [24:32<07:29,  5.21step/s, loss=0.044492, elapsed=24.5min]

Entraînement:  77%|███████▋  | 7657/10000 [24:32<07:29,  5.21step/s, loss=0.028702, elapsed=24.5min]

Entraînement:  77%|███████▋  | 7658/10000 [24:32<07:29,  5.21step/s, loss=0.028702, elapsed=24.5min]

Entraînement:  77%|███████▋  | 7658/10000 [24:32<07:29,  5.21step/s, loss=0.041948, elapsed=24.5min]

Entraînement:  77%|███████▋  | 7659/10000 [24:32<07:29,  5.21step/s, loss=0.041948, elapsed=24.5min]

Entraînement:  77%|███████▋  | 7659/10000 [24:32<07:29,  5.21step/s, loss=0.025991, elapsed=24.5min]

Entraînement:  77%|███████▋  | 7660/10000 [24:32<07:27,  5.22step/s, loss=0.025991, elapsed=24.5min]

Entraînement:  77%|███████▋  | 7660/10000 [24:32<07:27,  5.22step/s, loss=0.069124, elapsed=24.5min]

Entraînement:  77%|███████▋  | 7661/10000 [24:33<07:26,  5.24step/s, loss=0.069124, elapsed=24.5min]

Entraînement:  77%|███████▋  | 7661/10000 [24:33<07:26,  5.24step/s, loss=0.037895, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7662/10000 [24:33<07:26,  5.24step/s, loss=0.037895, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7662/10000 [24:33<07:26,  5.24step/s, loss=0.037480, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7663/10000 [24:33<07:24,  5.26step/s, loss=0.037480, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7663/10000 [24:33<07:24,  5.26step/s, loss=0.022840, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7664/10000 [24:33<07:24,  5.25step/s, loss=0.022840, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7664/10000 [24:33<07:24,  5.25step/s, loss=0.032679, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7665/10000 [24:33<07:23,  5.26step/s, loss=0.032679, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7665/10000 [24:33<07:23,  5.26step/s, loss=0.026514, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7666/10000 [24:34<07:23,  5.26step/s, loss=0.026514, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7666/10000 [24:34<07:23,  5.26step/s, loss=0.033285, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7667/10000 [24:34<07:23,  5.27step/s, loss=0.033285, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7667/10000 [24:34<07:23,  5.27step/s, loss=0.040228, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7668/10000 [24:34<07:22,  5.27step/s, loss=0.040228, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7668/10000 [24:34<07:22,  5.27step/s, loss=0.069278, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7669/10000 [24:34<07:23,  5.26step/s, loss=0.069278, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7669/10000 [24:34<07:23,  5.26step/s, loss=0.044112, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7670/10000 [24:34<07:23,  5.26step/s, loss=0.044112, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7670/10000 [24:34<07:23,  5.26step/s, loss=0.064036, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7671/10000 [24:35<07:23,  5.25step/s, loss=0.064036, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7671/10000 [24:35<07:23,  5.25step/s, loss=0.116721, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7672/10000 [24:35<07:22,  5.26step/s, loss=0.116721, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7672/10000 [24:35<07:22,  5.26step/s, loss=0.020202, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7673/10000 [24:35<07:22,  5.26step/s, loss=0.020202, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7673/10000 [24:35<07:22,  5.26step/s, loss=0.022918, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7674/10000 [24:35<07:21,  5.27step/s, loss=0.022918, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7674/10000 [24:35<07:21,  5.27step/s, loss=0.079635, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7675/10000 [24:35<07:20,  5.27step/s, loss=0.079635, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7675/10000 [24:35<07:20,  5.27step/s, loss=0.085228, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7676/10000 [24:35<07:21,  5.27step/s, loss=0.085228, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7676/10000 [24:35<07:21,  5.27step/s, loss=0.052829, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7677/10000 [24:36<07:20,  5.27step/s, loss=0.052829, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7677/10000 [24:36<07:20,  5.27step/s, loss=0.032113, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7678/10000 [24:36<07:21,  5.27step/s, loss=0.032113, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7678/10000 [24:36<07:21,  5.27step/s, loss=0.066748, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7679/10000 [24:36<07:20,  5.27step/s, loss=0.066748, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7679/10000 [24:36<07:20,  5.27step/s, loss=0.021636, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7680/10000 [24:36<07:20,  5.27step/s, loss=0.021636, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7680/10000 [24:36<07:20,  5.27step/s, loss=0.021975, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7681/10000 [24:36<07:19,  5.27step/s, loss=0.021975, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7681/10000 [24:36<07:19,  5.27step/s, loss=0.016430, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7682/10000 [24:37<07:19,  5.28step/s, loss=0.016430, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7682/10000 [24:37<07:19,  5.28step/s, loss=0.030541, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7683/10000 [24:37<07:18,  5.28step/s, loss=0.030541, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7683/10000 [24:37<07:18,  5.28step/s, loss=0.040493, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7684/10000 [24:37<07:18,  5.28step/s, loss=0.040493, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7684/10000 [24:37<07:18,  5.28step/s, loss=0.057518, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7685/10000 [24:37<07:18,  5.27step/s, loss=0.057518, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7685/10000 [24:37<07:18,  5.27step/s, loss=0.054310, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7686/10000 [24:37<07:18,  5.28step/s, loss=0.054310, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7686/10000 [24:37<07:18,  5.28step/s, loss=0.052579, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7687/10000 [24:38<07:18,  5.27step/s, loss=0.052579, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7687/10000 [24:38<07:18,  5.27step/s, loss=0.034012, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7688/10000 [24:38<07:18,  5.27step/s, loss=0.034012, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7688/10000 [24:38<07:18,  5.27step/s, loss=0.028674, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7689/10000 [24:38<07:18,  5.27step/s, loss=0.028674, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7689/10000 [24:38<07:18,  5.27step/s, loss=0.052544, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7690/10000 [24:38<07:18,  5.27step/s, loss=0.052544, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7690/10000 [24:38<07:18,  5.27step/s, loss=0.017995, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7691/10000 [24:38<07:17,  5.28step/s, loss=0.017995, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7691/10000 [24:38<07:17,  5.28step/s, loss=0.078571, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7692/10000 [24:38<07:18,  5.26step/s, loss=0.078571, elapsed=24.6min]

Entraînement:  77%|███████▋  | 7692/10000 [24:38<07:18,  5.26step/s, loss=0.061314, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7693/10000 [24:39<07:18,  5.26step/s, loss=0.061314, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7693/10000 [24:39<07:18,  5.26step/s, loss=0.035158, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7694/10000 [24:39<07:18,  5.26step/s, loss=0.035158, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7694/10000 [24:39<07:18,  5.26step/s, loss=0.076783, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7695/10000 [24:39<07:17,  5.27step/s, loss=0.076783, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7695/10000 [24:39<07:17,  5.27step/s, loss=0.030241, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7696/10000 [24:39<07:17,  5.27step/s, loss=0.030241, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7696/10000 [24:39<07:17,  5.27step/s, loss=0.048160, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7697/10000 [24:39<07:17,  5.27step/s, loss=0.048160, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7697/10000 [24:39<07:17,  5.27step/s, loss=0.081467, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7698/10000 [24:40<07:16,  5.28step/s, loss=0.081467, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7698/10000 [24:40<07:16,  5.28step/s, loss=0.057692, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7699/10000 [24:40<07:16,  5.27step/s, loss=0.057692, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7699/10000 [24:40<07:16,  5.27step/s, loss=0.047593, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7700/10000 [24:40<07:16,  5.27step/s, loss=0.047593, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7700/10000 [24:40<07:16,  5.27step/s, loss=0.048997, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7700/10000 [24:40<07:16,  5.27step/s, loss=0.048997, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7701/10000 [24:40<07:20,  5.22step/s, loss=0.048997, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7701/10000 [24:40<07:20,  5.22step/s, loss=0.086283, elapsed=24.7min]

Step 7700/10000 | Train loss: 0.048997 | Elapsed: 24.7min | ETA: 7.4min

Entraînement:  77%|███████▋  | 7702/10000 [24:40<07:18,  5.25step/s, loss=0.086283, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7702/10000 [24:40<07:18,  5.25step/s, loss=0.035402, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7703/10000 [24:41<07:16,  5.26step/s, loss=0.035402, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7703/10000 [24:41<07:16,  5.26step/s, loss=0.032202, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7704/10000 [24:41<07:15,  5.27step/s, loss=0.032202, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7704/10000 [24:41<07:15,  5.27step/s, loss=0.067640, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7705/10000 [24:41<07:15,  5.27step/s, loss=0.067640, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7705/10000 [24:41<07:15,  5.27step/s, loss=0.023855, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7706/10000 [24:41<07:14,  5.28step/s, loss=0.023855, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7706/10000 [24:41<07:14,  5.28step/s, loss=0.034394, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7707/10000 [24:41<07:14,  5.27step/s, loss=0.034394, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7707/10000 [24:41<07:14,  5.27step/s, loss=0.032250, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7708/10000 [24:42<07:15,  5.26step/s, loss=0.032250, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7708/10000 [24:42<07:15,  5.26step/s, loss=0.041299, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7709/10000 [24:42<07:15,  5.26step/s, loss=0.041299, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7709/10000 [24:42<07:15,  5.26step/s, loss=0.052598, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7710/10000 [24:42<07:14,  5.27step/s, loss=0.052598, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7710/10000 [24:42<07:14,  5.27step/s, loss=0.070902, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7711/10000 [24:42<07:14,  5.27step/s, loss=0.070902, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7711/10000 [24:42<07:14,  5.27step/s, loss=0.054806, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7712/10000 [24:42<07:14,  5.27step/s, loss=0.054806, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7712/10000 [24:42<07:14,  5.27step/s, loss=0.017635, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7713/10000 [24:42<07:13,  5.27step/s, loss=0.017635, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7713/10000 [24:42<07:13,  5.27step/s, loss=0.046722, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7714/10000 [24:43<07:13,  5.27step/s, loss=0.046722, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7714/10000 [24:43<07:13,  5.27step/s, loss=0.040361, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7715/10000 [24:43<07:13,  5.27step/s, loss=0.040361, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7715/10000 [24:43<07:13,  5.27step/s, loss=0.036803, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7716/10000 [24:43<07:13,  5.27step/s, loss=0.036803, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7716/10000 [24:43<07:13,  5.27step/s, loss=0.031847, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7717/10000 [24:43<07:13,  5.27step/s, loss=0.031847, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7717/10000 [24:43<07:13,  5.27step/s, loss=0.028533, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7718/10000 [24:43<07:11,  5.29step/s, loss=0.028533, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7718/10000 [24:43<07:11,  5.29step/s, loss=0.026164, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7719/10000 [24:44<07:12,  5.28step/s, loss=0.026164, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7719/10000 [24:44<07:12,  5.28step/s, loss=0.028252, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7720/10000 [24:44<07:11,  5.28step/s, loss=0.028252, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7720/10000 [24:44<07:11,  5.28step/s, loss=0.086142, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7721/10000 [24:44<07:10,  5.29step/s, loss=0.086142, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7721/10000 [24:44<07:10,  5.29step/s, loss=0.071118, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7722/10000 [24:44<07:10,  5.29step/s, loss=0.071118, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7722/10000 [24:44<07:10,  5.29step/s, loss=0.042163, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7723/10000 [24:44<07:10,  5.28step/s, loss=0.042163, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7723/10000 [24:44<07:10,  5.28step/s, loss=0.023982, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7724/10000 [24:45<07:11,  5.28step/s, loss=0.023982, elapsed=24.7min]

Entraînement:  77%|███████▋  | 7724/10000 [24:45<07:11,  5.28step/s, loss=0.046118, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7725/10000 [24:45<07:10,  5.28step/s, loss=0.046118, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7725/10000 [24:45<07:10,  5.28step/s, loss=0.023271, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7726/10000 [24:45<07:10,  5.28step/s, loss=0.023271, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7726/10000 [24:45<07:10,  5.28step/s, loss=0.039306, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7727/10000 [24:45<07:10,  5.28step/s, loss=0.039306, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7727/10000 [24:45<07:10,  5.28step/s, loss=0.034593, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7728/10000 [24:45<07:10,  5.28step/s, loss=0.034593, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7728/10000 [24:45<07:10,  5.28step/s, loss=0.063993, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7729/10000 [24:46<07:09,  5.28step/s, loss=0.063993, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7729/10000 [24:46<07:09,  5.28step/s, loss=0.034848, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7730/10000 [24:46<07:09,  5.28step/s, loss=0.034848, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7730/10000 [24:46<07:09,  5.28step/s, loss=0.028237, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7731/10000 [24:46<07:11,  5.26step/s, loss=0.028237, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7731/10000 [24:46<07:11,  5.26step/s, loss=0.034676, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7732/10000 [24:46<07:10,  5.27step/s, loss=0.034676, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7732/10000 [24:46<07:10,  5.27step/s, loss=0.101592, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7733/10000 [24:46<07:10,  5.27step/s, loss=0.101592, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7733/10000 [24:46<07:10,  5.27step/s, loss=0.032448, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7734/10000 [24:46<07:09,  5.28step/s, loss=0.032448, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7734/10000 [24:46<07:09,  5.28step/s, loss=0.024247, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7735/10000 [24:47<07:09,  5.28step/s, loss=0.024247, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7735/10000 [24:47<07:09,  5.28step/s, loss=0.034489, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7736/10000 [24:47<07:08,  5.28step/s, loss=0.034489, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7736/10000 [24:47<07:08,  5.28step/s, loss=0.036674, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7737/10000 [24:47<07:08,  5.29step/s, loss=0.036674, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7737/10000 [24:47<07:08,  5.29step/s, loss=0.027168, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7738/10000 [24:47<07:08,  5.27step/s, loss=0.027168, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7738/10000 [24:47<07:08,  5.27step/s, loss=0.033241, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7739/10000 [24:47<07:09,  5.27step/s, loss=0.033241, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7739/10000 [24:47<07:09,  5.27step/s, loss=0.044073, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7740/10000 [24:48<07:09,  5.26step/s, loss=0.044073, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7740/10000 [24:48<07:09,  5.26step/s, loss=0.145473, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7741/10000 [24:48<07:08,  5.27step/s, loss=0.145473, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7741/10000 [24:48<07:08,  5.27step/s, loss=0.038588, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7742/10000 [24:48<07:07,  5.28step/s, loss=0.038588, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7742/10000 [24:48<07:07,  5.28step/s, loss=0.034427, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7743/10000 [24:48<07:07,  5.28step/s, loss=0.034427, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7743/10000 [24:48<07:07,  5.28step/s, loss=0.040541, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7744/10000 [24:48<07:06,  5.28step/s, loss=0.040541, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7744/10000 [24:48<07:06,  5.28step/s, loss=0.084975, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7745/10000 [24:49<07:08,  5.26step/s, loss=0.084975, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7745/10000 [24:49<07:08,  5.26step/s, loss=0.095826, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7746/10000 [24:49<07:08,  5.26step/s, loss=0.095826, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7746/10000 [24:49<07:08,  5.26step/s, loss=0.029670, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7747/10000 [24:49<07:07,  5.27step/s, loss=0.029670, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7747/10000 [24:49<07:07,  5.27step/s, loss=0.022051, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7748/10000 [24:49<07:07,  5.27step/s, loss=0.022051, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7748/10000 [24:49<07:07,  5.27step/s, loss=0.039600, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7749/10000 [24:49<07:07,  5.27step/s, loss=0.039600, elapsed=24.8min]

Entraînement:  77%|███████▋  | 7749/10000 [24:49<07:07,  5.27step/s, loss=0.042761, elapsed=24.8min]

Entraînement:  78%|███████▊  | 7750/10000 [24:49<07:06,  5.27step/s, loss=0.042761, elapsed=24.8min]

Entraînement:  78%|███████▊  | 7750/10000 [24:50<07:06,  5.27step/s, loss=0.046800, elapsed=24.8min]

Entraînement:  78%|███████▊  | 7751/10000 [24:50<07:06,  5.28step/s, loss=0.046800, elapsed=24.8min]

Entraînement:  78%|███████▊  | 7751/10000 [24:50<07:06,  5.28step/s, loss=0.066438, elapsed=24.8min]

Entraînement:  78%|███████▊  | 7752/10000 [24:50<07:05,  5.28step/s, loss=0.066438, elapsed=24.8min]

Entraînement:  78%|███████▊  | 7752/10000 [24:50<07:05,  5.28step/s, loss=0.042297, elapsed=24.8min]

Entraînement:  78%|███████▊  | 7753/10000 [24:50<07:05,  5.28step/s, loss=0.042297, elapsed=24.8min]

Entraînement:  78%|███████▊  | 7753/10000 [24:50<07:05,  5.28step/s, loss=0.066046, elapsed=24.8min]

Entraînement:  78%|███████▊  | 7754/10000 [24:50<07:09,  5.23step/s, loss=0.066046, elapsed=24.8min]

Entraînement:  78%|███████▊  | 7754/10000 [24:50<07:09,  5.23step/s, loss=0.053205, elapsed=24.8min]

Entraînement:  78%|███████▊  | 7755/10000 [24:50<07:08,  5.24step/s, loss=0.053205, elapsed=24.8min]

Entraînement:  78%|███████▊  | 7755/10000 [24:50<07:08,  5.24step/s, loss=0.036705, elapsed=24.8min]

Entraînement:  78%|███████▊  | 7756/10000 [24:51<07:07,  5.25step/s, loss=0.036705, elapsed=24.8min]

Entraînement:  78%|███████▊  | 7756/10000 [24:51<07:07,  5.25step/s, loss=0.023224, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7757/10000 [24:51<07:05,  5.27step/s, loss=0.023224, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7757/10000 [24:51<07:05,  5.27step/s, loss=0.076355, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7758/10000 [24:51<07:05,  5.27step/s, loss=0.076355, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7758/10000 [24:51<07:05,  5.27step/s, loss=0.100985, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7759/10000 [24:51<07:04,  5.28step/s, loss=0.100985, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7759/10000 [24:51<07:04,  5.28step/s, loss=0.026179, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7760/10000 [24:51<07:03,  5.29step/s, loss=0.026179, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7760/10000 [24:51<07:03,  5.29step/s, loss=0.046687, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7761/10000 [24:52<07:05,  5.26step/s, loss=0.046687, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7761/10000 [24:52<07:05,  5.26step/s, loss=0.075508, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7762/10000 [24:52<07:05,  5.27step/s, loss=0.075508, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7762/10000 [24:52<07:05,  5.27step/s, loss=0.025529, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7763/10000 [24:52<07:04,  5.27step/s, loss=0.025529, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7763/10000 [24:52<07:04,  5.27step/s, loss=0.015165, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7764/10000 [24:52<07:04,  5.27step/s, loss=0.015165, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7764/10000 [24:52<07:04,  5.27step/s, loss=0.060016, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7765/10000 [24:52<07:04,  5.26step/s, loss=0.060016, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7765/10000 [24:52<07:04,  5.26step/s, loss=0.047594, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7766/10000 [24:53<07:03,  5.27step/s, loss=0.047594, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7766/10000 [24:53<07:03,  5.27step/s, loss=0.028798, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7767/10000 [24:53<07:03,  5.28step/s, loss=0.028798, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7767/10000 [24:53<07:03,  5.28step/s, loss=0.023028, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7768/10000 [24:53<07:02,  5.28step/s, loss=0.023028, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7768/10000 [24:53<07:02,  5.28step/s, loss=0.029862, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7769/10000 [24:53<07:03,  5.27step/s, loss=0.029862, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7769/10000 [24:53<07:03,  5.27step/s, loss=0.020447, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7770/10000 [24:53<07:03,  5.26step/s, loss=0.020447, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7770/10000 [24:53<07:03,  5.26step/s, loss=0.066816, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7771/10000 [24:53<07:03,  5.26step/s, loss=0.066816, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7771/10000 [24:53<07:03,  5.26step/s, loss=0.023177, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7772/10000 [24:54<07:03,  5.26step/s, loss=0.023177, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7772/10000 [24:54<07:03,  5.26step/s, loss=0.032002, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7773/10000 [24:54<07:03,  5.25step/s, loss=0.032002, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7773/10000 [24:54<07:03,  5.25step/s, loss=0.016803, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7774/10000 [24:54<07:03,  5.25step/s, loss=0.016803, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7774/10000 [24:54<07:03,  5.25step/s, loss=0.057993, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7775/10000 [24:54<07:02,  5.26step/s, loss=0.057993, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7775/10000 [24:54<07:02,  5.26step/s, loss=0.080249, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7776/10000 [24:54<07:05,  5.23step/s, loss=0.080249, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7776/10000 [24:54<07:05,  5.23step/s, loss=0.112553, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7777/10000 [24:55<07:04,  5.23step/s, loss=0.112553, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7777/10000 [24:55<07:04,  5.23step/s, loss=0.059580, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7778/10000 [24:55<07:04,  5.24step/s, loss=0.059580, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7778/10000 [24:55<07:04,  5.24step/s, loss=0.045969, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7779/10000 [24:55<07:02,  5.25step/s, loss=0.045969, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7779/10000 [24:55<07:02,  5.25step/s, loss=0.030737, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7780/10000 [24:55<07:02,  5.25step/s, loss=0.030737, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7780/10000 [24:55<07:02,  5.25step/s, loss=0.033475, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7781/10000 [24:55<07:01,  5.26step/s, loss=0.033475, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7781/10000 [24:55<07:01,  5.26step/s, loss=0.036746, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7782/10000 [24:56<07:01,  5.26step/s, loss=0.036746, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7782/10000 [24:56<07:01,  5.26step/s, loss=0.023502, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7783/10000 [24:56<07:01,  5.25step/s, loss=0.023502, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7783/10000 [24:56<07:01,  5.25step/s, loss=0.089524, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7784/10000 [24:56<07:01,  5.26step/s, loss=0.089524, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7784/10000 [24:56<07:01,  5.26step/s, loss=0.049509, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7785/10000 [24:56<07:01,  5.25step/s, loss=0.049509, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7785/10000 [24:56<07:01,  5.25step/s, loss=0.023937, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7786/10000 [24:56<07:00,  5.26step/s, loss=0.023937, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7786/10000 [24:56<07:00,  5.26step/s, loss=0.034596, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7787/10000 [24:57<07:01,  5.26step/s, loss=0.034596, elapsed=24.9min]

Entraînement:  78%|███████▊  | 7787/10000 [24:57<07:01,  5.26step/s, loss=0.072063, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7788/10000 [24:57<07:00,  5.26step/s, loss=0.072063, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7788/10000 [24:57<07:00,  5.26step/s, loss=0.055772, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7789/10000 [24:57<07:00,  5.25step/s, loss=0.055772, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7789/10000 [24:57<07:00,  5.25step/s, loss=0.033206, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7790/10000 [24:57<07:00,  5.26step/s, loss=0.033206, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7790/10000 [24:57<07:00,  5.26step/s, loss=0.037035, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7791/10000 [24:57<06:59,  5.26step/s, loss=0.037035, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7791/10000 [24:57<06:59,  5.26step/s, loss=0.100633, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7792/10000 [24:57<07:00,  5.26step/s, loss=0.100633, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7792/10000 [24:57<07:00,  5.26step/s, loss=0.037601, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7793/10000 [24:58<06:59,  5.26step/s, loss=0.037601, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7793/10000 [24:58<06:59,  5.26step/s, loss=0.053290, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7794/10000 [24:58<07:00,  5.25step/s, loss=0.053290, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7794/10000 [24:58<07:00,  5.25step/s, loss=0.052305, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7795/10000 [24:58<06:59,  5.25step/s, loss=0.052305, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7795/10000 [24:58<06:59,  5.25step/s, loss=0.064938, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7796/10000 [24:58<06:59,  5.25step/s, loss=0.064938, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7796/10000 [24:58<06:59,  5.25step/s, loss=0.038737, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7797/10000 [24:58<06:58,  5.26step/s, loss=0.038737, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7797/10000 [24:58<06:58,  5.26step/s, loss=0.031620, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7798/10000 [24:59<06:59,  5.25step/s, loss=0.031620, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7798/10000 [24:59<06:59,  5.25step/s, loss=0.045023, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7799/10000 [24:59<06:58,  5.26step/s, loss=0.045023, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7799/10000 [24:59<06:58,  5.26step/s, loss=0.024570, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7800/10000 [24:59<06:58,  5.25step/s, loss=0.024570, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7800/10000 [24:59<06:58,  5.25step/s, loss=0.061774, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7800/10000 [24:59<06:58,  5.25step/s, loss=0.061774, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7801/10000 [24:59<07:03,  5.19step/s, loss=0.061774, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7801/10000 [24:59<07:03,  5.19step/s, loss=0.048398, elapsed=25.0min]

Step 7800/10000 | Train loss: 0.061774 | Elapsed: 25.0min | ETA: 7.0min

Entraînement:  78%|███████▊  | 7802/10000 [24:59<07:02,  5.20step/s, loss=0.048398, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7802/10000 [24:59<07:02,  5.20step/s, loss=0.041528, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7803/10000 [25:00<07:03,  5.19step/s, loss=0.041528, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7803/10000 [25:00<07:03,  5.19step/s, loss=0.099817, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7804/10000 [25:00<07:01,  5.22step/s, loss=0.099817, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7804/10000 [25:00<07:01,  5.22step/s, loss=0.028439, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7805/10000 [25:00<06:58,  5.24step/s, loss=0.028439, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7805/10000 [25:00<06:58,  5.24step/s, loss=0.032888, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7806/10000 [25:00<06:58,  5.24step/s, loss=0.032888, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7806/10000 [25:00<06:58,  5.24step/s, loss=0.021041, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7807/10000 [25:00<06:57,  5.25step/s, loss=0.021041, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7807/10000 [25:00<06:57,  5.25step/s, loss=0.064221, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7808/10000 [25:01<06:57,  5.25step/s, loss=0.064221, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7808/10000 [25:01<06:57,  5.25step/s, loss=0.038971, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7809/10000 [25:01<06:56,  5.25step/s, loss=0.038971, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7809/10000 [25:01<06:56,  5.25step/s, loss=0.039405, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7810/10000 [25:01<06:55,  5.27step/s, loss=0.039405, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7810/10000 [25:01<06:55,  5.27step/s, loss=0.107758, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7811/10000 [25:01<06:54,  5.28step/s, loss=0.107758, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7811/10000 [25:01<06:54,  5.28step/s, loss=0.030783, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7812/10000 [25:01<06:54,  5.28step/s, loss=0.030783, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7812/10000 [25:01<06:54,  5.28step/s, loss=0.022813, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7813/10000 [25:01<06:54,  5.27step/s, loss=0.022813, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7813/10000 [25:01<06:54,  5.27step/s, loss=0.023466, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7814/10000 [25:02<06:55,  5.26step/s, loss=0.023466, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7814/10000 [25:02<06:55,  5.26step/s, loss=0.054946, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7815/10000 [25:02<06:55,  5.25step/s, loss=0.054946, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7815/10000 [25:02<06:55,  5.25step/s, loss=0.038132, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7816/10000 [25:02<06:55,  5.26step/s, loss=0.038132, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7816/10000 [25:02<06:55,  5.26step/s, loss=0.041889, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7817/10000 [25:02<06:53,  5.28step/s, loss=0.041889, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7817/10000 [25:02<06:53,  5.28step/s, loss=0.049753, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7818/10000 [25:02<06:56,  5.24step/s, loss=0.049753, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7818/10000 [25:02<06:56,  5.24step/s, loss=0.044704, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7819/10000 [25:03<06:55,  5.25step/s, loss=0.044704, elapsed=25.0min]

Entraînement:  78%|███████▊  | 7819/10000 [25:03<06:55,  5.25step/s, loss=0.028514, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7820/10000 [25:03<06:55,  5.25step/s, loss=0.028514, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7820/10000 [25:03<06:55,  5.25step/s, loss=0.045412, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7821/10000 [25:03<06:55,  5.24step/s, loss=0.045412, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7821/10000 [25:03<06:55,  5.24step/s, loss=0.060386, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7822/10000 [25:03<06:54,  5.26step/s, loss=0.060386, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7822/10000 [25:03<06:54,  5.26step/s, loss=0.036012, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7823/10000 [25:03<06:50,  5.30step/s, loss=0.036012, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7823/10000 [25:03<06:50,  5.30step/s, loss=0.019162, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7824/10000 [25:04<06:52,  5.28step/s, loss=0.019162, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7824/10000 [25:04<06:52,  5.28step/s, loss=0.026936, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7825/10000 [25:04<06:52,  5.27step/s, loss=0.026936, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7825/10000 [25:04<06:52,  5.27step/s, loss=0.072640, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7826/10000 [25:04<06:52,  5.27step/s, loss=0.072640, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7826/10000 [25:04<06:52,  5.27step/s, loss=0.038791, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7827/10000 [25:04<06:52,  5.27step/s, loss=0.038791, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7827/10000 [25:04<06:52,  5.27step/s, loss=0.074269, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7828/10000 [25:04<06:52,  5.27step/s, loss=0.074269, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7828/10000 [25:04<06:52,  5.27step/s, loss=0.067616, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7829/10000 [25:05<06:52,  5.26step/s, loss=0.067616, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7829/10000 [25:05<06:52,  5.26step/s, loss=0.034149, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7830/10000 [25:05<06:52,  5.26step/s, loss=0.034149, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7830/10000 [25:05<06:52,  5.26step/s, loss=0.082100, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7831/10000 [25:05<06:52,  5.26step/s, loss=0.082100, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7831/10000 [25:05<06:52,  5.26step/s, loss=0.091804, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7832/10000 [25:05<06:51,  5.26step/s, loss=0.091804, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7832/10000 [25:05<06:51,  5.26step/s, loss=0.098804, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7833/10000 [25:05<06:50,  5.27step/s, loss=0.098804, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7833/10000 [25:05<06:50,  5.27step/s, loss=0.026579, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7834/10000 [25:05<06:50,  5.27step/s, loss=0.026579, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7834/10000 [25:05<06:50,  5.27step/s, loss=0.057393, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7835/10000 [25:06<06:50,  5.28step/s, loss=0.057393, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7835/10000 [25:06<06:50,  5.28step/s, loss=0.029760, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7836/10000 [25:06<06:50,  5.27step/s, loss=0.029760, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7836/10000 [25:06<06:50,  5.27step/s, loss=0.020275, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7837/10000 [25:06<06:51,  5.26step/s, loss=0.020275, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7837/10000 [25:06<06:51,  5.26step/s, loss=0.093758, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7838/10000 [25:06<06:52,  5.24step/s, loss=0.093758, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7838/10000 [25:06<06:52,  5.24step/s, loss=0.055519, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7839/10000 [25:06<06:51,  5.25step/s, loss=0.055519, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7839/10000 [25:06<06:51,  5.25step/s, loss=0.106379, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7840/10000 [25:07<06:51,  5.25step/s, loss=0.106379, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7840/10000 [25:07<06:51,  5.25step/s, loss=0.041791, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7841/10000 [25:07<06:50,  5.26step/s, loss=0.041791, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7841/10000 [25:07<06:50,  5.26step/s, loss=0.053333, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7842/10000 [25:07<06:50,  5.26step/s, loss=0.053333, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7842/10000 [25:07<06:50,  5.26step/s, loss=0.050007, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7843/10000 [25:07<06:49,  5.26step/s, loss=0.050007, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7843/10000 [25:07<06:49,  5.26step/s, loss=0.051704, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7844/10000 [25:07<06:50,  5.25step/s, loss=0.051704, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7844/10000 [25:07<06:50,  5.25step/s, loss=0.039980, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7845/10000 [25:08<06:49,  5.26step/s, loss=0.039980, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7845/10000 [25:08<06:49,  5.26step/s, loss=0.050117, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7846/10000 [25:08<06:49,  5.26step/s, loss=0.050117, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7846/10000 [25:08<06:49,  5.26step/s, loss=0.023142, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7847/10000 [25:08<06:49,  5.26step/s, loss=0.023142, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7847/10000 [25:08<06:49,  5.26step/s, loss=0.045739, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7848/10000 [25:08<06:48,  5.27step/s, loss=0.045739, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7848/10000 [25:08<06:48,  5.27step/s, loss=0.016686, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7849/10000 [25:08<06:48,  5.26step/s, loss=0.016686, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7849/10000 [25:08<06:48,  5.26step/s, loss=0.032300, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7850/10000 [25:09<06:48,  5.27step/s, loss=0.032300, elapsed=25.1min]

Entraînement:  78%|███████▊  | 7850/10000 [25:09<06:48,  5.27step/s, loss=0.058986, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7851/10000 [25:09<06:47,  5.27step/s, loss=0.058986, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7851/10000 [25:09<06:47,  5.27step/s, loss=0.032882, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7852/10000 [25:09<06:48,  5.25step/s, loss=0.032882, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7852/10000 [25:09<06:48,  5.25step/s, loss=0.090552, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7853/10000 [25:09<06:48,  5.26step/s, loss=0.090552, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7853/10000 [25:09<06:48,  5.26step/s, loss=0.042968, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7854/10000 [25:09<06:49,  5.24step/s, loss=0.042968, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7854/10000 [25:09<06:49,  5.24step/s, loss=0.023789, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7855/10000 [25:09<06:48,  5.25step/s, loss=0.023789, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7855/10000 [25:09<06:48,  5.25step/s, loss=0.071047, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7856/10000 [25:10<06:47,  5.26step/s, loss=0.071047, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7856/10000 [25:10<06:47,  5.26step/s, loss=0.040965, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7857/10000 [25:10<06:47,  5.26step/s, loss=0.040965, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7857/10000 [25:10<06:47,  5.26step/s, loss=0.023038, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7858/10000 [25:10<06:46,  5.27step/s, loss=0.023038, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7858/10000 [25:10<06:46,  5.27step/s, loss=0.023278, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7859/10000 [25:10<06:46,  5.26step/s, loss=0.023278, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7859/10000 [25:10<06:46,  5.26step/s, loss=0.082173, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7860/10000 [25:10<06:47,  5.25step/s, loss=0.082173, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7860/10000 [25:10<06:47,  5.25step/s, loss=0.028337, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7861/10000 [25:11<06:47,  5.25step/s, loss=0.028337, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7861/10000 [25:11<06:47,  5.25step/s, loss=0.033857, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7862/10000 [25:11<06:46,  5.26step/s, loss=0.033857, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7862/10000 [25:11<06:46,  5.26step/s, loss=0.049981, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7863/10000 [25:11<06:46,  5.26step/s, loss=0.049981, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7863/10000 [25:11<06:46,  5.26step/s, loss=0.033706, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7864/10000 [25:11<06:46,  5.26step/s, loss=0.033706, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7864/10000 [25:11<06:46,  5.26step/s, loss=0.109833, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7865/10000 [25:11<06:45,  5.26step/s, loss=0.109833, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7865/10000 [25:11<06:45,  5.26step/s, loss=0.052518, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7866/10000 [25:12<06:45,  5.26step/s, loss=0.052518, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7866/10000 [25:12<06:45,  5.26step/s, loss=0.022357, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7867/10000 [25:12<06:45,  5.26step/s, loss=0.022357, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7867/10000 [25:12<06:45,  5.26step/s, loss=0.043431, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7868/10000 [25:12<06:45,  5.26step/s, loss=0.043431, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7868/10000 [25:12<06:45,  5.26step/s, loss=0.022809, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7869/10000 [25:12<06:45,  5.25step/s, loss=0.022809, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7869/10000 [25:12<06:45,  5.25step/s, loss=0.032053, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7870/10000 [25:12<06:48,  5.22step/s, loss=0.032053, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7870/10000 [25:12<06:48,  5.22step/s, loss=0.047054, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7871/10000 [25:13<06:47,  5.23step/s, loss=0.047054, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7871/10000 [25:13<06:47,  5.23step/s, loss=0.037500, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7872/10000 [25:13<06:45,  5.25step/s, loss=0.037500, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7872/10000 [25:13<06:45,  5.25step/s, loss=0.056443, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7873/10000 [25:13<06:43,  5.27step/s, loss=0.056443, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7873/10000 [25:13<06:43,  5.27step/s, loss=0.084862, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7874/10000 [25:13<06:42,  5.28step/s, loss=0.084862, elapsed=25.2min]

Entraînement:  79%|███████▊  | 7874/10000 [25:13<06:42,  5.28step/s, loss=0.019026, elapsed=25.2min]

Entraînement:  79%|███████▉  | 7875/10000 [25:13<06:42,  5.28step/s, loss=0.019026, elapsed=25.2min]

Entraînement:  79%|███████▉  | 7875/10000 [25:13<06:42,  5.28step/s, loss=0.050372, elapsed=25.2min]

Entraînement:  79%|███████▉  | 7876/10000 [25:13<06:43,  5.26step/s, loss=0.050372, elapsed=25.2min]

Entraînement:  79%|███████▉  | 7876/10000 [25:13<06:43,  5.26step/s, loss=0.038444, elapsed=25.2min]

Entraînement:  79%|███████▉  | 7877/10000 [25:14<06:42,  5.27step/s, loss=0.038444, elapsed=25.2min]

Entraînement:  79%|███████▉  | 7877/10000 [25:14<06:42,  5.27step/s, loss=0.027455, elapsed=25.2min]

Entraînement:  79%|███████▉  | 7878/10000 [25:14<06:43,  5.25step/s, loss=0.027455, elapsed=25.2min]

Entraînement:  79%|███████▉  | 7878/10000 [25:14<06:43,  5.25step/s, loss=0.027819, elapsed=25.2min]

Entraînement:  79%|███████▉  | 7879/10000 [25:14<06:43,  5.26step/s, loss=0.027819, elapsed=25.2min]

Entraînement:  79%|███████▉  | 7879/10000 [25:14<06:43,  5.26step/s, loss=0.049393, elapsed=25.2min]

Entraînement:  79%|███████▉  | 7880/10000 [25:14<06:42,  5.27step/s, loss=0.049393, elapsed=25.2min]

Entraînement:  79%|███████▉  | 7880/10000 [25:14<06:42,  5.27step/s, loss=0.044487, elapsed=25.2min]

Entraînement:  79%|███████▉  | 7881/10000 [25:14<06:42,  5.26step/s, loss=0.044487, elapsed=25.2min]

Entraînement:  79%|███████▉  | 7881/10000 [25:14<06:42,  5.26step/s, loss=0.073873, elapsed=25.2min]

Entraînement:  79%|███████▉  | 7882/10000 [25:15<06:42,  5.27step/s, loss=0.073873, elapsed=25.2min]

Entraînement:  79%|███████▉  | 7882/10000 [25:15<06:42,  5.27step/s, loss=0.080685, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7883/10000 [25:15<06:41,  5.27step/s, loss=0.080685, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7883/10000 [25:15<06:41,  5.27step/s, loss=0.021354, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7884/10000 [25:15<06:40,  5.28step/s, loss=0.021354, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7884/10000 [25:15<06:40,  5.28step/s, loss=0.051858, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7885/10000 [25:15<06:41,  5.27step/s, loss=0.051858, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7885/10000 [25:15<06:41,  5.27step/s, loss=0.035772, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7886/10000 [25:15<06:40,  5.28step/s, loss=0.035772, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7886/10000 [25:15<06:40,  5.28step/s, loss=0.047357, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7887/10000 [25:16<06:39,  5.29step/s, loss=0.047357, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7887/10000 [25:16<06:39,  5.29step/s, loss=0.041317, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7888/10000 [25:16<06:39,  5.28step/s, loss=0.041317, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7888/10000 [25:16<06:39,  5.28step/s, loss=0.020250, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7889/10000 [25:16<06:39,  5.29step/s, loss=0.020250, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7889/10000 [25:16<06:39,  5.29step/s, loss=0.085607, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7890/10000 [25:16<06:39,  5.29step/s, loss=0.085607, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7890/10000 [25:16<06:39,  5.29step/s, loss=0.037565, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7891/10000 [25:16<06:38,  5.29step/s, loss=0.037565, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7891/10000 [25:16<06:38,  5.29step/s, loss=0.066943, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7892/10000 [25:16<06:38,  5.29step/s, loss=0.066943, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7892/10000 [25:16<06:38,  5.29step/s, loss=0.041384, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7893/10000 [25:17<06:38,  5.29step/s, loss=0.041384, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7893/10000 [25:17<06:38,  5.29step/s, loss=0.052850, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7894/10000 [25:17<06:38,  5.29step/s, loss=0.052850, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7894/10000 [25:17<06:38,  5.29step/s, loss=0.039694, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7895/10000 [25:17<06:37,  5.29step/s, loss=0.039694, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7895/10000 [25:17<06:37,  5.29step/s, loss=0.021796, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7896/10000 [25:17<06:38,  5.28step/s, loss=0.021796, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7896/10000 [25:17<06:38,  5.28step/s, loss=0.030512, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7897/10000 [25:17<06:39,  5.26step/s, loss=0.030512, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7897/10000 [25:17<06:39,  5.26step/s, loss=0.105934, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7898/10000 [25:18<06:39,  5.27step/s, loss=0.105934, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7898/10000 [25:18<06:39,  5.27step/s, loss=0.045649, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7899/10000 [25:18<06:38,  5.27step/s, loss=0.045649, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7899/10000 [25:18<06:38,  5.27step/s, loss=0.023863, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7900/10000 [25:18<06:38,  5.27step/s, loss=0.023863, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7900/10000 [25:18<06:38,  5.27step/s, loss=0.032812, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7900/10000 [25:18<06:38,  5.27step/s, loss=0.032812, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7901/10000 [25:18<06:41,  5.23step/s, loss=0.032812, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7901/10000 [25:18<06:41,  5.23step/s, loss=0.038092, elapsed=25.3min]

Step 7900/10000 | Train loss: 0.032812 | Elapsed: 25.3min | ETA: 6.7min

Entraînement:  79%|███████▉  | 7902/10000 [25:18<06:41,  5.23step/s, loss=0.038092, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7902/10000 [25:18<06:41,  5.23step/s, loss=0.058144, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7903/10000 [25:19<06:41,  5.23step/s, loss=0.058144, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7903/10000 [25:19<06:41,  5.23step/s, loss=0.067039, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7904/10000 [25:19<06:40,  5.24step/s, loss=0.067039, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7904/10000 [25:19<06:40,  5.24step/s, loss=0.077439, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7905/10000 [25:19<06:40,  5.23step/s, loss=0.077439, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7905/10000 [25:19<06:40,  5.23step/s, loss=0.026247, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7906/10000 [25:19<06:39,  5.24step/s, loss=0.026247, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7906/10000 [25:19<06:39,  5.24step/s, loss=0.022466, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7907/10000 [25:19<06:38,  5.25step/s, loss=0.022466, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7907/10000 [25:19<06:38,  5.25step/s, loss=0.042968, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7908/10000 [25:20<06:38,  5.25step/s, loss=0.042968, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7908/10000 [25:20<06:38,  5.25step/s, loss=0.014049, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7909/10000 [25:20<06:37,  5.25step/s, loss=0.014049, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7909/10000 [25:20<06:37,  5.25step/s, loss=0.028080, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7910/10000 [25:20<06:37,  5.26step/s, loss=0.028080, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7910/10000 [25:20<06:37,  5.26step/s, loss=0.025541, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7911/10000 [25:20<06:38,  5.24step/s, loss=0.025541, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7911/10000 [25:20<06:38,  5.24step/s, loss=0.059120, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7912/10000 [25:20<06:37,  5.25step/s, loss=0.059120, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7912/10000 [25:20<06:37,  5.25step/s, loss=0.063157, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7913/10000 [25:20<06:37,  5.25step/s, loss=0.063157, elapsed=25.3min]

Entraînement:  79%|███████▉  | 7913/10000 [25:20<06:37,  5.25step/s, loss=0.025082, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7914/10000 [25:21<06:37,  5.25step/s, loss=0.025082, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7914/10000 [25:21<06:37,  5.25step/s, loss=0.061879, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7915/10000 [25:21<06:36,  5.26step/s, loss=0.061879, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7915/10000 [25:21<06:36,  5.26step/s, loss=0.033820, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7916/10000 [25:21<06:35,  5.27step/s, loss=0.033820, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7916/10000 [25:21<06:35,  5.27step/s, loss=0.058001, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7917/10000 [25:21<06:35,  5.27step/s, loss=0.058001, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7917/10000 [25:21<06:35,  5.27step/s, loss=0.058269, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7918/10000 [25:21<06:35,  5.26step/s, loss=0.058269, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7918/10000 [25:21<06:35,  5.26step/s, loss=0.048481, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7919/10000 [25:22<06:35,  5.26step/s, loss=0.048481, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7919/10000 [25:22<06:35,  5.26step/s, loss=0.065461, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7920/10000 [25:22<06:35,  5.25step/s, loss=0.065461, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7920/10000 [25:22<06:35,  5.25step/s, loss=0.048021, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7921/10000 [25:22<06:35,  5.26step/s, loss=0.048021, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7921/10000 [25:22<06:35,  5.26step/s, loss=0.078084, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7922/10000 [25:22<06:35,  5.25step/s, loss=0.078084, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7922/10000 [25:22<06:35,  5.25step/s, loss=0.070357, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7923/10000 [25:22<06:35,  5.25step/s, loss=0.070357, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7923/10000 [25:22<06:35,  5.25step/s, loss=0.044484, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7924/10000 [25:23<06:34,  5.26step/s, loss=0.044484, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7924/10000 [25:23<06:34,  5.26step/s, loss=0.022725, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7925/10000 [25:23<06:34,  5.26step/s, loss=0.022725, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7925/10000 [25:23<06:34,  5.26step/s, loss=0.035897, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7926/10000 [25:23<06:34,  5.26step/s, loss=0.035897, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7926/10000 [25:23<06:34,  5.26step/s, loss=0.043326, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7927/10000 [25:23<06:34,  5.26step/s, loss=0.043326, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7927/10000 [25:23<06:34,  5.26step/s, loss=0.035121, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7928/10000 [25:23<06:38,  5.20step/s, loss=0.035121, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7928/10000 [25:23<06:38,  5.20step/s, loss=0.068863, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7929/10000 [25:24<06:37,  5.22step/s, loss=0.068863, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7929/10000 [25:24<06:37,  5.22step/s, loss=0.027222, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7930/10000 [25:24<06:35,  5.24step/s, loss=0.027222, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7930/10000 [25:24<06:35,  5.24step/s, loss=0.092450, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7931/10000 [25:24<06:33,  5.25step/s, loss=0.092450, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7931/10000 [25:24<06:33,  5.25step/s, loss=0.091112, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7932/10000 [25:24<06:32,  5.26step/s, loss=0.091112, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7932/10000 [25:24<06:32,  5.26step/s, loss=0.035317, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7933/10000 [25:24<06:32,  5.27step/s, loss=0.035317, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7933/10000 [25:24<06:32,  5.27step/s, loss=0.079230, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7934/10000 [25:24<06:32,  5.26step/s, loss=0.079230, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7934/10000 [25:24<06:32,  5.26step/s, loss=0.102796, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7935/10000 [25:25<06:31,  5.28step/s, loss=0.102796, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7935/10000 [25:25<06:31,  5.28step/s, loss=0.067436, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7936/10000 [25:25<06:30,  5.28step/s, loss=0.067436, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7936/10000 [25:25<06:30,  5.28step/s, loss=0.035893, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7937/10000 [25:25<06:31,  5.27step/s, loss=0.035893, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7937/10000 [25:25<06:31,  5.27step/s, loss=0.044074, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7938/10000 [25:25<06:30,  5.28step/s, loss=0.044074, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7938/10000 [25:25<06:30,  5.28step/s, loss=0.037394, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7939/10000 [25:25<06:30,  5.28step/s, loss=0.037394, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7939/10000 [25:25<06:30,  5.28step/s, loss=0.052563, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7940/10000 [25:26<06:30,  5.28step/s, loss=0.052563, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7940/10000 [25:26<06:30,  5.28step/s, loss=0.130145, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7941/10000 [25:26<06:30,  5.28step/s, loss=0.130145, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7941/10000 [25:26<06:30,  5.28step/s, loss=0.026543, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7942/10000 [25:26<06:29,  5.28step/s, loss=0.026543, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7942/10000 [25:26<06:29,  5.28step/s, loss=0.050514, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7943/10000 [25:26<06:30,  5.27step/s, loss=0.050514, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7943/10000 [25:26<06:30,  5.27step/s, loss=0.088538, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7944/10000 [25:26<06:29,  5.28step/s, loss=0.088538, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7944/10000 [25:26<06:29,  5.28step/s, loss=0.041889, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7945/10000 [25:27<06:28,  5.28step/s, loss=0.041889, elapsed=25.4min]

Entraînement:  79%|███████▉  | 7945/10000 [25:27<06:28,  5.28step/s, loss=0.020033, elapsed=25.5min]

Entraînement:  79%|███████▉  | 7946/10000 [25:27<06:29,  5.28step/s, loss=0.020033, elapsed=25.5min]

Entraînement:  79%|███████▉  | 7946/10000 [25:27<06:29,  5.28step/s, loss=0.087014, elapsed=25.5min]

Entraînement:  79%|███████▉  | 7947/10000 [25:27<06:28,  5.29step/s, loss=0.087014, elapsed=25.5min]

Entraînement:  79%|███████▉  | 7947/10000 [25:27<06:28,  5.29step/s, loss=0.050636, elapsed=25.5min]

Entraînement:  79%|███████▉  | 7948/10000 [25:27<06:28,  5.29step/s, loss=0.050636, elapsed=25.5min]

Entraînement:  79%|███████▉  | 7948/10000 [25:27<06:28,  5.29step/s, loss=0.054676, elapsed=25.5min]

Entraînement:  79%|███████▉  | 7949/10000 [25:27<06:27,  5.29step/s, loss=0.054676, elapsed=25.5min]

Entraînement:  79%|███████▉  | 7949/10000 [25:27<06:27,  5.29step/s, loss=0.097443, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7950/10000 [25:28<06:27,  5.29step/s, loss=0.097443, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7950/10000 [25:28<06:27,  5.29step/s, loss=0.024729, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7951/10000 [25:28<06:27,  5.29step/s, loss=0.024729, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7951/10000 [25:28<06:27,  5.29step/s, loss=0.042141, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7952/10000 [25:28<06:27,  5.29step/s, loss=0.042141, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7952/10000 [25:28<06:27,  5.29step/s, loss=0.051901, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7953/10000 [25:28<06:26,  5.30step/s, loss=0.051901, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7953/10000 [25:28<06:26,  5.30step/s, loss=0.040921, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7954/10000 [25:28<06:26,  5.30step/s, loss=0.040921, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7954/10000 [25:28<06:26,  5.30step/s, loss=0.016048, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7955/10000 [25:28<06:26,  5.30step/s, loss=0.016048, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7955/10000 [25:28<06:26,  5.30step/s, loss=0.066546, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7956/10000 [25:29<06:26,  5.29step/s, loss=0.066546, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7956/10000 [25:29<06:26,  5.29step/s, loss=0.083519, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7957/10000 [25:29<06:26,  5.29step/s, loss=0.083519, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7957/10000 [25:29<06:26,  5.29step/s, loss=0.022295, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7958/10000 [25:29<06:25,  5.29step/s, loss=0.022295, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7958/10000 [25:29<06:25,  5.29step/s, loss=0.042692, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7959/10000 [25:29<06:26,  5.29step/s, loss=0.042692, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7959/10000 [25:29<06:26,  5.29step/s, loss=0.117318, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7960/10000 [25:29<06:26,  5.28step/s, loss=0.117318, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7960/10000 [25:29<06:26,  5.28step/s, loss=0.062791, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7961/10000 [25:30<06:27,  5.27step/s, loss=0.062791, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7961/10000 [25:30<06:27,  5.27step/s, loss=0.074673, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7962/10000 [25:30<06:26,  5.27step/s, loss=0.074673, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7962/10000 [25:30<06:26,  5.27step/s, loss=0.046298, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7963/10000 [25:30<06:27,  5.26step/s, loss=0.046298, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7963/10000 [25:30<06:27,  5.26step/s, loss=0.033150, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7964/10000 [25:30<06:27,  5.26step/s, loss=0.033150, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7964/10000 [25:30<06:27,  5.26step/s, loss=0.034080, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7965/10000 [25:30<06:27,  5.26step/s, loss=0.034080, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7965/10000 [25:30<06:27,  5.26step/s, loss=0.031960, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7966/10000 [25:31<06:27,  5.25step/s, loss=0.031960, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7966/10000 [25:31<06:27,  5.25step/s, loss=0.029908, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7967/10000 [25:31<06:26,  5.26step/s, loss=0.029908, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7967/10000 [25:31<06:26,  5.26step/s, loss=0.029412, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7968/10000 [25:31<06:26,  5.26step/s, loss=0.029412, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7968/10000 [25:31<06:26,  5.26step/s, loss=0.027323, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7969/10000 [25:31<06:26,  5.25step/s, loss=0.027323, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7969/10000 [25:31<06:26,  5.25step/s, loss=0.056579, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7970/10000 [25:31<06:28,  5.23step/s, loss=0.056579, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7970/10000 [25:31<06:28,  5.23step/s, loss=0.076667, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7971/10000 [25:32<06:27,  5.24step/s, loss=0.076667, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7971/10000 [25:32<06:27,  5.24step/s, loss=0.054187, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7972/10000 [25:32<06:26,  5.24step/s, loss=0.054187, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7972/10000 [25:32<06:26,  5.24step/s, loss=0.071171, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7973/10000 [25:32<06:27,  5.24step/s, loss=0.071171, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7973/10000 [25:32<06:27,  5.24step/s, loss=0.048906, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7974/10000 [25:32<06:26,  5.25step/s, loss=0.048906, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7974/10000 [25:32<06:26,  5.25step/s, loss=0.025015, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7975/10000 [25:32<06:24,  5.27step/s, loss=0.025015, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7975/10000 [25:32<06:24,  5.27step/s, loss=0.039963, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7976/10000 [25:32<06:23,  5.27step/s, loss=0.039963, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7976/10000 [25:32<06:23,  5.27step/s, loss=0.061272, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7977/10000 [25:33<06:22,  5.28step/s, loss=0.061272, elapsed=25.5min]

Entraînement:  80%|███████▉  | 7977/10000 [25:33<06:22,  5.28step/s, loss=0.023247, elapsed=25.6min]

Entraînement:  80%|███████▉  | 7978/10000 [25:33<06:22,  5.28step/s, loss=0.023247, elapsed=25.6min]

Entraînement:  80%|███████▉  | 7978/10000 [25:33<06:22,  5.28step/s, loss=0.075585, elapsed=25.6min]

Entraînement:  80%|███████▉  | 7979/10000 [25:33<06:22,  5.29step/s, loss=0.075585, elapsed=25.6min]

Entraînement:  80%|███████▉  | 7979/10000 [25:33<06:22,  5.29step/s, loss=0.035192, elapsed=25.6min]

Entraînement:  80%|███████▉  | 7980/10000 [25:33<06:22,  5.28step/s, loss=0.035192, elapsed=25.6min]

Entraînement:  80%|███████▉  | 7980/10000 [25:33<06:22,  5.28step/s, loss=0.030881, elapsed=25.6min]

Entraînement:  80%|███████▉  | 7981/10000 [25:33<06:24,  5.25step/s, loss=0.030881, elapsed=25.6min]

Entraînement:  80%|███████▉  | 7981/10000 [25:33<06:24,  5.25step/s, loss=0.034009, elapsed=25.6min]

Entraînement:  80%|███████▉  | 7982/10000 [25:34<06:25,  5.24step/s, loss=0.034009, elapsed=25.6min]

Entraînement:  80%|███████▉  | 7982/10000 [25:34<06:25,  5.24step/s, loss=0.037891, elapsed=25.6min]

Entraînement:  80%|███████▉  | 7983/10000 [25:34<06:23,  5.26step/s, loss=0.037891, elapsed=25.6min]

Entraînement:  80%|███████▉  | 7983/10000 [25:34<06:23,  5.26step/s, loss=0.041876, elapsed=25.6min]

Entraînement:  80%|███████▉  | 7984/10000 [25:34<06:23,  5.26step/s, loss=0.041876, elapsed=25.6min]

Entraînement:  80%|███████▉  | 7984/10000 [25:34<06:23,  5.26step/s, loss=0.022846, elapsed=25.6min]

Entraînement:  80%|███████▉  | 7985/10000 [25:34<06:22,  5.27step/s, loss=0.022846, elapsed=25.6min]

Entraînement:  80%|███████▉  | 7985/10000 [25:34<06:22,  5.27step/s, loss=0.035839, elapsed=25.6min]

Entraînement:  80%|███████▉  | 7986/10000 [25:34<06:22,  5.26step/s, loss=0.035839, elapsed=25.6min]

Entraînement:  80%|███████▉  | 7986/10000 [25:34<06:22,  5.26step/s, loss=0.118779, elapsed=25.6min]

Entraînement:  80%|███████▉  | 7987/10000 [25:35<06:21,  5.27step/s, loss=0.118779, elapsed=25.6min]

Entraînement:  80%|███████▉  | 7987/10000 [25:35<06:21,  5.27step/s, loss=0.053887, elapsed=25.6min]

Entraînement:  80%|███████▉  | 7988/10000 [25:35<06:21,  5.28step/s, loss=0.053887, elapsed=25.6min]

Entraînement:  80%|███████▉  | 7988/10000 [25:35<06:21,  5.28step/s, loss=0.033569, elapsed=25.6min]

Entraînement:  80%|███████▉  | 7989/10000 [25:35<06:22,  5.26step/s, loss=0.033569, elapsed=25.6min]

Entraînement:  80%|███████▉  | 7989/10000 [25:35<06:22,  5.26step/s, loss=0.029047, elapsed=25.6min]

Entraînement:  80%|███████▉  | 7990/10000 [25:35<06:21,  5.27step/s, loss=0.029047, elapsed=25.6min]

Entraînement:  80%|███████▉  | 7990/10000 [25:35<06:21,  5.27step/s, loss=0.021296, elapsed=25.6min]

Entraînement:  80%|███████▉  | 7991/10000 [25:35<06:21,  5.27step/s, loss=0.021296, elapsed=25.6min]

Entraînement:  80%|███████▉  | 7991/10000 [25:35<06:21,  5.27step/s, loss=0.016517, elapsed=25.6min]

Entraînement:  80%|███████▉  | 7992/10000 [25:35<06:21,  5.26step/s, loss=0.016517, elapsed=25.6min]

Entraînement:  80%|███████▉  | 7992/10000 [25:35<06:21,  5.26step/s, loss=0.058282, elapsed=25.6min]

Entraînement:  80%|███████▉  | 7993/10000 [25:36<06:20,  5.28step/s, loss=0.058282, elapsed=25.6min]

Entraînement:  80%|███████▉  | 7993/10000 [25:36<06:20,  5.28step/s, loss=0.040948, elapsed=25.6min]

Entraînement:  80%|███████▉  | 7994/10000 [25:36<06:19,  5.28step/s, loss=0.040948, elapsed=25.6min]

Entraînement:  80%|███████▉  | 7994/10000 [25:36<06:19,  5.28step/s, loss=0.075738, elapsed=25.6min]

Entraînement:  80%|███████▉  | 7995/10000 [25:36<06:18,  5.29step/s, loss=0.075738, elapsed=25.6min]

Entraînement:  80%|███████▉  | 7995/10000 [25:36<06:18,  5.29step/s, loss=0.022363, elapsed=25.6min]

Entraînement:  80%|███████▉  | 7996/10000 [25:36<06:18,  5.29step/s, loss=0.022363, elapsed=25.6min]

Entraînement:  80%|███████▉  | 7996/10000 [25:36<06:18,  5.29step/s, loss=0.041501, elapsed=25.6min]

Entraînement:  80%|███████▉  | 7997/10000 [25:36<06:19,  5.28step/s, loss=0.041501, elapsed=25.6min]

Entraînement:  80%|███████▉  | 7997/10000 [25:36<06:19,  5.28step/s, loss=0.046215, elapsed=25.6min]

Entraînement:  80%|███████▉  | 7998/10000 [25:37<06:18,  5.29step/s, loss=0.046215, elapsed=25.6min]

Entraînement:  80%|███████▉  | 7998/10000 [25:37<06:18,  5.29step/s, loss=0.044146, elapsed=25.6min]

Entraînement:  80%|███████▉  | 7999/10000 [25:37<06:18,  5.29step/s, loss=0.044146, elapsed=25.6min]

Entraînement:  80%|███████▉  | 7999/10000 [25:37<06:18,  5.29step/s, loss=0.029907, elapsed=25.6min]

Entraînement:  80%|████████  | 8000/10000 [25:37<06:18,  5.29step/s, loss=0.029907, elapsed=25.6min]

Entraînement:  80%|████████  | 8000/10000 [25:37<06:18,  5.29step/s, loss=0.058344, elapsed=25.6min]

Entraînement:  80%|████████  | 8000/10000 [25:37<06:18,  5.29step/s, loss=0.058344, elapsed=25.6min]

Step 8000/10000 | Train loss: 0.058344 | Elapsed: 25.6min | ETA: 6.4min

Entraînement:  80%|████████  | 8000/10000 [25:39<06:18,  5.29step/s, loss=0.058344, elapsed=25.6min]

Entraînement:  80%|████████  | 8000/10000 [25:39<06:18,  5.29step/s, loss=0.058344, elapsed=25.6min]

Step 8000/10000 | Val loss: 0.043287 | Validation en 1.8s
Dernier checkpoint sauvegardé : /workspace/DiffWave_Project/checkpoints/diffwave_doda_male/last_checkpoint.pt

Entraînement:  80%|████████  | 8001/10000 [25:39<25:20,  1.31step/s, loss=0.058344, elapsed=25.6min]

Entraînement:  80%|████████  | 8001/10000 [25:39<25:20,  1.31step/s, loss=0.056807, elapsed=25.7min]

Entraînement:  80%|████████  | 8002/10000 [25:39<19:37,  1.70step/s, loss=0.056807, elapsed=25.7min]

Entraînement:  80%|████████  | 8002/10000 [25:39<19:37,  1.70step/s, loss=0.029030, elapsed=25.7min]

Entraînement:  80%|████████  | 8003/10000 [25:39<15:37,  2.13step/s, loss=0.029030, elapsed=25.7min]

Entraînement:  80%|████████  | 8003/10000 [25:39<15:37,  2.13step/s, loss=0.057312, elapsed=25.7min]

Entraînement:  80%|████████  | 8004/10000 [25:40<12:49,  2.59step/s, loss=0.057312, elapsed=25.7min]

Entraînement:  80%|████████  | 8004/10000 [25:40<12:49,  2.59step/s, loss=0.021878, elapsed=25.7min]

Entraînement:  80%|████████  | 8005/10000 [25:40<10:52,  3.06step/s, loss=0.021878, elapsed=25.7min]

Entraînement:  80%|████████  | 8005/10000 [25:40<10:52,  3.06step/s, loss=0.019892, elapsed=25.7min]

Entraînement:  80%|████████  | 8006/10000 [25:40<09:30,  3.50step/s, loss=0.019892, elapsed=25.7min]

Entraînement:  80%|████████  | 8006/10000 [25:40<09:30,  3.50step/s, loss=0.052817, elapsed=25.7min]

Entraînement:  80%|████████  | 8007/10000 [25:40<08:31,  3.89step/s, loss=0.052817, elapsed=25.7min]

Entraînement:  80%|████████  | 8007/10000 [25:40<08:31,  3.89step/s, loss=0.068627, elapsed=25.7min]

Entraînement:  80%|████████  | 8008/10000 [25:40<07:50,  4.23step/s, loss=0.068627, elapsed=25.7min]

Entraînement:  80%|████████  | 8008/10000 [25:40<07:50,  4.23step/s, loss=0.044471, elapsed=25.7min]

Entraînement:  80%|████████  | 8009/10000 [25:41<07:22,  4.50step/s, loss=0.044471, elapsed=25.7min]

Entraînement:  80%|████████  | 8009/10000 [25:41<07:22,  4.50step/s, loss=0.132544, elapsed=25.7min]

Entraînement:  80%|████████  | 8010/10000 [25:41<07:01,  4.72step/s, loss=0.132544, elapsed=25.7min]

Entraînement:  80%|████████  | 8010/10000 [25:41<07:01,  4.72step/s, loss=0.059461, elapsed=25.7min]

Entraînement:  80%|████████  | 8011/10000 [25:41<06:48,  4.87step/s, loss=0.059461, elapsed=25.7min]

Entraînement:  80%|████████  | 8011/10000 [25:41<06:48,  4.87step/s, loss=0.026618, elapsed=25.7min]

Entraînement:  80%|████████  | 8012/10000 [25:41<06:37,  5.00step/s, loss=0.026618, elapsed=25.7min]

Entraînement:  80%|████████  | 8012/10000 [25:41<06:37,  5.00step/s, loss=0.031946, elapsed=25.7min]

Entraînement:  80%|████████  | 8013/10000 [25:41<06:30,  5.09step/s, loss=0.031946, elapsed=25.7min]

Entraînement:  80%|████████  | 8013/10000 [25:41<06:30,  5.09step/s, loss=0.052769, elapsed=25.7min]

Entraînement:  80%|████████  | 8014/10000 [25:42<06:25,  5.15step/s, loss=0.052769, elapsed=25.7min]

Entraînement:  80%|████████  | 8014/10000 [25:42<06:25,  5.15step/s, loss=0.029641, elapsed=25.7min]

Entraînement:  80%|████████  | 8015/10000 [25:42<06:22,  5.19step/s, loss=0.029641, elapsed=25.7min]

Entraînement:  80%|████████  | 8015/10000 [25:42<06:22,  5.19step/s, loss=0.022161, elapsed=25.7min]

Entraînement:  80%|████████  | 8016/10000 [25:42<06:20,  5.22step/s, loss=0.022161, elapsed=25.7min]

Entraînement:  80%|████████  | 8016/10000 [25:42<06:20,  5.22step/s, loss=0.035929, elapsed=25.7min]

Entraînement:  80%|████████  | 8017/10000 [25:42<06:18,  5.24step/s, loss=0.035929, elapsed=25.7min]

Entraînement:  80%|████████  | 8017/10000 [25:42<06:18,  5.24step/s, loss=0.080328, elapsed=25.7min]

Entraînement:  80%|████████  | 8018/10000 [25:42<06:18,  5.24step/s, loss=0.080328, elapsed=25.7min]

Entraînement:  80%|████████  | 8018/10000 [25:42<06:18,  5.24step/s, loss=0.054302, elapsed=25.7min]

Entraînement:  80%|████████  | 8019/10000 [25:43<06:16,  5.26step/s, loss=0.054302, elapsed=25.7min]

Entraînement:  80%|████████  | 8019/10000 [25:43<06:16,  5.26step/s, loss=0.031873, elapsed=25.7min]

Entraînement:  80%|████████  | 8020/10000 [25:43<06:15,  5.27step/s, loss=0.031873, elapsed=25.7min]

Entraînement:  80%|████████  | 8020/10000 [25:43<06:15,  5.27step/s, loss=0.065375, elapsed=25.7min]

Entraînement:  80%|████████  | 8021/10000 [25:43<06:15,  5.27step/s, loss=0.065375, elapsed=25.7min]

Entraînement:  80%|████████  | 8021/10000 [25:43<06:15,  5.27step/s, loss=0.032348, elapsed=25.7min]

Entraînement:  80%|████████  | 8022/10000 [25:43<06:14,  5.28step/s, loss=0.032348, elapsed=25.7min]

Entraînement:  80%|████████  | 8022/10000 [25:43<06:14,  5.28step/s, loss=0.044087, elapsed=25.7min]

Entraînement:  80%|████████  | 8023/10000 [25:43<06:13,  5.29step/s, loss=0.044087, elapsed=25.7min]

Entraînement:  80%|████████  | 8023/10000 [25:43<06:13,  5.29step/s, loss=0.068657, elapsed=25.7min]

Entraînement:  80%|████████  | 8024/10000 [25:43<06:13,  5.29step/s, loss=0.068657, elapsed=25.7min]

Entraînement:  80%|████████  | 8024/10000 [25:43<06:13,  5.29step/s, loss=0.051799, elapsed=25.7min]

Entraînement:  80%|████████  | 8025/10000 [25:44<06:13,  5.29step/s, loss=0.051799, elapsed=25.7min]

Entraînement:  80%|████████  | 8025/10000 [25:44<06:13,  5.29step/s, loss=0.048583, elapsed=25.7min]

Entraînement:  80%|████████  | 8026/10000 [25:44<06:12,  5.30step/s, loss=0.048583, elapsed=25.7min]

Entraînement:  80%|████████  | 8026/10000 [25:44<06:12,  5.30step/s, loss=0.037221, elapsed=25.7min]

Entraînement:  80%|████████  | 8027/10000 [25:44<06:13,  5.29step/s, loss=0.037221, elapsed=25.7min]

Entraînement:  80%|████████  | 8027/10000 [25:44<06:13,  5.29step/s, loss=0.214855, elapsed=25.7min]

Entraînement:  80%|████████  | 8028/10000 [25:44<06:14,  5.27step/s, loss=0.214855, elapsed=25.7min]

Entraînement:  80%|████████  | 8028/10000 [25:44<06:14,  5.27step/s, loss=0.035333, elapsed=25.7min]

Entraînement:  80%|████████  | 8029/10000 [25:44<06:14,  5.26step/s, loss=0.035333, elapsed=25.7min]

Entraînement:  80%|████████  | 8029/10000 [25:44<06:14,  5.26step/s, loss=0.123113, elapsed=25.7min]

Entraînement:  80%|████████  | 8030/10000 [25:45<06:14,  5.27step/s, loss=0.123113, elapsed=25.7min]

Entraînement:  80%|████████  | 8030/10000 [25:45<06:14,  5.27step/s, loss=0.016603, elapsed=25.8min]

Entraînement:  80%|████████  | 8031/10000 [25:45<06:14,  5.26step/s, loss=0.016603, elapsed=25.8min]

Entraînement:  80%|████████  | 8031/10000 [25:45<06:14,  5.26step/s, loss=0.049665, elapsed=25.8min]

Entraînement:  80%|████████  | 8032/10000 [25:45<06:13,  5.27step/s, loss=0.049665, elapsed=25.8min]

Entraînement:  80%|████████  | 8032/10000 [25:45<06:13,  5.27step/s, loss=0.032792, elapsed=25.8min]

Entraînement:  80%|████████  | 8033/10000 [25:45<06:12,  5.27step/s, loss=0.032792, elapsed=25.8min]

Entraînement:  80%|████████  | 8033/10000 [25:45<06:12,  5.27step/s, loss=0.025533, elapsed=25.8min]

Entraînement:  80%|████████  | 8034/10000 [25:45<06:13,  5.27step/s, loss=0.025533, elapsed=25.8min]

Entraînement:  80%|████████  | 8034/10000 [25:45<06:13,  5.27step/s, loss=0.122015, elapsed=25.8min]

Entraînement:  80%|████████  | 8035/10000 [25:46<06:12,  5.28step/s, loss=0.122015, elapsed=25.8min]

Entraînement:  80%|████████  | 8035/10000 [25:46<06:12,  5.28step/s, loss=0.024484, elapsed=25.8min]

Entraînement:  80%|████████  | 8036/10000 [25:46<06:12,  5.27step/s, loss=0.024484, elapsed=25.8min]

Entraînement:  80%|████████  | 8036/10000 [25:46<06:12,  5.27step/s, loss=0.023883, elapsed=25.8min]

Entraînement:  80%|████████  | 8037/10000 [25:46<06:11,  5.28step/s, loss=0.023883, elapsed=25.8min]

Entraînement:  80%|████████  | 8037/10000 [25:46<06:11,  5.28step/s, loss=0.046716, elapsed=25.8min]

Entraînement:  80%|████████  | 8038/10000 [25:46<06:11,  5.28step/s, loss=0.046716, elapsed=25.8min]

Entraînement:  80%|████████  | 8038/10000 [25:46<06:11,  5.28step/s, loss=0.051718, elapsed=25.8min]

Entraînement:  80%|████████  | 8039/10000 [25:46<06:11,  5.28step/s, loss=0.051718, elapsed=25.8min]

Entraînement:  80%|████████  | 8039/10000 [25:46<06:11,  5.28step/s, loss=0.049399, elapsed=25.8min]

Entraînement:  80%|████████  | 8040/10000 [25:46<06:12,  5.26step/s, loss=0.049399, elapsed=25.8min]

Entraînement:  80%|████████  | 8040/10000 [25:46<06:12,  5.26step/s, loss=0.053056, elapsed=25.8min]

Entraînement:  80%|████████  | 8041/10000 [25:47<06:12,  5.26step/s, loss=0.053056, elapsed=25.8min]

Entraînement:  80%|████████  | 8041/10000 [25:47<06:12,  5.26step/s, loss=0.042217, elapsed=25.8min]

Entraînement:  80%|████████  | 8042/10000 [25:47<06:12,  5.25step/s, loss=0.042217, elapsed=25.8min]

Entraînement:  80%|████████  | 8042/10000 [25:47<06:12,  5.25step/s, loss=0.098664, elapsed=25.8min]

Entraînement:  80%|████████  | 8043/10000 [25:47<06:12,  5.25step/s, loss=0.098664, elapsed=25.8min]

Entraînement:  80%|████████  | 8043/10000 [25:47<06:12,  5.25step/s, loss=0.043038, elapsed=25.8min]

Entraînement:  80%|████████  | 8044/10000 [25:47<06:11,  5.26step/s, loss=0.043038, elapsed=25.8min]

Entraînement:  80%|████████  | 8044/10000 [25:47<06:11,  5.26step/s, loss=0.078606, elapsed=25.8min]

Entraînement:  80%|████████  | 8045/10000 [25:47<06:11,  5.26step/s, loss=0.078606, elapsed=25.8min]

Entraînement:  80%|████████  | 8045/10000 [25:47<06:11,  5.26step/s, loss=0.068416, elapsed=25.8min]

Entraînement:  80%|████████  | 8046/10000 [25:48<06:11,  5.26step/s, loss=0.068416, elapsed=25.8min]

Entraînement:  80%|████████  | 8046/10000 [25:48<06:11,  5.26step/s, loss=0.030425, elapsed=25.8min]

Entraînement:  80%|████████  | 8047/10000 [25:48<06:12,  5.24step/s, loss=0.030425, elapsed=25.8min]

Entraînement:  80%|████████  | 8047/10000 [25:48<06:12,  5.24step/s, loss=0.053021, elapsed=25.8min]

Entraînement:  80%|████████  | 8048/10000 [25:48<06:12,  5.24step/s, loss=0.053021, elapsed=25.8min]

Entraînement:  80%|████████  | 8048/10000 [25:48<06:12,  5.24step/s, loss=0.081066, elapsed=25.8min]

Entraînement:  80%|████████  | 8049/10000 [25:48<06:13,  5.23step/s, loss=0.081066, elapsed=25.8min]

Entraînement:  80%|████████  | 8049/10000 [25:48<06:13,  5.23step/s, loss=0.155429, elapsed=25.8min]

Entraînement:  80%|████████  | 8050/10000 [25:48<06:12,  5.23step/s, loss=0.155429, elapsed=25.8min]

Entraînement:  80%|████████  | 8050/10000 [25:48<06:12,  5.23step/s, loss=0.133985, elapsed=25.8min]

Entraînement:  81%|████████  | 8051/10000 [25:49<06:11,  5.25step/s, loss=0.133985, elapsed=25.8min]

Entraînement:  81%|████████  | 8051/10000 [25:49<06:11,  5.25step/s, loss=0.059304, elapsed=25.8min]

Entraînement:  81%|████████  | 8052/10000 [25:49<06:11,  5.24step/s, loss=0.059304, elapsed=25.8min]

Entraînement:  81%|████████  | 8052/10000 [25:49<06:11,  5.24step/s, loss=0.055791, elapsed=25.8min]

Entraînement:  81%|████████  | 8053/10000 [25:49<06:10,  5.25step/s, loss=0.055791, elapsed=25.8min]

Entraînement:  81%|████████  | 8053/10000 [25:49<06:10,  5.25step/s, loss=0.026837, elapsed=25.8min]

Entraînement:  81%|████████  | 8054/10000 [25:49<06:10,  5.25step/s, loss=0.026837, elapsed=25.8min]

Entraînement:  81%|████████  | 8054/10000 [25:49<06:10,  5.25step/s, loss=0.039905, elapsed=25.8min]

Entraînement:  81%|████████  | 8055/10000 [25:49<06:10,  5.25step/s, loss=0.039905, elapsed=25.8min]

Entraînement:  81%|████████  | 8055/10000 [25:49<06:10,  5.25step/s, loss=0.037681, elapsed=25.8min]

Entraînement:  81%|████████  | 8056/10000 [25:50<06:10,  5.25step/s, loss=0.037681, elapsed=25.8min]

Entraînement:  81%|████████  | 8056/10000 [25:50<06:10,  5.25step/s, loss=0.033503, elapsed=25.8min]

Entraînement:  81%|████████  | 8057/10000 [25:50<06:10,  5.24step/s, loss=0.033503, elapsed=25.8min]

Entraînement:  81%|████████  | 8057/10000 [25:50<06:10,  5.24step/s, loss=0.037994, elapsed=25.8min]

Entraînement:  81%|████████  | 8058/10000 [25:50<06:10,  5.25step/s, loss=0.037994, elapsed=25.8min]

Entraînement:  81%|████████  | 8058/10000 [25:50<06:10,  5.25step/s, loss=0.059940, elapsed=25.8min]

Entraînement:  81%|████████  | 8059/10000 [25:50<06:09,  5.25step/s, loss=0.059940, elapsed=25.8min]

Entraînement:  81%|████████  | 8059/10000 [25:50<06:09,  5.25step/s, loss=0.035037, elapsed=25.8min]

Entraînement:  81%|████████  | 8060/10000 [25:50<06:09,  5.25step/s, loss=0.035037, elapsed=25.8min]

Entraînement:  81%|████████  | 8060/10000 [25:50<06:09,  5.25step/s, loss=0.058456, elapsed=25.8min]

Entraînement:  81%|████████  | 8061/10000 [25:50<06:08,  5.26step/s, loss=0.058456, elapsed=25.8min]

Entraînement:  81%|████████  | 8061/10000 [25:50<06:08,  5.26step/s, loss=0.039618, elapsed=25.8min]

Entraînement:  81%|████████  | 8062/10000 [25:51<06:07,  5.27step/s, loss=0.039618, elapsed=25.8min]

Entraînement:  81%|████████  | 8062/10000 [25:51<06:07,  5.27step/s, loss=0.030248, elapsed=25.9min]

Entraînement:  81%|████████  | 8063/10000 [25:51<06:07,  5.27step/s, loss=0.030248, elapsed=25.9min]

Entraînement:  81%|████████  | 8063/10000 [25:51<06:07,  5.27step/s, loss=0.053570, elapsed=25.9min]

Entraînement:  81%|████████  | 8064/10000 [25:51<06:07,  5.27step/s, loss=0.053570, elapsed=25.9min]

Entraînement:  81%|████████  | 8064/10000 [25:51<06:07,  5.27step/s, loss=0.053489, elapsed=25.9min]

Entraînement:  81%|████████  | 8065/10000 [25:51<06:07,  5.27step/s, loss=0.053489, elapsed=25.9min]

Entraînement:  81%|████████  | 8065/10000 [25:51<06:07,  5.27step/s, loss=0.040629, elapsed=25.9min]

Entraînement:  81%|████████  | 8066/10000 [25:51<06:06,  5.28step/s, loss=0.040629, elapsed=25.9min]

Entraînement:  81%|████████  | 8066/10000 [25:51<06:06,  5.28step/s, loss=0.071775, elapsed=25.9min]

Entraînement:  81%|████████  | 8067/10000 [25:52<06:06,  5.27step/s, loss=0.071775, elapsed=25.9min]

Entraînement:  81%|████████  | 8067/10000 [25:52<06:06,  5.27step/s, loss=0.030586, elapsed=25.9min]

Entraînement:  81%|████████  | 8068/10000 [25:52<06:06,  5.27step/s, loss=0.030586, elapsed=25.9min]

Entraînement:  81%|████████  | 8068/10000 [25:52<06:06,  5.27step/s, loss=0.041262, elapsed=25.9min]

Entraînement:  81%|████████  | 8069/10000 [25:52<06:06,  5.28step/s, loss=0.041262, elapsed=25.9min]

Entraînement:  81%|████████  | 8069/10000 [25:52<06:06,  5.28step/s, loss=0.036760, elapsed=25.9min]

Entraînement:  81%|████████  | 8070/10000 [25:52<06:06,  5.27step/s, loss=0.036760, elapsed=25.9min]

Entraînement:  81%|████████  | 8070/10000 [25:52<06:06,  5.27step/s, loss=0.036710, elapsed=25.9min]

Entraînement:  81%|████████  | 8071/10000 [25:52<06:05,  5.27step/s, loss=0.036710, elapsed=25.9min]

Entraînement:  81%|████████  | 8071/10000 [25:52<06:05,  5.27step/s, loss=0.034557, elapsed=25.9min]

Entraînement:  81%|████████  | 8072/10000 [25:53<06:05,  5.27step/s, loss=0.034557, elapsed=25.9min]

Entraînement:  81%|████████  | 8072/10000 [25:53<06:05,  5.27step/s, loss=0.057658, elapsed=25.9min]

Entraînement:  81%|████████  | 8073/10000 [25:53<06:05,  5.27step/s, loss=0.057658, elapsed=25.9min]

Entraînement:  81%|████████  | 8073/10000 [25:53<06:05,  5.27step/s, loss=0.051871, elapsed=25.9min]

Entraînement:  81%|████████  | 8074/10000 [25:53<06:05,  5.27step/s, loss=0.051871, elapsed=25.9min]

Entraînement:  81%|████████  | 8074/10000 [25:53<06:05,  5.27step/s, loss=0.082320, elapsed=25.9min]

Entraînement:  81%|████████  | 8075/10000 [25:53<06:05,  5.27step/s, loss=0.082320, elapsed=25.9min]

Entraînement:  81%|████████  | 8075/10000 [25:53<06:05,  5.27step/s, loss=0.031297, elapsed=25.9min]

Entraînement:  81%|████████  | 8076/10000 [25:53<06:05,  5.26step/s, loss=0.031297, elapsed=25.9min]

Entraînement:  81%|████████  | 8076/10000 [25:53<06:05,  5.26step/s, loss=0.021759, elapsed=25.9min]

Entraînement:  81%|████████  | 8077/10000 [25:54<06:05,  5.26step/s, loss=0.021759, elapsed=25.9min]

Entraînement:  81%|████████  | 8077/10000 [25:54<06:05,  5.26step/s, loss=0.024933, elapsed=25.9min]

Entraînement:  81%|████████  | 8078/10000 [25:54<06:06,  5.24step/s, loss=0.024933, elapsed=25.9min]

Entraînement:  81%|████████  | 8078/10000 [25:54<06:06,  5.24step/s, loss=0.034687, elapsed=25.9min]

Entraînement:  81%|████████  | 8079/10000 [25:54<06:07,  5.23step/s, loss=0.034687, elapsed=25.9min]

Entraînement:  81%|████████  | 8079/10000 [25:54<06:07,  5.23step/s, loss=0.030786, elapsed=25.9min]

Entraînement:  81%|████████  | 8080/10000 [25:54<06:06,  5.24step/s, loss=0.030786, elapsed=25.9min]

Entraînement:  81%|████████  | 8080/10000 [25:54<06:06,  5.24step/s, loss=0.040159, elapsed=25.9min]

Entraînement:  81%|████████  | 8081/10000 [25:54<06:06,  5.23step/s, loss=0.040159, elapsed=25.9min]

Entraînement:  81%|████████  | 8081/10000 [25:54<06:06,  5.23step/s, loss=0.024721, elapsed=25.9min]

Entraînement:  81%|████████  | 8082/10000 [25:54<06:05,  5.25step/s, loss=0.024721, elapsed=25.9min]

Entraînement:  81%|████████  | 8082/10000 [25:54<06:05,  5.25step/s, loss=0.067101, elapsed=25.9min]

Entraînement:  81%|████████  | 8083/10000 [25:55<06:04,  5.25step/s, loss=0.067101, elapsed=25.9min]

Entraînement:  81%|████████  | 8083/10000 [25:55<06:04,  5.25step/s, loss=0.053263, elapsed=25.9min]

Entraînement:  81%|████████  | 8084/10000 [25:55<06:04,  5.26step/s, loss=0.053263, elapsed=25.9min]

Entraînement:  81%|████████  | 8084/10000 [25:55<06:04,  5.26step/s, loss=0.046960, elapsed=25.9min]

Entraînement:  81%|████████  | 8085/10000 [25:55<06:04,  5.26step/s, loss=0.046960, elapsed=25.9min]

Entraînement:  81%|████████  | 8085/10000 [25:55<06:04,  5.26step/s, loss=0.078327, elapsed=25.9min]

Entraînement:  81%|████████  | 8086/10000 [25:55<06:03,  5.26step/s, loss=0.078327, elapsed=25.9min]

Entraînement:  81%|████████  | 8086/10000 [25:55<06:03,  5.26step/s, loss=0.027716, elapsed=25.9min]

Entraînement:  81%|████████  | 8087/10000 [25:55<06:04,  5.25step/s, loss=0.027716, elapsed=25.9min]

Entraînement:  81%|████████  | 8087/10000 [25:55<06:04,  5.25step/s, loss=0.055194, elapsed=25.9min]

Entraînement:  81%|████████  | 8088/10000 [25:56<06:03,  5.26step/s, loss=0.055194, elapsed=25.9min]

Entraînement:  81%|████████  | 8088/10000 [25:56<06:03,  5.26step/s, loss=0.054397, elapsed=25.9min]

Entraînement:  81%|████████  | 8089/10000 [25:56<06:02,  5.27step/s, loss=0.054397, elapsed=25.9min]

Entraînement:  81%|████████  | 8089/10000 [25:56<06:02,  5.27step/s, loss=0.085371, elapsed=25.9min]

Entraînement:  81%|████████  | 8090/10000 [25:56<06:02,  5.27step/s, loss=0.085371, elapsed=25.9min]

Entraînement:  81%|████████  | 8090/10000 [25:56<06:02,  5.27step/s, loss=0.050875, elapsed=25.9min]

Entraînement:  81%|████████  | 8091/10000 [25:56<06:01,  5.28step/s, loss=0.050875, elapsed=25.9min]

Entraînement:  81%|████████  | 8091/10000 [25:56<06:01,  5.28step/s, loss=0.019145, elapsed=25.9min]

Entraînement:  81%|████████  | 8092/10000 [25:56<06:00,  5.29step/s, loss=0.019145, elapsed=25.9min]

Entraînement:  81%|████████  | 8092/10000 [25:56<06:00,  5.29step/s, loss=0.031705, elapsed=25.9min]

Entraînement:  81%|████████  | 8093/10000 [25:57<06:01,  5.28step/s, loss=0.031705, elapsed=25.9min]

Entraînement:  81%|████████  | 8093/10000 [25:57<06:01,  5.28step/s, loss=0.025395, elapsed=26.0min]

Entraînement:  81%|████████  | 8094/10000 [25:57<06:00,  5.28step/s, loss=0.025395, elapsed=26.0min]

Entraînement:  81%|████████  | 8094/10000 [25:57<06:00,  5.28step/s, loss=0.035429, elapsed=26.0min]

Entraînement:  81%|████████  | 8095/10000 [25:57<06:00,  5.28step/s, loss=0.035429, elapsed=26.0min]

Entraînement:  81%|████████  | 8095/10000 [25:57<06:00,  5.28step/s, loss=0.057348, elapsed=26.0min]

Entraînement:  81%|████████  | 8096/10000 [25:57<06:00,  5.28step/s, loss=0.057348, elapsed=26.0min]

Entraînement:  81%|████████  | 8096/10000 [25:57<06:00,  5.28step/s, loss=0.098083, elapsed=26.0min]

Entraînement:  81%|████████  | 8097/10000 [25:57<06:00,  5.28step/s, loss=0.098083, elapsed=26.0min]

Entraînement:  81%|████████  | 8097/10000 [25:57<06:00,  5.28step/s, loss=0.104617, elapsed=26.0min]

Entraînement:  81%|████████  | 8098/10000 [25:58<06:00,  5.27step/s, loss=0.104617, elapsed=26.0min]

Entraînement:  81%|████████  | 8098/10000 [25:58<06:00,  5.27step/s, loss=0.045183, elapsed=26.0min]

Entraînement:  81%|████████  | 8099/10000 [25:58<06:00,  5.28step/s, loss=0.045183, elapsed=26.0min]

Entraînement:  81%|████████  | 8099/10000 [25:58<06:00,  5.28step/s, loss=0.029046, elapsed=26.0min]

Entraînement:  81%|████████  | 8100/10000 [25:58<06:00,  5.27step/s, loss=0.029046, elapsed=26.0min]

Entraînement:  81%|████████  | 8100/10000 [25:58<06:00,  5.27step/s, loss=0.154709, elapsed=26.0min]

Entraînement:  81%|████████  | 8100/10000 [25:58<06:00,  5.27step/s, loss=0.154709, elapsed=26.0min]

Entraînement:  81%|████████  | 8101/10000 [25:58<06:03,  5.23step/s, loss=0.154709, elapsed=26.0min]

Entraînement:  81%|████████  | 8101/10000 [25:58<06:03,  5.23step/s, loss=0.095626, elapsed=26.0min]

Step 8100/10000 | Train loss: 0.154709 | Elapsed: 26.0min | ETA: 6.1min

Entraînement:  81%|████████  | 8102/10000 [25:58<06:03,  5.23step/s, loss=0.095626, elapsed=26.0min]

Entraînement:  81%|████████  | 8102/10000 [25:58<06:03,  5.23step/s, loss=0.074342, elapsed=26.0min]

Entraînement:  81%|████████  | 8103/10000 [25:58<06:07,  5.17step/s, loss=0.074342, elapsed=26.0min]

Entraînement:  81%|████████  | 8103/10000 [25:58<06:07,  5.17step/s, loss=0.029047, elapsed=26.0min]

Entraînement:  81%|████████  | 8104/10000 [25:59<06:04,  5.20step/s, loss=0.029047, elapsed=26.0min]

Entraînement:  81%|████████  | 8104/10000 [25:59<06:04,  5.20step/s, loss=0.050105, elapsed=26.0min]

Entraînement:  81%|████████  | 8105/10000 [25:59<06:02,  5.22step/s, loss=0.050105, elapsed=26.0min]

Entraînement:  81%|████████  | 8105/10000 [25:59<06:02,  5.22step/s, loss=0.031056, elapsed=26.0min]

Entraînement:  81%|████████  | 8106/10000 [25:59<06:01,  5.24step/s, loss=0.031056, elapsed=26.0min]

Entraînement:  81%|████████  | 8106/10000 [25:59<06:01,  5.24step/s, loss=0.020224, elapsed=26.0min]

Entraînement:  81%|████████  | 8107/10000 [25:59<06:00,  5.25step/s, loss=0.020224, elapsed=26.0min]

Entraînement:  81%|████████  | 8107/10000 [25:59<06:00,  5.25step/s, loss=0.063626, elapsed=26.0min]

Entraînement:  81%|████████  | 8108/10000 [25:59<06:00,  5.25step/s, loss=0.063626, elapsed=26.0min]

Entraînement:  81%|████████  | 8108/10000 [25:59<06:00,  5.25step/s, loss=0.021080, elapsed=26.0min]

Entraînement:  81%|████████  | 8109/10000 [26:00<05:59,  5.26step/s, loss=0.021080, elapsed=26.0min]

Entraînement:  81%|████████  | 8109/10000 [26:00<05:59,  5.26step/s, loss=0.048922, elapsed=26.0min]

Entraînement:  81%|████████  | 8110/10000 [26:00<05:59,  5.26step/s, loss=0.048922, elapsed=26.0min]

Entraînement:  81%|████████  | 8110/10000 [26:00<05:59,  5.26step/s, loss=0.022741, elapsed=26.0min]

Entraînement:  81%|████████  | 8111/10000 [26:00<08:57,  3.51step/s, loss=0.022741, elapsed=26.0min]

Entraînement:  81%|████████  | 8111/10000 [26:00<08:57,  3.51step/s, loss=0.015215, elapsed=26.0min]

Entraînement:  81%|████████  | 8112/10000 [26:01<08:06,  3.88step/s, loss=0.015215, elapsed=26.0min]

Entraînement:  81%|████████  | 8112/10000 [26:01<08:06,  3.88step/s, loss=0.063396, elapsed=26.0min]

Entraînement:  81%|████████  | 8113/10000 [26:01<07:27,  4.22step/s, loss=0.063396, elapsed=26.0min]

Entraînement:  81%|████████  | 8113/10000 [26:01<07:27,  4.22step/s, loss=0.026770, elapsed=26.0min]

Entraînement:  81%|████████  | 8114/10000 [26:01<07:00,  4.48step/s, loss=0.026770, elapsed=26.0min]

Entraînement:  81%|████████  | 8114/10000 [26:01<07:00,  4.48step/s, loss=0.035172, elapsed=26.0min]

Entraînement:  81%|████████  | 8115/10000 [26:01<06:41,  4.69step/s, loss=0.035172, elapsed=26.0min]

Entraînement:  81%|████████  | 8115/10000 [26:01<06:41,  4.69step/s, loss=0.021998, elapsed=26.0min]

Entraînement:  81%|████████  | 8116/10000 [26:01<06:27,  4.86step/s, loss=0.021998, elapsed=26.0min]

Entraînement:  81%|████████  | 8116/10000 [26:01<06:27,  4.86step/s, loss=0.021625, elapsed=26.0min]

Entraînement:  81%|████████  | 8117/10000 [26:01<06:18,  4.98step/s, loss=0.021625, elapsed=26.0min]

Entraînement:  81%|████████  | 8117/10000 [26:01<06:18,  4.98step/s, loss=0.016178, elapsed=26.0min]

Entraînement:  81%|████████  | 8118/10000 [26:02<06:11,  5.06step/s, loss=0.016178, elapsed=26.0min]

Entraînement:  81%|████████  | 8118/10000 [26:02<06:11,  5.06step/s, loss=0.028739, elapsed=26.0min]

Entraînement:  81%|████████  | 8119/10000 [26:02<06:07,  5.12step/s, loss=0.028739, elapsed=26.0min]

Entraînement:  81%|████████  | 8119/10000 [26:02<06:07,  5.12step/s, loss=0.041236, elapsed=26.0min]

Entraînement:  81%|████████  | 8120/10000 [26:02<06:03,  5.17step/s, loss=0.041236, elapsed=26.0min]

Entraînement:  81%|████████  | 8120/10000 [26:02<06:03,  5.17step/s, loss=0.032183, elapsed=26.0min]

Entraînement:  81%|████████  | 8121/10000 [26:02<06:01,  5.20step/s, loss=0.032183, elapsed=26.0min]

Entraînement:  81%|████████  | 8121/10000 [26:02<06:01,  5.20step/s, loss=0.059587, elapsed=26.0min]

Entraînement:  81%|████████  | 8122/10000 [26:02<05:59,  5.22step/s, loss=0.059587, elapsed=26.0min]

Entraînement:  81%|████████  | 8122/10000 [26:02<05:59,  5.22step/s, loss=0.024081, elapsed=26.0min]

Entraînement:  81%|████████  | 8123/10000 [26:03<05:57,  5.24step/s, loss=0.024081, elapsed=26.0min]

Entraînement:  81%|████████  | 8123/10000 [26:03<05:57,  5.24step/s, loss=0.031362, elapsed=26.1min]

Entraînement:  81%|████████  | 8124/10000 [26:03<05:57,  5.25step/s, loss=0.031362, elapsed=26.1min]

Entraînement:  81%|████████  | 8124/10000 [26:03<05:57,  5.25step/s, loss=0.043361, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8125/10000 [26:03<05:56,  5.26step/s, loss=0.043361, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8125/10000 [26:03<05:56,  5.26step/s, loss=0.040426, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8126/10000 [26:03<05:57,  5.24step/s, loss=0.040426, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8126/10000 [26:03<05:57,  5.24step/s, loss=0.117444, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8127/10000 [26:03<05:56,  5.26step/s, loss=0.117444, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8127/10000 [26:03<05:56,  5.26step/s, loss=0.034624, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8128/10000 [26:04<05:56,  5.26step/s, loss=0.034624, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8128/10000 [26:04<05:56,  5.26step/s, loss=0.021689, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8129/10000 [26:04<05:55,  5.26step/s, loss=0.021689, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8129/10000 [26:04<05:55,  5.26step/s, loss=0.037316, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8130/10000 [26:04<05:55,  5.26step/s, loss=0.037316, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8130/10000 [26:04<05:55,  5.26step/s, loss=0.047402, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8131/10000 [26:04<05:54,  5.27step/s, loss=0.047402, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8131/10000 [26:04<05:54,  5.27step/s, loss=0.046113, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8132/10000 [26:04<05:54,  5.26step/s, loss=0.046113, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8132/10000 [26:04<05:54,  5.26step/s, loss=0.030816, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8133/10000 [26:04<05:54,  5.26step/s, loss=0.030816, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8133/10000 [26:04<05:54,  5.26step/s, loss=0.105093, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8134/10000 [26:05<05:54,  5.26step/s, loss=0.105093, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8134/10000 [26:05<05:54,  5.26step/s, loss=0.051437, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8135/10000 [26:05<05:54,  5.27step/s, loss=0.051437, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8135/10000 [26:05<05:54,  5.27step/s, loss=0.055774, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8136/10000 [26:05<05:53,  5.27step/s, loss=0.055774, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8136/10000 [26:05<05:53,  5.27step/s, loss=0.046389, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8137/10000 [26:05<05:53,  5.27step/s, loss=0.046389, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8137/10000 [26:05<05:53,  5.27step/s, loss=0.060418, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8138/10000 [26:05<05:52,  5.28step/s, loss=0.060418, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8138/10000 [26:05<05:52,  5.28step/s, loss=0.053665, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8139/10000 [26:06<05:52,  5.29step/s, loss=0.053665, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8139/10000 [26:06<05:52,  5.29step/s, loss=0.041940, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8140/10000 [26:06<05:52,  5.28step/s, loss=0.041940, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8140/10000 [26:06<05:52,  5.28step/s, loss=0.045073, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8141/10000 [26:06<05:51,  5.28step/s, loss=0.045073, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8141/10000 [26:06<05:51,  5.28step/s, loss=0.042061, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8142/10000 [26:06<05:52,  5.28step/s, loss=0.042061, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8142/10000 [26:06<05:52,  5.28step/s, loss=0.051096, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8143/10000 [26:06<05:51,  5.28step/s, loss=0.051096, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8143/10000 [26:06<05:51,  5.28step/s, loss=0.040262, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8144/10000 [26:07<05:51,  5.29step/s, loss=0.040262, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8144/10000 [26:07<05:51,  5.29step/s, loss=0.102006, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8145/10000 [26:07<05:50,  5.29step/s, loss=0.102006, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8145/10000 [26:07<05:50,  5.29step/s, loss=0.033696, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8146/10000 [26:07<05:50,  5.29step/s, loss=0.033696, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8146/10000 [26:07<05:50,  5.29step/s, loss=0.045731, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8147/10000 [26:07<05:50,  5.29step/s, loss=0.045731, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8147/10000 [26:07<05:50,  5.29step/s, loss=0.039501, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8148/10000 [26:07<05:50,  5.29step/s, loss=0.039501, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8148/10000 [26:07<05:50,  5.29step/s, loss=0.033753, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8149/10000 [26:08<05:50,  5.28step/s, loss=0.033753, elapsed=26.1min]

Entraînement:  81%|████████▏ | 8149/10000 [26:08<05:50,  5.28step/s, loss=0.042898, elapsed=26.1min]

Entraînement:  82%|████████▏ | 8150/10000 [26:08<05:51,  5.26step/s, loss=0.042898, elapsed=26.1min]

Entraînement:  82%|████████▏ | 8150/10000 [26:08<05:51,  5.26step/s, loss=0.108580, elapsed=26.1min]

Entraînement:  82%|████████▏ | 8151/10000 [26:08<05:50,  5.27step/s, loss=0.108580, elapsed=26.1min]

Entraînement:  82%|████████▏ | 8151/10000 [26:08<05:50,  5.27step/s, loss=0.047704, elapsed=26.1min]

Entraînement:  82%|████████▏ | 8152/10000 [26:08<05:50,  5.27step/s, loss=0.047704, elapsed=26.1min]

Entraînement:  82%|████████▏ | 8152/10000 [26:08<05:50,  5.27step/s, loss=0.034721, elapsed=26.1min]

Entraînement:  82%|████████▏ | 8153/10000 [26:08<05:49,  5.28step/s, loss=0.034721, elapsed=26.1min]

Entraînement:  82%|████████▏ | 8153/10000 [26:08<05:49,  5.28step/s, loss=0.122387, elapsed=26.1min]

Entraînement:  82%|████████▏ | 8154/10000 [26:08<05:49,  5.28step/s, loss=0.122387, elapsed=26.1min]

Entraînement:  82%|████████▏ | 8154/10000 [26:08<05:49,  5.28step/s, loss=0.081966, elapsed=26.1min]

Entraînement:  82%|████████▏ | 8155/10000 [26:09<05:49,  5.28step/s, loss=0.081966, elapsed=26.1min]

Entraînement:  82%|████████▏ | 8155/10000 [26:09<05:49,  5.28step/s, loss=0.030490, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8156/10000 [26:09<05:49,  5.27step/s, loss=0.030490, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8156/10000 [26:09<05:49,  5.27step/s, loss=0.041659, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8157/10000 [26:09<05:49,  5.27step/s, loss=0.041659, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8157/10000 [26:09<05:49,  5.27step/s, loss=0.093808, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8158/10000 [26:09<05:50,  5.26step/s, loss=0.093808, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8158/10000 [26:09<05:50,  5.26step/s, loss=0.091960, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8159/10000 [26:09<05:49,  5.26step/s, loss=0.091960, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8159/10000 [26:09<05:49,  5.26step/s, loss=0.030938, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8160/10000 [26:10<05:51,  5.24step/s, loss=0.030938, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8160/10000 [26:10<05:51,  5.24step/s, loss=0.028400, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8161/10000 [26:10<05:50,  5.25step/s, loss=0.028400, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8161/10000 [26:10<05:50,  5.25step/s, loss=0.022464, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8162/10000 [26:10<05:49,  5.26step/s, loss=0.022464, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8162/10000 [26:10<05:49,  5.26step/s, loss=0.071170, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8163/10000 [26:10<05:49,  5.26step/s, loss=0.071170, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8163/10000 [26:10<05:49,  5.26step/s, loss=0.045773, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8164/10000 [26:10<05:48,  5.27step/s, loss=0.045773, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8164/10000 [26:10<05:48,  5.27step/s, loss=0.033739, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8165/10000 [26:11<05:48,  5.27step/s, loss=0.033739, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8165/10000 [26:11<05:48,  5.27step/s, loss=0.022204, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8166/10000 [26:11<05:47,  5.27step/s, loss=0.022204, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8166/10000 [26:11<05:47,  5.27step/s, loss=0.030738, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8167/10000 [26:11<05:45,  5.30step/s, loss=0.030738, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8167/10000 [26:11<05:45,  5.30step/s, loss=0.049356, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8168/10000 [26:11<05:46,  5.29step/s, loss=0.049356, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8168/10000 [26:11<05:46,  5.29step/s, loss=0.051164, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8169/10000 [26:11<05:46,  5.29step/s, loss=0.051164, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8169/10000 [26:11<05:46,  5.29step/s, loss=0.032755, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8170/10000 [26:11<05:46,  5.29step/s, loss=0.032755, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8170/10000 [26:12<05:46,  5.29step/s, loss=0.016565, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8171/10000 [26:12<05:45,  5.29step/s, loss=0.016565, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8171/10000 [26:12<05:45,  5.29step/s, loss=0.106643, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8172/10000 [26:12<05:46,  5.28step/s, loss=0.106643, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8172/10000 [26:12<05:46,  5.28step/s, loss=0.039272, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8173/10000 [26:12<05:46,  5.28step/s, loss=0.039272, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8173/10000 [26:12<05:46,  5.28step/s, loss=0.081979, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8174/10000 [26:12<05:45,  5.28step/s, loss=0.081979, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8174/10000 [26:12<05:45,  5.28step/s, loss=0.016539, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8175/10000 [26:12<05:45,  5.28step/s, loss=0.016539, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8175/10000 [26:12<05:45,  5.28step/s, loss=0.041106, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8176/10000 [26:13<05:44,  5.29step/s, loss=0.041106, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8176/10000 [26:13<05:44,  5.29step/s, loss=0.037266, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8177/10000 [26:13<05:44,  5.29step/s, loss=0.037266, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8177/10000 [26:13<05:44,  5.29step/s, loss=0.029760, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8178/10000 [26:13<05:44,  5.29step/s, loss=0.029760, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8178/10000 [26:13<05:44,  5.29step/s, loss=0.022220, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8179/10000 [26:13<05:45,  5.27step/s, loss=0.022220, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8179/10000 [26:13<05:45,  5.27step/s, loss=0.024332, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8180/10000 [26:13<05:49,  5.21step/s, loss=0.024332, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8180/10000 [26:13<05:49,  5.21step/s, loss=0.046705, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8181/10000 [26:14<05:48,  5.22step/s, loss=0.046705, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8181/10000 [26:14<05:48,  5.22step/s, loss=0.031089, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8182/10000 [26:14<05:47,  5.24step/s, loss=0.031089, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8182/10000 [26:14<05:47,  5.24step/s, loss=0.130294, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8183/10000 [26:14<05:48,  5.22step/s, loss=0.130294, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8183/10000 [26:14<05:48,  5.22step/s, loss=0.074823, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8184/10000 [26:14<05:46,  5.23step/s, loss=0.074823, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8184/10000 [26:14<05:46,  5.23step/s, loss=0.073129, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8185/10000 [26:14<05:46,  5.24step/s, loss=0.073129, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8185/10000 [26:14<05:46,  5.24step/s, loss=0.094816, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8186/10000 [26:15<05:47,  5.23step/s, loss=0.094816, elapsed=26.2min]

Entraînement:  82%|████████▏ | 8186/10000 [26:15<05:47,  5.23step/s, loss=0.032276, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8187/10000 [26:15<05:46,  5.23step/s, loss=0.032276, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8187/10000 [26:15<05:46,  5.23step/s, loss=0.069817, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8188/10000 [26:15<05:45,  5.24step/s, loss=0.069817, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8188/10000 [26:15<05:45,  5.24step/s, loss=0.038691, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8189/10000 [26:15<05:45,  5.24step/s, loss=0.038691, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8189/10000 [26:15<05:45,  5.24step/s, loss=0.053304, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8190/10000 [26:15<05:45,  5.24step/s, loss=0.053304, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8190/10000 [26:15<05:45,  5.24step/s, loss=0.034743, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8191/10000 [26:16<05:45,  5.24step/s, loss=0.034743, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8191/10000 [26:16<05:45,  5.24step/s, loss=0.024497, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8192/10000 [26:16<05:44,  5.24step/s, loss=0.024497, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8192/10000 [26:16<05:44,  5.24step/s, loss=0.093451, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8193/10000 [26:16<05:44,  5.24step/s, loss=0.093451, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8193/10000 [26:16<05:44,  5.24step/s, loss=0.043246, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8194/10000 [26:16<05:44,  5.24step/s, loss=0.043246, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8194/10000 [26:16<05:44,  5.24step/s, loss=0.101675, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8195/10000 [26:16<05:44,  5.24step/s, loss=0.101675, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8195/10000 [26:16<05:44,  5.24step/s, loss=0.024299, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8196/10000 [26:16<05:43,  5.24step/s, loss=0.024299, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8196/10000 [26:16<05:43,  5.24step/s, loss=0.091904, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8197/10000 [26:17<05:44,  5.23step/s, loss=0.091904, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8197/10000 [26:17<05:44,  5.23step/s, loss=0.072309, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8198/10000 [26:17<05:43,  5.25step/s, loss=0.072309, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8198/10000 [26:17<05:43,  5.25step/s, loss=0.021650, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8199/10000 [26:17<05:42,  5.25step/s, loss=0.021650, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8199/10000 [26:17<05:42,  5.25step/s, loss=0.046019, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8200/10000 [26:17<05:42,  5.25step/s, loss=0.046019, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8200/10000 [26:17<05:42,  5.25step/s, loss=0.043454, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8200/10000 [26:17<05:42,  5.25step/s, loss=0.043454, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8201/10000 [26:17<05:46,  5.19step/s, loss=0.043454, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8201/10000 [26:17<05:46,  5.19step/s, loss=0.035097, elapsed=26.3min]

Step 8200/10000 | Train loss: 0.043454 | Elapsed: 26.3min | ETA: 5.8min

Entraînement:  82%|████████▏ | 8202/10000 [26:18<05:45,  5.21step/s, loss=0.035097, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8202/10000 [26:18<05:45,  5.21step/s, loss=0.047391, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8203/10000 [26:18<05:42,  5.24step/s, loss=0.047391, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8203/10000 [26:18<05:42,  5.24step/s, loss=0.055243, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8204/10000 [26:18<05:42,  5.24step/s, loss=0.055243, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8204/10000 [26:18<05:42,  5.24step/s, loss=0.060629, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8205/10000 [26:18<05:42,  5.24step/s, loss=0.060629, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8205/10000 [26:18<05:42,  5.24step/s, loss=0.037501, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8206/10000 [26:18<05:42,  5.24step/s, loss=0.037501, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8206/10000 [26:18<05:42,  5.24step/s, loss=0.042222, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8207/10000 [26:19<05:40,  5.26step/s, loss=0.042222, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8207/10000 [26:19<05:40,  5.26step/s, loss=0.057789, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8208/10000 [26:19<05:38,  5.29step/s, loss=0.057789, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8208/10000 [26:19<05:38,  5.29step/s, loss=0.026755, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8209/10000 [26:19<05:36,  5.32step/s, loss=0.026755, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8209/10000 [26:19<05:36,  5.32step/s, loss=0.041306, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8210/10000 [26:19<05:35,  5.33step/s, loss=0.041306, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8210/10000 [26:19<05:35,  5.33step/s, loss=0.100712, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8211/10000 [26:19<05:35,  5.33step/s, loss=0.100712, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8211/10000 [26:19<05:35,  5.33step/s, loss=0.031266, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8212/10000 [26:19<05:35,  5.33step/s, loss=0.031266, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8212/10000 [26:19<05:35,  5.33step/s, loss=0.047324, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8213/10000 [26:20<05:36,  5.30step/s, loss=0.047324, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8213/10000 [26:20<05:36,  5.30step/s, loss=0.038295, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8214/10000 [26:20<05:37,  5.29step/s, loss=0.038295, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8214/10000 [26:20<05:37,  5.29step/s, loss=0.056739, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8215/10000 [26:20<05:38,  5.28step/s, loss=0.056739, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8215/10000 [26:20<05:38,  5.28step/s, loss=0.014549, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8216/10000 [26:20<05:38,  5.27step/s, loss=0.014549, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8216/10000 [26:20<05:38,  5.27step/s, loss=0.027455, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8217/10000 [26:20<05:38,  5.26step/s, loss=0.027455, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8217/10000 [26:20<05:38,  5.26step/s, loss=0.039072, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8218/10000 [26:21<05:38,  5.26step/s, loss=0.039072, elapsed=26.3min]

Entraînement:  82%|████████▏ | 8218/10000 [26:21<05:38,  5.26step/s, loss=0.076304, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8219/10000 [26:21<05:38,  5.26step/s, loss=0.076304, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8219/10000 [26:21<05:38,  5.26step/s, loss=0.035867, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8220/10000 [26:21<05:38,  5.26step/s, loss=0.035867, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8220/10000 [26:21<05:38,  5.26step/s, loss=0.023960, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8221/10000 [26:21<05:38,  5.26step/s, loss=0.023960, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8221/10000 [26:21<05:38,  5.26step/s, loss=0.023913, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8222/10000 [26:21<05:38,  5.26step/s, loss=0.023913, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8222/10000 [26:21<05:38,  5.26step/s, loss=0.028769, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8223/10000 [26:22<05:38,  5.25step/s, loss=0.028769, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8223/10000 [26:22<05:38,  5.25step/s, loss=0.033200, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8224/10000 [26:22<05:37,  5.26step/s, loss=0.033200, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8224/10000 [26:22<05:37,  5.26step/s, loss=0.019366, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8225/10000 [26:22<05:38,  5.24step/s, loss=0.019366, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8225/10000 [26:22<05:38,  5.24step/s, loss=0.075125, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8226/10000 [26:22<05:38,  5.24step/s, loss=0.075125, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8226/10000 [26:22<05:38,  5.24step/s, loss=0.086920, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8227/10000 [26:22<05:38,  5.24step/s, loss=0.086920, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8227/10000 [26:22<05:38,  5.24step/s, loss=0.048913, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8228/10000 [26:23<05:37,  5.26step/s, loss=0.048913, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8228/10000 [26:23<05:37,  5.26step/s, loss=0.027681, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8229/10000 [26:23<05:38,  5.24step/s, loss=0.027681, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8229/10000 [26:23<05:38,  5.24step/s, loss=0.061095, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8230/10000 [26:23<05:37,  5.24step/s, loss=0.061095, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8230/10000 [26:23<05:37,  5.24step/s, loss=0.074530, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8231/10000 [26:23<05:36,  5.26step/s, loss=0.074530, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8231/10000 [26:23<05:36,  5.26step/s, loss=0.039361, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8232/10000 [26:23<05:36,  5.26step/s, loss=0.039361, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8232/10000 [26:23<05:36,  5.26step/s, loss=0.056869, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8233/10000 [26:23<05:36,  5.26step/s, loss=0.056869, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8233/10000 [26:23<05:36,  5.26step/s, loss=0.056745, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8234/10000 [26:24<05:35,  5.26step/s, loss=0.056745, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8234/10000 [26:24<05:35,  5.26step/s, loss=0.073694, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8235/10000 [26:24<05:36,  5.25step/s, loss=0.073694, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8235/10000 [26:24<05:36,  5.25step/s, loss=0.025798, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8236/10000 [26:24<05:36,  5.25step/s, loss=0.025798, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8236/10000 [26:24<05:36,  5.25step/s, loss=0.032230, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8237/10000 [26:24<05:35,  5.26step/s, loss=0.032230, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8237/10000 [26:24<05:35,  5.26step/s, loss=0.059736, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8238/10000 [26:24<05:35,  5.25step/s, loss=0.059736, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8238/10000 [26:24<05:35,  5.25step/s, loss=0.025941, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8239/10000 [26:25<05:35,  5.26step/s, loss=0.025941, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8239/10000 [26:25<05:35,  5.26step/s, loss=0.043536, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8240/10000 [26:25<05:34,  5.26step/s, loss=0.043536, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8240/10000 [26:25<05:34,  5.26step/s, loss=0.057004, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8241/10000 [26:25<05:34,  5.26step/s, loss=0.057004, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8241/10000 [26:25<05:34,  5.26step/s, loss=0.034424, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8242/10000 [26:25<05:33,  5.26step/s, loss=0.034424, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8242/10000 [26:25<05:33,  5.26step/s, loss=0.063089, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8243/10000 [26:25<05:35,  5.23step/s, loss=0.063089, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8243/10000 [26:25<05:35,  5.23step/s, loss=0.096307, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8244/10000 [26:26<05:35,  5.23step/s, loss=0.096307, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8244/10000 [26:26<05:35,  5.23step/s, loss=0.026717, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8245/10000 [26:26<05:34,  5.24step/s, loss=0.026717, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8245/10000 [26:26<05:34,  5.24step/s, loss=0.063618, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8246/10000 [26:26<05:33,  5.25step/s, loss=0.063618, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8246/10000 [26:26<05:33,  5.25step/s, loss=0.170475, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8247/10000 [26:26<05:33,  5.26step/s, loss=0.170475, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8247/10000 [26:26<05:33,  5.26step/s, loss=0.069827, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8248/10000 [26:26<05:32,  5.26step/s, loss=0.069827, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8248/10000 [26:26<05:32,  5.26step/s, loss=0.047352, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8249/10000 [26:27<05:32,  5.26step/s, loss=0.047352, elapsed=26.4min]

Entraînement:  82%|████████▏ | 8249/10000 [26:27<05:32,  5.26step/s, loss=0.093551, elapsed=26.5min]

Entraînement:  82%|████████▎ | 8250/10000 [26:27<05:32,  5.27step/s, loss=0.093551, elapsed=26.5min]

Entraînement:  82%|████████▎ | 8250/10000 [26:27<05:32,  5.27step/s, loss=0.036522, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8251/10000 [26:27<05:31,  5.27step/s, loss=0.036522, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8251/10000 [26:27<05:31,  5.27step/s, loss=0.138209, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8252/10000 [26:27<05:32,  5.26step/s, loss=0.138209, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8252/10000 [26:27<05:32,  5.26step/s, loss=0.058079, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8253/10000 [26:27<05:32,  5.26step/s, loss=0.058079, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8253/10000 [26:27<05:32,  5.26step/s, loss=0.034686, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8254/10000 [26:27<05:31,  5.27step/s, loss=0.034686, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8254/10000 [26:27<05:31,  5.27step/s, loss=0.035182, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8255/10000 [26:28<05:31,  5.27step/s, loss=0.035182, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8255/10000 [26:28<05:31,  5.27step/s, loss=0.028044, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8256/10000 [26:28<05:30,  5.27step/s, loss=0.028044, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8256/10000 [26:28<05:30,  5.27step/s, loss=0.046851, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8257/10000 [26:28<05:30,  5.28step/s, loss=0.046851, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8257/10000 [26:28<05:30,  5.28step/s, loss=0.114888, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8258/10000 [26:28<05:30,  5.28step/s, loss=0.114888, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8258/10000 [26:28<05:30,  5.28step/s, loss=0.022304, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8259/10000 [26:28<05:29,  5.28step/s, loss=0.022304, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8259/10000 [26:28<05:29,  5.28step/s, loss=0.060702, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8260/10000 [26:29<05:30,  5.27step/s, loss=0.060702, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8260/10000 [26:29<05:30,  5.27step/s, loss=0.054851, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8261/10000 [26:29<05:29,  5.27step/s, loss=0.054851, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8261/10000 [26:29<05:29,  5.27step/s, loss=0.062849, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8262/10000 [26:29<05:30,  5.27step/s, loss=0.062849, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8262/10000 [26:29<05:30,  5.27step/s, loss=0.056909, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8263/10000 [26:29<05:30,  5.26step/s, loss=0.056909, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8263/10000 [26:29<05:30,  5.26step/s, loss=0.030857, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8264/10000 [26:29<05:30,  5.26step/s, loss=0.030857, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8264/10000 [26:29<05:30,  5.26step/s, loss=0.024542, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8265/10000 [26:30<05:29,  5.26step/s, loss=0.024542, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8265/10000 [26:30<05:29,  5.26step/s, loss=0.103282, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8266/10000 [26:30<05:29,  5.27step/s, loss=0.103282, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8266/10000 [26:30<05:29,  5.27step/s, loss=0.029221, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8267/10000 [26:30<05:28,  5.27step/s, loss=0.029221, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8267/10000 [26:30<05:28,  5.27step/s, loss=0.052065, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8268/10000 [26:30<05:28,  5.28step/s, loss=0.052065, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8268/10000 [26:30<05:28,  5.28step/s, loss=0.030208, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8269/10000 [26:30<05:28,  5.26step/s, loss=0.030208, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8269/10000 [26:30<05:28,  5.26step/s, loss=0.087521, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8270/10000 [26:31<05:28,  5.27step/s, loss=0.087521, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8270/10000 [26:31<05:28,  5.27step/s, loss=0.040389, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8271/10000 [26:31<05:27,  5.28step/s, loss=0.040389, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8271/10000 [26:31<05:27,  5.28step/s, loss=0.031093, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8272/10000 [26:31<05:27,  5.27step/s, loss=0.031093, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8272/10000 [26:31<05:27,  5.27step/s, loss=0.033104, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8273/10000 [26:31<05:27,  5.28step/s, loss=0.033104, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8273/10000 [26:31<05:27,  5.28step/s, loss=0.050320, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8274/10000 [26:31<05:28,  5.25step/s, loss=0.050320, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8274/10000 [26:31<05:28,  5.25step/s, loss=0.018592, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8275/10000 [26:31<05:27,  5.26step/s, loss=0.018592, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8275/10000 [26:31<05:27,  5.26step/s, loss=0.058465, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8276/10000 [26:32<05:27,  5.26step/s, loss=0.058465, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8276/10000 [26:32<05:27,  5.26step/s, loss=0.024097, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8277/10000 [26:32<05:27,  5.26step/s, loss=0.024097, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8277/10000 [26:32<05:27,  5.26step/s, loss=0.058553, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8278/10000 [26:32<05:27,  5.26step/s, loss=0.058553, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8278/10000 [26:32<05:27,  5.26step/s, loss=0.027571, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8279/10000 [26:32<05:26,  5.27step/s, loss=0.027571, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8279/10000 [26:32<05:26,  5.27step/s, loss=0.042482, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8280/10000 [26:32<05:25,  5.28step/s, loss=0.042482, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8280/10000 [26:32<05:25,  5.28step/s, loss=0.038712, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8281/10000 [26:33<05:25,  5.29step/s, loss=0.038712, elapsed=26.5min]

Entraînement:  83%|████████▎ | 8281/10000 [26:33<05:25,  5.29step/s, loss=0.034398, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8282/10000 [26:33<05:24,  5.30step/s, loss=0.034398, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8282/10000 [26:33<05:24,  5.30step/s, loss=0.043898, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8283/10000 [26:33<05:23,  5.31step/s, loss=0.043898, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8283/10000 [26:33<05:23,  5.31step/s, loss=0.027470, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8284/10000 [26:33<05:23,  5.30step/s, loss=0.027470, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8284/10000 [26:33<05:23,  5.30step/s, loss=0.031288, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8285/10000 [26:33<05:23,  5.29step/s, loss=0.031288, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8285/10000 [26:33<05:23,  5.29step/s, loss=0.038302, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8286/10000 [26:34<05:24,  5.28step/s, loss=0.038302, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8286/10000 [26:34<05:24,  5.28step/s, loss=0.110032, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8287/10000 [26:34<05:23,  5.29step/s, loss=0.110032, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8287/10000 [26:34<05:23,  5.29step/s, loss=0.020271, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8288/10000 [26:34<05:25,  5.26step/s, loss=0.020271, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8288/10000 [26:34<05:25,  5.26step/s, loss=0.055662, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8289/10000 [26:34<05:24,  5.27step/s, loss=0.055662, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8289/10000 [26:34<05:24,  5.27step/s, loss=0.019985, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8290/10000 [26:34<05:24,  5.27step/s, loss=0.019985, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8290/10000 [26:34<05:24,  5.27step/s, loss=0.060555, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8291/10000 [26:34<05:24,  5.27step/s, loss=0.060555, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8291/10000 [26:34<05:24,  5.27step/s, loss=0.043491, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8292/10000 [26:35<05:23,  5.29step/s, loss=0.043491, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8292/10000 [26:35<05:23,  5.29step/s, loss=0.017797, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8293/10000 [26:35<05:23,  5.27step/s, loss=0.017797, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8293/10000 [26:35<05:23,  5.27step/s, loss=0.057481, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8294/10000 [26:35<05:23,  5.28step/s, loss=0.057481, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8294/10000 [26:35<05:23,  5.28step/s, loss=0.098680, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8295/10000 [26:35<05:22,  5.29step/s, loss=0.098680, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8295/10000 [26:35<05:22,  5.29step/s, loss=0.026087, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8296/10000 [26:35<05:22,  5.29step/s, loss=0.026087, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8296/10000 [26:35<05:22,  5.29step/s, loss=0.026224, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8297/10000 [26:36<05:21,  5.29step/s, loss=0.026224, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8297/10000 [26:36<05:21,  5.29step/s, loss=0.028778, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8298/10000 [26:36<05:21,  5.30step/s, loss=0.028778, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8298/10000 [26:36<05:21,  5.30step/s, loss=0.022208, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8299/10000 [26:36<05:21,  5.30step/s, loss=0.022208, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8299/10000 [26:36<05:21,  5.30step/s, loss=0.063768, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8300/10000 [26:36<05:21,  5.29step/s, loss=0.063768, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8300/10000 [26:36<05:21,  5.29step/s, loss=0.050393, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8300/10000 [26:36<05:21,  5.29step/s, loss=0.050393, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8301/10000 [26:36<05:24,  5.23step/s, loss=0.050393, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8301/10000 [26:36<05:24,  5.23step/s, loss=0.040188, elapsed=26.6min]

Step 8300/10000 | Train loss: 0.050393 | Elapsed: 26.6min | ETA: 5.5min

Entraînement:  83%|████████▎ | 8302/10000 [26:37<05:22,  5.26step/s, loss=0.040188, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8302/10000 [26:37<05:22,  5.26step/s, loss=0.078022, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8303/10000 [26:37<05:22,  5.26step/s, loss=0.078022, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8303/10000 [26:37<05:22,  5.26step/s, loss=0.021093, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8304/10000 [26:37<05:22,  5.27step/s, loss=0.021093, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8304/10000 [26:37<05:22,  5.27step/s, loss=0.019457, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8305/10000 [26:37<05:21,  5.27step/s, loss=0.019457, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8305/10000 [26:37<05:21,  5.27step/s, loss=0.082148, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8306/10000 [26:37<05:20,  5.28step/s, loss=0.082148, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8306/10000 [26:37<05:20,  5.28step/s, loss=0.030411, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8307/10000 [26:38<05:20,  5.29step/s, loss=0.030411, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8307/10000 [26:38<05:20,  5.29step/s, loss=0.052588, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8308/10000 [26:38<05:20,  5.28step/s, loss=0.052588, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8308/10000 [26:38<05:20,  5.28step/s, loss=0.022222, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8309/10000 [26:38<05:20,  5.28step/s, loss=0.022222, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8309/10000 [26:38<05:20,  5.28step/s, loss=0.025243, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8310/10000 [26:38<05:20,  5.28step/s, loss=0.025243, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8310/10000 [26:38<05:20,  5.28step/s, loss=0.063111, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8311/10000 [26:38<05:20,  5.28step/s, loss=0.063111, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8311/10000 [26:38<05:20,  5.28step/s, loss=0.020177, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8312/10000 [26:38<05:19,  5.28step/s, loss=0.020177, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8312/10000 [26:38<05:19,  5.28step/s, loss=0.030748, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8313/10000 [26:39<05:19,  5.28step/s, loss=0.030748, elapsed=26.6min]

Entraînement:  83%|████████▎ | 8313/10000 [26:39<05:19,  5.28step/s, loss=0.036564, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8314/10000 [26:39<05:19,  5.28step/s, loss=0.036564, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8314/10000 [26:39<05:19,  5.28step/s, loss=0.065165, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8315/10000 [26:39<05:19,  5.27step/s, loss=0.065165, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8315/10000 [26:39<05:19,  5.27step/s, loss=0.033556, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8316/10000 [26:39<05:19,  5.28step/s, loss=0.033556, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8316/10000 [26:39<05:19,  5.28step/s, loss=0.065281, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8317/10000 [26:39<05:19,  5.27step/s, loss=0.065281, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8317/10000 [26:39<05:19,  5.27step/s, loss=0.026039, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8318/10000 [26:40<05:18,  5.27step/s, loss=0.026039, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8318/10000 [26:40<05:18,  5.27step/s, loss=0.039670, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8319/10000 [26:40<05:17,  5.29step/s, loss=0.039670, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8319/10000 [26:40<05:17,  5.29step/s, loss=0.087896, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8320/10000 [26:40<05:18,  5.27step/s, loss=0.087896, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8320/10000 [26:40<05:18,  5.27step/s, loss=0.054726, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8321/10000 [26:40<05:18,  5.28step/s, loss=0.054726, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8321/10000 [26:40<05:18,  5.28step/s, loss=0.030994, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8322/10000 [26:40<05:17,  5.28step/s, loss=0.030994, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8322/10000 [26:40<05:17,  5.28step/s, loss=0.035600, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8323/10000 [26:41<05:17,  5.28step/s, loss=0.035600, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8323/10000 [26:41<05:17,  5.28step/s, loss=0.050359, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8324/10000 [26:41<05:17,  5.27step/s, loss=0.050359, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8324/10000 [26:41<05:17,  5.27step/s, loss=0.063252, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8325/10000 [26:41<05:17,  5.28step/s, loss=0.063252, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8325/10000 [26:41<05:17,  5.28step/s, loss=0.075446, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8326/10000 [26:41<05:16,  5.28step/s, loss=0.075446, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8326/10000 [26:41<05:16,  5.28step/s, loss=0.030330, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8327/10000 [26:41<05:16,  5.28step/s, loss=0.030330, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8327/10000 [26:41<05:16,  5.28step/s, loss=0.017666, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8328/10000 [26:42<05:16,  5.29step/s, loss=0.017666, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8328/10000 [26:42<05:16,  5.29step/s, loss=0.046393, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8329/10000 [26:42<05:16,  5.29step/s, loss=0.046393, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8329/10000 [26:42<05:16,  5.29step/s, loss=0.025827, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8330/10000 [26:42<05:15,  5.29step/s, loss=0.025827, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8330/10000 [26:42<05:15,  5.29step/s, loss=0.057066, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8331/10000 [26:42<05:16,  5.27step/s, loss=0.057066, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8331/10000 [26:42<05:16,  5.27step/s, loss=0.023183, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8332/10000 [26:42<05:16,  5.28step/s, loss=0.023183, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8332/10000 [26:42<05:16,  5.28step/s, loss=0.025658, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8333/10000 [26:42<05:16,  5.27step/s, loss=0.025658, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8333/10000 [26:42<05:16,  5.27step/s, loss=0.020008, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8334/10000 [26:43<05:15,  5.28step/s, loss=0.020008, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8334/10000 [26:43<05:15,  5.28step/s, loss=0.042386, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8335/10000 [26:43<05:15,  5.28step/s, loss=0.042386, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8335/10000 [26:43<05:15,  5.28step/s, loss=0.059854, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8336/10000 [26:43<05:14,  5.28step/s, loss=0.059854, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8336/10000 [26:43<05:14,  5.28step/s, loss=0.047536, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8337/10000 [26:43<05:14,  5.28step/s, loss=0.047536, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8337/10000 [26:43<05:14,  5.28step/s, loss=0.038945, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8338/10000 [26:43<05:15,  5.27step/s, loss=0.038945, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8338/10000 [26:43<05:15,  5.27step/s, loss=0.043431, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8339/10000 [26:44<05:15,  5.27step/s, loss=0.043431, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8339/10000 [26:44<05:15,  5.27step/s, loss=0.016476, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8340/10000 [26:44<05:15,  5.27step/s, loss=0.016476, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8340/10000 [26:44<05:15,  5.27step/s, loss=0.050912, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8341/10000 [26:44<05:14,  5.27step/s, loss=0.050912, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8341/10000 [26:44<05:14,  5.27step/s, loss=0.052742, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8342/10000 [26:44<05:13,  5.28step/s, loss=0.052742, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8342/10000 [26:44<05:13,  5.28step/s, loss=0.023746, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8343/10000 [26:44<05:14,  5.27step/s, loss=0.023746, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8343/10000 [26:44<05:14,  5.27step/s, loss=0.044808, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8344/10000 [26:45<05:14,  5.27step/s, loss=0.044808, elapsed=26.7min]

Entraînement:  83%|████████▎ | 8344/10000 [26:45<05:14,  5.27step/s, loss=0.029038, elapsed=26.8min]

Entraînement:  83%|████████▎ | 8345/10000 [26:45<05:14,  5.27step/s, loss=0.029038, elapsed=26.8min]

Entraînement:  83%|████████▎ | 8345/10000 [26:45<05:14,  5.27step/s, loss=0.068343, elapsed=26.8min]

Entraînement:  83%|████████▎ | 8346/10000 [26:45<05:13,  5.27step/s, loss=0.068343, elapsed=26.8min]

Entraînement:  83%|████████▎ | 8346/10000 [26:45<05:13,  5.27step/s, loss=0.079388, elapsed=26.8min]

Entraînement:  83%|████████▎ | 8347/10000 [26:45<05:13,  5.27step/s, loss=0.079388, elapsed=26.8min]

Entraînement:  83%|████████▎ | 8347/10000 [26:45<05:13,  5.27step/s, loss=0.041938, elapsed=26.8min]

Entraînement:  83%|████████▎ | 8348/10000 [26:45<05:13,  5.27step/s, loss=0.041938, elapsed=26.8min]

Entraînement:  83%|████████▎ | 8348/10000 [26:45<05:13,  5.27step/s, loss=0.026586, elapsed=26.8min]

Entraînement:  83%|████████▎ | 8349/10000 [26:45<05:12,  5.28step/s, loss=0.026586, elapsed=26.8min]

Entraînement:  83%|████████▎ | 8349/10000 [26:45<05:12,  5.28step/s, loss=0.051808, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8350/10000 [26:46<05:12,  5.28step/s, loss=0.051808, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8350/10000 [26:46<05:12,  5.28step/s, loss=0.064198, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8351/10000 [26:46<05:11,  5.29step/s, loss=0.064198, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8351/10000 [26:46<05:11,  5.29step/s, loss=0.023658, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8352/10000 [26:46<05:11,  5.28step/s, loss=0.023658, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8352/10000 [26:46<05:11,  5.28step/s, loss=0.055524, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8353/10000 [26:46<05:11,  5.29step/s, loss=0.055524, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8353/10000 [26:46<05:11,  5.29step/s, loss=0.030876, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8354/10000 [26:46<05:12,  5.28step/s, loss=0.030876, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8354/10000 [26:46<05:12,  5.28step/s, loss=0.028986, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8355/10000 [26:47<05:11,  5.28step/s, loss=0.028986, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8355/10000 [26:47<05:11,  5.28step/s, loss=0.034781, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8356/10000 [26:47<05:10,  5.29step/s, loss=0.034781, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8356/10000 [26:47<05:10,  5.29step/s, loss=0.032525, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8357/10000 [26:47<05:10,  5.28step/s, loss=0.032525, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8357/10000 [26:47<05:10,  5.28step/s, loss=0.026983, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8358/10000 [26:47<05:10,  5.28step/s, loss=0.026983, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8358/10000 [26:47<05:10,  5.28step/s, loss=0.018102, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8359/10000 [26:47<05:10,  5.28step/s, loss=0.018102, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8359/10000 [26:47<05:10,  5.28step/s, loss=0.018157, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8360/10000 [26:48<05:10,  5.28step/s, loss=0.018157, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8360/10000 [26:48<05:10,  5.28step/s, loss=0.045748, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8361/10000 [26:48<05:10,  5.27step/s, loss=0.045748, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8361/10000 [26:48<05:10,  5.27step/s, loss=0.023635, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8362/10000 [26:48<05:11,  5.26step/s, loss=0.023635, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8362/10000 [26:48<05:11,  5.26step/s, loss=0.025819, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8363/10000 [26:48<05:12,  5.24step/s, loss=0.025819, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8363/10000 [26:48<05:12,  5.24step/s, loss=0.016821, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8364/10000 [26:48<05:11,  5.25step/s, loss=0.016821, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8364/10000 [26:48<05:11,  5.25step/s, loss=0.028815, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8365/10000 [26:49<05:10,  5.27step/s, loss=0.028815, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8365/10000 [26:49<05:10,  5.27step/s, loss=0.018846, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8366/10000 [26:49<05:12,  5.23step/s, loss=0.018846, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8366/10000 [26:49<05:12,  5.23step/s, loss=0.108710, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8367/10000 [26:49<05:10,  5.25step/s, loss=0.108710, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8367/10000 [26:49<05:10,  5.25step/s, loss=0.026511, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8368/10000 [26:49<05:10,  5.26step/s, loss=0.026511, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8368/10000 [26:49<05:10,  5.26step/s, loss=0.026251, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8369/10000 [26:49<05:09,  5.26step/s, loss=0.026251, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8369/10000 [26:49<05:09,  5.26step/s, loss=0.036652, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8370/10000 [26:49<05:09,  5.26step/s, loss=0.036652, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8370/10000 [26:49<05:09,  5.26step/s, loss=0.066278, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8371/10000 [26:50<05:09,  5.26step/s, loss=0.066278, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8371/10000 [26:50<05:09,  5.26step/s, loss=0.037656, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8372/10000 [26:50<05:08,  5.27step/s, loss=0.037656, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8372/10000 [26:50<05:08,  5.27step/s, loss=0.021573, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8373/10000 [26:50<05:08,  5.27step/s, loss=0.021573, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8373/10000 [26:50<05:08,  5.27step/s, loss=0.083782, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8374/10000 [26:50<05:07,  5.28step/s, loss=0.083782, elapsed=26.8min]

Entraînement:  84%|████████▎ | 8374/10000 [26:50<05:07,  5.28step/s, loss=0.080253, elapsed=26.8min]

Entraînement:  84%|████████▍ | 8375/10000 [26:50<05:07,  5.28step/s, loss=0.080253, elapsed=26.8min]

Entraînement:  84%|████████▍ | 8375/10000 [26:50<05:07,  5.28step/s, loss=0.017397, elapsed=26.8min]

Entraînement:  84%|████████▍ | 8376/10000 [26:51<05:07,  5.29step/s, loss=0.017397, elapsed=26.8min]

Entraînement:  84%|████████▍ | 8376/10000 [26:51<05:07,  5.29step/s, loss=0.049188, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8377/10000 [26:51<05:07,  5.28step/s, loss=0.049188, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8377/10000 [26:51<05:07,  5.28step/s, loss=0.021740, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8378/10000 [26:51<05:06,  5.28step/s, loss=0.021740, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8378/10000 [26:51<05:06,  5.28step/s, loss=0.052618, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8379/10000 [26:51<05:06,  5.28step/s, loss=0.052618, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8379/10000 [26:51<05:06,  5.28step/s, loss=0.034803, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8380/10000 [26:51<05:06,  5.28step/s, loss=0.034803, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8380/10000 [26:51<05:06,  5.28step/s, loss=0.043013, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8381/10000 [26:52<05:05,  5.29step/s, loss=0.043013, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8381/10000 [26:52<05:05,  5.29step/s, loss=0.027737, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8382/10000 [26:52<05:05,  5.29step/s, loss=0.027737, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8382/10000 [26:52<05:05,  5.29step/s, loss=0.048888, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8383/10000 [26:52<05:05,  5.30step/s, loss=0.048888, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8383/10000 [26:52<05:05,  5.30step/s, loss=0.018111, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8384/10000 [26:52<05:05,  5.30step/s, loss=0.018111, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8384/10000 [26:52<05:05,  5.30step/s, loss=0.039803, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8385/10000 [26:52<05:05,  5.28step/s, loss=0.039803, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8385/10000 [26:52<05:05,  5.28step/s, loss=0.020894, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8386/10000 [26:52<05:05,  5.29step/s, loss=0.020894, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8386/10000 [26:53<05:05,  5.29step/s, loss=0.077560, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8387/10000 [26:53<05:05,  5.28step/s, loss=0.077560, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8387/10000 [26:53<05:05,  5.28step/s, loss=0.093838, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8388/10000 [26:53<05:05,  5.28step/s, loss=0.093838, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8388/10000 [26:53<05:05,  5.28step/s, loss=0.037630, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8389/10000 [26:53<05:04,  5.28step/s, loss=0.037630, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8389/10000 [26:53<05:04,  5.28step/s, loss=0.020910, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8390/10000 [26:53<05:05,  5.28step/s, loss=0.020910, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8390/10000 [26:53<05:05,  5.28step/s, loss=0.035179, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8391/10000 [26:53<05:05,  5.27step/s, loss=0.035179, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8391/10000 [26:53<05:05,  5.27step/s, loss=0.029833, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8392/10000 [26:54<05:06,  5.25step/s, loss=0.029833, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8392/10000 [26:54<05:06,  5.25step/s, loss=0.040692, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8393/10000 [26:54<05:06,  5.25step/s, loss=0.040692, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8393/10000 [26:54<05:06,  5.25step/s, loss=0.055703, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8394/10000 [26:54<05:05,  5.25step/s, loss=0.055703, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8394/10000 [26:54<05:05,  5.25step/s, loss=0.035650, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8395/10000 [26:54<05:04,  5.26step/s, loss=0.035650, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8395/10000 [26:54<05:04,  5.26step/s, loss=0.067985, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8396/10000 [26:54<05:04,  5.27step/s, loss=0.067985, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8396/10000 [26:54<05:04,  5.27step/s, loss=0.053189, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8397/10000 [26:55<05:03,  5.28step/s, loss=0.053189, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8397/10000 [26:55<05:03,  5.28step/s, loss=0.028267, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8398/10000 [26:55<05:03,  5.28step/s, loss=0.028267, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8398/10000 [26:55<05:03,  5.28step/s, loss=0.035299, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8399/10000 [26:55<05:03,  5.28step/s, loss=0.035299, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8399/10000 [26:55<05:03,  5.28step/s, loss=0.060107, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8400/10000 [26:55<05:03,  5.28step/s, loss=0.060107, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8400/10000 [26:55<05:03,  5.28step/s, loss=0.030342, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8400/10000 [26:55<05:03,  5.28step/s, loss=0.030342, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8401/10000 [26:55<05:05,  5.24step/s, loss=0.030342, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8401/10000 [26:55<05:05,  5.24step/s, loss=0.027856, elapsed=26.9min]

Step 8400/10000 | Train loss: 0.030342 | Elapsed: 26.9min | ETA: 5.1min

Entraînement:  84%|████████▍ | 8402/10000 [26:56<05:05,  5.24step/s, loss=0.027856, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8402/10000 [26:56<05:05,  5.24step/s, loss=0.022631, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8403/10000 [26:56<05:03,  5.25step/s, loss=0.022631, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8403/10000 [26:56<05:03,  5.25step/s, loss=0.115674, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8404/10000 [26:56<05:03,  5.26step/s, loss=0.115674, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8404/10000 [26:56<05:03,  5.26step/s, loss=0.022414, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8405/10000 [26:56<05:02,  5.27step/s, loss=0.022414, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8405/10000 [26:56<05:02,  5.27step/s, loss=0.023244, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8406/10000 [26:56<05:02,  5.28step/s, loss=0.023244, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8406/10000 [26:56<05:02,  5.28step/s, loss=0.046042, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8407/10000 [26:56<05:02,  5.27step/s, loss=0.046042, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8407/10000 [26:56<05:02,  5.27step/s, loss=0.038907, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8408/10000 [26:57<05:02,  5.27step/s, loss=0.038907, elapsed=26.9min]

Entraînement:  84%|████████▍ | 8408/10000 [26:57<05:02,  5.27step/s, loss=0.063196, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8409/10000 [26:57<05:01,  5.27step/s, loss=0.063196, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8409/10000 [26:57<05:01,  5.27step/s, loss=0.020968, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8410/10000 [26:57<05:01,  5.27step/s, loss=0.020968, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8410/10000 [26:57<05:01,  5.27step/s, loss=0.146717, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8411/10000 [26:57<05:01,  5.28step/s, loss=0.146717, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8411/10000 [26:57<05:01,  5.28step/s, loss=0.068308, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8412/10000 [26:57<05:00,  5.28step/s, loss=0.068308, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8412/10000 [26:57<05:00,  5.28step/s, loss=0.049732, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8413/10000 [26:58<05:00,  5.29step/s, loss=0.049732, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8413/10000 [26:58<05:00,  5.29step/s, loss=0.046978, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8414/10000 [26:58<05:00,  5.28step/s, loss=0.046978, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8414/10000 [26:58<05:00,  5.28step/s, loss=0.026543, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8415/10000 [26:58<05:00,  5.27step/s, loss=0.026543, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8415/10000 [26:58<05:00,  5.27step/s, loss=0.057812, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8416/10000 [26:58<05:00,  5.27step/s, loss=0.057812, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8416/10000 [26:58<05:00,  5.27step/s, loss=0.097366, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8417/10000 [26:58<05:00,  5.27step/s, loss=0.097366, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8417/10000 [26:58<05:00,  5.27step/s, loss=0.040401, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8418/10000 [26:59<04:59,  5.27step/s, loss=0.040401, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8418/10000 [26:59<04:59,  5.27step/s, loss=0.052003, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8419/10000 [26:59<04:59,  5.27step/s, loss=0.052003, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8419/10000 [26:59<04:59,  5.27step/s, loss=0.029800, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8420/10000 [26:59<04:59,  5.28step/s, loss=0.029800, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8420/10000 [26:59<04:59,  5.28step/s, loss=0.066955, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8421/10000 [26:59<04:59,  5.28step/s, loss=0.066955, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8421/10000 [26:59<04:59,  5.28step/s, loss=0.059276, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8422/10000 [26:59<05:01,  5.24step/s, loss=0.059276, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8422/10000 [26:59<05:01,  5.24step/s, loss=0.042192, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8423/10000 [27:00<05:00,  5.24step/s, loss=0.042192, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8423/10000 [27:00<05:00,  5.24step/s, loss=0.019417, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8424/10000 [27:00<04:59,  5.26step/s, loss=0.019417, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8424/10000 [27:00<04:59,  5.26step/s, loss=0.109656, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8425/10000 [27:00<04:59,  5.26step/s, loss=0.109656, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8425/10000 [27:00<04:59,  5.26step/s, loss=0.086704, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8426/10000 [27:00<04:58,  5.27step/s, loss=0.086704, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8426/10000 [27:00<04:58,  5.27step/s, loss=0.068907, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8427/10000 [27:00<04:59,  5.26step/s, loss=0.068907, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8427/10000 [27:00<04:59,  5.26step/s, loss=0.017971, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8428/10000 [27:00<04:58,  5.27step/s, loss=0.017971, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8428/10000 [27:00<04:58,  5.27step/s, loss=0.060633, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8429/10000 [27:01<04:57,  5.28step/s, loss=0.060633, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8429/10000 [27:01<04:57,  5.28step/s, loss=0.088706, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8430/10000 [27:01<04:57,  5.27step/s, loss=0.088706, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8430/10000 [27:01<04:57,  5.27step/s, loss=0.030652, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8431/10000 [27:01<04:57,  5.27step/s, loss=0.030652, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8431/10000 [27:01<04:57,  5.27step/s, loss=0.043996, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8432/10000 [27:01<04:57,  5.27step/s, loss=0.043996, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8432/10000 [27:01<04:57,  5.27step/s, loss=0.097676, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8433/10000 [27:01<04:56,  5.28step/s, loss=0.097676, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8433/10000 [27:01<04:56,  5.28step/s, loss=0.044475, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8434/10000 [27:02<04:56,  5.28step/s, loss=0.044475, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8434/10000 [27:02<04:56,  5.28step/s, loss=0.056732, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8435/10000 [27:02<04:55,  5.29step/s, loss=0.056732, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8435/10000 [27:02<04:55,  5.29step/s, loss=0.072200, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8436/10000 [27:02<04:57,  5.27step/s, loss=0.072200, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8436/10000 [27:02<04:57,  5.27step/s, loss=0.019042, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8437/10000 [27:02<04:56,  5.27step/s, loss=0.019042, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8437/10000 [27:02<04:56,  5.27step/s, loss=0.024899, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8438/10000 [27:02<04:56,  5.27step/s, loss=0.024899, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8438/10000 [27:02<04:56,  5.27step/s, loss=0.029570, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8439/10000 [27:03<04:56,  5.27step/s, loss=0.029570, elapsed=27.0min]

Entraînement:  84%|████████▍ | 8439/10000 [27:03<04:56,  5.27step/s, loss=0.084936, elapsed=27.1min]

Entraînement:  84%|████████▍ | 8440/10000 [27:03<04:55,  5.27step/s, loss=0.084936, elapsed=27.1min]

Entraînement:  84%|████████▍ | 8440/10000 [27:03<04:55,  5.27step/s, loss=0.031961, elapsed=27.1min]

Entraînement:  84%|████████▍ | 8441/10000 [27:03<04:54,  5.29step/s, loss=0.031961, elapsed=27.1min]

Entraînement:  84%|████████▍ | 8441/10000 [27:03<04:54,  5.29step/s, loss=0.098058, elapsed=27.1min]

Entraînement:  84%|████████▍ | 8442/10000 [27:03<04:55,  5.28step/s, loss=0.098058, elapsed=27.1min]

Entraînement:  84%|████████▍ | 8442/10000 [27:03<04:55,  5.28step/s, loss=0.042818, elapsed=27.1min]

Entraînement:  84%|████████▍ | 8443/10000 [27:03<04:54,  5.29step/s, loss=0.042818, elapsed=27.1min]

Entraînement:  84%|████████▍ | 8443/10000 [27:03<04:54,  5.29step/s, loss=0.041987, elapsed=27.1min]

Entraînement:  84%|████████▍ | 8444/10000 [27:04<04:54,  5.29step/s, loss=0.041987, elapsed=27.1min]

Entraînement:  84%|████████▍ | 8444/10000 [27:04<04:54,  5.29step/s, loss=0.039612, elapsed=27.1min]

Entraînement:  84%|████████▍ | 8445/10000 [27:04<04:53,  5.29step/s, loss=0.039612, elapsed=27.1min]

Entraînement:  84%|████████▍ | 8445/10000 [27:04<04:53,  5.29step/s, loss=0.091654, elapsed=27.1min]

Entraînement:  84%|████████▍ | 8446/10000 [27:04<04:53,  5.29step/s, loss=0.091654, elapsed=27.1min]

Entraînement:  84%|████████▍ | 8446/10000 [27:04<04:53,  5.29step/s, loss=0.065414, elapsed=27.1min]

Entraînement:  84%|████████▍ | 8447/10000 [27:04<04:53,  5.29step/s, loss=0.065414, elapsed=27.1min]

Entraînement:  84%|████████▍ | 8447/10000 [27:04<04:53,  5.29step/s, loss=0.085653, elapsed=27.1min]

Entraînement:  84%|████████▍ | 8448/10000 [27:04<04:52,  5.30step/s, loss=0.085653, elapsed=27.1min]

Entraînement:  84%|████████▍ | 8448/10000 [27:04<04:52,  5.30step/s, loss=0.035937, elapsed=27.1min]

Entraînement:  84%|████████▍ | 8449/10000 [27:04<04:53,  5.29step/s, loss=0.035937, elapsed=27.1min]

Entraînement:  84%|████████▍ | 8449/10000 [27:04<04:53,  5.29step/s, loss=0.049255, elapsed=27.1min]

Entraînement:  84%|████████▍ | 8450/10000 [27:05<04:52,  5.29step/s, loss=0.049255, elapsed=27.1min]

Entraînement:  84%|████████▍ | 8450/10000 [27:05<04:52,  5.29step/s, loss=0.013676, elapsed=27.1min]

Entraînement:  85%|████████▍ | 8451/10000 [27:05<04:52,  5.30step/s, loss=0.013676, elapsed=27.1min]

Entraînement:  85%|████████▍ | 8451/10000 [27:05<04:52,  5.30step/s, loss=0.066880, elapsed=27.1min]

Entraînement:  85%|████████▍ | 8452/10000 [27:05<04:51,  5.30step/s, loss=0.066880, elapsed=27.1min]

Entraînement:  85%|████████▍ | 8452/10000 [27:05<04:51,  5.30step/s, loss=0.044017, elapsed=27.1min]

Entraînement:  85%|████████▍ | 8453/10000 [27:05<04:51,  5.30step/s, loss=0.044017, elapsed=27.1min]

Entraînement:  85%|████████▍ | 8453/10000 [27:05<04:51,  5.30step/s, loss=0.025316, elapsed=27.1min]

Entraînement:  85%|████████▍ | 8454/10000 [27:05<04:51,  5.30step/s, loss=0.025316, elapsed=27.1min]

Entraînement:  85%|████████▍ | 8454/10000 [27:05<04:51,  5.30step/s, loss=0.048310, elapsed=27.1min]

Entraînement:  85%|████████▍ | 8455/10000 [27:06<04:51,  5.29step/s, loss=0.048310, elapsed=27.1min]

Entraînement:  85%|████████▍ | 8455/10000 [27:06<04:51,  5.29step/s, loss=0.042969, elapsed=27.1min]

Entraînement:  85%|████████▍ | 8456/10000 [27:06<04:51,  5.29step/s, loss=0.042969, elapsed=27.1min]

Entraînement:  85%|████████▍ | 8456/10000 [27:06<04:51,  5.29step/s, loss=0.048900, elapsed=27.1min]

Entraînement:  85%|████████▍ | 8457/10000 [27:06<04:52,  5.28step/s, loss=0.048900, elapsed=27.1min]

Entraînement:  85%|████████▍ | 8457/10000 [27:06<04:52,  5.28step/s, loss=0.023612, elapsed=27.1min]

Entraînement:  85%|████████▍ | 8458/10000 [27:06<04:52,  5.28step/s, loss=0.023612, elapsed=27.1min]

Entraînement:  85%|████████▍ | 8458/10000 [27:06<04:52,  5.28step/s, loss=0.063659, elapsed=27.1min]

Entraînement:  85%|████████▍ | 8459/10000 [27:06<04:51,  5.29step/s, loss=0.063659, elapsed=27.1min]

Entraînement:  85%|████████▍ | 8459/10000 [27:06<04:51,  5.29step/s, loss=0.058972, elapsed=27.1min]

Entraînement:  85%|████████▍ | 8460/10000 [27:07<04:51,  5.28step/s, loss=0.058972, elapsed=27.1min]

Entraînement:  85%|████████▍ | 8460/10000 [27:07<04:51,  5.28step/s, loss=0.044543, elapsed=27.1min]

Entraînement:  85%|████████▍ | 8461/10000 [27:07<04:51,  5.28step/s, loss=0.044543, elapsed=27.1min]

Entraînement:  85%|████████▍ | 8461/10000 [27:07<04:51,  5.28step/s, loss=0.019215, elapsed=27.1min]

Entraînement:  85%|████████▍ | 8462/10000 [27:07<04:51,  5.27step/s, loss=0.019215, elapsed=27.1min]

Entraînement:  85%|████████▍ | 8462/10000 [27:07<04:51,  5.27step/s, loss=0.060142, elapsed=27.1min]

Entraînement:  85%|████████▍ | 8463/10000 [27:07<04:51,  5.27step/s, loss=0.060142, elapsed=27.1min]

Entraînement:  85%|████████▍ | 8463/10000 [27:07<04:51,  5.27step/s, loss=0.064381, elapsed=27.1min]

Entraînement:  85%|████████▍ | 8464/10000 [27:07<04:51,  5.27step/s, loss=0.064381, elapsed=27.1min]

Entraînement:  85%|████████▍ | 8464/10000 [27:07<04:51,  5.27step/s, loss=0.024737, elapsed=27.1min]

Entraînement:  85%|████████▍ | 8465/10000 [27:07<04:51,  5.27step/s, loss=0.024737, elapsed=27.1min]

Entraînement:  85%|████████▍ | 8465/10000 [27:07<04:51,  5.27step/s, loss=0.019237, elapsed=27.1min]

Entraînement:  85%|████████▍ | 8466/10000 [27:08<04:50,  5.28step/s, loss=0.019237, elapsed=27.1min]

Entraînement:  85%|████████▍ | 8466/10000 [27:08<04:50,  5.28step/s, loss=0.046870, elapsed=27.1min]

Entraînement:  85%|████████▍ | 8467/10000 [27:08<04:50,  5.28step/s, loss=0.046870, elapsed=27.1min]

Entraînement:  85%|████████▍ | 8467/10000 [27:08<04:50,  5.28step/s, loss=0.036690, elapsed=27.1min]

Entraînement:  85%|████████▍ | 8468/10000 [27:08<04:50,  5.28step/s, loss=0.036690, elapsed=27.1min]

Entraînement:  85%|████████▍ | 8468/10000 [27:08<04:50,  5.28step/s, loss=0.070418, elapsed=27.1min]

Entraînement:  85%|████████▍ | 8469/10000 [27:08<04:50,  5.27step/s, loss=0.070418, elapsed=27.1min]

Entraînement:  85%|████████▍ | 8469/10000 [27:08<04:50,  5.27step/s, loss=0.044437, elapsed=27.1min]

Entraînement:  85%|████████▍ | 8470/10000 [27:08<04:50,  5.26step/s, loss=0.044437, elapsed=27.1min]

Entraînement:  85%|████████▍ | 8470/10000 [27:08<04:50,  5.26step/s, loss=0.050840, elapsed=27.1min]

Entraînement:  85%|████████▍ | 8471/10000 [27:09<04:52,  5.22step/s, loss=0.050840, elapsed=27.1min]

Entraînement:  85%|████████▍ | 8471/10000 [27:09<04:52,  5.22step/s, loss=0.047774, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8472/10000 [27:09<04:51,  5.25step/s, loss=0.047774, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8472/10000 [27:09<04:51,  5.25step/s, loss=0.035141, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8473/10000 [27:09<04:50,  5.25step/s, loss=0.035141, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8473/10000 [27:09<04:50,  5.25step/s, loss=0.037820, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8474/10000 [27:09<04:50,  5.26step/s, loss=0.037820, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8474/10000 [27:09<04:50,  5.26step/s, loss=0.024028, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8475/10000 [27:09<04:49,  5.26step/s, loss=0.024028, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8475/10000 [27:09<04:49,  5.26step/s, loss=0.087177, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8476/10000 [27:10<04:49,  5.26step/s, loss=0.087177, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8476/10000 [27:10<04:49,  5.26step/s, loss=0.046179, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8477/10000 [27:10<04:49,  5.26step/s, loss=0.046179, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8477/10000 [27:10<04:49,  5.26step/s, loss=0.022980, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8478/10000 [27:10<04:49,  5.26step/s, loss=0.022980, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8478/10000 [27:10<04:49,  5.26step/s, loss=0.059753, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8479/10000 [27:10<04:49,  5.26step/s, loss=0.059753, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8479/10000 [27:10<04:49,  5.26step/s, loss=0.019430, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8480/10000 [27:10<04:48,  5.27step/s, loss=0.019430, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8480/10000 [27:10<04:48,  5.27step/s, loss=0.046996, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8481/10000 [27:11<04:48,  5.27step/s, loss=0.046996, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8481/10000 [27:11<04:48,  5.27step/s, loss=0.089976, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8482/10000 [27:11<04:47,  5.28step/s, loss=0.089976, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8482/10000 [27:11<04:47,  5.28step/s, loss=0.035112, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8483/10000 [27:11<04:47,  5.28step/s, loss=0.035112, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8483/10000 [27:11<04:47,  5.28step/s, loss=0.034852, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8484/10000 [27:11<04:47,  5.28step/s, loss=0.034852, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8484/10000 [27:11<04:47,  5.28step/s, loss=0.052550, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8485/10000 [27:11<04:47,  5.26step/s, loss=0.052550, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8485/10000 [27:11<04:47,  5.26step/s, loss=0.057542, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8486/10000 [27:11<04:47,  5.27step/s, loss=0.057542, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8486/10000 [27:11<04:47,  5.27step/s, loss=0.046145, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8487/10000 [27:12<04:47,  5.27step/s, loss=0.046145, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8487/10000 [27:12<04:47,  5.27step/s, loss=0.065335, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8488/10000 [27:12<04:46,  5.27step/s, loss=0.065335, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8488/10000 [27:12<04:46,  5.27step/s, loss=0.078759, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8489/10000 [27:12<04:45,  5.28step/s, loss=0.078759, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8489/10000 [27:12<04:45,  5.28step/s, loss=0.027266, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8490/10000 [27:12<04:45,  5.28step/s, loss=0.027266, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8490/10000 [27:12<04:45,  5.28step/s, loss=0.035206, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8491/10000 [27:12<04:45,  5.29step/s, loss=0.035206, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8491/10000 [27:12<04:45,  5.29step/s, loss=0.032087, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8492/10000 [27:13<04:45,  5.27step/s, loss=0.032087, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8492/10000 [27:13<04:45,  5.27step/s, loss=0.029200, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8493/10000 [27:13<04:46,  5.26step/s, loss=0.029200, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8493/10000 [27:13<04:46,  5.26step/s, loss=0.055339, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8494/10000 [27:13<04:45,  5.27step/s, loss=0.055339, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8494/10000 [27:13<04:45,  5.27step/s, loss=0.047898, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8495/10000 [27:13<04:45,  5.28step/s, loss=0.047898, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8495/10000 [27:13<04:45,  5.28step/s, loss=0.093620, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8496/10000 [27:13<04:44,  5.30step/s, loss=0.093620, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8496/10000 [27:13<04:44,  5.30step/s, loss=0.032255, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8497/10000 [27:14<04:43,  5.30step/s, loss=0.032255, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8497/10000 [27:14<04:43,  5.30step/s, loss=0.045485, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8498/10000 [27:14<04:43,  5.30step/s, loss=0.045485, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8498/10000 [27:14<04:43,  5.30step/s, loss=0.050022, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8499/10000 [27:14<04:43,  5.30step/s, loss=0.050022, elapsed=27.2min]

Entraînement:  85%|████████▍ | 8499/10000 [27:14<04:43,  5.30step/s, loss=0.053378, elapsed=27.2min]

Entraînement:  85%|████████▌ | 8500/10000 [27:14<04:42,  5.30step/s, loss=0.053378, elapsed=27.2min]

Entraînement:  85%|████████▌ | 8500/10000 [27:14<04:42,  5.30step/s, loss=0.030523, elapsed=27.2min]

Entraînement:  85%|████████▌ | 8500/10000 [27:14<04:42,  5.30step/s, loss=0.030523, elapsed=27.2min]

Entraînement:  85%|████████▌ | 8501/10000 [27:14<04:45,  5.24step/s, loss=0.030523, elapsed=27.2min]

Entraînement:  85%|████████▌ | 8501/10000 [27:14<04:45,  5.24step/s, loss=0.025608, elapsed=27.2min]

Step 8500/10000 | Train loss: 0.030523 | Elapsed: 27.2min | ETA: 4.8min

Entraînement:  85%|████████▌ | 8502/10000 [27:14<04:45,  5.26step/s, loss=0.025608, elapsed=27.2min]

Entraînement:  85%|████████▌ | 8502/10000 [27:14<04:45,  5.26step/s, loss=0.038558, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8503/10000 [27:15<04:44,  5.27step/s, loss=0.038558, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8503/10000 [27:15<04:44,  5.27step/s, loss=0.054244, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8504/10000 [27:15<04:43,  5.28step/s, loss=0.054244, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8504/10000 [27:15<04:43,  5.28step/s, loss=0.054786, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8505/10000 [27:15<04:42,  5.29step/s, loss=0.054786, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8505/10000 [27:15<04:42,  5.29step/s, loss=0.019530, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8506/10000 [27:15<04:42,  5.29step/s, loss=0.019530, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8506/10000 [27:15<04:42,  5.29step/s, loss=0.020951, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8507/10000 [27:15<04:41,  5.30step/s, loss=0.020951, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8507/10000 [27:15<04:41,  5.30step/s, loss=0.043724, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8508/10000 [27:16<04:41,  5.30step/s, loss=0.043724, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8508/10000 [27:16<04:41,  5.30step/s, loss=0.040983, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8509/10000 [27:16<04:41,  5.29step/s, loss=0.040983, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8509/10000 [27:16<04:41,  5.29step/s, loss=0.051541, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8510/10000 [27:16<04:42,  5.27step/s, loss=0.051541, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8510/10000 [27:16<04:42,  5.27step/s, loss=0.060298, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8511/10000 [27:16<04:41,  5.28step/s, loss=0.060298, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8511/10000 [27:16<04:41,  5.28step/s, loss=0.017759, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8512/10000 [27:16<04:41,  5.29step/s, loss=0.017759, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8512/10000 [27:16<04:41,  5.29step/s, loss=0.089369, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8513/10000 [27:17<04:41,  5.29step/s, loss=0.089369, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8513/10000 [27:17<04:41,  5.29step/s, loss=0.052165, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8514/10000 [27:17<04:40,  5.30step/s, loss=0.052165, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8514/10000 [27:17<04:40,  5.30step/s, loss=0.060048, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8515/10000 [27:17<04:40,  5.29step/s, loss=0.060048, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8515/10000 [27:17<04:40,  5.29step/s, loss=0.070889, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8516/10000 [27:17<04:40,  5.29step/s, loss=0.070889, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8516/10000 [27:17<04:40,  5.29step/s, loss=0.039906, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8517/10000 [27:17<04:40,  5.29step/s, loss=0.039906, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8517/10000 [27:17<04:40,  5.29step/s, loss=0.033362, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8518/10000 [27:18<04:40,  5.29step/s, loss=0.033362, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8518/10000 [27:18<04:40,  5.29step/s, loss=0.035065, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8519/10000 [27:18<04:39,  5.30step/s, loss=0.035065, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8519/10000 [27:18<04:39,  5.30step/s, loss=0.046971, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8520/10000 [27:18<04:38,  5.31step/s, loss=0.046971, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8520/10000 [27:18<04:38,  5.31step/s, loss=0.033826, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8521/10000 [27:18<04:38,  5.31step/s, loss=0.033826, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8521/10000 [27:18<04:38,  5.31step/s, loss=0.114891, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8522/10000 [27:18<04:38,  5.31step/s, loss=0.114891, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8522/10000 [27:18<04:38,  5.31step/s, loss=0.055988, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8523/10000 [27:18<04:38,  5.31step/s, loss=0.055988, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8523/10000 [27:18<04:38,  5.31step/s, loss=0.071053, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8524/10000 [27:19<04:38,  5.30step/s, loss=0.071053, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8524/10000 [27:19<04:38,  5.30step/s, loss=0.015038, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8525/10000 [27:19<04:38,  5.30step/s, loss=0.015038, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8525/10000 [27:19<04:38,  5.30step/s, loss=0.034741, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8526/10000 [27:19<04:38,  5.30step/s, loss=0.034741, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8526/10000 [27:19<04:38,  5.30step/s, loss=0.050389, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8527/10000 [27:19<04:38,  5.30step/s, loss=0.050389, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8527/10000 [27:19<04:38,  5.30step/s, loss=0.043765, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8528/10000 [27:19<04:37,  5.30step/s, loss=0.043765, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8528/10000 [27:19<04:37,  5.30step/s, loss=0.044422, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8529/10000 [27:20<04:37,  5.30step/s, loss=0.044422, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8529/10000 [27:20<04:37,  5.30step/s, loss=0.051726, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8530/10000 [27:20<04:37,  5.31step/s, loss=0.051726, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8530/10000 [27:20<04:37,  5.31step/s, loss=0.049347, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8531/10000 [27:20<04:36,  5.31step/s, loss=0.049347, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8531/10000 [27:20<04:36,  5.31step/s, loss=0.051417, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8532/10000 [27:20<04:36,  5.30step/s, loss=0.051417, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8532/10000 [27:20<04:36,  5.30step/s, loss=0.033123, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8533/10000 [27:20<04:36,  5.30step/s, loss=0.033123, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8533/10000 [27:20<04:36,  5.30step/s, loss=0.027967, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8534/10000 [27:21<04:36,  5.30step/s, loss=0.027967, elapsed=27.3min]

Entraînement:  85%|████████▌ | 8534/10000 [27:21<04:36,  5.30step/s, loss=0.018157, elapsed=27.4min]

Entraînement:  85%|████████▌ | 8535/10000 [27:21<04:36,  5.30step/s, loss=0.018157, elapsed=27.4min]

Entraînement:  85%|████████▌ | 8535/10000 [27:21<04:36,  5.30step/s, loss=0.030091, elapsed=27.4min]

Entraînement:  85%|████████▌ | 8536/10000 [27:21<04:35,  5.31step/s, loss=0.030091, elapsed=27.4min]

Entraînement:  85%|████████▌ | 8536/10000 [27:21<04:35,  5.31step/s, loss=0.051883, elapsed=27.4min]

Entraînement:  85%|████████▌ | 8537/10000 [27:21<04:35,  5.31step/s, loss=0.051883, elapsed=27.4min]

Entraînement:  85%|████████▌ | 8537/10000 [27:21<04:35,  5.31step/s, loss=0.100861, elapsed=27.4min]

Entraînement:  85%|████████▌ | 8538/10000 [27:21<04:35,  5.31step/s, loss=0.100861, elapsed=27.4min]

Entraînement:  85%|████████▌ | 8538/10000 [27:21<04:35,  5.31step/s, loss=0.041684, elapsed=27.4min]

Entraînement:  85%|████████▌ | 8539/10000 [27:21<04:35,  5.31step/s, loss=0.041684, elapsed=27.4min]

Entraînement:  85%|████████▌ | 8539/10000 [27:21<04:35,  5.31step/s, loss=0.044106, elapsed=27.4min]

Entraînement:  85%|████████▌ | 8540/10000 [27:22<04:35,  5.30step/s, loss=0.044106, elapsed=27.4min]

Entraînement:  85%|████████▌ | 8540/10000 [27:22<04:35,  5.30step/s, loss=0.036991, elapsed=27.4min]

Entraînement:  85%|████████▌ | 8541/10000 [27:22<04:35,  5.30step/s, loss=0.036991, elapsed=27.4min]

Entraînement:  85%|████████▌ | 8541/10000 [27:22<04:35,  5.30step/s, loss=0.021044, elapsed=27.4min]

Entraînement:  85%|████████▌ | 8542/10000 [27:22<04:35,  5.30step/s, loss=0.021044, elapsed=27.4min]

Entraînement:  85%|████████▌ | 8542/10000 [27:22<04:35,  5.30step/s, loss=0.025283, elapsed=27.4min]

Entraînement:  85%|████████▌ | 8543/10000 [27:22<04:35,  5.29step/s, loss=0.025283, elapsed=27.4min]

Entraînement:  85%|████████▌ | 8543/10000 [27:22<04:35,  5.29step/s, loss=0.055205, elapsed=27.4min]

Entraînement:  85%|████████▌ | 8544/10000 [27:22<04:34,  5.30step/s, loss=0.055205, elapsed=27.4min]

Entraînement:  85%|████████▌ | 8544/10000 [27:22<04:34,  5.30step/s, loss=0.047889, elapsed=27.4min]

Entraînement:  85%|████████▌ | 8545/10000 [27:23<04:34,  5.29step/s, loss=0.047889, elapsed=27.4min]

Entraînement:  85%|████████▌ | 8545/10000 [27:23<04:34,  5.29step/s, loss=0.026517, elapsed=27.4min]

Entraînement:  85%|████████▌ | 8546/10000 [27:23<04:34,  5.29step/s, loss=0.026517, elapsed=27.4min]

Entraînement:  85%|████████▌ | 8546/10000 [27:23<04:34,  5.29step/s, loss=0.018382, elapsed=27.4min]

Entraînement:  85%|████████▌ | 8547/10000 [27:23<04:34,  5.30step/s, loss=0.018382, elapsed=27.4min]

Entraînement:  85%|████████▌ | 8547/10000 [27:23<04:34,  5.30step/s, loss=0.021270, elapsed=27.4min]

Entraînement:  85%|████████▌ | 8548/10000 [27:23<04:33,  5.30step/s, loss=0.021270, elapsed=27.4min]

Entraînement:  85%|████████▌ | 8548/10000 [27:23<04:33,  5.30step/s, loss=0.027271, elapsed=27.4min]

Entraînement:  85%|████████▌ | 8549/10000 [27:23<04:33,  5.30step/s, loss=0.027271, elapsed=27.4min]

Entraînement:  85%|████████▌ | 8549/10000 [27:23<04:33,  5.30step/s, loss=0.033347, elapsed=27.4min]

Entraînement:  86%|████████▌ | 8550/10000 [27:24<04:33,  5.31step/s, loss=0.033347, elapsed=27.4min]

Entraînement:  86%|████████▌ | 8550/10000 [27:24<04:33,  5.31step/s, loss=0.032873, elapsed=27.4min]

Entraînement:  86%|████████▌ | 8551/10000 [27:24<04:33,  5.30step/s, loss=0.032873, elapsed=27.4min]

Entraînement:  86%|████████▌ | 8551/10000 [27:24<04:33,  5.30step/s, loss=0.056567, elapsed=27.4min]

Entraînement:  86%|████████▌ | 8552/10000 [27:24<04:33,  5.30step/s, loss=0.056567, elapsed=27.4min]

Entraînement:  86%|████████▌ | 8552/10000 [27:24<04:33,  5.30step/s, loss=0.033043, elapsed=27.4min]

Entraînement:  86%|████████▌ | 8553/10000 [27:24<04:33,  5.30step/s, loss=0.033043, elapsed=27.4min]

Entraînement:  86%|████████▌ | 8553/10000 [27:24<04:33,  5.30step/s, loss=0.105644, elapsed=27.4min]

Entraînement:  86%|████████▌ | 8554/10000 [27:24<04:33,  5.29step/s, loss=0.105644, elapsed=27.4min]

Entraînement:  86%|████████▌ | 8554/10000 [27:24<04:33,  5.29step/s, loss=0.021601, elapsed=27.4min]

Entraînement:  86%|████████▌ | 8555/10000 [27:24<04:32,  5.29step/s, loss=0.021601, elapsed=27.4min]

Entraînement:  86%|████████▌ | 8555/10000 [27:25<04:32,  5.29step/s, loss=0.156457, elapsed=27.4min]

Entraînement:  86%|████████▌ | 8556/10000 [27:25<04:33,  5.29step/s, loss=0.156457, elapsed=27.4min]

Entraînement:  86%|████████▌ | 8556/10000 [27:25<04:33,  5.29step/s, loss=0.050134, elapsed=27.4min]

Entraînement:  86%|████████▌ | 8557/10000 [27:25<04:33,  5.28step/s, loss=0.050134, elapsed=27.4min]

Entraînement:  86%|████████▌ | 8557/10000 [27:25<04:33,  5.28step/s, loss=0.137972, elapsed=27.4min]

Entraînement:  86%|████████▌ | 8558/10000 [27:25<04:33,  5.28step/s, loss=0.137972, elapsed=27.4min]

Entraînement:  86%|████████▌ | 8558/10000 [27:25<04:33,  5.28step/s, loss=0.021401, elapsed=27.4min]

Entraînement:  86%|████████▌ | 8559/10000 [27:25<04:33,  5.27step/s, loss=0.021401, elapsed=27.4min]

Entraînement:  86%|████████▌ | 8559/10000 [27:25<04:33,  5.27step/s, loss=0.049724, elapsed=27.4min]

Entraînement:  86%|████████▌ | 8560/10000 [27:25<04:32,  5.28step/s, loss=0.049724, elapsed=27.4min]

Entraînement:  86%|████████▌ | 8560/10000 [27:25<04:32,  5.28step/s, loss=0.031837, elapsed=27.4min]

Entraînement:  86%|████████▌ | 8561/10000 [27:26<04:32,  5.28step/s, loss=0.031837, elapsed=27.4min]

Entraînement:  86%|████████▌ | 8561/10000 [27:26<04:32,  5.28step/s, loss=0.044748, elapsed=27.4min]

Entraînement:  86%|████████▌ | 8562/10000 [27:26<04:32,  5.28step/s, loss=0.044748, elapsed=27.4min]

Entraînement:  86%|████████▌ | 8562/10000 [27:26<04:32,  5.28step/s, loss=0.040166, elapsed=27.4min]

Entraînement:  86%|████████▌ | 8563/10000 [27:26<04:31,  5.29step/s, loss=0.040166, elapsed=27.4min]

Entraînement:  86%|████████▌ | 8563/10000 [27:26<04:31,  5.29step/s, loss=0.031391, elapsed=27.4min]

Entraînement:  86%|████████▌ | 8564/10000 [27:26<04:31,  5.29step/s, loss=0.031391, elapsed=27.4min]

Entraînement:  86%|████████▌ | 8564/10000 [27:26<04:31,  5.29step/s, loss=0.043864, elapsed=27.4min]

Entraînement:  86%|████████▌ | 8565/10000 [27:26<04:31,  5.29step/s, loss=0.043864, elapsed=27.4min]

Entraînement:  86%|████████▌ | 8565/10000 [27:26<04:31,  5.29step/s, loss=0.102949, elapsed=27.4min]

Entraînement:  86%|████████▌ | 8566/10000 [27:27<04:30,  5.29step/s, loss=0.102949, elapsed=27.4min]

Entraînement:  86%|████████▌ | 8566/10000 [27:27<04:30,  5.29step/s, loss=0.069363, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8567/10000 [27:27<04:30,  5.31step/s, loss=0.069363, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8567/10000 [27:27<04:30,  5.31step/s, loss=0.044900, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8568/10000 [27:27<04:30,  5.29step/s, loss=0.044900, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8568/10000 [27:27<04:30,  5.29step/s, loss=0.055372, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8569/10000 [27:27<04:30,  5.29step/s, loss=0.055372, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8569/10000 [27:27<04:30,  5.29step/s, loss=0.073731, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8570/10000 [27:27<04:30,  5.29step/s, loss=0.073731, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8570/10000 [27:27<04:30,  5.29step/s, loss=0.109521, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8571/10000 [27:28<04:28,  5.32step/s, loss=0.109521, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8571/10000 [27:28<04:28,  5.32step/s, loss=0.027478, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8572/10000 [27:28<04:26,  5.35step/s, loss=0.027478, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8572/10000 [27:28<04:26,  5.35step/s, loss=0.032881, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8573/10000 [27:28<04:26,  5.36step/s, loss=0.032881, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8573/10000 [27:28<04:26,  5.36step/s, loss=0.089333, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8574/10000 [27:28<04:25,  5.37step/s, loss=0.089333, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8574/10000 [27:28<04:25,  5.37step/s, loss=0.021335, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8575/10000 [27:28<04:25,  5.37step/s, loss=0.021335, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8575/10000 [27:28<04:25,  5.37step/s, loss=0.040757, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8576/10000 [27:28<04:26,  5.34step/s, loss=0.040757, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8576/10000 [27:28<04:26,  5.34step/s, loss=0.025261, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8577/10000 [27:29<04:28,  5.30step/s, loss=0.025261, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8577/10000 [27:29<04:28,  5.30step/s, loss=0.043218, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8578/10000 [27:29<04:28,  5.29step/s, loss=0.043218, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8578/10000 [27:29<04:28,  5.29step/s, loss=0.139858, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8579/10000 [27:29<04:28,  5.28step/s, loss=0.139858, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8579/10000 [27:29<04:28,  5.28step/s, loss=0.051397, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8580/10000 [27:29<04:29,  5.27step/s, loss=0.051397, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8580/10000 [27:29<04:29,  5.27step/s, loss=0.020538, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8581/10000 [27:29<04:29,  5.27step/s, loss=0.020538, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8581/10000 [27:29<04:29,  5.27step/s, loss=0.017967, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8582/10000 [27:30<04:29,  5.27step/s, loss=0.017967, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8582/10000 [27:30<04:29,  5.27step/s, loss=0.085380, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8583/10000 [27:30<04:29,  5.26step/s, loss=0.085380, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8583/10000 [27:30<04:29,  5.26step/s, loss=0.058770, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8584/10000 [27:30<04:29,  5.25step/s, loss=0.058770, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8584/10000 [27:30<04:29,  5.25step/s, loss=0.033886, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8585/10000 [27:30<04:29,  5.25step/s, loss=0.033886, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8585/10000 [27:30<04:29,  5.25step/s, loss=0.021263, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8586/10000 [27:30<04:28,  5.26step/s, loss=0.021263, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8586/10000 [27:30<04:28,  5.26step/s, loss=0.028374, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8587/10000 [27:31<04:30,  5.22step/s, loss=0.028374, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8587/10000 [27:31<04:30,  5.22step/s, loss=0.014006, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8588/10000 [27:31<04:29,  5.24step/s, loss=0.014006, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8588/10000 [27:31<04:29,  5.24step/s, loss=0.039444, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8589/10000 [27:31<04:29,  5.23step/s, loss=0.039444, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8589/10000 [27:31<04:29,  5.23step/s, loss=0.077906, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8590/10000 [27:31<04:30,  5.22step/s, loss=0.077906, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8590/10000 [27:31<04:30,  5.22step/s, loss=0.025306, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8591/10000 [27:31<04:29,  5.23step/s, loss=0.025306, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8591/10000 [27:31<04:29,  5.23step/s, loss=0.039538, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8592/10000 [27:32<04:28,  5.25step/s, loss=0.039538, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8592/10000 [27:32<04:28,  5.25step/s, loss=0.032070, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8593/10000 [27:32<04:28,  5.24step/s, loss=0.032070, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8593/10000 [27:32<04:28,  5.24step/s, loss=0.040976, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8594/10000 [27:32<04:27,  5.25step/s, loss=0.040976, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8594/10000 [27:32<04:27,  5.25step/s, loss=0.100429, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8595/10000 [27:32<04:26,  5.27step/s, loss=0.100429, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8595/10000 [27:32<04:26,  5.27step/s, loss=0.017408, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8596/10000 [27:32<04:26,  5.27step/s, loss=0.017408, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8596/10000 [27:32<04:26,  5.27step/s, loss=0.046400, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8597/10000 [27:32<04:26,  5.27step/s, loss=0.046400, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8597/10000 [27:32<04:26,  5.27step/s, loss=0.018478, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8598/10000 [27:33<04:25,  5.28step/s, loss=0.018478, elapsed=27.5min]

Entraînement:  86%|████████▌ | 8598/10000 [27:33<04:25,  5.28step/s, loss=0.066534, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8599/10000 [27:33<04:24,  5.29step/s, loss=0.066534, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8599/10000 [27:33<04:24,  5.29step/s, loss=0.027100, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8600/10000 [27:33<04:24,  5.29step/s, loss=0.027100, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8600/10000 [27:33<04:24,  5.29step/s, loss=0.025696, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8600/10000 [27:33<04:24,  5.29step/s, loss=0.025696, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8601/10000 [27:33<04:27,  5.23step/s, loss=0.025696, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8601/10000 [27:33<04:27,  5.23step/s, loss=0.030348, elapsed=27.6min]

Step 8600/10000 | Train loss: 0.025696 | Elapsed: 27.6min | ETA: 4.5min

Entraînement:  86%|████████▌ | 8602/10000 [27:33<04:26,  5.25step/s, loss=0.030348, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8602/10000 [27:33<04:26,  5.25step/s, loss=0.039153, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8603/10000 [27:34<04:25,  5.26step/s, loss=0.039153, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8603/10000 [27:34<04:25,  5.26step/s, loss=0.056822, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8604/10000 [27:34<04:24,  5.27step/s, loss=0.056822, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8604/10000 [27:34<04:24,  5.27step/s, loss=0.029343, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8605/10000 [27:34<04:24,  5.28step/s, loss=0.029343, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8605/10000 [27:34<04:24,  5.28step/s, loss=0.027637, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8606/10000 [27:34<04:24,  5.27step/s, loss=0.027637, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8606/10000 [27:34<04:24,  5.27step/s, loss=0.042279, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8607/10000 [27:34<04:24,  5.27step/s, loss=0.042279, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8607/10000 [27:34<04:24,  5.27step/s, loss=0.030847, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8608/10000 [27:35<04:23,  5.28step/s, loss=0.030847, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8608/10000 [27:35<04:23,  5.28step/s, loss=0.043485, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8609/10000 [27:35<04:23,  5.27step/s, loss=0.043485, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8609/10000 [27:35<04:23,  5.27step/s, loss=0.030800, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8610/10000 [27:35<04:23,  5.27step/s, loss=0.030800, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8610/10000 [27:35<04:23,  5.27step/s, loss=0.025745, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8611/10000 [27:35<04:23,  5.26step/s, loss=0.025745, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8611/10000 [27:35<04:23,  5.26step/s, loss=0.030708, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8612/10000 [27:35<04:23,  5.27step/s, loss=0.030708, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8612/10000 [27:35<04:23,  5.27step/s, loss=0.053751, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8613/10000 [27:35<04:22,  5.28step/s, loss=0.053751, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8613/10000 [27:35<04:22,  5.28step/s, loss=0.018945, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8614/10000 [27:36<04:22,  5.27step/s, loss=0.018945, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8614/10000 [27:36<04:22,  5.27step/s, loss=0.022660, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8615/10000 [27:36<04:22,  5.28step/s, loss=0.022660, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8615/10000 [27:36<04:22,  5.28step/s, loss=0.015355, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8616/10000 [27:36<04:22,  5.28step/s, loss=0.015355, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8616/10000 [27:36<04:22,  5.28step/s, loss=0.069407, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8617/10000 [27:36<04:22,  5.27step/s, loss=0.069407, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8617/10000 [27:36<04:22,  5.27step/s, loss=0.019114, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8618/10000 [27:36<04:22,  5.27step/s, loss=0.019114, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8618/10000 [27:36<04:22,  5.27step/s, loss=0.047062, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8619/10000 [27:37<04:23,  5.25step/s, loss=0.047062, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8619/10000 [27:37<04:23,  5.25step/s, loss=0.022318, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8620/10000 [27:37<04:22,  5.26step/s, loss=0.022318, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8620/10000 [27:37<04:22,  5.26step/s, loss=0.037218, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8621/10000 [27:37<04:22,  5.26step/s, loss=0.037218, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8621/10000 [27:37<04:22,  5.26step/s, loss=0.019134, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8622/10000 [27:37<04:21,  5.26step/s, loss=0.019134, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8622/10000 [27:37<04:21,  5.26step/s, loss=0.064714, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8623/10000 [27:37<04:21,  5.26step/s, loss=0.064714, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8623/10000 [27:37<04:21,  5.26step/s, loss=0.051059, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8624/10000 [27:38<04:22,  5.24step/s, loss=0.051059, elapsed=27.6min]

Entraînement:  86%|████████▌ | 8624/10000 [27:38<04:22,  5.24step/s, loss=0.036476, elapsed=27.6min]

Entraînement:  86%|████████▋ | 8625/10000 [27:38<04:22,  5.24step/s, loss=0.036476, elapsed=27.6min]

Entraînement:  86%|████████▋ | 8625/10000 [27:38<04:22,  5.24step/s, loss=0.026331, elapsed=27.6min]

Entraînement:  86%|████████▋ | 8626/10000 [27:38<04:22,  5.24step/s, loss=0.026331, elapsed=27.6min]

Entraînement:  86%|████████▋ | 8626/10000 [27:38<04:22,  5.24step/s, loss=0.028803, elapsed=27.6min]

Entraînement:  86%|████████▋ | 8627/10000 [27:38<04:22,  5.23step/s, loss=0.028803, elapsed=27.6min]

Entraînement:  86%|████████▋ | 8627/10000 [27:38<04:22,  5.23step/s, loss=0.032219, elapsed=27.6min]

Entraînement:  86%|████████▋ | 8628/10000 [27:38<04:21,  5.24step/s, loss=0.032219, elapsed=27.6min]

Entraînement:  86%|████████▋ | 8628/10000 [27:38<04:21,  5.24step/s, loss=0.028046, elapsed=27.6min]

Entraînement:  86%|████████▋ | 8629/10000 [27:39<04:21,  5.25step/s, loss=0.028046, elapsed=27.6min]

Entraînement:  86%|████████▋ | 8629/10000 [27:39<04:21,  5.25step/s, loss=0.057607, elapsed=27.7min]

Entraînement:  86%|████████▋ | 8630/10000 [27:39<04:20,  5.26step/s, loss=0.057607, elapsed=27.7min]

Entraînement:  86%|████████▋ | 8630/10000 [27:39<04:20,  5.26step/s, loss=0.048946, elapsed=27.7min]

Entraînement:  86%|████████▋ | 8631/10000 [27:39<04:19,  5.27step/s, loss=0.048946, elapsed=27.7min]

Entraînement:  86%|████████▋ | 8631/10000 [27:39<04:19,  5.27step/s, loss=0.034648, elapsed=27.7min]

Entraînement:  86%|████████▋ | 8632/10000 [27:39<04:19,  5.28step/s, loss=0.034648, elapsed=27.7min]

Entraînement:  86%|████████▋ | 8632/10000 [27:39<04:19,  5.28step/s, loss=0.026809, elapsed=27.7min]

Entraînement:  86%|████████▋ | 8633/10000 [27:39<04:19,  5.28step/s, loss=0.026809, elapsed=27.7min]

Entraînement:  86%|████████▋ | 8633/10000 [27:39<04:19,  5.28step/s, loss=0.051365, elapsed=27.7min]

Entraînement:  86%|████████▋ | 8634/10000 [27:39<04:19,  5.27step/s, loss=0.051365, elapsed=27.7min]

Entraînement:  86%|████████▋ | 8634/10000 [27:39<04:19,  5.27step/s, loss=0.024298, elapsed=27.7min]

Entraînement:  86%|████████▋ | 8635/10000 [27:40<04:19,  5.27step/s, loss=0.024298, elapsed=27.7min]

Entraînement:  86%|████████▋ | 8635/10000 [27:40<04:19,  5.27step/s, loss=0.048872, elapsed=27.7min]

Entraînement:  86%|████████▋ | 8636/10000 [27:40<04:18,  5.28step/s, loss=0.048872, elapsed=27.7min]

Entraînement:  86%|████████▋ | 8636/10000 [27:40<04:18,  5.28step/s, loss=0.028634, elapsed=27.7min]

Entraînement:  86%|████████▋ | 8637/10000 [27:40<04:18,  5.27step/s, loss=0.028634, elapsed=27.7min]

Entraînement:  86%|████████▋ | 8637/10000 [27:40<04:18,  5.27step/s, loss=0.045722, elapsed=27.7min]

Entraînement:  86%|████████▋ | 8638/10000 [27:40<04:18,  5.27step/s, loss=0.045722, elapsed=27.7min]

Entraînement:  86%|████████▋ | 8638/10000 [27:40<04:18,  5.27step/s, loss=0.072359, elapsed=27.7min]

Entraînement:  86%|████████▋ | 8639/10000 [27:40<04:18,  5.27step/s, loss=0.072359, elapsed=27.7min]

Entraînement:  86%|████████▋ | 8639/10000 [27:40<04:18,  5.27step/s, loss=0.023988, elapsed=27.7min]

Entraînement:  86%|████████▋ | 8640/10000 [27:41<04:17,  5.27step/s, loss=0.023988, elapsed=27.7min]

Entraînement:  86%|████████▋ | 8640/10000 [27:41<04:17,  5.27step/s, loss=0.030427, elapsed=27.7min]

Entraînement:  86%|████████▋ | 8641/10000 [27:41<04:17,  5.28step/s, loss=0.030427, elapsed=27.7min]

Entraînement:  86%|████████▋ | 8641/10000 [27:41<04:17,  5.28step/s, loss=0.029445, elapsed=27.7min]

Entraînement:  86%|████████▋ | 8642/10000 [27:41<04:17,  5.27step/s, loss=0.029445, elapsed=27.7min]

Entraînement:  86%|████████▋ | 8642/10000 [27:41<04:17,  5.27step/s, loss=0.031388, elapsed=27.7min]

Entraînement:  86%|████████▋ | 8643/10000 [27:41<04:17,  5.27step/s, loss=0.031388, elapsed=27.7min]

Entraînement:  86%|████████▋ | 8643/10000 [27:41<04:17,  5.27step/s, loss=0.038329, elapsed=27.7min]

Entraînement:  86%|████████▋ | 8644/10000 [27:41<04:16,  5.28step/s, loss=0.038329, elapsed=27.7min]

Entraînement:  86%|████████▋ | 8644/10000 [27:41<04:16,  5.28step/s, loss=0.038211, elapsed=27.7min]

Entraînement:  86%|████████▋ | 8645/10000 [27:42<04:16,  5.27step/s, loss=0.038211, elapsed=27.7min]

Entraînement:  86%|████████▋ | 8645/10000 [27:42<04:16,  5.27step/s, loss=0.085823, elapsed=27.7min]

Entraînement:  86%|████████▋ | 8646/10000 [27:42<04:16,  5.28step/s, loss=0.085823, elapsed=27.7min]

Entraînement:  86%|████████▋ | 8646/10000 [27:42<04:16,  5.28step/s, loss=0.038101, elapsed=27.7min]

Entraînement:  86%|████████▋ | 8647/10000 [27:42<04:16,  5.28step/s, loss=0.038101, elapsed=27.7min]

Entraînement:  86%|████████▋ | 8647/10000 [27:42<04:16,  5.28step/s, loss=0.023090, elapsed=27.7min]

Entraînement:  86%|████████▋ | 8648/10000 [27:42<04:16,  5.26step/s, loss=0.023090, elapsed=27.7min]

Entraînement:  86%|████████▋ | 8648/10000 [27:42<04:16,  5.26step/s, loss=0.035047, elapsed=27.7min]

Entraînement:  86%|████████▋ | 8649/10000 [27:42<04:17,  5.25step/s, loss=0.035047, elapsed=27.7min]

Entraînement:  86%|████████▋ | 8649/10000 [27:42<04:17,  5.25step/s, loss=0.022322, elapsed=27.7min]

Entraînement:  86%|████████▋ | 8650/10000 [27:43<04:16,  5.26step/s, loss=0.022322, elapsed=27.7min]

Entraînement:  86%|████████▋ | 8650/10000 [27:43<04:16,  5.26step/s, loss=0.022350, elapsed=27.7min]

Entraînement:  87%|████████▋ | 8651/10000 [27:43<04:16,  5.27step/s, loss=0.022350, elapsed=27.7min]

Entraînement:  87%|████████▋ | 8651/10000 [27:43<04:16,  5.27step/s, loss=0.053241, elapsed=27.7min]

Entraînement:  87%|████████▋ | 8652/10000 [27:43<04:15,  5.27step/s, loss=0.053241, elapsed=27.7min]

Entraînement:  87%|████████▋ | 8652/10000 [27:43<04:15,  5.27step/s, loss=0.034225, elapsed=27.7min]

Entraînement:  87%|████████▋ | 8653/10000 [27:43<04:14,  5.29step/s, loss=0.034225, elapsed=27.7min]

Entraînement:  87%|████████▋ | 8653/10000 [27:43<04:14,  5.29step/s, loss=0.024730, elapsed=27.7min]

Entraînement:  87%|████████▋ | 8654/10000 [27:43<04:14,  5.28step/s, loss=0.024730, elapsed=27.7min]

Entraînement:  87%|████████▋ | 8654/10000 [27:43<04:14,  5.28step/s, loss=0.037422, elapsed=27.7min]

Entraînement:  87%|████████▋ | 8655/10000 [27:43<04:14,  5.28step/s, loss=0.037422, elapsed=27.7min]

Entraînement:  87%|████████▋ | 8655/10000 [27:43<04:14,  5.28step/s, loss=0.024341, elapsed=27.7min]

Entraînement:  87%|████████▋ | 8656/10000 [27:44<04:14,  5.27step/s, loss=0.024341, elapsed=27.7min]

Entraînement:  87%|████████▋ | 8656/10000 [27:44<04:14,  5.27step/s, loss=0.020422, elapsed=27.7min]

Entraînement:  87%|████████▋ | 8657/10000 [27:44<04:14,  5.27step/s, loss=0.020422, elapsed=27.7min]

Entraînement:  87%|████████▋ | 8657/10000 [27:44<04:14,  5.27step/s, loss=0.036943, elapsed=27.7min]

Entraînement:  87%|████████▋ | 8658/10000 [27:44<04:14,  5.27step/s, loss=0.036943, elapsed=27.7min]

Entraînement:  87%|████████▋ | 8658/10000 [27:44<04:14,  5.27step/s, loss=0.058902, elapsed=27.7min]

Entraînement:  87%|████████▋ | 8659/10000 [27:44<04:14,  5.28step/s, loss=0.058902, elapsed=27.7min]

Entraînement:  87%|████████▋ | 8659/10000 [27:44<04:14,  5.28step/s, loss=0.049835, elapsed=27.7min]

Entraînement:  87%|████████▋ | 8660/10000 [27:44<04:13,  5.28step/s, loss=0.049835, elapsed=27.7min]

Entraînement:  87%|████████▋ | 8660/10000 [27:44<04:13,  5.28step/s, loss=0.043937, elapsed=27.7min]

Entraînement:  87%|████████▋ | 8661/10000 [27:45<04:14,  5.27step/s, loss=0.043937, elapsed=27.7min]

Entraînement:  87%|████████▋ | 8661/10000 [27:45<04:14,  5.27step/s, loss=0.061573, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8662/10000 [27:45<04:13,  5.28step/s, loss=0.061573, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8662/10000 [27:45<04:13,  5.28step/s, loss=0.027081, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8663/10000 [27:45<04:12,  5.29step/s, loss=0.027081, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8663/10000 [27:45<04:12,  5.29step/s, loss=0.029608, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8664/10000 [27:45<04:13,  5.28step/s, loss=0.029608, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8664/10000 [27:45<04:13,  5.28step/s, loss=0.052275, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8665/10000 [27:45<04:12,  5.28step/s, loss=0.052275, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8665/10000 [27:45<04:12,  5.28step/s, loss=0.021341, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8666/10000 [27:46<04:12,  5.28step/s, loss=0.021341, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8666/10000 [27:46<04:12,  5.28step/s, loss=0.028462, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8667/10000 [27:46<04:12,  5.28step/s, loss=0.028462, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8667/10000 [27:46<04:12,  5.28step/s, loss=0.032357, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8668/10000 [27:46<04:12,  5.28step/s, loss=0.032357, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8668/10000 [27:46<04:12,  5.28step/s, loss=0.027244, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8669/10000 [27:46<04:11,  5.29step/s, loss=0.027244, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8669/10000 [27:46<04:11,  5.29step/s, loss=0.018921, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8670/10000 [27:46<04:11,  5.30step/s, loss=0.018921, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8670/10000 [27:46<04:11,  5.30step/s, loss=0.027582, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8671/10000 [27:46<04:10,  5.30step/s, loss=0.027582, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8671/10000 [27:46<04:10,  5.30step/s, loss=0.045312, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8672/10000 [27:47<04:10,  5.29step/s, loss=0.045312, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8672/10000 [27:47<04:10,  5.29step/s, loss=0.031324, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8673/10000 [27:47<04:10,  5.29step/s, loss=0.031324, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8673/10000 [27:47<04:10,  5.29step/s, loss=0.039184, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8674/10000 [27:47<04:10,  5.29step/s, loss=0.039184, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8674/10000 [27:47<04:10,  5.29step/s, loss=0.022476, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8675/10000 [27:47<04:09,  5.30step/s, loss=0.022476, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8675/10000 [27:47<04:09,  5.30step/s, loss=0.032960, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8676/10000 [27:47<04:09,  5.30step/s, loss=0.032960, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8676/10000 [27:47<04:09,  5.30step/s, loss=0.028438, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8677/10000 [27:48<04:09,  5.30step/s, loss=0.028438, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8677/10000 [27:48<04:09,  5.30step/s, loss=0.032078, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8678/10000 [27:48<04:09,  5.29step/s, loss=0.032078, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8678/10000 [27:48<04:09,  5.29step/s, loss=0.021314, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8679/10000 [27:48<04:09,  5.29step/s, loss=0.021314, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8679/10000 [27:48<04:09,  5.29step/s, loss=0.028031, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8680/10000 [27:48<04:09,  5.28step/s, loss=0.028031, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8680/10000 [27:48<04:09,  5.28step/s, loss=0.088971, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8681/10000 [27:48<04:09,  5.28step/s, loss=0.088971, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8681/10000 [27:48<04:09,  5.28step/s, loss=0.021788, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8682/10000 [27:49<04:09,  5.28step/s, loss=0.021788, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8682/10000 [27:49<04:09,  5.28step/s, loss=0.061491, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8683/10000 [27:49<04:08,  5.29step/s, loss=0.061491, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8683/10000 [27:49<04:08,  5.29step/s, loss=0.048566, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8684/10000 [27:49<04:08,  5.29step/s, loss=0.048566, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8684/10000 [27:49<04:08,  5.29step/s, loss=0.031335, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8685/10000 [27:49<04:08,  5.29step/s, loss=0.031335, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8685/10000 [27:49<04:08,  5.29step/s, loss=0.013556, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8686/10000 [27:49<04:08,  5.30step/s, loss=0.013556, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8686/10000 [27:49<04:08,  5.30step/s, loss=0.058268, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8687/10000 [27:50<04:08,  5.29step/s, loss=0.058268, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8687/10000 [27:50<04:08,  5.29step/s, loss=0.030219, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8688/10000 [27:50<04:07,  5.29step/s, loss=0.030219, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8688/10000 [27:50<04:07,  5.29step/s, loss=0.028882, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8689/10000 [27:50<04:08,  5.29step/s, loss=0.028882, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8689/10000 [27:50<04:08,  5.29step/s, loss=0.067328, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8690/10000 [27:50<04:08,  5.27step/s, loss=0.067328, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8690/10000 [27:50<04:08,  5.27step/s, loss=0.035502, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8691/10000 [27:50<04:08,  5.27step/s, loss=0.035502, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8691/10000 [27:50<04:08,  5.27step/s, loss=0.113381, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8692/10000 [27:50<04:07,  5.28step/s, loss=0.113381, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8692/10000 [27:50<04:07,  5.28step/s, loss=0.036736, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8693/10000 [27:51<04:08,  5.27step/s, loss=0.036736, elapsed=27.8min]

Entraînement:  87%|████████▋ | 8693/10000 [27:51<04:08,  5.27step/s, loss=0.060116, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8694/10000 [27:51<04:08,  5.26step/s, loss=0.060116, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8694/10000 [27:51<04:08,  5.26step/s, loss=0.048580, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8695/10000 [27:51<04:07,  5.27step/s, loss=0.048580, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8695/10000 [27:51<04:07,  5.27step/s, loss=0.027551, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8696/10000 [27:51<04:07,  5.26step/s, loss=0.027551, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8696/10000 [27:51<04:07,  5.26step/s, loss=0.018464, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8697/10000 [27:51<04:06,  5.28step/s, loss=0.018464, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8697/10000 [27:51<04:06,  5.28step/s, loss=0.034320, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8698/10000 [27:52<04:07,  5.27step/s, loss=0.034320, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8698/10000 [27:52<04:07,  5.27step/s, loss=0.052403, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8699/10000 [27:52<04:06,  5.27step/s, loss=0.052403, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8699/10000 [27:52<04:06,  5.27step/s, loss=0.043206, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8700/10000 [27:52<04:06,  5.27step/s, loss=0.043206, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8700/10000 [27:52<04:06,  5.27step/s, loss=0.039138, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8700/10000 [27:52<04:06,  5.27step/s, loss=0.039138, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8701/10000 [27:52<04:08,  5.22step/s, loss=0.039138, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8701/10000 [27:52<04:08,  5.22step/s, loss=0.035459, elapsed=27.9min]

Step 8700/10000 | Train loss: 0.039138 | Elapsed: 27.9min | ETA: 4.2min

Entraînement:  87%|████████▋ | 8702/10000 [27:52<04:08,  5.23step/s, loss=0.035459, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8702/10000 [27:52<04:08,  5.23step/s, loss=0.027001, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8703/10000 [27:53<04:07,  5.23step/s, loss=0.027001, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8703/10000 [27:53<04:07,  5.23step/s, loss=0.037138, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8704/10000 [27:53<04:07,  5.23step/s, loss=0.037138, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8704/10000 [27:53<04:07,  5.23step/s, loss=0.083405, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8705/10000 [27:53<04:07,  5.24step/s, loss=0.083405, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8705/10000 [27:53<04:07,  5.24step/s, loss=0.083491, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8706/10000 [27:53<04:07,  5.24step/s, loss=0.083491, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8706/10000 [27:53<04:07,  5.24step/s, loss=0.019884, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8707/10000 [27:53<04:06,  5.24step/s, loss=0.019884, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8707/10000 [27:53<04:06,  5.24step/s, loss=0.052375, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8708/10000 [27:54<04:06,  5.25step/s, loss=0.052375, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8708/10000 [27:54<04:06,  5.25step/s, loss=0.041767, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8709/10000 [27:54<04:05,  5.26step/s, loss=0.041767, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8709/10000 [27:54<04:05,  5.26step/s, loss=0.066855, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8710/10000 [27:54<04:05,  5.26step/s, loss=0.066855, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8710/10000 [27:54<04:05,  5.26step/s, loss=0.030416, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8711/10000 [27:54<04:05,  5.25step/s, loss=0.030416, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8711/10000 [27:54<04:05,  5.25step/s, loss=0.049013, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8712/10000 [27:54<04:05,  5.24step/s, loss=0.049013, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8712/10000 [27:54<04:05,  5.24step/s, loss=0.046328, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8713/10000 [27:54<04:05,  5.24step/s, loss=0.046328, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8713/10000 [27:54<04:05,  5.24step/s, loss=0.032128, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8714/10000 [27:55<04:05,  5.25step/s, loss=0.032128, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8714/10000 [27:55<04:05,  5.25step/s, loss=0.020399, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8715/10000 [27:55<04:04,  5.25step/s, loss=0.020399, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8715/10000 [27:55<04:04,  5.25step/s, loss=0.022724, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8716/10000 [27:55<04:04,  5.25step/s, loss=0.022724, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8716/10000 [27:55<04:04,  5.25step/s, loss=0.019133, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8717/10000 [27:55<04:04,  5.25step/s, loss=0.019133, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8717/10000 [27:55<04:04,  5.25step/s, loss=0.044741, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8718/10000 [27:55<04:04,  5.24step/s, loss=0.044741, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8718/10000 [27:55<04:04,  5.24step/s, loss=0.026021, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8719/10000 [27:56<04:04,  5.24step/s, loss=0.026021, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8719/10000 [27:56<04:04,  5.24step/s, loss=0.048554, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8720/10000 [27:56<04:03,  5.25step/s, loss=0.048554, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8720/10000 [27:56<04:03,  5.25step/s, loss=0.069465, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8721/10000 [27:56<04:03,  5.25step/s, loss=0.069465, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8721/10000 [27:56<04:03,  5.25step/s, loss=0.056696, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8722/10000 [27:56<04:03,  5.26step/s, loss=0.056696, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8722/10000 [27:56<04:03,  5.26step/s, loss=0.023374, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8723/10000 [27:56<04:02,  5.26step/s, loss=0.023374, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8723/10000 [27:56<04:02,  5.26step/s, loss=0.081078, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8724/10000 [27:57<04:01,  5.27step/s, loss=0.081078, elapsed=27.9min]

Entraînement:  87%|████████▋ | 8724/10000 [27:57<04:01,  5.27step/s, loss=0.085660, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8725/10000 [27:57<04:01,  5.29step/s, loss=0.085660, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8725/10000 [27:57<04:01,  5.29step/s, loss=0.018566, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8726/10000 [27:57<04:01,  5.28step/s, loss=0.018566, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8726/10000 [27:57<04:01,  5.28step/s, loss=0.025942, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8727/10000 [27:57<04:00,  5.29step/s, loss=0.025942, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8727/10000 [27:57<04:00,  5.29step/s, loss=0.078956, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8728/10000 [27:57<04:00,  5.29step/s, loss=0.078956, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8728/10000 [27:57<04:00,  5.29step/s, loss=0.043308, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8729/10000 [27:58<04:00,  5.29step/s, loss=0.043308, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8729/10000 [27:58<04:00,  5.29step/s, loss=0.090073, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8730/10000 [27:58<03:59,  5.29step/s, loss=0.090073, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8730/10000 [27:58<03:59,  5.29step/s, loss=0.043071, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8731/10000 [27:58<03:59,  5.29step/s, loss=0.043071, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8731/10000 [27:58<03:59,  5.29step/s, loss=0.050345, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8732/10000 [27:58<03:59,  5.30step/s, loss=0.050345, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8732/10000 [27:58<03:59,  5.30step/s, loss=0.032613, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8733/10000 [27:58<03:59,  5.30step/s, loss=0.032613, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8733/10000 [27:58<03:59,  5.30step/s, loss=0.024475, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8734/10000 [27:58<03:59,  5.28step/s, loss=0.024475, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8734/10000 [27:58<03:59,  5.28step/s, loss=0.044388, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8735/10000 [27:59<03:59,  5.28step/s, loss=0.044388, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8735/10000 [27:59<03:59,  5.28step/s, loss=0.044358, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8736/10000 [27:59<03:59,  5.28step/s, loss=0.044358, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8736/10000 [27:59<03:59,  5.28step/s, loss=0.029164, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8737/10000 [27:59<03:58,  5.29step/s, loss=0.029164, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8737/10000 [27:59<03:58,  5.29step/s, loss=0.032798, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8738/10000 [27:59<03:59,  5.28step/s, loss=0.032798, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8738/10000 [27:59<03:59,  5.28step/s, loss=0.083948, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8739/10000 [27:59<03:58,  5.28step/s, loss=0.083948, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8739/10000 [27:59<03:58,  5.28step/s, loss=0.029246, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8740/10000 [28:00<03:58,  5.28step/s, loss=0.029246, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8740/10000 [28:00<03:58,  5.28step/s, loss=0.041675, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8741/10000 [28:00<03:58,  5.27step/s, loss=0.041675, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8741/10000 [28:00<03:58,  5.27step/s, loss=0.025495, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8742/10000 [28:00<03:58,  5.27step/s, loss=0.025495, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8742/10000 [28:00<03:58,  5.27step/s, loss=0.058294, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8743/10000 [28:00<03:58,  5.27step/s, loss=0.058294, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8743/10000 [28:00<03:58,  5.27step/s, loss=0.055080, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8744/10000 [28:00<03:57,  5.28step/s, loss=0.055080, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8744/10000 [28:00<03:57,  5.28step/s, loss=0.026801, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8745/10000 [28:01<03:57,  5.28step/s, loss=0.026801, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8745/10000 [28:01<03:57,  5.28step/s, loss=0.028623, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8746/10000 [28:01<03:57,  5.29step/s, loss=0.028623, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8746/10000 [28:01<03:57,  5.29step/s, loss=0.045006, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8747/10000 [28:01<03:56,  5.29step/s, loss=0.045006, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8747/10000 [28:01<03:56,  5.29step/s, loss=0.030155, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8748/10000 [28:01<03:56,  5.29step/s, loss=0.030155, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8748/10000 [28:01<03:56,  5.29step/s, loss=0.020093, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8749/10000 [28:01<03:56,  5.29step/s, loss=0.020093, elapsed=28.0min]

Entraînement:  87%|████████▋ | 8749/10000 [28:01<03:56,  5.29step/s, loss=0.019887, elapsed=28.0min]

Entraînement:  88%|████████▊ | 8750/10000 [28:01<03:56,  5.29step/s, loss=0.019887, elapsed=28.0min]

Entraînement:  88%|████████▊ | 8750/10000 [28:01<03:56,  5.29step/s, loss=0.091196, elapsed=28.0min]

Entraînement:  88%|████████▊ | 8751/10000 [28:02<03:56,  5.29step/s, loss=0.091196, elapsed=28.0min]

Entraînement:  88%|████████▊ | 8751/10000 [28:02<03:56,  5.29step/s, loss=0.020330, elapsed=28.0min]

Entraînement:  88%|████████▊ | 8752/10000 [28:02<03:55,  5.29step/s, loss=0.020330, elapsed=28.0min]

Entraînement:  88%|████████▊ | 8752/10000 [28:02<03:55,  5.29step/s, loss=0.036493, elapsed=28.0min]

Entraînement:  88%|████████▊ | 8753/10000 [28:02<03:55,  5.29step/s, loss=0.036493, elapsed=28.0min]

Entraînement:  88%|████████▊ | 8753/10000 [28:02<03:55,  5.29step/s, loss=0.033258, elapsed=28.0min]

Entraînement:  88%|████████▊ | 8754/10000 [28:02<03:55,  5.28step/s, loss=0.033258, elapsed=28.0min]

Entraînement:  88%|████████▊ | 8754/10000 [28:02<03:55,  5.28step/s, loss=0.069013, elapsed=28.0min]

Entraînement:  88%|████████▊ | 8755/10000 [28:02<03:56,  5.28step/s, loss=0.069013, elapsed=28.0min]

Entraînement:  88%|████████▊ | 8755/10000 [28:02<03:56,  5.28step/s, loss=0.043144, elapsed=28.0min]

Entraînement:  88%|████████▊ | 8756/10000 [28:03<03:56,  5.27step/s, loss=0.043144, elapsed=28.0min]

Entraînement:  88%|████████▊ | 8756/10000 [28:03<03:56,  5.27step/s, loss=0.030110, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8757/10000 [28:03<03:55,  5.28step/s, loss=0.030110, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8757/10000 [28:03<03:55,  5.28step/s, loss=0.037403, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8758/10000 [28:03<03:55,  5.27step/s, loss=0.037403, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8758/10000 [28:03<03:55,  5.27step/s, loss=0.048704, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8759/10000 [28:03<03:55,  5.27step/s, loss=0.048704, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8759/10000 [28:03<03:55,  5.27step/s, loss=0.119716, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8760/10000 [28:03<03:55,  5.27step/s, loss=0.119716, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8760/10000 [28:03<03:55,  5.27step/s, loss=0.056843, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8761/10000 [28:04<03:55,  5.27step/s, loss=0.056843, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8761/10000 [28:04<03:55,  5.27step/s, loss=0.086740, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8762/10000 [28:04<03:54,  5.27step/s, loss=0.086740, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8762/10000 [28:04<03:54,  5.27step/s, loss=0.042936, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8763/10000 [28:04<03:54,  5.28step/s, loss=0.042936, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8763/10000 [28:04<03:54,  5.28step/s, loss=0.028126, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8764/10000 [28:04<03:54,  5.28step/s, loss=0.028126, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8764/10000 [28:04<03:54,  5.28step/s, loss=0.026019, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8765/10000 [28:04<03:54,  5.26step/s, loss=0.026019, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8765/10000 [28:04<03:54,  5.26step/s, loss=0.126809, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8766/10000 [28:05<03:53,  5.27step/s, loss=0.126809, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8766/10000 [28:05<03:53,  5.27step/s, loss=0.025697, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8767/10000 [28:05<03:54,  5.27step/s, loss=0.025697, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8767/10000 [28:05<03:54,  5.27step/s, loss=0.039616, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8768/10000 [28:05<03:53,  5.28step/s, loss=0.039616, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8768/10000 [28:05<03:53,  5.28step/s, loss=0.019930, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8769/10000 [28:05<03:53,  5.27step/s, loss=0.019930, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8769/10000 [28:05<03:53,  5.27step/s, loss=0.034680, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8770/10000 [28:05<03:53,  5.28step/s, loss=0.034680, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8770/10000 [28:05<03:53,  5.28step/s, loss=0.030317, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8771/10000 [28:05<03:52,  5.28step/s, loss=0.030317, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8771/10000 [28:05<03:52,  5.28step/s, loss=0.113679, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8772/10000 [28:06<03:53,  5.26step/s, loss=0.113679, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8772/10000 [28:06<03:53,  5.26step/s, loss=0.028830, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8773/10000 [28:06<03:53,  5.26step/s, loss=0.028830, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8773/10000 [28:06<03:53,  5.26step/s, loss=0.081136, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8774/10000 [28:06<03:52,  5.26step/s, loss=0.081136, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8774/10000 [28:06<03:52,  5.26step/s, loss=0.044206, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8775/10000 [28:06<03:52,  5.27step/s, loss=0.044206, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8775/10000 [28:06<03:52,  5.27step/s, loss=0.026909, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8776/10000 [28:06<03:51,  5.28step/s, loss=0.026909, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8776/10000 [28:06<03:51,  5.28step/s, loss=0.089410, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8777/10000 [28:07<03:51,  5.28step/s, loss=0.089410, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8777/10000 [28:07<03:51,  5.28step/s, loss=0.017184, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8778/10000 [28:07<03:51,  5.29step/s, loss=0.017184, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8778/10000 [28:07<03:51,  5.29step/s, loss=0.084220, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8779/10000 [28:07<03:50,  5.29step/s, loss=0.084220, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8779/10000 [28:07<03:50,  5.29step/s, loss=0.074496, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8780/10000 [28:07<03:50,  5.29step/s, loss=0.074496, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8780/10000 [28:07<03:50,  5.29step/s, loss=0.021013, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8781/10000 [28:07<03:50,  5.28step/s, loss=0.021013, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8781/10000 [28:07<03:50,  5.28step/s, loss=0.019191, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8782/10000 [28:08<03:50,  5.28step/s, loss=0.019191, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8782/10000 [28:08<03:50,  5.28step/s, loss=0.018454, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8783/10000 [28:08<03:50,  5.28step/s, loss=0.018454, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8783/10000 [28:08<03:50,  5.28step/s, loss=0.012514, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8784/10000 [28:08<03:50,  5.27step/s, loss=0.012514, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8784/10000 [28:08<03:50,  5.27step/s, loss=0.020161, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8785/10000 [28:08<03:50,  5.27step/s, loss=0.020161, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8785/10000 [28:08<03:50,  5.27step/s, loss=0.049019, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8786/10000 [28:08<03:50,  5.27step/s, loss=0.049019, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8786/10000 [28:08<03:50,  5.27step/s, loss=0.019583, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8787/10000 [28:08<03:50,  5.27step/s, loss=0.019583, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8787/10000 [28:08<03:50,  5.27step/s, loss=0.059939, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8788/10000 [28:09<03:50,  5.25step/s, loss=0.059939, elapsed=28.1min]

Entraînement:  88%|████████▊ | 8788/10000 [28:09<03:50,  5.25step/s, loss=0.032879, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8789/10000 [28:09<03:50,  5.26step/s, loss=0.032879, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8789/10000 [28:09<03:50,  5.26step/s, loss=0.025799, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8790/10000 [28:09<03:49,  5.27step/s, loss=0.025799, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8790/10000 [28:09<03:49,  5.27step/s, loss=0.034719, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8791/10000 [28:09<03:49,  5.27step/s, loss=0.034719, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8791/10000 [28:09<03:49,  5.27step/s, loss=0.051980, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8792/10000 [28:09<03:50,  5.23step/s, loss=0.051980, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8792/10000 [28:09<03:50,  5.23step/s, loss=0.030271, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8793/10000 [28:10<03:50,  5.24step/s, loss=0.030271, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8793/10000 [28:10<03:50,  5.24step/s, loss=0.053934, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8794/10000 [28:10<03:50,  5.24step/s, loss=0.053934, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8794/10000 [28:10<03:50,  5.24step/s, loss=0.025433, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8795/10000 [28:10<03:50,  5.23step/s, loss=0.025433, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8795/10000 [28:10<03:50,  5.23step/s, loss=0.039702, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8796/10000 [28:10<03:49,  5.24step/s, loss=0.039702, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8796/10000 [28:10<03:49,  5.24step/s, loss=0.025544, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8797/10000 [28:10<03:49,  5.24step/s, loss=0.025544, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8797/10000 [28:10<03:49,  5.24step/s, loss=0.028829, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8798/10000 [28:11<03:49,  5.25step/s, loss=0.028829, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8798/10000 [28:11<03:49,  5.25step/s, loss=0.021785, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8799/10000 [28:11<03:49,  5.24step/s, loss=0.021785, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8799/10000 [28:11<03:49,  5.24step/s, loss=0.055236, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8800/10000 [28:11<03:48,  5.24step/s, loss=0.055236, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8800/10000 [28:11<03:48,  5.24step/s, loss=0.108132, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8800/10000 [28:11<03:48,  5.24step/s, loss=0.108132, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8801/10000 [28:11<03:50,  5.20step/s, loss=0.108132, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8801/10000 [28:11<03:50,  5.20step/s, loss=0.031142, elapsed=28.2min]

Step 8800/10000 | Train loss: 0.108132 | Elapsed: 28.2min | ETA: 3.8min

Entraînement:  88%|████████▊ | 8802/10000 [28:11<03:49,  5.21step/s, loss=0.031142, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8802/10000 [28:11<03:49,  5.21step/s, loss=0.049731, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8803/10000 [28:12<03:49,  5.22step/s, loss=0.049731, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8803/10000 [28:12<03:49,  5.22step/s, loss=0.098218, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8804/10000 [28:12<03:48,  5.24step/s, loss=0.098218, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8804/10000 [28:12<03:48,  5.24step/s, loss=0.056056, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8805/10000 [28:12<03:47,  5.24step/s, loss=0.056056, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8805/10000 [28:12<03:47,  5.24step/s, loss=0.060054, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8806/10000 [28:12<03:47,  5.25step/s, loss=0.060054, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8806/10000 [28:12<03:47,  5.25step/s, loss=0.059406, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8807/10000 [28:12<03:47,  5.25step/s, loss=0.059406, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8807/10000 [28:12<03:47,  5.25step/s, loss=0.023416, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8808/10000 [28:12<03:46,  5.25step/s, loss=0.023416, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8808/10000 [28:13<03:46,  5.25step/s, loss=0.037307, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8809/10000 [28:13<03:46,  5.26step/s, loss=0.037307, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8809/10000 [28:13<03:46,  5.26step/s, loss=0.072054, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8810/10000 [28:13<03:46,  5.25step/s, loss=0.072054, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8810/10000 [28:13<03:46,  5.25step/s, loss=0.041499, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8811/10000 [28:13<03:47,  5.24step/s, loss=0.041499, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8811/10000 [28:13<03:47,  5.24step/s, loss=0.036231, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8812/10000 [28:13<03:46,  5.24step/s, loss=0.036231, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8812/10000 [28:13<03:46,  5.24step/s, loss=0.102713, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8813/10000 [28:13<03:46,  5.23step/s, loss=0.102713, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8813/10000 [28:13<03:46,  5.23step/s, loss=0.075691, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8814/10000 [28:14<03:46,  5.23step/s, loss=0.075691, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8814/10000 [28:14<03:46,  5.23step/s, loss=0.030572, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8815/10000 [28:14<03:46,  5.24step/s, loss=0.030572, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8815/10000 [28:14<03:46,  5.24step/s, loss=0.022149, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8816/10000 [28:14<03:45,  5.24step/s, loss=0.022149, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8816/10000 [28:14<03:45,  5.24step/s, loss=0.044361, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8817/10000 [28:14<03:45,  5.26step/s, loss=0.044361, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8817/10000 [28:14<03:45,  5.26step/s, loss=0.070958, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8818/10000 [28:14<03:45,  5.24step/s, loss=0.070958, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8818/10000 [28:14<03:45,  5.24step/s, loss=0.037515, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8819/10000 [28:15<03:45,  5.23step/s, loss=0.037515, elapsed=28.2min]

Entraînement:  88%|████████▊ | 8819/10000 [28:15<03:45,  5.23step/s, loss=0.016170, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8820/10000 [28:15<03:45,  5.24step/s, loss=0.016170, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8820/10000 [28:15<03:45,  5.24step/s, loss=0.021356, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8821/10000 [28:15<03:44,  5.25step/s, loss=0.021356, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8821/10000 [28:15<03:44,  5.25step/s, loss=0.035788, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8822/10000 [28:15<03:44,  5.25step/s, loss=0.035788, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8822/10000 [28:15<03:44,  5.25step/s, loss=0.108854, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8823/10000 [28:15<03:44,  5.25step/s, loss=0.108854, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8823/10000 [28:15<03:44,  5.25step/s, loss=0.023974, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8824/10000 [28:16<03:44,  5.25step/s, loss=0.023974, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8824/10000 [28:16<03:44,  5.25step/s, loss=0.036554, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8825/10000 [28:16<03:44,  5.25step/s, loss=0.036554, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8825/10000 [28:16<03:44,  5.25step/s, loss=0.038286, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8826/10000 [28:16<03:43,  5.24step/s, loss=0.038286, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8826/10000 [28:16<03:43,  5.24step/s, loss=0.071636, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8827/10000 [28:16<03:43,  5.24step/s, loss=0.071636, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8827/10000 [28:16<03:43,  5.24step/s, loss=0.056613, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8828/10000 [28:16<03:43,  5.24step/s, loss=0.056613, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8828/10000 [28:16<03:43,  5.24step/s, loss=0.058892, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8829/10000 [28:17<03:43,  5.25step/s, loss=0.058892, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8829/10000 [28:17<03:43,  5.25step/s, loss=0.064656, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8830/10000 [28:17<03:43,  5.24step/s, loss=0.064656, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8830/10000 [28:17<03:43,  5.24step/s, loss=0.062449, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8831/10000 [28:17<03:42,  5.25step/s, loss=0.062449, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8831/10000 [28:17<03:42,  5.25step/s, loss=0.032022, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8832/10000 [28:17<03:42,  5.25step/s, loss=0.032022, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8832/10000 [28:17<03:42,  5.25step/s, loss=0.032199, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8833/10000 [28:17<03:42,  5.24step/s, loss=0.032199, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8833/10000 [28:17<03:42,  5.24step/s, loss=0.056341, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8834/10000 [28:17<03:42,  5.23step/s, loss=0.056341, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8834/10000 [28:17<03:42,  5.23step/s, loss=0.080325, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8835/10000 [28:18<03:42,  5.25step/s, loss=0.080325, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8835/10000 [28:18<03:42,  5.25step/s, loss=0.102893, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8836/10000 [28:18<03:42,  5.24step/s, loss=0.102893, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8836/10000 [28:18<03:42,  5.24step/s, loss=0.141046, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8837/10000 [28:18<03:41,  5.25step/s, loss=0.141046, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8837/10000 [28:18<03:41,  5.25step/s, loss=0.077921, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8838/10000 [28:18<03:41,  5.25step/s, loss=0.077921, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8838/10000 [28:18<03:41,  5.25step/s, loss=0.073191, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8839/10000 [28:18<03:40,  5.26step/s, loss=0.073191, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8839/10000 [28:18<03:40,  5.26step/s, loss=0.184499, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8840/10000 [28:19<03:40,  5.26step/s, loss=0.184499, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8840/10000 [28:19<03:40,  5.26step/s, loss=0.031590, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8841/10000 [28:19<03:40,  5.26step/s, loss=0.031590, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8841/10000 [28:19<03:40,  5.26step/s, loss=0.131707, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8842/10000 [28:19<03:39,  5.27step/s, loss=0.131707, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8842/10000 [28:19<03:39,  5.27step/s, loss=0.055659, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8843/10000 [28:19<03:39,  5.27step/s, loss=0.055659, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8843/10000 [28:19<03:39,  5.27step/s, loss=0.040181, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8844/10000 [28:19<03:39,  5.27step/s, loss=0.040181, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8844/10000 [28:19<03:39,  5.27step/s, loss=0.062302, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8845/10000 [28:20<03:40,  5.23step/s, loss=0.062302, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8845/10000 [28:20<03:40,  5.23step/s, loss=0.077936, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8846/10000 [28:20<03:39,  5.25step/s, loss=0.077936, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8846/10000 [28:20<03:39,  5.25step/s, loss=0.034386, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8847/10000 [28:20<03:40,  5.24step/s, loss=0.034386, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8847/10000 [28:20<03:40,  5.24step/s, loss=0.021696, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8848/10000 [28:20<03:39,  5.25step/s, loss=0.021696, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8848/10000 [28:20<03:39,  5.25step/s, loss=0.050259, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8849/10000 [28:20<03:39,  5.25step/s, loss=0.050259, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8849/10000 [28:20<03:39,  5.25step/s, loss=0.047954, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8850/10000 [28:21<03:38,  5.26step/s, loss=0.047954, elapsed=28.3min]

Entraînement:  88%|████████▊ | 8850/10000 [28:21<03:38,  5.26step/s, loss=0.036323, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8851/10000 [28:21<03:38,  5.26step/s, loss=0.036323, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8851/10000 [28:21<03:38,  5.26step/s, loss=0.034524, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8852/10000 [28:21<03:37,  5.27step/s, loss=0.034524, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8852/10000 [28:21<03:37,  5.27step/s, loss=0.037155, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8853/10000 [28:21<03:37,  5.27step/s, loss=0.037155, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8853/10000 [28:21<03:37,  5.27step/s, loss=0.113352, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8854/10000 [28:21<03:37,  5.27step/s, loss=0.113352, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8854/10000 [28:21<03:37,  5.27step/s, loss=0.037387, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8855/10000 [28:21<03:37,  5.27step/s, loss=0.037387, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8855/10000 [28:21<03:37,  5.27step/s, loss=0.090670, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8856/10000 [28:22<03:37,  5.27step/s, loss=0.090670, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8856/10000 [28:22<03:37,  5.27step/s, loss=0.033015, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8857/10000 [28:22<03:36,  5.28step/s, loss=0.033015, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8857/10000 [28:22<03:36,  5.28step/s, loss=0.085785, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8858/10000 [28:22<03:36,  5.27step/s, loss=0.085785, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8858/10000 [28:22<03:36,  5.27step/s, loss=0.050865, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8859/10000 [28:22<03:36,  5.28step/s, loss=0.050865, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8859/10000 [28:22<03:36,  5.28step/s, loss=0.040874, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8860/10000 [28:22<03:36,  5.27step/s, loss=0.040874, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8860/10000 [28:22<03:36,  5.27step/s, loss=0.032505, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8861/10000 [28:23<03:35,  5.27step/s, loss=0.032505, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8861/10000 [28:23<03:35,  5.27step/s, loss=0.117400, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8862/10000 [28:23<03:35,  5.27step/s, loss=0.117400, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8862/10000 [28:23<03:35,  5.27step/s, loss=0.076763, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8863/10000 [28:23<03:35,  5.27step/s, loss=0.076763, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8863/10000 [28:23<03:35,  5.27step/s, loss=0.034829, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8864/10000 [28:23<03:35,  5.27step/s, loss=0.034829, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8864/10000 [28:23<03:35,  5.27step/s, loss=0.037285, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8865/10000 [28:23<03:35,  5.28step/s, loss=0.037285, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8865/10000 [28:23<03:35,  5.28step/s, loss=0.026105, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8866/10000 [28:24<03:34,  5.28step/s, loss=0.026105, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8866/10000 [28:24<03:34,  5.28step/s, loss=0.023720, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8867/10000 [28:24<03:34,  5.28step/s, loss=0.023720, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8867/10000 [28:24<03:34,  5.28step/s, loss=0.025800, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8868/10000 [28:24<03:34,  5.28step/s, loss=0.025800, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8868/10000 [28:24<03:34,  5.28step/s, loss=0.135370, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8869/10000 [28:24<03:34,  5.28step/s, loss=0.135370, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8869/10000 [28:24<03:34,  5.28step/s, loss=0.021678, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8870/10000 [28:24<03:35,  5.25step/s, loss=0.021678, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8870/10000 [28:24<03:35,  5.25step/s, loss=0.042806, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8871/10000 [28:24<03:35,  5.24step/s, loss=0.042806, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8871/10000 [28:24<03:35,  5.24step/s, loss=0.016585, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8872/10000 [28:25<03:34,  5.26step/s, loss=0.016585, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8872/10000 [28:25<03:34,  5.26step/s, loss=0.035599, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8873/10000 [28:25<03:34,  5.26step/s, loss=0.035599, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8873/10000 [28:25<03:34,  5.26step/s, loss=0.044787, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8874/10000 [28:25<03:34,  5.25step/s, loss=0.044787, elapsed=28.4min]

Entraînement:  89%|████████▊ | 8874/10000 [28:25<03:34,  5.25step/s, loss=0.065485, elapsed=28.4min]

Entraînement:  89%|████████▉ | 8875/10000 [28:25<03:34,  5.25step/s, loss=0.065485, elapsed=28.4min]

Entraînement:  89%|████████▉ | 8875/10000 [28:25<03:34,  5.25step/s, loss=0.019271, elapsed=28.4min]

Entraînement:  89%|████████▉ | 8876/10000 [28:25<03:33,  5.26step/s, loss=0.019271, elapsed=28.4min]

Entraînement:  89%|████████▉ | 8876/10000 [28:25<03:33,  5.26step/s, loss=0.059659, elapsed=28.4min]

Entraînement:  89%|████████▉ | 8877/10000 [28:26<03:33,  5.27step/s, loss=0.059659, elapsed=28.4min]

Entraînement:  89%|████████▉ | 8877/10000 [28:26<03:33,  5.27step/s, loss=0.025304, elapsed=28.4min]

Entraînement:  89%|████████▉ | 8878/10000 [28:26<03:33,  5.26step/s, loss=0.025304, elapsed=28.4min]

Entraînement:  89%|████████▉ | 8878/10000 [28:26<03:33,  5.26step/s, loss=0.048552, elapsed=28.4min]

Entraînement:  89%|████████▉ | 8879/10000 [28:26<03:33,  5.25step/s, loss=0.048552, elapsed=28.4min]

Entraînement:  89%|████████▉ | 8879/10000 [28:26<03:33,  5.25step/s, loss=0.048344, elapsed=28.4min]

Entraînement:  89%|████████▉ | 8880/10000 [28:26<03:32,  5.26step/s, loss=0.048344, elapsed=28.4min]

Entraînement:  89%|████████▉ | 8880/10000 [28:26<03:32,  5.26step/s, loss=0.081126, elapsed=28.4min]

Entraînement:  89%|████████▉ | 8881/10000 [28:26<03:32,  5.26step/s, loss=0.081126, elapsed=28.4min]

Entraînement:  89%|████████▉ | 8881/10000 [28:26<03:32,  5.26step/s, loss=0.019696, elapsed=28.4min]

Entraînement:  89%|████████▉ | 8882/10000 [28:27<03:32,  5.27step/s, loss=0.019696, elapsed=28.4min]

Entraînement:  89%|████████▉ | 8882/10000 [28:27<03:32,  5.27step/s, loss=0.038837, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8883/10000 [28:27<03:32,  5.27step/s, loss=0.038837, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8883/10000 [28:27<03:32,  5.27step/s, loss=0.016433, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8884/10000 [28:27<03:32,  5.26step/s, loss=0.016433, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8884/10000 [28:27<03:32,  5.26step/s, loss=0.035686, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8885/10000 [28:27<03:31,  5.27step/s, loss=0.035686, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8885/10000 [28:27<03:31,  5.27step/s, loss=0.092837, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8886/10000 [28:27<03:31,  5.26step/s, loss=0.092837, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8886/10000 [28:27<03:31,  5.26step/s, loss=0.095013, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8887/10000 [28:28<03:31,  5.26step/s, loss=0.095013, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8887/10000 [28:28<03:31,  5.26step/s, loss=0.042355, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8888/10000 [28:28<03:31,  5.26step/s, loss=0.042355, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8888/10000 [28:28<03:31,  5.26step/s, loss=0.020540, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8889/10000 [28:28<03:30,  5.27step/s, loss=0.020540, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8889/10000 [28:28<03:30,  5.27step/s, loss=0.029545, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8890/10000 [28:28<03:30,  5.28step/s, loss=0.029545, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8890/10000 [28:28<03:30,  5.28step/s, loss=0.031086, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8891/10000 [28:28<03:30,  5.27step/s, loss=0.031086, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8891/10000 [28:28<03:30,  5.27step/s, loss=0.038563, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8892/10000 [28:28<03:30,  5.27step/s, loss=0.038563, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8892/10000 [28:28<03:30,  5.27step/s, loss=0.049386, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8893/10000 [28:29<03:30,  5.26step/s, loss=0.049386, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8893/10000 [28:29<03:30,  5.26step/s, loss=0.030401, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8894/10000 [28:29<03:30,  5.26step/s, loss=0.030401, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8894/10000 [28:29<03:30,  5.26step/s, loss=0.038359, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8895/10000 [28:29<03:29,  5.27step/s, loss=0.038359, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8895/10000 [28:29<03:29,  5.27step/s, loss=0.065641, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8896/10000 [28:29<03:30,  5.25step/s, loss=0.065641, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8896/10000 [28:29<03:30,  5.25step/s, loss=0.048938, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8897/10000 [28:29<03:29,  5.26step/s, loss=0.048938, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8897/10000 [28:29<03:29,  5.26step/s, loss=0.057941, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8898/10000 [28:30<03:29,  5.26step/s, loss=0.057941, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8898/10000 [28:30<03:29,  5.26step/s, loss=0.077311, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8899/10000 [28:30<03:28,  5.27step/s, loss=0.077311, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8899/10000 [28:30<03:28,  5.27step/s, loss=0.091917, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8900/10000 [28:30<03:28,  5.27step/s, loss=0.091917, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8900/10000 [28:30<03:28,  5.27step/s, loss=0.033389, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8900/10000 [28:30<03:28,  5.27step/s, loss=0.033389, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8901/10000 [28:30<03:30,  5.22step/s, loss=0.033389, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8901/10000 [28:30<03:30,  5.22step/s, loss=0.036037, elapsed=28.5min]

Step 8900/10000 | Train loss: 0.033389 | Elapsed: 28.5min | ETA: 3.5min

Entraînement:  89%|████████▉ | 8902/10000 [28:30<03:29,  5.24step/s, loss=0.036037, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8902/10000 [28:30<03:29,  5.24step/s, loss=0.049742, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8903/10000 [28:31<03:28,  5.26step/s, loss=0.049742, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8903/10000 [28:31<03:28,  5.26step/s, loss=0.111195, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8904/10000 [28:31<03:28,  5.26step/s, loss=0.111195, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8904/10000 [28:31<03:28,  5.26step/s, loss=0.025637, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8905/10000 [28:31<03:27,  5.28step/s, loss=0.025637, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8905/10000 [28:31<03:27,  5.28step/s, loss=0.057904, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8906/10000 [28:31<03:27,  5.28step/s, loss=0.057904, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8906/10000 [28:31<03:27,  5.28step/s, loss=0.108901, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8907/10000 [28:31<03:26,  5.28step/s, loss=0.108901, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8907/10000 [28:31<03:26,  5.28step/s, loss=0.052835, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8908/10000 [28:32<03:27,  5.26step/s, loss=0.052835, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8908/10000 [28:32<03:27,  5.26step/s, loss=0.038937, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8909/10000 [28:32<03:27,  5.26step/s, loss=0.038937, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8909/10000 [28:32<03:27,  5.26step/s, loss=0.052086, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8910/10000 [28:32<03:27,  5.27step/s, loss=0.052086, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8910/10000 [28:32<03:27,  5.27step/s, loss=0.022177, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8911/10000 [28:32<03:28,  5.22step/s, loss=0.022177, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8911/10000 [28:32<03:28,  5.22step/s, loss=0.031404, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8912/10000 [28:32<03:27,  5.23step/s, loss=0.031404, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8912/10000 [28:32<03:27,  5.23step/s, loss=0.025016, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8913/10000 [28:32<03:27,  5.24step/s, loss=0.025016, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8913/10000 [28:32<03:27,  5.24step/s, loss=0.015990, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8914/10000 [28:33<03:26,  5.25step/s, loss=0.015990, elapsed=28.5min]

Entraînement:  89%|████████▉ | 8914/10000 [28:33<03:26,  5.25step/s, loss=0.012867, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8915/10000 [28:33<03:26,  5.26step/s, loss=0.012867, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8915/10000 [28:33<03:26,  5.26step/s, loss=0.029959, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8916/10000 [28:33<03:25,  5.27step/s, loss=0.029959, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8916/10000 [28:33<03:25,  5.27step/s, loss=0.082735, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8917/10000 [28:33<03:25,  5.27step/s, loss=0.082735, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8917/10000 [28:33<03:25,  5.27step/s, loss=0.026565, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8918/10000 [28:33<03:25,  5.28step/s, loss=0.026565, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8918/10000 [28:33<03:25,  5.28step/s, loss=0.023832, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8919/10000 [28:34<03:25,  5.27step/s, loss=0.023832, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8919/10000 [28:34<03:25,  5.27step/s, loss=0.038023, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8920/10000 [28:34<03:24,  5.27step/s, loss=0.038023, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8920/10000 [28:34<03:24,  5.27step/s, loss=0.092461, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8921/10000 [28:34<03:24,  5.29step/s, loss=0.092461, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8921/10000 [28:34<03:24,  5.29step/s, loss=0.023748, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8922/10000 [28:35<05:11,  3.46step/s, loss=0.023748, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8922/10000 [28:35<05:11,  3.46step/s, loss=0.024910, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8923/10000 [28:35<04:40,  3.84step/s, loss=0.024910, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8923/10000 [28:35<04:40,  3.84step/s, loss=0.041751, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8924/10000 [28:35<04:17,  4.17step/s, loss=0.041751, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8924/10000 [28:35<04:17,  4.17step/s, loss=0.045424, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8925/10000 [28:35<04:01,  4.45step/s, loss=0.045424, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8925/10000 [28:35<04:01,  4.45step/s, loss=0.024635, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8926/10000 [28:35<03:50,  4.66step/s, loss=0.024635, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8926/10000 [28:35<03:50,  4.66step/s, loss=0.101646, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8927/10000 [28:35<03:42,  4.82step/s, loss=0.101646, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8927/10000 [28:35<03:42,  4.82step/s, loss=0.037854, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8928/10000 [28:36<03:36,  4.94step/s, loss=0.037854, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8928/10000 [28:36<03:36,  4.94step/s, loss=0.030261, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8929/10000 [28:36<03:32,  5.04step/s, loss=0.030261, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8929/10000 [28:36<03:32,  5.04step/s, loss=0.053501, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8930/10000 [28:36<03:29,  5.10step/s, loss=0.053501, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8930/10000 [28:36<03:29,  5.10step/s, loss=0.037591, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8931/10000 [28:36<03:27,  5.15step/s, loss=0.037591, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8931/10000 [28:36<03:27,  5.15step/s, loss=0.045222, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8932/10000 [28:36<03:26,  5.18step/s, loss=0.045222, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8932/10000 [28:36<03:26,  5.18step/s, loss=0.061657, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8933/10000 [28:37<03:25,  5.20step/s, loss=0.061657, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8933/10000 [28:37<03:25,  5.20step/s, loss=0.024659, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8934/10000 [28:37<03:24,  5.22step/s, loss=0.024659, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8934/10000 [28:37<03:24,  5.22step/s, loss=0.023487, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8935/10000 [28:37<03:23,  5.22step/s, loss=0.023487, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8935/10000 [28:37<03:23,  5.22step/s, loss=0.017669, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8936/10000 [28:37<03:23,  5.23step/s, loss=0.017669, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8936/10000 [28:37<03:23,  5.23step/s, loss=0.032514, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8937/10000 [28:37<03:22,  5.25step/s, loss=0.032514, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8937/10000 [28:37<03:22,  5.25step/s, loss=0.023315, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8938/10000 [28:38<03:22,  5.25step/s, loss=0.023315, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8938/10000 [28:38<03:22,  5.25step/s, loss=0.044989, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8939/10000 [28:38<03:22,  5.25step/s, loss=0.044989, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8939/10000 [28:38<03:22,  5.25step/s, loss=0.100842, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8940/10000 [28:38<03:21,  5.25step/s, loss=0.100842, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8940/10000 [28:38<03:21,  5.25step/s, loss=0.024688, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8941/10000 [28:38<03:21,  5.25step/s, loss=0.024688, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8941/10000 [28:38<03:21,  5.25step/s, loss=0.094673, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8942/10000 [28:38<03:21,  5.25step/s, loss=0.094673, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8942/10000 [28:38<03:21,  5.25step/s, loss=0.071730, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8943/10000 [28:39<03:21,  5.25step/s, loss=0.071730, elapsed=28.6min]

Entraînement:  89%|████████▉ | 8943/10000 [28:39<03:21,  5.25step/s, loss=0.061462, elapsed=28.7min]

Entraînement:  89%|████████▉ | 8944/10000 [28:39<03:21,  5.24step/s, loss=0.061462, elapsed=28.7min]

Entraînement:  89%|████████▉ | 8944/10000 [28:39<03:21,  5.24step/s, loss=0.034817, elapsed=28.7min]

Entraînement:  89%|████████▉ | 8945/10000 [28:39<03:21,  5.25step/s, loss=0.034817, elapsed=28.7min]

Entraînement:  89%|████████▉ | 8945/10000 [28:39<03:21,  5.25step/s, loss=0.046337, elapsed=28.7min]

Entraînement:  89%|████████▉ | 8946/10000 [28:39<03:20,  5.27step/s, loss=0.046337, elapsed=28.7min]

Entraînement:  89%|████████▉ | 8946/10000 [28:39<03:20,  5.27step/s, loss=0.107645, elapsed=28.7min]

Entraînement:  89%|████████▉ | 8947/10000 [28:39<03:20,  5.26step/s, loss=0.107645, elapsed=28.7min]

Entraînement:  89%|████████▉ | 8947/10000 [28:39<03:20,  5.26step/s, loss=0.019403, elapsed=28.7min]

Entraînement:  89%|████████▉ | 8948/10000 [28:39<03:19,  5.27step/s, loss=0.019403, elapsed=28.7min]

Entraînement:  89%|████████▉ | 8948/10000 [28:39<03:19,  5.27step/s, loss=0.103932, elapsed=28.7min]

Entraînement:  89%|████████▉ | 8949/10000 [28:40<03:19,  5.28step/s, loss=0.103932, elapsed=28.7min]

Entraînement:  89%|████████▉ | 8949/10000 [28:40<03:19,  5.28step/s, loss=0.031261, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8950/10000 [28:40<03:19,  5.25step/s, loss=0.031261, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8950/10000 [28:40<03:19,  5.25step/s, loss=0.042203, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8951/10000 [28:40<03:20,  5.24step/s, loss=0.042203, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8951/10000 [28:40<03:20,  5.24step/s, loss=0.016989, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8952/10000 [28:40<03:19,  5.25step/s, loss=0.016989, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8952/10000 [28:40<03:19,  5.25step/s, loss=0.093712, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8953/10000 [28:40<03:19,  5.26step/s, loss=0.093712, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8953/10000 [28:40<03:19,  5.26step/s, loss=0.023782, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8954/10000 [28:41<03:18,  5.26step/s, loss=0.023782, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8954/10000 [28:41<03:18,  5.26step/s, loss=0.094981, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8955/10000 [28:41<03:18,  5.27step/s, loss=0.094981, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8955/10000 [28:41<03:18,  5.27step/s, loss=0.131444, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8956/10000 [28:41<03:17,  5.27step/s, loss=0.131444, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8956/10000 [28:41<03:17,  5.27step/s, loss=0.071938, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8957/10000 [28:41<03:17,  5.28step/s, loss=0.071938, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8957/10000 [28:41<03:17,  5.28step/s, loss=0.033318, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8958/10000 [28:41<03:17,  5.28step/s, loss=0.033318, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8958/10000 [28:41<03:17,  5.28step/s, loss=0.044642, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8959/10000 [28:42<03:17,  5.28step/s, loss=0.044642, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8959/10000 [28:42<03:17,  5.28step/s, loss=0.092034, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8960/10000 [28:42<03:17,  5.27step/s, loss=0.092034, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8960/10000 [28:42<03:17,  5.27step/s, loss=0.049315, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8961/10000 [28:42<03:16,  5.27step/s, loss=0.049315, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8961/10000 [28:42<03:16,  5.27step/s, loss=0.048744, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8962/10000 [28:42<03:16,  5.28step/s, loss=0.048744, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8962/10000 [28:42<03:16,  5.28step/s, loss=0.047244, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8963/10000 [28:42<03:16,  5.27step/s, loss=0.047244, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8963/10000 [28:42<03:16,  5.27step/s, loss=0.053861, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8964/10000 [28:42<03:16,  5.28step/s, loss=0.053861, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8964/10000 [28:42<03:16,  5.28step/s, loss=0.113545, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8965/10000 [28:43<03:16,  5.28step/s, loss=0.113545, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8965/10000 [28:43<03:16,  5.28step/s, loss=0.032877, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8966/10000 [28:43<03:15,  5.28step/s, loss=0.032877, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8966/10000 [28:43<03:15,  5.28step/s, loss=0.061410, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8967/10000 [28:43<03:15,  5.29step/s, loss=0.061410, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8967/10000 [28:43<03:15,  5.29step/s, loss=0.023374, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8968/10000 [28:43<03:15,  5.28step/s, loss=0.023374, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8968/10000 [28:43<03:15,  5.28step/s, loss=0.026044, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8969/10000 [28:43<03:15,  5.28step/s, loss=0.026044, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8969/10000 [28:43<03:15,  5.28step/s, loss=0.085782, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8970/10000 [28:44<03:15,  5.27step/s, loss=0.085782, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8970/10000 [28:44<03:15,  5.27step/s, loss=0.111805, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8971/10000 [28:44<03:15,  5.27step/s, loss=0.111805, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8971/10000 [28:44<03:15,  5.27step/s, loss=0.054127, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8972/10000 [28:44<03:15,  5.27step/s, loss=0.054127, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8972/10000 [28:44<03:15,  5.27step/s, loss=0.032480, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8973/10000 [28:44<03:14,  5.27step/s, loss=0.032480, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8973/10000 [28:44<03:14,  5.27step/s, loss=0.110486, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8974/10000 [28:44<03:14,  5.28step/s, loss=0.110486, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8974/10000 [28:44<03:14,  5.28step/s, loss=0.030422, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8975/10000 [28:45<03:13,  5.28step/s, loss=0.030422, elapsed=28.7min]

Entraînement:  90%|████████▉ | 8975/10000 [28:45<03:13,  5.28step/s, loss=0.036280, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8976/10000 [28:45<03:13,  5.29step/s, loss=0.036280, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8976/10000 [28:45<03:13,  5.29step/s, loss=0.033828, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8977/10000 [28:45<03:12,  5.31step/s, loss=0.033828, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8977/10000 [28:45<03:12,  5.31step/s, loss=0.053462, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8978/10000 [28:45<03:11,  5.34step/s, loss=0.053462, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8978/10000 [28:45<03:11,  5.34step/s, loss=0.048363, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8979/10000 [28:45<03:11,  5.34step/s, loss=0.048363, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8979/10000 [28:45<03:11,  5.34step/s, loss=0.033065, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8980/10000 [28:46<03:10,  5.35step/s, loss=0.033065, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8980/10000 [28:46<03:10,  5.35step/s, loss=0.024046, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8981/10000 [28:46<03:10,  5.35step/s, loss=0.024046, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8981/10000 [28:46<03:10,  5.35step/s, loss=0.066403, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8982/10000 [28:46<03:09,  5.36step/s, loss=0.066403, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8982/10000 [28:46<03:09,  5.36step/s, loss=0.109729, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8983/10000 [28:46<03:09,  5.36step/s, loss=0.109729, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8983/10000 [28:46<03:09,  5.36step/s, loss=0.041330, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8984/10000 [28:46<03:09,  5.36step/s, loss=0.041330, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8984/10000 [28:46<03:09,  5.36step/s, loss=0.042508, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8985/10000 [28:46<03:09,  5.36step/s, loss=0.042508, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8985/10000 [28:46<03:09,  5.36step/s, loss=0.049136, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8986/10000 [28:47<03:09,  5.35step/s, loss=0.049136, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8986/10000 [28:47<03:09,  5.35step/s, loss=0.080329, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8987/10000 [28:47<03:09,  5.35step/s, loss=0.080329, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8987/10000 [28:47<03:09,  5.35step/s, loss=0.101774, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8988/10000 [28:47<03:08,  5.36step/s, loss=0.101774, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8988/10000 [28:47<03:08,  5.36step/s, loss=0.042221, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8989/10000 [28:47<03:08,  5.36step/s, loss=0.042221, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8989/10000 [28:47<03:08,  5.36step/s, loss=0.066441, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8990/10000 [28:47<03:08,  5.36step/s, loss=0.066441, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8990/10000 [28:47<03:08,  5.36step/s, loss=0.027508, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8991/10000 [28:48<03:08,  5.36step/s, loss=0.027508, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8991/10000 [28:48<03:08,  5.36step/s, loss=0.078905, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8992/10000 [28:48<03:07,  5.37step/s, loss=0.078905, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8992/10000 [28:48<03:07,  5.37step/s, loss=0.081169, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8993/10000 [28:48<03:07,  5.36step/s, loss=0.081169, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8993/10000 [28:48<03:07,  5.36step/s, loss=0.049139, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8994/10000 [28:48<03:08,  5.35step/s, loss=0.049139, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8994/10000 [28:48<03:08,  5.35step/s, loss=0.028903, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8995/10000 [28:48<03:08,  5.34step/s, loss=0.028903, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8995/10000 [28:48<03:08,  5.34step/s, loss=0.027787, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8996/10000 [28:49<03:08,  5.33step/s, loss=0.027787, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8996/10000 [28:49<03:08,  5.33step/s, loss=0.042481, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8997/10000 [28:49<03:09,  5.30step/s, loss=0.042481, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8997/10000 [28:49<03:09,  5.30step/s, loss=0.032980, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8998/10000 [28:49<03:09,  5.29step/s, loss=0.032980, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8998/10000 [28:49<03:09,  5.29step/s, loss=0.042419, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8999/10000 [28:49<03:09,  5.28step/s, loss=0.042419, elapsed=28.8min]

Entraînement:  90%|████████▉ | 8999/10000 [28:49<03:09,  5.28step/s, loss=0.025306, elapsed=28.8min]

Entraînement:  90%|█████████ | 9000/10000 [28:49<03:09,  5.28step/s, loss=0.025306, elapsed=28.8min]

Entraînement:  90%|█████████ | 9000/10000 [28:49<03:09,  5.28step/s, loss=0.026382, elapsed=28.8min]

Entraînement:  90%|█████████ | 9000/10000 [28:49<03:09,  5.28step/s, loss=0.026382, elapsed=28.8min]

Step 9000/10000 | Train loss: 0.026382 | Elapsed: 28.8min | ETA: 3.2min

Entraînement:  90%|█████████ | 9000/10000 [28:51<03:09,  5.28step/s, loss=0.026382, elapsed=28.8min]

Entraînement:  90%|█████████ | 9000/10000 [28:51<03:09,  5.28step/s, loss=0.026382, elapsed=28.8min]

Step 9000/10000 | Val loss: 0.045698 | Validation en 1.7s
Dernier checkpoint sauvegardé : /workspace/DiffWave_Project/checkpoints/diffwave_doda_male/last_checkpoint.pt

Entraînement:  90%|█████████ | 9001/10000 [28:51<12:36,  1.32step/s, loss=0.026382, elapsed=28.8min]

Entraînement:  90%|█████████ | 9001/10000 [28:51<12:36,  1.32step/s, loss=0.024138, elapsed=28.9min]

Entraînement:  90%|█████████ | 9002/10000 [28:52<09:46,  1.70step/s, loss=0.024138, elapsed=28.9min]

Entraînement:  90%|█████████ | 9002/10000 [28:52<09:46,  1.70step/s, loss=0.073911, elapsed=28.9min]

Entraînement:  90%|█████████ | 9003/10000 [28:52<07:46,  2.14step/s, loss=0.073911, elapsed=28.9min]

Entraînement:  90%|█████████ | 9003/10000 [28:52<07:46,  2.14step/s, loss=0.051937, elapsed=28.9min]

Entraînement:  90%|█████████ | 9004/10000 [28:52<06:23,  2.60step/s, loss=0.051937, elapsed=28.9min]

Entraînement:  90%|█████████ | 9004/10000 [28:52<06:23,  2.60step/s, loss=0.029558, elapsed=28.9min]

Entraînement:  90%|█████████ | 9005/10000 [28:52<05:25,  3.06step/s, loss=0.029558, elapsed=28.9min]

Entraînement:  90%|█████████ | 9005/10000 [28:52<05:25,  3.06step/s, loss=0.040235, elapsed=28.9min]

Entraînement:  90%|█████████ | 9006/10000 [28:52<04:43,  3.50step/s, loss=0.040235, elapsed=28.9min]

Entraînement:  90%|█████████ | 9006/10000 [28:52<04:43,  3.50step/s, loss=0.086919, elapsed=28.9min]

Entraînement:  90%|█████████ | 9007/10000 [28:52<04:15,  3.88step/s, loss=0.086919, elapsed=28.9min]

Entraînement:  90%|█████████ | 9007/10000 [28:52<04:15,  3.88step/s, loss=0.043949, elapsed=28.9min]

Entraînement:  90%|█████████ | 9008/10000 [28:53<03:55,  4.21step/s, loss=0.043949, elapsed=28.9min]

Entraînement:  90%|█████████ | 9008/10000 [28:53<03:55,  4.21step/s, loss=0.043756, elapsed=28.9min]

Entraînement:  90%|█████████ | 9009/10000 [28:53<03:41,  4.47step/s, loss=0.043756, elapsed=28.9min]

Entraînement:  90%|█████████ | 9009/10000 [28:53<03:41,  4.47step/s, loss=0.120866, elapsed=28.9min]

Entraînement:  90%|█████████ | 9010/10000 [28:53<03:31,  4.68step/s, loss=0.120866, elapsed=28.9min]

Entraînement:  90%|█████████ | 9010/10000 [28:53<03:31,  4.68step/s, loss=0.019707, elapsed=28.9min]

Entraînement:  90%|█████████ | 9011/10000 [28:53<03:24,  4.84step/s, loss=0.019707, elapsed=28.9min]

Entraînement:  90%|█████████ | 9011/10000 [28:53<03:24,  4.84step/s, loss=0.045724, elapsed=28.9min]

Entraînement:  90%|█████████ | 9012/10000 [28:53<03:19,  4.95step/s, loss=0.045724, elapsed=28.9min]

Entraînement:  90%|█████████ | 9012/10000 [28:53<03:19,  4.95step/s, loss=0.045864, elapsed=28.9min]

Entraînement:  90%|█████████ | 9013/10000 [28:54<03:16,  5.03step/s, loss=0.045864, elapsed=28.9min]

Entraînement:  90%|█████████ | 9013/10000 [28:54<03:16,  5.03step/s, loss=0.028961, elapsed=28.9min]

Entraînement:  90%|█████████ | 9014/10000 [28:54<03:14,  5.08step/s, loss=0.028961, elapsed=28.9min]

Entraînement:  90%|█████████ | 9014/10000 [28:54<03:14,  5.08step/s, loss=0.028171, elapsed=28.9min]

Entraînement:  90%|█████████ | 9015/10000 [28:54<03:12,  5.12step/s, loss=0.028171, elapsed=28.9min]

Entraînement:  90%|█████████ | 9015/10000 [28:54<03:12,  5.12step/s, loss=0.021829, elapsed=28.9min]

Entraînement:  90%|█████████ | 9016/10000 [28:54<03:11,  5.15step/s, loss=0.021829, elapsed=28.9min]

Entraînement:  90%|█████████ | 9016/10000 [28:54<03:11,  5.15step/s, loss=0.022659, elapsed=28.9min]

Entraînement:  90%|█████████ | 9017/10000 [28:54<03:10,  5.17step/s, loss=0.022659, elapsed=28.9min]

Entraînement:  90%|█████████ | 9017/10000 [28:54<03:10,  5.17step/s, loss=0.049577, elapsed=28.9min]

Entraînement:  90%|█████████ | 9018/10000 [28:55<03:09,  5.19step/s, loss=0.049577, elapsed=28.9min]

Entraînement:  90%|█████████ | 9018/10000 [28:55<03:09,  5.19step/s, loss=0.027032, elapsed=28.9min]

Entraînement:  90%|█████████ | 9019/10000 [28:55<03:08,  5.20step/s, loss=0.027032, elapsed=28.9min]

Entraînement:  90%|█████████ | 9019/10000 [28:55<03:08,  5.20step/s, loss=0.094931, elapsed=28.9min]

Entraînement:  90%|█████████ | 9020/10000 [28:55<03:08,  5.20step/s, loss=0.094931, elapsed=28.9min]

Entraînement:  90%|█████████ | 9020/10000 [28:55<03:08,  5.20step/s, loss=0.027773, elapsed=28.9min]

Entraînement:  90%|█████████ | 9021/10000 [28:55<03:08,  5.21step/s, loss=0.027773, elapsed=28.9min]

Entraînement:  90%|█████████ | 9021/10000 [28:55<03:08,  5.21step/s, loss=0.042701, elapsed=28.9min]

Entraînement:  90%|█████████ | 9022/10000 [28:55<03:07,  5.23step/s, loss=0.042701, elapsed=28.9min]

Entraînement:  90%|█████████ | 9022/10000 [28:55<03:07,  5.23step/s, loss=0.060120, elapsed=28.9min]

Entraînement:  90%|█████████ | 9023/10000 [28:56<03:07,  5.22step/s, loss=0.060120, elapsed=28.9min]

Entraînement:  90%|█████████ | 9023/10000 [28:56<03:07,  5.22step/s, loss=0.028462, elapsed=28.9min]

Entraînement:  90%|█████████ | 9024/10000 [28:56<03:06,  5.23step/s, loss=0.028462, elapsed=28.9min]

Entraînement:  90%|█████████ | 9024/10000 [28:56<03:06,  5.23step/s, loss=0.083207, elapsed=28.9min]

Entraînement:  90%|█████████ | 9025/10000 [28:56<03:05,  5.25step/s, loss=0.083207, elapsed=28.9min]

Entraînement:  90%|█████████ | 9025/10000 [28:56<03:05,  5.25step/s, loss=0.025878, elapsed=28.9min]

Entraînement:  90%|█████████ | 9026/10000 [28:56<03:05,  5.24step/s, loss=0.025878, elapsed=28.9min]

Entraînement:  90%|█████████ | 9026/10000 [28:56<03:05,  5.24step/s, loss=0.079599, elapsed=28.9min]

Entraînement:  90%|█████████ | 9027/10000 [28:56<03:05,  5.25step/s, loss=0.079599, elapsed=28.9min]

Entraînement:  90%|█████████ | 9027/10000 [28:56<03:05,  5.25step/s, loss=0.030223, elapsed=28.9min]

Entraînement:  90%|█████████ | 9028/10000 [28:57<03:05,  5.25step/s, loss=0.030223, elapsed=28.9min]

Entraînement:  90%|█████████ | 9028/10000 [28:57<03:05,  5.25step/s, loss=0.031956, elapsed=29.0min]

Entraînement:  90%|█████████ | 9029/10000 [28:57<03:04,  5.25step/s, loss=0.031956, elapsed=29.0min]

Entraînement:  90%|█████████ | 9029/10000 [28:57<03:04,  5.25step/s, loss=0.070370, elapsed=29.0min]

Entraînement:  90%|█████████ | 9030/10000 [28:57<03:05,  5.24step/s, loss=0.070370, elapsed=29.0min]

Entraînement:  90%|█████████ | 9030/10000 [28:57<03:05,  5.24step/s, loss=0.039740, elapsed=29.0min]

Entraînement:  90%|█████████ | 9031/10000 [28:57<03:04,  5.24step/s, loss=0.039740, elapsed=29.0min]

Entraînement:  90%|█████████ | 9031/10000 [28:57<03:04,  5.24step/s, loss=0.023866, elapsed=29.0min]

Entraînement:  90%|█████████ | 9032/10000 [28:57<03:04,  5.24step/s, loss=0.023866, elapsed=29.0min]

Entraînement:  90%|█████████ | 9032/10000 [28:57<03:04,  5.24step/s, loss=0.025343, elapsed=29.0min]

Entraînement:  90%|█████████ | 9033/10000 [28:57<03:04,  5.25step/s, loss=0.025343, elapsed=29.0min]

Entraînement:  90%|█████████ | 9033/10000 [28:57<03:04,  5.25step/s, loss=0.042470, elapsed=29.0min]

Entraînement:  90%|█████████ | 9034/10000 [28:58<03:04,  5.24step/s, loss=0.042470, elapsed=29.0min]

Entraînement:  90%|█████████ | 9034/10000 [28:58<03:04,  5.24step/s, loss=0.024803, elapsed=29.0min]

Entraînement:  90%|█████████ | 9035/10000 [28:58<03:04,  5.24step/s, loss=0.024803, elapsed=29.0min]

Entraînement:  90%|█████████ | 9035/10000 [28:58<03:04,  5.24step/s, loss=0.075858, elapsed=29.0min]

Entraînement:  90%|█████████ | 9036/10000 [28:58<03:04,  5.24step/s, loss=0.075858, elapsed=29.0min]

Entraînement:  90%|█████████ | 9036/10000 [28:58<03:04,  5.24step/s, loss=0.103443, elapsed=29.0min]

Entraînement:  90%|█████████ | 9037/10000 [28:58<03:04,  5.22step/s, loss=0.103443, elapsed=29.0min]

Entraînement:  90%|█████████ | 9037/10000 [28:58<03:04,  5.22step/s, loss=0.016206, elapsed=29.0min]

Entraînement:  90%|█████████ | 9038/10000 [28:58<03:04,  5.22step/s, loss=0.016206, elapsed=29.0min]

Entraînement:  90%|█████████ | 9038/10000 [28:58<03:04,  5.22step/s, loss=0.036784, elapsed=29.0min]

Entraînement:  90%|█████████ | 9039/10000 [28:59<03:04,  5.20step/s, loss=0.036784, elapsed=29.0min]

Entraînement:  90%|█████████ | 9039/10000 [28:59<03:04,  5.20step/s, loss=0.034428, elapsed=29.0min]

Entraînement:  90%|█████████ | 9040/10000 [28:59<03:04,  5.21step/s, loss=0.034428, elapsed=29.0min]

Entraînement:  90%|█████████ | 9040/10000 [28:59<03:04,  5.21step/s, loss=0.037556, elapsed=29.0min]

Entraînement:  90%|█████████ | 9041/10000 [28:59<03:03,  5.22step/s, loss=0.037556, elapsed=29.0min]

Entraînement:  90%|█████████ | 9041/10000 [28:59<03:03,  5.22step/s, loss=0.030965, elapsed=29.0min]

Entraînement:  90%|█████████ | 9042/10000 [28:59<03:03,  5.21step/s, loss=0.030965, elapsed=29.0min]

Entraînement:  90%|█████████ | 9042/10000 [28:59<03:03,  5.21step/s, loss=0.043293, elapsed=29.0min]

Entraînement:  90%|█████████ | 9043/10000 [28:59<03:02,  5.24step/s, loss=0.043293, elapsed=29.0min]

Entraînement:  90%|█████████ | 9043/10000 [28:59<03:02,  5.24step/s, loss=0.045033, elapsed=29.0min]

Entraînement:  90%|█████████ | 9044/10000 [29:00<03:02,  5.25step/s, loss=0.045033, elapsed=29.0min]

Entraînement:  90%|█████████ | 9044/10000 [29:00<03:02,  5.25step/s, loss=0.031193, elapsed=29.0min]

Entraînement:  90%|█████████ | 9045/10000 [29:00<03:02,  5.24step/s, loss=0.031193, elapsed=29.0min]

Entraînement:  90%|█████████ | 9045/10000 [29:00<03:02,  5.24step/s, loss=0.028785, elapsed=29.0min]

Entraînement:  90%|█████████ | 9046/10000 [29:00<03:02,  5.24step/s, loss=0.028785, elapsed=29.0min]

Entraînement:  90%|█████████ | 9046/10000 [29:00<03:02,  5.24step/s, loss=0.021833, elapsed=29.0min]

Entraînement:  90%|█████████ | 9047/10000 [29:00<03:01,  5.24step/s, loss=0.021833, elapsed=29.0min]

Entraînement:  90%|█████████ | 9047/10000 [29:00<03:01,  5.24step/s, loss=0.048423, elapsed=29.0min]

Entraînement:  90%|█████████ | 9048/10000 [29:00<03:01,  5.24step/s, loss=0.048423, elapsed=29.0min]

Entraînement:  90%|█████████ | 9048/10000 [29:00<03:01,  5.24step/s, loss=0.042637, elapsed=29.0min]

Entraînement:  90%|█████████ | 9049/10000 [29:01<03:01,  5.25step/s, loss=0.042637, elapsed=29.0min]

Entraînement:  90%|█████████ | 9049/10000 [29:01<03:01,  5.25step/s, loss=0.040738, elapsed=29.0min]

Entraînement:  90%|█████████ | 9050/10000 [29:01<03:01,  5.24step/s, loss=0.040738, elapsed=29.0min]

Entraînement:  90%|█████████ | 9050/10000 [29:01<03:01,  5.24step/s, loss=0.071230, elapsed=29.0min]

Entraînement:  91%|█████████ | 9051/10000 [29:01<03:00,  5.24step/s, loss=0.071230, elapsed=29.0min]

Entraînement:  91%|█████████ | 9051/10000 [29:01<03:00,  5.24step/s, loss=0.035631, elapsed=29.0min]

Entraînement:  91%|█████████ | 9052/10000 [29:01<03:01,  5.23step/s, loss=0.035631, elapsed=29.0min]

Entraînement:  91%|█████████ | 9052/10000 [29:01<03:01,  5.23step/s, loss=0.041182, elapsed=29.0min]

Entraînement:  91%|█████████ | 9053/10000 [29:01<03:00,  5.25step/s, loss=0.041182, elapsed=29.0min]

Entraînement:  91%|█████████ | 9053/10000 [29:01<03:00,  5.25step/s, loss=0.028642, elapsed=29.0min]

Entraînement:  91%|█████████ | 9054/10000 [29:01<03:00,  5.25step/s, loss=0.028642, elapsed=29.0min]

Entraînement:  91%|█████████ | 9054/10000 [29:01<03:00,  5.25step/s, loss=0.026109, elapsed=29.0min]

Entraînement:  91%|█████████ | 9055/10000 [29:02<03:00,  5.25step/s, loss=0.026109, elapsed=29.0min]

Entraînement:  91%|█████████ | 9055/10000 [29:02<03:00,  5.25step/s, loss=0.022055, elapsed=29.0min]

Entraînement:  91%|█████████ | 9056/10000 [29:02<02:59,  5.26step/s, loss=0.022055, elapsed=29.0min]

Entraînement:  91%|█████████ | 9056/10000 [29:02<02:59,  5.26step/s, loss=0.041944, elapsed=29.0min]

Entraînement:  91%|█████████ | 9057/10000 [29:02<02:59,  5.26step/s, loss=0.041944, elapsed=29.0min]

Entraînement:  91%|█████████ | 9057/10000 [29:02<02:59,  5.26step/s, loss=0.070877, elapsed=29.0min]

Entraînement:  91%|█████████ | 9058/10000 [29:02<02:58,  5.27step/s, loss=0.070877, elapsed=29.0min]

Entraînement:  91%|█████████ | 9058/10000 [29:02<02:58,  5.27step/s, loss=0.015209, elapsed=29.0min]

Entraînement:  91%|█████████ | 9059/10000 [29:02<02:58,  5.27step/s, loss=0.015209, elapsed=29.0min]

Entraînement:  91%|█████████ | 9059/10000 [29:02<02:58,  5.27step/s, loss=0.027460, elapsed=29.0min]

Entraînement:  91%|█████████ | 9060/10000 [29:03<02:58,  5.26step/s, loss=0.027460, elapsed=29.0min]

Entraînement:  91%|█████████ | 9060/10000 [29:03<02:58,  5.26step/s, loss=0.057855, elapsed=29.1min]

Entraînement:  91%|█████████ | 9061/10000 [29:03<02:58,  5.27step/s, loss=0.057855, elapsed=29.1min]

Entraînement:  91%|█████████ | 9061/10000 [29:03<02:58,  5.27step/s, loss=0.044419, elapsed=29.1min]

Entraînement:  91%|█████████ | 9062/10000 [29:03<02:58,  5.27step/s, loss=0.044419, elapsed=29.1min]

Entraînement:  91%|█████████ | 9062/10000 [29:03<02:58,  5.27step/s, loss=0.042823, elapsed=29.1min]

Entraînement:  91%|█████████ | 9063/10000 [29:03<02:57,  5.28step/s, loss=0.042823, elapsed=29.1min]

Entraînement:  91%|█████████ | 9063/10000 [29:03<02:57,  5.28step/s, loss=0.034450, elapsed=29.1min]

Entraînement:  91%|█████████ | 9064/10000 [29:03<02:57,  5.27step/s, loss=0.034450, elapsed=29.1min]

Entraînement:  91%|█████████ | 9064/10000 [29:03<02:57,  5.27step/s, loss=0.073781, elapsed=29.1min]

Entraînement:  91%|█████████ | 9065/10000 [29:04<02:57,  5.28step/s, loss=0.073781, elapsed=29.1min]

Entraînement:  91%|█████████ | 9065/10000 [29:04<02:57,  5.28step/s, loss=0.064700, elapsed=29.1min]

Entraînement:  91%|█████████ | 9066/10000 [29:04<02:56,  5.30step/s, loss=0.064700, elapsed=29.1min]

Entraînement:  91%|█████████ | 9066/10000 [29:04<02:56,  5.30step/s, loss=0.066438, elapsed=29.1min]

Entraînement:  91%|█████████ | 9067/10000 [29:04<02:56,  5.30step/s, loss=0.066438, elapsed=29.1min]

Entraînement:  91%|█████████ | 9067/10000 [29:04<02:56,  5.30step/s, loss=0.044333, elapsed=29.1min]

Entraînement:  91%|█████████ | 9068/10000 [29:04<02:56,  5.29step/s, loss=0.044333, elapsed=29.1min]

Entraînement:  91%|█████████ | 9068/10000 [29:04<02:56,  5.29step/s, loss=0.097127, elapsed=29.1min]

Entraînement:  91%|█████████ | 9069/10000 [29:04<02:57,  5.26step/s, loss=0.097127, elapsed=29.1min]

Entraînement:  91%|█████████ | 9069/10000 [29:04<02:57,  5.26step/s, loss=0.030917, elapsed=29.1min]

Entraînement:  91%|█████████ | 9070/10000 [29:05<02:57,  5.25step/s, loss=0.030917, elapsed=29.1min]

Entraînement:  91%|█████████ | 9070/10000 [29:05<02:57,  5.25step/s, loss=0.051504, elapsed=29.1min]

Entraînement:  91%|█████████ | 9071/10000 [29:05<02:57,  5.23step/s, loss=0.051504, elapsed=29.1min]

Entraînement:  91%|█████████ | 9071/10000 [29:05<02:57,  5.23step/s, loss=0.021721, elapsed=29.1min]

Entraînement:  91%|█████████ | 9072/10000 [29:05<02:57,  5.22step/s, loss=0.021721, elapsed=29.1min]

Entraînement:  91%|█████████ | 9072/10000 [29:05<02:57,  5.22step/s, loss=0.076778, elapsed=29.1min]

Entraînement:  91%|█████████ | 9073/10000 [29:05<02:57,  5.21step/s, loss=0.076778, elapsed=29.1min]

Entraînement:  91%|█████████ | 9073/10000 [29:05<02:57,  5.21step/s, loss=0.039640, elapsed=29.1min]

Entraînement:  91%|█████████ | 9074/10000 [29:05<02:58,  5.20step/s, loss=0.039640, elapsed=29.1min]

Entraînement:  91%|█████████ | 9074/10000 [29:05<02:58,  5.20step/s, loss=0.020782, elapsed=29.1min]

Entraînement:  91%|█████████ | 9075/10000 [29:05<02:57,  5.22step/s, loss=0.020782, elapsed=29.1min]

Entraînement:  91%|█████████ | 9075/10000 [29:05<02:57,  5.22step/s, loss=0.026816, elapsed=29.1min]

Entraînement:  91%|█████████ | 9076/10000 [29:06<02:56,  5.23step/s, loss=0.026816, elapsed=29.1min]

Entraînement:  91%|█████████ | 9076/10000 [29:06<02:56,  5.23step/s, loss=0.035665, elapsed=29.1min]

Entraînement:  91%|█████████ | 9077/10000 [29:06<02:56,  5.24step/s, loss=0.035665, elapsed=29.1min]

Entraînement:  91%|█████████ | 9077/10000 [29:06<02:56,  5.24step/s, loss=0.059266, elapsed=29.1min]

Entraînement:  91%|█████████ | 9078/10000 [29:06<02:55,  5.26step/s, loss=0.059266, elapsed=29.1min]

Entraînement:  91%|█████████ | 9078/10000 [29:06<02:55,  5.26step/s, loss=0.060985, elapsed=29.1min]

Entraînement:  91%|█████████ | 9079/10000 [29:06<02:54,  5.26step/s, loss=0.060985, elapsed=29.1min]

Entraînement:  91%|█████████ | 9079/10000 [29:06<02:54,  5.26step/s, loss=0.029040, elapsed=29.1min]

Entraînement:  91%|█████████ | 9080/10000 [29:06<02:54,  5.27step/s, loss=0.029040, elapsed=29.1min]

Entraînement:  91%|█████████ | 9080/10000 [29:06<02:54,  5.27step/s, loss=0.069146, elapsed=29.1min]

Entraînement:  91%|█████████ | 9081/10000 [29:07<02:53,  5.28step/s, loss=0.069146, elapsed=29.1min]

Entraînement:  91%|█████████ | 9081/10000 [29:07<02:53,  5.28step/s, loss=0.038271, elapsed=29.1min]

Entraînement:  91%|█████████ | 9082/10000 [29:07<02:54,  5.27step/s, loss=0.038271, elapsed=29.1min]

Entraînement:  91%|█████████ | 9082/10000 [29:07<02:54,  5.27step/s, loss=0.025410, elapsed=29.1min]

Entraînement:  91%|█████████ | 9083/10000 [29:07<02:53,  5.27step/s, loss=0.025410, elapsed=29.1min]

Entraînement:  91%|█████████ | 9083/10000 [29:07<02:53,  5.27step/s, loss=0.038941, elapsed=29.1min]

Entraînement:  91%|█████████ | 9084/10000 [29:07<02:53,  5.27step/s, loss=0.038941, elapsed=29.1min]

Entraînement:  91%|█████████ | 9084/10000 [29:07<02:53,  5.27step/s, loss=0.058225, elapsed=29.1min]

Entraînement:  91%|█████████ | 9085/10000 [29:07<02:53,  5.28step/s, loss=0.058225, elapsed=29.1min]

Entraînement:  91%|█████████ | 9085/10000 [29:07<02:53,  5.28step/s, loss=0.055047, elapsed=29.1min]

Entraînement:  91%|█████████ | 9086/10000 [29:08<02:53,  5.27step/s, loss=0.055047, elapsed=29.1min]

Entraînement:  91%|█████████ | 9086/10000 [29:08<02:53,  5.27step/s, loss=0.021960, elapsed=29.1min]

Entraînement:  91%|█████████ | 9087/10000 [29:08<02:53,  5.28step/s, loss=0.021960, elapsed=29.1min]

Entraînement:  91%|█████████ | 9087/10000 [29:08<02:53,  5.28step/s, loss=0.069956, elapsed=29.1min]

Entraînement:  91%|█████████ | 9088/10000 [29:08<02:52,  5.28step/s, loss=0.069956, elapsed=29.1min]

Entraînement:  91%|█████████ | 9088/10000 [29:08<02:52,  5.28step/s, loss=0.035995, elapsed=29.1min]

Entraînement:  91%|█████████ | 9089/10000 [29:08<02:52,  5.28step/s, loss=0.035995, elapsed=29.1min]

Entraînement:  91%|█████████ | 9089/10000 [29:08<02:52,  5.28step/s, loss=0.035972, elapsed=29.1min]

Entraînement:  91%|█████████ | 9090/10000 [29:08<02:52,  5.28step/s, loss=0.035972, elapsed=29.1min]

Entraînement:  91%|█████████ | 9090/10000 [29:08<02:52,  5.28step/s, loss=0.065519, elapsed=29.1min]

Entraînement:  91%|█████████ | 9091/10000 [29:08<02:52,  5.27step/s, loss=0.065519, elapsed=29.1min]

Entraînement:  91%|█████████ | 9091/10000 [29:09<02:52,  5.27step/s, loss=0.022015, elapsed=29.2min]

Entraînement:  91%|█████████ | 9092/10000 [29:09<02:52,  5.27step/s, loss=0.022015, elapsed=29.2min]

Entraînement:  91%|█████████ | 9092/10000 [29:09<02:52,  5.27step/s, loss=0.055212, elapsed=29.2min]

Entraînement:  91%|█████████ | 9093/10000 [29:09<02:52,  5.25step/s, loss=0.055212, elapsed=29.2min]

Entraînement:  91%|█████████ | 9093/10000 [29:09<02:52,  5.25step/s, loss=0.111966, elapsed=29.2min]

Entraînement:  91%|█████████ | 9094/10000 [29:09<02:52,  5.27step/s, loss=0.111966, elapsed=29.2min]

Entraînement:  91%|█████████ | 9094/10000 [29:09<02:52,  5.27step/s, loss=0.116622, elapsed=29.2min]

Entraînement:  91%|█████████ | 9095/10000 [29:09<02:51,  5.27step/s, loss=0.116622, elapsed=29.2min]

Entraînement:  91%|█████████ | 9095/10000 [29:09<02:51,  5.27step/s, loss=0.038847, elapsed=29.2min]

Entraînement:  91%|█████████ | 9096/10000 [29:09<02:51,  5.26step/s, loss=0.038847, elapsed=29.2min]

Entraînement:  91%|█████████ | 9096/10000 [29:09<02:51,  5.26step/s, loss=0.058625, elapsed=29.2min]

Entraînement:  91%|█████████ | 9097/10000 [29:10<02:51,  5.26step/s, loss=0.058625, elapsed=29.2min]

Entraînement:  91%|█████████ | 9097/10000 [29:10<02:51,  5.26step/s, loss=0.072536, elapsed=29.2min]

Entraînement:  91%|█████████ | 9098/10000 [29:10<02:51,  5.25step/s, loss=0.072536, elapsed=29.2min]

Entraînement:  91%|█████████ | 9098/10000 [29:10<02:51,  5.25step/s, loss=0.022840, elapsed=29.2min]

Entraînement:  91%|█████████ | 9099/10000 [29:10<02:51,  5.25step/s, loss=0.022840, elapsed=29.2min]

Entraînement:  91%|█████████ | 9099/10000 [29:10<02:51,  5.25step/s, loss=0.023931, elapsed=29.2min]

Entraînement:  91%|█████████ | 9100/10000 [29:10<02:51,  5.25step/s, loss=0.023931, elapsed=29.2min]

Entraînement:  91%|█████████ | 9100/10000 [29:10<02:51,  5.25step/s, loss=0.028326, elapsed=29.2min]

Entraînement:  91%|█████████ | 9100/10000 [29:10<02:51,  5.25step/s, loss=0.028326, elapsed=29.2min]

Entraînement:  91%|█████████ | 9101/10000 [29:10<02:52,  5.20step/s, loss=0.028326, elapsed=29.2min]

Entraînement:  91%|█████████ | 9101/10000 [29:10<02:52,  5.20step/s, loss=0.096930, elapsed=29.2min]

Step 9100/10000 | Train loss: 0.028326 | Elapsed: 29.2min | ETA: 2.9min

Entraînement:  91%|█████████ | 9102/10000 [29:11<02:51,  5.23step/s, loss=0.096930, elapsed=29.2min]

Entraînement:  91%|█████████ | 9102/10000 [29:11<02:51,  5.23step/s, loss=0.024494, elapsed=29.2min]

Entraînement:  91%|█████████ | 9103/10000 [29:11<02:50,  5.25step/s, loss=0.024494, elapsed=29.2min]

Entraînement:  91%|█████████ | 9103/10000 [29:11<02:50,  5.25step/s, loss=0.026877, elapsed=29.2min]

Entraînement:  91%|█████████ | 9104/10000 [29:11<02:50,  5.26step/s, loss=0.026877, elapsed=29.2min]

Entraînement:  91%|█████████ | 9104/10000 [29:11<02:50,  5.26step/s, loss=0.040851, elapsed=29.2min]

Entraînement:  91%|█████████ | 9105/10000 [29:11<02:49,  5.27step/s, loss=0.040851, elapsed=29.2min]

Entraînement:  91%|█████████ | 9105/10000 [29:11<02:49,  5.27step/s, loss=0.028347, elapsed=29.2min]

Entraînement:  91%|█████████ | 9106/10000 [29:11<02:49,  5.26step/s, loss=0.028347, elapsed=29.2min]

Entraînement:  91%|█████████ | 9106/10000 [29:11<02:49,  5.26step/s, loss=0.070653, elapsed=29.2min]

Entraînement:  91%|█████████ | 9107/10000 [29:12<02:49,  5.27step/s, loss=0.070653, elapsed=29.2min]

Entraînement:  91%|█████████ | 9107/10000 [29:12<02:49,  5.27step/s, loss=0.042326, elapsed=29.2min]

Entraînement:  91%|█████████ | 9108/10000 [29:12<02:49,  5.27step/s, loss=0.042326, elapsed=29.2min]

Entraînement:  91%|█████████ | 9108/10000 [29:12<02:49,  5.27step/s, loss=0.024858, elapsed=29.2min]

Entraînement:  91%|█████████ | 9109/10000 [29:12<02:48,  5.28step/s, loss=0.024858, elapsed=29.2min]

Entraînement:  91%|█████████ | 9109/10000 [29:12<02:48,  5.28step/s, loss=0.033223, elapsed=29.2min]

Entraînement:  91%|█████████ | 9110/10000 [29:12<02:49,  5.24step/s, loss=0.033223, elapsed=29.2min]

Entraînement:  91%|█████████ | 9110/10000 [29:12<02:49,  5.24step/s, loss=0.024744, elapsed=29.2min]

Entraînement:  91%|█████████ | 9111/10000 [29:12<02:49,  5.25step/s, loss=0.024744, elapsed=29.2min]

Entraînement:  91%|█████████ | 9111/10000 [29:12<02:49,  5.25step/s, loss=0.028433, elapsed=29.2min]

Entraînement:  91%|█████████ | 9112/10000 [29:12<02:49,  5.25step/s, loss=0.028433, elapsed=29.2min]

Entraînement:  91%|█████████ | 9112/10000 [29:12<02:49,  5.25step/s, loss=0.019083, elapsed=29.2min]

Entraînement:  91%|█████████ | 9113/10000 [29:13<02:49,  5.25step/s, loss=0.019083, elapsed=29.2min]

Entraînement:  91%|█████████ | 9113/10000 [29:13<02:49,  5.25step/s, loss=0.086092, elapsed=29.2min]

Entraînement:  91%|█████████ | 9114/10000 [29:13<02:48,  5.26step/s, loss=0.086092, elapsed=29.2min]

Entraînement:  91%|█████████ | 9114/10000 [29:13<02:48,  5.26step/s, loss=0.045744, elapsed=29.2min]

Entraînement:  91%|█████████ | 9115/10000 [29:13<02:48,  5.26step/s, loss=0.045744, elapsed=29.2min]

Entraînement:  91%|█████████ | 9115/10000 [29:13<02:48,  5.26step/s, loss=0.079444, elapsed=29.2min]

Entraînement:  91%|█████████ | 9116/10000 [29:13<02:47,  5.27step/s, loss=0.079444, elapsed=29.2min]

Entraînement:  91%|█████████ | 9116/10000 [29:13<02:47,  5.27step/s, loss=0.158351, elapsed=29.2min]

Entraînement:  91%|█████████ | 9117/10000 [29:13<02:47,  5.26step/s, loss=0.158351, elapsed=29.2min]

Entraînement:  91%|█████████ | 9117/10000 [29:13<02:47,  5.26step/s, loss=0.083491, elapsed=29.2min]

Entraînement:  91%|█████████ | 9118/10000 [29:14<02:47,  5.27step/s, loss=0.083491, elapsed=29.2min]

Entraînement:  91%|█████████ | 9118/10000 [29:14<02:47,  5.27step/s, loss=0.072609, elapsed=29.2min]

Entraînement:  91%|█████████ | 9119/10000 [29:14<02:47,  5.27step/s, loss=0.072609, elapsed=29.2min]

Entraînement:  91%|█████████ | 9119/10000 [29:14<02:47,  5.27step/s, loss=0.027105, elapsed=29.2min]

Entraînement:  91%|█████████ | 9120/10000 [29:14<02:47,  5.25step/s, loss=0.027105, elapsed=29.2min]

Entraînement:  91%|█████████ | 9120/10000 [29:14<02:47,  5.25step/s, loss=0.040830, elapsed=29.2min]

Entraînement:  91%|█████████ | 9121/10000 [29:14<02:47,  5.25step/s, loss=0.040830, elapsed=29.2min]

Entraînement:  91%|█████████ | 9121/10000 [29:14<02:47,  5.25step/s, loss=0.089007, elapsed=29.2min]

Entraînement:  91%|█████████ | 9122/10000 [29:14<02:47,  5.25step/s, loss=0.089007, elapsed=29.2min]

Entraînement:  91%|█████████ | 9122/10000 [29:14<02:47,  5.25step/s, loss=0.059846, elapsed=29.2min]

Entraînement:  91%|█████████ | 9123/10000 [29:15<02:47,  5.25step/s, loss=0.059846, elapsed=29.2min]

Entraînement:  91%|█████████ | 9123/10000 [29:15<02:47,  5.25step/s, loss=0.087958, elapsed=29.3min]

Entraînement:  91%|█████████ | 9124/10000 [29:15<02:46,  5.25step/s, loss=0.087958, elapsed=29.3min]

Entraînement:  91%|█████████ | 9124/10000 [29:15<02:46,  5.25step/s, loss=0.051264, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9125/10000 [29:15<02:46,  5.26step/s, loss=0.051264, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9125/10000 [29:15<02:46,  5.26step/s, loss=0.029361, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9126/10000 [29:15<02:46,  5.26step/s, loss=0.029361, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9126/10000 [29:15<02:46,  5.26step/s, loss=0.037018, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9127/10000 [29:15<02:45,  5.27step/s, loss=0.037018, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9127/10000 [29:15<02:45,  5.27step/s, loss=0.015050, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9128/10000 [29:16<02:45,  5.26step/s, loss=0.015050, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9128/10000 [29:16<02:45,  5.26step/s, loss=0.021051, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9129/10000 [29:16<02:45,  5.27step/s, loss=0.021051, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9129/10000 [29:16<02:45,  5.27step/s, loss=0.024474, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9130/10000 [29:16<02:45,  5.26step/s, loss=0.024474, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9130/10000 [29:16<02:45,  5.26step/s, loss=0.020408, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9131/10000 [29:16<02:45,  5.26step/s, loss=0.020408, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9131/10000 [29:16<02:45,  5.26step/s, loss=0.063443, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9132/10000 [29:16<02:44,  5.26step/s, loss=0.063443, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9132/10000 [29:16<02:44,  5.26step/s, loss=0.053853, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9133/10000 [29:16<02:44,  5.26step/s, loss=0.053853, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9133/10000 [29:16<02:44,  5.26step/s, loss=0.033275, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9134/10000 [29:17<02:44,  5.27step/s, loss=0.033275, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9134/10000 [29:17<02:44,  5.27step/s, loss=0.085483, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9135/10000 [29:17<02:44,  5.26step/s, loss=0.085483, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9135/10000 [29:17<02:44,  5.26step/s, loss=0.086715, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9136/10000 [29:17<02:44,  5.26step/s, loss=0.086715, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9136/10000 [29:17<02:44,  5.26step/s, loss=0.039593, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9137/10000 [29:17<02:44,  5.25step/s, loss=0.039593, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9137/10000 [29:17<02:44,  5.25step/s, loss=0.044446, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9138/10000 [29:17<02:44,  5.25step/s, loss=0.044446, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9138/10000 [29:17<02:44,  5.25step/s, loss=0.044524, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9139/10000 [29:18<02:43,  5.26step/s, loss=0.044524, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9139/10000 [29:18<02:43,  5.26step/s, loss=0.028278, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9140/10000 [29:18<02:43,  5.26step/s, loss=0.028278, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9140/10000 [29:18<02:43,  5.26step/s, loss=0.029971, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9141/10000 [29:18<02:43,  5.26step/s, loss=0.029971, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9141/10000 [29:18<02:43,  5.26step/s, loss=0.066804, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9142/10000 [29:18<02:43,  5.25step/s, loss=0.066804, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9142/10000 [29:18<02:43,  5.25step/s, loss=0.022647, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9143/10000 [29:18<02:43,  5.26step/s, loss=0.022647, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9143/10000 [29:18<02:43,  5.26step/s, loss=0.034251, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9144/10000 [29:19<02:42,  5.25step/s, loss=0.034251, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9144/10000 [29:19<02:42,  5.25step/s, loss=0.118386, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9145/10000 [29:19<02:42,  5.25step/s, loss=0.118386, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9145/10000 [29:19<02:42,  5.25step/s, loss=0.046587, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9146/10000 [29:19<02:42,  5.25step/s, loss=0.046587, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9146/10000 [29:19<02:42,  5.25step/s, loss=0.071049, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9147/10000 [29:19<02:42,  5.26step/s, loss=0.071049, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9147/10000 [29:19<02:42,  5.26step/s, loss=0.053878, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9148/10000 [29:19<02:42,  5.26step/s, loss=0.053878, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9148/10000 [29:19<02:42,  5.26step/s, loss=0.026740, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9149/10000 [29:20<02:41,  5.26step/s, loss=0.026740, elapsed=29.3min]

Entraînement:  91%|█████████▏| 9149/10000 [29:20<02:41,  5.26step/s, loss=0.021687, elapsed=29.3min]

Entraînement:  92%|█████████▏| 9150/10000 [29:20<02:41,  5.26step/s, loss=0.021687, elapsed=29.3min]

Entraînement:  92%|█████████▏| 9150/10000 [29:20<02:41,  5.26step/s, loss=0.043135, elapsed=29.3min]

Entraînement:  92%|█████████▏| 9151/10000 [29:20<02:41,  5.26step/s, loss=0.043135, elapsed=29.3min]

Entraînement:  92%|█████████▏| 9151/10000 [29:20<02:41,  5.26step/s, loss=0.084551, elapsed=29.3min]

Entraînement:  92%|█████████▏| 9152/10000 [29:20<02:41,  5.26step/s, loss=0.084551, elapsed=29.3min]

Entraînement:  92%|█████████▏| 9152/10000 [29:20<02:41,  5.26step/s, loss=0.046734, elapsed=29.3min]

Entraînement:  92%|█████████▏| 9153/10000 [29:20<02:41,  5.26step/s, loss=0.046734, elapsed=29.3min]

Entraînement:  92%|█████████▏| 9153/10000 [29:20<02:41,  5.26step/s, loss=0.032966, elapsed=29.3min]

Entraînement:  92%|█████████▏| 9154/10000 [29:20<02:40,  5.27step/s, loss=0.032966, elapsed=29.3min]

Entraînement:  92%|█████████▏| 9154/10000 [29:20<02:40,  5.27step/s, loss=0.026004, elapsed=29.3min]

Entraînement:  92%|█████████▏| 9155/10000 [29:21<02:40,  5.27step/s, loss=0.026004, elapsed=29.3min]

Entraînement:  92%|█████████▏| 9155/10000 [29:21<02:40,  5.27step/s, loss=0.029957, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9156/10000 [29:21<02:40,  5.27step/s, loss=0.029957, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9156/10000 [29:21<02:40,  5.27step/s, loss=0.033183, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9157/10000 [29:21<02:39,  5.27step/s, loss=0.033183, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9157/10000 [29:21<02:39,  5.27step/s, loss=0.033738, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9158/10000 [29:21<02:40,  5.26step/s, loss=0.033738, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9158/10000 [29:21<02:40,  5.26step/s, loss=0.014386, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9159/10000 [29:21<02:39,  5.27step/s, loss=0.014386, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9159/10000 [29:21<02:39,  5.27step/s, loss=0.027044, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9160/10000 [29:22<02:39,  5.27step/s, loss=0.027044, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9160/10000 [29:22<02:39,  5.27step/s, loss=0.109042, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9161/10000 [29:22<02:39,  5.27step/s, loss=0.109042, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9161/10000 [29:22<02:39,  5.27step/s, loss=0.024714, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9162/10000 [29:22<02:39,  5.26step/s, loss=0.024714, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9162/10000 [29:22<02:39,  5.26step/s, loss=0.042040, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9163/10000 [29:22<02:38,  5.27step/s, loss=0.042040, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9163/10000 [29:22<02:38,  5.27step/s, loss=0.042971, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9164/10000 [29:22<02:38,  5.26step/s, loss=0.042971, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9164/10000 [29:22<02:38,  5.26step/s, loss=0.089085, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9165/10000 [29:23<02:38,  5.27step/s, loss=0.089085, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9165/10000 [29:23<02:38,  5.27step/s, loss=0.189741, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9166/10000 [29:23<02:38,  5.27step/s, loss=0.189741, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9166/10000 [29:23<02:38,  5.27step/s, loss=0.019584, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9167/10000 [29:23<02:38,  5.25step/s, loss=0.019584, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9167/10000 [29:23<02:38,  5.25step/s, loss=0.022005, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9168/10000 [29:23<02:38,  5.26step/s, loss=0.022005, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9168/10000 [29:23<02:38,  5.26step/s, loss=0.027926, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9169/10000 [29:23<02:37,  5.27step/s, loss=0.027926, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9169/10000 [29:23<02:37,  5.27step/s, loss=0.050228, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9170/10000 [29:24<02:37,  5.26step/s, loss=0.050228, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9170/10000 [29:24<02:37,  5.26step/s, loss=0.029031, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9171/10000 [29:24<02:37,  5.26step/s, loss=0.029031, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9171/10000 [29:24<02:37,  5.26step/s, loss=0.015552, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9172/10000 [29:24<02:37,  5.26step/s, loss=0.015552, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9172/10000 [29:24<02:37,  5.26step/s, loss=0.063266, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9173/10000 [29:24<02:37,  5.27step/s, loss=0.063266, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9173/10000 [29:24<02:37,  5.27step/s, loss=0.083718, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9174/10000 [29:24<02:36,  5.26step/s, loss=0.083718, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9174/10000 [29:24<02:36,  5.26step/s, loss=0.048179, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9175/10000 [29:24<02:36,  5.26step/s, loss=0.048179, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9175/10000 [29:24<02:36,  5.26step/s, loss=0.088872, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9176/10000 [29:25<02:36,  5.26step/s, loss=0.088872, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9176/10000 [29:25<02:36,  5.26step/s, loss=0.035591, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9177/10000 [29:25<02:36,  5.26step/s, loss=0.035591, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9177/10000 [29:25<02:36,  5.26step/s, loss=0.030614, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9178/10000 [29:25<02:36,  5.26step/s, loss=0.030614, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9178/10000 [29:25<02:36,  5.26step/s, loss=0.056253, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9179/10000 [29:25<02:35,  5.27step/s, loss=0.056253, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9179/10000 [29:25<02:35,  5.27step/s, loss=0.050818, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9180/10000 [29:25<02:35,  5.27step/s, loss=0.050818, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9180/10000 [29:25<02:35,  5.27step/s, loss=0.027056, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9181/10000 [29:26<02:35,  5.26step/s, loss=0.027056, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9181/10000 [29:26<02:35,  5.26step/s, loss=0.073450, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9182/10000 [29:26<02:35,  5.26step/s, loss=0.073450, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9182/10000 [29:26<02:35,  5.26step/s, loss=0.075024, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9183/10000 [29:26<02:35,  5.26step/s, loss=0.075024, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9183/10000 [29:26<02:35,  5.26step/s, loss=0.029030, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9184/10000 [29:26<02:34,  5.27step/s, loss=0.029030, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9184/10000 [29:26<02:34,  5.27step/s, loss=0.035181, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9185/10000 [29:26<02:34,  5.26step/s, loss=0.035181, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9185/10000 [29:26<02:34,  5.26step/s, loss=0.060802, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9186/10000 [29:27<02:34,  5.27step/s, loss=0.060802, elapsed=29.4min]

Entraînement:  92%|█████████▏| 9186/10000 [29:27<02:34,  5.27step/s, loss=0.050932, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9187/10000 [29:27<02:34,  5.27step/s, loss=0.050932, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9187/10000 [29:27<02:34,  5.27step/s, loss=0.054458, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9188/10000 [29:27<02:34,  5.27step/s, loss=0.054458, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9188/10000 [29:27<02:34,  5.27step/s, loss=0.073652, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9189/10000 [29:27<02:34,  5.26step/s, loss=0.073652, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9189/10000 [29:27<02:34,  5.26step/s, loss=0.040912, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9190/10000 [29:27<02:34,  5.25step/s, loss=0.040912, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9190/10000 [29:27<02:34,  5.25step/s, loss=0.032811, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9191/10000 [29:28<02:33,  5.26step/s, loss=0.032811, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9191/10000 [29:28<02:33,  5.26step/s, loss=0.048183, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9192/10000 [29:28<02:33,  5.25step/s, loss=0.048183, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9192/10000 [29:28<02:33,  5.25step/s, loss=0.034929, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9193/10000 [29:28<02:33,  5.25step/s, loss=0.034929, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9193/10000 [29:28<02:33,  5.25step/s, loss=0.044668, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9194/10000 [29:28<02:33,  5.25step/s, loss=0.044668, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9194/10000 [29:28<02:33,  5.25step/s, loss=0.034468, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9195/10000 [29:28<02:33,  5.25step/s, loss=0.034468, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9195/10000 [29:28<02:33,  5.25step/s, loss=0.103015, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9196/10000 [29:28<02:33,  5.24step/s, loss=0.103015, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9196/10000 [29:28<02:33,  5.24step/s, loss=0.114605, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9197/10000 [29:29<02:33,  5.24step/s, loss=0.114605, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9197/10000 [29:29<02:33,  5.24step/s, loss=0.074901, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9198/10000 [29:29<02:32,  5.24step/s, loss=0.074901, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9198/10000 [29:29<02:32,  5.24step/s, loss=0.054439, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9199/10000 [29:29<02:32,  5.24step/s, loss=0.054439, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9199/10000 [29:29<02:32,  5.24step/s, loss=0.042320, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9200/10000 [29:29<02:32,  5.25step/s, loss=0.042320, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9200/10000 [29:29<02:32,  5.25step/s, loss=0.048264, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9200/10000 [29:29<02:32,  5.25step/s, loss=0.048264, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9201/10000 [29:29<02:33,  5.19step/s, loss=0.048264, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9201/10000 [29:29<02:33,  5.19step/s, loss=0.055492, elapsed=29.5min]

Step 9200/10000 | Train loss: 0.048264 | Elapsed: 29.5min | ETA: 2.6min

Entraînement:  92%|█████████▏| 9202/10000 [29:30<02:33,  5.20step/s, loss=0.055492, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9202/10000 [29:30<02:33,  5.20step/s, loss=0.188739, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9203/10000 [29:30<02:32,  5.22step/s, loss=0.188739, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9203/10000 [29:30<02:32,  5.22step/s, loss=0.113364, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9204/10000 [29:30<02:32,  5.22step/s, loss=0.113364, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9204/10000 [29:30<02:32,  5.22step/s, loss=0.042067, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9205/10000 [29:30<02:32,  5.23step/s, loss=0.042067, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9205/10000 [29:30<02:32,  5.23step/s, loss=0.036538, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9206/10000 [29:30<02:31,  5.23step/s, loss=0.036538, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9206/10000 [29:30<02:31,  5.23step/s, loss=0.034856, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9207/10000 [29:31<02:31,  5.24step/s, loss=0.034856, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9207/10000 [29:31<02:31,  5.24step/s, loss=0.073904, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9208/10000 [29:31<02:31,  5.24step/s, loss=0.073904, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9208/10000 [29:31<02:31,  5.24step/s, loss=0.064068, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9209/10000 [29:31<02:30,  5.25step/s, loss=0.064068, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9209/10000 [29:31<02:30,  5.25step/s, loss=0.031061, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9210/10000 [29:31<02:30,  5.24step/s, loss=0.031061, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9210/10000 [29:31<02:30,  5.24step/s, loss=0.031232, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9211/10000 [29:31<02:30,  5.24step/s, loss=0.031232, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9211/10000 [29:31<02:30,  5.24step/s, loss=0.033145, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9212/10000 [29:32<02:30,  5.23step/s, loss=0.033145, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9212/10000 [29:32<02:30,  5.23step/s, loss=0.052682, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9213/10000 [29:32<02:30,  5.21step/s, loss=0.052682, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9213/10000 [29:32<02:30,  5.21step/s, loss=0.043114, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9214/10000 [29:32<02:30,  5.21step/s, loss=0.043114, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9214/10000 [29:32<02:30,  5.21step/s, loss=0.056058, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9215/10000 [29:32<02:30,  5.21step/s, loss=0.056058, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9215/10000 [29:32<02:30,  5.21step/s, loss=0.024832, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9216/10000 [29:32<02:31,  5.18step/s, loss=0.024832, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9216/10000 [29:32<02:31,  5.18step/s, loss=0.026015, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9217/10000 [29:32<02:30,  5.19step/s, loss=0.026015, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9217/10000 [29:32<02:30,  5.19step/s, loss=0.103366, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9218/10000 [29:33<02:30,  5.20step/s, loss=0.103366, elapsed=29.5min]

Entraînement:  92%|█████████▏| 9218/10000 [29:33<02:30,  5.20step/s, loss=0.076362, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9219/10000 [29:33<02:29,  5.23step/s, loss=0.076362, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9219/10000 [29:33<02:29,  5.23step/s, loss=0.034283, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9220/10000 [29:33<02:28,  5.24step/s, loss=0.034283, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9220/10000 [29:33<02:28,  5.24step/s, loss=0.020624, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9221/10000 [29:33<02:28,  5.26step/s, loss=0.020624, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9221/10000 [29:33<02:28,  5.26step/s, loss=0.019874, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9222/10000 [29:33<02:27,  5.27step/s, loss=0.019874, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9222/10000 [29:33<02:27,  5.27step/s, loss=0.023439, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9223/10000 [29:34<02:29,  5.18step/s, loss=0.023439, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9223/10000 [29:34<02:29,  5.18step/s, loss=0.028269, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9224/10000 [29:34<02:29,  5.20step/s, loss=0.028269, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9224/10000 [29:34<02:29,  5.20step/s, loss=0.105728, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9225/10000 [29:34<02:28,  5.21step/s, loss=0.105728, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9225/10000 [29:34<02:28,  5.21step/s, loss=0.098777, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9226/10000 [29:34<02:28,  5.22step/s, loss=0.098777, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9226/10000 [29:34<02:28,  5.22step/s, loss=0.060699, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9227/10000 [29:34<02:27,  5.23step/s, loss=0.060699, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9227/10000 [29:34<02:27,  5.23step/s, loss=0.026936, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9228/10000 [29:35<02:27,  5.24step/s, loss=0.026936, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9228/10000 [29:35<02:27,  5.24step/s, loss=0.047644, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9229/10000 [29:35<02:26,  5.26step/s, loss=0.047644, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9229/10000 [29:35<02:26,  5.26step/s, loss=0.020439, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9230/10000 [29:35<02:26,  5.26step/s, loss=0.020439, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9230/10000 [29:35<02:26,  5.26step/s, loss=0.033973, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9231/10000 [29:35<02:25,  5.27step/s, loss=0.033973, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9231/10000 [29:35<02:25,  5.27step/s, loss=0.048582, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9232/10000 [29:35<02:25,  5.26step/s, loss=0.048582, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9232/10000 [29:35<02:25,  5.26step/s, loss=0.022171, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9233/10000 [29:36<02:25,  5.26step/s, loss=0.022171, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9233/10000 [29:36<02:25,  5.26step/s, loss=0.040820, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9234/10000 [29:36<02:25,  5.26step/s, loss=0.040820, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9234/10000 [29:36<02:25,  5.26step/s, loss=0.062260, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9235/10000 [29:36<02:25,  5.26step/s, loss=0.062260, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9235/10000 [29:36<02:25,  5.26step/s, loss=0.054408, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9236/10000 [29:36<02:24,  5.27step/s, loss=0.054408, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9236/10000 [29:36<02:24,  5.27step/s, loss=0.034601, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9237/10000 [29:36<02:24,  5.27step/s, loss=0.034601, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9237/10000 [29:36<02:24,  5.27step/s, loss=0.038813, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9238/10000 [29:36<02:24,  5.28step/s, loss=0.038813, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9238/10000 [29:36<02:24,  5.28step/s, loss=0.036222, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9239/10000 [29:37<02:24,  5.28step/s, loss=0.036222, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9239/10000 [29:37<02:24,  5.28step/s, loss=0.048639, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9240/10000 [29:37<02:24,  5.27step/s, loss=0.048639, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9240/10000 [29:37<02:24,  5.27step/s, loss=0.043469, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9241/10000 [29:37<02:23,  5.27step/s, loss=0.043469, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9241/10000 [29:37<02:23,  5.27step/s, loss=0.023680, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9242/10000 [29:37<02:23,  5.27step/s, loss=0.023680, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9242/10000 [29:37<02:23,  5.27step/s, loss=0.024133, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9243/10000 [29:37<02:23,  5.27step/s, loss=0.024133, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9243/10000 [29:37<02:23,  5.27step/s, loss=0.049718, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9244/10000 [29:38<02:23,  5.26step/s, loss=0.049718, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9244/10000 [29:38<02:23,  5.26step/s, loss=0.035104, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9245/10000 [29:38<02:23,  5.26step/s, loss=0.035104, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9245/10000 [29:38<02:23,  5.26step/s, loss=0.032736, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9246/10000 [29:38<02:23,  5.26step/s, loss=0.032736, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9246/10000 [29:38<02:23,  5.26step/s, loss=0.037011, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9247/10000 [29:38<02:23,  5.25step/s, loss=0.037011, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9247/10000 [29:38<02:23,  5.25step/s, loss=0.051400, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9248/10000 [29:38<02:23,  5.23step/s, loss=0.051400, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9248/10000 [29:38<02:23,  5.23step/s, loss=0.078865, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9249/10000 [29:39<02:23,  5.23step/s, loss=0.078865, elapsed=29.6min]

Entraînement:  92%|█████████▏| 9249/10000 [29:39<02:23,  5.23step/s, loss=0.079555, elapsed=29.7min]

Entraînement:  92%|█████████▎| 9250/10000 [29:39<02:23,  5.23step/s, loss=0.079555, elapsed=29.7min]

Entraînement:  92%|█████████▎| 9250/10000 [29:39<02:23,  5.23step/s, loss=0.048659, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9251/10000 [29:39<02:22,  5.24step/s, loss=0.048659, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9251/10000 [29:39<02:22,  5.24step/s, loss=0.026438, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9252/10000 [29:39<02:22,  5.25step/s, loss=0.026438, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9252/10000 [29:39<02:22,  5.25step/s, loss=0.040143, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9253/10000 [29:39<02:22,  5.26step/s, loss=0.040143, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9253/10000 [29:39<02:22,  5.26step/s, loss=0.063290, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9254/10000 [29:40<02:21,  5.27step/s, loss=0.063290, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9254/10000 [29:40<02:21,  5.27step/s, loss=0.031826, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9255/10000 [29:40<02:21,  5.26step/s, loss=0.031826, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9255/10000 [29:40<02:21,  5.26step/s, loss=0.036329, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9256/10000 [29:40<02:21,  5.26step/s, loss=0.036329, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9256/10000 [29:40<02:21,  5.26step/s, loss=0.031617, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9257/10000 [29:40<02:21,  5.26step/s, loss=0.031617, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9257/10000 [29:40<02:21,  5.26step/s, loss=0.045494, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9258/10000 [29:40<02:21,  5.26step/s, loss=0.045494, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9258/10000 [29:40<02:21,  5.26step/s, loss=0.023100, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9259/10000 [29:40<02:20,  5.27step/s, loss=0.023100, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9259/10000 [29:40<02:20,  5.27step/s, loss=0.058984, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9260/10000 [29:41<02:20,  5.27step/s, loss=0.058984, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9260/10000 [29:41<02:20,  5.27step/s, loss=0.030916, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9261/10000 [29:41<02:20,  5.27step/s, loss=0.030916, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9261/10000 [29:41<02:20,  5.27step/s, loss=0.029414, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9262/10000 [29:41<02:19,  5.28step/s, loss=0.029414, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9262/10000 [29:41<02:19,  5.28step/s, loss=0.025524, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9263/10000 [29:41<02:19,  5.27step/s, loss=0.025524, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9263/10000 [29:41<02:19,  5.27step/s, loss=0.047247, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9264/10000 [29:41<02:19,  5.26step/s, loss=0.047247, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9264/10000 [29:41<02:19,  5.26step/s, loss=0.035942, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9265/10000 [29:42<02:19,  5.27step/s, loss=0.035942, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9265/10000 [29:42<02:19,  5.27step/s, loss=0.031799, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9266/10000 [29:42<02:19,  5.26step/s, loss=0.031799, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9266/10000 [29:42<02:19,  5.26step/s, loss=0.019952, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9267/10000 [29:42<02:19,  5.25step/s, loss=0.019952, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9267/10000 [29:42<02:19,  5.25step/s, loss=0.036337, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9268/10000 [29:42<02:19,  5.24step/s, loss=0.036337, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9268/10000 [29:42<02:19,  5.24step/s, loss=0.089773, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9269/10000 [29:42<02:19,  5.24step/s, loss=0.089773, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9269/10000 [29:42<02:19,  5.24step/s, loss=0.151147, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9270/10000 [29:43<02:19,  5.23step/s, loss=0.151147, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9270/10000 [29:43<02:19,  5.23step/s, loss=0.025833, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9271/10000 [29:43<02:19,  5.22step/s, loss=0.025833, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9271/10000 [29:43<02:19,  5.22step/s, loss=0.096775, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9272/10000 [29:43<02:19,  5.23step/s, loss=0.096775, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9272/10000 [29:43<02:19,  5.23step/s, loss=0.046557, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9273/10000 [29:43<02:18,  5.25step/s, loss=0.046557, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9273/10000 [29:43<02:18,  5.25step/s, loss=0.060697, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9274/10000 [29:43<02:18,  5.25step/s, loss=0.060697, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9274/10000 [29:43<02:18,  5.25step/s, loss=0.043513, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9275/10000 [29:44<02:18,  5.24step/s, loss=0.043513, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9275/10000 [29:44<02:18,  5.24step/s, loss=0.023625, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9276/10000 [29:44<02:17,  5.26step/s, loss=0.023625, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9276/10000 [29:44<02:17,  5.26step/s, loss=0.032331, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9277/10000 [29:44<02:17,  5.26step/s, loss=0.032331, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9277/10000 [29:44<02:17,  5.26step/s, loss=0.036380, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9278/10000 [29:44<02:17,  5.27step/s, loss=0.036380, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9278/10000 [29:44<02:17,  5.27step/s, loss=0.035592, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9279/10000 [29:44<02:16,  5.26step/s, loss=0.035592, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9279/10000 [29:44<02:16,  5.26step/s, loss=0.050860, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9280/10000 [29:44<02:16,  5.27step/s, loss=0.050860, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9280/10000 [29:44<02:16,  5.27step/s, loss=0.045978, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9281/10000 [29:45<02:16,  5.26step/s, loss=0.045978, elapsed=29.7min]

Entraînement:  93%|█████████▎| 9281/10000 [29:45<02:16,  5.26step/s, loss=0.039079, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9282/10000 [29:45<02:16,  5.26step/s, loss=0.039079, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9282/10000 [29:45<02:16,  5.26step/s, loss=0.062357, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9283/10000 [29:45<02:16,  5.27step/s, loss=0.062357, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9283/10000 [29:45<02:16,  5.27step/s, loss=0.046526, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9284/10000 [29:45<02:15,  5.28step/s, loss=0.046526, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9284/10000 [29:45<02:15,  5.28step/s, loss=0.018649, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9285/10000 [29:45<02:15,  5.28step/s, loss=0.018649, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9285/10000 [29:45<02:15,  5.28step/s, loss=0.036346, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9286/10000 [29:46<02:15,  5.26step/s, loss=0.036346, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9286/10000 [29:46<02:15,  5.26step/s, loss=0.022628, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9287/10000 [29:46<02:15,  5.27step/s, loss=0.022628, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9287/10000 [29:46<02:15,  5.27step/s, loss=0.020543, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9288/10000 [29:46<02:14,  5.28step/s, loss=0.020543, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9288/10000 [29:46<02:14,  5.28step/s, loss=0.046099, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9289/10000 [29:46<02:15,  5.26step/s, loss=0.046099, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9289/10000 [29:46<02:15,  5.26step/s, loss=0.039666, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9290/10000 [29:46<02:15,  5.25step/s, loss=0.039666, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9290/10000 [29:46<02:15,  5.25step/s, loss=0.028301, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9291/10000 [29:47<02:14,  5.26step/s, loss=0.028301, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9291/10000 [29:47<02:14,  5.26step/s, loss=0.028096, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9292/10000 [29:47<02:14,  5.26step/s, loss=0.028096, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9292/10000 [29:47<02:14,  5.26step/s, loss=0.031834, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9293/10000 [29:47<02:14,  5.26step/s, loss=0.031834, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9293/10000 [29:47<02:14,  5.26step/s, loss=0.051082, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9294/10000 [29:47<02:13,  5.27step/s, loss=0.051082, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9294/10000 [29:47<02:13,  5.27step/s, loss=0.102812, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9295/10000 [29:47<02:13,  5.27step/s, loss=0.102812, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9295/10000 [29:47<02:13,  5.27step/s, loss=0.024560, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9296/10000 [29:48<02:13,  5.27step/s, loss=0.024560, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9296/10000 [29:48<02:13,  5.27step/s, loss=0.032669, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9297/10000 [29:48<02:13,  5.27step/s, loss=0.032669, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9297/10000 [29:48<02:13,  5.27step/s, loss=0.026654, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9298/10000 [29:48<02:13,  5.25step/s, loss=0.026654, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9298/10000 [29:48<02:13,  5.25step/s, loss=0.123997, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9299/10000 [29:48<02:13,  5.26step/s, loss=0.123997, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9299/10000 [29:48<02:13,  5.26step/s, loss=0.101880, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9300/10000 [29:48<02:12,  5.27step/s, loss=0.101880, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9300/10000 [29:48<02:12,  5.27step/s, loss=0.075998, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9300/10000 [29:48<02:12,  5.27step/s, loss=0.075998, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9301/10000 [29:48<02:14,  5.21step/s, loss=0.075998, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9301/10000 [29:48<02:14,  5.21step/s, loss=0.093231, elapsed=29.8min]

Step 9300/10000 | Train loss: 0.075998 | Elapsed: 29.8min | ETA: 2.2min

Entraînement:  93%|█████████▎| 9302/10000 [29:49<02:13,  5.21step/s, loss=0.093231, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9302/10000 [29:49<02:13,  5.21step/s, loss=0.071873, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9303/10000 [29:49<02:13,  5.23step/s, loss=0.071873, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9303/10000 [29:49<02:13,  5.23step/s, loss=0.020784, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9304/10000 [29:49<02:12,  5.25step/s, loss=0.020784, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9304/10000 [29:49<02:12,  5.25step/s, loss=0.060790, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9305/10000 [29:49<02:12,  5.25step/s, loss=0.060790, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9305/10000 [29:49<02:12,  5.25step/s, loss=0.048258, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9306/10000 [29:49<02:13,  5.20step/s, loss=0.048258, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9306/10000 [29:49<02:13,  5.20step/s, loss=0.068178, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9307/10000 [29:50<02:13,  5.21step/s, loss=0.068178, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9307/10000 [29:50<02:13,  5.21step/s, loss=0.042316, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9308/10000 [29:50<02:12,  5.24step/s, loss=0.042316, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9308/10000 [29:50<02:12,  5.24step/s, loss=0.077327, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9309/10000 [29:50<02:11,  5.24step/s, loss=0.077327, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9309/10000 [29:50<02:11,  5.24step/s, loss=0.029468, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9310/10000 [29:50<02:11,  5.25step/s, loss=0.029468, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9310/10000 [29:50<02:11,  5.25step/s, loss=0.036476, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9311/10000 [29:50<02:10,  5.26step/s, loss=0.036476, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9311/10000 [29:50<02:10,  5.26step/s, loss=0.104337, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9312/10000 [29:51<02:10,  5.26step/s, loss=0.104337, elapsed=29.8min]

Entraînement:  93%|█████████▎| 9312/10000 [29:51<02:10,  5.26step/s, loss=0.043459, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9313/10000 [29:51<02:10,  5.27step/s, loss=0.043459, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9313/10000 [29:51<02:10,  5.27step/s, loss=0.020692, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9314/10000 [29:51<02:10,  5.27step/s, loss=0.020692, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9314/10000 [29:51<02:10,  5.27step/s, loss=0.021271, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9315/10000 [29:51<02:09,  5.27step/s, loss=0.021271, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9315/10000 [29:51<02:09,  5.27step/s, loss=0.058255, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9316/10000 [29:51<02:09,  5.27step/s, loss=0.058255, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9316/10000 [29:51<02:09,  5.27step/s, loss=0.029168, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9317/10000 [29:52<02:09,  5.28step/s, loss=0.029168, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9317/10000 [29:52<02:09,  5.28step/s, loss=0.063762, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9318/10000 [29:52<02:09,  5.28step/s, loss=0.063762, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9318/10000 [29:52<02:09,  5.28step/s, loss=0.026508, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9319/10000 [29:52<02:09,  5.28step/s, loss=0.026508, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9319/10000 [29:52<02:09,  5.28step/s, loss=0.034919, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9320/10000 [29:52<02:09,  5.25step/s, loss=0.034919, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9320/10000 [29:52<02:09,  5.25step/s, loss=0.071721, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9321/10000 [29:52<02:08,  5.26step/s, loss=0.071721, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9321/10000 [29:52<02:08,  5.26step/s, loss=0.023090, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9322/10000 [29:52<02:08,  5.27step/s, loss=0.023090, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9322/10000 [29:52<02:08,  5.27step/s, loss=0.122317, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9323/10000 [29:53<02:08,  5.25step/s, loss=0.122317, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9323/10000 [29:53<02:08,  5.25step/s, loss=0.032018, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9324/10000 [29:53<02:08,  5.27step/s, loss=0.032018, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9324/10000 [29:53<02:08,  5.27step/s, loss=0.065730, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9325/10000 [29:53<02:07,  5.28step/s, loss=0.065730, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9325/10000 [29:53<02:07,  5.28step/s, loss=0.039424, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9326/10000 [29:53<02:07,  5.28step/s, loss=0.039424, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9326/10000 [29:53<02:07,  5.28step/s, loss=0.038150, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9327/10000 [29:53<02:07,  5.29step/s, loss=0.038150, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9327/10000 [29:53<02:07,  5.29step/s, loss=0.040142, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9328/10000 [29:54<02:07,  5.28step/s, loss=0.040142, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9328/10000 [29:54<02:07,  5.28step/s, loss=0.036331, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9329/10000 [29:54<02:07,  5.28step/s, loss=0.036331, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9329/10000 [29:54<02:07,  5.28step/s, loss=0.042710, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9330/10000 [29:54<02:07,  5.26step/s, loss=0.042710, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9330/10000 [29:54<02:07,  5.26step/s, loss=0.057956, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9331/10000 [29:54<02:07,  5.26step/s, loss=0.057956, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9331/10000 [29:54<02:07,  5.26step/s, loss=0.027072, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9332/10000 [29:54<02:07,  5.26step/s, loss=0.027072, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9332/10000 [29:54<02:07,  5.26step/s, loss=0.031275, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9333/10000 [29:55<02:06,  5.26step/s, loss=0.031275, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9333/10000 [29:55<02:06,  5.26step/s, loss=0.022272, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9334/10000 [29:55<02:06,  5.27step/s, loss=0.022272, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9334/10000 [29:55<02:06,  5.27step/s, loss=0.041503, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9335/10000 [29:55<02:07,  5.23step/s, loss=0.041503, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9335/10000 [29:55<02:07,  5.23step/s, loss=0.018206, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9336/10000 [29:55<02:06,  5.25step/s, loss=0.018206, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9336/10000 [29:55<02:06,  5.25step/s, loss=0.055366, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9337/10000 [29:55<02:06,  5.25step/s, loss=0.055366, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9337/10000 [29:55<02:06,  5.25step/s, loss=0.036441, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9338/10000 [29:56<02:06,  5.25step/s, loss=0.036441, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9338/10000 [29:56<02:06,  5.25step/s, loss=0.024661, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9339/10000 [29:56<02:05,  5.26step/s, loss=0.024661, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9339/10000 [29:56<02:05,  5.26step/s, loss=0.032908, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9340/10000 [29:56<02:05,  5.26step/s, loss=0.032908, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9340/10000 [29:56<02:05,  5.26step/s, loss=0.040425, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9341/10000 [29:56<02:05,  5.27step/s, loss=0.040425, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9341/10000 [29:56<02:05,  5.27step/s, loss=0.027750, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9342/10000 [29:56<02:04,  5.27step/s, loss=0.027750, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9342/10000 [29:56<02:04,  5.27step/s, loss=0.050834, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9343/10000 [29:56<02:04,  5.27step/s, loss=0.050834, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9343/10000 [29:56<02:04,  5.27step/s, loss=0.053706, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9344/10000 [29:57<02:04,  5.27step/s, loss=0.053706, elapsed=29.9min]

Entraînement:  93%|█████████▎| 9344/10000 [29:57<02:04,  5.27step/s, loss=0.058370, elapsed=30.0min]

Entraînement:  93%|█████████▎| 9345/10000 [29:57<02:04,  5.28step/s, loss=0.058370, elapsed=30.0min]

Entraînement:  93%|█████████▎| 9345/10000 [29:57<02:04,  5.28step/s, loss=0.026509, elapsed=30.0min]

Entraînement:  93%|█████████▎| 9346/10000 [29:57<02:04,  5.27step/s, loss=0.026509, elapsed=30.0min]

Entraînement:  93%|█████████▎| 9346/10000 [29:57<02:04,  5.27step/s, loss=0.113213, elapsed=30.0min]

Entraînement:  93%|█████████▎| 9347/10000 [29:57<02:03,  5.28step/s, loss=0.113213, elapsed=30.0min]

Entraînement:  93%|█████████▎| 9347/10000 [29:57<02:03,  5.28step/s, loss=0.022172, elapsed=30.0min]

Entraînement:  93%|█████████▎| 9348/10000 [29:57<02:03,  5.28step/s, loss=0.022172, elapsed=30.0min]

Entraînement:  93%|█████████▎| 9348/10000 [29:57<02:03,  5.28step/s, loss=0.029982, elapsed=30.0min]

Entraînement:  93%|█████████▎| 9349/10000 [29:58<02:03,  5.28step/s, loss=0.029982, elapsed=30.0min]

Entraînement:  93%|█████████▎| 9349/10000 [29:58<02:03,  5.28step/s, loss=0.034307, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9350/10000 [29:58<02:03,  5.28step/s, loss=0.034307, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9350/10000 [29:58<02:03,  5.28step/s, loss=0.039133, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9351/10000 [29:58<02:03,  5.27step/s, loss=0.039133, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9351/10000 [29:58<02:03,  5.27step/s, loss=0.043458, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9352/10000 [29:58<02:02,  5.27step/s, loss=0.043458, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9352/10000 [29:58<02:02,  5.27step/s, loss=0.032190, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9353/10000 [29:58<02:02,  5.26step/s, loss=0.032190, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9353/10000 [29:58<02:02,  5.26step/s, loss=0.049175, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9354/10000 [29:59<02:02,  5.26step/s, loss=0.049175, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9354/10000 [29:59<02:02,  5.26step/s, loss=0.019607, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9355/10000 [29:59<02:02,  5.26step/s, loss=0.019607, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9355/10000 [29:59<02:02,  5.26step/s, loss=0.057881, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9356/10000 [29:59<02:02,  5.26step/s, loss=0.057881, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9356/10000 [29:59<02:02,  5.26step/s, loss=0.030493, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9357/10000 [29:59<02:01,  5.27step/s, loss=0.030493, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9357/10000 [29:59<02:01,  5.27step/s, loss=0.049414, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9358/10000 [29:59<02:01,  5.27step/s, loss=0.049414, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9358/10000 [29:59<02:01,  5.27step/s, loss=0.080415, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9359/10000 [29:59<02:01,  5.27step/s, loss=0.080415, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9359/10000 [29:59<02:01,  5.27step/s, loss=0.033491, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9360/10000 [30:00<02:02,  5.22step/s, loss=0.033491, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9360/10000 [30:00<02:02,  5.22step/s, loss=0.029816, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9361/10000 [30:00<02:02,  5.23step/s, loss=0.029816, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9361/10000 [30:00<02:02,  5.23step/s, loss=0.040901, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9362/10000 [30:00<02:01,  5.24step/s, loss=0.040901, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9362/10000 [30:00<02:01,  5.24step/s, loss=0.024712, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9363/10000 [30:00<02:01,  5.26step/s, loss=0.024712, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9363/10000 [30:00<02:01,  5.26step/s, loss=0.017175, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9364/10000 [30:00<02:00,  5.26step/s, loss=0.017175, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9364/10000 [30:00<02:00,  5.26step/s, loss=0.045831, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9365/10000 [30:01<02:00,  5.27step/s, loss=0.045831, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9365/10000 [30:01<02:00,  5.27step/s, loss=0.021661, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9366/10000 [30:01<01:59,  5.28step/s, loss=0.021661, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9366/10000 [30:01<01:59,  5.28step/s, loss=0.129047, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9367/10000 [30:01<01:59,  5.29step/s, loss=0.129047, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9367/10000 [30:01<01:59,  5.29step/s, loss=0.034149, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9368/10000 [30:01<01:59,  5.29step/s, loss=0.034149, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9368/10000 [30:01<01:59,  5.29step/s, loss=0.058311, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9369/10000 [30:01<01:59,  5.29step/s, loss=0.058311, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9369/10000 [30:01<01:59,  5.29step/s, loss=0.029399, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9370/10000 [30:02<01:58,  5.30step/s, loss=0.029399, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9370/10000 [30:02<01:58,  5.30step/s, loss=0.021210, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9371/10000 [30:02<01:58,  5.31step/s, loss=0.021210, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9371/10000 [30:02<01:58,  5.31step/s, loss=0.094659, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9372/10000 [30:02<01:58,  5.31step/s, loss=0.094659, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9372/10000 [30:02<01:58,  5.31step/s, loss=0.022097, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9373/10000 [30:02<01:58,  5.31step/s, loss=0.022097, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9373/10000 [30:02<01:58,  5.31step/s, loss=0.010491, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9374/10000 [30:02<01:58,  5.29step/s, loss=0.010491, elapsed=30.0min]

Entraînement:  94%|█████████▎| 9374/10000 [30:02<01:58,  5.29step/s, loss=0.024229, elapsed=30.0min]

Entraînement:  94%|█████████▍| 9375/10000 [30:03<01:58,  5.27step/s, loss=0.024229, elapsed=30.0min]

Entraînement:  94%|█████████▍| 9375/10000 [30:03<01:58,  5.27step/s, loss=0.071861, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9376/10000 [30:03<01:58,  5.27step/s, loss=0.071861, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9376/10000 [30:03<01:58,  5.27step/s, loss=0.019136, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9377/10000 [30:03<01:58,  5.24step/s, loss=0.019136, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9377/10000 [30:03<01:58,  5.24step/s, loss=0.034833, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9378/10000 [30:03<01:58,  5.25step/s, loss=0.034833, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9378/10000 [30:03<01:58,  5.25step/s, loss=0.048013, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9379/10000 [30:03<01:58,  5.24step/s, loss=0.048013, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9379/10000 [30:03<01:58,  5.24step/s, loss=0.051864, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9380/10000 [30:03<01:58,  5.24step/s, loss=0.051864, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9380/10000 [30:03<01:58,  5.24step/s, loss=0.040375, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9381/10000 [30:04<01:58,  5.24step/s, loss=0.040375, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9381/10000 [30:04<01:58,  5.24step/s, loss=0.016137, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9382/10000 [30:04<01:57,  5.24step/s, loss=0.016137, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9382/10000 [30:04<01:57,  5.24step/s, loss=0.031936, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9383/10000 [30:04<01:57,  5.24step/s, loss=0.031936, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9383/10000 [30:04<01:57,  5.24step/s, loss=0.045083, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9384/10000 [30:04<01:57,  5.24step/s, loss=0.045083, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9384/10000 [30:04<01:57,  5.24step/s, loss=0.026855, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9385/10000 [30:04<01:57,  5.24step/s, loss=0.026855, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9385/10000 [30:04<01:57,  5.24step/s, loss=0.090121, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9386/10000 [30:05<01:56,  5.25step/s, loss=0.090121, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9386/10000 [30:05<01:56,  5.25step/s, loss=0.033360, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9387/10000 [30:05<01:56,  5.25step/s, loss=0.033360, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9387/10000 [30:05<01:56,  5.25step/s, loss=0.048252, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9388/10000 [30:05<01:56,  5.26step/s, loss=0.048252, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9388/10000 [30:05<01:56,  5.26step/s, loss=0.048990, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9389/10000 [30:05<01:56,  5.26step/s, loss=0.048990, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9389/10000 [30:05<01:56,  5.26step/s, loss=0.048977, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9390/10000 [30:05<01:55,  5.26step/s, loss=0.048977, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9390/10000 [30:05<01:55,  5.26step/s, loss=0.094127, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9391/10000 [30:06<01:55,  5.27step/s, loss=0.094127, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9391/10000 [30:06<01:55,  5.27step/s, loss=0.032185, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9392/10000 [30:06<01:55,  5.27step/s, loss=0.032185, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9392/10000 [30:06<01:55,  5.27step/s, loss=0.019256, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9393/10000 [30:06<01:55,  5.27step/s, loss=0.019256, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9393/10000 [30:06<01:55,  5.27step/s, loss=0.125999, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9394/10000 [30:06<01:55,  5.26step/s, loss=0.125999, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9394/10000 [30:06<01:55,  5.26step/s, loss=0.030955, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9395/10000 [30:06<01:54,  5.27step/s, loss=0.030955, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9395/10000 [30:06<01:54,  5.27step/s, loss=0.100902, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9396/10000 [30:07<01:54,  5.27step/s, loss=0.100902, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9396/10000 [30:07<01:54,  5.27step/s, loss=0.052707, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9397/10000 [30:07<01:54,  5.27step/s, loss=0.052707, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9397/10000 [30:07<01:54,  5.27step/s, loss=0.057013, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9398/10000 [30:07<01:54,  5.27step/s, loss=0.057013, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9398/10000 [30:07<01:54,  5.27step/s, loss=0.046290, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9399/10000 [30:07<01:54,  5.26step/s, loss=0.046290, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9399/10000 [30:07<01:54,  5.26step/s, loss=0.041783, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9400/10000 [30:07<01:53,  5.27step/s, loss=0.041783, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9400/10000 [30:07<01:53,  5.27step/s, loss=0.027259, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9400/10000 [30:07<01:53,  5.27step/s, loss=0.027259, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9401/10000 [30:07<01:54,  5.21step/s, loss=0.027259, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9401/10000 [30:07<01:54,  5.21step/s, loss=0.060200, elapsed=30.1min]

Step 9400/10000 | Train loss: 0.027259 | Elapsed: 30.1min | ETA: 1.9min

Entraînement:  94%|█████████▍| 9402/10000 [30:08<01:54,  5.20step/s, loss=0.060200, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9402/10000 [30:08<01:54,  5.20step/s, loss=0.017260, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9403/10000 [30:08<01:54,  5.21step/s, loss=0.017260, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9403/10000 [30:08<01:54,  5.21step/s, loss=0.068007, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9404/10000 [30:08<01:54,  5.22step/s, loss=0.068007, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9404/10000 [30:08<01:54,  5.22step/s, loss=0.049084, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9405/10000 [30:08<01:54,  5.20step/s, loss=0.049084, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9405/10000 [30:08<01:54,  5.20step/s, loss=0.090192, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9406/10000 [30:08<01:54,  5.20step/s, loss=0.090192, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9406/10000 [30:08<01:54,  5.20step/s, loss=0.047807, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9407/10000 [30:09<01:54,  5.19step/s, loss=0.047807, elapsed=30.1min]

Entraînement:  94%|█████████▍| 9407/10000 [30:09<01:54,  5.19step/s, loss=0.075809, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9408/10000 [30:09<01:54,  5.18step/s, loss=0.075809, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9408/10000 [30:09<01:54,  5.18step/s, loss=0.069314, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9409/10000 [30:09<01:53,  5.20step/s, loss=0.069314, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9409/10000 [30:09<01:53,  5.20step/s, loss=0.035506, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9410/10000 [30:09<01:53,  5.20step/s, loss=0.035506, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9410/10000 [30:09<01:53,  5.20step/s, loss=0.030849, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9411/10000 [30:09<01:53,  5.21step/s, loss=0.030849, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9411/10000 [30:09<01:53,  5.21step/s, loss=0.036310, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9412/10000 [30:10<01:52,  5.22step/s, loss=0.036310, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9412/10000 [30:10<01:52,  5.22step/s, loss=0.100624, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9413/10000 [30:10<01:52,  5.20step/s, loss=0.100624, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9413/10000 [30:10<01:52,  5.20step/s, loss=0.033628, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9414/10000 [30:10<01:52,  5.20step/s, loss=0.033628, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9414/10000 [30:10<01:52,  5.20step/s, loss=0.101781, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9415/10000 [30:10<01:52,  5.22step/s, loss=0.101781, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9415/10000 [30:10<01:52,  5.22step/s, loss=0.040602, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9416/10000 [30:10<01:51,  5.24step/s, loss=0.040602, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9416/10000 [30:10<01:51,  5.24step/s, loss=0.045613, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9417/10000 [30:11<01:50,  5.26step/s, loss=0.045613, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9417/10000 [30:11<01:50,  5.26step/s, loss=0.050126, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9418/10000 [30:11<01:50,  5.27step/s, loss=0.050126, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9418/10000 [30:11<01:50,  5.27step/s, loss=0.036771, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9419/10000 [30:11<01:50,  5.27step/s, loss=0.036771, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9419/10000 [30:11<01:50,  5.27step/s, loss=0.024259, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9420/10000 [30:11<01:49,  5.28step/s, loss=0.024259, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9420/10000 [30:11<01:49,  5.28step/s, loss=0.043999, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9421/10000 [30:11<01:49,  5.28step/s, loss=0.043999, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9421/10000 [30:11<01:49,  5.28step/s, loss=0.031910, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9422/10000 [30:11<01:49,  5.28step/s, loss=0.031910, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9422/10000 [30:11<01:49,  5.28step/s, loss=0.050551, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9423/10000 [30:12<01:49,  5.28step/s, loss=0.050551, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9423/10000 [30:12<01:49,  5.28step/s, loss=0.062079, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9424/10000 [30:12<01:49,  5.28step/s, loss=0.062079, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9424/10000 [30:12<01:49,  5.28step/s, loss=0.033481, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9425/10000 [30:12<01:48,  5.29step/s, loss=0.033481, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9425/10000 [30:12<01:48,  5.29step/s, loss=0.091052, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9426/10000 [30:12<01:48,  5.31step/s, loss=0.091052, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9426/10000 [30:12<01:48,  5.31step/s, loss=0.071689, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9427/10000 [30:12<01:48,  5.29step/s, loss=0.071689, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9427/10000 [30:12<01:48,  5.29step/s, loss=0.046821, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9428/10000 [30:13<01:48,  5.27step/s, loss=0.046821, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9428/10000 [30:13<01:48,  5.27step/s, loss=0.027848, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9429/10000 [30:13<01:48,  5.26step/s, loss=0.027848, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9429/10000 [30:13<01:48,  5.26step/s, loss=0.081123, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9430/10000 [30:13<01:48,  5.26step/s, loss=0.081123, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9430/10000 [30:13<01:48,  5.26step/s, loss=0.042613, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9431/10000 [30:13<01:48,  5.26step/s, loss=0.042613, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9431/10000 [30:13<01:48,  5.26step/s, loss=0.035348, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9432/10000 [30:13<01:48,  5.24step/s, loss=0.035348, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9432/10000 [30:13<01:48,  5.24step/s, loss=0.026013, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9433/10000 [30:14<01:47,  5.25step/s, loss=0.026013, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9433/10000 [30:14<01:47,  5.25step/s, loss=0.029494, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9434/10000 [30:14<01:47,  5.25step/s, loss=0.029494, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9434/10000 [30:14<01:47,  5.25step/s, loss=0.023334, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9435/10000 [30:14<01:47,  5.23step/s, loss=0.023334, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9435/10000 [30:14<01:47,  5.23step/s, loss=0.067540, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9436/10000 [30:14<01:47,  5.23step/s, loss=0.067540, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9436/10000 [30:14<01:47,  5.23step/s, loss=0.027621, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9437/10000 [30:14<01:47,  5.24step/s, loss=0.027621, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9437/10000 [30:14<01:47,  5.24step/s, loss=0.039194, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9438/10000 [30:15<01:47,  5.24step/s, loss=0.039194, elapsed=30.2min]

Entraînement:  94%|█████████▍| 9438/10000 [30:15<01:47,  5.24step/s, loss=0.045285, elapsed=30.3min]

Entraînement:  94%|█████████▍| 9439/10000 [30:15<01:46,  5.25step/s, loss=0.045285, elapsed=30.3min]

Entraînement:  94%|█████████▍| 9439/10000 [30:15<01:46,  5.25step/s, loss=0.134275, elapsed=30.3min]

Entraînement:  94%|█████████▍| 9440/10000 [30:15<01:46,  5.26step/s, loss=0.134275, elapsed=30.3min]

Entraînement:  94%|█████████▍| 9440/10000 [30:15<01:46,  5.26step/s, loss=0.026753, elapsed=30.3min]

Entraînement:  94%|█████████▍| 9441/10000 [30:15<01:46,  5.26step/s, loss=0.026753, elapsed=30.3min]

Entraînement:  94%|█████████▍| 9441/10000 [30:15<01:46,  5.26step/s, loss=0.032941, elapsed=30.3min]

Entraînement:  94%|█████████▍| 9442/10000 [30:15<01:46,  5.26step/s, loss=0.032941, elapsed=30.3min]

Entraînement:  94%|█████████▍| 9442/10000 [30:15<01:46,  5.26step/s, loss=0.018849, elapsed=30.3min]

Entraînement:  94%|█████████▍| 9443/10000 [30:15<01:45,  5.27step/s, loss=0.018849, elapsed=30.3min]

Entraînement:  94%|█████████▍| 9443/10000 [30:15<01:45,  5.27step/s, loss=0.062041, elapsed=30.3min]

Entraînement:  94%|█████████▍| 9444/10000 [30:16<01:45,  5.26step/s, loss=0.062041, elapsed=30.3min]

Entraînement:  94%|█████████▍| 9444/10000 [30:16<01:45,  5.26step/s, loss=0.037996, elapsed=30.3min]

Entraînement:  94%|█████████▍| 9445/10000 [30:16<01:45,  5.27step/s, loss=0.037996, elapsed=30.3min]

Entraînement:  94%|█████████▍| 9445/10000 [30:16<01:45,  5.27step/s, loss=0.023519, elapsed=30.3min]

Entraînement:  94%|█████████▍| 9446/10000 [30:16<01:45,  5.26step/s, loss=0.023519, elapsed=30.3min]

Entraînement:  94%|█████████▍| 9446/10000 [30:16<01:45,  5.26step/s, loss=0.028770, elapsed=30.3min]

Entraînement:  94%|█████████▍| 9447/10000 [30:16<01:45,  5.26step/s, loss=0.028770, elapsed=30.3min]

Entraînement:  94%|█████████▍| 9447/10000 [30:16<01:45,  5.26step/s, loss=0.054680, elapsed=30.3min]

Entraînement:  94%|█████████▍| 9448/10000 [30:16<01:44,  5.26step/s, loss=0.054680, elapsed=30.3min]

Entraînement:  94%|█████████▍| 9448/10000 [30:16<01:44,  5.26step/s, loss=0.053440, elapsed=30.3min]

Entraînement:  94%|█████████▍| 9449/10000 [30:17<01:44,  5.26step/s, loss=0.053440, elapsed=30.3min]

Entraînement:  94%|█████████▍| 9449/10000 [30:17<01:44,  5.26step/s, loss=0.022767, elapsed=30.3min]

Entraînement:  94%|█████████▍| 9450/10000 [30:17<01:44,  5.25step/s, loss=0.022767, elapsed=30.3min]

Entraînement:  94%|█████████▍| 9450/10000 [30:17<01:44,  5.25step/s, loss=0.037037, elapsed=30.3min]

Entraînement:  95%|█████████▍| 9451/10000 [30:17<01:44,  5.24step/s, loss=0.037037, elapsed=30.3min]

Entraînement:  95%|█████████▍| 9451/10000 [30:17<01:44,  5.24step/s, loss=0.118900, elapsed=30.3min]

Entraînement:  95%|█████████▍| 9452/10000 [30:17<01:44,  5.24step/s, loss=0.118900, elapsed=30.3min]

Entraînement:  95%|█████████▍| 9452/10000 [30:17<01:44,  5.24step/s, loss=0.032208, elapsed=30.3min]

Entraînement:  95%|█████████▍| 9453/10000 [30:17<01:45,  5.21step/s, loss=0.032208, elapsed=30.3min]

Entraînement:  95%|█████████▍| 9453/10000 [30:17<01:45,  5.21step/s, loss=0.030981, elapsed=30.3min]

Entraînement:  95%|█████████▍| 9454/10000 [30:18<01:44,  5.23step/s, loss=0.030981, elapsed=30.3min]

Entraînement:  95%|█████████▍| 9454/10000 [30:18<01:44,  5.23step/s, loss=0.037747, elapsed=30.3min]

Entraînement:  95%|█████████▍| 9455/10000 [30:18<01:43,  5.25step/s, loss=0.037747, elapsed=30.3min]

Entraînement:  95%|█████████▍| 9455/10000 [30:18<01:43,  5.25step/s, loss=0.026068, elapsed=30.3min]

Entraînement:  95%|█████████▍| 9456/10000 [30:18<01:43,  5.27step/s, loss=0.026068, elapsed=30.3min]

Entraînement:  95%|█████████▍| 9456/10000 [30:18<01:43,  5.27step/s, loss=0.027785, elapsed=30.3min]

Entraînement:  95%|█████████▍| 9457/10000 [30:18<01:43,  5.27step/s, loss=0.027785, elapsed=30.3min]

Entraînement:  95%|█████████▍| 9457/10000 [30:18<01:43,  5.27step/s, loss=0.060285, elapsed=30.3min]

Entraînement:  95%|█████████▍| 9458/10000 [30:18<01:42,  5.27step/s, loss=0.060285, elapsed=30.3min]

Entraînement:  95%|█████████▍| 9458/10000 [30:18<01:42,  5.27step/s, loss=0.025950, elapsed=30.3min]

Entraînement:  95%|█████████▍| 9459/10000 [30:19<01:42,  5.27step/s, loss=0.025950, elapsed=30.3min]

Entraînement:  95%|█████████▍| 9459/10000 [30:19<01:42,  5.27step/s, loss=0.028312, elapsed=30.3min]

Entraînement:  95%|█████████▍| 9460/10000 [30:19<01:42,  5.26step/s, loss=0.028312, elapsed=30.3min]

Entraînement:  95%|█████████▍| 9460/10000 [30:19<01:42,  5.26step/s, loss=0.121276, elapsed=30.3min]

Entraînement:  95%|█████████▍| 9461/10000 [30:19<01:42,  5.26step/s, loss=0.121276, elapsed=30.3min]

Entraînement:  95%|█████████▍| 9461/10000 [30:19<01:42,  5.26step/s, loss=0.041326, elapsed=30.3min]

Entraînement:  95%|█████████▍| 9462/10000 [30:19<01:42,  5.27step/s, loss=0.041326, elapsed=30.3min]

Entraînement:  95%|█████████▍| 9462/10000 [30:19<01:42,  5.27step/s, loss=0.042158, elapsed=30.3min]

Entraînement:  95%|█████████▍| 9463/10000 [30:19<01:41,  5.28step/s, loss=0.042158, elapsed=30.3min]

Entraînement:  95%|█████████▍| 9463/10000 [30:19<01:41,  5.28step/s, loss=0.025847, elapsed=30.3min]

Entraînement:  95%|█████████▍| 9464/10000 [30:19<01:41,  5.27step/s, loss=0.025847, elapsed=30.3min]

Entraînement:  95%|█████████▍| 9464/10000 [30:19<01:41,  5.27step/s, loss=0.031936, elapsed=30.3min]

Entraînement:  95%|█████████▍| 9465/10000 [30:20<01:41,  5.26step/s, loss=0.031936, elapsed=30.3min]

Entraînement:  95%|█████████▍| 9465/10000 [30:20<01:41,  5.26step/s, loss=0.020134, elapsed=30.3min]

Entraînement:  95%|█████████▍| 9466/10000 [30:20<01:41,  5.26step/s, loss=0.020134, elapsed=30.3min]

Entraînement:  95%|█████████▍| 9466/10000 [30:20<01:41,  5.26step/s, loss=0.025987, elapsed=30.3min]

Entraînement:  95%|█████████▍| 9467/10000 [30:20<01:41,  5.25step/s, loss=0.025987, elapsed=30.3min]

Entraînement:  95%|█████████▍| 9467/10000 [30:20<01:41,  5.25step/s, loss=0.028508, elapsed=30.3min]

Entraînement:  95%|█████████▍| 9468/10000 [30:20<01:41,  5.25step/s, loss=0.028508, elapsed=30.3min]

Entraînement:  95%|█████████▍| 9468/10000 [30:20<01:41,  5.25step/s, loss=0.043838, elapsed=30.3min]

Entraînement:  95%|█████████▍| 9469/10000 [30:20<01:40,  5.26step/s, loss=0.043838, elapsed=30.3min]

Entraînement:  95%|█████████▍| 9469/10000 [30:20<01:40,  5.26step/s, loss=0.065079, elapsed=30.3min]

Entraînement:  95%|█████████▍| 9470/10000 [30:21<01:40,  5.27step/s, loss=0.065079, elapsed=30.3min]

Entraînement:  95%|█████████▍| 9470/10000 [30:21<01:40,  5.27step/s, loss=0.048752, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9471/10000 [30:21<01:40,  5.27step/s, loss=0.048752, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9471/10000 [30:21<01:40,  5.27step/s, loss=0.030109, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9472/10000 [30:21<01:40,  5.27step/s, loss=0.030109, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9472/10000 [30:21<01:40,  5.27step/s, loss=0.046466, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9473/10000 [30:21<01:40,  5.26step/s, loss=0.046466, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9473/10000 [30:21<01:40,  5.26step/s, loss=0.132373, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9474/10000 [30:21<01:40,  5.26step/s, loss=0.132373, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9474/10000 [30:21<01:40,  5.26step/s, loss=0.022985, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9475/10000 [30:22<01:39,  5.26step/s, loss=0.022985, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9475/10000 [30:22<01:39,  5.26step/s, loss=0.064539, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9476/10000 [30:22<01:39,  5.26step/s, loss=0.064539, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9476/10000 [30:22<01:39,  5.26step/s, loss=0.017338, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9477/10000 [30:22<01:39,  5.26step/s, loss=0.017338, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9477/10000 [30:22<01:39,  5.26step/s, loss=0.030852, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9478/10000 [30:22<01:39,  5.25step/s, loss=0.030852, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9478/10000 [30:22<01:39,  5.25step/s, loss=0.024793, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9479/10000 [30:22<01:39,  5.25step/s, loss=0.024793, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9479/10000 [30:22<01:39,  5.25step/s, loss=0.035444, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9480/10000 [30:23<01:39,  5.24step/s, loss=0.035444, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9480/10000 [30:23<01:39,  5.24step/s, loss=0.061483, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9481/10000 [30:23<01:38,  5.25step/s, loss=0.061483, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9481/10000 [30:23<01:38,  5.25step/s, loss=0.059590, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9482/10000 [30:23<01:38,  5.25step/s, loss=0.059590, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9482/10000 [30:23<01:38,  5.25step/s, loss=0.078682, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9483/10000 [30:23<01:38,  5.25step/s, loss=0.078682, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9483/10000 [30:23<01:38,  5.25step/s, loss=0.030419, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9484/10000 [30:23<01:38,  5.26step/s, loss=0.030419, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9484/10000 [30:23<01:38,  5.26step/s, loss=0.023327, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9485/10000 [30:23<01:37,  5.26step/s, loss=0.023327, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9485/10000 [30:23<01:37,  5.26step/s, loss=0.130375, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9486/10000 [30:24<01:37,  5.27step/s, loss=0.130375, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9486/10000 [30:24<01:37,  5.27step/s, loss=0.036098, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9487/10000 [30:24<01:37,  5.26step/s, loss=0.036098, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9487/10000 [30:24<01:37,  5.26step/s, loss=0.033165, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9488/10000 [30:24<01:37,  5.26step/s, loss=0.033165, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9488/10000 [30:24<01:37,  5.26step/s, loss=0.040110, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9489/10000 [30:24<01:37,  5.26step/s, loss=0.040110, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9489/10000 [30:24<01:37,  5.26step/s, loss=0.035899, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9490/10000 [30:24<01:36,  5.26step/s, loss=0.035899, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9490/10000 [30:24<01:36,  5.26step/s, loss=0.114898, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9491/10000 [30:25<01:36,  5.27step/s, loss=0.114898, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9491/10000 [30:25<01:36,  5.27step/s, loss=0.082427, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9492/10000 [30:25<01:36,  5.27step/s, loss=0.082427, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9492/10000 [30:25<01:36,  5.27step/s, loss=0.022965, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9493/10000 [30:25<01:36,  5.27step/s, loss=0.022965, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9493/10000 [30:25<01:36,  5.27step/s, loss=0.040234, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9494/10000 [30:25<01:35,  5.27step/s, loss=0.040234, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9494/10000 [30:25<01:35,  5.27step/s, loss=0.071918, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9495/10000 [30:25<01:35,  5.27step/s, loss=0.071918, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9495/10000 [30:25<01:35,  5.27step/s, loss=0.070684, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9496/10000 [30:26<01:35,  5.26step/s, loss=0.070684, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9496/10000 [30:26<01:35,  5.26step/s, loss=0.028856, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9497/10000 [30:26<01:35,  5.26step/s, loss=0.028856, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9497/10000 [30:26<01:35,  5.26step/s, loss=0.051982, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9498/10000 [30:26<01:35,  5.27step/s, loss=0.051982, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9498/10000 [30:26<01:35,  5.27step/s, loss=0.032534, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9499/10000 [30:26<01:35,  5.27step/s, loss=0.032534, elapsed=30.4min]

Entraînement:  95%|█████████▍| 9499/10000 [30:26<01:35,  5.27step/s, loss=0.030774, elapsed=30.4min]

Entraînement:  95%|█████████▌| 9500/10000 [30:26<01:34,  5.28step/s, loss=0.030774, elapsed=30.4min]

Entraînement:  95%|█████████▌| 9500/10000 [30:26<01:34,  5.28step/s, loss=0.066999, elapsed=30.4min]

Entraînement:  95%|█████████▌| 9500/10000 [30:26<01:34,  5.28step/s, loss=0.066999, elapsed=30.4min]

Entraînement:  95%|█████████▌| 9501/10000 [30:27<01:35,  5.22step/s, loss=0.066999, elapsed=30.4min]

Entraînement:  95%|█████████▌| 9501/10000 [30:27<01:35,  5.22step/s, loss=0.036938, elapsed=30.5min]

Step 9500/10000 | Train loss: 0.066999 | Elapsed: 30.4min | ETA: 1.6min

Entraînement:  95%|█████████▌| 9502/10000 [30:27<01:35,  5.23step/s, loss=0.036938, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9502/10000 [30:27<01:35,  5.23step/s, loss=0.025414, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9503/10000 [30:27<01:34,  5.24step/s, loss=0.025414, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9503/10000 [30:27<01:34,  5.24step/s, loss=0.015918, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9504/10000 [30:27<01:34,  5.25step/s, loss=0.015918, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9504/10000 [30:27<01:34,  5.25step/s, loss=0.053650, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9505/10000 [30:27<01:34,  5.25step/s, loss=0.053650, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9505/10000 [30:27<01:34,  5.25step/s, loss=0.104860, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9506/10000 [30:27<01:33,  5.26step/s, loss=0.104860, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9506/10000 [30:27<01:33,  5.26step/s, loss=0.030917, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9507/10000 [30:28<01:33,  5.27step/s, loss=0.030917, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9507/10000 [30:28<01:33,  5.27step/s, loss=0.053738, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9508/10000 [30:28<01:33,  5.27step/s, loss=0.053738, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9508/10000 [30:28<01:33,  5.27step/s, loss=0.033532, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9509/10000 [30:28<01:33,  5.27step/s, loss=0.033532, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9509/10000 [30:28<01:33,  5.27step/s, loss=0.032120, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9510/10000 [30:28<01:33,  5.27step/s, loss=0.032120, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9510/10000 [30:28<01:33,  5.27step/s, loss=0.028859, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9511/10000 [30:28<01:32,  5.27step/s, loss=0.028859, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9511/10000 [30:28<01:32,  5.27step/s, loss=0.029573, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9512/10000 [30:29<01:32,  5.27step/s, loss=0.029573, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9512/10000 [30:29<01:32,  5.27step/s, loss=0.097765, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9513/10000 [30:29<01:32,  5.27step/s, loss=0.097765, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9513/10000 [30:29<01:32,  5.27step/s, loss=0.071359, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9514/10000 [30:29<01:32,  5.27step/s, loss=0.071359, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9514/10000 [30:29<01:32,  5.27step/s, loss=0.026208, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9515/10000 [30:29<01:31,  5.28step/s, loss=0.026208, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9515/10000 [30:29<01:31,  5.28step/s, loss=0.039973, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9516/10000 [30:29<01:31,  5.28step/s, loss=0.039973, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9516/10000 [30:29<01:31,  5.28step/s, loss=0.036662, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9517/10000 [30:30<01:31,  5.28step/s, loss=0.036662, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9517/10000 [30:30<01:31,  5.28step/s, loss=0.037723, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9518/10000 [30:30<01:31,  5.26step/s, loss=0.037723, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9518/10000 [30:30<01:31,  5.26step/s, loss=0.053688, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9519/10000 [30:30<01:31,  5.25step/s, loss=0.053688, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9519/10000 [30:30<01:31,  5.25step/s, loss=0.061473, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9520/10000 [30:30<01:31,  5.25step/s, loss=0.061473, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9520/10000 [30:30<01:31,  5.25step/s, loss=0.052333, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9521/10000 [30:30<01:31,  5.24step/s, loss=0.052333, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9521/10000 [30:30<01:31,  5.24step/s, loss=0.136122, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9522/10000 [30:31<01:31,  5.25step/s, loss=0.136122, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9522/10000 [30:31<01:31,  5.25step/s, loss=0.034804, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9523/10000 [30:31<01:30,  5.25step/s, loss=0.034804, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9523/10000 [30:31<01:30,  5.25step/s, loss=0.050460, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9524/10000 [30:31<01:30,  5.26step/s, loss=0.050460, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9524/10000 [30:31<01:30,  5.26step/s, loss=0.053620, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9525/10000 [30:31<01:30,  5.26step/s, loss=0.053620, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9525/10000 [30:31<01:30,  5.26step/s, loss=0.030732, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9526/10000 [30:31<01:30,  5.26step/s, loss=0.030732, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9526/10000 [30:31<01:30,  5.26step/s, loss=0.039881, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9527/10000 [30:31<01:30,  5.23step/s, loss=0.039881, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9527/10000 [30:31<01:30,  5.23step/s, loss=0.053290, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9528/10000 [30:32<01:30,  5.23step/s, loss=0.053290, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9528/10000 [30:32<01:30,  5.23step/s, loss=0.034071, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9529/10000 [30:32<01:30,  5.23step/s, loss=0.034071, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9529/10000 [30:32<01:30,  5.23step/s, loss=0.030542, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9530/10000 [30:32<01:29,  5.24step/s, loss=0.030542, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9530/10000 [30:32<01:29,  5.24step/s, loss=0.047792, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9531/10000 [30:32<01:29,  5.23step/s, loss=0.047792, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9531/10000 [30:32<01:29,  5.23step/s, loss=0.093881, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9532/10000 [30:32<01:29,  5.23step/s, loss=0.093881, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9532/10000 [30:32<01:29,  5.23step/s, loss=0.038888, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9533/10000 [30:33<01:29,  5.22step/s, loss=0.038888, elapsed=30.5min]

Entraînement:  95%|█████████▌| 9533/10000 [30:33<01:29,  5.22step/s, loss=0.035952, elapsed=30.6min]

Entraînement:  95%|█████████▌| 9534/10000 [30:33<01:29,  5.22step/s, loss=0.035952, elapsed=30.6min]

Entraînement:  95%|█████████▌| 9534/10000 [30:33<01:29,  5.22step/s, loss=0.066816, elapsed=30.6min]

Entraînement:  95%|█████████▌| 9535/10000 [30:33<01:29,  5.22step/s, loss=0.066816, elapsed=30.6min]

Entraînement:  95%|█████████▌| 9535/10000 [30:33<01:29,  5.22step/s, loss=0.027537, elapsed=30.6min]

Entraînement:  95%|█████████▌| 9536/10000 [30:33<01:28,  5.23step/s, loss=0.027537, elapsed=30.6min]

Entraînement:  95%|█████████▌| 9536/10000 [30:33<01:28,  5.23step/s, loss=0.110522, elapsed=30.6min]

Entraînement:  95%|█████████▌| 9537/10000 [30:33<01:28,  5.24step/s, loss=0.110522, elapsed=30.6min]

Entraînement:  95%|█████████▌| 9537/10000 [30:33<01:28,  5.24step/s, loss=0.102334, elapsed=30.6min]

Entraînement:  95%|█████████▌| 9538/10000 [30:34<01:28,  5.24step/s, loss=0.102334, elapsed=30.6min]

Entraînement:  95%|█████████▌| 9538/10000 [30:34<01:28,  5.24step/s, loss=0.012926, elapsed=30.6min]

Entraînement:  95%|█████████▌| 9539/10000 [30:34<01:27,  5.25step/s, loss=0.012926, elapsed=30.6min]

Entraînement:  95%|█████████▌| 9539/10000 [30:34<01:27,  5.25step/s, loss=0.034043, elapsed=30.6min]

Entraînement:  95%|█████████▌| 9540/10000 [30:34<01:27,  5.25step/s, loss=0.034043, elapsed=30.6min]

Entraînement:  95%|█████████▌| 9540/10000 [30:34<01:27,  5.25step/s, loss=0.023359, elapsed=30.6min]

Entraînement:  95%|█████████▌| 9541/10000 [30:34<01:27,  5.25step/s, loss=0.023359, elapsed=30.6min]

Entraînement:  95%|█████████▌| 9541/10000 [30:34<01:27,  5.25step/s, loss=0.079172, elapsed=30.6min]

Entraînement:  95%|█████████▌| 9542/10000 [30:34<01:27,  5.22step/s, loss=0.079172, elapsed=30.6min]

Entraînement:  95%|█████████▌| 9542/10000 [30:34<01:27,  5.22step/s, loss=0.117058, elapsed=30.6min]

Entraînement:  95%|█████████▌| 9543/10000 [30:35<01:27,  5.22step/s, loss=0.117058, elapsed=30.6min]

Entraînement:  95%|█████████▌| 9543/10000 [30:35<01:27,  5.22step/s, loss=0.095559, elapsed=30.6min]

Entraînement:  95%|█████████▌| 9544/10000 [30:35<01:27,  5.23step/s, loss=0.095559, elapsed=30.6min]

Entraînement:  95%|█████████▌| 9544/10000 [30:35<01:27,  5.23step/s, loss=0.059518, elapsed=30.6min]

Entraînement:  95%|█████████▌| 9545/10000 [30:35<01:26,  5.23step/s, loss=0.059518, elapsed=30.6min]

Entraînement:  95%|█████████▌| 9545/10000 [30:35<01:26,  5.23step/s, loss=0.044968, elapsed=30.6min]

Entraînement:  95%|█████████▌| 9546/10000 [30:35<01:26,  5.24step/s, loss=0.044968, elapsed=30.6min]

Entraînement:  95%|█████████▌| 9546/10000 [30:35<01:26,  5.24step/s, loss=0.032360, elapsed=30.6min]

Entraînement:  95%|█████████▌| 9547/10000 [30:35<01:26,  5.23step/s, loss=0.032360, elapsed=30.6min]

Entraînement:  95%|█████████▌| 9547/10000 [30:35<01:26,  5.23step/s, loss=0.098572, elapsed=30.6min]

Entraînement:  95%|█████████▌| 9548/10000 [30:35<01:26,  5.22step/s, loss=0.098572, elapsed=30.6min]

Entraînement:  95%|█████████▌| 9548/10000 [30:35<01:26,  5.22step/s, loss=0.032587, elapsed=30.6min]

Entraînement:  95%|█████████▌| 9549/10000 [30:36<01:26,  5.22step/s, loss=0.032587, elapsed=30.6min]

Entraînement:  95%|█████████▌| 9549/10000 [30:36<01:26,  5.22step/s, loss=0.037483, elapsed=30.6min]

Entraînement:  96%|█████████▌| 9550/10000 [30:36<01:26,  5.22step/s, loss=0.037483, elapsed=30.6min]

Entraînement:  96%|█████████▌| 9550/10000 [30:36<01:26,  5.22step/s, loss=0.020905, elapsed=30.6min]

Entraînement:  96%|█████████▌| 9551/10000 [30:36<01:25,  5.22step/s, loss=0.020905, elapsed=30.6min]

Entraînement:  96%|█████████▌| 9551/10000 [30:36<01:25,  5.22step/s, loss=0.066567, elapsed=30.6min]

Entraînement:  96%|█████████▌| 9552/10000 [30:36<01:25,  5.23step/s, loss=0.066567, elapsed=30.6min]

Entraînement:  96%|█████████▌| 9552/10000 [30:36<01:25,  5.23step/s, loss=0.039301, elapsed=30.6min]

Entraînement:  96%|█████████▌| 9553/10000 [30:36<01:25,  5.23step/s, loss=0.039301, elapsed=30.6min]

Entraînement:  96%|█████████▌| 9553/10000 [30:36<01:25,  5.23step/s, loss=0.025061, elapsed=30.6min]

Entraînement:  96%|█████████▌| 9554/10000 [30:37<01:25,  5.24step/s, loss=0.025061, elapsed=30.6min]

Entraînement:  96%|█████████▌| 9554/10000 [30:37<01:25,  5.24step/s, loss=0.045533, elapsed=30.6min]

Entraînement:  96%|█████████▌| 9555/10000 [30:37<01:25,  5.23step/s, loss=0.045533, elapsed=30.6min]

Entraînement:  96%|█████████▌| 9555/10000 [30:37<01:25,  5.23step/s, loss=0.025385, elapsed=30.6min]

Entraînement:  96%|█████████▌| 9556/10000 [30:37<01:24,  5.24step/s, loss=0.025385, elapsed=30.6min]

Entraînement:  96%|█████████▌| 9556/10000 [30:37<01:24,  5.24step/s, loss=0.033052, elapsed=30.6min]

Entraînement:  96%|█████████▌| 9557/10000 [30:37<01:24,  5.25step/s, loss=0.033052, elapsed=30.6min]

Entraînement:  96%|█████████▌| 9557/10000 [30:37<01:24,  5.25step/s, loss=0.013421, elapsed=30.6min]

Entraînement:  96%|█████████▌| 9558/10000 [30:37<01:24,  5.24step/s, loss=0.013421, elapsed=30.6min]

Entraînement:  96%|█████████▌| 9558/10000 [30:37<01:24,  5.24step/s, loss=0.026957, elapsed=30.6min]

Entraînement:  96%|█████████▌| 9559/10000 [30:38<01:23,  5.25step/s, loss=0.026957, elapsed=30.6min]

Entraînement:  96%|█████████▌| 9559/10000 [30:38<01:23,  5.25step/s, loss=0.029054, elapsed=30.6min]

Entraînement:  96%|█████████▌| 9560/10000 [30:38<01:23,  5.26step/s, loss=0.029054, elapsed=30.6min]

Entraînement:  96%|█████████▌| 9560/10000 [30:38<01:23,  5.26step/s, loss=0.056411, elapsed=30.6min]

Entraînement:  96%|█████████▌| 9561/10000 [30:38<01:23,  5.28step/s, loss=0.056411, elapsed=30.6min]

Entraînement:  96%|█████████▌| 9561/10000 [30:38<01:23,  5.28step/s, loss=0.069743, elapsed=30.6min]

Entraînement:  96%|█████████▌| 9562/10000 [30:38<01:22,  5.31step/s, loss=0.069743, elapsed=30.6min]

Entraînement:  96%|█████████▌| 9562/10000 [30:38<01:22,  5.31step/s, loss=0.031253, elapsed=30.6min]

Entraînement:  96%|█████████▌| 9563/10000 [30:38<01:22,  5.33step/s, loss=0.031253, elapsed=30.6min]

Entraînement:  96%|█████████▌| 9563/10000 [30:38<01:22,  5.33step/s, loss=0.080332, elapsed=30.6min]

Entraînement:  96%|█████████▌| 9564/10000 [30:39<01:21,  5.33step/s, loss=0.080332, elapsed=30.6min]

Entraînement:  96%|█████████▌| 9564/10000 [30:39<01:21,  5.33step/s, loss=0.018608, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9565/10000 [30:39<01:21,  5.33step/s, loss=0.018608, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9565/10000 [30:39<01:21,  5.33step/s, loss=0.064111, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9566/10000 [30:39<01:21,  5.35step/s, loss=0.064111, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9566/10000 [30:39<01:21,  5.35step/s, loss=0.024325, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9567/10000 [30:39<01:20,  5.35step/s, loss=0.024325, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9567/10000 [30:39<01:20,  5.35step/s, loss=0.075754, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9568/10000 [30:39<01:21,  5.33step/s, loss=0.075754, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9568/10000 [30:39<01:21,  5.33step/s, loss=0.029296, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9569/10000 [30:39<01:21,  5.31step/s, loss=0.029296, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9569/10000 [30:39<01:21,  5.31step/s, loss=0.062681, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9570/10000 [30:40<01:21,  5.30step/s, loss=0.062681, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9570/10000 [30:40<01:21,  5.30step/s, loss=0.026558, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9571/10000 [30:40<01:20,  5.30step/s, loss=0.026558, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9571/10000 [30:40<01:20,  5.30step/s, loss=0.030846, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9572/10000 [30:40<01:20,  5.29step/s, loss=0.030846, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9572/10000 [30:40<01:20,  5.29step/s, loss=0.030252, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9573/10000 [30:40<01:20,  5.30step/s, loss=0.030252, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9573/10000 [30:40<01:20,  5.30step/s, loss=0.050195, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9574/10000 [30:40<01:20,  5.29step/s, loss=0.050195, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9574/10000 [30:40<01:20,  5.29step/s, loss=0.037500, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9575/10000 [30:41<01:20,  5.29step/s, loss=0.037500, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9575/10000 [30:41<01:20,  5.29step/s, loss=0.020226, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9576/10000 [30:41<01:20,  5.30step/s, loss=0.020226, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9576/10000 [30:41<01:20,  5.30step/s, loss=0.131869, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9577/10000 [30:41<01:19,  5.30step/s, loss=0.131869, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9577/10000 [30:41<01:19,  5.30step/s, loss=0.020346, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9578/10000 [30:41<01:19,  5.30step/s, loss=0.020346, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9578/10000 [30:41<01:19,  5.30step/s, loss=0.023651, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9579/10000 [30:41<01:19,  5.30step/s, loss=0.023651, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9579/10000 [30:41<01:19,  5.30step/s, loss=0.038796, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9580/10000 [30:42<01:19,  5.29step/s, loss=0.038796, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9580/10000 [30:42<01:19,  5.29step/s, loss=0.044487, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9581/10000 [30:42<01:19,  5.27step/s, loss=0.044487, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9581/10000 [30:42<01:19,  5.27step/s, loss=0.065591, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9582/10000 [30:42<01:19,  5.26step/s, loss=0.065591, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9582/10000 [30:42<01:19,  5.26step/s, loss=0.044671, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9583/10000 [30:42<01:19,  5.25step/s, loss=0.044671, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9583/10000 [30:42<01:19,  5.25step/s, loss=0.048240, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9584/10000 [30:42<01:19,  5.24step/s, loss=0.048240, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9584/10000 [30:42<01:19,  5.24step/s, loss=0.031970, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9585/10000 [30:42<01:19,  5.25step/s, loss=0.031970, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9585/10000 [30:42<01:19,  5.25step/s, loss=0.054438, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9586/10000 [30:43<01:18,  5.26step/s, loss=0.054438, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9586/10000 [30:43<01:18,  5.26step/s, loss=0.068718, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9587/10000 [30:43<01:18,  5.26step/s, loss=0.068718, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9587/10000 [30:43<01:18,  5.26step/s, loss=0.031620, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9588/10000 [30:43<01:18,  5.26step/s, loss=0.031620, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9588/10000 [30:43<01:18,  5.26step/s, loss=0.019447, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9589/10000 [30:43<01:18,  5.26step/s, loss=0.019447, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9589/10000 [30:43<01:18,  5.26step/s, loss=0.030315, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9590/10000 [30:43<01:17,  5.26step/s, loss=0.030315, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9590/10000 [30:43<01:17,  5.26step/s, loss=0.137024, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9591/10000 [30:44<01:17,  5.27step/s, loss=0.137024, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9591/10000 [30:44<01:17,  5.27step/s, loss=0.050989, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9592/10000 [30:44<01:17,  5.27step/s, loss=0.050989, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9592/10000 [30:44<01:17,  5.27step/s, loss=0.035242, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9593/10000 [30:44<01:17,  5.27step/s, loss=0.035242, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9593/10000 [30:44<01:17,  5.27step/s, loss=0.023976, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9594/10000 [30:44<01:17,  5.27step/s, loss=0.023976, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9594/10000 [30:44<01:17,  5.27step/s, loss=0.024607, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9595/10000 [30:44<01:16,  5.27step/s, loss=0.024607, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9595/10000 [30:44<01:16,  5.27step/s, loss=0.050907, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9596/10000 [30:45<01:16,  5.27step/s, loss=0.050907, elapsed=30.7min]

Entraînement:  96%|█████████▌| 9596/10000 [30:45<01:16,  5.27step/s, loss=0.060900, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9597/10000 [30:45<01:16,  5.28step/s, loss=0.060900, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9597/10000 [30:45<01:16,  5.28step/s, loss=0.037919, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9598/10000 [30:45<01:16,  5.27step/s, loss=0.037919, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9598/10000 [30:45<01:16,  5.27step/s, loss=0.077622, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9599/10000 [30:45<01:15,  5.28step/s, loss=0.077622, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9599/10000 [30:45<01:15,  5.28step/s, loss=0.046189, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9600/10000 [30:45<01:15,  5.28step/s, loss=0.046189, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9600/10000 [30:45<01:15,  5.28step/s, loss=0.023754, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9600/10000 [30:45<01:15,  5.28step/s, loss=0.023754, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9601/10000 [30:46<01:16,  5.23step/s, loss=0.023754, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9601/10000 [30:46<01:16,  5.23step/s, loss=0.063018, elapsed=30.8min]

Step 9600/10000 | Train loss: 0.023754 | Elapsed: 30.8min | ETA: 1.3min

Entraînement:  96%|█████████▌| 9602/10000 [30:46<01:15,  5.25step/s, loss=0.063018, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9602/10000 [30:46<01:15,  5.25step/s, loss=0.079302, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9603/10000 [30:46<01:15,  5.24step/s, loss=0.079302, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9603/10000 [30:46<01:15,  5.24step/s, loss=0.036706, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9604/10000 [30:46<01:15,  5.25step/s, loss=0.036706, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9604/10000 [30:46<01:15,  5.25step/s, loss=0.054381, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9605/10000 [30:46<01:15,  5.25step/s, loss=0.054381, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9605/10000 [30:46<01:15,  5.25step/s, loss=0.030414, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9606/10000 [30:46<01:15,  5.25step/s, loss=0.030414, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9606/10000 [30:46<01:15,  5.25step/s, loss=0.021018, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9607/10000 [30:47<01:14,  5.26step/s, loss=0.021018, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9607/10000 [30:47<01:14,  5.26step/s, loss=0.091769, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9608/10000 [30:47<01:14,  5.26step/s, loss=0.091769, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9608/10000 [30:47<01:14,  5.26step/s, loss=0.024010, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9609/10000 [30:47<01:14,  5.26step/s, loss=0.024010, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9609/10000 [30:47<01:14,  5.26step/s, loss=0.037439, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9610/10000 [30:47<01:14,  5.25step/s, loss=0.037439, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9610/10000 [30:47<01:14,  5.25step/s, loss=0.118241, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9611/10000 [30:47<01:14,  5.25step/s, loss=0.118241, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9611/10000 [30:47<01:14,  5.25step/s, loss=0.029139, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9612/10000 [30:48<01:13,  5.24step/s, loss=0.029139, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9612/10000 [30:48<01:13,  5.24step/s, loss=0.061282, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9613/10000 [30:48<01:13,  5.25step/s, loss=0.061282, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9613/10000 [30:48<01:13,  5.25step/s, loss=0.024878, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9614/10000 [30:48<01:13,  5.27step/s, loss=0.024878, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9614/10000 [30:48<01:13,  5.27step/s, loss=0.034773, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9615/10000 [30:48<01:13,  5.26step/s, loss=0.034773, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9615/10000 [30:48<01:13,  5.26step/s, loss=0.036532, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9616/10000 [30:48<01:12,  5.27step/s, loss=0.036532, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9616/10000 [30:48<01:12,  5.27step/s, loss=0.036524, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9617/10000 [30:49<01:12,  5.27step/s, loss=0.036524, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9617/10000 [30:49<01:12,  5.27step/s, loss=0.019110, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9618/10000 [30:49<01:12,  5.25step/s, loss=0.019110, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9618/10000 [30:49<01:12,  5.25step/s, loss=0.085752, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9619/10000 [30:49<01:12,  5.25step/s, loss=0.085752, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9619/10000 [30:49<01:12,  5.25step/s, loss=0.034805, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9620/10000 [30:49<01:12,  5.26step/s, loss=0.034805, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9620/10000 [30:49<01:12,  5.26step/s, loss=0.032226, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9621/10000 [30:49<01:12,  5.25step/s, loss=0.032226, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9621/10000 [30:49<01:12,  5.25step/s, loss=0.099893, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9622/10000 [30:50<01:11,  5.26step/s, loss=0.099893, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9622/10000 [30:50<01:11,  5.26step/s, loss=0.040275, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9623/10000 [30:50<01:11,  5.25step/s, loss=0.040275, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9623/10000 [30:50<01:11,  5.25step/s, loss=0.063509, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9624/10000 [30:50<01:11,  5.26step/s, loss=0.063509, elapsed=30.8min]

Entraînement:  96%|█████████▌| 9624/10000 [30:50<01:11,  5.26step/s, loss=0.057188, elapsed=30.8min]

Entraînement:  96%|█████████▋| 9625/10000 [30:50<01:11,  5.26step/s, loss=0.057188, elapsed=30.8min]

Entraînement:  96%|█████████▋| 9625/10000 [30:50<01:11,  5.26step/s, loss=0.034691, elapsed=30.8min]

Entraînement:  96%|█████████▋| 9626/10000 [30:50<01:11,  5.26step/s, loss=0.034691, elapsed=30.8min]

Entraînement:  96%|█████████▋| 9626/10000 [30:50<01:11,  5.26step/s, loss=0.064227, elapsed=30.8min]

Entraînement:  96%|█████████▋| 9627/10000 [30:50<01:10,  5.26step/s, loss=0.064227, elapsed=30.8min]

Entraînement:  96%|█████████▋| 9627/10000 [30:50<01:10,  5.26step/s, loss=0.096490, elapsed=30.8min]

Entraînement:  96%|█████████▋| 9628/10000 [30:51<01:10,  5.26step/s, loss=0.096490, elapsed=30.8min]

Entraînement:  96%|█████████▋| 9628/10000 [30:51<01:10,  5.26step/s, loss=0.039867, elapsed=30.9min]

Entraînement:  96%|█████████▋| 9629/10000 [30:51<01:10,  5.26step/s, loss=0.039867, elapsed=30.9min]

Entraînement:  96%|█████████▋| 9629/10000 [30:51<01:10,  5.26step/s, loss=0.030970, elapsed=30.9min]

Entraînement:  96%|█████████▋| 9630/10000 [30:51<01:10,  5.27step/s, loss=0.030970, elapsed=30.9min]

Entraînement:  96%|█████████▋| 9630/10000 [30:51<01:10,  5.27step/s, loss=0.041465, elapsed=30.9min]

Entraînement:  96%|█████████▋| 9631/10000 [30:51<01:09,  5.27step/s, loss=0.041465, elapsed=30.9min]

Entraînement:  96%|█████████▋| 9631/10000 [30:51<01:09,  5.27step/s, loss=0.027095, elapsed=30.9min]

Entraînement:  96%|█████████▋| 9632/10000 [30:51<01:09,  5.28step/s, loss=0.027095, elapsed=30.9min]

Entraînement:  96%|█████████▋| 9632/10000 [30:51<01:09,  5.28step/s, loss=0.048387, elapsed=30.9min]

Entraînement:  96%|█████████▋| 9633/10000 [30:52<01:09,  5.28step/s, loss=0.048387, elapsed=30.9min]

Entraînement:  96%|█████████▋| 9633/10000 [30:52<01:09,  5.28step/s, loss=0.036328, elapsed=30.9min]

Entraînement:  96%|█████████▋| 9634/10000 [30:52<01:09,  5.28step/s, loss=0.036328, elapsed=30.9min]

Entraînement:  96%|█████████▋| 9634/10000 [30:52<01:09,  5.28step/s, loss=0.046614, elapsed=30.9min]

Entraînement:  96%|█████████▋| 9635/10000 [30:52<01:09,  5.28step/s, loss=0.046614, elapsed=30.9min]

Entraînement:  96%|█████████▋| 9635/10000 [30:52<01:09,  5.28step/s, loss=0.038605, elapsed=30.9min]

Entraînement:  96%|█████████▋| 9636/10000 [30:52<01:08,  5.31step/s, loss=0.038605, elapsed=30.9min]

Entraînement:  96%|█████████▋| 9636/10000 [30:52<01:08,  5.31step/s, loss=0.031461, elapsed=30.9min]

Entraînement:  96%|█████████▋| 9637/10000 [30:52<01:08,  5.33step/s, loss=0.031461, elapsed=30.9min]

Entraînement:  96%|█████████▋| 9637/10000 [30:52<01:08,  5.33step/s, loss=0.039886, elapsed=30.9min]

Entraînement:  96%|█████████▋| 9638/10000 [30:53<01:07,  5.33step/s, loss=0.039886, elapsed=30.9min]

Entraînement:  96%|█████████▋| 9638/10000 [30:53<01:07,  5.33step/s, loss=0.066500, elapsed=30.9min]

Entraînement:  96%|█████████▋| 9639/10000 [30:53<01:07,  5.34step/s, loss=0.066500, elapsed=30.9min]

Entraînement:  96%|█████████▋| 9639/10000 [30:53<01:07,  5.34step/s, loss=0.047172, elapsed=30.9min]

Entraînement:  96%|█████████▋| 9640/10000 [30:53<01:07,  5.34step/s, loss=0.047172, elapsed=30.9min]

Entraînement:  96%|█████████▋| 9640/10000 [30:53<01:07,  5.34step/s, loss=0.032613, elapsed=30.9min]

Entraînement:  96%|█████████▋| 9641/10000 [30:53<01:07,  5.34step/s, loss=0.032613, elapsed=30.9min]

Entraînement:  96%|█████████▋| 9641/10000 [30:53<01:07,  5.34step/s, loss=0.029080, elapsed=30.9min]

Entraînement:  96%|█████████▋| 9642/10000 [30:53<01:06,  5.35step/s, loss=0.029080, elapsed=30.9min]

Entraînement:  96%|█████████▋| 9642/10000 [30:53<01:06,  5.35step/s, loss=0.059529, elapsed=30.9min]

Entraînement:  96%|█████████▋| 9643/10000 [30:53<01:06,  5.36step/s, loss=0.059529, elapsed=30.9min]

Entraînement:  96%|█████████▋| 9643/10000 [30:53<01:06,  5.36step/s, loss=0.019683, elapsed=30.9min]

Entraînement:  96%|█████████▋| 9644/10000 [30:54<01:06,  5.36step/s, loss=0.019683, elapsed=30.9min]

Entraînement:  96%|█████████▋| 9644/10000 [30:54<01:06,  5.36step/s, loss=0.036541, elapsed=30.9min]

Entraînement:  96%|█████████▋| 9645/10000 [30:54<01:06,  5.33step/s, loss=0.036541, elapsed=30.9min]

Entraînement:  96%|█████████▋| 9645/10000 [30:54<01:06,  5.33step/s, loss=0.050234, elapsed=30.9min]

Entraînement:  96%|█████████▋| 9646/10000 [30:54<01:06,  5.31step/s, loss=0.050234, elapsed=30.9min]

Entraînement:  96%|█████████▋| 9646/10000 [30:54<01:06,  5.31step/s, loss=0.105374, elapsed=30.9min]

Entraînement:  96%|█████████▋| 9647/10000 [30:54<01:06,  5.30step/s, loss=0.105374, elapsed=30.9min]

Entraînement:  96%|█████████▋| 9647/10000 [30:54<01:06,  5.30step/s, loss=0.029618, elapsed=30.9min]

Entraînement:  96%|█████████▋| 9648/10000 [30:54<01:06,  5.28step/s, loss=0.029618, elapsed=30.9min]

Entraînement:  96%|█████████▋| 9648/10000 [30:54<01:06,  5.28step/s, loss=0.070147, elapsed=30.9min]

Entraînement:  96%|█████████▋| 9649/10000 [30:55<01:06,  5.29step/s, loss=0.070147, elapsed=30.9min]

Entraînement:  96%|█████████▋| 9649/10000 [30:55<01:06,  5.29step/s, loss=0.032180, elapsed=30.9min]

Entraînement:  96%|█████████▋| 9650/10000 [30:55<01:06,  5.28step/s, loss=0.032180, elapsed=30.9min]

Entraînement:  96%|█████████▋| 9650/10000 [30:55<01:06,  5.28step/s, loss=0.048845, elapsed=30.9min]

Entraînement:  97%|█████████▋| 9651/10000 [30:55<01:06,  5.28step/s, loss=0.048845, elapsed=30.9min]

Entraînement:  97%|█████████▋| 9651/10000 [30:55<01:06,  5.28step/s, loss=0.049359, elapsed=30.9min]

Entraînement:  97%|█████████▋| 9652/10000 [30:55<01:05,  5.28step/s, loss=0.049359, elapsed=30.9min]

Entraînement:  97%|█████████▋| 9652/10000 [30:55<01:05,  5.28step/s, loss=0.022112, elapsed=30.9min]

Entraînement:  97%|█████████▋| 9653/10000 [30:55<01:05,  5.29step/s, loss=0.022112, elapsed=30.9min]

Entraînement:  97%|█████████▋| 9653/10000 [30:55<01:05,  5.29step/s, loss=0.061317, elapsed=30.9min]

Entraînement:  97%|█████████▋| 9654/10000 [30:56<01:05,  5.29step/s, loss=0.061317, elapsed=30.9min]

Entraînement:  97%|█████████▋| 9654/10000 [30:56<01:05,  5.29step/s, loss=0.020315, elapsed=30.9min]

Entraînement:  97%|█████████▋| 9655/10000 [30:56<01:05,  5.29step/s, loss=0.020315, elapsed=30.9min]

Entraînement:  97%|█████████▋| 9655/10000 [30:56<01:05,  5.29step/s, loss=0.031293, elapsed=30.9min]

Entraînement:  97%|█████████▋| 9656/10000 [30:56<01:05,  5.29step/s, loss=0.031293, elapsed=30.9min]

Entraînement:  97%|█████████▋| 9656/10000 [30:56<01:05,  5.29step/s, loss=0.051136, elapsed=30.9min]

Entraînement:  97%|█████████▋| 9657/10000 [30:56<01:04,  5.28step/s, loss=0.051136, elapsed=30.9min]

Entraînement:  97%|█████████▋| 9657/10000 [30:56<01:04,  5.28step/s, loss=0.037909, elapsed=30.9min]

Entraînement:  97%|█████████▋| 9658/10000 [30:56<01:04,  5.31step/s, loss=0.037909, elapsed=30.9min]

Entraînement:  97%|█████████▋| 9658/10000 [30:56<01:04,  5.31step/s, loss=0.014557, elapsed=30.9min]

Entraînement:  97%|█████████▋| 9659/10000 [30:56<01:04,  5.31step/s, loss=0.014557, elapsed=30.9min]

Entraînement:  97%|█████████▋| 9659/10000 [30:56<01:04,  5.31step/s, loss=0.020457, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9660/10000 [30:57<01:04,  5.30step/s, loss=0.020457, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9660/10000 [30:57<01:04,  5.30step/s, loss=0.023559, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9661/10000 [30:57<01:03,  5.30step/s, loss=0.023559, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9661/10000 [30:57<01:03,  5.30step/s, loss=0.061617, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9662/10000 [30:57<01:03,  5.30step/s, loss=0.061617, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9662/10000 [30:57<01:03,  5.30step/s, loss=0.020621, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9663/10000 [30:57<01:03,  5.30step/s, loss=0.020621, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9663/10000 [30:57<01:03,  5.30step/s, loss=0.043270, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9664/10000 [30:57<01:03,  5.30step/s, loss=0.043270, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9664/10000 [30:57<01:03,  5.30step/s, loss=0.037300, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9665/10000 [30:58<01:03,  5.29step/s, loss=0.037300, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9665/10000 [30:58<01:03,  5.29step/s, loss=0.028460, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9666/10000 [30:58<01:03,  5.28step/s, loss=0.028460, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9666/10000 [30:58<01:03,  5.28step/s, loss=0.034464, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9667/10000 [30:58<01:03,  5.28step/s, loss=0.034464, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9667/10000 [30:58<01:03,  5.28step/s, loss=0.076397, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9668/10000 [30:58<01:02,  5.28step/s, loss=0.076397, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9668/10000 [30:58<01:02,  5.28step/s, loss=0.103444, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9669/10000 [30:58<01:02,  5.29step/s, loss=0.103444, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9669/10000 [30:58<01:02,  5.29step/s, loss=0.061495, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9670/10000 [30:59<01:02,  5.28step/s, loss=0.061495, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9670/10000 [30:59<01:02,  5.28step/s, loss=0.042804, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9671/10000 [30:59<01:02,  5.28step/s, loss=0.042804, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9671/10000 [30:59<01:02,  5.28step/s, loss=0.041107, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9672/10000 [30:59<01:01,  5.30step/s, loss=0.041107, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9672/10000 [30:59<01:01,  5.30step/s, loss=0.031917, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9673/10000 [30:59<01:01,  5.28step/s, loss=0.031917, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9673/10000 [30:59<01:01,  5.28step/s, loss=0.019769, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9674/10000 [30:59<01:01,  5.28step/s, loss=0.019769, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9674/10000 [30:59<01:01,  5.28step/s, loss=0.045618, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9675/10000 [31:00<01:01,  5.28step/s, loss=0.045618, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9675/10000 [31:00<01:01,  5.28step/s, loss=0.145652, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9676/10000 [31:00<01:01,  5.28step/s, loss=0.145652, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9676/10000 [31:00<01:01,  5.28step/s, loss=0.018076, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9677/10000 [31:00<01:01,  5.27step/s, loss=0.018076, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9677/10000 [31:00<01:01,  5.27step/s, loss=0.015336, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9678/10000 [31:00<01:01,  5.28step/s, loss=0.015336, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9678/10000 [31:00<01:01,  5.28step/s, loss=0.017510, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9679/10000 [31:00<01:00,  5.29step/s, loss=0.017510, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9679/10000 [31:00<01:00,  5.29step/s, loss=0.043235, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9680/10000 [31:00<01:00,  5.28step/s, loss=0.043235, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9680/10000 [31:00<01:00,  5.28step/s, loss=0.037758, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9681/10000 [31:01<01:00,  5.28step/s, loss=0.037758, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9681/10000 [31:01<01:00,  5.28step/s, loss=0.067671, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9682/10000 [31:01<01:00,  5.28step/s, loss=0.067671, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9682/10000 [31:01<01:00,  5.28step/s, loss=0.053448, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9683/10000 [31:01<00:59,  5.28step/s, loss=0.053448, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9683/10000 [31:01<00:59,  5.28step/s, loss=0.035623, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9684/10000 [31:01<00:59,  5.29step/s, loss=0.035623, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9684/10000 [31:01<00:59,  5.29step/s, loss=0.044303, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9685/10000 [31:01<00:59,  5.29step/s, loss=0.044303, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9685/10000 [31:01<00:59,  5.29step/s, loss=0.026967, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9686/10000 [31:02<00:59,  5.30step/s, loss=0.026967, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9686/10000 [31:02<00:59,  5.30step/s, loss=0.051012, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9687/10000 [31:02<00:59,  5.30step/s, loss=0.051012, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9687/10000 [31:02<00:59,  5.30step/s, loss=0.111972, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9688/10000 [31:02<00:58,  5.30step/s, loss=0.111972, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9688/10000 [31:02<00:58,  5.30step/s, loss=0.033889, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9689/10000 [31:02<00:58,  5.28step/s, loss=0.033889, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9689/10000 [31:02<00:58,  5.28step/s, loss=0.023643, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9690/10000 [31:02<00:58,  5.28step/s, loss=0.023643, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9690/10000 [31:02<00:58,  5.28step/s, loss=0.121460, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9691/10000 [31:03<00:58,  5.29step/s, loss=0.121460, elapsed=31.0min]

Entraînement:  97%|█████████▋| 9691/10000 [31:03<00:58,  5.29step/s, loss=0.043876, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9692/10000 [31:03<00:58,  5.28step/s, loss=0.043876, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9692/10000 [31:03<00:58,  5.28step/s, loss=0.030360, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9693/10000 [31:03<00:58,  5.29step/s, loss=0.030360, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9693/10000 [31:03<00:58,  5.29step/s, loss=0.052504, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9694/10000 [31:03<00:57,  5.30step/s, loss=0.052504, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9694/10000 [31:03<00:57,  5.30step/s, loss=0.031039, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9695/10000 [31:03<00:57,  5.30step/s, loss=0.031039, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9695/10000 [31:03<00:57,  5.30step/s, loss=0.037705, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9696/10000 [31:03<00:57,  5.29step/s, loss=0.037705, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9696/10000 [31:03<00:57,  5.29step/s, loss=0.029783, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9697/10000 [31:04<00:57,  5.30step/s, loss=0.029783, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9697/10000 [31:04<00:57,  5.30step/s, loss=0.037763, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9698/10000 [31:04<00:57,  5.29step/s, loss=0.037763, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9698/10000 [31:04<00:57,  5.29step/s, loss=0.110041, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9699/10000 [31:04<00:56,  5.29step/s, loss=0.110041, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9699/10000 [31:04<00:56,  5.29step/s, loss=0.088406, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9700/10000 [31:04<00:56,  5.30step/s, loss=0.088406, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9700/10000 [31:04<00:56,  5.30step/s, loss=0.044265, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9700/10000 [31:04<00:56,  5.30step/s, loss=0.044265, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9701/10000 [31:04<00:56,  5.25step/s, loss=0.044265, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9701/10000 [31:04<00:56,  5.25step/s, loss=0.064405, elapsed=31.1min]

Step 9700/10000 | Train loss: 0.044265 | Elapsed: 31.1min | ETA: 1.0min

Entraînement:  97%|█████████▋| 9702/10000 [31:05<00:56,  5.27step/s, loss=0.064405, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9702/10000 [31:05<00:56,  5.27step/s, loss=0.024152, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9703/10000 [31:05<00:56,  5.28step/s, loss=0.024152, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9703/10000 [31:05<00:56,  5.28step/s, loss=0.031567, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9704/10000 [31:05<00:55,  5.29step/s, loss=0.031567, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9704/10000 [31:05<00:55,  5.29step/s, loss=0.037273, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9705/10000 [31:05<00:55,  5.28step/s, loss=0.037273, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9705/10000 [31:05<00:55,  5.28step/s, loss=0.037615, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9706/10000 [31:05<00:55,  5.29step/s, loss=0.037615, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9706/10000 [31:05<00:55,  5.29step/s, loss=0.034122, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9707/10000 [31:06<00:55,  5.29step/s, loss=0.034122, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9707/10000 [31:06<00:55,  5.29step/s, loss=0.064248, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9708/10000 [31:06<00:55,  5.29step/s, loss=0.064248, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9708/10000 [31:06<00:55,  5.29step/s, loss=0.027191, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9709/10000 [31:06<00:54,  5.29step/s, loss=0.027191, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9709/10000 [31:06<00:54,  5.29step/s, loss=0.030787, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9710/10000 [31:06<00:54,  5.29step/s, loss=0.030787, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9710/10000 [31:06<00:54,  5.29step/s, loss=0.123203, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9711/10000 [31:06<00:54,  5.30step/s, loss=0.123203, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9711/10000 [31:06<00:54,  5.30step/s, loss=0.092867, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9712/10000 [31:07<00:54,  5.29step/s, loss=0.092867, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9712/10000 [31:07<00:54,  5.29step/s, loss=0.017379, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9713/10000 [31:07<00:54,  5.28step/s, loss=0.017379, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9713/10000 [31:07<00:54,  5.28step/s, loss=0.055909, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9714/10000 [31:07<00:54,  5.28step/s, loss=0.055909, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9714/10000 [31:07<00:54,  5.28step/s, loss=0.027768, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9715/10000 [31:07<00:53,  5.28step/s, loss=0.027768, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9715/10000 [31:07<00:53,  5.28step/s, loss=0.028863, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9716/10000 [31:07<00:53,  5.28step/s, loss=0.028863, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9716/10000 [31:07<00:53,  5.28step/s, loss=0.056650, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9717/10000 [31:07<00:53,  5.29step/s, loss=0.056650, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9717/10000 [31:07<00:53,  5.29step/s, loss=0.044284, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9718/10000 [31:08<00:53,  5.29step/s, loss=0.044284, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9718/10000 [31:08<00:53,  5.29step/s, loss=0.056498, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9719/10000 [31:08<00:53,  5.30step/s, loss=0.056498, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9719/10000 [31:08<00:53,  5.30step/s, loss=0.034717, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9720/10000 [31:08<00:52,  5.30step/s, loss=0.034717, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9720/10000 [31:08<00:52,  5.30step/s, loss=0.042985, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9721/10000 [31:08<00:52,  5.29step/s, loss=0.042985, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9721/10000 [31:08<00:52,  5.29step/s, loss=0.016738, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9722/10000 [31:08<00:52,  5.27step/s, loss=0.016738, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9722/10000 [31:08<00:52,  5.27step/s, loss=0.033439, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9723/10000 [31:09<00:52,  5.27step/s, loss=0.033439, elapsed=31.1min]

Entraînement:  97%|█████████▋| 9723/10000 [31:09<00:52,  5.27step/s, loss=0.031177, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9724/10000 [31:09<00:52,  5.27step/s, loss=0.031177, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9724/10000 [31:09<00:52,  5.27step/s, loss=0.063993, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9725/10000 [31:09<00:52,  5.27step/s, loss=0.063993, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9725/10000 [31:09<00:52,  5.27step/s, loss=0.025352, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9726/10000 [31:09<00:51,  5.28step/s, loss=0.025352, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9726/10000 [31:09<00:51,  5.28step/s, loss=0.038045, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9727/10000 [31:09<00:51,  5.29step/s, loss=0.038045, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9727/10000 [31:09<00:51,  5.29step/s, loss=0.053381, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9728/10000 [31:10<00:51,  5.30step/s, loss=0.053381, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9728/10000 [31:10<00:51,  5.30step/s, loss=0.031776, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9729/10000 [31:10<00:51,  5.29step/s, loss=0.031776, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9729/10000 [31:10<00:51,  5.29step/s, loss=0.034298, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9730/10000 [31:10<00:51,  5.28step/s, loss=0.034298, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9730/10000 [31:10<00:51,  5.28step/s, loss=0.047503, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9731/10000 [31:10<00:50,  5.28step/s, loss=0.047503, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9731/10000 [31:10<00:50,  5.28step/s, loss=0.034382, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9732/10000 [31:10<00:50,  5.30step/s, loss=0.034382, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9732/10000 [31:10<00:50,  5.30step/s, loss=0.043165, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9733/10000 [31:11<01:13,  3.62step/s, loss=0.043165, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9733/10000 [31:11<01:13,  3.62step/s, loss=0.032690, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9734/10000 [31:11<01:06,  3.98step/s, loss=0.032690, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9734/10000 [31:11<01:06,  3.98step/s, loss=0.038470, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9735/10000 [31:11<01:01,  4.30step/s, loss=0.038470, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9735/10000 [31:11<01:01,  4.30step/s, loss=0.056011, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9736/10000 [31:11<00:58,  4.55step/s, loss=0.056011, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9736/10000 [31:11<00:58,  4.55step/s, loss=0.066082, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9737/10000 [31:12<00:55,  4.75step/s, loss=0.066082, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9737/10000 [31:12<00:55,  4.75step/s, loss=0.041106, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9738/10000 [31:12<00:53,  4.89step/s, loss=0.041106, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9738/10000 [31:12<00:53,  4.89step/s, loss=0.051013, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9739/10000 [31:12<00:52,  4.99step/s, loss=0.051013, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9739/10000 [31:12<00:52,  4.99step/s, loss=0.051973, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9740/10000 [31:12<00:51,  5.06step/s, loss=0.051973, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9740/10000 [31:12<00:51,  5.06step/s, loss=0.069114, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9741/10000 [31:12<00:50,  5.12step/s, loss=0.069114, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9741/10000 [31:12<00:50,  5.12step/s, loss=0.014679, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9742/10000 [31:12<00:49,  5.18step/s, loss=0.014679, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9742/10000 [31:12<00:49,  5.18step/s, loss=0.021050, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9743/10000 [31:13<00:49,  5.21step/s, loss=0.021050, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9743/10000 [31:13<00:49,  5.21step/s, loss=0.046715, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9744/10000 [31:13<00:48,  5.23step/s, loss=0.046715, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9744/10000 [31:13<00:48,  5.23step/s, loss=0.047453, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9745/10000 [31:13<00:48,  5.25step/s, loss=0.047453, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9745/10000 [31:13<00:48,  5.25step/s, loss=0.038436, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9746/10000 [31:13<00:48,  5.25step/s, loss=0.038436, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9746/10000 [31:13<00:48,  5.25step/s, loss=0.037540, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9747/10000 [31:13<00:48,  5.21step/s, loss=0.037540, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9747/10000 [31:13<00:48,  5.21step/s, loss=0.050853, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9748/10000 [31:14<00:48,  5.24step/s, loss=0.050853, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9748/10000 [31:14<00:48,  5.24step/s, loss=0.097129, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9749/10000 [31:14<00:47,  5.25step/s, loss=0.097129, elapsed=31.2min]

Entraînement:  97%|█████████▋| 9749/10000 [31:14<00:47,  5.25step/s, loss=0.024816, elapsed=31.2min]

Entraînement:  98%|█████████▊| 9750/10000 [31:14<00:47,  5.26step/s, loss=0.024816, elapsed=31.2min]

Entraînement:  98%|█████████▊| 9750/10000 [31:14<00:47,  5.26step/s, loss=0.047067, elapsed=31.2min]

Entraînement:  98%|█████████▊| 9751/10000 [31:14<00:47,  5.28step/s, loss=0.047067, elapsed=31.2min]

Entraînement:  98%|█████████▊| 9751/10000 [31:14<00:47,  5.28step/s, loss=0.074371, elapsed=31.2min]

Entraînement:  98%|█████████▊| 9752/10000 [31:14<00:46,  5.28step/s, loss=0.074371, elapsed=31.2min]

Entraînement:  98%|█████████▊| 9752/10000 [31:14<00:46,  5.28step/s, loss=0.040880, elapsed=31.2min]

Entraînement:  98%|█████████▊| 9753/10000 [31:15<00:46,  5.28step/s, loss=0.040880, elapsed=31.2min]

Entraînement:  98%|█████████▊| 9753/10000 [31:15<00:46,  5.28step/s, loss=0.030115, elapsed=31.3min]

In [ ]:
final_checkpoint_path = EXPERIMENT_DIR / "final_checkpoint.pt"

torch.save({
    "step": global_step,
    "model_state_dict": model.state_dict(),
    "optimizer_state_dict": optimizer.state_dict(),
    "train_losses": train_losses,
    "val_losses": val_losses,
    "params": params.__dict__ if hasattr(params, "__dict__") else None,
    "summary": summary
}, final_checkpoint_path)

print("Checkpoint final sauvegardé ici :")
print(final_checkpoint_path)

In [ ]:
loss_df = pd.DataFrame({
    "step": list(range(1, len(train_losses) + 1)),
    "train_loss": train_losses
})

loss_csv_path = RESULTS_DIR / "diffwave_training_losses.csv"
loss_df.to_csv(loss_csv_path, index=False)

plt.figure(figsize=(10, 5))
plt.plot(loss_df["step"], loss_df["train_loss"])
plt.xlabel("Step")
plt.ylabel("MSE Loss")
plt.title("Évolution de la loss d'entraînement")
plt.grid(True)
plt.show()

loss_fig_path = FIGURES_DIR / "diffwave_training_loss.png"

plt.figure(figsize=(10, 5))
plt.plot(loss_df["step"], loss_df["train_loss"])
plt.xlabel("Step")
plt.ylabel("MSE Loss")
plt.title("Évolution de la loss d'entraînement")
plt.grid(True)
plt.savefig(loss_fig_path, dpi=300, bbox_inches="tight")
plt.close()

print("Loss CSV sauvegardé :", loss_csv_path)
print("Figure sauvegardée :", loss_fig_path)

In [ ]:
if len(val_losses) > 0:
    val_loss_df = pd.DataFrame(val_losses)

    val_loss_csv_path = RESULTS_DIR / "diffwave_validation_losses.csv"
    val_loss_df.to_csv(val_loss_csv_path, index=False)

    plt.figure(figsize=(10, 5))
    plt.plot(val_loss_df["step"], val_loss_df["val_loss"], marker="o")
    plt.xlabel("Step")
    plt.ylabel("Validation MSE Loss")
    plt.title("Évolution de la loss de validation")
    plt.grid(True)
    plt.show()

    val_loss_fig_path = FIGURES_DIR / "diffwave_validation_loss.png"

    plt.figure(figsize=(10, 5))
    plt.plot(val_loss_df["step"], val_loss_df["val_loss"], marker="o")
    plt.xlabel("Step")
    plt.ylabel("Validation MSE Loss")
    plt.title("Évolution de la loss de validation")
    plt.grid(True)
    plt.savefig(val_loss_fig_path, dpi=300, bbox_inches="tight")
    plt.close()

    print("Validation CSV sauvegardé :", val_loss_csv_path)
    print("Figure sauvegardée :", val_loss_fig_path)
else:
    print("Aucune validation enregistrée.")

# Fin de l'entraînement

À ce stade, le modèle a été entraîné sur le dataset DODa prétraité.

Les fichiers importants sauvegardés sont :

- `best_checkpoint.pt` : meilleur modèle selon la validation ;
- `last_checkpoint.pt` : dernier modèle sauvegardé pendant l’entraînement ;
- `final_checkpoint.pt` : modèle final ;
- courbes de loss pour le rapport.

La prochaine étape sera la génération audio à partir d’un spectrogramme Mel du jeu de test.

# Génération audio avec le modèle DiffWave entraîné

Dans cette partie, on utilise le modèle entraîné pour générer de l'audio à partir d'un spectrogramme Mel.

Le principe est le suivant :

1. On charge le meilleur checkpoint sauvegardé pendant l'entraînement.
2. On prend un exemple du jeu de test.
3. On utilise son Mel spectrogram comme condition.
4. On part d'un bruit blanc aléatoire.
5. On applique progressivement le processus inverse de diffusion.
6. On obtient une waveform audio générée.
7. On compare l'audio généré avec l'audio original.

In [ ]:
# Chargement du meilleur checkpoint entraîné

best_checkpoint_path = EXPERIMENT_DIR / "best_checkpoint.pt"
last_checkpoint_path = EXPERIMENT_DIR / "last_checkpoint.pt"
final_checkpoint_path = EXPERIMENT_DIR / "final_checkpoint.pt"

# On choisit le meilleur checkpoint disponible
if best_checkpoint_path.exists():
    checkpoint_path = best_checkpoint_path
elif final_checkpoint_path.exists():
    checkpoint_path = final_checkpoint_path
elif last_checkpoint_path.exists():
    checkpoint_path = last_checkpoint_path
else:
    checkpoint_path = None

if checkpoint_path is not None:
    checkpoint = torch.load(
        checkpoint_path,
        map_location=device,
        weights_only=False
    )

    model.load_state_dict(checkpoint["model_state_dict"])
    model.to(device)
    model.eval()

    print("Checkpoint chargé :", checkpoint_path)
    print("Step du checkpoint :", checkpoint.get("step", "inconnu"))

else:
    print("Aucun checkpoint trouvé.")
    print("Le modèle actuellement en mémoire sera utilisé.")
    model.eval()

## Préparation du jeu de test

On utilise maintenant `test.csv`, qui contient les exemples réservés à l’évaluation.

Pour la génération, on a besoin :

- du Mel spectrogram comme entrée du modèle ;
- de l’audio original pour comparer avec l’audio généré.

In [ ]:
test_dataset = DiffWaveDODaDataset(
    dataframe=test_df,
    wav_dir=WAV_DIR,
    mel_dir=MEL_DIR,
    sample_rate=summary["sample_rate"],
    hop_length=summary["hop_length"],
    crop_mel_frames=params.crop_mel_frames
)

test_loader = DataLoader(
    test_dataset,
    batch_size=1,
    shuffle=False,
    num_workers=0
)

print("Nombre d'exemples test :", len(test_dataset))

## Fonction de génération

La fonction suivante applique le processus inverse de diffusion.

On part d’un bruit blanc aléatoire, puis le modèle prédit à chaque étape le bruit à retirer.  
À la fin du processus, on obtient un signal audio généré.

In [ ]:
@torch.no_grad()
def p_sample(model, x, diffusion_step, mel):
    """
    Une étape de diffusion inverse.

    x doit avoir la shape [B, T].
    mel doit avoir la shape [B, 80, F].
    """

    # Sécurité : si x est [B, 1, T], on enlève la dimension inutile
    if x.dim() == 3:
        x = x.squeeze(1)

    batch_size = x.shape[0]

    t = torch.full(
        (batch_size,),
        diffusion_step,
        device=device,
        dtype=torch.long
    )

    predicted_noise = model(x, t, mel)

    # Sécurité : predicted_noise doit aussi être [B, T]
    if predicted_noise.dim() == 3:
        predicted_noise = predicted_noise.squeeze(1)

    beta_t = noise_schedule[diffusion_step]
    alpha_t = alphas[diffusion_step]
    alpha_cumprod_t = alpha_cumprod[diffusion_step]

    coef = beta_t / torch.sqrt(1.0 - alpha_cumprod_t)

    mean = (1.0 / torch.sqrt(alpha_t)) * (x - coef * predicted_noise)

    if diffusion_step > 0:
        noise = torch.randn_like(x)
        sigma = torch.sqrt(beta_t)
        x_prev = mean + sigma * noise
    else:
        x_prev = mean

    return x_prev


@torch.no_grad()
def generate_audio_from_mel(model, mel, audio_length):
    """
    Génère un audio à partir d'un Mel spectrogram.

    Le modèle DiffWave attend :
    - audio : [B, T]
    - mel : [B, 80, F]
    """

    model.eval()

    if mel.dim() == 2:
        mel = mel.unsqueeze(0)

    mel = mel.to(device)

    # Important : x doit être [B, T], pas [B, 1, T]
    x = torch.randn(
        mel.shape[0],
        audio_length,
        device=device
    )

    for step in tqdm(
        reversed(range(NUM_DIFFUSION_STEPS)),
        total=NUM_DIFFUSION_STEPS,
        desc="Génération"
    ):
        x = p_sample(model, x, step, mel)

    # Normalisation finale
    x = x / (x.abs().max(dim=1, keepdim=True)[0] + 1e-8)

    return x

## Génération d’un premier exemple

On sélectionne un exemple du jeu de test, puis on génère l’audio correspondant à partir de son Mel spectrogram.

On pourra ensuite écouter :

- l’audio original ;
- l’audio généré.

In [ ]:
# Récupération d'un exemple du jeu de test

test_batch = next(iter(test_loader))

original_audio = test_batch["audio"].to(device)
mel = test_batch["mel"].to(device)

example_id = test_batch["id"][0]
example_speaker = test_batch["speaker"][0]
example_text = test_batch["text_latin"][0]

audio_length = original_audio.shape[1]

print("ID :", example_id)
print("Speaker :", example_speaker)
print("Texte :", example_text)
print("Audio original shape :", original_audio.shape)
print("Mel shape :", mel.shape)
print("Longueur audio à générer :", audio_length)

In [ ]:
generated_audio = generate_audio_from_mel(
    model=model,
    mel=mel,
    audio_length=audio_length
)

print("Audio généré shape :", generated_audio.shape)

## Sauvegarde et écoute

On sauvegarde l’audio généré au format `.wav`, puis on écoute l’original et le généré directement dans le notebook.

In [ ]:
from IPython.display import Audio, display

GENERATED_DIR = PROJECT_DIR / "generated_audios"
GENERATED_DIR.mkdir(parents=True, exist_ok=True)

generated_audio_np = generated_audio[0].detach().cpu().numpy()
original_audio_np = original_audio[0].detach().cpu().numpy()

generated_audio_path = GENERATED_DIR / f"generated_{str(example_id).zfill(5)}.wav"

sf.write(
    generated_audio_path,
    generated_audio_np,
    summary["sample_rate"]
)

print("Audio généré sauvegardé ici :")
print(generated_audio_path)

In [ ]:
print("Audio original :")
display(Audio(original_audio_np, rate=summary["sample_rate"]))

print("Audio généré :")
display(Audio(generated_audio_np, rate=summary["sample_rate"]))

## Comparaison visuelle

On compare maintenant l’audio original et l’audio généré sous forme de waveform.

Cette visualisation permet de vérifier rapidement si le signal généré présente une structure ou s’il ressemble seulement à du bruit.

In [ ]:
plt.figure(figsize=(12, 4))
plt.plot(original_audio_np, label="Original", alpha=0.8)
plt.plot(generated_audio_np, label="Généré", alpha=0.7)
plt.title(f"Waveform original vs généré — ID {example_id}")
plt.xlabel("Échantillons")
plt.ylabel("Amplitude")
plt.legend()
plt.grid(True)
plt.show()

waveform_comparison_path = FIGURES_DIR / f"waveform_original_vs_generated_{str(example_id).zfill(5)}.png"

plt.figure(figsize=(12, 4))
plt.plot(original_audio_np, label="Original", alpha=0.8)
plt.plot(generated_audio_np, label="Généré", alpha=0.7)
plt.title(f"Waveform original vs généré — ID {example_id}")
plt.xlabel("Échantillons")
plt.ylabel("Amplitude")
plt.legend()
plt.grid(True)
plt.savefig(waveform_comparison_path, dpi=300, bbox_inches="tight")
plt.close()

print("Figure sauvegardée ici :")
print(waveform_comparison_path)

## Spectrogramme Mel de l’audio généré

On calcule le Mel spectrogram de l’audio généré afin de le comparer visuellement avec le Mel utilisé comme condition.

In [ ]:
generated_mel = librosa.feature.melspectrogram(
    y=generated_audio_np,
    sr=summary["sample_rate"],
    n_fft=summary["n_fft"],
    hop_length=summary["hop_length"],
    win_length=summary["n_fft"],
    n_mels=summary["n_mels"],
    power=1.0
)

generated_mel_log = np.log(np.clip(generated_mel, 1e-5, None))
generated_mel_log = np.clip(generated_mel_log, -11.5, None)

condition_mel = mel[0].detach().cpu().numpy()

fig, axes = plt.subplots(1, 2, figsize=(14, 4))

librosa.display.specshow(
    condition_mel,
    sr=summary["sample_rate"],
    hop_length=summary["hop_length"],
    x_axis="time",
    y_axis="mel",
    ax=axes[0]
)
axes[0].set_title("Mel conditionnel")

librosa.display.specshow(
    generated_mel_log,
    sr=summary["sample_rate"],
    hop_length=summary["hop_length"],
    x_axis="time",
    y_axis="mel",
    ax=axes[1]
)
axes[1].set_title("Mel de l'audio généré")

plt.suptitle(f"Comparaison Mel — ID {example_id}")
plt.tight_layout()
plt.show()

mel_comparison_path = FIGURES_DIR / f"mel_condition_vs_generated_{str(example_id).zfill(5)}.png"

fig, axes = plt.subplots(1, 2, figsize=(14, 4))

librosa.display.specshow(
    condition_mel,
    sr=summary["sample_rate"],
    hop_length=summary["hop_length"],
    x_axis="time",
    y_axis="mel",
    ax=axes[0]
)
axes[0].set_title("Mel conditionnel")

librosa.display.specshow(
    generated_mel_log,
    sr=summary["sample_rate"],
    hop_length=summary["hop_length"],
    x_axis="time",
    y_axis="mel",
    ax=axes[1]
)
axes[1].set_title("Mel de l'audio généré")

plt.suptitle(f"Comparaison Mel — ID {example_id}")
plt.tight_layout()
plt.savefig(mel_comparison_path, dpi=300, bbox_inches="tight")
plt.close()

print("Figure sauvegardée ici :")
print(mel_comparison_path)

## Génération de plusieurs exemples

On génère maintenant plusieurs audios à partir du jeu de test.

Les résultats sont sauvegardés dans un dossier dédié et récapitulés dans un fichier CSV.

In [ ]:
NUM_EXAMPLES_TO_GENERATE = 5

generated_results = []

model.eval()

for i in range(NUM_EXAMPLES_TO_GENERATE):
    sample = test_dataset[i]

    mel_i = sample["mel"].unsqueeze(0).to(device)
    original_audio_i = sample["audio"].unsqueeze(0).to(device)

    sample_id = str(sample["id"]).zfill(5)
    speaker = sample["speaker"]
    text = sample["text_latin"]

    audio_length_i = original_audio_i.shape[1]

    gen_audio_i = generate_audio_from_mel(
        model=model,
        mel=mel_i,
        audio_length=audio_length_i
    )

    gen_audio_np_i = gen_audio_i[0].detach().cpu().numpy()

    output_path = GENERATED_DIR / f"generated_{sample_id}.wav"

    sf.write(
        output_path,
        gen_audio_np_i,
        summary["sample_rate"]
    )

    generated_results.append({
        "id": sample_id,
        "speaker": speaker,
        "text_latin": text,
        "generated_audio_path": str(output_path)
    })

    print(f"Exemple {i+1}/{NUM_EXAMPLES_TO_GENERATE} généré :", output_path)

In [ ]:
generated_results_df = pd.DataFrame(generated_results)

generated_results_path = RESULTS_DIR / "generated_audio_results.csv"
generated_results_df.to_csv(generated_results_path, index=False)

print("Résultats sauvegardés ici :")
print(generated_results_path)

display(generated_results_df)

In [ ]:
for _, row in generated_results_df.iterrows():
    print("ID :", row["id"])
    print("Speaker :", row["speaker"])
    print("Texte :", row["text_latin"])
    display(Audio(row["generated_audio_path"], rate=summary["sample_rate"]))

## Évaluation qualitative

Les audios générés peuvent être évalués manuellement selon plusieurs critères :

- qualité sonore générale ;
- niveau de bruit ;
- stabilité du signal ;
- ressemblance avec une voix humaine ;
- cohérence avec le Mel conditionnel.

Si l’entraînement est court, il est normal que les audios soient encore bruités.  
Dans ce cas, l’objectif principal est de montrer que le pipeline complet fonctionne.

In [ ]:
evaluation_df = pd.DataFrame({
    "id": generated_results_df["id"],
    "speaker": generated_results_df["speaker"],
    "quality_score_1_to_5": [None] * len(generated_results_df),
    "noise_level_1_to_5": [None] * len(generated_results_df),
    "voice_naturalness_1_to_5": [None] * len(generated_results_df),
    "comments": [None] * len(generated_results_df)
})

evaluation_path = RESULTS_DIR / "qualitative_evaluation_template.csv"
evaluation_df.to_csv(evaluation_path, index=False)

print("Template d'évaluation sauvegardé ici :")
print(evaluation_path)

display(evaluation_df)

# Fin de la génération audio

À ce stade, le pipeline complet est réalisé :

1. données prétraitées ;
2. Dataset PyTorch ;
3. modèle DiffWave ;
4. entraînement ;
5. sauvegarde du checkpoint ;
6. génération audio ;
7. comparaison original / généré ;
8. préparation de l’évaluation qualitative.

Les résultats générés peuvent maintenant être utilisés dans le rapport et la présentation.